### ISSUE TITLE
PaddleOCR训练报错 RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:111)

### ISSUE THREAD

**Issue by wangweiweinimeng** [PaddlePaddle/PaddleOCR#10009]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0523 10:15:23.436717  3299 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
- 版本号/Version：Paddle：paddlepaddle-gpu-2.4.2  PaddleOCR：2.4.2 问题相关组件/Related components：
- 运行指令/Command Code： python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 181, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/root/20230508目标检测文本识别/resources/PaddleOCR/tools/program.py", line 304, in train
    loss = loss_class(preds, batch)
  File "/root/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/20230508目标检测文本识别/resources/PaddleOCR/ppocr/losses/vqa_token_layoutlm_loss.py", line 41, in forward
    loss = self.loss_class(active_output, active_label)
  File "/root/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/layer/loss.py", line 377, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "/root/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 2532, in cross_entropy
    paddle.cast(label != ignore_index, dtype=label.dtype) * label
  File "/root/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 304, in __impl__
    return math_op(self, other_var, -1)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:111)

**Comment by andyjpaddle** [comment]
用的是最新的2.6分支的代码吗？跑的什么数据集？

**Comment by wangweiweinimeng** [comment]
问题已经解决了，是paddle版本和GPU不匹配，谢谢。

**Comment by ariefwijaya** [comment]
@wangweiweinimeng How did you solve the problem?

**Comment by Iteachyou233** [comment]
> 您是如何解决这个问题的？

You can upgrade Paddle according to the CUDA version.
For example
`pip install paddlepaddle_gpu==2.5.2.post117`
