### ISSUE TITLE
PPOCRLabel生成的标注文件格式不符合KIE识别需求

### ISSUE THREAD

**Issue by tanjh** [PaddlePaddle/PaddleOCR#10018]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
使用PPOCRLabel生成的标注文件，其保存格式如下：

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
[2023/05/24 02:37:05] ppocr ERROR: When parsing line /opt/ppocr/PaddleOCR/train_data/ser/train/4cfddbed-c35f-4e61-a20c-a99b0a267f82.jpg [{"transcription": "姓名", "points": [[52, 160], [97, 159], [94, 179], [52, 181]], "d              ifficult": true, "key_cls": "Key_Name"}, {"transcription": "1988年7月12日", "points": [[104, 230], [252, 230], [252, 247], [104, 247]], "difficult": false, "key_cls": "Value_BirthDay"}, {"transcription": "住址", "points":               [[52, 267], [92, 267], [92, 281], [52, 281]], "difficult": false, "key_cls": "Key_Address"}, {"transcription": "公民身份号码", "points": [[48, 358], [155, 358], [155, 375], [48, 375]], "difficult": false, "key_cls": "Key              _ICNO"}, {"transcription": "130682198807120058", "points": [[170, 358], [442, 358], [442, 375], [170, 375]], "difficult": false, "key_cls": "Value_ICNO"}, {"transcription": "冯涛", "points": [[104, 156], [168, 156], [168,               180], [104, 180]], "difficult": true, "key_cls": "Value_Name"}, {"transcription": "性别", "points": [[47, 196], [97, 196], [97, 213], [47, 213]], "difficult": true, "key_cls": "Key_Gender"}, {"transcription": "男", "poin              ts": [[105, 193], [127, 193], [127, 211], [105, 211]], "difficult": true, "key_cls": "Value_Gender"}, {"transcription": "民族", "points": [[150, 193], [192, 193], [192, 214], [150, 214]], "difficult": true, "key_cls": "Ke              y_Nation"}, {"transcription": "汉", "points": [[196, 193], [218, 193], [218, 215], [196, 215]], "difficult": true, "key_cls": "Value_Nation"}, {"transcription": "出生", "points": [[49, 228], [91, 228], [91, 246], [49, 246              ]], "difficult": true, "key_cls": "Key_BirthDay"}, {"transcription": "河北省定州市南城区庞家佐村3队32号", "points": [[101, 265], [294, 265], [294, 309], [101, 309]], "difficult": true, "key_cls": "Value_Address"}]
, error happened with msg: Traceback (most recent call last):
  File "/opt/ppocr/PaddleOCR/ppocr/data/simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/opt/ppocr/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/opt/ppocr/PaddleOCR/ppocr/data/imaug/label_ops.py", line 1092, in __call__
    label = info['label']
KeyError: 'label'

**Comment by tanjh** [comment]
使用PPOCRLabel生成的标注文件，其保存格式如下：
/opt/ppocr/PaddleOCR/train_data/ser/train/4cfddbed-c35f-4e61-a20c-a99b0a267f82.jpg [{"transcription": "姓名", "points": [[52, 160], [97, 159], [94, 179], [52, 181]], "d ifficult": true, "key_cls": "Key_Name"}, {"transcription": "1988年7月12日", "points": [[104, 230], [252, 230], [252, 247], [104, 247]], "difficult": false, "key_cls": "Value_BirthDay"}, {"transcription": "住址", "points": [[52, 267], [92, 267], [92, 281], [52, 281]], "difficult": false, "key_cls": "Key_Address"}, {"transcription": "公民身份号码", "points": [[48, 358], [155, 358], [155, 375], [48, 375]], "difficult": false, "key_cls": "Key _ICNO"}, {"transcription": "130682198807120058", "points": [[170, 358], [442, 358], [442, 375], [170, 375]], "difficult": false, "key_cls": "Value_ICNO"}, {"transcription": "冯涛", "points": [[104, 156], [168, 156], [168, 180], [104, 180]], "difficult": true, "key_cls": "Value_Name"}, {"transcription": "性别", "points": [[47, 196], [97, 196], [97, 213], [47, 213]], "difficult": true, "key_cls": "Key_Gender"}, {"transcription": "男", "poin ts": [[105, 193], [127, 193], [127, 211], [105, 211]], "difficult": true, "key_cls": "Value_Gender"}, {"transcription": "民族", "points": [[150, 193], [192, 193], [192, 214], [150, 214]], "difficult": true, "key_cls": "Ke y_Nation"}, {"transcription": "汉", "points": [[196, 193], [218, 193], [218, 215], [196, 215]], "difficult": true, "key_cls": "Value_Nation"}, {"transcription": "出生", "points": [[49, 228], [91, 228], [91, 246], [49, 246 ]], "difficult": true, "key_cls": "Key_BirthDay"}, {"transcription": "河北省定州市南城区庞家佐村3队32号", "points": [[101, 265], [294, 265], [294, 309], [101, 309]], "difficult": true, "key_cls": "Value_Address"}]
根据https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md进行训练时，提示KeyError：label。
在PaddleOCR中是key_cls，而KIE中是需要使用Label，是需要自行做转换吗？

**Comment by zhaoqf-cq** [comment]
反正我是自己增加了id, linking属性, cls_key 替换成label ,而且关联也是用脚本处理的... 现在训练完成了, 评估也不是很高...
```
[2023/05/24 22:26:39] ppocr INFO: metric eval ***************
[2023/05/24 22:26:39] ppocr INFO: precision:0.8220858895705522
[2023/05/24 22:26:39] ppocr INFO: recall:0.864516129032258
[2023/05/24 22:26:39] ppocr INFO: hmean:0.8427672955974844
```

**Comment by first236108** [comment]
> 反正我是自己增加了id, linking属性, cls_key 替换成label ,而且关联也是用脚本处理的... 现在训练完成了, 评估也不是很高...
> 
> ```
> [2023/05/24 22:26:39] ppocr INFO: metric eval ***************
> [2023/05/24 22:26:39] ppocr INFO: precision:0.8220858895705522
> [2023/05/24 22:26:39] ppocr INFO: recall:0.864516129032258
> [2023/05/24 22:26:39] ppocr INFO: hmean:0.8427672955974844
> ```

me too...
大佬们出来指导一下呗，照着readme训练发票kie效果不好，自己标注的格式又不对。。这第一步数据标注都不顺利，很受打击呀.

**Comment by first236108** [comment]
昨天编写脚本添加了id、linking并把把cls_key替换为label，已经可以进行 SER训练，但RE训练会报错
ppocr ERROR: When parsing line 0020.jpg   [{"transcription": "名称", "points": [[316, 833], [739, 833],
查了资料说是分隔符\t，在0020.jpg和[{ 之间就是用的\t做分隔的，关于这个数据格式报错，谁能给个解答？ 非常感谢

**Comment by zhaoqf-cq** [comment]
> > 反正我是自己增加了id, linking属性, cls_key 替换成label ,而且关联也是用脚本处理的... 现在训练完成了, 评估也不是很高...
> > ```
> > [2023/05/24 22:26:39] ppocr INFO: metric eval ***************
> > [2023/05/24 22:26:39] ppocr INFO: precision:0.8220858895705522
> > [2023/05/24 22:26:39] ppocr INFO: recall:0.864516129032258
> > [2023/05/24 22:26:39] ppocr INFO: hmean:0.8427672955974844
> > ```
> 
> me too... 大佬们出来指导一下呗，照着readme训练发票kie效果不好，自己标注的格式又不对。。这第一步数据标注都不顺利，很受打击呀.

我也是萌新啊... 发票我没有试，我直接抽的合同的甲方和乙方，迁移学习完了后，评估就是我发出来这个...但是我拿去识别效果一点都不好，我觉得可能是因为 非标吧，如果合同都长一个样，可能效果会好很多...我就学着玩儿，就没弄了

但是我觉得发票应该还好吧，发票版面都是标准的，自己标注的话 linking 的关系要处理好，看一下 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/how_to_do_kie.md ，自己找规律吧...

**Comment by zhaoqf-cq** [comment]
> 昨天编写脚本添加了id、linking并把把cls_key替换为label，已经可以进行 SER训练，但RE训练会报错 ppocr ERROR: When parsing line 0020.jpg [{"transcription": "名称", "points": [[316, 833], [739, 833], 查了资料说是分隔符\t，在0020.jpg和[{ 之间就是用的\t做分隔的，关于这个数据格式报错，谁能给个解答？ 非常感谢

有没有可能不是格式问题， 而是处理的代码bug了... 你把错误信息贴出来啊，我看看我遇到过没有

**Comment by tanjh** [comment]
> 昨天编写脚本添加了id、linking并把把cls_key替换为label，已经可以进行 SER训练，但RE训练会报错 ppocr ERROR: When parsing line 0020.jpg [{"transcription": "名称", "points": [[316, 833], [739, 833], 查了资料说是分隔符\t，在0020.jpg和[{ 之间就是用的\t做分隔的，关于这个数据格式报错，谁能给个解答？ 非常感谢

可以使用如下命令将PPOCRLabel标注文件修改成SER训练所需文件：
