### ISSUE TITLE
使用 RE+SER demo 错误

### ISSUE THREAD

**Issue by chopin1998** [PaddlePaddle/PaddleOCR#10035]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux/ ubuntu 22.04
- 版本号/Version：Paddle：  PaddleOCR：2.6.1.3 
- 运行指令/Command Code：python3 predict_system.py \                                                                                                                                                       ─╯
  --kie_algorithm=LayoutXLM \
  --re_model_dir=/home/marco/.paddleocr/whl/re_vi_layoutxlm_xfund_infer \
  --ser_model_dir=/home/marco/.paddleocr/whl/ser_vi_layoutxlm_xfund_infer \
  --image_dir=./docs/kie/input/zh_val_42.jpg \
  --ser_dict_path=../ppocr/utils/dict/kie_dict/xfund_class_list.txt \
  --vis_font_path=../doc/fonts/simfang.ttf \
  --ocr_order_method="tb-yx" \
  --mode=kie

- 完整报错/Complete Error Message：
❯ python3 predict_system.py \
  --kie_algorithm=LayoutXLM \
  --re_model_dir=/home/marco/.paddleocr/whl/re_vi_layoutxlm_xfund_infer \
  --ser_model_dir=/home/marco/.paddleocr/whl/ser_vi_layoutxlm_xfund_infer \
  --image_dir=./docs/kie/input/zh_val_42.jpg \
  --ser_dict_path=../ppocr/utils/dict/kie_dict/xfund_class_list.txt \
  --vis_font_path=../doc/fonts/simfang.ttf \
  --ocr_order_method="tb-yx" \
  --mode=kie
[2023-05-25 15:16:48,383] [    INFO] - Already cached /home/marco/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2023-05-25 15:16:48,576] [    INFO] - tokenizer config file saved in /home/marco/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2023-05-25 15:16:48,576] [    INFO] - Special tokens file saved in /home/marco/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2023/05/25 15:16:53] ppocr INFO: [0/1] ./docs/kie/input/zh_val_42.jpg
Corrupt JPEG data: premature end of data segment
Traceback (most recent call last):
  File "/home/marco/Build/PaddleOCR/ppstructure/predict_system.py", line 315, in <module>
    main(args)
  File "/home/marco/Build/PaddleOCR/ppstructure/predict_system.py", line 254, in main
    res, time_dict = structure_sys(img, img_idx=index)
  File "/home/marco/Build/PaddleOCR/ppstructure/predict_system.py", line 181, in __call__
    re_res, elapse = self.kie_predictor(img)
  File "/home/marco/Build/PaddleOCR/ppstructure/kie/predict_kie_token_ser_re.py", line 64, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 258, in <module>
      main()
    File "tools/export_model.py", line 254, in main
      model, arch_config, save_path, logger, input_shape=input_shape)
    File "tools/export_model.py", line 174, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "<decorator-gen-106>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 861, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-104>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmp1jzgs091.py", line 28, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 237, in forward
      relations=relations)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1542, in forward
      relations)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1408, in forward
      relations, entities = self.build_relation(relations, entities)
    File "/tmp/tmpt8u0m8_d.py", line 106, in build_relation
      for_loop_body_2, [entities, new_relations, relations, b, batch_size])
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
      output_vars = body(*loop_vars)
    File "/tmp/tmpt8u0m8_d.py", line 30, in for_loop_body_2
      paddle.jit.dy2static.convert_ifelse(entities[b, 0, 0] <= 2,
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve (int64) does not match the type of data (float32) currently contained in the container.
      [Hint: Expected dtype() == phi::CppTypeToDataType<T>::Type(), but received dtype():10 != phi::CppTypeToDataType<T>::Type():9.] (at ../paddle/phi/core/dense_tensor.cc:165)
      [operator < less_equal > error]

单独使用SER是可以的， 一加入RE就报错

**Comment by zcgg2zhmm** [comment]
--use_visual_backbone=false

**Comment by ColorfulDick** [comment]
> --use_visual_backbone=false

谢谢老哥，确实有用，不过这是什么原理？这个use_visual_backbone的实现有问题吗，感觉In user code那里调用了一大堆不存在的代码

**Comment by xlg-go** [comment]
> > --use_visual_backbone=false
> 
> 谢谢老哥，确实有用，不过这是什么原理？这个use_visual_backbone的实现有问题吗，感觉In user code那里调用了一大堆不存在的代码

具体没仔细看，因为是互监督蒸馏模型，推理貌似用不到backbone
