### ISSUE TITLE
Error in identifying PDF of Math of china heigh shcoool: IndexError: list index out of range

### ISSUE THREAD

**Issue by litongjava** [PaddlePaddle/PaddleOCR#10032]
- 系统环境/System Environment：
Ubuntu 20.04.6 LTS
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
PaddleOCR 2.6
- 运行指令/Command Code：
```
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt \
    --vis_font_path=../doc/fonts/simfang.ttf \
    --recovery=True \
    --output=../output/ \
    --image_dir=/data/code/math/人教A版教材/28.pdf
```
- 完整报错/Complete Error Message：
```
[2023/05/25 10:14:10] ppocr ERROR: error in layout recovery image:/data/code/math/人教A版教材/28.pdf, err msg: list index out of range
(paddle_env) root@ping-Inspiron-3458:/data/code/python/PaddleOCR/ppstructure# python3 predict_system.py     --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer     --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer     --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer     --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer     --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt     --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt     --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt     --vis_font_path=../doc/fonts/simfang.ttf     --recovery=True     --output=../output/     --image_dir=/data/code/math/人教A版教材/28.pdf
E0525 10:16:22.591948  2923 analysis_config.cc:110] Please use PaddlePaddle with GPU version.
E0525 10:16:23.275753  2923 analysis_config.cc:110] Please use PaddlePaddle with GPU version.
E0525 10:16:23.612995  2923 analysis_config.cc:110] Please use PaddlePaddle with GPU version.
E0525 10:16:23.858932  2923 analysis_config.cc:110] Please use PaddlePaddle with GPU version.
E0525 10:16:24.348661  2923 analysis_config.cc:110] Please use PaddlePaddle with GPU version.
[2023/05/25 10:16:24] ppocr INFO: [0/1] /data/code/math/人教A版教材/28.pdf
[2023/05/25 10:16:26] ppocr DEBUG: dt_boxes num : 5, elapse : 0.6336286067962646
[2023/05/25 10:16:27] ppocr DEBUG: rec_res num  : 5, elapse : 1.4776272773742676
[2023/05/25 10:16:28] ppocr DEBUG: dt_boxes num : 2, elapse : 0.5351152420043945
[2023/05/25 10:16:28] ppocr DEBUG: rec_res num  : 2, elapse : 0.5850696563720703
[2023/05/25 10:16:29] ppocr DEBUG: dt_boxes num : 1, elapse : 0.5289239883422852
[2023/05/25 10:16:29] ppocr DEBUG: rec_res num  : 1, elapse : 0.24619626998901367
[2023/05/25 10:16:30] ppocr DEBUG: dt_boxes num : 1, elapse : 0.5300474166870117
[2023/05/25 10:16:30] ppocr DEBUG: rec_res num  : 1, elapse : 0.13910746574401855
[2023/05/25 10:16:30] ppocr DEBUG: dt_boxes num : 2, elapse : 0.5298504829406738
[2023/05/25 10:16:31] ppocr DEBUG: rec_res num  : 2, elapse : 0.4956939220428467
[2023/05/25 10:16:31] ppocr DEBUG: dt_boxes num : 6, elapse : 0.5337200164794922
[2023/05/25 10:16:33] ppocr DEBUG: rec_res num  : 6, elapse : 1.2434008121490479
[2023/05/25 10:16:33] ppocr DEBUG: dt_boxes num : 5, elapse : 0.5326559543609619
[2023/05/25 10:16:35] ppocr DEBUG: rec_res num  : 5, elapse : 1.4729366302490234
[2023/05/25 10:16:35] ppocr DEBUG: dt_boxes num : 8, elapse : 0.5323255062103271
[2023/05/25 10:16:37] ppocr DEBUG: rec_res num  : 8, elapse : 1.4917480945587158
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 5
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 6
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 5
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 6
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 5
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 6
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 5
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 48
['sos', '<thead>', '</thead>', '<tbody>', '</tbody>', '<tr>', '</tr>', '<td', '>', '</td>', ' colspan="2"', ' colspan="3"', ' colspan="4"', ' colspan="5"', ' colspan="6"', ' colspan="7"', ' colspan="8"', ' colspan="9"', ' colspan="10"', ' colspan="11"', ' colspan="12"', ' colspan="13"', ' colspan="14"', ' colspan="15"', ' colspan="16"', ' colspan="17"', ' colspan="18"', ' colspan="19"', ' colspan="20"', ' rowspan="2"', ' rowspan="3"', ' rowspan="4"', ' rowspan="5"', ' rowspan="6"', ' rowspan="7"', ' rowspan="8"', ' rowspan="9"', ' rowspan="10"', ' rowspan="11"', ' rowspan="12"', ' rowspan="13"', ' rowspan="14"', ' rowspan="15"', ' rowspan="16"', ' rowspan="17"', ' rowspan="18"', ' rowspan="19"', ' rowspan="20"', '<td></td>', 'eos'] 6
[2023/05/25 10:16:38] ppocr DEBUG: dt_boxes num : 5, elapse : 0.06738853454589844
[2023/05/25 10:16:39] ppocr DEBUG: rec_res num  : 5, elapse : 1.0756454467773438
[2023/05/25 10:16:39] ppocr DEBUG: dt_boxes num : 0, elapse : 0.52899169921875
[2023/05/25 10:16:39] ppocr DEBUG: rec_res num  : 0, elapse : 3.0994415283203125e-06
[2023/05/25 10:16:40] ppocr DEBUG: dt_boxes num : 1, elapse : 0.5289013385772705
[2023/05/25 10:16:40] ppocr DEBUG: rec_res num  : 1, elapse : 0.14141845703125
[2023/05/25 10:16:41] ppocr DEBUG: dt_boxes num : 4, elapse : 0.5315251350402832
[2023/05/25 10:16:41] ppocr DEBUG: rec_res num  : 4, elapse : 0.4820683002471924
[2023/05/25 10:16:42] ppocr DEBUG: dt_boxes num : 1, elapse : 0.5292830467224121
[2023/05/25 10:16:42] ppocr DEBUG: rec_res num  : 1, elapse : 0.07964825630187988
[2023/05/25 10:16:42] ppocr INFO: result save to ../output/structure/28/show_0.jpg
{'type': 'table', 'bbox': [53, 65, 615, 198], 'img': array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8), 'res': {'cell_bbox': [[67.48173522949219, 1.7552905082702637, 277.7029724121094, 1.9860482215881348, 271.30377197265625, 31.782075881958008, 61.96620559692383, 30.505210876464844], [72.19209289550781, 19.09928321838379, 277.66796875, 18.936664581298828, 275.373291015625, 81.58122253417969, 69.52903747558594, 81.64505767822266], [260.7604675292969, 17.41342544555664, 364.8869323730469, 16.978675842285156, 360.866455078125, 61.51895523071289, 252.63662719726562, 62.239112854003906], [155.0291290283203, 41.46330261230469, 332.2381286621094, 41.49628448486328, 330.3970031738281, 78.244140625, 152.89418029785156, 78.5308609008789], [339.83721923828125, 44.1794319152832, 477.6401062011719, 44.46284484863281, 475.40594482421875, 79.1575927734375, 335.17315673828125, 78.89389038085938], [148.29124450683594, 71.98780059814453, 278.8443298339844, 71.74150085449219, 280.7147521972656, 106.94396209716797, 148.95669555664062, 107.12264251708984], [315.23065185546875, 71.02446746826172, 448.80303955078125, 71.02499389648438, 446.0591735839844, 102.68832397460938, 310.24444580078125, 102.59243774414062]], 'html': '<html><body><table><tr><td>因为①，②式都成立，所以θ角的终边只能位于第三象限</td></tr><tr><td></td><td>于是角0为第三象限角. 反过来请同学们自己证明.</td></tr><tr><td></td><td></td></tr><tr><td></td><td>由三角函数的定义，可以知道：终边相同的角的同一三 角函数的值相等。由此得到一组公式（公式一）：</td></tr></table></body></html>'}, 'img_idx': 0, 'layout': 'single'}
Traceback (most recent call last):
  File "predict_system.py", line 292, in main
    convert_info_docx(img, all_res, save_folder, img_name)
  File "/data/code/python/PaddleOCR/ppstructure/recovery/recovery_to_doc.py", line 66, in convert_info_docx
    parser.handle_table(region['res']['html'], doc)
  File "/data/code/python/PaddleOCR/ppstructure/recovery/table_process.py", line 263, in handle_table
    docx_cell = table.cell(cell_row, cell_col)
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/site-packages/docx/table.py", line 81, in cell
    return self._cells[cell_idx]
IndexError: list index out of range
```
pdf file
[28.pdf](https://github.com/PaddlePaddle/PaddleOCR/files/11560542/28.pdf)

**Comment by JuneYaooo** [comment]
I met the same problem

**Comment by archeradvanture** [comment]
@litongjava  请问一下 这个问题怎么解决的？
