### ISSUE TITLE
PaddleOCR 2.6识别pdf报错

### ISSUE THREAD

**Issue by ajie425** [PaddlePaddle/PaddleOCR#10047]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- win11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- PaddleOCR：2.6.0.1
- 运行指令/Command Code：
- paddleocr --image_dir ./output.pdf --use_angle_cls true --use_gpu true
- 完整报错/Complete Error Message：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40158391/07e2ad7d-41c4-4952-9099-d5583409cb43)

C:\Users\xxx\Desktop\itext-ocr\双层pdf>paddleocr --image_dir ./pdfOcr1.pdf --use_angle_cls true --use_gpu true
[2023/05/29 11:41:59] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, shape_info_filename=None, precision='fp32', gpu_mem=500, image_dir='./pdfOcr1.pdf', det_algorithm='DB', det_model_dir='C:\\Users\\xxx/.paddleocr/whl\\det\\ch\\ch_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_box_type='quad', det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, det_fce_box_type='poly', rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\xxx/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv3_rec_infer', rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='D:\\Program Files\\Python310\\Lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='C:\\Users\\xxx/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, save_pdf=False, lang='ch', det=True, rec=True, type='ocr', ocr_version='PP-OCRv3', structure_version='PP-Structurev2')
[2023/05/29 11:42:03] ppocr INFO: **********./pdfOcr1.pdf**********
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python310\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "D:\Program Files\Python310\Lib\site-packages\paddleocr\paddleocr.py", line 630, in main
    result = engine.ocr(img_path,
  File "D:\Program Files\Python310\Lib\site-packages\paddleocr\paddleocr.py", line 521, in ocr
    img = check_img(img)
  File "D:\Program Files\Python310\Lib\site-packages\paddleocr\paddleocr.py", line 431, in check_img
    img, flag, _ = check_and_read(image_file)
  File "D:\Program Files\Python310\Lib\site-packages\paddleocr\ppocr\utils\utility.py", line 89, in check_and_read
    import fitz
  File "D:\Program Files\Python310\Lib\site-packages\fitz\__init__.py", line 28, in <module>
    raise ValueError(
ValueError: MuPDF library mismatch 1.19.0 <> 1.21.1

使用的PyMuPdf版本为1.19.0，尝试使用1.20，1.21，1.22会出现一下同[https://github.com/PaddlePaddle/PaddleOCR/discussions/8972](url)的错误

**Comment by ajie425** [comment]
默认安装的PyMuPdf版本为1.20.2则会出现以下问题：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40158391/bee90e68-aa8b-4f82-90ac-345ca9e9774b)
修改了PyMuPdf版本则会出现上面的问题

**Comment by fantacymaker** [comment]
如何解决的呢？

**Comment by fantacymaker** [comment]
https://github.com/PaddlePaddle/PaddleOCR/discussions/8972 通过修改代码解决
