### ISSUE TITLE
AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict

### ISSUE THREAD

**Issue by inesriahi** [PaddlePaddle/PaddleOCR#10053]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04
- 版本号/Version：Paddle： 2.4.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
```
!python -m paddle.distributed.launch --gpus '0' tools/train.py -c configs/cls/cls_mv3.yml \
    -o  Global.checkpoints=/home/jovyan/work/models/base_models/ch_ppocr_mobile_v2.0_cls_train/best_accuracy \
    Train.dataset.data_dir="/home/jovyan/work/src/ocr_data/cls_dataset_2023-05-29" \
    Train.dataset.label_file_list="- /home/jovyan/work/src/ocr_data/cls_dataset_2023-05-29/train_gt.txt" \
    Eval.dataset.label_file_list="- /home/jovyan/work/src/ocr_data/cls_dataset_2023-05-29/val_gt.txt" \
    Eval.dataset.data_dir="/home/jovyan/work/src/ocr_data/cls_dataset_2023-05-29" \
    Global.save_model_dir="/home/jovyan/work/models/cls/{date.today()}" \
```
- 完整报错/Complete Error Message：
```
LAUNCH INFO 2023-05-29 08:58:03,129 ------------------------- ERROR LOG DETAIL -------------------------
[2023-05-29 08:58:03,129] [    INFO] controller.py:111 - ------------------------- ERROR LOG DETAIL -------------------------
 08:57:56.249325  9151 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.7
W0529 08:57:56.252480  9151 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[2023/05/29 08:57:57] ppocr INFO: train dataloader has 115 iters
[2023/05/29 08:57:57] ppocr INFO: valid dataloader has 22 iters
[2023/05/29 08:57:57] ppocr INFO: resume from /home/jovyan/work/models/base_models/ch_ppocr_mobile_v2.0_cls_train/best_accuracy
[2023/05/29 08:57:57] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 1000 iterations
Traceback (most recent call last):
  File "/home/jovyan/work/PaddleOCR/tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/jovyan/work/PaddleOCR/tools/train.py", line 181, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/jovyan/work/PaddleOCR/tools/program.py", line 298, in train
    optimizer.step()
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/optimizer/adam.py", line 546, in step
    optimize_ops = self._apply_optimize(
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/optimizer/optimizer.py", line 1166, in _apply_optimize
    optimize_ops = self._create_optimization_pass(
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/optimizer/optimizer.py", line 924, in _create_optimization_pass
    self._create_accumulators(
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/optimizer/adam.py", line 337, in _create_accumulators
    self._add_moments_pows(p)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/optimizer/adam.py", line 293, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/home/jovyan/work/paddle_env/lib/python3.10/site-packages/paddle/optimizer/optimizer.py", line 754, in _add_accumulator
    var_name in self._accumulators_holder
AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict
LAUNCH INFO 2023-05-29 08:58:03,129 Exit code 1
[2023-05-29 08:58:03,129] [    INFO] controller.py:141 - Exit code 1
```

I get this error when I try to finetune the angle classification model that I downloaded I get this error...
Any help please?

**Comment by inesriahi** [comment]
I figured out the solution.
Instead of setting the model's path to Global.checkpoints, set it to Global.pretrained_model

**Comment by asif-ca** [comment]
What if someone resumes the training, one must set the argument `Global.checkpoints` otherwise training will start from epoch 1 (meaning training will start from scratch? )
