### ISSUE TITLE
模型转换后结果不对

### ISSUE THREAD

**Issue by Acheerfulloser** [PaddlePaddle/PaddleOCR#10076]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：Paddle 2.3.2  PaddleOCR：v2.6   问题相关组件/Related components：paddle2onnx
- 运行指令/Command Code：paddle2onnx --model_dir=./inference/rec_tiny/ --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./models/rec_tiny/inference.onnx --opset_version=11 --enable_onnx_checker=True
- 完整报错/Complete Error Message：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: models/rec_tiny/inference.pdmodel
[Paddle2ONNX] Paramters file path: models/rec_tiny/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 12 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2023-06-01 19:48:50 [INFO]      ===============Make PaddlePaddle Better!================
2023-06-01 19:48:50 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s

转换成功了，但是推理时，结果错误

训练config是在 rec_svtrnet.yml基础上，删减了几个层

onnx模型输出结果和pdmodel的结果完全不同
输出后处理前的一段：
 if self.use_onnx:
                    input_dict = {}
                    input_dict[self.input_tensor.name] = norm_img_batch
                    outputs = self.predictor.run(self.output_tensors,
                                                 input_dict)
                    preds = outputs[0]
else:
     .......

onnx: 
        preds:  [[[9.99988794e-01 3.35570660e-09 1.41508130e-08 ... 6.24736884e-09
           1.34460210e-09 3.35605044e-10]
          [9.99997020e-01 2.42531062e-09 1.81766016e-08 ... 2.35306385e-10
           1.41753914e-10 3.33223345e-11]
          [9.99976516e-01 9.84722881e-09 7.59528689e-08 ... 2.92463526e-10
           1.62757183e-10 4.82482214e-11]
          ...
          [1.00000000e+00 9.74938446e-12 8.65813116e-11 ... 8.74888096e-12
           1.22539057e-09 2.20180536e-12]
          [1.00000000e+00 1.04049625e-11 3.51490156e-11 ... 3.60729654e-12
           1.97253702e-09 1.01442303e-12]
          [9.99992013e-01 1.60909522e-10 2.17858037e-10 ... 1.83610627e-10
           7.77434616e-06 3.03652485e-11]]]

pdmodel:
          preds:  [[[4.6769638e-10 1.8844891e-13 3.7232229e-13 ... 1.5882405e-07
             6.2306785e-11 9.7676823e-12]
            [9.9999988e-01 7.8201152e-12 2.4377909e-11 ... 1.2135571e-11
             2.7126040e-12 7.9253721e-13]
            [1.0000000e+00 4.0680410e-12 5.0043133e-11 ... 9.4905278e-14
             6.3180038e-14 2.1807304e-14]
            ...
            [9.9999988e-01 2.5763153e-10 7.7356821e-10 ... 2.0909291e-10
             5.3304966e-08 2.4174131e-11]
            [9.9988663e-01 1.3994308e-09 1.7279674e-09 ... 1.3682887e-09
             1.1256166e-04 2.0313215e-10]
            [2.0423245e-11 2.8795016e-15 3.2619429e-16 ... 7.1152116e-14
             1.0000000e+00 1.3177787e-15]]]

直接比较两个模型的计算结果，np.testing.assert_allclose，也完全不同：
  [[[1.8135782e-01 1.5200827e-02 4.7576926e-03 ... 4.5358655e-03
     9.2102890e-04 1.9215635e-03]
    [5.0488651e-01 9.2241410e-03 2.0844908e-03 ... 4.5321285e-04
     1.6669241e-04 4.2731935e-04]
    [7.3310447e-01 8.8874949e-03 1.5868813e-03 ... 2.1377967e-04
     5.9665737e-05 1.5556124e-04]
    ...
    [5.1070523e-01 1.1931979e-03 1.1640229e-03 ... 1.7816754e-04
     1.4474997e-04 1.3426512e-04]
    [6.2103230e-01 1.3569598e-03 1.5096597e-03 ... 2.3472562e-04
     2.8088345e-04 1.8662077e-04]
    [3.9202306e-01 2.6310622e-03 2.7609386e-03 ... 1.4866155e-03
     6.5830939e-02 1.0277504e-03]]]
  [[[5.2969546e-07 3.1621798e-06 3.4210218e-05 ... 2.6090713e-02
     2.7934657e-04 4.3804594e-05]
    [1.1609105e-02 1.2324314e-04 3.2272344e-04 ... 2.4418987e-05
     3.0634550e-05 6.3906366e-05]
    [6.1462116e-03 2.2648326e-04 6.9376258e-03 ... 8.0300204e-05
     1.7087330e-05 4.3060660e-05]
    ...
    [9.9067736e-01 6.6978006e-05 9.0876456e-05 ... 9.9728386e-06
     7.1107308e-05 8.2255719e-06]
    [9.7150898e-01 1.4582949e-04 2.3480748e-04 ... 4.6729230e-05
     9.0753083e-04 3.7116632e-05]
    [1.1433153e-11 1.7215195e-11 3.3881340e-12 ... 2.0088874e-10
     1.0000000e+00 7.6368070e-12]]]
  Traceback (most recent call last):
    File "tools/buggggg.py", line 45, in <module>
      np.testing.assert_allclose(paddle_outs.numpy(), ort_outs[0], rtol=1e-03, atol=1e-05)
    File "/root/anaconda3/envs/paddle_env/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
      verbose=verbose, header=header, equal_nan=equal_nan)
    File "/root/anaconda3/envs/paddle_env/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
      raise AssertionError(msg)
  AssertionError:
  Not equal to tolerance rtol=0.001, atol=1e-05
  
  Mismatched elements: 4286 / 4360 (98.3%)
  Max absolute difference: 0.93416905
  Max relative difference: 702.8186
   x: array([[[5.296955e-07, 3.162180e-06, 3.421022e-05, ..., 2.609071e-02,
           2.793466e-04, 4.380459e-05],
          [1.160911e-02, 1.232431e-04, 3.227234e-04, ..., 2.441899e-05,...
   y: array([[[1.813578e-01, 1.520083e-02, 4.757693e-03, ..., 4.535866e-03,
           9.210289e-04, 1.921564e-03],
          [5.048865e-01, 9.224141e-03, 2.084491e-03, ..., 4.532129e-04,...

用infer_rec.py和predict_rec.py跑结果是一样的，但是转成onnx就不同了。
希望能帮忙看一下问题出在了哪里？

**Comment by phamkhactu** [comment]
@Acheerfulloser 

Have you fixed it?
