### ISSUE TITLE
导出的center loss文件train_center.pkl怎么使用？好像加入yml文件报错了。

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#10131]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

导出的center loss文件train_center.pkl怎么使用？好像加入yml文件报错了。

**Comment by nissansz** [comment]
Traceback (most recent call last):
  File "./tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "./tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward
    loss = loss_func(input, batch, **kargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in __call__
    assert isinstance(predicts, (list, tuple))
AssertionError

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/adc46b37-964b-4513-9c3e-f59d909a4d3f)
