### ISSUE TITLE
使用自己训练的模型转换为inference模型之后re+ser预测报错，单独运行ser模型没报错

### ISSUE THREAD

**Issue by yjzb** [PaddlePaddle/PaddleOCR#10149]
系统环境/System Environment： 
Linux
版本号/Version：Paddle：2.4.2  PaddleOCR： 2.6
问题相关组件/Related components： 
运行指令/Command Code： 
python3 kie/predict_kie_token_ser_re.py  --kie_algorithm=LayoutXLM --re_model_dir=/home/PaddleOCR/output/re_vi_layoutxlm_xfund_zh/inference --ser_model_dir=/home/PaddleOCR/output/ser_vi_layoutxlm_xfund_zh/inference --use_visual_backbone=False --image_dir=./docs/kie/input/1.png --ser_dict_path=../train_data/XFUND/class_list_xfun.txt --vis_font_path=../doc/fonts/simfang.ttf --ocr_order_method="tb-yx"
完整报错/Complete Error Message：
Traceback (most recent call last):
  File "kie/predict_kie_token_ser_re.py", line 135, in <module>
    main(parse_args())
  File "kie/predict_kie_token_ser_re.py", line 101, in main
    re_res, elapse = ser_re_predictor(img)
  File "kie/predict_kie_token_ser_re.py", line 64, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 269, in <module>
      main()
    File "tools/export_model.py", line 265, in main
      model, arch_config, save_path, logger, input_shape=input_shape)
    File "tools/export_model.py", line 185, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 649, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 928, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in concrete_program_specify_input_spec
      is_train=self._is_train_mode())
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 485, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 955, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 944, in _build_once
      **cache_key.kwargs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 888, in from_func_spec
      outputs = static_func(*inputs)
    File "/home/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 85, in forward
      if self.use_backbone:
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 324, in convert_ifelse
      return_name_ids)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 380, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/home/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1014, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 993, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
      x = self.model(
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1014, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 993, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1412, in forward
      loss, pred_relations = self.extractor(sequence_output, entities, relations)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1014, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 993, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1309, in forward
      for b in range(batch_size):
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 104, in convert_while_loop
      push_pop_names)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 153, in _run_paddle_while
      loop_vars = control_flow.while_loop(new_cond_fn, new_body_fn, loop_vars)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 1460, in while_loop
      output_vars = body(*loop_vars)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 136, in new_body_fn
      body()
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1339, in forward
      if len(pred_relations) > 0:
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 321, in convert_ifelse
      return_name_ids, push_pop_names)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 358, in _run_paddle_cond
      return_name_ids)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 2934, in cond
      _to_sequence_except_dict(return_names),
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 2927, in merge_every_var_list
      return map_structure(partial(merge_func, name), false_vars, true_vars)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py", line 219, in map_structure
      return pack_sequence_as(structure[0], [func(*x) for x in entries])
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py", line 219, in <listcomp>
      return pack_sequence_as(structure[0], [func(*x) for x in entries])
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 2922, in <lambda>
      [false_var, true_var], mask, name
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 186, in select_input_with_buildin_type
      return select_input(inputs, mask)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 165, in select_input
      outputs={'Out': out},
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 4046, in append_op
      attrs=kwargs.get("attrs", None),
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Variable type must be N3phi11TensorArrayE, but the type it holds is N3phi11DenseTensorE.
      [Hint: Expected holder_->Type() == VarTypeTrait<T>::kId, but received holder_->Type():7 != VarTypeTrait<T>::kId:13.] (at /paddle/paddle/fluid/framework/variable.h:58)
      [operator < select_input > error]

使用自己训练的模型转换为inference模型之后进行预测，报错如上，单独运行ser模型没报错，re+ser报错，希望大家帮忙看看怎么解决

**Comment by yjzb** [comment]
问题解决了，通过查着资料，大家可以按照以下思路排查：
1、查看自己使用的文本检测，识别等模型是否一致
2、查看模型前后处理参数是否一致
3、重新下载最新版代码，重新搭建环境（我是通过这个解决的，不知道是官方代码问题还是自己有修改不记得了）
提醒：感觉官方的代码还是很完善的，如果有问题，可以采用重新搭建环境进行测试
希望对大家有所帮助，欢迎大家积极交流

**Comment by ColorfulDick** [comment]
看日志，paddle.jit.save 这个方法有问题，会调用一大堆不存在的代码(python3.7那些)
