### ISSUE TITLE
Error: Can not import avx core while this file exists: /usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core_avx.so

### ISSUE THREAD

**Issue by v587xpt** [PaddlePaddle/PaddleOCR#10162]
我的系统信息以及其他版本信息：
```
[root@ndb2 paddle_ocr_test]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@ndb2 paddle_ocr_test]# uname -a
Linux ndb2 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@ndb2 paddle_ocr_test]# python3 -V
Python 3.8.6
[root@ndb2 paddle_ocr_test]# pip3 -V
pip 23.1.2 from /usr/local/python3/lib/python3.8/site-packages/pip (python 3.8)
[root@ndb2 paddle_ocr_test]# pip3 list | grep paddle
paddle-bfloat         0.1.7
paddleocr             2.0.1
paddlepaddle          2.3.2
```
当我试着用paddleocr命令来识别一张图片时，出现了报错：
```
[root@ndb2 paddle_ocr_test]# paddleocr --image_dir ./1-2.jpg --det false
Error: Can not import avx core while this file exists: /usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/usr/local/python3/bin/paddleocr", line 5, in <module>
    from paddleocr.paddleocr import main
  File "/usr/local/python3/lib/python3.8/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/usr/local/python3/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "/usr/local/python3/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 26, in <module>
    import tools.infer.utility as utility
  File "/usr/local/python3/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 23, in <module>
    from paddle.fluid.core import AnalysisConfig
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core_avx.so)
```
我尝试过的方法：
1、降低了paddleocr和paddlepaddle的版本；
2、gcc安装为8.x版本，低于9.x版本；
3、使用docker识别。这个成功了，但是在容器中貌似没有paddleocr这个命令？（可能因为我是个linux运维，对开发不太熟悉。）
请求帮助，非常感谢；

**Comment by William9Baker** [comment]
同问
