### ISSUE TITLE
扫描版的PDF文件进行版面恢复报错

### ISSUE THREAD

**Issue by zhupeifox** [PaddlePaddle/PaddleOCR#10169]
``请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：paddleocr --image_dir=”resource\***.pdf“ --type=structure 
- 完整报错/Complete Error Message：
```
[2023/06/15 10:27:02] ppocr INFO: **********resource\***.pdf**********
Deprecation: 'getPixmap' removed from class 'Page' after v1.19.0 - use 'get_pixmap'.
[2023/06/15 10:27:44] ppocr INFO: processing 1/654 page:
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Project\electronicrecordslibrary\TextTranslator\venv\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "D:\Project\electronicrecordslibrary\TextTranslator\venv\lib\site-packages\paddleocr\paddleocr.py", line 718, in main
    result = engine(new_img_path, img_idx=index)
  File "D:\Project\electronicrecordslibrary\TextTranslator\venv\lib\site-packages\paddleocr\paddleocr.py", line 644, in __call__
    img = check_img(img)
  File "D:\Project\electronicrecordslibrary\TextTranslator\venv\lib\site-packages\paddleocr\paddleocr.py", line 436, in check_img
    with open(image_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './output\\***\\***_0.jpg'
```

**Comment by ATP-BME** [comment]
请问解决了吗？我也遇到了这个问题
