### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by wzh159** [PaddlePaddle/PaddleOCR#10200]
在官网训练模型报错
/home/aistudio/PaddleOCR
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 657, in preprocess
    .dev_id) if use_gpu else 'cpu'
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 208, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

**Comment by livingbody** [comment]
建议贴出训练命令，看样子是多卡训练没找到卡的设备id

**Comment by shiyutang** [comment]
建议根据下面的issue继续排查：https://github.com/PaddlePaddle/Paddle/issues/46377

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by 350050183** [comment]
python3 tools/train.py -c configs/rec/PP-OCRv4/en_PP-OCRv4_rec.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv4_rec_server_train/

CPU单卡，macos m2上训练也报错
