### ISSUE TITLE
跟着官方QUICK START，报错list index out of range？

### ISSUE THREAD

**Issue by alexHxun** [PaddlePaddle/PaddleOCR#10214]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle==2.4.2;paddleocr==2.0.1
- 运行指令/Command Code：paddleocr --image_dir D:\dev\nuc_codes\test_img\1.png --use_angle_cls true --lang en --use_gpu false
- 完整报错/Complete Error Message：
- 
Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\Alex/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\Alex/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='D:\\dev\\nuc_codes\\test_img\\1.png', ir_optim=True, label_list=['0', '180'], lang='en', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/dict/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\Alex/.paddleocr/2.0/rec/en', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
W0620 11:46:06.881074  2844 analysis_predictor.cc:2166] Deprecated. Please use CreatePredictor instead.
[2023-06-20 11:46:07,411] [    INFO] paddleocr.py:333 - **********D:\dev\nuc_codes\test_img\1.png**********
[2023/06/20 11:46:07] root INFO: **********D:\dev\nuc_codes\test_img\1.png**********
[2023-06-20 11:46:08,352] [    INFO] predict_system.py:89 - dt_boxes num : 4, elapse : 0.9091010093688965
[2023/06/20 11:46:08] root INFO: dt_boxes num : 4, elapse : 0.9091010093688965
[2023-06-20 11:46:08,385] [    INFO] predict_system.py:104 - cls num  : 4, elapse : 0.029901742935180664
[2023/06/20 11:46:08] root INFO: cls num  : 4, elapse : 0.029901742935180664
Traceback (most recent call last):
  File "E:\miniconda3\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\miniconda3\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\miniconda3\envs\paddle\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\paddleocr.py", line 337, in main
    cls=args.use_angle_cls)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 106, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 115, in __call__
    rec_result = self.postprocess_op(preds)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\ppocr\postprocess\rec_postprocess.py", line 110, in __call__
    text = self.decode(preds_idx, preds_prob)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\ppocr\postprocess\rec_postprocess.py", line 80, in decode
    idx])])
IndexError: list index out of range

**Comment by alexHxun** [comment]
用官方给的python脚本跑也报错：
`from paddleocr import PaddleOCR,draw_ocr
# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `fr`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=True, lang='en',use_gpu=False) # need to run only once to download and load model into memory
img_path = r'D:\dev\nuc_codes\test_img\1.png'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)


# draw result
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='./fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')`


报错信息：
`Namespace(cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\Alex/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=2.0, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\Alex/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='en', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/dict/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\Alex/.paddleocr/2.0/rec/en', use_angle_cls=True, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
W0620 11:46:43.483044  7528 analysis_predictor.cc:2166] Deprecated. Please use CreatePredictor instead.
[2023-06-20 11:46:44,939] [    INFO] predict_system.py:89 - dt_boxes num : 4, elapse : 0.9015927314758301
[2023/06/20 11:46:44] root INFO: dt_boxes num : 4, elapse : 0.9015927314758301     
[2023-06-20 11:46:44,976] [    INFO] predict_system.py:104 - cls num  : 4, elapse : 0.0343930721282959
[2023/06/20 11:46:44] root INFO: cls num  : 4, elapse : 0.0343930721282959
Traceback (most recent call last):
  File "d:/dev/paddleocr/test.py", line 7, in <module>
    result = ocr.ocr(img_path, cls=True)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 106, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 115, in __call__
    rec_result = self.postprocess_op(preds)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\ppocr\postprocess\rec_postprocess.py", line 110, in __call__
    text = self.decode(preds_idx, preds_prob)
  File "E:\miniconda3\envs\paddle\lib\site-packages\paddleocr\ppocr\postprocess\rec_postprocess.py", line 80, in decode
    idx])])
IndexError: list index out of range`

**Comment by XiangPiIi** [comment]
6
