### ISSUE TITLE
error training any rec model with dygraph branch (win 10 cpu/gpu , python 3.10.11,paddle 2.4.2 or 2.5)

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleOCR#10211]
[2023/06/19 18:09:09] ppocr INFO: train with paddle 2.5.0-rc1 and device Place(cpu)
Traceback (most recent call last):
  File "D:\PaddleOCR-dygraph\tools\train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "D:\PaddleOCR-dygraph\tools\train.py", line 52, in main
    set_signal_handlers()
  File "D:\PaddleOCR-dygraph\ppocr\data\__init__.py", line 56, in set_signal_handlers
    pgid = os.getpgid(os.getpid())
AttributeError: module 'os' has no attribute 'getpgid'. Did you mean: 'getpid'?

D:\PaddleOCR-dygraph>

**Comment by centurions** [comment]
It has been fixed by [Bobholamovic] . Thank you
