### ISSUE TITLE
paddleOCR 服务化部署demo报错

### ISSUE THREAD

**Issue by XxsSss** [PaddlePaddle/PaddleOCR#10224]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：paddle aistudio 平台
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：Paddle Serving
- 运行指令/Command Code：
import os
os.chdir("/home/aistudio/PaddleOCR/deploy/pdserving/")
!python pipeline_http_client.py
- 完整报错/Complete Error Message：
**********../../doc/imgs/korean_1.jpg**********
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f493fc89150>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9998): Max retries exceeded with url: /ocr/prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f493fc89150>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipeline_http_client.py", line 67, in <module>
    r = requests.post(url=url, data=json.dumps(data))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9998): Max retries exceeded with url: /ocr/prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f493fc89150>: Failed to establish a new connection: [Errno 111] Connection refused'))

参考官方文档中的教程（https://aistudio.baidu.com/aistudio/projectdetail/3630726）测试paddleOCR服务化部署报错
在aistudio中报错，本地也报错

**Comment by EasyIsAllYouNeed** [comment]
看上去像是http代理惹的祸，执行
unset https_proxy  
unset http_proxy 
后再试试

**Comment by XxsSss** [comment]
> 看上去像是http代理惹的祸，执行 unset https_proxy unset http_proxy 后再试试

好的谢谢
