### ISSUE TITLE
使用RE推理模型报错

### ISSUE THREAD

**Issue by yuminzhe** [PaddlePaddle/PaddleOCR#10253]
- 系统环境/System Environment：苹果 m2

- 版本号/Version：Paddle： 2.3.2 PaddleOCR： 2.6.1.3

- 运行指令/Command Code：

python3 kie/predict_kie_token_ser_re.py --kie_algorithm=LayoutXLM --re_model_dir=/Users/zcy1/Desktop/PaddleOCR/ppstructure/re_vi_layoutxlm_xfund_infer --ser_model_dir=/Users/zcy1/Desktop/PaddleOCR/ppstructure/ser_vi_layoutxlm_xfund_infer --use_visual_backbone=False --ser_dict_path=/Users/zcy1/Desktop/ocr-modules/labels_ser.txt  --vis_font_path=../doc/fonts/simfang.ttf  --ocr_order_method="tb-yx" --image_dir=/Users/zcy1/Downloads/mask/1565212117673821_149.jpg

- 完整报错/Complete Error Message：

[2023-06-27 11:51:21,708] [    INFO] - Already cached /Users/zcy1/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2023-06-27 11:51:21,975] [    INFO] - tokenizer config file saved in /Users/zcy1/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2023-06-27 11:51:21,975] [    INFO] - Special tokens file saved in /Users/zcy1/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
E0627 11:51:22.065899 77439616 analysis_config.cc:95] Please compile with gpu to EnableGpu()
E0627 11:51:23.358011 77439616 analysis_config.cc:95] Please compile with gpu to EnableGpu()
Traceback (most recent call last):
  File "kie/predict_kie_token_ser_re.py", line 135, in <module>
    main(parse_args())
  File "kie/predict_kie_token_ser_re.py", line 101, in main
    re_res, elapse = ser_re_predictor(img)
  File "kie/predict_kie_token_ser_re.py", line 64, in __call__
    self.predictor.run()
RuntimeError: In user code:

    File "tools/export_model.py", line 258, in <module>
      main()
    File "tools/export_model.py", line 254, in main
      model, arch_config, save_path, logger, input_shape=input_shape)
    File "tools/export_model.py", line 174, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "<decorator-gen-106>", line 2, in save

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 861, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-104>", line 2, in from_func_spec

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmp1jzgs091.py", line 28, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 237, in forward
      relations=relations)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1542, in forward
      relations)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1408, in forward
      relations, entities = self.build_relation(relations, entities)
    File "/tmp/tmpt8u0m8_d.py", line 106, in build_relation
      for_loop_body_2, [entities, new_relations, relations, b, batch_size])
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
      output_vars = body(*loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1344, in build_relation
      axis=2).reshape([-1, 2])
    File "/usr/local/lib/python3.7/site-packages/paddle/tensor/creation.py", line 803, in meshgrid
      type='meshgrid', inputs={'X': list(args)}, outputs={'Out': out})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Tensor holds no memory. Call Tensor::mutable_data firstly.
      [Hint: holder_ should not be null.] (at /home/Paddle/paddle/phi/core/dense_tensor_impl.cc:46)
      [operator < meshgrid > error]

有些图片报错，有些图片可以正常运行。

**Comment by shiyutang** [comment]
建议检查哪些图片报错，是否是图片读取报错。
