### ISSUE TITLE
The size of Op(Conv) inputs should not be 0

### ISSUE THREAD

**Issue by skye-z** [PaddlePaddle/PaddleOCR#10263]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.5  PaddleOCR：2.6 问题相关组件/Related components：ch_PP-OCRv3_det_infer
- 运行指令/Command Code：调用 goapi 预测器
- 完整报错/Complete Error Message：
```shell
[DET] Input Image
libc++abi: terminating due to uncaught exception of type phi::enforce::EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 172, in <module>
      main()
    File "tools/export_model.py", line 165, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 99, in export_single_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 79, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 146, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 179, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 677, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 148, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The size of Op(Conv) inputs should not be 0.
  [Hint: Expected in_dims[i] != 0, but received in_dims[i]:0 == 0:0.] (at /Users/paddle/xly/workspace/compile_infer/Paddle/paddle/phi/infermeta/binary.cc:465)
  [operator < conv2d > error]
SIGABRT: abort
PC=0x7ff8099a61f2 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x10022b030, 0xc000052db0)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000052d88 sp=0xc000052d50 pc=0x10000735c
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi._Cfunc_PD_PredictorRun(0x100de09c0)
        _cgo_gotypes.go:1329 +0x49 fp=0xc000052db0 sp=0xc000052d88 pc=0x100226b29
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi.(*Predictor).Run.func1(0x0?)
        /Users/zhaoguiyang/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20230619060011-feff99f5e164/predictor.go:145 +0x46 fp=0xc000052de8 sp=0xc000052db0 pc=0x1002280e6
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi.(*Predictor).Run(0x1002fc8c0?)
        /Users/zhaoguiyang/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20230619060011-feff99f5e164/predictor.go:145 +0x19 fp=0xc000052e00 sp=0xc000052de8 pc=0x100228079
micro-ocr/ocr.(*GoDET).Run(0xc000052f18, {0x1002fdc88, 0xc000174680})
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/ocr/det.go:36 +0x18e fp=0xc000052ee8 sp=0xc000052e00 pc=0x1002298ee
main.runDemo()
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/main.go:34 +0xb3 fp=0xc000052f38 sp=0xc000052ee8 pc=0x10022a0b3
main.main()
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/main.go:25 +0x5d fp=0xc000052f80 sp=0xc000052f38 pc=0x100229fdd
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000052fe0 sp=0xc000052f80 pc=0x1000394a7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x100068421

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044fb0 sp=0xc000044f90 pc=0x1000398d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000044fe0 sp=0xc000044fb0 pc=0x100039710
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x100068421
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000045780 sp=0xc000045760 pc=0x1000398d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000457c8 sp=0xc000045780 pc=0x1000268be
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000457e0 sp=0xc0000457c8 pc=0x10001bce6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x100068421
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xebdc9bf4885f6?, 0xb86793?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000045f70 sp=0xc000045f50 pc=0x1000398d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x10047bd60)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000045fa0 sp=0xc000045f70 pc=0x100024753
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000045fc8 sp=0xc000045fa0 pc=0x100024d45
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x10001bc86
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x100068421
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x10047c280?, 0xa0?, 0x61?, 0xc000044770?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044628 sp=0xc000044608 pc=0x1000398d6
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000447e0 sp=0xc000044628 pc=0x10001ad27
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x100068421
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x45

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040750 sp=0xc000040730 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000407e0 sp=0xc000040750 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xebdc9bf456622?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000092750 sp=0xc000092730 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000927e0 sp=0xc000092750 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000927e8 sp=0xc0000927e0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0xebdc9bf455489?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000046750 sp=0xc000046730 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000467e0 sp=0xc000046750 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000467e8 sp=0xc0000467e0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 6 [GC worker (idle)]:
runtime.gopark(0xebdc9bf4d982f?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000046f50 sp=0xc000046f30 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000046fe0 sp=0xc000046f50 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

rax    0x0
rbx    0x7ff84d0b1340
rcx    0x7ff7bfefe2f8
rdx    0x0
rdi    0x103
rsi    0x6
rbp    0x7ff7bfefe320
rsp    0x7ff7bfefe2f8
r8     0x7ff7bfefe1c0
r9     0x7ff80999b6fe
```

**Comment by skye-z** [comment]
前置信息见 Paddle [#54915](https://github.com/PaddlePaddle/Paddle/issues/54915)

**Comment by GreatV** [comment]
det_mobilenet_v3 输入得float32类型

**Comment by skye-z** [comment]
> det_mobilenet_v3 输入得float32类型

我在Paddle [#54915](https://github.com/PaddlePaddle/Paddle/issues/54915) 中有提到传入类型已经是float32了

目前主要的问题是无法使用OpenCV, 那么我只能自己把图片转为三维向量, 但是转出来的[]float32模型不认, 报`The size of Op(Conv) inputs should not be 0`

转换示例代码
```go
package main

import (
	"fmt"
	"image"
	_ "image/png"
	"os"
)

func main() {
	f, err := os.Open("./gopher.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	// 获取图片的长宽
	bounds := img.Bounds()
	width := bounds.Dx()
	height := bounds.Dy()
	// 创建一个长度为 width * height * 3 的 []float32 类型的向量
	vector := make([]float32, width*height*3)
	// 遍历图片的每个像素点，将其红、绿、蓝三个分量分别存入向量
	for x := 0; x < width; x++ {
		for y := 0; y < height; y++ {
			// 获取像素点的颜色
			color := img.At(x, y)
			// 将颜色转换为 uint8 类型
			r, g, b, _ := color.RGBA()
			r = r >> 8
			g = g >> 8
			b = b >> 8
			// 将红绿蓝转换 float32 类型后存入
			vector[(x+y*width)*3] = float32(r)
			vector[(x+y*width)*3+1] = float32(g)
			vector[(x+y*width)*3+2] = float32(b)
		}
	}
	fmt.Println(vector)
}
```

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
