### ISSUE TITLE
Trouble serving layout model

### ISSUE THREAD

**Issue by Shadow-Alex** [PaddlePaddle/PaddleOCR#10285]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 + py3.9 + CUDA 11.6
- 版本号/Version：Paddle：2.5.0  PaddleOCR：2.6.0 问题相关组件/Related components：
- 运行指令/Command Code：hub install deploy\hubserving\structure_layout\
- 完整报错/Complete Error Message：
 ```
Traceback (most recent call last):
  File "E:\anaconda3\envs\ocr\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\ocr\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\envs\ocr\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "E:\anaconda3\envs\ocr\lib\site-packages\paddlehub\__init__.py", line 52, in <module>
    from paddlehub.compat.task.text_generation_task import TextGenerationTask
  File "E:\anaconda3\envs\ocr\lib\site-packages\paddlehub\compat\task\text_generation_task.py", line 22, in <module>
    from paddle.fluid.layers import RNNCell, LSTMCell, rnn, BeamSearchDecoder, dynamic_decode
ImportError: cannot import name 'RNNCell' from 'paddle.fluid.layers' (E:\anaconda3\envs\ocr\lib\site-packages\paddle\fluid\layers\__init__.py)
```

**Comment by GreatV** [comment]
Hi, @Shadow-Alex, `RNNCell` has been removed in paddle 2.5, you might use paddle 2.4.2.

**Comment by Shadow-Alex** [comment]
thanks, downgrade works well

**Comment by shiyutang** [comment]
You are welcomed to participate in our activity：https://github.com/PaddlePaddle/PaddleOCR/issues/10223
