### ISSUE TITLE
文字检测时transform出现问题

### ISSUE THREAD

**Issue by guangyangL** [PaddlePaddle/PaddleOCR#10283]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：) python3 tools/train.py -c configs/det/det_r18_vd_ct.yml -o Global.pretrained_model=pretrain_models/ResNet18_vd_pretrained
- 完整报错/Complete Error Message：[2023/07/03 19:58:10] ppocr ERROR: When parsing line train_data/rec/train/good_cc_13_0.jpg      [{"transcription": "MIN28MM", "points": [[49, 209], [98, 136], [150, 86], [213, 47], [193, 10], [117, 52], [57, 114], [13, 186]], "difficult": true}]
, error happened with msg: Traceback (most recent call last):
  File "/opt/product/PaddleOCR/ppocr/data/simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/opt/product/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/opt/product/PaddleOCR/ppocr/data/imaug/ct_process.py", line 113, in __call__
    bboxes[i] = np.reshape(bboxes[i] * (
ValueError: operands could not be broadcast together with shapes (8,2) (8,) 

[2023/07/03 19:58:10] ppocr ERROR: When parsing line train_data/rec/train/good_cc_10_0.jpg      [{"transcription": "MIN28MM", "points": [[14, 31], [55, 15], [76, 79], [80, 182], [59, 271], [17, 253], [34, 176], [29, 90]], "difficult": true}]
, error happened with msg: Traceback (most recent call last):
  File "/opt/product/PaddleOCR/ppocr/data/simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/opt/product/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/opt/product/PaddleOCR/ppocr/data/imaug/ct_process.py", line 113, in __call__
    bboxes[i] = np.reshape(bboxes[i] * (
ValueError: operands could not be broadcast together with shapes (8,2) (8,) 

[2023/07/03 19:58:10] ppocr ERROR: When parsing line train_data/rec/train/good_cc_9_1.jpg       [{"transcription": "3E21", "points": [[46, 52], [62, 87], [98, 73], [171, 58], [167, 16], [100, 28]], "difficult": true}]
, error happened with msg: Traceback (most recent call last):
  File "/opt/product/PaddleOCR/ppocr/data/simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/opt/product/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/opt/product/PaddleOCR/ppocr/data/imaug/ct_process.py", line 113, in __call__
    bboxes[i] = np.reshape(bboxes[i] * (
ValueError: operands could not be broadcast together with shapes (6,2) (6,)

**Comment by guangyangL** [comment]
我在训练模型时出现的问题
