### ISSUE TITLE
检测弯曲文本时评估产生问题

### ISSUE THREAD

**Issue by guangyangL** [PaddlePaddle/PaddleOCR#10308]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_mv3_db.yml
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "/opt/product/PaddleOCR/tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "/opt/product/PaddleOCR/tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/opt/product/PaddleOCR/tools/program.py", line 385, in train
    cur_metric = eval(
  File "/opt/product/PaddleOCR/tools/program.py", line 558, in eval
    post_result = post_process_class(preds, batch_numpy[1])
  File "/opt/product/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 237, in __call__
    boxes, scores = self.polygons_from_bitmap(pred[batch_index],
  File "/opt/product/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 91, in polygons_from_bitmap
    _, sside = self.get_mini_boxes(box.reshape((-1, 1, 2)))
  File "/opt/product/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 160, in get_mini_boxes
    bounding_box = cv2.minAreaRect(contour)
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-1mhygbdf/opencv/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'

训练日志
Architecture : 
[2023/07/06 15:46:03] ppocr INFO:     Backbone : 
[2023/07/06 15:46:03] ppocr INFO:         model_name : large
[2023/07/06 15:46:03] ppocr INFO:         name : MobileNetV3
[2023/07/06 15:46:03] ppocr INFO:         scale : 0.5
[2023/07/06 15:46:03] ppocr INFO:     Head : 
[2023/07/06 15:46:03] ppocr INFO:         k : 50
[2023/07/06 15:46:03] ppocr INFO:         name : DBHead
[2023/07/06 15:46:03] ppocr INFO:     Neck : 
[2023/07/06 15:46:03] ppocr INFO:         name : DBFPN
[2023/07/06 15:46:03] ppocr INFO:         out_channels : 256
[2023/07/06 15:46:03] ppocr INFO:     Transform : None
[2023/07/06 15:46:03] ppocr INFO:     algorithm : DB
[2023/07/06 15:46:03] ppocr INFO:     model_type : det
[2023/07/06 15:46:03] ppocr INFO: Eval : 
[2023/07/06 15:46:03] ppocr INFO:     dataset : 
[2023/07/06 15:46:03] ppocr INFO:         data_dir : ./train_data_polygon/det
[2023/07/06 15:46:03] ppocr INFO:         label_file_list : ['./train_data_polygon/det/test/test.txt']
[2023/07/06 15:46:03] ppocr INFO:         name : SimpleDataSet
[2023/07/06 15:46:03] ppocr INFO:         transforms : 
[2023/07/06 15:46:03] ppocr INFO:             DecodeImage : 
[2023/07/06 15:46:03] ppocr INFO:                 channel_first : False
[2023/07/06 15:46:03] ppocr INFO:                 img_mode : BGR
[2023/07/06 15:46:03] ppocr INFO:             DetLabelEncode : None
[2023/07/06 15:46:03] ppocr INFO:             DetResizeForTest : 
[2023/07/06 15:46:03] ppocr INFO:                 image_shape : [416, 416]
[2023/07/06 15:46:03] ppocr INFO:             NormalizeImage : 
[2023/07/06 15:46:03] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2023/07/06 15:46:03] ppocr INFO:                 order : hwc
[2023/07/06 15:46:03] ppocr INFO:                 scale : 1./255.
[2023/07/06 15:46:03] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2023/07/06 15:46:03] ppocr INFO:             ToCHWImage : None
[2023/07/06 15:46:03] ppocr INFO:             KeepKeys : 
[2023/07/06 15:46:03] ppocr INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2023/07/06 15:46:03] ppocr INFO:     loader : 
[2023/07/06 15:46:03] ppocr INFO:         batch_size_per_card : 1
[2023/07/06 15:46:03] ppocr INFO:         drop_last : False
[2023/07/06 15:46:03] ppocr INFO:         num_workers : 8
[2023/07/06 15:46:03] ppocr INFO:         shuffle : False
[2023/07/06 15:46:03] ppocr INFO:         use_shared_memory : True
[2023/07/06 15:46:03] ppocr INFO: Global : 
[2023/07/06 15:46:03] ppocr INFO:     cal_metric_during_train : False
[2023/07/06 15:46:03] ppocr INFO:     checkpoints : None
[2023/07/06 15:46:03] ppocr INFO:     distributed : False
[2023/07/06 15:46:03] ppocr INFO:     epoch_num : 500
[2023/07/06 15:46:03] ppocr INFO:     eval_batch_step : [0, 100]
[2023/07/06 15:46:03] ppocr INFO:     infer_img : doc/imgs_en/img_10.jpg
[2023/07/06 15:46:03] ppocr INFO:     log_smooth_window : 20
[2023/07/06 15:46:03] ppocr INFO:     pretrained_model : ./pretrain_models/MobileNetV3_large_x0_5_pretrained
[2023/07/06 15:46:03] ppocr INFO:     print_batch_step : 100
[2023/07/06 15:46:03] ppocr INFO:     save_epoch_step : 1200
[2023/07/06 15:46:03] ppocr INFO:     save_inference_dir : None
[2023/07/06 15:46:03] ppocr INFO:     save_model_dir : ./output/db_mv3/polygons
[2023/07/06 15:46:03] ppocr INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2023/07/06 15:46:03] ppocr INFO:     use_gpu : True
[2023/07/06 15:46:03] ppocr INFO:     use_mlu : False
[2023/07/06 15:46:03] ppocr INFO:     use_visualdl : False
[2023/07/06 15:46:03] ppocr INFO:     use_xpu : False
[2023/07/06 15:46:03] ppocr INFO: Loss : 
[2023/07/06 15:46:03] ppocr INFO:     alpha : 5
[2023/07/06 15:46:03] ppocr INFO:     balance_loss : True
[2023/07/06 15:46:03] ppocr INFO:     beta : 10
[2023/07/06 15:46:03] ppocr INFO:     main_loss_type : DiceLoss
[2023/07/06 15:46:03] ppocr INFO:     name : DBLoss
[2023/07/06 15:46:03] ppocr INFO:     ohem_ratio : 3
[2023/07/06 15:46:03] ppocr INFO: Metric : 
[2023/07/06 15:46:03] ppocr INFO:     main_indicator : hmean
[2023/07/06 15:46:03] ppocr INFO:     name : DetMetric
[2023/07/06 15:46:03] ppocr INFO: Optimizer : 
[2023/07/06 15:46:03] ppocr INFO:     beta1 : 0.9
[2023/07/06 15:46:03] ppocr INFO:     beta2 : 0.999
[2023/07/06 15:46:03] ppocr INFO:     lr : 
[2023/07/06 15:46:03] ppocr INFO:         learning_rate : 0.0001
[2023/07/06 15:46:03] ppocr INFO:     name : Adam
[2023/07/06 15:46:03] ppocr INFO:     regularizer : 
[2023/07/06 15:46:03] ppocr INFO:         factor : 0
[2023/07/06 15:46:03] ppocr INFO:         name : L2
[2023/07/06 15:46:03] ppocr INFO: PostProcess : 
[2023/07/06 15:46:03] ppocr INFO:     box_thresh : 0.6
[2023/07/06 15:46:03] ppocr INFO:     max_candidates : 1000
[2023/07/06 15:46:03] ppocr INFO:     name : DBPostProcess
[2023/07/06 15:46:03] ppocr INFO:     thresh : 0.3
[2023/07/06 15:46:03] ppocr INFO:     unclip_ratio : 1.5
[2023/07/06 15:46:03] ppocr INFO:     use_polygon : True
[2023/07/06 15:46:03] ppocr INFO: Train : 
[2023/07/06 15:46:03] ppocr INFO:     dataset : 
[2023/07/06 15:46:03] ppocr INFO:         data_dir : ./train_data_polygon/det
[2023/07/06 15:46:03] ppocr INFO:         label_file_list : ['./train_data_polygon/det/train/train.txt']
[2023/07/06 15:46:03] ppocr INFO:         name : SimpleDataSet
[2023/07/06 15:46:03] ppocr INFO:         ratio_list : [1.0]
[2023/07/06 15:46:03] ppocr INFO:         transforms : 
[2023/07/06 15:46:03] ppocr INFO:             DecodeImage : 
[2023/07/06 15:46:03] ppocr INFO:                 channel_first : False
[2023/07/06 15:46:03] ppocr INFO:                 img_mode : BGR
[2023/07/06 15:46:03] ppocr INFO:             DetLabelEncode : None
[2023/07/06 15:46:03] ppocr INFO:             IaaAugment : 
[2023/07/06 15:46:03] ppocr INFO:                 augmenter_args : 
[2023/07/06 15:46:03] ppocr INFO:                     args : 
[2023/07/06 15:46:03] ppocr INFO:                         p : 0.5
[2023/07/06 15:46:03] ppocr INFO:                     type : Fliplr
[2023/07/06 15:46:03] ppocr INFO:                     args : 
[2023/07/06 15:46:03] ppocr INFO:                         rotate : [-10, 10]
[2023/07/06 15:46:03] ppocr INFO:                     type : Affine
[2023/07/06 15:46:03] ppocr INFO:                     args : 
[2023/07/06 15:46:03] ppocr INFO:                         size : [0.5, 3]
[2023/07/06 15:46:03] ppocr INFO:                     type : Resize
[2023/07/06 15:46:03] ppocr INFO:             EastRandomCropData : 
[2023/07/06 15:46:03] ppocr INFO:                 keep_ratio : True
[2023/07/06 15:46:03] ppocr INFO:                 max_tries : 50
[2023/07/06 15:46:03] ppocr INFO:                 size : [320, 320]
[2023/07/06 15:46:03] ppocr INFO:             MakeBorderMap : 
[2023/07/06 15:46:03] ppocr INFO:                 shrink_ratio : 0.4
[2023/07/06 15:46:03] ppocr INFO:                 thresh_max : 0.7
[2023/07/06 15:46:03] ppocr INFO:                 thresh_min : 0.3
[2023/07/06 15:46:03] ppocr INFO:             MakeShrinkMap : 
[2023/07/06 15:46:03] ppocr INFO:                 min_text_size : 8
[2023/07/06 15:46:03] ppocr INFO:                 shrink_ratio : 0.4
[2023/07/06 15:46:03] ppocr INFO:             NormalizeImage : 
[2023/07/06 15:46:03] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2023/07/06 15:46:03] ppocr INFO:                 order : hwc
[2023/07/06 15:46:03] ppocr INFO:                 scale : 1./255.
[2023/07/06 15:46:03] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2023/07/06 15:46:03] ppocr INFO:             ToCHWImage : None
[2023/07/06 15:46:03] ppocr INFO:             KeepKeys : 
[2023/07/06 15:46:03] ppocr INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2023/07/06 15:46:03] ppocr INFO:     loader : 
[2023/07/06 15:46:03] ppocr INFO:         batch_size_per_card : 20
[2023/07/06 15:46:03] ppocr INFO:         drop_last : False
[2023/07/06 15:46:03] ppocr INFO:         num_workers : 8
[2023/07/06 15:46:03] ppocr INFO:         shuffle : True
[2023/07/06 15:46:03] ppocr INFO:         use_shared_memory : True
[2023/07/06 15:46:03] ppocr INFO: profiler_options : None
[2023/07/06 15:46:03] ppocr INFO: train with paddle 0.0.0 and device Place(gpu:0)
[2023/07/06 15:46:03] ppocr INFO: Initialize indexs of datasets:['./train_data_polygon/det/train/train.txt']
[2023/07/06 15:46:03] ppocr INFO: Initialize indexs of datasets:['./train_data_polygon/det/test/test.txt']
[2023/07/06 15:46:05] ppocr INFO: train dataloader has 9 iters
[2023/07/06 15:46:05] ppocr INFO: valid dataloader has 48 iters

之前训练时不出现多边形
我修改了ppocr/postprocess/DBPostPricess中的
 def __init__(self,
                 thresh=0.3,
                 box_thresh=0.7,
                 max_candidates=1000,
                 unclip_ratio=2.0,
                 use_dilation=False,
                 score_mode="fast",
                 box_type='poly',
                 **kwargs):
然后就出现这个错误

**Comment by guangyangL** [comment]
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
又跑了一遍出现了新的error

**Comment by guangyangL** [comment]
File "/opt/product/PaddleOCR/tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "/opt/product/PaddleOCR/tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/opt/product/PaddleOCR/tools/program.py", line 385, in train
    cur_metric = eval(
  File "/opt/product/PaddleOCR/tools/program.py", line 558, in eval
    post_result = post_process_class(preds, batch_numpy[1])
  File "/opt/product/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 238, in __call__
    boxes, scores = self.polygons_from_bitmap(pred[batch_index],
  File "/opt/product/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 85, in polygons_from_bitmap
    box = self.unclip(points, self.unclip_ratio)
  File "/opt/product/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 157, in unclip
    expanded = np.array(offset.Execute(distance))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
