### ISSUE TITLE
logging error in training

### ISSUE THREAD

**Issue by Rudragoud** [PaddlePaddle/PaddleOCR#10302]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：google colab
- 版本号/Version：Paddle：2.4.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
[2023/07/05 08:09:14] ppocr INFO: epoch: [50/150], global_step: 1740, lr: 0.000799, acc: 0.499999, norm_edit_dis: 0.915404, CTCLoss: 3.166237, SARLoss: 0.402030, loss: 3.531956, avg_reader_cost: 0.00040 s, avg_batch_cost: 7.87280 s, avg_samples: 6.0, ips: 0.76212 samples/s, eta: 7:22:50
[2023/07/05 08:10:01] ppocr INFO: epoch: [50/150], global_step: 1746, lr: 0.000797, acc: 0.416666, norm_edit_dis: 0.902147, CTCLoss: 3.058416, SARLoss: 0.413477, loss: 3.430591, avg_reader_cost: 0.00035 s, avg_batch_cost: 7.78237 s, avg_samples: 6.0, ips: 0.77097 samples/s, eta: 7:22:07
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1104, in emit
    self.flush()
  File "/usr/lib/python3.10/logging/__init__.py", line 1084, in flush
    self.stream.flush()
OSError: [Errno 107] Transport endpoint is not connected
Call stack:
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/train.py", line 181, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/program.py", line 369, in train
    logger.info(strs)
Message: 'epoch: [50/150], global_step: 1746, lr: 0.000797, acc: 0.416666, norm_edit_dis: 0.902147, CTCLoss: 3.058416, SARLoss: 0.413477, loss: 3.430591, avg_reader_cost: 0.00035 s, avg_batch_cost: 7.78237 s, avg_samples: 6.0, ips: 0.77097 samples/s, eta: 7:22:07'
Arguments: ()

**Comment by GreatV** [comment]
This may not be a PaddleOCR problem `OSError: [Errno 107] Transport endpoint is not connected`. See:
- https://github.com/googlecolab/colabtools/issues/3221#issue-1441136412

**Comment by Rudragoud** [comment]
Thanks, Got it

**Comment by Rudragoud** [comment]
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.ctc_head.fc.weight [64, 65] not matched with loaded params head.ctc_head.fc.weight [64, 97] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.ctc_head.fc.bias [65] not matched with loaded params head.ctc_head.fc.bias [97] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.embedding.weight [67, 512] not matched with loaded params head.sar_head.decoder.embedding.weight [99, 512] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.weight [1536, 66] not matched with loaded params head.sar_head.decoder.prediction.weight [1536, 98] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.bias [66] not matched with loaded params head.sar_head.decoder.prediction.bias [98] !

dose the  above warnings  affect the accuracy of the training  model?

**Comment by GreatV** [comment]
Did you change the character dictionary? It usually does not affect the accuracy.

https://github.com/PaddlePaddle/PaddleOCR/blob/795c81f1835725dbf9bf9f5a13e0c793dfd5f243/configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml#L16

**Comment by Rudragoud** [comment]
Yeah path is changed before only

**Comment by GreatV** [comment]
For more details, please refer: 
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/finetune_en.md#3-text-recognition-model-fine-tuning

**Comment by Rudragoud** [comment]
Yeah, sure I will check on this . Thank You

**Comment by yuki-inaho** [comment]
> [2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.ctc_head.fc.weight [64, 65] not matched with loaded params head.ctc_head.fc.weight [64, 97] ! [2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.ctc_head.fc.bias [65] not matched with loaded params head.ctc_head.fc.bias [97] ! [2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.embedding.weight [67, 512] not matched with loaded params head.sar_head.decoder.embedding.weight [99, 512] ! [2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.weight [1536, 66] not matched with loaded params head.sar_head.decoder.prediction.weight [1536, 98] ! [2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.bias [66] not matched with loaded params head.sar_head.decoder.prediction.bias [98] !
> 
> dose the above warnings affect the accuracy of the training model?
> 
> I am using en_PP-OCRv3_rec.yml file to train

Regarding this comment, it's highly likely that the error occurred when specifying `ppocr/utils/dict/en_dict.txt` instead of `ppocr/utils/en_dict.txt`.This issue seems to arise more frequently when using absolute paths rather than relative paths for specifying the dictionary.
I also encountered a similar error code and noticed that this issue did not have an explicit solution described.Therefore, I provide an additional note.

```
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.ctc_head.fc.weight [64, 65] not matched with loaded params head.ctc_head.fc.weight [64, 97] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.ctc_head.fc.bias [65] not matched with loaded params head.ctc_head.fc.bias [97] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.embedding.weight [67, 512] not matched with loaded params head.sar_head.decoder.embedding.weight [99, 512] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.weight [1536, 66] not matched with loaded params head.sar_head.decoder.prediction.weight [1536, 98] !
[2023/07/06 06:41:12] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.bias [66] not matched with loaded params head.sar_head.decoder.prediction.bias [98] !
```
