### ISSUE TITLE
paddle转onnx时，将paddle训练模型转推理模型失败。

### ISSUE THREAD

**Issue by chengchao23** [PaddlePaddle/PaddleOCR#10374]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle==2.4.2, paddleocr== 2.6.1.3
- 运行指令/Command Code：python3.7 tools/export_model.py -c configs/det/det_r50_drrg_ctw.yml -o Global.pretrained_model=/data/chengchao/paddlemodel/det_r50_drrg_ctw_train/best_accuracy Global.save_inference_dir=/data/chengchao/paddlemodel/det_r50_drrg_ctw_train/
- 完整报错/Complete Error Message：
 Traceback (most recent call last):
  File "tools/export_model.py", line 269, in <module>
    main()
  File "tools/export_model.py", line 265, in main
    model, arch_config, save_path, logger, input_shape=input_shape)
  File "tools/export_model.py", line 185, in export_single_model
    paddle.jit.save(model, save_path)
  File "/root/miniconda3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/api.py", line 752, in wrapper
    func(layer, path, input_spec, **configs)
  File "/root/miniconda3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/api.py", line 1046, in save
    is_prim_infer=is_prim_infer,
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/dy2static/program_translator.py", line 713, in concrete_program_specify_input_spec
    is_prim_infer=is_prim_infer,
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/dy2static/program_translator.py", line 590, in get_concrete_program
    cache_key
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/dy2static/program_translator.py", line 1249, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/dy2static/program_translator.py", line 1198, in _build_once
    **cache_key.kwargs,
  File "/root/miniconda3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/dy2static/program_translator.py", line 1070, in from_func_spec
    error_data.raise_new_exception()
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/jit/dy2static/error.py", line 452, in raise_new_exception
    raise new_exception from None
ValueError: In transformed code:

    File "/data/z00579964/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 99, in forward
        if self.use_head:
    File "/data/z00579964/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward
        x = self.head(x, targets=data)
    File "/data/z00579964/PaddleOCR/ppocr/modeling/heads/det_drrg_head.py", line 131, in forward
        if self.training:
    File "/data/z00579964/PaddleOCR/ppocr/modeling/heads/det_drrg_head.py", line 143, in forward
        return self.single_test(inputs)
    File "/data/z00579964/PaddleOCR/ppocr/modeling/heads/det_drrg_head.py", line 165, in single_test
        none_flag, graph_data = self.graph_test(pred_maps, feat_maps)
    File "/data/z00579964/PaddleOCR/ppocr/modeling/heads/proposal_local_graph.py", line 380, in __call__
        comp_attribs, text_comps = self.propose_comps_and_attribs(
    File "/data/z00579964/PaddleOCR/ppocr/modeling/heads/proposal_local_graph.py", line 171, in propose_comps_and_attribs
        center_region_mask = fill_hole(center_region_mask)
    File "/data/z00579964/PaddleOCR/ppocr/modeling/heads/proposal_local_graph.py", line 36, in fill_hole
        def fill_hole(input_mask):
            h, w = input_mask.shape
            ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            canvas = np.zeros((h + 2, w + 2), np.uint8)
            canvas[1:h + 1, 1:w + 1] = input_mask.copy()


    ValueError: too many values to unpack (expected 2)

**Comment by chengchao23** [comment]
感觉是yml文件的问题

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
