### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by xuri422** [PaddlePaddle/PaddleOCR#10398]
My code run in JetBrain is very well, There are no errors.

But when I use "pyinstaller -F main.py"  build code to exe file(no error), and then run in command line. there are show me some errors:

PyInstaller\loader\pyimod02_importers.py:385: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\paddleocr.py", line 33, in <module>
  File "importlib\__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'tools'
[11752] Failed to execute script 'main' due to unhandled exception!

I have try it in two PC, show the some errors. So, How can I resolve it?

**Comment by xuri422** [comment]
pip list show versions:
paddleocr                 2.6.1.3
paddlepaddle           2.4.2
pandas                     2.0.1

**Comment by UserWangZz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/discussions/11490
you can reference this link to packpage the code. the paddle official isn't support to package the paddleocr.
