### ISSUE TITLE
运行PGNet的时候报错

### ISSUE THREAD

**Issue by forAlgorithm** [PaddlePaddle/PaddleOCR#10449]
import os
os.chdir('/content/PaddleOCR')
!python tools/infer/predict_e2e.py --e2e_algorithm="PGNet" --image_dir="./doc/imgs_en/img10.jpg" --e2e_model_dir="/content/inference/e2e_server_pgnetA_infer" --e2e_pgnet_valid_set="totaltext"
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/content/PaddleOCR/tools/infer/predict_e2e.py", line 28, in <module>
    import tools.infer.utility as utility
  File "/content/PaddleOCR/tools/infer/utility.py", line 21, in <module>
    import paddle
  File "/usr/local/lib/python3.10/dist-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by GreatV** [comment]
这个是paddle的报错，暂时的解决方案是降paddle版本到2.4.2。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
