### ISSUE TITLE
help No output, paddleStructure layout analysis (PubLayNet pretrained model)

### ISSUE THREAD

**Issue by mllife** [PaddlePaddle/PaddleOCR#10476]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Mac M1 PRO
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddleStructure
- 运行指令/Command Code：used python snippet code ([2.2 Use by python script](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#22-use-by-python-script))

`
import os
import cv2
from PIL import Image
from paddleocr import PPStructure, draw_structure_result, save_structure_res

engine = PPStructure(
    show_log=True,
    lang='en',
    layout_model_dir="./layout_model",  # containing 'ppyolov2_r50vd_dcn_365e_publaynet_pretrained.pdparams'
    layout_dict_path="./layout_model/layout_publaynet_dict.txt",
    structure_version="PP-Structure",
    # structure_version="PP-StructureV2",
    ocr=False,
    recovery=False
)

save_folder = './output'
img_path = "data/test_page_0.jpg"
img = cv2.imread(img_path)
result = engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

font_path = './Roboto/Roboto-Light.ttf'  # font provided in PaddleOCR
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result, font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.show()
im_show.save('result.jpg')
`
- 完整报错/Complete Error Message：
  - i used the python code snipped given here with model parameters provided in readme - https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#222-layout-analysis--table-recognition
  - i want to get the layout analysis using the model here - https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list_en.md#:~:text=ppyolov2_r50vd_dcn_365e_publaynet,same%20as%20above
  
  - nothing is working after line 20, no result

**Comment by mllife** [comment]
this code only download some other models like cn_ocr or table_infer which i don't want, i want to use the publaynet pretrained model published here - https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list_en.md#:~:text=ppyolov2_r50vd_dcn_365e_publaynet,same%20as%20above

**Comment by mllife** [comment]
@shiyutang , please help

**Comment by mllife** [comment]
@vikhil0609, can you help here?

**Comment by vikhil0609** [comment]
Yes sure ,
We can connect sallagargivikhil123@gmail.com
7506229401

**Comment by mllife** [comment]
@vikhil0609 , please check your email. try to help here if possible so others can also benefit.

**Comment by mllife** [comment]
update - unable to get the code working on m1 mac, but got it working in sagemaker
this error now
```
(python3) sh-4.2$ python custom_ppstructure.py 
[2023/07/26 05:02:54] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, use_npu=False, use_mlu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/home/ec2-user/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/home/ec2-user/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/home/ec2-user/SageMaker/paddleocr/PaddleOCR/ppocr/utils/en_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=False, cls_model_dir=None, cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir='/home/ec2-user/.paddleocr/whl/table/en_ppocr_mobile_v2.0_table_structure_infer', merge_no_span_structure=False, table_char_dict_path='/home/ec2-user/SageMaker/paddleocr/PaddleOCR/ppocr/utils/dict/table_structure_dict.txt', layout_model_dir='./PaddleOCR/ppstructure/inference/ppyolov2_r50vd_dcn_365e_publaynet/', layout_dict_path='./PaddleOCR/ppstructure/inference/picodet_lcnet_x1_0_layout_infer/label.txt', layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=False, ocr=False, recovery=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='en', det=True, rec=True, type='ocr', ocr_version='PP-OCRv3', structure_version='PP-Structure')
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/paddleocr/custom_ppstructure.py", line 21, in <module>
    result = engine(img)
  File "/home/ec2-user/SageMaker/paddleocr/PaddleOCR/paddleocr.py", line 654, in __call__
    res, _ = super().__call__(
  File "/home/ec2-user/SageMaker/paddleocr/PaddleOCR/ppstructure/predict_system.py", line 112, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "/home/ec2-user/SageMaker/paddleocr/PaddleOCR/ppstructure/layout/predict_layout.py", line 86, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 107, in <module>
      main()
    File "tools/export_model.py", line 103, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/engine/trainer.py", line 460, in export
      input_spec, static_model.forward.main_program,
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/var/folders/0t/0lmgjgfj7012tggtgbwtqby80000l2/T/tmpk8piw4sd.py", line 26, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_1,
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/architectures/yolo.py", line 75, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/architectures/yolo.py", line 59, in _forward
      body_feats = self.backbone(self.inputs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/backbones/resnet.py", line 573, in forward
      conv1 = self.conv1(x)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
      input = layer(input)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/backbones/resnet.py", line 122, in forward
      out = self.conv(inputs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 631, in forward
      out = F.conv._conv_nd(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 143, in _conv_nd
      helper.append_op(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3012, in append_op
      op = Operator(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2102, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 1, input's shape is [0].
      [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at ../paddle/fluid/operators/fused/conv_fusion_op.cc:236)
      [operator < conv2d_fusion > error]
```

**Comment by tuongtranngoc** [comment]
@mllife  I also faced with this error, do you have any idea?

**Comment by mllife** [comment]
@tuongtranngoc , @chmjelek Sorry, but the issue is still not resolved for me. Hoping for some help from senior devs in this community. Please tag anyone who can help.

**Comment by mllife** [comment]
@tink2123
@shiyutang
pls help, urgent.

**Comment by mllife** [comment]
@andyjpaddle, urgent help?

**Comment by mllife** [comment]
> Yes sure , We can connect [sallagargivikhil123@gmail.com](mailto:sallagargivikhil123@gmail.com) 7506229401

your email is incorrect, couldn't send any mail.

**Comment by kenho211** [comment]
It is related to the input shape after resize. Please see https://github.com/PaddlePaddle/PaddleOCR/issues/9654

**Comment by nithamitabh** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：Mac M1 PRO
> * 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：PaddleStructure
> * 运行指令/Command Code：used python snippet code ([2.2 Use by python script](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#22-use-by-python-script))
> 
> ` import os import cv2 from PIL import Image from paddleocr import PPStructure, draw_structure_result, save_structure_res
> 
> engine = PPStructure( show_log=True, lang='en', layout_model_dir="./layout_model", # containing 'ppyolov2_r50vd_dcn_365e_publaynet_pretrained.pdparams' layout_dict_path="./layout_model/layout_publaynet_dict.txt", structure_version="PP-Structure", # structure_version="PP-StructureV2", ocr=False, recovery=False )
> 
> save_folder = './output' img_path = "data/test_page_0.jpg" img = cv2.imread(img_path) result = engine(img) save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])
> 
> for line in result: line.pop('img') print(line)
> 
> font_path = './Roboto/Roboto-Light.ttf' # font provided in PaddleOCR image = Image.open(img_path).convert('RGB') im_show = draw_structure_result(image, result, font_path=font_path) im_show = Image.fromarray(im_show) im_show.show() im_show.save('result.jpg') `
> 
> * 完整报错/Complete Error Message：
>   
>   * i used the python code snipped given here with model parameters provided in readme - https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#222-layout-analysis--table-recognition
>   * i want to get the layout analysis using the model here - https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list_en.md#:~:text=ppyolov2_r50vd_dcn_365e_publaynet,same%20as%20above
>   * nothing is working after line 20, no result

Let's start by looking at the code from line 20 onwards. It's important to examine the error message you encountered as well, as that will provide insight into what might be going wrong.

Let's go through the code step by step from line 20 and see if we can identify and fix the issue:

python
`
for line in result:
    line.pop('img')
print(line)
`
In this part of the code, you're iterating through the result list, which contains the structure analysis results. Within each iteration, you're using the pop() method to remove the 'img' key from the current line dictionary. This step is performed for each line in the result. However, after the loop, you are only printing the last line dictionary, which might not be your intention.

If you want to see the updated dictionaries after removing the 'img' key from all of them, you can modify the code like this:

python
`
for line in result:
    line.pop('img')
    print(line)  # Print the line after removing 'img' key
`
This change will print each modified line dictionary within the loop.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
