### ISSUE TITLE
使用pyinstaller打包pdserving cpu版本出现问题

### ISSUE THREAD

**Issue by gl94** [PaddlePaddle/PaddleOCR#10486]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04
- 版本号/Version：Paddle：2.5.0  PaddleOCR： 问题相关组件/Related components：pdserving
- 运行指令/Command Code：pyinstaller web_service.py
- 完整报错/Complete Error Message：
./web_service --config=config.yml
args config: {'rpc_port': 18091, 'http_port': 9998, 'worker_num': 4, 'build_dag_each_worker': False, 'dag': {'is_thread_op': False, 'retry': 10, 'use_profile': True, 'tracer': {'interval_s': 10}}, 'op': {'det': {'concurrency': 4, 'local_service_conf': {'client_type': 'local_predictor', 'model_config': '/home/guolei/Projects/pdserving/dist/web_service/ppocr_det_v3_serving', 'devices': None, 'ir_optim': True}}, 'rec': {'concurrency': 2, 'timeout': -1, 'retry': 1, 'local_service_conf': {'client_type': 'local_predictor', 'model_config': 'pdserving/dist/web_service/ppocr_det_v3_serving', 'devices': None, 'ir_optim': True}}}}
[DAG] Succ init
[PipelineServicer] succ init
2023/07/26 18:13:29 start proxy service
[det|2] failed to init op: Log_id: 0  Raise_msg: sequence item 0: expected str instance, NoneType found  ClassName: Op._run.&lt;locals&gt;.check_helper  FunctionName: check_helper
已杀死
pyinstaller import依赖啥的都解决了，不会报错，模型也换成绝对路径了，就是读不出来

**Comment by gl94** [comment]
log错误：
Traceback (most recent call last):
  File "paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "paddle_serving_server/pipeline/operator.py", line 1363, in check_helper
    concurrency_idx)
  File "paddle_serving_server/pipeline/local_service_handler.py", line 235, in get_client
    from paddle_serving_app.local_predict import LocalPredictor
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle_serving_app/local_predict.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/framework/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/framework/random.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/framework.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/core.py", line 394, in <module>
  File "paddle/fluid/core.py", line 386, in set_paddle_lib_path
TypeError: sequence item 0: expected str instance, NoneType found
Classname: Op._run.<locals>.check_helper
FunctionName: check_helper
可能还是根protoc有关系，这个很难打包

**Comment by gl94** [comment]
新定位到这个函数：
# set paddle lib path
def set_paddle_lib_path():
    site_dirs = (
        site.getsitepackages()
        if hasattr(site, 'getsitepackages')
        else [x for x in sys.path if 'site-packages' in x]
    )
    for site_dir in site_dirs:
        lib_dir = os.path.sep.join([site_dir, 'paddle', 'libs'])
        if os.path.exists(lib_dir):
            _set_paddle_lib_path(lib_dir)
            set_paddle_custom_device_lib_path(
                os.path.sep.join([lib_dir, '..', '..', 'paddle_custom_device'])
            )
            return
    if hasattr(site, 'USER_SITE'):
        lib_dir = os.path.sep.join([site.USER_SITE, 'paddle', 'libs'])
        if os.path.exists(lib_dir):
            _set_paddle_lib_path(lib_dir)
            set_paddle_custom_device_lib_path(
                os.path.sep.join([lib_dir, '..', '..', 'paddle_custom_device'])
            )
总之确实很难打包，各种互相引用，剪不断理还乱，慎打包！

**Comment by Atomadeus** [comment]
在Windows下试了pyinstaller和nuitka，根本没法打包，各种报错，不是模块缺失就是DLL缺失。

**Comment by gl94** [comment]
> 在Windows下试了pyinstaller和nuitka，根本没法打包，各种报错，不是模块缺失就是DLL缺失。

定位到新问题，只要import paddle，pyinsaller就无法打包
https://github.com/PaddlePaddle/Paddle/issues/55750

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。

**Comment by DrLarck** [comment]
Hi, you should use ![PaddlePaddle/fastdeploy](https://github.com/PaddlePaddle/FastDeploy) to distribute with PyInstaller, it works just fine.
