### ISSUE TITLE
关于通用模型的检测训练

### ISSUE THREAD

**Issue by strWuYaoJu** [PaddlePaddle/PaddleOCR#1053]
环境：
CPU      4
RAM     32GB
GPU      v100
显存     16GB
磁盘     100GB

下载好ch_ppocr_server_v1.1_det_train.tar，解压到pretrain_models目录，把自己的训练图片数据放在指定位置后，执行如下指令：
 python tools/train.py -c configs/det/det_r18_vd_db_v1.1.yml -o Global.pretrain_weights=./pretrain_models/ch_ppocr_server_v1.1_det_train/

报错：
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor version 1904018048 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] at (/paddle/paddle/fluid/framework/lod_tensor.cc:287)
  [operator < load > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main()
  File "tools/train.py", line 88, in main
    init_model(config, train_program, exe)
  File "/home/aistudio/PaddleOCR/ppocr/utils/save_load.py", line 124, in init_model
    load_params(exe, program, path)
  File "/home/aistudio/PaddleOCR/ppocr/utils/save_load.py", line 78, in load_params
    state = _load_state(path)
  File "/home/aistudio/PaddleOCR/ppocr/utils/save_load.py", line 56, in _load_state
    state = fluid.io.load_program_state(path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1868, in load_program_state
    "Failed to load model file , please make sure model file is saved with the "
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars

**Comment by MissPenguin** [comment]
pretrain_weights路径要写到文件名（不包含后缀），也就是你用的这个模型要写到best_accurracy哈。
