### ISSUE TITLE
_queue.Empty

### ISSUE THREAD

**Issue by zhangsirya** [PaddlePaddle/PaddleOCR#10557]
请问出现以下错误是什么原因

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 631, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 4706
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 181, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/workspace/zy/PaddleOCR-release-2.6/tools/program.py", line 267, in train
    for idx, batch in enumerate(train_dataloader):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 742, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by UserWangZz** [comment]
请问是windows吗，可以尝试降低num_workers
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
