### ISSUE TITLE
AttributeError: 'paddle.fluid.libpaddle.Tensor' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by wapus** [PaddlePaddle/PaddleOCR#10579]
- 系统环境/System Environment： windows11
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.6  
- 运行指令/Command Code： python tools/train.py -c configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 175, in main
    pre_best_model_dict = load_model(config, model, optimizer,
  File "D:\PaddleOCR-release-2.6\ppocr\utils\save_load.py", line 139, in load_model
    is_float16 = load_pretrained_params(model, pretrained_model)
  File "D:\PaddleOCR-release-2.6\ppocr\utils\save_load.py", line 165, in load_pretrained_params
    if params[k1].dtype == paddle.float16:
AttributeError: 'paddle.fluid.libpaddle.Tensor' object has no attribute 'dtype'

**Comment by wapus** [comment]
最高版本的paddle和最高版本的PaddleOcr竟然在方法上不一致，把dtype改成_dtype,还有shape用法的问题，这些都改完传输的格式又异常了，新手搞不懂了
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 181, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\PaddleOCR-release-2.6\tools\program.py", line 303, in train
    preds = model(images)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1256, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1235, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PaddleOCR-release-2.6\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1256, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1235, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PaddleOCR-release-2.6\ppocr\modeling\backbones\det_resnet_vd.py", line 343, in forward
    y = self.conv1_1(inputs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1256, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1235, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PaddleOCR-release-2.6\ppocr\modeling\backbones\det_resnet_vd.py", line 139, in forward
    y = self._conv(inputs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1256, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\layers.py", line 1235, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\layer\conv.py", line 710, in forward
    out = F.conv._conv_nd(
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\nn\functional\conv.py", line 238, in _conv_nd
    check_variable_and_dtype(
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\data_feeder.py", line 131, in check_variable_and_dtype
    check_type(input, input_name, Variable, op_name, extra_message)
  File "C:\ProgramData\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\data_feeder.py", line 164, in check_type
    raise TypeError(
TypeError: The type of 'x' in conv2d must be <class 'paddle.fluid.framework.Variable'>, but received <class 'paddle.fluid.libpaddle.Tensor'>.

**Comment by UserWangZz** [comment]
可能是paddle的bug

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
