### ISSUE TITLE
Error when export custom model

### ISSUE THREAD

**Issue by hungtrieu07** [PaddlePaddle/PaddleOCR#10621]
I'm training a model for my language (Vietnamese). After training done, i want to export model following the instruction in documentation, but i have an error:

```
W0812 15:55:05.823475 183606 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.7
W0812 15:55:05.824684 183606 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
[2023/08/12 15:55:07] ppocr INFO: load pretrain successful from /content/results/best_accuracy
Traceback (most recent call last):
  File "/content/PaddleOCR/tools/export_model.py", line 289, in <module>
    main()
  File "/content/PaddleOCR/tools/export_model.py", line 284, in main
    export_single_model(
  File "/content/PaddleOCR/tools/export_model.py", line 74, in export_single_model
    shape=[None] + input_shape, dtype="float32"),
TypeError: can only concatenate list (not "NoneType") to list
```

This is my config file:
```
Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /content/results
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img:
  character_dict_path: /content/PaddleOCR/ppocr/utils/dict/vi_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: /content/results/predicts_ppocrv3_latin.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /content/rec
    ext_op_transform_idx: 1
    label_file_list:
    - /content/rec/rec_gt_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 1
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /content/rec
    label_file_list:
    - /content/rec/rec_gt_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 1

```

The command i use to export model is:

```
!python3 tools/export_model.py -c /content/drive/MyDrive/AI/paddle/latin_PP-OCRv3_rec.yml -o Global.pretrained_model=/content/results/best_accuracy  Global.save_inference_dir=/content/results/
```

**Comment by hungtrieu07** [comment]
> try to use version 2.6
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/export_model.py
> 
> ![image](https://user-images.githubusercontent.com/1589422/261642665-e5061fc5-87b7-4529-b290-498a2a25e568.png)

Thank you, now i can training with custom model. After I trained done and make inference model, it return me strange output with character like ắ[ắ[ắ[ắ[ắ[ắ[ắ[Ợ 

This is the command:
```
!python tools/infer/predict_rec.py --use_gpu=True --rec_model_dir="/content/drive/MyDrive/AI/inference_model/rec" --rec_char_dict_path='./ppocr/utils/dict/vi_dict.txt' --image_dir='/content/rec/test/'
```

Some output:
```
[2023/08/22 22:33:31] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_0.jpg:('!^Ì', 0.006254128646105528)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_1.jpg:('F^', 0.006477894727140665)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_10.jpg:('^', 0.005721398629248142)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_11.jpg:('Ằ!Q', 0.0060051605105400085)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_12.jpg:('!^', 0.006111873313784599)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_13.jpg:('!^', 0.0064021083526313305)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_14.jpg:('!Q', 0.005697106011211872)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_15.jpg:('^3', 0.005896078422665596)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_16.jpg:('!^', 0.006787663325667381)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_17.jpg:('ựỀmĐ', 0.005692533683031797)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_18.jpg:('ựmĐ', 0.005696969572454691)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_19.jpg:('!', 0.0061057512648403645)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_2.jpg:('!^', 0.0065368954092264175)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_20.jpg:('!Q', 0.0056608328595757484)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_21.jpg:('!Ợ', 0.005592969711869955)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_22.jpg:('^', 0.005921301431953907)
[2023/08/22 22:33:35] ppocr INFO: Predicts of /content/rec/test/0_crop_23.jpg:('ỗL', 0.005997303873300552)
```

**Comment by hungtrieu07** [comment]
[https://drive.google.com/drive/folders/1vmtr0cLnW25deFcHHfCJ68uV26aNULQm?usp=sharing](url)

I have recogition config file, dictionary file in this link
