### ISSUE TITLE
 (InvalidArgument) Failed to parse program_desc from binary string

### ISSUE THREAD

**Issue by gubinjie** [PaddlePaddle/PaddleOCR#10638]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
 paddleocr 2.6

Adopt a linked template:
[https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/README_CN.md](url)

The command executed:
`1、python -m paddle_serving_client.convert --dirname  D://JetBrains//PycharmProjects//PaddleOCR//deploy//pdserving//ch_PP-OCRv3_det_infer// --model_filename D://Je
tBrains//PycharmProjects//PaddleOCR//deploy//pdserving//ch_PP-OCRv3_det_infer//model.pdiparams   --params_filename  D://JetBrains//PycharmProjects//PaddleOCR//deploy//pdserving//ch_PP-OCRv3_det_infer//model.pdparams --serving_server
 D://JetBrains//PycharmProjects//PaddleOCR//deploy//pdserving//ppocr_det_v3_serving// --serving_client D://JetBrains//PycharmProjects//PaddleOCR//deploy//pdserving//ppocr_det_v3_client//`

`2、 python -m paddle_serving_client.convert --dirname ./ch_PP-OCRv3_det_infer/ --model_filename D:\JetBrains\PycharmProjects\PaddleOCR\deploy\pdserving\ch_PP-OCRv3_
det_infer\model.pdiparams   --params_filename D:\JetBrains\PycharmProjects\PaddleOCR\deploy\pdserving\ch_PP-OCRv3_det_infer\model.pdparams --serving_server ./ppocr_det_v3_serving/ --serving_client ./ppocr_det_v3_client/`

Exception information：
`Traceback (most recent call last):
  File "D:\anaconda3\envs\PaddleOCR\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\PaddleOCR\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle_serving_client\convert.py", line 87, in <module>
    fetch_alias_names=args.fetch_alias_names)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle_serving_client\io\__init__.py", line 334, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\framework.py", line 473, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\io.py", line 478, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\framework.py", line 6266, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at ..\paddle\fluid\framework\program_desc.cc:150)
`
How should this be solved?TH

**Comment by UserWangZz** [comment]
you can try fastdeploy to deploy the ocr server.
[FastDeploy](https://github.com/PaddlePaddle/FastDeploy)
