### ISSUE TITLE
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function.

### ISSUE THREAD

**Issue by chuwang9964** [PaddlePaddle/PaddleOCR#10644]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10,NVIDIA GTX 1050ti , CUDA 12.0 ,cuDNN 8.9.1
- 版本号/Version：Paddle：paddlepaddle-gpu-2.5.1  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：  python tools/train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\tools\train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\tools\train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\tools\program.py", line 288, in train
    preds = model(images, data=batch[1:])
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\venv\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 100, in forward
    x = self.head(x, targets=data)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\venv\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\ppocr\modeling\heads\rec_multi_head.py", line 69, in forward
    sar_out = self.sar_head(x, targets[1:])
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\venv\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\ppocr\modeling\heads\rec_sar_head.py", line 395, in forward
    holistic_feat = self.encoder(feat, targets)  # bsz c
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\venv\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\ppocr\modeling\heads\rec_sar_head.py", line 105, in forward
    valid_hf.append(holistic_feat[i, valid_step, :])
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\venv\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 743, in __getitem__
    return _getitem_impl_(self, item)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\PaddleOCR\venv\lib\site-packages\paddle\fluid\variable_index.py", line 561, in _getitem_impl_
    out = paddle._C_ops.slice(
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function.
  [Hint: Expected valid() == true, but received valid():0 != true:1.] (at ..\paddle\phi\core\dense_tensor.cc:122)

**Comment by jiangbossB** [comment]
你好解决了吗

**Comment by piperino11** [comment]
did you solve this ?

**Comment by SwordyLee** [comment]
请问解决了吗

**Comment by UserWangZz** [comment]
可能是数据中存在无法解析的字符，可能是\n \t等字符
