### ISSUE TITLE
PGNet Value Error

### ISSUE THREAD

**Issue by AbdulDD** [PaddlePaddle/PaddleOCR#10663]
System Environment：google colab
command: PGNet training command
Error Message:
Traceback (most recent call last):
  File "/content/PaddleOCR/tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "/content/PaddleOCR/tools/train.py", line 198, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/content/PaddleOCR/tools/program.py", line 334, in train
    post_result = post_process_class(preds, batch[1])
  File "/content/PaddleOCR/ppocr/postprocess/pg_postprocess.py", line 60, in __call__
    data = post.pg_postprocess_fast()
  File "/content/PaddleOCR/ppocr/utils/e2e_utils/pgnet_pp_utils.py", line 62, in pg_postprocess_fast
    src_h, src_w, ratio_h, ratio_w = self.shape_list[0]
ValueError: not enough values to unpack (expected 4, got 1)

Note: I have already checked dataset format which is correct.

**Comment by UserWangZz** [comment]
config file set error？

**Comment by AbdulDD** [comment]
Yes you can directly make changes in config file. such that you do not have to use "-o" or "-c" and then it works fine.
