### ISSUE TITLE
CUDA driver and runtime could not be initialized with python celery environment

### ISSUE THREAD

**Issue by sunxianliang** [PaddlePaddle/PaddleOCR#1068]
直接执行
```
python3 tools/infer/predict_system.py   --image_dir="./doc/imgs/11.jpeg"   --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"    --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/"   --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/"   --use_angle_cls=True   --use_space_char=True
```
命令是正常的, 但是放到celery work中执行报如下错误
```
[2020-10-30 18:48:03,199: ERROR/ForkPoolWorker-2] Traceback (most recent call last):
  File "/home/paddle/paddle-ocr/PaddleOCR-develop/celery_app/ocr_task.py", line 60, in ocr
    dt_boxes, rec_res = ocr.text_system(img)
  File "/home/paddle/venv/lib/python3.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paddle/paddle-ocr/PaddleOCR-develop/celery_app/ocr_task.py", line 42, in text_system
    self._text_system = TextSystem(args)
  File "/home/paddle/paddle-ocr/PaddleOCR-develop/tools/infer/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/paddle/paddle-ocr/PaddleOCR-develop/tools/infer/predict_det.py", line 80, in __init__
    utility.create_predictor(args, mode="det")
  File "/home/paddle/paddle-ocr/PaddleOCR-develop/tools/infer/utility.py", line 144, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisConfig::fraction_of_gpu_memory_for_pool() const
3   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
4   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:219)
```
环境如下:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

libcudnn.so.7.6.5

**Comment by LDOUBLEV** [comment]
celery work 的执行环境是不是和你命令执行是同一个cuda环境，命令执行时，设置 --use_gpu=True试试

**Comment by sunxianliang** [comment]
> celery work 的执行环境是不是和你命令执行是同一个cuda环境，命令执行时，设置 --use_gpu=True试试
见[/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py](/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py) 默认是True, 我为了这事特意重装了一次系统. 从deploy/模块中看, 意思是GPU模式不支持单卡多进程或者多线程吗?

**Comment by ByronGe** [comment]
hi，如何支持多进程这个问题你解决了吗？

**Comment by admin0528** [comment]
> > celery work的执行环境是不是和你命令执行是同一个cuda环境，命令执行时，设置--use_gpu = True尝试
> 
> 见/ [PaddlePaddle / PaddleOCR / blob / develop / tools / infer / utility](/PaddlePaddle/PaddleOCR/blob/develop/tools/infer/utility.py)。从deploy /模块中看，意思是GPU模式不支持单卡多进程或者多线程吗？

你好，请问这个问题解决了吗？

**Comment by f4z3k4s** [comment]
I am experiencing exactly the same with celery. Works perfectly without celery, but whenever I run my script with celery, I get:
```
api_1              | /app/node_modules/celery-node/dist/app/result.js:15
api_1              |     const error = new Error(message);
api_1              |                   ^
api_1              | 
api_1              | Error: FAILURE
api_1              |     at createError (/app/node_modules/celery-node/dist/app/result.js:15:19)
api_1              |     at /app/node_modules/celery-node/dist/app/result.js:77:23
api_1              |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
api_1              |     at async createTextRecognitionTaskMock (/app/dist/mocks/create-text-recognition-task.mock.js:18:20) {
api_1              |   exc_type: 'OSError',
api_1              |   exc_message: [
api_1              |     '(External) CUDA error(3), initialization error. \n' +
api_1              |       "  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:283)\n"
api_1              |   ],
api_1              |   exc_module: 'builtins'
api_1              | }
ocr-backend-prod_api_1 exited with code 1
```

Any updates on this possibly?
