### ISSUE TITLE
ValueError: (InvalidArgument) Currently, Tensor.__indices__()

### ISSUE THREAD

**Issue by Rishi-NF** [PaddlePaddle/PaddleOCR#10728]
[2023/08/24 13:00:26] ppocr INFO: resume from ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy
Traceback (most recent call last):
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/./tools/infer_kie_token_ser_re.py", line 218, in <module>
    result = ser_re_engine(data)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/./tools/infer_kie_token_ser_re.py", line 151, in __call__
    preds = self.model(re_input)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
        ^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
    x = self.model(
        ^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
    relations, entities = self.build_relation(relations, entities)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1185, in build_relation
    negative_relations = all_possible_relations[negative_mask]
                         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/rishisharath/Desktop/PaddleOCR/PaddleOCR/venv/lib/python3.11/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 747, in __getitem__
    return self._getitem_index_not_tensor(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received bool in 1th slice item (at /Users/paddle/xly/workspace/3641f345-7c6e-4164-b874-0eaae86a0f20/Paddle/paddle/fluid/pybind/slice_utils.h:298)




What do i have to do to fix this???

**Comment by rickon43** [comment]
If we have to fix this error, they are two options may be file is not saved in that particular location why because if the file documents and other files u should create in the one place . another option before the line of this (result = ser_re_engine(data))
u need to check the code that what is the logic that u mentioned in it.

**Comment by GaganaMD** [comment]
Hey! I'd like to be assigned to this issue.

**Comment by rickon43** [comment]
yes ,
it is

**Comment by SkyScraperTwc** [comment]
+1

**Comment by Ashwariya2310** [comment]
Hi,

You need to install paddlenlp==2.5.2
If you get probut issue, downgrade the protobuf
