### ISSUE TITLE
运行SER + RE模型串联报错

### ISSUE THREAD

**Issue by VignetteApril** [PaddlePaddle/PaddleOCR#10766]
# 系统环境
Ubuntu20.04
Cuda 11.8
Pytorch 2.0.0
# paddle版本
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.9
paddlefsl                      1.1.0
paddlenlp                      2.6.0
paddleocr                      2.7.0.2
paddlepaddle-gpu               2.5.1

# 运行指令
```shell
# SER + RE模型串联
python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./train_data/XFUND/zh_val/image/zh_val_42.jpg \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
```

# 完整报错
[2023/08/28 18:04:39] ppocr INFO: resume from ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy
Corrupt JPEG data: premature end of data segment
Traceback (most recent call last):
  File "./tools/infer_kie_token_ser_re.py", line 217, in <module>
    result = ser_re_engine(data)
  File "./tools/infer_kie_token_ser_re.py", line 151, in __call__
    preds = self.model(re_input)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
    x = self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/root/miniconda3/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1185, in build_relation
    negative_relations = all_possible_relations[negative_mask]
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 747, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received bool in 1th slice item (at ../paddle/fluid/pybind/slice_utils.h:298)

**Comment by CassieFeng** [comment]
**+10086**
# 环境
centos7 cuda11.6 cudnn8.4.0(官方推荐的对应版本)，单机多卡，安装了对应的nccl，执行paddle.utils.run_check()没问题

paddle相关的包本本：
paddle-bfloat         0.1.7
paddle2onnx           1.0.9
paddlefsl             1.1.0
paddlenlp             2.6.0
paddleocr             2.7.0.2
paddlepaddle-gpu      2.5.1.post116

# 仅预测SER模型部分没问题
python3 tools/infer_kie_token_ser.py \
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./train_data/XFUND/zh_val/val.json \
  Global.infer_mode=False

# SER + RE模型串联报错
python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./train_data/XFUND/zh_val/val.json \
  Global.infer_mode=False \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy

# 完整log日志

[2023/09/07 02:02:26] ppocr INFO: ********** re config **********
[2023/09/07 02:02:26] ppocr INFO: Architecture : 
[2023/09/07 02:02:26] ppocr INFO:     Backbone : 
[2023/09/07 02:02:26] ppocr INFO:         checkpoints : ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy
[2023/09/07 02:02:26] ppocr INFO:         mode : vi
[2023/09/07 02:02:26] ppocr INFO:         name : LayoutXLMForRe
[2023/09/07 02:02:26] ppocr INFO:         pretrained : True
[2023/09/07 02:02:26] ppocr INFO:     Transform : None
[2023/09/07 02:02:26] ppocr INFO:     algorithm : LayoutXLM
[2023/09/07 02:02:26] ppocr INFO:     model_type : kie
[2023/09/07 02:02:26] ppocr INFO: Eval : 
[2023/09/07 02:02:26] ppocr INFO:     dataset : 
[2023/09/07 02:02:26] ppocr INFO:         data_dir : train_data/XFUND/zh_val/image
[2023/09/07 02:02:26] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_val/val.json']
[2023/09/07 02:02:26] ppocr INFO:         name : SimpleDataSet
[2023/09/07 02:02:26] ppocr INFO:         transforms : 
[2023/09/07 02:02:26] ppocr INFO:             DecodeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 channel_first : False
[2023/09/07 02:02:26] ppocr INFO:                 img_mode : RGB
[2023/09/07 02:02:26] ppocr INFO:             VQATokenLabelEncode : 
[2023/09/07 02:02:26] ppocr INFO:                 algorithm : LayoutXLM
[2023/09/07 02:02:26] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/07 02:02:26] ppocr INFO:                 contains_re : True
[2023/09/07 02:02:26] ppocr INFO:                 order_method : tb-yx
[2023/09/07 02:02:26] ppocr INFO:                 use_textline_bbox_info : True
[2023/09/07 02:02:26] ppocr INFO:             VQATokenPad : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:                 return_attention_mask : True
[2023/09/07 02:02:26] ppocr INFO:             VQAReTokenRelation : None
[2023/09/07 02:02:26] ppocr INFO:             VQAReTokenChunk : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:             TensorizeEntitiesRelations : None
[2023/09/07 02:02:26] ppocr INFO:             Resize : 
[2023/09/07 02:02:26] ppocr INFO:                 size : [224, 224]
[2023/09/07 02:02:26] ppocr INFO:             NormalizeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2023/09/07 02:02:26] ppocr INFO:                 order : hwc
[2023/09/07 02:02:26] ppocr INFO:                 scale : 1
[2023/09/07 02:02:26] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2023/09/07 02:02:26] ppocr INFO:             ToCHWImage : None
[2023/09/07 02:02:26] ppocr INFO:             KeepKeys : 
[2023/09/07 02:02:26] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'entities', 'relations']
[2023/09/07 02:02:26] ppocr INFO:     loader : 
[2023/09/07 02:02:26] ppocr INFO:         batch_size_per_card : 8
[2023/09/07 02:02:26] ppocr INFO:         drop_last : False
[2023/09/07 02:02:26] ppocr INFO:         num_workers : 8
[2023/09/07 02:02:26] ppocr INFO:         shuffle : False
[2023/09/07 02:02:26] ppocr INFO: Global : 
[2023/09/07 02:02:26] ppocr INFO:     cal_metric_during_train : False
[2023/09/07 02:02:26] ppocr INFO:     epoch_num : 130
[2023/09/07 02:02:26] ppocr INFO:     eval_batch_step : [0, 19]
[2023/09/07 02:02:26] ppocr INFO:     infer_img : ./train_data/XFUND/zh_val/val.json
[2023/09/07 02:02:26] ppocr INFO:     infer_mode : False
[2023/09/07 02:02:26] ppocr INFO:     kie_det_model_dir : None
[2023/09/07 02:02:26] ppocr INFO:     kie_rec_model_dir : None
[2023/09/07 02:02:26] ppocr INFO:     log_smooth_window : 10
[2023/09/07 02:02:26] ppocr INFO:     print_batch_step : 10
[2023/09/07 02:02:26] ppocr INFO:     save_epoch_step : 2000
[2023/09/07 02:02:26] ppocr INFO:     save_inference_dir : None
[2023/09/07 02:02:26] ppocr INFO:     save_model_dir : ./output/re_vi_layoutxlm_xfund_zh
[2023/09/07 02:02:26] ppocr INFO:     save_res_path : ./output/re/xfund_zh/with_gt
[2023/09/07 02:02:26] ppocr INFO:     seed : 2022
[2023/09/07 02:02:26] ppocr INFO:     use_gpu : True
[2023/09/07 02:02:26] ppocr INFO:     use_visualdl : False
[2023/09/07 02:02:26] ppocr INFO: Loss : 
[2023/09/07 02:02:26] ppocr INFO:     key : loss
[2023/09/07 02:02:26] ppocr INFO:     name : LossFromOutput
[2023/09/07 02:02:26] ppocr INFO:     reduction : mean
[2023/09/07 02:02:26] ppocr INFO: Metric : 
[2023/09/07 02:02:26] ppocr INFO:     main_indicator : hmean
[2023/09/07 02:02:26] ppocr INFO:     name : VQAReTokenMetric
[2023/09/07 02:02:26] ppocr INFO: Optimizer : 
[2023/09/07 02:02:26] ppocr INFO:     beta1 : 0.9
[2023/09/07 02:02:26] ppocr INFO:     beta2 : 0.999
[2023/09/07 02:02:26] ppocr INFO:     clip_norm : 10
[2023/09/07 02:02:26] ppocr INFO:     lr : 
[2023/09/07 02:02:26] ppocr INFO:         learning_rate : 5e-05
[2023/09/07 02:02:26] ppocr INFO:         warmup_epoch : 10
[2023/09/07 02:02:26] ppocr INFO:     name : AdamW
[2023/09/07 02:02:26] ppocr INFO:     regularizer : 
[2023/09/07 02:02:26] ppocr INFO:         factor : 0.0
[2023/09/07 02:02:26] ppocr INFO:         name : L2
[2023/09/07 02:02:26] ppocr INFO: PostProcess : 
[2023/09/07 02:02:26] ppocr INFO:     name : VQAReTokenLayoutLMPostProcess
[2023/09/07 02:02:26] ppocr INFO: Train : 
[2023/09/07 02:02:26] ppocr INFO:     dataset : 
[2023/09/07 02:02:26] ppocr INFO:         data_dir : train_data/XFUND/zh_train/image
[2023/09/07 02:02:26] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_train/train.json']
[2023/09/07 02:02:26] ppocr INFO:         name : SimpleDataSet
[2023/09/07 02:02:26] ppocr INFO:         ratio_list : [1.0]
[2023/09/07 02:02:26] ppocr INFO:         transforms : 
[2023/09/07 02:02:26] ppocr INFO:             DecodeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 channel_first : False
[2023/09/07 02:02:26] ppocr INFO:                 img_mode : RGB
[2023/09/07 02:02:26] ppocr INFO:             VQATokenLabelEncode : 
[2023/09/07 02:02:26] ppocr INFO:                 algorithm : LayoutXLM
[2023/09/07 02:02:26] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/07 02:02:26] ppocr INFO:                 contains_re : True
[2023/09/07 02:02:26] ppocr INFO:                 order_method : tb-yx
[2023/09/07 02:02:26] ppocr INFO:                 use_textline_bbox_info : True
[2023/09/07 02:02:26] ppocr INFO:             VQATokenPad : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:                 return_attention_mask : True
[2023/09/07 02:02:26] ppocr INFO:             VQAReTokenRelation : None
[2023/09/07 02:02:26] ppocr INFO:             VQAReTokenChunk : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:             TensorizeEntitiesRelations : None
[2023/09/07 02:02:26] ppocr INFO:             Resize : 
[2023/09/07 02:02:26] ppocr INFO:                 size : [224, 224]
[2023/09/07 02:02:26] ppocr INFO:             NormalizeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2023/09/07 02:02:26] ppocr INFO:                 order : hwc
[2023/09/07 02:02:26] ppocr INFO:                 scale : 1
[2023/09/07 02:02:26] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2023/09/07 02:02:26] ppocr INFO:             ToCHWImage : None
[2023/09/07 02:02:26] ppocr INFO:             KeepKeys : 
[2023/09/07 02:02:26] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'entities', 'relations']
[2023/09/07 02:02:26] ppocr INFO:     loader : 
[2023/09/07 02:02:26] ppocr INFO:         batch_size_per_card : 2
[2023/09/07 02:02:26] ppocr INFO:         drop_last : False
[2023/09/07 02:02:26] ppocr INFO:         num_workers : 4
[2023/09/07 02:02:26] ppocr INFO:         shuffle : True
[2023/09/07 02:02:26] ppocr INFO: 

[2023/09/07 02:02:26] ppocr INFO: ********** ser config **********
[2023/09/07 02:02:26] ppocr INFO: Architecture : 
[2023/09/07 02:02:26] ppocr INFO:     Backbone : 
[2023/09/07 02:02:26] ppocr INFO:         checkpoints : ./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
[2023/09/07 02:02:26] ppocr INFO:         mode : vi
[2023/09/07 02:02:26] ppocr INFO:         name : LayoutXLMForSer
[2023/09/07 02:02:26] ppocr INFO:         num_classes : 7
[2023/09/07 02:02:26] ppocr INFO:         pretrained : True
[2023/09/07 02:02:26] ppocr INFO:     Transform : None
[2023/09/07 02:02:26] ppocr INFO:     algorithm : LayoutXLM
[2023/09/07 02:02:26] ppocr INFO:     model_type : kie
[2023/09/07 02:02:26] ppocr INFO: Eval : 
[2023/09/07 02:02:26] ppocr INFO:     dataset : 
[2023/09/07 02:02:26] ppocr INFO:         data_dir : train_data/XFUND/zh_val/image
[2023/09/07 02:02:26] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_val/val.json']
[2023/09/07 02:02:26] ppocr INFO:         name : SimpleDataSet
[2023/09/07 02:02:26] ppocr INFO:         transforms : 
[2023/09/07 02:02:26] ppocr INFO:             DecodeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 channel_first : False
[2023/09/07 02:02:26] ppocr INFO:                 img_mode : RGB
[2023/09/07 02:02:26] ppocr INFO:             VQATokenLabelEncode : 
[2023/09/07 02:02:26] ppocr INFO:                 algorithm : LayoutXLM
[2023/09/07 02:02:26] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/07 02:02:26] ppocr INFO:                 contains_re : False
[2023/09/07 02:02:26] ppocr INFO:                 order_method : tb-yx
[2023/09/07 02:02:26] ppocr INFO:                 use_textline_bbox_info : True
[2023/09/07 02:02:26] ppocr INFO:             VQATokenPad : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:                 return_attention_mask : True
[2023/09/07 02:02:26] ppocr INFO:             VQASerTokenChunk : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:             Resize : 
[2023/09/07 02:02:26] ppocr INFO:                 size : [224, 224]
[2023/09/07 02:02:26] ppocr INFO:             NormalizeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2023/09/07 02:02:26] ppocr INFO:                 order : hwc
[2023/09/07 02:02:26] ppocr INFO:                 scale : 1
[2023/09/07 02:02:26] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2023/09/07 02:02:26] ppocr INFO:             ToCHWImage : None
[2023/09/07 02:02:26] ppocr INFO:             KeepKeys : 
[2023/09/07 02:02:26] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2023/09/07 02:02:26] ppocr INFO:     loader : 
[2023/09/07 02:02:26] ppocr INFO:         batch_size_per_card : 8
[2023/09/07 02:02:26] ppocr INFO:         drop_last : False
[2023/09/07 02:02:26] ppocr INFO:         num_workers : 4
[2023/09/07 02:02:26] ppocr INFO:         shuffle : False
[2023/09/07 02:02:26] ppocr INFO: Global : 
[2023/09/07 02:02:26] ppocr INFO:     amp_custom_white_list : ['scale', 'concat', 'elementwise_add']
[2023/09/07 02:02:26] ppocr INFO:     cal_metric_during_train : False
[2023/09/07 02:02:26] ppocr INFO:     d2s_train_image_shape : [3, 224, 224]
[2023/09/07 02:02:26] ppocr INFO:     epoch_num : 200
[2023/09/07 02:02:26] ppocr INFO:     eval_batch_step : [0, 19]
[2023/09/07 02:02:26] ppocr INFO:     infer_img : ppstructure/docs/kie/input/zh_val_42.jpg
[2023/09/07 02:02:26] ppocr INFO:     kie_det_model_dir : None
[2023/09/07 02:02:26] ppocr INFO:     kie_rec_model_dir : None
[2023/09/07 02:02:26] ppocr INFO:     log_smooth_window : 10
[2023/09/07 02:02:26] ppocr INFO:     print_batch_step : 10
[2023/09/07 02:02:26] ppocr INFO:     save_epoch_step : 2000
[2023/09/07 02:02:26] ppocr INFO:     save_inference_dir : None
[2023/09/07 02:02:26] ppocr INFO:     save_model_dir : ./output/ser_vi_layoutxlm_xfund_zh
[2023/09/07 02:02:26] ppocr INFO:     save_res_path : ./output/ser/xfund_zh/res
[2023/09/07 02:02:26] ppocr INFO:     seed : 2022
[2023/09/07 02:02:26] ppocr INFO:     use_gpu : True
[2023/09/07 02:02:26] ppocr INFO:     use_visualdl : False
[2023/09/07 02:02:26] ppocr INFO: Loss : 
[2023/09/07 02:02:26] ppocr INFO:     key : backbone_out
[2023/09/07 02:02:26] ppocr INFO:     name : VQASerTokenLayoutLMLoss
[2023/09/07 02:02:26] ppocr INFO:     num_classes : 7
[2023/09/07 02:02:26] ppocr INFO: Metric : 
[2023/09/07 02:02:26] ppocr INFO:     main_indicator : hmean
[2023/09/07 02:02:26] ppocr INFO:     name : VQASerTokenMetric
[2023/09/07 02:02:26] ppocr INFO: Optimizer : 
[2023/09/07 02:02:26] ppocr INFO:     beta1 : 0.9
[2023/09/07 02:02:26] ppocr INFO:     beta2 : 0.999
[2023/09/07 02:02:26] ppocr INFO:     lr : 
[2023/09/07 02:02:26] ppocr INFO:         epochs : 200
[2023/09/07 02:02:26] ppocr INFO:         learning_rate : 5e-05
[2023/09/07 02:02:26] ppocr INFO:         name : Linear
[2023/09/07 02:02:26] ppocr INFO:         warmup_epoch : 2
[2023/09/07 02:02:26] ppocr INFO:     name : AdamW
[2023/09/07 02:02:26] ppocr INFO:     regularizer : 
[2023/09/07 02:02:26] ppocr INFO:         factor : 0.0
[2023/09/07 02:02:26] ppocr INFO:         name : L2
[2023/09/07 02:02:26] ppocr INFO: PostProcess : 
[2023/09/07 02:02:26] ppocr INFO:     class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/07 02:02:26] ppocr INFO:     name : VQASerTokenLayoutLMPostProcess
[2023/09/07 02:02:26] ppocr INFO: Train : 
[2023/09/07 02:02:26] ppocr INFO:     dataset : 
[2023/09/07 02:02:26] ppocr INFO:         data_dir : train_data/XFUND/zh_train/image
[2023/09/07 02:02:26] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_train/train.json']
[2023/09/07 02:02:26] ppocr INFO:         name : SimpleDataSet
[2023/09/07 02:02:26] ppocr INFO:         ratio_list : [1.0]
[2023/09/07 02:02:26] ppocr INFO:         transforms : 
[2023/09/07 02:02:26] ppocr INFO:             DecodeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 channel_first : False
[2023/09/07 02:02:26] ppocr INFO:                 img_mode : RGB
[2023/09/07 02:02:26] ppocr INFO:             VQATokenLabelEncode : 
[2023/09/07 02:02:26] ppocr INFO:                 algorithm : LayoutXLM
[2023/09/07 02:02:26] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/07 02:02:26] ppocr INFO:                 contains_re : False
[2023/09/07 02:02:26] ppocr INFO:                 order_method : tb-yx
[2023/09/07 02:02:26] ppocr INFO:                 use_textline_bbox_info : True
[2023/09/07 02:02:26] ppocr INFO:             VQATokenPad : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:                 return_attention_mask : True
[2023/09/07 02:02:26] ppocr INFO:             VQASerTokenChunk : 
[2023/09/07 02:02:26] ppocr INFO:                 max_seq_len : 512
[2023/09/07 02:02:26] ppocr INFO:             Resize : 
[2023/09/07 02:02:26] ppocr INFO:                 size : [224, 224]
[2023/09/07 02:02:26] ppocr INFO:             NormalizeImage : 
[2023/09/07 02:02:26] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2023/09/07 02:02:26] ppocr INFO:                 order : hwc
[2023/09/07 02:02:26] ppocr INFO:                 scale : 1
[2023/09/07 02:02:26] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2023/09/07 02:02:26] ppocr INFO:             ToCHWImage : None
[2023/09/07 02:02:26] ppocr INFO:             KeepKeys : 
[2023/09/07 02:02:26] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2023/09/07 02:02:26] ppocr INFO:     loader : 
[2023/09/07 02:02:26] ppocr INFO:         batch_size_per_card : 8
[2023/09/07 02:02:26] ppocr INFO:         drop_last : False
[2023/09/07 02:02:26] ppocr INFO:         num_workers : 4
[2023/09/07 02:02:26] ppocr INFO:         shuffle : True
[2023/09/07 02:02:26] ppocr INFO: train with paddle 2.5.1 and device Place(gpu:0)
[2023-09-07 02:02:28,446] [    INFO] - Loading configuration file ./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy/config.json
[2023-09-07 02:02:28,447] [    INFO] - Loading weights file ./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy/model_state.pdparams
[2023-09-07 02:02:29,151] [    INFO] - Loaded weights file from disk, setting weights to model.
W0907 02:02:29.155144 53488 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.0, Runtime API Version: 11.6
W0907 02:02:29.161136 53488 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
[2023-09-07 02:02:32,054] [    INFO] - All model checkpoint weights were used when initializing LayoutXLMForTokenClassification.

[2023-09-07 02:02:32,054] [    INFO] - All the weights of LayoutXLMForTokenClassification were initialized from the model checkpoint at ./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LayoutXLMForTokenClassification for predictions without further training.
[2023/09/07 02:02:32] ppocr INFO: resume from ./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
[2023-09-07 02:02:34,870] [    INFO] - Already cached /root/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2023-09-07 02:02:35,331] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2023-09-07 02:02:35,331] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2023-09-07 02:02:35,333] [    INFO] - Loading configuration file ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy/config.json
[2023-09-07 02:02:35,333] [    INFO] - Loading weights file ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy/model_state.pdparams
[2023-09-07 02:02:35,908] [    INFO] - Loaded weights file from disk, setting weights to model.
[2023-09-07 02:02:36,655] [    INFO] - All model checkpoint weights were used when initializing LayoutXLMForRelationExtraction.

[2023-09-07 02:02:36,655] [    INFO] - All the weights of LayoutXLMForRelationExtraction were initialized from the model checkpoint at ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LayoutXLMForRelationExtraction for predictions without further training.
[2023/09/07 02:02:36] ppocr INFO: resume from ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy
Traceback (most recent call last):
  File "/home/fengqianqian/PaddleOCR/./tools/infer_kie_token_ser_re.py", line 217, in <module>
    result = ser_re_engine(data)
  File "/home/fengqianqian/PaddleOCR/./tools/infer_kie_token_ser_re.py", line 151, in __call__
    preds = self.model(re_input)
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/fengqianqian/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/fengqianqian/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
    x = self.model(
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1185, in build_relation
    negative_relations = all_possible_relations[negative_mask]
  File "/root/miniconda3/envs/fqq-paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 747, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received bool in 1th slice item (at ../paddle/fluid/pybind/slice_utils.h:298)

**Comment by CassieFeng** [comment]
+我在aistudio v100的环境下跑通了，没问题，版本也是参考对应的环境

cat /usr/include/cudnn_version.h | grep CUDNN_MAJOR -A 2 我自己服务器和aistudio的都是8.4.0

但是刚才用paddle.version.cudnn() 看了一下cudnn环境，我的是8.4.0，aistudio的是8.2.1，不知道是否和这个有关系，这个aistudio对应的和官网给的不一致呢

**Comment by CassieFeng** [comment]
切换为cuda11.2 cudnn8.2.1 还是不行😭

**Comment by CassieFeng** [comment]
这个问题应该是环境或者某一个包的版本问题，我把cuda和cudnn版本改为和aistudio调通的环境一致，其他包版本也生成requriements后copy到自己服务器上安装后，没问题了

**Comment by VignetteApril** [comment]
> 这个问题应该是环境或者某一个包的版本问题，我把cuda和cudnn版本改为和aistudio调通的环境一致，其他包版本也生成requriements后copy到自己服务器上安装后，没问题了

能否发下你的环境中的依赖版本？感谢
