### ISSUE TITLE
Where can I find the file '../train_data/XFUND/class_list_xfun.txt' when running KIE inference?

### ISSUE THREAD

**Issue by vandesa003** [PaddlePaddle/PaddleOCR#10807]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：MacOS M1
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.7.0.2 问题相关组件/Related components：padleocr.ppstructure
- 运行指令/Command Code：
```
python3 kie/predict_kie_token_ser_re.py \
  --kie_algorithm=LayoutXLM \
  --re_model_dir=../inference/re_vi_layoutxlm_xfund_infer \
  --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer \
  --use_visual_backbone=False \
  --image_dir=./docs/kie/input/zh_val_42.jpg \
  --ser_dict_path=../train_data/XFUND/class_list_xfun.txt \
  --vis_font_path=../doc/fonts/simfang.ttf \
  --ocr_order_method="tb-yx"
```
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "/Users/vandesalee/Desktop/code_repo/id_ocr_ext/PaddleOCR/ppstructure/kie/predict_kie_token_ser.py", line 177, in <module>
    main(parse_args())
  File "/Users/vandesalee/Desktop/code_repo/id_ocr_ext/PaddleOCR/ppstructure/kie/predict_kie_token_ser.py", line 134, in main
    ser_predictor = SerPredictor(args)
  File "/Users/vandesalee/Desktop/code_repo/id_ocr_ext/PaddleOCR/ppstructure/kie/predict_kie_token_ser.py", line 95, in __init__
    self.preprocess_op = create_operators(pre_process_list,
  File "/Users/vandesalee/Desktop/code_repo/id_ocr_ext/PaddleOCR/ppocr/data/imaug/__init__.py", line 78, in create_operators
    op = eval(op_name)(**param)
  File "/Users/vandesalee/Desktop/code_repo/id_ocr_ext/PaddleOCR/ppocr/data/imaug/label_ops.py", line 1028, in __init__
    self.label2id_map, id2label_map = load_vqa_bio_label_maps(class_path)
  File "/Users/vandesalee/Desktop/code_repo/id_ocr_ext/PaddleOCR/ppocr/utils/utility.py", line 131, in load_vqa_bio_label_maps
    with open(label_map_path, "r", encoding='utf-8') as fin:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data/XFUND/class_list_xfun.txt'
```

**Comment by vandesa003** [comment]
Found it in `ppocr/utils/dict/kie_dict/xfund_class_list.txt`
will close the issue as it resolved.

**Comment by Hemilibeatriz** [comment]
I have the same issue:

```
Traceback (most recent call last):
  File "/content/PaddleOCR/tools/infer_kie_token_ser_re.py", line 189, in <module>
    ser_re_engine = SerRePredictor(config, ser_config)
  File "/content/PaddleOCR/tools/infer_kie_token_ser_re.py", line 130, in __init__
    self.ser_engine = SerPredictor(ser_config)
  File "/content/PaddleOCR/tools/infer_kie_token_ser.py", line 64, in __init__
    self.post_process_class = build_post_process(config['PostProcess'],
  File "/content/PaddleOCR/ppocr/postprocess/__init__.py", line 71, in build_post_process
    module_class = eval(module_name)(**config)
  File "/content/PaddleOCR/ppocr/postprocess/vqa_token_ser_layoutlm_postprocess.py", line 24, in __init__
    label2id_map, self.id2label_map = load_vqa_bio_label_maps(class_path)
  File "/content/PaddleOCR/ppocr/utils/utility.py", line 132, in load_vqa_bio_label_maps
    with open(label_map_path, "r", encoding='utf-8') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'train_data/XFUND/class_list_xfun.txt'
```

When can i found the _class_path_ variable, to change her path value?
