### ISSUE TITLE
PPOCRLabel.py启动不了，报错InvalidArgumentError: The 'shape' in ReshapeOp is invalid.

### ISSUE THREAD

**Issue by Yanic0420** [PaddlePaddle/PaddleOCR#10817]
- 系统环境/System Environment：Window11
- 版本号/Version：Python=3.8,Paddle：2.5.0  PaddleOCR：2.7.0.0 问题相关组件/Related components：
- 运行指令/Command Code：python PPOCRLabel.py --lang ch --kie True
- 完整报错/Complete Error Message：
 ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2840, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
  File "PPOCRLabel.py", line 112, in __init__
    result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
  File "D:\ToolsStudy\Anacon3\envs\pocr\lib\site-packages\paddleocr\paddleocr.py", line 735, in __call__
    res, _ = super().__call__(
  File "E:\DataStudy\Program\new\PaddleOCR\PPOCRLabel\..\ppstructure\predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
  File "E:\DataStudy\Program\new\PaddleOCR\PPOCRLabel\..\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "E:\DataStudy\Program\new\PaddleOCR\PPOCRLabel\..\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "E:\DataStudy\Program\new\PaddleOCR\PPOCRLabel\..\ppstructure\table\predict_structure.py", line 134, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 269, in <module>
      main()
    File "tools/export_model.py", line 261, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 179, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 649, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 928, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in concrete_program_specify_input_spec
      is_train=self._is_train_mode())
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 485, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 955, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 944, in _build_once
      **cache_key.kwargs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 888, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward
      if self.use_head:
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 324, in convert_ifelse
      return_name_ids)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 380, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 101, in forward
      x = self.head(x, targets=data)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1014, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 993, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/heads/rec_multihead_v4_stu.py", line 312, in forward
      ctc_encoder = self.ctc_encoder(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1014, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 993, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/heads/rec_multihead_v4_stu.py", line 249, in forward
      if self.encoder_type != 'svtr' and self.encoder_type != 'svtrv4':
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 324, in convert_ifelse
      return_name_ids)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 380, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/heads/rec_multihead_v4_stu.py", line 253, in forward
      elif self.encoder_type == 'svtrv4':
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 324, in convert_ifelse
      return_name_ids)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 380, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/heads/rec_multihead_v4_stu.py", line 256, in forward
      x = self.encoder(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1014, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 993, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/PPOCRV4/rec/PaddleOCR/ppocr/modeling/heads/rec_multihead_v4_stu.py", line 196, in forward
      z = z.reshape([0, H, W, C]).transpose([0, 3, 1, 2])
    File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/manipulation.py", line 3662, in reshape
      outputs={"Out": out, "XShape": x_shape},
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 4046, in append_op
      attrs=kwargs.get("attrs", None),
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 610, 120], X's size = 73200, 'shape' is [0, 1, 61, 120], the capacity of 'shape' is 7320.
      [Hint: Expected capacity == in_size, but received capacity:7320 != in_size:73200.] (at ..\paddle\phi\infermeta\unary.cc:1781)
      [operator < reshape2 > error]

**Comment by achaosss** [comment]
我也遇到了这个报错

**Comment by SWHL** [comment]
hi,如果问题仍然存在，各位请移步https://github.com/PFCCLab/PPOCRLabel，拉取仓库最新代码，再次尝试。
如仍有问题，请在新仓库提问
