### ISSUE TITLE
conda环境下启动PPOCRLabel报错

### ISSUE THREAD

**Issue by Mrc-2020** [PaddlePaddle/PaddleOCR#10861]
Traceback (most recent call last):
  File "PPOCRLabel.py", line 40, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "D:\Anaconda3\envs\paddlepaddle2.5\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\Anaconda3\envs\paddlepaddle2.5\lib\site-packages\paddleocr\paddleocr.py", line 52, in <module>
    from ppstructure.utility import init_args, draw_structure_result
  File "D:\00PaddleTrain\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\utility.py", line 18, in <module>
    from tools.infer.utility import draw_ocr_box_txt, str2bool, str2int_tuple, init_args as infer_args
ImportError: cannot import name 'str2int_tuple' from 'tools.infer.utility' (D:\Anaconda3\envs\paddlepaddle2.5\lib\site-packages\paddleocr\tools\infer\utility.py)

**Comment by Gmgge** [comment]
尝试使用PaddleOCR-release-2.6版本的paddlelabel，目前2.7正在优化中

**Comment by 07571026** [comment]
可能是版本不一致導致的問題，你的ppstructure\utility.py 是2.7
2.6跟2.7的 tools/infer/[utility.py](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/tools/infer/utility.py) 的莫約33行是有str2int_tuple這個function的
但在2.5的 tools/infer/[utility.py](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/tools/infer/utility.py) 並沒有str2int_tuple這個function
所以你要把版本對齊
