### ISSUE TITLE
Error when training the KIE model vi_layoutxlm unexpected keyword argument 'num_classes' for LayoutXLMForTokenClassification.__init__()

### ISSUE THREAD

**Issue by andreaIskanderBelkhir** [PaddlePaddle/PaddleOCR#10883]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem:

I tryed to train a model using the config file present in the config like i did 2 month ago (the only thing that i changed is the folder for the dataset) but now give me this error, if i remove the keyword it give me  a error where i miss the argument for LayoutXLMForSer.

- 系统环境/System Environment：Colab
- 版本号/Version：Paddle：2.5.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：%run  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml 
- 完整报错/Complete Error Message：TypeError: LayoutXLMForTokenClassification.__init__() got an unexpected keyword argument 'num_classes'

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by HuiGitH** [comment]
hi， bor 我也遇到了同样问题

**Comment by HuiGitH** [comment]
@andyjpaddle 

应该和PaddleNLP的这次改动有关
"新增configuration
模型支持config"

https://github.com/PaddlePaddle/PaddleNLP/pull/5637/commits/27936b6b21298d306b254165baafbc285b7562ac#diff-2742b8e7477bc6c550f7ac3a94fe8bbe2f3726eef2b56cdac75d187e9f9a44fc
paddlenlp/transformers/layoutxlm/modeling.py line 837
<img width="1511" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/37790680/3d40baa7-65f3-4441-8bdb-4162cb0baf26">

**Comment by pjh714332048** [comment]
我也遇到同样问题

- 系统环境: ubuntu 20.04
- 版本号: paddlepaddle 2.5.1 paddleocr 2.7.0.3 paddlenlp 2.6.1
- 运行指令: python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- 完整报错: [2023/09/25 17:36:46] ppocr INFO: Architecture : 
[2023/09/25 17:36:46] ppocr INFO:     Backbone : 
[2023/09/25 17:36:46] ppocr INFO:         checkpoints : None
[2023/09/25 17:36:46] ppocr INFO:         mode : vi
[2023/09/25 17:36:46] ppocr INFO:         name : LayoutXLMForSer
[2023/09/25 17:36:46] ppocr INFO:         num_classes : 7
[2023/09/25 17:36:46] ppocr INFO:         pretrained : True
[2023/09/25 17:36:46] ppocr INFO:     Transform : None
[2023/09/25 17:36:46] ppocr INFO:     algorithm : LayoutXLM
[2023/09/25 17:36:46] ppocr INFO:     model_type : kie
[2023/09/25 17:36:46] ppocr INFO: Eval : 
[2023/09/25 17:36:46] ppocr INFO:     dataset : 
[2023/09/25 17:36:46] ppocr INFO:         data_dir : train_data/XFUND/zh_val/image
[2023/09/25 17:36:46] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_val/val.json']
[2023/09/25 17:36:46] ppocr INFO:         name : SimpleDataSet
[2023/09/25 17:36:46] ppocr INFO:         transforms : 
[2023/09/25 17:36:46] ppocr INFO:             DecodeImage : 
[2023/09/25 17:36:46] ppocr INFO:                 channel_first : False
[2023/09/25 17:36:46] ppocr INFO:                 img_mode : RGB
[2023/09/25 17:36:46] ppocr INFO:             VQATokenLabelEncode : 
[2023/09/25 17:36:46] ppocr INFO:                 algorithm : LayoutXLM
[2023/09/25 17:36:46] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/25 17:36:46] ppocr INFO:                 contains_re : False
[2023/09/25 17:36:46] ppocr INFO:                 order_method : tb-yx
[2023/09/25 17:36:46] ppocr INFO:                 use_textline_bbox_info : True
[2023/09/25 17:36:46] ppocr INFO:             VQATokenPad : 
[2023/09/25 17:36:46] ppocr INFO:                 max_seq_len : 512
[2023/09/25 17:36:46] ppocr INFO:                 return_attention_mask : True
[2023/09/25 17:36:46] ppocr INFO:             VQASerTokenChunk : 
[2023/09/25 17:36:46] ppocr INFO:                 max_seq_len : 512
[2023/09/25 17:36:46] ppocr INFO:             Resize : 
[2023/09/25 17:36:46] ppocr INFO:                 size : [224, 224]
[2023/09/25 17:36:46] ppocr INFO:             NormalizeImage : 
[2023/09/25 17:36:46] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2023/09/25 17:36:46] ppocr INFO:                 order : hwc
[2023/09/25 17:36:46] ppocr INFO:                 scale : 1
[2023/09/25 17:36:46] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2023/09/25 17:36:46] ppocr INFO:             ToCHWImage : None
[2023/09/25 17:36:46] ppocr INFO:             KeepKeys : 
[2023/09/25 17:36:46] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2023/09/25 17:36:46] ppocr INFO:     loader : 
[2023/09/25 17:36:46] ppocr INFO:         batch_size_per_card : 8
[2023/09/25 17:36:46] ppocr INFO:         drop_last : False
[2023/09/25 17:36:46] ppocr INFO:         num_workers : 4
[2023/09/25 17:36:46] ppocr INFO:         shuffle : False
[2023/09/25 17:36:46] ppocr INFO: Global : 
[2023/09/25 17:36:46] ppocr INFO:     amp_custom_white_list : ['scale', 'concat', 'elementwise_add']
[2023/09/25 17:36:46] ppocr INFO:     cal_metric_during_train : False
[2023/09/25 17:36:46] ppocr INFO:     d2s_train_image_shape : [3, 224, 224]
[2023/09/25 17:36:46] ppocr INFO:     distributed : False
[2023/09/25 17:36:46] ppocr INFO:     epoch_num : 200
[2023/09/25 17:36:46] ppocr INFO:     eval_batch_step : [0, 19]
[2023/09/25 17:36:46] ppocr INFO:     infer_img : ppstructure/docs/kie/input/zh_val_42.jpg
[2023/09/25 17:36:46] ppocr INFO:     kie_det_model_dir : None
[2023/09/25 17:36:46] ppocr INFO:     kie_rec_model_dir : None
[2023/09/25 17:36:46] ppocr INFO:     log_smooth_window : 10
[2023/09/25 17:36:46] ppocr INFO:     print_batch_step : 10
[2023/09/25 17:36:46] ppocr INFO:     save_epoch_step : 2000
[2023/09/25 17:36:46] ppocr INFO:     save_inference_dir : None
[2023/09/25 17:36:46] ppocr INFO:     save_model_dir : ./output/ser_vi_layoutxlm_xfund_zh
[2023/09/25 17:36:46] ppocr INFO:     save_res_path : ./output/ser/xfund_zh/res
[2023/09/25 17:36:46] ppocr INFO:     seed : 2022
[2023/09/25 17:36:46] ppocr INFO:     use_gpu : False
[2023/09/25 17:36:46] ppocr INFO:     use_visualdl : False
[2023/09/25 17:36:46] ppocr INFO: Loss : 
[2023/09/25 17:36:46] ppocr INFO:     key : backbone_out
[2023/09/25 17:36:46] ppocr INFO:     name : VQASerTokenLayoutLMLoss
[2023/09/25 17:36:46] ppocr INFO:     num_classes : 7
[2023/09/25 17:36:46] ppocr INFO: Metric : 
[2023/09/25 17:36:46] ppocr INFO:     main_indicator : hmean
[2023/09/25 17:36:46] ppocr INFO:     name : VQASerTokenMetric
[2023/09/25 17:36:46] ppocr INFO: Optimizer : 
[2023/09/25 17:36:46] ppocr INFO:     beta1 : 0.9
[2023/09/25 17:36:46] ppocr INFO:     beta2 : 0.999
[2023/09/25 17:36:46] ppocr INFO:     lr : 
[2023/09/25 17:36:46] ppocr INFO:         epochs : 200
[2023/09/25 17:36:46] ppocr INFO:         learning_rate : 5e-05
[2023/09/25 17:36:46] ppocr INFO:         name : Linear
[2023/09/25 17:36:46] ppocr INFO:         warmup_epoch : 2
[2023/09/25 17:36:46] ppocr INFO:     name : AdamW
[2023/09/25 17:36:46] ppocr INFO:     regularizer : 
[2023/09/25 17:36:46] ppocr INFO:         factor : 0.0
[2023/09/25 17:36:46] ppocr INFO:         name : L2
[2023/09/25 17:36:46] ppocr INFO: PostProcess : 
[2023/09/25 17:36:46] ppocr INFO:     class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/25 17:36:46] ppocr INFO:     name : VQASerTokenLayoutLMPostProcess
[2023/09/25 17:36:46] ppocr INFO: Train : 
[2023/09/25 17:36:46] ppocr INFO:     dataset : 
[2023/09/25 17:36:46] ppocr INFO:         data_dir : train_data/XFUND/zh_train/image
[2023/09/25 17:36:46] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_train/train.json']
[2023/09/25 17:36:46] ppocr INFO:         name : SimpleDataSet
[2023/09/25 17:36:46] ppocr INFO:         ratio_list : [1.0]
[2023/09/25 17:36:46] ppocr INFO:         transforms : 
[2023/09/25 17:36:46] ppocr INFO:             DecodeImage : 
[2023/09/25 17:36:46] ppocr INFO:                 channel_first : False
[2023/09/25 17:36:46] ppocr INFO:                 img_mode : RGB
[2023/09/25 17:36:46] ppocr INFO:             VQATokenLabelEncode : 
[2023/09/25 17:36:46] ppocr INFO:                 algorithm : LayoutXLM
[2023/09/25 17:36:46] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2023/09/25 17:36:46] ppocr INFO:                 contains_re : False
[2023/09/25 17:36:46] ppocr INFO:                 order_method : tb-yx
[2023/09/25 17:36:46] ppocr INFO:                 use_textline_bbox_info : True
[2023/09/25 17:36:46] ppocr INFO:             VQATokenPad : 
[2023/09/25 17:36:46] ppocr INFO:                 max_seq_len : 512
[2023/09/25 17:36:46] ppocr INFO:                 return_attention_mask : True
[2023/09/25 17:36:46] ppocr INFO:             VQASerTokenChunk : 
[2023/09/25 17:36:46] ppocr INFO:                 max_seq_len : 512
[2023/09/25 17:36:46] ppocr INFO:             Resize : 
[2023/09/25 17:36:46] ppocr INFO:                 size : [224, 224]
[2023/09/25 17:36:46] ppocr INFO:             NormalizeImage : 
[2023/09/25 17:36:46] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2023/09/25 17:36:46] ppocr INFO:                 order : hwc
[2023/09/25 17:36:46] ppocr INFO:                 scale : 1
[2023/09/25 17:36:46] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2023/09/25 17:36:46] ppocr INFO:             ToCHWImage : None
[2023/09/25 17:36:46] ppocr INFO:             KeepKeys : 
[2023/09/25 17:36:46] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2023/09/25 17:36:46] ppocr INFO:     loader : 
[2023/09/25 17:36:46] ppocr INFO:         batch_size_per_card : 8
[2023/09/25 17:36:46] ppocr INFO:         drop_last : False
[2023/09/25 17:36:46] ppocr INFO:         num_workers : 4
[2023/09/25 17:36:46] ppocr INFO:         shuffle : True
[2023/09/25 17:36:46] ppocr INFO: profiler_options : None
[2023/09/25 17:36:46] ppocr INFO: train with paddle 2.5.1 and device Place(cpu)
[2023/09/25 17:36:46] ppocr INFO: Initialize indexs of datasets:['train_data/XFUND/zh_train/train.json']
list index out of range
[2023-09-25 17:36:47,613] [    INFO] - Already cached /home/jinhuapeng/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2023-09-25 17:36:48,020] [    INFO] - tokenizer config file saved in /home/jinhuapeng/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2023-09-25 17:36:48,020] [    INFO] - Special tokens file saved in /home/jinhuapeng/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2023/09/25 17:36:48] ppocr INFO: Initialize indexs of datasets:['train_data/XFUND/zh_val/val.json']
[2023-09-25 17:36:48,021] [    INFO] - Already cached /home/jinhuapeng/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2023-09-25 17:36:48,426] [    INFO] - tokenizer config file saved in /home/jinhuapeng/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2023-09-25 17:36:48,426] [    INFO] - Special tokens file saved in /home/jinhuapeng/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2023-09-25 17:36:48,428] [ WARNING] - You are using a model of type layoutlmv2 to instantiate a model of type layoutxlm. This is not supported for all configurations of models and can yield errors.
[2023-09-25 17:36:48,428] [    INFO] - Already cached /home/jinhuapeng/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2023-09-25 17:36:48,428] [    INFO] - Loading weights file model_state.pdparams from cache at /home/jinhuapeng/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2023-09-25 17:36:49,191] [    INFO] - Loaded weights file from disk, setting weights to model.
[2023-09-25 17:36:56,724] [ WARNING] - Some weights of the model checkpoint at vi-layoutxlm-base-uncased were not used when initializing LayoutXLMModel: ['visual_proj.weight', 'visual.pixel_std', 'visual_proj.bias', 'visual.pixel_mean']
- This IS expected if you are initializing LayoutXLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LayoutXLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2023-09-25 17:36:56,724] [    INFO] - All the weights of LayoutXLMModel were initialized from the model checkpoint at vi-layoutxlm-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LayoutXLMModel for predictions without further training.
Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "/home/jinhuapeng/Desktop/paddleOCR/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 30, in build_model
    arch = BaseModel(config)
  File "/home/jinhuapeng/Desktop/paddleOCR/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 55, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/jinhuapeng/Desktop/paddleOCR/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 80, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/jinhuapeng/Desktop/paddleOCR/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 149, in __init__
    super(LayoutXLMForSer, self).__init__(
  File "/home/jinhuapeng/Desktop/paddleOCR/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 65, in __init__
    self.model = model_class(
  File "/home/jinhuapeng/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 253, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_classes'

**Comment by jinyichao** [comment]
我也遇到同样问题

- 系统环境: Mac Pro
- 版本号: paddlepaddle 2.5.1 paddleocr 2.7.0.3 paddlenlp 2.6.1
- 运行指令: python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- 完整报错: File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paddlenlp/transformers/utils.py", line 253, in __impl__ init_func(self, *args, **kwargs)
TypeError: LayoutXLMForTokenClassification.__init__() got an unexpected keyword argument 'num_classes'

**Comment by jinyichao** [comment]
把paddlenlp的版本退回到2.5.2可以暂时解决这个问题，让训练跑起来

**Comment by L-Q-K** [comment]
> 我也遇到同样问题
> 
> * 系统环境: ubuntu 20.04
> * 版本号: paddlepaddle 2.5.1 paddleocr 2.7.0.3 paddlenlp 2.6.1
> * 运行指令: python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
> * 完整报错: envs/paddle_env/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 253, in **impl**
>   init_func(self, *args, **kwargs)
>   TypeError: **init**() got an unexpected keyword argument 'num_classes'

Have you fix this ? I am facing the sam issue

**Comment by caohrong** [comment]
这个问题有动静么？ 我也遇到了。

**Comment by huanghao128** [comment]
PaddleOCR和PaddleNLP版本问题，目前发现可行的版本匹配方案：
1、PaddleOCR<=2.7.0 + PaddleNLP==2.5.2
2、PaddleOCR>=2.7.1 + PaddleNLP>=2.6.0
