### ISSUE TITLE
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function.

### ISSUE THREAD

**Issue by jiangbossB** [PaddlePaddle/PaddleOCR#10898]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- win10    Driver Version: 537.13       CUDA Version: 12.2
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- numpy                 1.25.2
onnx                  1.14.1
opencv-contrib-python 4.6.0.66
opencv-python         4.6.0.66
openpyxl              3.1.2
opt-einsum            3.3.0
packaging             23.1
paddle-bfloat         0.1.7
paddle2onnx           1.0.6
paddlefsl             1.1.0
paddlenlp             2.4.5
paddleocr             2.7.0.2
paddlepaddle-gpu      2.5.1.post120
- 运行指令/Command Code：python tools/train.py -c configs\rec\PP-OCRv3\en_PP-OCRv3_rec.yml
- 完整报错/Complete Error Message：
[2023/09/14 10:00:03] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.weight [1536, 58] not matched with loaded params head.sar_head.decoder.prediction.weight [1536, 98] !
[2023/09/14 10:00:03] ppocr WARNING: The shape of model params head.sar_head.decoder.prediction.bias [58] not matched with loaded params head.sar_head.decoder.prediction.bias [98] !     
[2023/09/14 10:00:07] ppocr INFO: load pretrain successful from models/en_PP-OCRv3_rec_train/best_accuracy
[2023/09/14 10:00:07] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 50 iterations
Traceback (most recent call last):
  File "F:\python_project\PaddleOCR\tools\train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "F:\python_project\PaddleOCR\tools\train.py", line 198, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "F:\python_project\PaddleOCR\tools\program.py", line 301, in train
    preds = model(images, data=batch[1:])
  File "F:\Program Files\anaconda3\envs\ppocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\python_project\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 100, in forward
    x = self.head(x, targets=data)
  File "F:\Program Files\anaconda3\envs\ppocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\python_project\PaddleOCR\ppocr\modeling\heads\rec_multi_head.py", line 101, in forward
    sar_out = self.sar_head(x, targets[1:])
  File "F:\Program Files\anaconda3\envs\ppocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\python_project\PaddleOCR\ppocr\modeling\heads\rec_sar_head.py", line 397, in forward
    holistic_feat = self.encoder(feat, targets)  # bsz c
  File "F:\Program Files\anaconda3\envs\ppocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\python_project\PaddleOCR\ppocr\modeling\heads\rec_sar_head.py", line 105, in forward
    valid_hf.append(holistic_feat[i, valid_step, :])
  File "F:\Program Files\anaconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 743, in __getitem__
    return _getitem_impl_(self, item)
  File "F:\Program Files\anaconda3\envs\ppocr\lib\site-packages\paddle\fluid\variable_index.py", line 561, in _getitem_impl_
    out = paddle._C_ops.slice(
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function.
  [Hint: Expected valid() == true, but received valid():0 != true:1.] (at ..\paddle\phi\core\dense_tensor.cc:122)

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by jiangbossB** [comment]
我看了几个相关的issue都说什么版本啥的不匹配 怎么搞啊

**Comment by jiangbossB** [comment]
> 我看了几个相关的issue都说什么版本啥的不匹配 怎么搞啊

我的分支 release2.7

**Comment by jiangbossB** [comment]
> > 我看了几个相关的issue都说什么版本啥的不匹配 怎么搞啊
> 
> 我的分支 release2.7

gt：
train/134.jpg	bC24
train/135.jpg	XF32
train/136.jpg	SNX7
train/137.jpg	MJg1
train/138.jpg	bQ91
train/139.jpg	hHm6
train/14.jpg	Alw8
train/140.jpg	YQ5f
train/141.jpg	1fjE
train/142.jpg	1Trn
train/143.jpg	RcB9
train/144.jpg	UYM5
train/145.jpg	Q6xL
train/148.jpg	u7l9
train/149.jpg	VbV5

**Comment by piperino11** [comment]
did you solve this ?
