### ISSUE TITLE
安装paddleOCR时，PyMuPDF安装错误，求解！

### ISSUE THREAD

**Issue by kwhjohn** [PaddlePaddle/PaddleOCR#10919]
安装paddleOCR时，安装到PyMuPDF提示安装错误，错误信息如下，请问如何解决？
安装环境是conda，python=3.11，paddle是CPU版

Building wheels for collected packages: PyMuPDF
  Building wheel for PyMuPDF (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [108 lines of output]
      PyMuPDF/setup.py: sys.argv: ['C:\\Users\\kwh\\AppData\\Local\\Temp\\pip-install-25bfr9jl\\pymupdf_d9d07fcd750343138be843c53700bffe\\setup.py', 'bdist_wheel', '-d', 'C:\\Users\\kwh\\AppData\\Local\\Temp\\pip-wheel-7ju0zhrn']
      PyMuPDF/setup.py: os.getcwd(): C:\Users\kwh\AppData\Local\Temp\pip-install-25bfr9jl\pymupdf_d9d07fcd750343138be843c53700bffe
      PyMuPDF/setup.py: __file__: C:\Users\kwh\AppData\Local\Temp\pip-install-25bfr9jl\pymupdf_d9d07fcd750343138be843c53700bffe\setup.py
      PyMuPDF/setup.py: $PYTHON_ARCH: None
      PyMuPDF/setup.py: os.environ (87):
      PyMuPDF/setup.py:     ALLUSERSPROFILE: C:\ProgramData
      PyMuPDF/setup.py:     ANDROID_SDK_HOME: D:\share\Tools\Android sdk\sdk
      PyMuPDF/setup.py:     APPCODE_VM_OPTIONS: D:\jihuo-tool\vmoptions\appcode.vmoptions
      PyMuPDF/setup.py:     APPDATA: C:\Users\kwh\AppData\Roaming
      PyMuPDF/setup.py:     CLION_VM_OPTIONS: D:\jihuo-tool\vmoptions\clion.vmoptions
      PyMuPDF/setup.py:     COMMONPROGRAMFILES: C:\Program Files\Common Files
      PyMuPDF/setup.py:     COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
      PyMuPDF/setup.py:     COMMONPROGRAMW6432: C:\Program Files\Common Files
      PyMuPDF/setup.py:     COMPUTERNAME: 512-OFFICEPC
      PyMuPDF/setup.py:     COMSPEC: C:\WINDOWS\system32\cmd.exe
      PyMuPDF/setup.py:     CONDA_DEFAULT_ENV: D:\paddle\env
      PyMuPDF/setup.py:     CONDA_EXE: D:\ProgramData\anaconda3\Scripts\conda.exe
      PyMuPDF/setup.py:     CONDA_PREFIX: D:\paddle\env
      PyMuPDF/setup.py:     CONDA_PREFIX_1: D:\ProgramData\anaconda3
      PyMuPDF/setup.py:     CONDA_PREFIX_2: D:\paddle\env
      PyMuPDF/setup.py:     CONDA_PREFIX_3: D:\ProgramData\anaconda3
      PyMuPDF/setup.py:     CONDA_PROMPT_MODIFIER: (D:\paddle\env)
      PyMuPDF/setup.py:     CONDA_PYTHON_EXE: D:\ProgramData\anaconda3\python.exe
      PyMuPDF/setup.py:     CONDA_SHLVL: 4
      PyMuPDF/setup.py:     CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0
      PyMuPDF/setup.py:     CUDA_PATH_V12_0: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0
      PyMuPDF/setup.py:     DATAGRIP_VM_OPTIONS: D:\jihuo-tool\vmoptions\datagrip.vmoptions
      PyMuPDF/setup.py:     DATASPELL_VM_OPTIONS: D:\jihuo-tool\vmoptions\dataspell.vmoptions
      PyMuPDF/setup.py:     DEVECOSTUDIO_VM_OPTIONS: D:\jihuo-tool\vmoptions\devecostudio.vmoptions
      PyMuPDF/setup.py:     DOKANLIBRARY1: C:\Program Files\Dokan\Dokan Library-1.2.2.1000\
      PyMuPDF/setup.py:     DRIVERDATA: C:\Windows\System32\Drivers\DriverData
      PyMuPDF/setup.py:     EMULATOR_AVD_ROOT: D:\Program Files\MobileAppEngine\emui
      PyMuPDF/setup.py:     EMULATOR_SDK_ROOT: C:\Program Files\MobileAppEngine\EmulatorSdk
      PyMuPDF/setup.py:     FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
      PyMuPDF/setup.py:     FPS_BROWSER_USER_PROFILE_STRING: Default
      PyMuPDF/setup.py:     GATEWAY_VM_OPTIONS: D:\jihuo-tool\vmoptions\gateway.vmoptions
      PyMuPDF/setup.py:     GOLAND_VM_OPTIONS: D:\jihuo-tool\vmoptions\goland.vmoptions
      PyMuPDF/setup.py:     GOPATH: E:\GoDev
      PyMuPDF/setup.py:     HOMEDRIVE: C:
      PyMuPDF/setup.py:     HOMEPATH: \Users\kwh
      PyMuPDF/setup.py:     IDEA_VM_OPTIONS: D:\jihuo-tool\vmoptions\idea.vmoptions
      PyMuPDF/setup.py:     JETBRAINSCLIENT_VM_OPTIONS: D:\jihuo-tool\vmoptions\jetbrainsclient.vmoptions
      PyMuPDF/setup.py:     JETBRAINS_CLIENT_VM_OPTIONS: D:\jihuo-tool\vmoptions\jetbrains_client.vmoptions
      PyMuPDF/setup.py:     LOCALAPPDATA: C:\Users\kwh\AppData\Local
      PyMuPDF/setup.py:     LOGONSERVER: \\512-OFFICEPC
      PyMuPDF/setup.py:     NUMBER_OF_PROCESSORS: 8
      PyMuPDF/setup.py:     NVTOOLSEXT_PATH: C:\Program Files\NVIDIA Corporation\NvToolsExt\
      PyMuPDF/setup.py:     ONEDRIVE: C:\Users\kwh\OneDrive
      PyMuPDF/setup.py:     OPENSSL_CONF: D:\share\Tools\UPUPW\PHP7\extras\openssl\openssl.cnf
      PyMuPDF/setup.py:     OS: Windows_NT
      PyMuPDF/setup.py:     PATH: D:\paddle\env;D:\paddle\env\Library\mingw-w64\bin;D:\paddle\env\Library\usr\bin;D:\paddle\env\Library\bin;D:\paddle\env\Scripts;D:\paddle\env\bin;D:\ProgramData\anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\libnvvp;C:\Program Files (x86)\VMware\VMware Workstation\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\szzfcg\tbqw;C:\cygwin64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Go\bin;E:\GoDev\bin;C:\Program Files\dotnet;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.4.1;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\kwh\AppData\Roaming\Python\Python310\Scripts;C:\Users\kwh\AppData\Local\Programs\Python\Python310;C:\Users\kwh\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\kwh\AppData\Local\Programs\Python\Python310;C:\Users\kwh\AppData\Local\Microsoft\WindowsApps;C:\Users\kwh\go\bin;D:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Tencent\QQGameTempest\Hall.57967;D:\share\Tools\JetBrains\PyCharm 2023.2\bin;.;D:\share\Tools\JetBrains\PhpStorm 2023.2\bin;.
      PyMuPDF/setup.py:     PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
      PyMuPDF/setup.py:     PHPSTORM: D:\share\Tools\JetBrains\PhpStorm 2023.2\bin;
      PyMuPDF/setup.py:     PHPSTORM_VM_OPTIONS: D:\jihuo-tool\vmoptions\phpstorm.vmoptions
      PyMuPDF/setup.py:     PROCESSOR_ARCHITECTURE: AMD64
      PyMuPDF/setup.py:     PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
      PyMuPDF/setup.py:     PROCESSOR_LEVEL: 6
      PyMuPDF/setup.py:     PROCESSOR_REVISION: 3a09
      PyMuPDF/setup.py:     PROG27B48B2C053: 1
      PyMuPDF/setup.py:     PROGRAMDATA: C:\ProgramData
      PyMuPDF/setup.py:     PROGRAMFILES: C:\Program Files
      PyMuPDF/setup.py:     PROGRAMFILES(X86): C:\Program Files (x86)
      PyMuPDF/setup.py:     PROGRAMW6432: C:\Program Files
      PyMuPDF/setup.py:     PSEXECUTIONPOLICYPREFERENCE: Bypass
      PyMuPDF/setup.py:     PSMODULEPATH: C:\Users\kwh\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
      PyMuPDF/setup.py:     PUBLIC: C:\Users\Public
      PyMuPDF/setup.py:     PYCHARM: D:\share\Tools\JetBrains\PyCharm 2023.2\bin;
      PyMuPDF/setup.py:     PYCHARM_VM_OPTIONS: D:\jihuo-tool\vmoptions\pycharm.vmoptions
      PyMuPDF/setup.py:     RIDER_VM_OPTIONS: D:\jihuo-tool\vmoptions\rider.vmoptions
      PyMuPDF/setup.py:     RUBYMINE_VM_OPTIONS: D:\jihuo-tool\vmoptions\rubymine.vmoptions
      PyMuPDF/setup.py:     SESSIONNAME: Console
      PyMuPDF/setup.py:     SSL_CERT_FILE: D:\paddle\env\Library\ssl\cacert.pem
      PyMuPDF/setup.py:     STUDIO_VM_OPTIONS: D:\jihuo-tool\vmoptions\studio.vmoptions
      PyMuPDF/setup.py:     SYSTEMDRIVE: C:
      PyMuPDF/setup.py:     SYSTEMROOT: C:\WINDOWS
      PyMuPDF/setup.py:     TEMP: C:\Users\kwh\AppData\Local\Temp
      PyMuPDF/setup.py:     TMP: C:\Users\kwh\AppData\Local\Temp
      PyMuPDF/setup.py:     USERDOMAIN: 512-OFFICEPC
      PyMuPDF/setup.py:     USERDOMAIN_ROAMINGPROFILE: 512-OFFICEPC
      PyMuPDF/setup.py:     USERNAME: kwh
      PyMuPDF/setup.py:     USERPROFILE: C:\Users\kwh
      PyMuPDF/setup.py:     VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
      PyMuPDF/setup.py:     VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
      PyMuPDF/setup.py:     VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
      PyMuPDF/setup.py:     WEBIDE_VM_OPTIONS: D:\jihuo-tool\vmoptions\webide.vmoptions
      PyMuPDF/setup.py:     WEBSTORM_VM_OPTIONS: D:\jihuo-tool\vmoptions\webstorm.vmoptions
      PyMuPDF/setup.py:     WINDIR: C:\WINDOWS
      PyMuPDF/setup.py:     WXDRIVE_START_ARGS: --wxdrive-setting=0 --disable-gpu --disable-software-rasterizer --enable-features=NetworkServiceInProcess
      PyMuPDF/setup.py:     _CONDA_EXE: D:/ProgramData/anaconda3\Scripts\conda.exe
      PyMuPDF/setup.py:     _CONDA_ROOT: D:/ProgramData/anaconda3
      PyMuPDF/setup.py:     __CONDA_OPENSLL_CERT_FILE_SET: 1
      PyMuPDF/setup.py:     PIP_BUILD_TRACKER: C:\Users\kwh\AppData\Local\Temp\pip-build-tracker-6obpge4y
      PyMuPDF/setup.py: mupdf_tgz already exists: C:\Users\kwh\AppData\Local\Temp\pip-install-25bfr9jl\pymupdf_d9d07fcd750343138be843c53700bffe\mupdf.tgz
      PyMuPDF/setup.py: Extracting C:\Users\kwh\AppData\Local\Temp\pip-install-25bfr9jl\pymupdf_d9d07fcd750343138be843c53700bffe\mupdf.tgz
      PyMuPDF/setup.py: mupdf_local='mupdf-1.20.3-source/'
      PyMuPDF/setup.py: Building mupdf.
      PyMuPDF/setup.py: Cannot find devenv.com in default locations, using: 'devenv.com'
      PyMuPDF/setup.py: Building MuPDF by running: cd mupdf-1.20.3-source/&&"devenv.com" platform/win32/mupdf.sln /Build "ReleaseTesseract|x64" /Project mupdf
      '"devenv.com"' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\kwh\AppData\Local\Temp\pip-install-25bfr9jl\pymupdf_d9d07fcd750343138be843c53700bffe\setup.py", line 550, in <module>
          subprocess.run( command, shell=True, check=True)
        File "D:\paddle\env\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'cd mupdf-1.20.3-source/&&"devenv.com" platform/win32/mupdf.sln /Build "ReleaseTesseract|x64" /Project mupdf' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyMuPDF
  Running setup.py clean for PyMuPDF
Failed to build PyMuPDF
ERROR: Could not build wheels for PyMuPDF, which is required to install pyproject.toml-based projects

**Comment by chenhao86** [comment]
PyMuPDF  我安装的是1.20.2 这个版本。

**Comment by lwc1984** [comment]
你需要把devenv.com的路径添加到path环境变量里

**Comment by MrMello9** [comment]
python版本太高了，在anaconda里新建个环境，下3.9的就行

**Comment by arguskao** [comment]
我是python 3.9

 xcrun ranlib build/release/libmupdf-pkcs7.a
      mkdir -p build/release/source/helpers/mu-threads/ ; xcrun cc -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -fomit-frame-pointer  -Iinclude -MMD -MP -o build/release/source/helpers/mu-threads/mu-threads.o -c source/helpers/mu-threads/mu-threads.c -Wall -Wsign-compare
      mkdir -p build/release/ ; xcrun ar cr build/release/libmupdf-threads.a build/release/source/helpers/mu-threads/mu-threads.o
      xcrun ranlib build/release/libmupdf-threads.a
      mkdir -p build/release/ ; xcrun cc -Wl,-dead_strip -Wl,-s -o build/release/mutool build/release/source/tools/mutool.o build/release/source/tools/muconvert.o build/release/source/tools/mudraw.o build/release/source/tools/murun.o build/release/source/tools/mutrace.o build/release/source/tools/cmapdump.o build/release/source/tools/pdfclean.o build/release/source/tools/pdfcreate.o build/release/source/tools/pdfextract.o build/release/source/tools/pdfinfo.o build/release/source/tools/pdfmerge.o build/release/source/tools/pdfpages.o build/release/source/tools/pdfposter.o build/release/source/tools/pdfshow.o build/release/source/tools/pdfsign.o build/release/libmupdf.a build/release/libmupdf-third.a build/release/libmupdf-pkcs7.a build/release/libmupdf-threads.a  -lm           -lpthread -lstdc++   -L/opt/homebrew/Cellar/openssl@3/3.1.4/lib -lcrypto
      ld: warning: option -s is obsolete and being ignored
      mkdir -p build/release/source/tools/ ; xcrun cc -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -fomit-frame-pointer  -Iinclude -MMD -MP -o build/release/source/tools/muraster.o -c source/tools/muraster.c -Wall -Wsign-compare -Ithirdparty/freetype/include -Iscripts/freetype -Ithirdparty/gumbo-parser/src -Ithirdparty/harfbuzz/src -Ithirdparty/libjpeg -Iscripts/libjpeg -Ithirdparty/lcms2/include -DHAVE_LCMS2MT -Ithirdparty/mujs -Ithirdparty/zlib -Ithirdparty/jbig2dec -Ithirdparty/openjpeg/src/lib/openjp2 -DOPJ_STATIC -DOPJ_HAVE_INTTYPES_H -DOPJ_HAVE_STDINT_H -DHAVE_LEPTONICA -Ithirdparty/leptonica/src -DHAVE_TESSERACT -Ithirdparty/tesseract/include -Iscripts/tesseract -Ithirdparty/extract/include
      mkdir -p build/release/ ; xcrun cc -Wl,-dead_strip -Wl,-s -o build/release/muraster build/release/source/tools/muraster.o build/release/libmupdf.a build/release/libmupdf-third.a build/release/libmupdf-pkcs7.a build/release/libmupdf-threads.a  -lm           -lpthread -lstdc++   -L/opt/homebrew/Cellar/openssl@3/3.1.4/lib -lcrypto
      ld: warning: option -s is obsolete and being ignored
      build/release:
      total 161304
      drwxr-xr-x@  3 user  staff        96 Nov  9 21:28 generated
      -rw-r--r--@  1 user  staff     17200 Nov  9 21:30 libmupdf-pkcs7.a
      -rw-r--r--@  1 user  staff  12913480 Nov  9 21:30 libmupdf-third.a
      -rw-r--r--@  1 user  staff      2080 Nov  9 21:30 libmupdf-threads.a
      -rw-r--r--@  1 user  staff  48714864 Nov  9 21:28 libmupdf.a
      -rwxr-xr-x@  1 user  staff   9039461 Nov  9 21:30 muraster
      -rwxr-xr-x@  1 user  staff  11888515 Nov  9 21:30 mutool
      drwxr-xr-x@ 11 user  staff       352 Nov  9 21:30 source
      drwxr-xr-x@ 14 user  staff       448 Nov  9 21:30 thirdparty
      PyMuPDF/setup.py: Finished building mupdf.
      PyMuPDF/setup.py: sys.platform='darwin'
      PyMuPDF/setup.py: library_dirs=['mupdf-1.20.3-source/build/release', 'mupdf-1.20.3-source/build/release']
      PyMuPDF/setup.py: libraries=['mupdf', 'mupdf-third']
      PyMuPDF/setup.py: include_dirs=['mupdf-1.20.3-source/include', 'mupdf-1.20.3-source/include/mupdf', 'mupdf-1.20.3-source/thirdparty/freetype/include']
      PyMuPDF/setup.py: extra_link_args=[]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'fitz._fitz' extension
      swigging fitz/fitz.i to fitz/fitz_wrap.c
      swig -python -o fitz/fitz_wrap.c fitz/fitz.i
      error: command 'swig' failed: Not a directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyMuPDF
  Building wheel for lmdb (pyproject.toml) ... done
  Created wheel for lmdb: filename=lmdb-1.4.1-cp39-cp39-macosx_10_9_universal2.whl size=169635 sha256=e2e759409c93de37cacc8c11b711fc1ecc5b581beb39cb62833a00279dbd70cf
  Stored in directory: /Users/user/Library/Caches/pip/wheels/84/55/b3/bf057744f7438df5fdd827e608375a671404240663202e5ff0
  Building wheel for lxml (pyproject.toml) ... done
  Created wheel for lxml: filename=lxml-4.9.3-cp39-cp39-macosx_10_9_universal2.whl size=3108214 sha256=d1a604e2ef512ff8de78c39d80e2a436d55655d6a5ef9362abb25a8a29b019a4
  Stored in directory: /Users/user/Library/Caches/pip/wheels/5c/05/aa/530f84480d476c5bb9ea09877eea78fb144ec047fbb00ee2ca
Successfully built fire lmdb lxml
Failed to build PyMuPDF
ERROR: Could not build wheels for PyMuPDF, which is required to install pyproject.toml-based projects

不知道該怎麼辦

**Comment by EricLiuAno** [comment]
> 我是python 3.9，mac M2 晶片！
> 
> xcrun ranlib build/release/libmupdf-pkcs7.a mkdir -p build/release/source/helpers/mu-threads/ ; xcrun cc -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -fomit-frame-pointer -Iinclude -MMD -MP -o build/release/source/helpers/mu-threads/mu-threads.o -c source/helpers/mu-threads/mu-threads.c -Wall -Wsign-compare mkdir -p build/release/ ; xcrun ar cr build/release/libmupdf-threads.a build/release/source/helpers/mu-threads/mu-threads.o xcrun ranlib build/release/libmupdf-threads.a mkdir -p build/release/ ; xcrun cc -Wl,-dead_strip -Wl,-s -o build/release/mutool build/release/source/tools/mutool.o build/release/source/tools/muconvert.o build/release/source/tools/mudraw.o build/release/source/tools/murun.o build/release/source/tools/mutrace.o build/release/source/tools/cmapdump.o build/release/source/tools/pdfclean.o build/release/source/tools/pdfcreate.o build/release/source/tools/pdfextract.o build/release/source/tools/pdfinfo.o build/release/source/tools/pdfmerge.o build/release/source/tools/pdfpages.o build/release/source/tools/pdfposter.o build/release/source/tools/pdfshow.o build/release/source/tools/pdfsign.o build/release/libmupdf.a build/release/libmupdf-third.a build/release/libmupdf-pkcs7.a build/release/libmupdf-threads.a -lm -lpthread -lstdc++ -L/opt/homebrew/Cellar/openssl@3/3.1.4/lib -lcrypto ld: warning: option -s is obsolete and being ignored mkdir -p build/release/source/tools/ ; xcrun cc -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -fomit-frame-pointer -Iinclude -MMD -MP -o build/release/source/tools/muraster.o -c source/tools/muraster.c -Wall -Wsign-compare -Ithirdparty/freetype/include -Iscripts/freetype -Ithirdparty/gumbo-parser/src -Ithirdparty/harfbuzz/src -Ithirdparty/libjpeg -Iscripts/libjpeg -Ithirdparty/lcms2/include -DHAVE_LCMS2MT -Ithirdparty/mujs -Ithirdparty/zlib -Ithirdparty/jbig2dec -Ithirdparty/openjpeg/src/lib/openjp2 -DOPJ_STATIC -DOPJ_HAVE_INTTYPES_H -DOPJ_HAVE_STDINT_H -DHAVE_LEPTONICA -Ithirdparty/leptonica/src -DHAVE_TESSERACT -Ithirdparty/tesseract/include -Iscripts/tesseract -Ithirdparty/extract/include mkdir -p build/release/ ; xcrun cc -Wl,-dead_strip -Wl,-s -o build/release/muraster build/release/source/tools/muraster.o build/release/libmupdf.a build/release/libmupdf-third.a build/release/libmupdf-pkcs7.a build/release/libmupdf-threads.a -lm -lpthread -lstdc++ -L/opt/homebrew/Cellar/openssl@3/3.1.4/lib -lcrypto ld: warning: option -s is obsolete and being ignored build/release: total 161304 drwxr-xr-x@ 3 user staff 96 Nov 9 21:28 generated -rw-r--r--@ 1 user staff 17200 Nov 9 21:30 libmupdf-pkcs7.a -rw-r--r--@ 1 user staff 12913480 Nov 9 21:30 libmupdf-third.a -rw-r--r--@ 1 user staff 2080 Nov 9 21:30 libmupdf-threads.a -rw-r--r--@ 1 user staff 48714864 Nov 9 21:28 libmupdf.a -rwxr-xr-x@ 1 user staff 9039461 Nov 9 21:30 muraster -rwxr-xr-x@ 1 user staff 11888515 Nov 9 21:30 mutool drwxr-xr-x@ 11 user staff 352 Nov 9 21:30 source drwxr-xr-x@ 14 user staff 448 Nov 9 21:30 thirdparty PyMuPDF/setup.py: Finished building mupdf. PyMuPDF/setup.py: sys.platform='darwin' PyMuPDF/setup.py: library_dirs=['mupdf-1.20.3-source/build/release', 'mupdf-1.20.3-source/build/release'] PyMuPDF/setup.py: libraries=['mupdf', 'mupdf-third'] PyMuPDF/setup.py: include_dirs=['mupdf-1.20.3-source/include', 'mupdf-1.20.3-source/include/mupdf', 'mupdf-1.20.3-source/thirdparty/freetype/include'] PyMuPDF/setup.py: extra_link_args=[] running bdist_wheel running build running build_py running build_ext building 'fitz._fitz' extension swigging fitz/fitz.i to fitz/fitz_wrap.c swig -python -o fitz/fitz_wrap.c fitz/fitz.i error: command 'swig' failed: Not a directory [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for PyMuPDF Building wheel for lmdb (pyproject.toml) ... done Created wheel for lmdb: filename=lmdb-1.4.1-cp39-cp39-macosx_10_9_universal2.whl size=169635 sha256=e2e759409c93de37cacc8c11b711fc1ecc5b581beb39cb62833a00279dbd70cf Stored in directory: /Users/user/Library/Caches/pip/wheels/84/55/b3/bf057744f7438df5fdd827e608375a671404240663202e5ff0 Building wheel for lxml (pyproject.toml) ... done Created wheel for lxml: filename=lxml-4.9.3-cp39-cp39-macosx_10_9_universal2.whl size=3108214 sha256=d1a604e2ef512ff8de78c39d80e2a436d55655d6a5ef9362abb25a8a29b019a4 Stored in directory: /Users/user/Library/Caches/pip/wheels/5c/05/aa/530f84480d476c5bb9ea09877eea78fb144ec047fbb00ee2ca Successfully built fire lmdb lxml Failed to build PyMuPDF ERROR: Could not build wheels for PyMuPDF, which is required to install pyproject.toml-based projects
> 
> 不知道該怎麼辦

Same problem here
同上

**Comment by CrewS** [comment]
遇到相同的问题，通过brew install swig 解决 @arguskao @EricLiuAno

**Comment by KevinRodriguez777** [comment]
this issue persists on 3.11 windows.
