### ISSUE TITLE
ppocr 2.7版本中  PPOCRLabel.py报错。

### ISSUE THREAD

**Issue by Bigb20** [PaddlePaddle/PaddleOCR#10971]
PS E:\PJ\PaddleOCR-release-2.7\PPOCRLabel> python PPOCRLabel.py --lang ch                                         
[2023/09/22 12:05:51] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2840, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
  File "PPOCRLabel.py", line 112, in __init__
    result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\paddleocr.py", line 766, in __call__
    res, _ = super().__call__(
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\table\predict_structure.py", line 120, in __call__
    data = transform(data, self.preprocess_op)
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "E:\PJ\PaddleOCR-release-2.7\PPOCRLabel\..\ppocr\data\imaug\operators.py", line 92, in __call__
    data['image'] = (img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)

**Comment by Gerres** [comment]
和我一样，我也是这个报错

**Comment by Gmgge** [comment]
请参考该问题，release版本正在修复进行中，https://github.com/PaddlePaddle/PaddleOCR/issues/10748。

**Comment by Paartha** [comment]
Is there any solution for this yet? I am also facing same error.

**Comment by Paartha** [comment]
Fix:
enviroment: Ubuntu 20.04, Python 3.7

pip install paddlepaddle
pip install PPOCRLabel
sudo apt-get install libxcb-xinerama0
pip uninstall opencv-python
pip install opencv-python-headless
this worked for me

**Comment by SWHL** [comment]
Since PPOCRLabel has moved, please go to [PPOCRLabel](https://github.com/PFCCLab/PPOCRLabel) to ask questions if you have any questions!
This issue has been closed first.
