### ISSUE TITLE
大佬，报错阿，救救孩子

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/PaddleOCR#10984]
采用paddleocr2.7，配置文件det_r18_vd_ct.yml，报错：
, error happened with msg: Traceback (most recent call last):
  File "/home/jmt/Paddleocr_2.7/PaddleOCR-release-2.7/ppocr/data/simple_dataset.py", line 159, in __getitem__
    outs = transform(data, self.ops)
  File "/home/jmt/Paddleocr_2.7/PaddleOCR-release-2.7/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/jmt/Paddleocr_2.7/PaddleOCR-release-2.7/ppocr/data/imaug/ct_process.py", line 117, in __call__
    [scale_factor[0], scale_factor[1]] * (bboxes[i].shape[0] // 2)),
ValueError: operands could not be broadcast together with shapes (4,2) (4,)

**Comment by KrisTopherHao** [comment]
我也是，啥原因啊

**Comment by YangSN0719** [comment]
同样的错误
Traceback (most recent call last):
  File "/workspace/code/PaddleOCR-release-2.7/ppocr/data/simple_dataset.py", line 159, in __getitem__
    outs = transform(data, self.ops)
  File "/workspace/code/PaddleOCR-release-2.7/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/workspace/code/PaddleOCR-release-2.7/ppocr/data/imaug/ct_process.py", line 116, in __call__
    print("***bboxes[i]***", bboxes[i]*([scale_factor[0], scale_factor[1]]*(bboxes[i].shape[0]//2)) , bboxes[i].shape)
ValueError: operands could not be broadcast together with shapes (4,2) (4,)

**Comment by YangSN0719** [comment]
ct_process.py文件中的下面这句程序输出了以上报错，使用其他配置时暂时没有发现该问题

**Comment by YangSN0719** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/44280931/cf25d6d1-8cf3-4af5-a327-5ee48232683c)
