### ISSUE TITLE
转换模型后识别结果乱码，请大佬帮忙分析下

### ISSUE THREAD

**Issue by scyangjunjie** [PaddlePaddle/PaddleOCR#10992]
(test) PS D:\paddle-ocr\PaddleOCR-release-2.6> python tools/infer_rec.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model=output/v3_en_mobile/best_accuracy.pdparams Global.infer_img=D:\paddle-ocr\PaddleOCR-release-2.6\train_data\data\image_0.png
C:\ProgramData\anaconda3\envs\test\lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\ProgramData\anaconda3\envs\test\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[2023/09/25 16:24:19] ppocr INFO: Architecture :
[2023/09/25 16:24:19] ppocr INFO:     Backbone :
[2023/09/25 16:24:19] ppocr INFO:         last_conv_stride : [1, 2]
[2023/09/25 16:24:19] ppocr INFO:         last_pool_type : avg
[2023/09/25 16:24:19] ppocr INFO:         name : MobileNetV1Enhance
[2023/09/25 16:24:19] ppocr INFO:         scale : 0.5
[2023/09/25 16:24:19] ppocr INFO:     Head :
[2023/09/25 16:24:19] ppocr INFO:         head_list :
[2023/09/25 16:24:19] ppocr INFO:             CTCHead :
[2023/09/25 16:24:19] ppocr INFO:                 Head :
[2023/09/25 16:24:19] ppocr INFO:                     fc_decay : 1e-05
[2023/09/25 16:24:19] ppocr INFO:                 Neck :
[2023/09/25 16:24:19] ppocr INFO:                     depth : 2
[2023/09/25 16:24:19] ppocr INFO:                     dims : 64
[2023/09/25 16:24:19] ppocr INFO:                     hidden_dims : 120
[2023/09/25 16:24:19] ppocr INFO:                     name : svtr
[2023/09/25 16:24:19] ppocr INFO:                     use_guide : True
[2023/09/25 16:24:19] ppocr INFO:             SARHead :
[2023/09/25 16:24:19] ppocr INFO:                 enc_dim : 512
[2023/09/25 16:24:19] ppocr INFO:                 max_text_length : 25
[2023/09/25 16:24:19] ppocr INFO:         name : MultiHead
[2023/09/25 16:24:19] ppocr INFO:     Transform : None
[2023/09/25 16:24:19] ppocr INFO:     algorithm : SVTR
[2023/09/25 16:24:19] ppocr INFO:     model_type : rec
[2023/09/25 16:24:19] ppocr INFO: Eval :
[2023/09/25 16:24:19] ppocr INFO:     dataset :
[2023/09/25 16:24:19] ppocr INFO:         data_dir : ./train_data
[2023/09/25 16:24:19] ppocr INFO:         label_file_list : ['./train_data/rec/val.txt']
[2023/09/25 16:24:19] ppocr INFO:         name : SimpleDataSet
[2023/09/25 16:24:19] ppocr INFO:         transforms :
[2023/09/25 16:24:19] ppocr INFO:             DecodeImage :
[2023/09/25 16:24:19] ppocr INFO:                 channel_first : False
[2023/09/25 16:24:19] ppocr INFO:                 img_mode : BGR
[2023/09/25 16:24:19] ppocr INFO:             MultiLabelEncode : None
[2023/09/25 16:24:19] ppocr INFO:             RecResizeImg :
[2023/09/25 16:24:19] ppocr INFO:                 image_shape : [3, 48, 320]
[2023/09/25 16:24:19] ppocr INFO:             KeepKeys :
[2023/09/25 16:24:19] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2023/09/25 16:24:19] ppocr INFO:     loader :
[2023/09/25 16:24:19] ppocr INFO:         batch_size_per_card : 1
[2023/09/25 16:24:19] ppocr INFO:         drop_last : False
[2023/09/25 16:24:19] ppocr INFO:         num_workers : 4
[2023/09/25 16:24:19] ppocr INFO:         shuffle : False
[2023/09/25 16:24:19] ppocr INFO: Global :
[2023/09/25 16:24:19] ppocr INFO:     cal_metric_during_train : True
[2023/09/25 16:24:19] ppocr INFO:     character_dict_path : ppocr/utils/en_dict.txt
[2023/09/25 16:24:19] ppocr INFO:     checkpoints : None
[2023/09/25 16:24:19] ppocr INFO:     debug : False
[2023/09/25 16:24:19] ppocr INFO:     distributed : False
[2023/09/25 16:24:19] ppocr INFO:     epoch_num : 500
[2023/09/25 16:24:19] ppocr INFO:     eval_batch_step : [0, 2000]
[2023/09/25 16:24:19] ppocr INFO:     infer_img : D:\paddle-ocr\PaddleOCR-release-2.6\train_data\data\image_0.png
[2023/09/25 16:24:19] ppocr INFO:     infer_mode : False
[2023/09/25 16:24:19] ppocr INFO:     log_smooth_window : 20
[2023/09/25 16:24:19] ppocr INFO:     max_text_length : 25
[2023/09/25 16:24:19] ppocr INFO:     pretrained_model : output/v3_en_mobile/best_accuracy.pdparams
[2023/09/25 16:24:19] ppocr INFO:     print_batch_step : 10
[2023/09/25 16:24:19] ppocr INFO:     save_epoch_step : 3
[2023/09/25 16:24:19] ppocr INFO:     save_inference_dir : None
[2023/09/25 16:24:19] ppocr INFO:     save_model_dir : ./output/v3_en_mobile
[2023/09/25 16:24:19] ppocr INFO:     save_res_path : ./output/rec/predicts_ppocrv3_en.txt
[2023/09/25 16:24:19] ppocr INFO:     use_gpu : True
[2023/09/25 16:24:19] ppocr INFO:     use_space_char : True
[2023/09/25 16:24:19] ppocr INFO:     use_visualdl : False
[2023/09/25 16:24:19] ppocr INFO: Loss :
[2023/09/25 16:24:19] ppocr INFO:     loss_config_list :
[2023/09/25 16:24:19] ppocr INFO:         CTCLoss : None
[2023/09/25 16:24:19] ppocr INFO:         SARLoss : None
[2023/09/25 16:24:19] ppocr INFO:     name : MultiLoss
[2023/09/25 16:24:19] ppocr INFO: Metric :
[2023/09/25 16:24:19] ppocr INFO:     ignore_space : False
[2023/09/25 16:24:19] ppocr INFO:     main_indicator : acc
[2023/09/25 16:24:19] ppocr INFO:     name : RecMetric
[2023/09/25 16:24:19] ppocr INFO: Optimizer :
[2023/09/25 16:24:19] ppocr INFO:     beta1 : 0.9
[2023/09/25 16:24:19] ppocr INFO:     beta2 : 0.999
[2023/09/25 16:24:19] ppocr INFO:     lr :
[2023/09/25 16:24:19] ppocr INFO:         learning_rate : 0.001
[2023/09/25 16:24:19] ppocr INFO:         name : Cosine
[2023/09/25 16:24:19] ppocr INFO:         warmup_epoch : 5
[2023/09/25 16:24:19] ppocr INFO:     name : Adam
[2023/09/25 16:24:19] ppocr INFO:     regularizer :
[2023/09/25 16:24:19] ppocr INFO:         factor : 3e-05
[2023/09/25 16:24:19] ppocr INFO:         name : L2
[2023/09/25 16:24:19] ppocr INFO: PostProcess :
[2023/09/25 16:24:19] ppocr INFO:     name : CTCLabelDecode
[2023/09/25 16:24:19] ppocr INFO: Train :
[2023/09/25 16:24:19] ppocr INFO:     dataset :
[2023/09/25 16:24:19] ppocr INFO:         data_dir : ./train_data/
[2023/09/25 16:24:19] ppocr INFO:         ext_op_transform_idx : 1
[2023/09/25 16:24:19] ppocr INFO:         label_file_list : ['./train_data/rec/train.txt']
[2023/09/25 16:24:19] ppocr INFO:         name : SimpleDataSet
[2023/09/25 16:24:19] ppocr INFO:         transforms :
[2023/09/25 16:24:19] ppocr INFO:             DecodeImage :
[2023/09/25 16:24:19] ppocr INFO:                 channel_first : False
[2023/09/25 16:24:19] ppocr INFO:                 img_mode : BGR
[2023/09/25 16:24:19] ppocr INFO:             RecConAug :
[2023/09/25 16:24:19] ppocr INFO:                 ext_data_num : 2
[2023/09/25 16:24:19] ppocr INFO:                 image_shape : [48, 320, 3]
[2023/09/25 16:24:19] ppocr INFO:                 max_text_length : 25
[2023/09/25 16:24:19] ppocr INFO:                 prob : 0.5
[2023/09/25 16:24:19] ppocr INFO:             RecAug : None
[2023/09/25 16:24:19] ppocr INFO:             MultiLabelEncode : None
[2023/09/25 16:24:19] ppocr INFO:             RecResizeImg :
[2023/09/25 16:24:19] ppocr INFO:                 image_shape : [3, 48, 320]
[2023/09/25 16:24:19] ppocr INFO:             KeepKeys :
[2023/09/25 16:24:19] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2023/09/25 16:24:19] ppocr INFO:     loader :
[2023/09/25 16:24:19] ppocr INFO:         batch_size_per_card : 8
[2023/09/25 16:24:19] ppocr INFO:         drop_last : True
[2023/09/25 16:24:19] ppocr INFO:         num_workers : 4
[2023/09/25 16:24:19] ppocr INFO:         shuffle : True
[2023/09/25 16:24:19] ppocr INFO: profiler_options : None
[2023/09/25 16:24:19] ppocr INFO: train with paddle 2.4.0 and device Place(gpu:0)
W0925 16:24:19.603299 21572 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 11.2
W0925 16:24:19.606289 21572 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
[2023/09/25 16:24:21] ppocr INFO: load pretrain successful from output/v3_en_mobile/best_accuracy
[2023/09/25 16:24:21] ppocr INFO: infer_img: D:\paddle-ocr\PaddleOCR-release-2.6\train_data\data\image_0.png
[2023/09/25 16:24:22] ppocr INFO:        result: SIKSONOPU6mm   0.9228772521018982
[2023/09/25 16:24:22] ppocr INFO: success!

**以上是使用 tools/infer_rec.py来验证模型，结果result: SIKSONOPU6mm正确**

**然后我进行了模型转换**

(test) PS D:\paddle-ocr\PaddleOCR-release-2.6> python tools/export_model.py -c "./configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml" -o Global.pretrained_model="./output/v3_en_mobile/best_accuracy.pdparams" Global.save_inference_dir="./inference_model/rec/"
C:\ProgramData\anaconda3\envs\test\lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\ProgramData\anaconda3\envs\test\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
W0925 16:25:46.523634 10848 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 11.2
W0925 16:25:46.525628 10848 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
[2023/09/25 16:25:47] ppocr INFO: load pretrain successful from ./output/v3_en_mobile/best_accuracy
[2023/09/25 16:25:48] ppocr INFO: inference model is saved to ./inference_model/rec/inference
(test) PS D:\paddle-ocr\PaddleOCR-release-2.6>

**然后我使用转换后的模型进行识别验证同样的图片（由于没有训练det模型，我使用的是现有det模型->en_PP-OCRv3_det_infer）**

(test) PS D:\paddle-ocr\PaddleOCR-release-2.6> python tools/infer/predict_system.py --image_dir="D:\paddle-ocr\PaddleOCR-release-2.6\train_data\rec\test\image_0_crop_2.jpg" --det_model_dir="D:\paddle-ocr\en_PP-OCRv3_det_infer" --rec_model_dir="D:\paddle-ocr\PaddleOCR-release-2.6\inference_model\rec\"
C:\ProgramData\anaconda3\envs\test\lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\ProgramData\anaconda3\envs\test\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[2023/09/25 16:28:36] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2023/09/25 16:28:37] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.9437923431396484
[2023/09/25 16:28:37] ppocr DEBUG: rec_res num  : 1, elapsed : 0.008970022201538086
[2023/09/25 16:28:37] ppocr DEBUG: 0  Predict time of D:\paddle-ocr\PaddleOCR-release-2.6\train_data\rec\test\image_0_crop_2.jpg: 0.953s
[2023/09/25 16:28:37] ppocr DEBUG: 0-骑:>, 0.919
Traceback (most recent call last):
  File "D:\paddle-ocr\PaddleOCR-release-2.6\tools\infer\predict_system.py", line 272, in <module>
    main(args)
  File "D:\paddle-ocr\PaddleOCR-release-2.6\tools\infer\predict_system.py", line 223, in main
    draw_img = draw_ocr_box_txt(
  File "D:\paddle-ocr\PaddleOCR-release-2.6\tools\infer\utility.py", line 433, in draw_ocr_box_txt
    img_right_text = draw_box_txt_fine((w, h), box, txt, font_path)
  File "D:\paddle-ocr\PaddleOCR-release-2.6\tools\infer\utility.py", line 461, in draw_box_txt_fine
    font = create_font(txt, (box_width, box_height), font_path)
  File "D:\paddle-ocr\PaddleOCR-release-2.6\tools\infer\utility.py", line 483, in create_font
    length = font.getsize(txt)[0]
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**输出结果是乱码的，请大佬分析下**

**我的rec模型训练参数如下：**

Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/v3_en_mobile
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/en_PP-OCRv3_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3_en.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/rec/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list:
    - ./train_data/rec/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4

**Comment by scyangjunjie** [comment]
训练图片只有30多张，而且字符内容单一
使用的是en_PP-OCRv3_rec_train预训练模型

**Comment by scyangjunjie** [comment]
我再贴一个rec训练配置文件，大佬有机会看看呗

Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/v3_en_mobile
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: .\pretrain_models\en_PP-OCRv3_rec_train\best_accuracy.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3_en.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/rec/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list:
    - ./train_data/rec/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 4

**Comment by JackieWangxiao** [comment]
如果你转换模型前的识别效果是ok的，那你应该在推理的时候，在ocr = PaddleOCR(use_angle_cls=True, rec_model_dir='E:/paddleocr/PaddleOCR-release-2.6/inference_model/rec',det_model_dir='E:\paddleocr\PaddleOCR-release-2.6\inference_model\det\Student2')这句话中，指定你的字典文件，试试

**Comment by dyhisbig** [comment]
我也遇到过，导出之前好好的，导出来模型就不行，解决方法就是换模型，换检测和识别模型，多试几个模型，还有就是增加数据集数量
