### ISSUE TITLE
padded_polygon = np.array(padding.Execute(distance)[0]) IndexError: list index out of range

### ISSUE THREAD

**Issue by xuxiansheng2018** [PaddlePaddle/PaddleOCR#11005]
当我训练ppocrv4_student.yml文件的时候 出现以下问题？请问该如何解决？
[2023/09/26 21:17:23] ppocr ERROR: When parsing line crop_img/DL54532.jpg       [{"transcription": "kV311东欣线", "points": [[1407, 782], [1521, 752], [1525, 772], [1413, 806]], "difficult": true}, {"transcription": "20号", "points": [[1410, 815], [1508, 793], [1519, 837], [1421, 860]], "difficult": false}, {"transcription": "20号", "points": [[1178, 885], [1252, 858], [1264, 891], [1189, 917]], "difficult": false}, {"transcription": "35kV324耀华线", "points": [[1169, 858], [1280, 821], [1283, 839], [1167, 875]], "difficult": true}]
, error happened with msg: Traceback (most recent call last):
  File "/home/xuguozhu/project/PaddleOCR-dygraph/ppocr/data/simple_dataset.py", line 153, in __getitem__
    outs = transform(data, self.ops)
  File "/home/xuguozhu/project/PaddleOCR-dygraph/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/xuguozhu/project/PaddleOCR-dygraph/ppocr/data/imaug/make_border_map.py", line 64, in __call__
    self.draw_border_map(text_polys[i], canvas, mask=mask)
  File "/home/xuguozhu/project/PaddleOCR-dygraph/ppocr/data/imaug/make_border_map.py", line 85, in draw_border_map
    padded_polygon = np.array(padding.Execute(distance)[0])
IndexError: list index out of range

**Comment by xuxiansheng2018** [comment]
训练在继续执行 ，但是中途会有这样的error ，请问该如何解决

**Comment by wzgwy** [comment]
请问这个问题解决了吗？我也遇到这个问题

**Comment by wangchenhong** [comment]
请问问题解决了吗？我也遇到了一样的问题

**Comment by uuleaf** [comment]
这个问题遇到的最多了

**Comment by ariefwijaya** [comment]
I have this problem

**Comment by muthu-28** [comment]
i have this problem

**Comment by cuntoushifu** [comment]
yeah you have

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by June-Hall** [comment]
我的解决方案，不知道有没有帮助
```
# in PaddleOCR/ppocr/data/imaug/make_border_map.py
padded_polygon = np.array(padding.Execute(distance)[0])
```

```
# updated in PaddleOCR/ppocr/data/imaug/make_border_map.py
offset_polygons = padding.Execute(distance)
if not offset_polygons:
    return
padded_polygon = np.array(offset_polygons[0])
```
