### ISSUE TITLE
按照识别数据集格式制作的数据集，在训练文本识别模型的时候大部分数据报错

### ISSUE THREAD

**Issue by juneana123** [PaddlePaddle/PaddleOCR#11000]
[2023/09/26 11:35:15] ppocr INFO: epoch: [1/50], global_step: 10, lr: 0.000001, acc: 0.000000, norm_edit_dis: 0.000940, loss: 289.598267, avg_reader_cost: 0.40490 s, avg_batch_cost: 0.92538 s, avg_samples: 64.0, ips: 69.16067 samples/s, eta: 10:28:20
[2023/09/26 11:35:19] ppocr INFO: epoch: [1/50], global_step: 20, lr: 0.000003, acc: 0.000000, norm_edit_dis: 0.000782, loss: 287.031311, avg_reader_cost: 0.00022 s, avg_batch_cost: 0.42367 s, avg_samples: 64.0, ips: 151.06142 samples/s, eta: 7:37:53
[2023/09/26 11:35:21] ppocr ERROR: When parsing line 31536.jpg  2015
, error happened with msg: Traceback (most recent call last):
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/simple_dataset.py", line 136, in __getitem__
    data['ext_data'] = self.get_ext_data()
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/simple_dataset.py", line 110, in get_ext_data
    data = transform(data, load_data_ops)
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform
    data = op(data)
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/imaug/operators.py", line 49, in __call__
    img) > 0, "invalid input 'img' in DecodeImage"
AssertionError: invalid input 'img' in DecodeImage

[2023/09/26 11:35:26] ppocr ERROR: When parsing line 65208.jpg  R
, error happened with msg: Traceback (most recent call last):
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/simple_dataset.py", line 136, in __getitem__
    data['ext_data'] = self.get_ext_data()
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/simple_dataset.py", line 110, in get_ext_data
    data = transform(data, load_data_ops)
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform
    data = op(data)
  File "/media/newvolume/datasets/PaddleOCR/ppocr/data/imaug/operators.py", line 49, in __call__
    img) > 0, "invalid input 'img' in DecodeImage"
AssertionError: invalid input 'img' in DecodeImage

[2023/09/26 11:35:26] ppocr INFO: epoch: [1/50], global_step: 30, lr: 0.000006, acc: 0.000000, norm_edit_dis: 0.000569, loss: 275.064331, avg_reader_cost: 0.26659 s, avg_batch_cost: 0.69090 s, avg_samples: 64.0, ips: 92.63215 samples/s, eta: 7:41:28

**Comment by juneana123** [comment]
31536.jpg	2015
其中一个报错的标注
