### ISSUE TITLE
paddleserving模式部署，最后一步客户端执行报错

### ISSUE THREAD

**Issue by LiuWenSheng** [PaddlePaddle/PaddleOCR#1101]
使用Paddle Serving 模式部署服务，使用的模型分别为 `ch_ppocr_mobile_v1.1_cls_infer  `，  `ch_ppocr_server_v1.1_det_infer  ` ，`ch_ppocr_server_v1.1_rec_infer` 部署完成之后使用客户端预测出错。

最后控制台报错的代码为：
```shell
(paddle-serving) [deployer@s2 pdserving]$ python pdserving_client.py testorc/
2020-11-04 15:14:47,970-INFO: Predict time of testorc/1.jpeg: 5.535s
2020-11-04 15:14:47,970-INFO: Fetch names should not be empty or out of saved fetch list.
Traceback (most recent call last):
  File "pdserving_client.py", line 117, in <module>
    main(image_path)
  File "pdserving_client.py", line 96, in main
    draw_img = draw_server_result(image_file, res)
  File "pdserving_client.py", line 45, in draw_server_result
    keys = res[0].keys()
AttributeError: 'str' object has no attribute 'keys'

```
我没有修改过这个client文件，而且还强制更新了几次，都是报这个错误

**Comment by MissPenguin** [comment]
paddle serving这两天有点bug，先用hub serving吧😳

**Comment by LiuWenSheng** [comment]
好的

**Comment by kylewangt** [comment]
执行python3 pipeline_http_client.py后追踪pipe.tracer文件
2021-06-04 03:48:12,429 ==================== TRACER ======================
2021-06-04 03:48:12,430 Channel (server worker num[10]):
2021-06-04 03:48:12,432 	chl0(In: ['@DAGExecutor'], Out: ['det']) size[4/0]
2021-06-04 03:48:12,434 	chl1(In: ['det'], Out: ['rec']) size[0/0]
2021-06-04 03:48:12,434 	chl2(In: ['rec'], Out: ['@DAGExecutor']) size[0/0]
一直没有识别结果，请问是啥问题呢？

**Comment by kylewangt** [comment]
另外，执行python3 web_service.py,在log.txt中显示如下内容
/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/pipeline_server.py:341: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf = yaml.load(f.read())
2021/06/04 02:50:49 start proxy service
这个是表示服务启动成功了吗？
