### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [6, 96, 3, 20] and the shape of Y = [6, 96, 4, 20].

### ISSUE THREAD

**Issue by baudneo** [PaddlePaddle/PaddleOCR#11035]
The image is a numpy.ndarray. EasyOCR has no problems with it.

code:

```
from paddleocr import PaddleOCR
import cv2

paddleocr = PaddleOCR(
                use_angle_cls=True,
                lang="en",
                det_model_dir=str(
                    get_global_config().config.system.variable_data_path / ".ocr/models"
                ),
                rec_model_dir=str(
                    get_global_config().config.system.variable_data_path / ".ocr/models"
                ),
                cls_model_dir=str(
                    get_global_config().config.system.variable_data_path
                    / ".ocr/models"
                ),
            )
image = <cv2 jpeg encoded image in numpy.ndarray>
result = paddleocr.ocr(image, cls=True)
```

```
 '10/03/23 20:12:43.0271' uvicorn.error[203165] ERROR h11_impl:413 -> Exception in ASGI application
  Traceback (most recent call last):
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
      result = await app(  # type: ignore[func-returns-value]
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
      return await self.app(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
      await super().__call__(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
      await self.middleware_stack(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
      raise exc
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
      await self.app(scope, receive, _send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
      raise exc
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
      await self.app(scope, receive, sender)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
      raise e
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
      await self.app(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
      await route.handle(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
      await self.app(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
      response = await func(request)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
      raw_response = await run_endpoint_function(
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
      return await dependant.call(**values)
    File "/opt/zm_ml/src/zm_ml/Server/app.py", line 430, in get_annotated_image
      detections, images = await detect(hints_, [image], return_image=True)
    File "/opt/zm_ml/src/zm_ml/Server/app.py", line 296, in detect
      img_dets.append(await detector.detect(image))
    File "/opt/zm_ml/src/zm_ml/Server/Models/config.py", line 1420, in detect
      return await self.model.detect(images)
    File "/opt/zm_ml/src/zm_ml/Server/ML/Detectors/onnx_runtime.py", line 175, in detect
      ocr_results = self.paddle_ocr(cropped_image)
    File "/opt/zm_ml/src/zm_ml/Server/ML/file_locks.py", line 159, in paddle_ocr
      result = self.paddleocr.ocr(image, cls=True)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 661, in ocr
      dt_boxes, rec_res, _ = self.__call__(img, cls)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/tools/infer/predict_system.py", line 105, in __call__
      rec_res, elapse = self.text_recognizer(img_crop_list)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/tools/infer/predict_rec.py", line 616, in __call__
      self.predictor.run()
  ValueError: In user code:

      File "tools/export_model.py", line 187, in <module>
        main()
      File "tools/export_model.py", line 179, in main
        sub_model_save_path, logger)
      File "tools/export_model.py", line 106, in export_single_model
        paddle.jit.save(model, save_path)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
        func(layer, path, input_spec, **configs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/decorator.py", line 232, in fun
        return caller(func, *(extras + args), **kw)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
        return wrapped_func(*args, **kwargs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
        return func(*args, **kwargs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 857, in save
        inner_input_spec, with_hook=with_hook)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528,
   in concrete_program_specify_input_spec
        *desired_input_spec, with_hook=with_hook)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436,
   in get_concrete_program
        concrete_program, partial_program_layer = self._program_cache[cache_key]
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801,
   in __getitem__
        self._caches[item_id] = self._build_once(item)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790,
   in _build_once
        **cache_key.kwargs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/decorator.py", line 232, in fun
        return caller(func, *(extras + args), **kw)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
        return wrapped_func(*args, **kwargs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
        return func(*args, **kwargs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733,
   in from_func_spec
        outputs = static_func(*inputs)
      File "/tmp/tmpnwredzuu.py", line 30, in forward
        false_fn_1, (x,), (x,), (x,))
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211,
  in convert_ifelse
        out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257,
  in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
      File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 82, in forward
        x = self.neck(x)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
        return self._dygraph_call_func(*inputs, **kwargs)
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
        outputs = self.forward(*inputs, **kwargs)
      File "/paddle/debug/PaddleOCR/ppocr/modeling/necks/db_fpn.py", line 247, in forward
        in5, scale_factor=2, mode="nearest", align_mode=1)  # 1/16
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
        attrs={'axis': axis})
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
        attrs=kwargs.get("attrs", None))
      File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
        for frame in traceback.extract_stack():

      InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [6, 96, 3, 20] a
  nd the shape of Y = [6, 96, 4, 20]. Received [3] in X is not equal to [4] in Y at i:2.
        [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_a
  rray[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h
  :86)
        [operator < elementwise_add > error]

```

**Comment by baudneo** [comment]
Ubuntu 22.04 AMD64

Python 3.10 with paddleocr in a venv

**Comment by XinAn9508** [comment]
same problem. how to fix it? thanks!

**Comment by Asher018** [comment]
i couldn't solve it yet, have you found it?

> same problem. how to fix it? thanks!
