### ISSUE TITLE
PPOCRLabel:- ppocr WARNING: When args.layout is false, args.ocr is automatically set to false

### ISSUE THREAD

**Issue by AbhishekPSI7042** [PaddlePaddle/PaddleOCR#11056]
Hi, I'm getting this error when I run the PPOCRLabel.py, please resolve this issue.

[2023/10/10 11:33:25] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\PPOCRLabel.py", line 2840, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\PPOCRLabel.py", line 112, in __init__
    result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\anaconda3\envs\env\Lib\site-packages\paddleocr\paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\..\ppstructure\predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\..\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\..\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\..\ppstructure\table\predict_structure.py", line 120, in __call__
    data = transform(data, self.preprocess_op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\..\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
           ^^^^^^^^
  File "C:\Users\dell\Desktop\YoloV4\PaddleOCR\PPOCRLabel\..\ppocr\data\imaug\operators.py", line 94, in __call__
    img.astype('float32') * self.scale - self.mean) / self.std
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)

**Comment by hz-1** [comment]
I meet the same problem,Did you fix it ?

**Comment by AbhishekPSI7042** [comment]
Yes, go to the paddlerocr directory, through cmd and then just write the PPOCRLABEL folder name and run it will work @hz-1 .

**Comment by hz-1** [comment]
can't find '__main__' module in 'PPOCRLabel'

**Comment by AbhishekPSI7042** [comment]
run the whole folder write folder name in cmd and press enter.

**Comment by hz-1** [comment]
Done!thank you!

**Comment by 555myhair** [comment]
您好，我没看明白这是什么意思。

**Comment by 555myhair** [comment]
@hz-1 您好，您这个是怎么解决的？上面的过程我看不太明白

**Comment by hz-1** [comment]
> @hz-1 您好，您这个是怎么解决的？上面的过程我看不太明白
直接cd到PPOCRLabel目录下，然后运行python PPOCRLabel.py --lang ch就可以了

**Comment by hz-1** [comment]
@555myhair 直接cd到PPOCRLabel目录下，然后运行python PPOCRLabel.py --lang ch就可以了

**Comment by 555myhair** [comment]
@hz-1 试过了，还是这个报错

**Comment by hz-1** [comment]
@555myhair 那你试试上面那种到paddleocr目录下，然后命令行run PPOCRLabel

**Comment by 555myhair** [comment]
这个也试过

**Comment by 555myhair** [comment]
有没有一个软件可以代替PPOCRLabel标注啊？ @hz-1

**Comment by hz-1** [comment]
@555myhair 你要去微调paddleocr的话建议还是用PPOCRLabel,因为它打标是先用paddleocr的模型去自动识别，然后你可以看哪些图片标的不好，去做手动修正，这样得到的数据去训paddleocr在你的数据上的效果会明显提升的

**Comment by 555myhair** [comment]
我下载的是2.7版本的程序 一直报这个错，网上能找的方法都找了还是不行。 后来又下载了2.7.1 没有这个报错，但是一标注就闪退 @hz-1

**Comment by hz-1** [comment]
@555myhair 我是2.7.0.3版本的paddleocr

**Comment by 555myhair** [comment]
找不到这个版本的安装包~
