### ISSUE TITLE
下载的docker运行不了

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/PaddleOCR#1106]
docker_pdocr_cuda10.tar.gz

下载解压，load后，创建容器，安装paddlepaddle，paddleocr，但是运行不了，出现异常

安装的是：pip install paddlepaddle-gpu==2.0.0rc0 -i https://mirror.baidu.com/pypi/simple

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "src/test_baidu_ocr.py", line 1, in <module>
    from paddleocr import PaddleOCR,draw_ocr
  File "/opt/ocr/python/lib/python3.7/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/opt/ocr/python/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "/opt/ocr/python/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 21, in <module>
    import tools.infer.utility as utility
  File "/opt/ocr/python/lib/python3.7/site-packages/paddleocr/tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "/opt/ocr/python/lib/python3.7/site-packages/paddleocr/ppocr/utils/utility.py", line 19, in <module>
    from paddle import fluid
  File "/opt/ocr/python/lib/python3.7/site-packages/paddle/__init__.py", line 34, in <module>
    from .fluid import monkey_patch_variable
  File "/opt/ocr/python/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/opt/ocr/python/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/opt/ocr/python/lib/python3.7/site-packages/paddle/fluid/core.py", line 285, in <module>
    raise e
  File "/opt/ocr/python/lib/python3.7/site-packages/paddle/fluid/core.py", line 254, in <module>
    from .core_avx import *
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /opt/ocr/python/lib/python3.7/site-packages/paddle/fluid/co

**Comment by LDOUBLEV** [comment]
可以试一下docker pull下来的景象：

sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev /bin/bash

**Comment by cole-dda** [comment]
如果是paddlepaddle-gpu==2.0.0b0 可以正常运行，rc0就不可以。是否可以在安装说明中，说明需要使用哪一个版本的cuda和cudnn。

**Comment by littletomatodonkey** [comment]
你好，目前建议使用cuda10.2及以上的版本，对应显卡驱动如下。cudnn为7.6.4+即可

在cuda10.1时，建议显卡驱动版本大于等于418.39；在使用cuda10.2时，建议显卡驱动版本大于440.33，更多cuda版本与要求的显卡驱动版本可以参考链接。

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
