### ISSUE TITLE
paddle_gpu2.4.2post117paddleocr2.7.0.2cuda11.7 导入 ocr_v4_server 版模型报错 CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Droliven** [PaddlePaddle/PaddleOCR#11061]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centeros
- 版本号/Version：Paddle：paddle_gpu2.4.2post117  PaddleOCR：2.7.0.2 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

(1) 环境信息：paddlepaddle_gpu==2.4.2.post117, paddleocr==2.7.0.2, python3.8

(2) 调用 paddleocr

```
import os
import time
from paddleocr import PaddleOCR, draw_ocr

filepath = r"/ossfs/workspace/test.png"
paddle_root=r"/ossfs/workspace/text_extractor/libs/model_zoos/paddle_ocr/whl"

# # middle
# ocr_model = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True, show_log=False,
#                 det_db_box_thresh=0.1, use_dilation=True,
#                 det_model_dir=os.path.join(paddle_root, "det", "ch", 'ch_PP-OCRv4_det_infer'),
#                 cls_model_dir=os.path.join(paddle_root, "cls", 'ch_ppocr_mobile_v2.0_cls_infer'),
#                 rec_model_dir=os.path.join(paddle_root, "rec", "ch", 'ch_PP-OCRv4_rec_infer'))
# large
ocr_model = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True, show_log=False,
                det_db_box_thresh=0.1, use_dilation=True,
                det_model_dir=os.path.join(paddle_root, "det", "ch", 'ch_PP-OCRv4_server_det_infer'),
                cls_model_dir=os.path.join(paddle_root, "cls", 'ch_ppocr_mobile_v2.0_cls_infer'),
                rec_model_dir=os.path.join(paddle_root, "rec", "ch", 'ch_PP-OCRv4_rec_server_infer'))

t1 = time.time()
for i in range(10):
    result = ocr_model.ocr(img=filepath, det=True, rec=True, cls=True)[0]
t2 = time.time() #0.49456236362457273
print((t2-t1) / 10)
print(result)
```

(3) 如果是导入 midddle 模型，可以正常运行，导入 server 会报错

```
Traceback (most recent call last):
  File "text_extractor/test.py", line 23, in <module>
    result = ocr_model.ocr(img=filepath, det=True, rec=True, cls=True)[0]
  File "/opt/conda/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 648, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/opt/conda/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/opt/conda/lib/python3.8/site-packages/paddleocr/tools/infer/predict_det.py", line 245, in __call__
    self.predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 288, in <module>
      main()
    File "tools/export_model.py", line 284, in main
      model, arch_config, save_path, logger, input_shape=input_shape)
    File "tools/export_model.py", line 197, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 857, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpjvb2gofp.py", line 28, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/workspace/huangjun12/Projects/PP-OCRv4/pr/check_acc/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpsr4zekry.py", line 45, in forward
      for_loop_condition_0, for_loop_body_0, [__for_loop_var_index_0, i, x])
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/workspace/huangjun12/Projects/PP-OCRv4/pr/check_acc/PaddleOCR/ppocr/modeling/backbones/rec_hgnet.py", line 252, in forward
      x = stage(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/workspace/huangjun12/Projects/PP-OCRv4/pr/check_acc/PaddleOCR/ppocr/modeling/backbones/rec_hgnet.py", line 172, in forward
      x = self.blocks(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/container.py", line 98, in forward
      input = layer(input)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/workspace/huangjun12/Projects/PP-OCRv4/pr/check_acc/PaddleOCR/ppocr/modeling/backbones/rec_hgnet.py", line 125, in forward
      x = self.att(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/workspace/huangjun12/Projects/PP-OCRv4/pr/check_acc/PaddleOCR/ppocr/modeling/backbones/rec_hgnet.py", line 76, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/conv.py", line 678, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/conv.py", line 169, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED. 
      [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:519)
      [operator < conv2d_fusion > error]
```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no): yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by JettaLee** [comment]
We met the same issue

**Comment by Droliven** [comment]
degrade the cudnn version <= 8.5

**Comment by maoruishan** [comment]
cuda11.8 + cudnn8.6

**Comment by Thunderltx** [comment]
> degrade the cudnn version <= 8.5

Thank you! It's worked!
