### ISSUE TITLE
文字角度和文字识别预测相关问题

### ISSUE THREAD

**Issue by strWuYaoJu** [PaddlePaddle/PaddleOCR#1107]
在训练文字角度、文字识别得到对应的模型后，执行以下指令：
python3 tools/infer_cls.py -c configs/cls/cls_mv3.yml -o TestReader.infer_img="./train_data/cls/test/"  Global.checkpoints="./output/cls_mv3/best_accuracy"
或
python3 tools/infer_rec.py -c configs/rec/rec_chinese_common_train_v1.1.yml -o TestReader.infer_img="./train_data/rec/test/"  Global.checkpoints="./output/rec_CRNN/best_accuracy"

报类似的错：
Traceback (most recent call last):
  File "tools/infer_cls.py", line 114, in <module>
    main()
  File "tools/infer_cls.py", line 54, in main
    program.merge_config(FLAGS.opt)
  File "tools/../tools/program.py", line 126, in merge_config
    assert (sub_key in cur)
AssertionError

或

Traceback (most recent call last):
  File "tools/infer_rec.py", line 176, in <module>
    main()
  File "tools/infer_rec.py", line 53, in main
    program.merge_config(FLAGS.opt)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 126, in merge_config
    assert (sub_key in cur)
AssertionError

**Comment by LDOUBLEV** [comment]
TestReader.infer_img 替换为 Global.infer_img吧，稍后提个PR修一下报错提示和配置文件

**Comment by littletomatodonkey** [comment]
#1113

**Comment by strWuYaoJu** [comment]
@LDOUBLEV 改成 Global.infer_img可以了，谢谢哦！
