### ISSUE TITLE
fastdeploy在windows server 2012无法运行

### ISSUE THREAD

**Issue by mrg79433283** [PaddlePaddle/PaddleOCR#11116]
- 系统环境/System Environment：windows server 2012 R2 standard,  Anaconda3 2022.10，python3.8, cpu模式，无gpu
- 版本号/Version：Paddle：PaddleOCR： 
- 问题相关组件/Related components：fastdeploy
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
python3.8和python3.10都试过，都是在c_lib_wrap中调用  from .libs.fastdeploy_main import * 时出现报错。
网络上搜索的方法：1. server 2012系统的桌面体验功能，已安装；
                                 2. vc运行库已安装2015-2022，也无效
                            

- Traceback (most recent call last):
  File "C:\Users\MRG\anaconda3\envs\paddleX38\lib\site-packages\fastdeploy\c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: DLL load failed while importing fastdeploy_main: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MRG\Desktop\FastDeploy_Windows_Python_SDK_v1.1.0_x86_64__PP-OCRv4\example\infer.py", line 15, in <module>
    import fastdeploy as fd
  File "C:\Users\MRG\anaconda3\envs\paddleX38\lib\site-packages\fastdeploy\__init__.py", line 122, in <module>
    from .c_lib_wrap import (
  File "C:\Users\MRG\anaconda3\envs\paddleX38\lib\site-packages\fastdeploy\c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: DLL load failed while importing fastdeploy_main: 找不到指定的模块。

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

**Comment by mrg79433283** [comment]
已经尝试在server 2012的环境下，使用vs2019、python3.9重新自己编译获得fastdeploy的wheel文件，重新测试功能仍然在 fastdeploy_main提示找不到指定模块。

**Comment by mrg79433283** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/31495221/7b38f3d2-46b0-4a38-9403-bf1e8b13a0ab)
该问题已自行解决。在server上使用c++进行自编译fastdeploy时，发现加上enable_ort_backend后无法通过编译，在ort相关函数内报类型错误，将其关闭就通过。
所以尝试在用python自编译时把ort和paddle都关闭了，如图所示；因为仅需要使用openvino，只开了enable_openvino_backend。
