### ISSUE TITLE
PPOCRV3 train recognition model "list index out of range"

### ISSUE THREAD

**Issue by XuanTung4501** [PaddlePaddle/PaddleOCR#11124]
When I started training the model, I got "list index out of range" message, please give me some advice:
[2023/10/23 02:46:08] ppocr INFO:         scales : [[320, 32], [320, 48], [320, 64]]
[2023/10/23 02:46:08] ppocr INFO: profiler_options : None
[2023/10/23 02:46:08] ppocr INFO: train with paddle 2.5.1 and device Place(gpu:0)
[2023/10/23 02:46:08] ppocr INFO: Initialize indexs of datasets:['/content/PaddleOCR/dataset/train_label.txt']
list index out of range
[2023/10/23 02:46:08] ppocr INFO: Initialize indexs of datasets:['/content/PaddleOCR/dataset/test_label.txt']
W1023 02:46:08.893149  1861 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.8

**Comment by wangchenhong** [comment]
I also encountered this problem, and the final output is as follows:
[2023/10/23 10:27:49] ppocr INFO: load pretrain successful from ./pretrain_models/ch_PP-OCRv4_rec_server_train/best_accuracy
[2023/10/23 10:27:49] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Exception in thread Thread-1 (_thread_loop):
Traceback (most recent call last):
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 623, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 638, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 14231
Traceback (most recent call last):
  File "/home/project_OCR/PaddleOCR/tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/project_OCR/PaddleOCR/tools/train.py", line 198, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/project_OCR/PaddleOCR/tools/program.py", line 269, in train
    for idx, batch in enumerate(train_dataloader):
  File "/home/project_OCR/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
    self._reader.read_next_list()[0])
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:175)

**Comment by wangchenhong** [comment]
Strangely enough, I had no problems when training the detection model, but these problems arose when training the recognition model

**Comment by AMALVAASISH** [comment]
did you get the solution ?
