### ISSUE TITLE
微调出现错误提示

### ISSUE THREAD

**Issue by hz-1** [PaddlePaddle/PaddleOCR#11138]
Traceback (most recent call last):
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/__main__.py", line 17, in <module>
    launch()
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/main.py", line 304, in launch
    c.run()
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/controllers/controller.py", line 74, in run
    self.build_pod()
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/controllers/collective.py", line 48, in build_pod
    return self._build_pod_with_master()
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/controllers/collective.py", line 204, in _build_pod_with_master
    selected_dev_list = self.ctx.node.device.get_selected_devices(
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/context/device.py", line 86, in get_selected_devices
    return [str(self._labels.index(d)) for d in devs]
  File "/home/jsj201-5/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/distributed/launch/context/device.py", line 86, in <listcomp>
    return [str(self._labels.index(d)) for d in devs]
ValueError: substring not found

**Comment by idontkonwher** [comment]
麻烦问下这个问题有什么进展吗？

**Comment by vtmjapandev** [comment]
@hz-1 Have anyone fix this issue?

**Comment by Scry-SarthKanani** [comment]
@hz-1 @vtmjapandev  Has anyone fixed this yet?

**Comment by SirLaughsALot007** [comment]
@hz-1 Have anyone fix this issue?

**Comment by sathyagorla** [comment]
Have anyone fix this issue?

**Comment by lsch0lz** [comment]
Issue seems to be still around for:
```python3 -m paddle.distributed.launch --gpus "0,1,2" tools/train.py -c configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml```

**Comment by pbehjatii** [comment]
you need to make sure that you have installed paddlepaddle for gpu. to make sure you can write these commands in the terminal import paddle and paddle.utils.run_check(). please check https://www.paddlepaddle.org.cn/en.
