### ISSUE TITLE
NameError: name 'libpaddle' is not defined  没人解决吗  操蛋的了

### ISSUE THREAD

**Issue by zbbwss** [PaddlePaddle/PaddleOCR#11156]
Error: Can not import paddle core while this file exists: C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\ocr\src\ocr.py", line 6, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\framework\random.py", line 17, in <module>
    from paddle import fluid
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\paddle\fluid\core.py", line 351, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

**Comment by Gmgge** [comment]
请检测你的机器cpu是否支持AVX指令 cat /proc/cpuinfo | grep -i avx，paddlepaddle2.5以及之后，不在支持noavx设备。

如果不支持请根据以下进行安装，具体文档可参考[官方说明](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/linux-pip.html)
首先使用如下命令将 wheel 包下载到本地：
cpu、mkl 版本 noavx 机器安装：
python3 -m pip download paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps
cpu、openblas 版本 noavx 机器安装：
python3 -m pip download paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps

**Comment by tjubjy** [comment]
我也遇到同样的问题，最后尝试python换成3.7、gcc、g++换成7.5.0可以解决。

**Comment by Shubham4471** [comment]
Error: Can not import paddle core while this file exists: [c:\Users\Jyoti.Chounsaste\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddle\base\libpaddle.pyd](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/libpaddle.pyd)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File [c:\Users\Jyoti.Chounsaste\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddle\base\core.py:268](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:268)
    [267](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:267) try:
--> [268](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:268)     from . import libpaddle
    [270](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:270)     if avx_supported() and not libpaddle.is_compiled_with_avx():

ImportError: DLL load failed while importing libpaddle: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
Cell In[1], [line 1](vscode-notebook-cell:?execution_count=1&line=1)
----> [1](vscode-notebook-cell:?execution_count=1&line=1) from paddleocr import PaddleOCR
      [3](vscode-notebook-cell:?execution_count=1&line=3) ocr = PaddleOCR()
      [5](vscode-notebook-cell:?execution_count=1&line=5) print(ocr)

File [c:\Users\Jyoti.Chounsaste\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddleocr\__init__.py:14](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:14)
      [1](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:1) # Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
      [2](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:2) #
      [3](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:3) # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     [12](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:12) # See the License for the specific language governing permissions and
     [13](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:13) # limitations under the License.
---> [14](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddleocr/__init__.py:14) from .paddleocr import *
...
    [378](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:378)         "you should reinstall paddlepaddle with no-avx core.\n"
    [379](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:379)     )
    [380](file:///C:/Users/Jyoti.Chounsaste/AppData/Local/Programs/Python/Python311/Lib/site-packages/paddle/base/core.py:380) raise e

NameError: name 'libpaddle' is not defined
python -m pip download paddlepaddle==2.4.2 
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.4.2 (from versions: 2.5.1, 2.5.2, 2.6.0, 2.6.1)      
ERROR: No matching distribution found for paddlepaddle==2.4.2
I am using python 3.11

**Comment by 12dc32d** [comment]
> 我也遇到同样的问题，最后尝试python换成3.7、gcc、g++换成7.5.0可以解决。

大哥能详细描述一下吗，我打包后的exe可执行文件在自己的电脑上能够运行，但是在其它电脑上点开后立即关闭结束进程，cmd中的报错同样ImportError: DLL load failed while importing libpaddle: 动态链接库(DLL)初始化例程失败。和 NameError: name 'libpaddle' is not defined。 
有没有办法解决客户环境问题？（我用的python3.11）

**Comment by 12dc32d** [comment]
我是ai开发实习，问题已经解决了。
这个内容涉及到DLL文件，是一种对共享文件的使用。新版的Windows系统里基本都有，但是阉割版和旧版会出现问题（因为缺少某些dll文件）。同时python语言包是可以打包进项目里的。
