### ISSUE TITLE
车牌识别模型：检测和识别的量化训练无法进行

### ISSUE THREAD

**Issue by yuanxinliang** [PaddlePaddle/PaddleOCR#11172]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio、Linux
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.5.0 问题相关组件/Related components：ch_PP-OCRv3_det
- 运行指令/Command Code：python deploy/slim/quantization/quant.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml
- 完整报错/Complete Error Message：
[11-01 18:34:51 MainThread @logger.py:242] Argv: deploy/slim/quantization/quant.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml
[11-01 18:34:51 MainThread @utils.py:79] WRN paddlepaddle version: 2.3.2. The dynamic graph version of PARL is under development, not fully tested and supported
Traceback (most recent call last):
  File "deploy/slim/quantization/quant.py", line 42, in <module>
    from paddleslim.dygraph.quant import QAT
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/__init__.py", line 17, in <module>
    from paddleslim import prune
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/__init__.py", line 16, in <module>
    from .pruner import *
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 20, in <module>
    from ..core import VarWrapper, OpWrapper, GraphWrapper
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/__init__.py", line 19, in <module>
    from ..core import dygraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 9, in <module>
    from ..common import get_logger
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/common/__init__.py", line 21, in <module>
    from .server import Server
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/common/server.py", line 28, in <module>
    from .rl_controller.utils import add_grad, ConnectMessage
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/common/rl_controller/__init__.py", line 19, in <module>
    import parl
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/__init__.py", line 47, in <module>
    from parl.remote import remote_class, connect
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/__init__.py", line 19, in <module>
    from parl.remote.remote_decorator import *
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/remote_decorator.py", line 19, in <module>
    from parl.remote.remote_wrapper import RemoteWrapper
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/remote_wrapper.py", line 21, in <module>
    from parl.remote.communication import loads_argument, loads_return,\
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/communication.py", line 38, in <module>
    context = pyarrow.default_serialization_context()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyarrow/__init__.py", line 317, in __getattr__
    "module 'pyarrow' has no attribute '{0}'".format(name)
AttributeError: module 'pyarrow' has no attribute 'default_serialization_context'

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by yuanxinliang** [comment]
pyarrow的版本问题，需要换成11.0.0版本。

原因：
pyarrow.default_serialization_context()在pyarrow：12.0.0版本中已经被移除
