### ISSUE TITLE
使用pyinstaller打包的时候出现问题。

### ISSUE THREAD

**Issue by zhuimengren-a11u** [PaddlePaddle/PaddleOCR#11189]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.5.2
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

我有一个ocr的小demo，基于paddleocr来实现的。现在在使用pyinstaller打包之后，在运行 就会出现
Traceback (most recent call last):
  File "ID_card.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddleocr/__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddleocr/paddleocr.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/framework/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/framework/random.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/framework.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/core.py", line 394, in <module>
  File "paddle/fluid/core.py", line 386, in set_paddle_lib_path
TypeError: sequence item 0: expected str instance, NoneType found
[3709027] Failed to execute script 'ID_card' due to unhandled exception!
请问这是什么样的问题，我在打包之前都可以执行程序，打包之后就出错了。

**Comment by Edmond-Lee-Zse-Wong** [comment]
我也是封装之后就疯狂报错，from paddleocr import PaddleOCR 就报错了，显示file not found，不知道你有没有遇到过同样的问题

**Comment by TurboTu** [comment]
请问解决了吗，手工替换库也没成功，同样的问题

**Comment by Edmond-Lee-Zse-Wong** [comment]
> 请问解决了吗，手工替换库也没成功，同样的问题
试试看这个行不行
#11490

**Comment by Edmond-Lee-Zse-Wong** [comment]
@TurboTu 
试试看下面这个方法能不能行
#11490
