### ISSUE TITLE
KIE RE 模型导出报错，请问该如何处理，谢谢！

### ISSUE THREAD

**Issue by zzgHiker** [PaddlePaddle/PaddleOCR#11180]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`Mac Book（x86)`
- 版本号/Version：Paddle：`2.5.1`  PaddleOCR：`2.7.1`  PaddleNLP: `2.6.1` 问题相关组件/Related components：`tools/export_model.py`
- 运行指令/Command Code：
参考[RE模型导出文档](https://github.com/PaddlePaddle/PaddleOCR/blob/344b7594e49f0fbb4d6578bd347505664ed728bf/doc/doc_ch/algorithm_kie_vi_layoutxlm.md)进行导出推理模型
```
# 下载并解压预训练模型到目录：./models/
wget https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/re_vi_layoutxlm_xfund_pretrained.tar
tar -xf re_vi_layoutxlm_xfund_pretrained.tar

# 导出模型
python3 tools/export_model.py \
-c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
-o \
   Architecture.Backbone.checkpoints=./models/re_vi_layoutxlm_xfund_pretrained/best_accuracy \
   Global.save_inference_dir=./output/inference/re_vi_layoutxlm_infer
```

- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "~/PaddleOCR/tools/export_model.py", line 289, in <module>
    main()
  File "~/PaddleOCR/tools/export_model.py", line 284, in main
    export_single_model(
  File "~/PaddleOCR/tools/export_model.py", line 198, in export_single_model
    paddle.jit.save(model, save_path)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/api.py", line 752, in wrapper
    func(layer, path, input_spec, **configs)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/api.py", line 1043, in save
    static_func.concrete_program_specify_input_spec(
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 709, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 589, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1249, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1193, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1070, in from_func_spec
    error_data.raise_new_exception()
  File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddle/jit/dy2static/error.py", line 452, in raise_new_exception
    raise new_exception from None
AttributeError: In transformed code:

    File "~/PycharmProjects/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
        if self.use_backbone:
    File "~/PycharmProjects/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 87, in forward
        x = self.backbone(x)
    File "~/PycharmProjects/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
        x = self.model(
    File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
        loss, pred_relations = self.extractor(sequence_output, entities, relations)
    File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
        relations, entities = self.build_relation(relations, entities)
    File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1153, in build_relation
        for b in range(batch_size):
    File "~/miniconda3/envs/paddle-env/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1189, in build_relation
        positive_mask = paddle.any(mask, axis=0) is True
        positive_relations = positive_relations[positive_mask]
        if negative_mask.sum() > 0:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            reordered_relations = paddle.concat([positive_relations, negative_relations])
        else:


    AttributeError: 'bool' object has no attribute 'sum'

```

**Comment by zzgHiker** [comment]
将依赖的PaddleNLP版本降到`2.5.2`，可以正常导出

**Comment by dz902** [comment]
Same issue here.

paddle2onnx              1.1.0
paddleclas               2.5.1
paddlefsl                1.1.0
paddlenlp                2.7.1
paddleocr                2.7.0.3
paddlepaddle-gpu         2.6.0

**Comment by dz902** [comment]
https://github.com/PaddlePaddle/PaddleNLP/commit/2560f2da0202a2985a142a327107edb9580cf3aa#r136888496

**Comment by XiYuan68** [comment]
> > 将依赖的PaddleNLP版本降到`2.5.2`，可以正常导出
> > 请问降低版本后提示ModuleNotFoundError: No module named 'paddle.fluid'这个错误怎么解决呢
> > ![image](https://private-user-images.githubusercontent.com/29534227/299641337-b25ac9fc-eead-462f-9792-3ddcc97319ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzU5NzgsIm5iZiI6MTcwNjc3NTY3OCwicGF0aCI6Ii8yOTUzNDIyNy8yOTk2NDEzMzctYjI1YWM5ZmMtZWVhZC00NjJmLTk3OTItM2RkY2M5NzMxOWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4MjExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDA4OTU1ZTk4Mzk3NjVkYmJmYjVmNDQ1NzYzOTZiNmQ5MzI3ODE2OTJkYTI2MGYwOGU4OTFjZWM5NjM0ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rEJQrwm_DoH7c30LY1KjWHQE2ozITb2e4J1k-pOZxz4)

把paddlepaddle版本降到2.5.0
