### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle'

### ISSUE THREAD

**Issue by devcang** [PaddlePaddle/PaddleOCR#11214]
pip install paddleocr

When done, try to run the simpliest sample code “only recognition”  in github

But failed: 

Traceback (most recent call last):
  File "paddleocr_test.py", line 4, in <module>
    from paddleocr import PaddleOCR
  File "C:\Python38\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\Python38\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

windows7 X64、 Python 3.8

**Comment by adam-harwood** [comment]
`paddlepaddle` needs to be installed separately:

```
pip install paddlepaddle
```
