### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)

### ISSUE THREAD

**Issue by KrisTopherHao** [PaddlePaddle/PaddleOCR#11217]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：WINDOW10
- 版本号/Version：paddleocr             2.7.0.3
    paddlepaddle          2.5.2
     PPOCRLabel            2.1.3
- 运行指令/Command Code： PPOCRLabel --lang ch

- 完整报错/Complete Error Message：
[2023/11/07 16:56:40] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "d:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python38\Scripts\PPOCRLabel.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "d:\python38\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
  File "d:\python38\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
  File "d:\python38\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 112, in __init__
    result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
  File "d:\python38\lib\site-packages\paddleocr\paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\table\predict_structure.py", line 120, in __call__
    data = transform(data, self.preprocess_op)
  File "..\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "..\ppocr\data\imaug\operators.py", line 94, in __call__
    img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)
PS C:\Users\HEDY\Desktop\PaddleOCR-release-2.7\PPOCRLabel>                      
PS C:\Users\HEDY\Desktop\PaddleOCR-release-2.7\PPOCRLabel> PPOCRLabel --lang ch
[2023/11/07 17:07:38] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "d:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python38\Scripts\PPOCRLabel.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "d:\python38\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
  File "d:\python38\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
  File "d:\python38\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 112, in __init__
    result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
  File "d:\python38\lib\site-packages\paddleocr\paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "d:\python38\lib\site-packages\PaddleOCR\ppstructure\table\predict_structure.py", line 120, in __call__
    data = transform(data, self.preprocess_op)
  File "..\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "..\ppocr\data\imaug\operators.py", line 94, in __call__
    img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)

**Comment by tigflanker** [comment]
吃井不忘挖水人，在PPOCRLabel.py脚本里的112行，把result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)这一句注释掉就行了，软件可以正常打开使用

**Comment by Iamlaoli** [comment]
@tigflanker 感谢老哥
