### ISSUE TITLE
输入训练模型指令后，疯狂报错

### ISSUE THREAD

**Issue by 555myhair** [PaddlePaddle/PaddleOCR#11344]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：GPU  cuda10.2  cudnn 8.6.0  python3.9
- 版本号/Version：Paddle：paddleocr             2.7.0.0           paddlepaddle-gpu      2.5.2.post102 
- PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml
- 完整报错/Complete Error Message：
[2023/12/05 12:51:59] ppocr INFO: profiler_options : None
[2023/12/05 12:51:59] ppocr INFO: train with paddle 2.5.2 and device Place(gpu:0)
[2023/12/05 12:51:59] ppocr INFO: Initialize indexs of datasets:['./train_data/det/train.txt']
[2023/12/05 12:51:59] ppocr INFO: Initialize indexs of datasets:['./train_data/det/val.txt']
W1205 12:51:59.223706  6740 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 10.2
W1205 12:51:59.244609  6740 gpu_resources.cc:149] device: 0, cuDNN Version: 7.6.
[2023/12/05 12:52:03] ppocr INFO: train dataloader has 1 iters
[2023/12/05 12:52:03] ppocr INFO: valid dataloader has 0 iters
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.conv.conv.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.conv.conv.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.conv.bn.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.conv.bn.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.conv.bn.bias not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.conv.bn.bias not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.conv.bn._mean not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.conv.bn._mean not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.conv.bn._variance not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.conv.bn._variance not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.expand_conv.conv.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.expand_conv.conv.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.expand_conv.bn.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.expand_conv.bn.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.expand_conv.bn.bias not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.expand_conv.bn.bias not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.expand_conv.bn._mean not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.expand_conv.bn._mean not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.expand_conv.bn._variance not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.expand_conv.bn._variance not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.bottleneck_conv.conv.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.bottleneck_conv.conv.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.bottleneck_conv.bn.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.bottleneck_conv.bn.weight not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.bottleneck_conv.bn.bias not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student.backbone.stage0.0.bottleneck_conv.bn.bias not in model
[2023/12/05 12:52:03] ppocr WARNING: The pretrained params Student2.backbone.stage0.0.bottleneck_conv.bn._mean not in model
.
.
.

[2023/12/05 12:57:19] ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 12:57:19] ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 12:57:20] ppocr INFO: save model in ./output/ch_db_result/latest
[2023/12/05 12:57:20] ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 12:57:20] ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 12:57:20] ppocr INFO: save model in ./output/ch_db_result/latest
[2023/12/05 12:57:20] ppocr INFO: best metric, hmean: 0, is_float16: False

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by 555myhair** [comment]
[2023/12/05 12:52:04] ppocr WARNING: The pretrained params Teacher.head.thresh.conv_bn2.weight not in model
[2023/12/05 12:52:04] ppocr WARNING: The pretrained params Teacher.head.thresh.conv_bn2.bias not in model
[2023/12/05 12:52:04] ppocr WARNING: The pretrained params Teacher.head.thresh.conv_bn2._mean not in model
[2023/12/05 12:52:04] ppocr WARNING: The pretrained params Teacher.head.thresh.conv_bn2._variance not in model
[2023/12/05 12:52:04] ppocr WARNING: The pretrained params Teacher.head.thresh.conv3.weight not in model
[2023/12/05 12:52:04] ppocr WARNING: The pretrained params Teacher.head.thresh.conv3.bias not in model
[2023/12/05 12:52:04] ppocr INFO: load pretrain successful from ./pretrain_models/ch_ppocr_server_v3.0_det_train/best_accuracy
[2023/12/05 12:52:04] ppocr INFO: No Images in eval dataset, evaluation during training will be disabled
[2023/12/05 12:52:04] ppocr INFO: During the training process, after the 1e+111th iteration, an evaluation is run every 2000 iterations

之后就开始疯狂报下面这个错误，直到GPU满了....


[2023/12/05 12:52:04] ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 12:52:04] ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

我的标签用ppocrlabel自动生成的，格式没改过。paddleocr程序是2.7.1版本的

**Comment by tink2123** [comment]
1. `The pretrained params Teacher.head.thresh.conv3.bias not in model` 相关报错是由于选择的预训练模型和model参数不一致，可以忽略
2. 检查一下标签文件中， img_path 和 label 是不是用 \t 分割的， 一般可能是电脑的编码问题。手动替换一下分隔符就可以了

**Comment by 555myhair** [comment]
picture/1.jpg	[{"transcription": "6414067", "points": [[253, 169], [326, 169], [326, 187], [252, 188]], "difficult": false}]
我生成的标签文件格式是这样的。我把中间的空格换成\t试试

**Comment by 555myhair** [comment]
手动改了之后变成了这个报错。
ppocr ERROR: When parsing line picture/1.jpg\t[{"transcription": "6414067", "points": [[253, 169], [326, 169], [326, 187], [252, 188]], "difficult": false}]
, error happened with msg: Traceback (most recent call last):
  File "D:\model\PaddleOCR-release-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

**Comment by 555myhair** [comment]
我用tab键也试了，还是报错。。。

**Comment by ericyeyeye** [comment]
> picture/1.jpg [{"transcription": "6414067", "points": [[253, 169], [326, 169], [326, 187], [252, 188]], "difficult": false}] picture/1.jpg [{"transcription": "6414067", "points": [[253, 169], [326, 169], [326, 187], [252, 188]], "difficult": false}] 都试过了，这个\t是什么东西？

給你參考一下我的格式
crop/2023-09-14T12:13:02_14390.jpg	[{"transcription": "14.390", "points": [[108, 81], [342, 81], [342, 147], [108, 147]], "difficult": false}]
建議你用with open 直接讀再print出來看比較準
`with open("./train/Label.txt", "r", encoding='utf-8') as file:
        contents = file.readlines()`
