### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by xiaozhou0311** [PaddlePaddle/PaddleOCR#11343]
023/12/05 15:58:17] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 3 iterations
[2023/12/05 15:58:33] ppocr ERROR: When parsing line 

, error happened with msg: Traceback (most recent call last):
  File "E:\AI_Code\PaddleOCR-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 15:58:37] ppocr INFO: cur metric, precision: 0.8888888888888888, recall: 1.0, hmean: 0.9411764705882353, fps: 1.2720649282331695
[2023/12/05 15:58:37] ppocr INFO: save best model is to ./output/ch_PP-OCR_V3_det/best_accuracy
[2023/12/05 15:58:37] ppocr INFO: best metric, hmean: 0.9411764705882353, is_float16: False, precision: 0.8888888888888888, recall: 1.0, fps: 1.2720649282331695, best_epoch: 1
[2023/12/05 15:58:53] ppocr ERROR: When parsing line 

, error happened with msg: Traceback (most recent call last):
  File "E:\AI_Code\PaddleOCR-2.7.1\ppocr\data\simple_dataset.py", line 150, in __getitem__
    label = substr[1]
IndexError: list index out of range

[2023/12/05 15:58:57] ppocr INFO: cur metric, precision: 0.8888888888888888, recall: 1.0, hmean: 0.9411764705882353, fps: 1.2869010204678446      

修改了标签文件txt之间多余的空格后，在加载数据的时候没有出现 label = substr[1]，但是训练的时候就出现了

**Comment by xiaozhou0311** [comment]
https://blog.csdn.net/weixin_51302403/article/details/134818251?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22134818251%22%2C%22source%22%3A%22weixin_51302403%22%7D    一顿折腾解决了

**Comment by phb-shiyige-fw** [comment]
> 件txt之间多余的空格后

请问那个CSDN文章中的py文件在哪里啊？我怎么找不到

**Comment by phb-shiyige-fw** [comment]
> https://blog.csdn.net/weixin_51302403/article/details/134818251?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22134818251%22%2C%22source%22%3A%22weixin_51302403%22%7D 一顿折腾解决了

你好 请问修改完后 是不是要重新标注数据集，才能正常训练
