### ISSUE TITLE
cv2: 找不到指定的模块

### ISSUE THREAD

**Issue by epowerstudio** [PaddlePaddle/PaddleOCR#11439]
(paddlelabel) PS C:\> paddlelabel
Starting PaddleLabel
INFO  [paddlelabel.config.19]: Database path: sqlite:///C:\Users\Administrator\.
paddlelabel\paddlelabel.db
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Scripts\paddlelabel.exe\__main
__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Lib\site-packages\paddlelabel\
__main__.py", line 107, in run
    from paddlelabel import api, task
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Lib\site-packages\paddlelabel\
task\__init__.py", line 5, in <module>
    from .semantic_segmentation import SemanticSegmentation
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Lib\site-packages\paddlelabel\
task\semantic_segmentation.py", line 10, in <module>
    import cv2
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Lib\site-packages\cv2\__init__
.py", line 181, in <module>
    bootstrap()
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Lib\site-packages\cv2\__init__
.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\paddlelabel\Lib\importlib\__init__.py", li
ne 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

**Comment by epowerstudio** [comment]
完全按照安装指南操作，
conda create -n paddlelabel python=3.11
conda activate paddlelabel
pip install --upgrade paddlelabel
完毕后，运行后有一系列问题，后面引用了#208 [https://github.com/PaddleCV-SIG/PaddleLabel/issues/208]里面的包：
pip install uvicorn==0.14 --no-deps
pip install connexion==2.14.1 --no-deps
pip install anyio==3.0 --no-deps
pip install Werkzeug==2.2.2 --no-deps
pip install starlette==0.21.0 --no-deps
pip install Flask==2.2.2 --no-deps
pip install Flask-Cors==3.0.10 --no-deps
pip install a2wsgi==1.8.0 --no-deps
pip install alembic==1.12.1 --no-deps
再运行：
paddlelabel
提示如上。应该如何解决。3QS

**Comment by chenhao86** [comment]
发错地儿了吧。 这边是PPOCR
