### ISSUE TITLE
用pyinstaller封装时报file not found

### ISSUE THREAD

**Issue by Edmond-Lee-Zse-Wong** [PaddlePaddle/PaddleOCR#11443]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.5.2  PaddleOCR：2.7.0.3 问题相关组件/Related components：python：3.10.1  pyinstaller：6.3.0
- 运行指令/Command Code：
```
import traceback

try:
    from paddleocr import PaddleOCR
    ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
    img_path = 'test.png'
    result = ocr.ocr(img_path, cls=True)
    for idx in range(len(result)):
        res = result[idx]
        for line in res:
            print(line)
except Exception as e:
    traceback.print_exc()
```
vscode运行上述代码，一切正常，使用pyinstaller库执行
`pyinstaller -F test.py`
封装为exe之后执行才会报错
- 完整报错/Complete Error Message：
```
 Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from paddleocr import PaddleOCR
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "paddleocr\paddleocr.py", line 43, in <module>
  File "paddleocr\paddleocr.py", line 37, in _import_file
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\18191\\AppData\\Local\\Temp\\_MEI86442\\paddleocr\\tools/__init__.py'
```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no): yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by Heryk13** [comment]
Try this, i think it will work if dont work comment there, then maybe i can help you

https://github.com/PaddlePaddle/PaddleOCR/discussions/11490#discussion-6072471

**Comment by Edmond-Lee-Zse-Wong** [comment]
参照 #11490，问题可以解决
