### ISSUE TITLE
PPOCRLabel open error

### ISSUE THREAD

**Issue by hinink** [PaddlePaddle/PaddleOCR#11459]
[2024/01/03 18:21:39] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2842, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2830, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2820, in get_main_app
    win = MainWindow(lang=args.lang,
  File "PPOCRLabel.py", line 114, in __init__
    result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
  File "D:\Program Files\anaconda3\envs\paddle_env\lib\site-packages\paddleocr\paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
  File "D:\workspace\Python\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
  File "D:\workspace\Python\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "D:\workspace\Python\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "D:\workspace\Python\PaddleOCR-release-2.7\PPOCRLabel\..\ppstructure\table\predict_structure.py", line 120, in __call__
    data = transform(data, self.preprocess_op)
  File "D:\workspace\Python\PaddleOCR-release-2.7\PPOCRLabel\..\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "D:\workspace\Python\PaddleOCR-release-2.7\PPOCRLabel\..\ppocr\data\imaug\operators.py", line 92, in __call__
    data['image'] = (img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)

**Comment by Hommoner** [comment]
試試修改源代碼
```
if os.path.exists('./data/paddle.png'):
            result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
```
為
```
if os.path.exists('./data/paddle.png'):
            result = self.ocr.ocr('./data/paddle.png', cls=True, det=True)  
```

或是直接拿掉

**Comment by Evenjine** [comment]
if os.path.exists('./data/paddle.png'):
            try:
                result = self.ocr.ocr('./data/paddle.png', cls=True, det=True)
            except:
                result = self.table_ocr('./data/paddle.png', return_ocr_result_in_table=True)
