### ISSUE TITLE
求教：利用test_reader()单独测试数据，报错KeyError: 'char_ops'

### ISSUE THREAD

**Issue by silence0628** [PaddlePaddle/PaddleOCR#1148]
Traceback (most recent call last):
  File "tools/train.py", line 144, in <module>
    test_reader()
  File "tools/train.py", line 123, in test_reader
    train_reader = reader_main(config=config, mode="train")
  File "tools/../ppocr/data/reader_main.py", line 67, in reader_main
    function = create_module(reader_function)(params)
  File "tools/../ppocr/data/rec/dataset_traversal.py", line 188, in __init__
    self.char_ops = params['char_ops']
KeyError: 'char_ops'

**Comment by littletomatodonkey** [comment]
可以拉下最新代码，char_ops是在这里初始化的

https://github.com/PaddlePaddle/PaddleOCR/blob/e0c8b88993da6330f36f4bbfb2bd6794a670e648/tools/program.py#L668


需要确保这句话被执行了

https://github.com/PaddlePaddle/PaddleOCR/blob/e0c8b88993da6330f36f4bbfb2bd6794a670e648/tools/train.py#L129
