### ISSUE TITLE
The latest version of PaddlePaddle (2.6.0) had removed the 'fluid' module

### ISSUE THREAD

**Issue by Kare-Udon** [PaddlePaddle/PaddleOCR#11517]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 22.04.3 LTS x86_64
- 版本号/Version：Paddle：2.6.0  PaddleOCR：2.7.0.3 问题相关组件/Related components：paddle.fluid
- 运行指令/Command Code：ocr = PaddleOCR(......)
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "/home/xxxx/code/xxxx/xxxx.py", line 30, in <module>
    OCR = PaddleOCR(
  File "/opt/anaconda3/envs/xxxx/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 501, in __init__
    super().__init__(params)
  File "/opt/anaconda3/envs/xxxx/lib/python3.9/site-packages/paddleocr/tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/opt/anaconda3/envs/xxxx/lib/python3.9/site-packages/paddleocr/tools/infer/predict_det.py", line 136, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/opt/anaconda3/envs/xxxx/lib/python3.9/site-packages/paddleocr/tools/infer/utility.py", line 214, in create_predictor
    gpu_id = get_infer_gpuid()
  File "/opt/anaconda3/envs/xxxx/lib/python3.9/site-packages/paddleocr/tools/infer/utility.py", line 310, in get_infer_gpuid
    if not paddle.fluid.core.is_compiled_with_rocm():
AttributeError: module 'paddle' has no attribute 'fluid'

It seems that the latest version of PaddlePaddle (2.6.0) had removed the 'fluid' module.
Go back to paddlepaddle==2.5.2, everything works fine.

**Comment by feifei-111** [comment]
“PaddlePaddle (2.6.0) had removed the 'fluid' module.” That's True.
