### ISSUE TITLE
运行python tools/infer/predict_rec.py这个推理代码时候，会出现bug

### ISSUE THREAD

**Issue by dragronstranding** [PaddlePaddle/PaddleOCR#11534]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux version=3.10.0-1160.el7.x86_64(gcc version=4.8.5)
- 版本号/Version：Paddle：paddlepadlle-gpu=2.3.0.post112  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/infer/predict_rec.py --image_dir="./doc/imgs_words/ch/word_1.jpg"  --rec_model_dir=./weights/ch_PP-OCRv3_rec_infer/ --rec_image_shape='3, 32, 320'  --rec_char_dict_path=ppocr/utils/ppocr_keys_v1.txt --use_gpu=True
- 完整报错/Complete Error Message：Error: Can not import avx core while this file exists: /usr/local/lib/python3.7/dist-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 28, in <module>
    import paddle
  File "/usr/local/lib/python3.7/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /usr/lib/x86_64-linux-gnu/libGLX.so.0: undefined symbol: pthread_mutex_lock

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):yes

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by tink2123** [comment]
看报错是paddle环境安装错误，请参考paddle安装说明选择和开发环境一致的paddle安装包:https://www.paddlepaddle.org.cn/

**Comment by dragronstranding** [comment]
感谢回复，我选的paddle2.3.0.post112，与我的开发环境的cuda版本是对应的上的。麻烦指导下，这个paddle版本和我开发环境中的哪个库产生了冲突
