### ISSUE TITLE
运行python3 tools/infer_kie_token_ser_re.py -c fapiao/re_vi_layoutxlm.yml -o Architecture.Backbone.checkpoints=fapiao/models/re_vi_layoutxlm_fapiao_udml/best_accuracy Global.infer_img=./train_data/zzsfp/val.json Global.infer_mode=True -c_ser fapiao/ser_vi_layoutxlm.yml -o_ser Architecture.Backbone.checkpoints=fapiao/models/ser_vi_layoutxlm_fapiao_udml/best_accuracy进行推理是

### ISSUE THREAD

**Issue by snowcakkke** [PaddlePaddle/PaddleOCR#11537]
- 系统环境/System Environment：Linux
- 版本号/Version：Paddle：2.6.0  PaddleOCR：2.6 问题相关组件/Related components：发票识别场景
- 运行指令/Command Code：运行python3 tools/infer_kie_token_ser_re.py -c fapiao/re_vi_layoutxlm.yml -o Architecture.Backbone.checkpoints=fapiao/models/re_vi_layoutxlm_fapiao_udml/best_accuracy Global.infer_img=./train_data/zzsfp/val.json Global.infer_mode=True -c_ser fapiao/ser_vi_layoutxlm.yml -o_ser Architecture.Backbone.checkpoints=fapiao/models/ser_vi_layoutxlm_fapiao_udml/best_accuracy
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/linmj/PaddleOCR-release-2.6/api_bill_nlp.py", line 149, in bill_recognition
    response = picture_recognition(file)
  File "/home/linmj/PaddleOCR-release-2.6/api_bill_nlp.py", line 162, in picture_recognition
    results_re = ser_re_engine({'img_path': file_path})
  File "/home/linmj/PaddleOCR-release-2.6/tools/infer_kie_token_ser_re.py", line 151, in __call__
    preds = self.model(re_input)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
    x = self.model(
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1189, in build_relation
    if negative_mask.sum() > 0:

**Comment by cuicheng01** [comment]
确保一下依赖包和PaddleOCR的要求是一样的呢？
