### ISSUE TITLE
有关于修改运行gpu的问题，发票推理模型如何修改运行在哪块gpu上，用CUDA_VISIBLE_DEVICES没有起作用

### ISSUE THREAD

**Issue by snowcakkke** [PaddlePaddle/PaddleOCR#11542]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "api_bill_nlp.py", line 138, in <module>
    ser_engine = SerPredictor(ser_config)
  File "/home/linmj/PaddleOCR-release-2.6/tools/infer_kie_token_ser.py", line 69, in __init__
    self.model = build_model(config['Architecture'])
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/architectures/__init__.py", line 31, in build_model
    arch = BaseModel(config)
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 56, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/backbones/__init__.py", line 76, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 151, in __init__
    super(LayoutXLMForSer, self).__init__(
  File "/home/linmj/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 57, in __init__
    self.model = model_class.from_pretrained(checkpoints)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 2195, in from_pretrained
    model = cls(config, *init_args, **model_kwargs)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 255, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 843, in __init__
    self.layoutxlm = LayoutXLMModel(config)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 255, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 643, in __init__
    self.embeddings = LayoutXLMEmbeddings(config)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 121, in __init__
    self.word_embeddings = nn.Embedding(config.vocab_size, config.hidden_size, padding_idx=0)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1496, in __init__
    self.weight = self.create_parameter(
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 781, in create_parameter
    return self._helper.create_parameter(
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/base/layer_helper_base.py", line 430, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/base/framework.py", line 4381, in create_parameter
    initializer(param, self)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
    return self.forward(param, block)
  File "/home/linmj/anaconda3/envs/bill_nlp/lib/python3.8/site-packages/paddle/nn/initializer/xavier.py", line 135, in forward
    out_var = _C_ops.uniform(
OSError: (External) CUDA error(2), out of memory.
  [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:209)

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by tink2123** [comment]
export CUDA_VISIBLE_DEVICES=0 指定任务跑在0号卡上。
