### ISSUE TITLE
 Paddle deploying ISSUE in a docker container.

### ISSUE THREAD

**Issue by bayoleems** [PaddlePaddle/PaddleOCR#11664]
### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/11066

<div type='discussions-op-text'>

<sup>Originally posted by **Sparshjain25** October 11, 2023</sup>
 Error: Can not import paddle core while this file exists: /usr/local/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
searchapp-1  | Traceback (most recent call last):
searchapp-1  |   File "/usr/src/app/main.py", line 4, in <module>
searchapp-1  |     from helpers import *
searchapp-1  |   File "/usr/src/app/helpers.py", line 16, in <module>
searchapp-1  |     from paddleocr import PaddleOCR
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddleocr/__init__.py", line 14, in <module>
searchapp-1  |     from .paddleocr import *
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 21, in <module>
searchapp-1  |     import paddle
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/__init__.py", line 31, in <module>
searchapp-1  |     from .framework import monkey_patch_variable
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
searchapp-1  |     from . import random  # noqa: F401
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/framework/random.py", line 17, in <module>
searchapp-1  |     from paddle import fluid
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
searchapp-1  |     from . import framework
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
searchapp-1  |     from . import core
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/core.py", line 356, in <module>
searchapp-1  |     raise e
searchapp-1  |   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/core.py", line 269, in <module>
searchapp-1  |     from . import libpaddle
searchapp-1  | ImportError: libgomp.so.1: cannot open shared object file: No such file or directory

I got this while running paddle OCR in a docker container.
Do anyone know how to resolve it?</div>

**Comment by bayoleems** [comment]
I solved this problem by creating these environments in my Docker container


RUN apt-get update && apt-get install -y libgomp1

RUN apt-get update && apt-get install -y libgl1-mesa-glx

RUN apt-get update && apt-get install -y libglib2.0-0

cheers
