### ISSUE TITLE
Error while running the exe

### ISSUE THREAD

**Issue by HawkingRadiation42** [PaddlePaddle/PaddleOCR#11671]
Before creating the exe file the code is running perfectly well but  while running the exe file I'm getting the below error:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from ocr_paddle import ProcessImage
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ocr_paddle.py", line 6, in <module>
    from PaddleOCR.tools.infer.predict_det import TextDetector
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PaddleOCR\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PaddleOCR\paddleocr.py", line 48, in <module>
    from tools.infer import predict_system
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "PyInstaller\loader\pyimod02_importers.py", line 312, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1150, in __init__
  File "<frozen importlib._bootstrap_external>", line 1165, in _get_parent_path
KeyError: 'PaddleOCR.tools'

 i can share you my .spec file as well.
Windows 10 
Using my custom trained paddleocr models 

Any help is welcomed
Thank you

**Comment by tink2123** [comment]
It should be caused by an error in the exe packaging process, not by replacing the model. You can first check the logic of code packaging.

**Comment by HawkingRadiation42** [comment]
i have cloned the paddleocr repo as im using its predict_det and predict_rec file for my models 
and below is my pyinstaller spec file, im basically adding all the folders and file present in the root folder to the exe for execution and here one of the folder is for PaddleOCR repo as well.

```
# -*- mode: python ; coding: utf-8 -*-
import os
block_cipher = None
def collect_datas(src_folder):
    def filter_data(data_tuple):
        excludes = ['__pycache__', '.git', '.idea', '.vscode', 'dist', 'build']  # Added 'venv' to the excludes list
        for exclude in excludes:
            if f'{os.sep}{exclude}{os.sep}' in data_tuple[0] or data_tuple[0].endswith(os.sep + exclude):
                return False
        return True

    datas = []
    for folder, subfolders, files in os.walk(src_folder):
        for file in files:
            file_path = os.path.join(folder, file)
            if filter_data((file_path, folder)):
                # Calculate relative destination path
                relative_folder = os.path.relpath(folder, src_folder)
                datas.append((file_path, relative_folder))
    return datas

project_dir = os.getcwd()

datas = collect_datas(project_dir)

a = Analysis(
    ['main.py'],
    pathex=[project_dir],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'Flask',
        'cryptography',
        'Flask-Cors',
        'Flask-SQLAlchemy',
        'pandas',
        'PIL',
        'rapidfuzz',
        'pythonnet',
        'PaddleOCR.tools',
        'PaddleOCR'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='localdb_paddle',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    onefile=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```

**Comment by HawkingRadiation42** [comment]
@kerneltravel
