### ISSUE TITLE
跟着 applications/发票关键信息抽取.md 教程执行报错

### ISSUE THREAD

**Issue by tinyxia** [PaddlePaddle/PaddleOCR#11696]
环境如下

- 系统环境/System Environment：MacOS 13.6
-  代码分支 2.7
- paddle2onnx               1.0.9
- paddlefsl                 1.1.0
- paddlehub                 2.4.0
- paddlenlp                 2.6.1
- paddleocr                 2.7.0.3
- paddlepaddle              2.6.0
- python                    3.8.12
- 运行指令/Command Code：python tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh_udml.yml
- 完整报错/Complete Error Message：

[2024-03-08 09:55:08,197] [    INFO] - All the weights of LayoutXLMModel were initialized from the model checkpoint at vi-layoutxlm-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LayoutXLMModel for predictions without further training.
Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "/Users/zhuxiaoxia/Documents/python/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 34, in build_model
    arch = getattr(mod, name)(config)
  File "/Users/zhuxiaoxia/Documents/python/PaddleOCR/ppocr/modeling/architectures/distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "/Users/zhuxiaoxia/Documents/python/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 55, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/Users/zhuxiaoxia/Documents/python/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 80, in build_backbone
    module_class = eval(module_name)(**config)
  File "/Users/zhuxiaoxia/Documents/python/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 149, in __init__
    super(LayoutXLMForSer, self).__init__(
  File "/Users/zhuxiaoxia/Documents/python/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 65, in __init__
    self.model = model_class(
  File "/Users/zhuxiaoxia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 253, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_classes'
➜  PaddleOCR git:(release/2.7) ✗

**Comment by changdazhou** [comment]
建议仔细检查配置文件是否有修改错误，这边复现是没有问题的哈

**Comment by SwordyLee** [comment]
> 建议仔细检查配置文件是否有修改错误，这边复现是没有问题的哈

可以提供一下您那边的配置吗，我这边也有同样的问题

**Comment by changdazhou** [comment]
我这边就是使用的官方配置哈
