### ISSUE TITLE
cudaErrorInitializationError

### ISSUE THREAD

**Issue by Tianny109** [PaddlePaddle/PaddleOCR#11701]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
我在imaug模块中新增了一个预处理模块 使用了一个加载预训练参数的完整卷积网络 但是运行以后报错cudaErrorInitializationError
使用runcheck以后显示正常，请问这是什么原因呢
- 系统环境/System Environment：
- BML codelab 4核V100 
- 版本号/Version：
-PaddlePaddle 2.6.0  PaddleOCR：release2.7 PP-OCRv4 问题相关组件/Related components：
- 运行指令/Command Code：
- `python tools/train.py -c configs/rec/PP-OCRv4/ch_PP-OCRv4_rec.yml -o Global.pretrained_model=/home/aistudio/ch_PP-OCRv4_rec_train/student.pdparams`
- 完整报错/Complete Error Message：
- `[2024/03/08 20:51:40] ppocr ERROR: When parsing line train/3531.jpg
, error happened with msg: Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR/ppocr/data/simple_dataset.py", line 253, in __getitem__
    outs = transform(data, self.ops[:-1])
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/__init__.py", line 58, in transform
    data = op(data)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/image.py", line 83, in __call__
    sr = self.net(input)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/image.py", line 63, in forward
    out = self.conv1(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/conv.py", line 715, in forward
    out = F.conv._conv_nd(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/functional/conv.py", line 128, in _conv_nd
    pre_bias = _C_ops.conv2d(
**OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:178)`**

**Comment by Sunting78** [comment]
您好，可以再检测一下图像是否正确，是否有损坏。另外可能是安装包和环境不对应，请自查下CUDA和Paddle版本
