### ISSUE TITLE
使用paddledetection进行训练时，每10次迭代后进行的eval报错

### ISSUE THREAD

**Issue by Asaiyume0926** [PaddlePaddle/PaddleOCR#11718]
使用paddledetection进行ppyoloe_s模型的训练时，每10次迭代后进行的eval报错，仅在第10次迭代结束时正常评估，在20、30乃至80次迭代结束时均无法正常评估，中断训练。使用数据集为widerperson行人检测的coco格式数据集。
系统环境：windows11、单显卡GTX1660ti 6G、处理器i5 9300f
版本号：PaddlePaddle 2.6、CUDA12.3、CUDNN8.9
运行指令：python tools/train.py -c configs/ppyoloe/ppyoloe_crn_s_400e_coco.yml -r output/69 --eval
完整报错：
loading annotations into memory...
Done (t=0.96s)
creating index...
index created!
[03/12 12:05:20] ppdet.data.source.coco INFO: Load [1000 samples valid, 0 samples invalid] in file dataset/widerperson_coco\annotations/valid.json.
loading annotations into memory...
Done (t=0.14s)
creating index...
index created!
Traceback (most recent call last):
  File "D:\PaddleDetection\PaddleDetection\tools\train.py", line 209, in <module>
    main()
  File "D:\PaddleDetection\PaddleDetection\tools\train.py", line 205, in main
    run(FLAGS, cfg)
  File "D:\PaddleDetection\PaddleDetection\tools\train.py", line 158, in run
    trainer.train(FLAGS.eval)
  File "D:\PaddleDetection\PaddleDetection\ppdet\engine\trainer.py", line 639, in train
    self._eval_with_loader(self._eval_loader)
  File "D:\PaddleDetection\PaddleDetection\ppdet\engine\trainer.py", line 676, in _eval_with_loader
    metric.update(data, outs)
  File "D:\PaddleDetection\PaddleDetection\ppdet\metrics\metrics.py", line 114, in update
    infer_results = get_infer_results(
  File "D:\PaddleDetection\PaddleDetection\ppdet\metrics\coco_utils.py", line 52, in get_infer_results
    infer_res['bbox'] = get_det_res(
  File "D:\PaddleDetection\PaddleDetection\ppdet\metrics\json_results.py", line 30, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 1

**Comment by TingquanGao** [comment]
检测的问题建议到PaddleDetection repo下提问~

不过，看这个报错信息，应该是分类数（class num）设置错误或是数据集label id格式有问题。可以检查一下数据集

**Comment by TingquanGao** [comment]
长时间未回复，已close，如有问题，可reopen并补充
