### ISSUE TITLE
更换ppstructure的layout中的大模型如ppyolov2会报错

### ISSUE THREAD

**Issue by charliedream1** [PaddlePaddle/PaddleOCR#11740]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.7
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "ppstructure_layout_table_rev.py", line 177, in <module>
    result = table_engine(img)
  File "/home/a/miniconda3/envs/train_py310/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 759, in __call__
    res, _ = super().__call__(
  File "/home/a/miniconda3/envs/train_py310/lib/python3.10/site-packages/paddleocr/ppstructure/predict_system.py", line 112, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "/home/a/miniconda3/envs/train_py310/lib/python3.10/site-packages/paddleocr/ppstructure/layout/predict_layout.py", line 86, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 107, in <module>
      main()
    File "tools/export_model.py", line 103, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/engine/trainer.py", line 460, in export
      input_spec, static_model.forward.main_program,
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/var/folders/0t/0lmgjgfj7012tggtgbwtqby80000l2/T/tmp0hu0he2y.py", line 26, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_1,
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/architectures/yolo.py", line 75, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/architectures/yolo.py", line 59, in _forward
      body_feats = self.backbone(self.inputs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/backbones/resnet.py", line 573, in forward
      conv1 = self.conv1(x)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
      input = layer(input)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/Desktop/model_ED/PaddleDetection-release-2.0/ppdet/modeling/backbones/resnet.py", line 122, in forward
      out = self.conv(inputs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 631, in forward
      out = F.conv._conv_nd(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 143, in _conv_nd
      helper.append_op(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3012, in append_op
      op = Operator(
    File "/Users/anmengtao/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2102, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The size of Op(Conv) inputs should not be 0.
      [Hint: Expected in_dims[i] != 0, but received in_dims[i]:0 == 0:0.] (at ../paddle/phi/infermeta/binary.cc:465)
      [operator < conv2d > error]

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by cuicheng01** [comment]
您好，请问具体是怎么更新的呢？

**Comment by charliedream1** [comment]
下载了这个模型
https://paddle-model-ecology.bj.bcebos.com/model/layout-parser/ppyolov2_r50vd_dcn_365e_tableBank_word.tar


然后用如下代码运行，指定了模型的目录


```python
layout_model_dir = '/ocr_ppstructure/ppyolov2_r50vd_dcn_365e_tableBank_latex'
table_engine = PPStructure(show_log=True, use_gpu=False, lang='ch', layout_model_dir=layout_model_dir)

```


现有的模型容易存在识别丢行的问题，不知这个200M的能否又改善呢？我目前用的是中文文档（标准的PDF截的图，格式很正规），但就是文件的上面和下面容易丢掉一行，请问是什么问题原因，怎么解决？


天天高兴！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月15日(星期五) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 更换ppstructure的layout中的大模型如ppyolov2会报错 (Issue #11740)





 
您好，请问具体是怎么更新的呢？

**Comment by charliedream1** [comment]
用的就是PP-Structure Model list里的：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppstructure/docs/models_list_en.md

**Comment by heweisheng** [comment]
我也是这个情况 只能用picodet的 不能用yolo的

**Comment by heweisheng** [comment]
> ppyolov2_r50vd_dcn_365e_tableBank_la
你这个好像情况还跟我不同 table是给table用的 我的是layout的模型

**Comment by UserWangZz** [comment]
可以参考PaddleDeteciton仓库中关于PP-yolo的运行
