### ISSUE TITLE
用det_r50_vd_db.yml训练得到模型进行模型评估时报错：

### ISSUE THREAD

**Issue by Lew9s** [PaddlePaddle/PaddleOCR#11752]
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/vipuser/miniconda3/envs/seal/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 692, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/vipuser/miniconda3/envs/seal/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vipuser/miniconda3/envs/seal/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/vipuser/miniconda3/envs/seal/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
  File "tools/eval.py", line 146, in <module>
    main()
  File "tools/eval.py", line 136, in main
    metric = program.eval(model, valid_dataloader, post_process_class,
  File "/root/.jupyter/PaddleOCR/tools/program.py", line 511, in eval
    for idx, batch in enumerate(valid_dataloader):
  File "/home/vipuser/miniconda3/envs/seal/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 825, in __next__
    self._reader.read_next_list()[0]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at ../paddle/fluid/operators/reader/blocking_queue.h:175)

**Comment by changdazhou** [comment]
请问使用的什么数据集呢

**Comment by changdazhou** [comment]
长时间未回复，先关闭issue，如有需要可重新开启
