### ISSUE TITLE
zhoujun20 请出来改一下代码

### ISSUE THREAD

**Issue by ttkrpink** [PaddlePaddle/PaddleOCR#11755]
使用 predict_table 进行识别，竟然出现了：

`/Users/zhoujun20/opt/`

zhoujun20 显然不是我电脑上的用户。

```
(Health_Report_API) PS F:\pythonProjects\Medical_Report\health-report-api\project> python F:\pythonProjects\Medical_Report\health-report-api\project\./OCR_Models/PaddleOCR/ppstructure/table/predict_table.py --det_model_dir=F:\pythonProjects\Medical_Report\health-report-api\project\./OCR_Models/ch_PP-OCRv4_det_server_infer --rec_model_dir=F:\pythonProjects\Medical_Report\health-report-api\project\./OCR_Models/ch_PP-OCRv4_rec_server_infer --table_model_dir=F:\pythonProjects\Medical_Report\health-report-api\project\./OCR_Models/ch_ppstructure_mobile_v2.0_SLANet_infer --rec_char_dict_path=F:\pythonProjects\Medical_Report\health-report-api\project\./OCR_Models/PaddleOCR/ppocr/utils/ppocr_keys_v1.txt --table_char_dict_path=F:\pythonProjects\Medical_Report\health-report-api\project\./OCR_Models/PaddleOCR/ppocr/utils/dict/table_structure_dict_ch.txt --image_dir=F:\pythonProjects\Medical_Report\health-report-api\project\media\./Download/Report_01.jpg --output=F:\pythonProjects\Medical_Report\health-report-api\project\media\./Upload/
[2024/03/17 09:27:08] ppocr INFO: [0/1] F:\pythonProjects\Medical_Report\health-report-api\project\media\./Download/Report_01.jpg
Traceback (most recent call last):
  File "F:\pythonProjects\Medical_Report\health-report-api\project\OCR_Models\PaddleOCR\ppstructure\table\predict_table.py", line 230, in <module>
    main(args)
  File "F:\pythonProjects\Medical_Report\health-report-api\project\OCR_Models\PaddleOCR\ppstructure\table\predict_table.py", line 181, in main
    pred_res, _ = table_sys(img)
  File "F:\pythonProjects\Medical_Report\health-report-api\project\OCR_Models\PaddleOCR\ppstructure\table\predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "F:\pythonProjects\Medical_Report\health-report-api\project\OCR_Models\PaddleOCR\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "F:\pythonProjects\Medical_Report\health-report-api\project\OCR_Models\PaddleOCR\ppstructure\table\predict_structure.py", line 134, in __call__
    self.predictor.run()
RuntimeError: In user code:

    File "tools/export_model.py", line 255, in <module>
      main()
    File "tools/export_model.py", line 250, in main
      export_single_model(
    File "tools/export_model.py", line 171, in export_single_model
      paddle.jit.save(model, save_path)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmpyqukhdph.py", line 91, in forward
      final_name, x = paddle.jit.dy2static.convert_ifelse(self.use_head,
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward
      x = self.head(x, targets=data)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmpco4rpr5e.py", line 97, in forward
      paddle.jit.dy2static.convert_ifelse(paddle.jit.dy2static.
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmpco4rpr5e.py", line 91, in false_fn_17
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_3,
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
      output_vars = body(*loop_vars)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 234, in forward
      hidden, structure_step, loc_step = self._decode(pre_chars, fea,
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 253, in _decode
      (output, hidden), alpha = self.structure_attention_cell(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/heads/rec_att_head.py", line 96, in forward
      batch_H_proj = self.i2h(batch_H)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 171, in forward
      out = F.linear(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1560, in linear
      helper.append_op(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The third-party dynamic library (cublas64_120.dll;cublas64_12.dll) that Paddle depends on is not configured correctly. (error code is 126)
      Suggestions:
      1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
      2. Configure third-party dynamic library environment variables as follows:
      - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
      - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)
      [operator < matmul_v2 > error]
```

**Comment by cuicheng01** [comment]
模型导出时的路径，但是不是由这个问题导致的，可以看下LD_LIBRARY_PATH是否ok

**Comment by jzhang533** [comment]
Fun issue1~

**Comment by ttkrpink** [comment]
世上无难事，只要肯放弃。

转到 Linux 上部署了，一切顺利。Close Issue

**Comment by masquerlin** [comment]
linux上部署也有这个zhoujun20.这是什么鬼

**Comment by GreatV** [comment]
这怎么产生的

**Comment by jzhang533** [comment]
paddle 导出的模型里会记录一个 op_callstack
用下面的代码可以看出来：

```python
import paddle.base.proto.framework_pb2 as pppb

prog = pppb.ProgramDesc()
with open('./demo.pdmodel', "rb") as f:
    prog.ParseFromString(f.read())
print(prog)
```

我也没搞懂这么做的原因。 🥲
