### ISSUE TITLE
使用开源飞浆训练模型报错，版本2.5.2

### ISSUE THREAD

**Issue by czs397001** [PaddlePaddle/PaddleOCR#11765]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment  window
- 版本号/Version：Paddle： 2.5.2  PaddleOCR：2.5.0.2  问题相关组件/Related components：
- 运行指令/Command Code：python ./PaddleOCR/tools/train.py -c ./work/ser_vi_layoutxlm_udml.yml   
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File ".\PaddleOCR\tools\train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File ".\PaddleOCR\tools\train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\国药\code\pythonProject\val-ocr\PaddleOCR\tools\program.py", line 304, in train
    loss = loss_class(preds, batch)
  File "D:\anaconda3\envs\val-ocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\国药\code\pythonProject\val-ocr\PaddleOCR\ppocr\losses\combined_loss.py", line 58, in forward
    loss = loss_func(input, batch, **kargs)
  File "D:\anaconda3\envs\val-ocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\国药\code\pythonProject\val-ocr\PaddleOCR\ppocr\losses\distillation_loss.py", line 346, in forward
    loss = super().forward(out, batch)
  File "D:\国药\code\pythonProject\val-ocr\PaddleOCR\ppocr\losses\vqa_token_layoutlm_loss.py", line 42, in forward
    loss = self.loss_class(active_output, active_label)
  File "D:\anaconda3\envs\val-ocr\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\anaconda3\envs\val-ocr\lib\site-packages\paddle\nn\layer\loss.py", line 373, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\anaconda3\envs\val-ocr\lib\site-packages\paddle\nn\functional\loss.py", line 2707, in cross_entropy
    _, out = _C_ops.cross_entropy_with_softmax(
IndexError: (OutOfRange) label value should less than the shape of axis dimension when label value(3) not equal to ignore_index(-100), But received label value as 3 and shape of axis dimension is 3
  [Hint: Expected lbl < axis_dim_, but received lbl:3 >= axis_dim_:3.] (at ..\paddle\phi\kernels\funcs\cross_entropy.cc:74)

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by TingquanGao** [comment]
使用的是私有数据集吗？还是我们提供的公开数据集呢？配置文件有修改吗？

**Comment by czs397001** [comment]
> 使用的是私有数据集吗？还是我们提供的公开数据集呢？配置文件有修改吗？

使用的是公开数据集，配置文件基本没有修改，就改了是否使用gpu，num_classes 数量和路径，其余的都没有修改

**Comment by czs397001** [comment]
> 使用的是私有数据集吗？还是我们提供的公开数据集呢？配置文件有修改吗？

[2024/03/20 08:43:30] ppocr INFO: Architecture : 
[2024/03/20 08:43:30] ppocr INFO:     Models : 
[2024/03/20 08:43:30] ppocr INFO:         Student : 
[2024/03/20 08:43:30] ppocr INFO:             Backbone : 
[2024/03/20 08:43:30] ppocr INFO:                 checkpoints : None
[2024/03/20 08:43:30] ppocr INFO:                 mode : vi
[2024/03/20 08:43:30] ppocr INFO:                 name : LayoutXLMForSer
[2024/03/20 08:43:30] ppocr INFO:                 num_classes : 2
[2024/03/20 08:43:30] ppocr INFO:                 pretrained : True
[2024/03/20 08:43:30] ppocr INFO:             Transform : None
[2024/03/20 08:43:30] ppocr INFO:             algorithm : LayoutXLM
[2024/03/20 08:43:30] ppocr INFO:             freeze_params : False
[2024/03/20 08:43:30] ppocr INFO:             model_type : kie
[2024/03/20 08:43:30] ppocr INFO:             pretrained : None
[2024/03/20 08:43:30] ppocr INFO:             return_all_feats : True
[2024/03/20 08:43:30] ppocr INFO:         Teacher : 
[2024/03/20 08:43:30] ppocr INFO:             Backbone : 
[2024/03/20 08:43:30] ppocr INFO:                 checkpoints : None
[2024/03/20 08:43:30] ppocr INFO:                 mode : vi
[2024/03/20 08:43:30] ppocr INFO:                 name : LayoutXLMForSer
[2024/03/20 08:43:30] ppocr INFO:                 num_classes : 2
[2024/03/20 08:43:30] ppocr INFO:                 pretrained : True
[2024/03/20 08:43:30] ppocr INFO:             Transform : None
[2024/03/20 08:43:30] ppocr INFO:             algorithm : LayoutXLM
[2024/03/20 08:43:30] ppocr INFO:             freeze_params : False
[2024/03/20 08:43:30] ppocr INFO:             model_type : kie
[2024/03/20 08:43:30] ppocr INFO:             pretrained : None
[2024/03/20 08:43:30] ppocr INFO:             return_all_feats : True
[2024/03/20 08:43:30] ppocr INFO:     algorithm : Distillation
[2024/03/20 08:43:30] ppocr INFO:     model_type : kie
[2024/03/20 08:43:30] ppocr INFO:     name : DistillationModel
[2024/03/20 08:43:30] ppocr INFO: Eval : 
[2024/03/20 08:43:30] ppocr INFO:     dataset : 
[2024/03/20 08:43:30] ppocr INFO:         data_dir : train_data/zzsfp/imgs
[2024/03/20 08:43:30] ppocr INFO:         label_file_list : ['train_data/zzsfp/val.json']
[2024/03/20 08:43:30] ppocr INFO:         name : SimpleDataSet
[2024/03/20 08:43:30] ppocr INFO:         transforms : 
[2024/03/20 08:43:30] ppocr INFO:             DecodeImage : 
[2024/03/20 08:43:30] ppocr INFO:                 channel_first : False
[2024/03/20 08:43:30] ppocr INFO:                 img_mode : RGB
[2024/03/20 08:43:30] ppocr INFO:             VQATokenLabelEncode : 
[2024/03/20 08:43:30] ppocr INFO:                 algorithm : LayoutXLM
[2024/03/20 08:43:30] ppocr INFO:                 class_path : train_data/zzsfp/class_list.txt
[2024/03/20 08:43:30] ppocr INFO:                 contains_re : False
[2024/03/20 08:43:30] ppocr INFO:                 order_method : tb-yx
[2024/03/20 08:43:30] ppocr INFO:             VQATokenPad : 
[2024/03/20 08:43:30] ppocr INFO:                 max_seq_len : 512
[2024/03/20 08:43:30] ppocr INFO:                 return_attention_mask : True
[2024/03/20 08:43:30] ppocr INFO:             VQASerTokenChunk : 
[2024/03/20 08:43:30] ppocr INFO:                 max_seq_len : 512
[2024/03/20 08:43:30] ppocr INFO:             Resize : 
[2024/03/20 08:43:30] ppocr INFO:                 size : [224, 224]
[2024/03/20 08:43:30] ppocr INFO:             NormalizeImage : 
[2024/03/20 08:43:30] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2024/03/20 08:43:30] ppocr INFO:                 order : hwc
[2024/03/20 08:43:30] ppocr INFO:                 scale : 1
[2024/03/20 08:43:30] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2024/03/20 08:43:30] ppocr INFO:             ToCHWImage : None
[2024/03/20 08:43:30] ppocr INFO:             KeepKeys : 
[2024/03/20 08:43:30] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2024/03/20 08:43:30] ppocr INFO:     loader : 
[2024/03/20 08:43:30] ppocr INFO:         batch_size_per_card : 8
[2024/03/20 08:43:30] ppocr INFO:         drop_last : False
[2024/03/20 08:43:30] ppocr INFO:         num_workers : 4
[2024/03/20 08:43:30] ppocr INFO:         shuffle : False
[2024/03/20 08:43:30] ppocr INFO: Global : 
[2024/03/20 08:43:30] ppocr INFO:     cal_metric_during_train : False
[2024/03/20 08:43:30] ppocr INFO:     distributed : False
[2024/03/20 08:43:30] ppocr INFO:     epoch_num : 50
[2024/03/20 08:43:30] ppocr INFO:     eval_batch_step : [0, 10]
[2024/03/20 08:43:30] ppocr INFO:     infer_img : ppstructure/docs/vqa/input/zh_val_42.jpg
[2024/03/20 08:43:30] ppocr INFO:     log_smooth_window : 10
[2024/03/20 08:43:30] ppocr INFO:     print_batch_step : 10
[2024/03/20 08:43:30] ppocr INFO:     save_epoch_step : 2000
[2024/03/20 08:43:30] ppocr INFO:     save_inference_dir : None
[2024/03/20 08:43:30] ppocr INFO:     save_model_dir : ./output/ser_vi_layoutxlm_xfund_zh_udml
[2024/03/20 08:43:30] ppocr INFO:     save_res_path : ./output/fapiao_res/ser_vi_layoutxlm_udml
[2024/03/20 08:43:30] ppocr INFO:     seed : 2022
[2024/03/20 08:43:30] ppocr INFO:     use_gpu : False
[2024/03/20 08:43:30] ppocr INFO:     use_visualdl : False
[2024/03/20 08:43:30] ppocr INFO: Loss : 
[2024/03/20 08:43:30] ppocr INFO:     loss_config_list : 
[2024/03/20 08:43:30] ppocr INFO:         DistillationVQASerTokenLayoutLMLoss : 
[2024/03/20 08:43:30] ppocr INFO:             key : backbone_out
[2024/03/20 08:43:30] ppocr INFO:             model_name_list : ['Student', 'Teacher']
[2024/03/20 08:43:30] ppocr INFO:             num_classes : 2
[2024/03/20 08:43:30] ppocr INFO:             weight : 1.0
[2024/03/20 08:43:30] ppocr INFO:         DistillationSERDMLLoss : 
[2024/03/20 08:43:30] ppocr INFO:             act : softmax
[2024/03/20 08:43:30] ppocr INFO:             key : backbone_out
[2024/03/20 08:43:30] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2024/03/20 08:43:30] ppocr INFO:             use_log : True
[2024/03/20 08:43:30] ppocr INFO:             weight : 1.0
[2024/03/20 08:43:30] ppocr INFO:         DistillationVQADistanceLoss : 
[2024/03/20 08:43:30] ppocr INFO:             key : hidden_states_5
[2024/03/20 08:43:30] ppocr INFO:             mode : l2
[2024/03/20 08:43:30] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2024/03/20 08:43:30] ppocr INFO:             name : loss_5
[2024/03/20 08:43:30] ppocr INFO:             weight : 0.5
[2024/03/20 08:43:30] ppocr INFO:         DistillationVQADistanceLoss : 
[2024/03/20 08:43:30] ppocr INFO:             key : hidden_states_8
[2024/03/20 08:43:30] ppocr INFO:             mode : l2
[2024/03/20 08:43:30] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2024/03/20 08:43:30] ppocr INFO:             name : loss_8
[2024/03/20 08:43:30] ppocr INFO:             weight : 0.5
[2024/03/20 08:43:30] ppocr INFO:     name : CombinedLoss
[2024/03/20 08:43:30] ppocr INFO: Metric : 
[2024/03/20 08:43:30] ppocr INFO:     base_metric_name : VQASerTokenMetric
[2024/03/20 08:43:30] ppocr INFO:     key : Student
[2024/03/20 08:43:30] ppocr INFO:     main_indicator : hmean
[2024/03/20 08:43:30] ppocr INFO:     name : DistillationMetric
[2024/03/20 08:43:30] ppocr INFO: Optimizer : 
[2024/03/20 08:43:30] ppocr INFO:     beta1 : 0.9
[2024/03/20 08:43:30] ppocr INFO:     beta2 : 0.999
[2024/03/20 08:43:30] ppocr INFO:     lr : 
[2024/03/20 08:43:30] ppocr INFO:         epochs : 50
[2024/03/20 08:43:30] ppocr INFO:         learning_rate : 5e-05
[2024/03/20 08:43:30] ppocr INFO:         name : Linear
[2024/03/20 08:43:30] ppocr INFO:         warmup_epoch : 5
[2024/03/20 08:43:30] ppocr INFO:     name : AdamW
[2024/03/20 08:43:30] ppocr INFO:     regularizer : 
[2024/03/20 08:43:30] ppocr INFO:         factor : 0.0
[2024/03/20 08:43:30] ppocr INFO:         name : L2
[2024/03/20 08:43:30] ppocr INFO: PostProcess : 
[2024/03/20 08:43:30] ppocr INFO:     class_path : train_data/zzsfp/class_list.txt
[2024/03/20 08:43:30] ppocr INFO:     key : backbone_out
[2024/03/20 08:43:30] ppocr INFO:     model_name : ['Student', 'Teacher']
[2024/03/20 08:43:30] ppocr INFO:     name : DistillationSerPostProcess
[2024/03/20 08:43:30] ppocr INFO: Train : 
[2024/03/20 08:43:30] ppocr INFO:     dataset : 
[2024/03/20 08:43:30] ppocr INFO:         data_dir : train_data/zzsfp/imgs
[2024/03/20 08:43:30] ppocr INFO:         label_file_list : ['train_data/zzsfp/train.json']
[2024/03/20 08:43:30] ppocr INFO:         name : SimpleDataSet
[2024/03/20 08:43:30] ppocr INFO:         ratio_list : [1.0]
[2024/03/20 08:43:30] ppocr INFO:         transforms : 
[2024/03/20 08:43:30] ppocr INFO:             DecodeImage : 
[2024/03/20 08:43:30] ppocr INFO:                 channel_first : False
[2024/03/20 08:43:30] ppocr INFO:                 img_mode : RGB
[2024/03/20 08:43:30] ppocr INFO:             VQATokenLabelEncode : 
[2024/03/20 08:43:30] ppocr INFO:                 algorithm : LayoutXLM
[2024/03/20 08:43:30] ppocr INFO:                 class_path : train_data/zzsfp/class_list.txt
[2024/03/20 08:43:30] ppocr INFO:                 contains_re : False
[2024/03/20 08:43:30] ppocr INFO:                 order_method : tb-yx
[2024/03/20 08:43:30] ppocr INFO:             VQATokenPad : 
[2024/03/20 08:43:30] ppocr INFO:                 max_seq_len : 512
[2024/03/20 08:43:30] ppocr INFO:                 return_attention_mask : True
[2024/03/20 08:43:30] ppocr INFO:             VQASerTokenChunk : 
[2024/03/20 08:43:30] ppocr INFO:                 max_seq_len : 512
[2024/03/20 08:43:30] ppocr INFO:             Resize : 
[2024/03/20 08:43:30] ppocr INFO:                 size : [224, 224]
[2024/03/20 08:43:30] ppocr INFO:             NormalizeImage : 
[2024/03/20 08:43:30] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2024/03/20 08:43:30] ppocr INFO:                 order : hwc
[2024/03/20 08:43:30] ppocr INFO:                 scale : 1
[2024/03/20 08:43:30] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2024/03/20 08:43:30] ppocr INFO:             ToCHWImage : None
[2024/03/20 08:43:30] ppocr INFO:             KeepKeys : 
[2024/03/20 08:43:30] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2024/03/20 08:43:30] ppocr INFO:     loader : 
[2024/03/20 08:43:30] ppocr INFO:         batch_size_per_card : 4
[2024/03/20 08:43:30] ppocr INFO:         drop_last : False
[2024/03/20 08:43:30] ppocr INFO:         num_workers : 4
[2024/03/20 08:43:30] ppocr INFO:         shuffle : True
[2024/03/20 08:43:30] ppocr INFO: profiler_options : None
[2024/03/20 08:43:30] ppocr INFO: train with paddle 2.5.1 and device Place(cpu)
[2024/03/20 08:43:30] ppocr INFO: Initialize indexs of datasets:['train_data/zzsfp/train.json']
这是日志
