### ISSUE TITLE
paddleocr当用户名为中文时报错怎么解决？

### ISSUE THREAD

**Issue by yiyuhewei** [PaddlePaddle/PaddleOCR#11794]
使用这一句代码加载模型时ocr = PaddleOCR(use_gpu=False)，因为用户名为中文时就会报错？下面是错误代码：Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2023.3.5\plugins\python-ce\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2023.3.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\pythonProject1\main.py", line 8, in <module>
    ocr = PaddleOCR(use_gpu=False)
  File "C:\Users\解甲归田\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py", line 616, in __init__
    super().__init__(params)
  File "C:\Users\解甲归田\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\Users\解甲归田\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "C:\Users\解甲归田\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\utility.py", line 285, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file C:\Users\解甲归田\.paddleocr\whl\det\ch\ch_PP-OCRv4_det_infer\inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2578)

**Comment by changdazhou** [comment]
不建议将python环境安装在带有中文目录的路径下哈，建议重装python到全英文路径下

**Comment by sealofyou** [comment]
已解决，解决方法
要将paddleocr源代码里的BASE_DIR = os.path.expanduser("~/.paddleocr/")改为BASE_DIR = os.path.expanduser(".paddleocr/")
然后运行就会自动下载模型然后可以运行 
[运行](https://cdn.nlark.com/yuque/0/2024/png/26676983/1721626177215-84d4ae8b-9f3e-4710-afe2-755c8ba6057e.png?x-oss-process=image%2Fformat%2Cwebp)

潜在问题，因为更改存储位置可能导致出现其他问题。
