### ISSUE TITLE
 AttributeError: 'bool' object has no attribute 'sum'

### ISSUE THREAD

**Issue by abcmleng** [PaddlePaddle/PaddleOCR#11844]
- paddlepaddle version: 2.5.2
- paddleocr version: 2.7.2
- paddlenlp version: 2.7.2
- Command Code：python3 tools/export_model.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml -o - Architecture.Backbone.checkpoints=./re_vi_layoutxlm_xfund_pretrained/best_accuracy Global.save_inference_dir=./inference/re_vi_layoutxlm_infer

- Complete Error Message：Traceback (most recent call last):
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/tools/export_model.py", line 289, in <module>
    main()
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/tools/export_model.py", line 284, in main
    export_single_model(
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/tools/export_model.py", line 198, in export_single_model
    paddle.jit.save(model, save_path)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/api.py", line 752, in wrapper
    func(layer, path, input_spec, **configs)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/api.py", line 1043, in save
    static_func.concrete_program_specify_input_spec(
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 709, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 589, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1249, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1193, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1070, in from_func_spec
    error_data.raise_new_exception()
  File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddle/jit/dy2static/error.py", line 452, in raise_new_exception
    raise new_exception from None
AttributeError: In transformed code:

    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 85, in forward
        if self.use_backbone:
    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
        x = self.backbone(x)
    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
        x = self.model(
    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1330, in forward
        loss, pred_relations = self.extractor(sequence_output, entities, relations)
    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1224, in forward
        relations, entities = self.build_relation(relations, entities)
    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1153, in build_relation
        for b in range(batch_size):
    File "/home/sunita.k/Documents/OCR_parser/PaddleOCR/env_paddle/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1190, in build_relation
        positive_relations = positive_relations[positive_mask]

        if negative_mask.sum() > 0:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            reordered_relations = paddle.concat([positive_relations, negative_relations])
        else:


    AttributeError: 'bool' object has no attribute 'sum'

Getting the same error with the below command
python3 tools/export_model.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./re_vi_layoutxlm_xfund_pretrained/best_accuracy Global.save_inference_dir=./inference/re_vi_layoutxlm_infer

**Comment by UserWangZz** [comment]
尝试降低一下paddlenlp的版本试试

**Comment by 564142183** [comment]
@UserWangZz 大佬，paddlenlp试了2.8.0、2.7.2、2.6.1，都报这个错

**Comment by nam157** [comment]
@abcmleng i happend this error and i don't fix. Can you help me ?

**Comment by UserWangZz** [comment]
#13368 使用对应版本的paddlepaddle和paddlenlp即可

**Comment by DAAworld** [comment]
> #13368 使用对应版本的paddlepaddle和paddlenlp即可

![image](https://github.com/user-attachments/assets/a6061905-8a8b-4473-a93b-bc9b605e79e0)
bu'xing不行啊。

**Comment by UserWangZz** [comment]
> > #13368 使用对应版本的paddlepaddle和paddlenlp即可
> 
> ![image](https://private-user-images.githubusercontent.com/46104689/353363795-a6061905-8a8b-4473-a93b-bc9b605e79e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjU4MzEsIm5iZiI6MTcyMjMyNTUzMSwicGF0aCI6Ii80NjEwNDY4OS8zNTMzNjM3OTUtYTYwNjE5MDUtOGE4Yi00NDczLWE5M2ItYmM5YjYwNWU3OWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMDkyNDY0ZjgxZjMxNTIzMjYyZDEzNTE1YzJjY2U5NWNhNTA0ZWM3YjkzZWViZmM0NzU1YTMyMGE4ZTUxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBx2pG6im9X6ButeW4sfhH18QR2TvFILkqNLe72LZEM) bu'xing不行啊。

你好，请仔细查看链接，目前复现测试使用paddlepaddle==2.4.1，paddlenlp==2.5.2是可以运行的

**Comment by DAAworld** [comment]
> > > #13368 使用对应版本的paddlepaddle和paddlenlp即可
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/46104689/353363795-a6061905-8a8b-4473-a93b-bc9b605e79e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjU4MzEsIm5iZiI6MTcyMjMyNTUzMSwicGF0aCI6Ii80NjEwNDY4OS8zNTMzNjM3OTUtYTYwNjE5MDUtOGE4Yi00NDczLWE5M2ItYmM5YjYwNWU3OWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMDkyNDY0ZjgxZjMxNTIzMjYyZDEzNTE1YzJjY2U5NWNhNTA0ZWM3YjkzZWViZmM0NzU1YTMyMGE4ZTUxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBx2pG6im9X6ButeW4sfhH18QR2TvFILkqNLe72LZEM) bu'xing不行啊。
> 
> 你好，请仔细查看链接，目前复现测试使用paddlepaddle==2.4.1，paddlenlp==2.5.2是可以运行的

这个版本的我也测试了，报个某个.so文件的错误，我就没再试了。
