### ISSUE TITLE
gpus的情况下报错 install_check.py:265 - PaddlePaddle meets some problem with 2 GPUs.

### ISSUE THREAD

**Issue by q465414859** [PaddlePaddle/PaddleOCR#11901]
显卡驱动和CUDA cudnn nccl 都是对应版本的12.0

- 系统环境/System Environment：ubuntu 22. 04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle-gpu       2.5.2.post120
- 运行指令/Command Code：paddle.utils.run_check()
- 完整报错/Complete Error Message：

Running verify PaddlePaddle program ...
I0409 16:04:35.709347  7944 interpretercore.cc:237] New Executor is Running.
W0409 16:04:35.710853  7944 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0iver API Version: 12.0, Runtime API Version: 12.0
W0409 16:04:35.711491  7944 gpu_resources.cc:149] device: 0, cuDNN Version: 90.0.
I0409 16:04:36.996335  7944 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
Running verify PaddlePaddle program ...
Running verify PaddlePaddle program ...
I0409 16:04:41.629110  8023 interpretercore.cc:237] New Executor is Running.
W0409 16:04:41.630621  8023 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0iver API Version: 12.0, Runtime API Version: 12.0
W0409 16:04:41.631137  8023 gpu_resources.cc:149] device: 0, cuDNN Version: 90.0.
I0409 16:04:41.951776  8024 interpretercore.cc:237] New Executor is Running.
W0409 16:04:41.953104  8024 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0iver API Version: 12.0, Runtime API Version: 12.0
W0409 16:04:41.953649  8024 gpu_resources.cc:149] device: 0, cuDNN Version: 90.0.
I0409 16:04:42.958331  8023 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
[2024-04-09 16:04:42,967] [ WARNING] install_check.py:265 - PaddlePaddle meets some problem with 2 GPThis may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://githom/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-g/index.html
[2024-04-09 16:04:42,967] [ WARNING] install_check.py:275 -
 Original Error is:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddow.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/test.py", line 2, in <module>
    paddle.utils.run_check()
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 282, in run_chec
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 255, in run_chec
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 206, in _run_parl
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 585, in spawn
    process.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
I0409 16:04:43.284149  8024 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
[2024-04-09 16:04:43,293] [ WARNING] install_check.py:265 - PaddlePaddle meets some problem with 2 GPThis may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://githom/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-g/index.html
[2024-04-09 16:04:43,293] [ WARNING] install_check.py:275 -
 Original Error is:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddow.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/test.py", line 2, in <module>
    paddle.utils.run_check()
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 282, in run_chec
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 255, in run_chec
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 206, in _run_parl
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 585, in spawn
    process.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1712649883 (unix time) try "date -d @1712649883" if you are using GNU dat*]
  [SignalInfo: *** SIGTERM (@0x1f08) received by PID 8024 (TID 0x7f27c9971480) from PID 7944 ***]

[2024-04-09 16:04:43,870] [ WARNING] install_check.py:265 - PaddlePaddle meets some problem with 2 GPThis may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://githom/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-g/index.html
[2024-04-09 16:04:43,870] [ WARNING] install_check.py:275 -
 Original Error is: Process 0 terminated with exit code 1.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddow.
Traceback (most recent call last):
  File "/data/test.py", line 2, in <module>
    paddle.utils.run_check()
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 282, in run_chec
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 255, in run_chec
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 206, in _run_parl
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 595, in spawn
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 399, in join
    self._throw_exception(error_index)
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 411, in _throw_excon
    raise Exception(
Exception: Process 0 terminated with exit code 1.

**Comment by GreatV** [comment]
可以到[paddle](https://github.com/PaddlePaddle/Paddle)仓库下反馈一下

**Comment by TingquanGao** [comment]
是否试过在docker中运行呢？`nvidia-docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6 /bin/bash`，参考https://www.paddlepaddle.org.cn/

**Comment by q465414859** [comment]
> 是否试过在docker中运行呢？`nvidia-docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6 /bin/bash`，参考https://www.paddlepaddle.org.cn/

还是一样的报错。

root@ecs-1cf4:~# docker exec -it 9e2548b1330a /bin/bash
λ 9e2548b1330a /home ls
ccache-4.8.2/  cmake-3.18.0-Linux-x86_64/  log/  test.py
λ 9e2548b1330a /home python test.py 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Running verify PaddlePaddle program ... 
I0415 01:15:44.325572    50 program_interpreter.cc:212] New Executor is Running.
W0415 01:15:44.326015    50 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.0, Runtime API Version: 12.0
W0415 01:15:44.327044    50 gpu_resources.cc:164] device: 0, cuDNN Version: 8.8.
I0415 01:15:46.750312    50 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
grep: grep: warning: GREP_OPTIONS is deprecated; please use an alias or scriptwarning: GREP_OPTIONS is deprecated; please use an alias or script

Running verify PaddlePaddle program ... 
Running verify PaddlePaddle program ... 
I0415 01:15:50.691897   125 program_interpreter.cc:212] New Executor is Running.
W0415 01:15:50.692445   125 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.0, Runtime API Version: 12.0
W0415 01:15:50.693403   125 gpu_resources.cc:164] device: 0, cuDNN Version: 8.8.
I0415 01:15:50.697796   126 program_interpreter.cc:212] New Executor is Running.
W0415 01:15:50.698231   126 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.0, Runtime API Version: 12.0
W0415 01:15:50.699101   126 gpu_resources.cc:164] device: 0, cuDNN Version: 8.8.
I0415 01:15:53.014739   126 interpreter_util.cc:624] Standalone Executor is Used.
I0415 01:15:53.020294   125 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
[2024-04-15 01:15:53,026] [ WARNING] install_check.py:289 - PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
[2024-04-15 01:15:53,026] [ WARNING] install_check.py:297 - 
 Original Error is: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test.py", line 2, in <module>
    paddle.utils.run_check()
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 302, in run_check
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 283, in run_check
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 210, in _run_parallel
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 604, in spawn
    process.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
PaddlePaddle works well on 1 GPU.
[2024-04-15 01:15:53,031] [ WARNING] install_check.py:289 - PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
[2024-04-15 01:15:53,031] [ WARNING] install_check.py:297 - 
 Original Error is: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test.py", line 2, in <module>
    paddle.utils.run_check()
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 302, in run_check
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 283, in run_check
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 210, in _run_parallel
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 604, in spawn
    process.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
[2024-04-15 01:15:53,654] [ WARNING] install_check.py:289 - PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
[2024-04-15 01:15:53,654] [ WARNING] install_check.py:297 - 
 Original Error is: Process 0 terminated with exit code 1.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
Traceback (most recent call last):
  File "/home/test.py", line 2, in <module>
    paddle.utils.run_check()
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 302, in run_check
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 283, in run_check
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 210, in _run_parallel
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 614, in spawn
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 423, in join
    self._throw_exception(error_index)
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 435, in _throw_exception
    raise Exception(
Exception: Process 0 terminated with exit code 1.

**Comment by TingquanGao** [comment]
辛苦转到Paddle框架的issue跟进：https://github.com/PaddlePaddle/Paddle/issues/63386
