### ISSUE TITLE
急急急，训练v4的rec模型，出现BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zhanghengjiayou** [PaddlePaddle/PaddleOCR#11951]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu20.04 cuda12.2 cudnn 8.1(paddle要求8.2，但目前能训练)
- 版本号/Version：Paddle：2.4.2gpu-post112  PaddleOCR：2.7 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train -c config/rec/pp-ocrv4/ch_PP-OCRv4_rec_hgnet.yml
- 完整报错/Complete Error Message：

[2024/04/17 10:09:48] ppocr INFO: epoch: [124/800], global_step: 2232, lr: 0.000947, acc: 0.957031, norm_edit_dis: 0.997020, CTCLoss: 0.228386, NRTRLoss: 2.013444, loss: 2.227122, avg_reader_cost: 0.10725 s, avg_batch_cost: 0.18262 s, avg_samples: 12.8, ips: 70.09017 samples/s, eta: 5:24:45, max_mem_reserved: 11835 MB, max_mem_allocated: 9273 MB
Traceback (most recent call last):
  File "tools/train.py", line 229, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "tools/train.py", line 204, in main
    amp_custom_white_list, amp_dtype)
  File "/mnt/122.149-sr01/zhangheng/Project/Python/PaddleOCR-2.7/tools/program.py", line 467, in train
    global_step=global_step)
  File "/mnt/122.149-sr01/zhangheng/Project/Python/PaddleOCR-2.7/ppocr/utils/save_load.py", line 205, in save_model
    paddle.save(optimizer.state_dict(), model_prefix + '.pdopt')
  File "/home/gpu_zh/.local/lib/python3.7/site-packages/paddle/framework/io.py", line 811, in save
    _legacy_save(obj, path, protocol)
  File "/home/gpu_zh/.local/lib/python3.7/site-packages/paddle/framework/io.py", line 873, in _legacy_save
    pickle.dump(saved_obj, f, protocol=protocol)
BrokenPipeError: [Errno 32] Broken pipe

config file如下：

Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_ppocr_v4_hgnet
  save_epoch_step: 50
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: model/ch_PP-OCRv4_rec_server_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_HGNet
  Transform:
  Backbone:
    name: PPHGNet_small
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: ./train/image
    ext_op_transform_idx: 1
    label_file_list:
    - ./train/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[320, 32], [320, 48], [320, 64]]
    first_bs: &bs 128
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: true
    num_workers: 0
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train/image
    label_file_list:
    - ./train/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 0

![(A %5 VQOSST~)3AF96$7](https://github.com/PaddlePaddle/PaddleOCR/assets/38059512/035c8455-b47e-4bfd-9b11-c5f885fb02c2)

**Comment by zhanghengjiayou** [comment]
@Sunting78 老师能帮忙看看吗
