### ISSUE TITLE
训练自己的rec模型报错

### ISSUE THREAD

**Issue by 1259666087** [PaddlePaddle/PaddleOCR#12063]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu  python3.8
- 版本号/Version：Paddle：2.5.1  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code： python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c /public/home/liuzhongyang/guo/PaddleOCR/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=/public/home/liuzhongyang/guo/PaddleOCR/model/best_model/best_model/model.pdparams

- 完整报错/Complete Error Message：
I0507 12:39:47.985450 44903 tcp_utils.cc:181] The server starts to listen on IP_ANY:63081
I0507 12:39:47.985638 44903 tcp_utils.cc:130] Successfully connected to 12.12.12.125:63081
W0507 12:39:56.520090 44903 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.1, Runtime API Version: 11.4
W0507 12:39:56.600693 44903 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.
[2024/05/07 12:39:58] ppocr INFO: Initialize indexs of datasets:['/public/home/liuzhongyang/guo/data_rec/train_dataset.txt']
list index out of range
[2024/05/07 12:40:00] ppocr INFO: Initialize indexs of datasets:['/public/home/liuzhongyang/guo/data_rec/val_dataset.txt']
[2024/05/07 12:40:01] ppocr INFO: train dataloader has 1203 iters
[2024/05/07 12:40:01] ppocr INFO: valid dataloader has 1204 iters
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Teacher.head.ctc_head.fc.weight [64, 6625] not matched with loaded params Teacher.head.ctc_head.fc.weight [64, 8221] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Teacher.head.ctc_head.fc.bias [6625] not matched with loaded params Teacher.head.ctc_head.fc.bias [8221] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Teacher.head.sar_head.decoder.embedding.weight [6627, 512] not matched with loaded params Teacher.head.sar_head.decoder.embedding.weight [8223, 512] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Teacher.head.sar_head.decoder.prediction.weight [1536, 6626] not matched with loaded params Teacher.head.sar_head.decoder.prediction.weight [1536, 8222] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Teacher.head.sar_head.decoder.prediction.bias [6626] not matched with loaded params Teacher.head.sar_head.decoder.prediction.bias [8222] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Student.head.ctc_head.fc.weight [64, 6625] not matched with loaded params Student.head.ctc_head.fc.weight [64, 8221] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Student.head.ctc_head.fc.bias [6625] not matched with loaded params Student.head.ctc_head.fc.bias [8221] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Student.head.sar_head.decoder.embedding.weight [6627, 512] not matched with loaded params Student.head.sar_head.decoder.embedding.weight [8223, 512] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Student.head.sar_head.decoder.prediction.weight [1536, 6626] not matched with loaded params Student.head.sar_head.decoder.prediction.weight [1536, 8222] !
[2024/05/07 12:40:04] ppocr WARNING: The shape of model params Student.head.sar_head.decoder.prediction.bias [6626] not matched with loaded params Student.head.sar_head.decoder.prediction.bias [8222] !
[2024/05/07 12:40:04] ppocr INFO: load pretrain successful from /public/home/liuzhongyang/guo/PaddleOCR/model/best_model/best_model/model
[2024/05/07 12:40:04] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
LAUNCH WARNING 2024-05-07 12:42:31,921 save gpu log failed
LAUNCH WARNING 2024-05-07 12:44:01,188 save gpu log failed
LAUNCH INFO 2024-05-07 12:45:00,823 Pod failed
LAUNCH ERROR 2024-05-07 12:45:00,829 Container failed !!!
Container rank 3 status failed cmd ['/public/home/liuzhongyang/.conda/envs/paddle_guo1/bin/python3', '-u', 'tools/train.py', '-c', '/public/home/liuzhongyang/guo/PaddleOCR/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml', '-o', 'Global.pretrained_model=/public/home/liuzhongyang/guo/PaddleOCR/model/best_model/best_model/model.pdparams'] code -9 log log/workerlog.3
env {'MANPATH': '/opt/gridview/pmix/share/pmix:/opt/gridview/ucx/share/ucx:/opt/gridview/slurm/share/man:/opt/gridview/munge/share/man:', 'HOSTNAME': 'sist_gpu69', 'SLURM_PMIX_DIRECT_CONN_UCX': 'false', 'UCX_HOME': '/opt/gridview/ucx', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'HISTSIZE': '1000', 'SSH_CLIENT': '12.12.12.49 44906 22', 'CONDA_SHLVL': '2', 'PERL5LIB': '/public/home/liuzhongyang/perl5/lib/perl5:', 'CONDA_PROMPT_MODIFIER': '(paddle_guo1) ', 'QTDIR': '/usr/lib64/qt-3.3', 'OLDPWD': '/public/home/liuzhongyang', 'QTINC': '/usr/lib64/qt-3.3/include', 'PERL_MB_OPT': '--install_base /public/home/liuzhongyang/perl5', 'SSH_TTY': '/dev/pts/1', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'UCX_WARN_UNUSED_ENV_VARS': 'n', 'USER': 'liuzhongyang', 'LD_LIBRARY_PATH': '/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/cv2/../../lib64:/public/home/liuzhongyang/software/nccl_2.21.5-1+cuda11.0_x86_64/include/:/public/home/liuzhongyang/software/nccl_2.21.5-1+cuda11.0_x86_64/lib:/public/home/liuzhongyang/openssl/lib:/public/software/CUDA/cuda-11.4/lib64:/opt/gridview/pmix/lib:/opt/gridview/ucx/lib:/opt/gridview/ucx/lib/ucx:/opt/gridview/slurm/lib:/opt/gridview/slurm/lib64:/opt/gridview/munge/lib:/public/home/liuzhongyang/software/nccl/lib\r', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'CONDA_EXE': '/public/software/anaconda3/bin/conda', '_CE_CONDA': '', 'CONDA_PREFIX_1': '/public/software/anaconda3', 'MAIL': '/var/spool/mail/liuzhongyang', 'PATH': '/public/home/liuzhongyang/.conda/envs/paddle_guo1/bin:/public/software/anaconda3/condabin:/public/home/liuzhongyang/openssl/bin:/public/software/CUDA/cuda-11.4/bin:/public/software/anaconda3/bin:/usr/lib64/qt-3.3/bin:/opt/gridview/pmix/bin:/opt/gridview/pmix/sbin:/opt/gridview/ucx/bin:/opt/gridview/ucx/sbin:/public/home/liuzhongyang/perl5/bin:/opt/gridview/slurm/bin:/opt/gridview/slurm/sbin:/opt/gridview/munge/bin:/opt/gridview/munge/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/public/home/liuzhongyang/software/nccl/include', 'SLURM_JOB_ID': '613777', 'CONDA_PREFIX': '/public/home/liuzhongyang/.conda/envs/paddle_guo1', 'C_INCLUDE_PATH': '/opt/gridview/pmix/include:/opt/gridview/ucx/include:/opt/gridview/slurm/include:/opt/gridview/munge/include', 'PWD': '/public/home/liuzhongyang/guo/PaddleOCR', 'LANG': 'en_US.UTF-8', 'MODULEPATH': '/public/software/modules:/public/software/modules', 'SLURM_PMIX_TIMEOUT': '3000', 'LOADEDMODULES': '', 'KDEDIRS': '/usr', 'SLURM_HOME': '/opt/gridview/slurm', '_CE_M': '', 'HISTCONTROL': 'ignoredups', 'SHLVL': '1', 'HOME': '/public/home/liuzhongyang', 'SLURM_PMIX_DIRECT_CONN': 'true', 'PERL_LOCAL_LIB_ROOT': ':/public/home/liuzhongyang/perl5', 'CONDA_PYTHON_EXE': '/public/software/anaconda3/bin/python', 'LOGNAME': 'liuzhongyang', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'XDG_DATA_DIRS': '/public/home/liuzhongyang/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share', 'SSH_CONNECTION': '12.12.12.49 44906 12.12.12.125 22', 'MODULESHOME': '/usr/share/Modules', 'CONDA_DEFAULT_ENV': 'paddle_guo1', 'PMIX_HOME': '/opt/gridview/pmix', 'MUNGE_HOME': '/opt/gridview/munge', 'QT_PLUGIN_PATH': '/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins', 'PERL_MM_OPT': 'INSTALL_BASE=/public/home/liuzhongyang/perl5', 'SLURM_PMIX_DIRECT_CONN_EARLY': 'false', 'BASH_FUNC_module()': '() {  eval `/usr/bin/modulecmd bash $*`\n}', '_': '/public/home/liuzhongyang/.conda/envs/paddle_guo1/bin/python3', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/cv2/qt/fonts', 'POD_NAME': 'zldxnv', 'PADDLE_MASTER': '12.12.12.125:63081', 'PADDLE_GLOBAL_SIZE': '4', 'PADDLE_LOCAL_SIZE': '4', 'PADDLE_GLOBAL_RANK': '3', 'PADDLE_LOCAL_RANK': '3', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '12.12.12.125:63082,12.12.12.125:63083,12.12.12.125:63084,12.12.12.125:63085', 'PADDLE_CURRENT_ENDPOINT': '12.12.12.125:63085', 'PADDLE_TRAINER_ID': '3', 'PADDLE_TRAINERS_NUM': '4', 'PADDLE_RANK_IN_NODE': '3', 'FLAGS_selected_gpus': '3'}
LAUNCH INFO 2024-05-07 12:45:00,830 ------------------------- ERROR LOG DETAIL -------------------------
12:39:47.958590 44959 tcp_utils.cc:107] Retry to connect to 12.12.12.125:63081 while the server is not yet listening.
I0507 12:39:50.958804 44959 tcp_utils.cc:130] Successfully connected to 12.12.12.125:63081
W0507 12:39:56.654572 44959 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 7.5, Driver API Version: 12.1, Runtime API Version: 11.4
W0507 12:39:56.676385 44959 gpu_resources.cc:149] device: 3, cuDNN Version: 8.2.
list index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 604, in _thread_loop
    batch = self._get_data()
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 708, in _get_data
    raise RuntimeError(
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 15049
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f4a316ec1f0>
Traceback (most recent call last):
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 794, in __del__
    self._try_shutdown_all()
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 586, in _try_shutdown_all
    w.join(timeout)
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/public/home/liuzhongyang/.conda/envs/paddle_guo1/lib/python3.8/site-packages/paddle/io/multiprocess_utils.py", line 135, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 15303) exited is killed by signal: Killed. (at ../paddle/fluid/imperative/data_loader.cc:189)

LAUNCH INFO 2024-05-07 12:45:04,573 Exit code -9

**Comment by 1259666087** [comment]
> 需要先确认下paddle框架是否正常，执行以下python代码
> 
> ```python
> import paddle
> paddle.utils.run_check()
> ```
I0507 18:56:20.621838 37919 tcp_utils.cc:130] Successfully connected to 127.0.0.1:35940
W0507 18:56:55.101862 37917 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:55.136854 37928 gpu_resources.cc:119] Please NOTE: device: 5, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:55.336438 37917 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.
W0507 18:56:55.561231 37928 gpu_resources.cc:149] device: 5, cuDNN Version: 8.2.
W0507 18:56:56.032884 37924 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:56.118166 37924 gpu_resources.cc:149] device: 3, cuDNN Version: 8.2.
W0507 18:56:56.171370 37926 gpu_resources.cc:119] Please NOTE: device: 4, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:56.278628 37930 gpu_resources.cc:119] Please NOTE: device: 6, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:56.314707 37932 gpu_resources.cc:119] Please NOTE: device: 7, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:56.314240 37919 gpu_resources.cc:119] Please NOTE: device: 1, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:56.321817 37926 gpu_resources.cc:149] device: 4, cuDNN Version: 8.2.
W0507 18:56:56.351359 37930 gpu_resources.cc:149] device: 6, cuDNN Version: 8.2.
W0507 18:56:56.360203 37932 gpu_resources.cc:149] device: 7, cuDNN Version: 8.2.
W0507 18:56:56.414502 37919 gpu_resources.cc:149] device: 1, cuDNN Version: 8.2.
W0507 18:56:56.481050 37921 gpu_resources.cc:119] Please NOTE: device: 2, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0507 18:56:56.543385 37921 gpu_resources.cc:149] device: 2, cuDNN Version: 8.2.
I0507 18:57:31.844931 38067 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
PaddlePaddle works well on 8 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by UserWangZz** [comment]
检查一下可能是配置文件和预训练模型不匹配导致的

**Comment by 1259666087** [comment]
> 检查一下可能是配置文件和预训练模型不匹配导致的

您好单卡可以在a40上运行但是多卡a100没法运行 a100的环境是Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.2

**Comment by TingquanGao** [comment]
感觉是环境问题，建议使用Paddle官方docker试试，具体可以参考文档：

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
