### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle'

### ISSUE THREAD

**Issue by seeeyou** [PaddlePaddle/PaddleOCR#12107]
```
(paddle_env) ☁  PaddleOCR [main] ⚡  python tools/infer_kie_token_ser_re.py \
    -o Architecture.Backbone.checkpoints=/Users/qyongkang/working/paddle/re_LayoutXLM_xfun_zh/ \
    Global.infer_img=/Users/qyongkang/working/paddle/form/ \
    -o_ser Architecture.Backbone.checkpoints=/Users/qyongkang/working/paddle/ser_LayoutXLM_xfun_zh/
Traceback (most recent call last):
  File "/Users/qyongkang/working/PaddleOCR/tools/infer_kie_token_ser_re.py", line 31, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'
```
请问如何解决，文档中写的这样运行，但结果有错误。安装paddle时也安装不了，提示另外的错误
```
(paddle_env) ☁  PaddleOCR [main] ⚡  pip install paddle                      
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8l/pl5jym7107n6dbn56f5slg7r0000gn/T/pip-install-69isce0v/paddle_78dbfedf57be4d18bbd73b6de304acb1/setup.py", line 3, in <module>
          import paddle
        File "/private/var/folders/8l/pl5jym7107n6dbn56f5slg7r0000gn/T/pip-install-69isce0v/paddle_78dbfedf57be4d18bbd73b6de304acb1/paddle/__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

**Comment by GreatV** [comment]
这是什么运行环境 参考 https://www.paddlepaddle.org.cn/ 快速安装

**Comment by UserWangZz** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/quickstart.md
参考文档
