### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by QQiangren** [PaddlePaddle/PaddleOCR#12118]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Linux,CenterOS7
- 版本号/Version：paddleclas==2.5.2,paddleocr==2.7.3,paddlepaddle-gpu==2.6.1

- 运行指令/Command Code：paddleocr --image_dir=ppstructure/docs/table/1.png --type=structure --image_orientation=true

- 完整报错/Complete Error Message：
[2024/05/15 09:01:00] ppocr DEBUG: Namespace(alpha=1.0, alphacolor=(255, 255, 255), benchmark=False, beta=1.0, binarize=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir=None, cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_id=0, gpu_mem=500, help='==SUPPRESS==', image_dir='1.png', image_orientation=False, invert=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path='/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppocr/utils/dict/layout_dict/layout_cdla_dict.txt', layout_model_dir='/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer', layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv4', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/root/.paddleocr/whl/rec/ch/ch_PP-OCRv4_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path='/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppocr/utils/dict/table_structure_dict_ch.txt', table_max_len=488, table_model_dir='/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer', total_process_num=1, type='structure', use_angle_cls=False, use_dilation=False, use_gpu=True, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2024/05/15 09:01:07] ppocr INFO: **********1.png**********
[2024/05/15 09:01:07] ppocr INFO: processing 1/1 page:
[2024/05/15 09:01:09] ppocr DEBUG: dt_boxes num : 7, elapsed : 0.21311306953430176
Traceback (most recent call last):
  File "/paasdata/anaconda3/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 842, in main
    result = engine(img, img_idx=index)
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 766, in __call__
    res, _ = super().__call__(
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 143, in __call__
    filter_boxes, filter_rec_res, ocr_time_dict = self.text_system(
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 105, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/tools/infer/predict_rec.py", line 616, in __call__
    self.predictor.run()
OSError: (External) CUBLAS error(7).
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:599)
  [operator < fc > error]

**Comment by GreatV** [comment]
`use_gpu=False` 试一下看看

**Comment by QQiangren** [comment]
你好，我执行了：paddleocr --image_dir=./1.png --type=structure --use_gpu=False
报错如下：
[2024/05/15 09:29:15] ppocr INFO: **********./1.png**********
[2024/05/15 09:29:15] ppocr INFO: processing 1/1 page:
[2024/05/15 09:29:15] ppocr DEBUG: dt_boxes num : 7, elapsed : 0.12430214881896973
[2024/05/15 09:29:17] ppocr DEBUG: rec_res num  : 7, elapsed : 1.2942302227020264
[2024/05/15 09:29:17] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.0942528247833252
[2024/05/15 09:29:17] ppocr DEBUG: rec_res num  : 2, elapsed : 0.14473485946655273
[2024/05/15 09:29:17] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.05190682411193848
[2024/05/15 09:29:17] ppocr DEBUG: rec_res num  : 0, elapsed : 1.430511474609375e-06
[2024/05/15 09:29:17] ppocr DEBUG: dt_boxes num : 21, elapsed : 0.2660982608795166
[2024/05/15 09:29:18] ppocr DEBUG: rec_res num  : 21, elapsed : 0.9750688076019287
[2024/05/15 09:29:18] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.13176536560058594
[2024/05/15 09:29:18] ppocr DEBUG: rec_res num  : 1, elapsed : 0.08745384216308594
[2024/05/15 09:29:18] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.031230926513671875
[2024/05/15 09:29:18] ppocr DEBUG: rec_res num  : 0, elapsed : 1.430511474609375e-06
[2024/05/15 09:29:20] ppocr DEBUG: dt_boxes num : 80, elapse : 0.1718449592590332
[2024/05/15 09:29:23] ppocr DEBUG: rec_res num  : 80, elapse : 2.6729636192321777
[2024/05/15 09:29:24] ppocr DEBUG: dt_boxes num : 110, elapse : 0.2005479335784912
[2024/05/15 09:29:28] ppocr DEBUG: rec_res num  : 110, elapse : 3.736450672149658
[2024/05/15 09:29:28] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.09121108055114746
[2024/05/15 09:29:29] ppocr DEBUG: rec_res num  : 1, elapsed : 0.21436071395874023
[2024/05/15 09:29:29] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.03216981887817383
[2024/05/15 09:29:29] ppocr DEBUG: rec_res num  : 1, elapsed : 0.12643194198608398
Traceback (most recent call last):
  File "/paasdata/anaconda3/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 843, in main
    save_structure_res(result, args.output, img_name, index)
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 206, in save_structure_res
    to_excel(region['res']['html'], excel_path)
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppstructure/table/predict_table.py", line 144, in to_excel
    from tablepyxl import tablepyxl
  File "/paasdata/anaconda3/lib/python3.8/site-packages/paddleocr/ppstructure/table/tablepyxl/tablepyxl.py", line 5, in <module>
    from openpyxl import Workbook
  File "/paasdata/anaconda3/lib/python3.8/site-packages/openpyxl/__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/paasdata/anaconda3/lib/python3.8/site-packages/openpyxl/compat/__init__.py", line 3, in <module>
    from .numbers import NUMERIC_TYPES
  File "/paasdata/anaconda3/lib/python3.8/site-packages/openpyxl/compat/numbers.py", line 41, in <module>
    numpy.float,
  File "/paasdata/anaconda3/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by GreatV** [comment]
可能需要最新版本的PaddleOCR `pip install -e git+https://https://github.com/PaddlePaddle/PaddleOCR.git`，或者降低一下numpy的版本

**Comment by Sunting78** [comment]
NumPy 1.20版本后不再支持float
