### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by dyhisbig** [PaddlePaddle/PaddleOCR#12163]
RecursionError: maximum recursion depth exceeded in comparison
使用自己的数据集训练出现这个问题，是不是数据集的量太少了啊，我就放了几张图

[2024/05/24 09:50:36] ppocr ERROR: **When parsing line G:\zifu_shibie\train_data\rec\train\A40-1-8246ECam_crop_3.jpg      H
, error happened with msg: Traceback (most recent call last):**
  File "G:\zifu_shibie\PaddleOCR-release-2.7\ppocr\data\simple_dataset.py", line 158, in __getitem__
    data['ext_data'] = self.get_ext_data()
  File "G:\zifu_shibie\PaddleOCR-release-2.7\ppocr\data\simple_dataset.py", line 124, in get_ext_data
    label = substr[1]
IndexError: list index out of range

**Comment by GreatV** [comment]
看着像字典没用对

**Comment by zhangyubo0722** [comment]
检查所用的是否传入参数character_dict_path

**Comment by YangWulve** [comment]
可以看一下training.txt还有训练用的yml文件。
1. training.txt是否和需要格式完全一致，详见对应readme， path \r labels \n
2. yml文件可以配置无需ext_data

因为这里label = substr[1]报错数组越界，在正常情况下substr[0]是img_path， substr[1]是对应label。
