### ISSUE TITLE
cffi.VerificationError: CompileError: command '/usr/bin/clang' failed with exit code 1

### ISSUE THREAD

**Issue by gaowq2017** [PaddlePaddle/PaddleOCR#12164]
System Environment：
Mac os
Version：Paddle：2.6.1  PaddleOCR： 2.7.3
Command Code：from paddleocr import PaddleOCR
Complete Error Message：
通过pip安装的paddleocr，已经成功安装了paddle，并且测试已经OK，导入orc相关的包时出现编译器问题
brew install cffi也已经安装
请问有没有遇到同样问题的，谢谢

**Comment by GreatV** [comment]
用的python版本是多少

**Comment by gaowq2017** [comment]
> 用的python版本是多少

python3.9

**Comment by changdazhou** [comment]
建议尝试一下PaddleOCR2.7.0试下呢，另外能贴一下报错信息吗

**Comment by gaowq2017** [comment]
> 建议尝试一下PaddleOCR2.7.0试下呢，另外能贴一下报错信息吗

安装paddleocr==2.7.0时提示PyMuPDF这个包build失败！
以下是具体的错误信息
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 48, in <module>
    from tools.infer import predict_system
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/paddleocr/tools/infer/predict_system.py", line 33, in <module>
    import tools.infer.predict_det as predict_det
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/paddleocr/tools/infer/predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/paddleocr/ppocr/data/__init__.py", line 37, in <module>
    from ppocr.data.lmdb_dataset import LMDBDataSet, LMDBDataSetSR, LMDBDataSetTableMaster
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/paddleocr/ppocr/data/lmdb_dataset.py", line 17, in <module>
    import lmdb
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/lmdb/__init__.py", line 48, in <module>
    from lmdb.cffi import *
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/lmdb/cffi.py", line 372, in <module>
    _lib = _ffi.verify(_CFFI_VERIFY,
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/cffi/api.py", line 468, in verify
    lib = self.verifier.load_library()
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/cffi/verifier.py", line 105, in load_library
    self._compile_module()
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/cffi/verifier.py", line 201, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Users/theoyu/miniforge3/envs/py39/lib/python3.9/site-packages/cffi/ffiplatform.py", line 54, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/usr/bin/clang' failed with exit code 1

**Comment by zhangyubo0722** [comment]
可以尝试clone PaddleOCR套件代码，采用自定义安装的方式

**Comment by zhangyubo0722** [comment]
可以尝试clone PaddleOCR套件代码，采用自定义安装的方式`cd PaddleOCR; pip install -e .`

**Comment by gaowq2017** [comment]
> 可以尝试clone PaddleOCR套件代码，采用自定义安装的方式`cd PaddleOCR; pip install -e .`

试过了，可以安装，但是import还是同样的错误
