### ISSUE TITLE
list index out of range EAST and SAST

### ISSUE THREAD

**Issue by baireddy417** [PaddlePaddle/PaddleOCR#1218]
I was trying to use east and sast model for text detection but i was getting list index out of range error 
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 181, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 145, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 88, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Users\harish\PaddleOCR\tools\infer\predict_det.py", line 155, in __call__
    outs_dict['f_score'] = outputs[1]
IndexError: list index out of range

**Comment by MissPenguin** [comment]
When using east or sast for text detection, you should add the parameter "det_algorithm". Check out more details here: https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/inference_en.md#2-other-models

**Comment by pruthviraj2453** [comment]
Did you get the solution to this ? I am facing same error while trying to run with det_algorithm as "EAST"
