### ISSUE TITLE
Detection training and EVALUATION problems..

### ISSUE THREAD

**Issue by yeongwoonIm** [PaddlePaddle/PaddleOCR#1244]
OS : windows8.1

I trained 8 pictures for detection. 
I just want to know training is possible or not..
I tried training as below command.
>> python tools/train.py -c configs/det/det_r50_vd_custom.yml

###Command screen###
F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop>python tools/train.py -c configs/det/det_r50_vd_custom.yml
2020-11-25 15:56:04,078-INFO: {'Global': {'debug': False, 'algorithm': 'DB', 'use_gpu': True, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': './output/det_db/', 'save_epoch_step': 200, 'eval_batch_step': [5000, 5000], 'train_batch_size_per_card': 8, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': './configs/det/det_db_custom_reader.yml', 'pretrain_weights': './pretrain_models/detection/ResNet50_vd_ssld_pretrained/', 'save_res_path': './output/det_db/predicts_db.txt', 'checkpoints': None, 'save_inference_dir': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_resnet_vd,ResNet', 'layers': 50}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 256, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.7, 'max_candidates': 1000, 'unclip_ratio': 1.5}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 8, 'img_set_dir': './training_set/training_test/training_img/', 'label_file_path': './training_set/training_test/kor_test_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': './training_set/training_test/training_img/', 'label_file_path': './training_set/training_test/kor_test_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'infer_img': None, 'img_set_dir': './training_set/training_test/training_img/', 'label_file_path': './training_set/training_test/kor_test_label.txt', 'do_eval': True}}
3 640 640
2020-11-25 15:56:04,795-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000000] in Optimizer will not take effect, and it will only be applied to other Parameters!
3 640 640
./training_set/training_test/kor_test_label.txt
2020-11-25 15:56:06,469-INFO: places would be ommited when DataLoader is not iterable
W1125 15:56:06.549525  9180 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 10.0
W1125 15:56:06.557544  9180 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-11-25 15:56:08,586-INFO: Loading parameters from ./pretrain_models/detection/ResNet50_vd_ssld_pretrained/...
2020-11-25 15:56:08,586-WARNING: ./pretrain_models/detection/ResNet50_vd_ssld_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-11-25 15:56:09,130-INFO: Finish initing model from ./pretrain_models/detection/ResNet50_vd_ssld_pretrained/
2020-11-25 15:56:09,131-INFO: During the training process, after the 5000th iteration, an evaluation is run every 5000 iterations
W1125 15:56:09.160465  9180 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
multiprocess is not fully compatible with Windows.num_workers will be 1.
2020-11-25 16:01:07,267-INFO: Already save model in ./output/det_db//iter_epoch_200
2020-11-25 16:06:15,168-INFO: Already save model in ./output/det_db//iter_epoch_400
2020-11-25 16:11:11,098-INFO: Already save model in ./output/det_db//iter_epoch_600
2020-11-25 16:16:06,388-INFO: Already save model in ./output/det_db//iter_epoch_800
2020-11-25 16:21:04,741-INFO: Already save model in ./output/det_db//iter_epoch_1000
####################################################################

then I got 15 files on output folder.

and I checked EVALUATION.
the command
>> python tools/eval.py -c configs/det/det_r50_vd_custom.yml  -o Global.checkpoints="./output/det_db/best_accuracy" PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5

###Command screen###
F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop>python tools/eval.py -c configs/det/det_r50_vd_custom.yml  -o Global.checkpoints="./output/det_db/best_accuracy" PostProcess.box_thresh=0.6 PostProcess.unclip_ratio=1.5
2020-11-25 16:41:08,296-INFO: {'Global': {'debug': False, 'algorithm': 'DB', 'use_gpu': True, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': './output/det_db/', 'save_epoch_step': 200, 'eval_batch_step': [5000, 5000], 'train_batch_size_per_card': 8, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': './configs/det/det_db_custom_reader.yml', 'pretrain_weights': './pretrain_models/detection/ResNet50_vd_ssld_pretrained/', 'save_res_path': './output/det_db/predicts_db.txt', 'checkpoints': './output/det_db/best_accuracy', 'save_inference_dir': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_resnet_vd,ResNet', 'layers': 50}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 256, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.6, 'max_candidates': 1000, 'unclip_ratio': 1.5}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 8, 'img_set_dir': './training_set/training_test/training_img/', 'label_file_path': './training_set/training_test/kor_test_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': './training_set/training_test/training_img/', 'label_file_path': './training_set/training_test/kor_test_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'infer_img': None, 'img_set_dir': './training_set/training_test/training_img/', 'label_file_path': './training_set/training_test/kor_test_label.txt', 'do_eval': True}}
3 640 640
W1125 16:41:08.924358 14752 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 10.0
W1125 16:41:08.981482 14752 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/eval.py", line 98, in <module>
    main()
  File "tools/eval.py", line 62, in main
    init_model(config, eval_program, exe)
  File "F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop\ppocr\utils\save_load.py", line 119, in init_model
    checkpoints + '.pdparams'))
ValueError: Model checkpoints ./output/det_db/best_accuracy.pdparams does not exists,check if you lost the file prefix.
####################################################################

then I got this error message..
What am i miss??

thank you for read.

**Comment by LDOUBLEV** [comment]
# Training
There is only model information in the training log, and no training iter information. You can debug the test_reader function in tools/train.py to ensure that the training data is read correctly.

# Evaluation
The error is "ValueError: Model checkpoints ./output/det_db/best_accuracy.pdparams does not exists"

**Comment by yeongwoonIm** [comment]
> # Training
> There is only model information in the training log, and no training iter information. You can debug the test_reader function in tools/train.py to ensure that the training data is read correctly.
> 
> # Evaluation
> The error is "ValueError: Model checkpoints ./output/det_db/best_accuracy.pdparams does not exists"

Thank you so much
