### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#1251]
python tools/test_hubserving.py http://127.0.0.1:8868/predict/ocr_system ./doc/imgs_en/
Traceback (most recent call last):
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb3cbade6d8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8868): Max retries exceeded with url: /predict/ocr_system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3cbade6d8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_hubserving.py", line 119, in <module>
    main(server_url, image_path)
  File "tools/test_hubserving.py", line 87, in main
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8868): Max retries exceeded with url: /predict/ocr_system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3cbade6d8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by MissPenguin** [comment]
seems like server is not started successfully. You can check your server by the following 2 steps:
1. restart you server and make sure it is started successfully.
2. check the server address (http://127.0.0.1:8868/predict/ocr_system) is right or not, especially the ip port 8868.

**Comment by Jitesh4389** [comment]
1.restart you server and make sure it is started successfully.
how to restart server  its not working

**Comment by Jitesh4389** [comment]
hub serving start -m ocr_system
W1127 14:18:05.772059 19265 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.
ocr_system == 1.0.0
 * Serving Flask app "paddlehub.serving.app_single" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-11-27 14:18:06,137-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
Intel MKL function load error: cpu specific dynamic library is not loaded.

**Comment by Jitesh4389** [comment]
*****************************************************************
Traceback (most recent call last):
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1b533a8048>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8866): Max retries exceeded with url: /predict/ocr_dat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b533a8048>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_hubserving.py", line 116, in <module>
    main(server_url, image_path)
  File "tools/test_hubserving.py", line 86, in main
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8866): Max retries exceeded with url: /predict/ocr_dat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b533a8048>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by zengqi0730** [comment]
修改映射端口 docker .....     8866:8866
