### ISSUE TITLE
使用带tps模型训练，识别结果出现问题

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#1279]
您好，我使用ctc+tps训练中文识别模型，训练配置如下：
![1](https://user-images.githubusercontent.com/51456283/100562918-027da900-32f8-11eb-87ac-b3a8c079ec9e.JPG)
但是训练出来的模型只能识别英文和数字，不能识别中文，连中文字符都没有，但是我检查了，字典是正确的，infer口令如下：
![捕获](https://user-images.githubusercontent.com/51456283/100562995-4375bd80-32f8-11eb-900f-f4de16ffb4c6.JPG)
检测结果如下：
![捕获](https://user-images.githubusercontent.com/51456283/100563025-59837e00-32f8-11eb-80df-c6ef448783dd.JPG)
请问是什么原因呢，无法识别中文字符。

**Comment by WenmuZhou** [comment]
infer模型是用你训练的模型导出的吗

**Comment by tyy2tyy** [comment]
是的，单独使用infer_rec.py预测失败，报错：
TPS does not support variable shape in chinese!We set img_shape to be the same , it may affect the inference effect

···
InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 32, 100].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] at (/paddle/paddle/fluid/operators/conv_op.cc:59)
  [operator < conv2d > error]

**Comment by WenmuZhou** [comment]
报错的问题把这里改掉就可以了，改掉之后看看infer_rec.py能不能跑出结果吧，https://github.com/PaddlePaddle/PaddleOCR/blob/develop/ppocr/modeling/architectures/rec_model.py#L156

下面那个报错看看这个能不能fix一下
https://github.com/PaddlePaddle/PaddleOCR/issues/1282#issuecomment-735679184

**Comment by tyy2tyy** [comment]
好的，更新了代码，重新测试，报了这个错：
2020-12-01 08:16:07,182-INFO: Finish initing model from /data/tang/OCR/Paddle_OC                                                                                                                                                             R/output/rec/rec_model/best_accuracy
2020-12-01 08:16:07,185-INFO: infer_img:doc/imgs_words/ch/word_5.jpg
/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserW                                                                                                                                                             arning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/infer_rec.py", line 176, in <module>
    main()
  File "tools/infer_rec.py", line 92, in main
    return_numpy=False)
  File "/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/miniconda3/lib/python3.7/site-packages/six.py", line 693, in rerais                                                                                                                                                             e
    raise value
  File "/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1066, in run
    return_merged=return_merged)
  File "/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1226, in _run_program
    self._feed_data(program, feed, feed_var_name, scope)
  File "/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 638, in _feed_data
    check_feed_shape_type(var, cur_feed)
  File "/opt/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 225, in check_feed_shape_type
    (var.name, len(var.shape), var.shape, diff_shape))
ValueError: The fed Variable 'image' should have dimensions = 4, shape = (-1, 3,                                                                                                                                                              32, 100), but received fed shape [1, 3, 32, 147] on each device
请问这应该怎么解决呢？tps不能用于识别中文吗？谢谢。

**Comment by littletomatodonkey** [comment]
目前tps还没有针对中文去适配，tps的模型，输入图像的shape需要是3x32x100，中文识别中，图像的shape会发生变化~

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
