### ISSUE TITLE
Error PaddleRE: The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]

### ISSUE THREAD

**Issue by piarosebelledelapaz** [PaddlePaddle/PaddleOCR#13065]
#### 问题描述 / Problem Description
Got an error for shape mismatch but its the same values, so i dont understand where the error is coming from. Trying to train RE model (LayoutXLMForRe) using custom dataset

#### 运行环境 / Runtime Environment
- OS: Windows
- Paddle:
- PaddleOCR:

#### 复现代码 / Reproduction Code
Global:
  use_gpu: False
  epoch_num: &epoch_num 100
  log_smooth_window: 10
  print_batch_step: 25
  save_model_dir: ./output/re_vi_layoutxlm_xfund_zh
  save_epoch_step: 2000
  eval_batch_step: [ 0, 2000 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img:
  save_res_path: ./output/re/xfund_zh/with_gt
  kie_rec_model_dir: ./pretrained_models/det_r50_db++_icdar15_train/best_accuracy.pdparams
  kie_det_model_dir: ./pretrained_models/multilang_PP-OCR_V3_det_rot10_adam_best_model/best_model/model.pdparams

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutXLM"
  Transform:
  Backbone:
    name: LayoutXLMForRe
    pretrained: True
    mode: vi
    checkpoints:

Loss:
  name: LossFromOutput
  key: loss
  reduction: mean

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr:
    learning_rate: 0.00005
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: VQAReTokenLayoutLMPostProcess

Metric:
  name: VQAReTokenMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./dataset/relation-extraction/img_re_train
    label_file_list: 
      - ./dataset/relation-extraction/re_train.txt
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: &class_path ./dataset/relation-extraction/class_list.txt
          use_textline_bbox_info: &use_textline_bbox_info True
          order_method: &order_method "tb-yx"
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
          entities_labels: {'VACCINE_NAME': 1, 'VACCINE_DATE':2}
      - TensorizeEntitiesRelations:
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox','attention_mask', 'token_type_ids', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 2
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./dataset/relation-extraction/img_re_eval
    label_file_list:
      - dataset/relation-extraction/re_eval.txt
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: *use_textline_bbox_info
          order_method: *order_method
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
      - TensorizeEntitiesRelations:
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8
    num_workers: 8

#### 完整报错 / Complete Error Message
(luks_paddleOCR) PS C:\Users\piade\LUKS\luks_ocr> python tools/train.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml
[2024/06/14 02:15:28] ppocr INFO: Architecture : 
[2024/06/14 02:15:28] ppocr INFO:     Backbone :
[2024/06/14 02:15:28] ppocr INFO:         checkpoints : None
[2024/06/14 02:15:28] ppocr INFO:         mode : vi
[2024/06/14 02:15:28] ppocr INFO:         name : LayoutXLMForRe
[2024/06/14 02:15:28] ppocr INFO:         pretrained : True
[2024/06/14 02:15:28] ppocr INFO:     Transform : None
[2024/06/14 02:15:28] ppocr INFO:     algorithm : LayoutXLM
[2024/06/14 02:15:28] ppocr INFO:     model_type : kie
[2024/06/14 02:15:28] ppocr INFO: Eval :
[2024/06/14 02:15:28] ppocr INFO:     dataset :
[2024/06/14 02:15:28] ppocr INFO:         data_dir : ./dataset/relation-extraction/img_re_eval
[2024/06/14 02:15:28] ppocr INFO:         label_file_list : ['dataset/relation-extraction/re_eval.txt']
[2024/06/14 02:15:28] ppocr INFO:         name : SimpleDataSet
[2024/06/14 02:15:28] ppocr INFO:         transforms :
[2024/06/14 02:15:28] ppocr INFO:             DecodeImage :
[2024/06/14 02:15:28] ppocr INFO:                 channel_first : False
[2024/06/14 02:15:28] ppocr INFO:                 img_mode : RGB
[2024/06/14 02:15:28] ppocr INFO:             VQATokenLabelEncode :
[2024/06/14 02:15:28] ppocr INFO:                 algorithm : LayoutXLM
[2024/06/14 02:15:28] ppocr INFO:                 class_path : ./dataset/relation-extraction/class_list.txt
[2024/06/14 02:15:28] ppocr INFO:                 contains_re : True
[2024/06/14 02:15:28] ppocr INFO:                 order_method : tb-yx
[2024/06/14 02:15:28] ppocr INFO:                 use_textline_bbox_info : True
[2024/06/14 02:15:28] ppocr INFO:             VQATokenPad :
[2024/06/14 02:15:28] ppocr INFO:                 max_seq_len : 512
[2024/06/14 02:15:28] ppocr INFO:                 return_attention_mask : True
[2024/06/14 02:15:28] ppocr INFO:             VQAReTokenRelation : None
[2024/06/14 02:15:28] ppocr INFO:             VQAReTokenChunk :
[2024/06/14 02:15:28] ppocr INFO:                 max_seq_len : 512
[2024/06/14 02:15:28] ppocr INFO:             TensorizeEntitiesRelations : None
[2024/06/14 02:15:28] ppocr INFO:             Resize :
[2024/06/14 02:15:28] ppocr INFO:                 size : [224, 224]
[2024/06/14 02:15:28] ppocr INFO:             NormalizeImage :
[2024/06/14 02:15:28] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2024/06/14 02:15:28] ppocr INFO:                 order : hwc
[2024/06/14 02:15:28] ppocr INFO:                 scale : 1
[2024/06/14 02:15:28] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2024/06/14 02:15:28] ppocr INFO:             ToCHWImage : None
[2024/06/14 02:15:28] ppocr INFO:             KeepKeys :
[2024/06/14 02:15:28] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'entities', 'relations']
[2024/06/14 02:15:28] ppocr INFO:     loader :
[2024/06/14 02:15:28] ppocr INFO:         batch_size_per_card : 8
[2024/06/14 02:15:28] ppocr INFO:         drop_last : False
[2024/06/14 02:15:28] ppocr INFO:         num_workers : 8
[2024/06/14 02:15:28] ppocr INFO:         shuffle : False
[2024/06/14 02:15:28] ppocr INFO: Global :
[2024/06/14 02:15:28] ppocr INFO:     cal_metric_during_train : False
[2024/06/14 02:15:28] ppocr INFO:     distributed : False
[2024/06/14 02:15:28] ppocr INFO:     epoch_num : 100
[2024/06/14 02:15:28] ppocr INFO:     eval_batch_step : [0, 2000]
[2024/06/14 02:15:28] ppocr INFO:     infer_img : None
[2024/06/14 02:15:28] ppocr INFO:     kie_det_model_dir : ./pretrained_models/multilang_PP-OCR_V3_det_rot10_adam_best_model/best_model/model.pdparams
[2024/06/14 02:15:28] ppocr INFO:     kie_rec_model_dir : ./pretrained_models/det_r50_db++_icdar15_train/best_accuracy.pdparams
[2024/06/14 02:15:28] ppocr INFO:     log_smooth_window : 10
[2024/06/14 02:15:28] ppocr INFO:     print_batch_step : 25
[2024/06/14 02:15:28] ppocr INFO:     save_epoch_step : 2000
[2024/06/14 02:15:28] ppocr INFO:     save_inference_dir : None
[2024/06/14 02:15:28] ppocr INFO:     save_model_dir : ./output/re_vi_layoutxlm_xfund_zh
[2024/06/14 02:15:28] ppocr INFO:     save_res_path : ./output/re/xfund_zh/with_gt
[2024/06/14 02:15:28] ppocr INFO:     seed : 2022
[2024/06/14 02:15:28] ppocr INFO:     use_gpu : False
[2024/06/14 02:15:28] ppocr INFO:     use_visualdl : False
[2024/06/14 02:15:28] ppocr INFO: Loss :
[2024/06/14 02:15:28] ppocr INFO:     key : loss
[2024/06/14 02:15:28] ppocr INFO:     name : LossFromOutput
[2024/06/14 02:15:28] ppocr INFO:     reduction : mean
[2024/06/14 02:15:28] ppocr INFO: Metric :
[2024/06/14 02:15:28] ppocr INFO:     main_indicator : hmean
[2024/06/14 02:15:28] ppocr INFO:     name : VQAReTokenMetric
[2024/06/14 02:15:28] ppocr INFO: Optimizer :
[2024/06/14 02:15:28] ppocr INFO:     beta1 : 0.9
[2024/06/14 02:15:28] ppocr INFO:     beta2 : 0.999
[2024/06/14 02:15:28] ppocr INFO:     clip_norm : 10
[2024/06/14 02:15:28] ppocr INFO:     lr :
[2024/06/14 02:15:28] ppocr INFO:         learning_rate : 5e-05
[2024/06/14 02:15:28] ppocr INFO:         warmup_epoch : 10
[2024/06/14 02:15:28] ppocr INFO:     name : AdamW
[2024/06/14 02:15:28] ppocr INFO:     regularizer :
[2024/06/14 02:15:28] ppocr INFO:         factor : 0.0
[2024/06/14 02:15:28] ppocr INFO:         name : L2
[2024/06/14 02:15:28] ppocr INFO: PostProcess :
[2024/06/14 02:15:28] ppocr INFO:     name : VQAReTokenLayoutLMPostProcess
[2024/06/14 02:15:28] ppocr INFO: Train :
[2024/06/14 02:15:28] ppocr INFO:     dataset :
[2024/06/14 02:15:28] ppocr INFO:         data_dir : ./dataset/relation-extraction/img_re_train
[2024/06/14 02:15:28] ppocr INFO:         label_file_list : ['./dataset/relation-extraction/re_train.txt']
[2024/06/14 02:15:28] ppocr INFO:         name : SimpleDataSet
[2024/06/14 02:15:28] ppocr INFO:         ratio_list : [1.0]
[2024/06/14 02:15:28] ppocr INFO:         transforms :
[2024/06/14 02:15:28] ppocr INFO:             DecodeImage :
[2024/06/14 02:15:28] ppocr INFO:                 channel_first : False
[2024/06/14 02:15:28] ppocr INFO:                 img_mode : RGB
[2024/06/14 02:15:28] ppocr INFO:             VQATokenLabelEncode :
[2024/06/14 02:15:28] ppocr INFO:                 algorithm : LayoutXLM
[2024/06/14 02:15:28] ppocr INFO:                 class_path : ./dataset/relation-extraction/class_list.txt
[2024/06/14 02:15:28] ppocr INFO:                 contains_re : True
[2024/06/14 02:15:28] ppocr INFO:                 order_method : tb-yx
[2024/06/14 02:15:28] ppocr INFO:                 use_textline_bbox_info : True
[2024/06/14 02:15:28] ppocr INFO:             VQATokenPad :
[2024/06/14 02:15:28] ppocr INFO:                 max_seq_len : 512
[2024/06/14 02:15:28] ppocr INFO:                 return_attention_mask : True
[2024/06/14 02:15:28] ppocr INFO:             VQAReTokenRelation : None
[2024/06/14 02:15:28] ppocr INFO:             VQAReTokenChunk :
[2024/06/14 02:15:28] ppocr INFO:                 entities_labels :
[2024/06/14 02:15:28] ppocr INFO:                     VACCINE_DATE : 2
[2024/06/14 02:15:28] ppocr INFO:                     VACCINE_NAME : 1
[2024/06/14 02:15:28] ppocr INFO:                 max_seq_len : 512
[2024/06/14 02:15:28] ppocr INFO:             TensorizeEntitiesRelations : None
[2024/06/14 02:15:28] ppocr INFO:             Resize :
[2024/06/14 02:15:28] ppocr INFO:                 size : [224, 224]
[2024/06/14 02:15:28] ppocr INFO:             NormalizeImage :
[2024/06/14 02:15:28] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2024/06/14 02:15:28] ppocr INFO:                 order : hwc
[2024/06/14 02:15:28] ppocr INFO:                 scale : 1
[2024/06/14 02:15:28] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2024/06/14 02:15:28] ppocr INFO:             ToCHWImage : None
[2024/06/14 02:15:28] ppocr INFO:             KeepKeys :
[2024/06/14 02:15:28] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'entities', 'relations']
[2024/06/14 02:15:28] ppocr INFO:     loader :
[2024/06/14 02:15:28] ppocr INFO:         batch_size_per_card : 2
[2024/06/14 02:15:28] ppocr INFO:         drop_last : False
[2024/06/14 02:15:28] ppocr INFO:         num_workers : 4
[2024/06/14 02:15:28] ppocr INFO:         shuffle : True
[2024/06/14 02:15:28] ppocr INFO: profiler_options : None
[2024/06/14 02:15:28] ppocr INFO: train with paddle 2.5.0 and device Place(cpu)
[2024/06/14 02:15:28] ppocr INFO: Initialize indexs of datasets:['./dataset/relation-extraction/re_train.txt']
list index out of range
[2024-06-14 02:15:29,898] [    INFO] - Already cached C:\Users\piade\.paddlenlp\models\layoutxlm-base-uncased\sentencepiece.bpe.model
[2024-06-14 02:15:30,230] [    INFO] - tokenizer config file saved in C:\Users\piade\.paddlenlp\models\layoutxlm-base-uncased\tokenizer_config.json
[2024-06-14 02:15:30,230] [    INFO] - Special tokens file saved in C:\Users\piade\.paddlenlp\models\layoutxlm-base-uncased\special_tokens_map.json
[2024/06/14 02:15:30] ppocr INFO: Initialize indexs of datasets:['dataset/relation-extraction/re_eval.txt']
[2024-06-14 02:15:30,233] [    INFO] - Already cached C:\Users\piade\.paddlenlp\models\layoutxlm-base-uncased\sentencepiece.bpe.model
[2024-06-14 02:15:30,595] [    INFO] - tokenizer config file saved in C:\Users\piade\.paddlenlp\models\layoutxlm-base-uncased\tokenizer_config.json
[2024-06-14 02:15:30,595] [    INFO] - Special tokens file saved in C:\Users\piade\.paddlenlp\models\layoutxlm-base-uncased\special_tokens_map.json
[2024-06-14 02:15:30,607] [    INFO] - Already cached C:\Users\piade\.paddlenlp\models\vi-layoutxlm-base-uncased\model_state.pdparams
[2024-06-14 02:15:40,357] [    INFO] - Weights of LayoutXLMForRelationExtraction not initialized from pretrained model: ['extractor.entity_emb.weight', 'extractor.ffnn_head.0.weigh
t', 'extractor.ffnn_head.0.bias', 'extractor.ffnn_head.3.weight', 'extractor.ffnn_head.3.bias', 'extractor.ffnn_tail.0.weight', 'extractor.ffnn_tail.0.bias', 'extractor.ffnn_tail.3.weight', 'extractor.ffnn_tail.3.bias', 'extractor.rel_classifier.bilinear.weight', 'extractor.rel_classifier.linear.weight', 'extractor.rel_classifier.linear.bias']
[2024/06/14 02:15:42] ppocr INFO: train dataloader has 32 iters
[2024/06/14 02:15:42] ppocr INFO: valid dataloader has 1 iters
[2024/06/14 02:15:42] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Traceback (most recent call last):
  File "tools/train.py", line 229, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "tools/train.py", line 200, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\Users\piade\LUKS\luks_ocr\tools\program.py", line 306, in train
    preds = model(batch)
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\piade\LUKS\luks_ocr\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\piade\LUKS\luks_ocr\ppocr\modeling\backbones\vqa_layoutlm.py", line 220, in forward
    x = self.model(
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1412, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1304, in forward
    relations, entities = self.build_relation(relations, entities)
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1241, in build_relation
    entities[b] = entitie_new
  File "C:\Users\piade\anaconda3\envs\luks_paddleOCR\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 789, in __setitem__
    return self.__setitem_eager_tensor__(item, value)
ValueError: (InvalidArgument) The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]. (at ..\paddle/phi/kernels/impl/set_value_kernel_impl.h:68)
  [operator < set_value > error]

#### 可能解决方案 / Possible solutions
Can anyone help me find the problem and resolve the issue?

**Comment by GreatV** [comment]
This may be a bug.

**Comment by Royhuiy** [comment]
@piarosebelledelapaz Have you resolved this bug？how?

**Comment by piarosebelledelapaz** [comment]
@Royhuiy yes, try checking the annotations in your dataset, if you have images where annotations are less than 3, remove them and the error will be solved
