### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'INTER_LINEAR'

### ISSUE THREAD

**Issue by wanghaisheng** [PaddlePaddle/PaddleOCR#1321]
```
(py3.6) wenke@wenkedeMac-mini PPOCRLabel % python3 PPOCRLabel.py
Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "../tools/infer/predict_system.py", line 21, in <module>
    import tools.infer.utility as utility
  File "../tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "../ppocr/utils/utility.py", line 19, in <module>
    import paddle
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/__init__.py", line 275, in <module>
    import paddle.vision
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/__init__.py", line 18, in <module>
    from . import transforms
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/transforms/__init__.py", line 15, in <module>
    from . import transforms
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/transforms/transforms.py", line 29, in <module>
    from . import functional as F
  File "/opt/anaconda3/envs/py3.6/lib/python3.6/site-packages/paddle/vision/transforms/functional.py", line 84, in <module>
    def resize(img, size, interpolation=cv2.INTER_LINEAR):
AttributeError: module 'cv2' has no attribute 'INTER_LINEAR'
```

macos.  python3.6

pip3 install pyqt5
pip3 uninstall opencv-python # 由于mac版本的opencv与pyqt有冲突，需先手动卸载opencv
pip3 install opencv-contrib-python-headless # 安装headless版本的open-cv
cd ./PPOCRLabel # 将目录切换到PPOCRLabel文件夹下
python3 PPOCRLabel.py

**Comment by MissPenguin** [comment]
把OpenCV卸了重装试试

**Comment by wanghaisheng** [comment]
@MissPenguin 
 pip3 uninstall opencv-python # 由于mac版本的opencv与pyqt有冲突，需先手动卸载opencv
?

**Comment by wanghaisheng** [comment]
···
(py3.8) wenke@wenkedeMac-mini PPOCRLabel % python3 PPOCRLabel.py
PPOCRLabel.py:1096: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if trans_dic["label"] is "" and mode == 'Auto':
PPOCRLabel.py:1898: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if result[0][0] is not '':
PPOCRLabel.py:2090: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert output is 0, "operate the cmd have some problems ,please check  whether there is a in the lib " \
Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "../paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "../tools/infer/predict_system.py", line 26, in <module>
    import tools.infer.predict_det as predict_det
  File "../tools/infer/predict_det.py", line 35, in <module>
    from ppocr.data.det.db_process import DBProcessTest
  File "../ppocr/data/det/db_process.py", line 23, in <module>
    from .data_augment import AugmentData
  File "../ppocr/data/det/data_augment.py", line 13, in <module>
    import imgaug
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/imgaug/__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/imgaug/imgaug.py", line 53, in <module>
    cv2.INTER_NEAREST, cv2.INTER_LINEAR, cv2.INTER_AREA, cv2.INTER_CUBIC]
AttributeError: module 'cv2' has no attribute 'INTER_NEAREST'
···

**Comment by WenmuZhou** [comment]
去paddle提一下这个问题
