### ISSUE TITLE
ModuleNotFoundError: No module named `common` even when common is installed

### ISSUE THREAD

**Issue by QuantumStaticFR** [PaddlePaddle/PaddleOCR#13246]
#### 问题描述 / Problem Description
When I try install paddle using `pip3 install paddle` I run into the error that the module `common` was not found. However, the module `common` is already present in my virtual environment. As expected, I installed `common` using the command `pip3 install common`

#### 运行环境 / Runtime Environment
- OS: Ubuntu 22.04
- Paddle: N/A
- PaddleOCR: N/A
- Python: 3.8/3.9/3.12

#### 复现代码 / Reproduction Code

`pip3 install paddle`

#### 完整报错 / Complete Error Message

```bash
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/home/my/path/myvenv3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/my/path/myvenv3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/my/path/myvenv3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-bmp73yg1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-bmp73yg1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bmp73yg1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-bmp73yg1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-install-hley6e_b/paddle_be621ddd2287409eb9a2e89fd495e3dd/paddle/__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by nextdoorUncleLiu** [comment]
Hello, I have also encountered the same problem. How did you solve it

**Comment by GreatV** [comment]
please refer to: https://www.paddlepaddle.org.cn/install/quick

**Comment by SunlerZRY** [comment]
> Hello, I have also encountered the same problem. How did you solve it

先安装这些缺失的包：pip install common, dual, tight, data, prox
再安装paddle: pip install paddle

**Comment by js179** [comment]
please:  pip install paddlepaddle
