### ISSUE TITLE
表格训练计算TEDS table_char_dict_path取值索引超值

### ISSUE THREAD

**Issue by 77bw** [PaddlePaddle/PaddleOCR#13286]
#### 问题描述 / Problem Description
使用表格计算输出teds指标索引取值报错

#### 复现代码 / Reproduction Code

python table/eval_table.py 
--det_model_dir=D:\PycharmProjects\PaddleOCR\inference\ch_PP-OCRv4_det_server_infer 
--rec_model_dir=D:\PycharmProjects\PaddleOCR\inference\ch_PP-OCRv4_rec_server_infer 
--table_model_dir=D:\PycharmProjects\PaddleOCR\inference\table_batch12_lr0.000064 
--image_dir=D:\PycharmProjects\PaddleOCR\train_data\table_images 
--table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt 
--det_limit_side_len=736 --det_limit_type=min 
--gt_path=D:\PycharmProjects\PaddleOCR\train_data\table_images\convert_label2html.txt

#### 完整报错 / Complete Error Message
Traceback (most recent call last):
  File "D:\PycharmProjects\PaddleOCR\ppstructure\table\eval_table.py", line 112, in <module>
    main(args.gt_path, args.image_dir, args)
  File "D:\PycharmProjects\PaddleOCR\ppstructure\table\eval_table.py", line 92, in main
    structure_res, _ = text_sys._structure(img)
  File "D:\PycharmProjects\PaddleOCR\ppstructure\table\predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "D:\PycharmProjects\PaddleOCR\ppstructure\table\predict_structure.py", line 147, in __call__
    post_result = self.postprocess_op(preds, [shape_list])
  File "D:\PycharmProjects\PaddleOCR\ppocr\postprocess\table_postprocess.py", line 56, in __call__
    result = self.decode(structure_probs, bbox_preds, shape_list)
  File "D:\PycharmProjects\PaddleOCR\ppocr\postprocess\table_postprocess.py", line 85, in decode
    text = self.character[char_idx]
IndexError: list index out of range

#### 可能解决方案 / Possible solutions
尝试过修改其他table_char_dict_path值也还是报一样的错误

#### 附件 / Appendix
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/94338396/67ad901f-e2f4-4582-9455-6e07145be3d0)

**Comment by Topdu** [comment]
../ppocr/utils/dict/table_structure_dict.txt 字典应该用中文的../ppocr/utils/dict/table_structure_dict_ch.txt
