### ISSUE TITLE
OCR模型自动压缩 PPOCRV4_rec 报错

### ISSUE THREAD

**Issue by huangguifeng** [PaddlePaddle/PaddleOCR#13296]
2024-07-08 18:00:06,589-INFO: Selected strategies: ['qat_dis']
Traceback (most recent call last):
  File "run.py", line 171, in <module>
    main()
  File "run.py", line 164, in main
    ac.compress()
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 586, in compress
    self.single_strategy_compress(strategy, config, strategy_idx,
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 769, in single_strategy_compress
    train_program_info, test_program_info = self._prepare_program(
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 506, in _prepare_program
    train_program_info, test_program_info = build_distill_program(
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/auto_compression/create_compressed_program.py", line 327, in build_distill_program
    train_program, data_name_map = _load_program_and_merge(
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/auto_compression/create_compressed_program.py", line 219, in _load_program_and_merge
    merge(
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/dist/single_distiller.py", line 197, in merge
    student_program.global_block().append_op(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4013, in append_op
    op = Operator(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2889, in __init__
    raise ValueError(
ValueError: Incorrect setting for output(s) of operator "dropout", should set: [Mask].

**Comment by huangguifeng** [comment]
det模型 自动压缩 召回率一直为0
2024-07-08 18:17:02,228-INFO: metric eval ***************
2024-07-08 18:17:02,228-INFO: precision:0.0
2024-07-08 18:17:02,228-INFO: recall:0.0
2024-07-08 18:17:02,228-INFO: hmean:0

**Comment by GreatV** [comment]
Hi @huangguifeng, you may need to submit an issue to https://github.com/PaddlePaddle/PaddleSlim/issues.
