### ISSUE TITLE
windows下 python3.6和python3.7 安装paddle_serving_app-0.0.0-py3-none-any.whl一直报错

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/PaddleOCR#1331]
在Collecting shapely<=1.6.1 (from paddle-serving-app==0.0.0)时就会
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MINHOO\AppData\Local\Temp\pip-install-x8u0894j\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\MINHOO\AppData\Local\Temp\pip-install-x8u0894j\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\minhoo\appdata\local\programs\python\python36\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] 找不到指定的模块。

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MINHOO\AppData\Local\Temp\pip-install-x8u0894j\shapely\
下载1.7.1的whl再安装也没用

**Comment by MissPenguin** [comment]
paddle serving现在Windows支持的不好，可以先用hub serving替代
