### ISSUE TITLE
A global iterator flag was passed as a per-operand flag to the iterator constructor

### ISSUE THREAD

**Issue by clSpider** [PaddlePaddle/PaddleOCR#13354]
#### 问题描述 / Problem Description
windows 本地不报错，linux报错
ValueError: A global iterator flag was passed as a per-operand flag to the iterator constructor

#### 运行环境 / Runtime Environment
- OS: linux conda python3.8.19
- Paddle: 2.3.1
- PaddleOCR: 2.7.0.0

#### 复现代码 / Reproduction Code
ocr = PaddleOCR(
    use_angle_cls=True,
    lang="ch",
    use_gpu=False,
    use_mp=True,
    # total_process_num=8,
    page_num= 20
)
result = ocr.ocr('image')

#### 完整报错 / Complete Error Message

Traceback (most recent call last):
  File "OCR_PDF_temp.py", line 98, in run
    result = ocr.ocr(img)
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 645, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/tools/infer/predict_det.py", line 229, in __call__
    data = transform(data, self.preprocess_op)
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/yscredit/anaconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/operators.py", line 93, in __call__
    data['image'] = (
ValueError: A global iterator flag was passed as a per-operand flag to the iterator constructor

**Comment by GreatV** [comment]
try update your paddle and paddleocr version.

**Comment by clSpider** [comment]
> try update your paddle and paddleocr version.

更新到 PaddleOCR: 2.8 还是一样的错

**Comment by GreatV** [comment]
无法复现

```
from paddleocr import PaddleOCR

PAGE_NUM = 0
pdf_path = 'test.pdf'
ocr = PaddleOCR(use_angle_cls=True, lang="ch", page_num=PAGE_NUM, use_gpu=False, use_mp=True)
result = ocr.ocr(pdf_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    if res == None:
        print(f"[DEBUG] Empty page {idx+1} detected, skip it.")
        continue
    for line in res:
        print(line)
```

**Comment by clSpider** [comment]
我重新创建了一个conda的环境 python是3.9 ，只安装了paddlepaddle， paddleocr，不报错了
