### ISSUE TITLE
paddleocr支持动态图训练吗？

### ISSUE THREAD

**Issue by cgq0816** [PaddlePaddle/PaddleOCR#1336]
![image](https://user-images.githubusercontent.com/42534237/101305179-0ae85d80-387d-11eb-925b-330df32e6d52.png)

加载ch_ppocr_server_v1.1_det预训练模型对自己标注的数据进行训练，执行时提示找不到模型参数，如何支持动态图训练呢，有没有好的案例分享呢

**Comment by cgq0816** [comment]
W1207 10:24:12.339685  3855 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 52, Driver API Version: 10.1, Runtime API Version: 10.0
W1207 10:24:12.347663  3855 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-12-07 10:24:13,814-INFO: Loading parameters from /home/jupyter-gqchen/baidu/ocr/ch_ppocr_server_v1.1_det_train/...
2020-12-07 10:24:13,815-WARNING: /home/jupyter-gqchen/baidu/ocr/ch_ppocr_server_v1.1_det_train/.pdparams not found, try toload model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/paddle/fluid/io.py", line 1891, in load_program_state
    filename=file_name)
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/paddle/fluid/io.py", line 805, in load_vars
    executor.run(load_prog)
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/jupyter-gqchen/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:
图裂了，上面是报错信息

**Comment by MissPenguin** [comment]
动态图版本正在紧锣密鼓开发中，预计1-2周后就会正式发布了
