### ISSUE TITLE
执行paddleocr报ImportError

### ISSUE THREAD

**Issue by socay1** [PaddlePaddle/PaddleOCR#13405]
#### 问题描述 / Problem Description
执行 
paddleocr --image_dir ~/hobby/test/1.png --use_angle_cls true --use_gpu false 命令报错，如下：
```log
Error: Can not import paddle core while this file exists: /Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/Users/janu/.local/share/virtualenvs/py3/bin/paddleocr", line 5, in <module>
    from paddleocr.paddleocr import main
  File "/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/__init__.py", line 36, in <module>
    from . import core
  File "/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/core.py", line 380, in <module>
    raise e
  File "/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/core.py", line 268, in <module>
    from . import libpaddle
ImportError: dlopen(/Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/libpaddle.so, 2): Symbol not found: __ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /Users/janu/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/../libs/libcommon.dylib (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
```

#### 运行环境 / Runtime Environment
- OS: mac 11.2.3
- Paddle: 2.6.1
- PaddleOCR:  2.8.0

#### 复现代码 / Reproduction Code
执行 paddleocr -h 也能复现问题

**Comment by GreatV** [comment]
paddle没有安装好

**Comment by mattheliu** [comment]
请根据教程：https://www.paddlepaddle.org.cn/install/quick?docurl=undefined   重新安装paddle尝试

**Comment by socay1** [comment]
@mattheliu 使用链接中的方式安装，仍然有相同的报错信息。如下：
```log
(py3) socay@localhost src %
(py3) socay@localhost src %
(py3) socay@localhost src % python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
64bit
x86_64
(py3) socay@localhost src %
(py3) socay@localhost src % python -V
Python 3.11.5
(py3) socay@localhost src %
(py3) socay@localhost src %
(py3) socay@localhost src % python3 -m pip install paddlepaddle==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/

Looking in indexes: https://www.paddlepaddle.org.cn/packages/stable/cpu/
Collecting paddlepaddle==3.0.0b1
  Using cached https://paddle-whl.bj.bcebos.com/stable/cpu/paddlepaddle/paddlepaddle-3.0.0b1-cp311-cp311-macosx_10_9_x86_64.whl (84.9 MB)
Requirement already satisfied: httpx in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (0.27.0)
Requirement already satisfied: numpy<2.0,>=1.13 in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (1.26.4)
Requirement already satisfied: protobuf>=3.20.2 in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (5.27.2)
Requirement already satisfied: Pillow in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (10.3.0)
Requirement already satisfied: decorator in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (5.1.1)
Requirement already satisfied: astor in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (0.8.1)
Requirement already satisfied: opt-einsum==3.3.0 in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (3.3.0)
Requirement already satisfied: networkx in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (3.3)
Requirement already satisfied: typing-extensions in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from paddlepaddle==3.0.0b1) (4.12.2)
Requirement already satisfied: anyio in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from httpx->paddlepaddle==3.0.0b1) (4.4.0)
Requirement already satisfied: certifi in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from httpx->paddlepaddle==3.0.0b1) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from httpx->paddlepaddle==3.0.0b1) (1.0.5)
Requirement already satisfied: idna in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from httpx->paddlepaddle==3.0.0b1) (2.10)
Requirement already satisfied: sniffio in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from httpx->paddlepaddle==3.0.0b1) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages (from httpcore==1.*->httpx->paddlepaddle==3.0.0b1) (0.14.0)
Installing collected packages: paddlepaddle
Successfully installed paddlepaddle-3.0.0b1

[notice] A new release of pip is available: 24.1.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
(py3) socay@localhost src %
(py3) socay@localhost src %
(py3) socay@localhost src % python
Python 3.11.5 (main, Aug 24 2023, 15:23:14) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/__init__.py", line 33, in <module>
    from .base import core  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/core.py", line 384, in <module>
    raise e
  File "/Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: dlopen(/Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/libpaddle.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Users/socay/.local/share/virtualenvs/py3/lib/python3.11/site-packages/paddle/base/../libs/libcommon.dylib (which was built for Mac OS X 12.3)
  Expected in: /usr/lib/libc++.1.dylib
```

**Comment by SWHL** [comment]
建议用miniconda重新搞一个环境，安装尝试。virtualenv之前总是遇到莫名其妙的问题
