### ISSUE TITLE
Can't use the lang="chinese_cht" 

### ISSUE THREAD

**Issue by B1029038** [PaddlePaddle/PaddleOCR#13454]
#### 问题描述 / Problem Description
如標題所述，無法使用繁體中文chinese_cht進行ocr，使用簡體中文ch是完全沒問題的
It is totally ok to run with lang="ch", but when i change to chinese_cht, this error happend.

#### 运行环境 / Runtime Environment
- OS:windows
- Paddle:同教學
- PaddleOCR:同教學

#### 复现代码 / Reproduction Code
ocr = OCR(use_angle_cls=True, lang="chinese_cht", use_gpu=True)

#### 完整报错 / Complete Error Message
(paddle_env) C:\Users\USER>python -u C:\Users\USER\Desktop\ppocr_img\test2.py
download https://paddleocr.bj.bcebos.com/PP-OCRv3/multilingual/chinese_cht_PP-OCRv3_rec_infer.tar to C:\Users\USER/.paddleocr/whl\rec\chinese_cht\chinese_cht_PP-OCRv3_rec_infer\chinese_cht_PP-OCRv3_rec_infer.tar
[2024/07/22 14:46:40] ppocr INFO: Path C:\Users\USER/.paddleocr/whl\rec\chinese_cht\chinese_cht_PP-OCRv3_rec_infer\chinese_cht_PP-OCRv3_rec_infer.tar already exists. Skipping...
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\ppocr_img\test2.py", line 14, in <module>
    ocr = OCR(use_angle_cls=True, lang="chinese_cht", use_gpu=True)
  File "C:\Users\USER\anaconda3\envs\paddle_env\lib\site-packages\paddleocr\paddleocr.py", line 654, in __init__
    maybe_download(params.rec_model_dir, rec_url)
  File "C:\Users\USER\anaconda3\envs\paddle_env\lib\site-packages\paddleocr\ppocr\utils\network.py", line 58, in maybe_download
    for member in tarObj.getmembers():
  File "C:\Users\USER\anaconda3\envs\paddle_env\lib\tarfile.py", line 1971, in getmembers
    self._load()        # all members, we first have to
  File "C:\Users\USER\anaconda3\envs\paddle_env\lib\tarfile.py", line 2656, in _load
    tarinfo = self.next()
  File "C:\Users\USER\anaconda3\envs\paddle_env\lib\tarfile.py", line 2572, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data

**Comment by GreatV** [comment]
It seems there was a network issue, and the tar file wasn't fully downloaded. Please clear the cache and try again several times.
