### ISSUE TITLE
对线程执行，跑着跑着会报错，但是多进程就不会

### ISSUE THREAD

**Issue by haike-1213** [PaddlePaddle/PaddleOCR#13477]
Traceback (most recent call last):
  File "D:\fm\work\investoday-Chat-Report\tests\gpu_test.py", line 35, in <module>
    main()
  File "D:\fm\work\investoday-Chat-Report\tests\gpu_test.py", line 31, in main
    
  File "D:\fmdata\conda\envs\GPU\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\fmdata\conda\envs\GPU\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fm\work\investoday-Chat-Report\tests\gpu_test.py", line 14, in job
    a = UnstructuredUtil().unstructuredimageloader(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fm\work\investoday-Chat-Report\src\investoday\utils\paddle_ocr\unstructured_util.py", line 37, in unstructuredimageloader
    content = txt.load()
              ^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\langchain_core\document_loaders\base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\langchain_community\document_loaders\unstructured.py", line 88, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\langchain_community\document_loaders\image.py", line 33, in _get_elements
    return partition_image(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\documents\elements.py", line 591, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\file_utils\filetype.py", line 582, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\chunking\dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\partition\image.py", line 103, in partition_image
    return partition_pdf_or_image(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\partition\pdf.py", line 288, in partition_pdf_or_image
    elements = _partition_pdf_or_image_local(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\utils.py", line 245, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\partition\pdf.py", line 580, in _partition_pdf_or_image_local
    final_document_layout = process_file_with_ocr(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\utils.py", line 245, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\partition\pdf_image\ocr.py", line 166, in process_file_with_ocr
    raise e
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\partition\pdf_image\ocr.py", line 132, in process_file_with_ocr
    merged_page_layout = supplement_page_layout_with_ocr(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\utils.py", line 245, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured\partition\pdf_image\ocr.py", line 190, in supplement_page_layout_with_ocr
    ocr_layout = ocr_agent.get_layout_from_image(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fm\work\investoday-Chat-Report\src\investoday\utils\paddle_ocr\paddle_ocr_interface_impl.py", line 80, in get_layout_from_image
    ocr_data = self.agent.ocr(np.array(image), cls=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured_paddleocr\paddleocr.py", line 570, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured_paddleocr\paddle_tools\infer\predict_system.py", line 89, in __call__
    img_crop_list, angle_list, elapse = self.text_classifier(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\fmdata\conda\envs\GPU\Lib\site-packages\unstructured_paddleocr\paddle_tools\infer\predict_cls.py", line 112, in __call__
    
    prob_out = self.output_tensors[0].copy_to_cpu()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at ..\paddle\phi\core\dense_tensor_impl.cc:44)

**Comment by GreatV** [comment]
麻烦提供下可复现的代码
