### ISSUE TITLE
异常： AssertionError: Only one dimension value of 'shape' in reshape can be -1. But received shape[1] is also -1

### ISSUE THREAD

**Issue by shiwenliang** [PaddlePaddle/PaddleOCR#13484]
#### 问题描述 / Problem Description
执行：python tools/export_model.py -c configs/vqa/ser/layoutxlm_sfz.yml -o Architecture.Backbone.checkpoints=./output/ser_layoutxlm_sfz/best_accuracy  Global.save_inference_dir=./inference/ser_layoutxlm_sfz

报错：
AssertionError: Only one dimension value of 'shape' in reshape can be -1. But received shape[1] is also -1

#### 运行环境 / Runtime Environment
- OS: windows
- Paddle: 2.3.2
- PaddleOCR: 2.4.0

#### 完整报错 / Complete Error Message
Traceback (most recent call last):
  File "tools/export_model.py", line 172, in <module>
    main()
  File "tools/export_model.py", line 168, in main
    export_single_model(model, arch_config, save_path, logger)
  File "tools/export_model.py", line 99, in export_single_model
    paddle.jit.save(model, save_path)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\jit.py", line 860, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "D:\tools\anaconda3\envs\xfunddemo\Lib\site-packages\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 79, in forward
        x = self.backbone(x)
    File "D:\tools\anaconda3\envs\xfunddemo\Lib\site-packages\PaddleOCR\ppocr\modeling\backbones\vqa_layoutlm.py", line 121, in forward
        x = self.model(
    File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 873, in forward
        outputs = self.layoutxlm(
    File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 767, in forward
        expand_shape = self.config["image_feature_pool_shape"][0:2]

        visual_bbox = paddle.stack(
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            [
                visual_bbox_x[:-1].expand(expand_shape),

    File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\tensor\manipulation.py", line 2139, in reshape
        return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\layers\nn.py", line 6435, in reshape
        attrs["shape"] = get_attr_shape(shape)
    File "D:\tools\anaconda3\envs\xfunddemo\lib\site-packages\paddle\fluid\layers\nn.py", line 6402, in get_attr_shape
        assert unk_dim_idx == -1, (

    AssertionError: Only one dimension value of 'shape' in reshape can be -1. But received shape[1] is also -1.

        # N = x.shape()[2]              # N is an int. (NOT recommend under @to_static)
        N = paddle.shape(x)[2]          # N is a Tensor. (Recommend)
        z = paddle.reshape([N, -1, 4])  # z.shape is [-1, -1, 4]

    If your target shape in Reshape represents dynamic shape, please turn it into a Tensor under @to_static. See above example for details.

#### 可能解决方案 / Possible solutions


#### 附件 / Appendix

**Comment by shiwenliang** [comment]
请各位大神看一下这个问题
