### ISSUE TITLE
印章文本检测DB++加svtr文字识别，碰到弯曲文本裁剪问题，这个到底要怎么解决，能联合识别吗

### ISSUE THREAD

**Issue by shallow10** [PaddlePaddle/PaddleOCR#13620]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

![Uploading image.png…]()

db++和文字识别都训练好了，就是用不了，弄了两周了看了各种办法都解决不了

### Environment

python3.8
paddle2.7.0
cuda11.8

### Minimal Reproducible Example

这个opencv裁剪到底怎么解决

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by shallow10** [comment]
[2024/08/08 14:52:31] ppocr DEBUG: 瑞安市南氏机械配件有限公司, 0.884
[2024/08/08 14:52:31] ppocr DEBUG: 法定代表人章, 1.000
[2024/08/08 14:52:31] ppocr DEBUG: 4021973548, 0.806
[2024/08/08 14:52:31] ppocr DEBUG: 法定代表人章, 1.000
[2024/08/08 14:52:31] ppocr DEBUG: 4021973548, 0.806
[2024/08/08 14:52:31] ppocr DEBUG: 寨荚丑, 0.999
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 272, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 223, in main
    draw_img = draw_ocr_box_txt(
  File "E:\paddle\PaddleOCR-main\PaddleOCR-release-2.7\tools\infer\utility.py", line 453, in draw_ocr_box_txt
    img_right_text = draw_box_txt_fine((w, h), box, txt, font_path)
  File "E:\paddle\PaddleOCR-main\PaddleOCR-release-2.7\tools\infer\utility.py", line 490, in draw_box_txt_fine
    M = cv2.getPerspectiveTransform(pts1, pts2)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3392: error: (-215:Assertion failed) src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4 in function 'cv::getPerspectiveTransform'

**Comment by UserWangZz** [comment]
你是使用polygon格式还是quad格式的检测框？
polygon格式检测框可以尝试获取到检测框后进行一个矫正
