### ISSUE TITLE
昇腾910B4报错 

### ISSUE THREAD

**Issue by yujunhuics** [PaddlePaddle/PaddleOCR#13647]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

Traceback (most recent call last):
    result = ocr.ocr(img_path, cls=True)
  File "/root/miniconda3/envs/pp/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 729, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
  File "/root/miniconda3/envs/pp/lib/python3.10/site-packages/paddleocr/tools/infer/predict_system.py", line 109, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/root/miniconda3/envs/pp/lib/python3.10/site-packages/paddleocr/tools/infer/predict_det.py", line 396, in __call__
    dt_boxes, elapse = self.predict(img)
  File "/root/miniconda3/envs/pp/lib/python3.10/site-packages/paddleocr/tools/infer/predict_det.py", line 255, in predict
    self.predictor.run()
OSError: (External)  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:443)
  [operator < elementwise_add > error]

### Environment

paddle-custom-npu      3.0.0b1
paddleocr              2.8.1
paddlepaddle           3.0.0b1

芯片：昇腾910B4 arm架构

### Minimal Reproducible Example

如上所述

**Comment by GreatV** [comment]
欢迎提交pr修复这个问题

**Comment by yujunhuics** [comment]
> 欢迎提交pr修复这个问题

您好，请问这个bug有解决方案吗？

**Comment by wangna11BD** [comment]
辛苦发一下你的运行命令，这边复现一下看看

**Comment by yujunhuics** [comment]
> 辛苦发一下你的运行命令，这边复现一下看看

您好，我按照这里的步骤安装了相应的paddlepaddle，https://www.paddlepaddle.org.cn/install/quick?docurl=undefined
paddleocr 2.8.1
这是官方的ocr脚本，我仅将use_npu设置为True
```
from paddleocr import PaddleOCR
import time
import os

ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_npu=True)

s = time.time()

img_path = 'img.png'
result = ocr.ocr(img_path, cls=True)

for idx in range(len(result)):
    res = result[idx]
    # print(res)
    for line in res:
        print(type(line))
        for i in line:
            print(i)

e = time.time()
print('时间：', e - s)
```

**Comment by yujunhuics** [comment]
> 辛苦发一下你的运行命令，这边复现一下看看

到处都有你拿别人的运行脚本

**Comment by wangna11BD** [comment]
img.png也发一下哈

**Comment by yujunhuics** [comment]
```
from paddleocr import PaddleOCR
import time
import os

ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_npu=True)

s = time.time()

img_path = 'img.png'
result = ocr.ocr(img_path, cls=True)

for idx in range(len(result)):
    res = result[idx]
    # print(res)
    for line in res:
        print(type(line))
        for i in line:
            print(i)

e = time.time()
print('时间：', e - s)
```
你可以参考这个，img.png随便截图一张即可

```
Environment
paddle-custom-npu 3.0.0b1
paddleocr 2.8.1
paddlepaddle 3.0.0b1

芯片：昇腾910B4 arm架构
```
这是环境

**Comment by wangna11BD** [comment]
先Python解释器中确认PaddlePaddle安装成功
>>> import paddle
>>> paddle.utils.run_check()

然后在Python解释器中验证一下报错的elementwise_add算子
>>> import paddle
>>> a = paddle.ones([3, 4])
>>> b = paddle.ones([3, 4])
>>> c = a + b

看一下你的CANN包信息 （可能不是下面这个位置，可以找找ascend-toolkit）
ll /usr/local/Ascend/ascend-toolkit

可以把你的镜像也发一下我看看

**Comment by yujunhuics** [comment]
验证paddle时：出现这个，我安装paddlepaddle的步骤来源于这里：https://www.paddlepaddle.org.cn/install/quick?docurl=undefined
```
>>> import paddle
I0815 11:04:53.050539 945380 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle_custom_device
I0815 11:04:53.050628 945380 init.cc:145] Try loading custom device libs from: [/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle_custom_device]
I0815 11:04:53.897814 945380 custom_device.cc:1099] Succeed in loading custom runtime in lib: /root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0815 11:04:53.903594 945380 custom_kernel.cc:63] Succeed in loading 350 custom kernel(s) from loaded lib(s), will be used like native ones.
I0815 11:04:53.903801 945380 init.cc:157] Finished in LoadCustomDevice with libs_path: [/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle_custom_device]
I0815 11:04:53.903853 945380 init.cc:242] CustomDevice: npu, visible devices count: 8
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I0815 11:05:00.339409 945380 program_interpreter.cc:243] New Executor is Running.
I0815 11:05:00.538004 945380 interpreter_util.cc:648] Standalone Executor is Used.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/utils/install_check.py", line 271, in run_check
    _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
  File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/utils/install_check.py", line 151, in _run_static_single
    exe.run(
  File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/base/executor.py", line 1806, in run
    res = self._run_impl(
  File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/base/executor.py", line 2012, in _run_impl
    ret = new_exe.run(
  File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/base/executor.py", line 831, in run
    tensors = self._new_exe.run(
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/utils/install_check.py", line 271, in run_check
      _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/utils/install_check.py", line 135, in _run_static_single
      input, out, weight = _simple_network()
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      out = paddle.tensor.sum(linear_out)
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/tensor/math.py", line 1569, in sum
      helper.append_op(
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/base/layer_helper.py", line 50, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/base/framework.py", line 4612, in append_op
      op = Operator(
    File "/root/miniconda3/envs/ocr/lib/python3.10/site-packages/paddle/base/framework.py", line 3166, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:443)
      [operator < reduce_sum_grad > error]
```

CANN包信息：
```
lrwxrwxrwx 1 root root    9 Jul 23 11:33 8.0 -> ./8.0.T16/
drwxr-xr-x 1 root root 4096 Jul 23 11:37 8.0.T16/
drwxr-xr-x 1 root root 4096 Jul 23 11:37 latest/
-r-xr-xr-x 1 root root  907 Jul 23 11:33 set_env.sh*
```

**Comment by wangna11BD** [comment]
你把2个paddle包卸载了，重新用下面2个包安装试试
https://paddle-whl.bj.bcebos.com/stable/npu/paddle-custom-npu/paddle_custom_npu-3.0.0b1-cp310-cp310-linux_aarch64.whl
https://paddle-whl.bj.bcebos.com/stable/cpu/paddlepaddle/paddlepaddle-3.0.0b1-cp310-cp310-linux_aarch64.whl

**Comment by yujunhuics** [comment]
> paddle.utils.run_check()

报错依旧：
```
    ExternalError:  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:443)
      [operator < reduce_sum_grad > error]
```

**Comment by wangna11BD** [comment]
paddle还是没安装好，先安装paddle_cpu，然后自己编译paddle_custom_npu试试，paddle_custom_npu源代码路径https://github.com/PaddlePaddle/PaddleCustomDevice，编译参考文档https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
