### ISSUE TITLE
表格识别算法-SLANet-LCNetV2 推理报错，怎么解决？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#13641]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

L:
cd L:\paddle\PaddleOCR-2.8.1\ppstructure
python table/predict_structure.py --table_model_dir=L:\paddle\models\ch_ppstructure_openatom_SLANetv2_infer/ --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --image_dir=docs/table/table.jpg --output=../output/table_slanet_lcnetv2 --use_gpu=False --benchmark=True --enable_mkldnn=True --table_max_len=512

[libprotobuf ERROR C:\cache_release\third_party\cuda102\3ad0da47b86006a7bf40b5685bc39f90\protobuf\src\extern_protobuf\src\google\protobuf\message_lite.cc:121] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[40].attrs[13].type, blocks[1].ops[42].attrs[13].type, blocks[1].ops[44].attrs[13].type
[libprotobuf ERROR C:\cache_release\third_party\cuda102\3ad0da47b86006a7bf40b5685bc39f90\protobuf\src\extern_protobuf\src\google\protobuf\message_lite.cc:121] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[40].attrs[13].type, blocks[1].ops[42].attrs[13].type, blocks[1].ops[44].attrs[13].type
Traceback (most recent call last):
  File "table/predict_structure.py", line 207, in <module>
    main(parse_args())
  File "table/predict_structure.py", line 171, in main
    table_structurer = TableStructurer(args)
  File "table/predict_structure.py", line 97, in __init__
    ) = utility.create_predictor(args, "table", logger)
  File "L:\paddle\PaddleOCR-2.8.1\tools\infer\utility.py", line 304, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at ..\paddle\fluid\framework\program_desc.cc:103)

### Environment

win10

### Minimal Reproducible Example

[libprotobuf ERROR C:\cache_release\third_party\cuda102\3ad0da47b86006a7bf40b5685bc39f90\protobuf\src\extern_protobuf\src\google\protobuf\message_lite.cc:121] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[40].attrs[13].type, blocks[1].ops[42].attrs[13].type, blocks[1].ops[44].attrs[13].type
[libprotobuf ERROR C:\cache_release\third_party\cuda102\3ad0da47b86006a7bf40b5685bc39f90\protobuf\src\extern_protobuf\src\google\protobuf\message_lite.cc:121] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[40].attrs[13].type, blocks[1].ops[42].attrs[13].type, blocks[1].ops[44].attrs[13].type
Traceback (most recent call last):
  File "table/predict_structure.py", line 207, in <module>
    main(parse_args())
  File "table/predict_structure.py", line 171, in main
    table_structurer = TableStructurer(args)
  File "table/predict_structure.py", line 97, in __init__
    ) = utility.create_predictor(args, "table", logger)
  File "L:\paddle\PaddleOCR-2.8.1\tools\infer\utility.py", line 304, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at ..\paddle\fluid\framework\program_desc.cc:103)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by b4bbuilder** [comment]
I resolved this with `rm -rf ~/.paddleocr`. I think I aborted the code run initially causing the models to only partially install.

**Comment by liu-jiaxuan** [comment]
可以试下上面的方法是否可行，看看是不是模型损坏了
