### ISSUE TITLE
structure_layout报错

### ISSUE THREAD

**Issue by zhang19523zhao** [PaddlePaddle/PaddleOCR#13667]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

deploy/hubserving/structure_layout/module.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "deploy/hubserving/structure_layout/module.py", line 142, in <module>
    res = layout.predict(paths=image_path)
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "deploy/hubserving/structure_layout/module.py", line 119, in predict
    res, _ = self.layout_predictor(img)
  File "./ppstructure/layout/predict_layout.py", line 112, in __call__
    post_preds = self.postprocess_op(ori_im, img, preds)
  File "./ppocr/postprocess/picodet_postprocess.py", line 268, in __call__
    label = self.labels[clsid]
IndexError: list index out of range

### Environment

![image](https://github.com/user-attachments/assets/bab1ef47-e468-4158-97ed-d3ff9763816e)
python3 deploy/hubserving/structure_layout/module.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "deploy/hubserving/structure_layout/module.py", line 142, in <module>
    res = layout.predict(paths=image_path)
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "deploy/hubserving/structure_layout/module.py", line 119, in predict
    res, _ = self.layout_predictor(img)
  File "./ppstructure/layout/predict_layout.py", line 112, in __call__
    post_preds = self.postprocess_op(ori_im, img, preds)
  File "./ppocr/postprocess/picodet_postprocess.py", line 268, in __call__
    label = self.labels[clsid]
IndexError: list index out of range

### Minimal Reproducible Example

python3 deploy/hubserving/structure_layout/module.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "deploy/hubserving/structure_layout/module.py", line 142, in <module>
    res = layout.predict(paths=image_path)
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "deploy/hubserving/structure_layout/module.py", line 119, in predict
    res, _ = self.layout_predictor(img)
  File "./ppstructure/layout/predict_layout.py", line 112, in __call__
    post_preds = self.postprocess_op(ori_im, img, preds)
  File "./ppocr/postprocess/picodet_postprocess.py", line 268, in __call__
    label = self.labels[clsid]
IndexError: list index out of range

### Additional

python3 deploy/hubserving/structure_layout/module.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "deploy/hubserving/structure_layout/module.py", line 142, in <module>
    res = layout.predict(paths=image_path)
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "deploy/hubserving/structure_layout/module.py", line 119, in predict
    res, _ = self.layout_predictor(img)
  File "./ppstructure/layout/predict_layout.py", line 112, in __call__
    post_preds = self.postprocess_op(ori_im, img, preds)
  File "./ppocr/postprocess/picodet_postprocess.py", line 268, in __call__
    label = self.labels[clsid]
IndexError: list index out of range

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by GreatV** [comment]
可以先试试命令行看看可以不 https://paddlepaddle.github.io/PaddleOCR/ppstructure/quick_start.html#11-paddlepaddle
