### ISSUE TITLE
用quick start推理实现检测和识别 InvalidArgumentError: Broadcast dimension mismatch

### ISSUE THREAD

**Issue by changeyourdestiny** [PaddlePaddle/PaddleOCR#13728]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

https://paddlepaddle.github.io/PaddleOCR/ppocr/quick_start.html#212 我看这个快速教程里，通过Python脚本使用PaddleOCR whl包，whl包会自动下载ppocr轻量级模型作为默认模型。教程代码如下

`from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'

result = ocr.ocr(img_path, cls=True)

`
 
试了下教程的代码是可以运行的。但我将它运行时下载的ppocr轻量级模型inference.pdiparams，inference.pdiparams.info，inference.pdmodel拷贝到脚本当前目录的pdModel文件夹里，再作为模型载入，就报错了，检测图片没有改动。(use_angle_cls设为False也试过了，也是报错) 会报错的代码如下:

`model_dir = 'pdModel/'

ocr = PaddleOCR(
    det_model_dir=model_dir,
    cls_model_dir=model_dir,
    rec_model_dir=model_dir,
    use_angle_cls=True
    ) `

报错信息：
Traceback (most recent call last):
  File "F:\work\test\ppOcrTest.py", line 14, in <module>
    result = ocr.ocr(img_path, cls=True)
  File "F:\anaconda\envs\adbPy39\lib\site-packages\paddleocr\paddleocr.py", line 729, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
  File "F:\anaconda\envs\adbPy39\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 134, in __call__
    img_crop_list, angle_list, elapse = self.text_classifier(img_crop_list)
  File "F:\anaconda\envs\adbPy39\lib\site-packages\paddleocr\tools\infer\predict_cls.py", line 114, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [6, 96, 3, 12] and the shape of Y = [6, 96, 4, 12]. Received [3] in X is not equal to [4] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:86)
  [operator < elementwise_add > error]  

### 🏃‍♂️ Environment (运行环境)

paddleocr             2.8.1
paddlepaddle          2.6.1             
paddleslim            2.6.0         
Python 3.9.19
torch                 2.3.1+cu118
torchvision           0.18.1+cu118  

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation             
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89         
Build cuda_11.8.r11.8/compiler.31833905_0  

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

model_dir = 'pdModel/'
ocr = PaddleOCR(
    det_model_dir=model_dir,
    cls_model_dir=model_dir,
    rec_model_dir=model_dir,
    use_angle_cls=True
    )

**Comment by changeyourdestiny** [comment]
我搜索这个问题搜了挺久，没有得到答案。图片的尺寸也试过高宽都改为32的倍数，也没有用

**Comment by GreatV** [comment]
无法复现

```shell
cp -rf ~/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ .

cp -rf ~/.paddleocr/whl/rec/ch/ch_PP-OCRv4_rec_infer/ .

cp -rf ~/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ .
```
```python
from paddleocr import PaddleOCR

det_model_dir = "./ch_PP-OCRv4_det_infer"
rec_model_dir = "./ch_PP-OCRv4_rec_infer"
cls_model_dir = "./ch_ppocr_mobile_v2.0_cls_infer"


ocr = PaddleOCR(
det_model_dir=det_model_dir,
rec_model_dir=rec_model_dir,
cls_model_dir=cls_model_dir,
use_angle_cls=True
)

test_image_path = "docs/images/en_1.png"
result = ocr.ocr(test_image_path, cls=True)
```

```text
[2024/08/23 02:59:29] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, use_npu=False, use_mlu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='./ch_PP-OCRv4_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='./ch_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/home/greatx/repos/PaddleOCR/ppocr/utils/ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='./ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ch', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2024/08/23 02:59:29] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/08/23 02:59:29] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/08/23 02:59:29] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/08/23 02:59:30] ppocr DEBUG: dt_boxes num : 37, elapsed : 0.17484712600708008
[2024/08/23 02:59:30] ppocr DEBUG: cls num  : 37, elapsed : 0.04606747627258301
[2024/08/23 02:59:30] ppocr DEBUG: rec_res num  : 37, elapsed : 0.06449365615844727
```

**Comment by changeyourdestiny** [comment]
感谢，是我的错，我把rec_model_dir和cls_model_dir都指向了det_model_dir
