### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.infer'

### ISSUE THREAD

**Issue by ZhengHui-Z** [PaddlePaddle/PaddleOCR#13769]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

> 弱弱吐槽一下，百度程序员代码规范可真随意，包的导入方式很粗鲁

```
Traceback (most recent call last):
  File "/root/anaconda3/bin/paddleocr", line 5, in <module>
    from paddleocr.paddleocr import main
  File "/root/anaconda3/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/root/anaconda3/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'
```

明显是和python的tools库直接冲突了，我看也有比较多人吐槽了，可是一直没有修改

### 🏃‍♂️ Environment (运行环境)

any

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

paddleocr --image_dir ./imgs_en/254.jpg --lang=en

**Comment by ZhengHui-Z** [comment]
> 这个问题已经在这个main分支修复，还没有release，tools确实是个容易冲突。这个项目目前是社区在维护，力量有限，忘了同步到release。

辛苦大佬们处理一下，这个问题确实影响面比较广，反馈的人也比较多，另外一个社区PR应该需要一些规范，避免不规范的代码被合并进来。
