### ISSUE TITLE
训练时报错 IndexError: list index out of range

### ISSUE THREAD

**Issue by HHaidai** [PaddlePaddle/PaddleOCR#13826]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

IndexError: list index out of range训练时部分数据会报错，图片和框的坐标都没有问题，模型能正常训练完，但是中间有大量此类报错。
 error happened with msg: Traceback (most recent call last):
  File "/app/PaddleOCR/ppocr/data/simple_dataset.py", line 162, in __getitem__
    outs = transform(data, self.ops)
  File "/app/PaddleOCR/ppocr/data/imaug/__init__.py", line 71, in transform
    data = op(data)
  File "/app/PaddleOCR/ppocr/data/imaug/make_border_map.py", line 59, in __call__
    self.draw_border_map(text_polys[i], canvas, mask=mask)
  File "/app/PaddleOCR/ppocr/data/imaug/make_border_map.py", line 83, in draw_border_map
    padded_polygon = np.array(padding.Execute(distance)[0])
IndexError: list index out of range

### 🏃‍♂️ Environment (运行环境)

python3.7  paddle2.7 使用cuda在2台gpu上训练

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

的报错
2024/09/05 08:37:24] ppocr INFO: epoch: [1/1200], global_step: 10, lr: 0.001000, loss: 7.093800, loss_shrink_maps: 4.369740, loss_threshold_maps: 1.881960, loss_binary_maps: 0.877478, loss_cbn: 0.000000, avg_reader_cost: 1.17849 s, avg_batch_cost: 3.84260 s, avg_samples: 16.0, ips: 4.16385 samples/s, eta: 8 days, 14:12:31, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:37:35] ppocr INFO: epoch: [1/1200], global_step: 20, lr: 0.001000, loss: 6.126780, loss_shrink_maps: 4.116320, loss_threshold_maps: 1.177882, loss_binary_maps: 0.825142, loss_cbn: 0.000000, avg_reader_cost: 0.01832 s, avg_batch_cost: 0.77432 s, avg_samples: 16.0, ips: 20.66333 samples/s, eta: 5 days, 3:52:28, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:37:45] ppocr INFO: epoch: [1/1200], global_step: 30, lr: 0.001000, loss: 5.479256, loss_shrink_maps: 3.781492, loss_threshold_maps: 0.956095, loss_binary_maps: 0.754782, loss_cbn: 0.000000, avg_reader_cost: 0.03214 s, avg_batch_cost: 0.81754 s, avg_samples: 16.0, ips: 19.57082 samples/s, eta: 4 days, 1:12:04, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:37:56] ppocr INFO: epoch: [1/1200], global_step: 40, lr: 0.001000, loss: 4.838632, loss_shrink_maps: 3.287195, loss_threshold_maps: 0.902247, loss_binary_maps: 0.629435, loss_cbn: 0.000000, avg_reader_cost: 0.11379 s, avg_batch_cost: 0.82289 s, avg_samples: 16.0, ips: 19.44368 samples/s, eta: 3 days, 11:56:07, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:38:07] ppocr INFO: epoch: [1/1200], global_step: 50, lr: 0.001000, loss: 4.191125, loss_shrink_maps: 2.880770, loss_threshold_maps: 0.841938, loss_binary_maps: 0.470247, loss_cbn: 0.000000, avg_reader_cost: 0.03645 s, avg_batch_cost: 0.82181 s, avg_samples: 16.0, ips: 19.46918 samples/s, eta: 3 days, 3:57:48, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:38:17] ppocr INFO: epoch: [1/1200], global_step: 60, lr: 0.001000, loss: 3.689357, loss_shrink_maps: 2.506985, loss_threshold_maps: 0.816842, loss_binary_maps: 0.372827, loss_cbn: 0.000000, avg_reader_cost: 0.08888 s, avg_batch_cost: 0.83989 s, avg_samples: 16.0, ips: 19.05005 samples/s, eta: 2 days, 22:48:34, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:38:27] ppocr INFO: epoch: [1/1200], global_step: 70, lr: 0.001000, loss: 3.306236, loss_shrink_maps: 2.180038, loss_threshold_maps: 0.784642, loss_binary_maps: 0.329583, loss_cbn: 0.000000, avg_reader_cost: 0.09959 s, avg_batch_cost: 0.88551 s, avg_samples: 16.0, ips: 18.06874 samples/s, eta: 2 days, 19:28:37, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:38:38] ppocr INFO: epoch: [1/1200], global_step: 80, lr: 0.001000, loss: 2.993502, loss_shrink_maps: 1.925983, loss_threshold_maps: 0.762090, loss_binary_maps: 0.296068, loss_cbn: 0.000000, avg_reader_cost: 0.09365 s, avg_batch_cost: 0.85095 s, avg_samples: 16.0, ips: 18.80252 samples/s, eta: 2 days, 16:44:44, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:38:45] ppocr ERROR: When parsing line train_images/322.jpg       [{"transcription": "default", "points": [[987, 1172], [1037, 1172], [1037, 1224], [987, 1224]]}, {"transcription": "default", "points": [[213, 1808], [272, 1808], [272, 1868], [213, 1868]]}, {"transcription": "default", "points": [[518, 1816], [568, 1816], [568, 1866], [518, 1866]]}, {"transcription": "default", "points": [[518, 1818], [568, 1818], [568, 1866], [518, 1866]]}, {"transcription": "default", "points": [[1011, 692], [1013, 692], [1013, 758], [1011, 758]]}, {"transcription": "default", "points": [[101, 1709], [146, 1709], [146, 1747], [101, 1747]]}, {"transcription": "default", "points": [[216, 1651], [279, 1651], [279, 1699], [216, 1699]]}, {"transcription": "default", "points": [[449, 1332], [503, 1332], [503, 1373], [449, 1373]]}, {"transcription": "default", "points": [[244, 801], [332, 801], [332, 852], [244, 852]]}, {"transcription": "default", "points": [[837, 806], [913, 806], [913, 849], [837, 849]]}, {"transcription": "default", "points": [[365, 260], [422, 260], [422, 292], [365, 292]]}, {"transcription": "default", "points": [[549, 1503], [643, 1503], [643, 1553], [549, 1553]]}, {"transcription": "default", "points": [[28, 1306], [138, 1306], [138, 1354], [28, 1354]]}, {"transcription": "default", "points": [[549, 40], [668, 40], [668, 90], [549, 90]]}, {"transcription": "default", "points": [[423, 1007], [504, 1007], [504, 1041], [423, 1041]]}, {"transcription": "default", "points": [[545, 370], [667, 370], [667, 418], [545, 418]]}, {"transcription": "default", "points": [[949, 808], [1054, 808], [1054, 849], [949, 849]]}, {"transcription": "default", "points": [[362, 511], [429, 511], [429, 536], [362, 536]]}, {"transcription": "default", "points": [[347, 292], [433, 292], [433, 324], [347, 324]]}, {"transcription": "default", "points": [[553, 701], [666, 701], [666, 742], [553, 742]]}, {"transcription": "default", "points": [[550, 1345], [665, 1345], [665, 1386], [550, 1386]]}, {"transcription": "default", "points": [[30, 710], [170, 710], [170, 762], [30, 762]]}, {"transcription": "default", "points": [[553, 957], [695, 957], [695, 1005], [553, 1005]]}, {"transcription": "default", "points": [[30, 3], [174, 3], [174, 51], [30, 51]]}, {"transcription": "default", "points": [[30, 1073], [172, 1073], [172, 1119], [30, 1119]]}, {"transcription": "default", "points": [[28, 596], [172, 596], [172, 642], [28, 642]]}, {"transcription": "default", "points": [[30, 955], [172, 955], [172, 1000], [30, 1000]]}, {"transcription": "default", "points": [[30, 836], [172, 836], [172, 881], [30, 881]]}, {"transcription": "default", "points": [[553, 1062], [684, 1062], [684, 1103], [553, 1103]]}, {"transcription": "default", "points": [[801, 1670], [978, 1670], [978, 1725], [801, 1725]]}, {"transcription": "default", "points": [[317, 294], [434, 294], [434, 322], [317, 322]]}, {"transcription": "default", "points": [[288, 1329], [400, 1329], [400, 1361], [288, 1361]]}, {"transcription": "default", "points": [[32, 1194], [170, 1194], [170, 1233], [32, 1233]]}, {"transcription": "default", "points": [[32, 1432], [170, 1432], [170, 1471], [32, 1471]]}, {"transcription": "default", "points": [[288, 1350], [400, 1350], [400, 1380], [288, 1380]]}, {"transcription": "default", "points": [[285, 1373], [414, 1373], [414, 1405], [285, 1405]]}, {"transcription": "default", "points": [[549, 1176], [756, 1176], [756, 1222], [549, 1222]]}, {"transcription": "default", "points": [[276, 1009], [414, 1009], [414, 1039], [276, 1039]]}, {"transcription": "default", "points": [[273, 1478], [494, 1478], [494, 1544], [273, 1544]]}, {"transcription": "default", "points": [[558, 1441], [744, 1441], [744, 1480], [558, 1480]]}, {"transcription": "default", "points": [[217, 1711], [442, 1711], [442, 1750], [217, 1750]]}, {"transcription": "default", "points": [[550, 148], [840, 148], [840, 200], [550, 200]]}, {"transcription": "default", "points": [[553, 1009], [859, 1009], [859, 1055], [553, 1055]]}, {"transcription": "default", "points": [[553, 1110], [861, 1110], [861, 1156], [553, 1156]]}, {"transcription": "default", "points": [[553, 902], [938, 902], [938, 948], [553, 948]]}, {"transcription": "default", "points": [[550, 470], [1036, 470], [1036, 532], [550, 532]]}, {"transcription": "default", "points": [[550, 1281], [993, 1281], [993, 1333], [550, 1333]]}, {"transcription": "default", "points": [[206, 1567], [873, 1567], [873, 1603], [206, 1603]]}]
, error happened with msg: Traceback (most recent call last):
  File "/app/PaddleOCR/ppocr/data/simple_dataset.py", line 162, in __getitem__
    outs = transform(data, self.ops)
  File "/app/PaddleOCR/ppocr/data/imaug/__init__.py", line 71, in transform
    data = op(data)
  File "/app/PaddleOCR/ppocr/data/imaug/make_border_map.py", line 59, in __call__
    self.draw_border_map(text_polys[i], canvas, mask=mask)
  File "/app/PaddleOCR/ppocr/data/imaug/make_border_map.py", line 83, in draw_border_map
    padded_polygon = np.array(padding.Execute(distance)[0])
IndexError: list index out of range

[2024/09/05 08:38:47] ppocr INFO: epoch: [1/1200], global_step: 90, lr: 0.001000, loss: 2.830525, loss_shrink_maps: 1.780520, loss_threshold_maps: 0.757842, loss_binary_maps: 0.282294, loss_cbn: 0.000000, avg_reader_cost: 0.00373 s, avg_batch_cost: 0.85116 s, avg_samples: 16.0, ips: 18.79787 samples/s, eta: 2 days, 14:37:18, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB
[2024/09/05 08:38:58] ppocr INFO: epoch: [1/1200], global_step: 100, lr: 0.001000, loss: 2.761092, loss_shrink_maps: 1.711642, loss_threshold_maps: 0.757842, loss_binary_maps: 0.283466, loss_cbn: 0.000000, avg_reader_cost: 0.09590 s, avg_batch_cost: 0.75386 s, avg_samples: 16.0, ips: 21.22401 samples/s, eta: 2 days, 12:24:00, max_mem_reserved: 7410 MB, max_mem_allocated: 7034 MB

**Comment by savio1999** [comment]
1 - i am facing the same issue and tried experimenting with shrink_ratio, epoch_num but still the issue exists
2 - but the training continues will there be any accuracy issue?

**Comment by GreatV** [comment]
可以试试我们的main branch，看看会不会出现这个问题。

**Comment by HHaidai** [comment]
具体的报错是PaddleOCR/ppocr/data/imaug/make_border_map.py 下的padded_polygon = np.array(padding.Execute(distance)[0])，通过打印发现是distance太小导致padding.Execute(distance)返回一个空数组然后引发的报错，正常的distance一般都大于1，引发报错时的distance都是0.1 0.2这种。我目前的措施是判断len(padding.Execute(distance))==0就return，目前是没有报错了，但是不知道对模型会不会有什么影响。
