### ISSUE TITLE
2.9.1 win10 python3.1.2 报错

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#14092]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

L:\paddle\PaddleOCR-2.9.1>cd L:\paddle\PaddleOCR-2.9.1

L:\paddle\PaddleOCR-2.9.1>python312 tools/infer/predict_rec.py --image_dir='F:\0ppt' --rec_model_dir='L:\paddle\models\openatom_rec_svtrv2_ch_infer/'
Traceback (most recent call last):
  File "L:\paddle\PaddleOCR-2.9.1\tools\infer\predict_rec.py", line 29, in <module>
    import paddle
  File "L:\python312\Lib\site-packages\paddle\__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "L:\python312\Lib\site-packages\paddle\base\__init__.py", line 39, in <module>
    from . import framework
  File "L:\python312\Lib\site-packages\paddle\base\framework.py", line 40, in <module>
    from .proto import (
  File "L:\python312\Lib\site-packages\paddle\base\proto\data_feed_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "L:\python312\Lib\site-packages\google\protobuf\descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

### 🏃‍♂️ Environment (运行环境)

win10 

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

L:\paddle\PaddleOCR-2.9.1>cd L:\paddle\PaddleOCR-2.9.1

L:\paddle\PaddleOCR-2.9.1>python312 tools/infer/predict_rec.py --image_dir='F:\0ppt' --rec_model_dir='L:\paddle\models\openatom_rec_svtrv2_ch_infer/'
Traceback (most recent call last):
  File "L:\paddle\PaddleOCR-2.9.1\tools\infer\predict_rec.py", line 29, in <module>
    import paddle
  File "L:\python312\Lib\site-packages\paddle\__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "L:\python312\Lib\site-packages\paddle\base\__init__.py", line 39, in <module>
    from . import framework
  File "L:\python312\Lib\site-packages\paddle\base\framework.py", line 40, in <module>
    from .proto import (
  File "L:\python312\Lib\site-packages\paddle\base\proto\data_feed_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "L:\python312\Lib\site-packages\google\protobuf\descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by GreatV** [comment]
报错写得清清楚楚，按照日志处理吧

**Comment by nissansz** [comment]
pip312 install --upgrade protobuf==3.20.0 可以解决报错。

但是
python312 tools/infer/predict_rec.py --image_dir='F:\0ppt' --rec_model_dir='L:\paddle\models\openatom_rec_svtrv2_ch_infer/'

提示找不到图片
  File "L:\paddle\PaddleOCR-2.9.1\ppocr\utils\utility.py", line 80, in get_image_file_list
    raise Exception("not found any img file in {}".format(img_file))
Exception: not found any img file in 'F:\0ppt'
