### ISSUE TITLE
[Infererence] AttributeError: ‘ParallelEnv‘ object has no attribute

### ISSUE THREAD

**Issue by Cupcc** [PaddlePaddle/PaddleOCR#14124]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

show the error when running the inference program.
```bash
> python3 tools/infer_rec.py -c pretrain_models/v3_digital_mobile/config.yml -o Global.pretrained_model=pretrain_models/v3_digital_mobile/best_accuracy  Global.infer_img="ppocr_img/rec_test_img.png"

Traceback (most recent call last):
  File "/to/PaddleOCR/tools/infer_rec.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/to/PaddleOCR/tools/program.py", line 857, in preprocess
    device = "gpu:{}".format(dist.ParallelEnv().dev_id) if use_gpu else "cpu"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/to//miniconda3/envs/paddle_ocr/lib/python3.11/site-packages/paddle/distributed/parallel.py", line 783, in device_id
    return self._device_id
           ^^^^^^^^^^^^^^^
AttributeError: 'ParallelEnv' object has no attribute '_device_id'. Did you mean: 'device_id'?
```
I've run this test and passed successfully.
```bash
python3
Python 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I1030 13:53:45.171574 50727 program_interpreter.cc:243] New Executor is Running.
I1030 13:53:45.179387 50727 interpreter_util.cc:648] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

### 🏃‍♂️ Environment (运行环境)

```bash
os: ubuntu 22.04 LTS
python: 3.11.10
# pip list
paddleocr                2.9.1
paddlepaddle             3.0.0b1
paddlepaddle-gpu         3.0.0b1
nvidia-cublas-cu12       12.3.4.1
nvidia-cuda-cupti-cu12   12.3.101
nvidia-cuda-nvrtc-cu12   12.3.107
nvidia-cuda-runtime-cu12 12.3.101
nvidia-cudnn-cu12        9.0.0.312
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.5.40
nvidia-nvtx-cu12         12.4.127
nvidia-pyindex           1.0.9

```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

```bash
 python3 tools/infer_rec.py -c pretrain_models/v3_digital_mobile/config.yml -o Global.pretrained_model=pretrain_models/v3_digital_mobile/best_accuracy  Global.infer_img="ppocr_img/rec_test_img.png"
 ```

**Comment by Cupcc** [comment]
I try to infer a image on cpu and it works.
but the detection result is wrong.

**Comment by GreatV** [comment]
Can't reproduce
```shell
python3 tools/infer_rec.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=pretrained_models/ch_PP-OCRv3_rec_train/best_accuracy  Global.infer_img=doc/imgs_words/en/word_1.png
```

```text
[2024/10/30 14:39:02] ppocr INFO: Architecture : 
[2024/10/30 14:39:02] ppocr INFO:     Models : 
[2024/10/30 14:39:02] ppocr INFO:         Student : 
[2024/10/30 14:39:02] ppocr INFO:             Backbone : 
[2024/10/30 14:39:02] ppocr INFO:                 last_conv_stride : [1, 2]
[2024/10/30 14:39:02] ppocr INFO:                 last_pool_kernel_size : [2, 2]
[2024/10/30 14:39:02] ppocr INFO:                 last_pool_type : avg
[2024/10/30 14:39:02] ppocr INFO:                 name : MobileNetV1Enhance
[2024/10/30 14:39:02] ppocr INFO:                 scale : 0.5
[2024/10/30 14:39:02] ppocr INFO:             Head : 
[2024/10/30 14:39:02] ppocr INFO:                 head_list : 
[2024/10/30 14:39:02] ppocr INFO:                     CTCHead : 
[2024/10/30 14:39:02] ppocr INFO:                         Head : 
[2024/10/30 14:39:02] ppocr INFO:                             fc_decay : 1e-05
[2024/10/30 14:39:02] ppocr INFO:                         Neck : 
[2024/10/30 14:39:02] ppocr INFO:                             depth : 2
[2024/10/30 14:39:02] ppocr INFO:                             dims : 64
[2024/10/30 14:39:02] ppocr INFO:                             hidden_dims : 120
[2024/10/30 14:39:02] ppocr INFO:                             name : svtr
[2024/10/30 14:39:02] ppocr INFO:                             use_guide : True
[2024/10/30 14:39:02] ppocr INFO:                     SARHead : 
[2024/10/30 14:39:02] ppocr INFO:                         enc_dim : 512
[2024/10/30 14:39:02] ppocr INFO:                         max_text_length : 25
[2024/10/30 14:39:02] ppocr INFO:                 name : MultiHead
[2024/10/30 14:39:02] ppocr INFO:             Transform : None
[2024/10/30 14:39:02] ppocr INFO:             algorithm : SVTR_LCNet
[2024/10/30 14:39:02] ppocr INFO:             freeze_params : False
[2024/10/30 14:39:02] ppocr INFO:             model_type : rec
[2024/10/30 14:39:02] ppocr INFO:             pretrained : None
[2024/10/30 14:39:02] ppocr INFO:             return_all_feats : True
[2024/10/30 14:39:02] ppocr INFO:         Teacher : 
[2024/10/30 14:39:02] ppocr INFO:             Backbone : 
[2024/10/30 14:39:02] ppocr INFO:                 last_conv_stride : [1, 2]
[2024/10/30 14:39:02] ppocr INFO:                 last_pool_kernel_size : [2, 2]
[2024/10/30 14:39:02] ppocr INFO:                 last_pool_type : avg
[2024/10/30 14:39:02] ppocr INFO:                 name : MobileNetV1Enhance
[2024/10/30 14:39:02] ppocr INFO:                 scale : 0.5
[2024/10/30 14:39:02] ppocr INFO:             Head : 
[2024/10/30 14:39:02] ppocr INFO:                 head_list : 
[2024/10/30 14:39:02] ppocr INFO:                     CTCHead : 
[2024/10/30 14:39:02] ppocr INFO:                         Head : 
[2024/10/30 14:39:02] ppocr INFO:                             fc_decay : 1e-05
[2024/10/30 14:39:02] ppocr INFO:                         Neck : 
[2024/10/30 14:39:02] ppocr INFO:                             depth : 2
[2024/10/30 14:39:02] ppocr INFO:                             dims : 64
[2024/10/30 14:39:02] ppocr INFO:                             hidden_dims : 120
[2024/10/30 14:39:02] ppocr INFO:                             name : svtr
[2024/10/30 14:39:02] ppocr INFO:                             use_guide : True
[2024/10/30 14:39:02] ppocr INFO:                     SARHead : 
[2024/10/30 14:39:02] ppocr INFO:                         enc_dim : 512
[2024/10/30 14:39:02] ppocr INFO:                         max_text_length : 25
[2024/10/30 14:39:02] ppocr INFO:                 name : MultiHead
[2024/10/30 14:39:02] ppocr INFO:             Transform : None
[2024/10/30 14:39:02] ppocr INFO:             algorithm : SVTR_LCNet
[2024/10/30 14:39:02] ppocr INFO:             freeze_params : False
[2024/10/30 14:39:02] ppocr INFO:             model_type : rec
[2024/10/30 14:39:02] ppocr INFO:             pretrained : None
[2024/10/30 14:39:02] ppocr INFO:             return_all_feats : True
[2024/10/30 14:39:02] ppocr INFO:     algorithm : Distillation
[2024/10/30 14:39:02] ppocr INFO:     model_type : rec
[2024/10/30 14:39:02] ppocr INFO:     name : DistillationModel
[2024/10/30 14:39:02] ppocr INFO: Eval : 
[2024/10/30 14:39:02] ppocr INFO:     dataset : 
[2024/10/30 14:39:02] ppocr INFO:         data_dir : ./train_data
[2024/10/30 14:39:02] ppocr INFO:         label_file_list : ['./train_data/val_list.txt']
[2024/10/30 14:39:02] ppocr INFO:         name : SimpleDataSet
[2024/10/30 14:39:02] ppocr INFO:         transforms : 
[2024/10/30 14:39:02] ppocr INFO:             DecodeImage : 
[2024/10/30 14:39:02] ppocr INFO:                 channel_first : False
[2024/10/30 14:39:02] ppocr INFO:                 img_mode : BGR
[2024/10/30 14:39:02] ppocr INFO:             MultiLabelEncode : None
[2024/10/30 14:39:02] ppocr INFO:             RecResizeImg : 
[2024/10/30 14:39:02] ppocr INFO:                 image_shape : [3, 48, 320]
[2024/10/30 14:39:02] ppocr INFO:             KeepKeys : 
[2024/10/30 14:39:02] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2024/10/30 14:39:02] ppocr INFO:     loader : 
[2024/10/30 14:39:02] ppocr INFO:         batch_size_per_card : 128
[2024/10/30 14:39:02] ppocr INFO:         drop_last : False
[2024/10/30 14:39:02] ppocr INFO:         num_workers : 4
[2024/10/30 14:39:02] ppocr INFO:         shuffle : False
[2024/10/30 14:39:02] ppocr INFO: Global : 
[2024/10/30 14:39:02] ppocr INFO:     cal_metric_during_train : True
[2024/10/30 14:39:02] ppocr INFO:     character_dict_path : ppocr/utils/ppocr_keys_v1.txt
[2024/10/30 14:39:02] ppocr INFO:     checkpoints : None
[2024/10/30 14:39:02] ppocr INFO:     d2s_train_image_shape : [3, 48, -1]
[2024/10/30 14:39:02] ppocr INFO:     debug : False
[2024/10/30 14:39:02] ppocr INFO:     distributed : False
[2024/10/30 14:39:02] ppocr INFO:     epoch_num : 800
[2024/10/30 14:39:02] ppocr INFO:     eval_batch_step : [0, 2000]
[2024/10/30 14:39:02] ppocr INFO:     infer_img : doc/imgs_words/en/word_1.png
[2024/10/30 14:39:02] ppocr INFO:     infer_mode : False
[2024/10/30 14:39:02] ppocr INFO:     log_smooth_window : 20
[2024/10/30 14:39:02] ppocr INFO:     max_text_length : 25
[2024/10/30 14:39:02] ppocr INFO:     pretrained_model : pretrained_models/ch_PP-OCRv3_rec_train/best_accuracy
[2024/10/30 14:39:02] ppocr INFO:     print_batch_step : 10
[2024/10/30 14:39:02] ppocr INFO:     save_epoch_step : 3
[2024/10/30 14:39:02] ppocr INFO:     save_inference_dir : None
[2024/10/30 14:39:02] ppocr INFO:     save_model_dir : ./output/rec_ppocr_v3_distillation
[2024/10/30 14:39:02] ppocr INFO:     save_res_path : ./output/rec/predicts_ppocrv3_distillation.txt
[2024/10/30 14:39:02] ppocr INFO:     use_gpu : True
[2024/10/30 14:39:02] ppocr INFO:     use_space_char : True
[2024/10/30 14:39:02] ppocr INFO:     use_visualdl : False
[2024/10/30 14:39:02] ppocr INFO: Loss : 
[2024/10/30 14:39:02] ppocr INFO:     loss_config_list : 
[2024/10/30 14:39:02] ppocr INFO:         DistillationDMLLoss : 
[2024/10/30 14:39:02] ppocr INFO:             act : softmax
[2024/10/30 14:39:02] ppocr INFO:             dis_head : ctc
[2024/10/30 14:39:02] ppocr INFO:             key : head_out
[2024/10/30 14:39:02] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2024/10/30 14:39:02] ppocr INFO:             multi_head : True
[2024/10/30 14:39:02] ppocr INFO:             name : dml_ctc
[2024/10/30 14:39:02] ppocr INFO:             use_log : True
[2024/10/30 14:39:02] ppocr INFO:             weight : 1.0
[2024/10/30 14:39:02] ppocr INFO:         DistillationDMLLoss : 
[2024/10/30 14:39:02] ppocr INFO:             act : softmax
[2024/10/30 14:39:02] ppocr INFO:             dis_head : sar
[2024/10/30 14:39:02] ppocr INFO:             key : head_out
[2024/10/30 14:39:02] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2024/10/30 14:39:02] ppocr INFO:             multi_head : True
[2024/10/30 14:39:02] ppocr INFO:             name : dml_sar
[2024/10/30 14:39:02] ppocr INFO:             use_log : True
[2024/10/30 14:39:02] ppocr INFO:             weight : 0.5
[2024/10/30 14:39:02] ppocr INFO:         DistillationDistanceLoss : 
[2024/10/30 14:39:02] ppocr INFO:             key : backbone_out
[2024/10/30 14:39:02] ppocr INFO:             mode : l2
[2024/10/30 14:39:02] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2024/10/30 14:39:02] ppocr INFO:             weight : 1.0
[2024/10/30 14:39:02] ppocr INFO:         DistillationCTCLoss : 
[2024/10/30 14:39:02] ppocr INFO:             key : head_out
[2024/10/30 14:39:02] ppocr INFO:             model_name_list : ['Student', 'Teacher']
[2024/10/30 14:39:02] ppocr INFO:             multi_head : True
[2024/10/30 14:39:02] ppocr INFO:             weight : 1.0
[2024/10/30 14:39:02] ppocr INFO:         DistillationSARLoss : 
[2024/10/30 14:39:02] ppocr INFO:             key : head_out
[2024/10/30 14:39:02] ppocr INFO:             model_name_list : ['Student', 'Teacher']
[2024/10/30 14:39:02] ppocr INFO:             multi_head : True
[2024/10/30 14:39:02] ppocr INFO:             weight : 1.0
[2024/10/30 14:39:02] ppocr INFO:     name : CombinedLoss
[2024/10/30 14:39:02] ppocr INFO: Metric : 
[2024/10/30 14:39:02] ppocr INFO:     base_metric_name : RecMetric
[2024/10/30 14:39:02] ppocr INFO:     ignore_space : False
[2024/10/30 14:39:02] ppocr INFO:     key : Student
[2024/10/30 14:39:02] ppocr INFO:     main_indicator : acc
[2024/10/30 14:39:02] ppocr INFO:     name : DistillationMetric
[2024/10/30 14:39:02] ppocr INFO: Optimizer : 
[2024/10/30 14:39:02] ppocr INFO:     beta1 : 0.9
[2024/10/30 14:39:02] ppocr INFO:     beta2 : 0.999
[2024/10/30 14:39:02] ppocr INFO:     lr : 
[2024/10/30 14:39:02] ppocr INFO:         decay_epochs : [700]
[2024/10/30 14:39:02] ppocr INFO:         name : Piecewise
[2024/10/30 14:39:02] ppocr INFO:         values : [0.0005, 5e-05]
[2024/10/30 14:39:02] ppocr INFO:         warmup_epoch : 5
[2024/10/30 14:39:02] ppocr INFO:     name : Adam
[2024/10/30 14:39:02] ppocr INFO:     regularizer : 
[2024/10/30 14:39:02] ppocr INFO:         factor : 3e-05
[2024/10/30 14:39:02] ppocr INFO:         name : L2
[2024/10/30 14:39:02] ppocr INFO: PostProcess : 
[2024/10/30 14:39:02] ppocr INFO:     key : head_out
[2024/10/30 14:39:02] ppocr INFO:     model_name : ['Student', 'Teacher']
[2024/10/30 14:39:02] ppocr INFO:     multi_head : True
[2024/10/30 14:39:02] ppocr INFO:     name : DistillationCTCLabelDecode
[2024/10/30 14:39:02] ppocr INFO: Train : 
[2024/10/30 14:39:02] ppocr INFO:     dataset : 
[2024/10/30 14:39:02] ppocr INFO:         data_dir : ./train_data/
[2024/10/30 14:39:02] ppocr INFO:         ext_op_transform_idx : 1
[2024/10/30 14:39:02] ppocr INFO:         label_file_list : ['./train_data/train_list.txt']
[2024/10/30 14:39:02] ppocr INFO:         name : SimpleDataSet
[2024/10/30 14:39:02] ppocr INFO:         transforms : 
[2024/10/30 14:39:02] ppocr INFO:             DecodeImage : 
[2024/10/30 14:39:02] ppocr INFO:                 channel_first : False
[2024/10/30 14:39:02] ppocr INFO:                 img_mode : BGR
[2024/10/30 14:39:02] ppocr INFO:             RecConAug : 
[2024/10/30 14:39:02] ppocr INFO:                 ext_data_num : 2
[2024/10/30 14:39:02] ppocr INFO:                 image_shape : [48, 320, 3]
[2024/10/30 14:39:02] ppocr INFO:                 max_text_length : 25
[2024/10/30 14:39:02] ppocr INFO:                 prob : 0.5
[2024/10/30 14:39:02] ppocr INFO:             RecAug : None
[2024/10/30 14:39:02] ppocr INFO:             MultiLabelEncode : None
[2024/10/30 14:39:02] ppocr INFO:             RecResizeImg : 
[2024/10/30 14:39:02] ppocr INFO:                 image_shape : [3, 48, 320]
[2024/10/30 14:39:02] ppocr INFO:             KeepKeys : 
[2024/10/30 14:39:02] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2024/10/30 14:39:02] ppocr INFO:     loader : 
[2024/10/30 14:39:02] ppocr INFO:         batch_size_per_card : 128
[2024/10/30 14:39:02] ppocr INFO:         drop_last : True
[2024/10/30 14:39:02] ppocr INFO:         num_workers : 4
[2024/10/30 14:39:02] ppocr INFO:         shuffle : True
[2024/10/30 14:39:02] ppocr INFO: profiler_options : None
[2024/10/30 14:39:02] ppocr INFO: train with paddle 3.0.0-beta1 and device Place(gpu:0)
W1030 14:39:02.894258 42551 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.4, Runtime API Version: 12.3
W1030 14:39:02.894680 42551 gpu_resources.cc:164] device: 0, cuDNN Version: 9.0.
[2024/10/30 14:39:03] ppocr INFO: load pretrain successful from pretrained_models/ch_PP-OCRv3_rec_train/best_accuracy
[2024/10/30 14:39:03] ppocr INFO: infer_img: doc/imgs_words/en/word_1.png
[2024/10/30 14:39:03] ppocr INFO:        result: {"Student": {"label": "JOINT", "score": 0.9162648916244507}, "Teacher": {"label": "JOINT", "score": 0.9543692469596863}}
[2024/10/30 14:39:03] ppocr INFO: success!
```

**Comment by Cupcc** [comment]
I have updated description for model.
model: v3_digital_mobile/best_accuracy downloaded from baidu netdisk.
please try it again with this model.
