### ISSUE TITLE
recognition training problem with SRN Resnet50_vd_fpn

### ISSUE THREAD

**Issue by yeongwoonIm** [PaddlePaddle/PaddleOCR#1413]
I trained more than 80000 image. it's still training.. it needs so many times...

I picked up one of result files.

I tested it if it is training going well.

but I got error messages it ( the log is below)

==================================================================
**F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop>python tools/infer/predict_system.py --image_dir="./test/t6.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./output/rec/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True --rec_char_type="korean" --rec_char_dict_path="ppocr/utils/dict/korean_dict_edition.txt" --vis_font_path="doc/korean.ttf**
E1214 14:14:38.310488 15088 analysis_predictor.cc:518] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E1214 14:14:38.310488 15088 analysis_predictor.cc:521] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
E1214 14:14:38.488984 15088 analysis_predictor.cc:518] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E1214 14:14:38.488984 15088 analysis_predictor.cc:521] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
E1214 14:14:39.421443 15088 analysis_predictor.cc:518] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E1214 14:14:39.421443 15088 analysis_predictor.cc:521] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
dt_boxes num : 2, elapse : 1.3345222473144531
cls num  : 2, elapse : 0.027072906494140625
E1214 14:14:40.992620 15088 analysis_predictor.cc:330] wrong feed input size, need 5 but get 1
E1214 14:14:40.992620 15088 analysis_predictor.cc:283] fail to set feed
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 181, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 145, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 105, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop\tools\infer\predict_rec.py", line 242, in __call__
    rec_idx_batch = self.output_tensors[0].copy_to_cpu()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (D:\1.8.5\paddle\paddle/fluid/framework/tensor.h:140)
==================================================================

so. I tested another command. and I get error message

==================================================================
**F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop>python tools/infer_rec.py -c configs/rec/rec_r50fpn_vd_none_srn_custom.yml -o Global.checkpoints=./output/rec/best_accuracy Global.infer_img=./test/t1.jpg**
2020-12-14 14:41:21,949-INFO: {'Global': {'debug': False, 'algorithm': 'SRN', 'use_gpu': True, 'epoch_num': 72, 'log_smooth_window': 20, 'print_batch_step': 10, 'save_model_dir': 'output/rec_pvam_withrotate', 'save_epoch_step': 1, 'eval_batch_step': 8000, 'train_batch_size_per_card': 1, 'test_batch_size_per_card': 1, 'image_shape': [1, 64, 256], 'max_text_length': 25, 'character_type': 'korean', 'character_dict_path': './ppocr/utils/dict/korean_dict.txt', 'loss_type': 'srn', 'num_heads': 8, 'average_window': 0.15, 'max_average_window': 15625, 'min_average_window': 10000, 'reader_yml': './configs/rec/rec_benchmark_reader_custom.yml', 'pretrain_weights': './pretrain_models/recognition/rec_r50fpn_vd_none_srn/best_accuracy', 'checkpoints': './output/rec/best_accuracy', 'save_inference_dir': None, 'infer_img': './test/t1.jpg'}, 'Architecture': {'function': 'ppocr.modeling.architectures.rec_model,RecModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.rec_resnet_fpn,ResNet', 'layers': 50}, 'Head': {'function': 'ppocr.modeling.heads.rec_srn_all_head,SRNPredict', 'encoder_type': 'rnn', 'num_encoder_TUs': 2, 'num_decoder_TUs': 4, 'hidden_dims': 512, 'SeqRNN': {'hidden_size': 256}}, 'Loss': {'function': 'ppocr.modeling.losses.rec_srn_loss,SRNLoss'}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.0001, 'beta1': 0.9, 'beta2': 0.999}, 'TrainReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'num_workers': 8, 'img_set_dir': './train_data/recognition/korean/', 'label_file_path': './train_data/recognition/korean/rec_gt.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'img_set_dir': './train_data/recognition/korean/', 'label_file_path': './train_data/recognition/korean/rec_gt.txt'}, 'TestReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader'}}
C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
W1214 14:41:23.087620  8180 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 10.0
W1214 14:41:23.169821  8180 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-12-14 14:41:28,716-INFO: Finish initing model from ./output/rec/best_accuracy
2020-12-14 14:41:28,858-INFO: infer_img:./test/t1.jpg
C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/infer_rec.py", line 176, in <module>
    main()
  File "tools/infer_rec.py", line 117, in main
    return_numpy=False)
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "C:\Users\imyw\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\layers\nn.py", line 7480, in reshape
    "XShape": x_shape})
  File "F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop\ppocr\modeling\heads\rec_srn_all_head.py", line 212, in gsrm
    [-1, c]))
  File "F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop\ppocr\modeling\heads\rec_srn_all_head.py", line 251, in __call__
    gsrm_features, word_out, gsrm_out = self.gsrm(pvam_features, others)
  File "F:\ywim\OCR\PaddleOCR-develop\PaddleOCR-develop\ppocr\modeling\architectures\rec_model.py", line 209, in __call__
    predicts = self.head(conv_feas, labels, mode)
  File "tools/infer_rec.py", line 71, in main
    _, outputs = rec_model(mode="test")
  File "tools/infer_rec.py", line 176, in <module>
    main()

----------------------

Error Message Summary:
----------------------
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 25, 11270], X's size = 281750, 'shape' is [-1, 3691], known capacity of 'shape' is -3691.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-280516 != -in_size:-281750.] at (D:\1.8.5\paddle\paddle\fluid\operators\reshape_op.cc:192)
  [operator < reshape2 > error]
==================================================================

test image
![t1](https://user-images.githubusercontent.com/12051241/102046962-bfefbc80-3e1f-11eb-8a5f-2888933da5c6.jpg)

what should I wrong??

thank you for read my isuue.

**Comment by yeongwoonIm** [comment]
I use should dict files that I made. I use other dict files;;;
