### ISSUE TITLE
导出推理模型时，能导出，但是有报错UnicodeEncodeError: 'gbk' codec can't encode character '\xa1' in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#14136]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

[2024/10/31 21:10:33] ppocr INFO: resume from C:\Users\Ni\Desktop\svtr2\best_accuracy
[2024/10/31 21:10:41] ppocr INFO: inference model is saved to C:\Users\Ni\Desktop\svtr2\best_accuracy\inference
Traceback (most recent call last):
  File "tools/export_model.py", line 37, in <module>
    main()
  File "tools/export_model.py", line 33, in main
    export(config)
  File "L:\paddle\PaddleOCR-2.9.1\ppocr\utils\export_model.py", line 382, in export
    dump_infer_config(config, yaml_path, logger)
  File "L:\paddle\PaddleOCR-2.9.1\ppocr\utils\export_model.py", line 100, in dump_infer_config
    yaml.dump(
  File "D:\Python3.8.8\lib\site-packages\yaml\__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "D:\Python3.8.8\lib\site-packages\yaml\__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "D:\Python3.8.8\lib\site-packages\yaml\representer.py", line 28, in represent
    self.serialize(node)
  File "D:\Python3.8.8\lib\site-packages\yaml\serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "D:\Python3.8.8\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "D:\Python3.8.8\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "D:\Python3.8.8\lib\site-packages\yaml\serializer.py", line 98, in serialize_node
    self.serialize_node(item, node, index)
  File "D:\Python3.8.8\lib\site-packages\yaml\serializer.py", line 89, in serialize_node
    self.emit(ScalarEvent(alias, node.tag, implicit, node.value,
  File "D:\Python3.8.8\lib\site-packages\yaml\emitter.py", line 115, in emit
    self.state()
  File "D:\Python3.8.8\lib\site-packages\yaml\emitter.py", line 384, in expect_block_sequence_item
    self.expect_node(sequence=True)
  File "D:\Python3.8.8\lib\site-packages\yaml\emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "D:\Python3.8.8\lib\site-packages\yaml\emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "D:\Python3.8.8\lib\site-packages\yaml\emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "D:\Python3.8.8\lib\site-packages\yaml\emitter.py", line 1132, in write_plain
    self.stream.write(data)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa1' in position 0: illegal multibyte sequence

### 🏃‍♂️ Environment (运行环境)

win10
paddleocr2.9.1
paddlepaddle2.3.2

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

win10
paddleocr2.9.1
paddlepaddle2.3.2

**Comment by jingsongliujing** [comment]
修改一下代码编辑器的字符编码试试，改成utf-8

**Comment by nissansz** [comment]
我是windows10命令行直接执行的，要怎么修改？

python tools/export_model.py -c "F:\rec_svtrv2_ch.yml" -o Global.checkpoints="\best_accuracy"  Global.save_inference_dir="\best_accuracy"

**Comment by nissansz** [comment]
没解决，不过不影响转换

**Comment by GreatV** [comment]
换linux训练吧
