### ISSUE TITLE
[海光CPU]paddleOCR Docker部署提示libgalaxyhip.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shininglxj** [PaddlePaddle/PaddleOCR#14263]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

Docker启动后报如下错误：

```
Error: Can not import paddle core while this file exists: /opt/py310/lib/python3.10/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/opt/py310/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/opt/py310/lib/python3.10/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
  File "/opt/py310/lib/python3.10/site-packages/paddle/__init__.py", line 38, in <module>
    from .base import core  # noqa: F401
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/backward.py", line 28, in <module>
    from . import core, framework, log_helper, unique_name
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/core.py", line 387, in <module>
    raise e
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: libgalaxyhip.so.5: cannot open shared object file: No such file or directory
```

### 🏃‍♂️ Environment (运行环境)

CPU环境
```
(paddleOCR) root@inspur-H3C-UniServer-R4930-G5-H3:/data2/paddle# lscpu
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
字节序：                         Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU:                             128
在线 CPU 列表：                  0-127
每个核的线程数：                 2
每个座的核数：                   32
座：                             2
NUMA 节点：                      8
厂商 ID：                        HygonGenuine
CPU 系列：                       24
型号：                           3
型号名称：                       Hygon C86 7390 32-core Processor
步进：                           1
Frequency boost:                 enabled
CPU MHz：                        1600.000
CPU 最大 MHz：                   2700.0000
CPU 最小 MHz：                   1600.0000
BogoMIPS：                       5399.93
虚拟化：                         AMD-V
L1d 缓存：                       2 MiB
L1i 缓存：                       4 MiB
L2 缓存：                        32 MiB
L3 缓存：                        128 MiB
NUMA 节点0 CPU：                 0-7,64-71
NUMA 节点1 CPU：                 8-15,72-79
NUMA 节点2 CPU：                 16-23,80-87
NUMA 节点3 CPU：                 24-31,88-95
NUMA 节点4 CPU：                 32-39,96-103
NUMA 节点5 CPU：                 40-47,104-111
NUMA 节点6 CPU：                 48-55,112-119
NUMA 节点7 CPU：                 56-63,120-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl 
                                 nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8
                                 _legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 s
                                 mep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeas
                                 sists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev sev_es
```

GPU环境
```
Thu Nov 21 11:52:00 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:41:00.0 Off |                    0 |
|  0%   42C    P0             75W /  300W |   24098MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A40                     On  |   00000000:C1:00.0 Off |                    0 |
|  0%   41C    P0             77W /  300W |   11385MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

Dockerfile配置:
```
FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle-dcu:dtk24.04.1-kylinv10-gcc82

RUN pip3 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install --pre paddlepaddle-dcu -i https://www.paddlepaddle.org.cn/packages/nightly/dcu/
RUN pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple

# git clone https://gitee.com/paddlepaddle/PaddleOCR /PaddleOCR
ADD PaddleOCR.zip /
RUN unzip /PaddleOCR.zip -d /
WORKDIR /PaddleOCR

RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
 
RUN mkdir -p /PaddleOCR/inference/

# 下载解压模型开始 ps:如果切换为服务端模型，记得修改deploy/hubserving/ocr_system/params.py下对应的模型位置
ADD https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_server_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_PP-OCRv4_det_server_infer.tar -C /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_server_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_PP-OCRv4_rec_server_infer.tar -C /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer.tar -C /PaddleOCR/inference/
# 下载解压模型结束
EXPOSE 8868
CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system"]
```

**Comment by jingsongliujing** [comment]
你这个镜像是针对海光DCU显卡的环境，但是你没有DCU显卡，而我看你的卡是英伟达的，建议换一个部署的基础镜像，cpu环境的话建议换一个python的基础环境镜像比如：FROM python:3.9-slim-buster
![image](https://github.com/user-attachments/assets/0b7c1a9f-e3fb-44b3-8b7e-704fed01ea68)

**Comment by JeffRody** [comment]
export LD_LIBRARY_PATH=/opt/dtk-24.04.3/lib:/opt/dtk-24.04.3/cuda/extras/CUPTI/lib64:/opt/dtk-24.04.3/cuda/targets/x86_64-linux/lib:$LD_LIBRARY_PATH

**Comment by JeffRody** [comment]
设置动态库关联后就行

**Comment by JeffRody** [comment]
https://developer.sourcefind.cn/codes/modelzoo/crnn_paddle/-/blob/main/README.md 参考这篇文章
