### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by shadow-wxh** [PaddlePaddle/PaddleOCR#14412]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

OCR GPU 执行报错

### 🏃‍♂️ Environment (运行环境)

‘OS Win10, GPU NVidia 1080Ti, CUDA12.0, PaddelPaddle2.6.1, PaddleOCR 2.9.1’

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

`F:\MyProjects\FormBoxOCR\ppocr_img>paddleocr --image_dir ./imgs/1.jpg --use_angle_cls true --use_gpu true
[2024/12/18 04:00:50] ppocr INFO: for usage help, please use `paddleocr --help`
[2024/12/18 04:00:50] ppocr DEBUG: Namespace(alpha=1.0, alphacolor=(255, 255, 255), benchmark=False, beta=1.0, binarize=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\shado/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\shado/.paddleocr/whl\\det\\ch\\ch_PP-OCRv4_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, formula=False, formula_algorithm='LaTeXOCR', formula_batch_num=1, formula_char_dict_path=None, formula_model_dir=None, fourier_degree=5, gpu_id=0, gpu_mem=500, help='==SUPPRESS==', image_dir='./imgs/1.jpg', image_orientation=False, invert=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv4', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='F:\\Python38\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='C:\\Users\\shado/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv4_rec_infer', recovery=False, recovery_to_markdown=False, return_word_box=False, save_crop_res=False, save_log_path='./log_output/', savefile=False, scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=True, use_mlu=False, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2024/12/18 04:00:50] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/12/18 04:00:52] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/12/18 04:00:55] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/12/18 04:00:57] ppocr INFO: **********./imgs/1.jpg**********
[2024/12/18 04:00:57] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.31247758865356445
[2024/12/18 04:00:57] ppocr DEBUG: cls num  : 0, elapsed : 0
[2024/12/18 04:00:57] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
Traceback (most recent call last):
  File "F:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Python38\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\Python38\lib\site-packages\paddleocr\paddleocr.py", line 978, in main
    for line in res:
TypeError: 'NoneType' object is not iterable`

**Comment by jingsongliujing** [comment]
看看图片数据是否正确读取，或者说图片数据是否损坏？
```
import cv2

# 图片文件的路径，替换为你实际的图片路径
image_path = "your_image_path.jpg"  

try:
    # 使用cv2.imread函数读取图片，它会返回一个表示图像的numpy数组
    image = cv2.imread(image_path)
    if image is not None:
        print("图片读取成功")
    else:
        print("无法正确读取图片，可能是文件路径错误、文件损坏或者图片格式不被支持等原因")
except Exception as e:
    print(f"读取图片时出现错误: {str(e)}")
```
