### ISSUE TITLE
使用StyleText批量生成图像结果不成功

### ISSUE THREAD

**Issue by yiyi99** [PaddlePaddle/PaddleOCR#1508]
使用StyleText批量生成图像结果不成功，执行：python tools/synth_dataset.py -c configs/dataset_config.yml
dataset_config.yml文件内容：
Global:
  output_num: 10
  output_dir: output_data
  use_gpu: false
  image_height: 32
  image_width: 320
  standard_font: fonts/en_standard.ttf
TextDrawer:
  fonts:
    en: fonts/en_standard.ttf
    ch: fonts/ch_standard.ttf
    ko: fonts/ko_standard.ttf
StyleSampler:
  method: DatasetSampler
  image_home: datas/bg
  label_file: 
  with_label: false
CorpusGenerator:
  method: FileCorpus
  language: ch
  corpus_file: datas/text/unit.txt
Predictor:
  method: StyleTextRecPredictor
  algorithm: StyleTextRec
  scale: 0.00392156862745098
  mean:
  - 0.5
  - 0.5
  - 0.5
  std:
  - 0.5
  - 0.5
  - 0.5
  expand_result: false
  bg_generator:
    pretrain: style_text_models/bg_generator
    module_name: bg_generator
    generator_type: BgGeneratorWithMask
    encode_dim: 64
    norm_layer: null
    conv_block_num: 4
    conv_block_dropout: false
    conv_block_dilation: true
    output_factor: 1.05
  text_generator:
    pretrain: style_text_models/text_generator
    module_name: text_generator
    generator_type: TextGenerator
    encode_dim: 64
    norm_layer: InstanceNorm2D
    conv_block_num: 4
    conv_block_dropout: false
    conv_block_dilation: true
  fusion_generator:
    pretrain: style_text_models/fusion_generator
    module_name: fusion_generator
    generator_type: FusionGeneratorSimple
    encode_dim: 64
    norm_layer: null
    conv_block_num: 4
    conv_block_dropout: false
    conv_block_dilation: true
Writer:
  method: SimpleWriter
结果只在StyleText目录下生成了三个文件：
![image](https://user-images.githubusercontent.com/3916992/102600685-19c2f000-415a-11eb-9340-45b5882d3049.png)

**Comment by weisy11** [comment]
如果使用的style_image的输入没有标签，label_file需要输入一个图片列表文件，详见：
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/StyleText/README_ch.md#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B

**Comment by yiyi99** [comment]
[root@localhost StyleText]# python3 tools/synth_dataset.py -c configs/dataset_config.yml
[2020/12/22 15:20:23] srnet INFO: load pretrained model from style_text_models/bg_generator
[2020/12/22 15:20:25] srnet INFO: load pretrained model from style_text_models/text_generator
[2020/12/22 15:20:25] srnet INFO: load pretrained model from style_text_models/fusion_generator
[2020/12/22 15:20:25] srnet INFO: using FileCorpus
[2020/12/22 15:20:26] srnet INFO: generate image: output_data/images/0/0.png
[2020/12/22 15:20:26] srnet WARNING: corpus length exceed limit: METABOLIC: CALCIUM
[2020/12/22 15:20:27] srnet INFO: generate image: output_data/images/0/1.png
Traceback (most recent call last):
  File "tools/synth_dataset.py", line 31, in <module>
    synth_dataset()
  File "tools/synth_dataset.py", line 27, in synth_dataset
    dataset_synthesiser.synth_dataset()
  File "/PaddleOCR/StyleText/engine/synthesisers.py", line 60, in synth_dataset
    style_data = self.style_sampler.sample()
  File "/PaddleOCR/StyleText/engine/style_samplers.py", line 44, in sample
    origin_height = image.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

image_list.txt文件内容：
b0.jpg	
b1.jpg	
b2.jpg
b3.jpg
b4.jpg

请问是哪里有问题？是对图像文件有尺寸要求吗？

**Comment by cxy86121** [comment]
可能是图片路径问题，建议把图片路径打印出来看一下
