### ISSUE TITLE
windows python3.7按照paddle后，导入失败ImportError: DLL load failed

### ISSUE THREAD

**Issue by sz-lcw** [PaddlePaddle/PaddleOCR#1567]
系统：windows10
paddle版本：2.0.0b0
参照https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md 安装cpu版本paddle。
安装完成之后，import paddle报错：

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\__init__.py", line 34, in <module>
    from .fluid import monkey_patch_variable
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\core.py", line 271, in <module>
    raise e
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\core.py", line 241, in <module>
    from .core_avx import *
ImportError: DLL load failed: 找不到指定的模块。

**Comment by xmy0916** [comment]
换2.0.0rc1的paddlepaddle试试

**Comment by sz-lcw** [comment]
> 换2.0.0rc1的paddlepaddle试试

谢谢，我这边尝试切换成paddlepaddle-2.0.0rc1版本，还是报同样的错误。

**Comment by xmy0916** [comment]
你这个是在docker的环境下嘛？

**Comment by sz-lcw** [comment]
> 你这个是在docker的环境下嘛？

我是在默认widows10的系统环境下安装的，整个安装过程没有问题，就是安装完成后无法调用。

**Comment by MissPenguin** [comment]
paddle框架repo下有些类似issue可以参考下，比如这个：https://github.com/PaddlePaddle/Paddle/issues/28205

**Comment by sz-lcw** [comment]
> paddle框架repo下有些类似issue可以参考下，比如这个：[PaddlePaddle/Paddle#28205](https://github.com/PaddlePaddle/Paddle/issues/28205)

@MissPenguin 感谢指导，按照链接指引，现在import paddle已经不会报错了，但是启动PPOCRLabel.py时仍然会报错，是否对imgaug有特定的版本要求呢？
错误如下：

> Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "..\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "..\tools\infer\predict_system.py", line 30, in <module>
    import tools.infer.predict_det as predict_det
  File "..\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "..\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "..\ppocr\data\imaug\__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "..\ppocr\data\imaug\iaa_augment.py", line 20, in <module>
    import imgaug
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\imgaug\imgaug.py", line 22, in <module>
    import skimage.draw
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: 找不到指定的模块。

**Comment by sz-lcw** [comment]
> > paddle框架repo下有些类似issue可以参考下，比如这个：[PaddlePaddle/Paddle#28205](https://github.com/PaddlePaddle/Paddle/issues/28205)
> 
> @MissPenguin 感谢指导，按照链接指引，现在import paddle已经不会报错了，但是启动PPOCRLabel.py时仍然会报错，是否对imgaug有特定的版本要求呢？
> 错误如下：
> 
> > Traceback (most recent call last):
> > File "PPOCRLabel.py", line 34, in 
> > from paddleocr import PaddleOCR
> > File "..\paddleocr.py", line 28, in 
> > from tools.infer import predict_system
> > File "..\tools\infer\predict_system.py", line 30, in 
> > import tools.infer.predict_det as predict_det
> > File "..\tools\infer\predict_det.py", line 31, in 
> > from ppocr.data import create_operators, transform
> > File "..\ppocr\data__init__.py", line 34, in 
> > from ppocr.data.imaug import transform, create_operators
> > File "..\ppocr\data\imaug__init__.py", line 19, in 
> > from .iaa_augment import IaaAugment
> > File "..\ppocr\data\imaug\iaa_augment.py", line 20, in 
> > import imgaug
> > File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\imgaug__init__.py", line 7, in 
> > from imgaug.imgaug import *  # pylint: disable=redefined-builtin
> > File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\imgaug\imgaug.py", line 22, in 
> > import skimage.draw
> > File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage__init__.py", line 127, in 
> > from .util.dtype import (img_as_float32,
> > File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\util__init__.py", line 17, in 
> > from ._map_array import map_array
> > File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\util_map_array.py", line 2, in 
> > from ._remap import _map_array
> > ImportError: DLL load failed: 找不到指定的模块。

感谢各位的解答，根据错误信息，定位到时skimage加载问题，google后发现是安装的numpy不是MKL版本导致。
在https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy 上下载对应版本的Numpy+MKL安装包即可。
