### ISSUE TITLE
报bug，下载的PaddleOCR-1.1.0.tar.gz，无法启动服务的问题，No module named 'tools.infer'`

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#1568]
**module.py少了下面三行代码，会导致项目无法部署**
![ZX3JK7VPTQOB$MHAJ$J4{T9](https://user-images.githubusercontent.com/15188456/103047505-b6f0af00-45c6-11eb-852f-ff18854057cd.png)
**如果没有加会报下面的错误：**
`Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\Service\pythonProjects\paddlehubTest\windows\python-3.7.9\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\service\pythonprojects\paddlehubtest\windows\python-3.7.9\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "d:\service\pythonprojects\paddlehubtest\windows\python-3.7.9\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "d:\service\pythonprojects\paddlehubtest\windows\python-3.7.9\lib\site-packages\paddlehub\commands\install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "d:\service\pythonprojects\paddlehubtest\windows\python-3.7.9\lib\site-packages\paddlehub\module\manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "d:\service\pythonprojects\paddlehubtest\windows\python-3.7.9\lib\site-packages\paddlehub\module\module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "d:\service\pythonprojects\paddlehubtest\windows\python-3.7.9\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "deploy\hubserving\ocr_system\module.py", line 26, in <module>
    from tools.infer.utility import base64_to_cv2
ModuleNotFoundError: No module named 'tools.infer'`

**Comment by YY007H** [comment]
加上的代码如下：
import sys
sys.path.insert(0, ".")

**Comment by xmy0916** [comment]
这个一般需要export一下PYTHONPATH就可以了的~
例如
cd 对应目录
export PYTHONPATH=./
python xxx.py

**Comment by YY007H** [comment]
@xmy0916 不是这个原因，你可以把PaddleOCR-1.1.0.tar.gz下载下来试一下

**Comment by MissPenguin** [comment]
repo中的最新代码是有这部分代码的，可能你用的时候代码没有更新到最新。

**Comment by YY007H** [comment]
@MissPenguin https://codeload.github.com/PaddlePaddle/PaddleOCR/tar.gz/v1.1.0，你看看这个连接下载的里面有吗？我是从这里下载的

**Comment by MissPenguin** [comment]
> @MissPenguin [https://codeload.github.com/PaddlePaddle/PaddleOCR/tar.gz/v1.1.0，你看看这个连接下载的里面有吗？我是从这里下载的](https://codeload.github.com/PaddlePaddle/PaddleOCR/tar.gz/v1.1.0%EF%BC%8C%E4%BD%A0%E7%9C%8B%E7%9C%8B%E8%BF%99%E4%B8%AA%E8%BF%9E%E6%8E%A5%E4%B8%8B%E8%BD%BD%E7%9A%84%E9%87%8C%E9%9D%A2%E6%9C%89%E5%90%97%EF%BC%9F%E6%88%91%E6%98%AF%E4%BB%8E%E8%BF%99%E9%87%8C%E4%B8%8B%E8%BD%BD%E7%9A%84)

这是哪里的链接，用静态图版本（v1.1）的话，直接拉最新代码切develop分支吧，发现问题一般都在develop分支修复的
