### ISSUE TITLE
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/platform/cudnn_helper.h:373)

### ISSUE THREAD

**Issue by leminhyen2** [PaddlePaddle/PaddleOCR#1576]
I encountered this issue while using chinese common.yml training configuration. I'm not sure if this is a cudnn error or error on my changes in the yml file. Can you help me out

python3 -m paddle.distributed.launch --gpus '0'  tools/train.py -c ./configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml

-----------  Configuration Arguments -----------
gpus: 0
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', './configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml']
worker_num: None
workers: 
------------------------------------------------
WARNING 2020-12-25 06:45:32,831 launch.py:314] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2020-12-25 06:45:32,832 launch_utils.py:472] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55383               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:55383               |
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2020-12-25 06:45:32,832 launch_utils.py:476] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log.
[2020/12/25 06:45:34] root INFO: Architecture : 
[2020/12/25 06:45:34] root INFO:     Backbone : 
[2020/12/25 06:45:34] root INFO:         layers : 34
[2020/12/25 06:45:34] root INFO:         name : ResNet
[2020/12/25 06:45:34] root INFO:     Head : 
[2020/12/25 06:45:34] root INFO:         fc_decay : 4e-05
[2020/12/25 06:45:34] root INFO:         name : CTCHead
[2020/12/25 06:45:34] root INFO:     Neck : 
[2020/12/25 06:45:34] root INFO:         encoder_type : rnn
[2020/12/25 06:45:34] root INFO:         hidden_size : 256
[2020/12/25 06:45:34] root INFO:         name : SequenceEncoder
[2020/12/25 06:45:34] root INFO:     Transform : None
[2020/12/25 06:45:34] root INFO:     algorithm : CRNN
[2020/12/25 06:45:34] root INFO:     model_type : rec
[2020/12/25 06:45:34] root INFO: Eval : 
[2020/12/25 06:45:34] root INFO:     dataset : 
[2020/12/25 06:45:34] root INFO:         data_dir : ./
[2020/12/25 06:45:34] root INFO:         label_file_list : ['./test_data/labels.txt']
[2020/12/25 06:45:34] root INFO:         name : SimpleDataSet
[2020/12/25 06:45:34] root INFO:         transforms : 
[2020/12/25 06:45:34] root INFO:             DecodeImage : 
[2020/12/25 06:45:34] root INFO:                 channel_first : False
[2020/12/25 06:45:34] root INFO:                 img_mode : BGR
[2020/12/25 06:45:34] root INFO:             CTCLabelEncode : None
[2020/12/25 06:45:34] root INFO:             RecResizeImg : 
[2020/12/25 06:45:34] root INFO:                 image_shape : [3, 32, 320]
[2020/12/25 06:45:34] root INFO:             KeepKeys : 
[2020/12/25 06:45:34] root INFO:                 keep_keys : ['image', 'label', 'length']
[2020/12/25 06:45:34] root INFO:     loader : 
[2020/12/25 06:45:34] root INFO:         batch_size_per_card : 256
[2020/12/25 06:45:34] root INFO:         drop_last : False
[2020/12/25 06:45:34] root INFO:         num_workers : 8
[2020/12/25 06:45:34] root INFO:         shuffle : False
[2020/12/25 06:45:34] root INFO: Global : 
[2020/12/25 06:45:34] root INFO:     cal_metric_during_train : False
[2020/12/25 06:45:34] root INFO:     character_dict_path : ./ppocr/utils/ppocr_keys_v1.txt
[2020/12/25 06:45:34] root INFO:     character_type : ch
[2020/12/25 06:45:34] root INFO:     checkpoints : None
[2020/12/25 06:45:34] root INFO:     debug : False
[2020/12/25 06:45:34] root INFO:     distributed : False
[2020/12/25 06:45:34] root INFO:     epoch_num : 500
[2020/12/25 06:45:34] root INFO:     eval_batch_step : [0, 2000]
[2020/12/25 06:45:34] root INFO:     infer_img : doc/imgs_words/ch/word_1.jpg
[2020/12/25 06:45:34] root INFO:     infer_mode : False
[2020/12/25 06:45:34] root INFO:     log_smooth_window : 20
[2020/12/25 06:45:34] root INFO:     max_text_length : 25
[2020/12/25 06:45:34] root INFO:     pretrained_model : ./pretrain_models/CRNN/best_accuracy
[2020/12/25 06:45:34] root INFO:     print_batch_step : 10
[2020/12/25 06:45:34] root INFO:     save_epoch_step : 3
[2020/12/25 06:45:34] root INFO:     save_inference_dir : None
[2020/12/25 06:45:34] root INFO:     save_model_dir : ./output/rec_chinese_common_v2.0
[2020/12/25 06:45:34] root INFO:     use_gpu : True
[2020/12/25 06:45:34] root INFO:     use_space_char : True
[2020/12/25 06:45:34] root INFO:     use_visualdl : False
[2020/12/25 06:45:34] root INFO: Loss : 
[2020/12/25 06:45:34] root INFO:     name : CTCLoss
[2020/12/25 06:45:34] root INFO: Metric : 
[2020/12/25 06:45:34] root INFO:     main_indicator : acc
[2020/12/25 06:45:34] root INFO:     name : RecMetric
[2020/12/25 06:45:34] root INFO: Optimizer : 
[2020/12/25 06:45:34] root INFO:     beta1 : 0.9
[2020/12/25 06:45:34] root INFO:     beta2 : 0.999
[2020/12/25 06:45:34] root INFO:     lr : 
[2020/12/25 06:45:34] root INFO:         learning_rate : 0.001
[2020/12/25 06:45:34] root INFO:         name : Cosine
[2020/12/25 06:45:34] root INFO:     name : Adam
[2020/12/25 06:45:34] root INFO:     regularizer : 
[2020/12/25 06:45:34] root INFO:         factor : 4e-05
[2020/12/25 06:45:34] root INFO:         name : L2
[2020/12/25 06:45:34] root INFO: PostProcess : 
[2020/12/25 06:45:34] root INFO:     name : CTCLabelDecode
[2020/12/25 06:45:34] root INFO: Train : 
[2020/12/25 06:45:34] root INFO:     dataset : 
[2020/12/25 06:45:34] root INFO:         data_dir : ./
[2020/12/25 06:45:34] root INFO:         label_file_list : ['./train_data/labels.txt']
[2020/12/25 06:45:34] root INFO:         name : SimpleDataSet
[2020/12/25 06:45:34] root INFO:         transforms : 
[2020/12/25 06:45:34] root INFO:             DecodeImage : 
[2020/12/25 06:45:34] root INFO:                 channel_first : False
[2020/12/25 06:45:34] root INFO:                 img_mode : BGR
[2020/12/25 06:45:34] root INFO:             RecAug : None
[2020/12/25 06:45:34] root INFO:             CTCLabelEncode : None
[2020/12/25 06:45:34] root INFO:             RecResizeImg : 
[2020/12/25 06:45:34] root INFO:                 image_shape : [3, 32, 320]
[2020/12/25 06:45:34] root INFO:             KeepKeys : 
[2020/12/25 06:45:34] root INFO:                 keep_keys : ['image', 'label', 'length']
[2020/12/25 06:45:34] root INFO:     loader : 
[2020/12/25 06:45:34] root INFO:         batch_size_per_card : 256
[2020/12/25 06:45:34] root INFO:         drop_last : True
[2020/12/25 06:45:34] root INFO:         num_workers : 8
[2020/12/25 06:45:34] root INFO:         shuffle : True
[2020/12/25 06:45:34] root INFO: train with paddle 2.0.0-rc1 and device CUDAPlace(0)
[2020/12/25 06:45:34] root INFO: Initialize indexs of datasets:['./train_data/labels.txt']
[2020/12/25 06:45:34] root INFO: Initialize indexs of datasets:['./test_data/labels.txt']
W1225 06:45:34.368119  3828 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.2
W1225 06:45:34.372629  3828 device_context.cc:330] device: 0, cuDNN Version: 7.6.
[2020/12/25 06:45:37] root INFO: load pretrained model from ['./pretrain_models/CRNN/best_accuracy']
[2020/12/25 06:45:37] root INFO: train dataloader has 388 iters, valid dataloader has 39 iters
[2020/12/25 06:45:37] root INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/ubuntu/PaddleOCR/tools/program.py", line 197, in train
    preds = model(images)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 76, in forward
    x = self.neck(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/PaddleOCR/ppocr/modeling/necks/rnn.py", line 91, in forward
    x = self.encoder(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/PaddleOCR/ppocr/modeling/necks/rnn.py", line 45, in forward
    x, _ = self.lstm(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1035, in forward
    return self._cudnn_impl(inputs, initial_states, sequence_length)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1012, in _cudnn_impl
    type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2837, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/platform/cudnn_helper.h:373)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < rnn > error]
INFO 2020-12-25 06:45:47,859 launch_utils.py:308] terminate all the procs
ERROR 2020-12-25 06:45:47,860 launch_utils.py:546] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-12-25 06:45:50,863 launch_utils.py:308] terminate all the procs

**Comment by leminhyen2** [comment]
For anyone with similar issues, I lower the batch size to 100 and got the training to start

**Comment by 1193700079** [comment]
减小batchsize 就可以了
