### ISSUE TITLE
TensorRT inference: Input shapes are inconsistent with the model.

### ISSUE THREAD

**Issue by akarsh1995** [PaddlePaddle/PaddleOCR#1596]
I've compiled Paddle library natively with tensorrt. I tried inference detection model by setting `--use_tensorrt True` flag and it doesn't work.

**CUDA Versions:** 
```
cuda: 11.0.3
cudnn: 8.0.5.39-1+cuda11.0
tensorrt: 7.1.3-1+cuda11.0
```

**Stack trace:**
```
$ FLAGS_call_stack_level=2 python3 tools/infer/predict_det.py --image_dir ./doc/imgs/12.jpg --det_model_dir ./inference_models/ch_ppocr_mobile_v2.0_det_infer --gpu_mem 2000 --use_tensorrt True
W1228 18:13:45.902424 28424 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 215, in <module>
    dt_boxes, elapse = text_detector(img)
  File "tools/infer/predict_det.py", line 169, in __call__
    self.predictor.run([im])
ValueError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::operators::TensorRTEngineOp::RunTrt(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::inference::tensorrt::TensorRTEngine*) const
4   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Input shapes are inconsistent with the model. Expect [3, 640, 640] in model description, but got [3, 1184, 736] in runtime. TRT 5 or lower version does not support dynamic input shapes. Please check and modify your input shapes.
  [Hint: Expected model_input_shape == runtime_input_shape == true, but received model_input_shape == runtime_input_shape:0 != true:1.] (at /home/akarsh/Programming/compilation-pdl/Paddle/paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:76)
```

**Comment by littletomatodonkey** [comment]
Support for inconsistent shape of tensorRT inference is on the way, Thanks for your attention.

**Comment by littletomatodonkey** [comment]
As for now, it's remonnended to keep consistent input shape for tensorRT inference using resize and padding. Of course, the model should also be re-exported using your expected inference shape.

**Comment by NextGuido** [comment]
@littletomatodonkey any updates here?

**Comment by lfxx** [comment]
> Support for inconsistent shape of tensorRT inference is on the way, Thanks for your attention.

Any updates?looking forward to this function.

**Comment by rsingh2083** [comment]
> > Support for inconsistent shape of tensorRT inference is on the way, Thanks for your attention.
> 
> Any updates?looking forward to this function.

Did you find this solution ?

**Comment by RS00001** [comment]
Any update on this?
