### ISSUE TITLE
infer.py有bug多定义了一个 --use_tensorrt:

### ISSUE THREAD

**Issue by atczyh** [PaddlePaddle/PaddleOCR#1627]
运行python3 tools/infer/predict_system.py 报错
`Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 187, in <module>
    main(utility.parse_args())
  File "/mnt/linuxsdb/zengyihui/PaddleOCR/tools/infer/utility.py", line 86, in parse_args
    parser.add_argument("--use_tensorrt", type=str2bool, default=False)
  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1724, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1565, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1375, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.6/argparse.py", line 1514, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.6/argparse.py", line 1523, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --use_tensorrt: conflicting option string: --use_tensorrt
`
经检查infer.py下 --use_tensorrt定义两次

**Comment by WenmuZhou** [comment]
fixed https://github.com/PaddlePaddle/PaddleOCR/pull/1631
