### ISSUE TITLE
win10运行 python PPOCRLabel.py --lang ch出现以下错误！！

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#1632]
Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "..\tools\infer\predict_system.py", line 28, in <module>
    import tools.infer.predict_det as predict_det
  File "..\tools\infer\predict_det.py", line 30, in <module>
    from ppocr.data import create_operators, transform
  File "..\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "..\ppocr\data\imaug\__init__.py", line 20, in <module>
    from .make_border_map import MakeBorderMap
  File "..\ppocr\data\imaug\make_border_map.py", line 13, in <module>
    from shapely.geometry import Polygon
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by Evezerest** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/installation.md shapely库的问题，最后一行可以参考一下

**Comment by WZMIAOMIAO** [comment]
win10遇到了同样的问题，安装了shapely库也没有用（PadleOCR里的整个requirements都安装完了）。
