### ISSUE TITLE
发现个导致内存爆了的问题

### ISSUE THREAD

**Issue by singlebear** [PaddlePaddle/PaddleOCR#1665]
在训练检测模型时，多次复现证明reader存在问题。主要如下：
1、reader的读取没有动态变化，当读取速度大于训练速度时，导致占用内存不断增长，使得最终爆内存。此条可通过减小读取线程数暂时缓解。
2、eval时，训练的reader依旧在读取数据，导致内存不断增长至爆内存死机。哪怕eval过程报错弹出了Error Message Summary,按理进程应该停止，但是他依旧在继续读取导致爆内存。
一爆内存的结果就是导致电脑死机

**Comment by singlebear** [comment]
2中eval时，内存的增长与设置的test_batch_size无关，tackling num无关，只按时间定增，说明是读取导致的内存增大

**Comment by singlebear** [comment]
且2中内存增长速率随着降低训练的读取线程数，增长量变低。说明爆内存是由于训练的读取线程一直读取，但是没进行训练导致的。
优化建议：
1、eval时，终止训练的数据读取。
2、抛出异常时，终止数据读取。否则回来一看电脑死了，异常原因都看不全。

**Comment by zhaoyantao-murray** [comment]
老哥借楼，我用AIstudio上的GPU环境eval自己的图片显示共享内存不足，能帮忙看一下怎么办吗？感谢感谢。报错信息如下：

[2021/04/04 17:18:28] root INFO: Architecture : 
[2021/04/04 17:18:28] root INFO:     Backbone : 
[2021/04/04 17:18:28] root INFO:         disable_se : True
[2021/04/04 17:18:28] root INFO:         layers : 18
[2021/04/04 17:18:28] root INFO:         name : ResNet
[2021/04/04 17:18:28] root INFO:     Head : 
[2021/04/04 17:18:28] root INFO:         k : 50
[2021/04/04 17:18:28] root INFO:         name : DBHead
[2021/04/04 17:18:28] root INFO:     Neck : 
[2021/04/04 17:18:28] root INFO:         name : DBFPN
[2021/04/04 17:18:28] root INFO:         out_channels : 256
[2021/04/04 17:18:28] root INFO:     Transform : None
[2021/04/04 17:18:28] root INFO:     algorithm : DB
[2021/04/04 17:18:28] root INFO:     model_type : det
[2021/04/04 17:18:28] root INFO: Eval : 
[2021/04/04 17:18:28] root INFO:     dataset : 
[2021/04/04 17:18:28] root INFO:         data_dir : ../work/LiquorBrand/det/imgs
[2021/04/04 17:18:28] root INFO:         label_file_list : ['../work/LiquorBrand/det/Label.txt']
[2021/04/04 17:18:28] root INFO:         name : SimpleDataSet
[2021/04/04 17:18:28] root INFO:         transforms : 
[2021/04/04 17:18:28] root INFO:             DecodeImage : 
[2021/04/04 17:18:28] root INFO:                 channel_first : False
[2021/04/04 17:18:28] root INFO:                 img_mode : BGR
[2021/04/04 17:18:28] root INFO:             DetLabelEncode : None
[2021/04/04 17:18:28] root INFO:             DetResizeForTest : None
[2021/04/04 17:18:28] root INFO:             NormalizeImage : 
[2021/04/04 17:18:28] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/04/04 17:18:28] root INFO:                 order : hwc
[2021/04/04 17:18:28] root INFO:                 scale : 1./255.
[2021/04/04 17:18:28] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/04/04 17:18:28] root INFO:             ToCHWImage : None
[2021/04/04 17:18:28] root INFO:             KeepKeys : 
[2021/04/04 17:18:28] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2021/04/04 17:18:28] root INFO:     loader : 
[2021/04/04 17:18:28] root INFO:         batch_size_per_card : 1
[2021/04/04 17:18:28] root INFO:         drop_last : False
[2021/04/04 17:18:28] root INFO:         num_workers : 2
[2021/04/04 17:18:28] root INFO:         shuffle : False
[2021/04/04 17:18:28] root INFO: Global : 
[2021/04/04 17:18:28] root INFO:     cal_metric_during_train : False
[2021/04/04 17:18:28] root INFO:     checkpoints : None
[2021/04/04 17:18:28] root INFO:     debug : False
[2021/04/04 17:18:28] root INFO:     distributed : False
[2021/04/04 17:18:28] root INFO:     epoch_num : 1200
[2021/04/04 17:18:28] root INFO:     eval_batch_step : [3000, 2000]
[2021/04/04 17:18:28] root INFO:     infer_img : doc/imgs_en/img_10.jpg
[2021/04/04 17:18:28] root INFO:     load_static_weights : False
[2021/04/04 17:18:28] root INFO:     log_smooth_window : 20
[2021/04/04 17:18:28] root INFO:     pretrained_model : ./pretrained_models/ch_ppocr_server_v2.0_det_train/best_accuracy
[2021/04/04 17:18:28] root INFO:     print_batch_step : 2
[2021/04/04 17:18:28] root INFO:     save_epoch_step : 1200
[2021/04/04 17:18:28] root INFO:     save_inference_dir : None
[2021/04/04 17:18:28] root INFO:     save_model_dir : ./output/ch_db_res18/
[2021/04/04 17:18:28] root INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2021/04/04 17:18:28] root INFO:     use_gpu : True
[2021/04/04 17:18:28] root INFO:     use_visualdl : False
[2021/04/04 17:18:28] root INFO: Loss : 
[2021/04/04 17:18:28] root INFO:     alpha : 5
[2021/04/04 17:18:28] root INFO:     balance_loss : True
[2021/04/04 17:18:28] root INFO:     beta : 10
[2021/04/04 17:18:28] root INFO:     main_loss_type : DiceLoss
[2021/04/04 17:18:28] root INFO:     name : DBLoss
[2021/04/04 17:18:28] root INFO:     ohem_ratio : 3
[2021/04/04 17:18:28] root INFO: Metric : 
[2021/04/04 17:18:28] root INFO:     main_indicator : hmean
[2021/04/04 17:18:28] root INFO:     name : DetMetric
[2021/04/04 17:18:28] root INFO: Optimizer : 
[2021/04/04 17:18:28] root INFO:     beta1 : 0.9
[2021/04/04 17:18:28] root INFO:     beta2 : 0.999
[2021/04/04 17:18:28] root INFO:     lr : 
[2021/04/04 17:18:28] root INFO:         learning_rate : 0.001
[2021/04/04 17:18:28] root INFO:         name : Cosine
[2021/04/04 17:18:28] root INFO:         warmup_epoch : 2
[2021/04/04 17:18:28] root INFO:     name : Adam
[2021/04/04 17:18:28] root INFO:     regularizer : 
[2021/04/04 17:18:28] root INFO:         factor : 0
[2021/04/04 17:18:28] root INFO:         name : L2
[2021/04/04 17:18:28] root INFO: PostProcess : 
[2021/04/04 17:18:28] root INFO:     box_thresh : 0.6
[2021/04/04 17:18:28] root INFO:     max_candidates : 1000
[2021/04/04 17:18:28] root INFO:     name : DBPostProcess
[2021/04/04 17:18:28] root INFO:     thresh : 0.3
[2021/04/04 17:18:28] root INFO:     unclip_ratio : 1.5
[2021/04/04 17:18:28] root INFO: Train : 
[2021/04/04 17:18:28] root INFO:     dataset : 
[2021/04/04 17:18:28] root INFO:         data_dir : None
[2021/04/04 17:18:28] root INFO:         label_file_list : [None]
[2021/04/04 17:18:28] root INFO:         name : SimpleDataSet
[2021/04/04 17:18:28] root INFO:         ratio_list : [1.0]
[2021/04/04 17:18:28] root INFO:         transforms : 
[2021/04/04 17:18:28] root INFO:             DecodeImage : 
[2021/04/04 17:18:28] root INFO:                 channel_first : False
[2021/04/04 17:18:28] root INFO:                 img_mode : BGR
[2021/04/04 17:18:28] root INFO:             DetLabelEncode : None
[2021/04/04 17:18:28] root INFO:             IaaAugment : 
[2021/04/04 17:18:28] root INFO:                 augmenter_args : 
[2021/04/04 17:18:28] root INFO:                     args : 
[2021/04/04 17:18:28] root INFO:                         p : 0.5
[2021/04/04 17:18:28] root INFO:                     type : Fliplr
[2021/04/04 17:18:28] root INFO:                     args : 
[2021/04/04 17:18:28] root INFO:                         rotate : [-10, 10]
[2021/04/04 17:18:28] root INFO:                     type : Affine
[2021/04/04 17:18:28] root INFO:                     args : 
[2021/04/04 17:18:28] root INFO:                         size : [0.5, 3]
[2021/04/04 17:18:28] root INFO:                     type : Resize
[2021/04/04 17:18:28] root INFO:             EastRandomCropData : 
[2021/04/04 17:18:28] root INFO:                 keep_ratio : True
[2021/04/04 17:18:28] root INFO:                 max_tries : 50
[2021/04/04 17:18:28] root INFO:                 size : [960, 960]
[2021/04/04 17:18:28] root INFO:             MakeBorderMap : 
[2021/04/04 17:18:28] root INFO:                 shrink_ratio : 0.4
[2021/04/04 17:18:28] root INFO:                 thresh_max : 0.7
[2021/04/04 17:18:28] root INFO:                 thresh_min : 0.3
[2021/04/04 17:18:28] root INFO:             MakeShrinkMap : 
[2021/04/04 17:18:28] root INFO:                 min_text_size : 8
[2021/04/04 17:18:28] root INFO:                 shrink_ratio : 0.4
[2021/04/04 17:18:28] root INFO:             NormalizeImage : 
[2021/04/04 17:18:28] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/04/04 17:18:28] root INFO:                 order : hwc
[2021/04/04 17:18:28] root INFO:                 scale : 1./255.
[2021/04/04 17:18:28] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/04/04 17:18:28] root INFO:             ToCHWImage : None
[2021/04/04 17:18:28] root INFO:             KeepKeys : 
[2021/04/04 17:18:28] root INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2021/04/04 17:18:28] root INFO:     loader : 
[2021/04/04 17:18:28] root INFO:         batch_size_per_card : 8
[2021/04/04 17:18:28] root INFO:         drop_last : False
[2021/04/04 17:18:28] root INFO:         num_workers : 4
[2021/04/04 17:18:28] root INFO:         shuffle : True
[2021/04/04 17:18:28] root INFO: train with paddle 2.0.1 and device CUDAPlace(0)
[2021/04/04 17:18:28] root INFO: Initialize indexs of datasets:['../work/LiquorBrand/det/Label.txt']
W0404 17:18:28.367261  2105 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0404 17:18:28.372813  2105 device_context.cc:372] device: 0, cuDNN Version: 7.6.
[2021/04/04 17:18:33] root INFO: load pretrained model from ['./pretrained_models/ch_ppocr_server_v2.0_det_train/best_accuracy']
eval model::   2%|▌                              | 1/56 [00:00<00:33,  1.63it/s]Traceback (most recent call last):
  File "tools/eval.py", line 71, in <module>
    main()
  File "tools/eval.py", line 63, in main
    eval_class, use_srn)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 351, in eval
    post_result = post_process_class(preds, batch[1])
  File "/home/aistudio/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 153, in __call__
    src_w, src_h)
  File "/home/aistudio/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 85, in boxes_from_bitmap
    np.round(box[:, 1] / height * dest_height), 0, dest_height)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid   1. If run DataLoader by DataLoader.from_generator(...), queue capacity is set by from_generator(..., capacity=xx, ...).
  2. If run DataLoader by DataLoader(dataset, ...), queue capacity is set as 2 times of the max value of num_workers and len(places).
  3. If run by DataLoader(dataset, ..., use_shared_memory=True), set use_shared_memory=False for not using shared memory.) exited is killed by signal: 2168.
  It may be caused by insufficient shared storage space. This problem usually occurs when using docker as a development environment.
  Please use command `df -h` to check the storage space of `/dev/shm`. Shared storage space needs to be greater than (DataLoader Num * DataLoader queue capacity * 1 batch data size).
  You can solve this problem by increasing the shared storage space or reducing the queue capacity appropriately.
Bus error (at /paddle/paddle/fluid/imperative/data_loader.cc:161)

**Comment by li26338710** [comment]
遇到了同样的问题  是否可以通过改变训练时的image shape 解决呢?

**Comment by zhaoyantao-murray** [comment]
> 遇到了同样的问题 是否可以通过改变训练时的image shape 解决呢?

把train和eval中的num_works设置为0即可。

**Comment by qiujian1232** [comment]
可以看看这个
https://github.com/PaddlePaddle/PaddleOCR/issues/3297#issuecomment-890957107
修改 xxx/paddle/fluid/dataloader/dataloader_iter.py 文件相关代码

**Comment by onenerve** [comment]
请问这个问题怎样解决的呢？

**Comment by leoterry-ulrica** [comment]
> > 遇到了同样的问题 是否可以通过改变训练时的image shape 解决呢?
> 
> 把train和eval中的num_works设置为0即可。

果然有效~thx
