### ISSUE TITLE
训练文字检测模型报错

### ISSUE THREAD

**Issue by yiyi99** [PaddlePaddle/PaddleOCR#1691]
ubuntu下执行：python3 tools/train.py -c  configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml
在保存best_accuracy出错：
eval model:: 100%|################################################| 270/270 [01:54<00:00,  2.36it/s]
[2021/01/08 04:44:00] root INFO: cur metirc, precision: 0.5886761032472939, recall: 0.5409334353481254, hmean: 0.5637958532695375, fps: 3.1480363326190743
[2021/01/08 04:44:00] root INFO: save best model is to ./output/ch_db_mv3/best_accuracy
[2021/01/08 04:44:00] root INFO: best metirc, hmean: 0.5637958532695375, start_epoch: 442, precision: 0.5886761032472939, recall: 0.5409334353481254, fps: 3.1480363326190743, best_epoch: 589
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/PaddleOCR/tools/program.py", line 198, in train
    loss = loss_class(preds, batch)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/PaddleOCR/ppocr/losses/det_db_loss.py", line 58, in forward
    label_shrink_mask)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/PaddleOCR/ppocr/losses/det_basic_loss.py", line 89, in forward
    min(negative.sum(), positive_count * self.negative_ratio))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/math_op_patch.py", line 238, in __impl__
    return math_op(self, other_var, 'axis', axis)
SystemError: (Fatal) Operator greater_than raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorLaunchOutOfResources: too many resources requested for launch. (at /paddle/paddle/fluid/imperative/tracer.cc:98)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
请问这是什么原因啊？谢谢。

**Comment by LDOUBLEV** [comment]
好像是保存模型的时候显存不够用了，你的显卡内存是足够的吗

**Comment by LDOUBLEV** [comment]
重新训练下，看能否复现，建议使用Paddle2.0rc1版本的paddle
