### ISSUE TITLE
tensor 是不是有最小限制，在利用paddleocr预测时，图片过小，会出错

### ISSUE THREAD

**Issue by hudielv** [PaddlePaddle/PaddleOCR#1702]
下面是在paddle2rc1的cpu环境下的错误，然后我把图片调大就不会出错了，是不是tensor有最小的限制还是什么    

"""
    Traceback (most recent call last):
      File "/opt/lvym/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "./ocr_basic_service/ocr_pre/predict.py", line 204, in image_parse
      File "./ocr_basic_service/paddown/paddleocr.py", line 300, in ocr
      File "./ocr_basic_service/paddown/tools/infer/predict_system.py", line 108, in __call__
      File "./ocr_basic_service/paddown/tools/infer/predict_rec.py", line 105, in __call__
    ValueError: In user code:
    
        File "tools/export_model.py", line 75, in <module>
          main()
        File "tools/export_model.py", line 70, in main
          paddle.jit.save(model, save_path)
        File "<decorator-gen-60>", line 2, in save
          
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
          return wrapped_func(*args, **kwargs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
          return func(*args, **kwargs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
          concrete_program = static_func.concrete_program
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
          concrete_program, _ = self.get_concrete_program(*input_spec)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
          concrete_program, partial_program_layer = self._program_cache[cache_key]
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
          self._caches[item] = self._build_once(item)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
          class_instance=cache_key.class_instance)
        File "<decorator-gen-58>", line 2, in from_func_spec
          
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
          return wrapped_func(*args, **kwargs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
          return func(*args, **kwargs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
          outputs = static_func(*inputs)
        File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/architectures/base_model.py", line 74, in forward
          x = self.backbone(x)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
          outputs = self.forward(*inputs, **kwargs)
        File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/backbones/rec_resnet_vd.py", line 279, in forward
          y = self.conv1_1(inputs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
          outputs = self.forward(*inputs, **kwargs)
        File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/backbones/rec_resnet_vd.py", line 67, in forward
          y = self._conv(inputs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
          outputs = self.forward(*inputs, **kwargs)
        File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 644, in forward
          use_cudnn=self._use_cudnn)
        File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 144, in _conv_nd
          type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
          return self.main_program.current_block().append_op(*args, **kwargs)
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2849, in append_op
          attrs=kwargs.get("attrs", None))
        File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1934, in __init__
          for frame in traceback.extract_stack():
    
        InvalidArgumentError: The requested memory size is less than the memory size of Tensor. But received requested memory size is d131072 memory size of Tensor is 524288.
          [Hint: Expected requested_size >= size, but received requested_size:131072 < size:524288.] (at /paddle/paddle/fluid/framework/tensor.cc:65)
          [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
          [operator < conv2d > error]

**Comment by LDOUBLEV** [comment]
是多大的图像预测时会报这个错？

**Comment by hudielv** [comment]
图像为（高，宽、通道）：
(118,640,3)
(29,202,3)
(39,449,3)
会报错

**Comment by hudielv** [comment]
我是多进程在调用paddleocr的api时，偶现会出错
出错一回，再次调用api，就不会出错了
1）我试了把enable_mkldnn设成Fasle，就没问题了，但速度很慢
2）或者把 config.set_mkldnn_cache_capacity()设置为1（之前为6），就没问题了
但不知道以后有没有问题
所以，定位是mkldnn出错的，但是不知道是为什么

**Comment by LDOUBLEV** [comment]
> 我是多进程在调用paddleocr的api时，偶现会出错
> 出错一回，再次调用api，就不会出错了
> 1）我试了把enable_mkldnn设成Fasle，就没问题了，但速度很慢
> 2）或者把 config.set_mkldnn_cache_capacity()设置为1（之前为6），就没问题了
> 但不知道以后有没有问题
> 所以，定位是mkldnn出错的，但是不知道是为什么

好的，感谢反馈

**Comment by hudielv** [comment]
这个解决了么？是什么原因呢？

**Comment by hudielv** [comment]
config.set_mkldnn_cache_capacity()设置成1，也会有问题？

**Comment by tink2123** [comment]
2.1分支的代码已解决这个问题，可以更新下paddle版本并使用最新代码预测。

**Comment by hudielv** [comment]
好的，谢谢
