### ISSUE TITLE
PPOCRLabel 安装问题求助

### ISSUE THREAD

**Issue by sagisaga** [PaddlePaddle/PaddleOCR#1708]
按照官网流程安装，尝试运行PPOCRLabel时出错，命令 python3 PPOCRLabel.py --lang ch
大家谁遇到这个错误，求指一条明路

出错信息：

Traceback (most recent call last):
  File "PPOCRLabel.py", line 34, in <module>
    from paddleocr import PaddleOCR
  File "../paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "../tools/infer/predict_system.py", line 29, in <module>
    import tools.infer.predict_rec as predict_rec
  File "../tools/infer/predict_rec.py", line 30, in <module>
    from ppocr.postprocess import build_post_process
  File "/Users/zhoujingchao/Work/chengxin/ppocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/Users/zhoujingchao/Work/chengxin/ppocr/paddleocr.py", line 29, in <module>
    from ppocr.utils.logging import get_logger
ModuleNotFoundError: No module named 'ppocr.utils'

**Comment by Evezerest** [comment]
It seems like PaddleOCR is not installed very well

**Comment by Young1993** [comment]
你可以去看 ppocr.utils文件夹下没有logging文件，你用git clone https://github.com/PaddlePaddle/PaddleOCR重新下载一次就可以了

**Comment by sagisaga** [comment]
解决了，是Python版本的问题，有的版本不支持代码中的目录方式。

**Comment by jefferyvvv** [comment]
> 解决了，是Python版本的问题，有的版本不支持代码中的目录方式。

怎么解决的，我也遇到了这个问题

**Comment by smalllyingspinach** [comment]
同问，是python3.8版本吗？
