### ISSUE TITLE
python.exe /tools/train.py -c ../configs/det/det_mv3_db.yml

### ISSUE THREAD

**Issue by Jasonxgw** [PaddlePaddle/PaddleOCR#171]
2020-06-09 22:54:13,418-INFO: {'Global': {'algorithm': 'DB', 'use_gpu': True, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': '../output/det_db/', 'save_epoch_step': 200, 'eval_batch_step': 5000, 'train_batch_size_per_card': 16, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': '../configs/det/det_db_icdar15_reader.yml', 'pretrain_weights': '../pretrain_models/MobileNetV3_large_x0_5_pretrained/', 'checkpoints': None, 'save_res_path': '../output/det_db/predicts_db.txt', 'save_inference_dir': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 96, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.7, 'max_candidates': 1000, 'unclip_ratio': 2.0}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 8, 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/train_icdar2015_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'infer_img': None, 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280], 'do_eval': True}}
3 640 640
3 640 640
2020-06-09 22:54:16,228-INFO: places would be ommited when DataLoader is not iterable
2020-06-09 22:54:18,197-INFO: Loading parameters from ../pretrain_models/MobileNetV3_large_x0_5_pretrained/...
2020-06-09 22:54:18,197-WARNING: ../pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-09 22:54:18,197-WARNING: ../pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 1865, in load_program_state
    filename=file_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 793, in load_vars
    executor.run(load_prog)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 838, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 912, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 773, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 1865, in load_program_state
    filename=file_name)
  File "D:\Downloads\PaddleOCR-develop\ppocr\utils\save_load.py", line 57, in _load_state
    state = fluid.io.load_program_state(path)
  File "D:\Downloads\PaddleOCR-develop\ppocr\utils\save_load.py", line 79, in load_params
    state = _load_state(path)
  File "D:\Downloads\PaddleOCR-develop\ppocr\utils\save_load.py", line 121, in init_model
    load_params(exe, program, path)
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 76, in main
    init_model(config, train_program, exe)
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 98, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor version 1974636042 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:1974636042 != 0U:0.] at (D:\1.7.2\paddle\paddle\fluid\framework\lod_tensor.cc:287)
  [operator < load > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 98, in <module>
    main()
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 76, in main
    init_model(config, train_program, exe)
  File "D:\Downloads\PaddleOCR-develop\ppocr\utils\save_load.py", line 121, in init_model
    load_params(exe, program, path)
  File "D:\Downloads\PaddleOCR-develop\ppocr\utils\save_load.py", line 79, in load_params
    state = _load_state(path)
  File "D:\Downloads\PaddleOCR-develop\ppocr\utils\save_load.py", line 57, in _load_state
    state = fluid.io.load_program_state(path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 1868, in load_program_state
    "Failed to load model file , please make sure model file is saved with the "
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars
W0609 22:54:16.984372 14860 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0609 22:54:16.991372 14860 device_context.cc:245] device: 0, cuDNN Version: 7.6.
![Uploading ce8172676e3b83745f1701ae1552ed2.png…]()
![2aa1d206d500908ea60e56f70a32114](https://user-images.githubusercontent.com/31821866/84164033-a9e5f580-aaa4-11ea-9227-7c9a5277d970.png)

**Comment by tink2123** [comment]
please change 
`pretrain_weights:  ./pretrain_models/MobileNetV3_large_x0_5_pretrained/`
to
`pretrain_weights:  ./pretrain_models/MobileNetV3_large_x0_5_pretrained/best_accuracy`

**Comment by Jasonxgw** [comment]
又报了以下错误:
2020-06-10 11:30:06,092-INFO: {'Global': {'algorithm': 'DB', 'use_gpu': True, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': '../output/det_db/', 'save_epoch_step': 200, 'eval_batch_step': 5000, 'train_batch_size_per_card': 16, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': '../configs/det/det_db_icdar15_reader.yml', 'pretrain_weights': '../pretrain_models/MobileNetV3_large_x0_5_pretrained/best_accuracy', 'checkpoints': None, 'save_res_path': '../output/det_db/predicts_db.txt', 'save_inference_dir': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 96, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.7, 'max_candidates': 1000, 'unclip_ratio': 2.0}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 8, 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/train_icdar2015_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'infer_img': None, 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280], 'do_eval': True}}
3 640 640
3 640 640
2020-06-10 11:30:08,793-INFO: places would be ommited when DataLoader is not iterable
2020-06-10 11:30:10,728-INFO: Loading parameters from ../pretrain_models/MobileNetV3_large_x0_5_pretrained/best_accuracy...
2020-06-10 11:30:10,795-WARNING: variable batch_norm_50.b_0 not used
2020-06-10 11:30:10,795-WARNING: variable conv2_b_attr not used
2020-06-10 11:30:10,795-WARNING: variable batch_norm_49.w_1 not used
2020-06-10 11:30:10,795-WARNING: variable batch_norm_49.w_2 not used
2020-06-10 11:30:10,795-WARNING: variable batch_norm_50.w_0 not used
2020-06-10 11:30:10,795-WARNING: variable batch_norm_48.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_55.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_transpose_3.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_49.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_transpose_0.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_49.b_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_50.w_2 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_47.b_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_48.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_48.w_1 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_49.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_53.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_47.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_48.b_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_50.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_48.w_2 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_47.w_2 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_47.w_1 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_transpose_1.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_54.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_transpose_2.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_51.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_57.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_52.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable conv2d_56.w_0 not used
2020-06-10 11:30:10,796-WARNING: variable batch_norm_50.w_1 not used
2020-06-10 11:30:10,854-INFO: Finish initing model from ../pretrain_models/MobileNetV3_large_x0_5_pretrained/best_accuracy
multiprocess is not fully compatible with Windows.num_workers will be 1.
2020-06-10 11:30:11,170-WARNING: Your reader has raised an exception!
Traceback (most recent call last):
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 98, in <module>
    main()
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 90, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "D:\Downloads\PaddleOCR-develop\tools\program.py", line 240, in train_eval_det_run
    return_numpy=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 850, in _run_impl
    return_numpy=return_numpy)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 684, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\reader.py", line 733, in _init_non_iterable
    outputs={'Out': self._feed_list})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\reader.py", line 646, in __init__
    self._init_non_iterable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\reader.py", line 280, in from_generator
    iterable, return_list)
  File "D:\Downloads\PaddleOCR-develop\ppocr\modeling\architectures\det_model.py", line 97, in create_feed
    iterable=False)
  File "D:\Downloads\PaddleOCR-develop\ppocr\modeling\architectures\det_model.py", line 110, in __call__
    image, labels, loader = self.create_feed(mode)
  File "D:\Downloads\PaddleOCR-develop\tools\program.py", line 171, in build
    dataloader, outputs = model(mode=mode)
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 52, in main
    config, train_program, startup_program, mode='train')
  File "D:/Downloads/PaddleOCR-develop/tools/train.py", line 98, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.7.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
W0610 11:30:09.528388 13396 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0610 11:30:09.535392 13396 device_context.cc:245] device: 0, cuDNN Version: 7.6.
I0610 11:30:10.886363 13396 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0610 11:30:10.937362 13396 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0610 11:30:11.065394 13396 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0610 11:30:11.097362 13396 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0

**Comment by Jasonxgw** [comment]
我用了以下的数据集，是我用错了吗？
![image](https://user-images.githubusercontent.com/31821866/84224246-8eafd000-ab0e-11ea-8e9b-dbfc956279aa.png)
![image](https://user-images.githubusercontent.com/31821866/84224430-1990ca80-ab0f-11ea-9f0e-0f4222a08654.png)

**Comment by Jasonxgw** [comment]
![dfdb0538972402bba8e1fc6e7ced04a](https://user-images.githubusercontent.com/31821866/84224672-b81d2b80-ab0f-11ea-90d1-f2b5934b7a63.png)
![c420d06733e2958320bdb4b94ea8f34](https://user-images.githubusercontent.com/31821866/84224675-b94e5880-ab0f-11ea-9af1-6a2270a16b6f.png)

**Comment by LDOUBLEV** [comment]
@Jasonxgw  MobileNetV3_large_x0_5_pretrained文件是 在imagenet上训练好的backbone的参数文件，加载预训练模型时，设置配置文件中的Global.pretrain_weights 参数为解压好的预训练模型路径。

注意：建议使用tar xf MobileNetV3_large_x0_5_pretrained.tar 命令解压，正确解压后，应该会有一个MobileNetV3_large_x0_5_pretrained文件夹，文件夹下有很多以网络参数命名的小文件。win上解压工具解压出来的如果是单个文件，就无法正确加载

**Comment by SixGodGG** [comment]
我想试试CPU训练，但报错了，我觉得这个预训练模型还是加载的不对，已经按照你的方式加载了。
@LDOUBLEV 
PS D:\PythonAPI\Python37> python E:/GitHub/PaddleOCR/tools/train.py -c E:/GitHub/PaddleOCR/configs/det/det_mv3_db.yml
2020-06-10 16:32:42,103-INFO: {'Global': {'algorithm': 'DB', 'use_gpu': False, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': 'E:/GitHub/PaddleOCR/output/det_db/', 'save_epoch_step': 200, 'eval_batch_step': 5000, 'train_batch_size_per_card': 16, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': 'E:/GitHub/PaddleOCR/configs/det/det_db_icdar15_reader.yml', 'pretrain_weights': 'E:/GitHub/PaddleOCR/pretrain_models/MobileNetV3_large_x0_5_pretrained/', 'checkpoints': None, 'save_res_path': 'E:/GitHub/PaddleOCR/output/det_db/predicts_db.txt', 'save_inference_dir': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 96, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.7, 'max_candidates': 1000, 'unclip_ratio': 2.0}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 2, 'img_set_dir': 'E:/GitHub/PaddleOCR/train_data/', 'label_file_path': 'E:/GitHub/PaddleOCR/train_data/train_icdar2015_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': 'E:/GitHub/PaddleOCR/train_data/', 'label_file_path': 'E:/GitHub/PaddleOCR/train_data/test_icdar2015_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'infer_img': None, 'img_set_dir': 'E:/GitHub/PaddleOCR/train_data/ch4_test_images/', 'label_file_path': 'E:/GitHub/PaddleOCR/train_data/ch4_test_images/test_icdar2015_label.txt', 'test_image_shape': [736, 1280], 'do_eval': True}}
False
3 640 640
3 640 640
2020-06-10 16:32:52,470-INFO: places would be ommited when DataLoader is not iterable
E:/GitHub/PaddleOCR/pretrain_models/MobileNetV3_large_x0_5_pretrained/
2020-06-10 16:32:52,615-INFO: Loading parameters from E:/GitHub/PaddleOCR/pretrain_models/MobileNetV3_large_x0_5_pretrained/...
2020-06-10 16:32:52,616-WARNING: E:/GitHub/PaddleOCR/pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-10 16:32:52,616-WARNING: E:/GitHub/PaddleOCR/pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-10 16:32:52,844-INFO: Finish initing model from E:/GitHub/PaddleOCR/pretrain_models/MobileNetV3_large_x0_5_pretrained/
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=12 # for example, set CPU_NUM as number of physical CPU core which is 12.

!!! The default number of CPU_NUM=1.
multiprocess is not fully compatible with Windows.num_workers will be 1.
I0610 16:32:52.899940  9384 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0610 16:32:52.950803  9384 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0610 16:32:53.071481  9384 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0610 16:32:53.102398  9384 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
Traceback (most recent call last):
  File "E:/GitHub/PaddleOCR/tools/train.py", line 112, in <module>
    main()
  File "E:/GitHub/PaddleOCR/tools/train.py", line 104, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "E:\GitHub\PaddleOCR\tools\program.py", line 238, in train_eval_det_run
    return_numpy=False)
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "D:\pythonAPI\Python37\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "D:\pythonAPI\Python37\Lib\site-packages\paddle\fluid\layers\tensor.py", line 286, in concat
    type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
  File "E:\GitHub\PaddleOCR\ppocr\modeling\heads\det_db_head.py", line 203, in __call__
    input=[shrink_maps, threshold_maps, binary_maps], axis=1)
  File "E:\GitHub\PaddleOCR\ppocr\modeling\architectures\det_model.py", line 113, in __call__
    predicts = self.head(conv_feas, mode)
  File "E:\GitHub\PaddleOCR\tools\program.py", line 169, in build
    dataloader, outputs = model(mode=mode)
  File "E:/GitHub/PaddleOCR/tools/train.py", line 66, in main
    config, train_program, startup_program, mode='train')
  File "E:/GitHub/PaddleOCR/tools/train.py", line 112, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Fail to allocate CPU memory: size = 524288000 .
  [Hint: p should not be null.] at (D:\1.7.0\paddle\paddle\fluid\memory\detail\system_allocator.cc:61)
  [operator < concat > error]

**Comment by LDOUBLEV** [comment]
@SixGodGG 你这个是内存不足的问题，建议把batchsize 调小，具体是改配置文件里的 train_batch_size_per_card参数
