### ISSUE TITLE
关于:AttributeError: module 'paddle.distributed' has no attribute 'get_rank'

### ISSUE THREAD

**Issue by Cllan-z** [PaddlePaddle/PaddleOCR#1721]
环境 Python3.8
安装: python -m pip install paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple
         python -m pip install paddleocr

from paddleocr import PaddleOCR

def init():
    ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
    img_path = './image/20210112190106.bmp'
    result = ocr.ocr(img_path, cls=True)
    for line in result:
        print(line)

if __name__ == "__main__":
    init()

错误:
D:\Code\CC\venv\Scripts\python.exe D:/Code/CC/paddleOCR.py
Traceback (most recent call last):
  File "D:/Code/CC/paddleOCR.py", line 1, in <module>
    from paddleocr import PaddleOCR
  File "D:\Code\CC\venv\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "D:\Code\CC\venv\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "D:\Code\CC\venv\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 27, in <module>
    import tools.infer.predict_rec as predict_rec
  File "D:\Code\CC\venv\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 33, in <module>
    logger = get_logger()
  File "D:\Code\CC\venv\lib\site-packages\paddleocr\ppocr\utils\logging.py", line 61, in get_logger
    if dist.get_rank() == 0:
AttributeError: module 'paddle.distributed' has no attribute 'get_rank'

**Comment by zouxiaoshi** [comment]
if you are installing the CPU version of Paddle, use pip install paddlepaddle==2.0.0rc1 other than pip install paddlepaddle.
The version 2.0.0rc1 works for me.
