### ISSUE TITLE
StyleText批量生成图片报错

### ISSUE THREAD

**Issue by sjtugzx** [PaddlePaddle/PaddleOCR#1743]
![image](https://user-images.githubusercontent.com/20066885/104560519-f5870000-5680-11eb-9edd-95b982cd4c9e.png)

**Comment by littletomatodonkey** [comment]
你好，应该是标注文件的格式问题，每一行中应该包含图片路径和label，用`\t`分割开，你这个可以打印一下split之后的结果，看下split成了几份

**Comment by meonline-f** [comment]
使用原例子未做更改，批量生成图片报错
Traceback (most recent call last):
  File "D:\workspace\python\develope\PaddleOCR\StyleText\tools\synth_dataset.py", line 31, in <module>
    synth_dataset()
  File "D:\workspace\python\develope\PaddleOCR\StyleText\tools\synth_dataset.py", line 26, in synth_dataset
    dataset_synthesiser = DatasetSynthesiser()
  File "D:\workspace\python\develope\PaddleOCR\StyleText\engine\synthesisers.py", line 58, in __init__
    self.style_sampler = style_samplers.DatasetSampler(self.config)
  File "D:\workspace\python\develope\PaddleOCR\StyleText\engine\style_samplers.py", line 27, in __init__
    label_raw = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 63: illegal multibyte sequence
