### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by 554518983** [PaddlePaddle/PaddleOCR#1777]
paddleOCR版本：2.0rc1
python版本：3.7
系统：windows
没有使用docker
----------------------------------------------------------------------------------------------------------------------------------------------
paddle安装成功
import paddle.fluid
paddle.fluid.install_check.run_check()
测试成功，输出了Your Paddle Fluid is installed successfully
---------------------------------------------------------------------------------------------------------------------------------------
运行官方示例：
python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
-----------------------------------------------------------------------------------------------------------------------------------------
报错：
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 30, in <module>
    import tools.infer.predict_det as predict_det
  File "D:\py_workspace\PaddleOCR\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "D:\py_workspace\PaddleOCR\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "D:\py_workspace\PaddleOCR\ppocr\data\imaug\__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "D:\py_workspace\PaddleOCR\ppocr\data\imaug\iaa_augment.py", line 20, in <module>
    import imgaug
  File "D:\py_workspace\env\orcl_2.0rc1\lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "D:\py_workspace\env\orcl_2.0rc1\lib\site-packages\imgaug\imgaug.py", line 22, in <module>
    import skimage.draw
  File "D:\py_workspace\env\orcl_2.0rc1\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "D:\py_workspace\env\orcl_2.0rc1\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "D:\py_workspace\env\orcl_2.0rc1\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: 找不到指定的模块。

**Comment by tink2123** [comment]
参考：https://github.com/PaddlePaddle/PaddleOCR/issues/1567
