### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_fetch_list'

### ISSUE THREAD

**Issue by eashow** [PaddlePaddle/PaddleOCR#1800]
E:\AI\classify>python infer.py class5
Traceback (most recent call last):
  File "infer.py", line 25, in <module>
    exe.run(fluid.default_startup_program())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1108, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1106, in run
    return_merged=return_merged)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1236, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1330, in _run_program
    arr = scope.find_var(fetch_var_name).get_fetch_list()
AttributeError: 'NoneType' object has no attribute 'get_fetch_list'

用 paddlepaddle1.8的时候是正常的，现在改为2.0就报这个错了！

**Comment by WenmuZhou** [comment]
你好，静态图版本是建议使用1.8的paddle的
