### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'max_batch_size' and AttributeError: 'Namespace' object has no attribute 'use_fp16'

### ISSUE THREAD

**Issue by vman-tcin** [PaddlePaddle/PaddleOCR#1802]
## Steps to reproduce
1. Build from source `branch release/2.0-rc1-0` using py36
2. Install the built wheel
3. Run `paddleocr --image_dir img_10.jpg --use_angle_cls true --lang en --gpu_mem 100 --use_tensorrt True`

## Error 1
```python
Traceback (most recent call last):
  File "/home/user/paddle/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 331, in main
    ocr_engine = PaddleOCR(**(args.__dict__))
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 269, in __init__
    super().__init__(postprocess_params)
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 39, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 96, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 120, in create_predictor
    if args.use_fp16 else AnalysisConfig.Precision.Float32,
AttributeError: 'Namespace' object has no attribute 'use_fp16'
```

## Error 2
```python
Traceback (most recent call last):
  File "/home/user/paddle/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 333, in main
    ocr_engine = PaddleOCR(**(args.__dict__))
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 271, in __init__
    super().__init__(postprocess_params)
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 39, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 96, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/home/user/paddle/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 121, in create_predictor
    max_batch_size=args.max_batch_size)
AttributeError: 'Namespace' object has no attribute 'max_batch_size'
```

These two are due to missing arguments in the parser in `paddleocr/paddleocr.py`. Adding the two arguments seems to fix the issue. Can I raise a PR?

**Comment by WenmuZhou** [comment]
fixed in latest code

**Comment by QuantumLiu** [comment]
> fixed in latest code

Same error, would you please tell me how to fix it in old code?
