### ISSUE TITLE
window下运行python tools/train.py -c configs/det/det_mv3_east.yml出错

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#1817]
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 68, in main
    model = build_model(config['Architecture'])
  File "E:\Users\PycharmProjects\PaddleOCR-dygraph\ppocr\modeling\architectures\__init__.py", line 23, in build_model
    module_class = BaseModel(config)
  File "E:\Users\PycharmProjects\PaddleOCR-dygraph\ppocr\modeling\architectures\base_model.py", line 52, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "E:\Users\PycharmProjects\PaddleOCR-dygraph\ppocr\modeling\backbones\__init__.py", line 35, in build_backbone
    module_class = eval(module_name)(**config)
  File "E:\Users\PycharmProjects\PaddleOCR-dygraph\ppocr\modeling\backbones\det_mobilenet_v3.py", line 106, in __init__
    name='conv1')
  File "E:\Users\PycharmProjects\PaddleOCR-dygraph\ppocr\modeling\backbones\det_mobilenet_v3.py", line 178, in __init__
    bias_attr=False)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\nn\layer\conv.py", line 623, in __init__
    data_format=data_format)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\nn\layer\conv.py", line 136, in __init__
    default_initializer=_get_default_param_initializer())
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\layers.py", line 390, in create_parameter
    default_initializer)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\layer_helper_base.py", line 366, in create_parameter
    "constructor of dygraph Layers".format(attr.name))
ValueError: parameter name [conv1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by WenmuZhou** [comment]
你好，拉一下最新代码试试，我这边刚刚没有复现你的问题

**Comment by hsyy673150343** [comment]
> 你好，拉一下最新代码试试，我这边刚刚没有复现你的问题

**Comment by hsyy673150343** [comment]
> 你好，拉一下最新代码试试，我这边刚刚没有复现你的问题

一直拉不成功
