### ISSUE TITLE
pdservering 推理问题libcrypto.so.10

### ISSUE THREAD

**Issue by foocker** [PaddlePaddle/PaddleOCR#1828]
This API will be deprecated later. Please do not use it
Traceback (most recent call last):
  File "ocr_rpc_server.py", line 120, in <module>
    ocr_service.init_rec()
  File "ocr_rpc_server.py", line 90, in init_rec
    self.text_system = TextSystemHelper(global_args)
  File "ocr_rpc_server.py", line 43, in __init__
    self.clas_client = Client()
  File "/usr/local/lib/python3.6/dist-packages/paddle_serving_client/__init__.py", line 136, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

环境： py3.6,按照pdservering readme.md。该文档在develop分支，paddlecor mobile_xx_2.0...

**Comment by MissPenguin** [comment]
pdserving目前还不支持使用2.0版模型哈，近期会完成适配，可以先用1.1的模型
