### ISSUE TITLE
出现新错误

### ISSUE THREAD

**Issue by hsyy673150343** [PaddlePaddle/PaddleOCR#1832]
你好，拉一下最新代码试试，我这边刚刚没有复现你的问题

_Originally posted by @WenmuZhou in https://github.com/PaddlePaddle/PaddleOCR/issues/1817#issuecomment-767284530_

Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "D:\OCR_PRO\hsyy-PaddleOCR-dygraph\PaddleOCR\tools\program.py", line 197, in train
    preds = model(images)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\OCR_PRO\hsyy-PaddleOCR-dygraph\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 74, in forward
    x = self.backbone(x)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\OCR_PRO\hsyy-PaddleOCR-dygraph\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3.py", line 151, in forward
    x = stage(x)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\container.py", line 86, in forward
    input = layer(input)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\OCR_PRO\hsyy-PaddleOCR-dygraph\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3.py", line 252, in forward
    x = self.mid_se(x)
  File "E:\Users\anaconda3\envs\Paddle_new_test\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\OCR_PRO\hsyy-PaddleOCR-dygraph\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3.py", line 285, in forward
    outputs = F.hardsigmoid(outputs, slope=0.2, offset=0.5)
TypeError: hardsigmoid() got an unexpected keyword argument 'slope'

**Comment by light1003** [comment]
遇到同样问题，一些函数有变更，更新最新代码或者手动改掉outputs = F.hardsigmoid(outputs, slope=0.2, offset=0.5)

**Comment by hsyy673150343** [comment]
我是直接改掉这个了发自我的华为手机-------- 原始邮件 --------发件人： light1003 <notifications@github.com>日期： 2021年1月27日周三 傍晚6:01收件人： PaddlePaddle/PaddleOCR <PaddleOCR@noreply.github.com>抄送： "13096337080@163.com" <18080166480@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleOCR] 出现新错误 (#1832)

遇到同样问题，一些函数有变更，更新最新代码或者手动改掉outputs = F.hardsigmoid(outputs, slope=0.2, offset=0.5)

**Comment by jimyho-msn** [comment]
hardsigmoid 函数参数改短了。

我改这样过了： outputs = F.hardsigmoid(outputs）
