### ISSUE TITLE
运行这句时python tools/train.py -c ../configs/det/det_mv3_db.yml

### ISSUE THREAD

**Issue by Jasonxgw** [PaddlePaddle/PaddleOCR#185]
我在mac上同一套代码和环境没有报错window报以下错误：
2020-06-11 15:32:26,348-INFO: {'Global': {'algorithm': 'DB', 'use_gpu': False, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': '../output/det_db', 'save_epoch_step': 200, 'eval_batch_step': 5000, 'train_batch_size_per_card': 2, 'test_batch_size_per_card': 2, 'image_shape': [3, 640, 640], 'reader_yml': '../configs/det/det_db_icdar15_reader.yml', 'pretrain_weights': '../pretrain_models/MobileNetV3_large_x0_5_pretrained/', 'checkpoints': None, 'save_res_path': '../output/det_db/predicts_db.txt', 'save_inference_dir': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 96, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.7, 'max_candidates': 1000, 'unclip_ratio': 2.0}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 8, 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/train_icdar2015_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'infer_img': None, 'img_set_dir': '../train_data/icdar2015/text_localization/', 'label_file_path': '../train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280], 'do_eval': True}}
3 640 640
3 640 640
2020-06-11 15:32:29,885-INFO: places would be ommited when DataLoader is not iterable
2020-06-11 15:32:30,041-INFO: Loading parameters from ../pretrain_models/MobileNetV3_large_x0_5_pretrained/...
2020-06-11 15:32:30,041-WARNING: ../pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-11 15:32:30,041-WARNING: ../pretrain_models/MobileNetV3_large_x0_5_pretrained/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-11 15:32:31,254-INFO: Finish initing model from ../pretrain_models/MobileNetV3_large_x0_5_pretrained/
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=6 # for example, set CPU_NUM as number of physical CPU core which is 6.

!!! The default number of CPU_NUM=1.
multiprocess is not fully compatible with Windows.num_workers will be 1.
2020-06-11 15:32:31,511-WARNING: Your reader has raised an exception!
Traceback (most recent call last):
  File "D:/Downloads/PaddleOCR-develop (1)/PaddleOCR-develop/tools/train.py", line 112, in <module>
    main()
  File "D:/Downloads/PaddleOCR-develop (1)/PaddleOCR-develop/tools/train.py", line 104, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "D:\Downloads\PaddleOCR-develop (1)\PaddleOCR-develop\tools\program.py", line 238, in train_eval_det_run
    return_numpy=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 850, in _run_impl
    return_numpy=return_numpy)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 684, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\reader.py", line 733, in _init_non_iterable
    outputs={'Out': self._feed_list})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\reader.py", line 646, in __init__
    self._init_non_iterable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\reader.py", line 280, in from_generator
    iterable, return_list)
  File "D:\Downloads\PaddleOCR-develop (1)\PaddleOCR-develop\ppocr\modeling\architectures\det_model.py", line 97, in create_feed
    iterable=False)
  File "D:\Downloads\PaddleOCR-develop (1)\PaddleOCR-develop\ppocr\modeling\architectures\det_model.py", line 110, in __call__
    image, labels, loader = self.create_feed(mode)
  File "D:\Downloads\PaddleOCR-develop (1)\PaddleOCR-develop\tools\program.py", line 169, in build
    dataloader, outputs = model(mode=mode)
  File "D:/Downloads/PaddleOCR-develop (1)/PaddleOCR-develop/tools/train.py", line 66, in main
    config, train_program, startup_program, mode='train')
  File "D:/Downloads/PaddleOCR-develop (1)/PaddleOCR-develop/tools/train.py", line 112, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.7.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
I0611 15:32:31.286535 19084 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0611 15:32:31.334564 19084 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0611 15:32:31.455535 19084 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0611 15:32:31.487565 19084 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
![image](https://user-images.githubusercontent.com/31821866/84358216-681a9380-abf9-11ea-92a3-11a17c123fe0.png)
mac下的结果
![{DD327CBA-BEF4-C313-3339-FF79660BD454}](https://user-images.githubusercontent.com/31821866/84358498-cf384800-abf9-11ea-8131-3a3b26ef05f7.jpg)

**Comment by tink2123** [comment]
请问在 mac 下也报错吗？看起来是数据读取相关的错误

**Comment by Jasonxgw** [comment]
mac是使用cpu训练，训练的结果是第二张图，运行一段时间后并没有停止运行；而且预训练模型和数据集我都下了好几遍了，不知道哪里出现了问题

**Comment by tink2123** [comment]
抱歉回复晚了～ 这个报错是因为**检测模型**在训练时，部分预处理中的opencv的操作不支持mac环境，因此不建议在mac上训练检测模型。抱歉给您带来困扰，或许可以尝试安装一个docker，在linux环境下试试？
识别模型在mac或windows上都可以训练，可以跑一个demo测试一下

**Comment by qiullv** [comment]
我在windows下运行这句训练命令时候，报错Error: Blocking queue is killed because the data reader raises an exception，请问这个怎么解决的呢
