### ISSUE TITLE
Text Recognition Model ch_ppocr_server_v2.0_det IndexError: list index out of range

### ISSUE THREAD

**Issue by chuk-yong** [PaddlePaddle/PaddleOCR#1852]
Using the default or ch_ppocr_mobile_v2.0_rec, both work but when I tried to use the server model, it gave me the "list index out of range" error.

It may due to nothing being recognised.  However, the detection did found 7 text boxes.
 
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
[2021/01/28 11:49:56] root INFO: dt_boxes num : 7, elapse : 1.3247952461242676
[2021/01/28 11:49:57] root INFO: cls num  : 7, elapse : 0.13612890243530273

I found it strange that the recognition result is worse than the default setting.

**Comment by tink2123** [comment]
Did you modify the dictionary? Please check if the model and dictionary are consistent

**Comment by chuk-yong** [comment]
No, I did not.  
How do I check the model vs the dictionary?

**Comment by tink2123** [comment]
Is it convenient to provide the command you executed

**Comment by chuk-yong** [comment]
import paddle
from paddleocr import PaddleOCR, draw_ocr
det_path ="./paddleocr/ch_ppocr_server_v2.0_det/ch_ppocr_server_v2.0_det_infer"
rec_path = "./paddleocr/ch_ppocr_server_v2.0_rec/ch_ppocr_server_v2.0_rec_infer"
ocr = PaddleOCR(use_angle_cls=True, lang='en', use_gpu=False, det_model_dir = det_path, rec_model_dir = rec_path)
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)

**Comment by flycrane01** [comment]
I've experienced the same issue. This is the picture I tried [https://ibb.co/cbnFcgN](url)

The mobile model recognized it well.
```
[[[[378.0, 63.0], [497.0, 63.0], [497.0, 109.0], [378.0, 109.0]], ('月光色', 0.9980741)], [[[486.0, 64.0], [648.0, 62.0], [649.0, 108.0], [487.0, 110.0]], ('女子香', 0.99479586)]]
```
But the server model gave an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 108, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 111, in __call__
    rec_result = self.postprocess_op(preds)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\ppocr\postprocess\rec_postprocess.py", line 112, in __call__
    text = self.decode(preds_idx, preds_prob)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\ppocr\postprocess\rec_postprocess.py", line 81, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range
```
All the options were the same except the rec and det paths. I'm quite curious

**Comment by bijonguha** [comment]
> Using the default or ch_ppocr_mobile_v2.0_rec, both work but when I tried to use the server model, it gave me the "list index out of range" error.
> 
> It may due to nothing being recognised. However, the detection did found 7 text boxes.
> 
> result = ocr.ocr(img_path, cls=True)
> for line in result:
> print(line)
> [2021/01/28 11:49:56] root INFO: dt_boxes num : 7, elapse : 1.3247952461242676
> [2021/01/28 11:49:57] root INFO: cls num : 7, elapse : 0.13612890243530273
> 
> I found it strange that the recognition result is worse than the default setting.

I am facing the same issue currently. A solution would be very helpful. When I am switching to server model, I am getting that error

**Comment by Ru-Van** [comment]
The same "list index out of range" error with EN recognition (2.6M) model !

**Comment by Programmerwyl** [comment]
In MODEL_URLS in paddleocr.py, add the path to the new model, it works for me.

'2.22': {
            'det': {
                'en': {
                    'url':
                    'https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar',
                },
            },
            'rec': {
                'en': {
                    'url':
                    'https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar',
                    'dict_path': './ppocr/utils/ppocr_keys_v1.txt'
                }
            }
        },

**Comment by yc0619** [comment]
Hi, i have also met such problem. But i use the model to detect german.
`pd_ocr = PaddleOCR(lang="german")
pd_ocr = PaddleOCR(lang="german")`

`
Traceback (most recent call last):
  File "/scannerbox.ki-project/scannerbox.Ki/src/develop/ocr/main.py", line 32, in <module>
    result = pd_ocr.ocr(img_path, cls=True)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 383, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 89, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py", line 375, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 98, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 66, in decode
    for text_id in text_index[batch_idx][selection]
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 66, in <listcomp>
    for text_id in text_index[batch_idx][selection]
IndexError: list index out of range
`
Could someone help? Thanks!

**Comment by zjlamtt** [comment]
I have stumbled upon the same program vulnerability. I found that the problem was probably caused by the detection of blank characters.
use
`ocr = PPStructure(show_log=True, use_space_char=False,det_db_unclip_ratio=2.92, det_db_thresh=0.001, det_db_box_thresh=0.2)`
will have bug, and use
`ocr = PPStructure(show_log=True, det_db_unclip_ratio=2.92, det_db_thresh=0.001, det_db_box_thresh=0.2)`
is OK.
So try to remove the use_space_char Parameters may solve  this.

**Comment by halqadasi** [comment]
> use_space_char

Could you please tell me where I can find this line you mentioned to change it?
