### ISSUE TITLE
how to train resnet with layer 50? error occured

### ISSUE THREAD

**Issue by Pooksin** [PaddlePaddle/PaddleOCR#1860]
[2021/01/28 16:55:58] root INFO: Architecture : 
[2021/01/28 16:55:58] root INFO:     Backbone : 
[2021/01/28 16:55:58] root INFO:         layers : 50
[2021/01/28 16:55:58] root INFO:         name : ResNet
[2021/01/28 16:55:58] root INFO:     Head : 
[2021/01/28 16:55:58] root INFO:         fc_decay : 0
[2021/01/28 16:55:58] root INFO:         name : CTCHead
[2021/01/28 16:55:58] root INFO:     Neck : 
[2021/01/28 16:55:58] root INFO:         encoder_type : rnn
[2021/01/28 16:55:58] root INFO:         hidden_size : 48
[2021/01/28 16:55:58] root INFO:         name : SequenceEncoder
[2021/01/28 16:55:58] root INFO:     Transform : None
[2021/01/28 16:55:58] root INFO:     algorithm : CRNN
[2021/01/28 16:55:58] root INFO:     model_type : rec

Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/jcjoo/PaddleOCR-release-2.0-rc1-0/tools/program.py", line 197, in train
    preds = model(images)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jcjoo/PaddleOCR-release-2.0-rc1-0/ppocr/modeling/architectures/base_model.py", line 76, in forward
    x = self.neck(x)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jcjoo/PaddleOCR-release-2.0-rc1-0/ppocr/modeling/necks/rnn.py", line 94, in forward
    x = self.encoder(x)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jcjoo/PaddleOCR-release-2.0-rc1-0/ppocr/modeling/necks/rnn.py", line 48, in forward
    x, _ = self.lstm(x)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1035, in forward
    return self._cudnn_impl(inputs, initial_states, sequence_length)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1012, in _cudnn_impl
    type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2837, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/jcjoo/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) The cudnn rnn and setting weight size should be same.
  [Hint: Expected weights_size_ == sizeof(T) * weight_numel_, but received weights_size_:3446784 != sizeof(T) * weight_numel_:1087488.] (at /paddle/paddle/fluid/operators/rnn_op.cu.cc:132)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < rnn > error]

when i set layer 18 or 34, it works well.. but layer 50 above, it fails. help!

when use_gpu False
 [Hint: Expected dim_a.width_ == dim_b.height_, but received dim_a.width_:2048 != dim_b.height_:512.] (at /paddle/paddle/fluid/operators/math/blas_impl.h:1166)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < rnn > error]

**Comment by tink2123** [comment]
Resnet50 is a large network. The errors is  out of memory. Try to reduce the batch size of training.

**Comment by Pooksin** [comment]
> Resnet50 is a large network. The errors is out of memory. Try to reduce the batch size of training.

thank you for replying this question

i already try. but it occur same error.

i insert a single line in rnn.py 

class EncoderWithRNN(nn.Layer):
    def __init__(self, in_channels, hidden_size):
        super(EncoderWithRNN, self).__init__()
        self.out_channels = hidden_size * 2
        print("in_channels:{} \n hidden_size:{}".format(in_channels,hidden_size))
        **in_channels=2048**
        self.lstm = nn.LSTM(
            in_channels, hidden_size, direction='bidirectional', num_layers=2)

    def forward(self, x):
        #print(" {}   {}\n".format(len(x[0]),len(x[0][0])))
        x, _ = self.lstm(x)
        return x


when i insert "in_channel=2048" , it works . but i worried about it is really work.

have you any idea for this?

**Comment by WenmuZhou** [comment]
you can try the latest code

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
