### ISSUE TITLE
ppocr/data/Imdb_dataset.py 类命定义错误

### ISSUE THREAD

**Issue by billtsu** [PaddlePaddle/PaddleOCR#1871]
![image](https://user-images.githubusercontent.com/15612265/106242195-3f0b4980-6242-11eb-804e-8848817b8b10.png)
运行实例代码报错如下
```shell
Traceback (most recent call last):  File "/Users/xx/tmp/PaddleOCR-dygraph/tools/infer/predict_system.py", line 30, in <module>
    import tools.infer.predict_det as predict_det
  File "/Users/xx/tmp/PaddleOCR-dygraph/tools/infer/predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "/Users/xx/tmp/PaddleOCR-dygraph/ppocr/data/__init__.py", line 36, in <module>
    from ppocr.data.lmdb_dataset import LMDBDataSet
ImportError: cannot import name 'LMDBDataSet' from 'ppocr.data.lmdb_dataset' (/Users/xx/tmp/PaddleOCR-dygraph/ppocr/data/lmdb_dataset.py)
```
```python3
class LMDBDataSet(Dataset):
    def __init__(self, config, mode, logger, seed=None):
        super(LMDBDataSet, self).__init__()
```

修改类名称 构造函数参数后运行无误

**Comment by WenmuZhou** [comment]
tks,  方便给个pr吗

**Comment by WenmuZhou** [comment]
![image](https://user-images.githubusercontent.com/12406017/106353767-ed3cef00-6327-11eb-9cbf-693c3f841495.png)
我这边看最新的代码和你的有所不同

**Comment by billtsu** [comment]
> ![image](https://user-images.githubusercontent.com/12406017/106353767-ed3cef00-6327-11eb-9cbf-693c3f841495.png)
> 我这边看最新的代码和你的有所不同

ok
