### ISSUE TITLE
distributed training AttributeError:    DataParallel' object has no attribute 'head'

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#1932]
eval model::   0%|          | 0/74 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 92, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/paddle/PaddleOCR/tools/program.py", line 258, in train
    eval_class)
  File "/paddle/PaddleOCR/tools/program.py", line 334, in eval
    if "SRN" in str(model.head):
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 1039, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataParallel' object has no attribute 'head'

command:     python3 -u -m paddle.distributed.launch --gpus '4,5,6,7'  tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml

**Comment by LDOUBLEV** [comment]
We fixed the problem, please update your dygraph branch code.
