### ISSUE TITLE
eval model:forward() takes 2 positional arguments but 3 were given错误

### ISSUE THREAD

**Issue by Young1993** [PaddlePaddle/PaddleOCR#1950]
训练命令行：
FLAGS_selected_gpus=1,2 python3.5 tools/train.py -c configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml -o Global.pretrain_weights=./pretrain_models/ResNet18_vd_pretrained/

训练部分正常，但到了
            if global_step > start_eval_step and \
                    (global_step - start_eval_step) % eval_batch_step == 0 and dist.get_rank() == 0:
                if model_average:
                    Model_Average = paddle.incubate.optimizer.ModelAverage(
                        0.15,
                        parameters=model.parameters(),
                        min_average_window=10000,
                        max_average_window=15625)
                    Model_Average.apply()
                cur_metirc = eval(model, valid_dataloader, post_process_class,
                                  eval_class)
计算metric时报错

eval model::   0%|                                                                              | 0/11 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/jy/xxx/scene_image/PaddleOCR/tools/program.py", line 255, in train
    eval_class)
  File "/home/jy/xxx/scene_image/PaddleOCR/tools/program.py", line 331, in eval
    preds = model(images, others)
  File "/home/jy/.local/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jy/xxx/scene_image/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 80, in forward
    x = self.head(x, data)
  File "/home/jy/.local/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

请问这个大概是什么问题？

**Comment by WenmuZhou** [comment]
请问是最新的代码吗，这个问题最新的dygraph已经修复了
