### ISSUE TITLE
onnxruntime部署PPOCR， 运行predict_rec.py时输入尺寸出错

### ISSUE THREAD

**Issue by shixinlishixinli** [PaddlePaddle/PaddleOCR#2050]
onnx的rec网络输入尺寸不能灵活

Traceback (most recent call last):
  File "onnx_inference/predit_system.py", line 190, in <module>
    main(utility.parse_args())
  File "onnx_inference/predit_system.py", line 159, in main
    dt_boxes, rec_res = text_sys(img)
  File "onnx_inference/predit_system.py", line 108, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/lisa/program/paddlepaddle/ocr/PaddleOCR/onnx_inference/predit_rec.py", line 106, in __call__
    outputs = self.predictor.run(self.output_tensors, input_dict)
  File "/home/lisa/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: x for the following indices
 index: 3 Got: 262 Expected: 100
 Please fix either the inputs or the model.

**Comment by HongChow** [comment]
请问onnx的预测代码 onnx_inference/ 文件夹在哪里呢？

**Comment by shixinlishixinli** [comment]
> 请问onnx的预测代码 onnx_inference/ 文件夹在哪里呢？
我从这里找的代码
https://aistudio.baidu.com/aistudio/projectdetail/1479970

**Comment by shixinlishixinli** [comment]
我找到了出现这个问题的原因，可以参考这个https://github.com/PaddlePaddle/PaddleOCR/pull/1837

**Comment by 471417367** [comment]
@shixinlishixinli 请问onnx_inference文件夹是怎么找到的呢
