### ISSUE TITLE
使用paddleocr报错ModuleNotFoundError: No module named 'tools.infer'

### ISSUE THREAD

**Issue by ray111722** [PaddlePaddle/PaddleOCR#2070]
paddlepaddle ==2.0.0rc1
paddleocr == 2.0.1

Traceback (most recent call last):
  File "E:/Fuelrailerrorproofing/paddleOcr.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "F:\Anaconda\envs\pp\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "F:\Anaconda\envs\pp\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'

**Comment by ray111722** [comment]
pip uninstall tools

**Comment by YY007H** [comment]
这个方法适合误安装了tools包的
