### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by vikenlove** [PaddlePaddle/PaddleOCR#2084]
python3 tools/infer/predict_system.py --image_dir="/root/fp.jpg" --det_model_dir="/root/inference/ch_ppocr_server_v2.0_det_infer/"  --rec_model_dir="/root/inference/ch_ppocr_server_v2.0_rec_infer/" --cls_model_dir="/root/inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/skimage/__init__.py", line 119, in <module>
    from ._shared import geometry
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 30, in <module>
    import tools.infer.predict_det as predict_det
  File "/root/PaddleOCR/tools/infer/predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "/root/PaddleOCR/ppocr/data/__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/root/PaddleOCR/ppocr/data/imaug/__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "/root/PaddleOCR/ppocr/data/imaug/iaa_augment.py", line 20, in <module>
    import imgaug
  File "/usr/local/python3/lib/python3.8/site-packages/imgaug/__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "/usr/local/python3/lib/python3.8/site-packages/imgaug/imgaug.py", line 22, in <module>
    import skimage.draw
  File "/usr/local/python3/lib/python3.8/site-packages/skimage/__init__.py", line 122, in <module>
    _raise_build_error(e)
  File "/usr/local/python3/lib/python3.8/site-packages/skimage/__init__.py", line 100, in _raise_build_error
    raise ImportError("""%s
ImportError: dlopen: cannot load any more object with static TLS
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html

**Comment by jimzhang828** [comment]
I also encountered this problem, have you solved it?

**Comment by weiluonika** [comment]
没人回答一下吗？
