### ISSUE TITLE
预测时内存不断增加

### ISSUE THREAD

**Issue by tyy1tyy** [PaddlePaddle/PaddleOCR#2108]
使用realease/2.0代码中的ch_det_res18_db_v2.0.yml训练检测模型。预测命令为
python3 tools/infer_det.py -c ch_det_res18_db_v2.0.yml -o Global.infer_img="/data/OCR_det/handwriting/" Global.checkpoints="/data/OCR_det/output/db_r18/best_accuracy"，配置文件基本不变。
图片约有20张，预测时内存不断增加，直至溢出，请问是什么原因导致的呢？
Traceback (most recent call last):
  File "tools/infer_det.py", line 115, in <module>
    main()
  File "tools/infer_det.py", line 97, in main
    preds = model(images)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tang/OCR-2.0-det/ppocr/modeling/architectures/base_model.py", line 74, in forward
    x = self.backbone(x)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tang/OCR-2.0-det/ppocr/modeling/backbones/det_resnet_vd.py", line 278, in forward
    y = block(y)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
    input = layer(input)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tang/OCR-2.0-det/ppocr/modeling/backbones/det_resnet_vd.py", line 171, in forward
    y = F.relu(y)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/nn/functional/activation.py", line 528, in relu
    return core.ops.relu(x)
SystemError: (Fatal) Operator relu raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 185.062744MB memory on GPU 0, available memory is only 6.312500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
. (at /paddle/paddle/fluid/imperative/tracer.cc:172)

**Comment by heyhumor** [comment]
同问，一张4k的大图导致内存爆满，电脑卡了十几分钟

**Comment by simplew2011** [comment]
> 同问，一张4k的大图导致内存爆满，电脑卡了十几分钟

这个问题似乎是由于配置表内Eval.dataset.DetResizeForTest.image_shape:被注释掉的原因。图片太大了。

**Comment by HongChow** [comment]
请问C++端是否会有一样的问题？

**Comment by heyhumor** [comment]
> > 同问，一张4k的大图导致内存爆满，电脑卡了十几分钟
> 
> 这个问题似乎是由于配置表内Eval.dataset.DetResizeForTest.image_shape:被注释掉的原因。图片太大了。

的确，如果不进行resize会导致内存溢出，但是对大图进行resize，精度就会大大下降，2.0的infer_det对分辨率似乎过于敏感了

**Comment by simplew2011** [comment]
对一个文件内图片遍历预测，图片大小不一时，
utility.py     
parser.add_argument("--det_limit_side_len", type=float, default=960)
parser.add_argument("--det_limit_type", type=str, default='max')

predict_det.py
'DetResizeForTest': {
'limit_side_len': args.det_limit_side_len,
 'limit_type': args.det_limit_type

在预测时显存占用不断增加，因为图片尺寸不一，动态申请，导致卡死
2.0版本问题还是不少。
predict_det.py和infer_det.py  DB预处理参数对齐后，预测结果还是不一致。

**Comment by SWHL** [comment]
@heyhumor  我这里尝试了，还是不行
不过，我把我之前验证集图像数目由原来的1500张改为了800张，可以完整跑完eval了
