### ISSUE TITLE
 中英文通用OCR识别模型报错：AssertionError: Variable Shape not match

### ISSUE THREAD

**Issue by jiongjiongli** [PaddlePaddle/PaddleOCR#2138]
# 模型地址
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_pre.tar

# paddle版本
```
paddlepaddle-gpu==2.0.0.post100
paddleocr: 最新代码 release/2.0
```

# 命令
```
python3.7 tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml
```

# 异常信息
```
[2021/02/28 15:57:23] root INFO: Initialize indexs of datasets:['./train_data/rec/2021-02-28/train_rec_gt.txt']
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 97, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/root/proj/PaddleOCR/tools/program.py", line 214, in train
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 260, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 367, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 775, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 597, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if p[0].trainable])
  File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 249, in _create_accumulators
    self._add_moments_pows(p)
  File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 216, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 516, in _add_accumulator
    var.set_value(self._accumulators_holder[var_name])
  File "<decorator-gen-113>", line 2, in set_value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 125, in set_value
    self.name, self_tensor_np.shape, value_np.shape)
AssertionError: Variable Shape not match, Variable [ ctc_fc_w_attr_moment1_0 ] need tensor with shape (512, 6624) but load set tensor with shape (512, 6625)
```

**Comment by jiongjiongli** [comment]
找到原因了😂
use_space_char=True

**Comment by Yaoxingtian** [comment]
> 
> 
> 找到原因了😂
> use_space_char=True

我也是遇到这个问题了，但是这个方法还是没有用啊？
