### ISSUE TITLE
将识别模型替换为ch_rec_r34_vd_crnn_enhance后，报错

### ISSUE THREAD

**Issue by jingruhou** [PaddlePaddle/PaddleOCR#2152]
运行命令：

` python tools/infer/predict_system.py --image_dir="./c10/c10_007.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_rec_r34_vd_crnn_enhance/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True `

错误日志：

`Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 187, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 156, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 108, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home1/houjr/develop/PaddleOCR/tools/infer/predict_rec.py", line 111, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home1/houjr/develop/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 110, in __call__
    preds_idx = preds.argmax(axis=2)
numpy.AxisError: axis 2 is out of bounds for array of dimension 2`

**Comment by littletomatodonkey** [comment]
你好，动态图模型需要使用动态图代码，静态图模型需要使用静态图代码预测，你这个看着是静态图导出的inference model，使用动态图的代码预测，会有问题的

**Comment by jingruhou** [comment]
@littletomatodonkey 谢谢回复。
确实是模型版本没有对上，修改为2.0的模型之后，解决该问题。
（以上命令之中的识别模型路径中是静态图模型）
