### ISSUE TITLE
执行tools\train.py时的错误

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleOCR#217]
PS E:\Python37\PaddleOCR-develop> python  .\tools\train.py -c .\configs\rec\rec_icdar15_train.yml
2020-06-16 17:23:35,857-INFO: {'Global': {'algorithm': 'CRNN', 'use_gpu': False, 'epoch_num': 1000, 'log_smooth_window': 20, 'print_batch_step': 10, 'save_model_dir': './output/rec_CRNN', 'save_epoch_step': 300, 'eval_batch_step': 500, 'train_batch_size_per_card': 256, 'test_batch_size_per_card': 256, 'image_shape': [3, 32, 100], 'max_text_length': 7, 'character_type': 'en', 'loss_type': 'ctc', 'reader_yml': '.\\configs\\rec\\rec_icdar15_reader.yml', 'pretrain_weights': '.\\pretrain_models\\rec_mv3_none_bilstm_ctc\\best_accuracy', 'checkpoints': None, 'save_inference_dir': None, 'infer_img': None, 'character_dict_path': './ppocr/utils/numbers.txt'}, 'Architecture': {'function': 'ppocr.modeling.architectures.rec_model,RecModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.rec_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.rec_ctc_head,CTCPredict', 'encoder_type': 'rnn', 'SeqRNN': {'hidden_size': 96}}, 'Loss': {'function': 'ppocr.modeling.losses.rec_ctc_loss,CTCLoss'}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.0005, 'beta1': 0.9, 'beta2': 0.999, 'decay': {'function': 'cosine_decay', 'step_each_epoch': 20, 'total_epoch': 1000}}, 'TrainReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'num_workers': 8, 'img_set_dir': './train_data/ic15_data', 'label_file_path': './train_data/ic15_data/rec_gt_train.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'img_set_dir': './train_data/ic15_data', 'label_file_path': './train_data/ic15_data/rec_gt_test.txt'}, 'TestReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader'}}
2020-06-16 17:23:39,282-INFO: places would be ommited when DataLoader is not iterable
2020-06-16 17:23:39,537-INFO: Loading parameters from .\pretrain_models\rec_mv3_none_bilstm_ctc\best_accuracy...
Traceback (most recent call last):
  File ".\tools\train.py", line 112, in <module>
    main()
  File ".\tools\train.py", line 90, in main
    init_model(config, train_program, exe)
  File "E:\Python37\PaddleOCR-develop\ppocr\utils\save_load.py", line 121, in init_model
    load_params(exe, program, path)
  File "E:\Python37\PaddleOCR-develop\ppocr\utils\save_load.py", line 104, in load_params
    fluid.io.set_program_state(prog, state)
  File "E:\Python37\lib\site-packages\paddle\fluid\io.py", line 1959, in set_program_state
    "Variable [ {} ] Not found, Please make sure run startup program".format(para.name)
AssertionError: Variable [ tmp_4 ] Not found, Please make sure run startup program
这是什么情况

**Comment by LDOUBLEV** [comment]
是一个bug，已经在修了，你可以暂时把rec_icdar15_train.yml中的
```
decay:
    function: cosine_decay
    step_each_epoch: 20
    total_epoch: 1000
```
删掉，主要是加上decay后，会自动给学习率创建相关的decay变量，之前保存的模型中没有decay变量，导致加载模型出错。

**Comment by Matiz7** [comment]
谢谢。
另外rec_icdar15_train.yml 里这个参数具体什么意思  
像是train所需图片的尺寸限制 ？  image_shape: [3, 32, 100]

**Comment by tink2123** [comment]
> image_shape: [3, 32, 100]

输入图片会在网络中统一缩放为[3,32,100]

**Comment by LDOUBLEV** [comment]
> PS E:\Python37\PaddleOCR-develop> python .\tools\train.py -c .\configs\rec\rec_icdar15_train.yml
> 2020-06-16 17:23:35,857-INFO: {'Global': {'algorithm': 'CRNN', 'use_gpu': False, 'epoch_num': 1000, 'log_smooth_window': 20, 'print_batch_step': 10, 'save_model_dir': './output/rec_CRNN', 'save_epoch_step': 300, 'eval_batch_step': 500, 'train_batch_size_per_card': 256, 'test_batch_size_per_card': 256, 'image_shape': [3, 32, 100], 'max_text_length': 7, 'character_type': 'en', 'loss_type': 'ctc', 'reader_yml': '.\configs\rec\rec_icdar15_reader.yml', 'pretrain_weights': '.\pretrain_models\rec_mv3_none_bilstm_ctc\best_accuracy', 'checkpoints': None, 'save_inference_dir': None, 'infer_img': None, 'character_dict_path': './ppocr/utils/numbers.txt'}, 'Architecture': {'function': 'ppocr.modeling.architectures.rec_model,RecModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.rec_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.rec_ctc_head,CTCPredict', 'encoder_type': 'rnn', 'SeqRNN': {'hidden_size': 96}}, 'Loss': {'function': 'ppocr.modeling.losses.rec_ctc_loss,CTCLoss'}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.0005, 'beta1': 0.9, 'beta2': 0.999, 'decay': {'function': 'cosine_decay', 'step_each_epoch': 20, 'total_epoch': 1000}}, 'TrainReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'num_workers': 8, 'img_set_dir': './train_data/ic15_data', 'label_file_path': './train_data/ic15_data/rec_gt_train.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'img_set_dir': './train_data/ic15_data', 'label_file_path': './train_data/ic15_data/rec_gt_test.txt'}, 'TestReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader'}}
> 2020-06-16 17:23:39,282-INFO: places would be ommited when DataLoader is not iterable
> 2020-06-16 17:23:39,537-INFO: Loading parameters from .\pretrain_models\rec_mv3_none_bilstm_ctc\best_accuracy...
> Traceback (most recent call last):
> File ".\tools\train.py", line 112, in
> main()
> File ".\tools\train.py", line 90, in main
> init_model(config, train_program, exe)
> File "E:\Python37\PaddleOCR-develop\ppocr\utils\save_load.py", line 121, in init_model
> load_params(exe, program, path)
> File "E:\Python37\PaddleOCR-develop\ppocr\utils\save_load.py", line 104, in load_params
> fluid.io.set_program_state(prog, state)
> File "E:\Python37\lib\site-packages\paddle\fluid\io.py", line 1959, in set_program_state
> "Variable [ {} ] Not found, Please make sure run startup program".format(para.name)
> AssertionError: Variable [ tmp_4 ] Not found, Please make sure run startup program
> 这是什么情况

fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/222

**Comment by Matiz7** [comment]
2020-06-18 13:40:02,615-INFO: epoch: 21, iter: 1580, lr: 0.000500, 'loss': 43.19416, 'acc': 0.992188, time: 19.396
2020-06-18 13:43:15,457-INFO: epoch: 21, iter: 1590, lr: 0.000500, 'loss': 43.67629, 'acc': 0.992188, time: 19.375
训练到什么程度会结束 ？执行很久了 怪我cpu太弱

**Comment by tink2123** [comment]
eval 的 acc 符合预期就可以停止了，默认会训练1000个epoch

**Comment by Matiz7** [comment]
2020-06-18 18:00:01,229-INFO: epoch: 29, iter: 2140, lr: 0.000500, 'loss': 21.369263, 'acc': 0.998047, time: 19.920
acc到 1 才结束吗
另外 生成的这个模型文件 output\rec_CRNN\best_accuracy.pdopt 要怎么使用

**Comment by LDOUBLEV** [comment]
如果你感觉ACC符合你的预期，可以手动停止训练，或者等设定的1000epoch执行完自动停止。训练好的模型使用方式可以参考文档doc／doc_ch／recognition.md

**Comment by Matiz7** [comment]
tools/infer_det.py 这个执行参数是怎么样的

**Comment by LDOUBLEV** [comment]
> tools/infer_det.py 这个执行参数是怎么样的

参考文档最后一部分：https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/detection.md

**Comment by Matiz7** [comment]
使用OCR默认自带模型和参数时  调整哪个参数能更准确识别诸如此类，下图中的数字识别成 9795047
http://kfimage.oss-cn-hangzhou.aliyuncs.com/pb_photo/591/2020-06-20/1200311/E0145107/5534/1592703765534.jpg
