### ISSUE TITLE
Error while training detection model

### ISSUE THREAD

**Issue by Ankan1998** [PaddlePaddle/PaddleOCR#2192]
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 98, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "C:\Users\Ankan\Desktop\PaddleOCR-release-2.0\tools\program.py", line 236, in train
    post_result = post_process_class(preds, batch[1])
  File "C:\Users\Ankan\Desktop\PaddleOCR-release-2.0\ppocr\postprocess\east_postprocess.py", line 132, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[ino]
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by HawkingRadiation42** [comment]
hey, were you able to solve this error? im facing the same issue. 
thankyou
