### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by jiongjiongli** [PaddlePaddle/PaddleOCR#2203]
麻烦帮忙看下什么原因

[2021/03/09 09:44:59] root INFO: resume from ./models/ch_ppocr_server_v2.0_rec_pre/best_accuracy
[2021/03/09 09:44:59] root INFO: train dataloader has 51 iters, valid dataloader has 12 iters
[2021/03/09 09:44:59] root INFO: During the training process, after the 0th iteration, an evaluation is run every 4 iterations
[2021/03/09 09:44:59] root INFO: Initialize indexs of datasets:['./train_data/rec/2021-02-28/train_rec_gt.txt']
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 91, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/PaddleOCR/tools/program.py", line 192, in train
    for idx, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/reader.py", line 412, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 500, in __init__
    self._init_workers()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 515, in _init_workers
    self._data_queue = multiprocessing.Queue()
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
**OSError: [Errno 28] No space left on device**
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f75d1e8e620>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 755, in __del__
    self._try_shutdown_all()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 576, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
INFO 2021-03-09 09:45:07,014 launch_utils.py:308] terminate all the procs
ERROR 2021-03-09 09:45:07,015 launch_utils.py:546] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-03-09 09:45:10,018 launch_utils.py:308] terminate all the procs

**Comment by WenmuZhou** [comment]
磁盘空间不足了

**Comment by WenmuZhou** [comment]
df -h 看一下

**Comment by Crown-Messi** [comment]
你好，请问这个问题您当时怎么解决的呢。
