### ISSUE TITLE
图片识别报错如下，MemoryError: std::bad_alloc 是否对 图片大小有限制？

### ISSUE THREAD

**Issue by huailian1216** [PaddlePaddle/PaddleOCR#2285]
```
Traceback (most recent call last):
  File "tests.py", line 13, in <module>
    init()
  File "tests.py", line 8, in init
    result = ocr.ocr(img_path, cls=True)
  File "/home/jsohua/virtual_env/iss_ai_cloud/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/home/jsohua/virtual_env/iss_ai_cloud/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 87, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/jsohua/virtual_env/iss_ai_cloud/lib/python3.7/site-packages/paddleocr/tools/infer/predict_det.py", line 164, in __call__
    im = paddle.fluid.core.PaddleTensor(img)
MemoryError: std::bad_alloc
```

**Comment by tink2123** [comment]
你的图片是多大的呢？可以先尝试用我们提供的测试图，看能否得到正确的结果：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/imgs/11.jpg

**Comment by amrjlg** [comment]
我这里也是有整个疑问，图片大小是254*14
![单行文本](https://user-images.githubusercontent.com/31244260/120154466-815d8b00-c222-11eb-899c-ff4acbe3ce26.png)
