### ISSUE TITLE
100张A4大小图片eval()完成后报错，20180TI，11G显存，如下描述cudaErrorLaunchOutOfResources

### ISSUE THREAD

**Issue by ymzx** [PaddlePaddle/PaddleOCR#2319]
检测模型训练，eval()计算完成后，报错如下
Traceback (most recent call last):
  File "tools/train.py", line 88, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 83, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/ocr/djw/PaddleOCR-release-2.0/tools/program.py", line 212, in train
    loss = loss_class(preds, batch)
  File "/home/ocr/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ocr/djw/PaddleOCR-release-2.0/ppocr/losses/det_db_loss.py", line 58, in forward
    label_shrink_mask)
  File "/home/ocr/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ocr/djw/PaddleOCR-release-2.0/ppocr/losses/det_basic_loss.py", line 89, in forward
    min(negative.sum(), positive_count * self.negative_ratio))
  File "/home/ocr/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 249, in __impl__
    return math_op(self, other_var, 'axis', axis)
SystemError: (Fatal) Operator greater_than raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorLaunchOutOfResources: too many resources requested for launch. (at /paddle/paddle/fluid/imperative/tracer.cc:172)
请问可能是什么原因？

**Comment by ymzx** [comment]
辅助信息：
该问题eval()后，程序回到train()，继续训练，计算loss时报错，
![image](https://user-images.githubusercontent.com/29808550/112116242-0a3dc200-8bf5-11eb-9431-79df220c2d7e.png)
貌似，eval()计算后，GPU显存没有释放，和train()累加，导致too many resources,如果是，请问如何解决？
谢
