### ISSUE TITLE
 AttributeError: module 'gast' has no attribute 'Index'

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#2320]
Traceback (most recent call last):
  File "tools/export_model.py", line 103, in <module>
    main()
  File "tools/export_model.py", line 98, in main
    paddle.jit.save(model, save_path)
  File "<decorator-gen-60>", line 2, in save
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 681, in save
    inner_input_spec)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "/home/jitesh/Desktop/PaddleOCR-release-2.0/ppocr/modeling/architectures/base_model.py", line 74, in forward (* user code *)
	x = self.backbone(x)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 220, in convert_call
	forward_func = convert_to_static(forward_func)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
	static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
	static_func = self._convert(func)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 116, in _convert
	root_wrapper = self._dygraph_to_static.get_static_ast(root)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 61, in get_static_ast
	self.transfer_from_node_type(self.static_analysis_root)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 92, in transfer_from_node_type
	self._apply(transformer, node_wrapper, log_level=index + 1)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 65, in _apply
	transformer(node_wrapper).transform()
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 433, in transform
	self.visit(self.root)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 436, in visit
	self.generic_visit(node)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/ast.py", line 308, in generic_visit
	value = self.visit(value)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 439, in visit
	self.replace_stmt_list(node.body)
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 455, in replace_stmt_list
	new_stmts = self.get_for_stmt_nodes(body_list[i])
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 477, in get_for_stmt_nodes
	stmts_tuple = current_for_node_parser.parse()
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 879, in parse
	return self._parse_for_stmts()
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 943, in _parse_for_stmts
	target_node, assign_node = self._build_assign_var_slice_node()
    File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1094, in _build_assign_var_slice_node
	slice=gast.Index(value=gast.Name(
    AttributeError: module 'gast' has no attribute 'Index'

**Comment by mjack3** [comment]
Same error here, do you know why ?

**Comment by mjack3** [comment]
solved.

pip install tensorflow-gpu

https://github.com/serge-sans-paille/gast/issues/53

**Comment by Jitesh4389** [comment]
Solved...

In the meantime you can use pip install gast==0.3.3 with tf-nightly.
