### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by wanghaotian233** [PaddlePaddle/PaddleOCR#2330]
运行命令时报错
python3 tools/infer/predict_system.py --image_dir="/home/data/test_images/" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True

Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 187, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 169, in main
    draw_img = draw_ocr_box_txt(
  File "/home/hexian/anaconda3/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 254, in draw_ocr_box_txt
    font = ImageFont.truetype(font_path, font_size, encoding="utf-8")
  File "/home/hexian/anaconda3/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/home/hexian/anaconda3/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/hexian/anaconda3/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by MissPenguin** [comment]
看着像PIL这个库有问题，换Python3.7试试？

**Comment by Pxtri2156** [comment]
I also got the same error. And I using python 3.8.  Can anyone help me to resolve this problem ?
