### ISSUE TITLE
attention infer_rec报错

### ISSUE THREAD

**Issue by itscarrot** [PaddlePaddle/PaddleOCR#2345]
自己retrain了一个 attention loss的识别模型，训练完后做infer时报错，dimension不匹配，未对infer_rec.py做修改,看似paddle和python脚本不兼容引起的？
使用paddlepaddle-gp版本为1.8.5.post107，paddleocr版本为1.1静态图版本，train yml文件是在rec_mv3_tps_bilstm_attn.yml基础上修改的，reader为SimpleReader。

错误信息如下：
```
TPS does not support variable shape in chinese!We set img_shape to be the same , it may affect the inference effect
Traceback (most recent call last):
  File "tools/infer_rec.py", line 176, in <module>
    main()
  File "tools/infer_rec.py", line 71, in main
    _, outputs = rec_model(mode="test")
  File "/content/PaddleOCR/ppocr/modeling/architectures/rec_model.py", line 191, in __call__
    inputs = self.tps(image)
  File "/content/PaddleOCR/ppocr/modeling/stns/tps.py", line 254, in __call__
    batch_C_prime = self.loc_net(image)
  File "/content/PaddleOCR/ppocr/modeling/stns/tps.py", line 86, in __call__
    image, num_filters, 3, act='relu', name=name)
  File "/content/PaddleOCR/ppocr/modeling/stns/tps.py", line 51, in conv_bn_layer
    bias_attr=False)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1971, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ConvOp::ComputeOutputShape(paddle::framework::InferShapeContext*) const
3   paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/content/PaddleOCR/ppocr/modeling/stns/tps.py", line 51, in conv_bn_layer
    bias_attr=False)
  File "/content/PaddleOCR/ppocr/modeling/stns/tps.py", line 86, in __call__
    image, num_filters, 3, act='relu', name=name)
  File "/content/PaddleOCR/ppocr/modeling/stns/tps.py", line 254, in __call__
    batch_C_prime = self.loc_net(image)
  File "/content/PaddleOCR/ppocr/modeling/architectures/rec_model.py", line 191, in __call__
    inputs = self.tps(image)
  File "tools/infer_rec.py", line 71, in main
    _, outputs = rec_model(mode="test")
  File "tools/infer_rec.py", line 176, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 32, 320].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] at (/paddle/paddle/fluid/operators/conv_op.cc:59)
  [operator < conv2d > error]
```

**Comment by itscarrot** [comment]
head为attention的情况，reader一定要用lmdb格式吗？

**Comment by WenmuZhou** [comment]
看起来是你输入的图片的三维的，缺少一个batch维度，https://github.com/PaddlePaddle/PaddleOCR/blob/release/1.1/tools/infer_rec.py#L113这里的img[0]改为img看看
