### ISSUE TITLE
训练ch_det_mv3_db_v2.0.yml 网络的时候报异常。请大佬关注

### ISSUE THREAD

**Issue by yfc886** [PaddlePaddle/PaddleOCR#2392]
**使用ch_det_mv3_db_v2.0.yml 训练的时候，成功跑起来了一次。大概训练了3个多小时然后就报异常退出了。之后无论如何都无法再启动ch_det_mv3_db_v2.0.yml 的训练了。 **
配置信息：
GTX：3060
CUDA：11.0
CUDNN：v8.0.4.30
操作系统：windows10  64位

异常信息：
[2021/04/03 17:52:31] root INFO: load pretrained model from ['./pretrain_models/ch_ppocr_server_v2.0_det_train/best_accuracy']
[2021/04/03 17:52:31] root INFO: train dataloader has 12 iters, valid dataloader has 32 iters
[2021/04/03 17:52:31] root INFO: During the training process, after the 3000th iteration, an evaluation is run every 2000 iterations
[2021/04/03 17:52:31] root INFO: Initialize indexs of datasets:['./train_data/shouxie_train_data/det/train/Label.txt']
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 97, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "D:\PaddleOCR-release-2.0\tools\program.py", line 230, in train
    post_result = post_process_class(preds, batch[1])
  File "D:\PaddleOCR-release-2.0\ppocr\postprocess\db_postprocess.py", line 145, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
ValueError: too many values to unpack (expected 4)

**Comment by yfc886** [comment]
找到原因了，原来是配置文件中的Global 的cal_metric_during_train: False  设置为True 导致错误异常。修改回False 就行了。。。

**Comment by yaoruinupt** [comment]
无语，我也是改了配置文件以后报了这个，还找了半天标记文件的格式错误orz，谢谢兄弟

**Comment by qqqqq127** [comment]
但是如果像设置为true，应该怎么解决呢？
