### ISSUE TITLE
paddleOCR用paddlehub部署运行问题

### ISSUE THREAD

**Issue by ghostcy** [PaddlePaddle/PaddleOCR#2409]
1、在anaconda虚拟环境下安装paddleOCR
hub install deploy/hubserving/ocr_system/
安装成功
2、export CUDA_VISIBLE_DEVICES="0" &&hub serving start -c deploy/configGPU.json
启动服务后，hub list 查看服务停止
3、查看/root/.paddlehub/log的日志，错误如下
==================================================
Record at 2021-04-07 11:17:03
==================================================
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle2_py3.8/lib/python3.8/site-packages/paddlehub/module/manager.py", line 243, in list
    self._local_modules[subdir] = HubModule.load(fulldir)
  File "/root/anaconda3/envs/paddle2_py3.8/lib/python3.8/site-packages/paddlehub/module/module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/root/anaconda3/envs/paddle2_py3.8/lib/python3.8/site-packages/paddlehub/utils/utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/root/anaconda3/envs/paddle2_py3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/ocr_system/module.py", line 18, in <module>
    from tools.infer.utility import base64_to_cv2
ModuleNotFoundError: No module named 'tools'
请问如何解决？

**Comment by LDOUBLEV** [comment]
在PaddleOCR 目录下 启动hub服务
