### ISSUE TITLE
ImportError: cannot import name 'initial_logger'

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#2410]
Traceback (most recent call last):
  File "PPOCRLabel.py", line 35, in <module>
    from paddleocr import PaddleOCR
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 21, in <module>
    import tools.infer.utility as utility
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
ImportError: cannot import name 'initial_logger'

**Comment by LDOUBLEV** [comment]
重新卸载安装最新的ppocr whl包试试

**Comment by Jitesh4389** [comment]
how to install
