### ISSUE TITLE
AssertionError: Variable Shape not match, 

### ISSUE THREAD

**Issue by Yaoxingtian** [PaddlePaddle/PaddleOCR#2479]
hello, I met the problem as blow , when I  use my own data to train, could you please help solve it ?
thanks so much!

AssertionError: Variable Shape not match, Variable [ ctc_fc_w_attr_moment1_0 ] need tensor with shape (192, 13) but load set tensor with shape (192, 37)
####################################################3

 File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 97, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/xiaou/YAO/PaddleOCR_release2.0/tools/program.py", line 214, in train
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 260, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 367, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 775, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 597, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if p[0].trainable])
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 249, in _create_accumulators
    self._add_moments_pows(p)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 216, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 516, in _add_accumulator
    var.set_value(self._accumulators_holder[var_name])
  File "<decorator-gen-113>", line 2, in set_value
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/xiaou/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 125, in set_value
    self.name, self_tensor_np.shape, value_np.shape)
AssertionError: Variable Shape not match, Variable [ ctc_fc_w_attr_moment1_0 ] need tensor with shape (192, 14) but load set tensor with shape (192, 37)

**Comment by MissPenguin** [comment]
Please post your command line here, and describe which parameters have you modified, show your yml file may be helpful.

**Comment by Ankan1998** [comment]
I got the same error
Can anyone help me out

Traceback (most recent call last):
  File "C:/Users/Ankan/Desktop/PaddleOCR-release-2.0 - Copy/train.py", line 127, in <module>
    main_train(config_path_tr)
  File "C:/Users/Ankan/Desktop/PaddleOCR-release-2.0 - Copy/train.py", line 100, in main_train
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "C:\Users\Ankan\Desktop\PaddleOCR-release-2.0 - Copy\tools\program.py", line 230, in train
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\dygraph\base.py", line 260, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\optimizer\adam.py", line 367, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\optimizer\optimizer.py", line 775, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\optimizer\optimizer.py", line 597, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if p[0].trainable])
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\optimizer\adam.py", line 249, in _create_accumulators
    self._add_moments_pows(p)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\optimizer\adam.py", line 216, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\optimizer\optimizer.py", line 516, in _add_accumulator
    var.set_value(self._accumulators_holder[var_name])
  File "<decorator-gen-113>", line 2, in set_value
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\Ankan\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 125, in set_value
    self.name, self_tensor_np.shape, value_np.shape)
AssertionError: Variable Shape not match, Variable [ ctc_fc_w_attr_moment1_0 ] need tensor with shape (512, 63) but load set tensor with shape (512, 6625)

**yaml file**

Global:
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir: ./output/rec_ctc_server
  save_epoch_step: 1
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [1,1]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/ch_ppocr_server_v2.0_rec_pre/best_accuracy
  checkpoints: ./pretrain_models/ch_ppocr_server_v2.0_rec_pre/best_accuracy
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  character_dict_path: ppocr/utils/ic15_dict.txt
  character_type: en
  max_text_length: 25
  infer_mode: False
  use_space_char: True


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list: ["./train_data/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 1
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list: ["./train_data/eval_rec.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: True
    batch_size_per_card: 1
    num_workers: 1

**Comment by gxy0727** [comment]
我也遇到了这个问题，不知道如何

**Comment by linnnn1** [comment]
请问解决了吗？
