### ISSUE TITLE
带tps的模型只能训练英文?

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleOCR#248]
用rec_r34_vd_tps_bilstm_attn.yml训练的日文ocr,训练好inference阶段报错:
```
Error: Input(X) dims[3] and Input(Grid) dims[2] should be equal.
  [Hint: Expected grid_dims[2] == x_dims[3], but received grid_dims[2]:320 != x_dims[3]:100.] at (/paddle/paddle/fluid/operators/grid_sampler_op.cc:55)
  [operator < grid_sampler > error]
2020-06-22 10:55:45,453-INFO: ERROR!!!! 
Please read the FAQ：https://github.com/PaddlePaddle/PaddleOCR#faq 
If your model has tps module:  TPS does not support variable shape.
Please set --rec_image_shape='3,32,100' and --rec_char_type='en'
```
预测命令:
```
python tools/infer/predict_rec.py --image_dir="./word_254.png" --rec_model_dir="./inference/rare_72_rec_japan/" --rec_image_shape="3, 32, 100" --rec_char_type="ch" --rec_algorithm="RARE" --rec_char_dict_path="/data/OCR/japan_dict.txt"
```
我训练的时候输入分辨率是3,32,320,是不是想用带tps的模型,训练时输入分辨率只能设置为3,32,100?

**Comment by tink2123** [comment]
不是的，只要保持固定长度的输入即可，使用了自定义数据集，会默认对输入图片做变长处理，麻烦手动注释掉下面两行，保持固定输入
https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_rec.py#L54-L55

**Comment by lfxx** [comment]
> 不是的，只要保持固定长度的输入即可，使用了自定义数据集，会默认对输入图片做变长处理，麻烦手动注释掉下面两行，保持固定输入
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_rec.py#L54-L55

使用如下命令预测:
```
python tools/infer/predict_rec.py --image_dir="./word_254.png" --rec_model_dir="./inference/rare_72_rec_japan/" --rec_image_shape="3, 32, 320" --rec_char_type="ch" --rec_algorithm="RARE" --rec_char_dict_path="/data/OCR/japan_dict.txt"
```,可以成功运行,但是没有输出结果:
```
/data/.conda/envs/paddle/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/data/.conda/envs/paddle/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Predicts of ./word_254.png:['', nan]
Total predict time for 1 images:0.801
```

**Comment by tink2123** [comment]
请问您的运行环境是？直接使用 infer_rec.py 可以得到正确的预测结果吗？

**Comment by lfxx** [comment]
> 请问您的运行环境是？直接使用 infer_rec.py 可以得到正确的预测结果吗？
用infer_rec.py报错,预测的单张图片,使用命令:
```
Error: ShapeError: the input of Op(conv) should be 4-D or 5-D Tensor. But received: 3-D Tensor, the shape of input is [3, 32, 320].
```
预测命令如下:
```
 python tools/infer_rec.py -c configs/rec/rec_r34_vd_tps_bilstm_attn_smlange.yml -o Global.checkpoints=./output/rec_RARE/best_accuracy Global.infer_img=./my_pic/word_254.png
```

**Comment by tink2123** [comment]
save_inference_model 这个api在1.7.1上有bug，请更新到paddle1.8.1试一下，抱歉

**Comment by lfxx** [comment]
> save_inference_model 这个api在1.7.1上有bug，请更新到paddle1.8.1试一下，抱歉

OCR这些模型支持1.8.1了吗,另外是不是意味着我需要重新训练模型?

**Comment by tink2123** [comment]
支持了～做了1.8.1的适配，不需要重新训练模型的

**Comment by lfxx** [comment]
> 支持了～做了1.8.1的适配，不需要重新训练模型的

好的,升级后,将模型重新导出,已经可以成功运行predict_rec.py了,效果很好,非常感谢

**Comment by tink2123** [comment]
不客气～我们会尽快更新文档说明

**Comment by kingwpf** [comment]
> 不是的，只要保持固定长度的输入即可，使用了自定义数据集，会默认对输入图片做变长处理，麻烦手动注释掉下面两行，保持固定输入
> https://github.com/PaddlePaddle/PaddleOCR/blob/f051be8657e46d16e4732cfadaa9951772c200a1/tools/infer/predict_rec.py#L54-L55

加tps的模型训练只能用固定的宽高比吗？

**Comment by kingwpf** [comment]
> save_inference_model 这个api在1.7.1上有bug，请更新到paddle1.8.1试一下，抱歉

我更新到paddlepaddle-gpu=1.8.1.post107后，用redict_rec.py预测单张图片还是会报shape不对的错误
`TPS does not support variable shape in chinese!We set img_shape to be the same , it may affect the inference effect
Traceback (most recent call last):
  File "tools/infer_rec.py", line 176, in <module>
    main()
  File "tools/infer_rec.py", line 71, in main
    _, outputs = rec_model(mode="test")
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/architectures/rec_model.py", line 189, in __call__
    inputs = self.tps(image)
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/stns/tps.py", line 254, in __call__
    batch_C_prime = self.loc_net(image)
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/stns/tps.py", line 86, in __call__
    image, num_filters, 3, act='relu', name=name)
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/stns/tps.py", line 51, in conv_bn_layer
    bias_attr=False)
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2933, in conv2d
    "data_format": data_format,
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1971, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ConvOp::ComputeOutputShape(paddle::framework::InferShapeContext*) const
3   paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/srwpf/miniconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 2933, in conv2d
    "data_format": data_format,
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/stns/tps.py", line 51, in conv_bn_layer
    bias_attr=False)
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/stns/tps.py", line 86, in __call__
    image, num_filters, 3, act='relu', name=name)
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/stns/tps.py", line 254, in __call__
    batch_C_prime = self.loc_net(image)
  File "/data2/srwpf/Projects/OCR/PaddleOCR/PaddleOCR/ppocr/modeling/architectures/rec_model.py", line 189, in __call__
    inputs = self.tps(image)
  File "tools/infer_rec.py", line 71, in main
    _, outputs = rec_model(mode="test")
  File "tools/infer_rec.py", line 176, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 32, 320].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] at (/paddle/paddle/fluid/operators/conv_op.cc:59)
  [operator < conv2d > error]
`
