### ISSUE TITLE
文本识别，训练出错 Fail to alloc memory of 391589504 size, error code is 12.请教

### ISSUE THREAD

**Issue by mybrew** [PaddlePaddle/PaddleOCR#2489]
我的电脑K4450A,联想昭阳,CPU-I7-4500; RAM-8G。文本识别自己数据训练。数据就1000张图。运行报内存不足，还请帮忙看看，谢谢。是配置不够吗？ CPU方式跑的。paddlepaddle-2.0.1 paddleOCR=2.00 
$ python3 tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/usr/local/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/usr/local/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
[2021/04/13 16:39:18] root INFO: Architecture :
[2021/04/13 16:39:18] root INFO:     Backbone :
[2021/04/13 16:39:18] root INFO:         layers : 34
[2021/04/13 16:39:18] root INFO:         name : ResNet
[2021/04/13 16:39:18] root INFO:     Head :
[2021/04/13 16:39:18] root INFO:         fc_decay : 4e-05
[2021/04/13 16:39:18] root INFO:         name : CTCHead
[2021/04/13 16:39:18] root INFO:     Neck :
[2021/04/13 16:39:18] root INFO:         encoder_type : rnn
[2021/04/13 16:39:18] root INFO:         hidden_size : 256
[2021/04/13 16:39:18] root INFO:         name : SequenceEncoder
[2021/04/13 16:39:18] root INFO:     Transform : None
[2021/04/13 16:39:18] root INFO:     algorithm : CRNN
[2021/04/13 16:39:18] root INFO:     model_type : rec
[2021/04/13 16:39:18] root INFO: Eval :
[2021/04/13 16:39:18] root INFO:     dataset :
[2021/04/13 16:39:18] root INFO:         data_dir : ./train_data/ic15_datamini/
[2021/04/13 16:39:18] root INFO:         label_file_list : ['./train_data/ic15_datamini/rec_gt_test.txt']
[2021/04/13 16:39:18] root INFO:         name : SimpleDataSet
[2021/04/13 16:39:18] root INFO:         transforms :
[2021/04/13 16:39:18] root INFO:             DecodeImage :
[2021/04/13 16:39:18] root INFO:                 channel_first : False
[2021/04/13 16:39:18] root INFO:                 img_mode : BGR
[2021/04/13 16:39:18] root INFO:             CTCLabelEncode : None
[2021/04/13 16:39:18] root INFO:             RecResizeImg :
[2021/04/13 16:39:18] root INFO:                 image_shape : [3, 32, 320]
[2021/04/13 16:39:18] root INFO:             KeepKeys :
[2021/04/13 16:39:18] root INFO:                 keep_keys : ['image', 'label', 'length']
[2021/04/13 16:39:18] root INFO:     loader :
[2021/04/13 16:39:18] root INFO:         batch_size_per_card : 256
[2021/04/13 16:39:18] root INFO:         drop_last : False
[2021/04/13 16:39:18] root INFO:         num_workers : 8
[2021/04/13 16:39:18] root INFO:         shuffle : False
[2021/04/13 16:39:18] root INFO: Global :
[2021/04/13 16:39:18] root INFO:     cal_metric_during_train : True
[2021/04/13 16:39:18] root INFO:     character_dict_path : ppocr/utils/ppocr_keys_v1.txt
[2021/04/13 16:39:18] root INFO:     character_type : ch
[2021/04/13 16:39:18] root INFO:     checkpoints : None
[2021/04/13 16:39:18] root INFO:     debug : False
[2021/04/13 16:39:18] root INFO:     distributed : False
[2021/04/13 16:39:18] root INFO:     epoch_num : 500
[2021/04/13 16:39:18] root INFO:     eval_batch_step : [0, 2000]
[2021/04/13 16:39:18] root INFO:     infer_img : doc/imgs_words/ch/word_1.jpg
[2021/04/13 16:39:18] root INFO:     infer_mode : False
[2021/04/13 16:39:18] root INFO:     log_smooth_window : 20
[2021/04/13 16:39:18] root INFO:     max_text_length : 25
[2021/04/13 16:39:18] root INFO:     pretrained_model : ./pretrain_models/ch_ppocr_server_v2.0_rec_pre/best_accuracy
[2021/04/13 16:39:18] root INFO:     print_batch_step : 10
[2021/04/13 16:39:18] root INFO:     save_epoch_step : 3
[2021/04/13 16:39:18] root INFO:     save_inference_dir : None
[2021/04/13 16:39:18] root INFO:     save_model_dir : ./output/rec_chinese_common_v2.0
[2021/04/13 16:39:18] root INFO:     use_gpu : False
[2021/04/13 16:39:18] root INFO:     use_space_char : True
[2021/04/13 16:39:18] root INFO:     use_visualdl : False
[2021/04/13 16:39:18] root INFO: Loss :
[2021/04/13 16:39:18] root INFO:     name : CTCLoss
[2021/04/13 16:39:18] root INFO: Metric :
[2021/04/13 16:39:18] root INFO:     main_indicator : acc
[2021/04/13 16:39:18] root INFO:     name : RecMetric
[2021/04/13 16:39:18] root INFO: Optimizer :
[2021/04/13 16:39:18] root INFO:     beta1 : 0.9
[2021/04/13 16:39:18] root INFO:     beta2 : 0.999
[2021/04/13 16:39:18] root INFO:     lr :
[2021/04/13 16:39:18] root INFO:         learning_rate : 0.001
[2021/04/13 16:39:18] root INFO:         name : Cosine
[2021/04/13 16:39:18] root INFO:     name : Adam
[2021/04/13 16:39:18] root INFO:     regularizer :
[2021/04/13 16:39:18] root INFO:         factor : 4e-05
[2021/04/13 16:39:18] root INFO:         name : L2
[2021/04/13 16:39:18] root INFO: PostProcess :
[2021/04/13 16:39:18] root INFO:     name : CTCLabelDecode
[2021/04/13 16:39:18] root INFO: Train :
[2021/04/13 16:39:18] root INFO:     dataset :
[2021/04/13 16:39:18] root INFO:         data_dir : ./train_data/ic15_datamini/
[2021/04/13 16:39:18] root INFO:         label_file_list : ['./train_data/ic15_datamini/rec_gt_train.txt']
[2021/04/13 16:39:18] root INFO:         name : SimpleDataSet
[2021/04/13 16:39:18] root INFO:         transforms :
[2021/04/13 16:39:18] root INFO:             DecodeImage :
[2021/04/13 16:39:18] root INFO:                 channel_first : False
[2021/04/13 16:39:18] root INFO:                 img_mode : BGR
[2021/04/13 16:39:18] root INFO:             RecAug : None
[2021/04/13 16:39:18] root INFO:             CTCLabelEncode : None
[2021/04/13 16:39:18] root INFO:             RecResizeImg :
[2021/04/13 16:39:18] root INFO:                 image_shape : [3, 32, 320]
[2021/04/13 16:39:18] root INFO:             KeepKeys :
[2021/04/13 16:39:18] root INFO:                 keep_keys : ['image', 'label', 'length']
[2021/04/13 16:39:18] root INFO:     loader :
[2021/04/13 16:39:18] root INFO:         batch_size_per_card : 256
[2021/04/13 16:39:18] root INFO:         drop_last : True
[2021/04/13 16:39:18] root INFO:         num_workers : 8
[2021/04/13 16:39:18] root INFO:         shuffle : True
[2021/04/13 16:39:18] root INFO: train with paddle 2.0.0 and device CPUPlace
[2021/04/13 16:39:18] root INFO: Initialize indexs of datasets:['./train_data/ic15_datamini/rec_gt_train.txt']
[2021/04/13 16:39:18] root INFO: Initialize indexs of datasets:['./train_data/ic15_datamini/rec_gt_test.txt']
[2021/04/13 16:39:22] root INFO: load pretrained model from ['./pretrain_models/ch_ppocr_server_v2.0_rec_pre/best_accuracy']
[2021/04/13 16:39:22] root INFO: train dataloader has 3 iters, valid dataloader has 4 iters
[2021/04/13 16:39:22] root INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
[2021/04/13 16:39:22] root INFO: Initialize indexs of datasets:['./train_data/ic15_datamini/rec_gt_train.txt']
W0413 17:00:47.943473  1625 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0413 17:01:24.133946  1625 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0413 17:01:32.315817  1625 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 97, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/inc052047/PaddleOCR/tools/program.py", line 210, in train
    preds = model(images)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/inc052047/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 74, in forward
    x = self.backbone(x)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/inc052047/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 284, in forward
    y = block(y)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/inc052047/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 171, in forward
    y = paddle.add(x=short, y=conv1)
  File "/usr/local/lib/python3.7/site-packages/paddle/tensor/math.py", line 289, in add
    x, y, axis=axis, op_name=op_type)
  File "<decorator-gen-119>", line 2, in _elementwise_op_in_dygraph
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/tensor/math.py", line 229, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
MemoryError: (ResourceExhausted) Fail to alloc memory of 391589504 size, error code is 12.
  [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/detail/system_allocator.cc:66)
  [operator < elementwise_add > error]

**Comment by WenmuZhou** [comment]
升级内存吧

**Comment by mybrew** [comment]
> 升级内存吧

谢谢，请问需要多大内存呢？能不能参考下你们的电脑是什么配置，或者有没有最低要求配置？

**Comment by lyhlyhl** [comment]
实在不行就先调低batch_size试试
