### ISSUE TITLE
训练res18 文字定位的时候提示 cuda  999错误。+

### ISSUE THREAD

**Issue by yfc886** [PaddlePaddle/PaddleOCR#2509]
[2021/04/15 07:32:41] root INFO: epoch: [1/1200], iter: 92, lr: 0.000333, loss: 6.348830, loss_shrink_maps: 4.409048, loss_threshold_maps: 1.084974, loss_binary_maps: 0.862995, reader_cost: 0.22711 s, batch_cost: 0.44850 s, samples: 8, ips: 8.91860
[2021/04/15 07:32:42] root INFO: epoch: [1/1200], iter: 94, lr: 0.000341, loss: 6.304469, loss_shrink_maps: 4.373852, loss_threshold_maps: 1.066532, loss_binary_maps: 0.859219, reader_cost: 0.25777 s, batch_cost: 0.47017 s, samples: 8, ips: 8.50761
[2021/04/15 07:32:44] root INFO: epoch: [1/1200], iter: 96, lr: 0.000349, loss: 6.281494, loss_shrink_maps: 4.369648, loss_threshold_maps: 1.057478, loss_binary_maps: 0.859219, reader_cost: 0.24214 s, batch_cost: 0.47115 s, samples: 8, ips: 8.48992
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "D:\PaddleOCR-release-2.0\tools\program.py", line 224, in train
    stats = {k: v.numpy().mean() for k, v in loss.items()}
  File "D:\PaddleOCR-release-2.0\tools\program.py", line 224, in <dictcomp>
    stats = {k: v.numpy().mean() for k, v in loss.items()}
OSError: (External)  Cuda error(999), unknown error.
  [Advise: Please search for the error code(999) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at D:\v2.0.1\paddle\paddle\fluid\platform\gpu_info.cc:301)

W0415 07:31:27.736148   672 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0415 07:31:27.845497   672 device_context.cc:372] device: 0, cuDNN Version: 8.0.
INFO 2021-04-15 07:32:54,029 launch_utils.py:307] terminate all the procs
ERROR 2021-04-15 07:32:54,029 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-04-15 07:32:57,033 launch_utils.py:307] terminate all the procs

**Comment by yfc886** [comment]
WINDOWS10 64位 专业版
内存：8+16
显卡：技嘉3060
cuda：11
