### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 24, 24] and the shape of Y = [1, 256, 23, 23]. Received [24] in X is not equal to [23] in Y at i:2.

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#2527]
python module.py
Traceback (most recent call last):
  File "module.py", line 157, in <module>
    res = ocr.predict(paths=image_path)
  File "/home/jitesh/Desktop/Web Services/PaddleOCR_2.1/ocr_det/module.py", line 92, in predict
    dt_boxes, elapse = self.text_detector(img)
  File "./tools/infer/predict_det.py", line 164, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 101, in <module>
      main()
    File "tools/export_model.py", line 96, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
      concrete_program, _ = self.get_concrete_program(*input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpn0h3o3uz.py", line 22, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/data/PaddleOCR_410/ppocr/modeling/architectures/base_model.py", line 76, in forward
      x = self.neck(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/data/PaddleOCR_410/ppocr/modeling/necks/pg_fpn.py", line 293, in forward
      g[1] = paddle.add(g[0], h[1])
    File "/usr/local/lib/python3.7/site-packages/paddle/tensor/math.py", line 281, in add
      return _elementwise_op(LayerHelper(op_type, **locals()))
    File "/usr/local/lib/python3.7/site-packages/paddle/tensor/math.py", line 258, in _elementwise_op
      'use_mkldnn': use_mkldnn})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 24, 24] and the shape of Y = [1, 256, 23, 23]. Received [24] in X is not equal to [23] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
      [operator < elementwise_add > error]

**Comment by Jitesh4389** [comment]
when i am run model.py it will give error

**Comment by NancyGu** [comment]
碰到了相同的问题

**Comment by starmemda** [comment]
Hi, I get the same problem, how should I solve it?
