### ISSUE TITLE
det训练出错了

### ISSUE THREAD

**Issue by wumeizhi** [PaddlePaddle/PaddleOCR#2559]
使用的命令是：
`python3.7 tools/train.py -c configs/det/det_r50_vd_db.yml -o Global.pretrain_weights=./pretrain_models/ResNet50_vd_ssld_pretrained/ 2>&1|tee train_det.log`

预训练模型是这个ResNet50_vd_ssld_pretrained

数据集用的是icda2019-LSVT的3w全标注图片

log如下：

- **grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2021/04/20 00:59:14] root INFO: Architecture : 
[2021/04/20 00:59:14] root INFO:     Backbone : 
[2021/04/20 00:59:14] root INFO:         layers : 50
[2021/04/20 00:59:14] root INFO:         name : ResNet
[2021/04/20 00:59:14] root INFO:     Head : 
[2021/04/20 00:59:14] root INFO:         k : 50
[2021/04/20 00:59:14] root INFO:         name : DBHead
[2021/04/20 00:59:14] root INFO:     Neck : 
[2021/04/20 00:59:14] root INFO:         name : DBFPN
[2021/04/20 00:59:14] root INFO:         out_channels : 256
[2021/04/20 00:59:14] root INFO:     Transform : None
[2021/04/20 00:59:14] root INFO:     algorithm : DB
[2021/04/20 00:59:14] root INFO:     model_type : det
[2021/04/20 00:59:14] root INFO: Eval : 
[2021/04/20 00:59:14] root INFO:     dataset : 
[2021/04/20 00:59:14] root INFO:         data_dir : ./train_data/icdar2015/text_localization/
[2021/04/20 00:59:14] root INFO:         label_file_list : ['./train_data/icdar2015/text_localization/test_icdar2015_label.txt']
[2021/04/20 00:59:14] root INFO:         name : SimpleDataSet
[2021/04/20 00:59:14] root INFO:         transforms : 
[2021/04/20 00:59:14] root INFO:             DecodeImage : 
[2021/04/20 00:59:14] root INFO:                 channel_first : False
[2021/04/20 00:59:14] root INFO:                 img_mode : BGR
[2021/04/20 00:59:14] root INFO:             DetLabelEncode : None
[2021/04/20 00:59:14] root INFO:             DetResizeForTest : 
[2021/04/20 00:59:14] root INFO:                 image_shape : [736, 1280]
[2021/04/20 00:59:14] root INFO:             NormalizeImage : 
[2021/04/20 00:59:14] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/04/20 00:59:14] root INFO:                 order : hwc
[2021/04/20 00:59:14] root INFO:                 scale : 1./255.
[2021/04/20 00:59:14] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/04/20 00:59:14] root INFO:             ToCHWImage : None
[2021/04/20 00:59:14] root INFO:             KeepKeys : 
[2021/04/20 00:59:14] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2021/04/20 00:59:14] root INFO:     loader : 
[2021/04/20 00:59:14] root INFO:         batch_size_per_card : 1
[2021/04/20 00:59:14] root INFO:         drop_last : False
[2021/04/20 00:59:14] root INFO:         num_workers : 8
[2021/04/20 00:59:14] root INFO:         shuffle : False
[2021/04/20 00:59:14] root INFO: Global : 
[2021/04/20 00:59:14] root INFO:     cal_metric_during_train : False
[2021/04/20 00:59:14] root INFO:     checkpoints : None
[2021/04/20 00:59:14] root INFO:     debug : False
[2021/04/20 00:59:14] root INFO:     distributed : False
[2021/04/20 00:59:14] root INFO:     epoch_num : 1200
[2021/04/20 00:59:14] root INFO:     eval_batch_step : [0, 2000]
[2021/04/20 00:59:14] root INFO:     infer_img : doc/imgs_en/img_10.jpg
[2021/04/20 00:59:14] root INFO:     load_static_weights : True
[2021/04/20 00:59:14] root INFO:     log_smooth_window : 20
[2021/04/20 00:59:14] root INFO:     pretrain_weights : ./pretrain_models/ResNet50_vd_ssld_pretrained/
[2021/04/20 00:59:14] root INFO:     pretrained_model : ./pretrain_models/ResNet50_vd_ssld_pretrained
[2021/04/20 00:59:14] root INFO:     print_batch_step : 10
[2021/04/20 00:59:14] root INFO:     save_epoch_step : 1200
[2021/04/20 00:59:14] root INFO:     save_inference_dir : None
[2021/04/20 00:59:14] root INFO:     save_model_dir : ./output/det_r50_vd/
[2021/04/20 00:59:14] root INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2021/04/20 00:59:14] root INFO:     use_gpu : True
[2021/04/20 00:59:14] root INFO:     use_visualdl : False
[2021/04/20 00:59:14] root INFO: Loss : 
[2021/04/20 00:59:14] root INFO:     alpha : 5
[2021/04/20 00:59:14] root INFO:     balance_loss : True
[2021/04/20 00:59:14] root INFO:     beta : 10
[2021/04/20 00:59:14] root INFO:     main_loss_type : DiceLoss
[2021/04/20 00:59:14] root INFO:     name : DBLoss
[2021/04/20 00:59:14] root INFO:     ohem_ratio : 3
[2021/04/20 00:59:14] root INFO: Metric : 
[2021/04/20 00:59:14] root INFO:     main_indicator : hmean
[2021/04/20 00:59:14] root INFO:     name : DetMetric
[2021/04/20 00:59:14] root INFO: Optimizer : 
[2021/04/20 00:59:14] root INFO:     beta1 : 0.9
[2021/04/20 00:59:14] root INFO:     beta2 : 0.999
[2021/04/20 00:59:14] root INFO:     lr : 
[2021/04/20 00:59:14] root INFO:         learning_rate : 0.001
[2021/04/20 00:59:14] root INFO:     name : Adam
[2021/04/20 00:59:14] root INFO:     regularizer : 
[2021/04/20 00:59:14] root INFO:         factor : 0
[2021/04/20 00:59:14] root INFO:         name : L2
[2021/04/20 00:59:14] root INFO: PostProcess : 
[2021/04/20 00:59:14] root INFO:     box_thresh : 0.7
[2021/04/20 00:59:14] root INFO:     max_candidates : 1000
[2021/04/20 00:59:14] root INFO:     name : DBPostProcess
[2021/04/20 00:59:14] root INFO:     thresh : 0.3
[2021/04/20 00:59:14] root INFO:     unclip_ratio : 1.5
[2021/04/20 00:59:14] root INFO: Train : 
[2021/04/20 00:59:14] root INFO:     dataset : 
[2021/04/20 00:59:14] root INFO:         data_dir : ./train_data/icdar2015/text_localization/
[2021/04/20 00:59:14] root INFO:         label_file_list : ['./train_data/icdar2015/text_localization/train_icdar2015_label.txt']
[2021/04/20 00:59:14] root INFO:         name : SimpleDataSet
[2021/04/20 00:59:14] root INFO:         ratio_list : [1.0]
[2021/04/20 00:59:14] root INFO:         transforms : 
[2021/04/20 00:59:14] root INFO:             DecodeImage : 
[2021/04/20 00:59:14] root INFO:                 channel_first : False
[2021/04/20 00:59:14] root INFO:                 img_mode : BGR
[2021/04/20 00:59:14] root INFO:             DetLabelEncode : None
[2021/04/20 00:59:14] root INFO:             IaaAugment : 
[2021/04/20 00:59:14] root INFO:                 augmenter_args : 
[2021/04/20 00:59:14] root INFO:                     args : 
[2021/04/20 00:59:14] root INFO:                         p : 0.5
[2021/04/20 00:59:14] root INFO:                     type : Fliplr
[2021/04/20 00:59:14] root INFO:                     args : 
[2021/04/20 00:59:14] root INFO:                         rotate : [-10, 10]
[2021/04/20 00:59:14] root INFO:                     type : Affine
[2021/04/20 00:59:14] root INFO:                     args : 
[2021/04/20 00:59:14] root INFO:                         size : [0.5, 3]
[2021/04/20 00:59:14] root INFO:                     type : Resize
[2021/04/20 00:59:14] root INFO:             EastRandomCropData : 
[2021/04/20 00:59:14] root INFO:                 keep_ratio : True
[2021/04/20 00:59:14] root INFO:                 max_tries : 50
[2021/04/20 00:59:14] root INFO:                 size : [640, 640]
[2021/04/20 00:59:14] root INFO:             MakeBorderMap : 
[2021/04/20 00:59:14] root INFO:                 shrink_ratio : 0.4
[2021/04/20 00:59:14] root INFO:                 thresh_max : 0.7
[2021/04/20 00:59:14] root INFO:                 thresh_min : 0.3
[2021/04/20 00:59:14] root INFO:             MakeShrinkMap : 
[2021/04/20 00:59:14] root INFO:                 min_text_size : 8
[2021/04/20 00:59:14] root INFO:                 shrink_ratio : 0.4
[2021/04/20 00:59:14] root INFO:             NormalizeImage : 
[2021/04/20 00:59:14] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/04/20 00:59:14] root INFO:                 order : hwc
[2021/04/20 00:59:14] root INFO:                 scale : 1./255.
[2021/04/20 00:59:14] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/04/20 00:59:14] root INFO:             ToCHWImage : None
[2021/04/20 00:59:14] root INFO:             KeepKeys : 
[2021/04/20 00:59:14] root INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2021/04/20 00:59:14] root INFO:     loader : 
[2021/04/20 00:59:14] root INFO:         batch_size_per_card : 16
[2021/04/20 00:59:14] root INFO:         drop_last : False
[2021/04/20 00:59:14] root INFO:         num_workers : 8
[2021/04/20 00:59:14] root INFO:         shuffle : True
[2021/04/20 00:59:14] root INFO: train with paddle 2.0.2 and device CUDAPlace(0)
[2021/04/20 00:59:14] root INFO: Initialize indexs of datasets:['./train_data/icdar2015/text_localization/train_icdar2015_label.txt']
[2021/04/20 00:59:14] root INFO: Initialize indexs of datasets:['./train_data/icdar2015/text_localization/test_icdar2015_label.txt']
W0420 00:59:14.583199 28999 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.3, Runtime API Version: 10.1
W0420 00:59:14.588254 28999 device_context.cc:372] device: 0, cuDNN Version: 7.6.
[2021/04/20 00:59:16] root INFO: load pretrained model from ['./pretrain_models/ResNet50_vd_ssld_pretrained']
[2021/04/20 00:59:16] root INFO: train dataloader has 1875 iters, valid dataloader has 500 iters
[2021/04/20 00:59:16] root INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
[2021/04/20 00:59:16] root INFO: Initialize indexs of datasets:['./train_data/icdar2015/text_localization/train_icdar2015_label.txt']
/usr/local/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2021-04-20 00:59:22,064 - ERROR - DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 97, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/PaddleOCR/tools/program.py", line 199, in train
    for idx, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)**

求大佬康康是哪里的问题

**Comment by littletomatodonkey** [comment]
把配置文件里的num worker改为0试下，

**Comment by liyandongpy** [comment]
> 把配置文件里的num worker改为0试下，

确实有效，但是是什么原因呢？
