### ISSUE TITLE
跑文字检测报错

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#259]
2020-06-23 15:51:25,957-INFO: test tackling num:11
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main()
  File "tools/train.py", line 104, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 258, in train_eval_det_run
    metrics = eval_det_run(exe, config, eval_info_dict, "eval")
  File "/home/aistudio/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 129, in eval_det_run
    cal_det_res(exe, config, eval_info_dict)
  File "/home/aistudio/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 62, in cal_det_res
    img_list = np.concatenate(img_list, axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by MissPenguin** [comment]
这是因为一个batch中的测试图像size不同，无法进行concatenate，可以把配置文件中的test_batch_size_per_card参数改成1

**Comment by Sunyingbin** [comment]
> 这是因为一个batch中的测试图像size不同，无法进行concatenate，可以把配置文件中的test_batch_size_per_card参数改成1

好的，非常感谢
