### ISSUE TITLE
AttributeError: module 'gast' has no attribute 'Index'

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleOCR#2602]
/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py:461: UserWarning: Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it.
  "Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it."
/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
W0423 10:12:22.840014  4939 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.0
W0423 10:12:22.844841  4939 device_context.cc:372] device: 0, cuDNN Version: 7.6.
[2021/04/23 10:12:26] root INFO: load pretrained model from ['./output/rec/ic15/iter_epoch_990']
Traceback (most recent call last):
  File "tools/export_model.py", line 93, in <module>
    main()
  File "tools/export_model.py", line 88, in main
    paddle.jit.save(model, save_path)
  File "<decorator-gen-60>", line 2, in save
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 681, in save
    inner_input_spec)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "/tmp/tmp7akqky3y.py", line 22, in forward
	false_fn_1, (x,), (x,), (x,))
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/data/wei/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 76, in forward (* user code *)
	x = self.neck(x)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/data/wei/PaddleOCR/ppocr/modeling/necks/rnn.py", line 89, in forward (* user code *)
	x = self.encoder_reshape(x)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 220, in convert_call
	forward_func = convert_to_static(forward_func)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
	static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
	static_func = self._convert(func)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 116, in _convert
	root_wrapper = self._dygraph_to_static.get_static_ast(root)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 61, in get_static_ast
	self.transfer_from_node_type(self.static_analysis_root)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 92, in transfer_from_node_type
	self._apply(transformer, node_wrapper, log_level=index + 1)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 65, in _apply
	transformer(node_wrapper).transform()
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 118, in transform
	self.visit(self.root)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/ast.py", line 271, in visit
	return visitor(node)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/ast.py", line 326, in generic_visit
	value = self.visit(value)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/ast.py", line 271, in visit
	return visitor(node)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/ast.py", line 326, in generic_visit
	value = self.visit(value)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/ast.py", line 271, in visit
	return visitor(node)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 121, in visit_Assign
	update_static_shape_var_node = self._update_name_to_var_shape(node)
    File "/opt/Anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 346, in _update_name_to_var_shape
	slice_index_node = gast.Index(value=index_value_node)
    AttributeError: module 'gast' has no attribute 'Index'

**Comment by jery0711** [comment]
look at this link, maybe usful.  https://github.com/PaddlePaddle/PaddleOCR/issues/2320

**Comment by JiaXiao243** [comment]
降低gast的版本即可，
python -m pip install gast==0.3.3

**Comment by weiaoliu** [comment]
好的，改天我试下，好像当时我降了版本，好像还是有问题，

**Comment by weiaoliu** [comment]
@JiaXiao243 好的，好像当时我把gast的版本降了，还是有问题，具体我再试试

**Comment by lxhmark7** [comment]
版本问题：gast版本太高了，降低gast的版本即可，
pip uninstall gast
pip install gast==0.3.3
