### ISSUE TITLE
pgnet model is wrong

### ISSUE THREAD

**Issue by gachiemchiep** [PaddlePaddle/PaddleOCR#2616]
Hello guys.
Thank you for your great work.
I tried the pg-net at [pgnet_en.md](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/pgnet_en.md), but somehow the models are corrupted. 
Would you mind update the link to model.

```bash
(ocr-py3) gachiemchiep:PaddleOCR$ python tools/infer/predict_e2e.py --e2e_algorithm="PGNet" --image_dir="/datadrive/workspace/aisin-ocr/datasets/icdar-2015/ch4_test_images" --e2e_model_dir="./inference/e2e_server_pgnetA_infer/" --e2e_pgnet_polygon=True
/home/gachiemchiep/miniconda3/envs/ocr-py3/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "tools/infer/predict_e2e.py", line 134, in <module>
    text_detector = TextE2E(args)
  File "tools/infer/predict_e2e.py", line 78, in __init__
    args, 'e2e', logger)  # paddle.jit.load(args.det_model_dir)
  File "/datadrive/workspace/aisin-ocr/PaddleOCR/tools/infer/utility.py", line 160, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 3122563555 found).
  [Hint: Expected version == 0U, but received version:3122563555 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:313)
  [operator < load_combine > error]

```

**Comment by littletomatodonkey** [comment]
Thanks for your attention, `export model.py` must be carried out before inference, please check whether the inference model is exported and saved in the dir `inference/e2e/`.

```shell
python3 tools/export_model.py -c configs/e2e/e2e_r50_vd_pg.yml -o Global.pretrained_model=./en_server_pgnetA/best_accuracy Global.load_static_weights=False Global.save_inference_dir=./inference/e2e
```

Information of the inference model dir is as follows.

```
drwxr-xr-x 2 root root 4.0K Apr 24 07:39 ./
drwxr-xr-x 5 root root 4.0K Apr 24 07:39 ../
-rw-r--r-- 1 root root 186M Apr 24 07:39 inference.pdiparams
-rw-r--r-- 1 root root  44K Apr 24 07:39 inference.pdiparams.info
-rw-r--r-- 1 root root 1.5M Apr 24 07:39 inference.pdmodel
```

**Comment by gachiemchiep** [comment]
Hello  @littletomatodonkey 
I don't train new models, I used the model file provided by your team. 
I checked files inside *https://paddleocr.bj.bcebos.com/dygraph_v2.0/pgnet/e2e_server_pgnetA_infer.tar* file. All of them are converted. 

```bash
(base) gachiemchiep:tmp$ ls -al e2e_server_pgnetA_infer
total 191188
drwxr-xr-x 2 gachiemchiep gachiemchiep      4096  4月 10 16:03 .
drwxrwxr-x 3 gachiemchiep gachiemchiep      4096  4月 24 16:11 ..
-rw-r--r-- 1 gachiemchiep gachiemchiep 194144159  4月 10 16:03 inference.pdiparams
-rw-r--r-- 1 gachiemchiep gachiemchiep     44297  4月 10 16:03 inference.pdiparams.info
-rw-r--r-- 1 gachiemchiep gachiemchiep   1573368  4月 10 16:03 inference.pdmodel

```
