### ISSUE TITLE
docker镜像中修改ocr_system的module.py之后ImportError: No module named 'tools'

### ISSUE THREAD

**Issue by Hathaway2019** [PaddlePaddle/PaddleOCR#2637]
Traceback (most recent call last):
  File "/usr/local/python3.5.1/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/serving.py", line 413, in execute
    self.start_serving()
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/serving.py", line 360, in start_serving
    self.start_single_app_with_args()
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/serving.py", line 275, in start_single_app_with_args
    self.preinstall_modules()
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/serving.py", line 205, in preinstall_modules
    m = hub.Module(**init_args)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/module.py", line 171, in init_with_name
    module_name=name, module_version=version, extra=extra)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/manager.py", line 127, in install_module
    self.all_modules(update=True)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/manager.py", line 72, in check_module_valid
    "{}.module".format(basename))
  File "/usr/local/python3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.paddlehub/modules/ocr_system/module.py", line 19, in <module>
    from tools.infer.utility import base64_to_cv2
ImportError: No module named 'tools'

**Comment by LDOUBLEV** [comment]
怎么修改的呢？
要在PaddleOCR目录下运行，tools是一个目录

**Comment by Hathaway2019** [comment]
好的&nbsp; 可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月26日(周一) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] docker镜像中修改ocr_system的module.py之后ImportError: No module named 'tools' (#2637)




 
怎么修改的呢？
 要在PaddleOCR目录下运行，tools是一个目录
