### ISSUE TITLE
paddleocr 使用paddleslim出现的问题

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleOCR#2673]
https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/slim/prune

按照相关教程进行模型裁剪 量化  进行测试发现如下报错，想知道是什么原因呢？

python deploy/slim/prune/sensitivity_anal.py -c configs/det/ch_ppocr_v2.0/ch_det_res18_db_v2.0.yml -o Global.pretrain_weights="/inference/ch_ppocr_server_v2.0_det_infer" 
[2021/04/28 10:08:25] root INFO: Architecture : 
[2021/04/28 10:08:25] root INFO:     Backbone : 
[2021/04/28 10:08:25] root INFO:         disable_se : True
[2021/04/28 10:08:25] root INFO:         layers : 18
[2021/04/28 10:08:25] root INFO:         name : ResNet
[2021/04/28 10:08:25] root INFO:     Head : 
[2021/04/28 10:08:25] root INFO:         k : 50
[2021/04/28 10:08:25] root INFO:         name : DBHead
[2021/04/28 10:08:25] root INFO:     Neck : 
[2021/04/28 10:08:25] root INFO:         name : DBFPN
[2021/04/28 10:08:25] root INFO:         out_channels : 256
[2021/04/28 10:08:25] root INFO:     Transform : None
[2021/04/28 10:08:25] root INFO:     algorithm : DB
[2021/04/28 10:08:25] root INFO:     model_type : det
[2021/04/28 10:08:25] root INFO: Eval : 
[2021/04/28 10:08:25] root INFO:     dataset : 
[2021/04/28 10:08:25] root INFO:         data_dir : ./train_data/det_data/datanonghang2/
[2021/04/28 10:08:25] root INFO:         label_file_list : ['./train_data/det_data/datanonghang2/a_rotate/val.txt', './train_data/det_data/datanonghang2/resize_imgs _no1/val.txt', './train_data/det_data/datanonghang2/scan/val.txt', './train_data/det_data/datanonghang2/表格 瞎写/val.txt']
[2021/04/28 10:08:25] root INFO:         name : SimpleDataSet
[2021/04/28 10:08:25] root INFO:         ratio_list : [0.3, 0.2, 0.2, 0.3]
[2021/04/28 10:08:25] root INFO:         transforms : 
[2021/04/28 10:08:25] root INFO:             DecodeImage : 
[2021/04/28 10:08:25] root INFO:                 channel_first : False
[2021/04/28 10:08:25] root INFO:                 img_mode : BGR
[2021/04/28 10:08:25] root INFO:             DetLabelEncode : None
[2021/04/28 10:08:25] root INFO:             DetResizeForTest : None
[2021/04/28 10:08:25] root INFO:             NormalizeImage : 
[2021/04/28 10:08:25] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/04/28 10:08:25] root INFO:                 order : hwc
[2021/04/28 10:08:25] root INFO:                 scale : 1./255.
[2021/04/28 10:08:25] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/04/28 10:08:25] root INFO:             ToCHWImage : None
[2021/04/28 10:08:25] root INFO:             KeepKeys : 
[2021/04/28 10:08:25] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2021/04/28 10:08:25] root INFO:     loader : 
[2021/04/28 10:08:25] root INFO:         batch_size_per_card : 1
[2021/04/28 10:08:25] root INFO:         drop_last : False
[2021/04/28 10:08:25] root INFO:         num_workers : 2
[2021/04/28 10:08:25] root INFO:         shuffle : False
[2021/04/28 10:08:25] root INFO: Global : 
[2021/04/28 10:08:25] root INFO:     cal_metric_during_train : False
[2021/04/28 10:08:25] root INFO:     checkpoints : None
[2021/04/28 10:08:25] root INFO:     debug : False
[2021/04/28 10:08:25] root INFO:     distributed : False
[2021/04/28 10:08:25] root INFO:     epoch_num : 1200
[2021/04/28 10:08:25] root INFO:     eval_batch_step : [3000, 2000]
[2021/04/28 10:08:25] root INFO:     infer_img : doc/imgs_en/img_10.jpg
[2021/04/28 10:08:25] root INFO:     load_static_weights : True
[2021/04/28 10:08:25] root INFO:     log_smooth_window : 20
[2021/04/28 10:08:25] root INFO:     pretrain_weights : /inference/ch_ppocr_server_v2.0_det_infer
[2021/04/28 10:08:25] root INFO:     pretrained_model : ./pretrain_models/ResNet18_vd_pretrained
[2021/04/28 10:08:25] root INFO:     print_batch_step : 2
[2021/04/28 10:08:25] root INFO:     save_epoch_step : 1200
[2021/04/28 10:08:25] root INFO:     save_inference_dir : None
[2021/04/28 10:08:25] root INFO:     save_model_dir : ./output/ch_db_res18/
[2021/04/28 10:08:25] root INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2021/04/28 10:08:25] root INFO:     use_gpu : True
[2021/04/28 10:08:25] root INFO:     use_visualdl : False
[2021/04/28 10:08:25] root INFO: Loss : 
[2021/04/28 10:08:25] root INFO:     alpha : 5
[2021/04/28 10:08:25] root INFO:     balance_loss : True
[2021/04/28 10:08:25] root INFO:     beta : 10
[2021/04/28 10:08:25] root INFO:     main_loss_type : DiceLoss
[2021/04/28 10:08:25] root INFO:     name : DBLoss
[2021/04/28 10:08:25] root INFO:     ohem_ratio : 3
[2021/04/28 10:08:25] root INFO: Metric : 
[2021/04/28 10:08:25] root INFO:     main_indicator : hmean
[2021/04/28 10:08:25] root INFO:     name : DetMetric
[2021/04/28 10:08:25] root INFO: Optimizer : 
[2021/04/28 10:08:25] root INFO:     beta1 : 0.9
[2021/04/28 10:08:25] root INFO:     beta2 : 0.999
[2021/04/28 10:08:25] root INFO:     lr : 
[2021/04/28 10:08:25] root INFO:         learning_rate : 0.001
[2021/04/28 10:08:25] root INFO:         name : Cosine
[2021/04/28 10:08:25] root INFO:         warmup_epoch : 2
[2021/04/28 10:08:25] root INFO:     name : Adam
[2021/04/28 10:08:25] root INFO:     regularizer : 
[2021/04/28 10:08:25] root INFO:         factor : 0
[2021/04/28 10:08:25] root INFO:         name : L2
[2021/04/28 10:08:25] root INFO: PostProcess : 
[2021/04/28 10:08:25] root INFO:     box_thresh : 0.6
[2021/04/28 10:08:25] root INFO:     max_candidates : 1000
[2021/04/28 10:08:25] root INFO:     name : DBPostProcess
[2021/04/28 10:08:25] root INFO:     thresh : 0.3
[2021/04/28 10:08:25] root INFO:     unclip_ratio : 1.5
[2021/04/28 10:08:25] root INFO: Train : 
[2021/04/28 10:08:25] root INFO:     dataset : 
[2021/04/28 10:08:25] root INFO:         data_dir : ./train_data/det_data/datanonghang2/
[2021/04/28 10:08:25] root INFO:         label_file_list : ['./train_data/det_data/datanonghang2/a_rotate/train.txt', './train_data/det_data/datanonghang2/resize_imgs _no1/train.txt', './train_data/det_data/datanonghang2/scan/train.txt', './train_data/det_data/datanonghang2/表格 瞎写/train.txt']
[2021/04/28 10:08:25] root INFO:         name : SimpleDataSet
[2021/04/28 10:08:25] root INFO:         ratio_list : [0.3, 0.2, 0.2, 0.3]
[2021/04/28 10:08:25] root INFO:         transforms : 
[2021/04/28 10:08:25] root INFO:             DecodeImage : 
[2021/04/28 10:08:25] root INFO:                 channel_first : False
[2021/04/28 10:08:25] root INFO:                 img_mode : BGR
[2021/04/28 10:08:25] root INFO:             DetLabelEncode : None
[2021/04/28 10:08:25] root INFO:             IaaAugment : 
[2021/04/28 10:08:25] root INFO:                 augmenter_args : 
[2021/04/28 10:08:25] root INFO:                     args : 
[2021/04/28 10:08:25] root INFO:                         p : 0.5
[2021/04/28 10:08:25] root INFO:                     type : Fliplr
[2021/04/28 10:08:25] root INFO:                     args : 
[2021/04/28 10:08:25] root INFO:                         rotate : [-10, 10]
[2021/04/28 10:08:25] root INFO:                     type : Affine
[2021/04/28 10:08:25] root INFO:                     args : 
[2021/04/28 10:08:25] root INFO:                         size : [0.5, 3]
[2021/04/28 10:08:25] root INFO:                     type : Resize
[2021/04/28 10:08:25] root INFO:             EastRandomCropData : 
[2021/04/28 10:08:25] root INFO:                 keep_ratio : True
[2021/04/28 10:08:25] root INFO:                 max_tries : 50
[2021/04/28 10:08:25] root INFO:                 size : [960, 960]
[2021/04/28 10:08:25] root INFO:             MakeBorderMap : 
[2021/04/28 10:08:25] root INFO:                 shrink_ratio : 0.4
[2021/04/28 10:08:25] root INFO:                 thresh_max : 0.7
[2021/04/28 10:08:25] root INFO:                 thresh_min : 0.3
[2021/04/28 10:08:25] root INFO:             MakeShrinkMap : 
[2021/04/28 10:08:25] root INFO:                 min_text_size : 8
[2021/04/28 10:08:25] root INFO:                 shrink_ratio : 0.4
[2021/04/28 10:08:25] root INFO:             NormalizeImage : 
[2021/04/28 10:08:25] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/04/28 10:08:25] root INFO:                 order : hwc
[2021/04/28 10:08:25] root INFO:                 scale : 1./255.
[2021/04/28 10:08:25] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/04/28 10:08:25] root INFO:             ToCHWImage : None
[2021/04/28 10:08:25] root INFO:             KeepKeys : 
[2021/04/28 10:08:25] root INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2021/04/28 10:08:25] root INFO:     loader : 
[2021/04/28 10:08:25] root INFO:         batch_size_per_card : 8
[2021/04/28 10:08:25] root INFO:         drop_last : False
[2021/04/28 10:08:25] root INFO:         num_workers : 4
[2021/04/28 10:08:25] root INFO:         shuffle : True
[2021/04/28 10:08:25] root INFO: train with paddle 0.0.0 and device CUDAPlace(0)
[2021/04/28 10:08:25] root INFO: Initialize indexs of datasets:['./train_data/det_data/datanonghang2/a_rotate/train.txt', './train_data/det_data/datanonghang2/resize_imgs _no1/train.txt', './train_data/det_data/datanonghang2/scan/train.txt', './train_data/det_data/datanonghang2/表格 瞎写/train.txt']
[2021/04/28 10:08:25] root INFO: Initialize indexs of datasets:['./train_data/det_data/datanonghang2/a_rotate/val.txt', './train_data/det_data/datanonghang2/resize_imgs _no1/val.txt', './train_data/det_data/datanonghang2/scan/val.txt', './train_data/det_data/datanonghang2/表格 瞎写/val.txt']
W0428 10:08:25.388952 156016 device_context.cc:342] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 9.0
W0428 10:08:25.391474 156016 device_context.cc:352] device: 0, cuDNN Version: 7.6.
<class 'paddle.nn.layer.pooling.AvgPool2D'>'s flops has been counted
<class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
<class 'paddle.fluid.dygraph.nn.BatchNorm'>'s flops has been counted
Cannot find suitable count function for <class 'paddle.nn.layer.pooling.MaxPool2D'>. Treat it as zero FLOPs.
<class 'paddle.nn.layer.conv.Conv2DTranspose'>'s flops has been counted
Traceback (most recent call last):
  File "deploy/slim/prune/sensitivity_anal.py", line 146, in <module>
    main(config, device, logger, vdl_writer)
  File "deploy/slim/prune/sensitivity_anal.py", line 77, in main
    flops = paddle.flops(model, [1, 3, 640, 640])
  File "/root/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py", line 108, in flops
    print_detail=print_detail)
  File "/root/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py", line 282, in dynamic_flops
    m.full_name(), list(m.input_shape.numpy()),
  File "/root/anaconda3/envs/ppocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1039, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'AvgPool2D' object has no attribute 'input_shape'

**Comment by LDOUBLEV** [comment]
你的paddle版本和paddleslim 版本是？建议用paddle>=2.0版本。paddleslim 2.0.0版本

**Comment by mingo-doer** [comment]
> 你的paddle版本和paddleslim 版本是？建议用paddle>=2.0版本。paddleslim 2.0.0版本
> 看报错是paddle.flops这个API 有问题，可以更新paddle版本试下

这个问题的确是版本问题，目前已解决

大佬知道为什么hmean 会出现=0吗？
![image](https://user-images.githubusercontent.com/28819717/116378294-953d5800-a844-11eb-9586-f27ef9c804d9.png)
