### ISSUE TITLE
docker hubserving 安装cpu版成功，但担示要安paddlepaddle-gpu，之后安装ocr_system又报Illegal instruction

### ISSUE THREAD

**Issue by wjtien** [PaddlePaddle/PaddleOCR#2675]
1先上我的Docker文件：
`FROM registry.baidubce.com/paddlepaddle/paddle:2.0.2

RUN pip3.8 install --upgrade pip -i https://mirror.baidu.com/pypi/simple
RUN pip3.8 install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple

ADD ./PaddleOCR /PaddleOCR

WORKDIR /PaddleOCR

RUN pip3.8 install -r requirements.txt -i https://mirror.baidu.com/pypi/simple

RUN mkdir -p /PaddleOCR/inference/

ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_server_v2.0_det_infer.tar -C /PaddleOCR/inference/

ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer.tar -C /PaddleOCR/inference/

ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer.tar -C /PaddleOCR/inference/

EXPOSE 8868`

2：
从git克隆PaddleOCR，和Docker文件在一起

`sudo docker build -f Dockerfile .`

3运行刚才的镜像：
`docker run --name ppocr -v /data/docker_volume:/paddle --network=host -it -p 8868:8868 799679c62073 /bin/bash`

4在镜像中运行：
 `hub install deploy/hubserving/ocr_system/`
4.1报错
`λ tian /PaddleOCR {release/2.1} hub install deploy/hubserving/ocr_system/
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
Error: AVX is not support on your machine, but you have installed paddlepaddle with avx core, you should reinstall paddlepaddle by 'python -m pip install -U paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/stable_noavx.html'
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/lib/python3.8/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
  File "/usr/local/lib/python3.8/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 36, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 349, in <module>
    raise e
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 308, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
`
4.2我执行了安装命令：
`python3.8 -m pip install -U paddlepaddle-gpu -f https://paddlepaddle.org.cn/whl/stable_noavx.html`

5最后执行报：
`hub install deploy/hubserving/ocr_system/
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
Illegal instruction (core dumped)
`
5.1我的CPU信息（是cpu太老吗？）：
`processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 6
model name      : AMD Athlon(tm) II X2 220 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 1600.000
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs            : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips        : 5625.09
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 6
model name      : AMD Athlon(tm) II X2 220 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 1600.000
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs            : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips        : 5625.09
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate`

**我该怎么办？**

**Comment by wjtien** [comment]
关闭吧
a. Docker环境
b. 显卡驱动和CUDA 10.0+（GPU）
c. NVIDIA Container Toolkit（GPU，Docker 19.03以上版本可以跳过此步）
d. cuDNN 7.6+（GPU）

我这b和d都不满足
