### ISSUE TITLE
'Namespace' object has no attribute 'det_db_score_mode'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2711]
python3 PPOCRLabel.py --lang ch

--------
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2077, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2065, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2058, in get_main_app
    defaultPrefdefClassFile=args.predefined_classes_file)
  File "PPOCRLabel.py", line 111, in __init__
    self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=True, det=True, cls=True, use_gpu=False, lang=lang)
  File "d:\anaconda3\envs\PaddleOCR\lib\site-packages\paddleocr\paddleocr.py", line 345, in __init__
    super().__init__(postprocess_params)
  File "..\tools\infer\predict_system.py", line 42, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "..\tools\infer\predict_det.py", line 65, in __init__
    postprocess_params["score_mode"] = args.det_db_score_mode
AttributeError: 'Namespace' object has no attribute 'det_db_score_mode'

**Comment by littletomatodonkey** [comment]
你好，可以拉下最新代码看下，这个问题已经修了

**Comment by xiaohuang1227** [comment]
> 你好，可以拉下最新代码看下，这个问题已经修了
你好，我下载了最新代码，还是有这个问题。我是在ubuntu18.04使用的。

**Comment by Paul-Neilson** [comment]
请问解决了吗？
