### ISSUE TITLE
ImportError: cannot import name 'inference'

### ISSUE THREAD

**Issue by yjdqk** [PaddlePaddle/PaddleOCR#2743]
File "../tools/infer/utility.py", line 23, in <module>
from paddle import inference
ImportError: cannot import name 'inference'

**Comment by omrastogi** [comment]
如何安装 Paddle2.0 版本. "pip install paddle==2.0"不管用

**Comment by wshzd** [comment]
Paddle2.0 版本应该这样安装 "pip install paddlepaddle==2.0"

**Comment by wshzd** [comment]
我尝试过paddlepaddle-gpu 2.2.1和2.3.1两个版本，都是报如下错误的：
Traceback (most recent call last):
  File "ocr_process.py", line 3, in <module>
    from paddleocr import PaddleOCR
  File "/mnt/data-1/zhidong.he/anaconda3/envs/paddle_car_manual/lib/python3.8/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/mnt/data-1/zhidong.he/anaconda3/envs/paddle_car_manual/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "/mnt/data-1/zhidong.he/anaconda3/envs/paddle_car_manual/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 31, in <module>
    import tools.infer.utility as utility
  File "/mnt/data-1/zhidong.he/anaconda3/envs/paddle_car_manual/lib/python3.8/site-packages/paddleocr/tools/infer/utility.py", line 24, in <module>
    from paddle import inference
ImportError: cannot import name 'inference' from 'paddle' (unknown location)
