### ISSUE TITLE
KeyError: 'infer_img'

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleOCR#276]
运行这个命令，CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/rec/rec_r34_vd_tps_bilstm_attn.yml

出现这个错误
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main()
  File "tools/train.py", line 66, in main
    config, train_program, startup_program, mode='train')
  File "/home/wn/projects/PaddleOCR-develop/tools/program.py", line 171, in build
    model = create_module(func_infor)(params=config)
  File "/home/wn/projects/PaddleOCR-develop/ppocr/modeling/architectures/rec_model.py", line 34, in __init__
    self.infer_img = global_params['infer_img']
KeyError: 'infer_img'

**Comment by LDOUBLEV** [comment]
验证了不会报这个错。是否修改了配置文件？代码更新到最新试试？
