### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2798]
python     3.6
numpy                 1.19.5+mkl
opencv-contrib-python 4.2.0.32
opencv-python         4.5.2.52
paddlepaddle-gpu      2.0.2
Pillow                8.2.0
pip                   21.0.1
pre-commit            2.12.1
protobuf              3.17.0
pyclipper             1.2.1
pycodestyle           2.7.0
pycryptodome          3.10.1
pyflakes              2.3.1
pyparsing             2.4.7
python-dateutil       2.8.1
python-Levenshtein    0.12.2
pytz                  2021.1
PyWavelets            1.1.1
PyYAML                5.4.1
requests              2.25.1
scikit-image          0.17.2
scipy                 1.5.4
setuptools            52.0.0.post20210125
Shapely               1.7.1
shellcheck-py         0.7.2.1
six                   1.16.0
tifffile              2020.9.3
toml                  0.10.2
tqdm                  4.60.0
typing-extensions     3.10.0.0
urllib3               1.26.4
virtualenv            20.4.6
visualdl              2.1.1
Werkzeug              2.0.0
wheel                 0.36.2
wincertstore          0.2

win10 
PaddleOCR 2.1
--------------------

(PaddleOCR) PS F:\PaddleOCR> python  tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_mobile_v2.0_det_infer/"  --rec_model_dir="./inference/ch_ppocr_mobile_v2.0_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=True --use_space_char=True
------------------
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 31, in <module>
    import tools.infer.predict_det as predict_det
  File "F:\PaddleOCR\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "F:\PaddleOCR\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "F:\PaddleOCR\ppocr\data\imaug\__init__.py", line 20, in <module>
    from .make_border_map import MakeBorderMap
  File "F:\PaddleOCR\ppocr\data\imaug\make_border_map.py", line 13, in <module>
    from shapely.geometry import Polygon
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\anaconda3\envs\PaddleOCR\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by littletomatodonkey** [comment]
shapely安装错误，可以参考faq，或者你在issue里搜一下，有解决方案的
