### ISSUE TITLE
使用自己的数据集训练PgNET时出现pickle的报错

### ISSUE THREAD

**Issue by lzzzzj** [PaddlePaddle/PaddleOCR#2809]
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 93, in main
    pre_best_model_dict = init_model(config, model, logger, optimizer)
  File "/home/aistudio/PaddleOCR-release-2.1/ppocr/utils/save_load.py", line 116, in init_model
    model, logger, path=pretrained, load_static_weights=load_static)
  File "/home/aistudio/PaddleOCR-release-2.1/ppocr/utils/save_load.py", line 74, in load_dygraph_pretrain
    param_state_dict = paddle.load(path + '.pdparams')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 365, in load
    f, encoding='latin1')
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
![image](https://user-images.githubusercontent.com/57863550/118475735-30886580-b73f-11eb-9b86-b2905f2125ab.png)
请问有什么可能的原因以及解决方案吗？
使用的平台是aistudio.baidu.com，不知道有没有影响。

**Comment by littletomatodonkey** [comment]
你加载的是什么pretrain，可以先试着直接使用paddle.load("your_model.pdparams")文件看下能否正常load

**Comment by lzzzzj** [comment]
> 你加载的是什么pretrain，可以先试着直接使用paddle.load("your_model.pdparams")文件看下能否正常load

谢谢，确实是这个文件的问题，已经解决了

**Comment by tjpulfn** [comment]
请问是怎么解决的，我也遇到了这个问题 @lzzzzj

**Comment by lzzzzj** [comment]
> 请问是怎么解决的，我也遇到了这个问题 @lzzzzj

我的预训练模型有问题，重新下了一遍就好了
