### ISSUE TITLE
无法使用tensorrt

### ISSUE THREAD

**Issue by Hubert2102** [PaddlePaddle/PaddleOCR#2826]
推理加了--use_tensorrt=True
报错如下：
alternative uses
  import imp
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 203, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 146, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 42, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/export/xufulai/PaddleOCR/tools/infer/predict_det.py", line 95, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/export/xufulai/PaddleOCR/tools/infer/utility.py", line 160, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:211)

**Comment by LDOUBLEV** [comment]
安装的paddle不支持tensorrt吧，可以安装paddle2.1版本，2.0之后发布的pip whl包应该都把tensorrt编译进去了

或者你自己编译带TRT的paddle，参考文档：https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html

另外，代码中的tensorrt是定长的，可以尝试用这个pr里的tensorrt 代码，支持变长输入
