### ISSUE TITLE
Train attention with more than 25 characters

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/PaddleOCR#2865]
It seems like there is a bug when training attention recognizer with the number of characters different than 25

**Comment by WenmuZhou** [comment]
can you upload error log?

**Comment by xxxpsyduck** [comment]
@WenmuZhou. Sorry I've been busy for a few days. Here is the stack trace:
```sh
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/khanhtq/PaddleOCR/tools/program.py", line 216, in train
    loss = loss_class(preds, batch)
  File "/home/khanhtq/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/khanhtq/PaddleOCR/ppocr/losses/rec_att_loss.py", line 39, in forward
    return {'loss': paddle.sum(self.loss_func(inputs, targets))}
  File "/home/khanhtq/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/khanhtq/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/loss.py", line 408, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "/home/khanhtq/miniconda3/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1400, in cross_entropy
    _, out = core.ops.softmax_with_cross_entropy(
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:6400 != labels_dims[i]:8960.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:150)
  [operator < softmax_with_cross_entropy > error]
```
This occurs whenever I use Attention with the number of characters different from 25.

**Comment by xxxpsyduck** [comment]
Training config:
```sh
Global:
  save_inference_dir: null
  log_smooth_window: 20
  distributed: false
  use_space_char: true
  cal_metric_during_train: true
  character_dict_path: vi.txt
  debug: false
  infer_img: null
  eval_batch_step: [0, 200]
  max_text_length: 35
  character_type: ch
  pretrained_model: null
  use_visualdl: false
  distort: true
  checkpoints:
  print_batch_step: 10
  infer_mode: false
  epoch_num: 500
  save_epoch_step: 10
  save_model_dir: ./output/crnn
  use_gpu: true

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
  regularizer:
    factor: 0.000
    name: L2

Loss:
  name: AttentionLoss

Metric:
  main_indicator: acc
  name: RecMetric

PostProcess:
  name: AttnLabelDecode

Architecture:
  model_type: rec
  Backbone:
    layers: 50
    name: ResNet
  algorithm: CRNN
  Neck:
    name: SequenceEncoder
    hidden_size: 256
    encoder_type: rnn
  Transform: null
  Head:
    name: AttentionHead
    hidden_size: 256 
    l2_decay: 0.00001

Train:
  dataset:
    data_dir: /data/train_data/
    label_file_list:
    - /data/train_data/train.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape: [3,16,64]
    - KeepKeys:
        keep_keys: ['image', 'label', 'length']
  loader:
    drop_last: true
    shuffle: true
    num_workers: 8
    batch_size_per_card: 256

Eval:
  dataset:
    data_dir: /data/train_data/
    label_file_list:
    - /data/train_data/val.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape: [3,16,64]
    - KeepKeys:
        keep_keys: ['image', 'label', 'length']
  loader:
    drop_last: false
    shuffle: false
    num_workers: 4
    batch_size_per_card: 256
```

**Comment by xxxpsyduck** [comment]
I believe this can be reproduced with any datasets. Just set the number of chars different from 25

**Comment by xxxpsyduck** [comment]
I figured out the problem. It's because `batch_max_length` is set fixed in [40](https://github.com/PaddlePaddle/PaddleOCR/blob/2fa256a71feb06910be150ee0be2700ae6d9f601/ppocr/modeling/heads/rec_att_head.py#L40) and [128](https://github.com/PaddlePaddle/PaddleOCR/blob/2fa256a71feb06910be150ee0be2700ae6d9f601/ppocr/modeling/heads/rec_att_head.py#L128). Will submit a PR to fix in a few days.

**Comment by ccl-private** [comment]
PR 怎么样了，有效果吗

**Comment by lzzzzj** [comment]
> 

Have you solve it? I met the same problem when training abinet with PaddleOCR2.6.
