### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#2872]
from paddleocr import PaddleOCR

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 31, in <module>
    import tools.infer.predict_det as predict_det
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\ppocr\data\imaug\__init__.py", line 20, in <module>
    from .make_border_map import MakeBorderMap
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\paddleocr\ppocr\data\imaug\make_border_map.py", line 13, in <module>
    from shapely.geometry import Polygon
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\anaconda3\envs\PaddleOCR36\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\anaconda3\envs\PaddleOCR36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
>>>

---------------------------
--------------------- -------------------
appdirs               1.4.4
astor                 0.8.1
Babel                 2.9.1
bce-python-sdk        0.8.60
certifi               2020.12.5
cfgv                  3.3.0
chardet               4.0.0
click                 8.0.1
colorama              0.4.4
cycler                0.10.0
dataclasses           0.8
decorator             4.4.2
distlib               0.3.1
filelock              3.0.12
flake8                3.9.2
Flask                 2.0.0
Flask-Babel           2.0.0
future                0.18.2
gast                  0.3.3
identify              2.2.4
idna                  2.10
imageio               2.9.0
imgaug                0.4.0
importlib-metadata    4.0.1
importlib-resources   5.1.3
itsdangerous          2.0.1
Jinja2                3.0.1
kiwisolver            1.3.1
lmdb                  1.2.1
MarkupSafe            2.0.1
matplotlib            3.3.4
mccabe                0.6.1
networkx              2.5.1
nodeenv               1.6.0
numpy                 1.19.3
opencv-contrib-python 4.2.0.32
opencv-python         4.2.0.32
paddleocr             2.0.6
paddlepaddle-gpu      2.0.0
Pillow                8.2.0
pip                   21.0.1
pre-commit            2.12.1
protobuf              3.17.0
pyclipper             1.2.1
pycodestyle           2.7.0
pycryptodome          3.10.1
pyflakes              2.3.1
pyparsing             2.4.7
PyQt5                 5.15.4
PyQt5-Qt5             5.15.2
PyQt5-sip             12.9.0
python-dateutil       2.8.1
python-Levenshtein    0.12.2
pytz                  2021.1
PyWavelets            1.1.1
PyYAML                5.4.1
requests              2.25.1
scikit-image          0.17.2
scipy                 1.5.4
setuptools            52.0.0.post20210125
Shapely               1.7.1
shellcheck-py         0.7.2.1
six                   1.16.0
tifffile              2020.9.3
toml                  0.10.2
tqdm                  4.60.0
typing-extensions     3.10.0.0
urllib3               1.26.4
virtualenv            20.4.6
visualdl              2.1.1
Werkzeug              2.0.1
wheel                 0.36.2
wincertstore          0.2
zipp                  3.4.1
---------------------------------------
win10  anaconda 环境
------------------------

**Comment by monkeycc** [comment]
已经解决问题

pip install Shapely-1.7.1-cp36-cp36m-win_amd64.whl --force-reinstall

虽然默认是安装完成的，但是win必须 强制安装一次Shapely

**Comment by thgpddl** [comment]
我多次重装Shapely都不行，最终通过复制DLL文件解决了，解决方法如下：
[“OSError: [WinError 126] 找不到指定的模块”的解决办法](https://blog.csdn.net/qq_40243750/article/details/120123119)
