### ISSUE TITLE
pyinstaller 打包exe后执行报错

### ISSUE THREAD

**Issue by xiliu** [PaddlePaddle/PaddleOCR#2885]
你好，我用pyinstaller 将PPOCRLabel打包成exe，执行exe报错如下图。 直接pycharm运行或在cmd命令窗口执行python PPOCRLabel.py都是没问题的。而且exe和py都是基于同一个虚拟环境运行的 单单exe报错。

![error](https://user-images.githubusercontent.com/7224986/119305350-37612c00-bc9b-11eb-916b-4a2492245e28.jpg)

https://github.com/PaddlePaddle/Paddle/issues/28205#issuecomment-714220901   提到的方法也试过，不行的。

**Comment by littletomatodonkey** [comment]
也可以参考这个issue的方法试下：#1567

**Comment by xiliu** [comment]
> 也可以参考这个issue的方法试下：#1567

感谢您的回复，上面的问题已解决，现在又遇到新的问题，执行打包好的exe出现如下错误。
![new_error](https://user-images.githubusercontent.com/7224986/119439995-0e51a180-bd56-11eb-818c-88c92a720f67.png)

可能的原因会是什么？？期待您的回复，谢谢。

**Comment by xiliu** [comment]
> 也可以参考这个issue的方法试下：#1567

感谢您的回复，上面的问题已解决。现在有新的问题，在执行打包后的exe时，出现如下错误。
![new_error_1](https://user-images.githubusercontent.com/7224986/119440992-e6633d80-bd57-11eb-89a9-d17a55a9d755.png)

可能的原因会是什么？期待您的回复，谢谢。

**Comment by xiliu** [comment]
问题找到了，是找不到检测模型的原因。还有一些其他问题，都已解决。打包完成并运行成功。

**Comment by thomaszheng** [comment]
@xiliu 你好，我这边也在尝试用pyinstaller把PPOCRLabel打包成exe，我这边可以打包成功，但是启动打包好的程序时无法启动的？可以提供一下你打包的exe，我这边使用一下吗？

**Comment by siliyuan** [comment]
你好，我也是一样找不到DLL，大佬能分享下怎么解决吗？ @xiliu

**Comment by FoneMobius** [comment]
我也是上面同样问题，现在解决了：
![image](https://user-images.githubusercontent.com/88438848/146510502-4ca13b08-3821-4c34-9348-d95e3715b345.png)

把python环境 D:\Python374\Lib\site-packages\paddle\libs这个文件夹下的所有dll复制到D:\Python374\Lib\site-packages\paddle\fluid这个文件夹下；
再试试重新打包，如果之后提示缺其他的模块（那种python项目程序里ppocr自己定义的模块），也可以把相应模块拷贝到D:\Python374\Lib\site-packages文件夹下，再尝试重新打包。

**Comment by FoneMobius** [comment]
![image](https://user-images.githubusercontent.com/88438848/146511900-790f29df-ec3c-4e91-8da1-8eb25e2a616e.png)
 最后也要把这些DLL拷贝到exe所在目录

**Comment by hf62580** [comment]
打包成exe之后，运行卡很久，然后报错
环境:python 3.7.4 paddleocr-2.0.1 paddlepaddle-2.0.1
E:\input>Mypaddleocr.exe
PyInstaller\loader\pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
C:\Users\ADMINI~1\AppData\Local\Temp\_MEI2974722\paddle\fluid\layers\utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "Mypaddleocr.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\paddleocr.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "tools\infer\predict_system.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "tools\infer\utility.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\__init__.py", line 51, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\io.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\reader.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\dataloader\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\dataloader\dataset.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\dataset\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\dataset\flowers.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\dataset\image.py", line 46, in <module>
  File "subprocess.py", line 939, in communicate
  File "subprocess.py", line 1267, in _communicate
  File "threading.py", line 1044, in join
  File "threading.py", line 1060, in _wait_for_tstate_lock

**Comment by Dawn-bin** [comment]
> File "threading.py", line 1060, in _wait_for_tstate_lock

有解决方案吗？

**Comment by DYF-AI** [comment]
(paddle) G:\dongyongfei786\multimodal-lm\third_party\ppocrlabel-pil\dist>PPOCRLabel.exe
Traceback (most recent call last):
  File "ppocrlabel-pil\PPOCRLabel.py", line 41, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "paddleocr\paddleocr.py", line 43, in <module>
  File "paddleocr\paddleocr.py", line 37, in _import_file
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\21702\\AppData\\Local\\Temp\\_MEI271362\\paddleocr\\tools/__init__.py'
[7336] Failed to execute script 'PPOCRLabel' due to unhandled exception!


请问这个问题如何解决？

**Comment by DYF-AI** [comment]
> (paddle) G:\dongyongfei786\multimodal-lm\third_party\ppocrlabel-pil\dist>PPOCRLabel.exe Traceback (most recent call last): File "ppocrlabel-pil\PPOCRLabel.py", line 41, in from paddleocr import PaddleOCR, PPStructure File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "paddleocr__init__.py", line 14, in File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "paddleocr\paddleocr.py", line 43, in File "paddleocr\paddleocr.py", line 37, in _import_file File "", line 839, in exec_module File "", line 975, in get_code File "", line 1032, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\21702\AppData\Local\Temp\_MEI271362\paddleocr\tools/**init**.py' [7336] Failed to execute script 'PPOCRLabel' due to unhandled exception!
> 
> 请问这个问题如何解决？

(paddle) G:\dongyongfei786\multimodal-lm\third_party\ppocrlabel-pil\dist>PPOCRLabel.exe
Traceback (most recent call last):
  File "ppocrlabel-pil\PPOCRLabel.py", line 28, in <module>
ImportError: DLL load failed while importing QtCore: 找不到指定的程序。
[25536] Failed to execute script 'PPOCRLabel' due to unhandled exception!

上面问题加 --collect-all paddleocr， 又会出现这个DLL问题，有大佬遇到吗？

**Comment by ydsjeff2020** [comment]
在pycharm中运行全部项目，皆正常运行，无报错。

把项目中包含paddleocr库的脚本注释掉，打包运行项目其余部分，生成的exe文件运行正常。

加入paddleocr打包后，运行程序报错：

NotFoundError: [Errno 2] No such file or directory:
 'C:\\Users\\12092\\AppData\\Local\\Temp\\_MEI344202\\paddleocr\\tools/__init__.py'，如有解决的请帮忙？

**Comment by ydsjeff2020** [comment]
在pycharm中运行全部项目，皆正常运行，无报错。

把项目中包含paddleocr库的脚本注释掉，打包运行项目其余部分，生成的exe文件运行正常。

加入paddleocr打包后，运行程序报错：

NotFoundError: [Errno 2] No such file or directory:
'C:\Users\12092\AppData\Local\Temp\_MEI344202\paddleocr\tools/init.py'，如有解决的请帮忙？
解决方法：
在.spec中的datas中添加，后再打包，我的已解决
datas=[('C:\\Users\\Administrator\\.virtualenvs\\MEBx_Test-b9tfmB5g\\Lib\\site-packages\\paddleocr\\tools', 'paddleocr' )],
