### ISSUE TITLE
官方教程infer报错

### ISSUE THREAD

**Issue by xuanxiaoliqu** [PaddlePaddle/PaddleOCR#2907]
Traceback (most recent call last):
  File "predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "D:\projects\PaddleOCR\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "D:\projects\PaddleOCR\ppocr\data\imaug\__init__.py", line 20, in <module>
    from .make_border_map import MakeBorderMap
  File "D:\projects\PaddleOCR\ppocr\data\imaug\make_border_map.py", line 13, in <module>
    from shapely.geometry import Polygon
  File "D:\Anaconda3\envs\paddle\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\Anaconda3\envs\paddle\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\Anaconda3\envs\paddle\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\Anaconda3\envs\paddle\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\Anaconda3\envs\paddle\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Anaconda3\envs\paddle\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by LDOUBLEV** [comment]
检查shapely库安装是否正确

**Comment by xuanxiaoliqu** [comment]
> 检查shapely库安装是否正确
一直都是成功安装的，

**Comment by xuanxiaoliqu** [comment]
> > 检查shapely库安装是否正确
> > 一直都是成功安装的，

geos_c.dll根本不在提示错误的那个路径下，而是在shapely包下

**Comment by xuanxiaoliqu** [comment]
> > > 检查shapely库安装是否正确
> > > 一直都是成功安装的，
> 
> geos_c.dll根本不在提示错误的那个路径下，而是在shapely包下
重新用conda 安装了一下，可以用了，谢谢
