### ISSUE TITLE
识别模型使用slim剪裁之后，acc一直为0

### ISSUE THREAD

**Issue by MTaoYue** [PaddlePaddle/PaddleOCR#2942]
python deploy/slim/prune/sensitivity_anal.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.pretrain_weights=~/work/PaddleOCR/output/rec_chinese_lite_v2.0/best_accuracy Global.test_batch_size_per_card=1

<class 'paddle.nn.layer.common.Linear'>'s flops has been counted
Total Flops: 112948128     Total Params: 901681
[2021/05/27 19:43:31] root INFO: FLOPs before pruning: 112948128
[05-27 19:43:31 MainThread @logger.py:242] Argv: deploy/slim/prune/sensitivity_anal.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml -o Global.pretrain_weights=~/work/PaddleOCR/output/rec_chinese_lite_v2.0/best_accuracy Global.test_batch_size_per_card=1
[05-27 19:43:31 MainThread @utils.py:79] WRN paddlepaddle version: 2.0.2. The dynamic graph version of PARL is under development, not fully tested and supported
2021-05-27 19:43:34,324-INFO: No walker for operator: rnn
2021-05-27 19:43:34,326-INFO: No walker for operator: rnn
2021-05-27 19:43:34,329-INFO: No walker for operator: rnn
2021-05-27 19:43:34,331-INFO: No walker for operator: rnn
2021-05-27 19:43:34,333-INFO: No walker for operator: rnn
2021-05-27 19:43:34,336-INFO: No walker for operator: rnn
2021-05-27 19:43:34,338-INFO: No walker for operator: rnn
2021-05-27 19:43:34,340-INFO: No walker for operator: rnn
2021-05-27 19:43:34,343-INFO: No walker for operator: rnn
2021-05-27 19:43:34,345-INFO: No walker for operator: rnn
2021-05-27 19:43:34,348-INFO: No walker for operator: rnn
2021-05-27 19:43:34,350-INFO: No walker for operator: rnn
2021-05-27 19:43:34,352-INFO: No walker for operator: rnn
2021-05-27 19:43:34,355-INFO: No walker for operator: rnn
2021-05-27 19:43:34,357-INFO: No walker for operator: rnn
2021-05-27 19:43:34,360-INFO: No walker for operator: rnn
2021-05-27 19:43:34,374-INFO: Found 26 groups.
2021-05-27 19:43:34,379 - INFO - If regularizer of a Parameter has been set by 'paddle.ParamAttr' or 'static.WeightNormParamAttr' already. The weight_decay[L2Decay, regularization_coeff=0.000010] in Optimizer will not take effect, and it will only be applied to other Parameters!
[2021/05/27 19:43:34] root INFO: train from scratch
[2021/05/27 19:43:34] root INFO: train dataloader has 390 iters, valid dataloader has 196 iters
[2021/05/27 19:43:34] root INFO: train dataloader has 390 iters, valid dataloader has 196 iters
eval model:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 196/196 [05:17<00:00,  1.62s/it]
[2021/05/27 19:48:51] root INFO: metric['acc']: 0.0
eval model:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 196/196 [05:25<00:00,  1.66s/it]
[2021/05/27 19:54:17] root INFO: metric['acc']: 0.0
Traceback (most recent call last):
  File "deploy/slim/prune/sensitivity_anal.py", line 146, in <module>
    main(config, device, logger, vdl_writer)
  File "deploy/slim/prune/sensitivity_anal.py", line 117, in main
    "conv2d_57.w_0", "conv2d_transpose_2.w_0", "conv2d_transpose_3.w_0"
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/dygraph/prune/filter_pruner.py", line 123, in sensitive
    skip_vars=skip_vars)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/dygraph/prune/filter_pruner.py", line 264, in _cal_sensitive
    loss = (baseline - pruned_metric) / baseline
ZeroDivisionError: float division by zero

**Comment by MTaoYue** [comment]
用来剪枝的模型在验证集上有60多的准确率
