### ISSUE TITLE
windows10 环境训练报错了，麻烦看一下

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#2952]
你好，paddleocr下载到本地后启动训练报错如下：
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppocr.data import build_dataloader
  File "D:\ooccrr\PaddleOCR-release-2.1\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "D:\ooccrr\PaddleOCR-release-2.1\ppocr\data\imaug\__init__.py", line 20, in <module>
    from .make_border_map import MakeBorderMap
  File "D:\ooccrr\PaddleOCR-release-2.1\ppocr\data\imaug\make_border_map.py", line 13, in <module>
    from shapely.geometry import Polygon
  File "D:\anaconda3\envs\paddle_gpu\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\anaconda3\envs\paddle_gpu\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\anaconda3\envs\paddle_gpu\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\anaconda3\envs\paddle_gpu\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\anaconda3\envs\paddle_gpu\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

shaply安装的1.7.1

**Comment by thgpddl** [comment]
我遇到的，解决办法如下：
[“OSError: [WinError 126] 找不到指定的模块”的解决办法](https://blog.csdn.net/qq_40243750/article/details/120123119)
