### ISSUE TITLE
启动训练报如下错误

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleOCR#2961]
2021-05-28 16:56:13,703 - ERROR - DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 684, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 700, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 8 workers exit unexpectedly, pids: 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400
    eval_class, pre_best_model_dict, logger, vdl_writer)

  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 199, in train
    for idx, batch in enumerate(train_dataloader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by surabbit** [comment]
把num_workers都设置为0应该可以解决报错问题，但是训练速度会很慢，目前我也在找解决方法

**Comment by Sunyingbin** [comment]
> 把num_workers都设置为0应该可以解决报错问题，但是训练速度会很慢，目前我也在找解决方法

我把batch_size_per_card这个变小了也可以解决问题，同样训练速度也变慢了

**Comment by Sunyingbin** [comment]
> 把num_workers都设置为0应该可以解决报错问题，但是训练速度会很慢，目前我也在找解决方法

你好，我测试我的电脑上设置num_workers为0、2、4、8、16，训练的时间是不变的，另外batch_size_per_card这个值设置成256会不跑，设置成512、64、16都会继续跑

**Comment by ddz-mark** [comment]
同样的问题，多卡训练多线程会出错，单卡就运行正常，不知道环境是不是有问题，准备重装一遍

**Comment by 01Juw** [comment]
> 同样的问题，多卡训练多线程会出错，单卡就运行正常，不知道环境是不是有问题，准备重装一遍

单卡训练正常 多卡下卡不动 这个问题有解决吗 多卡训练也遇到同样情况
