### ISSUE TITLE
PGNet用自己的数据集和Dict训练，eval时报错

### ISSUE THREAD

**Issue by HairongWu** [PaddlePaddle/PaddleOCR#2964]
PGNet用自己的数据集和Dict训练，eval时报错。Lexicon_Table里确认是0-9十个数字，但dst_str里有为10的index所以报错。不知是什么原因
eval model::   0%|                                                                            | 0/12615 [00:00<?, ?it/s](9,)
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/tools/program.py", line 267, in train
    cur_metric = eval(
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/tools/program.py", line 362, in eval
    post_result = post_process_class(preds, batch[1])
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/postprocess/pg_postprocess.py", line 49, in __call__
    data = post.pg_postprocess_fast()
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/pgnet_pp_utils.py", line 56, in pg_postprocess_fast
    instance_yxs_list, seq_strs = generate_pivot_list_fast(
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 389, in generate_pivot_list_fast
    decoded_str, keep_yxs_list = ctc_decoder_for_image(
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 120, in ctc_decoder_for_image
    dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])
  File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 120, in <listcomp>
    dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])
IndexError: list index out of range

**Comment by lin-0015** [comment]
> PGNet用自己的数据集和Dict训练，eval时报错。Lexicon_Table里确认是0-9十个数字，但dst_str里有为10的index所以报错。不知是什么原因
> eval model:: 0%| | 0/12615 [00:00<?, ?it/s](9,)
> Traceback (most recent call last):
> File "tools/train.py", line 125, in
> main(config, device, logger, vdl_writer)
> File "tools/train.py", line 100, in main
> program.train(config, train_dataloader, valid_dataloader, device, model,
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/tools/program.py", line 267, in train
> cur_metric = eval(
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/tools/program.py", line 362, in eval
> post_result = post_process_class(preds, batch[1])
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/postprocess/pg_postprocess.py", line 49, in **call**
> data = post.pg_postprocess_fast()
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/pgnet_pp_utils.py", line 56, in pg_postprocess_fast
> instance_yxs_list, seq_strs = generate_pivot_list_fast(
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 389, in generate_pivot_list_fast
> decoded_str, keep_yxs_list = ctc_decoder_for_image(
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 120, in ctc_decoder_for_image
> dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])
> File "/home/solis-ipfs/dataset_adapter/PaddleOCR-release-2.1/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 120, in
> dst_str_readable = ''.join([Lexicon_Table[idx] for idx in dst_str])
> IndexError: list index out of range

请问您是怎么解决的,我也遇到了一样的问题.
冒昧请教一下您~ 谢谢啦
