### ISSUE TITLE
在android6.0上使用abiFilters "armeabi-v7a"加载so报错

### ISSUE THREAD

**Issue by chriswack** [PaddlePaddle/PaddleOCR#2970]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.test.paddle-1/base.apk"...
05-31 09:15:26.457 3155-3205/com.test.paddle W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
05-31 09:15:26.457 3155-3205/com.test.paddle W/System.err:     at java.lang.System.loadLibrary(System.java:1076)

**Comment by WenmuZhou** [comment]
用最新的动态图代码和2.9的lite预测库看看
