### ISSUE TITLE
Can not import avx core while this file exists

### ISSUE THREAD

**Issue by TankosTao** [PaddlePaddle/PaddleOCR#3015]
Can not import avx core while this file exists: C:\Users\**\AppData\Local\Temp\_MEI233122\paddle\fluid\core_avx.pyd

Error: Can not import avx core while this file exists: C:\Users\**\AppData\Local\Temp\_MEI233122\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "darknet_nogui_mutimodel.py", line 59, in <module>
    import _vin.utility as utility
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "_vin\utility.py", line 23, in <module>
    from paddle import inference
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "paddle\__init__.py", line 29, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "paddle\fluid\__init__.py", line 35, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "paddle\fluid\framework.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "paddle\fluid\core.py", line 289, in <module>
  File "paddle\fluid\core.py", line 254, in <module>
ImportError: DLL load failed: 找不到指定的模块。
[20452] Failed to execute script darknet_nogui_mutimodel

paddlepaddle ==2.0.0，PaddleOCR

当我在pycharm、windows cmd终端运行项目是一切正常，但是当我打包成exe之后，运行报错。
打包指令：pyinstaller -F **.py

When I run the project in pycharm or windows'cmd, everything works fine. But when I package it using pyinstaller, the exe file reports some issues.

**Comment by TankosTao** [comment]
项目运行在windows10 ，paddle cpu版本，我的cpu是5800h

**Comment by LDOUBLEV** [comment]
看一下你的paddle版本里，paddle\fluid\core.py", line 254,是什么代码，像是加载一些库失败了

**Comment by TankosTao** [comment]
![图片](https://user-images.githubusercontent.com/26140080/120617416-a8b79080-c48c-11eb-9a77-f832abb2df4c.png)

**Comment by TankosTao** [comment]
版本、环境信息：
    1）PaddlePaddle版本：2.0.2 cpu版本
    2）CPU：5800h
    3）GPU：核显
    4）系统环境：win10、Python3.7
    安装方式信息：
    1）pip安装

**Comment by Evezerest** [comment]
抱歉打包现在暂时还不支持

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
