### ISSUE TITLE
styletext 批量生成图片报错

### ISSUE THREAD

**Issue by meonline-f** [PaddlePaddle/PaddleOCR#3034]
1，使用官方原始数据，执行批量生成图片
Traceback (most recent call last):
  File "D:\workspace\python\develope\PaddleOCR\StyleText\tools\synth_dataset.py", line 31, in <module>
    synth_dataset()
  File "D:\workspace\python\develope\PaddleOCR\StyleText\tools\synth_dataset.py", line 26, in synth_dataset
    dataset_synthesiser = DatasetSynthesiser()
  File "D:\workspace\python\develope\PaddleOCR\StyleText\engine\synthesisers.py", line 58, in __init__
    self.style_sampler = style_samplers.DatasetSampler(self.config)
  File "D:\workspace\python\develope\PaddleOCR\StyleText\engine\style_samplers.py", line 27, in __init__
    label_raw = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 63: illegal multibyte sequence

2，可以通过配置支持其他语言吗

**Comment by littletomatodonkey** [comment]
1. 看着是文件读取格式不同，默认是utf8的，可能需要把read这块修改为读取gbk格式的
2. 目前支持中英韩，其他语言还没支持

**Comment by meonline-f** [comment]
> 2. 目前支持中英韩，其他语言还没支持

可以自己训练语言吗，用什么模型？

**Comment by littletomatodonkey** [comment]
目前还没开源训练代码，后续整理下开源哈

**Comment by meonline-f** [comment]
给力

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
