### ISSUE TITLE
DBNet训练文本检测模型

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3053]
一开始训练时是正常的，过一段时间提示下面报错
![image](https://user-images.githubusercontent.com/44855506/121178715-6a0d4600-c891-11eb-9b58-fd0f623bd415.png)
能给看一下是什么问题吗，谢谢了

**Comment by Mafengqiang** [comment]
> 一开始训练时是正常的，过一段时间提示下面报错
> ![image](https://user-images.githubusercontent.com/44855506/121178715-6a0d4600-c891-11eb-9b58-fd0f623bd415.png)
> 能给看一下是什么问题吗，谢谢了

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/paddle/PaddleOCR-release-2.1/tools/program.py", line 216, in train
    loss = loss_class(preds, batch)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/PaddleOCR-release-2.1/ppocr/losses/det_db_loss.py", line 58, in forward
    label_shrink_mask)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/PaddleOCR-release-2.1/ppocr/losses/det_basic_loss.py", line 99, in forward
    sort_loss = negative_loss.sort(descending=True)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle/tensor/search.py", line 464, in sort
    out, _ = core.ops.argsort(x, 'axis', axis, 'descending', descending)
SystemError: (Fatal) Operator argsort raises an thrust::system::detail::bad_alloc exception.
The exception content is
:std::bad_alloc: temporary_buffer::allocate: get_temporary_buffer failed. (at /paddle/paddle/fluid/imperative/tracer.cc:172)

terminate called without an active exception

**Comment by XinchengYuYi** [comment]
我今天遇到了相似的问题，原因是机器的内存不足，请把配置文件里的训练numworkers数量调低

**Comment by Mafengqiang** [comment]
> 我今天遇到了相似的问题，原因是机器的内存不足，请把配置文件里的训练numworkers数量调低

我也发现是这个问题了，谢谢啦

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
