### ISSUE TITLE
用export_model.py转换rec_r34_vd_tps_bilstm_att模型时报错

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleOCR#3079]
转换指令：
`python3 tools/export_model.py -c configs/rec/rec_r34_vd_tps_bilstm_att.yml -o Global.pretrained_model=./output/rec/b3_rare_r34_none_gru/best_accuracy  Global.save_inference_dir=./inference/rec_att`
输出：

> /home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
[2021/06/10 12:09:02] root INFO: load pretrained model from ['./output/rec/b3_rare_r34_none_gru/best_accuracy']
[2021/06/10 12:09:02] root INFO: When there is tps in the network, variable length input is not supported, and the input size needs to be the same as during training
Traceback (most recent call last):
  File "tools/export_model.py", line 101, in <module>
    main()
  File "tools/export_model.py", line 96, in main
    paddle.jit.save(model, save_path)
  File "<decorator-gen-60>", line 2, in save
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:
    File "/tmp/tmpzd47424m.py", line 31, in forward
	x = paddle.jit.dy2static.convert_ifelse(data is None, true_fn_2,
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/chenzhao/projects/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 78, in forward (* user code *)
	x = self.head(x)
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmphvd4324k.py", line 103, in forward
	) = (paddle.jit.dy2static.convert_ifelse(targets is not None,
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/chenzhao/projects/PaddleOCR/ppocr/modeling/heads/rec_att_head.py", line 58, in forward (* user code *)
	targets = paddle.zeros(shape=[batch_size], dtype="int32")
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/tensor/creation.py", line 350, in zeros
	return fill_constant(value=0.0, shape=shape, dtype=dtype, name=name)
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 708, in fill_constant
	check_shape(shape)
    File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/layers/utils.py", line 374, in check_shape
	raise ValueError(
    ValueError: All elements in ``shape`` must be positive when it's a list or tuple

**Comment by littletomatodonkey** [comment]
这块用2.1.0的paddle试下呢？这个问题应该是修了

**Comment by chenxuezhao** [comment]
用release2.1的export_models.py可以转换
