### ISSUE TITLE
Docker部署安装ocr_system失败

### ISSUE THREAD

**Issue by mxxlei** [PaddlePaddle/PaddleOCR#3096]
运行安装命令： 
cd PaddleOCR
hub install deploy/hubserving/ocr_system/

失败的结果
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/commands/install.py", line 47, in execute
    manager.install(directory=_arg)
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/module/manager.py", line 192, in install
    return self._install_from_directory(directory)
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/module/manager.py", line 364, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/module/module.py", line 418, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/utils/utils.py", line 248, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/ocr_system/module.py", line 19, in <module>
    from tools.infer.utility import base64_to_cv2
ModuleNotFoundError: No module named 'tools.infer'

提示找不到tools.infer.utility.py这个文件，其实这个文件是存在的PaddleOCR/tools/infer/utitty.py。
运行命令的当前目录就是在PaddleOCR根目录。老哥帮忙解决一下好吗？

**Comment by littletomatodonkey** [comment]
`unset PYTHONPATH`，试下

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
