### ISSUE TITLE
在使用det_mv3_db.yml，训练自己数据报错，AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

### ISSUE THREAD

**Issue by Liuchen-20191106** [PaddlePaddle/PaddleOCR#3103]
使用自己数据训练300epoch，在211个epoch报错，如下：
[2021/06/16 13:42:23] root INFO: epoch: [210/300], iter: 6070, lr: 0.000219, loss: 1.035029, loss_shrink_maps: 0.545474, loss_threshold_maps: 0.377236, loss_binary_maps: 0.108668, reader_cost: 0.45080 s, batch_cost: 0.52057 s, samples: 40, ips: 7.68382
[2021/06/16 13:42:28] root INFO: epoch: [210/300], iter: 6080, lr: 0.000218, loss: 1.024136, loss_shrink_maps: 0.539381, loss_threshold_maps: 0.377122, loss_binary_maps: 0.107633, reader_cost: 0.41252 s, batch_cost: 0.48286 s, samples: 40, ips: 8.28404
[2021/06/16 13:42:33] root INFO: save model in ./output/draft_db_mv3_0616/latest
[2021/06/16 13:42:33] root INFO: Initialize indexs of datasets:['/media/qyjs/sd2/liuchen/2021/dataset/paddle_data/draft/train/train.txt']
[2021/06/16 13:42:34] root INFO: epoch: [211/300], iter: 6090, lr: 0.000216, loss: 1.058725, loss_shrink_maps: 0.565792, loss_threshold_maps: 0.386921, loss_binary_maps: 0.112470, reader_cost: 0.05266 s, batch_cost: 0.05982 s, samples: 4, ips: 6.68640
[2021/06/16 13:42:39] root INFO: epoch: [211/300], iter: 6100, lr: 0.000215, loss: 1.091230, loss_shrink_maps: 0.580888, loss_threshold_maps: 0.392257, loss_binary_maps: 0.115638, reader_cost: 0.43403 s, batch_cost: 0.50226 s, samples: 40, ips: 7.96407

eval model::   0%|          | 0/29 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 95, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/media/qyjs/sd2/liuchen/2021/code/q1/PaddleOCR/tools/program.py", line 262, in train
    cur_metric = eval(
  File "/media/qyjs/sd2/liuchen/2021/code/q1/PaddleOCR/tools/program.py", line 338, in eval
    for idx, batch in enumerate(valid_dataloader):
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 327, in _init_workers
    worker.start()
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f658a245dc0>
Traceback (most recent call last):
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/qyjs/anaconda3/envs/ptocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

**Comment by LDOUBLEV** [comment]
OSError: [Errno 12] Cannot allocate memory
  是不是内存不够了

改小一点num_works

或者试试清理共享内存 rm -rf /dev/shm/*

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by zcunyi** [comment]
> OSError: [Errno 12] Cannot allocate memory 是不是内存不够了
> 
> 改小一点num_works
> 
> 或者试试清理共享内存 rm -rf /dev/shm/*

我试了一下都不行，还是训练了多少个epoch之后就这样报错了，之前都是可以训练的，不知道为啥最近这样了
