### ISSUE TITLE
ExternalError:  Cuda error(77), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by gdwu1427** [PaddlePaddle/PaddleOCR#3113]
您好！在运行过程中，出现下述异常：有什么解决办法么？
Process Process-16:
Traceback (most recent call last):
  File "/home/znlh/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/znlh/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/znlh/dnn/ocr_gator3/ocr_flow.py", line 328, in ocr_recognize
    ocr_engine.ocr_ctn_yolo(frame, rect_list, rec_save_path)
  File "/home/znlh/dnn/ocr_gator3/paddleocr.py", line 172, in ocr_ctn_yolo
    res = self.ocr(roi_img_384)
  File "/home/znlh/dnn/ocr_gator3/paddleocr.py", line 147, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/home/znlh/dnn/ocr_gator3/predict_system.py", line 91, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/znlh/dnn/ocr_gator3/predict_det.py", line 147, in __call__
    self.predictor.run([im])
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
3   void paddle::memory::Copy<paddle::platform::CPUPlace, paddle::platform::CUDAPlace>(paddle::platform::CPUPlace, void*, paddle::platform::CUDAPlace, void const*, unsigned long, CUstream_st*)
4   paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
5   paddle::operators::FetchOp::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::NaiveExecutor::Run()
8   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/znlh/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/znlh/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 1053, in append_fetch_ops
    attrs={'col': i})
  File "/home/znlh/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 1222, in save_inference_model
    append_fetch_ops(main_program, fetch_var_names)
  File "tools/export_model.py", line 68, in main
    params_filename='params')
  File "tools/export_model.py", line 75, in <module>
    main()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:281)
  [operator < fetch > error]

**Comment by tink2123** [comment]
请问使用的是哪个版本的paddle，是在运行过程中报错吗？

**Comment by gdwu1427** [comment]
1.8.2 post 107 版本

**Comment by Evezerest** [comment]
升级一下paddle版本还会报错吗
