### ISSUE TITLE
Out of memory error on GPU 0

### ISSUE THREAD

**Issue by scopedog** [PaddlePaddle/PaddleOCR#3139]
I see similar errors in other issues but wonder what causes mine. 
With RTX 3080 + CUDA 11.3 + PaddlePaddle 2.1.0 for CUDA 11.2, I get the following error at the beginning of training:

```
Traceback (most recent call last):
  File "/home/hidebu/programs/PaddleOCR/tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/hidebu/programs/PaddleOCR/tools/train.py", line 100, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/hidebu/programs/PaddleOCR/tools/program.py", line 215, in train
    preds = model(images)
  File "/home/hideb/.local/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hidebu/programs/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 74, in forward
    x = self.backbone(x)
  File "/home/hidebu/.local/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hidebu/programs/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 284, in forward
    y = block(y)
  File "/home/hidebu/.local/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hidebu/programs/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 170, in forward
    short = self.short(inputs)
  File "/home/hidebu/.local/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hidebu/programs/PaddleOCR/ppocr/modeling/backbones/rec_resnet_vd.py", line 66, in forward
    inputs = self._pool2d_avg(inputs)
  File "/home/hidebu/.local/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hidebu/.local/lib/python3.9/site-packages/paddle/nn/layer/pooling.py", line 207, in forward
    return F.avg_pool2d(
  File "/home/hidebu/.local/lib/python3.9/site-packages/paddle/nn/functional/pooling.py", line 330, in avg_pool2d
    output = core.ops.pool2d(
SystemError: (Fatal) Operator pool2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 80.000244MB memory on GPU 0, 9.729126GB memory has been allocated and available memory is only 55.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```

I would appreciate it if somebody could tell me what causes this and how to fix it.
Thank you.

**Comment by scopedog** [comment]
Well, I could avoid it by changing batch_size_per_card in yml training config file from 256 to 64.
My training with a GPU has finally started.
Thank you.

**Comment by rsingh2083** [comment]
> Well, I could avoid it by changing batch_size_per_card in yml training config file from 256 to 64.
> My training with a GPU has finally started.
> Thank you.

I did batch_size_per_card = 16,
num_workers=6
My GPU = single 1080ti, 11GB

Still im getting this error (with just 50 files in my training directory): - OSError: [Errno 24] Too many open files

**Comment by scopedog** [comment]
That's another problem.
Google with "Linux Too many open files".
Their default limit of # of open files is usually too small.

**Comment by SamouchH** [comment]
I actually had batch_size_per_card = 8 and num_workers = 4 and had the same issue, even when try to set 'batch_size_per_card' to 4. However , when setting to 64 it worked

**Comment by stockarea** [comment]
I am using paddle 3.. where is .yml file to even configure this?
I am using PPStructureV3() and getting the issue.
