### ISSUE TITLE
多卡训练程序被杀死

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#3150]
文本识别任务，目前是 2 张 V100 32G 环境，单卡运行没有问题，一旦使用多卡训练，报错：
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', 'configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml', '-o', 'Global.pretrained_model=./output/rec_chinese_lite_v2.0/20210514_100w/best_accuracy', 'Global.use_gpu=True', 'Global.save_model_dir=./output/rec_chinese_lite_v2.0/20210622']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-06-22 03:34:08,940 launch.py:316] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2021-06-22 03:34:08,941 launch_utils.py:472] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:45995               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:45995,127.0.0.1:32911       |
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-06-22 03:34:08,941 launch_utils.py:475] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
[2021/06/22 03:34:10] root INFO: Architecture :
[2021/06/22 03:34:10] root INFO:     Backbone :
[2021/06/22 03:34:10] root INFO:         model_name : small
[2021/06/22 03:34:10] root INFO:         name : MobileNetV3
[2021/06/22 03:34:10] root INFO:         scale : 0.5
[2021/06/22 03:34:10] root INFO:         small_stride : [1, 2, 2, 2]
[2021/06/22 03:34:10] root INFO:     Head :
[2021/06/22 03:34:10] root INFO:         fc_decay : 1e-05
[2021/06/22 03:34:10] root INFO:         name : CTCHead
[2021/06/22 03:34:10] root INFO:     Neck :
[2021/06/22 03:34:10] root INFO:         encoder_type : rnn
[2021/06/22 03:34:10] root INFO:         hidden_size : 48
[2021/06/22 03:34:10] root INFO:         name : SequenceEncoder
[2021/06/22 03:34:10] root INFO:     Transform : None
[2021/06/22 03:34:10] root INFO:     algorithm : CRNN
[2021/06/22 03:34:10] root INFO:     model_type : rec
[2021/06/22 03:34:10] root INFO: Eval :
[2021/06/22 03:34:10] root INFO:     dataset :
[2021/06/22 03:34:10] root INFO:         data_dir : /dataset/online_data/
[2021/06/22 03:34:10] root INFO:         label_file_list : ['/dataset/online_data/20210516/val_235762_20210516.txt', '/dataset/online_data/20210517/val_278991_20210517.txt', '/dataset/online_data/20210518/val_278178_20210518.txt', '/dataset/online_data/ChineseStreetView/val_42405.txt']
[2021/06/22 03:34:10] root INFO:         name : SimpleDataSet
[2021/06/22 03:34:10] root INFO:         ratio_list : [0.2, 0.2, 0.2, 1.0]
[2021/06/22 03:34:10] root INFO:         transforms :
[2021/06/22 03:34:10] root INFO:             DecodeImage :
[2021/06/22 03:34:10] root INFO:                 channel_first : False
[2021/06/22 03:34:10] root INFO:                 img_mode : BGR
[2021/06/22 03:34:10] root INFO:             CTCLabelEncode : None
[2021/06/22 03:34:10] root INFO:             RecResizeImg :
[2021/06/22 03:34:10] root INFO:                 image_shape : [3, 32, 320]
[2021/06/22 03:34:10] root INFO:             KeepKeys :
[2021/06/22 03:34:10] root INFO:                 keep_keys : ['image', 'label', 'length']
[2021/06/22 03:34:10] root INFO:     loader :
[2021/06/22 03:34:10] root INFO:         batch_size_per_card : 32
[2021/06/22 03:34:10] root INFO:         drop_last : False
[2021/06/22 03:34:10] root INFO:         num_workers : 8
[2021/06/22 03:34:10] root INFO:         shuffle : False
[2021/06/22 03:34:10] root INFO: Global :
[2021/06/22 03:34:10] root INFO:     cal_metric_during_train : True
[2021/06/22 03:34:10] root INFO:     character_dict_path : ppocr/utils/ppocr_keys_v1.txt
[2021/06/22 03:34:10] root INFO:     character_type : ch
[2021/06/22 03:34:10] root INFO:     checkpoints : None
[2021/06/22 03:34:10] root INFO:     debug : False
[2021/06/22 03:34:10] root INFO:     distributed : True
[2021/06/22 03:34:10] root INFO:     epoch_num : 100
[2021/06/22 03:34:10] root INFO:     eval_batch_step : [5, 10]
[2021/06/22 03:34:10] root INFO:     infer_img : /dataset/online_test_data/crop_imgs/
[2021/06/22 03:34:10] root INFO:     infer_mode : False
[2021/06/22 03:34:10] root INFO:     log_smooth_window : 20
[2021/06/22 03:34:10] root INFO:     max_text_length : 25
[2021/06/22 03:34:10] root INFO:     pretrained_model : ./output/rec_chinese_lite_v2.0/20210514_100w/best_accuracy
[2021/06/22 03:34:10] root INFO:     print_batch_step : 1
[2021/06/22 03:34:10] root INFO:     save_epoch_step : 3
[2021/06/22 03:34:10] root INFO:     save_inference_dir : None
[2021/06/22 03:34:10] root INFO:     save_model_dir : ./output/rec_chinese_lite_v2.0/20210622
[2021/06/22 03:34:10] root INFO:     use_gpu : True
[2021/06/22 03:34:10] root INFO:     use_space_char : True
[2021/06/22 03:34:10] root INFO:     use_visualdl : False
[2021/06/22 03:34:10] root INFO: Loss :
[2021/06/22 03:34:10] root INFO:     name : CTCLoss
[2021/06/22 03:34:10] root INFO: Metric :
[2021/06/22 03:34:10] root INFO:     main_indicator : acc
[2021/06/22 03:34:10] root INFO:     name : RecMetric
[2021/06/22 03:34:10] root INFO: Optimizer :
[2021/06/22 03:34:10] root INFO:     beta1 : 0.9
[2021/06/22 03:34:10] root INFO:     beta2 : 0.999
[2021/06/22 03:34:10] root INFO:     lr :
[2021/06/22 03:34:10] root INFO:         learning_rate : 0.001
[2021/06/22 03:34:10] root INFO:         name : Cosine
[2021/06/22 03:34:10] root INFO:     name : Adam
[2021/06/22 03:34:10] root INFO:     regularizer :
[2021/06/22 03:34:10] root INFO:         factor : 1e-05
[2021/06/22 03:34:10] root INFO:         name : L2
[2021/06/22 03:34:10] root INFO: PostProcess :
[2021/06/22 03:34:10] root INFO:     name : CTCLabelDecode
[2021/06/22 03:34:10] root INFO: Train :
[2021/06/22 03:34:10] root INFO:     dataset :
[2021/06/22 03:34:10] root INFO:         data_dir : /dataset/online_data/
[2021/06/22 03:34:10] root INFO:         label_file_list : ['/dataset/online_data/20210516/train_943045_20210516.txt']
[2021/06/22 03:34:10] root INFO:         name : SimpleDataSet
[2021/06/22 03:34:10] root INFO:         transforms :
[2021/06/22 03:34:10] root INFO:             DecodeImage :
[2021/06/22 03:34:10] root INFO:                 channel_first : False
[2021/06/22 03:34:10] root INFO:                 img_mode : BGR
[2021/06/22 03:34:10] root INFO:             RecAug : None
[2021/06/22 03:34:10] root INFO:             CTCLabelEncode : None
[2021/06/22 03:34:10] root INFO:             RecResizeImg :
[2021/06/22 03:34:10] root INFO:                 image_shape : [3, 32, 320]
[2021/06/22 03:34:10] root INFO:             KeepKeys :
[2021/06/22 03:34:10] root INFO:                 keep_keys : ['image', 'label', 'length']
[2021/06/22 03:34:10] root INFO:     loader :
[2021/06/22 03:34:10] root INFO:         batch_size_per_card : 32
[2021/06/22 03:34:10] root INFO:         drop_last : True
[2021/06/22 03:34:10] root INFO:         num_workers : 8
[2021/06/22 03:34:10] root INFO:         shuffle : True
[2021/06/22 03:34:10] root INFO: train with paddle 2.0.0 and device CUDAPlace(0)

Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/root/dudaizhong/PaddleOCR/tools/program.py", line 212, in train
    loss = loss_class(preds, batch)
  File "/root/dudaizhong/PaddleOCR/ppocr/losses/rec_ctc_loss.py", line 34, in __call__
    loss = self.loss_func(predicts, labels, preds_lengths, label_lengths)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/nn/layer/loss.py", line 961, in forward
    self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/paddle/nn/functional/loss.py", line 1104, in ctc_loss
    input_lengths, label_lengths)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/loss.py", line 610, in warpctc
    norm_by_times, )
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 57686) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:165)

INFO 2021-06-22 03:34:29,985 launch_utils.py:307] terminate all the procs
ERROR 2021-06-22 03:34:29,985 launch_utils.py:545] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2021-06-22 03:34:32,988 launch_utils.py:307] terminate all the procs

**Comment by ddz-mark** [comment]
定位不出问题的所在：设置 num_workers=0也不行，用的是 paddle-gpu==2.0.0

**Comment by WenmuZhou** [comment]
看看log/worker.0和log/worker.1文件里的日志有没有更具体的报错信息

**Comment by ddz-mark** [comment]
log/worker.1 报错：
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 625, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 709, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 5 workers exit unexpectedly, pids: 63142, 63144, 63148, 63150, 63152

worker.0 报错：
Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/root/dudaizhong/PaddleOCR/tools/program.py", line 230, in train
    post_result = post_process_class(preds, batch[1])
  File "/root/dudaizhong/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 114, in __call__
    preds = preds.numpy()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 63143) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:165)

**Comment by WenmuZhou** [comment]
感觉的多进程的问题，paddle升级看看

**Comment by ddz-mark** [comment]
升级到 2.0.1 和 2.1.0 还是报一样的错误，不知道咋解决？

**Comment by ddz-mark** [comment]
最后算是解决了吧，把所有的环境重启一次就好了，神奇，还是 paddle-gpu=2.0.0 的版本

**Comment by WenmuZhou** [comment]
好的

**Comment by Mythos-Rudy** [comment]
> 好的

> 最后算是解决了吧，把所有的环境重启一次就好了，神奇，还是 paddle-gpu=2.0.0 的版本，谢谢大佬解答

这个是共享内存的问题，有时候训练报错（如nan）或者暴力kill，共享内存不会释放，删除/dev/shm里面paddle相关的东西就好了  @WenmuZhou
