### ISSUE TITLE
No HubModule named chinese_ocr_db_crnn was found

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleOCR#3195]
Python 3.6.8 (default, Aug 24 2020, 17:57:11) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub as hub
>>> ocr_c = hub.Module(name="chinese_ocr_db_crnn")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 395, in __new__
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 493, in init_with_name
    ignore_env_mismatch=ignore_env_mismatch)
  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 270, in _install_from_name
    raise HubModuleNotFoundError(name=name, version=version)
paddlehub.module.manager.HubModuleNotFoundError: No HubModule named chinese_ocr_db_crnn was found
>>> ocr = hub.Module(name="chinese_ocr_db_crnn_server")

chinese_ocr_db_crnn_server是正常的，chinese_ocr_db_crnn报找不到
环境CentOS8.3   4.18.0-240.22.1.el8_3.x86_64 #

**Comment by MissPenguin** [comment]
你要找的应该是chinese_ocr_db_crnn_mobile吧
