### ISSUE TITLE
训练时几个epoch就会报错：too many open files

### ISSUE THREAD

**Issue by jinqi2376** [PaddlePaddle/PaddleOCR#3256]
我看了下issue，好像数据集比较小的时候会出这个问题，有什么办法可以解决呢

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
  File "tools/train.py", line 100, in main
  File "/home/jin/PaddleOCR/tools/program.py", line 204, in train
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _init_workers
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/multiprocessing/context.py", line 103, in Queue
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/multiprocessing/context.py", line 68, in Lock
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
  File "/home/jin/anaconda3/envs/PaddleOCR/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
OSError: [Errno 24] Too many open files
main proc 55459 exit, kill process group 52185

**Comment by LDOUBLEV** [comment]
Dataloader 的num_workes设置为0

**Comment by neverstoplearn** [comment]
> Dataloader 的num_workes设置为0

遇到
[2021/07/14 20:49:57] root INFO: epoch: [237/1200], iter: 29550, lr: 0.001000, loss: 2.368439, loss_shrink_maps: 1.387464, loss_threshold_maps: 0.696744, loss_binary_maps: 0.277520, reader_cost: 0.03110 s, batch_cost: 0.30250 s, samples: 80, ips: 26.44638
[2021/07/14 20:50:00] root INFO: epoch: [237/1200], iter: 29560, lr: 0.001000, loss: 2.405833, loss_shrink_maps: 1.416644, loss_threshold_maps: 0.707004, loss_binary_maps: 0.283814, reader_cost: 0.02186 s, batch_cost: 0.29110 s, samples: 80, ips: 27.48233
W0714 20:50:31.665927 85586 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0714 20:50:46.915261 85586 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0714 20:51:02.254369 85586 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0714 20:51:23.866822 85586 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0714 20:52:50.875423 85586 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
W0714 20:55:33.167798 85586 sampler.cpp:139] bvar is busy at sampling for 2 seconds!
已杀死

有什么办法可以解决吗？

**Comment by neverstoplearn** [comment]
你好，出现同样的问题后，将configs/det/det_mv3_db.yml中train和eval下的num_workers均改为0,出现以下错误：
bvar is busy  at sampling for 2 seconds!
killed

请问应该怎么解决，谢谢。
