### ISSUE TITLE
训练出现问题

### ISSUE THREAD

**Issue by ClearTorch** [PaddlePaddle/PaddleOCR#3303]
paddle 2.1.1 cuda10.2 cudann7, 训练时出现如下错误，请问怎么解决？

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/paddle/PaddleOCR/tools/program.py", line 216, in train
    loss = loss_class(preds, batch)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/PaddleOCR/ppocr/losses/det_db_loss.py", line 58, in forward
    label_shrink_mask)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/PaddleOCR/ppocr/losses/det_basic_loss.py", line 99, in forward
    sort_loss = negative_loss.sort(descending=True)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/tensor/search.py", line 455, in sort
    out, _ = core.ops.argsort(x, 'axis', axis, 'descending', descending)
SystemError: (Fatal) Operator argsort raises an thrust::system::detail::bad_alloc exception.
The exception content is
:std::bad_alloc: temporary_buffer::allocate: get_temporary_buffer failed. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

**Comment by MissPenguin** [comment]
用paddle2.1.0试试呢，2.1.1我们还没做兼容性测试

**Comment by TangJiamin** [comment]
> 用paddle2.1.0试试呢，2.1.1我们还没做兼容性测试

使用paddle2.1.0训练ch_db_res18检测模型也出现了这个问题

**Comment by huahuabai** [comment]
使用2.2.1也不对呀
