### ISSUE TITLE
python -GPU版本安装时，导入paddle报错

### ISSUE THREAD

**Issue by Sandwichzhao** [PaddlePaddle/PaddleOCR#3319]
Error: Can not import avx core while this file exists: /data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/fluid/core.py", line 297, in <module>
    raise e
  File "/data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/fluid/core.py", line 257, in <module>
    from .core_avx import *
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /data1/bigdata/zhao/zhao_env/lib/python3.6/site-packages/paddle/fluid/core_avx.so)
环境：Python 3.6.6
OS：
      x86_64
      CentOS Linux release 7.6.1810 (Core)
      NAME="CentOS Linux"
      VERSION="7 (Core)"
      ID="centos"
      ID_LIKE="rhel fedora"
      VERSION_ID="7"
      PRETTY_NAME="CentOS Linux 7 (Core)"
      ANSI_COLOR="0;31"
      CPE_NAME="cpe:/o:centos:centos:7"
      HOME_URL="https://www.centos.org/"
      BUG_REPORT_URL="https://bugs.centos.org/"

**Comment by WenmuZhou** [comment]
参考这个博客看看 https://blog.csdn.net/sinat_24820331/article/details/53895244
