### ISSUE TITLE
训练 det_r50_vd_db 网络的时候，验证eval阶段出现bug

### ISSUE THREAD

**Issue by hanguangmic** [PaddlePaddle/PaddleOCR#3339]
bug记录如下，不知道为什么Memory map failed when create shared memory，我是从官网上下的docker，老是这一步出错。
求大神们指导一下

eval model::   2%|███                                                                                                                                                                          | 30/1667 [00:03<03:12,  8.51it/s]Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/worker.py", line 254, in _worker_loop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/worker.py", line 244, in _worker_loop
    for b in batch
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/worker.py", line 244, in <listcomp>
    for b in batch
RuntimeError: (Unavailable) Memory map failed when create shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:81)

eval model::   2%|███▎                                                                                                                                                                         | 32/1667 [00:03<02:47,  9.78it/s]ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 498, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 392985

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/others/PaddleOCR/tools/program.py", line 272, in train
    use_srn=use_srn)
  File "/home/others/PaddleOCR/tools/program.py", line 348, in eval
    for idx, batch in enumerate(valid_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by MissPenguin** [comment]
docker的共享内存多大

**Comment by MissPenguin** [comment]
建议4G以上

**Comment by hanguangmic** [comment]
> 建议4G以上

大佬 这个我用的是100G的shm 专门设置过

**Comment by lqniunjunlper** [comment]
Same question! Testing 600 imgs
shm>4

**Comment by lqniunjunlper** [comment]
> > 建议4G以上
> 
> 大佬 这个我用的是100G的shm 专门设置过

解决了吗

**Comment by lqniunjunlper** [comment]
@hanguangmic @MissPenguin 解决了吗 啥问题
