### ISSUE TITLE
使用ch_db_res18双卡训练时，异常DataLoader reader thread raised an exception!

### ISSUE THREAD

**Issue by llooper-dev** [PaddlePaddle/PaddleOCR#3340]
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 497, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 6581
Traceback (most recent call last):
  File "/home/paddlepaddle/PaddleOCR/tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/paddlepaddle/PaddleOCR/tools/train.py", line 100, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/paddlepaddle/PaddleOCR/tools/program.py", line 204, in train
    for idx, batch in enumerate(train_dataloader):
  File "/home/software/miniconda3/envs/python38.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

INFO 2021-07-14 23:45:31,863 launch_utils.py:327] terminate all the procs
ERROR 2021-07-14 23:45:31,864 launch_utils.py:582] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-07-14 23:45:34,867 launch_utils.py:327] terminate all the procs

**Comment by LDOUBLEV** [comment]
训练中出现的还是一开始训练就出现了
建议
- 先把num_workers改为0 再试下
- df -h 看下/dev/shm目录下有多少空间，是不是空间满了，可以放心的清理下
- 如果上面两个方法不行，建议检查下你的数据和标签格式是不是对的

**Comment by llooper-dev** [comment]
![image](https://user-images.githubusercontent.com/65935005/125756807-c888f5ba-d354-4fdd-b0b0-b974aee7fd40.png)
Train和Eval的num_workers都改为0 了。
也加上  use_shared_memory: False。
但内存就不断的往上升，最终还是oom被killed，哪时出错了吗？
