### ISSUE TITLE
训练出现问题，提示too many files, 将num_works改为0，到191epochs直接被kill,有解决办法和思路吗？

### ISSUE THREAD

**Issue by neverstoplearn** [PaddlePaddle/PaddleOCR#3341]

**Comment by neverstoplearn** [comment]
环境为  3060   cudatoolkit=11.2  python=3.7  paddle=2.1.1

**Comment by LDOUBLEV** [comment]
> 到191epochs直接被kill

有报错信息吗

**Comment by neverstoplearn** [comment]
> > 到191epochs直接被kill
> 
> 有报错信息吗

没有报错信息，训练过程中出现kill字样，然后程序中断。

**Comment by LDOUBLEV** [comment]
不能确定是程序出问题了，也可能是其他原因，建议你启动的时候加上--log_dir，如下：

python3 -m paddle.distributed.launch --log_dir=./debug/  --gpus '0,1'  tools/train.py -c configs/rec/your_config.yml 

训练的报错信息也会打印到--lod_dir中，查看日志即可知道是否其他报错，

另外，训练过程中看下内存占用，是否存在内存不断上涨的问题

**Comment by neverstoplearn** [comment]
将num_workers=2,目前到222epochs，没有出现问题，内存稳定在11G左右。

**Comment by neverstoplearn** [comment]
> 将num_workers=2,目前到222epochs，没有出现问题，内存稳定在11G左右。

272又断了

**Comment by neverstoplearn** [comment]
> 不能确定是程序出问题了，也可能是其他原因，建议你启动的时候加上--log_dir，如下：
> 
> python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0,1' tools/train.py -c configs/rec/your_config.yml
> 
> 训练的报错信息也会打印到--lod_dir中，查看日志即可知道是否其他报错，
> 
> 另外，训练过程中看下内存占用，是否存在内存不断上涨的问题
训练过程中内存不断增长

**Comment by neverstoplearn** [comment]
> 不能确定是程序出问题了，也可能是其他原因，建议你启动的时候加上--log_dir，如下：
> 
> python3 -m paddle.distributed.launch --log_dir=./debug/  --gpus '0,1'  tools/train.py -c configs/rec/your_config.yml 
> 
> 训练的报错信息也会打印到--lod_dir中，查看日志即可知道是否其他报错，
> 
> 另外，训练过程中看下内存占用，是否存在内存不断上涨的问题
> 

训练过程中内存不断增长

**Comment by MooncellAutomaton** [comment]
打開文件數量過多嗎?
ulimit -a 查看最大打開文件數量
ulimit -n 4096 設置成4096(運行訓練的那個終端),

**Comment by neverstoplearn** [comment]
> 打開文件數量過多嗎?
> ulimit -a 查看最大打開文件數量
> ulimit -n 4096 設置成4096(運行訓練的那個終端),

尝试过ulimit - n 10240，仍然会出现这个问题，直接被kill，训练过程中内存不断增加，应该是内存泄漏的问题。

**Comment by chenglong-do** [comment]
哪个版本…以前用1.1训练的时候容易这样挂掉，后面换2.1了没出现过…1.1的时候就是改小 batch_size 和 num_works

**Comment by neverstoplearn** [comment]
> 哪个版本…以前用1.1训练的时候容易这样挂掉，后面换2.1了没出现过…1.1的时候就是改小 batch_size 和 num_works

2.1.1

**Comment by MooncellAutomaton** [comment]
你pip list能看到paddlepaddle和paddlepaddle-gpu共存吗?
我安装paddlepaddle==2.1.1后再卸载,再安装paddlepaddle-gpu==2.0.2.post101版本,能解决
地址: https://www.paddlepaddle.org.cn/whl/mkl/stable.html
我cuda版本:11.2,ubuntu:20.04

把数据集改成几张图片能看到内存上升epoch有关,更快速看出来是否解决问题.

**Comment by neverstoplearn** [comment]
> 你pip list能看到paddlepaddle和paddlepaddle-gpu共存吗?
> 我安装paddlepaddle==2.1.1后再卸载,再安装paddlepaddle-gpu==2.0.2.post101版本,能解决
> 地址: https://www.paddlepaddle.org.cn/whl/mkl/stable.html
> 我cuda版本:11.2,ubuntu:20.04
> 
> 把数据集改成几张图片能看到内存上升epoch有关,更快速看出来是否解决问题.

pip list看到的是paddlepaddle-gpu=2.1.1.post112
没有paddlepaddle
我的硬件也是ubuntu20.04  CUDA  11.2

**Comment by MooncellAutomaton** [comment]
> > 你pip list能看到paddlepaddle和paddlepaddle-gpu共存吗?
> > 我安装paddlepaddle==2.1.1后再卸载,再安装paddlepaddle-gpu==2.0.2.post101版本,能解决
> > 地址: https://www.paddlepaddle.org.cn/whl/mkl/stable.html
> > 我cuda版本:11.2,ubuntu:20.04
> > 把数据集改成几张图片能看到内存上升epoch有关,更快速看出来是否解决问题.
> 
> pip list看到的是paddlepaddle-gpu=2.1.1.post112
> 没有paddlepaddle
> 我的硬件也是ubuntu20.04 CUDA 11.2

试下2.0.2.post101版本吧,这个版本训练侦测模型(det)没问题,
但是训练识别模型(rec),导出模型会报错,得装成2.1.1.post112才能正常导出

**Comment by neverstoplearn** [comment]
# 那这也太尴尬了吧 还得来回切换

**Comment by neverstoplearn** [comment]
> > > 你pip list能看到paddlepaddle和paddlepaddle-gpu共存吗?
> > > 我安装paddlepaddle==2.1.1后再卸载,再安装paddlepaddle-gpu==2.0.2.post101版本,能解决
> > > 地址: https://www.paddlepaddle.org.cn/whl/mkl/stable.html
> > > 我cuda版本:11.2,ubuntu:20.04
> > > 把数据集改成几张图片能看到内存上升epoch有关,更快速看出来是否解决问题.
> > 
> > 
> > pip list看到的是paddlepaddle-gpu=2.1.1.post112
> > 没有paddlepaddle
> > 我的硬件也是ubuntu20.04 CUDA 11.2
> 
> 试下2.0.2.post101版本吧,这个版本训练侦测模型(det)没问题,
> 但是训练识别模型(rec),导出模型会报错,得装成2.1.1.post112才能正常导出

那这也太尴尬了吧 还得来回切换

**Comment by ykpercy** [comment]
我之前在本机预测也出现图片太多，服务直接kill。本机内存16G，把服务装在64G内存的服务器上就可以。

**Comment by ykpercy** [comment]
不过现在出现新的情况，有时候预测一张图片直接报错。还没定位到问题，可以帮忙看看。
报错信息：
```
[2021/07/21 10:38:32] root INFO: dt_boxes num : 49, elapse : 2.983171224594116
Traceback (most recent call last):
  File "/home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py", line 251, in <module>
    res = ocr.predict(paths=image_path)
  File "/home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py", line 170, in predict
    dt_boxes, rec_res = self.text_sys(img)
  File "/home/percy/OCR_picture/PaddleOCR/./tools/infer/predict_system.py", line 109, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/percy/OCR_picture/PaddleOCR/./tools/infer/predict_rec.py", line 243, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/percy/OCR_picture/PaddleOCR/./ppocr/postprocess/rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/percy/OCR_picture/PaddleOCR/./ppocr/postprocess/rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range
```
