### ISSUE TITLE
'NoneType' object has no attribute 'get_fetch_list'

### ISSUE THREAD

**Issue by legendary111** [PaddlePaddle/PaddleOCR#3346]
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main()
  File "train.py", line 128, in main
    exe.run(fluid.default_startup_program())
  File "/home/songcq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/songcq/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/songcq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/songcq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/songcq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1233, in _run_program
    arr = scope.find_var(fetch_var_name).get_fetch_list()
AttributeError: 'NoneType' object has no attribute 'get_fetch_list'
用的是1.8.5版本 为啥会这样？

**Comment by LDOUBLEV** [comment]
测试了develop分支的代码使用ic15可以跑通，建议检查下代码修改
