### ISSUE TITLE
paddlehub推理小尺寸图像报错IndexError: list index out of range

### ISSUE THREAD

**Issue by ykpercy** [PaddlePaddle/PaddleOCR#3358]
本地运行代码：
`python3 /home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py`

运行deploy/hubserving/ocr_system/module.py时，图片改成测试图片./doc/imgs/00207393.jpg出现错误：

```
Traceback (most recent call last):
  File "/home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py", line 217, in <module>
    res = ocr.predict(paths=image_path)
  File "/home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py", line 137, in predict
    dt_boxes, rec_res = self.text_sys(img)
  File "/home/percy/OCR_picture/PaddleOCR/./tools/infer/predict_system.py", line 109, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/percy/OCR_picture/PaddleOCR/./tools/infer/predict_rec.py", line 243, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/percy/OCR_picture/PaddleOCR/./ppocr/postprocess/rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/percy/OCR_picture/PaddleOCR/./ppocr/postprocess/rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range
```
这个图片大小是50.5K，图片尺寸HW是375 * 489
并没有内存溢出的情况，现在不知道问题出在哪里。

**Comment by versusniubility** [comment]
mark一下，同问题
