### ISSUE TITLE
IndexError: list index out of range, when using SAST in paddleocr.py

### ISSUE THREAD

**Issue by neonin04** [PaddlePaddle/PaddleOCR#3383]
I added SAST related code in paddleocr.py:
`SUPPORT_DET_MODEL = ['DB', 'SAST']`
`parser.add_argument("--det_algorithm", type=str, default='SAST')`
```
#SAST params
        parser.add_argument("--det_sast_score_thresh", type=float, default=0.5)
        parser.add_argument("--det_sast_nms_thresh", type=float, default=0.2)
        parser.add_argument("--det_sast_polygon", type=bool, default=False)
```
```
det_sast_score_thresh=0.5,
            det_sast_nms_thresh=0.2,
            det_sast_polygon=False,
```
`det_algorithm='SAST'`

but this error comes out..
```
Traceback (most recent call last):
  File "ocr_multi.py", line 10, in <module>
    result = ocr.ocr(img_path, cls = True)
  File "/mnt/net/i2x256-ai01/hotel/sihwang/PaddleOCR/paddleocr.py", line 392, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/mnt/net/i2x256-ai01/hotel/sihwang/PaddleOCR/tools/infer/predict_system.py", line 90, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/mnt/net/i2x256-ai01/hotel/sihwang/PaddleOCR/tools/infer/predict_det.py", line 182, in __call__
    preds['f_score'] = outputs[1]
IndexError: list index out of range
```

what changes should I make in which files??
I looked into `predict_det.py`, but still have no idea what to change..

thank you!!

**Comment by tink2123** [comment]
The post-processing logic of the SAST model is not encapsulated in the whl package, you can refer to predict_det.py to add relevant code.

https://github.com/PaddlePaddle/PaddleOCR/blob/e10128ac4c8218beb15187ba460eabb149c7270c/tools/infer/predict_det.py#L76-L93
