### ISSUE TITLE
hub运行ocr_system预测服务，识别单张图片报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by ykpercy** [PaddlePaddle/PaddleOCR#3387]
报错信息：
```
[2021/07/21 10:38:32] root INFO: dt_boxes num : 49, elapse : 2.983171224594116
Traceback (most recent call last):
  File "/home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py", line 251, in <module>
    res = ocr.predict(paths=image_path)
  File "/home/percy/OCR_picture/PaddleOCR/deploy/hubserving/ocr_system/module.py", line 170, in predict
    dt_boxes, rec_res = self.text_sys(img)
  File "/home/percy/OCR_picture/PaddleOCR/./tools/infer/predict_system.py", line 109, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/percy/OCR_picture/PaddleOCR/./tools/infer/predict_rec.py", line 243, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/percy/OCR_picture/PaddleOCR/./ppocr/postprocess/rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/percy/OCR_picture/PaddleOCR/./ppocr/postprocess/rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range
```

**Comment by tink2123** [comment]
麻烦提供一下预测命令，我们复现一下。

**Comment by ykpercy** [comment]
这是修改过的代码，增加了识别文本保存为TXT文件的处理。
另外有个参数det_limit_side_len = 22400，推理模型用的mobile。
```
# -*- coding:utf-8 -*-
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import sys
sys.path.insert(0, ".")
import copy
import json
import imghdr

import time
import re

from paddlehub.common.logger import logger
from paddlehub.module.module import moduleinfo, runnable, serving
import cv2
import numpy as np
import paddlehub as hub

from tools.infer.utility import base64_to_cv2
from tools.infer.predict_system import TextSystem
from tools.infer.utility import parse_args
from deploy.hubserving.ocr_system.params import read_params
# from ppocr.utils.utility import get_image_file_list


@moduleinfo(
    name="ocr_system",
    version="1.0.0",
    summary="ocr system service",
    author="paddle-dev",
    author_email="paddle-dev@baidu.com",
    type="cv/text_recognition")
class OCRSystem(hub.Module):
    def _initialize(self, use_gpu=False, enable_mkldnn=False):
        """
        initialize with the necessary elements
        """
        cfg = self.merge_configs()

        cfg.use_gpu = use_gpu
        if use_gpu:
            try:
                _places = os.environ["CUDA_VISIBLE_DEVICES"]
                int(_places[0])
                print("use gpu: ", use_gpu)
                print("CUDA_VISIBLE_DEVICES: ", _places)
                cfg.gpu_mem = 8000
            except:
                raise RuntimeError(
                    "Environment Variable CUDA_VISIBLE_DEVICES is not set correctly. If you wanna use gpu, please set CUDA_VISIBLE_DEVICES via export CUDA_VISIBLE_DEVICES=cuda_device_id."
                )
        cfg.ir_optim = True
        cfg.enable_mkldnn = enable_mkldnn

        self.text_sys = TextSystem(cfg)

    def merge_configs(self, ):
        # deafult cfg
        backup_argv = copy.deepcopy(sys.argv)
        sys.argv = sys.argv[:1]
        cfg = parse_args()

        update_cfg_map = vars(read_params())

        for key in update_cfg_map:
            cfg.__setattr__(key, update_cfg_map[key])

        sys.argv = copy.deepcopy(backup_argv)
        return cfg

    # the function is deprecated
    # def match_string(self, txt):
    #     """
    #     description: detected phone number and mail
    #     input: txt | string of list
    #     output: txt | post process string of list
    #     """
    #     string_line = ','.join(txt)
    #     # phone_re = '1[0-9]{2}' + '-*?[0-9]{4}' + '-*?[0-9]{4}'
    #     try:
    #         phone_re = '1[0-9]{10}'
    #         phone = re.search(phone_re, string_line).group(0)
    #         pass
    #     except AttributeError:
    #         phone_re = '1[0-9]{2}' + '-[0-9]{4}' + '-[0-9]{4}'
    #         phone = re.search(phone_re, string_line).group(0)
    #
    #     pat = phone + '.{0,20}' + 'com'
    #     ori_mail = re.search(pat, string_line).group(0)
    #     mail = ori_mail.replace(phone, '')[1:]  # separate the special symbol
    #     if '-' in phone:
    #         phone = re.sub('-', '', phone)
    #     string_line = string_line.replace(ori_mail, phone + ',' + mail)
    #     txt = [i for i in string_line.split(',')]
    #     # txt.append(phone)
    #     # txt.append(mail)
    #     if phone is None:
    #         print(f"phone number don't detected")
    #     # print(f'phone number is {phone}\nmail is {mail}')
    #     # print(txt)
    #     return txt

    def read_images(self, paths=[]):
        images = []
        for img_path in paths:
            assert os.path.isfile(
                img_path), "The {} isn't a valid file.".format(img_path)
            img = cv2.imread(img_path)
            if img is None:
                logger.info("error in loading image:{}".format(img_path))
                continue
            images.append(img)
        return images

    # transfer the path to image file list
    def get_image_file_list(self, img_file):
        imgs_lists = []
        if img_file is None or not os.path.exists(img_file):
            raise Exception("not found any img file in {}".format(img_file))

        img_end = {'jpg', 'bmp', 'png', 'jpeg', 'rgb', 'tif', 'tiff', 'gif', 'GIF'}
        if os.path.isfile(img_file) and imghdr.what(img_file) in img_end:
            imgs_lists.append(img_file)
        elif os.path.isdir(img_file):
            for single_file in os.listdir(img_file):
                file_path = os.path.join(img_file, single_file)
                if os.path.isfile(file_path) and imghdr.what(file_path) in img_end:
                    imgs_lists.append(file_path)
        if len(imgs_lists) == 0:
            raise Exception("not found any img file in {}".format(img_file))
        # imgs_lists = sorted(imgs_lists)
        return imgs_lists

    def predict(self, images=[], paths=[]):
        """
        Get the chinese texts in the predicted images.
        Args:
            images (list(numpy.ndarray)): images data, shape of each is [H, W, C]. If images not paths
            paths (list[str]): The paths of images. If paths not images
            paths example: ['./doc/imgs/11.jpg', './doc/imgs/12.jpg']
                           './doc/imgs/11.jpg'
                           './doc/imgs/'
        Returns:
            res (list): The result of chinese texts and save path of images.
        """
        if images:
            predicted_data = images
        elif isinstance(paths, list) and paths != []:
            predicted_data = self.read_images(paths)
        elif os.path.isfile(paths) or os.path.isdir(paths):
            paths = self.get_image_file_list(paths)
            predicted_data = self.read_images(paths)
        else:
            raise TypeError("The input data is inconsistent with expectations.")

        assert predicted_data != [], "There is not any image to be predicted. Please checithe input data."
        # print(f'predict function output is {predicted_data}')

        all_results = []
        i = 0
        for img, image_file in zip(predicted_data, paths):
            if img is None:
                logger.info("error in loading image")
                all_results.append([])
                continue
            starttime = time.time()
            dt_boxes, rec_res = self.text_sys(img)
            elapse = time.time() - starttime
            logger.info("Predict time: {}".format(elapse))

            dt_num = len(dt_boxes)
            # rec_res_final = []
            text_file = []

            for dno in range(dt_num):
                text, score = rec_res[dno]
                text_file.append(text)
                # rec_res_final.append({
                #     'text': text_file
                #     # 'confidence': float(score),
                #     # 'text_region': dt_boxes[dno].astype(np.int).tolist()
                # })
            # text_file = self.match_string(text_file)

            all_results.append({
                'text': '\n'.join(text_file)
                # 'text_region': dt_boxes[dno].astype(np.int).tolist()
            })
            # print(all_results[0]['text'])
            text_content = all_results
            if text_content is not None:
                text_path = './inference_file/resume_text/'
                if not os.path.exists(text_path):
                    os.makedirs(text_path)
            image_name = os.path.basename(image_file).split('.')[0] + '.txt'
            text_path = os.path.join('./inference_file/resume_text/', image_name)
            with open(text_path, 'w') as file:
                # text = json.dumps(all_results[i], ensure_ascii=False)
                # file.write(text)
                for text in all_results[i]['text']:
                    file.write(text)
            logger.info(f"text file saved in {text_path}")
            i += 1

            # img_name = os.path.basename(img_path)
            # save_name = img_name.split('.')[0] + '.json'
            # save_path = os.path.join('./inference_text/', save_name)
            # with open(save_path, 'w') as f:  # save the file
            #     text = json.dumps(rec_res_final)
            #     f.write(text)
            #
            # print(f'text saved in {save_path}')
            # all_results.append(rec_res_final)
        # return output_str
        return all_results

    @serving
    def serving_method(self, images, paths, **kwargs):
        """
        Run as a service.
        """
        images_decode = [base64_to_cv2(image) for image in images]
        results = self.predict(images_decode, paths)
        return results

    # @serving
    # def serving_method(self, image_path, **kwargs):
    #     """
    #     Run as a service.
    #     """
    #     images_decode = [base64_to_cv2(image) for image in images]
    #     if isinstance(image_path, list) and image_path != []:
    #         paths = image_path
    #     elif os.path.isfile(image_path) or os.path.isdir(image_path):
    #         paths = self.get_image_file_list(image_path)
    #     results = self.predict(paths)
    #     return results


if __name__ == '__main__':
    ocr = OCRSystem()
    # image_path = [
    #     './doc/imgs/11.jpg',
    #     './doc/imgs/12.jpg',
    #     './doc/imgs/00207393.jpg',
    #     './doc/imgs/20210513204823870_zhwCV.png'
    # ]
    image_path = './doc/imgs/00207393.jpg'
    res = ocr.predict(paths=image_path)
    print(res)

```

**Comment by ykpercy** [comment]
> 麻烦提供一下预测命令，我们复现一下。

请问有复现出相同的问题吗

**Comment by Joevaen** [comment]
我这儿也有这个问题啊，按理说默认模式是'ch'，怎么会预测英文呢？我预测中文出问题的

**Comment by ykpercy** [comment]
> 我这儿也有这个问题啊，按理说默认模式是'ch'，怎么会预测英文呢？我预测中文出问题的

这个预测中文'ch'模式，字典里面包括中文字符和英文字母，还有特殊符号，总共有6000多个中英文字符，所以可以预测英文的。

**Comment by ykpercy** [comment]
单张图片读取不到的错误已经定位到了，是我修改的读取image部分存在读取为空的情况，所以最终报错list为空。
只要改回原始的读取image的方式即可。

**Comment by vance-coder** [comment]
我这里指定字典就行了
--rec_char_dict_path=vocab.txt
