### ISSUE TITLE
导出模型报错“AssertionError: Bad argument number for Assign: 2, expecting 3”

### ISSUE THREAD

**Issue by YY007H** [PaddlePaddle/PaddleOCR#3396]
系统：ubuntu 20.04
PaddleOCR分支：release/2.1
报错信息：
(venv) su@su-SYS-4028GR-TR:~/PycharmProjects/PaddleOCR-release/2.1$ python tools/export_model.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0_myself.yml -o Global.pretrained_model=./output/rec_chinese_lite_v2.0/best_accuracy Global.save_inference_dir=./inference/rec_chinese_lite_v2.0
/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
W0722 09:11:27.925444 1890825 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 11.0
W0722 09:11:27.928567 1890825 device_context.cc:372] device: 0, cuDNN Version: 8.0.
[2021/07/22 09:11:30] root INFO: load pretrained model from ['./output/rec_chinese_lite_v2.0/best_accuracy']
Traceback (most recent call last):
  File "tools/export_model.py", line 95, in <module>
    main()
  File "tools/export_model.py", line 90, in main
    paddle.jit.save(model, save_path)
  File "<decorator-gen-60>", line 2, in save
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 620, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
    static_func = self._convert(func)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 116, in _convert
    root_wrapper = self._dygraph_to_static.get_static_ast(root)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 61, in get_static_ast
    self.transfer_from_node_type(self.static_analysis_root)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 92, in transfer_from_node_type
    self._apply(transformer, node_wrapper, log_level=index + 1)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 65, in _apply
    transformer(node_wrapper).transform()
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ifelse_transformer.py", line 55, in transform
    self.visit(self.root)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 439, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 439, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ifelse_transformer.py", line 62, in visit_If
    new_node = create_convert_ifelse_node(return_name_ids, node.test,
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ifelse_transformer.py", line 540, in create_convert_ifelse_node
    _, cond_node = create_assign_node(return_name_ids, convert_ifelse_layer)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 439, in create_assign_node
    assign_node = gast.Assign(targets=[targets], value=node)
  File "/home/su/PycharmProjects/PaddleOCR-release/venv/lib/python3.8/site-packages/gast/gast.py", line 17, in create_node
    assert nbparam in (0, len(Fields)), \
AssertionError: Bad argument number for Assign: 2, expecting 3

**Comment by eggachecat** [comment]
+1

**Comment by eggachecat** [comment]
Update: `pip install -U gast==0.3.3 ` nailed it in my case

**Comment by haigege** [comment]
gast的版本太高，降一下版本。可以安装gast==0.3.3

**Comment by YY007H** [comment]
> gast的版本太高，降一下版本。可以安装gast==0.3.3

好使，多谢多谢！
