### ISSUE TITLE
predict_system.py --det_algorithm EAST

### ISSUE THREAD

**Issue by gekie** [PaddlePaddle/PaddleOCR#34]
Traceback (most recent call last):
  File "/projects/python/PaddleOCR/tools/infer/predict_system.py", line 115, in <module>
    dt_boxes, rec_res = text_sys(img)
  File "/projects/python/PaddleOCR/tools/infer/predict_system.py", line 67, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/projects/python/PaddleOCR/tools/infer/predict_det.py", line 143, in __call__
    outs_dict['f_geo'] = outputs[1]
IndexError: list index out of range

**Comment by dyning** [comment]
感谢关注和试用，目前还在紧急修复和更新相关文档中。今天会同步进展。

**Comment by dyning** [comment]
问题已修复，文档已更新，请查看
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/inference.md，
里面详细介绍了文字检测、文字识别以及串联系统的推理过程。
