### ISSUE TITLE
GPU单机运行失败

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3400]
cuda: 10.1
cuDNN Version: 7.6

安装
pip install paddle==1.0.2 -i https://mirror.baidu.com/pypi/simple
python -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

代码运行失败：
OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:371)

**Comment by WenmuZhou** [comment]
运行一下paddle检测命令吧，paddle.utils.run_check()

**Comment by LinXin04** [comment]
不安装paddlepaddle-gpu就没事，安装就报错。运行paddle.utils.run_check()提示：


W0726 09:49:03.588065 739 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0726 09:49:03.685165 739 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Running verify PaddlePaddle program ...

Traceback (most recent call last):
File "test.py", line 4, in <module>
paddle.utils.run_check()
File "/root/miniconda3/lib/python3.6/site-packages/paddle/utils/install_check.py", line 196, in run_check
_run_static_single(use_cuda)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
exe.run(startup_prog)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1110, in run
six.reraise(*sys.exc_info())
File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 703, in reraise
raise value
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
return_merged=return_merged)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
use_program_cache=use_program_cache)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
[fetch_var_name])
OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:371)
 
main process return code: 1
not found core file

**Comment by WenmuZhou** [comment]
cudnn装了吗
