### ISSUE TITLE
使用PGNet训练印章文字识别

### ISSUE THREAD

**Issue by tjpulfn** [PaddlePaddle/PaddleOCR#3426]
使用gpu训练印章文字识别，报错
`Traceback (most recent call last):
  File "tools/train.py", line 122, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    post_process_class, eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/root/liufn/PaddlePaddle/PaddleOCR/tools/program.py", line 198, in train
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:76)
  [operator < gaussian_random > error]
(paddle) [root@gpu PaddleOCR]# exit()
>
> ^C
    f_char = self.conv3(f_char)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 643, in forward
    use_cudnn=self._use_cudnn)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
OSError: (External)  Cudnn error, CUDNN_STATUS_NOT_SUPPORTED  (at /paddle/paddle/fluid/platform/cudnn_desc.h:163)
  [operator < conv2d > error]`

请问这个问题怎么解决，cuda是10.2，cudnn是7.6.5，paddle-gpu是2.0.0，使用cpu训练时没有问题，已经更换过cuda，和cudnn的版本之前用过cudn11.4，cudnn8.0，paddle用过2.2.0，一直不成功
请问一下各位怎么办，paddle有技术支持群吗

**Comment by tjpulfn** [comment]
完整报错

`W0726 10:47:33.674480  9248 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0726 10:47:33.680397  9248 device_context.cc:372] device: 0, cuDNN Version: 7.6.
[2021/07/26 10:47:37] root INFO: train from scratch
[2021/07/26 10:47:37] root INFO: train dataloader has 379 iters
[2021/07/26 10:47:37] root INFO: valid dataloader has 521 iters
----------start train----------
[2021/07/26 10:47:37] root INFO: During the training process, after the 0th iteration, an evaluation is run every 1000 iterations
----------makedir save model----------
----------epoch start----------
----------load data----------
Traceback (most recent call last):
  File "tools/train.py", line 122, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    post_process_class, eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/root/liufn/PaddlePaddle/PaddleOCR/tools/program.py", line 198, in train
    preds = model(images)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/liufn/PaddlePaddle/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 78, in forward
    x = self.head(x)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/liufn/PaddlePaddle/PaddleOCR/ppocr/modeling/heads/e2e_pg_head.py", line 213, in forward
    f_char = self.conv3(f_char)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 643, in forward
    use_cudnn=self._use_cudnn)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
OSError: (External)  Cudnn error, CUDNN_STATUS_NOT_SUPPORTED  (at /paddle/paddle/fluid/platform/cudnn_desc.h:163)
  [operator < conv2d > error]`

**Comment by tink2123** [comment]
请问是否是在dokcer里运行的呢？ 同时安装的paddle版本需要和你本地的cuda环境一致。安装问题也可以去[Paddle](https://github.com/PaddlePaddle/Paddle/issues) 提一个issue，安装同学会帮忙解决。
