### ISSUE TITLE
安装GPU版本报错

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3440]
AIstudio上GPU安装指令
python -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple

Error: Can not import avx core while this file exists: /root/miniconda3/lib/python3.6/site-packages/paddle/fluid/core_avx.so

torch版本： 1.9.0+cu102
cuda版本： 10.2
cudnn版本： 7605
Traceback (most recent call last):
File "test.py", line 8, in <module>
import paddle
File "/root/miniconda3/lib/python3.6/site-packages/paddle/__init__.py", line 25, in <module>
from .fluid import monkey_patch_variable
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 36, in <module>
from . import framework
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 37, in <module>
from . import core
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/core.py", line 297, in <module>
raise e
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/core.py", line 257, in <module>
from .core_avx import *
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/miniconda3/lib/python3.6/site-packages/paddle/fluid/core_avx.so)
main process return code: 1
not found core file

**Comment by WenmuZhou** [comment]
你这是安装了之后使用报错，还是安装报错啊，我看你的miniconda下已经有paddle了

**Comment by LinXin04** [comment]
安装好了，import paddle的时候报错

**Comment by LinXin04** [comment]
AI studio的镜像选择tensorflow的还是pytorch的？

**Comment by LinXin04** [comment]
那import paddle的时候报错是怎么回事呢？

**Comment by LinXin04** [comment]
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/miniconda3/lib/python3.6/site-packages/paddle/fluid/core_avx.so)

**Comment by ioracion** [comment]
老兄 看到你帖子好几次了，你创建完项目后，在啥也没动的情况下， import paddle 真的会报错嘛..?（我刚自己新建了个项目，import paddle没问题）你会不会是启动环境用CPU版本了？

**Comment by LinXin04** [comment]
我确认了一下，不是用的飞浆的AIstudio，是我们自己的GPU环境。。。。一直调试不通过

**Comment by WenmuZhou** [comment]
`CXXABI_1.3.8' not found  你百度一下这个
