### ISSUE TITLE
release/2.1 分支上 rec_mv3_tps_bilstm_att.yml 使用自己的数据训练报错

### ISSUE THREAD

**Issue by thomaszheng** [PaddlePaddle/PaddleOCR#3448]
在release/2.1分支上同一份训练数据和测试数据，rec_mv3_tps_bilstm_ctc.yml 这个配置可以正常训练，但是rec_mv3_tps_bilstm_att.yml 这个配置，会报错：（其他配置没有变化，SimpleDataset 这个类型的数据数据）

ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/root/dudaizhong/PaddleOCR/tools/program.py", line 199, in train
    for idx, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 788, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by thomaszheng** [comment]
我这边将rec_mv3_tps_bilstm_att.yml 里面的 Train.transforms 中label生成的方式从 AttnLabelEncode 调整为 CTCLabelEncode,就可以正常读取了，初步定位可能是 AttnLabelEncode 处理训练数据中的一些记录出现读取异常
