### ISSUE TITLE
AIStudio上安装paddlepaddle-GPU报错

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/PaddleOCR#3450]
[2021/07/28 13:24:11] root INFO: keep_keys : ['image', 'label', 'length']
--
[2021/07/28 13:24:11] root INFO: loader :
[2021/07/28 13:24:11] root INFO: batch_size_per_card : 10
[2021/07/28 13:24:11] root INFO: drop_last : True
[2021/07/28 13:24:11] root INFO: num_workers : 4
[2021/07/28 13:24:11] root INFO: shuffle : True
[2021/07/28 13:24:11] root INFO: train with paddle 2.1.1 and device CUDAPlace(0)
[2021/07/28 13:24:11] root INFO: Initialize indexs of datasets:['./train_data/rec/rec_gt_train_format.txt']
[2021/07/28 13:24:12] root INFO: Initialize indexs of datasets:['./train_data/rec/rec_gt_test_format.txt']
W0728 13:24:12.053575 783 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0728 13:24:12.184676 783 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
File "tools/train.py", line 126, in <module>
main(config, device, logger, vdl_writer)
File "tools/train.py", line 77, in main
model = build_model(config['Architecture'])
File "/workspace/bin/ppocr/modeling/architectures/__init__.py", line 23, in build_model
module_class = BaseModel(config)
File "/workspace/bin/ppocr/modeling/architectures/base_model.py", line 52, in __init__
self.backbone = build_backbone(config["Backbone"], model_type)
File "/workspace/bin/ppocr/modeling/backbones/__init__.py", line 39, in build_backbone
module_class = eval(module_name)(**config)
File "/workspace/bin/ppocr/modeling/backbones/rec_mobilenet_v3.py", line 100, in __init__
name='conv1')
File "/workspace/bin/ppocr/modeling/backbones/det_mobilenet_v3.py", line 179, in __init__
bias_attr=False)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
data_format=data_format)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
default_initializer=_get_default_param_initializer())
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
default_initializer)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
**attr._to_kwargs(with_initializer=True))
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2858, in create_parameter
initializer(param, self)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 366, in __call__
stop_gradient=True)
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2888, in append_op
kwargs.get("stop_gradient", False))
File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
not stop_gradient)
OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:371)
[operator < gaussian_random > error]
main process return code: 1
not found core file

**Comment by littletomatodonkey** [comment]
aistudio上面应该是已经有现成的paddle可以用，不需要重新安装的哈

**Comment by LinXin04** [comment]
不是飞浆的AIstudio，你可以理解为我们自己的GPU环境，这报错怎么搞呢

**Comment by littletomatodonkey** [comment]
看着是cudnn 环境有问题，按照官网的教程重新安装一下吧~

**Comment by LinXin04** [comment]
![Uploading image.png…]()
是这个吗？没有办法通过pip install 安装吗

**Comment by LinXin04** [comment]
![image](https://user-images.githubusercontent.com/25193686/127423181-d6960845-9bde-46bc-be24-b7841a1281bc.png)

是这个吗？只能下载下来吗？没有办法通过pip install 安装吗？
