### ISSUE TITLE
PGNet+en_dict.txt error

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/PaddleOCR#3456]
training config as following: 
`Global:
  use_gpu: True
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/pgnet_r50_vd_totaltext_en/
  save_epoch_step: 100
  # evaluation is run every 0 iterationss after the 1000th iteration
  eval_batch_step: [ 0, 1000 ]
  cal_metric_during_train: False
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img:
  valid_set: totaltext # two mode: totaltext valid curved words, partvgg valid non-curved words
  save_res_path: ./output/pgnet_r50_vd_totaltext/predicts_pgnet.txt
  character_dict_path: ppocr/utils/en_dict.txt
  character_type: EN
  max_text_length: 500 # the max length in seq
  max_text_nums: 300 # the max seq nums in a pic
  tcl_len: 1024

Architecture:
  model_type: e2e
  algorithm: PGNet
  Transform:
  Backbone:
    name: ResNet
    layers: 50
  Neck:
    name: PGFPN
  Head:
    name: PGHead

Loss:
  name: PGLoss
  tcl_bs: 1024
  max_text_length: 500 # the same as Global: max_text_length
  max_text_nums: 300 # the same as Global：max_text_nums
  pad_num: 96 # the length of dict for pad

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: PGPostProcess
  score_thresh: 0.5
  mode: fast   # fast or slow two ways

Metric:
  name: E2EMetric
  mode: A   # two ways for eval, A: label from txt,  B: label from gt_mat
  gt_mat_dir:  ./train_data/total_text/gt  # the dir of gt_mat
  character_dict_path: ppocr/utils/ic15_dict.txt
  main_indicator: f_score_e2e

Train:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/total_text/train
    label_file_list: [./train_data/total_text/train/train.txt]
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - E2ELabelEncodeTrain:
      - PGProcessTrain:
          batch_size: 14  # same as loader: batch_size_per_card
          min_crop_size: 24
          min_text_size: 4
          max_text_size: 512
      - KeepKeys:
          keep_keys: [ 'images', 'tcl_maps', 'tcl_label_maps', 'border_maps','direction_maps', 'training_masks', 'label_list', 'pos_list', 'pos_mask' ] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: True
    batch_size_per_card: 14
    num_workers: 16

Eval:
  dataset:
    name: PGDataSet
    data_dir: ./train_data/total_text/test
    label_file_list: [./train_data/total_text/test/test.txt]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - E2ELabelEncodeTest:
      - E2EResizeForTest:
          max_side_len: 768
      - NormalizeImage:
          scale: 1./255.
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'shape', 'polys', 'texts', 'ignore_tags', 'img_id']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2`

Process Process-9:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 472, in _worker_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 463, in _worker_loop
    tensor_list = core._convert_to_tensor_list(batch)
ValueError: (InvalidArgument) Faild to convert input data to a regular ndarray.
  * Usually this means the input data contains nested lists with different lengths.
  * Check the reader function passed to 'set_(sample/sample_list/batch)_generator' to locate the data causes this issue.
  [Hint: Expected string::Sprintf("%s", array.dtype()).compare("object") != 0, but received string::Sprintf("%s", array.dtype()).compare("object"):0 == 0:0.] (at /paddle/paddle/fluid/pybind/imperative.cc:472)

ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "/ppocr/src/PaddleOCR-2.1.1/tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

**Comment by littletomatodonkey** [comment]
num worker参数改为0看下
