### ISSUE TITLE
AttributeError: 'Assign' object has no attribute 'type_comment'

### ISSUE THREAD

**Issue by grasswolfs** [PaddlePaddle/PaddleOCR#3457]
环境配置完成：cuda11.2，cudnn8.1，训练也跑起来了。

在做infer时，按inference.md文档中运行如下语句：

python3 tools/export_model.py -c configs/det/ch_ppocr_v2.0/ch_det_mv3_db_v2.0.yml -o Global.pretrained_model=./ch_lite/ch_ppocr_mobile_v2.0_det_train/best_accuracy Global.save_inference_dir=./inference/det_db/

报错如下：
W0728 15:41:11.315989 123 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 1$
.2
W0728 15:41:12.576156 123 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[2021/07/28 15:41:18] root INFO: load pretrained model from ['./ch_lite/ch_ppocr_mobile_v2.0_det_train/best_accuracy']
Traceback (most recent call last):
File "tools/export_model.py", line 95, in
main()
File "tools/export_model.py", line 90, in main
paddle.jit.save(model, save_path)
File "", line 2, in save
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
return wrapped_func(*args, **kwargs)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
return func(*args, **kwargs)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
inner_input_spec)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488,
in concrete_program_specify_input_spec
*desired_input_spec)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402,
in get_concrete_program
concrete_program, partial_program_layer = self._program_cache[cache_key]
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711,
in __getitem__
self._caches[item] = self._build_once(item)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702,
in _build_once

class_instance=cache_key.class_instance)
File "", line 2, in from_func_spec
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
return wrapped_func(*args, **kwargs)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
return func(*args, **kwargs)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 620,
in from_func_spec
static_func = convert_to_static(dygraph_function)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141,
in convert_to_static
static_func = _FUNCTION_CACHE.convert_with_cache(function)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, i
n convert_with_cache
static_func = self._convert(func)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 122,
in _convert
create_and_update_origin_info_map(root_wrapper.node, static_func)
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 163, in crea
te_and_update_origin_info_map
for t_node, s_node in ast_walk(transformed_node, static_node):
File "/home/shenchenfei/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 241, in ast_
walk
t_node_child = getattr(t_node, field)

**Comment by littletomatodonkey** [comment]
你好，用paddle2.0.2试下呢？

**Comment by cplog** [comment]
我也是這問題, 其他VERSION  都不行

**Comment by thutran292** [comment]
I installed paddle 2.0.2 version but it is ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

**Comment by weekstudy** [comment]
我也是遇到了这个问题，能训练，但是转模型的时候就报错，安装的cuda11.0,cudnn8,paddle-2.0.2,

**Comment by cjt222** [comment]
版本适配问题，paddle2.0.0是ok的

**Comment by weekstudy** [comment]
> 版本适配问题，paddle2.0.0是ok的

哦哦，谢谢，我试了，paddle2.0.0确实可以

**Comment by LuChengTHU** [comment]
同问，是否可以适配最新的2.1.1的版本？

**Comment by mucunwuxian** [comment]
我也是遇到了这个问题在`tools/export_model.py`
用下面的安装命令解决了
(on linux prompt)
```
python -m pip install paddlepaddle-gpu==2.0.0.post110 -f https://paddlepaddle.org.cn/whl/stable.html
```
↓
gast也更新了
(log)
```
Installing collected packages: gast, paddlepaddle-gpu
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Successfully uninstalled gast-0.4.0
  Attempting uninstall: paddlepaddle-gpu
    Found existing installation: paddlepaddle-gpu 2.0.1.post110
    Uninstalling paddlepaddle-gpu-2.0.1.post110:
      Successfully uninstalled paddlepaddle-gpu-2.0.1.post110
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 2.5.0 requires gast==0.4.0, but you have gast 0.3.3 which is incompatible.
Successfully installed gast-0.3.3 paddlepaddle-gpu-2.0.0.post110
```

参考：
https://github.com/PaddlePaddle/PaddleOCR/issues/3457#issuecomment-890725746
https://dongle94.github.io/paddlepaddle/paddlepaddle-ubuntu-install/
