### ISSUE TITLE
训练Det的det_mv3_db.yml

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleOCR#3520]
!python3 tools/train.py -c configs/det/det_mv3_db.yml
日志如下：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
[2021/08/03 17:13:21] root INFO: Architecture : 
[2021/08/03 17:13:21] root INFO:     Backbone : 
[2021/08/03 17:13:21] root INFO:         model_name : large
[2021/08/03 17:13:21] root INFO:         name : MobileNetV3
[2021/08/03 17:13:21] root INFO:         scale : 0.5
[2021/08/03 17:13:21] root INFO:     Head : 
[2021/08/03 17:13:21] root INFO:         k : 50
[2021/08/03 17:13:21] root INFO:         name : DBHead
[2021/08/03 17:13:21] root INFO:     Neck : 
[2021/08/03 17:13:21] root INFO:         name : DBFPN
[2021/08/03 17:13:21] root INFO:         out_channels : 256
[2021/08/03 17:13:21] root INFO:     Transform : None
[2021/08/03 17:13:21] root INFO:     algorithm : DB
[2021/08/03 17:13:21] root INFO:     model_type : det
[2021/08/03 17:13:21] root INFO: Eval : 
[2021/08/03 17:13:21] root INFO:     dataset : 
[2021/08/03 17:13:21] root INFO:         data_dir : ./train_data/
[2021/08/03 17:13:21] root INFO:         label_file_list : ['train_data/val_label.txt']
[2021/08/03 17:13:21] root INFO:         name : SimpleDataSet
[2021/08/03 17:13:21] root INFO:         transforms : 
[2021/08/03 17:13:21] root INFO:             DecodeImage : 
[2021/08/03 17:13:21] root INFO:                 channel_first : False
[2021/08/03 17:13:21] root INFO:                 img_mode : BGR
[2021/08/03 17:13:21] root INFO:             DetLabelEncode : None
[2021/08/03 17:13:21] root INFO:             DetResizeForTest : 
[2021/08/03 17:13:21] root INFO:                 image_shape : [736, 1280]
[2021/08/03 17:13:21] root INFO:             NormalizeImage : 
[2021/08/03 17:13:21] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/08/03 17:13:21] root INFO:                 order : hwc
[2021/08/03 17:13:21] root INFO:                 scale : 1./255.
[2021/08/03 17:13:21] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/08/03 17:13:21] root INFO:             ToCHWImage : None
[2021/08/03 17:13:21] root INFO:             KeepKeys : 
[2021/08/03 17:13:21] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2021/08/03 17:13:21] root INFO:     loader : 
[2021/08/03 17:13:21] root INFO:         batch_size_per_card : 1
[2021/08/03 17:13:21] root INFO:         drop_last : False
[2021/08/03 17:13:21] root INFO:         num_workers : 8
[2021/08/03 17:13:21] root INFO:         shuffle : False
[2021/08/03 17:13:21] root INFO:         use_shared_memory : False
[2021/08/03 17:13:21] root INFO: Global : 
[2021/08/03 17:13:21] root INFO:     cal_metric_during_train : False
[2021/08/03 17:13:21] root INFO:     checkpoints : None
[2021/08/03 17:13:21] root INFO:     debug : False
[2021/08/03 17:13:21] root INFO:     distributed : False
[2021/08/03 17:13:21] root INFO:     epoch_num : 125
[2021/08/03 17:13:21] root INFO:     eta : True
[2021/08/03 17:13:21] root INFO:     eval_batch_step : [0, 32]
[2021/08/03 17:13:21] root INFO:     infer_img : doc/imgs_en/img_10.jpg
[2021/08/03 17:13:21] root INFO:     log_smooth_window : 50
[2021/08/03 17:13:21] root INFO:     pretrained_model : ./pretrain_models/MobileNetV3_large_x0_5_pretrained
[2021/08/03 17:13:21] root INFO:     print_batch_step : 280
[2021/08/03 17:13:21] root INFO:     save_epoch_step : 5
[2021/08/03 17:13:21] root INFO:     save_inference_dir : None
[2021/08/03 17:13:21] root INFO:     save_model_dir : ./output/db_mv3/
[2021/08/03 17:13:21] root INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2021/08/03 17:13:21] root INFO:     use_gpu : True
[2021/08/03 17:13:21] root INFO:     use_visualdl : True
[2021/08/03 17:13:21] root INFO: Loss : 
[2021/08/03 17:13:21] root INFO:     alpha : 5
[2021/08/03 17:13:21] root INFO:     balance_loss : True
[2021/08/03 17:13:21] root INFO:     beta : 10
[2021/08/03 17:13:21] root INFO:     main_loss_type : DiceLoss
[2021/08/03 17:13:21] root INFO:     name : DBLoss
[2021/08/03 17:13:21] root INFO:     ohem_ratio : 3
[2021/08/03 17:13:21] root INFO: Metric : 
[2021/08/03 17:13:21] root INFO:     main_indicator : hmean
[2021/08/03 17:13:21] root INFO:     name : DetMetric
[2021/08/03 17:13:21] root INFO: Optimizer : 
[2021/08/03 17:13:21] root INFO:     beta1 : 0.9
[2021/08/03 17:13:21] root INFO:     beta2 : 0.999
[2021/08/03 17:13:21] root INFO:     lr : 
[2021/08/03 17:13:21] root INFO:         learning_rate : 0.001
[2021/08/03 17:13:21] root INFO:     name : Adam
[2021/08/03 17:13:21] root INFO:     regularizer : 
[2021/08/03 17:13:21] root INFO:         factor : 0
[2021/08/03 17:13:21] root INFO:         name : L2
[2021/08/03 17:13:21] root INFO: PostProcess : 
[2021/08/03 17:13:21] root INFO:     box_thresh : 0.6
[2021/08/03 17:13:21] root INFO:     max_candidates : 1000
[2021/08/03 17:13:21] root INFO:     name : DBPostProcess
[2021/08/03 17:13:21] root INFO:     thresh : 0.3
[2021/08/03 17:13:21] root INFO:     unclip_ratio : 1.5
[2021/08/03 17:13:21] root INFO: Train : 
[2021/08/03 17:13:21] root INFO:     dataset : 
[2021/08/03 17:13:21] root INFO:         data_dir : ./train_data/
[2021/08/03 17:13:21] root INFO:         label_file_list : ['./train_data/train_label.txt']
[2021/08/03 17:13:21] root INFO:         name : SimpleDataSet
[2021/08/03 17:13:21] root INFO:         ratio_list : [1.0]
[2021/08/03 17:13:21] root INFO:         transforms : 
[2021/08/03 17:13:21] root INFO:             DecodeImage : 
[2021/08/03 17:13:21] root INFO:                 channel_first : False
[2021/08/03 17:13:21] root INFO:                 img_mode : BGR
[2021/08/03 17:13:21] root INFO:             DetLabelEncode : None
[2021/08/03 17:13:21] root INFO:             IaaAugment : 
[2021/08/03 17:13:21] root INFO:                 augmenter_args : 
[2021/08/03 17:13:21] root INFO:                     args : 
[2021/08/03 17:13:21] root INFO:                         p : 0.5
[2021/08/03 17:13:21] root INFO:                     type : Fliplr
[2021/08/03 17:13:21] root INFO:                     args : 
[2021/08/03 17:13:21] root INFO:                         rotate : [-10, 10]
[2021/08/03 17:13:21] root INFO:                     type : Affine
[2021/08/03 17:13:21] root INFO:                     args : 
[2021/08/03 17:13:21] root INFO:                         size : [0.5, 3]
[2021/08/03 17:13:21] root INFO:                     type : Resize
[2021/08/03 17:13:21] root INFO:             EastRandomCropData : 
[2021/08/03 17:13:21] root INFO:                 keep_ratio : True
[2021/08/03 17:13:21] root INFO:                 max_tries : 50
[2021/08/03 17:13:21] root INFO:                 size : [640, 640]
[2021/08/03 17:13:21] root INFO:             MakeBorderMap : 
[2021/08/03 17:13:21] root INFO:                 shrink_ratio : 0.4
[2021/08/03 17:13:21] root INFO:                 thresh_max : 0.7
[2021/08/03 17:13:21] root INFO:                 thresh_min : 0.3
[2021/08/03 17:13:21] root INFO:             MakeShrinkMap : 
[2021/08/03 17:13:21] root INFO:                 min_text_size : 8
[2021/08/03 17:13:21] root INFO:                 shrink_ratio : 0.4
[2021/08/03 17:13:21] root INFO:             NormalizeImage : 
[2021/08/03 17:13:21] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/08/03 17:13:21] root INFO:                 order : hwc
[2021/08/03 17:13:21] root INFO:                 scale : 1./255.
[2021/08/03 17:13:21] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/08/03 17:13:21] root INFO:             ToCHWImage : None
[2021/08/03 17:13:21] root INFO:             KeepKeys : 
[2021/08/03 17:13:21] root INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2021/08/03 17:13:21] root INFO:     loader : 
[2021/08/03 17:13:21] root INFO:         batch_size_per_card : 16
[2021/08/03 17:13:21] root INFO:         drop_last : False
[2021/08/03 17:13:21] root INFO:         num_workers : 8
[2021/08/03 17:13:21] root INFO:         shuffle : True
[2021/08/03 17:13:21] root INFO:         use_shared_memory : False
[2021/08/03 17:13:21] root INFO: train with paddle 2.1.0 and device CUDAPlace(0)
[2021/08/03 17:13:21] root INFO: Initialize indexs of datasets:['./train_data/train_label.txt']
[2021/08/03 17:13:21] root INFO: Initialize indexs of datasets:['train_data/val_label.txt']
W0803 17:13:21.189568  1360 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1
W0803 17:13:21.194458  1360 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[2021/08/03 17:13:24] root INFO: load pretrained model from ['./pretrain_models/MobileNetV3_large_x0_5_pretrained']
[2021/08/03 17:13:24] root INFO: train dataloader has 30 iters
[2021/08/03 17:13:24] root INFO: valid dataloader has 54 iters
[2021/08/03 17:13:24] root INFO: During the training process, after the 0th iteration, an evaluation is run every 32 iterations
[2021/08/03 17:13:24] root INFO: Initialize indexs of datasets:['./train_data/train_label.txt']
[2021/08/03 17:13:57] root INFO: epoch: [1/125], iter: 29, lr: 0.001000, loss: 5.313312, loss_shrink_maps: 3.485926, loss_threshold_maps: 1.200870, loss_binary_maps: 0.653937, reader_cost: 0.05058 s, batch_cost: 0.11409 s, samples: 478, ips: 14.96254
[2021/08/03 17:13:58] root INFO: save model in ./output/db_mv3/latest
[2021/08/03 17:13:58] root INFO: Initialize indexs of datasets:['./train_data/train_label.txt']
eval model::   0%|                                       | 0/54 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 272, in train
    use_srn=use_srn)
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 360, in eval
    batch = [item.numpy() for item in batch]
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 360, in <listcomp>
    batch = [item.numpy() for item in batch]
**AttributeError: 'list' object has no attribute 'numpy'**
eval model::   0%|                                       | 0/54 [00:11<?, ?it/s]

**Comment by Wei-JL** [comment]
> 使用刚刚更新的program.py。

确实可以了，这个内存老是溢出，不是显存。我训练集差不多是480张，每次30轮的时候都是内存溢出

**Comment by MissPenguin** [comment]
> > 使用刚刚更新的program.py。
> 
> 确实可以了，这个内存老是溢出，不是显存。我训练集差不多是480张，每次30轮的时候都是内存溢出

内存泄露的问题可以参考这里最后给的解决方案：https://github.com/PaddlePaddle/PaddleOCR/issues/3297，或者等Paddle发版2.1.2就不会泄露了。

**Comment by MissPenguin** [comment]
> > 使用刚刚更新的program.py。
> 
> 确实可以了，这个内存老是溢出，不是显存。我训练集差不多是480张，每次30轮的时候都是内存溢出

内存泄露的问题可以参考这里最后给的解决方案：https://github.com/PaddlePaddle/PaddleOCR/issues/3297 ，或者等Paddle发版2.1.2就不会泄露了。

**Comment by Wei-JL** [comment]
参考了，你们更新之后。
!pip install -r /home/aistudio/work/PaddleOCR/requirements.txt

< "3.8"->pre-commit->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (0.6.0)
Requirement already satisfied: more-itertools in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->pre-commit->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (7.2.0)
Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (PEP 517) ... |

一直卡死了，不加载了

**Comment by nine-hao** [comment]
> > > 使用刚刚更新的program.py。
> > 
> > 
> > 确实可以了，这个内存老是溢出，不是显存。我训练集差不多是480张，每次30轮的时候都是内存溢出
> 
> 内存泄露的问题可以参考这里最后给的解决方案：#3297 ，或者等Paddle发版2.1.2就不会泄露了。

你好，我目前使用的是Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
paddlepaddle-gpu=2.1.3，镜像是paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7，det_limit_type=max，det_limit_side_len=960，--use_mp=True，--total_process_num=6。   在推理检测几千张图片时，内存基本没变，当推理上万张后，gpu内存会有几百M的上涨，随着图片数量增加，gpu内存会慢慢往上涨，感觉paddle释放内存有bug。

> 参考了，你们更新之后。 !pip install -r /home/aistudio/work/PaddleOCR/requirements.txt
> 
> < "3.8"->pre-commit->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (0.6.0) Requirement already satisfied: more-itertools in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->pre-commit->visualdl->-r /home/aistudio/work/PaddleOCR/requirements.txt (line 8)) (7.2.0) Building wheels for collected packages: opencv-contrib-python Building wheel for opencv-contrib-python (PEP 517) ... |
> 
> 一直卡死了，不加载了

你好，我目前使用的是Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
paddlepaddle-gpu=2.1.3，镜像是paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7，det_limit_type=max，det_limit_side_len=960，--use_mp=True，--total_process_num=6。   在推理检测几千张图片时，内存基本没变，当推理上万张后，gpu内存会有几百M的上涨，随着图片数量增加，gpu内存会慢慢往上涨，感觉paddle释放内存不及时，会有堆积。

**Comment by nine-hao** [comment]
> > > 使用刚刚更新的program.py。
> > 
> > 
> > 确实可以了，这个内存老是溢出，不是显存。我训练集差不多是480张，每次30轮的时候都是内存溢出
> 
> 内存泄露的问题可以参考这里最后给的解决方案：#3297 ，或者等Paddle发版2.1.2就不会泄露了。

2.1.3版检测不同图片，预处理resize到960*960，检测数万张之后还是会泄露。。
