### ISSUE TITLE
Dockerfile 存在一些问题

### ISSUE THREAD

**Issue by skai-zhang** [PaddlePaddle/PaddleOCR#3565]
几个月前我通过项目内提供的dockerfile构建了镜像, 可以成功运行, 但是现在不行, 构建成功但是无法运行

> TIPS: 启动命令 `CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system"]`

首先是运行 `hub install deploy/hubserving/ocr_system/`
报错 ` No module named 'paddle.utils.cpp_extension' `

我通过 #2892  了解到paddle版本有问题, 按照里面提到的方案修改了dockerfile
```dockerfile
RUN pip3.7 install paddlepaddle==2.1.0 -i https://mirror.baidu.com/pypi/simple
```

然后再次启动容器, 这次是新的错误信息
`ImportError: cannot import name 'OrderedDict' from 'typing' (/usr/local/lib/python3.7/typing.py)`

我没能找到这个错误相关的案例, 难道我是第一个碰到的? 😂

问下这个情况要如何处理呢?

**Comment by skai-zhang** [comment]
附上完整的错误信息
```shell
/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:943: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

  collections.MutableMapping.register(ParseResults)

/usr/local/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

import imp

Traceback (most recent call last):

  File "/usr/local/bin/hub", line 5, in <module>

    from paddlehub.commands.utils import execute

  File "/usr/local/lib/python3.7/site-packages/paddlehub/__init__.py", line 35, in <module>

    from paddlehub.utils.paddlex import download, ResourceNotFoundError

  File "/usr/local/lib/python3.7/site-packages/paddlehub/utils/paddlex.py", line 19, in <module>

    from paddlehub.server.server import module_server, CacheUpdater

  File "/usr/local/lib/python3.7/site-packages/paddlehub/server/__init__.py", line 17, in <module>

    from paddlehub.server.git_source import GitSource

  File "/usr/local/lib/python3.7/site-packages/paddlehub/server/git_source.py", line 27, in <module>

    import git

  File "/usr/local/lib/python3.7/site-packages/git/__init__.py", line 42, in <module>

    from git.config import GitConfigParser  # @NoMove @IgnorePep8

  File "/usr/local/lib/python3.7/site-packages/git/config.py", line 48, in <module>

    from typing import OrderedDict

ImportError: cannot import name 'OrderedDict' from 'typing' (/usr/local/lib/python3.7/typing.py)
```

**Comment by lsqtongxin** [comment]
把/usr/local/lib/python3.7/typing.py 里的内容改为 https://github.com/python/cpython/blob/3.7/Lib/typing.py  就通过了

**Comment by skai-zhang** [comment]
@lsqtongxin 👌 已经成功启动了, 谢谢😄

总结下解决方案:

在 [官方Dockerfile](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/deploy/docker/hubserving/cpu/Dockerfile) 基础上添加两行指令.

1: 将 paddlepaddle 的版本升到 2.1.0
```dockerfile
RUN pip3.7 install paddlepaddle==2.1.0 -i https://mirror.baidu.com/pypi/simple
```
2: 将 python 中的 typing.py 替换为 3.7 仓库中的版本
```dockerfile
# 下面的根据服务器网络环境二选一即可

# Github - 海外
ADD https://raw.githubusercontent.com/python/cpython/3.7/Lib/typing.py /usr/local/lib/python3.7
# Gitee - 国内
ADD https://gitee.com/mirrors/cpython/raw/3.7/Lib/typing.py /usr/local/lib/python3.7
```

**Comment by bswhb** [comment]
@skai-zhang 用最新commit的dockerfile还是遇到你上述的问题（版本2.1.2，typing.py文件尝试了海外和国内两种方式），错误日志如下：
`ImportError: cannot import name 'OrderedDict' from 'typing' (/usr/local/python3.7.0/lib/python3.7/typing.py)`

现在container起不来也看不到具体typing.py的内容，有什么办法可以先启动container，再查看文件么？

**Comment by skai-zhang** [comment]
@bswhb 不清楚, 模块都安不上, 估摸着应该是没法启动的. 

另外附上我项目中的dockerfile, 这几天自动构建出来的镜像都是正常的

```dockerfile
# Version: 2.0.0
FROM registry.baidubce.com/paddlepaddle/paddle:2.1.2

RUN pip3.7 install --upgrade pip -i https://mirror.baidu.com/pypi/simple && pip3.7 install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple

RUN git clone https://gitee.com/PaddlePaddle/PaddleOCR.git /PaddleOCR

ADD https://gitee.com/mirrors/cpython/raw/3.7/Lib/typing.py /usr/local/python3.7.0/lib/python3.7

WORKDIR /PaddleOCR

RUN pip3.7 install -r requirements.txt -i https://mirror.baidu.com/pypi/simple && mkdir -p /PaddleOCR/inference/

ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar /PaddleOCR/inference/

RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_det_infer.tar -C /PaddleOCR/inference/ && tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer.tar -C /PaddleOCR/inference/ && tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_rec_infer.tar -C /PaddleOCR/inference/ 

EXPOSE 9890

CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system -p 9890"]
```

**Comment by bswhb** [comment]
问题找到了，repo里面的路径错了(/usr/local/python3.7.0/...)，看来还得麻烦你再开一个pr了：
`ADD https://raw.githubusercontent.com/python/cpython/3.7/Lib/typing.py /usr/local/lib/python3.7`

**Comment by skai-zhang** [comment]
@bswhb  抱歉 🤦‍♂️  python的安装目录发生变化了, 这个我没有pr上去, 仅仅只是复制了3楼的回答. 稍后我修改一下重新提交

**Comment by bswhb** [comment]
好的，谢谢啦，另外发现一个问题，缺省打开的端口似乎是8866，而不是8868，建议像你一样再Dockerfile用-p 8868指定一下吧

**Comment by foxundermoon** [comment]
```

hub install deploy/hubserving/ocr_system/ 
Traceback (most recent call last):
  File "/usr/local/python3.7.0/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/__init__.py", line 35, in <module>
    from paddlehub.utils.paddlex import download, ResourceNotFoundError
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/utils/paddlex.py", line 19, in <module>
    from paddlehub.server.server import module_server, CacheUpdater
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/server/__init__.py", line 17, in <module>
    from paddlehub.server.git_source import GitSource
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/server/git_source.py", line 27, in <module>
    import git
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/git/__init__.py", line 42, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/git/config.py", line 48, in <module>
    from typing import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing' (/usr/local/python3.7.0/lib/python3.7/typing.py)
```
新错误，目录有点差异

**Comment by skai-zhang** [comment]
🤔  @foxundermoon 这个目录和dockerfile中的一致啊, 你看下你用的是不是这个版本的 [修复错误 #3614](https://github.com/PaddlePaddle/PaddleOCR/pull/3614/commits/5e1e12474adb5ce16e9125964a29148845615199)
