### ISSUE TITLE
PP-Structure:跟着教程出现 OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by yazheng0307** [PaddlePaddle/PaddleOCR#3580]
用的是AI Studio编辑器，按照教程一步一步来做的，运行 paddleocr --image_dir=../doc/table/1.png --type=structure 后报以下错误：

`Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 355, in main
    engine = PPStructure(**(args.__dict__))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 316, in __init__
    super().__init__(params)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleocr/ppstructure/predict_system.py", line 45, in __init__
    self.text_system = TextSystem(args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 45, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleocr/tools/infer/predict_det.py", line 99, in __init__
    args, 'det', logger)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleocr/tools/infer/utility.py", line 249, in create_predictor
    predictor = inference.create_predictor(config)
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:99)`

请问是为什么呢？

**Comment by littletomatodonkey** [comment]
你好，在aistudio里面已经预装了paddle，这里不需要重新安装paddlepaddle，另外，建议用python3.7进行开发
