### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called

### ISSUE THREAD

**Issue by shubhambaid** [PaddlePaddle/PaddleOCR#3589]
**While simply running the PaddleOCR model for detection and recognition, I am coming up to this issue
and weirdly this is not the same with my other laptop.**

2021-08-06 11:30:16,251] ERROR in app: Exception on /read [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/DS/alpr-service/alprservice.py", line 29, in McQueen
    result_data, pre_reg_data = inference_object.find_numbers(image_list)
  File "/app/DS/alpr-service/alprservice.py", line 83, in find_numbers
    text_detection = self.ocr_model.ocr(superres_img, cls=True)
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/paddleocr.py", line 385, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/tools/infer/predict_system.py", line 90, in _call_
    dt_boxes, elapse = self.text_detector(img)
  File "/usr/local/lib/python3.8/dist-packages/paddleocr/tools/infer/predict_det.py", line 173, in _call_
    output = output_tensor.copy_to_cpu()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:202)

**Comment by falsebird** [comment]
I have encountered the same problem. Have you solved this problem?

**Comment by shubhambaid** [comment]
yes @falsebird , I actually figured out that I was invoking the function for inference multiple times for the same loaded model. Hence, it was throwing this error.
