### ISSUE TITLE
something wrong when using the inference model of pgnet

### ISSUE THREAD

**Issue by yulin1998** [PaddlePaddle/PaddleOCR#3597]
```
Traceback (most recent call last):
  File "/Users/Downloads/Paddle/PaddleOCR/tools/infer/predict_e2e.py", line 134, in <module>
    text_detector = TextE2E(args)
  File "/Users/Downloads/Paddle/PaddleOCR/tools/infer/predict_e2e.py", line 77, in __init__
    self.predictor, self.input_tensor, self.output_tensors = utility.create_predictor(
ValueError: too many values to unpack (expected 3)
```

**Comment by MissPenguin** [comment]
可以贴一下完整的预测命令吗

**Comment by ujjawalcse** [comment]
Hi @yulin1998 ,
This error is in the updated code of `utility.py`.
As updated code is returning 4 values from `create_predictor()`, just remove the 4th value returned from the function
like this `return predictor, input_tensor, output_tensors`  or 
assign the 4th value to a variable where it's called.

Cheers.
