### ISSUE TITLE
自己更换主干网络后报错

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3609]
Traceback (most recent call last):
  File "tools/eval.py", line 82, in <module>
    main()
  File "tools/eval.py", line 56, in main
    model = build_model(config['Architecture'])
  File "C:\Users\H1CE\Desktop\PaddleOCR-release-2.2\ppocr\modeling\architectures\__init__.py", line 27, in build_model
    arch = BaseModel(config)
  File "C:\Users\H1CE\Desktop\PaddleOCR-release-2.2\ppocr\modeling\architectures\base_model.py", line 51, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "C:\Users\H1CE\Desktop\PaddleOCR-release-2.2\ppocr\modeling\backbones\__init__.py", line 47, in build_backbone
    module_class = eval(module_name)(**config)
TypeError: __init__() got an unexpected keyword argument 'model_name'

**Comment by hice1207** [comment]
另外想问问ocr部分没有使用ghostnet吗，这部分的代码是从paddleclas中复制过来修改的。

**Comment by LDOUBLEV** [comment]
修改backbone后，需要契合现在的代码结构，
可以参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.2/doc/doc_ch/add_new_algorithm.md#%E7%BD%91%E7%BB%9C
