### ISSUE TITLE
更换主干网络后报错

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleOCR#3623]
Traceback (most recent call last):
File "tools/eval.py", line 82, in
main()
File "tools/eval.py", line 56, in main
model = build_model(config['Architecture'])
File "C:\Users\H1CE\Desktop\PaddleOCR-release-2.2\ppocr\modeling\architectures_init_.py", line 27, in build_model
arch = BaseModel(config)
File "C:\Users\H1CE\Desktop\PaddleOCR-release-2.2\ppocr\modeling\architectures\base_model.py", line 51, in init
self.backbone = build_backbone(config["Backbone"], model_type)
File "C:\Users\H1CE\Desktop\PaddleOCR-release-2.2\ppocr\modeling\backbones_init_.py", line 47, in build_backbone
module_class = eval(module_name)(**config)
TypeError: init() got an unexpected keyword argument 'model_name'

**Comment by tink2123** [comment]
你是怎么更换的呢？backbone_init_.py 是您自己创建的吗？建议参考文档说明：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_ch/add_new_algorithm.md

**Comment by hice1207** [comment]
> 你是怎么更换的呢？backbone_init_.py 是您自己创建的吗？建议参考文档说明：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_ch/add_new_algorithm.md

您好我就是参照文档换的，用的paddleclas的ghostnet代码做了修改

**Comment by tink2123** [comment]
不需要新增一个 backbones_init_.py 文件，只需要在 https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/ppocr/modeling/backbones/__init__.py#L24 这里新增你的backbone就可以

**Comment by hice1207** [comment]
> 不需要新增一个 backbones_init_.py 文件，只需要在
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/292f03b35dd15891fd4de31a2fefa5e39495a7d4/ppocr/modeling/backbones/__init__.py#L24-L31
> 
> 这里新增你的backbone就可以

您好我就是在这里添加的，我借用的paddleclas中的ghostnet
