### ISSUE TITLE
MKL报错

### ISSUE THREAD

**Issue by tan5jun2yi0** [PaddlePaddle/PaddleOCR#3644]
你好，请问我在按照教程安装2.1.2版本后测试时报错“ Load symbol MKL_Free_Buffers failed.”和“RuntimeError: MKL_Free_Buffers not found.”这个是为什么呢？已经在INTEL和AMD两种不同CPU电脑上测试，结果是一样的。

**Comment by WenmuZhou** [comment]
看看机器上有没有安装mkldnn，并且你的paddle编译的时候有没有开启mkldnn选项

**Comment by tan5jun2yi0** [comment]
> 看看机器上有没有安装mkldnn，并且你的paddle编译的时候有没有开启mkldnn选项

回大佬，MKLDNN是安装了的。并且所使用的测试代码是PADDLE的源代码，里面MKLDNN默认是开启的。
Traceback (most recent call last):
  File "E:\TJY\Paddle\PaddleOCR\tools\infer\predict_system.py", line 193, in <module>
    main(args)
  File "E:\TJY\Paddle\PaddleOCR\tools\infer\predict_system.py", line 126, in main
    res = text_sys(img)
  File "E:\TJY\Paddle\PaddleOCR\tools\infer\predict_system.py", line 60, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "E:\TJY\Paddle\PaddleOCR\tools\infer\predict_det.py", line 193, in __call__
    self.predictor.run()
RuntimeError: MKL_Free_Buffers not found.

**Comment by HaHaZero** [comment]
你好，你解决了？我也遇到了同样的问题

**Comment by tan5jun2yi0** [comment]
> 你好，你解决了？我也遇到了同样的问题

并没有解决~~害~~同样配置的电脑，参考同样的流程，我同事照着做就成功了~但在我测试过的另外两台电脑就是成功不了。
