### ISSUE TITLE
Paddle webserving error : mportError: cannot import name 'MultiLangClient' from 'paddle_serving_client' 

### ISSUE THREAD

**Issue by rsingh2083** [PaddlePaddle/PaddleOCR#3683]
`python3 web_service.py `
Im getting this error :-
```
Traceback (most recent call last):
  File "web_service.py", line 14, in <module>
    from paddle_serving_server.web_service import WebService, Op
  File "/home/rag/miniconda37/lib/python3.7/site-packages/paddle_serving_server/web_service.py", line 27, in <module>
    from paddle_serving_server import pipeline
  File "/home/rag/miniconda37/lib/python3.7/site-packages/paddle_serving_server/pipeline/__init__.py", line 15, in <module>
    from .operator import Op, RequestOp, ResponseOp
  File "/home/rag/miniconda37/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 19, in <module>
    from paddle_serving_client import MultiLangClient, Client
ImportError: cannot import name 'MultiLangClient' from 'paddle_serving_client' (/home/rag/miniconda37/lib/python3.7/site-packages/paddle_serving_client/__init__.py)

```

I dont have any module or file named MultiLangClient in my entire system 
`find / | grep -i "MultiLangClient"  `

**Comment by tink2123** [comment]
这里需要更新一下 paddle_serving_client 版本，可以尝试  python3.7 -m pip install paddle_serving_client==0.6.1
