### ISSUE TITLE
在预测时我调整表格版面分析table_max_len参数时报这个错，请问是什么这是什么原因，如何修改

### ISSUE THREAD

**Issue by 965662766** [PaddlePaddle/PaddleOCR#3685]
![2aed998cd4e6d877249089a99da24c4](https://user-images.githubusercontent.com/85744622/129502105-179139f5-96ec-42b6-a103-e57c8c6f487f.png)

Traceback (most recent call last):
  File "D:\WordInstaller\Anaconda3\envs\PaddleOCR\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\WordInstaller\Anaconda3\envs\PaddleOCR\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\WordInstaller\Anaconda3\envs\PaddleOCR\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\WordInstaller\Anaconda3\envs\PaddleOCR\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\WordInstaller\Anaconda3\envs\PaddleOCR\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\WordInstaller\Anaconda3\envs\PaddleOCR\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/Project/simple/PaddleOCR/ppstructure/table/predict_table2.py", line 234, in hello_world
    return predict_table.predict(image_path)
  File "E:/Project/simple/PaddleOCR/ppstructure/table/predict_table2.py", line 203, in predict
    pred_html = self.text_sys(img)
  File "E:/Project/simple/PaddleOCR/ppstructure/table/predict_table2.py", line 63, in __call__
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "E:\Project\simple\PaddleOCR\ppstructure\table\predict_structure.py", line 82, in __call__
    self.predictor.run()
ValueError: In user code:
    File "tools/export_model.py", line 97, in <module>
      main()
    File "tools/export_model.py", line 92, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-67>", line 2, in save
      
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
      inner_input_spec)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/var/folders/p1/k22nll251j929kk0z1xv80cc0000gp/T/tmpwwegsj2y.py", line 32, in forward
      false_fn_2, (x,), (data, x), (x,))
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/zhoujun20/Desktop/工作相关/table/table_pr/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 78, in forward
      x = self.head(x)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/var/folders/p1/k22nll251j929kk0z1xv80cc0000gp/T/tmp_7nnpqb2.py", line 22, in forward
      (fea, inputs), (fea,))
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 208, in convert_ifelse
      return_vars)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 231, in _run_paddle_cond
      lambda: false_fn(*false_args))
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 2431, in cond
      origin_false_output = false_fn()
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 231, in <lambda>
      lambda: false_fn(*false_args))
    File "/Users/zhoujun20/Desktop/工作相关/table/table_pr/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 68, in forward
      fea = paddle.reshape(fea, [fea.shape[0], fea.shape[1], last_shape])
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 1570, in reshape
      return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6207, in reshape
      "XShape": x_shape})
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "/Users/zhoujun20/anaconda3/envs/Paddle2.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():
    InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 960, 30, 30], X's size = 864000, 'shape' is [1, 960, 256], the capacity of 'shape' is 245760.
      [Hint: Expected capacity == in_size, but received capacity:245760 != in_size:864000.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/reshape_op.cc:222)
      [operator < reshape2 > error]
127.0.0.1 - - [16/Aug/2021 09:57:13] "GET / HTTP/1.1" 500 -

**Comment by WenmuZhou** [comment]
不建议在预测时修改这个数字，因为head里有部分代码和输入尺寸有关

**Comment by moyueheng** [comment]
这个如果一定要修改，有什么方式吗
比如重新训练
