### ISSUE TITLE
IndexError: index 113 is out of bounds for axis 0 with size 113

### ISSUE THREAD

**Issue by mzn32qwq** [PaddlePaddle/PaddleOCR#3701]
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 193, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 141, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 80, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/tang/PaddleOCR-release-2.2/tools/infer/predict_rec.py", line 263, in __call__
    rec_res[indices[beg_img_no + rno-1]] = rec_result[rno]

command: python3 tools/infer/predict_system.py --image_dir="/home/st/Downloads/case.jpg" --det_model_dir="/home/st/inference/ch_det_mv3_db" --rec_model_dir="/home/st/inference/ch_rec_mv3_crnn"

**Comment by mzn32qwq** [comment]
Meantime, i changed 115,116 lines in rec_postprocess.py.
Here is code after changed:
        preds_idx = preds.argmax(axis=1)
        preds_prob = preds.max(axis=1)

**Comment by WenmuZhou** [comment]
Send me the test image

**Comment by mzn32qwq** [comment]
it's just a table image.

> Send me the test image
