### ISSUE TITLE
你好，请问下，目前表格识别只有MobileNetV3网络模型，近期会出其它网络模型的吗？我需要识别分辨率比较高的图片，训练自定义标注的图片，比较急

### ISSUE THREAD

**Issue by 965662766** [PaddlePaddle/PaddleOCR#3706]

**Comment by MissPenguin** [comment]
暂时不计划发布其他backbone的模型哈，有需要可以自己替换一下重新训练，复用检测的backbone即可，例如替换为det_resnet50_vd。数据格式和pubtabnet对齐，应该能很方便启动训练。

**Comment by 965662766** [comment]
你好，配置文件上和源代码我不知道怎么改，我也调试过，理解比较困难，可以补这个吗，比如你说的det_resnet50_vd

**Comment by MissPenguin** [comment]
backbone在这里：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppocr/modeling/backbones/det_resnet_vd.py ，在配置文件里面配一下参数：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/configs/table/table_mv3.yml#L41 ，可以对照检测里面的写法：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/configs/det/det_r50_vd_db.yml#L22

**Comment by 965662766** [comment]
好的，我先试下，非常感谢！

**Comment by 965662766** [comment]
你好，我按你这说的方式去配置训练报错了，我查下资料说是显存原因，但我更改batch_size不生效，GPU是1080Ti 11G
其中：

这个文件没有更改：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppocr/modeling/backbones/det_resnet_vd.py 
这个文件有更改 在49行 256改成1024：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppocr/modeling/heads/table_att_head.py#49 
配置信息如下：
Global:
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/table_r50/
  save_epoch_step: 5
  # evaluation is run every 400 iterations after the 0th iteration
  eval_batch_step: [0, 400]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ppocr/utils/dict/table_structure_dict.txt
  character_type: en
  max_text_length: 100
  max_elem_length: 500
  max_cell_num: 500
  infer_mode: False
  process_total_num: 0
  process_cut_num: 0


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.0001
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: table
  algorithm: TableAttn
  Backbone:
    name: ResNet
    layers: 50
  Head:
    name: TableAttentionHead
    hidden_size: 256
    l2_decay: 0.00001
    loc_type: 2

Loss:
  name: TableAttentionLoss
  structure_weight: 100.0
  loc_weight: 10000.0

PostProcess:
  name: TableLabelDecode

Metric:
  name: TableMetric
  main_indicator: acc

Train:
  dataset:
    name: PubTabDataSet
    data_dir: /data2/project/dataset/pubtabnet/train/
    label_file_path: /data2/project/dataset/pubtabnet/PubTabNet_train_2.0.0.jsonl
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ResizeTableImage:
          max_len: 1024
      - TableLabelEncode:
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
  loader:
    shuffle: True
    batch_size_per_card: 1
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: /data2/project/dataset/pubtabnet/val/
    label_file_path: /data2/project/dataset/pubtabnet/PubTabNet_val_min_2.0.0.jsonl
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ResizeTableImage:
          max_len: 1024
      - TableLabelEncode:
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 1

**Comment by 965662766** [comment]
以下补上报错信息：
![image](https://user-images.githubusercontent.com/85744622/129700312-a70ed400-76aa-4e79-b492-4954812dcfac.png)
python tools/train.py -c configs/table/table_r50_vd_db.yml
/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
[2021/08/17 16:54:11] root INFO: Architecture : 
[2021/08/17 16:54:11] root INFO:     Backbone : 
[2021/08/17 16:54:11] root INFO:         layers : 50
[2021/08/17 16:54:11] root INFO:         name : ResNet
[2021/08/17 16:54:11] root INFO:     Head : 
[2021/08/17 16:54:11] root INFO:         hidden_size : 256
[2021/08/17 16:54:11] root INFO:         l2_decay : 1e-05
[2021/08/17 16:54:11] root INFO:         loc_type : 2
[2021/08/17 16:54:11] root INFO:         name : TableAttentionHead
[2021/08/17 16:54:11] root INFO:     algorithm : TableAttn
[2021/08/17 16:54:11] root INFO:     model_type : table
[2021/08/17 16:54:11] root INFO: Eval : 
[2021/08/17 16:54:11] root INFO:     dataset : 
[2021/08/17 16:54:11] root INFO:         data_dir : /data2/project/dataset/pubtabnet/val/
[2021/08/17 16:54:11] root INFO:         label_file_path : /data2/project/dataset/pubtabnet/PubTabNet_val_min_2.0.0.jsonl
[2021/08/17 16:54:11] root INFO:         name : PubTabDataSet
[2021/08/17 16:54:11] root INFO:         transforms : 
[2021/08/17 16:54:11] root INFO:             DecodeImage : 
[2021/08/17 16:54:11] root INFO:                 channel_first : False
[2021/08/17 16:54:11] root INFO:                 img_mode : BGR
[2021/08/17 16:54:11] root INFO:             ResizeTableImage : 
[2021/08/17 16:54:11] root INFO:                 max_len : 1024
[2021/08/17 16:54:11] root INFO:             TableLabelEncode : None
[2021/08/17 16:54:11] root INFO:             NormalizeImage : 
[2021/08/17 16:54:11] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/08/17 16:54:11] root INFO:                 order : hwc
[2021/08/17 16:54:11] root INFO:                 scale : 1./255.
[2021/08/17 16:54:11] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/08/17 16:54:11] root INFO:             PaddingTableImage : None
[2021/08/17 16:54:11] root INFO:             ToCHWImage : None
[2021/08/17 16:54:11] root INFO:             KeepKeys : 
[2021/08/17 16:54:11] root INFO:                 keep_keys : ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
[2021/08/17 16:54:11] root INFO:     loader : 
[2021/08/17 16:54:11] root INFO:         batch_size_per_card : 1
[2021/08/17 16:54:11] root INFO:         drop_last : False
[2021/08/17 16:54:11] root INFO:         num_workers : 1
[2021/08/17 16:54:11] root INFO:         shuffle : False
[2021/08/17 16:54:11] root INFO: Global : 
[2021/08/17 16:54:11] root INFO:     cal_metric_during_train : True
[2021/08/17 16:54:11] root INFO:     character_dict_path : ppocr/utils/dict/table_structure_dict.txt
[2021/08/17 16:54:11] root INFO:     character_type : en
[2021/08/17 16:54:11] root INFO:     checkpoints : None
[2021/08/17 16:54:11] root INFO:     debug : False
[2021/08/17 16:54:11] root INFO:     distributed : False
[2021/08/17 16:54:11] root INFO:     epoch_num : 50
[2021/08/17 16:54:11] root INFO:     eval_batch_step : [0, 400]
[2021/08/17 16:54:11] root INFO:     infer_img : doc/imgs_words/ch/word_1.jpg
[2021/08/17 16:54:11] root INFO:     infer_mode : False
[2021/08/17 16:54:11] root INFO:     log_smooth_window : 20
[2021/08/17 16:54:11] root INFO:     max_cell_num : 500
[2021/08/17 16:54:11] root INFO:     max_elem_length : 500
[2021/08/17 16:54:11] root INFO:     max_text_length : 100
[2021/08/17 16:54:11] root INFO:     pretrained_model : None
[2021/08/17 16:54:11] root INFO:     print_batch_step : 5
[2021/08/17 16:54:11] root INFO:     process_cut_num : 0
[2021/08/17 16:54:11] root INFO:     process_total_num : 0
[2021/08/17 16:54:11] root INFO:     save_epoch_step : 5
[2021/08/17 16:54:11] root INFO:     save_inference_dir : None
[2021/08/17 16:54:11] root INFO:     save_model_dir : ./output/table_r50/
[2021/08/17 16:54:11] root INFO:     use_gpu : True
[2021/08/17 16:54:11] root INFO:     use_visualdl : False
[2021/08/17 16:54:11] root INFO: Loss : 
[2021/08/17 16:54:11] root INFO:     loc_weight : 10000.0
[2021/08/17 16:54:11] root INFO:     name : TableAttentionLoss
[2021/08/17 16:54:11] root INFO:     structure_weight : 100.0
[2021/08/17 16:54:11] root INFO: Metric : 
[2021/08/17 16:54:11] root INFO:     main_indicator : acc
[2021/08/17 16:54:11] root INFO:     name : TableMetric
[2021/08/17 16:54:11] root INFO: Optimizer : 
[2021/08/17 16:54:11] root INFO:     beta1 : 0.9
[2021/08/17 16:54:11] root INFO:     beta2 : 0.999
[2021/08/17 16:54:11] root INFO:     clip_norm : 5.0
[2021/08/17 16:54:11] root INFO:     lr : 
[2021/08/17 16:54:11] root INFO:         learning_rate : 0.0001
[2021/08/17 16:54:11] root INFO:     name : Adam
[2021/08/17 16:54:11] root INFO:     regularizer : 
[2021/08/17 16:54:11] root INFO:         factor : 0.0
[2021/08/17 16:54:11] root INFO:         name : L2
[2021/08/17 16:54:11] root INFO: PostProcess : 
[2021/08/17 16:54:11] root INFO:     name : TableLabelDecode
[2021/08/17 16:54:11] root INFO: Train : 
[2021/08/17 16:54:11] root INFO:     dataset : 
[2021/08/17 16:54:11] root INFO:         data_dir : /data2/project/dataset/pubtabnet/train/
[2021/08/17 16:54:11] root INFO:         label_file_path : /data2/project/dataset/pubtabnet/PubTabNet_train_2.0.0.jsonl
[2021/08/17 16:54:11] root INFO:         name : PubTabDataSet
[2021/08/17 16:54:11] root INFO:         transforms : 
[2021/08/17 16:54:11] root INFO:             DecodeImage : 
[2021/08/17 16:54:11] root INFO:                 channel_first : False
[2021/08/17 16:54:11] root INFO:                 img_mode : BGR
[2021/08/17 16:54:11] root INFO:             ResizeTableImage : 
[2021/08/17 16:54:11] root INFO:                 max_len : 1024
[2021/08/17 16:54:11] root INFO:             TableLabelEncode : None
[2021/08/17 16:54:11] root INFO:             NormalizeImage : 
[2021/08/17 16:54:11] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/08/17 16:54:11] root INFO:                 order : hwc
[2021/08/17 16:54:11] root INFO:                 scale : 1./255.
[2021/08/17 16:54:11] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/08/17 16:54:11] root INFO:             PaddingTableImage : None
[2021/08/17 16:54:11] root INFO:             ToCHWImage : None
[2021/08/17 16:54:11] root INFO:             KeepKeys : 
[2021/08/17 16:54:11] root INFO:                 keep_keys : ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
[2021/08/17 16:54:11] root INFO:     loader : 
[2021/08/17 16:54:11] root INFO:         batch_size_per_card : 1
[2021/08/17 16:54:11] root INFO:         drop_last : True
[2021/08/17 16:54:11] root INFO:         num_workers : 1
[2021/08/17 16:54:11] root INFO:         shuffle : True
[2021/08/17 16:54:11] root INFO: train with paddle 2.1.2 and device CUDAPlace(0)
[2021/08/17 16:54:11] root INFO: Initialize indexs of datasets:/data2/project/dataset/pubtabnet/PubTabNet_train_2.0.0.jsonl
[2021/08/17 16:54:17] root INFO: Initialize indexs of datasets:/data2/project/dataset/pubtabnet/PubTabNet_val_min_2.0.0.jsonl
W0817 16:54:17.534898  8379 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0817 16:54:17.541751  8379 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 83, in main
    model = build_model(config['Architecture'])
  File "/data2/project/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 27, in build_model
    arch = BaseModel(config)
  File "/data2/project/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 51, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/data2/project/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 46, in build_backbone
    module_class = eval(module_name)(**config)
  File "/data2/project/PaddleOCR/ppocr/modeling/backbones/table_resnet_vd.py", line 205, in __init__
    name="conv1_1")
  File "/data2/project/PaddleOCR/ppocr/modeling/backbones/table_resnet_vd.py", line 51, in __init__
    bias_attr=False)
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
    default_initializer)
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 366, in __call__
    stop_gradient=True)
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2925, in append_op
    kwargs.get("stop_gradient", False))
  File "/root/miniconda3/envs/PaddleOCR/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  (at /paddle/paddle/fluid/platform/device_context.h:371)
  [operator < gaussian_random > error]
