### ISSUE TITLE
!paddleocr --image_dir=/mnt/c/Users/Betterme/Desktop/1048.jpg --type=structure

### ISSUE THREAD

**Issue by Jie-Yuan** [PaddlePaddle/PaddleOCR#3774]
--- Running analysis [ir_graph_to_program_pass]
I0823 14:52:24.694540  9100 analysis_predictor.cc:636] ======= optimize end =======
I0823 14:52:24.700675  9100 naive_executor.cc:98] ---  skip [feed], feed -> x
I0823 14:52:24.705000  9100 naive_executor.cc:98] ---  skip [batch_norm_4.tmp_3], fetch -> fetch
I0823 14:52:24.705044  9100 naive_executor.cc:98] ---  skip [conv2d_66.tmp_0], fetch -> fetch
Traceback (most recent call last):
  File "/home/yuanjie/.local/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/home/yuanjie/.local/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 355, in main
    engine = PPStructure(**(args.__dict__))
  File "/home/yuanjie/.local/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 316, in __init__
    super().__init__(params)
  File "/home/yuanjie/.local/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 54, in __init__
    self.table_layout = lp.PaddleDetectionLayoutModel(config_path=config_path,
AttributeError: module 'layoutparser' has no attribute 'PaddleDetectionLayoutModel'
​

**Comment by MissPenguin** [comment]
您好，我这边没有复现您这个问题，可以检查下layoutparser和paddleocr的安装流程是否有问题，参考[文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/ppstructure/README_ch.md#2-%E5%AE%89%E8%A3%85)
