### ISSUE TITLE
RECURSION ERROR WHILE TRAINING ICDAR2015 DATASET

### ISSUE THREAD

**Issue by karndeepsingh** [PaddlePaddle/PaddleOCR#3836]
Please help to solve the error while training the model on ICDAR2015 DATASET.

[2021/08/27 12:35:20] root ERROR: When parsing line word_3055.png, "Shop"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_3868.png, "OUND"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_3895.png, "DIAGNOSIS"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1077.png, "lives.\""
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1712.png, "Back"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_3317.png, "TOPSHOP"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_2025.png, "SAN"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_2027.png, "NEW"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_4103.png, "02-25"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_4166.png, "CHICKEN"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_717.png, "TUCKSHOP"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1163.png, "X-ING"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1006.png, "ULTIMATE"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_4031.png, "FILIPIN"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1946.png, "ARRIVAL"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1226.png, "Ayer"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_170.png, "Shop"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_3794.png, "MANGO"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1150.png, "19 99"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_226.png, "Ghaut"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_787.png, "outside"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1825.png, "FICTION"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_2325.png, "Green"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_4193.png, "Higest"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_3183.png, "Doc"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1270.png, "ICED"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_781.png, "FOREIGNERS"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_3369.png, "ALDO"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_697.png, "Japan"
, error happened with msg: list index out of range
[2021/08/27 12:35:20] root ERROR: When parsing line word_1983.png, "TOPSHOP"
, error happened with msg: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RecursionError: maximum recursion depth exceeded while pickling an object
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RecursionError: maximum recursion depth exceeded while pickling an object

**Comment by littletomatodonkey** [comment]
一行中，路径和标注需要用\t隔开，你这看着用的,

```
When parsing line word_781.png, "FOREIGNERS"
```

**Comment by chaosjeyli** [comment]
> 一行中，路径和标注需要用\t隔开，你这看着用的,
> 
> ```
> When parsing line word_781.png, "FOREIGNERS"
> ```

老哥能帮忙看下我的吗，用的中文文档数据集，标签应该没问题，但也是这个报错：

[2021/09/04 22:34:29] root ERROR: When parsing line img_0203488.jpg 带着弟弟去国外谋生，每月寄回一
, error happened with msg: list index out of range
[2021/09/04 22:34:29] root ERROR: When parsing line img_0871008.jpg 受启发，他向贾梅求援
, error happened with msg: list index out of range
[2021/09/04 22:34:29] root ERROR: When parsing line img_0321288.jpg 说："请坐吧！
, error happened with msg: list index out of range
[2021/09/04 22:34:29] root ERROR: When parsing line img_0578547.jpg 四、家庭轶事
, error happened with msg: list index out of range
[2021/09/04 22:34:29] root ERROR: When parsing line img_0780583.jpg 一下钢笔字学习
, error happened with msg: list index out of range
[2021/09/04 22:34:29] root ERROR: When parsing line img_0413555.jpg 十
, error happened with msg: list index out of range

**Comment by karndeepsingh** [comment]
Its

> > 一行中，路径和标注需要用\t隔开，你这看着用的,
> > ```
> > When parsing line word_781.png, "FOREIGNERS"
> > ```
> 
> 老哥能帮忙看下我的吗，用的中文文档数据集，标签应该没问题，但也是这个报错：
> 
> [2021/09/04 22:34:29] root ERROR: When parsing line img_0203488.jpg 带着弟弟去国外谋生，每月寄回一
> , error happened with msg: list index out of range
> [2021/09/04 22:34:29] root ERROR: When parsing line img_0871008.jpg 受启发，他向贾梅求援
> , error happened with msg: list index out of range
> [2021/09/04 22:34:29] root ERROR: When parsing line img_0321288.jpg 说："请坐吧！
> , error happened with msg: list index out of range
> [2021/09/04 22:34:29] root ERROR: When parsing line img_0578547.jpg 四、家庭轶事
> , error happened with msg: list index out of range
> [2021/09/04 22:34:29] root ERROR: When parsing line img_0780583.jpg 一下钢笔字学习
> , error happened with msg: list index out of range
> [2021/09/04 22:34:29] root ERROR: When parsing line img_0413555.jpg 十
> , error happened with msg: list index out of range

Its a problem of path you are mentioning in yaml file. Maintain the Train and Test directory as per tutorial. You will get running.

**Comment by chaosjeyli** [comment]
> Its
> 
> > > 一行中，路径和标注需要用\t隔开，你这看着用的,
> > > ```
> > > When parsing line word_781.png, "FOREIGNERS"
> > > ```
> > 
> > 
> > 老哥能帮忙看下我的吗，用的中文文档数据集，标签应该没问题，但也是这个报错：
> > [2021/09/04 22:34:29] root ERROR: When parsing line img_0203488.jpg 带着弟弟去国外谋生，每月寄回一
> > , error happened with msg: list index out of range
> > [2021/09/04 22:34:29] root ERROR: When parsing line img_0871008.jpg 受启发，他向贾梅求援
> > , error happened with msg: list index out of range
> > [2021/09/04 22:34:29] root ERROR: When parsing line img_0321288.jpg 说："请坐吧！
> > , error happened with msg: list index out of range
> > [2021/09/04 22:34:29] root ERROR: When parsing line img_0578547.jpg 四、家庭轶事
> > , error happened with msg: list index out of range
> > [2021/09/04 22:34:29] root ERROR: When parsing line img_0780583.jpg 一下钢笔字学习
> > , error happened with msg: list index out of range
> > [2021/09/04 22:34:29] root ERROR: When parsing line img_0413555.jpg 十
> > , error happened with msg: list index out of range
> 
> Its a problem of path you are mentioning in yaml file. Maintain the Train and Test directory as per tutorial. You will get running.

its not bro, I mentioned the other dataset in the same way, but it worked. Only this dataset finds this problem.
