### ISSUE TITLE
我下载了预训练的模型，但是报错2020-07-20 20:30:50,695-INFO: not find model file path “./inference/det_r50_vd_db/“/model

### ISSUE THREAD

**Issue by Jack-wx** [PaddlePaddle/PaddleOCR#388]
[root@kaifa01 PaddleOCR-develop]# python tools/infer/predict_system.py --image_dir=./doc/imgs/12.jpg --det_model_dir=“./inference/det_r50_vd_db/“   --rec_model_dir=”./inference/ch_rec_mv3_crnn/“ --use_gpu=False
2020-07-20 20:30:50,695-INFO: not find model file path “./inference/det_r50_vd_db/“/model
[root@kaifa01 PaddleOCR-develop]# ls -al ./inference/det_r50_vd_db/
总用量 412036
drwxr-xr-x 2 zhsc root      4096 5月  21 15:05 .
drwxr-xr-x 4 root root      4096 7月  20 20:24 ..
-rw-r--r-- 1 zhsc root   1494878 5月  21 15:05 best_accuracy.pdmodel
-rw-r--r-- 1 zhsc root 266381198 5月  21 15:05 best_accuracy.pdopt
-rw-r--r-- 1 zhsc root 154037947 5月  21 15:05 best_accuracy.pdparams

**Comment by Jack-wx** [comment]
又来新的报错了，好迷呀。。。
[root@kaifa01 PaddleOCR-develop]# python tools/infer/predict_system.py --image_dir=./doc/imgs/12.jpg --det_model_dir=./inference/det_r50_vd_db/   --rec_model_dir=”./inference/ch_rec_mv3_crnn/“ --use_gpu=False
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 161, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_system.py", line 118, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 38, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/tools/infer/predict_det.py", line 60, in __init__
    utility.create_predictor(args, mode="det")
  File "/data/WorkSpace/PaddleOcr/PaddleOCR-develop/tools/infer/utility.py", line 105, in create_predictor
    predictor = create_paddle_predictor(config)
ValueError: basic_string::resize

**Comment by tink2123** [comment]
使用inference预测时，下载的应该是inference model，而不是预训练模型

**Comment by Jack-wx** [comment]
> 使用inference预测时，下载的应该是inference model，而不是预训练模型

是的
