### ISSUE TITLE
我的标签是0-24 数字 加上一个字母M 加上背景类 一共27个标签   训练rec_icdar15_train的时候报错  出现了索引28  以下是输出的矩阵

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleOCR#3889]
打印的日志：

(20, 25)

[[ 7  7  7  0  6  0  6  6 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 0  0 21  0 21 21 21 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 1 19  8  8  8  6  7 25  7 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19  0  0  0  7 21  6  6 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [13 13  7  7  7  7  7 21 21 21 21 21 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 0  7  7  7  7  7 21  7 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [16  7  6  7  6  7 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19  7  7  7  7  7  7  7 21  7  7  7  6  6  6 19 19 19 19 19 19 19 19 19
  19]
 [ 7  7  7  7 25 25 25 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19 19  8  8  7  7  7  7 25 25 25  7 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19 19 19  0 19  0 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 0  7  7  7  7  6  6  6  6  2 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19  0 19  6  6  7  7 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 7  7  0  7  6  6 21 21  7  7 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 0  0  0  0  7  7  7  7  7  7  6  6 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]
 [ 6  7  7  7  7  6  7 21  7 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  19]]
batch_idx :  19  idx :  9 查到的label :  19
(27,) ['blank', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', 'M']

(20, 25)

[[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [41  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [41  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [34 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [41  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [41  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [34 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]]
batch_idx :  0  idx :  0 查到的label :  28
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 108, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 244, in train
    post_result = post_process_class(preds, batch[1])
  File "/home/aistudio/work/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 139, in __call__
    label = self.decode(label)
  File "/home/aistudio/work/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 102, in decode
    idx])])
IndexError: list index out of range

不知道怎么去改这个bug  ，求教？这个出错的矩阵不知道从哪来的     有没有转LMDBDataSet的脚本

**Comment by LDOUBLEV** [comment]
检查下你Head最后fc输出的维度是否是28，即是你字典字符的数量：https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/train.py#L81

**Comment by Wei-JL** [comment]
> 检查下你Head最后fc输出的维度是否是28，即是你字典字符的数量：
> 
> https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/train.py#L81


打印输出了 
[2021/09/03 16:18:42] root INFO: Initialize indexs of datasets:['./rec_data/rec_gt_train.txt']
[2021/09/03 16:18:42] root INFO: Initialize indexs of datasets:['./rec_data/rec_gt_test.txt']
===========char_num=========== : 27

确实是27  

主要是这个
https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/ppocr/postprocess/rec_postprocess.py#L71

这个函数
def decode(self, text_index, text_prob=None, is_remove_duplicate=False):  
在解码时出现那个奇怪的矩阵，不知道从何而来，上面的都是正确的，到这里出来这个矩阵报错

**Comment by Wei-JL** [comment]
而且我训练成功过，改了一下标注的方式，原本是标注一竖条数字，现在是这一条数字 ，我一个个标注的

**Comment by littletomatodonkey** [comment]
> > 检查下你Head最后fc输出的维度是否是28，即是你字典字符的数量：
> > https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/train.py#L81
> 
> 打印输出了
> [2021/09/03 16:18:42] root INFO: Initialize indexs of datasets:['./rec_data/rec_gt_train.txt']
> [2021/09/03 16:18:42] root INFO: Initialize indexs of datasets:['./rec_data/rec_gt_test.txt']
> ===========char_num=========== : 27
> 
> 确实是27
> 
> 主要是这个
> https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/ppocr/postprocess/rec_postprocess.py#L71
> 
> 这个函数
> def decode(self, text_index, text_prob=None, is_remove_duplicate=False):
> 在解码时出现那个奇怪的矩阵，不知道从何而来，上面的都是正确的，到这里出来这个矩阵报错

哪个奇怪的矩阵？方便用dygraph分支代码复现下吗？提供下复现数据和脚本

**Comment by littletomatodonkey** [comment]
另外，如果使用自定义字典的话，需要将character type的类型修改为ch

https://github.com/PaddlePaddle/PaddleOCR/blob/03b7daa5be911c0394f6742b5087576c3795143a/configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml#L18

**Comment by Wei-JL** [comment]
> > > 检查下你Head最后fc输出的维度是否是28，即是你字典字符的数量：
> > > https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/tools/train.py#L81
> > 
> > 
> > 打印输出了
> > [2021/09/03 16:18:42] root INFO: Initialize indexs of datasets:['./rec_data/rec_gt_train.txt']
> > [2021/09/03 16:18:42] root INFO: Initialize indexs of datasets:['./rec_data/rec_gt_test.txt']
> > ===========char_num=========== : 27
> > 确实是27
> > 主要是这个
> > https://github.com/PaddlePaddle/PaddleOCR/blob/cadc04cf6cb599bb005be344010443bcfb65e82b/ppocr/postprocess/rec_postprocess.py#L71
> > 
> > 这个函数
> > def decode(self, text_index, text_prob=None, is_remove_duplicate=False):
> > 在解码时出现那个奇怪的矩阵，不知道从何而来，上面的都是正确的，到这里出来这个矩阵报错
> 
> 哪个奇怪的矩阵？方便用dygraph分支代码复现下吗？提供下复现数据和脚本

可以给您公开一下，  奇怪的矩阵就是我发布在第一个的问题    报错前都是正常矩阵  ，如第一个
![image](https://user-images.githubusercontent.com/71386288/131977956-64df4546-87a8-43d9-87bf-035eb8486b85.png)

这些都没有超过27,也就说在我的标签内。
报错是IndexError: list index out of range

错误的矩阵打印出来了，
![image](https://user-images.githubusercontent.com/71386288/131978113-6712d1f8-411d-4e72-a5f8-c668c97b89ab.png)

**Comment by littletomatodonkey** [comment]
看下面的矩阵，解析的字典看着不对，没法提供对应的训练数据或者配置的话，可能得一步步进去debug看下，

**Comment by Wei-JL** [comment]
我找出问题所在了， 我把标签为2位数的 10-24 全部删除了  只剩下0-9加上字母M   可以训练   很奇怪 为什么会出现这种情况
