### ISSUE TITLE
部署时候hub install发生错误

### ISSUE THREAD

**Issue by BI4O** [PaddlePaddle/PaddleOCR#392]
OS: win10
Anaconda 虚拟环境
使用命令`hub install deploy/hubserving/ocr_system/`出错
(ocr) C:\Users\yunshuo\Desktop\HELP\OCR\PaddleOCR\deploy\hubserving>hub install ocr_system/
Traceback (most recent call last):
  File "c:\anaconda3\envs\ocr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\ocr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\ocr\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\commands\install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\module\manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\module\module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "c:\anaconda3\envs\ocr\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.module'

**Comment by Steffy-zxf** [comment]
@BI4O 你好！`hub install`命令支持安装 PaddleHub Module文件夹，该文件夹下应该包含module.py文件。想了解下，`ocr_system `文件夹下是什么内容呢？关于将训练保存的参数转化为PaddleHub Module可以参考教程：https://aistudio.baidu.com/aistudio/projectdetail/641317

**Comment by BI4O** [comment]
是我从PaddleOCR https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/hubserving/ocr_system 拉下的代码

**Comment by Steffy-zxf** [comment]
@BI4O 
> 是我从PaddleOCR https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/hubserving/ocr_system 拉下的代码

这样是不可行的。如果你想使用ocr模型直接预测，可以参考PaddleHub OCR模型使用，具体用法参见API说明以及代码示例：
https://www.paddlepaddle.org.cn/hubdetail?name=chinese_ocr_db_crnn_server&en_category=TextRecognition

**Comment by BI4O** [comment]
> @BI4O 你的运行环境是什么？paddlehub版本是多少？

我就是按照你们PaddleOCR上面的部署教程来的，他就是说明就是这样去安装这个的
paddlehub=1.7.1 
python=3.7
conda=4.8.3
win 10

**Comment by Steffy-zxf** [comment]
试试，在PaddleOCR目录下，执行`hub install deploy/hubserving/ocr_system/`

**Comment by BI4O** [comment]
> 试试，在PaddleOCR目录下，执行`hub install deploy/hubserving/ocr_system/`

我就是这样操作的，出了最上面的那个错

**Comment by BI4O** [comment]
> > 试试，在PaddleOCR目录下，执行`hub install deploy/hubserving/ocr_system/`
> 
> 我就是这样操作的，出了最上面的那个错

我知道你的意思，但不是路径的问题
(ocr) C:\Users\yunshuo\Desktop\HELP\OCR\PaddleOCR>hub install deploy/hubserving/ocr_system/
Traceback (most recent call last):
  File "c:\anaconda3\envs\ocr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\ocr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\ocr\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\commands\install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\module\manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\module\module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "c:\anaconda3\envs\ocr\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "c:\anaconda3\envs\ocr\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.module'

**Comment by MissPenguin** [comment]
可能是环境问题，试试不要用Anaconda或者直接用官网docker？

**Comment by mdddj** [comment]
我也遇到这个错误,楼主解决了吗

**Comment by littletomatodonkey** [comment]
你好，可以参考这个issue中解法： #418

**Comment by BI4O** [comment]
安装好了，但是我折腾了一番修改了ocr_system/params.py把里面的相对路径改成了绝对路径，就可以了
其实我觉得问题应该就出在Win下PATHONPATH的问题，一直觉得Win下的环境变量就很玄学哎....
我还是努力攒钱买个macbook吧
