### ISSUE TITLE
关于Enhanced CTCLoss

### ISSUE THREAD

**Issue by buptlihang** [PaddlePaddle/PaddleOCR#3962]
yt的center是如何生成的，代码里有写嘛？

![image](https://user-images.githubusercontent.com/30074778/132387987-9be455e2-af6f-4913-8204-7a3052476919.png)

**Comment by Intsigstephon** [comment]
yt的center是基于原始CTCLoss训练得到的模型，在训练数据集上提取特征聚合得到的；代码和文档部分，我们同事正在整理中，后续也会一并开源出来

**Comment by yeyupiaoling** [comment]
期待开源

**Comment by nissansz** [comment]
v3模型能用center loss吗？
我用上面的设置，放到resnet34中的loss部分，没有训练进度，读完数据半天后报以下错误？

Traceback (most recent call last):
File "./tools/train.py", line 191, in
main(config, device, logger, vdl_writer)
File "./tools/train.py", line 164, in main
program.train(config, train_dataloader, valid_dataloader, device, model,
File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train
loss = loss_class(preds, batch)
File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in call
return self._dygraph_call_func(*inputs, **kwargs)
File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward
loss = loss_func(input, batch, **kargs)
File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in call
assert isinstance(predicts, (list, tuple))
AssertionError
