### ISSUE TITLE
when I trian dbnet on windows with 4 V100 cards, it reports errors. I use   "os.environ["CUDA_VISIBLE_DEVICES"] = "0"   and paddle.device.set_device("gpu:0")" in main, but it does not work.

### ISSUE THREAD

**Issue by QishuoLu** [PaddlePaddle/PaddleOCR#4032]
C:\Users\luqs\anaconda3\envs\paddle_env\python.exe G:/luqs/ocr/paddleocr/tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrain_weights=pretrain_models/MobileNetV3_large_x0_5_pretrained
2021-09-13 15:03:10,195-INFO: {'Global': {'debug': False, 'algorithm': 'DB', 'use_gpu': True, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2, 'save_model_dir': './output/det_db/', 'save_epoch_step': 200, 'eval_batch_step': [4000, 5000], 'train_batch_size_per_card': 16, 'test_batch_size_per_card': 16, 'image_shape': [3, 640, 640], 'reader_yml': './configs/det/det_db_icdar15_reader.yml', 'pretrain_weights': 'pretrain_models/MobileNetV3_large_x0_5_pretrained', 'checkpoints': None, 'save_res_path': './output/det_db/predicts_db.txt', 'save_inference_dir': None, 'infer_img': None}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'large'}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_name': 'large', 'k': 50, 'inner_channels': 96, 'out_channels': 2}, 'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2': 0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'thresh': 0.3, 'box_thresh': 0.6, 'max_candidates': 1000, 'unclip_ratio': 1.5}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_workers': 8, 'img_set_dir': './train_data/icdar2015/text_localization/', 'label_file_path': './train_data/icdar2015/text_localization/train_icdar2015_label.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': './train_data/icdar2015/text_localization/', 'label_file_path': './train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [736, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': './train_data/icdar2015/text_localization/', 'label_file_path': './train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'do_eval': True}}
3 640 640
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\heads\det_db_head.py:123
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:46
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:47
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\data_feeder.py:51: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool, np.float16, np.uint16, np.float32, np.float64, np.int8,
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py:706: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:100
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:102
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:103
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:113
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\math_op_patch.py:317: UserWarning: G:\luqs\ocr\paddleocr\ppocr\modeling\losses\det_basic_loss.py:113
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
2021-09-13 15:03:11,862-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000000] in Optimizer will not take effect, and it will only be applied to other Parameters!
3 640 640
./train_data/icdar2015/text_localization/train_icdar2015_label.txt
2021-09-13 15:03:15,828-INFO: places would be ommited when DataLoader is not iterable
W0913 15:03:15.959702 571616 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0913 15:03:15.973717 571616 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-09-13 15:03:19,395-INFO: Loading parameters from pretrain_models/MobileNetV3_large_x0_5_pretrained...
2021-09-13 15:03:19,522-INFO: Finish initing model from pretrain_models/MobileNetV3_large_x0_5_pretrained
2021-09-13 15:03:19,522-INFO: During the training process, after the 4000th iteration, an evaluation is run every 5000 iterations
W0913 15:03:19.681726 571616 parallel_executor.cc:601] Cannot enable P2P access from 0 to 2
W0913 15:03:19.681726 571616 parallel_executor.cc:601] Cannot enable P2P access from 0 to 3
W0913 15:03:20.548732 571616 parallel_executor.cc:601] Cannot enable P2P access from 1 to 2
W0913 15:03:20.548732 571616 parallel_executor.cc:601] Cannot enable P2P access from 1 to 3
W0913 15:03:20.548732 571616 parallel_executor.cc:601] Cannot enable P2P access from 2 to 0
W0913 15:03:20.548732 571616 parallel_executor.cc:601] Cannot enable P2P access from 2 to 1
W0913 15:03:22.049734 571616 parallel_executor.cc:601] Cannot enable P2P access from 3 to 0
W0913 15:03:22.049734 571616 parallel_executor.cc:601] Cannot enable P2P access from 3 to 1
Traceback (most recent call last):
  File "G:/luqs/ocr/paddleocr/tools/train.py", line 136, in <module>
    main()
  File "G:/luqs/ocr/paddleocr/tools/train.py", line 104, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "G:\luqs\ocr\paddleocr\tools\program.py", line 299, in train_eval_det_run
    train_outs = exe.run(
  File "C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1241, in _run_impl
    program._compile(scope, self.place)
  File "C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\compiler.py", line 464, in _compile
    self._executor = self._compile_data_parallel(
  File "C:\Users\luqs\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\compiler.py", line 411, in _compile_data_parallel
    return core.ParallelExecutor(
RuntimeError: (Unavailable) Windows can support Single GPU only.
  [Hint: Expected device_count == 1, but received device_count:4 != 1:1.] (at C:\home\workspace\Paddle_release3\paddle\fluid\framework\parallel_executor.cc:1080)

**Comment by QishuoLu** [comment]
solved
