### ISSUE TITLE
ppstructure中使用 model_path 更换自己训练的版面分析模型，报错！

### ISSUE THREAD

**Issue by fly8764** [PaddlePaddle/PaddleOCR#4052]
套件中使用的模型默认为 ppyolov2_r50vd_dcn_365e_publaynet ,使用 model_path 更换自己训练的版面分析模型 ppyolo_mbv3_large_coco，就报错，报错信息如下所示：
    InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 160, 20, 20], input[1]'s shape = [1, 1, 10, 10].
      [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:20 != inputs_dims[i][j]:10.] (at /paddle/paddle/fluid/operators/concat_op.h:63)
      [operator < concat > error]

**Comment by WenmuZhou** [comment]
你模型训练的shape是多大

**Comment by fly8764** [comment]
> 你模型训练的shape是多大

按照 PaddleDetection/configs/ppyolo/ppyolo_mbv3_large_coco.yml 中的设置训练的，

TrainReader:  
  inputs_def:
    num_max_boxes: 90
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {} 
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]} 
    - RandomCrop: {} 
    - RandomFlip: {} 
  batch_transforms:
    - BatchRandomResize:
        target_size: [224, 256, 288, 320, 352, 384, 416, 448, 480, 512]
        random_size: True
        random_interp: True
        keep_ratio: False
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 90}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget:
        anchor_masks: [[3, 4, 5], [0, 1, 2]]
        anchors: [[11, 18], [34, 47], [51, 126], [115, 71], [120, 195], [254, 235]] 
        downsample_ratios: [32, 16]
        iou_thresh: 0.25
        num_classes: 5
  batch_size: 4
  mixup_epoch: 200
  shuffle: true

**Comment by fly8764** [comment]
报错信息中中，为什么会指向PaddleDetection_0项目？如下 加粗部分所示：
Traceback (most recent call last):
  File "predict_system.py", line 152, in <module>
    main(args)
  File "predict_system.py", line 128, in main
    res = structure_sys(img)
  File "predict_system.py", line 63, in __call__
    layout_res = self.table_layout.detect(img[..., ::-1])
  File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/layoutparser/models/layoutmodel.py", line 378, in detect
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    **File "/home/ailab/Desktop/yifei/workspace/PaddleDetection_0/ppdet/engine/trainer.py", line 541, in export
      input_spec, static_model.forward.main_program,**
    File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)

**Comment by fly8764** [comment]
报错信息中中，为什么会指向PaddleDetection_0项目？如下 加粗部分所示：
Traceback (most recent call last):
File "predict_system.py", line 152, in
main(args)
File "predict_system.py", line 128, in main
res = structure_sys(img)
File "predict_system.py", line 63, in call
layout_res = self.table_layout.detect(img[..., ::-1])
File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/layoutparser/models/layoutmodel.py", line 378, in detect
self.predictor.run()
ValueError: In user code:

File "tools/export_model.py", line 105, in <module>
  main()
File "tools/export_model.py", line 101, in main
  run(FLAGS, cfg)
File "tools/export_model.py", line 69, in run
  trainer.export(FLAGS.output_dir)
**File "/home/ailab/Desktop/yifei/workspace/PaddleDetection_0/ppdet/engine/trainer.py", line 541, in export**
  **input_spec, static_model.forward.main_program,**
File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
  concrete_program = self.concrete_program
File "/opt/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
  return self.concrete_program_specify_input_spec(input_spec=None)

**Comment by WenmuZhou** [comment]
指向PaddleDetection_0很正常，你应该setup install 过，
