### ISSUE TITLE
[OCR] android demo运行时崩溃

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/PaddleOCR#407]
Hi Team,

我在运行ocr的android demo时，编译都已经全部成功，但是在运行时崩溃，以下是崩溃信息

07-23 17:58:26.868 24321-24340/com.baidu.paddle.lite.demo.ocr E/art: dlopen("/data/app/com.baidu.paddle.lite.demo.ocr-2/lib/arm/libNative.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"...
07-23 17:58:26.871 24321-24340/com.baidu.paddle.lite.demo.ocr E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.ocr, PID: 24321
    java.lang.RuntimeException: Load libNative.so failed, please check it exists in apk file.
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:18)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:120)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:79)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:241)
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:129)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:16)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:120) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:79) 
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:241) 
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:129) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 

我的平台是rk3288 ,Android系统版本为5.1.1
AndroidStudio:4.0.1, NDK:21.3.6528147

谢谢

**Comment by AIpioneer** [comment]
你好，我们编译了一个适合于低版本的预测库，麻烦你改一下试试。另外，欢迎你直接联系到我，微信同手机：I52I0五9八六五吧。链接:https://pan.baidu.com/s/1r_eoMahWf9a1Gk3yamP3WQ  密码:tq39

**Comment by AIpioneer** [comment]
不知道您解决没有，可以给我们一个反馈

**Comment by zlszhonglongshen** [comment]
> tq39

能放出你自己后的源码am？

**Comment by AIpioneer** [comment]
在编译的时候，可以使用如下的参数来支持低版本的安卓。https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/tools/build_android.sh 
--android_api_level: (21~27); control android api level, default value is 22 when arch=armv7 , 23 when arch=armv8.               |"
    echo -e "|                 eg. when android platform version is lower than Android6.0, we need to set android_api_level:
