### ISSUE TITLE
at the time of inference 

### ISSUE THREAD

**Issue by YC7225** [PaddlePaddle/PaddleOCR#4082]
[2021/09/16 09:08:27] root INFO: Architecture : 
[2021/09/16 09:08:27] root INFO:     Backbone : 
[2021/09/16 09:08:27] root INFO:         name : ResNetFPN
[2021/09/16 09:08:27] root INFO:     Head : 
[2021/09/16 09:08:27] root INFO:         hidden_dims : 512
[2021/09/16 09:08:27] root INFO:         max_text_length : 25
[2021/09/16 09:08:27] root INFO:         name : SRNHead
[2021/09/16 09:08:27] root INFO:         num_decoder_TUs : 4
[2021/09/16 09:08:27] root INFO:         num_encoder_TUs : 2
[2021/09/16 09:08:27] root INFO:         num_heads : 8
[2021/09/16 09:08:27] root INFO:     Transform : None
[2021/09/16 09:08:27] root INFO:     algorithm : SRN
[2021/09/16 09:08:27] root INFO:     in_channels : 1
[2021/09/16 09:08:27] root INFO:     model_type : rec
[2021/09/16 09:08:27] root INFO: Eval : 
[2021/09/16 09:08:27] root INFO:     dataset : 
[2021/09/16 09:08:27] root INFO:         data_dir : /content/drive/MyDrive/tesseractMICR/datasets/e13b
[2021/09/16 09:08:27] root INFO:         label_file_list : ['/content/drive/MyDrive/sample.txt']
[2021/09/16 09:08:27] root INFO:         name : SimpleDataSet
[2021/09/16 09:08:27] root INFO:         transforms : 
[2021/09/16 09:08:27] root INFO:             DecodeImage : 
[2021/09/16 09:08:27] root INFO:                 channel_first : False
[2021/09/16 09:08:27] root INFO:                 img_mode : BGR
[2021/09/16 09:08:27] root INFO:             SRNLabelEncode : None
[2021/09/16 09:08:27] root INFO:             SRNRecResizeImg : 
[2021/09/16 09:08:27] root INFO:                 image_shape : [1, 64, 256]
[2021/09/16 09:08:27] root INFO:             KeepKeys : 
[2021/09/16 09:08:27] root INFO:                 keep_keys : ['image', 'label', 'length', 'encoder_word_pos', 'gsrm_word_pos', 'gsrm_slf_attn_bias1', 'gsrm_slf_attn_bias2']
[2021/09/16 09:08:27] root INFO:     loader : 
[2021/09/16 09:08:27] root INFO:         batch_size_per_card : 32
[2021/09/16 09:08:27] root INFO:         drop_last : False
[2021/09/16 09:08:27] root INFO:         num_workers : 4
[2021/09/16 09:08:27] root INFO:         shuffle : True
[2021/09/16 09:08:27] root INFO: Global : 
[2021/09/16 09:08:27] root INFO:     cal_metric_during_train : True
[2021/09/16 09:08:27] root INFO:     character_dict_path : /content/drive/MyDrive/PaddleOCR/word_dict1.txt
[2021/09/16 09:08:27] root INFO:     character_type : en
[2021/09/16 09:08:27] root INFO:     checkpoints : None
[2021/09/16 09:08:27] root INFO:     debug : False
[2021/09/16 09:08:27] root INFO:     distributed : False
[2021/09/16 09:08:27] root INFO:     epoch_num : 72
[2021/09/16 09:08:27] root INFO:     eval_batch_step : [0, 5000]
[2021/09/16 09:08:27] root INFO:     infer_img : /content/drive/MyDrive/tesseractMICR/datasets/e13b/reallife_cgi_1212991940-0.
[2021/09/16 09:08:27] root INFO:     infer_mode : False
[2021/09/16 09:08:27] root INFO:     load_static_weights : True
[2021/09/16 09:08:27] root INFO:     log_smooth_window : 20
[2021/09/16 09:08:27] root INFO:     max_text_length : 25
[2021/09/16 09:08:27] root INFO:     num_heads : 8
[2021/09/16 09:08:27] root INFO:     pretrained_model : /content/drive/MyDrive/PaddleOCR/iter_epoch_72
[2021/09/16 09:08:27] root INFO:     print_batch_step : 5
[2021/09/16 09:08:27] root INFO:     save_epoch_step : 3
[2021/09/16 09:08:27] root INFO:     save_inference_dir : None
[2021/09/16 09:08:27] root INFO:     save_model_dir : /content/drive/MyDrive/PaddleOCR/
[2021/09/16 09:08:27] root INFO:     use_gpu : False
[2021/09/16 09:08:27] root INFO:     use_space_char : True
[2021/09/16 09:08:27] root INFO:     use_visualdl : False
[2021/09/16 09:08:27] root INFO: Loss : 
[2021/09/16 09:08:27] root INFO:     name : SRNLoss
[2021/09/16 09:08:27] root INFO: Metric : 
[2021/09/16 09:08:27] root INFO:     main_indicator : acc
[2021/09/16 09:08:27] root INFO:     name : RecMetric
[2021/09/16 09:08:27] root INFO: Optimizer : 
[2021/09/16 09:08:27] root INFO:     beta1 : 0.9
[2021/09/16 09:08:27] root INFO:     beta2 : 0.999
[2021/09/16 09:08:27] root INFO:     clip_norm : 10.0
[2021/09/16 09:08:27] root INFO:     lr : 
[2021/09/16 09:08:27] root INFO:         learning_rate : 0.0001
[2021/09/16 09:08:27] root INFO:     name : Adam
[2021/09/16 09:08:27] root INFO: PostProcess : 
[2021/09/16 09:08:27] root INFO:     name : SRNLabelDecode
[2021/09/16 09:08:27] root INFO: Train : 
[2021/09/16 09:08:27] root INFO:     dataset : 
[2021/09/16 09:08:27] root INFO:         data_dir : /content/drive/MyDrive/tesseractMICR/datasets/e13b
[2021/09/16 09:08:27] root INFO:         label_file_list : ['/content/drive/MyDrive/sample.txt']
[2021/09/16 09:08:27] root INFO:         name : SimpleDataSet
[2021/09/16 09:08:27] root INFO:         transforms : 
[2021/09/16 09:08:27] root INFO:             DecodeImage : 
[2021/09/16 09:08:27] root INFO:                 channel_first : False
[2021/09/16 09:08:27] root INFO:                 img_mode : BGR
[2021/09/16 09:08:27] root INFO:             SRNLabelEncode : None
[2021/09/16 09:08:27] root INFO:             SRNRecResizeImg : 
[2021/09/16 09:08:27] root INFO:                 image_shape : [1, 64, 256]
[2021/09/16 09:08:27] root INFO:             KeepKeys : 
[2021/09/16 09:08:27] root INFO:                 keep_keys : ['image', 'label', 'length', 'encoder_word_pos', 'gsrm_word_pos', 'gsrm_slf_attn_bias1', 'gsrm_slf_attn_bias2']
[2021/09/16 09:08:27] root INFO:     loader : 
[2021/09/16 09:08:27] root INFO:         batch_size_per_card : 64
[2021/09/16 09:08:27] root INFO:         drop_last : False
[2021/09/16 09:08:27] root INFO:         num_workers : 4
[2021/09/16 09:08:27] root INFO:         shuffle : True
[2021/09/16 09:08:27] root INFO: train with paddle 2.1.3 and device CPUPlace
Traceback (most recent call last):
  File "tools/infer_rec.py", line 110, in <module>
    main()
  File "tools/infer_rec.py", line 52, in main
    model = build_model(config['Architecture'])
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 23, in build_model
    module_class = BaseModel(config)
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 69, in __init__
    self.head = build_head(config["Head"])
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/__init__.py", line 39, in build_head
    module_class = eval(module_name)(**config)
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/rec_srn_head.py", line 239, in __init__
    hidden_dims=self.hidden_dims)
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/rec_srn_head.py", line 61, in __init__
    weight_sharing=True)
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/self_attention.py", line 59, in __init__
    postprocess_cmd)
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/self_attention.py", line 137, in __init__
    postprocess_cmd)))
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/self_attention.py", line 168, in __init__
    prepostprocess_dropout)
  File "/content/drive/MyDrive/PaddleOCR/ppocr/modeling/heads/self_attention.py", line 289, in __init__
    self.sublayers(include_sublayers=False)),
TypeError: sublayers() got an unexpected keyword argument 'include_sublayers'

**Comment by littletomatodonkey** [comment]
你好，可以先升级paddle版本到2.1.2看下
