### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by wjl8** [PaddlePaddle/PaddleOCR#4111]
Traceback (most recent call last):
  File "gan.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\paddleocr\paddleocr.py", line 26, in <module>
    from tools.infer import predict_system
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 31, in <module>
    import tools.infer.predict_rec as predict_rec
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 31, in <module>
    from ppocr.postprocess import build_post_process
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\paddleocr\ppocr\postprocess\__init__.py", line 24, in <module>
    from .db_postprocess import DBPostProcess, DistillationDBPostProcess
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 22, in <module>
    from shapely.geometry import Polygon
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "D:\codeworkpace\python\envs\paddle\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "d:\anaconda\Lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

我看那一行显示CDLL，应该是找不到这个，但是为什么呢？它不是ctypes下的方法吗？

**Comment by LDOUBLEV** [comment]
搜一下FAQ或者相关issue，是shaply库的问题

**Comment by Evezerest** [comment]
可以参考这个 [文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/quickstart.md#1-%E5%AE%89%E8%A3%85paddleocr-whl%E5%8C%85)
