### ISSUE TITLE
pip install fails on linux

### ISSUE THREAD

**Issue by lbhdc** [PaddlePaddle/PaddleOCR#4117]
Hey! I wanted to try out your package, but it failed to install. I included the steps I took to reproduce the problem.

## Problem
pip installing `paddleocr` is failing due to module resolution
```shell
> pip install "paddleocr>=2.0.1"
...
ERROR: ResolutionImpossible: ...
```
After some hacking around I got it to install, but it seems it didn't install correctly and is failing to import
```python
>>> from paddleocr import PaddleOCR
...
ModuleNotFoundError: No module named 'paddle'
```

## My system
```shell
> python --version
Python 3.9.7
> pip --version
pip 21.2.4 from /home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/pip (python 3.9)
> uname -a
Linux 5.13.16-200.fc34.x86_64 #1 SMP Mon Sep 13 12:39:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

## Steps to reproduce
Create a new virtual env
```shell
> mkdir /tmp/pocr && cd /tmp/pocr
> pipenv install --python 3.9
Creating a virtualenv for this project...
...
> pipenv shell
Launching subshell in virtual environment...
>  source /home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/bin/activate.fish
(pocr) > pip freeze  # returns nothing
```

Instailling using the command from the quickstart fails to resolve the correct version of `scikit-images`
```shell
(pocr) > pip install "paddleocr>=2.0.1"
Collecting paddleocr>=2.0.1
  Downloading paddleocr-2.3.0.1-py3-none-any.whl (239 kB)
     |████████████████████████████████| 239 kB 1.5 MB/s 
Collecting openpyxl
  Downloading openpyxl-3.0.8-py2.py3-none-any.whl (244 kB)
     |████████████████████████████████| 244 kB 11.7 MB/s 
Collecting premailer
  Downloading premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Collecting lmdb
  Downloading lmdb-1.2.1-cp39-cp39-manylinux2010_x86_64.whl (306 kB)
     |████████████████████████████████| 306 kB 9.9 MB/s 
Collecting numpy
  Downloading numpy-1.21.2-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
     |████████████████████████████████| 15.8 MB 15.0 MB/s 
Collecting pyclipper
  Downloading pyclipper-1.3.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (124 kB)
     |████████████████████████████████| 124 kB 21.5 MB/s 
Collecting opencv-contrib-python==4.4.0.46
  Downloading opencv_contrib_python-4.4.0.46-cp39-cp39-manylinux2014_x86_64.whl (55.7 MB)
     |████████████████████████████████| 55.7 MB 11.5 MB/s 
Collecting tqdm
  Downloading tqdm-4.62.2-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 3.3 MB/s 
Collecting python-Levenshtein
  Downloading python-Levenshtein-0.12.2.tar.gz (50 kB)
     |████████████████████████████████| 50 kB 5.3 MB/s 
Collecting imgaug==0.4.0
  Downloading imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
     |████████████████████████████████| 948 kB 7.9 MB/s 
Collecting visualdl
  Downloading visualdl-2.2.1-py3-none-any.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 14.9 MB/s 
Collecting scikit-image==0.17.2
  Downloading scikit-image-0.17.2.tar.gz (29.8 MB)
     |████████████████████████████████| 29.8 MB 33.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-akmf7o91/scikit-image_a7b5fd7bd7f94bcf9edf407b822ec206/setup.py'"'"'; __file__='"'"'/tmp/pip-install-akmf7o91/scikit-image_a7b5fd7bd7f94bcf9edf407b822ec206/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o6kxpb18
         cwd: /tmp/pip-install-akmf7o91/scikit-image_a7b5fd7bd7f94bcf9edf407b822ec206/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-akmf7o91/scikit-image_a7b5fd7bd7f94bcf9edf407b822ec206/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/tmp/pip-install-akmf7o91/scikit-image_a7b5fd7bd7f94bcf9edf407b822ec206/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz#sha256=bd954c0588f0f7e81d9763dc95e06950e68247d540476e06cb77bcbcd8c2d8b3 (from https://pypi.org/simple/scikit-image/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting paddleocr>=2.0.1
  Downloading paddleocr-2.3-py3-none-any.whl (238 kB)
     |████████████████████████████████| 238 kB 18.2 MB/s 
  Downloading paddleocr-2.2.0.2-py3-none-any.whl (236 kB)
     |████████████████████████████████| 236 kB 11.2 MB/s 
  Downloading paddleocr-2.2.0.1-py3-none-any.whl (236 kB)
     |████████████████████████████████| 236 kB 15.9 MB/s 
  Downloading paddleocr-2.2-py3-none-any.whl (236 kB)
     |████████████████████████████████| 236 kB 14.4 MB/s 
  Downloading paddleocr-2.0.6-py3-none-any.whl (189 kB)
     |████████████████████████████████| 189 kB 8.7 MB/s 
  Downloading paddleocr-2.0.5-py3-none-any.whl (175 kB)
     |████████████████████████████████| 175 kB 9.7 MB/s 
  Downloading paddleocr-2.0.4-py3-none-any.whl (160 kB)
     |████████████████████████████████| 160 kB 88.8 MB/s 
  Downloading paddleocr-2.0.3-py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 20.9 MB/s 
  Downloading paddleocr-2.0.2-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 7.2 MB/s 
  Downloading paddleocr-2.0.1-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 17.3 MB/s 
ERROR: Cannot install paddleocr==2.0.1, paddleocr==2.0.2, paddleocr==2.0.3, paddleocr==2.0.4, paddleocr==2.0.5, paddleocr==2.0.6, paddleocr==2.2, paddleocr==2.2.0.1, paddleocr==2.2.0.2, paddleocr==2.3 and paddleocr==2.3.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    paddleocr 2.3.0.1 depends on scikit-image==0.17.2
    paddleocr 2.3 depends on scikit-image==0.17.2
    paddleocr 2.2.0.2 depends on scikit-image==0.17.2
    paddleocr 2.2.0.1 depends on opencv-contrib-python==4.2.0.32
    paddleocr 2.2 depends on opencv-contrib-python==4.2.0.32
    paddleocr 2.0.6 depends on opencv-python==4.2.0.32
    paddleocr 2.0.5 depends on opencv-python==4.2.0.32
    paddleocr 2.0.4 depends on opencv-python==4.2.0.32
    paddleocr 2.0.3 depends on opencv-python==4.2.0.32
    paddleocr 2.0.2 depends on opencv-python==4.2.0.32
    paddleocr 2.0.1 depends on opencv-python==4.2.0.32

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Trying to explicitly install the latest version of paddleocr fails with the same error.
```shell
(pocr) > pip install "paddleocr==2.3.0.1"
...
ERROR: No matching distribution found for scikit-image==0.17.2
```

Using pipenv it was able to resolve the dependencies that pip wasn't
```shell
(pocr) > pipenv install "paddleocr>=2.0.1"
Installing paddleocr>=2.0.1...
Adding paddleocr to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock (16c839) out of date, updating to (4a12d7)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (4a12d7)!
Installing dependencies from Pipfile.lock (4a12d7)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
```

This is the resulting environment
```shell
(pocr) > pip freeze
Babel==2.9.1
backports.entry-points-selectable==1.1.0
bce-python-sdk==0.8.62
cachetools==4.2.2
certifi==2021.5.30
cfgv==3.3.1
charset-normalizer==2.0.6
click==8.0.1
cssselect==1.1.0
cssutils==2.3.0
cycler==0.10.0
distlib==0.3.2
et-xmlfile==1.1.0
filelock==3.0.12
flake8==3.9.2
Flask==2.0.1
Flask-Babel==2.0.0
future==0.18.2
identify==2.2.14
idna==3.2
imageio==2.9.0
imgaug==0.4.0
itsdangerous==2.0.1
Jinja2==3.0.1
kiwisolver==1.3.2
lmdb==1.2.1
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib==3.4.3
mccabe==0.6.1
networkx==2.6.3
nodeenv==1.6.0
numpy==1.21.2
opencv-contrib-python==4.4.0.46
opencv-python==4.5.3.56
openpyxl==3.0.8
paddleocr==2.3.0.1
pandas==1.3.3
Pillow==8.3.2
platformdirs==2.3.0
pre-commit==2.15.0
premailer==3.10.0
protobuf==3.18.0
pyclipper==1.3.0
pycodestyle==2.7.0
pycryptodome==3.10.1
pyflakes==2.3.1
pyparsing==2.4.7
python-dateutil==2.8.2
python-Levenshtein==0.12.2
pytz==2021.1
PyWavelets==1.1.1
PyYAML==5.4.1
requests==2.26.0
scikit-image==0.17.2
scipy==1.7.1
Shapely==1.7.1
shellcheck-py==0.7.2.1
six==1.16.0
tifffile==2021.8.30
toml==0.10.2
tqdm==4.62.2
urllib3==1.26.6
virtualenv==20.8.0
visualdl==2.2.1
Werkzeug==2.0.1
```

Trying to import paddleocr from the repl fails
```python
>>> import paddleocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/__init__.py", line 15, in <module>
    from .paddleocr import *
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 26, in <module>
    from tools.infer import predict_system
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/tools/infer/predict_system.py", line 30, in <module>
    import tools.infer.utility as utility
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/tools/infer/utility.py", line 23, in <module>
    from paddle import inference
ModuleNotFoundError: No module named 'paddle'
>>> from paddleocr import PaddleOCR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/__init__.py", line 15, in <module>
    from .paddleocr import *
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 26, in <module>
    from tools.infer import predict_system
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/tools/infer/predict_system.py", line 30, in <module>
    import tools.infer.utility as utility
  File "/home/<user_name>/.local/share/virtualenvs/pocr-4L00uMQQ/lib/python3.9/site-packages/paddleocr/tools/infer/utility.py", line 23, in <module>
    from paddle import inference
ModuleNotFoundError: No module named 'paddle'
```

**Comment by tink2123** [comment]
You need to install the correct version of paddle，for example:
```
python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
```

more version can refer to:
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
