### ISSUE TITLE
在完成PaddleOCR体验小作业的时候，训练正常，但是测试报错

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleOCR#413]
在完成PaddleOCR体验小作业的时候，训练正常，但是测试报错：
单张检测：
export PYTHONPATH=. && python3 tools/infer_det.py -c configs/det/det_db_mv3.yml -o TestReader="./imgs/image_819.jpg"

2020-07-24 09:17:53,837-INFO: Finish initing model from ./output/det_db/best_accuracy
Traceback (most recent call last):
  File "tools/infer_det.py", line 150, in <module>
    main()
  File "tools/infer_det.py", line 107, in main
    test_reader = reader_main(config=config, mode='test')
  File "/home/aistudio/ppocr/data/reader_main.py", line 64, in reader_main
    params['mode'] = mode
TypeError: 'str' object does not support item assignment

单张识别：
export PYTHONPATH=. &&  python3 tools/infer_rec.py -c configs/rec/rec_icdar15_train.yml -o 
 Global.infer_img=./imgs/text_line.jpg

Traceback (most recent call last):
  File "tools/infer_rec.py", line 40, in <module>
    from ppocr.data.reader_main import test_reader
ImportError: cannot import name 'test_reader' from 'ppocr.data.reader_main' (/home/aistudio/ppocr/data/reader_main.py)

**Comment by littletomatodonkey** [comment]
单张检测：应该用`Global.infer_img`而不是`TestReader`去传入要处理的图像

单张识别：你这个是最新代码吗？官方的代码里，40行和你的内容不一样
https://github.com/PaddlePaddle/PaddleOCR/blob/02d8d51df4b4870b9ba8912770f04193824357a1/tools/infer_rec.py#L40

**Comment by deep-practice** [comment]
@littletomatodonkey 我是直接fork的官方那个AIStudio里面的 可能不是最新的

**Comment by deep-practice** [comment]
关键是我用官方Notobook那句命令去执行，一样的报错。。

**Comment by littletomatodonkey** [comment]
方便发一下详细的报错信息以及notebook链接吗？

**Comment by deep-practice** [comment]
单张检测：
第一种情况 Global.infer_img
export PYTHONPATH=. && python3 tools/infer_det.py -c configs/det/det_db_mv3.yml -o Global.infer_img="./imgs/image_819.jpg"

Traceback (most recent call last):
  File "tools/infer_det.py", line 150, in <module>
    main()
  File "tools/infer_det.py", line 73, in main
    program.merge_config(FLAGS.opt)
  File "/home/aistudio/tools/program.py", line 120, in merge_config
    assert (sub_key in cur)
AssertionError

第二种情况：
export PYTHONPATH=. && python3 tools/infer_det.py -c configs/det/det_db_mv3.yml -o TestReader="./imgs/image_819.jpg" 

3 640 640
W0724 16:07:15.612651   256 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0724 16:07:15.616487   256 device_context.cc:245] device: 0, cuDNN Version: 7.3.
2020-07-24 16:07:16,946-INFO: Finish initing model from ./output/det_db/best_accuracy
Traceback (most recent call last):
  File "tools/infer_det.py", line 150, in <module>
    main()
  File "tools/infer_det.py", line 107, in main
    test_reader = reader_main(config=config, mode='test')
  File "/home/aistudio/ppocr/data/reader_main.py", line 64, in reader_main
    params['mode'] = mode
TypeError: 'str' object does not support item assignment

  Notebook不提交作业的情况下能直接公开吗?
