### ISSUE TITLE
AI studio 2.1版本跑LMDB数据集时出现这个

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleOCR#4131]
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  [Previous line repeated 9973 more times]
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 112, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/__init__.py", line 41, in transform
    data = op(data)
  File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/operators.py", line 44, in __call__
    img = np.frombuffer(img, dtype='uint8')
RecursionError: maximum recursion depth exceeded in comparison

    for idx, batch in enumerate(train_dataloader):

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

相比之下，最大递归深度已超过

已经在对应文件下设置：
sys.setrecursionlimit(10000) #设置为万  

还是报错 ，请问怎么办

**Comment by Wei-JL** [comment]
[2021/09/22 11:09:53] root INFO: Architecture : 
[2021/09/22 11:09:53] root INFO:     Backbone : 
[2021/09/22 11:09:53] root INFO:         model_name : large
[2021/09/22 11:09:53] root INFO:         name : MobileNetV3
[2021/09/22 11:09:53] root INFO:         scale : 0.5
[2021/09/22 11:09:53] root INFO:     Head : 
[2021/09/22 11:09:53] root INFO:         hidden_size : 96
[2021/09/22 11:09:53] root INFO:         name : AttentionHead
[2021/09/22 11:09:53] root INFO:     Neck : 
[2021/09/22 11:09:53] root INFO:         encoder_type : rnn
[2021/09/22 11:09:53] root INFO:         hidden_size : 96
[2021/09/22 11:09:53] root INFO:         name : SequenceEncoder
[2021/09/22 11:09:53] root INFO:     Transform : 
[2021/09/22 11:09:53] root INFO:         loc_lr : 0.1
[2021/09/22 11:09:53] root INFO:         model_name : small
[2021/09/22 11:09:53] root INFO:         name : TPS
[2021/09/22 11:09:53] root INFO:         num_fiducial : 20
[2021/09/22 11:09:53] root INFO:     algorithm : RARE
[2021/09/22 11:09:53] root INFO:     model_type : rec
[2021/09/22 11:09:53] root INFO: Eval : 
[2021/09/22 11:09:53] root INFO:     dataset : 
[2021/09/22 11:09:53] root INFO:         data_dir : ./rec_data/test_lmdb
[2021/09/22 11:09:53] root INFO:         name : LMDBDataSet
[2021/09/22 11:09:53] root INFO:         transforms : 
[2021/09/22 11:09:53] root INFO:             DecodeImage : 
[2021/09/22 11:09:53] root INFO:                 channel_first : False
[2021/09/22 11:09:53] root INFO:                 img_mode : BGR
[2021/09/22 11:09:53] root INFO:             AttnLabelEncode : None
[2021/09/22 11:09:53] root INFO:             RecResizeImg : 
[2021/09/22 11:09:53] root INFO:                 image_shape : [3, 32, 100]
[2021/09/22 11:09:53] root INFO:             KeepKeys : 
[2021/09/22 11:09:53] root INFO:                 keep_keys : ['image', 'label', 'length']
[2021/09/22 11:09:53] root INFO:     loader : 
[2021/09/22 11:09:53] root INFO:         batch_size_per_card : 64
[2021/09/22 11:09:53] root INFO:         drop_last : False
[2021/09/22 11:09:53] root INFO:         num_workers : 1
[2021/09/22 11:09:53] root INFO:         shuffle : False
[2021/09/22 11:09:53] root INFO:         use_shared_memory : False
[2021/09/22 11:09:53] root INFO: Global : 
[2021/09/22 11:09:53] root INFO:     cal_metric_during_train : True
[2021/09/22 11:09:53] root INFO:     character_dict_path : ./rec_data/word_dict.txt
[2021/09/22 11:09:53] root INFO:     character_type : en
[2021/09/22 11:09:53] root INFO:     checkpoints : None
[2021/09/22 11:09:53] root INFO:     debug : False
[2021/09/22 11:09:53] root INFO:     distributed : False
[2021/09/22 11:09:53] root INFO:     epoch_num : 1230
[2021/09/22 11:09:53] root INFO:     eval_batch_step : [0, 540]
[2021/09/22 11:09:53] root INFO:     infer_img : ../../test_rec/000066.jpg
[2021/09/22 11:09:53] root INFO:     infer_mode : False
[2021/09/22 11:09:53] root INFO:     log_smooth_window : 20
[2021/09/22 11:09:53] root INFO:     max_text_length : 18
[2021/09/22 11:09:53] root INFO:     pretrained_model : ./pretrain_models/rec_mv3_tps_bilstm_attn/best_accuracy
[2021/09/22 11:09:53] root INFO:     print_batch_step : 30
[2021/09/22 11:09:53] root INFO:     save_epoch_step : 30
[2021/09/22 11:09:53] root INFO:     save_inference_dir : None
[2021/09/22 11:09:53] root INFO:     save_model_dir : ./output/rec/rec_mv3_tps_bilstm_att/
[2021/09/22 11:09:53] root INFO:     save_res_path : ./output/rec/predicts_mv3_tps_bilstm_attnew.txt
[2021/09/22 11:09:53] root INFO:     use_gpu : True
[2021/09/22 11:09:53] root INFO:     use_space_char : False
[2021/09/22 11:09:53] root INFO:     use_visualdl : True
[2021/09/22 11:09:53] root INFO: Loss : 
[2021/09/22 11:09:53] root INFO:     name : AttentionLoss
[2021/09/22 11:09:53] root INFO: Metric : 
[2021/09/22 11:09:53] root INFO:     main_indicator : acc
[2021/09/22 11:09:53] root INFO:     name : RecMetric
[2021/09/22 11:09:53] root INFO: Optimizer : 
[2021/09/22 11:09:53] root INFO:     beta1 : 0.9
[2021/09/22 11:09:53] root INFO:     beta2 : 0.999
[2021/09/22 11:09:53] root INFO:     lr : 
[2021/09/22 11:09:53] root INFO:         learning_rate : 8e-05
[2021/09/22 11:09:53] root INFO:     name : Adam
[2021/09/22 11:09:53] root INFO:     regularizer : 
[2021/09/22 11:09:53] root INFO:         factor : 1e-05
[2021/09/22 11:09:53] root INFO:         name : L2
[2021/09/22 11:09:53] root INFO: PostProcess : 
[2021/09/22 11:09:53] root INFO:     name : AttnLabelDecode
[2021/09/22 11:09:53] root INFO: Train : 
[2021/09/22 11:09:53] root INFO:     dataset : 
[2021/09/22 11:09:53] root INFO:         data_dir : ./rec_data/train_lmdb
[2021/09/22 11:09:53] root INFO:         name : LMDBDataSet
[2021/09/22 11:09:53] root INFO:         transforms : 
[2021/09/22 11:09:53] root INFO:             DecodeImage : 
[2021/09/22 11:09:53] root INFO:                 channel_first : False
[2021/09/22 11:09:53] root INFO:                 img_mode : BGR
[2021/09/22 11:09:53] root INFO:             AttnLabelEncode : None
[2021/09/22 11:09:53] root INFO:             RecResizeImg : 
[2021/09/22 11:09:53] root INFO:                 image_shape : [3, 32, 100]
[2021/09/22 11:09:53] root INFO:             KeepKeys : 
[2021/09/22 11:09:53] root INFO:                 keep_keys : ['image', 'label', 'length']
[2021/09/22 11:09:53] root INFO:     loader : 
[2021/09/22 11:09:53] root INFO:         batch_size_per_card : 160
[2021/09/22 11:09:53] root INFO:         drop_last : True
[2021/09/22 11:09:53] root INFO:         num_workers : 10
[2021/09/22 11:09:53] root INFO:         shuffle : True
[2021/09/22 11:09:53] root INFO:         use_shared_memory : False
[2021/09/22 11:09:53] root INFO: train with paddle 2.1.2 and device CUDAPlace(0)
[2021/09/22 11:09:53] root INFO: Initialize indexs of datasets:./rec_data/train_lmdb
[2021/09/22 11:09:53] root INFO: Initialize indexs of datasets:./rec_data/test_lmdb
W0922 11:09:53.600998  2001 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1
W0922 11:09:53.606202  2001 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[2021/09/22 11:09:56] root INFO: The shape of model params neck.encoder.lstm.1.cell_fw.bias_ih [384] not matched with loaded params rnn_out_fc.b_0 [38] !
[2021/09/22 11:09:56] root INFO: loaded pretrained_model successful from ./pretrain_models/rec_mv3_tps_bilstm_attn/best_accuracy.pdparams
[2021/09/22 11:09:56] root INFO: train dataloader has 18 iters
[2021/09/22 11:09:56] root INFO: valid dataloader has 5 iters
[2021/09/22 11:09:56] root INFO: During the training process, after the 0th iteration, an evaluation is run every 540 iterations
[2021/09/22 11:09:56] root INFO: Initialize indexs of datasets:./rec_data/train_lmdb
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 108, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 210, in train
    for idx, batch in enumerate(train_dataloader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
RecursionError: DataLoader worker(1) caught RecursionError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 114, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  [Previous line repeated 9973 more times]
  File "/home/aistudio/work/PaddleOCR/ppocr/data/lmdb_dataset.py", line 112, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/__init__.py", line 41, in transform
    data = op(data)
  File "/home/aistudio/work/PaddleOCR/ppocr/data/imaug/operators.py", line 44, in __call__
    img = np.frombuffer(img, dtype='uint8')
RecursionError: maximum recursion depth exceeded in comparison


这个是完整日志

**Comment by Wei-JL** [comment]
有人吗  挺急的  顺便问一下lmdb文件夹里面是只有lock.mdb  和 data.mdb文件吗

**Comment by tink2123** [comment]
请问你的数据是怎么获得的呢？看样本数应该不是官方的数据，可以先减少bs为1，看能否跑起来。
lmdb格式文件是只有 lock.mdb 和 data.mdb 两个文件

**Comment by Wei-JL** [comment]
是写代码转换的 从SimpleDataSet  转的LMDB

**Comment by Wei-JL** [comment]
import lmdb
import cv2
import numpy as np
import os

OUT_PATH = 'work/PaddleOCR/rec_data/test_lmdb'
IN_PATH = 'work/PaddleOCR/rec_data/rec_gt_test.txt'
PREFIX = 'work/PaddleOCR/rec_data/'


def checkImageIsValid(imageBin):
    if imageBin is None:
        return False
    try:
        imageBuf = np.frombuffer(imageBin, dtype=np.uint8)
        img = cv2.imdecode(imageBuf, cv2.IMREAD_GRAYSCALE)
        imgH, imgW = img.shape[0], img.shape[1]
    except:
        return False
    else:
        if imgH * imgW == 0:
            return False
    return True


def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            txn.put(k.encode(), str(v).encode())


def createDataset(outputPath, imagePathList, labelList, lexiconList=None, checkValid=True):
    """
    Create LMDB dataset for CRNN training.
    ARGS:
        outputPath    : LMDB output path
        imagePathList : list of image path
        labelList     : list of corresponding groundtruth texts
        lexiconList   : (optional) list of lexicon lists
        checkValid    : if true, check the validity of every image
    """
    assert (len(imagePathList) == len(labelList))
    nSamples = len(imagePathList)
    env = lmdb.open(outputPath, map_size=109951162777)
    cache = {}
    cnt = 1
    for i in range(nSamples):
        imagePath = os.path.join(PREFIX, imagePathList[i]).split()[0].replace('\n', '').replace('\r\n', '')
        print(imagePath)
        label = ''.join(labelList[i])
        print(label)
        # if not os.path.exists(imagePath):
        #     print('%s does not exist' % imagePath)
        #     continue

        with open(imagePath, 'rb') as f:
            imageBin = f.read()

        if checkValid:
            if not checkImageIsValid(imageBin):
                print('%s is not a valid image' % imagePath)
                continue
        imageKey = 'image-%09d' % cnt
        labelKey = 'label-%09d' % cnt
        cache[imageKey] = imageBin
        cache[labelKey] = label
        if lexiconList:
            lexiconKey = 'lexicon-%09d' % cnt
            cache[lexiconKey] = ' '.join(lexiconList[i])
        if cnt % 996 == 0:
            writeCache(env, cache)
            cache = {}
            print('Written %d / %d' % (cnt, nSamples))
        cnt += 1
        print(cnt)
    nSamples = cnt - 1
    cache['num-samples'] = str(nSamples)
    writeCache(env, cache)
    print('Created dataset with %d samples' % nSamples)


if __name__ == '__main__':
    outputPath = OUT_PATH
    if not os.path.exists(OUT_PATH):
        os.mkdir(OUT_PATH)
    imgdata = open(IN_PATH)
    imagePathList = list(imgdata)

    labelList = []
    for line in imagePathList:
        word = line.split()[1]
        labelList.append(word)
    createDataset(outputPath, imagePathList, labelList)

数据就是  txt的例如第一行是: train\00001.jpg    m    这种类型  你们肯定知道   然后用这代码转的 是不是有问题呢

**Comment by Wei-JL** [comment]
`import lmdb
import cv2
import numpy as np
import os

OUT_PATH = 'work/PaddleOCR/rec_data/test_lmdb'
IN_PATH = 'work/PaddleOCR/rec_data/rec_gt_test.txt'
PREFIX = 'work/PaddleOCR/rec_data/'


def checkImageIsValid(imageBin):
    if imageBin is None:
        return False
    try:
        imageBuf = np.frombuffer(imageBin, dtype=np.uint8)
        img = cv2.imdecode(imageBuf, cv2.IMREAD_GRAYSCALE)
        imgH, imgW = img.shape[0], img.shape[1]
    except:
        return False
    else:
        if imgH * imgW == 0:
            return False
    return True


def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            txn.put(k.encode(), str(v).encode())


def createDataset(outputPath, imagePathList, labelList, lexiconList=None, checkValid=True):
    """
    Create LMDB dataset for CRNN training.
    ARGS:
        outputPath    : LMDB output path
        imagePathList : list of image path
        labelList     : list of corresponding groundtruth texts
        lexiconList   : (optional) list of lexicon lists
        checkValid    : if true, check the validity of every image
    """
    assert (len(imagePathList) == len(labelList))
    nSamples = len(imagePathList)
    env = lmdb.open(outputPath, map_size=109951162777)
    cache = {}
    cnt = 1
    for i in range(nSamples):
        imagePath = os.path.join(PREFIX, imagePathList[i]).split()[0].replace('\n', '').replace('\r\n', '')
        print(imagePath)
        label = ''.join(labelList[i])
        print(label)
        # if not os.path.exists(imagePath):
        #     print('%s does not exist' % imagePath)
        #     continue

        with open(imagePath, 'rb') as f:
            imageBin = f.read()

        if checkValid:
            if not checkImageIsValid(imageBin):
                print('%s is not a valid image' % imagePath)
                continue
        imageKey = 'image-%09d' % cnt
        labelKey = 'label-%09d' % cnt
        cache[imageKey] = imageBin
        cache[labelKey] = label
        if lexiconList:
            lexiconKey = 'lexicon-%09d' % cnt
            cache[lexiconKey] = ' '.join(lexiconList[i])
        if cnt % 996 == 0:
            writeCache(env, cache)
            cache = {}
            print('Written %d / %d' % (cnt, nSamples))
        cnt += 1
        print(cnt)
    nSamples = cnt - 1
    cache['num-samples'] = str(nSamples)
    writeCache(env, cache)
    print('Created dataset with %d samples' % nSamples)


if __name__ == '__main__':
    outputPath = OUT_PATH
    if not os.path.exists(OUT_PATH):
        os.mkdir(OUT_PATH)
    imgdata = open(IN_PATH)
    imagePathList = list(imgdata)

    labelList = []
    for line in imagePathList:
        word = line.split()[1]
        labelList.append(word)
    createDataset(outputPath, imagePathList, labelList)

  `
数据就是  txt的例如第一行是: train\00001.jpg    m    这种类型  你们肯定知道   然后用这代码转的 是不是有问题呢

**Comment by Wei-JL** [comment]
`
import lmdb
import cv2
import numpy as np
import os

OUT_PATH = 'work/PaddleOCR/rec_data/test_lmdb'
IN_PATH = 'work/PaddleOCR/rec_data/rec_gt_test.txt'
PREFIX = 'work/PaddleOCR/rec_data/'


def checkImageIsValid(imageBin):
    if imageBin is None:
        return False
    try:
        imageBuf = np.frombuffer(imageBin, dtype=np.uint8)
        img = cv2.imdecode(imageBuf, cv2.IMREAD_GRAYSCALE)
        imgH, imgW = img.shape[0], img.shape[1]
    except:
        return False
    else:
        if imgH * imgW == 0:
            return False
    return True


def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            txn.put(k.encode(), str(v).encode())


def createDataset(outputPath, imagePathList, labelList, lexiconList=None, checkValid=True):
    """
    Create LMDB dataset for CRNN training.
    ARGS:
        outputPath    : LMDB output path
        imagePathList : list of image path
        labelList     : list of corresponding groundtruth texts
        lexiconList   : (optional) list of lexicon lists
        checkValid    : if true, check the validity of every image
    """
    assert (len(imagePathList) == len(labelList))
    nSamples = len(imagePathList)
    env = lmdb.open(outputPath, map_size=109951162777)
    cache = {}
    cnt = 1
    for i in range(nSamples):
        imagePath = os.path.join(PREFIX, imagePathList[i]).split()[0].replace('\n', '').replace('\r\n', '')
        print(imagePath)
        label = ''.join(labelList[i])
        print(label)

        with open(imagePath, 'rb') as f:
            imageBin = f.read()

        if checkValid:
            if not checkImageIsValid(imageBin):
                print('%s is not a valid image' % imagePath)
                continue
        imageKey = 'image-%09d' % cnt
        labelKey = 'label-%09d' % cnt
        cache[imageKey] = imageBin
        cache[labelKey] = label
        if lexiconList:
            lexiconKey = 'lexicon-%09d' % cnt
            cache[lexiconKey] = ' '.join(lexiconList[i])
        if cnt % 996 == 0:
            writeCache(env, cache)
            cache = {}
            print('Written %d / %d' % (cnt, nSamples))
        cnt += 1
        print(cnt)
    nSamples = cnt - 1
    cache['num-samples'] = str(nSamples)
    writeCache(env, cache)
    print('Created dataset with %d samples' % nSamples)


if __name__ == '__main__':
    outputPath = OUT_PATH
    if not os.path.exists(OUT_PATH):
        os.mkdir(OUT_PATH)
    imgdata = open(IN_PATH)
    imagePathList = list(imgdata)

    labelList = []
    for line in imagePathList:
        word = line.split()[1]
        labelList.append(word)
    createDataset(outputPath, imagePathList, labelList)

`

数据就是  txt的例如第一行是: train\00001.jpg    m    这种类型  你们肯定知道   然后用这代码转的 是不是有问题呢

**Comment by Wei-JL** [comment]
[代码.txt](https://github.com/PaddlePaddle/PaddleOCR/files/7229187/default.txt)

代码如上
数据就是  txt的例如第一行是: train\00001.jpg    m    这种类型  你们肯定知道   然后用这代码转的 是不是有问题呢

**Comment by Wei-JL** [comment]
> @Wei-JL 你解决了么？同问啊

https://blog.csdn.net/qq_37700257/article/details/120411636
可以参考这个
