### ISSUE TITLE
IndexError: list index out of range in OCR

### ISSUE THREAD

**Issue by felixgao** [PaddlePaddle/PaddleOCR#4198]
I am wrapping my application in FastAPI and in OCR function after passing in a numpy arrow it throws the following exception.

```
Traceback (most recent call last):
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/Users/ggao/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ggao/github/opensource/paddle-paddle/main.py", line 86, in process_ocr_overlay
    _, processed_img =  recognizer.recognize(image)
  File "/Users/ggao/github/opensource/paddle-paddle/ocr/recognizer.py", line 21, in recognize
    result = ocr.ocr(img_arr, cls=True)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 350, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/paddleocr/tools/infer/predict_system.py", line 80, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/paddleocr/tools/infer/predict_rec.py", line 263, in __call__
    rec_result = self.postprocess_op(preds)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/Users/ggao/github/opensource/paddle-paddle/.venv/lib/python3.8/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range
```

The code is written as 

```python
ocr = PaddleOCR(
    use_angle_cls=True,  # Whether to load classification model
    lang="en", 
    rec_char_type="en",
    use_gpu=False)


def recognize(img):
    """img is a PIL Image."""
    img_arr = np.array(img)
    logging.info(f"image shape = {img_arr.shape}")
    result = ocr.ocr(img_arr, cls=True)
    
    if result is not None and len(result) > 0:
        boxes = [line[0] for line in result]
        txts = [line[1][0] for line in result]
        scores = [line[1][1] for line in result]
        overlayed = draw_ocr(
            img, boxes, txts, scores, font_path="./fonts/simfang.ttf"
        )
        return result, overlayed

    return result, ""
```

The image I used as an example is 
![make-a-fake-w2-form](https://user-images.githubusercontent.com/1153820/134979844-c0a28d35-32cc-42e0-927f-2a48367210f3.jpeg)

**Comment by tink2123** [comment]
Try to modify the code to:

```
ocr = PaddleOCR(
    use_angle_cls=True,  # Whether to load classification model
    lang="en", 
    use_gpu=False)
```

No need to define rec_char_type separately，FastAPI will set the dictionary itself according to the `lang`
