### ISSUE TITLE
paddlepaddle2.1开启enable_mkldnn报错

### ISSUE THREAD

**Issue by sunshine2176** [PaddlePaddle/PaddleOCR#4212]
版本：paddlepaddle==2.1.2
配置: Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='ch_ppocr_server_v2.0_det_infer', drop_score=0.5, enable_mkldnn=True, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='ch_ppocr_server_v2.0_rec_infer', use_angle_cls=True, use_dilation=False, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
报错内容:
`Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mac/project/pyworkspace/PaddleOCR/study.py", line 4, in <module>
    ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False, det_model_dir='ch_ppocr_server_v2.0_det_infer',
  File "/Users/mac/project/pyworkspace/PaddleOCR/paddleocr.py", line 347, in __init__
    super().__init__(postprocess_params)
  File "/Users/mac/project/pyworkspace/PaddleOCR/tools/infer/predict_system.py", line 42, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/Users/mac/project/pyworkspace/PaddleOCR/tools/infer/predict_det.py", line 100, in __init__
    self.predictor, self.input_tensor, self.output_tensors = utility.create_predictor(
  File "/Users/mac/project/pyworkspace/PaddleOCR/tools/infer/utility.py", line 148, in create_predictor
    config.set_mkldnn_cache_capacity(10)
AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'set_mkldnn_cache_capacity'
`

**Comment by Gmgge** [comment]
建议升级ppocr的版本，最新的版本没有问题。

**Comment by sunshine2176** [comment]
> 建议升级ppocr的版本，最新的版本没有问题。

已升级最新版本ppoce，还是报相同错误

![image](https://user-images.githubusercontent.com/5172675/135187787-fc0ea6ff-a393-4838-8e2d-0ce1d5c39008.png)

**Comment by LDOUBLEV** [comment]
MAC上无法用mkldnn
