### ISSUE TITLE
使用表格的预训练模型报错

### ISSUE THREAD

**Issue by FangLi1** [PaddlePaddle/PaddleOCR#4223]
日志如下：
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 108, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/data/fang_li/code/PaddleOCR/tools/program.py", line 223, in train
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 260, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 367, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 775, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 597, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if p[0].trainable])
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 249, in _create_accumulators
    self._add_moments_pows(p)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 216, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 516, in _add_accumulator
    var.set_value(self._accumulators_holder[var_name])
  File "<decorator-gen-113>", line 2, in set_value
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/data/fang_li/code/Paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 125, in set_value
    self.name, self_tensor_np.shape, value_np.shape)
AssertionError: Variable Shape not match, Variable [ conv3_expand_weights_moment1_0 ] need tensor with shape (72, 16, 1, 1) but load set tensor with shape (64, 16, 1, 1)
INFO 2021-09-29 12:31:51,059 launch_utils.py:307] terminate all the procs
ERROR 2021-09-29 12:31:51,059 launch_utils.py:545] ABORT!!! Out of all 8 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2021-09-29 12:31:54,063 launch_utils.py:307] terminate all the procs

使用的预训练模型就是en_ppocr_mobile_v2.0_table_structure，配置也是表格结构的默认配置table_mv3.yml

**Comment by FangLi1** [comment]
出现了tensor维度不匹配的问题，为什么？使用的都是默认的配置。。。
