### ISSUE TITLE
list index out of range, EAST det

### ISSUE THREAD

**Issue by quanmou** [PaddlePaddle/PaddleOCR#4276]
I was trying to use east model for text detection but i was getting list index out of range error
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 240, in <module>
    res = text_detector(img)
  File "tools/infer/predict_det.py", line 204, in __call__
    preds['f_score'] = outputs[1]
IndexError: list index out of range

The branch I used is release/2.2
I already add the parameter "--det_algorithm". 
Below is my command line:
python3 tools/infer/predict_det.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="/Users/apple/Downloads/det_mv3_east" --det_algorithm="EAST"
The "det_mv3_east" model is transformed by export_model.py

**Comment by quanmou** [comment]
当时想测试下EAST效果来着
