### ISSUE TITLE
pyinstaller 打包paddleocr报错

### ISSUE THREAD

**Issue by liu100286** [PaddlePaddle/PaddleOCR#4299]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "i:\mypython\liaoyun\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddleocr\__init__.py", line 15, in <module>
  File "i:\mypython\liaoyun\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paddleocr\paddleocr.py", line 27, in <module>
ModuleNotFoundError: No module named 'tools'
[2432] Failed to execute script main

**Comment by latawangzi** [comment]
把tools文件夹考到打包目录下试没试？

**Comment by Atomadeus** [comment]
得用多文件打包，而且得不断地测试，缺少哪个模块或DLL文件就得从site-packages复制到可执行文件所在的目录下，或者直接把整个虚拟环境下的第三方模块都复制过来。
