### ISSUE TITLE
pdserving在ubuntu部署时输出的log.txt报错

### ISSUE THREAD

**Issue by lidapengpeng** [PaddlePaddle/PaddleOCR#4341]
我将web_service.py文件中config.yaml路径改为绝对路径也不对，希望大佬帮忙看一下，同时也试了unset https_proxy
unset http_proxy，没有用，错误代码如下：
更多信息：
模型为自己训练的det（SAST） rec（EN_Number_Lite）模型
对应的depoly下面的配置也都修改了

`Traceback (most recent call last):
  File "web_service.py", line 159, in <module>
    uci_service.prepare_pipeline_config("/home/dapeng/PaddleOCR/deploy/pdserving/config.yml")
  File "/home/dapeng/.local/lib/python3.7/site-packages/paddle_serving_server/web_service.py", line 65, in prepare_pipeline_config
    self._server.prepare_server(yaml_file)
  File "/home/dapeng/.local/lib/python3.7/site-packages/paddle_serving_server/pipeline/pipeline_server.py", line 172, in prepare_server
    yml_file=yml_file, yml_dict=yml_dict)
  File "/home/dapeng/.local/lib/python3.7/site-packages/paddle_serving_server/pipeline/pipeline_server.py", line 344, in load_server_yaml_conf
    conf = yaml.load(f.read())
TypeError: load() missing 1 required positional argument: 'Loader'`

**Comment by raghavzns** [comment]
我面临同样的问题。 你能解决吗？

**Comment by raghavzns** [comment]
Solved -->

pip3 install pyyaml==5.4.1
