### ISSUE TITLE
predict_table 报错

### ISSUE THREAD

**Issue by harryliuy** [PaddlePaddle/PaddleOCR#4343]
predict_system检测到表格，region.type == 'Table'的时候
或者直接用predict_table做识别都会报错

[2021/10/15 13:46:41] root DEBUG: dt_boxes num : 91, elapse : 0.6981337070465088
Traceback (most recent call last):
  File "E:\ml\PaddleOCR\ppstructure\table\predict_table.py", line 224, in <module>
    main(args)
  File "E:\ml\PaddleOCR\ppstructure\table\predict_table.py", line 200, in main
    pred_html = text_sys(img)
  File "E:\ml\PaddleOCR\ppstructure\table\predict_table.py", line 91, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "E:\ml\PaddleOCR\tools\infer\predict_rec.py", line 263, in __call__
    rec_result = self.postprocess_op(preds)
  File "E:\ml\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 117, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "E:\ml\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 87, in decode
    char_list.append(self.character[int(text_index[batch_idx][
IndexError: list index out of range

**Comment by versusniubility** [comment]
后来是怎么解决的呀

**Comment by Jiangyangya** [comment]
楼主这个问题解决了吗？我也遇到了，是不是代码需要改啊
