### ISSUE TITLE
GPU 利用率低，有什么办法改善？

### ISSUE THREAD

**Issue by ddz-mark** [PaddlePaddle/PaddleOCR#4353]
训练时的指标： 
batch_size = 960、print_batch_step=3
epoch: [3/100], iter: 594, lr: 0.000998, loss: 5.181252, acc: 0.655729, norm_edit_dis: 0.869380, reader_cost: 0.02042 s, batch_cost: 1.83910 s, samples: 2880, ips: 521.99307

显卡的使用情况：
![image](https://user-images.githubusercontent.com/18033495/137465464-372d6110-404f-4dc6-a19a-791541aef6cb.png)

请问 GPU 使用率一直在 40% 以下，这种情况怎么改善？

**Comment by WenmuZhou** [comment]
调大配置文件里的num_workers

**Comment by ddz-mark** [comment]
num_workers 从8调到16，发现速度并没有提升，反而出现了问题：
Traceback (most recent call last):
  File "tools/train.py", line 144, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 121, in main
    eval_class, pre_best_model_dict, logger, vdl_writer,eval_dataloader_length)
  File "/datasetocr/dudaizhong/paddleocr/tools/program.py", line 250, in train
    post_result = post_process_class(preds, batch[1])
  File "/datasetocr/dudaizhong/paddleocr/ppocr/postprocess/rec_postprocess.py", line 115, in __call__
    preds_idx = preds.argmax(axis=2)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 28858) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)
