### ISSUE TITLE
serving 部署pdocr，启动web_server报错

### ISSUE THREAD

**Issue by MrTsien** [PaddlePaddle/PaddleOCR#4361]
报错信息
λ 0ddc0e43818f /home/PaddleOCR/deploy/pdserving {release/2.3} python3 web_service.py &>log.txt &
[3] 769
λ 0ddc0e43818f /home/PaddleOCR/deploy/pdserving {release/2.3} tail -f log.txt 
Traceback (most recent call last):
  File "web_service.py", line 159, in <module>
    uci_service.prepare_pipeline_config("config.yml")
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/web_service.py", line 63, in prepare_pipeline_config
    self._server.prepare_server(yaml_file)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/pipeline_server.py", line 170, in prepare_server
    yml_file=yml_file, yml_dict=yml_dict)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/pipeline_server.py", line 342, in load_server_yaml_conf
    conf = yaml.load(f.read())
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by MrTsien** [comment]
pip install pyyaml==5.4.1
解决

**Comment by MrTsien** [comment]
pip install pyyaml==5.4.1
