### ISSUE TITLE
用Pyinstaller构建可执行程序 No module name 'tools'

### ISSUE THREAD

**Issue by a497134710** [PaddlePaddle/PaddleOCR#4390]
Code:
![image](https://user-images.githubusercontent.com/32241324/137903982-9fcdfa33-896b-4775-a3ed-60c48dd32402.png)

pyinstaller -F test_paddleocr.py
(store_scan) [root@localhost dist]# ./test_paddleocr 
Traceback (most recent call last):
  File "test_paddleocr.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "__init__.py", line 15, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "paddleocr.py", line 26, in <module>
ModuleNotFoundError: No module named 'tools'
[4301] Failed to execute script 'test_paddleocr' due to unhandled exception!

增加pyinstaller的hook:
![image](https://user-images.githubusercontent.com/32241324/137904388-92988fc7-84f3-4234-9924-29cfff56849a.png)
但是还是会出现相同的问题, 导包无效

老哥能帮忙解决一下这个问题吗？

**Comment by xuri422** [comment]
这是一个好问题，为什么却一直没人解决呢？

**Comment by xuri422** [comment]
> 可以设置一下python的环境变量 在PaddleOCR目录下： export PYTHONPATH=./

请问这个在windows下面如何操作？
