### ISSUE TITLE
 Failed to parse program_desc from binary string

### ISSUE THREAD

**Issue by Jitesh4389** [PaddlePaddle/PaddleOCR#4394]
Traceback (most recent call last):
  File "module.py", line 130, in <module>
    ocr = OCRRec()
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddlehub/module/module.py", line 122, in __new__
    directory=directory, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddlehub/module/module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/home/jitesh/anaconda3/envs/webservice/lib/python3.6/site-packages/paddlehub/module/module.py", line 146, in __init__
    self._initialize(**kwargs)
  File "/home/jitesh/Desktop/Web_Services/PaddleOCR_2.3/ocr_rec/module.py", line 51, in _initialize
    self.text_recognizer = TextRecognizer(cfg)
  File "./tools/infer/predict_rec.py", line 66, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "./tools/infer/utility.py", line 278, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:104)

**Comment by Jitesh4389** [comment]
how to solve this issue

**Comment by qinhuangdaoStation** [comment]
怎么解决这个问题呀？

**Comment by dongdongzi** [comment]
我也遇到了这个问题，InvalidArgumentError: Failed to parse program_desc from binary string. 大家有解决的吗
