### ISSUE TITLE
使用GPU运行报错

### ISSUE THREAD

**Issue by hhhhhhogan** [PaddlePaddle/PaddleOCR#4417]
我的系统为win10，python版本3.8.8,cuda为10.2，paddle版本为paddlepaddle-gpu 2.1.3，运行fluid.install_check.run_check()没有问题。可是使用gpu模式，运行OCR示例代码报错，cpu模式运行没问题。运行的模型是v2.0系列的检测与识别模型

示例代码如下：
![Uploading image.png…]()

报错内容如下：
Traceback (most recent call last):
  File "D:/project2021/PaddleOCR/test.py", line 10, in <module>
    result = ocr.ocr(img_path, cls=True)
  File "D:\project2021\PaddleOCR\paddleocr.py", line 343, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "D:\project2021\PaddleOCR\tools\infer\predict_system.py", line 60, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "D:\project2021\PaddleOCR\tools\infer\predict_det.py", line 195, in __call__
    self.predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 75, in <module>
      main()
    File "tools/export_model.py", line 70, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
      concrete_program, _ = self.get_concrete_program(*input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 77, in forward
      x = self.head(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/heads/det_db_head.py", line 121, in forward
      shrink_maps = self.binarize(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/heads/det_db_head.py", line 89, in forward
      x = self.conv_bn2(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 1379, in forward
      type="batch_norm", inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
      stop_gradient=stop_gradient)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at C:/home/workspace/Paddle_release/paddle/fluid/operators/batch_norm_op.cu:372)
      [operator < batch_norm > error]

请问如何解决？？

**Comment by Evezerest** [comment]
环境问题 cuda cudnn版本是多少那
