### ISSUE TITLE
导出识别模型时报错，训练没问题

### ISSUE THREAD

**Issue by haoyunjixiang** [PaddlePaddle/PaddleOCR#4534]
paddle2.1.0   Ubuntu 18.0.4  Python 3.6  报错内容如下：

Traceback (most recent call last):
  File "tools/export_model.py", line 95, in <module>
    main()
  File "tools/export_model.py", line 90, in main
    paddle.jit.save(model, save_path)
  File "<decorator-gen-67>", line 2, in save
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/tmp/tmpbu5i_rkt.py", line 78, in forward
	false_fn_6, (data, self, x), (data, self, x), (fake_HR, x))
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpbu5i_rkt.py", line 65, in false_fn_6
	false_fn_4, (x,), (x,), (x,))
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/yang/Documents/demo/IntelOCR/ppocr/modeling/architectures/base_model.py", line 110, in forward (* user code *)
	x = self.neck(x)
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/home/yang/Documents/demo/IntelOCR/ppocr/modeling/necks/rnn.py", line 89, in forward (* user code *)
	x = self.encoder_reshape(x)
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpn30p1ftr.py", line 17, in forward
	paddle.jit.dy2static.convert_assert(H == 1)
    File "/home/yang/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 447, in convert_assert
	assert cond, message
    AssertionError

**Comment by tink2123** [comment]
请问是在转换哪个模型时报错呢？方便提供一下命令吗
