### ISSUE TITLE
训练时找不到训练集图像文件夹

### ISSUE THREAD

**Issue by JawerZ** [PaddlePaddle/PaddleOCR#462]
开始训练后出现
`does not exist!:40,307-INFO: ./train_data/` 
我的yml配置的是 `img_set_dir: ./train_data`
训练集图像文件夹也放在train_data下
怎样解决这个问题

**Comment by littletomatodonkey** [comment]
以db检测训练为例，配置的*reader.yaml如下，需要查看下你的reader yaml文件中的路径是否正确
![image](https://user-images.githubusercontent.com/14270174/89030955-132b0c00-d364-11ea-9498-5bdb56798bb8.png)

**Comment by JawerZ** [comment]
我的reader.yml是这样的

目录结构是这样的

训练集图片放在train文件夹里
我这样写路径会有问题吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上8:36
收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;;
抄送:&nbsp;"G."<790899040@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 训练时找不到训练集图像文件夹 (#462)





 
以db检测训练为例，配置的*reader.yaml如下，需要查看下你的reader yaml文件中的路径是否正确

**Comment by littletomatodonkey** [comment]
![image](https://user-images.githubusercontent.com/14270174/89097289-3f9c6200-d410-11ea-8afb-7dbfc866ec54.png)

你的内容好像没有上传成功？我这边看不到具体内容

**Comment by xialei2821212670** [comment]
![image](https://user-images.githubusercontent.com/57654726/89097532-52b03180-d412-11ea-82ea-aeb3714af254.png)

![image](https://user-images.githubusercontent.com/57654726/89097601-ec77de80-d412-11ea-917c-8adf79fb597a.png)
我也是这个问题
![image](https://user-images.githubusercontent.com/57654726/89097615-074a5300-d413-11ea-92ad-933078146f9c.png)
路径好像没有问题，是因为标签没有\t？
![image](https://user-images.githubusercontent.com/57654726/89097631-32cd3d80-d413-11ea-9a5e-66ffb6c7a3f9.png)

**Comment by JawerZ** [comment]
> 我的reader.yml是这样的 目录结构是这样的 训练集图片放在train文件夹里 我这样写路径会有问题吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleOCR" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月31日(星期五) 晚上8:36 收件人:&nbsp;"PaddlePaddle/PaddleOCR"<PaddleOCR@noreply.github.com&gt;; 抄送:&nbsp;"G."<790899040@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 训练时找不到训练集图像文件夹 (#462) 以db检测训练为例，配置的*reader.yaml如下，需要查看下你的reader yaml文件中的路径是否正确 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

> 
![image](https://user-images.githubusercontent.com/59463796/89136241-425c9b80-d565-11ea-90f4-f73af8ba70bc.png)
![image](https://user-images.githubusercontent.com/59463796/89136256-50aab780-d565-11ea-8573-1c346e110d21.png)

**Comment by littletomatodonkey** [comment]
训练数据格式可以参考这里：
https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/recognition.md
图片路径和标注需要用`\t`隔开

**Comment by JawerZ** [comment]
> ![image](https://user-images.githubusercontent.com/14270174/89097289-3f9c6200-d410-11ea-8afb-7dbfc866ec54.png)
> 
> 你的内容好像没有上传成功？我这边看不到具体内容

![image](https://user-images.githubusercontent.com/59463796/89136458-784e4f80-d566-11ea-9bd1-a1ba957ab9aa.png)
![image](https://user-images.githubusercontent.com/59463796/89136467-7edcc700-d566-11ea-991b-f13a8947c499.png)
![image](https://user-images.githubusercontent.com/59463796/89136514-b77ca080-d566-11ea-8864-859479efe8c7.png)

**Comment by littletomatodonkey** [comment]
你好，标注文件这样写的话，需要保证训练集图片在test文件夹下

**Comment by JawerZ** [comment]
> 你好，标注文件这样写的话，需要保证训练集图片在test文件夹下

我更改了我的目录结构  可以读取到文件夹了
但是报异常
`2020-08-03 09:51:34,347-WARNING: Your reader has raised an exception!
C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 96, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "tools\..\tools\program.py", line 250, in train_eval_det_run
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1157, in __thread_main__
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1137, in __thread_main__
    for tensors in self._tensor_reader():
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1207, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "tools\..\ppocr\data\det\dataset_traversal.py", line 59, in batch_iter_reader
    for outs in sample_iter_reader():
  File "tools\..\ppocr\data\det\dataset_traversal.py", line 52, in sample_iter_reader
    outs = self.process(label_infor)
  File "tools\..\ppocr\data\det\east_process.py", line 417, in __call__
    infor = self.convert_label_infor(label_infor)
  File "tools\..\ppocr\data\det\east_process.py", line 57, in convert_label_infor
    label = json.loads(substr[1])
IndexError: list index out of range
    return_numpy=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.
------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1079, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 977, in __init__
    self._init_non_iterable()
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "tools\..\ppocr\modeling\architectures\det_model.py", line 104, in create_feed
    iterable=False)
  File "tools\..\ppocr\modeling\architectures\det_model.py", line 117, in __call__
    image, labels, loader = self.create_feed(mode)
  File "tools\..\tools\program.py", line 175, in build
    dataloader, outputs = model(mode=mode)
  File "tools/train.py", line 50, in main
    config, train_program, startup_program, mode='train')
  File "tools/train.py", line 121, in <module>
    main()
----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.3\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
`
请问这是什么原因

**Comment by littletomatodonkey** [comment]
标注文件的图片路径和标注信息用`\t`隔开，根据你这边的报错信息，应该是标注文件不符合格式规范导致的，可以在这里打印下substr的内容看下是否符合预期
https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/ppocr/data/det/east_process.py#L54

![image](https://user-images.githubusercontent.com/14270174/89139510-73db6400-d571-11ea-8bfa-1c566757ddb2.png)

**Comment by JawerZ** [comment]
> 标注文件的图片路径和标注信息用`\t`隔开，根据你这边的报错信息，应该是标注文件不符合格式规范导致的，可以在这里打印下substr的内容看下是否符合预期
> https://github.com/PaddlePaddle/PaddleOCR/blob/06b943f91adb3e0be940d63da411b79bed106ac8/ppocr/data/det/east_process.py#L54
> 
> ![image](https://user-images.githubusercontent.com/14270174/89139510-73db6400-d571-11ea-8bfa-1c566757ddb2.png)

已解决 原因是标准文本末尾多了一行空行  万分感谢！

**Comment by littletomatodonkey** [comment]
好的，客气~
