### ISSUE TITLE
运行export_model.py报错：ValueError: All elements in ``shape`` must be positive when it's a list or tuple

### ISSUE THREAD

**Issue by gsx1378** [PaddlePaddle/PaddleOCR#4641]
当我训练完表格识别模型后，使用export_model.py去导出模型报错如题所示。
1.镜像文件：registry.baidubce.com/paddlepaddle/paddle：2.0.2-gpu-cuda10.0-cudnn7
2.执行命令：python3.6 tools/export_model.py -c configs/table/table_mv3.yml 
　　　　　　　　　　　　　　　　　　　　　-o Global.pretrained_model=./output/best_accuracy/best_accuracy 
　　　　　　　　　　　　　　　　　　　　　     Global.save_inference_dir=./output/table_m3/
3.报错信息：
`[2021/11/12 07:51:06] root INFO: loaded pretrained_model successful from ./output/best_accuracy/best_accuracy.pdparams
Traceback (most recent call last):
  File "tools/export_model.py", line 123, in <module>
    main()
  File "tools/export_model.py", line 119, in main
    export_single_model(model, arch_config, save_path, logger)
  File "tools/export_model.py", line 74, in export_single_model
    paddle.jit.save(model, save_path)
  File "<decorator-gen-60>", line 2, in save
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 681, in save
    inner_input_spec)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/mnt/guoshouxiang/Projects/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 80, in forward (* user code *)
	x = self.head(x, targets=data)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpdaq6xp8z.py", line 178, in forward
	output, output_hiddens, outputs, structure_probs)))
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/mnt/guoshouxiang/Projects/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 91, in forward (* user code *)
	temp_elem = paddle.zeros(shape=[batch_size], dtype="int32")
    File "/usr/local/lib/python3.6/site-packages/paddle/tensor/creation.py", line 350, in zeros
	return fill_constant(value=0.0, shape=shape, dtype=dtype, name=name)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 708, in fill_constant
	check_shape(shape)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/layers/utils.py", line 375, in check_shape
	"All elements in ``shape`` must be positive when it's a list or tuple"
    ValueError: All elements in ``shape`` must be positive when it's a list or tuple`

**Comment by WenmuZhou** [comment]
使用2.1.3+的paddle版本
