### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#4707]
Paddlepaddle-gui  2.1.3.post112
paddleocr               2.3.0.1
win11
python  3.8.12

数据集是采用 PPOCRLabel 标注的

训练报错

python tools/train.py -c configs/det/det_r50_vd_db.yml

```

binary_maps: 0.099000, reader_cost: 0.03905 s, batch_cost: 0.07030 s, samples: 8, ips: 11.38042
[2021/11/19 22:51:06] root INFO: save model in ./output/det_r50_vd/latest
[2021/11/19 22:51:06] root INFO: Initialize indexs of datasets:['G:/Dbiao/QG_OK/Label.txt']
[2021/11/19 22:51:08] root INFO: epoch: [222/1200], iter: 1990, lr: 0.001000, loss: 1.126220, loss_shrink_maps: 0.505004, loss_threshold_maps: 0.500282, loss_binary_maps: 0.100141, reader_cost: 0.07186 s, batch_cost: 0.13434 s, samples: 16, ips: 11.90980
[2021/11/19 22:51:14] root INFO: save model in ./output/det_r50_vd/latest
[2021/11/19 22:51:14] root INFO: Initialize indexs of datasets:['G:/Dbiao/QG_OK/Label.txt']
[2021/11/19 22:51:16] root INFO: epoch: [223/1200], iter: 2000, lr: 0.001000, loss: 1.163789, loss_shrink_maps: 0.567137, loss_threshold_maps: 0.491938, loss_binary_maps: 0.111735, reader_cost: 0.05780 s, batch_cost: 0.15153 s, samples: 24, ips: 15.83795
eval model::   0%|                                                                                                                    | 0/10 [00:00<?, ?it/s]WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-227:
Traceback (most recent call last):
  File "D:\anaconda3\envs\PaddleOCR\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    self.run()
  File "D:\anaconda3\envs\PaddleOCR\lib\threading.py", line 870, in run
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 106, in main
    self._target(*self._args, **self._kwargs)
program.train(config, train_dataloader, valid_dataloader, device, model,  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop

  File "D:\PaddleOCR\tools\program.py", line 276, in train
    six.reraise(*sys.exc_info())
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\six.py", line 719, in reraise
    cur_metric = eval(
  File "D:\PaddleOCR\tools\program.py", line 362, in eval
    raise value
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop
    for idx, batch in enumerate(valid_dataloader):
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 197, in __next__
        data = self._reader.read_next_var_list()
batch = self._dataset_fetcher.fetch(indices)SystemError
:   File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 117, in fetch
(Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)

    data = self.collate_fn(data)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in default_collate_fn
eval model::   0%|

```

python tools/train.py -c configs/det/ch_PP-OCRv2/ch_PP-OCR_det_cml.yml"

```


[2021/11/19 23:13:00] root INFO: epoch: [142/1200], iter: 1980, lr: 0.001000, loss: 1.101504, loss_shrink_maps: 0.491645, loss_threshold_maps: 0.512899, loss_binary_maps: 0.097691, reader_cost: 0.05155 s, batch_cost: 0.21245 s, samples: 35, ips: 16.47432
[2021/11/19 23:13:04] root INFO: save model in ./output/det_r50_vd/latest
[2021/11/19 23:13:04] root INFO: Initialize indexs of datasets:['G:/Dbiao/QG_OK/Label.txt']
[2021/11/19 23:13:06] root INFO: epoch: [143/1200], iter: 1990, lr: 0.001000, loss: 1.060811, loss_shrink_maps: 0.465352, loss_threshold_maps: 0.528736, loss_binary_maps: 0.094402, reader_cost: 0.03907 s, batch_cost: 0.10467 s, samples: 15, ips: 14.33046
[2021/11/19 23:13:11] root INFO: epoch: [143/1200], iter: 2000, lr: 0.001000, loss: 1.083207, loss_shrink_maps: 0.480454, loss_threshold_maps: 0.518493, loss_binary_maps: 0.096321, reader_cost: 0.03438 s, batch_cost: 0.26088 s, samples: 50, ips: 19.16569
eval model::   0%|                                                                                                                    | 0/15 [00:00<?, ?it/s]WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-147:
Traceback (most recent call last):
  File "D:\anaconda3\envs\PaddleOCR\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "D:\anaconda3\envs\PaddleOCR\lib\threading.py", line 870, in run
  File "tools/train.py", line 131, in <module>
    self._target(*self._args, **self._kwargs)
    main(config, device, logger, vdl_writer)  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop

  File "tools/train.py", line 106, in main
    six.reraise(*sys.exc_info())
program.train(config, train_dataloader, valid_dataloader, device, model,  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\six.py", line 719, in reraise

  File "D:\PaddleOCR\tools\program.py", line 276, in train
        raise valuecur_metric = eval(

  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop
  File "D:\PaddleOCR\tools\program.py", line 362, in eval
    batch = self._dataset_fetcher.fetch(indices)
      File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 117, in fetch
for idx, batch in enumerate(valid_dataloader):
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 197, in __next__
    data = self.collate_fn(data)
      File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in default_collate_fn
data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in <listcomp>

    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
eval model::   0%|                                                                                                                    | 0/15 [00:00<?, ?it/s]


```

```


[2021/11/20 00:23:38] root INFO: epoch: [278/1200], iter: 5000, lr: 0.000888, dila_dbloss_Student_Teacher: 1.666616, dila_dbloss_Student2_Teacher: 1.613388, loss: 6.564206, dml_thrink_maps_0: 0.014159, db_Student_loss_shrink_maps: 0.984684, db_Student_loss_threshold_maps: 0.323593, db_Student_loss_binary_maps: 0.196551, db_Student2_loss_shrink_maps: 0.873661, db_Student2_loss_threshold_maps: 0.317341, db_Student2_loss_binary_maps: 0.174108, reader_cost: 0.09377 s, batch_cost: 0.61704 s, samples: 8, ips: 6.48253
eval model::   0%|                                                                                                                    | 0/19 [00:00<?, ?it/s]WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-282:
Traceback (most recent call last):
  File "D:\anaconda3\envs\PaddleOCR\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
    self.run()  File "tools/train.py", line 131, in <module>

  File "D:\anaconda3\envs\PaddleOCR\lib\threading.py", line 870, in run
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 106, in main
    self._target(*self._args, **self._kwargs)
      File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop
program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\PaddleOCR\tools\program.py", line 276, in train
    six.reraise(*sys.exc_info())
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\six.py", line 719, in reraise
    cur_metric = eval(
  File "D:\PaddleOCR\tools\program.py", line 362, in eval
    raise value
for idx, batch in enumerate(valid_dataloader):  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop

  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 197, in __next__
    batch = self._dataset_fetcher.fetch(indices)
data = self._reader.read_next_var_list()  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 117, in fetch

SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)

    data = self.collate_fn(data)
  File "D:\anaconda3\envs\PaddleOCR\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in default_collate_fn
eval model::   0%|                                                                                                                    | 0/19 [00:00<?, ?it/s]
```

**Comment by littletomatodonkey** [comment]
eval的时候报错了，检查下eval数据和配置看下，
