### ISSUE TITLE
将PaddePaddle框架建立的mnist手写数字例程打包成exe,执行过程中有问题

### ISSUE THREAD

**Issue by gaogaoandduidui** [PaddlePaddle/PaddleOCR#4709]
![image](https://user-images.githubusercontent.com/92768974/142717832-15504ede-2f48-4241-93e3-89f58ff8e41d.png)
Traceback (most recent call last):
  File "15CNN.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\__init__.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\fluid\__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\fluid\framework.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\fluid\core.py", line 68, in <module>
  File "paddle\fluid\core.py", line 49, in <module>
  File "os.py", line 1109, in add_dll_directory
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\15949\\AppData\\Local\\Temp\\_MEI79722\\paddle\\fluid\\..\\libs'
[25444] Failed to execute script '15CNN' due to unhandled exception!

这是怎么回事啊

**Comment by littletomatodonkey** [comment]
这个不太清楚具体的使用环境，可以描述的再清楚一些看下，可以先试下使用英文路径，另外把paddle的路径添加到系统环境变量中试下
