### ISSUE TITLE
SRN是否支持中文识别？

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleOCR#4763]
都是用的自己的数据和字典且不加载预训练模型，英文识别时训练和预测都没有问题，训练中文数据时改配置文件的character_type: ch，训练没有问题，但是
python tools/infer/predict_rec.py --image_dir="C:\data\standalone\own_vehicle_pic\crop_img\0111_16_crop_0.jpg" --rec_model_dir="C:\code\PaddleOCR-release-2.2\project\project\car_plate_
rec\0111_0112_0323\inference\srn" --rec_image_shape="1, 64, 256" --rec_char_type="ch" --rec_algorithm="SRN"，预测时会报错：

Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 305, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_rec.py", line 279, in main
    res = text_recognizer([img])
  File "tools/infer/predict_rec.py", line 261, in __call__
    rec_result = self.postprocess_op(preds)
  File "C:\code\PaddleOCR-release-2.2\ppocr\postprocess\rec_postprocess.py", line 259, in __call__
    pred = np.reshape(pred, [-1, char_num])
  File "<__array_function__ internals>", line 6, in reshape
  File "C:\ProgramData\Anaconda3\envs\PaddleOCR-release-2.2\lib\site-packages\numpy\core\fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\ProgramData\Anaconda3\envs\PaddleOCR-release-2.2\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 1750 into shape (71)

**Comment by Lebron-Harden** [comment]
SRN是支持中文识别的（亲测有效），看你这个报错，是不是字典的维度对不上？可能是最后一个全连接得到预测结果的时候的问题

**Comment by tink2123** [comment]
看起来是纬度没有对上，两个地方可以检查一下：
1. 预测时是否修改了自己的字典路径
2. use_space 这个参数是否和训练的配置文件一致

**Comment by wjrjsdx** [comment]
> 看起来是纬度没有对上，两个地方可以检查一下：
> 
> 1. 预测时是否修改了自己的字典路径
> 2. use_space 这个参数是否和训练的配置文件一致

我自己的问题，预测时没指定字典，现在可以了，效果比crnn+ctc要好，感谢回复
