### ISSUE TITLE
服务器版本部署paddleocr的cpp推理检测或者识别模型，报错”some trt inputs dynamic shape info not set“，

### ISSUE THREAD

**Issue by apple2333cream** [PaddlePaddle/PaddleOCR#4903]
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

**Comment by andyjpaddle** [comment]
请问，检测和识别分别用的是哪个模型？

**Comment by apple2333cream** [comment]
2.2版本的服务器版推理模型

**Comment by prettyocean85** [comment]
我遇到过类似的问题。尝试一下关闭分类是否可以，如果只是分类不用能trt是因为分类模型没有设置SetTRTDynamicShapeInfo，分类需要设置一下min_input_shape = {"x": [1, 3, 48, 10]}
max_input_shape = {"x": [args.rec_batch_num, 3, 48, 2000]}
opt_input_shape = {"x": [args.rec_batch_num, 3, 48, 320]}

**Comment by mokadevcloud** [comment]
Hi, 
I am facing the same error. It's quite strange as TensorRT works fine when I run inference in the main process. But when I try to deploy using TorchServe, which loads paddle ocr TextSystem in a subprocess, I have this error. On the other hand, if I set `use_tensorrt = False`, I don't have any problem, even on TorchServe.

**Comment by mokadevcloud** [comment]
A different error arises when I try to run paddle ocr with TensorRT in a python `threading.Thread`. As the error happens during the execution of compiled C code, it's virtually impossible to debug. Can you please help?

```
E0228 16:16:30.301519 102182 helper.h:111] 3: [executionContext.cpp::setBindingDimensions::926] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::926, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0228 16:16:30.301556 102182 helper.h:111] 3: [executionContext.cpp::getBindingDimensions::978] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::978, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0228 16:16:30.301573 102182 helper.h:111] 3: [executionContext.cpp::getBindingDimensions::978] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::978, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0228 16:16:30.301585 102182 helper.h:111] 3: [executionContext.cpp::getBindingDimensions::978] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::978, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0228 16:16:30.301595 102182 helper.h:111] 3: [executionContext.cpp::getBindingDimensions::978] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::978, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0228 16:16:30.301605 102182 helper.h:111] 3: [executionContext.cpp::getBindingDimensions::978] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::978, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0228 16:16:30.301620 102182 helper.h:111] 3: [executionContext.cpp::enqueueInternal::318] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::318, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
```

followed by 

```
Exception in thread TextSpotterPaddle:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/paddle/env/src/pypes/pypes/lib/pipe.py", line 65, in run
    data = self.process(data)
  File "/home/paddle/lib/pypes/text_spotter_paddle.py", line 60, in process
    texts, boxes = predict_text_ocr([
  File "/home/paddle/env/src/paddleocr/ptools/infer/predict.py", line 123, in predict_text_ocr
    dt_boxes, rec_res = text_sys(img)
  File "/home/paddle/env/src/paddleocr/ptools/infer/predict.py", line 64, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/paddle/env/src/paddleocr/ptools/infer/predict_det.py", line 214, in __call__
    self.predictor.run()
NotImplementedError: In user code:

    File "ptools/export_model.py", line 128, in <module>
      main()
    File "ptools/export_model.py", line 124, in main
      export_single_model(model, arch_config, save_path, logger)
    File "ptools/export_model.py", line 79, in export_single_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-101>", line 2, in save
      
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 743, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpvbw5y0g4.py", line 28, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.use_neck, true_fn_1,
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/paddle/env/src/paddleocr/ppocr/modeling/architectures/base_model.py", line 78, in forward
      x = self.neck(x)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/paddle/env/src/paddleocr/ppocr/modeling/necks/db_fpn.py", line 92, in forward
      out4 = in4 + F.upsample(
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 681, in upsample
      return interpolate(x, size, scale_factor, mode, align_corners, align_mode,
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 472, in interpolate
      helper.append_op(
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/home/paddle/env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    UnimplementedError: Input(X) dimension must be 3, 4 or 5, but got dimension = 0 . (at /paddle/paddle/fluid/operators/interpolate_v2_op.cc:395)
      [operator < nearest_interp_v2 > error]
```

**Comment by TianJian11** [comment]
> 2.2版本的服务器版推理模型

请问该问题解决了么

**Comment by andyjpaddle** [comment]
可以更新一下最新版代码试试
