### ISSUE TITLE
在训练文字检测模型时报错

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#491]
您好，我在训练文字检测模型时，报错了
2020-08-06 09:42:01,789-WARNING: Your reader has raised an exception!
TypeError: float() argument must be a string or a number, not 'list'
但我的标签是按照要求制作的，并且数据类型也都是str，请问应该怎么解决呢？

**Comment by tyy2tyy** [comment]
----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by tyy2tyy** [comment]
2020-08-06 09:58:29,867-WARNING: Your reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/reader/decorator.py", line 572, in queue_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception

TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

**Comment by MissPenguin** [comment]
原始数据能跑起来吗，如果不做任何修改能跑起来，那应该就是数据有问题

**Comment by tyy2tyy** [comment]
原始数据可以跑。我使用的是lvst2019的训练数据，转换格式以后和原始数据的格式一样，但是就跑不起来，也不知道是哪里出问题了。
![捕获](https://user-images.githubusercontent.com/51456283/89495848-bd36e800-d7eb-11ea-87c1-57850792b7ff.PNG)

**Comment by MissPenguin** [comment]
是\t分隔吗，\t后面的label部分是json.dumps的吗

**Comment by tyy2tyy** [comment]
是的，我找到问题所在了，lvst数据中的points有些是有多个的，不止四个，这样就在 wordBBs = np.array(wordBBs, dtype=np.float32)这里出现问题了。我使用的是east算法训练lvst数据，你们给的示例是用db算法，请问能否用east算法训练points的坐标维度不一样的数据呢

**Comment by MissPenguin** [comment]
east只能回归4个点哈，训练弯曲文本效果不好，建议还是用DB，但是DB训练弯曲文本需要点数一致，比如都是12点，要支持多种点数一起训练可能需要修改下代码。另外，预计下周发布SAST，也是支持弯曲文字检测的，到时可以试试。

**Comment by tyy2tyy** [comment]
好的，谢谢
