### ISSUE TITLE
多线程训练报错

### ISSUE THREAD

**Issue by TTMRonald** [PaddlePaddle/PaddleOCR#4940]
你好，我在训练表格结构识别模型的时候，设置`num_workers > 0`就会报错，`num_workers : 0`没有这个报错

训练使用命令：`python3 tools/train.py -c configs/table/table_mv3.yml`
GPU环境信息：单卡`cuda=10.1 cudnn=7.6`
Paddle版本信息：`paddleocr=2.3.0.2  paddlepaddle-gpu=2.1.2.post101`
table_mv3.yml修改内容：只修改`batch_size_per_card: 8`和`use_shared_memory: False`，其他保持默认配置
具体配置：
```
[2021/12/16 10:25:49] root INFO: Architecture : 
[2021/12/16 10:25:49] root INFO:     Backbone : 
[2021/12/16 10:25:49] root INFO:         disable_se : True
[2021/12/16 10:25:49] root INFO:         model_name : small
[2021/12/16 10:25:49] root INFO:         name : MobileNetV3
[2021/12/16 10:25:49] root INFO:         scale : 1.0
[2021/12/16 10:25:49] root INFO:     Head : 
[2021/12/16 10:25:49] root INFO:         hidden_size : 256
[2021/12/16 10:25:49] root INFO:         l2_decay : 1e-05
[2021/12/16 10:25:49] root INFO:         loc_type : 2
[2021/12/16 10:25:49] root INFO:         name : TableAttentionHead
[2021/12/16 10:25:49] root INFO:     algorithm : TableAttn
[2021/12/16 10:25:49] root INFO:     model_type : table
[2021/12/16 10:25:49] root INFO: Eval : 
[2021/12/16 10:25:49] root INFO:     dataset : 
[2021/12/16 10:25:49] root INFO:         data_dir : dataset/PubTabNet/images/val/
[2021/12/16 10:25:49] root INFO:         label_file_path : dataset/PubTabNet/annotations/PubTabNet_2.0.0_val.jsonl
[2021/12/16 10:25:49] root INFO:         name : PubTabDataSet
[2021/12/16 10:25:49] root INFO:         transforms : 
[2021/12/16 10:25:49] root INFO:             DecodeImage : 
[2021/12/16 10:25:49] root INFO:                 channel_first : False
[2021/12/16 10:25:49] root INFO:                 img_mode : BGR
[2021/12/16 10:25:49] root INFO:             ResizeTableImage : 
[2021/12/16 10:25:49] root INFO:                 max_len : 488
[2021/12/16 10:25:49] root INFO:             TableLabelEncode : None
[2021/12/16 10:25:49] root INFO:             NormalizeImage : 
[2021/12/16 10:25:49] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/12/16 10:25:49] root INFO:                 order : hwc
[2021/12/16 10:25:49] root INFO:                 scale : 1./255.
[2021/12/16 10:25:49] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/12/16 10:25:49] root INFO:             PaddingTableImage : None
[2021/12/16 10:25:49] root INFO:             ToCHWImage : None
[2021/12/16 10:25:49] root INFO:             KeepKeys : 
[2021/12/16 10:25:49] root INFO:                 keep_keys : ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
[2021/12/16 10:25:49] root INFO:     loader : 
[2021/12/16 10:25:49] root INFO:         batch_size_per_card : 8
[2021/12/16 10:25:49] root INFO:         drop_last : False
[2021/12/16 10:25:49] root INFO:         num_workers : 1
[2021/12/16 10:25:49] root INFO:         shuffle : False
[2021/12/16 10:25:49] root INFO:         use_shared_memory : False
[2021/12/16 10:25:49] root INFO: Global : 
[2021/12/16 10:25:49] root INFO:     cal_metric_during_train : True
[2021/12/16 10:25:49] root INFO:     character_dict_path : ppocr/utils/dict/table_structure_dict.txt
[2021/12/16 10:25:49] root INFO:     character_type : en
[2021/12/16 10:25:49] root INFO:     checkpoints : None
[2021/12/16 10:25:49] root INFO:     debug : False
[2021/12/16 10:25:49] root INFO:     distributed : False
[2021/12/16 10:25:49] root INFO:     epoch_num : 50
[2021/12/16 10:25:49] root INFO:     eval_batch_step : [0, 800]
[2021/12/16 10:25:49] root INFO:     infer_img : doc/imgs_words/ch/word_1.jpg
[2021/12/16 10:25:49] root INFO:     infer_mode : False
[2021/12/16 10:25:49] root INFO:     log_smooth_window : 20
[2021/12/16 10:25:49] root INFO:     max_cell_num : 500
[2021/12/16 10:25:49] root INFO:     max_elem_length : 500
[2021/12/16 10:25:49] root INFO:     max_text_length : 100
[2021/12/16 10:25:49] root INFO:     pretrained_model : None
[2021/12/16 10:25:49] root INFO:     print_batch_step : 5
[2021/12/16 10:25:49] root INFO:     process_cut_num : 0
[2021/12/16 10:25:49] root INFO:     process_total_num : 0
[2021/12/16 10:25:49] root INFO:     save_epoch_step : 5
[2021/12/16 10:25:49] root INFO:     save_inference_dir : None
[2021/12/16 10:25:49] root INFO:     save_model_dir : ./output/table_mv3_pubtabnet/
[2021/12/16 10:25:49] root INFO:     use_gpu : True
[2021/12/16 10:25:49] root INFO:     use_visualdl : False
[2021/12/16 10:25:49] root INFO: Loss : 
[2021/12/16 10:25:49] root INFO:     loc_weight : 10000.0
[2021/12/16 10:25:49] root INFO:     name : TableAttentionLoss
[2021/12/16 10:25:49] root INFO:     structure_weight : 100.0
[2021/12/16 10:25:49] root INFO: Metric : 
[2021/12/16 10:25:49] root INFO:     main_indicator : acc
[2021/12/16 10:25:49] root INFO:     name : TableMetric
[2021/12/16 10:25:49] root INFO: Optimizer : 
[2021/12/16 10:25:49] root INFO:     beta1 : 0.9
[2021/12/16 10:25:49] root INFO:     beta2 : 0.999
[2021/12/16 10:25:49] root INFO:     clip_norm : 5.0
[2021/12/16 10:25:49] root INFO:     lr : 
[2021/12/16 10:25:49] root INFO:         learning_rate : 0.001
[2021/12/16 10:25:49] root INFO:     name : Adam
[2021/12/16 10:25:49] root INFO:     regularizer : 
[2021/12/16 10:25:49] root INFO:         factor : 0.0
[2021/12/16 10:25:49] root INFO:         name : L2
[2021/12/16 10:25:49] root INFO: PostProcess : 
[2021/12/16 10:25:49] root INFO:     name : TableLabelDecode
[2021/12/16 10:25:49] root INFO: Train : 
[2021/12/16 10:25:49] root INFO:     dataset : 
[2021/12/16 10:25:49] root INFO:         data_dir : dataset/PubTabNet/images/train/
[2021/12/16 10:25:49] root INFO:         label_file_path : dataset/PubTabNet/annotations/PubTabNet_2.0.0_train.jsonl
[2021/12/16 10:25:49] root INFO:         name : PubTabDataSet
[2021/12/16 10:25:49] root INFO:         transforms : 
[2021/12/16 10:25:49] root INFO:             DecodeImage : 
[2021/12/16 10:25:49] root INFO:                 channel_first : False
[2021/12/16 10:25:49] root INFO:                 img_mode : BGR
[2021/12/16 10:25:49] root INFO:             ResizeTableImage : 
[2021/12/16 10:25:49] root INFO:                 max_len : 488
[2021/12/16 10:25:49] root INFO:             TableLabelEncode : None
[2021/12/16 10:25:49] root INFO:             NormalizeImage : 
[2021/12/16 10:25:49] root INFO:                 mean : [0.485, 0.456, 0.406]
[2021/12/16 10:25:49] root INFO:                 order : hwc
[2021/12/16 10:25:49] root INFO:                 scale : 1./255.
[2021/12/16 10:25:49] root INFO:                 std : [0.229, 0.224, 0.225]
[2021/12/16 10:25:49] root INFO:             PaddingTableImage : None
[2021/12/16 10:25:49] root INFO:             ToCHWImage : None
[2021/12/16 10:25:49] root INFO:             KeepKeys : 
[2021/12/16 10:25:49] root INFO:                 keep_keys : ['image', 'structure', 'bbox_list', 'sp_tokens', 'bbox_list_mask']
[2021/12/16 10:25:49] root INFO:     loader : 
[2021/12/16 10:25:49] root INFO:         batch_size_per_card : 4
[2021/12/16 10:25:49] root INFO:         drop_last : True
[2021/12/16 10:25:49] root INFO:         num_workers : 1
[2021/12/16 10:25:49] root INFO:         shuffle : True
[2021/12/16 10:25:49] root INFO:         use_shared_memory : False
```
报错日志：
```
[2021/12/16 10:25:49] root INFO: train with paddle 2.1.2 and device CUDAPlace(0)
[2021/12/16 10:25:49] root INFO: Initialize indexs of datasets:dataset/PubTabNet/annotations/PubTabNet_2.0.0_train.jsonl
[2021/12/16 10:25:56] root INFO: Initialize indexs of datasets:dataset/PubTabNet/annotations/PubTabNet_2.0.0_val.jsonl
W1216 10:25:56.111047 191862 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.1
W1216 10:25:56.120951 191862 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[2021/12/16 10:26:13] root INFO: train dataloader has 125194 iters
[2021/12/16 10:26:13] root INFO: valid dataloader has 2279 iters
[2021/12/16 10:26:13] root INFO: During the training process, after the 0th iteration, an evaluation is run every 800 iterations
[2021/12/16 10:26:13] root INFO: Initialize indexs of datasets:dataset/PubTabNet/annotations/PubTabNet_2.0.0_train.jsonl
Process Process-1:
Traceback (most recent call last):
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 346, in _worker_loop
six.reraise(*sys.exc_info())
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/six.py", line 703, in reraise
raise value
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 265, in _worker_loop
core._set_process_signal_handler()
SystemError: (Fatal) An error occurred while setting handler for Segmentation fault. (at /paddle/paddle/fluid/imperative/data_loader.cc:113)

ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
File "tools/train.py", line 131, in <module>
main(config, device, logger, vdl_writer)
File "tools/train.py", line 108, in main
Exception in thread Thread-1:
Traceback (most recent call last):
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 462, in _get_data
data = self._data_queue.get(timeout=self._timeout)
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/multiprocessing/queues.py", line 105, in get
raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
batch = self._get_data()
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 478, in _get_data
"pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 191961

eval_class, pre_best_model_dict, logger, vdl_writer)
File "/home/jovyan/wangbo/ocr/paddleOCR23/tools/program.py", line 210, in train
for idx, batch in enumerate(train_dataloader):
File "/home/jovyan/my-conda-envs/py36/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
[Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

exit status 1
```

**Comment by littletomatodonkey** [comment]
可能是本地内存资源不足，导致无法开启多进程读取数据

**Comment by TTMRonald** [comment]
> 可能是本地内存资源不足，导致无法开启多进程读取数据

本地内存free还剩200G多，而且后来我单独筛了100条数据来测试，也有同样的问题，基本上刚开始初始化index几秒后就会报这个多进程错误

**Comment by TTMRonald** [comment]
@littletomatodonkey 而且我尝试`num_workers : 0`发现同样在初始化数据index的时候，top查看内存发现RES用了3.2G，但是VIRT会不断增加，直到100多t后会，cpu利用率会基本降为0，表格识别模型训练是不是存在内存泄漏呢？
