### ISSUE TITLE
打开参数cal_metric_during_train会直接报错

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleOCR#4975]
**我是希望边训练边验证的，需要做额外的设置嘛？因为我之前训练的时候，都没有做打开这个参数“cal_metric_during_train”，然后训练过程中也会有评估。但是今天特定看了一下这个参数的意思，字面意思不就是想要边训练边评估的话，不是应该打开这个参数嘛？**

可是！我一打开这个参数，开启训练任务直接就报错了。
报错log如下
[2021/12/20 15:18:07] root INFO: load pretrained model from ['dataset/pre_model/ch_ppocr_mobile_v2.0_det/ch_ppocr_mobile_v2.0_det_train/best_accuracy']
[2021/12/20 15:18:07] root INFO: train dataloader has 535 iters
[2021/12/20 15:18:07] root INFO: valid dataloader has 801 iters
[2021/12/20 15:18:07] root INFO: During the training process, after the 3000th iteration, an evaluation is run every 2000 iterations
[2021/12/20 15:18:07] root INFO: Initialize indexs of datasets:['dataset/tripCard/det_data_12_13/Annotations_split/train/label.list']
shape_list[batch_index]: [[0.3 0.3 0.3 ... 0.3 0.3 0.3]
 [0.3 0.3 0.3 ... 0.3 0.3 0.3]
 [0.3 0.3 0.3 ... 0.3 0.3 0.3]
 ...
 [0.3 0.3 0.3 ... 0.3 0.3 0.3]
 [0.3 0.3 0.3 ... 0.3 0.3 0.3]
 [0.3 0.3 0.3 ... 0.3 0.3 0.3]]
111 batch_index: 0
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/mnt/ssd1/xcq/training_tools/PaddleOCR/tools/program.py", line 235, in train
    post_result = post_process_class(preds, batch[1])
  File "/mnt/ssd1/xcq/training_tools/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 180, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
ValueError: too many values to unpack (expected 4)

**Comment by TinyQi** [comment]
现在我有几个疑问，一是如果我想边训练边评估，标准的操作是怎么操作呢？
二是这个参数如果就是用来开启边训练边评估功能的话，那么我如何解决报错呢？

**Comment by LDOUBLEV** [comment]
cal_metric_during_train 参数是计算当前训练batch数据的精度，
训练检测的时候不用开启这个，如果你想增大评估的频率，可以修改这个参数：https://github.com/PaddlePaddle/PaddleOCR/blob/81ee76ad7f9ff534a0ae5439d2a5259c4263993c/configs/det/det_mv3_db.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9

比如修改为[0, 200]表示从第0次训练迭代开始，接下来每训练迭代200次做一次评估
