### ISSUE TITLE
pyinstaller 打包paddleocr报错ModuleNotFoundError: No module named 'framework_pb2'

### ISSUE THREAD

**Issue by gewenpulan** [PaddlePaddle/PaddleOCR#4997]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.2.1  PaddleOCR：2.3.0.2 问题相关组件/Related components：minPackage                           Version
--------------------------------- -----------
altgraph                          0.17.2
astor                             0.8.1
Babel                             2.9.1
backports.entry-points-selectable 1.1.1
bce-python-sdk                    0.8.64
cachetools                        4.2.4
certifi                           2021.10.8
cfgv                              3.3.1
charset-normalizer                2.0.9
click                             8.0.3
colorama                          0.4.4
cssselect                         1.1.0
cssutils                          2.3.0
cycler                            0.11.0
Cython                            0.29.26
decorator                         5.1.0
distlib                           0.3.4
et-xmlfile                        1.1.0
fasttext                          0.9.1
filelock                          3.4.0
flake8                            4.0.1
Flask                             2.0.2
Flask-Babel                       2.0.0
fonttools                         4.28.5
future                            0.18.2
gast                              0.3.3
identify                          2.4.0
idna                              3.3
imageio                           2.13.4
imgaug                            0.4.0
importlib-metadata                4.2.0
itsdangerous                      2.0.1
Jinja2                            3.0.3
kiwisolver                        1.3.2
lmdb                              1.2.1
lxml                              4.7.1
MarkupSafe                        2.0.1
matplotlib                        3.5.1
mccabe                            0.6.1
networkx                          2.6.3
nodeenv                           1.6.0
numpy                             1.19.3
opencv-contrib-python             4.4.0.46
opencv-python                     4.5.4.60
openpyxl                          3.0.9
packaging                         21.3
paddleocr                         2.3.0.2
paddlepaddle                      2.2.1
pandas                            1.3.5
pefile                            2021.9.3
Pillow                            8.4.0
pip                               21.2.4
platformdirs                      2.4.0
pre-commit                        2.16.0
premailer                         3.10.0
protobuf                          3.19.1
pybind11                          2.8.1
pyclipper                         1.3.0.post2
pycodestyle                       2.8.0
pycryptodome                      3.12.0
pyflakes                          2.4.0
pyinstaller                       4.7
pyinstaller-hooks-contrib         2021.4
pyparsing                         3.0.6
python-dateutil                   2.8.2
python-Levenshtein                0.12.2
pytz                              2021.3
PyWavelets                        1.2.0
pywin32-ctypes                    0.2.0
PyYAML                            6.0
requests                          2.26.0
scikit-image                      0.19.1
scipy                             1.7.3
setuptools                        58.0.4
Shapely                           1.8.0
shellcheck-py                     0.8.0.2
six                               1.16.0
tifffile                          2021.11.2
toml                              0.10.2
tqdm                              4.62.3
typing_extensions                 4.0.1
urllib3                           1.26.7
virtualenv                        20.10.0
visualdl                          2.2.2
Werkzeug                          2.0.2
wheel                             0.37.0
wincertstore                      0.2
zipp                              3.6.0iconda 
- 运行指令/Command `Code：from paddleocr import PaddleOCR
print('ok')`
pyinstaller指令是

> pyinstaller -F  --exclude matplotlib -p C:\Users\liu\miniconda3\envs\ppocr\Lib\site-packages\paddleocr;C:\Users\liu\miniconda3\envs\ppocr\Lib\site-packages\paddle\libs test.py  --add-binary C:\Users\liu\miniconda3\envs\ppocr\Lib\site-packages\paddle\libs;. --add-data .\model;.\model --additional-hooks-dir=. 

- 完整报错/Complete Error Message：
(base) PS D:\liuhao_work\code\file_digitization> .\1.exe
Traceback (most recent call last):
  File "paddle\fluid\ir.py", line 23, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from paddleocr import PaddleOCR
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddleocr.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\spawn.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\utils.py", line 28, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\fleet\__init__.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\fleet\base\fleet_base.py", line 31, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\fluid\ir.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'
[11760] Failed to execute script '1' due to unhandled exception!

**Comment by WenmuZhou** [comment]
麻烦搜索引擎搜一下看看，我们这边没试过打包

**Comment by gewenpulan** [comment]
搜过了，貌似之前paddleocr版本都有相关打包exe的修改方式，最近是不是paddleocr更新了，于是出现这个新问题？

**Comment by TonyWang2018** [comment]
这个问题我也遇到了，手动改一下paddleocr的源码搞定的

**Comment by linkangren** [comment]
怎么解决的呢我也有这个问题
 File "paddle/fluid/ir.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/fluid/proto/pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "abcd.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ku/predict_system.py", line 26, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ku/predict_rec.py", line 25, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ku/predictor.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/__init__.py", line 45, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/distributed/__init__.py", line 15, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/distributed/spawn.py", line 24, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/distributed/utils.py", line 28, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/distributed/fleet/__init__.py", line 20, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/distributed/fleet/base/fleet_base.py", line 31, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/fluid/ir.py", line 27, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/fluid/proto/pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'
[32181] Failed to execute script 'abcd' due to unhandled exception: No module named 'framework_pb2'
[32181] Traceback:
Traceback (most recent call last):
  File "paddle/fluid/ir.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/fluid/proto/pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'
