### ISSUE TITLE
windows python3.7安装完paddle之后，出现找不到指定模块。

### ISSUE THREAD

**Issue by wwwanwei** [PaddlePaddle/PaddleOCR#512]
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 20, in <module>
    import tools.infer.utility as utility
  File "F:\python\PaddleOCR\tools\infer\utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "F:\python\PaddleOCR\ppocr\utils\utility.py", line 19, in <module>
    from paddle import fluid
  File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 56, in <module>
    from . import contrib
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\__init__.py", line 27, in <module>
    from . import slim
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
    from .core import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
    from . import config
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
    from ..prune import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
    from . import prune_strategy
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
    from scipy.optimize import leastsq
  File "C:\Python37\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from .optimize import *
  File "C:\Python37\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Python37\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: 找不到指定的模块。

F:\python\PaddleOCR>python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/"
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 20, in <module>
    import tools.infer.utility as utility
  File "F:\python\PaddleOCR\tools\infer\utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "F:\python\PaddleOCR\ppocr\utils\utility.py", line 19, in <module>
    from paddle import fluid
  File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "C:\Python37\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Python37\lib\site-packages\paddle\fluid\core.py", line 264, in <module>
    raise e
  File "C:\Python37\lib\site-packages\paddle\fluid\core.py", line 234, in <module>
    from .core_avx import *
  File "C:\Python37\lib\site-packages\paddle\fluid\core_avx\__init__.py", line 107
    def infer_no_need_buffer_slots(arg0, arg1, p_str=None, List=None, p_str=None_1, *args, **kwargs): # real signature unknown; NOTE: unreliably restored from __doc__
    ^
SyntaxError: duplicate argument 'p_str' in function definition

F:\python\PaddleOCR>python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/"
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 20, in <module>
    import tools.infer.utility as utility
  File "F:\python\PaddleOCR\tools\infer\utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "F:\python\PaddleOCR\ppocr\utils\utility.py", line 19, in <module>
    from paddle import fluid
  File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 56, in <module>
    from . import contrib
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\__init__.py", line 27, in <module>
    from . import slim
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
    from .core import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
    from . import config
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
    from ..prune import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
    from . import prune_strategy
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
    from scipy.optimize import leastsq
  File "C:\Python37\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>

F:\python\PaddleOCR>python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/"

F:\python\PaddleOCR>python tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/"
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 20, in <module>
    import tools.infer.utility as utility
  File "F:\python\PaddleOCR\tools\infer\utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "F:\python\PaddleOCR\ppocr\utils\utility.py", line 19, in <module>
    from paddle import fluid
  File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 56, in <module>
    from . import contrib
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\__init__.py", line 27, in <module>
    from . import slim
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
    from .core import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
    from . import config
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
    from ..prune import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
    from . import prune_strategy
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
    from scipy.optimize import leastsq
  File "C:\Python37\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from .optimize import *
  File "C:\Python37\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Python37\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: 找不到指定的模块。

**Comment by LDOUBLEV** [comment]
1. 可以验证paddle是否安装成功：
```
import paddle
paddle.fluid.install_check.run_check()
```

2. 还需要安装第三方库
![image](https://user-images.githubusercontent.com/26592129/89861957-81c85f00-dbd9-11ea-868a-63134726ab64.png)


3. 报错在scipy中，可尝试重新安装scipy库

**Comment by wwwanwei** [comment]
好的谢谢，但是是paddle未安装成功：>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "C:\Python37\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "C:\Python37\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "C:\Python37\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "C:\Python37\lib\site-packages\paddle\fluid\__init__.py", line 56, in <module>
    from . import contrib
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\__init__.py", line 27, in <module>
    from . import slim
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
    from .core import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
    from . import config
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
    from ..prune import *
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
    from . import prune_strategy
  File "C:\Python37\lib\site-packages\paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
    from scipy.optimize import leastsq
  File "C:\Python37\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from .optimize import *
  File "C:\Python37\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Python37\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: 找不到指定的模块。

**Comment by wwwanwei** [comment]
感谢，已经解决，是scipy版本不对。
