### ISSUE TITLE
按照教程《基于PaddleHub Serving的服务部署》部署 OCR 服务时报错

### ISSUE THREAD

**Issue by elmershaw** [PaddlePaddle/PaddleOCR#5176]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 10, python 3.8.12
- 版本号/Version：Paddle：paddlepaddle-2.2.1  PaddleOCR：paddleocr-2.3.0.2 问题相关组件/Related components：paddlehub-2.2.0
- 运行指令/Command Code：hub install deploy\hubserving\ocr_system\
- 完整报错/Complete Error Message：
from collections import Iterable
Traceback (most recent call last):
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\manager.py", line 177, in install
    with lock:
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\filelock\_api.py", line 210, in __enter__
    self.acquire()
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\filelock\_api.py", line 166, in acquire
    self._acquire()
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\filelock\_windows.py", line 24, in _acquire
    fd = os.open(self._lock_file, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YFGZ-KF-XiaoYuhan\\.paddlehub\\tmp\\deploy\\hubserving\\ocr_system\\'

(paddle_env) C:\Users\YFGZ-KF-XiaoYuhan>hub serving start -m ocr_system
C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlenlp\transformers\funnel\modeling.py:31: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
Traceback (most recent call last):
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\serving.py", line 352, in execute
    self.start_serving()
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\serving.py", line 221, in start_single_app_with_args
    self.preinstall_modules()
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\serving.py", line 152, in preinstall_modules
    m = hub.Module(**init_args)
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\module.py", line 388, in __new__
    module = cls.init_with_name(
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\module.py", line 487, in init_with_name
    user_module_cls = manager.install(
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "C:\Users\YFGZ-KF-XiaoYuhan\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\manager.py", line 270, in _install_from_name
    raise HubModuleNotFoundError(name=name, version=version)
paddlehub.module.manager.HubModuleNotFoundError: No HubModule named ocr_system was found

**Comment by Shy280** [comment]
在你的PaddleOCR主目录输入命令： `hub install deploy/hubserving/ocr_system/`
