### ISSUE TITLE
NRTR训练模型转推理模型出错？

### ISSUE THREAD

**Issue by guanrenxue** [PaddlePaddle/PaddleOCR#5196]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：docker
- 版本号/Version：Paddle：2.3版本  PaddleOCR： 问题相关组件/Related components：使用NRTR算法进行英文识别，训练模型转推理模型出现错误？
- 运行指令/Command Code：python tools/export_model.py -c configs/rec/rec_mtb_nrtr.yml -o Global.ceckpoints=./output/rec_nrtr/nrtr/best_accuracy Global.save_inference_dir=./inference/rec_nrtr
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "tools/export_model.py", line 121, in <module>
    main()
  File "tools/export_model.py", line 117, in main
    export_single_model(model, arch_config, save_path, logger)
  File "tools/export_model.py", line 72, in export_single_model
    paddle.jit.save(model, save_path)
  File "<decorator-gen-67>", line 2, in save
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/home/work_pp/PaddleOCR-release-2.3/ppocr/modeling/architectures/base_model.py", line 75, in forward (* user code *)
	x = self.backbone(x)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/home/work_pp/PaddleOCR-release-2.3/ppocr/modeling/backbones/rec_nrtr_mtb.py", line 40, in forward (* user code *)
	x = self.block(images)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 97, in forward
	input = layer(input)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 667, in forward
	use_cudnn=self._use_cudnn)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 139, in _conv_nd
	type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3232, in append_op
	attrs=kwargs.get("attrs", None))
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2427, in __init__
	self.desc.infer_shape(self.block.desc)
    ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [-1, 3, 32, -1]; the filter's channels is 1, the filter's shape is [32, 1, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:100)
  [operator < conv2d > error]

**Comment by Topdu** [comment]
导出时应指定算法名称NRTR，在tool\export_model.py 第69行
```
if arch_config["algorithm"] == "NRTR":
                infer_shape = [1, 32, 100]
```
导出nrtr时，输入size应和配置文件相匹配
