### ISSUE TITLE
按照最新指令将paddleocr识别模型转ONNX报错

### ISSUE THREAD

**Issue by zxl222** [PaddlePaddle/PaddleOCR#5204]
您好，我按照说明成功将检测模型转换为ONNX格式，并可以成功运行 `predict_det.py`。但方向检测模型和识别模型报错。

系统环境： `win10;   paddle2onnx:0.9.0;  paddleocr2.3.0.2;  paddlepaddle 2.2.1；onnx 1.9.0；paddle-ocr_0106-release-2.4.`

运行指令：
1.检测转换指令： `paddle2onnx --model_dir=./inference/ch_PP-OCRv2_det_infer/ --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./inference/det_mobile_onnx/model111.onnx --opset_version=10 --input_shape_dict="{'x': [-1, 3, -1, -1]}" --enable_onnx_checker=True`
2.识别转换指令： `paddle2onnx --model_dir=./inference3/ch_PP-OCRv2_rec_infer/ --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./inference3/det_mobile_onnx/model33.onnx --opset_version=10 --input_shape_dict="{'x': [-1, 3, -1, -1]}" --enable_onnx_checker=True`

报错信息如下： 
`(base) F:\Paddle_ONNX>paddle2onnx --model_dir=./inference3/ch_PP-OCRv2_rec_infer/ --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./inference3/det_mobile_onnx/model33.onnx --opset_version=10 --input_shape_dict="{'x': [-1, 3, -1, -1]}" --enable_onnx_checker=True
D:\anaconda\lib\site-packages\setuptools\depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "D:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "D:\anaconda\lib\site-packages\paddle2onnx\command.py", line 184, in main
    input_shape_dict=input_shape_dict)
  File "D:\anaconda\lib\site-packages\paddle2onnx\command.py", line 138, in program2onnx
    program.blocks[0].ops[i].desc.infer_shape(program.blocks[0].desc)
RuntimeError: (NotFound) Attribute (head_number) should be in AttributeMap.
  [Hint: Expected found == true, but received found:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:229)
  [operator < matmul > error]`

我不知道如何解决这个问题，期待收到任何回复。（不指定input_shape_dict可以生成onnx文件，但运行推理代码报错

**Comment by jiangjiajun** [comment]
Hi, @tink2123 麻烦试下安装github上最新的Paddle2ONNX代码再测试

上面出错的原因可能是由于在设定了`input_shape_dict`时，模型转换时会重新对模型中各节点的shape进行推断，这时如果本地安装的paddle版本与之前保存inference模型的版本不同时，可能会出现上述问题

在重新安装最新的paddle2onnx后，会有相应的提示，根据提示重新安装paddlepaddle指定的版本即可解决。

至于您说的不指定可以生成onnx文件，但运行推理代码报错，麻烦贴一下这个对应的错误信息

```
pip uninstall paddle2onnx
git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
cd Paddle2ONNX
python setup.py install
```

**Comment by zxl222** [comment]
> Hi, @tink2123 麻烦试下安装github上最新的Paddle2ONNX代码再测试
> 
> 上面出错的原因可能是由于在设定了`input_shape_dict`时，模型转换时会重新对模型中各节点的shape进行推断，这时如果本地安装的paddle版本与之前保存inference模型的版本不同时，可能会出现上述问题
> 
> 在重新安装最新的paddle2onnx后，会有相应的提示，根据提示重新安装paddlepaddle指定的版本即可解决。
> 
> 至于您说的不指定可以生成onnx文件，但运行推理代码报错，麻烦贴一下这个对应的错误信息
> 
> ```
> pip uninstall paddle2onnx
> git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
> cd Paddle2ONNX
> python setup.py install
> ```

您好，感谢您的回复。我安装了最新的paddle2onnx,但提示版本为V0.0.0代码如下：
`(base) F:\Paddle_ONNX\0110>paddle2onnx --model_dir=./ch_PP-OCRv2_det_infer/ch_PP-OCRv2_det_infer/ --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./inference/det_mobile_onnx/model.onnx --opset_version=10 --input_shape_dict="{'x': [-1, 3, -1, -1]}" --enable_onnx_checker=True
D:\anaconda\lib\site-packages\setuptools\depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2022-01-10 10:57:41 [WARNING]   The model is saved by paddlepaddle v0.0.0, but now your paddlepaddle is version of 2.2.1, this difference may cause error, it is recommend you reinstall a same version of paddlepaddle for this model
2022-01-10 10:57:41 [INFO]      ONNX model generated is valid.
2022-01-10 10:57:41 [INFO]      ONNX model saved in ./inference/det_mobile_onnx/model.onnx`
我不知道V0.0.0是paddlepaddle的哪个版本，目前停顿在这一步。
@jiangjiajun

**Comment by jiangjiajun** [comment]
@zxl222 安装paddlepaddle 2.1.3试下

**Comment by zxl222** [comment]
已安装paddlepaddle==2.1.3,出现了同样的问题。识别模型无法转换。代码如下：

> 
(base) F:\Paddle_ONNX\0110>paddle2onnx --model_dir=./ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer/ --model_filename=inference.pdmodel --params_filename=inference.pdiparams --save_file=./inference/cls_mobile_onnx/model.onnx --opset_version=10 --input_shape_dict="{'x': [-1, 3, -1, -1]}" --enable_onnx_checker=True
D:\anaconda\lib\site-packages\setuptools\depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2022-01-10 11:30:14 [WARNING]   The model is saved by paddlepaddle v0.0.0, but now your paddlepaddle is version of 2.1.3, this difference may cause error, it is recommend you reinstall a same version of paddlepaddle for this model
Traceback (most recent call last):
  File "D:\anaconda\Scripts\paddle2onnx-script.py", line 11, in <module>
    load_entry_point('paddle2onnx==0.9.0', 'console_scripts', 'paddle2onnx')()
  File "D:\anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\command.py", line 195, in main
  File "D:\anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\command.py", line 149, in program2onnx
RuntimeError: (NotFound) Attribute (head_number) should be in AttributeMap.
  [Hint: Expected attrs_.count(name) != 0, but received attrs_.count(name):0 == 0:0.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:217)
  [operator < matmul > error]
> 
@jiangjiajun

**Comment by jiangjiajun** [comment]
麻烦提供一下模型

**Comment by zxl222** [comment]
> 麻烦提供一下模型

[0110.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7837086/0110.zip)
所使用的模型为此页面中提供的中英文超轻量PP-OCRv2模型（13.0M） `https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/README_ch.md`
@jiangjiajun

**Comment by jiangjiajun** [comment]
@zxl222 我在paddlepaddle 2.2.1 (CPU版本）下，paddle2onnx 0.9.0版本，以及python3.7环境下，导出正常

**Comment by zxl222** [comment]
我重新安装了基于python3.7的Anaconda,但出现了同样的错误，还没有找到原因。您能提供导出后的模型吗，我想测试一下。非常感谢

**Comment by zxl222** [comment]
> @zxl222 我在paddlepaddle 2.2.1 (CPU版本）下，paddle2onnx 0.9.0版本，以及python3.7环境下，导出正常

我重新安装了基于python3.7的Anaconda,但出现了同样的错误，还没有找到原因。您能提供导出后的模型吗，我想测试一下。非常感谢 
@jiangjiajun

**Comment by jiangjiajun** [comment]
[det_infer.onnx.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7838651/det_infer.onnx.zip)
[rec_infer.onnx.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7838653/rec_infer.onnx.zip)

**Comment by zxl222** [comment]
> [det_infer.onnx.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7838651/det_infer.onnx.zip) [rec_infer.onnx.zip](https://github.com/PaddlePaddle/PaddleOCR/files/7838653/rec_infer.onnx.zip)

我重装了一遍环境，并且按照提示重装了paddlepaddle2.0.2,但在导出onnx模型时出现了另一个问题，这是paddle2onnx版本问题所导致吗？：

> 
(paddle) E:\Paddle_onnx>paddle2onnx --model_dir ./ch_PP-OCRv2_det_infer/ch_PP-OCRv2_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_det_infer.onnx --opset_version 10 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True
Traceback (most recent call last):
  File "D:\Anaconda\Scripts\paddle2onnx-script.py", line 11, in <module>
    load_entry_point('paddle2onnx==0.9.0', 'console_scripts', 'paddle2onnx')()
  File "D:\Anaconda\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Anaconda\lib\site-packages\pkg_resources\__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "D:\Anaconda\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "D:\Anaconda\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\convert.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\graph\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\graph\onnx_graph.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\op_mapper\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\op_mapper\nn.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\Anaconda\lib\site-packages\paddle2onnx-0.9.0-py3.6.egg\paddle2onnx\op_mapper\mapper_helper.py", line 79, in <module>
AttributeError: module 'paddle' has no attribute 'float32'

> 
@jiangjiajun

**Comment by jiangjiajun** [comment]
是paddle太低导致

**Comment by zxl222** [comment]
我已经解决了这个问题，只需在第一步：模型转换时，选择第二种方式  `参考模型导出说明把训练好的权重转为 inference_model。`  。然后按照说明即可成功导出onnx模型。
感谢您的工作和及时回复。
@jiangjiajun

**Comment by ShiyangZhang** [comment]
@zxl222 用onnx跑 tools/infer/predict_system.py 似乎结果不一致

**Comment by jaysonteng** [comment]
你好，请问解决了吗，我也遇到了你这些问题
