### ISSUE TITLE
使用ACELoss报错

### ISSUE THREAD

**Issue by limaopeng1** [PaddlePaddle/PaddleOCR#5242]
在使用ACELoss的时候报错，请问batch[3]是什么：
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
	main(config, device, logger, vdl_writer)
  File "tools/train.py", line 125, in main
	eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/root/limaopeng/PaddleOCR_2.4/tools/program.py", line 246, in train
	loss = loss_class(preds, batch)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
  File "/root/limaopeng/PaddleOCR_2.4/ppocr/losses/combined_loss.py", line 55, in forward
	loss = loss_func(input, batch, **kargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs) 
  File "/root/limaopeng/PaddleOCR_2.4/ppocr/losses/distillation_loss.py", line 140, in forward    
	loss = super().forward(out, batch)  
  File "/root/limaopeng/PaddleOCR_2.4/ppocr/losses/rec_enhanced_ctc_loss.py", line 67, in forward   
	predicts, batch)["loss_ace"] * self.ace_loss_weight 
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__ 
	outputs = self.forward(*inputs, **kwargs)   
  File "/root/limaopeng/PaddleOCR_2.4/ppocr/losses/ace_loss.py", line 47, in forward  
	batch = batch[3].astype("float32")            
	IndexError: list index out of range                

ace_loss.py关键代码如下：

```
def forward(self, predicts, batch):
    if isinstance(predicts, (list, tuple)):
        predicts = predicts[-1]

    B, N = predicts.shape[:2]
    div = paddle.to_tensor([N]).astype('float32')

    predicts = nn.functional.softmax(predicts, axis=-1)
    aggregation_preds = paddle.sum(predicts, axis=1)
    aggregation_preds = paddle.divide(aggregation_preds, div)

    length = batch[2].astype("float32")
    batch = batch[3].astype("float32")
    batch[:, 0] = paddle.subtract(div, length)
    batch = paddle.divide(batch, div)

    loss = self.loss_func(aggregation_preds, batch)
    return {"loss_ace": loss}
```

**Comment by limaopeng1** [comment]
是我配置文件里去掉了label_ace的问题
- KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - label_ace
