### ISSUE TITLE
我在使用PaddleOCR: 车牌识别这个例子的时候出现以下错误，什么原因？，谢谢！

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5264]
我在使用这个例子的时候出现以下错误，什么原因？，谢谢！

https://aistudio.baidu.com/ibdcpu7/user/807875/3410130/

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/sparse/sputils.py:16: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/skimage/segmentation/random_walker_segmentation.py:49: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if Version(scipy.__version__) >= Version('1.1'):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
[2022/01/14 15:12:00] root INFO: Architecture : 
[2022/01/14 15:12:00] root INFO:     Backbone : 
[2022/01/14 15:12:00] root INFO:         model_name : large
[2022/01/14 15:12:00] root INFO:         name : MobileNetV3
[2022/01/14 15:12:00] root INFO:         scale : 0.5
[2022/01/14 15:12:00] root INFO:     Head : 
[2022/01/14 15:12:00] root INFO:         k : 50
[2022/01/14 15:12:00] root INFO:         name : DBHead
[2022/01/14 15:12:00] root INFO:     Neck : 
[2022/01/14 15:12:00] root INFO:         name : DBFPN
[2022/01/14 15:12:00] root INFO:         out_channels : 256
[2022/01/14 15:12:00] root INFO:     Transform : None
[2022/01/14 15:12:00] root INFO:     algorithm : DB
[2022/01/14 15:12:00] root INFO:     model_type : det
[2022/01/14 15:12:00] root INFO: Eval : 
[2022/01/14 15:12:00] root INFO:     dataset : 
[2022/01/14 15:12:00] root INFO:         data_dir : /home/aistudio/
[2022/01/14 15:12:00] root INFO:         label_file_list : ['/home/aistudio/dataset/dev_det.txt']
[2022/01/14 15:12:00] root INFO:         name : SimpleDataSet
[2022/01/14 15:12:00] root INFO:         transforms : 
[2022/01/14 15:12:00] root INFO:             DecodeImage : 
[2022/01/14 15:12:00] root INFO:                 channel_first : False
[2022/01/14 15:12:00] root INFO:                 img_mode : BGR
[2022/01/14 15:12:00] root INFO:             DetLabelEncode : None
[2022/01/14 15:12:00] root INFO:             DetResizeForTest : 
[2022/01/14 15:12:00] root INFO:                 image_shape : [736, 1280]
[2022/01/14 15:12:00] root INFO:             NormalizeImage : 
[2022/01/14 15:12:00] root INFO:                 mean : [0.485, 0.456, 0.406]
[2022/01/14 15:12:00] root INFO:                 order : hwc
[2022/01/14 15:12:00] root INFO:                 scale : 1./255.
[2022/01/14 15:12:00] root INFO:                 std : [0.229, 0.224, 0.225]
[2022/01/14 15:12:00] root INFO:             ToCHWImage : None
[2022/01/14 15:12:00] root INFO:             KeepKeys : 
[2022/01/14 15:12:00] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2022/01/14 15:12:00] root INFO:     loader : 
[2022/01/14 15:12:00] root INFO:         batch_size_per_card : 1
[2022/01/14 15:12:00] root INFO:         drop_last : False
[2022/01/14 15:12:00] root INFO:         num_workers : 8
[2022/01/14 15:12:00] root INFO:         shuffle : False
[2022/01/14 15:12:00] root INFO:         use_shared_memory : False
[2022/01/14 15:12:00] root INFO: Global : 
[2022/01/14 15:12:00] root INFO:     cal_metric_during_train : False
[2022/01/14 15:12:00] root INFO:     checkpoints : None
[2022/01/14 15:12:00] root INFO:     debug : False
[2022/01/14 15:12:00] root INFO:     distributed : False
[2022/01/14 15:12:00] root INFO:     epoch_num : 1200
[2022/01/14 15:12:00] root INFO:     eval_batch_step : [0, 2000]
[2022/01/14 15:12:00] root INFO:     infer_img : doc/imgs_en/img_10.jpg
[2022/01/14 15:12:00] root INFO:     log_smooth_window : 20
[2022/01/14 15:12:00] root INFO:     pretrained_model : ./pretrain_models/MobileNetV3_large_x0_5_pretrained
[2022/01/14 15:12:00] root INFO:     print_batch_step : 10
[2022/01/14 15:12:00] root INFO:     save_epoch_step : 1200
[2022/01/14 15:12:00] root INFO:     save_inference_dir : None
[2022/01/14 15:12:00] root INFO:     save_model_dir : ./output/db_mv3/
[2022/01/14 15:12:00] root INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2022/01/14 15:12:00] root INFO:     use_gpu : False
[2022/01/14 15:12:00] root INFO:     use_visualdl : False
[2022/01/14 15:12:00] root INFO: Loss : 
[2022/01/14 15:12:00] root INFO:     alpha : 5
[2022/01/14 15:12:00] root INFO:     balance_loss : True
[2022/01/14 15:12:00] root INFO:     beta : 10
[2022/01/14 15:12:00] root INFO:     main_loss_type : DiceLoss
[2022/01/14 15:12:00] root INFO:     name : DBLoss
[2022/01/14 15:12:00] root INFO:     ohem_ratio : 3
[2022/01/14 15:12:00] root INFO: Metric : 
[2022/01/14 15:12:00] root INFO:     main_indicator : hmean
[2022/01/14 15:12:00] root INFO:     name : DetMetric
[2022/01/14 15:12:00] root INFO: Optimizer : 
[2022/01/14 15:12:00] root INFO:     beta1 : 0.9
[2022/01/14 15:12:00] root INFO:     beta2 : 0.999
[2022/01/14 15:12:00] root INFO:     lr : 
[2022/01/14 15:12:00] root INFO:         learning_rate : 0.001
[2022/01/14 15:12:00] root INFO:     name : Adam
[2022/01/14 15:12:00] root INFO:     regularizer : 
[2022/01/14 15:12:00] root INFO:         factor : 0
[2022/01/14 15:12:00] root INFO:         name : L2
[2022/01/14 15:12:00] root INFO: PostProcess : 
[2022/01/14 15:12:00] root INFO:     box_thresh : 0.6
[2022/01/14 15:12:00] root INFO:     max_candidates : 1000
[2022/01/14 15:12:00] root INFO:     name : DBPostProcess
[2022/01/14 15:12:00] root INFO:     thresh : 0.3
[2022/01/14 15:12:00] root INFO:     unclip_ratio : 1.5
[2022/01/14 15:12:00] root INFO: Train : 
[2022/01/14 15:12:00] root INFO:     dataset : 
[2022/01/14 15:12:00] root INFO:         data_dir : /home/aistudio/
[2022/01/14 15:12:00] root INFO:         label_file_list : ['/home/aistudio/dataset/train_det.txt']
[2022/01/14 15:12:00] root INFO:         name : SimpleDataSet
[2022/01/14 15:12:00] root INFO:         ratio_list : [1.0]
[2022/01/14 15:12:00] root INFO:         transforms : 
[2022/01/14 15:12:00] root INFO:             DecodeImage : 
[2022/01/14 15:12:00] root INFO:                 channel_first : False
[2022/01/14 15:12:00] root INFO:                 img_mode : BGR
[2022/01/14 15:12:00] root INFO:             DetLabelEncode : None
[2022/01/14 15:12:00] root INFO:             IaaAugment : 
[2022/01/14 15:12:00] root INFO:                 augmenter_args : 
[2022/01/14 15:12:00] root INFO:                     args : 
[2022/01/14 15:12:00] root INFO:                         p : 0.5
[2022/01/14 15:12:00] root INFO:                     type : Fliplr
[2022/01/14 15:12:00] root INFO:                     args : 
[2022/01/14 15:12:00] root INFO:                         rotate : [-10, 10]
[2022/01/14 15:12:00] root INFO:                     type : Affine
[2022/01/14 15:12:00] root INFO:                     args : 
[2022/01/14 15:12:00] root INFO:                         size : [0.5, 3]
[2022/01/14 15:12:00] root INFO:                     type : Resize
[2022/01/14 15:12:00] root INFO:             EastRandomCropData : 
[2022/01/14 15:12:00] root INFO:                 keep_ratio : True
[2022/01/14 15:12:00] root INFO:                 max_tries : 50
[2022/01/14 15:12:00] root INFO:                 size : [640, 640]
[2022/01/14 15:12:00] root INFO:             MakeBorderMap : 
[2022/01/14 15:12:00] root INFO:                 shrink_ratio : 0.4
[2022/01/14 15:12:00] root INFO:                 thresh_max : 0.7
[2022/01/14 15:12:00] root INFO:                 thresh_min : 0.3
[2022/01/14 15:12:00] root INFO:             MakeShrinkMap : 
[2022/01/14 15:12:00] root INFO:                 min_text_size : 8
[2022/01/14 15:12:00] root INFO:                 shrink_ratio : 0.4
[2022/01/14 15:12:00] root INFO:             NormalizeImage : 
[2022/01/14 15:12:00] root INFO:                 mean : [0.485, 0.456, 0.406]
[2022/01/14 15:12:00] root INFO:                 order : hwc
[2022/01/14 15:12:00] root INFO:                 scale : 1./255.
[2022/01/14 15:12:00] root INFO:                 std : [0.229, 0.224, 0.225]
[2022/01/14 15:12:00] root INFO:             ToCHWImage : None
[2022/01/14 15:12:00] root INFO:             KeepKeys : 
[2022/01/14 15:12:00] root INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2022/01/14 15:12:00] root INFO:     loader : 
[2022/01/14 15:12:00] root INFO:         batch_size_per_card : 16
[2022/01/14 15:12:00] root INFO:         drop_last : False
[2022/01/14 15:12:00] root INFO:         num_workers : 8
[2022/01/14 15:12:00] root INFO:         shuffle : True
[2022/01/14 15:12:00] root INFO:         use_shared_memory : False
[2022/01/14 15:12:00] root INFO: train with paddle 2.1.2 and device CPUPlace
[2022/01/14 15:12:00] root INFO: Initialize indexs of datasets:['/home/aistudio/dataset/train_det.txt']
[2022/01/14 15:12:01] root INFO: Initialize indexs of datasets:['/home/aistudio/dataset/dev_det.txt']
[2022/01/14 15:12:01] root INFO: The shape of model params neck.in2_conv.weight [256, 16, 1, 1] not matched with loaded params last_conv.weight [1280, 480, 1, 1] !
[2022/01/14 15:12:01] root INFO: The shape of model params neck.in3_conv.weight [256, 24, 1, 1] not matched with loaded params out.weight [1280, 1000] !
[2022/01/14 15:12:01] root INFO: The shape of model params neck.in4_conv.weight [256, 56, 1, 1] not matched with loaded params out.bias [1000] !
[2022/01/14 15:12:01] root INFO: loaded pretrained_model successful from ./pretrain_models/MobileNetV3_large_x0_5_pretrained.pdparams
[2022/01/14 15:12:01] root INFO: train dataloader has 4789 iters
[2022/01/14 15:12:01] root INFO: valid dataloader has 19154 iters
[2022/01/14 15:12:01] root INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
[2022/01/14 15:12:01] root INFO: Initialize indexs of datasets:['/home/aistudio/dataset/train_det.txt']
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 108, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 221, in train
    preds = model(images)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 75, in forward
    x = self.backbone(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 149, in forward
    x = stage(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 235, in forward
    x = self.expand_conv(inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 183, in forward
    x = F.relu(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/activation.py", line 491, in relu
    return core.ops.relu(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 46440) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

![image](https://user-images.githubusercontent.com/75007961/149468481-4ce3e8e8-c3d8-4b2b-a0a9-5ecf510c7ee2.png)

**Comment by WenmuZhou** [comment]
num_workers设为0

**Comment by linkewei0580** [comment]
> 
我已经改了参数了，还是出现
![image](https://user-images.githubusercontent.com/75007961/149705304-04de513b-5510-4d50-bc0b-3c9e1ee12cbf.png)

[2022/01/17 11:47:54] root INFO:         num_workers : 0

**Comment by WenmuZhou** [comment]
改为0之后是啥报错

**Comment by linkewei0580** [comment]
> 

代码执行异常：内存溢出，执行已被中专，请查看相关代码，就是上面的弹框。

**Comment by WenmuZhou** [comment]
batch调低

**Comment by linkewei0580** [comment]
你好我要调整哪个batch?谢谢！
print_batch_step: 10
eval_batch_step: [0, 2000]
batch_size_per_card: 16
batch_size_per_card: 1 # must be 1

**Comment by linkewei0580** [comment]
![Uploading 1.png…]()
![Uploading 1.png…]()
我改了eval_batch_step: [0, 500]还是出现这个

**Comment by linkewei0580** [comment]
![Uploading 1.png…]()
我改了eval_batch_step: [0, 500]还是出现这个

**Comment by linkewei0580** [comment]
![Uploading 1.png…]()
![Uploading 1.png…]()
我改了eval_batch_step: [0, 500]还是出现这个
