### ISSUE TITLE
运行icdar检测训练，epoch第二轮时被自动killed

### ISSUE THREAD

**Issue by farukonfly** [PaddlePaddle/PaddleOCR#5282]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18.04 cuda 10.2 cudnn 7.6.5
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained
- 完整报错/Complete Error Message：
![image](https://user-images.githubusercontent.com/18646553/149889327-6ab20d1e-a3b3-4709-84ff-8098fd50733e.png)

**Comment by andyjpaddle** [comment]
请提供一下详细报错信息，查看显存或内存是否充足，尝试调小`batchsize`试试

**Comment by farukonfly** [comment]
请问需提供哪种详细的信息？下图这种属于异常退出了显存没有被释放么
![image](https://user-images.githubusercontent.com/18646553/149891132-b460e943-3006-4e7e-a3ef-d82717180fad.png)

**Comment by farukonfly** [comment]
我刚边跑训练的边使用watch nvidia-smi观测，显存也没爆，还有不少啊，但总会被killed

**Comment by andyjpaddle** [comment]
把你的kill后的信息也发出来，同时给一下你的配置文件和做了哪些修改？

**Comment by andyjpaddle** [comment]
> 请问需提供哪种详细的信息？下图这种属于异常退出了显存没有被释放么 ![image](https://user-images.githubusercontent.com/18646553/149891132-b460e943-3006-4e7e-a3ef-d82717180fad.png)

你这个是运行中的吗？还是kill后的？

**Comment by farukonfly** [comment]
killed之后没有任何信息。

> > 请问需提供哪种详细的信息？下图这种属于异常退出了显存没有被释放么 ![image](https://user-images.githubusercontent.com/18646553/149891132-b460e943-3006-4e7e-a3ef-d82717180fad.png)
> 
> 你这个是运行中的吗？还是kill后的？

 killed 后的

**Comment by andyjpaddle** [comment]
那应该是显存没释放，可以看一下相关进程是否结束

**Comment by farukonfly** [comment]
> 把你的kill后的信息也发出来，同时给一下你的配置文件和做了哪些修改？

killed之后没有任何信息，直接结束，运行https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.4/doc/doc_ch/detection.md 这个文档中的例子，没有对配置文件做任何修改
![image](https://user-images.githubusercontent.com/18646553/149892469-a5f8fc5a-034d-41a1-a726-6bdbe5129f2c.png)

**Comment by farukonfly** [comment]
> 把你的kill后的信息也发出来，同时给一下你的配置文件和做了哪些修改？
重新运行了一次，这次有kill的报错信息了
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 123, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/ubuntu/ai/PaddleOCR/tools/program.py", line 245, in train
    preds = model(images)
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/ai/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 75, in forward
    x = self.backbone(x)
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/ai/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 146, in forward
    x = self.conv(x)
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/ai/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 179, in forward
    x = self.conv(x)
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 665, in forward
    out = F.conv._conv_nd(
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
  File "/home/ubuntu/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 3087) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

**Comment by andyjpaddle** [comment]
你先把占显存的进程kill掉，然后调小batchsize，再运行看看？

**Comment by farukonfly** [comment]
> 你先把占显存的进程kill掉，然后调小batchsize，再运行看看？

我使用det_mv3_db.yml，调小batchsize应该调那个字段，还不太熟悉

**Comment by andyjpaddle** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/configs/det/det_mv3_db.yml#L101  这个地方，然后把下面的num_workers 也改小一些，use_shared_memory设置为True

**Comment by farukonfly** [comment]
修改之后确实可以跑起来了，非常感谢，是否可以给个介绍配置文件参数的链接

**Comment by andyjpaddle** [comment]
配置文件参数介绍: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/config.md

这个目录下面有很多参考文档 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/doc/doc_ch
