### ISSUE TITLE
apple m1 docker部署失败

### ISSUE THREAD

**Issue by dragon-zhang** [PaddlePaddle/PaddleOCR#5285]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
apple m1 
12.0.1 (21A559)

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：

- 运行指令/Command Code：
```dockerfile
# Version: 2.0.0
FROM registry.baidubce.com/paddlepaddle/paddle:2.0.0

# PaddleOCR base on Python3.7
RUN pip3.7 install --upgrade pip -i https://mirror.baidu.com/pypi/simple

RUN pip3.7 install -U paddlepaddle -f https://mirror.baidu.com/pypi/simple

RUN pip3.7 install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple

RUN git clone https://gitee.com/PaddlePaddle/PaddleOCR.git /PaddleOCR

WORKDIR /PaddleOCR

RUN pip3.7 install -r requirements.txt -i https://mirror.baidu.com/pypi/simple

RUN mkdir -p /PaddleOCR/inference/
# Download orc detect model(light version). if you want to change normal version, you can change ch_ppocr_mobile_v2.0_det_infer to ch_ppocr_server_v2.0_det_infer, also remember change det_model_dir in deploy/hubserving/ocr_system/params.py）
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_det_infer.tar -C /PaddleOCR/inference/

# Download direction classifier(light version). If you want to change normal version, you can change ch_ppocr_mobile_v2.0_cls_infer to ch_ppocr_mobile_v2.0_cls_infer, also remember change cls_model_dir in deploy/hubserving/ocr_system/params.py）
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer.tar -C /PaddleOCR/inference/

# Download orc recognition model(light version). If you want to change normal version, you can change ch_ppocr_mobile_v2.0_rec_infer to ch_ppocr_server_v2.0_rec_infer, also remember change rec_model_dir in deploy/hubserving/ocr_system/params.py）
ADD https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar /PaddleOCR/inference/
RUN tar xf /PaddleOCR/inference/ch_ppocr_mobile_v2.0_rec_infer.tar -C /PaddleOCR/inference/

EXPOSE 8868

CMD ["/bin/bash","-c","hub install deploy/hubserving/ocr_system/ && hub serving start -m ocr_system"]
```
构建镜像
```shell
cd deploy/docker/hubserving/cpu
docker buildx build --platform linux/arm64/v8 -t paddleocr:cpu-m1 .
```
启动
```shell
sudo docker run -dp 8868:8868 --name paddle_ocr paddleocr:cpu-m1
```

- 完整报错/Complete Error Message：
```text
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
Error: AVX is not support on your machine, but you have installed paddlepaddle without no_avx core, you should reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/mkl/stable/noavx.html or https://paddlepaddle.org.cn/whl/openblas/stable/noavx.html
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/lib/python3.7/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
  File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 26, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 369, in <module>
    raise e
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 316, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
```

**Comment by andyjpaddle** [comment]
建议用高版本的paddle，推荐2.2.1

**Comment by dragon-zhang** [comment]
有用的，乐意的话，我想更新下cpu的dockerfile和修正一些文档，这几天才了不少坑 @andyjpaddle

**Comment by andyjpaddle** [comment]
好的

**Comment by FlickerMi** [comment]
还是不行。

```
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "/opt/conda/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/opt/conda/lib/python3.8/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
  File "/opt/conda/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/core.py", line 365, in <module>
    raise e
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/core.py", line 313, in <module>
    from . import core_noavx
ImportError: cannot import name 'core_noavx' from partially initialized module 'paddle.fluid' (most likely due to a circular import) (/opt/conda/lib/python3.8/site-packages/paddle/fluid/__init__.py)
```

**Comment by yoeaki** [comment]
> 还是不行。
> 
> ```
> Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
> Traceback (most recent call last):
>   File "/opt/conda/bin/hub", line 5, in <module>
>     from paddlehub.commands.utils import execute
>   File "/opt/conda/lib/python3.8/site-packages/paddlehub/__init__.py", line 18, in <module>
>     import paddle
>   File "/opt/conda/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
>     from .framework import monkey_patch_variable
>   File "/opt/conda/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
>     from . import random  # noqa: F401
>   File "/opt/conda/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
>     import paddle.fluid as fluid
>   File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
>     from . import framework
>   File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
>     from . import core
>   File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/core.py", line 365, in <module>
>     raise e
>   File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/core.py", line 313, in <module>
>     from . import core_noavx
> ImportError: cannot import name 'core_noavx' from partially initialized module 'paddle.fluid' (most likely due to a circular import) (/opt/conda/lib/python3.8/site-packages/paddle/fluid/__init__.py)
> ```

大佬，这个问题有解决方案么？
