### ISSUE TITLE
No schema registered for 'ScaledTanh'

### ISSUE THREAD

**Issue by ziyeZzz** [PaddlePaddle/PaddleOCR#5289]
您好，我正在尝试将导出的.onnx模型转换成.DLC模型。
所使用的模型为：[官方页面](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md)中的en_number_mobile_slim_v2.0_rec

我在环境1下将下载的inference模型转成了onnx模型，此步没有报错：
【环境1】python==3.7, paddleocr==2.3.0.2, paddlepaddle==2.2.1, paddle2onnx==0.9.0

然后我在环境2下将转好的onnx模型转成DLC模型，会报错：
【环境2】python==3.5, snpe == 1.14.1, onnx ==1.8.1

报错信息如下：
`Traceback (most recent call last):
  File "/home/tina/softwares/SNPE/snpe-1.41.0.2173/bin/x86_64-linux-clang/snpe-onnx-to-dlc", line 20, in <module>
    from qti.aisw.converters import onnx as onnx_converter
  File "/home/tina/softwares/SNPE/snpe-1.41.0.2173/lib/python/qti/aisw/converters/onnx/__init__.py", line 14, in <module>
    from . import math_translations
  File "/home/tina/softwares/SNPE/snpe-1.41.0.2173/lib/python/qti/aisw/converters/onnx/math_translations.py", line 740, in <module>
    OnnxTranslations.register_translation(OnnxTanhTranslation(),
  File "/home/tina/softwares/SNPE/snpe-1.41.0.2173/lib/python/qti/aisw/converters/onnx/math_translations.py", line 724, in __init__
    self.register_op_schema('ScaledTanh', [1, 6])
  File "/home/tina/softwares/SNPE/snpe-1.41.0.2173/lib/python/qti/aisw/converters/onnx/onnx_translations.py", line 69, in register_op_schema
    schema = defs.get_schema(name, version, '')
onnx.onnx_cpp2py_export.defs.SchemaError: No schema registered for 'ScaledTanh'!
`

请问这个问题该如何解决呢？感谢回复。

**Comment by tink2123** [comment]
DLC的模型之前没有验证过，可以看下是否是onnx转DLC时有不支持的op呢？可以去snpe下问问哈
