### ISSUE TITLE
按照教程做det的时候，报Null geometry supports no operations

### ISSUE THREAD

**Issue by MA-Aaron** [PaddlePaddle/PaddleOCR#5310]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS bigsurf
- 版本号/Version：Paddle：2.2.2   PaddleOCR：2.3 问题相关组件/Related components：predict_det
- 
- 运行指令/Command Code：`python3 tools/infer/predict_det.py --image_dir="./doc/imgs/1.jpg" --det_model_dir="./ch_ppocr_mobile_v2.0_det_infer/"  --use_gpu=Fals`
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 255, in <module>
    dt_boxes, _ = text_detector(img)
  File "tools/infer/predict_det.py", line 218, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "/Users/yunfma/other_repo/PaddlePaddle/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 189, in __call__
    src_w, src_h)
  File "/Users/yunfma/other_repo/PaddlePaddle/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 88, in boxes_from_bitmap
    box = self.unclip(points).reshape(-1, 1, 2)
  File "/Users/yunfma/other_repo/PaddlePaddle/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 105, in unclip
    distance = poly.area * unclip_ratio / poly.length
  File "/Users/yunfma/.conda/envs/PaddleOCR/lib/python3.7/site-packages/shapely/geometry/base.py", line 440, in area
    return self.impl['area'](self)
  File "/Users/yunfma/.conda/envs/PaddleOCR/lib/python3.7/site-packages/shapely/topology.py", line 55, in __call__
    self._validate(this)
  File "/Users/yunfma/.conda/envs/PaddleOCR/lib/python3.7/site-packages/shapely/topology.py", line 18, in _validate
    raise ValueError("Null geometry supports no operations")
ValueError: Null geometry supports no operations

```

rec的时候就不会有问题

**Comment by WenmuZhou** [comment]
你好，我这边正常输出哦 
![image](https://user-images.githubusercontent.com/12406017/150468397-e859a78e-a616-4fbb-a81d-18aa797fbc8f.png)

我的Shapely版本为1.8.0
