### ISSUE TITLE
paddleocr infer_rec打包失败framework_pb2

### ISSUE THREAD

**Issue by that-learner** [PaddlePaddle/PaddleOCR#5326]
PaddleOCR识别模型打包正常，运行报错No module named 'framework_pb2 pyinstaller -F infer_rec.py
记录于2022/1/24

- 系统环境/windows 64bit：
- 版本号/PaddleOCR：paddlepaddle==2.2
- 运行指令/Command Code：打包的dist文件夹运行infer_rec.exe
- 完整报错/ File "paddle\fluid\proto\pass_desc_pb2.py", line 15, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

**Comment by andyjpaddle** [comment]
可否提供一下完整的报错信息？

**Comment by that-learner** [comment]
(paddleocr) D:\PaddleOCR\tools\dist>infer_rec.exe
Traceback (most recent call last):
  File "paddle\fluid\ir.py", line 23, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 15, in <module>
    import framework_pb2 as framework__pb2
ModuleNotFoundError: No module named 'framework_pb2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer_rec.py", line 32, in <module>
    import paddle
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\spawn.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\utils.py", line 28, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\fleet\__init__.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\distributed\fleet\base\fleet_base.py", line 31, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\fluid\ir.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 15, in <module>
    import framework_pb2 as framework__pb2
ModuleNotFoundError: No module named 'framework_pb2'
[43652] Failed to execute script 'infer_rec' due to unhandled exception!

**Comment by xushengfeng** [comment]
我是将 site-packages/paddle/fluid/中的proto文件夹复制到生成的dist/paddle/fluid/下

**Comment by Kromtar** [comment]
I have the same problem :(

**Comment by geoexploring** [comment]
我的这样改就可以了：

`Lib\site-packages\paddle\fluid\proto\pass_desc_pb2.py`下，将`import framework_pb2 as framework__pb2`改成`import paddle.fluid.proto.framework_pb2 as framework__pb2`。

**Comment by myCout** [comment]
@xushengfeng 试了下你的方案，我的还是报这个错；
@geoexploring 按照你的方式试了，报新的错误：
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\__init__.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\dataset\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\dataset\flowers.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "paddle\dataset\image.py", line 48, in <module>
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1252, in _get_handles
OSError: [WinError 6] 句柄无效。
还得继续折腾。

**Comment by shoou** [comment]
paddle\dataset\image.py has suppress process bug: it opens many processes. if you don't want cv2 you can change it like this:

source:

# FIXME(minqiyang): this is an ugly fix for the numpy bug reported here
# https://github.com/numpy/numpy/issues/12497
if six.PY3:
    import subprocess
    import sys
    import os
    interpreter = sys.executable
    # Note(zhouwei): if use Python/C 'PyRun_SimpleString', 'sys.executable'
    # will be the C++ execubable on Windows
    if sys.platform == 'win32' and 'python.exe' not in interpreter:
        interpreter = sys.exec_prefix + os.sep + 'python.exe'
    import_cv2_proc = subprocess.Popen(
        [interpreter, "-c", "import cv2"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)
    out, err = import_cv2_proc.communicate()
    retcode = import_cv2_proc.poll()
    if retcode != 0:
        cv2 = None
    else:
        import cv2
else:
    try:
        import cv2
    except ImportError:
        cv2 = None

change to below:
try:
    import cv2
except:
    cv2 = None

**Comment by BND-lhr** [comment]
@shoou it works

**Comment by Bug-Mr** [comment]
第一，我是将 site-packages/paddle/fluid/中的proto文件夹复制到生成的dist/paddle/fluid/下
第二，Lib\site-packages\paddle\fluid\proto\pass_desc_pb2.py下，将import framework_pb2 as framework__pb2改成import paddle.fluid.proto.framework_pb2 as framework__pb2。

做完两步后报错：
`
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\paddleocr.py", line 33, in <module>
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'tools'

`

**Comment by DYF-AI** [comment]
> 第一，我是将 site-packages/paddle/fluid/中的proto文件夹复制到生成的dist/paddle/fluid/下 第二，Lib\site-packages\paddle\fluid\proto\pass_desc_pb2.py下，将import framework_pb2 as framework__pb2改成import paddle.fluid.proto.framework_pb2 as framework__pb2。
> 
> 做完两步后报错： ` Traceback (most recent call last): File "main.py", line 1, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "paddleocr__init__.py", line 14, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "paddleocr\paddleocr.py", line 33, in File "importlib__init__.py", line 127, in import_module ModuleNotFoundError: No module named 'tools'
> 
> `

我也是，前两步都可以了，有出现如下问题：
(paddle) G:\dongyongfei786\multimodal-lm\third_party\ppocrlabel-pil\dist>PPOCRLabel.exe
Traceback (most recent call last):
  File "ppocrlabel-pil\PPOCRLabel.py", line 41, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "paddleocr\paddleocr.py", line 43, in <module>
  File "paddleocr\paddleocr.py", line 37, in _import_file
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\21702\\AppData\\Local\\Temp\\_MEI271362\\paddleocr\\tools/__init__.py'
[7336] Failed to execute script 'PPOCRLabel' due to unhandled exception!

**Comment by bigbox12138** [comment]
> 我用的方法不需要搞这些，也简单，啥都不用搞，配置好直接打包就行啦
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月4日(周一) 晚上10:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleOCR] paddleocr infer_rec打包失败framework_pb2 (Issue #5326) 第一，我是将 site-packages/paddle/fluid/中的proto文件夹复制到生成的dist/paddle/fluid/下 第二，Lib\site-packages\paddle\fluid\proto\pass_desc_pb2.py下，将import framework_pb2 as framework__pb2改成import paddle.fluid.proto.framework_pb2 as framework__pb2。 做完两步后报错： ` Traceback (most recent call last): File "main.py", line 1, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "paddleocr__init__.py", line 14, in File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module File "paddleocr\paddleocr.py", line 33, in File "importlib__init__.py", line 127, in import_module ModuleNotFoundError: No module named 'tools' ` 我也是，前两步都可以了，有出现如下问题： (paddle) G:\dongyongfei786\multimodal-lm\third_party\ppocrlabel-pil\dist&gt;PPOCRLabel.exe Traceback (most recent call last): File "ppocrlabel-pil\PPOCRLabel.py", line 41, in from paddleocr import PaddleOCR, PPStructure File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "paddleocr_init.py", line 14, in File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "paddleocr\paddleocr.py", line 43, in File "paddleocr\paddleocr.py", line 37, in _import_file File "", line 839, in exec_module File "", line 975, in get_code File "", line 1032, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\21702\AppData\Local\Temp\_MEI271362\paddleocr\tools/init.py' [7336] Failed to execute script 'PPOCRLabel' due to unhandled exception! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问您是使用的什么方法呢？
