### ISSUE TITLE
centos7部署hub服务模式报错

### ISSUE THREAD

**Issue by fociceo** [PaddlePaddle/PaddleOCR#533]
按照官方的serving配置说明，做到了hub install deploy/hubserving/ocr_system/命令，等了很久后，报如下错误：
Traceback (most recent call last):
  File "/usr/local/python3/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 199, in install_module
    self.all_modules(update=False)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 84, in check_module_valid
    return True, {'version': version, 'name': _item._name}
UnboundLocalError: local variable 'version' referenced before assignment

**Comment by littletomatodonkey** [comment]
https://github.com/PaddlePaddle/PaddleHub/blob/a6fb66311bbc3b5c5c4fc44dbfdfb5222b038e3b/paddlehub/module/manager.py#L81

**Comment by fociceo** [comment]
昨天下午5点下的代码，取得dev分支，是在paddleocr下执行，内网得centos7服务器。

**Comment by Steffy-zxf** [comment]
你好！请查看下$HUB_HOME/.paddlehub/modules/ 下 是否有 ocr_system/文件夹。$HUB_HOME诗歌环境变量，如果没有修改就是$HOME，即所有的module都会存放在`~/.paddlehub/modules/ `下。
如果有的话，请删除这个文件夹。之后运行
```shell
$ export PYTHONPATH=Path/to/PaddleOCR_repo/

$ hub install deploy/hubserving/ocr_system/
```

**Comment by fociceo** [comment]
操作后，执行提示：Request Hub-Server unsuccessfully, please check your network.
难道，不能在离线环境下安装。

**Comment by ShenYuhan** [comment]
离线环境可以直接安装包，这个应该没有影响的，我这边试了下是可以的
