### ISSUE TITLE
training PGNET  report an error of "IndexError: list index out of range"

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [PaddlePaddle/PaddleOCR#5376]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.04 
- 版本号/Version：Paddle：  PaddleOCR：PaddlePaddle 2.2.1.post112,  paddleocr2.2  问题相关组件/Related components：PGNET
- 运行指令/Command Code：python3 tools/train.py -c configs/e2e/e2e_r50_vd_pg.yml -o Global.pretrained_model=./pretrain_models/train_step1/best_accuracy Global.load_static_weights=False

- 完整报错/Complete Error Message：[2022/01/29 09:46:32] root INFO: Architecture : 
[2022/01/29 09:46:32] root INFO:     Backbone : 
[2022/01/29 09:46:32] root INFO:         layers : 50
[2022/01/29 09:46:32] root INFO:         name : ResNet
[2022/01/29 09:46:32] root INFO:     Head : 
[2022/01/29 09:46:32] root INFO:         name : PGHead
[2022/01/29 09:46:32] root INFO:     Neck : 
[2022/01/29 09:46:32] root INFO:         name : PGFPN
[2022/01/29 09:46:32] root INFO:     Transform : None
[2022/01/29 09:46:32] root INFO:     algorithm : PGNet
[2022/01/29 09:46:32] root INFO:     model_type : e2e
[2022/01/29 09:46:32] root INFO: Eval : 
[2022/01/29 09:46:32] root INFO:     dataset : 
[2022/01/29 09:46:32] root INFO:         data_dir : ./train_data/total_text/test
[2022/01/29 09:46:32] root INFO:         label_file_list : ['./train_data/total_text/test/test.txt']
[2022/01/29 09:46:32] root INFO:         name : PGDataSet
[2022/01/29 09:46:32] root INFO:         transforms : 
[2022/01/29 09:46:32] root INFO:             DecodeImage : 
[2022/01/29 09:46:32] root INFO:                 channel_first : False
[2022/01/29 09:46:32] root INFO:                 img_mode : BGR
[2022/01/29 09:46:32] root INFO:             E2ELabelEncodeTest : None
[2022/01/29 09:46:32] root INFO:             E2EResizeForTest : 
[2022/01/29 09:46:32] root INFO:                 max_side_len : 768
[2022/01/29 09:46:32] root INFO:             NormalizeImage : 
[2022/01/29 09:46:32] root INFO:                 mean : [0.485, 0.456, 0.406]
[2022/01/29 09:46:32] root INFO:                 order : hwc
[2022/01/29 09:46:32] root INFO:                 scale : 1./255.
[2022/01/29 09:46:32] root INFO:                 std : [0.229, 0.224, 0.225]
[2022/01/29 09:46:32] root INFO:             ToCHWImage : None
[2022/01/29 09:46:32] root INFO:             KeepKeys : 
[2022/01/29 09:46:32] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'texts', 'ignore_tags', 'img_id']
[2022/01/29 09:46:32] root INFO:     loader : 
[2022/01/29 09:46:32] root INFO:         batch_size_per_card : 1
[2022/01/29 09:46:32] root INFO:         drop_last : False
[2022/01/29 09:46:32] root INFO:         num_workers : 2
[2022/01/29 09:46:32] root INFO:         shuffle : False
[2022/01/29 09:46:32] root INFO: Global : 
[2022/01/29 09:46:32] root INFO:     cal_metric_during_train : False
[2022/01/29 09:46:32] root INFO:     character_dict_path : ppocr/utils/ic15_dict.txt
[2022/01/29 09:46:32] root INFO:     character_type : EN
[2022/01/29 09:46:32] root INFO:     checkpoints : None
[2022/01/29 09:46:32] root INFO:     debug : False
[2022/01/29 09:46:32] root INFO:     distributed : False
[2022/01/29 09:46:32] root INFO:     epoch_num : 600
[2022/01/29 09:46:32] root INFO:     eval_batch_step : [0, 1000]
[2022/01/29 09:46:32] root INFO:     infer_img : None
[2022/01/29 09:46:32] root INFO:     load_static_weights : False
[2022/01/29 09:46:32] root INFO:     log_smooth_window : 20
[2022/01/29 09:46:32] root INFO:     max_text_length : 50
[2022/01/29 09:46:32] root INFO:     max_text_nums : 30
[2022/01/29 09:46:32] root INFO:     pretrained_model : ./pretrain_models/train_step1/best_accuracy
[2022/01/29 09:46:32] root INFO:     print_batch_step : 10
[2022/01/29 09:46:32] root INFO:     save_epoch_step : 10
[2022/01/29 09:46:32] root INFO:     save_inference_dir : None
[2022/01/29 09:46:32] root INFO:     save_model_dir : ./output/pgnet_r50_vd_totaltext/
[2022/01/29 09:46:32] root INFO:     save_res_path : ./output/pgnet_r50_vd_totaltext/predicts_pgnet.txt
[2022/01/29 09:46:32] root INFO:     tcl_len : 64
[2022/01/29 09:46:32] root INFO:     use_gpu : True
[2022/01/29 09:46:32] root INFO:     use_visualdl : False
[2022/01/29 09:46:32] root INFO:     valid_set : totaltext
[2022/01/29 09:46:32] root INFO: Loss : 
[2022/01/29 09:46:32] root INFO:     max_text_length : 50
[2022/01/29 09:46:32] root INFO:     max_text_nums : 30
[2022/01/29 09:46:32] root INFO:     name : PGLoss
[2022/01/29 09:46:32] root INFO:     pad_num : 36
[2022/01/29 09:46:32] root INFO:     tcl_bs : 64
[2022/01/29 09:46:32] root INFO: Metric : 
[2022/01/29 09:46:32] root INFO:     character_dict_path : ppocr/utils/ic15_dict.txt
[2022/01/29 09:46:32] root INFO:     gt_mat_dir : ./train_data/total_text/gt
[2022/01/29 09:46:32] root INFO:     main_indicator : f_score_e2e
[2022/01/29 09:46:32] root INFO:     mode : A
[2022/01/29 09:46:32] root INFO:     name : E2EMetric
[2022/01/29 09:46:32] root INFO: Optimizer : 
[2022/01/29 09:46:32] root INFO:     beta1 : 0.9
[2022/01/29 09:46:32] root INFO:     beta2 : 0.999
[2022/01/29 09:46:32] root INFO:     lr : 
[2022/01/29 09:46:32] root INFO:         learning_rate : 0.001
[2022/01/29 09:46:32] root INFO:     name : Adam
[2022/01/29 09:46:32] root INFO:     regularizer : 
[2022/01/29 09:46:32] root INFO:         factor : 0
[2022/01/29 09:46:32] root INFO:         name : L2
[2022/01/29 09:46:32] root INFO: PostProcess : 
[2022/01/29 09:46:32] root INFO:     mode : fast
[2022/01/29 09:46:32] root INFO:     name : PGPostProcess
[2022/01/29 09:46:32] root INFO:     score_thresh : 0.5
[2022/01/29 09:46:32] root INFO: Train : 
[2022/01/29 09:46:32] root INFO:     dataset : 
[2022/01/29 09:46:32] root INFO:         data_dir : ./train_data/total_text/train
[2022/01/29 09:46:32] root INFO:         label_file_list : ['./train_data/total_text/train/train.txt']
[2022/01/29 09:46:32] root INFO:         name : PGDataSet
[2022/01/29 09:46:32] root INFO:         ratio_list : [1.0]
[2022/01/29 09:46:32] root INFO:         transforms : 
[2022/01/29 09:46:32] root INFO:             DecodeImage : 
[2022/01/29 09:46:32] root INFO:                 channel_first : False
[2022/01/29 09:46:32] root INFO:                 img_mode : BGR
[2022/01/29 09:46:32] root INFO:             E2ELabelEncodeTrain : None
[2022/01/29 09:46:32] root INFO:             PGProcessTrain : 
[2022/01/29 09:46:32] root INFO:                 batch_size : 14
[2022/01/29 09:46:32] root INFO:                 max_text_size : 512
[2022/01/29 09:46:32] root INFO:                 min_crop_size : 24
[2022/01/29 09:46:32] root INFO:                 min_text_size : 4
[2022/01/29 09:46:32] root INFO:             KeepKeys : 
[2022/01/29 09:46:32] root INFO:                 keep_keys : ['images', 'tcl_maps', 'tcl_label_maps', 'border_maps', 'direction_maps', 'training_masks', 'label_list', 'pos_list', 'pos_mask']
[2022/01/29 09:46:32] root INFO:     loader : 
[2022/01/29 09:46:32] root INFO:         batch_size_per_card : 8
[2022/01/29 09:46:32] root INFO:         drop_last : True
[2022/01/29 09:46:32] root INFO:         num_workers : 16
[2022/01/29 09:46:32] root INFO:         shuffle : True
[2022/01/29 09:46:32] root INFO: train with paddle 2.2.1 and device CUDAPlace(0)
[2022/01/29 09:46:32] root INFO: Initialize indexs of datasets:['./train_data/total_text/train/train.txt']
[2022/01/29 09:46:32] root INFO: Initialize indexs of datasets:['./train_data/total_text/test/test.txt']
W0129 09:46:32.298952  5439 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0129 09:46:32.300602  5439 device_context.cc:465] device: 0, cuDNN Version: 8.1.
[2022/01/29 09:46:34] root INFO: loaded pretrained_model successful from ./pretrain_models/train_step1/best_accuracy.pdparams
[2022/01/29 09:46:34] root INFO: train dataloader has 181 iters
[2022/01/29 09:46:34] root INFO: valid dataloader has 300 iters
[2022/01/29 09:46:34] root INFO: During the training process, after the 0th iteration, an evaluation is run every 1000 iterations
[2022/01/29 09:46:34] root INFO: Initialize indexs of datasets:['./train_data/total_text/train/train.txt']
[2022/01/29 09:46:47] root INFO: epoch: [1/600], iter: 10, lr: 0.001000, loss: 46.366352, score_loss: 0.590153, border_loss: 0.550790, direction_loss: 0.121632, ctc_loss: 9.101222, reader_cost: 0.29893 s, batch_cost: 1.26409 s, samples: 88, ips: 6.96151
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 106, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/jeck/Public/PaddleOCR/tools/program.py", line 222, in train
    loss = loss_class(preds, batch)
  File "/home/jeck/miniconda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jeck/Public/PaddleOCR/ppocr/losses/e2e_pg_loss.py", line 119, in forward
    pos_list, pos_mask, label_list, label_t = pre_process(
  File "/home/jeck/Public/PaddleOCR/ppocr/utils/e2e_utils/extract_batchsize.py", line 69, in pre_process
    pos_list, pos_mask, label_list = org_tcl_rois(batch, pos_list_t, pos_mask_t,
  File "/home/jeck/Public/PaddleOCR/ppocr/utils/e2e_utils/extract_batchsize.py", line 25, in org_tcl_rois
    pos_lists_split[gpu_id].append(pos_list)
IndexError: list index out of range

**Comment by wanggoudanscd** [comment]
将e2e_r50_vd_pg.yml中的Train与loader中的batchsize改为一致的
