### ISSUE TITLE
PPOCRLabel 使用自定义模型發生錯誤

### ISSUE THREAD

**Issue by kenhuang115** [PaddlePaddle/PaddleOCR#5423]
- 系统环境/System Environment：Windows 10
- 版本号/Version： PaddleOCR2.2
- 运行指令/Command Code：
![image](https://user-images.githubusercontent.com/54389569/153328036-e34c9380-8d05-4ad3-ac77-c88a045a2ab8.png)
按照教學更改 self.ocr後運行指令python PPOCRLabel.py --lang ch 就發生以下錯誤

- 完整报错/Complete Error Message：
[2022/02/10 10:44:30] root WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2091, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2079, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2072, in get_main_app
    defaultPrefdefClassFile=args.predefined_classes_file)
  File "PPOCRLabel.py", line 118, in __init__
    result = self.ocr.ocr('./data/paddle.png', cls=True, det=True)
  File "C:\Users\Ken\anaconda3\envs\paddle2.2\lib\site-packages\paddleocr\paddleocr.py", line 379, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "C:\Users\Ken\anaconda3\envs\paddle2.2\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 68, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Users\Ken\anaconda3\envs\paddle2.2\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 241, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "..\ppocr\postprocess\db_postprocess.py", line 173, in __call__
    pred = pred[:, 0, :, :]
IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/153358062-53bec49b-3dba-46e7-8b74-f227dceff6d0.png)
这里错了，检测模型的地方用了方向分类器的模型
