### ISSUE TITLE
使用SAST训练检测模型出错

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleOCR#544]
之前是使用east和db训练模型的，发现SAST开源了，就想试试。
1.我想问问使用SAST训练需要注意什么吗？为什么我使用之前处理好的标签和数据集训练SAST会出错，配置文件用哪一个都会出错。
2.请问SAST可以训练弯曲文本吗？那种点数不一致的数据集，譬如lvst2019？如果可以，请问应该做什么处理？谢谢。

**Comment by MissPenguin** [comment]
1. 可以贴一下具体的报错信息看下哈
2. 可以训练弯曲文本的，但点数不一致的话，需要先把数据处理一下，转换成点数一致的标注，可以使用一些类似插值的方式

**Comment by tyy2tyy** [comment]
2020-08-17 11:47:03,524-WARNING: Your reader has raised an exception!
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in                                                                                                                                                              _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in r                                                                                                                                                             un
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/reader/decorator.py",                                                                                                                                                              line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/lib/python3.7/site-packages/six.py", line 703, in rerais                                                                                                                                                             e
    raise value
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/reader/decorator.py",                                                                                                                                                              line 549, in _read_into_queue
    for sample in reader():
  File "tools/../ppocr/data/det/dataset_traversal.py", line 109, in batch_iter_r                                                                                                                                                             eader
    for outs in sample_iter_reader_mul():
  File "tools/../ppocr/data/det/dataset_traversal.py", line 80, in sample_iter_r                                                                                                                                                             eader_mul
    ds = data_size_list[i]
IndexError: list index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inn                                                                                                                                                             er
    self.run()
  File "/root/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", lin                                                                                                                                                             e 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/lib/python3.7/site-packages/six.py", line 703, in rerais                                                                                                                                                             e
    raise value
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", lin                                                                                                                                                             e 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", lin                                                                                                                                                             e 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py"                                                                                                                                                             , line 506, in __reader_creator__
    for item in reader():
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/reader/decorator.py",                                                                                                                                                              line 572, in queue_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception

/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserW                                                                                                                                                             arning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    main()
  File "tools/train.py", line 98, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "tools/../tools/program.py", line 263, in train_eval_det_run
    return_numpy=False)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1071, in run
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/lib/python3.7/site-packages/six.py", line 703, in rerais                                                                                                                                                             e
    raise value
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1066, in run
    return_merged=return_merged)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 1167, in _run_impl
    return_merged=return_merged)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", l                                                                                                                                                             ine 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::st                                                                                                                                                             ring const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char cons                                                                                                                                                             t*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDT                                                                                                                                                             ensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<pad                                                                                                                                                             dle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework:                                                                                                                                                             :LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std                                                                                                                                                             ::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<st                                                                                                                                                             d::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_R                                                                                                                                                             esult_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std                                                                                                                                                             ::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&,                                                                                                                                                              bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py",                                                                                                                                                              line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", lin                                                                                                                                                             e 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", lin                                                                                                                                                             e 976, in __init__
    self._init_non_iterable()
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", lin                                                                                                                                                             e 608, in from_generator
    iterable, return_list, drop_last)
  File "tools/../ppocr/modeling/architectures/det_model.py", line 121, in create                                                                                                                                                             _feed
    iterable=False)
  File "tools/../ppocr/modeling/architectures/det_model.py", line 134, in __call                                                                                                                                                             __
    image, labels, loader = self.create_feed(mode)
  File "tools/../tools/program.py", line 170, in build
    dataloader, outputs = model(mode=mode)
  File "tools/train.py", line 50, in main
    config, train_program, startup_program, mode='train')
  File "tools/train.py", line 123, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddl                                                                                                                                                             e/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by tyy2tyy** [comment]
可以详细说一下处理数据部分吗，类似插值的方式我不是很理解

**Comment by VixeruntR** [comment]
> 
> 
> 可以详细说一下处理数据部分吗，类似插值的方式我不是很理解

就比如（10， 100）和（20， 200）两个点之间 可以加入一个（15， 150） 保持点的数目一致[以最多数量的点标签为准]

**Comment by tyy2tyy** [comment]
好的，谢谢
