### ISSUE TITLE
rare算法报错

### ISSUE THREAD

**Issue by guanrenxue** [PaddlePaddle/PaddleOCR#5472]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：anaconda
- 版本号/Version：Paddle：2.2.1  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c configs/rec/rare_rec_r34_vd_tps_bilstm_att.yml
- 完整报错/Complete Error Message：
(ocr) E:\PaddleOCR-2.3>python tools/train.py -c configs/rec/rare_rec_r34_vd_tps_bilstm_att.yml
[2022/02/14 17:29:18] root INFO: Architecture :
[2022/02/14 17:29:18] root INFO:     Backbone :
[2022/02/14 17:29:18] root INFO:         layers : 34
[2022/02/14 17:29:18] root INFO:         name : ResNet
[2022/02/14 17:29:18] root INFO:     Head :
[2022/02/14 17:29:18] root INFO:         hidden_size : 256
[2022/02/14 17:29:18] root INFO:         l2_decay : 1e-05
[2022/02/14 17:29:18] root INFO:         name : AttentionHead
[2022/02/14 17:29:18] root INFO:     Neck :
[2022/02/14 17:29:18] root INFO:         encoder_type : rnn
[2022/02/14 17:29:18] root INFO:         hidden_size : 256
[2022/02/14 17:29:18] root INFO:         name : SequenceEncoder
[2022/02/14 17:29:18] root INFO:     Transform :
[2022/02/14 17:29:18] root INFO:         loc_lr : 0.1
[2022/02/14 17:29:18] root INFO:         model_name : large
[2022/02/14 17:29:18] root INFO:         name : TPS
[2022/02/14 17:29:18] root INFO:         num_fiducial : 20
[2022/02/14 17:29:18] root INFO:     algorithm : RARE
[2022/02/14 17:29:18] root INFO:     model_type : rec
[2022/02/14 17:29:18] root INFO: Eval :
[2022/02/14 17:29:18] root INFO:     dataset :
[2022/02/14 17:29:18] root INFO:         data_dir : ./train_data/rec_dataset/
[2022/02/14 17:29:18] root INFO:         label_file_list : ['./train_data/rec_dataset/val_1000.txt']
[2022/02/14 17:29:18] root INFO:         name : SimpleDataSet
[2022/02/14 17:29:18] root INFO:         transforms :
[2022/02/14 17:29:18] root INFO:             DecodeImage :
[2022/02/14 17:29:18] root INFO:                 channel_first : False
[2022/02/14 17:29:18] root INFO:                 img_mode : BGR
[2022/02/14 17:29:18] root INFO:             AttnLabelEncode : None
[2022/02/14 17:29:18] root INFO:             RecResizeImg :
[2022/02/14 17:29:18] root INFO:                 image_shape : [3, 32, 640]
[2022/02/14 17:29:18] root INFO:             KeepKeys :
[2022/02/14 17:29:18] root INFO:                 keep_keys : ['image', 'label', 'length']
[2022/02/14 17:29:18] root INFO:     loader :
[2022/02/14 17:29:18] root INFO:         batch_size_per_card : 16
[2022/02/14 17:29:18] root INFO:         drop_last : False
[2022/02/14 17:29:18] root INFO:         num_workers : 8
[2022/02/14 17:29:18] root INFO:         shuffle : False
[2022/02/14 17:29:18] root INFO:         use_shared_memory : False
[2022/02/14 17:29:18] root INFO: Global :
[2022/02/14 17:29:18] root INFO:     cal_metric_during_train : True
[2022/02/14 17:29:18] root INFO:     character_dict_path : ./train_data/rec_dataset/alphabet0830.txt
[2022/02/14 17:29:18] root INFO:     character_type : ch
[2022/02/14 17:29:18] root INFO:     checkpoints : None
[2022/02/14 17:29:18] root INFO:     debug : False
[2022/02/14 17:29:18] root INFO:     distributed : False
[2022/02/14 17:29:18] root INFO:     epoch_num : 100
[2022/02/14 17:29:18] root INFO:     eval_batch_step : [0, 378]
[2022/02/14 17:29:18] root INFO:     infer_img : doc/imgs_words/ch/word_1.jpg
[2022/02/14 17:29:18] root INFO:     infer_mode : False
[2022/02/14 17:29:18] root INFO:     log_smooth_window : 20
[2022/02/14 17:29:18] root INFO:     max_text_length : 118
[2022/02/14 17:29:18] root INFO:     pretrained_model : None
[2022/02/14 17:29:18] root INFO:     print_batch_step : 10
[2022/02/14 17:29:18] root INFO:     save_epoch_step : 3
[2022/02/14 17:29:18] root INFO:     save_inference_dir : None
[2022/02/14 17:29:18] root INFO:     save_model_dir : ./output/rec_rare/
[2022/02/14 17:29:18] root INFO:     save_res_path : ./output/rec_rare/predicts_rare.txt
[2022/02/14 17:29:18] root INFO:     use_gpu : True
[2022/02/14 17:29:18] root INFO:     use_space_char : True
[2022/02/14 17:29:18] root INFO:     use_visualdl : False
[2022/02/14 17:29:18] root INFO: Loss :
[2022/02/14 17:29:18] root INFO:     name : AttentionLoss
[2022/02/14 17:29:18] root INFO: Metric :
[2022/02/14 17:29:18] root INFO:     main_indicator : acc
[2022/02/14 17:29:18] root INFO:     name : RecMetric
[2022/02/14 17:29:18] root INFO: Optimizer :
[2022/02/14 17:29:18] root INFO:     beta1 : 0.9
[2022/02/14 17:29:18] root INFO:     beta2 : 0.999
[2022/02/14 17:29:18] root INFO:     lr :
[2022/02/14 17:29:18] root INFO:         learning_rate : 0.0005
[2022/02/14 17:29:18] root INFO:     name : Adam
[2022/02/14 17:29:18] root INFO:     regularizer :
[2022/02/14 17:29:18] root INFO:         factor : 0.0
[2022/02/14 17:29:18] root INFO:         name : L2
[2022/02/14 17:29:18] root INFO: PostProcess :
[2022/02/14 17:29:18] root INFO:     name : AttnLabelDecode
[2022/02/14 17:29:18] root INFO: Train :
[2022/02/14 17:29:18] root INFO:     dataset :
[2022/02/14 17:29:18] root INFO:         data_dir : ./train_data/rec_dataset/
[2022/02/14 17:29:18] root INFO:         label_file_list : ['./train_data/rec_dataset/train_6055.txt']
[2022/02/14 17:29:18] root INFO:         name : SimpleDataSet
[2022/02/14 17:29:18] root INFO:         transforms :
[2022/02/14 17:29:18] root INFO:             DecodeImage :
[2022/02/14 17:29:18] root INFO:                 channel_first : False
[2022/02/14 17:29:18] root INFO:                 img_mode : BGR
[2022/02/14 17:29:18] root INFO:             AttnLabelEncode : None
[2022/02/14 17:29:18] root INFO:             RecResizeImg :
[2022/02/14 17:29:18] root INFO:                 image_shape : [3, 32, 640]
[2022/02/14 17:29:18] root INFO:             KeepKeys :
[2022/02/14 17:29:18] root INFO:                 keep_keys : ['image', 'label', 'length']
[2022/02/14 17:29:18] root INFO:     loader :
[2022/02/14 17:29:18] root INFO:         batch_size_per_card : 16
[2022/02/14 17:29:18] root INFO:         drop_last : True
[2022/02/14 17:29:18] root INFO:         num_workers : 8
[2022/02/14 17:29:18] root INFO:         shuffle : True
[2022/02/14 17:29:18] root INFO:         use_shared_memory : False
[2022/02/14 17:29:18] root INFO: train with paddle 2.2.1 and device CUDAPlace(0)
[2022/02/14 17:29:18] root INFO: Initialize indexs of datasets:['./train_data/rec_dataset/train_6055.txt']
[2022/02/14 17:29:18] root INFO: Initialize indexs of datasets:['./train_data/rec_dataset/val_1000.txt']
W0214 17:29:18.660154  6396 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 10.2
W0214 17:29:18.670126  6396 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[2022/02/14 17:29:20] root INFO: train dataloader has 378 iters
[2022/02/14 17:29:20] root INFO: valid dataloader has 63 iters
[2022/02/14 17:29:20] root INFO: During the training process, after the 0th iteration, an evaluation is run every 378 iterations
[2022/02/14 17:29:20] root INFO: Initialize indexs of datasets:['./train_data/rec_dataset/train_6055.txt']
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 108, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "E:\PaddleOCR-2.3\tools\program.py", line 222, in train
    loss = loss_class(preds, batch)
  File "D:\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\PaddleOCR-2.3\ppocr\losses\rec_att_loss.py", line 39, in forward
    return {'loss': paddle.sum(self.loss_func(inputs, targets))}
  File "D:\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\ocr\lib\site-packages\paddle\nn\layer\loss.py", line 406, in forward
    name=self.name)
  File "D:\Anaconda3\envs\ocr\lib\site-packages\paddle\nn\functional\loss.py", line 1676, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:400 != labels_dims[i]:1888.] (at ..\paddle/fluid/operators/softmax_with_cross_entropy_op.cc:16
3)
  [operator < softmax_with_cross_entropy > error]

**Comment by tink2123** [comment]
请问使用的是PaddleOCR哪个分支的代码呢？

**Comment by guanrenxue** [comment]
使用的是paddleocr2.3版本的

**Comment by guanrenxue** [comment]
> 请问使用的是PaddleOCR哪个分支的代码呢？
使用的是paddleocr-2.3版本的

**Comment by tink2123** [comment]
我这边没有复现报错，请问除了配置文件，还修改了其他代码吗？

**Comment by guanrenxue** [comment]
没有进行其他修改，使用crnn，nrtr训练都没问题，唯独rare算法，报了损失函数的错误，提示维度不一致，是不是我用的paddle版本太高的缘故，此时用的版本paddle_gpu=2.2.1 ,报的错误为：
Traceback (most recent call last):
&nbsp; File "tools/train.py", line 131, in <module&gt;
&nbsp; &nbsp; main(config, device, logger, vdl_writer)
&nbsp; File "tools/train.py", line 108, in main
&nbsp; &nbsp; eval_class, pre_best_model_dict, logger, vdl_writer)
&nbsp; File "E:\PaddleOCR-2.3\tools\program.py", line 222, in train
&nbsp; &nbsp; loss = loss_class(preds, batch)
&nbsp; File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
&nbsp; &nbsp; return self._dygraph_call_func(*inputs, **kwargs)
&nbsp; File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
&nbsp; &nbsp; outputs = self.forward(*inputs, **kwargs)
&nbsp; File "E:\PaddleOCR-2.3\ppocr\losses\rec_att_loss.py", line 39, in forward
&nbsp; &nbsp; return {'loss': paddle.sum(self.loss_func(inputs, targets))}
&nbsp; File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
&nbsp; &nbsp; return self._dygraph_call_func(*inputs, **kwargs)
&nbsp; File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
&nbsp; &nbsp; outputs = self.forward(*inputs, **kwargs)
&nbsp; File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\nn\layer\loss.py", line 406, in forward
&nbsp; &nbsp; name=self.name)
&nbsp; File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\loss.py", line 1667, in cross_entropy
&nbsp; &nbsp; 'use_softmax', use_softmax)
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
&nbsp; [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:100 != labels_dims[i]:472.] (at ..\paddle/fluid/operators/softmax_with_cross_entropy_op.cc:163
)
&nbsp; [operator < softmax_with_cross_entropy &gt; error]







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] rare算法报错 (Issue #5472)





 
我这边没有复现报错，请问除了配置文件，还修改了其他代码吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by developWmark** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/2865 相似问题请问一下这个修复了吗

**Comment by HouYanGG** [comment]
> 我也遇到这个问题了

我也遇到这个问题了，crnn的Rosetta对应同样的数据集都不报错，只有rare这个说维度不匹配

**Comment by HouYanGG** [comment]
> 我这边没有复现报错，请问除了配置文件，还修改了其他代码吗？

您好，问下您是哪个版本的代码呀，我用2.2版本的代码rare算法出现问题，crnn的Rosetta对应同样的数据集都不报错，只有rare这个说维度不匹配
