### ISSUE TITLE
AttributeError: 'Program' object has no attribute '_remove_training_info'

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#5557]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda11.2-cudnn8 /bin/bash`
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：`PaddleServing`
- 运行指令/Command Code：
```
python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv2_det_infer/ \
                                         --model_filename inference.pdmodel          \
                                         --params_filename inference.pdiparams       \
                                         --serving_server ./ppocrv2_det_serving/ \
                                         --serving_client ./ppocrv2_det_client/
```
- 完整报错/Complete Error Message：
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_client/convert.py", line 87, in <module>
    fetch_alias_names=args.fetch_alias_names)
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_client/io/__init__.py", line 334, in inference_model_to_serving
    model_filename, params_filename, show_proto, feed_alias_names, fetch_alias_names)
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_client/io/__init__.py", line 214, in save_model
    new_model_file.write(main_program._remove_training_info(False).desc.serialize_to_string())
AttributeError: 'Program' object has no attribute '_remove_training_info'
```

您好，我在使用`PaddleServing`进行服务部署时，遇到上述问题，麻烦帮忙定位看下什么原因，多谢

**Comment by thomas-yanxin** [comment]
paddlepaddle版本升级到最新版本可以修复这个问题
