### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'int' and 'list'

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#5559]
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 123, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/hzq/liqian/PaddleOCR-release-2.4/tools/program.py", line 361, in train
    if dist.get_rank() == 0 and epoch > 0 and epoch % save_epoch_step == 0:
TypeError: unsupported operand type(s) for %: 'int' and 'list'
训练psenet时出现这种问题

**Comment by WenmuZhou** [comment]
贴一下训练配置和日志吧
