### ISSUE TITLE
Paddle Serving部署失败

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#5567]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
`sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda11.2-cudnn8 /bin/bash`
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
`Paddle Serving`
- 运行指令/Command Code：
`python3 web_service.py &>log.txt &`
- 完整报错/Complete Error Message：

启动部署服务命令后，`log.txt`日志与官方不一致，如下所示：
```
λ kna-nlp-mg-k8s /paddle/PaddleOCR/deploy/pdserving {release/2.4} cat log.txt
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
2022/02/25 03:05:06 start proxy service
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
λ kna-nlp-mg-k8s /paddle/PaddleOCR/deploy/pdserving {release/2.4}
```
且发送服务请求后（`python3 pipeline_http_client.py`），无任何输出，请问这是正常的吗？还是我哪里理解有问题

**Comment by WenmuZhou** [comment]
你好，pipeline_http_client请求过程中，serving服务还在运行吗

**Comment by Biaocsu** [comment]
使用ps -ef | grep python检查了，是的，还在运行

**Comment by WenmuZhou** [comment]
不挂后台盯一下看看

**Comment by Biaocsu** [comment]
> 不挂后台盯一下看看

挂后台没什么区别，你们是否能够自己验证一下。dokcer部署的应该教容易找出问题，而且我也是根据官方文档来的

**Comment by tink2123** [comment]
无任何输出是不对的，看您使用的docker是cuda11.2-cudnn8， 请问serving安装的版本是否也是对应cuda11.2-cudnn8的？另外也可以检测下是否设置了代理，把代理取消掉看看。

**Comment by Biaocsu** [comment]
@tink2123 是的，serving版本没问题为[paddle_serving_server_gpu-0.7.0.post112-py3-none-any.whl](https://paddle-serving.bj.bcebos.com/test-dev/whl/paddle_serving_server_gpu-0.7.0.post112-py3-none-any.whl)，也没有设置代理。这些我都校对确认过

**Comment by tink2123** [comment]
您好，我们校验后均可以正常运行，请您查看下 PipelineServingLogs/pipeline.log 这个目录下是否有报错信息呢？

**Comment by Biaocsu** [comment]
> 您好，我们校验后均可以正常运行，请您查看下 PipelineServingLogs/pipeline.log 这个目录下是否有报错信息呢？

是的，有如下报错信息：
```
CRITICAL 2022-03-02 02:39:32,400 [operator.py:1315] [rec|2] failed to init op: [Errno 2] No such file or directory: './ppocrv2_rec_serving/serving_server_conf.prototxt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_server/pipeline/operator.py", line 1308, in _run
    concurrency_idx)
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_server/pipeline/local_service_handler.py", line 228, in get_client
    mkldnn_bf16_op_list=self._mkldnn_bf16_op_list)
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_app/local_predict.py", line 115, in load_model_config
    f = open(client_config, 'r')
FileNotFoundError: [Errno 2] No such file or directory: './ppocrv2_rec_serving/serving_server_conf.prototxt'
```
但奇怪的是，这个文件明明存在，为什么没找到
