### ISSUE TITLE
Paddle OCR 训练图片时候报错

### ISSUE THREAD

**Issue by kylecj77** [PaddlePaddle/PaddleOCR#5583]
使用的ch_ppocr_server_v2.0_rec_pre这个模型

以下是报错内容：
[2022/02/28 16:51:44] root INFO:             CTCLabelEncode : None
[2022/02/28 16:51:44] root INFO:             RecResizeImg :
[2022/02/28 16:51:44] root INFO:                 image_shape : [3, 64, 220]
[2022/02/28 16:51:44] root INFO:             KeepKeys :
[2022/02/28 16:51:44] root INFO:                 keep_keys : ['image', 'label', 'length']
[2022/02/28 16:51:44] root INFO:     loader :
[2022/02/28 16:51:44] root INFO:         batch_size_per_card : 2
[2022/02/28 16:51:44] root INFO:         drop_last : True
[2022/02/28 16:51:44] root INFO:         num_workers : 8
[2022/02/28 16:51:44] root INFO:         shuffle : True
[2022/02/28 16:51:44] root INFO: profiler_options : None
[2022/02/28 16:51:44] root INFO: train with paddle 2.2.2 and device CPUPlace
[2022/02/28 16:51:44] root INFO: Initialize indexs of datasets:['./RSA/train_data/rec/rec_gt_dev.txt']
[2022/02/28 16:51:44] root INFO: Initialize indexs of datasets:['./RSA/train_data/rec/rec_gt_dev.txt']
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    pre_best_model_dict = load_model(config, model, optimizer)
  File "D:\Worke\Paddle\Rsa\PaddleOCR-release-2.4\ppocr\utils\save_load.py", line 99, in load_model
    load_pretrained_params(model, pretrained_model)
  File "D:\Worke\Paddle\Rsa\PaddleOCR-release-2.4\ppocr\utils\save_load.py", line 119, in load_pretrained_params
    if list(state_dict[k1].shape) == list(params[k1].shape):
TypeError: 'method' object is not iterable

---------------------

以下是设置的Config
Global:
  use_gpu: False
  epoch_num: 4
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./RSA/output/rec_num
  save_epoch_step: 3
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [0, 10]
  cal_metric_during_train: True
  pretrained_model: './RSA/ch_ppocr_server_v2.0_rec_pre/best_accuracy'
  Load_static_weights: True
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: ./RSA/train_data/rec/dev/8.bmp
  # for data or label process
  character_dict_path: ./RSA/RSA_dict.txt
  character_type: ch
  max_text_length: 6
  infer_mode: False
  use_space_char: False
  save_res_path: ./RSA/output/rec/numric

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./RSA/train_data/rec/dev
    label_file_list: ["./RSA/train_data/rec/rec_gt_dev.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 64, 220]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 2
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./RSA/train_data/rec/dev
    label_file_list: ["./RSA/train_data/rec/rec_gt_dev.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 64, 220]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 2
    num_workers: 8

**Comment by littletomatodonkey** [comment]
你好，直接使用ppocrv2模型试下呢？

**Comment by kylecj77** [comment]
是直接使用的库模型。并且修改了参数
使用的CPU

**Comment by littletomatodonkey** [comment]
Load_static_weights参数需要修改为false

**Comment by kylecj77** [comment]
> Load_static_weights参数需要修改为false

Thanks very mach
