### ISSUE TITLE
SRN模型在自己数据集上微调报错 RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by Babysun-ljh** [PaddlePaddle/PaddleOCR#5587]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python 3.8
- 版本号/Version：Paddle： 2.4  PaddleOCR： 问题相关组件/Related components：SRN模型微调
- 运行指令/Command Code： python tools/train.py -c /Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/configs/rec_pda/rec_r50_fpn_srn_finetune.yml

- 完整报错/Complete Error Message：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/cynthia/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/cynthia/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cynthia/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 212, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/Users/cynthia/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 111, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 111, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 111, in __getitem__
    return self.__getitem__(np.random.randint(self.__len__()))
  [Previous line repeated 986 more times]
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 109, in __getitem__
    outs = transform(data, self.ops)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/imaug/__init__.py", line 43, in transform
    data = op(data)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/imaug/operators.py", line 43, in __call__
    img = np.frombuffer(img, dtype='uint8')
RecursionError: maximum recursion depth exceeded in comparison

**Comment by Ginkle** [comment]
你好，我也遇到这个问题，请问你是怎么解决的？

**Comment by Ginkle** [comment]
> 请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
> 
> * 系统环境/System Environment：python 3.8
> * 版本号/Version：Paddle： 2.4  PaddleOCR： 问题相关组件/Related components：SRN模型微调
> * 运行指令/Command Code： python tools/train.py -c /Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/configs/rec_pda/rec_r50_fpn_srn_finetune.yml
> * 完整报错/Complete Error Message：
>   Exception in thread Thread-1:
>   Traceback (most recent call last):
>   File "/Users/cynthia/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>   self.run()
>   File "/Users/cynthia/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
>   self._target(*self._args, **self._kwargs)
>   File "/Users/cynthia/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 212, in _thread_loop
>   batch = self._dataset_fetcher.fetch(indices,
>   File "/Users/cynthia/opt/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
>   data.append(self.dataset[idx])
>   File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 111, in **getitem**
>   return self.**getitem**(np.random.randint(self.**len**()))
>   File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 111, in **getitem**
>   return self.**getitem**(np.random.randint(self.**len**()))
>   File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 111, in **getitem**
>   return self.**getitem**(np.random.randint(self.**len**()))
>   [Previous line repeated 986 more times]
>   File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/lmdb_dataset.py", line 109, in **getitem**
>   outs = transform(data, self.ops)
>   File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/imaug/**init**.py", line 43, in transform
>   data = op(data)
>   File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/data/imaug/operators.py", line 43, in **call**
>   img = np.frombuffer(img, dtype='uint8')
>   RecursionError: maximum recursion depth exceeded in comparison

你好，我也遇到这个问题，请问你是怎么解决的？

**Comment by HanMengdan6** [comment]
你好，我也是遇到同样的问题请问是如何解决的？
