### ISSUE TITLE
自定义词典训练报错

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleOCR#5645]
- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.2  PaddleOCR：2.4 问题相关组件/Related components：自定义词典训练报错
- 运行指令/Command Code：tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml
- 完整报错/Complete Error Message：
- [2022/03/07 14:39:56] root INFO: Initialize indexs of datasets:['d:/ocr/train_data_1_5_2k/lable.txt']
Traceback (most recent call last):
  File "tools/train.py", line 151, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 128, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "D:\work\projects\paddleocr23\PaddleOCR\tools\program.py", line 274, in train
    post_result = post_process_class(preds, batch[1])
  File "D:\work\projects\paddleocr23\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 133, in __call__
    output[name] = super().__call__(pred, label=label, *args, **kwargs)
  File "D:\work\projects\paddleocr23\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 99, in __call__
    label = self.decode(label)
  File "D:\work\projects\paddleocr23\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 68, in decode
    idx])])
IndexError: list index out of range

字典是自定义的，有22236行

**Comment by dengmingD** [comment]
找到原因了，list的索引小于字典的个数减1就好了

**Comment by xiatian114** [comment]
> 找到原因了，list的索引小于字典的个数减1就好了

哥你知道这个怎么改吗
ppocr ERROR: When parsing line
, error happened with msg: Traceback (most recent call last):
  File "D:\PaddleOCR\ppocr\data\simple_dataset.py", line 128, in __getitem__
    label = substr[1]
IndexError: list index out of range
