### ISSUE TITLE
蒸馏训练如何加载自己训练的student与teacher

### ISSUE THREAD

**Issue by AminGeng** [PaddlePaddle/PaddleOCR#5677]
- 系统环境/System Environment：Ubuntu 16.04.7 LTS
- 版本号/Version：Paddle: 2.1.3 PaddleOCR：2.3
- 运行指令/Command Code：python3.8 tools/train.py -c configs/det/ch_PP-OCRv2/ch_PP-OCR_det_dml.yml 
- 所做修改/ 配置文件configs/det/ch_PP-OCRv2/ch_PP-OCR_det_dml.yml, 
    Student:
      pretrained: ./output/ch_db_res18/first/best_accuracy
    Student2:
      pretrained: ./pretrain_models/ch_ppocr_server_v2.0_det_train/best_accuracy
- 完整报错/Complete Error Message：
load pretrain successful from ./output/ch_db_res18/first/best_accuracy.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 83, in main
    model = build_model(config['Architecture'])
  File "/paddle/PPv2/PaddleOCR-release-2.3/ppocr/modeling/architectures/__init__.py", line 31, in build_model
    arch = getattr(mod, name)(config)
  File "/paddle/PPv2/PaddleOCR-release-2.3/ppocr/modeling/architectures/distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "/paddle/PPv2/PaddleOCR-release-2.3/ppocr/modeling/architectures/base_model.py", line 50, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/paddle/PPv2/PaddleOCR-release-2.3/ppocr/modeling/backbones/__init__.py", line 47, in build_backbone
    module_class = eval(module_name)(**config)
  File "/paddle/PPv2/PaddleOCR-release-2.3/ppocr/modeling/backbones/det_resnet_vd.py", line 199, in __init__
    self.conv1_1 = ConvBNLayer(
  File "/paddle/PPv2/PaddleOCR-release-2.3/ppocr/modeling/backbones/det_resnet_vd.py", line 43, in __init__
    self._conv = nn.Conv2D(
  File "/usr/local/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/usr/local/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 364, in create_parameter
    raise ValueError(
ValueError: parameter name [conv1_1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by AminGeng** [comment]
完整报错/Complete Error Message：ValueError: parameter name [conv1_1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

**Comment by AminGeng** [comment]
**运行指令/**Command Code：**我修改了ch_PP-OCRv2/ch_PP-OCR_det_dml.yml, 想蒸馏两个另外的模型**
Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/ResNet18_dml/
  save_epoch_step: 100
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 20]
  cal_metric_during_train: False
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  name: DistillationModel
  algorithm: Distillation
  Models:
    Student:
      **pretrained: ./output/ch_db_res18/first/best_accuracy**
      freeze_params: false
      return_all_feats: false
      model_type: det
      algorithm: DB
      Transform:
      Backbone:
        name: ResNet
        layers: 18
        disable_se: True
      Neck:
        name: DBFPN
        out_channels: 256
      Head:
        name: DBHead
        k: 50

    Student2:
      **pretrained: ./pretrain_models/ch_ppocr_server_v2.0_det_train/best_accuracy**
      freeze_params: false
      return_all_feats: false
      model_type: det
      algorithm: DB
      Transform:
      Backbone:
        name: ResNet
        layers: 18
        disable_se: True
      Neck:
        name: DBFPN
        out_channels: 256
      Head:
        name: DBHead
        k: 50

**Comment by WenmuZhou** [comment]
你好，麻烦更新一下代码，这个问题我们已经修复了

**Comment by LiquorPerfect** [comment]
@LDOUBLEV 我使用的时paddle ocr release2.4，对于ch_PP-OCRv2_rec_distillation.yml模型进行DML的时候，两个模型权重都不固定，也会出现这个报错，麻烦验证一下，如果要更新版本，更新到哪个版本。

**Comment by LDOUBLEV** [comment]
github上 2.4分支的代码没有自定义的 参数命名，你重新更新代码试试？https://github.com/PaddlePaddle/PaddleOCR
