### ISSUE TITLE
srn模型backbone替换

### ISSUE THREAD

**Issue by Babysun-ljh** [PaddlePaddle/PaddleOCR#5687]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：python 3.8
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：srn模型backbone替换
- 运行指令/Command Code：
将backbone替换为mobilenetv3，self_attention中数据维度src_word_emb  src_pos_enc不一致
<img width="877" alt="image" src="https://user-images.githubusercontent.com/56462898/157632868-5439badd-a472-49ff-b819-f859f2c461c2.png">

- 完整报错/Complete Error Message：
self attn:  [4, 80, 480] [4, 160, 1]
self attn:  [4, 160]
self attn:  [4, 80, 480] [4, 160, 480]
Traceback (most recent call last):
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/tools/train.py", line 123, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/tools/program.py", line 241, in train
    preds = model(images, data=batch[1:])
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/modeling/architectures/base_model.py", line 83, in forward
    x = self.head(x, targets=data)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/modeling/heads/rec_srn_head.py", line 306, in forward
    pvam_feature = self.pvam(inputs, encoder_word_pos, gsrm_word_pos)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/modeling/heads/rec_srn_head.py", line 82, in forward
    word_features = self.wrap_encoder_for_feature(enc_inputs)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/modeling/heads/self_attention.py", line 63, in forward
    enc_input = self.prepare_encoder(conv_features, src_pos)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/cynthia/git_version_paddle/PaddleOCR-release-2.4/ppocr/modeling/heads/self_attention.py", line 335, in forward
    enc_input = src_word_emb + src_pos_enc
  File "/Users/cynthia/opt/anaconda3/python.app/Contents/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [4, 80, 480] and the shape of Y = [4, 160, 480]. Received [80] in X is not equal to [160] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /home/Paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]

**Comment by littletomatodonkey** [comment]
你好，可以先看下默认srn的backbone输出，然后更换backbone的时候，保证输出格式和他保持一致
