### ISSUE TITLE
训练时报：ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleOCR#5710]
环境 aistudio GPU
PADDLE 2.2.2 
PADDLEOCR 2.4
命令
python tools/train.py -c configs/det/det_res18_db_v2.0.yml 

batch_size_per_card: 8 会报以下错误， batch_size_per_card: 256 会内存溢出，
这个是我数据的问题吗，我做的数据用PPOCRLabel，都可以导入导出。

Global:
  debug: true
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/ch_db_res18/
  save_epoch_step: 2
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/ch_ppocr_server_v2.0_det_train/best_accuracy
  checkpoints:
  save_inference_dir: ./output/ch_db_res18_infer/
  use_visualdl: true
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet
    layers: 18
    disable_se: True
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/det/train/
    label_file_list:
      - ./train_data/det/train.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [960, 960]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir:  ./train_data/det/val/
    label_file_list:
      - ./train_data/det/val.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2

[2022/03/15 10:18:38] root INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
[2022/03/15 10:18:38] root INFO: Initialize indexs of datasets:['./train_data/det/train.txt']
Traceback (most recent call last):
  File "tools/train.py", line 149, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 126, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 274, in train
    post_result = post_process_class(preds, batch[1])
  File "/home/aistudio/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 181, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
ValueError: too many values to unpack (expected 4)

**Comment by linkewei0580** [comment]
发现的情况是，图片数量大于batch_size_per_card ，就会报这个错，应该是第二遍开始的时候报这个错了。

**Comment by linkewei0580** [comment]
> 
你好，我把cal_metric_during_train: False 设置成False 就可以了，我训练数据都是通过脚本生成的，这是啥原因。python gen_ocr_train_val_test.py --trainValTestRatio 6:2:2 --datasetRootPath ../../traindata --detRootPath ../train_data/det --recRootPath ../train_data/rec

**Comment by linkewei0580** [comment]
> 我把cal_metric_during_train: False 设置成False 就可以了

我把cal_metric_during_train: False 设置成False 就可以了
