### ISSUE TITLE
在小米4手机上出现崩溃的问题

### ISSUE THREAD

**Issue by 624209494** [PaddlePaddle/PaddleOCR#5732]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 型号：小米4
系统：安卓6.0.1
abifilter："arm64-v8a", "armeabi-v7a"
日志如下：
- 完整报错/Complete Error Message：
07-16 23:52:59.602 5540-5540/com.ifop.androidxdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ifop.androidxdemo, PID: 5540
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ifop.androidxdemo/com.ifop.androidxdemo.MainActivity}: java.lang.RuntimeException: Load libNative.so failed, please check it exists in apk file.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
        at android.app.ActivityThread.access$1100(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: java.lang.RuntimeException: Load libNative.so failed, please check it exists in apk file.
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:18)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:127)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89)
        at com.baidu.paddle.lite.demo.ocr.OcrManager.onLoadModel(OcrManager.java:47)
        at com.baidu.paddle.lite.demo.ocr.OcrManager.onResume(OcrManager.java:119)
        at com.baidu.paddle.lite.demo.ocr.OcrManager.<init>(OcrManager.java:43)
        at com.ifop.androidxdemo.MainActivity.onCreate(MainActivity.java:64)
        at android.app.Activity.performCreate(Activity.java:6355)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.ifop.androidxdemo-1/lib/arm/libhiai_ir.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:16)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:127) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:50) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:89) 
        at com.baidu.paddle.lite.demo.ocr.OcrManager.onLoadModel(OcrManager.java:47) 
        at com.baidu.paddle.lite.demo.ocr.OcrManager.onResume(OcrManager.java:119) 
        at com.baidu.paddle.lite.demo.ocr.OcrManager.<init>(OcrManager.java:43) 
        at com.ifop.androidxdemo.MainActivity.onCreate(MainActivity.java:64) 
        at android.app.Activity.performCreate(Activity.java:6355) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by YY007H** [comment]
一样一样的

**Comment by littletomatodonkey** [comment]
你好，可以试下这个链接：https://gitee.com/paddlepaddle/PaddleOCR/issues/I2BLD4
