### ISSUE TITLE
推理的时候报错/paddle/paddle/fluid/platform/cuda_helper.h:107

### ISSUE THREAD

**Issue by ChiLincoln** [PaddlePaddle/PaddleOCR#5740]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu18,cuda11.1,cudnn8.0
- 版本号/Version：Paddle：2.2.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：运行run_check()命令没问题,但是运行官方给的脚本报错,该脚本在另外一台服务器相同环境下运行成功
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "/data1/text_recognize/text_recognizer.py", line 136, in <module>
    predict_images(img_dir, weight_file, cfg_file)
  File "/home/pc/anaconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/data1/text_recognize/text_recognizer.py", line 78, in predict_images
    model, post_process_class = init_model(config, model_path)
  File "/data1/text_recognize/text_recognizer.py", line 62, in init_model
    model = build_model(config['Architecture'])
  File "/data1/text_recognize/ppocr/modeling/architectures/__init__.py", line 27, in build_model
    arch = BaseModel(config)
  File "/data1/text_recognize/ppocr/modeling/architectures/base_model.py", line 50, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/data1/text_recognize/ppocr/modeling/backbones/__init__.py", line 53, in build_backbone
    module_class = eval(module_name)(**config)
  File "/data1/text_recognize/ppocr/modeling/backbones/rec_mobilenet_v3.py", line 93, in __init__
    self.conv1 = ConvBNLayer(
  File "/data1/text_recognize/ppocr/modeling/backbones/det_mobilenet_v3.py", line 167, in __init__
    self.conv = nn.Conv2D(
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 643, in __init__
    super(Conv2D, self).__init__(
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 421, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 373, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 351, in __call__
    op = block.append_op(
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3163, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/pc/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/platform/cuda_helper.h:107)
  [operator < gaussian_random > error]

**Comment by WenmuZhou** [comment]
你好，你的命令是啥
