### ISSUE TITLE
安装完成后组件缺失，例程无法运行

### ISSUE THREAD

**Issue by LaciliaExe** [PaddlePaddle/PaddleOCR#5748]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10 64位，vscode
- 版本号/Version：Python：3.8.12 Paddle：2.2.2  PaddleOCR：2.4.0.2 
- 问题相关组件/Related components：draw_structure_result,save_structure_res,...
- 运行指令/Command Code：from paddleocr import PPStructure,draw_structure_result,save_structure_res
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "d:\Code\Python\Python38_0\test3.py", line 3, in <module>
    from paddleocr import PPStructure,draw_structure_result,save_structure_res
  File "E:\Anaconda\envs\python38_0\lib\site-packages\paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "E:\Anaconda\envs\python38_0\lib\site-packages\paddleocr\paddleocr.py", line 20, in <module>
    import paddle
  File "E:\Anaconda\envs\python38_0\lib\site-packages\paddle\__init__.py", line 59, in <module>
    import paddle.dataset  # noqa: F401
    import paddle.dataset.flowers  # noqa: F401
  File "E:\Anaconda\envs\python38_0\lib\site-packages\paddle\dataset\flowers.py", line 39, in <module>
    from paddle.dataset.image import load_image_bytes
  File "E:\Anaconda\envs\python38_0\lib\site-packages\paddle\dataset\image.py", line 48, in <module>
    import_cv2_proc = subprocess.Popen(
  File "E:\Anaconda\envs\python38_0\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Anaconda\envs\python38_0\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

打开库文件后可发现上述模块部分代码为白色，说明vscode无法定位引用，模块缺失

**Comment by 0-Maxwei-0** [comment]
您好，请问解决了吗

**Comment by k1ng0fic3** [comment]
同样的问题，解决了吗？
