### ISSUE TITLE
error in det_pse_loss when training

### ISSUE THREAD

**Issue by TankosTao** [PaddlePaddle/PaddleOCR#5763]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu
- 版本号/Version：paddlepaddle-gpu     2.1.1.post112：
- 运行指令/Command Code：python train.py 
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 125, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/***/project/PaddleOCR-2.4/tools/program.py", line 247, in train
    loss = loss_class(preds, batch)
  File "/home/***/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//***//project/PaddleOCR-2.4/ppocr/losses/det_pse_loss.py", line 53, in forward
    selected_masks = self.ohem_batch(texts, gt_texts, training_masks)
  File "/home//***//project/PaddleOCR-2.4/ppocr/losses/det_pse_loss.py", line 149, in ohem_batch
    training_masks[i, :, :], ohem_ratio))
  File "/home//***//project/PaddleOCR-2.4/ppocr/losses/det_pse_loss.py", line 127, in ohem_single
    selected_mask = selected_mask.view(
AttributeError: 'Tensor' object has no attribute 'view'
![图片](https://user-images.githubusercontent.com/26140080/159862164-d66ac730-2319-4225-b16c-dd96bc73c549.png)

**Comment by LDOUBLEV** [comment]
fixed in https://github.com/PaddlePaddle/PaddleOCR/pull/5804
