### ISSUE TITLE
PPOCRLabel  自动标注报错InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 4, axis's size is 3

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleOCR#5793]
`self.ocr = PaddleOCR(use_pdserving=False, use_angle_cls=True, det=True, cls=True, use_gpu=gpu, lang=lang, show_log=False,det_model_dir="E:/PaddleOCR/PPOCRLabel/rc_crnn/inference.pdiparams")`

```
PPOCRLabel --lang ch

resultPaths are ['\\strings', '\\strings-zh', 'E:\\anaconda3\\envs\\PaddleOCR\\lib\\site-packages\\PPOCRLabel\\resources\\strings\\strings-zh-CN.properties']
file name in openNext is  F:\paddleocr\WenBenbIAOZHU\Z128_0.jpg
DirPath in importDirImages is F:/paddleocr/WenBenbIAOZHU
Using model from  paddle
In user code:

    File "tools/export_model.py", line 129, in <module>
      main()
    File "tools/export_model.py", line 125, in main
      export_single_model(model, arch_config, save_path, logger)
    File "tools/export_model.py", line 80, in export_single_model
      paddle.jit.save(model, save_path)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\jit.py", line 743, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\mm\AppData\Local\Temp\tmpn2t6ntz9.py", line 28, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.use_neck, true_fn_1,
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "E:\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 78, in forward
      x = self.neck(x)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "E:\PaddleOCR\ppocr\modeling\necks\rnn.py", line 89, in forward
      x = self.encoder_reshape(x)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "E:\PaddleOCR\ppocr\modeling\necks\rnn.py", line 33, in forward
      x = x.transpose([0, 2, 1])  # (NTC)(batch, width, channels)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\layers\nn.py", line 5576, in transpose
      helper.append_op(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 4, axis's size is 3
      [Hint: Expected x_rank == axis_size, but received x_rank:4 != axis_size:3.] (at ..\paddle/fluid/operators/transpose_op.cc:47)
      [operator < transpose2 > error]
Traceback (most recent call last):
  File "E:\anaconda3\envs\PaddleOCR\lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 41, in run
    self.result_dic = self.ocr.ocr(Imgpath, cls=True, det=True)
  File "E:\anaconda3\envs\PaddleOCR\lib\site-packages\paddleocr\paddleocr.py", line 380, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "E:\anaconda3\envs\PaddleOCR\lib\site-packages\PaddleOCR\tools\infer\predict_system.py", line 69, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "E:\anaconda3\envs\PaddleOCR\lib\site-packages\PaddleOCR\tools\infer\predict_det.py", line 230, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 129, in <module>
      main()
    File "tools/export_model.py", line 125, in main
      export_single_model(model, arch_config, save_path, logger)
    File "tools/export_model.py", line 80, in export_single_model
      paddle.jit.save(model, save_path)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\jit.py", line 743, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\mm\AppData\Local\Temp\tmpn2t6ntz9.py", line 28, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.use_neck, true_fn_1,
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "E:\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 78, in forward
      x = self.neck(x)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "E:\PaddleOCR\ppocr\modeling\necks\rnn.py", line 89, in forward
      x = self.encoder_reshape(x)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "E:\PaddleOCR\ppocr\modeling\necks\rnn.py", line 33, in forward
      x = x.transpose([0, 2, 1])  # (NTC)(batch, width, channels)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\layers\nn.py", line 5576, in transpose
      helper.append_op(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "E:\anaconda3\envs\paddleocr\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 4, axis's size is 3
      [Hint: Expected x_rank == axis_size, but received x_rank:4 != axis_size:3.] (at ..\paddle/fluid/operators/transpose_op.cc:47)
      [operator < transpose2 > error]
```

**Comment by Evezerest** [comment]
你好，应该是这张图片的通道数有问题，可以发一下看看

**Comment by monkeycc** [comment]
![Z128_0](https://user-images.githubusercontent.com/6490927/160587373-70384ae8-93bc-46ad-ae2f-2f5e73fe9cd4.jpg)

**Comment by monkeycc** [comment]
@Evezerest

**Comment by Evezerest** [comment]
看了一下你的修改，应该是配置模型的时候错了，选择到 `E:/PaddleOCR/PPOCRLabel/rc_crnn/` 即可
