### ISSUE TITLE
文字识别出错

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleOCR#5796]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：!python /home/aistudio/work/PaddleOCR/tools/train.py -c /home/aistudio/work/PaddleOCR/configs/rec/ch_ppocr_v2.0/rec_chinese_common_train_v2.0.yml
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "/home/aistudio/work/PaddleOCR/tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/aistudio/work/PaddleOCR/tools/train.py", line 125, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/aistudio/work/PaddleOCR/tools/program.py", line 255, in train
    optimizer.step()
  File "<decorator-gen-225>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 296, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-223>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 422, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 891, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 677, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if not p[0].stop_gradient])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 297, in _create_accumulators
    self._add_moments_pows(p)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 262, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 592, in _add_accumulator
    "Optimizer set error, {} should in state dict".format( var_name )
AssertionError: Optimizer set error, linear_0.w_0_moment1_0 should in state dict

**Comment by WenmuZhou** [comment]
加载的参数和网络对不上，检查一下参数和网络
