### ISSUE TITLE
识别模型半精度训练 RuntimeError: (NotFound) Operator fill_constant_batch_size_like does not have kernel for data_type

### ISSUE THREAD

**Issue by kiclent** [PaddlePaddle/PaddleOCR#5817]
配置文字识别模型蒸馏训练时，出现以下错误

===========================================================
```
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 125, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/admin/tools/program.py", line 238, in train
    preds = model(images)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel.py", line 704, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/admin/ppocr/modeling/architectures/distillation_model.py", line 59, in forward
    result_dict[model_name] = self.model_list[idx](x)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/admin/ppocr/modeling/architectures/base_model.py", line 78, in forward
    x = self.neck(x)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/admin/ppocr/modeling/necks/rnn.py", line 91, in forward
    x = self.encoder(x)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/admin/ppocr/modeling/necks/rnn.py", line 45, in forward
    x, _ = self.lstm(x)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/rnn.py", line 1051, in forward
    for _ in range(self.state_components)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/rnn.py", line 1051, in <listcomp>
    for _ in range(self.state_components)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/tensor.py", line 838, in fill_constant_batch_size_like
    attrs=attrs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (NotFound) Operator fill_constant_batch_size_like does not have kernel for data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:159)
  [operator < fill_constant_batch_size_like > error]
INFO 2022-03-29 13:51:42,490 launch_utils.py:320] terminate process group gid:111223
INFO 2022-03-29 13:51:42,490 launch_utils.py:320] terminate process group gid:111233
INFO 2022-03-29 13:51:42,490 launch_utils.py:320] terminate process group gid:111238
INFO 2022-03-29 13:51:46,496 launch_utils.py:341] terminate all the procs
ERROR 2022-03-29 13:51:46,496 launch_utils.py:604] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1] was aborted. Please check its log.
INFO 2022-03-29 13:51:50,502 launch_utils.py:341] terminate all the procs
```
===========================================================
docker镜像环境：paddlepaddle/paddle:2.2.1-gpu-cuda11.2-cudnn8
显卡： tesla V100
```
CUDNN_VERSION=8.1.1.33
NCCL_VERSION=2.8.4
CUDA_VERSION=11.2.1
NVIDIA_REQUIRE_CUDA=cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450,driver<451
```

运行指令： `python -m paddle.distributed.launch --gpus='0,1,2,3' tools/train.py -c configs/rec/ch_PP-OCRv2/rec_r34_vd_distillation.yml`

配置：
```
Global:
  debug: false
  use_gpu: true
  scale_loss: 32768
  use_dynamic_loss_scaling: true
  use_amp: true
  epoch_num: 20
  ...
```

**Comment by littletomatodonkey** [comment]
你好，我们复现了这个问题，之前只在检测模型上验证了，我们先排查下哈，感谢反馈~

**Comment by littletomatodonkey** [comment]
你好，使用paddle develop的版本，就可以正常运行了哈，这个问题应该在前段时间被修复了
