### ISSUE TITLE
2.4版本识别模型训练报错：ImportError: dlopen: cannot load any more object with static TLS It seems that scikit-image has not been built correctly.

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleOCR#5819]
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/skimage/__init__.py", line 119, in <module>
    from ._shared import geometry
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/paddlejob/workspace/code/PaddleOCR/tools/train.py", line 32, in <module>
    from ppocr.data import build_dataloader
  File "/root/paddlejob/workspace/code/PaddleOCR/ppocr/data/__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/root/paddlejob/workspace/code/PaddleOCR/ppocr/data/imaug/__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "/root/paddlejob/workspace/code/PaddleOCR/ppocr/data/imaug/iaa_augment.py", line 24, in <module>
    import imgaug
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/imgaug/__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/imgaug/imgaug.py", line 22, in <module>
    import skimage.draw
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/skimage/__init__.py", line 122, in <module>
    _raise_build_error(e)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/skimage/__init__.py", line 102, in _raise_build_error
    %s""" % (e, msg))
ImportError: dlopen: cannot load any more object with static TLS
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
/root/paddlejob/workspace/code

**Comment by MissPenguin** [comment]
重新安装下scikit-image？
