### ISSUE TITLE
语义实体识别SER和关系抽取RE预训练模型转ONNX报错问题

### ISSUE THREAD

**Issue by 471417367** [PaddlePaddle/PaddleOCR#5868]
paddle2onnx==0.9.1

运行命令：
paddle2onnx --model_dir PP-Layout_v1.0_ser_pretrained --model_filename sentencepiece.bpe.model --params_filename model_state.pdparams --save_file ser_pretrained.onnx --opset_version 12

报错：
Traceback (most recent call last):
  File "/usr/local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/command.py", line 195, in main
    input_shape_dict=input_shape_dict)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/command.py", line 120, in program2onnx
    params_filename=params_filename)
  File "<decorator-gen-119>", line 2, in load_inference_model
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 238, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1592, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 5312, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

**Comment by WenmuZhou** [comment]
你好，暂不支持

**Comment by 471417367** [comment]
谢谢

zhoujun ***@***.***> 于2022年4月4日周一 15:42写道：

**Comment by taosean** [comment]
@WenmuZhou 你好，请问有计划支持 SER+RE 转换成 ONNX 吗？如果有的话，大概什么时候可以呢？
