### ISSUE TITLE
AssertionError: C:\Users\ui\Desktop\ww\dist\p1\distutils\core.pyc一直找不到原因，求解答

### ISSUE THREAD

**Issue by jsylkn** [PaddlePaddle/PaddleOCR#5926]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.2 PaddleOCR：2.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
```bash
Traceback (most recent call last):
  File "p1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\tools\infer\__init__.py", line 15, in <module>
    from . import predict_cls, predict_det, predict_e2e, predict_rec, predict_system, utility
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\tools\infer\predict_cls.py", line 30, in <module>
    import tools.infer.utility as utility
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\tools\infer\utility.py", line 23, in <module>
    from paddle import inference
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\__init__.py", line 45, in <module>
    from . import dataset
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\dataset.py", line 19, in <module>
    from ..utils import deprecated
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\utils\__init__.py", line 28, in <module>
    from . import cpp_extension  # noqa: F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\utils\cpp_extension\__init__.py", line 15, in <module>
    from .cpp_extension import CUDAExtension  # noqa: F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\utils\cpp_extension\cpp_extension.py", line 20, in <module>
    import setuptools
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "setuptools\__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "_distutils_hack\override.py", line 1, in <module>
  File "_distutils_hack\__init__.py", line 72, in do_override
  File "_distutils_hack\__init__.py", line 59, in ensure_local_distutils
AssertionError: C:\Users\ui\Desktop\ww\dist\p1\distutils\core.pyc
[7332] Failed to execute script 'p1' due to unhandled exception!
```

**Comment by WenmuZhou** [comment]
方便提供运行命令吗

**Comment by jsylkn** [comment]
> 方便提供运行命令吗

PS C:\Users\ui\Desktop\新建文件夹\dist> .\p1

**Comment by WenmuZhou** [comment]
能否提供复现脚本

**Comment by l759688461** [comment]
> 能否提供复现脚本

我和楼主情况一样，用pyinstaller打包paddlerocr，打包成功了，但是运行exe报错

from paddleocr import PaddleOCR
在这句报错的，代码就是PPOCRLable.py的源码，没进行任何改动

**Comment by atec2000** [comment]
同样的问题，打包就没有成功过。因为程序要打包给用户用而不是程序员自己用，请团队重视。

**Comment by hy-shadow** [comment]
你好，请问解决了吗，我也遇到了类似的问题

**Comment by BradXiao** [comment]
As workaround, try this...
https://stackoverflow.com/questions/71027006/assertionerror-inside-of-ensure-local-distutils-when-building-a-pyinstaller-exe

**Comment by shadowfienders** [comment]
有解决方法了吗，我们也找不到解决方法

**Comment by jsylkn** [comment]
> 有解决方法了吗，我们也找不到解决方法

试试楼上的方法，我没有找到方法

**Comment by saltfishhhhhhh** [comment]
加1，也遇到这情况了

**Comment by CGQhaha** [comment]
楼上BradXiao的方法可行

**Comment by chx-xuan** [comment]
无法解决,放弃了
