### ISSUE TITLE
用pyinstaller打包成exe之后运行报错

### ISSUE THREAD

**Issue by hf62580** [PaddlePaddle/PaddleOCR#5929]
python 3.8.0 打包成exe之后，报错
Traceback (most recent call last):
  File "Mypaddleocr.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\paddleocr.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\framework.py", line 36, in <module>
    from . import core
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\core.py", line 65, in <module>
    raise e
  File "paddle\fluid\core.py", line 46, in <module>
    os.add_dll_directory(third_lib_path)
  File "os.py", line 1105, in add_dll_directory
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI2531202\\paddle\\fluid\\..\\libs'

**Comment by hf62580** [comment]
换成python 3.7.4 paddleocr-2.0.1 paddlepaddle-2.0.1之后
打包成exe之后，运行卡很久，然后报错
E:\input>Mypaddleocr.exe
PyInstaller\loader\pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
C:\Users\ADMINI~1\AppData\Local\Temp_MEI2974722\paddle\fluid\layers\utils.py:26: DeprecationWarning: np.int is a deprecated alias for the builtin int. To silence this warning, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
File "Mypaddleocr.py", line 1, in
from paddleocr import PaddleOCR, draw_ocr
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddleocr_init.py", line 16, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddleocr\paddleocr.py", line 28, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "tools\infer\predict_system.py", line 26, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "tools\infer\utility.py", line 23, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle_init.py", line 29, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\fluid_init.py", line 51, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\fluid\io.py", line 40, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\fluid\reader.py", line 25, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\fluid\dataloader_init.py", line 17, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\fluid\dataloader\dataset.py", line 18, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\dataset_init.py", line 27, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\dataset\flowers.py", line 38, in
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "paddle\dataset\image.py", line 46, in
File "subprocess.py", line 939, in communicate
File "subprocess.py", line 1267, in _communicate
File "threading.py", line 1044, in join
File "threading.py", line 1060, in _wait_for_tstate_lock

**Comment by MissPenguin** [comment]
pyinstaller打包exe好像是比较麻烦，之前有别的开发者用QPT打包exe成功了，可以参考下：
https://github.com/QPT-Family/QPT
https://aistudio.baidu.com/aistudio/projectdetail/3571518

**Comment by neverever123789** [comment]
如果是要解決 ...\paddle\fluid\..\libs 的 FileNotFoundError 問題的話，可以嘗試修改 spec 檔中的 binaries
binaries = [(r'...\paddle\fluid\..\libs', '.')] ← 前項放絕對路徑

**Comment by Haeppypuppy** [comment]
> 如果是要解決 ...\paddle\fluid..\libs 的 FileNotFoundError 問題的話，可以嘗試修改 spec 檔中的 binaries binaries = [(r'...\paddle\fluid..\libs', '.')] ← 前項放絕對路徑

您好~我在https://hackmd.io/@computerVision/BkYrDUDxY看到您有實作paddleocr的結果
有一些問題想詢問您 因為我在復現論文上遇到一些問題>< 不知道方不方便
