### ISSUE TITLE
OCR_rec报错，InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 4, axis's size is 3       [Hint: Expected x_rank == axis_size, but received x_rank:4 != axis_size:3.] (at /paddle/paddle/fluid/operators/transpose_op.cc:47)       [operator < transpose2 > error]

### ISSUE THREAD

**Issue by suncan0207** [PaddlePaddle/PaddleOCR#5952]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：paddlepaddle2.2.2 cuda10.1,cudnn7.6.5环境问题可以排除，因为我另一个代码可以跑通
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 我的思路是检测之后再识别，但是识别出现这个问题，说输入维度不一致，但是看不懂究竟是哪里问题，排除了图片的问题，我可以正常保存检测之后的图像，用于输入，我看rec识别也是通过imread读取图片的，所以可以排除这个问题，附上我的识别部分代码
- 在main.py基础上删了点无关的
- def ocr_pred_rec_with_img(args, image):
    if image is None:
        logger.info("error in loading images. image is None.")
        return

    text_recognizer = TextRecognizer(args)
    img_list = []
    img_list.append(image)
    rec_res = []
    print('img_list',img_list)
    print('img_list len',len(img_list))
    try:
        rec_res, predict_time = text_recognizer(img_list)
    except:
        logger.info(traceback.format_exc())
        logger.info(
            "ERROR in ocr_pred_rec_with_img()!"
        )
        exit()
    if len(rec_res) == 1:
        logger.info("Predicts of input img:{}".format(rec_res[0]))

        logger.info("Total predict time for input image, cost: {:.3f}".format(predict_time))
        return rec_res[0]
    else:
        logger.info("Error in predicting rec result of input image.")
        return rec_res
__________________________________________________________________________________________________________________________________________
报错如下
[2022/04/12 17:44:58] root INFO: Traceback (most recent call last):
  File "/home/data/suncan/full_operator_ocr/operators/paddle_ocr/predict_rec_ocr.py", line 263, in ocr_pred_rec_with_img
    rec_res, predict_time = text_recognizer(img_list)
  File "/home/data/suncan/full_operator_ocr/operators/paddle_ocr/predict_rec_ocr.py", line 238, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 95, in <module>
      main()
    File "tools/export_model.py", line 90, in main
      paddle.jit.save(model, save_path)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmppukasmcm.py", line 24, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/data/suncan/paddle_ocr/ppocr/modeling/architectures/base_model.py", line 76, in forward
      x = self.neck(x)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/data/suncan/paddle_ocr/ppocr/modeling/necks/rnn.py", line 89, in forward
      x = self.encoder_reshape(x)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/data/suncan/paddle_ocr/ppocr/modeling/necks/rnn.py", line 33, in forward
      x = x.transpose([0, 2, 1])  # (NTC)(batch, width, channels)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 5581, in transpose
      attrs={'axis': perm})
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/data/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 4, axis's size is 3
      [Hint: Expected x_rank == axis_size, but received x_rank:4 != axis_size:3.] (at /paddle/paddle/fluid/operators/transpose_op.cc:47)
      [operator < transpose2 > error]

**Comment by suncan0207** [comment]
找到原因了，输入的高度是固定的32。。。我把源码的log部分删掉了，结果里面就有提示
![图片](https://user-images.githubusercontent.com/57487895/163147185-44ac7b3e-9782-4c20-8148-aaf5b5734d14.png)

**Comment by andyjpaddle** [comment]
好的

**Comment by Williamlizl** [comment]
> 找到原因了，输入的高度是固定的32。。。我把源码的log部分删掉了，结果里面就有提示 ![图片](https://user-images.githubusercontent.com/57487895/163147185-44ac7b3e-9782-4c20-8148-aaf5b5734d14.png)

你好，我也遇到相同问题，应该怎么修改呐
