### ISSUE TITLE
Paddleocr打包程序错误

### ISSUE THREAD

**Issue by JacksonFFFFF** [PaddlePaddle/PaddleOCR#5953]
Traceback (most recent call last):
  File "mainOCR.py", line 5, in <module>
  File "C:\Users\11\AppData\Local\Temp\embedded.v3fw7p3g.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "C:\Users\11\AppData\Local\Temp\embedded.v3fw7p3g.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\paddleocr.py", line 20, in <module>
    import paddle
  File "C:\Users\11\AppData\Local\Temp\embedded.v3fw7p3g.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\__init__.py", line 59, in <module>
    import paddle.dataset  # noqa: F401
  File "C:\Users\11\AppData\Local\Temp\embedded.v3fw7p3g.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\dataset\__init__.py", line 27, in <module>
    import paddle.dataset.flowers  # noqa: F401
  File "C:\Users\11\AppData\Local\Temp\embedded.v3fw7p3g.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\dataset\flowers.py", line 39, in <module>
    from paddle.dataset.image import load_image_bytes
  File "C:\Users\11\AppData\Local\Temp\embedded.v3fw7p3g.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\dataset\image.py", line 48, in <module>
    import_cv2_proc = subprocess.Popen(
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by andyjpaddle** [comment]
看报错是路径的问题，可以检查一下

**Comment by jluwoniu** [comment]
> 

老哥，我遇到一样的问题你，请问你怎么解决的？

**Comment by illuSION-crypto** [comment]
> > 
> 
> 老哥，我遇到一样的问题你，请问你怎么解决的？

在paddle\dataset\image.py里
![图片](https://user-images.githubusercontent.com/56497487/171998995-f33ddb8a-a8ad-431b-a2c6-0bb4ff94308e.png)
在这个函数里加上stdin的参数就好了
