### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by fishguysword** [PaddlePaddle/PaddleOCR#5956]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components： 数据处理 imaug 这一块
- 运行指令/Command Code： python tools/train.py -c captcha/configs/captcha_num_rec_prod.yml
- 完整报错/Complete Error Message：
12 12:30:40] root INFO: train with paddle 2.2.2 and device CUDAPlace(0)
[2022/04/12 12:30:40] root INFO: Initialize indexs of datasets:['./captcha/train_data/rec/rec_gt_train.txt']
[2022/04/12 12:30:40] root INFO: Initialize indexs of datasets:['./captcha/train_data/rec/rec_gt_test.txt']
W0412 12:30:40.722412 12389 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0412 12:30:40.727881 12389 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[2022/04/12 12:30:46] root WARNING: The shape of model params head.fc.weight [512, 63] not matched with loaded params head.fc.weight [512, 6625] !
[2022/04/12 12:30:46] root WARNING: The shape of model params head.fc.bias [63] not matched with loaded params head.fc.bias [6625] !
[2022/04/12 12:30:46] root INFO: load pretrain successful from ./captcha/ch_ppocr_server_v2.0_rec_pre/best_accuracy
[2022/04/12 12:30:46] root INFO: train dataloader has 18 iters
[2022/04/12 12:30:46] root INFO: valid dataloader has 7 iters
[2022/04/12 12:30:46] root INFO: During the training process, after the 0th iteration, an evaluation is run every 1000 iterations
[2022/04/12 12:30:46] root INFO: Initialize indexs of datasets:['./captcha/train_data/rec/rec_gt_train.txt']
[2022/04/12 12:30:52] root ERROR: When parsing line 6S4y.png    6S4y
, error happened with msg: Traceback (most recent call last):
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/simple_dataset.py", line 119, in __getitem__
    outs = transform(data, self.ops)
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/imaug/__init__.py", line 43, in transform
    data = op(data)
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/imaug/rec_img_aug.py", line 30, in __call__
    img = warp(img, 10, self.use_tia, self.aug_prob)
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/imaug/rec_img_aug.py", line 508, in warp
    new_img = tia_stretch(new_img, random.randint(3, 6))
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/imaug/text_image_aug/augment.py", line 94, in tia_stretch
    dst = trans.generate()
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/imaug/text_image_aug/warp_mls.py", line 42, in generate
    return self.gen_img()
  File "/opt/app/mrc-for-flat-nested-ner/PaddleOCR/ppocr/data/imaug/text_image_aug/warp_mls.py", line 148, in gen_img
    nx = np.clip(nx, 0, src_w - 1)
  File "<__array_function__ internals>", line 6, in clip
  File "/root/miniconda3/envs/liming/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2097, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/root/miniconda3/envs/liming/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
  File "/root/miniconda3/envs/liming/lib/python3.6/site-packages/numpy/core/_methods.py", line 115, in _clip
    if _clip_dep_is_scalar_nan(min):
  File "/root/miniconda3/envs/liming/lib/python3.6/site-packages/numpy/core/_methods.py", line 75, in _clip_dep_is_scalar_nan
    if ndim(a) != 0:
  File "<__array_function__ internals>", line 6, in ndim
  File "/root/miniconda3/envs/liming/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3108, in ndim
    return a.ndim
RecursionError: maximum recursion depth exceeded while calling a Python object

config信息是：
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: ./captcha/train_data/rec/test/word_00_9905.jpg
  # for data or label process
  character_dict_path: ./captcha/arbic_number_dic.txt
  character_type: ch
  max_text_length: 4
  infer_mode: False
  use_space_char: False
  save_res_path: ./captcha/output/rec/numric

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./captcha/train_data/rec/train
    label_file_list: ["./captcha/train_data/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 40, 220]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 8

原始图片验证码尺寸是 80*36

**Comment by fishguysword** [comment]
补充一下，这个代码我之前跑过很顺利之前跑的时候图片220*40，字典是10 ，现在的变动是80*36的图片了，然后字典是数字加大小写字母加空格，模型一直都是用的是ch_ppocr_server_v2.0_rec_pre

**Comment by andyjpaddle** [comment]
出现这个报错一般都是读取数据的问题，可以检查一下自己的数据和标签，是不是有很多无效数据，导致一直循环

**Comment by fishguysword** [comment]
> 出现这个报错一般都是读取数据的问题，可以检查一下自己的数据和标签，是不是有很多无效数据，导致一直循环
确实是数据问题，原来是标签后面多了一个/r，导致最大长度超过了，但是bug的定位信息确实不准，搞了好久，捂脸~~

**Comment by Daniel-ccx** [comment]
碰见了相同的问题，官网的训练集，很多图片没有找到。但这是个逻辑错误，找不到就打印一下，不至于死循环。
个人看法

**Comment by Daniel-ccx** [comment]
ppocr INFO: data_lines:b'train/u4_crop_0.jpg\t\xc3\xb9\n' 
多个\n也这样么？
