### ISSUE TITLE
使用新的注意力机制，替换了骨干网络中的MobileNetV3中的SE模块，训练模型可以预测出效果，评估也有指标，但是转换为推理模型后报错，将预处理参数修改了改，仍然如此，没有成效

### ISSUE THREAD

**Issue by AsOneMaster** [PaddlePaddle/PaddleOCR#5966]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code： python tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./inference/det_db_ca_new/" --image_dir="E:/iron_IMG/jiaogang/test/31.jpg"
- 完整报错/Complete Error Message：
- `Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 242, in <module>
    res = text_detector(img)
  File "tools/infer/predict_det.py", line 195, in __call__
    self.predictor.run()
RuntimeError: In user code:

    File "tools/export_model.py", line 123, in <module>
      main()
    File "tools/export_model.py", line 119, in main
      export_single_model(model, arch_config, save_path, logger)
    File "tools/export_model.py", line 74, in export_single_model
      paddle.jit.save(model, save_path)
    File "D:\creatTool\anaconda\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\jit.py", line 743, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "D:\creatTool\anaconda\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "D:\PythonProject\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 75, in forward
      x = self.backbone(x)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\ASONEM~1\AppData\Local\Temp\tmpq5o82cob.py", line 20, in forward
      [__for_loop_var_index_0, x] = paddle.jit.dy2static.convert_while_loop(
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "D:\PythonProject\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3_CA.py", line 152, in forward
      x = stage(x)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\container.py", line 98, in forward
      input = layer(input)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\ASONEM~1\AppData\Local\Temp\tmpl_q27ujf.py", line 15, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.if_ca, true_fn_7,
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\PythonProject\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3_CA.py", line 241, in forward
      x = self.mid_ca(x)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\PythonProject\PaddleOCR\ppocr\modeling\backbones\CA.py", line 28, in forward
      x_h = self.pool_h(x)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\nn\layer\pooling.py", line 772, in forward
      return F.adaptive_avg_pool2d(
    File "D:\creatTool\anaconda\lib\site-packages\paddle\nn\functional\pooling.py", line 1153, in adaptive_avg_pool2d
      helper.append_op(
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "D:\creatTool\anaconda\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The Tensor's element number must be equal or greater than zero. The Tensor's shape is [1, 40, -1, 1] now
      [Hint: Expected numel() >= 0, but received numel():-40 < 0:0.] (at D:\v2.0.0\paddle\paddle\fluid\framework\tensor.cc:59)
      [operator < pool2d > error]
`

**Comment by fengbaolongbest** [comment]
请问你是如何使用新的注意力机制替代的，我目前使用的是torch自带的mobilenetv3网络，有点不太会改
