### ISSUE TITLE
Training det_mv3_east problem

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleOCR#5975]
Hi 
I get cuda out of memory in traning . I tried to reduce the batch size to 8 then I got this error . What should I do to reduce the image_shape size  ? Thank you

Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 123, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\secsys\snake\tcl\PaddleOCR\tools\program.py", line 246, in train
    loss = loss_class(preds, batch)
  File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\secsys\snake\tcl\PaddleOCR\ppocr\losses\det_east_loss.py", line 39, in forward
    dice_loss = self.dice_loss(f_score, l_score, l_mask)
  File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\secsys\snake\tcl\PaddleOCR\ppocr\losses\det_basic_loss.py", line 128, in forward
    assert loss <= 1
AssertionError

**Comment by liebkne** [comment]
Same issue when training with config `det_mv3_db.yml` on `total_text`.
```
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/user/git/PaddleOCR/tools/program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "/home/user/git/PaddleOCR/.direnv/python-3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/user/git/PaddleOCR/.direnv/python-3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/user/git/PaddleOCR/ppocr/losses/det_db_loss.py", line 61, in forward
    loss_shrink_maps = self.bce_loss(shrink_maps, label_shrink_map,
  File "/home/user/git/PaddleOCR/.direnv/python-3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/user/git/PaddleOCR/.direnv/python-3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/user/git/PaddleOCR/ppocr/losses/det_basic_loss.py", line 87, in forward
    loss = self.loss(pred, gt, mask=mask)
  File "/home/user/git/PaddleOCR/.direnv/python-3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/user/git/PaddleOCR/.direnv/python-3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/user/git/PaddleOCR/ppocr/losses/det_basic_loss.py", line 128, in forward
    assert loss <= 1
AssertionError
```

**Comment by zhangqiqi1228** [comment]
> Hi I get cuda out of memory in traning . I tried to reduce the batch size to 8 then I got this error . What should I do to reduce the image_shape size ? Thank you
> 
> Traceback (most recent call last): File "tools/train.py", line 148, in main(config, device, logger, vdl_writer) File "tools/train.py", line 123, in main program.train(config, train_dataloader, valid_dataloader, device, model, File "C:\secsys\snake\tcl\PaddleOCR\tools\program.py", line 246, in train loss = loss_class(preds, batch) File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "C:\secsys\snake\tcl\PaddleOCR\ppocr\losses\det_east_loss.py", line 39, in forward dice_loss = self.dice_loss(f_score, l_score, l_mask) File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "C:\workspace\torchgpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "C:\secsys\snake\tcl\PaddleOCR\ppocr\losses\det_basic_loss.py", line 128, in forward assert loss <= 1 AssertionError

Hi, I faced the same error, did you solve this problem?
