### ISSUE TITLE
运行object_detection   demo时报错"libpaddle_lite_jni.so" not found

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleOCR#5984]
这是错误提示信息，该怎么解决呀。。。

E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.object_detection, PID: 6954
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpaddle_lite_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.baidu.paddle.lite.PaddleLiteInitializer.init(PaddleLiteInitializer.java:20)
        at com.baidu.paddle.lite.PaddlePredictor.<clinit>(PaddlePredictor.java:197)
        at com.baidu.paddle.lite.PaddlePredictor.createPaddlePredictor(PaddlePredictor.java:41)
        at com.baidu.paddle.lite.demo.object_detection.Predictor.loadModel(Predictor.java:130)
        at com.baidu.paddle.lite.demo.object_detection.Predictor.init(Predictor.java:77)
        at com.baidu.paddle.lite.demo.object_detection.MainActivity.onLoadModel(MainActivity.java:234)
        at com.baidu.paddle.lite.demo.object_detection.MainActivity$2.handleMessage(MainActivity.java:122)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by deepthman** [comment]
你这打不开动态库，是不是文件位置弄错了。
