### ISSUE TITLE
服务化部署出现问题

### ISSUE THREAD

**Issue by yuqiangabab** [PaddlePaddle/PaddleOCR#607]
λ localhost /home/PaddleOCR {develop} export PYTHONPATH=.
λ localhost /home/PaddleOCR {develop} hub install deploy/hubserving/ocr_system/
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/python3.5.1/bin/hub", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/commands/install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddlehub/module/module.py", line 146, in __init__
    self._initialize(**kwargs)
  File "deploy/hubserving/ocr_system/module.py", line 56, in _initialize
    self.text_sys = TextSystem(cfg)
  File "/home/PaddleOCR/tools/infer/predict_system.py", line 38, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/PaddleOCR/tools/infer/predict_det.py", line 45, in __init__
    self.use_zero_copy_run = args.use_zero_copy_run
AttributeError: 'Config' object has no attribute 'use_zero_copy_run'

**Comment by yuqiangabab** [comment]
这是在docker环境下的

**Comment by MissPenguin** [comment]
感谢反馈，目前代码已修复，可以拉取最新代码，或者直接在params.py中添加该参数：     cfg.use_zero_copy_run = False
