### ISSUE TITLE
baidu ai studio paddle train报错

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#6077]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：baidu ai studio
- 版本号/Version：Paddle：2.4  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "PaddleOCR-release-2.4/tools/train.py", line 27, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py", line 47, in <module>
    import paddle.distribution  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distribution/__init__.py", line 15, in <module>
    from paddle.distribution import transform
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distribution/transform.py", line 24, in <module>
    from paddle.distribution import (constraint, distribution,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distribution/distribution.py", line 33, in <module>
    from paddle.fluid.framework import _non_static_mode, in_dygraph_mode
ImportError: cannot import name '_non_static_mode' from 'paddle.fluid.framework' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py)
运行时长:1.634秒结束时间:2022-04-28 10:07:22

**Comment by MissPenguin** [comment]
看报错像paddle安装有问题，请问是怎么安装的呢，aistudio上应该是选择一个paddle版本就行，你选的哪个版本

**Comment by nissansz** [comment]
忘记了。换了电脑可以了。
