### ISSUE TITLE
SEED为什么一开始评估就会报错啊

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#6094]
eval model::   0%|                                                    | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/eval.py", line 82, in <module>
    main()
  File "tools/eval.py", line 73, in main
    metric = program.eval(model, valid_dataloader, post_process_class,
  File "/data/ocr/PaddleOCR-release-2.4-new/tools/program.py", line 403, in eval
    preds = model(images, data=batch[1:])
  File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs
 File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/modeling/architectures/base_model.py", line 80, in forward
    x = self.head(x, targets=data)
  File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, *
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/modeling/heads/rec_aster_head.py", line 63, in forward
    rec_pred, rec_pred_scores = self.decoder.beam_search(
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/modeling/heads/rec_aster_head.py", line 257, in beam_search
    current_symbol = paddle.index_select(
  File "/data/conda/env/paddle_env/lib/python3.8/site-packages/paddle/tensor/search.py", line 306, in index_select
    return _C_ops.index_select(x, index, 'dim', axis)
OSError: (External) CUDA error(700), an illegal memory access was encountered. 
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/operators/index_select_op.cu:112)
  [operator < index_select > error]
eval model::   0%|                                                    | 0/10 [00:19<?, ?it/s]

**Comment by LDOUBLEV** [comment]
看报错OSError: (External) CUDA error(700), an illegal memory access was encountered.
是显存不够
