### ISSUE TITLE
ImportError: cannot import name 'blake2s'

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleOCR#611]
当我尝试执行以下指令时：
`python3 tools/infer/predict_system.py --image_dir="http://seopic.699pic.com/photo/50107/1474.jpg_wh1200.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False`

会报如下错误：
```
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 20, in <module>
    import tools.infer.utility as utility
  File "/home/PaddleOCR/tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "/home/PaddleOCR/ppocr/utils/utility.py", line 19, in <module>
    from paddle import fluid
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/__init__.py", line 30, in <module>
    import paddle.dataset
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import paddle.dataset.mq2007
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
    import rarfile
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/rarfile.py", line 64, in <module>
    from hashlib import blake2s, sha1, sha256
ImportError: cannot import name 'blake2s'
```
请问需要怎么做？谢谢

**Comment by MissPenguin** [comment]
试试这个，应该能解决：
pip3 uninstall rarfile
pip3 install rarfile==3.0

**Comment by NarcissusInMirror** [comment]
> 试试这个，应该能解决：
> pip3 uninstall rarfile
> pip3 install rarfile==3.0

感谢！
