### ISSUE TITLE
PP-structure model conversion to onnx error

### ISSUE THREAD

**Issue by iazdan** [PaddlePaddle/PaddleOCR#6124]
Hi, 

I get the below error while converting the table recognition model. Does anyone know how to resolve this error? 

Traceback (most recent call last):
  File "bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.9.3', 'console_scripts', 'paddle2onnx')())
  File "/lib/python3.8/site-packages/paddle2onnx/command.py", line 273, in main
    program2onnx(
  File "/lib/python3.8/site-packages/paddle2onnx/command.py", line 200, in program2onnx
    p2o.program2onnx(
  File "lib/python3.8/site-packages/paddle2onnx/convert.py", line 95, in program2onnx
    return export_onnx(
  File "/paddle/lib/python3.8/site-packages/paddle2onnx/convert.py", line 35, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version,
  File "lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 323, in build
    onnx_graph = ONNXGraph(
  File "/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 85, in __init__
    self.update_opset_version()
  File "/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 202, in update_opset_version
    self.opset_version = OpMapper.get_recommend_opset_version(
  File "/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 128, in get_recommend_opset_version
    recommend_opset_version = OpMapper.check_support_status(
  File "/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 174, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 6 ops are not supported yet
=========== tensor_array_to_tensor ===========
=========== while ===========
=========== write_to_array ===========
=========== select_input ===========
=========== lod_array_length ===========
=========== conditional_block ===========

**Comment by MissPenguin** [comment]
The paddle2onnx related issues can be better solved here: https://github.com/PaddlePaddle/Paddle2ONNX/issues .
