### ISSUE TITLE
使用XPU进行一机多卡训练报错

### ISSUE THREAD

**Issue by drenched9** [PaddlePaddle/PaddleOCR#6134]
使用XPU训练（单机单卡）正常：
python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained \
     Global.epoch_num=1000 \
     Global.save_epoch_step=200 \
     Global.use_gpu=False \
     Global.use_xpu=True \
     Train.dataset.data_dir=./train_data/mydata \
     Train.dataset.label_file_list=[./train_data/train.txt] \
     Train.loader.num_workers=1 \
     Train.loader.batch_size_per_card=4 \
     Eval.dataset.data_dir=./train_data/mydata \
     Eval.dataset.label_file_list=[./train_data/test.txt]

使用XPU训练（一机多卡）报错：
python3  -m paddle.distributed.launch --xpus "0,1" tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained \
     Global.epoch_num=1000 \
     Global.save_epoch_step=200 \
     Global.use_gpu=False \
     Global.use_xpu=True \
     Train.dataset.data_dir=./train_data/mydata \
     Train.dataset.label_file_list=[./train_data/train.txt] \
     Train.loader.num_workers=1 \
     Train.loader.batch_size_per_card=4 \
     Eval.dataset.data_dir=./train_data/mydata \
     Eval.dataset.label_file_list=[./train_data/test.txt]

有几点可以确认：
1. XPU无人占用，且存在多块
2. 数据集正常，因为单卡是可以正常训练的
3. 程序报错位置在初始化并行环境处，即dist.init_parallel_env()

请问是否目前暂不支持除GPU外其他卡的并行训练呢？

------------------------------------------------并行训练详细日志------------------------------------------------------
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[INFO][BKCL][baidu/xpu/bkcl/src/globals.cpp:52] set BKCL timeout to 600 seconds
[INFO][BKCL][baidu/xpu/bkcl/src/globals.cpp:53] set BKCL RING BUFFER SIZE to 1048576
XPURT /usr/local/lib/python3.7/dist-packages/paddle/fluid/../libs/libxpurt.so loaded
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/det/det_mv3_db.yml', '-o', 'Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained', 'Global.epoch_num=1000', 'Global.save_epoch_step=200', 'Global.use_gpu=False', 'Global.use_xpu=True', 'Train.dataset.data_dir=./train_data/ships_label', 'Train.dataset.label_file_list=[./train_data/ships_label_train.txt]', 'Train.loader.num_workers=1', 'Train.loader.batch_size_per_card=4', 'Eval.dataset.data_dir=./train_data/ships_label', 'Eval.dataset.label_file_list=[./train_data/ships_label_test.txt]']
worker_num: None
workers: 
xpus: 0,1
------------------------------------------------
WARNING 2022-05-05 03:04:56,986 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in XPU mode
INFO 2022-05-05 03:04:56,987 launch_utils.py:528] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:58623               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:58623,127.0.0.1:51175       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |             FLAGS_selected_accelerators                        0                      |
    |                     FLAGS_selected_xpus                        0                      |
    +=======================================================================================+

INFO 2022-05-05 03:04:56,987 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:24668 idx:0
launch proc_id:24673 idx:1
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[INFO][BKCL][baidu/xpu/bkcl/src/globals.cpp:52] set BKCL timeout to 600 seconds
[INFO][BKCL][baidu/xpu/bkcl/src/globals.cpp:53] set BKCL RING BUFFER SIZE to 1048576
XPURT /usr/local/lib/python3.7/dist-packages/paddle/fluid/../libs/libxpurt.so loaded
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
use_xpu:  True
[2022/05/05 03:04:59] root INFO: Architecture : 
[2022/05/05 03:04:59] root INFO:     Backbone : 
[2022/05/05 03:04:59] root INFO:         model_name : large
[2022/05/05 03:04:59] root INFO:         name : MobileNetV3
[2022/05/05 03:04:59] root INFO:         scale : 0.5
[2022/05/05 03:04:59] root INFO:     Head : 
[2022/05/05 03:04:59] root INFO:         k : 50
[2022/05/05 03:04:59] root INFO:         name : DBHead
[2022/05/05 03:04:59] root INFO:     Neck : 
[2022/05/05 03:04:59] root INFO:         name : DBFPN
[2022/05/05 03:04:59] root INFO:         out_channels : 256
[2022/05/05 03:04:59] root INFO:     Transform : None
[2022/05/05 03:04:59] root INFO:     algorithm : DB
[2022/05/05 03:04:59] root INFO:     model_type : det
[2022/05/05 03:04:59] root INFO: Eval : 
[2022/05/05 03:04:59] root INFO:     dataset : 
[2022/05/05 03:04:59] root INFO:         data_dir : ./train_data/ships_label
[2022/05/05 03:04:59] root INFO:         label_file_list : ['./train_data/ships_label_test.txt']
[2022/05/05 03:04:59] root INFO:         name : SimpleDataSet
[2022/05/05 03:04:59] root INFO:         transforms : 
[2022/05/05 03:04:59] root INFO:             DecodeImage : 
[2022/05/05 03:04:59] root INFO:                 channel_first : False
[2022/05/05 03:04:59] root INFO:                 img_mode : BGR
[2022/05/05 03:04:59] root INFO:             DetLabelEncode : None
[2022/05/05 03:04:59] root INFO:             DetResizeForTest : 
[2022/05/05 03:04:59] root INFO:                 image_shape : [736, 1280]
[2022/05/05 03:04:59] root INFO:             NormalizeImage : 
[2022/05/05 03:04:59] root INFO:                 mean : [0.485, 0.456, 0.406]
[2022/05/05 03:04:59] root INFO:                 order : hwc
[2022/05/05 03:04:59] root INFO:                 scale : 1./255.
[2022/05/05 03:04:59] root INFO:                 std : [0.229, 0.224, 0.225]
[2022/05/05 03:04:59] root INFO:             ToCHWImage : None
[2022/05/05 03:04:59] root INFO:             KeepKeys : 
[2022/05/05 03:04:59] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2022/05/05 03:04:59] root INFO:     loader : 
[2022/05/05 03:04:59] root INFO:         batch_size_per_card : 1
[2022/05/05 03:04:59] root INFO:         drop_last : False
[2022/05/05 03:04:59] root INFO:         num_workers : 8
[2022/05/05 03:04:59] root INFO:         shuffle : False
[2022/05/05 03:04:59] root INFO:         use_shared_memory : False
[2022/05/05 03:04:59] root INFO: Global : 
[2022/05/05 03:04:59] root INFO:     cal_metric_during_train : False
[2022/05/05 03:04:59] root INFO:     checkpoints : None
[2022/05/05 03:04:59] root INFO:     debug : False
[2022/05/05 03:04:59] root INFO:     distributed : True
[2022/05/05 03:04:59] root INFO:     epoch_num : 1000
[2022/05/05 03:04:59] root INFO:     eval_batch_step : [0, 2000]
[2022/05/05 03:04:59] root INFO:     infer_img : doc/imgs_en/img_10.jpg
[2022/05/05 03:04:59] root INFO:     log_smooth_window : 20
[2022/05/05 03:04:59] root INFO:     pretrained_model : ./pretrain_models/MobileNetV3_large_x0_5_pretrained
[2022/05/05 03:04:59] root INFO:     print_batch_step : 10
[2022/05/05 03:04:59] root INFO:     save_epoch_step : 200
[2022/05/05 03:04:59] root INFO:     save_inference_dir : None
[2022/05/05 03:04:59] root INFO:     save_model_dir : ./output/db_mv3/
[2022/05/05 03:04:59] root INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2022/05/05 03:04:59] root INFO:     use_gpu : False
[2022/05/05 03:04:59] root INFO:     use_visualdl : False
[2022/05/05 03:04:59] root INFO:     use_xpu : True
[2022/05/05 03:04:59] root INFO: Loss : 
[2022/05/05 03:04:59] root INFO:     alpha : 5
[2022/05/05 03:04:59] root INFO:     balance_loss : True
[2022/05/05 03:04:59] root INFO:     beta : 10
[2022/05/05 03:04:59] root INFO:     main_loss_type : DiceLoss
[2022/05/05 03:04:59] root INFO:     name : DBLoss
[2022/05/05 03:04:59] root INFO:     ohem_ratio : 3
[2022/05/05 03:04:59] root INFO: Metric : 
[2022/05/05 03:04:59] root INFO:     main_indicator : hmean
[2022/05/05 03:04:59] root INFO:     name : DetMetric
[2022/05/05 03:04:59] root INFO: Optimizer : 
[2022/05/05 03:04:59] root INFO:     beta1 : 0.9
[2022/05/05 03:04:59] root INFO:     beta2 : 0.999
[2022/05/05 03:04:59] root INFO:     lr : 
[2022/05/05 03:04:59] root INFO:         learning_rate : 0.001
[2022/05/05 03:04:59] root INFO:     name : Adam
[2022/05/05 03:04:59] root INFO:     regularizer : 
[2022/05/05 03:04:59] root INFO:         factor : 0
[2022/05/05 03:04:59] root INFO:         name : L2
[2022/05/05 03:04:59] root INFO: PostProcess : 
[2022/05/05 03:04:59] root INFO:     box_thresh : 0.6
[2022/05/05 03:04:59] root INFO:     max_candidates : 1000
[2022/05/05 03:04:59] root INFO:     name : DBPostProcess
[2022/05/05 03:04:59] root INFO:     thresh : 0.3
[2022/05/05 03:04:59] root INFO:     unclip_ratio : 1.5
[2022/05/05 03:04:59] root INFO: Train : 
[2022/05/05 03:04:59] root INFO:     dataset : 
[2022/05/05 03:04:59] root INFO:         data_dir : ./train_data/ships_label
[2022/05/05 03:04:59] root INFO:         label_file_list : ['./train_data/ships_label_train.txt']
[2022/05/05 03:04:59] root INFO:         name : SimpleDataSet
[2022/05/05 03:04:59] root INFO:         ratio_list : [1.0]
[2022/05/05 03:04:59] root INFO:         transforms : 
[2022/05/05 03:04:59] root INFO:             DecodeImage : 
[2022/05/05 03:04:59] root INFO:                 channel_first : False
[2022/05/05 03:04:59] root INFO:                 img_mode : BGR
[2022/05/05 03:04:59] root INFO:             DetLabelEncode : None
[2022/05/05 03:04:59] root INFO:             IaaAugment : 
[2022/05/05 03:04:59] root INFO:                 augmenter_args : 
[2022/05/05 03:04:59] root INFO:                     args : 
[2022/05/05 03:04:59] root INFO:                         p : 0.5
[2022/05/05 03:04:59] root INFO:                     type : Fliplr
[2022/05/05 03:04:59] root INFO:                     args : 
[2022/05/05 03:04:59] root INFO:                         rotate : [-10, 10]
[2022/05/05 03:04:59] root INFO:                     type : Affine
[2022/05/05 03:04:59] root INFO:                     args : 
[2022/05/05 03:04:59] root INFO:                         size : [0.5, 3]
[2022/05/05 03:04:59] root INFO:                     type : Resize
[2022/05/05 03:04:59] root INFO:             EastRandomCropData : 
[2022/05/05 03:04:59] root INFO:                 keep_ratio : True
[2022/05/05 03:04:59] root INFO:                 max_tries : 50
[2022/05/05 03:04:59] root INFO:                 size : [640, 640]
[2022/05/05 03:04:59] root INFO:             MakeBorderMap : 
[2022/05/05 03:04:59] root INFO:                 shrink_ratio : 0.4
[2022/05/05 03:04:59] root INFO:                 thresh_max : 0.7
[2022/05/05 03:04:59] root INFO:                 thresh_min : 0.3
[2022/05/05 03:04:59] root INFO:             MakeShrinkMap : 
[2022/05/05 03:04:59] root INFO:                 min_text_size : 8
[2022/05/05 03:04:59] root INFO:                 shrink_ratio : 0.4
[2022/05/05 03:04:59] root INFO:             NormalizeImage : 
[2022/05/05 03:04:59] root INFO:                 mean : [0.485, 0.456, 0.406]
[2022/05/05 03:04:59] root INFO:                 order : hwc
[2022/05/05 03:04:59] root INFO:                 scale : 1./255.
[2022/05/05 03:04:59] root INFO:                 std : [0.229, 0.224, 0.225]
[2022/05/05 03:04:59] root INFO:             ToCHWImage : None
[2022/05/05 03:04:59] root INFO:             KeepKeys : 
[2022/05/05 03:04:59] root INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2022/05/05 03:04:59] root INFO:     loader : 
[2022/05/05 03:04:59] root INFO:         batch_size_per_card : 4
[2022/05/05 03:04:59] root INFO:         drop_last : False
[2022/05/05 03:04:59] root INFO:         num_workers : 1
[2022/05/05 03:04:59] root INFO:         shuffle : True
[2022/05/05 03:04:59] root INFO:         use_shared_memory : False
[2022/05/05 03:04:59] root INFO: profiler_options : None
[2022/05/05 03:04:59] root INFO: train with paddle 2.2.2 and device XPUPlace(0)
[INFO][BKCL][baidu/xpu/bkcl/src/network/net_socket.cpp:37] NET/Socket : ipv4 net card [eth0], ip[172.17.0.2]
I0505 03:04:59.156913 24668 bkcl_context.cc:91] init BKCL context nranks: 2 local rank: 0 xpu id: 0 ring id: 0
[WARN][XPURT][xpu_llmalloc:185] ioctl() fail, (705) Device memory not enough
[WARN][BKCL][baidu/xpu/bkcl/src/kl1/kl1_init.cpp:35] xpu_malloc error [-705][WARN][BKCL][baidu/xpu/bkcl/src/init.cpp:561] init device param failed
[WARN][BKCL][baidu/xpu/bkcl/src/init.cpp:670] init_bkcl_context failed
Traceback (most recent call last):
  File "tools/train.py", line 150, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 47, in main
    dist.init_parallel_env()
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/parallel.py", line 225, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
RuntimeError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BKCLParallelContext::Init()
1   paddle::platform::BKCLCommContext::CreateComm(BKCLUniqueId*, int, int, int, int)
2   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: bkcl_init_rank failed, got wrong value [3].
  [Hint: Expected ret == BKCL_SUCCESS, but received ret:3 != BKCL_SUCCESS:0.] (at /home/bml/Paddle/paddle/fluid/platform/collective_helper.cc:305)

INFO 2022-05-05 03:05:04,049 launch_utils.py:341] terminate all the procs
ERROR 2022-05-05 03:05:04,049 launch_utils.py:604] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-05-05 03:05:08,054 launch_utils.py:341] terminate all the procs
INFO 2022-05-05 03:05:08,054 launch.py:311] Local processes completed.

**Comment by drenched9** [comment]
还是无人回应==！自己先回复一下。
通过摸索，发现可以注释部分初始化等代码，让代码正常跑起来。但是多机多卡必须要依赖那部分代码，导致运行还是报错。。。
