### ISSUE TITLE
使用德语ocr模型报错：list index out of range

### ISSUE THREAD

**Issue by yc0619** [PaddlePaddle/PaddleOCR#6155]
- 系统环境/System Environment：ubuntu 20.04
- 版本号/Version：Paddle：paddlepaddle 2.2.2  PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：
```
from paddleocr import PaddleOCR

p_ocr = PaddleOCR(use_angle_cls=True, lang='german')
img_path = './musterrechnung.jpg'
result = p_ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
```
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "/dir.ki-project/dir.Ki/src/develop/ocr/tool/test.py", line 6, in <module>
    result = p_ocr.ocr(img_path, cls=True)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 383, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 89, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py", line 375, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 98, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 66, in decode
    for text_id in text_index[batch_idx][selection]
  File "/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 66, in <listcomp>
    for text_id in text_index[batch_idx][selection]
IndexError: list index out of range
```

Debug 信息
```
ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/ki/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/ki/.paddleocr/whl/det/en/en_ppocr_mobile_v2.0_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='german', layout=True, layout_label_map=None, layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, mode='structure', ocr=True, ocr_version='PP-OCRv2', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='/home/ki/miniconda3/envs/ocr/lib/python3.7/site-packages/paddleocr/ppocr/utils/dict/german_dict.txt', rec_image_shape='3, 32, 320', rec_model_dir='/home/ki/.paddleocr/whl/rec/german/german_mobile_v2.0_rec_infer', save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], show_log=True, structure_version='STRUCTURE', table=True, table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=False, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2022/05/06 14:38:41] ppocr DEBUG: dt_boxes num : 48, elapse : 0.37480688095092773
[2022/05/06 14:38:41] ppocr DEBUG: cls num  : 48, elapse : 0.28770899772644043
```

**Comment by yc0619** [comment]
scipy 1.5.0
numpy 1.19.1

**Comment by andyjpaddle** [comment]
可以用最新版代码试试哈

**Comment by yc0619** [comment]
> 可以用最新版代码试试哈
你好，我用的是版本如下(使用pip更新了最新的paddleocr)：
paddleocr 2.5
paddlepaddle 2.2.2
但是代码还是报一样的list out of range的错误。

**Comment by andyjpaddle** [comment]
还要更新一下本地代码哈，用最新的2.5分支的代码

**Comment by yc0619** [comment]
请问怎么更新本地代码？可以详细说明一下吗？谢谢！

**Comment by AndyHUI711** [comment]
一样的问题，请问您解决了吗？

**Comment by andyjpaddle** [comment]
> 请问怎么更新本地代码？可以详细说明一下吗？谢谢！
重新clone代码或者git pull一下最新的代码，另外推荐使用paddlepaddle最新版2.3

**Comment by andyjpaddle** [comment]
> 一样的问题，请问您解决了吗？

我这边用最新代码没有问题呢

**Comment by nkrot** [comment]
so, how is this issue solved?

**Comment by yc0619** [comment]
> 一样的问题，请问您解决了吗？

我最后用的tesserocr

**Comment by andyjpaddle** [comment]
用最新的paddleocr包，2.5.0.3，我这边测试是没问题的，可以更新一下试试
