### ISSUE TITLE
PGNet评估测试时均报错

### ISSUE THREAD

**Issue by qqqqq127** [PaddlePaddle/PaddleOCR#6188]
[2022/05/09 09:49:17] root INFO: Architecture :
[2022/05/09 09:49:17] root INFO:     Backbone :
[2022/05/09 09:49:17] root INFO:         layers : 50
[2022/05/09 09:49:17] root INFO:         name : ResNet
[2022/05/09 09:49:17] root INFO:     Head :
[2022/05/09 09:49:17] root INFO:         name : PGHead
[2022/05/09 09:49:17] root INFO:     Neck :
[2022/05/09 09:49:17] root INFO:         name : PGFPN
[2022/05/09 09:49:17] root INFO:     Transform : None
[2022/05/09 09:49:17] root INFO:     algorithm : PGNet
[2022/05/09 09:49:17] root INFO:     model_type : e2e
[2022/05/09 09:49:17] root INFO: Eval :
[2022/05/09 09:49:17] root INFO:     dataset :
[2022/05/09 09:49:17] root INFO:         data_dir : ./train_data/
[2022/05/09 09:49:17] root INFO:         label_file_list : ['./train_data/SXB_test/Label.txt']
[2022/05/09 09:49:17] root INFO:         name : PGDataSet
[2022/05/09 09:49:17] root INFO:         transforms :
[2022/05/09 09:49:17] root INFO:             DecodeImage :
[2022/05/09 09:49:17] root INFO:                 channel_first : False
[2022/05/09 09:49:17] root INFO:                 img_mode : BGR
[2022/05/09 09:49:17] root INFO:             E2ELabelEncodeTest : None
[2022/05/09 09:49:17] root INFO:             E2EResizeForTest :
[2022/05/09 09:49:17] root INFO:                 max_side_len : 768
[2022/05/09 09:49:17] root INFO:             NormalizeImage :
[2022/05/09 09:49:17] root INFO:                 mean : [0.485, 0.456, 0.406]
[2022/05/09 09:49:17] root INFO:                 order : hwc
[2022/05/09 09:49:17] root INFO:                 scale : 1./255.
[2022/05/09 09:49:17] root INFO:                 std : [0.229, 0.224, 0.225]
[2022/05/09 09:49:17] root INFO:             ToCHWImage : None
[2022/05/09 09:49:17] root INFO:             KeepKeys :
[2022/05/09 09:49:17] root INFO:                 keep_keys : ['image', 'shape', 'polys', 'texts', 'ignore_tags', 'img_id']
[2022/05/09 09:49:17] root INFO:     loader :
[2022/05/09 09:49:17] root INFO:         batch_size_per_card : 1
[2022/05/09 09:49:17] root INFO:         drop_last : False
[2022/05/09 09:49:17] root INFO:         num_workers : 0
[2022/05/09 09:49:17] root INFO:         shuffle : False
[2022/05/09 09:49:17] root INFO: Global :
[2022/05/09 09:49:17] root INFO:     cal_metric_during_train : False
[2022/05/09 09:49:17] root INFO:     character_dict_path : ppocr/utils/ppocr_keys_v1.txt
[2022/05/09 09:49:17] root INFO:     character_type : CH
[2022/05/09 09:49:17] root INFO:     checkpoints : None
[2022/05/09 09:49:17] root INFO:     debug : False
[2022/05/09 09:49:17] root INFO:     distributed : False
[2022/05/09 09:49:17] root INFO:     epoch_num : 200
[2022/05/09 09:49:17] root INFO:     eval_batch_step : [0, 2000]
[2022/05/09 09:49:17] root INFO:     infer_img : train_data/SXB_test/img_1551.jpg
[2022/05/09 09:49:17] root INFO:     load_static_weights : False
[2022/05/09 09:49:17] root INFO:     log_smooth_window : 20
[2022/05/09 09:49:17] root INFO:     max_text_length : 100
[2022/05/09 09:49:17] root INFO:     max_text_nums : 100
[2022/05/09 09:49:17] root INFO:     pretrained_model : ./output/pgnet_r50_vd/latest
[2022/05/09 09:49:17] root INFO:     print_batch_step : 10
[2022/05/09 09:49:17] root INFO:     save_epoch_step : 200
[2022/05/09 09:49:17] root INFO:     save_inference_dir : None
[2022/05/09 09:49:17] root INFO:     save_model_dir : ./output/pgnet_r50_vd/
[2022/05/09 09:49:17] root INFO:     save_res_path : ./output/pgnet_r50_vd_totaltext/predicts_pgnet.txt
[2022/05/09 09:49:17] root INFO:     tcl_len : 64
[2022/05/09 09:49:17] root INFO:     use_gpu : True
[2022/05/09 09:49:17] root INFO:     use_visualdl : False
[2022/05/09 09:49:17] root INFO:     valid_set : totaltext
[2022/05/09 09:49:17] root INFO: Loss :
[2022/05/09 09:49:17] root INFO:     max_text_length : 50
[2022/05/09 09:49:17] root INFO:     max_text_nums : 30
[2022/05/09 09:49:17] root INFO:     name : PGLoss
[2022/05/09 09:49:17] root INFO:     pad_num : 36
[2022/05/09 09:49:17] root INFO:     tcl_bs : 64
[2022/05/09 09:49:17] root INFO: Metric :
[2022/05/09 09:49:17] root INFO:     character_dict_path : ppocr/utils/ppocr_keys_v1.txt
[2022/05/09 09:49:17] root INFO:     gt_mat_dir : None
[2022/05/09 09:49:17] root INFO:     main_indicator : f_score_e2e
[2022/05/09 09:49:17] root INFO:     mode : A
[2022/05/09 09:49:17] root INFO:     name : E2EMetric
[2022/05/09 09:49:17] root INFO: Optimizer :
[2022/05/09 09:49:17] root INFO:     beta1 : 0.9
[2022/05/09 09:49:17] root INFO:     beta2 : 0.999
[2022/05/09 09:49:17] root INFO:     lr :
[2022/05/09 09:49:17] root INFO:         learning_rate : 0.001
[2022/05/09 09:49:17] root INFO:     name : Adam
[2022/05/09 09:49:17] root INFO:     regularizer :
[2022/05/09 09:49:17] root INFO:         factor : 0
[2022/05/09 09:49:17] root INFO:         name : L2
[2022/05/09 09:49:17] root INFO: PostProcess :
[2022/05/09 09:49:17] root INFO:     mode : fast
[2022/05/09 09:49:17] root INFO:     name : PGPostProcess
[2022/05/09 09:49:17] root INFO:     score_thresh : 0.5
[2022/05/09 09:49:17] root INFO: Train :
[2022/05/09 09:49:17] root INFO:     dataset :
[2022/05/09 09:49:17] root INFO:         data_dir : ./train_data/
[2022/05/09 09:49:17] root INFO:         label_file_list : ['./train_data/SXB_train/Label.txt']
[2022/05/09 09:49:17] root INFO:         name : PGDataSet
[2022/05/09 09:49:17] root INFO:         ratio_list : [1.0]
[2022/05/09 09:49:17] root INFO:         transforms :
[2022/05/09 09:49:17] root INFO:             DecodeImage :
[2022/05/09 09:49:17] root INFO:                 channel_first : False
[2022/05/09 09:49:17] root INFO:                 img_mode : BGR
[2022/05/09 09:49:17] root INFO:             E2ELabelEncodeTrain : None
[2022/05/09 09:49:17] root INFO:             PGProcessTrain :
[2022/05/09 09:49:17] root INFO:                 batch_size : 14
[2022/05/09 09:49:17] root INFO:                 max_text_size : 512
[2022/05/09 09:49:17] root INFO:                 min_crop_size : 24
[2022/05/09 09:49:17] root INFO:                 min_text_size : 4
[2022/05/09 09:49:17] root INFO:             KeepKeys :
[2022/05/09 09:49:17] root INFO:                 keep_keys : ['images', 'tcl_maps', 'tcl_label_maps', 'border_maps', 'direction_maps', 'training_masks', 'label_list', 'pos_list', 'pos_mask']
[2022/05/09 09:49:17] root INFO:     loader :
[2022/05/09 09:49:17] root INFO:         batch_size_per_card : 16
[2022/05/09 09:49:17] root INFO:         drop_last : True
[2022/05/09 09:49:17] root INFO:         num_workers : 0
[2022/05/09 09:49:17] root INFO:         shuffle : True
[2022/05/09 09:49:17] root INFO: profiler_options : None
[2022/05/09 09:49:17] root INFO: train with paddle 2.2.2 and device CUDAPlace(0)
W0509 09:49:17.388212 146352 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.5, Runtime API Version: 11.1
W0509 09:49:17.390826 146352 device_context.cc:465] device: 0, cuDNN Version: 8.0.
W0509 09:49:19.281210 146352 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[2022/05/09 09:49:21] root INFO: load pretrain successful from ./output/pgnet_r50_vd/latest
[2022/05/09 09:49:21] root INFO: infer_img: train_data/SXB_test/img_1551.jpg
Traceback (most recent call last):
  File "tools/infer_e2e.py", line 122, in <module>
    main()
  File "tools/infer_e2e.py", line 105, in main
    post_result = post_process_class(preds, shape_list)
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/postprocess/pg_postprocess.py", line 49, in __call__
    data = post.pg_postprocess_fast()
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/utils/e2e_utils/pgnet_pp_utils.py", line 56, in pg_postprocess_fast
    instance_yxs_list, seq_strs = generate_pivot_list_fast(
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 381, in generate_pivot_list_fast
    pos_list_sorted = sort_and_expand_with_direction_v2(
  File "/data/ocr/PaddleOCR-release-2.4-new/ppocr/utils/e2e_utils/extract_textpoint_fast.py", line 241, in sort_and_expand_with_direction_v2
    int((left_average_len + right_average_len) / 2.0 * 0.15), 1)
OverflowError: cannot convert float infinity to integer

**Comment by littletomatodonkey** [comment]
你好，看着是计算异常，这个模型的精度是多少呢？

**Comment by qqqqq127** [comment]
> 

你好，没法评估的话，精度怎么看呢
