### ISSUE TITLE
paddleocr转换模型inference成功了但是测试的时候报错，没看懂有没有大佬解释一下

### ISSUE THREAD

**Issue by wfm777** [PaddlePaddle/PaddleOCR#6208]
Traceback (most recent call last):
  File "/ocr/tools/infer/ocr/predict_system.py", line 229, in <module>
    main(args)
  File "/ocr/tools/infer/ocr/predict_system.py", line 177, in main
    dt_boxes, rec_res = text_sys(img)
  File "/ocr/tools/infer/ocr/predict_system.py", line 91, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/ocr/tools/infer/ocr/predict_rec.py", line 359, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 129, in <module>
      main()
    File "tools/export_model.py", line 125, in main
      export_single_model(model, arch_config, save_path, logger)
    File "tools/export_model.py", line 80, in export_single_model
      paddle.jit.save(model, save_path)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 743, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/home/ptadmin/OCR_project/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 75, in forward
      x = self.backbone(x)
    File "/home/ptadmin/OCR_project/PaddleOCR/ppocr/modeling/backbones/rec_resnet_fpn.py", line 150, in __call__
      x = self.conv(x)
    File "/home/ptadmin/OCR_project/PaddleOCR/ppocr/modeling/backbones/rec_resnet_fpn.py", line 212, in __call__
      x = self.conv(x)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 665, in forward
      out = F.conv._conv_nd(
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 147, in _conv_nd
      helper.append_op(
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/home/exit/envs/ocr/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(x) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1595)
      [operator < conv2d > error]

**Comment by littletomatodonkey** [comment]
看着是conv2d没有初始化，可能导出的时候节点有点问题，可以先不串联，先看下单独导出模型的效果
