### ISSUE TITLE
Warning! SRN does not support export model currently

### ISSUE THREAD

**Issue by Meicsu199345** [PaddlePaddle/PaddleOCR#634]
在线等更大佬们，梭哈srn了，急，危，秋泥膏更新整一个，再整个中文预训练模型带佬
warnings.warn("Caution! 'set_gradient_clip' is not recommended "
Traceback (most recent call last):
  File "tools/export_model.py", line 75, in <module>
    main()
  File "tools/export_model.py", line 51, in main
    config, eval_program, startup_prog)
  File "/data/kezhiyin01/kezhiyin01/kezhiyin-aicoach-146/baidu/PaddleOCR-adaptation_ch/tools/program.py", line 211, in build_export
    image, outputs = model(mode='export')
  File "/data/kezhiyin01/kezhiyin01/kezhiyin-aicoach-146/baidu/PaddleOCR-adaptation_ch/ppocr/modeling/architectures/rec_model.py", line 222, in __call__
    "Warning! SRN does not support export model currently")
Exception: Warning! SRN does not support export model currently

**Comment by Meicsu199345** [comment]
按照教程用infer_rec.py
# 预测中文结果
python3 tools/infer_rec.py -c configs/rec/rec_chinese_lite_train.yml -o Global.checkpoints={path/to/weights}/best_accuracy Global.infer_img=doc/imgs_words/ch/word_1.jpg
预测图片：

AssertionError: Each dimension value of 'shape' in reshape must not be negative except one unknown dimension. But received shape[2] = -4.

**Comment by littletomatodonkey** [comment]
你好，SRN export model的模块我们正在实现，等集成好了就会开源，敬请期待~

**Comment by deep-practice** [comment]
能提供个SRN的中文预训练模型吗

**Comment by MissPenguin** [comment]
> 能提供个SRN的中文预训练模型吗

SRN的中文模型暂时没时间搞，需要的话可以自己训练哈，目前已经支持使用自定义中文数据集训练
