### ISSUE TITLE
centos7 python3.9  这种怎么解决呢

### ISSUE THREAD

**Issue by ProsperousSun** [PaddlePaddle/PaddleOCR#6351]
Python 3.9.0 (default, Apr  8 2021, 18:43:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/core.py", line 357, in <module>
    raise e
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/core.py", line 309, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'

**Comment by ProsperousSun** [comment]
python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install "paddleocr>=2.0.1"   
甚至还会出现这种循环依赖的问题。

Python 3.9.0 (default, Apr  8 2021, 18:43:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/core.py", line 365, in <module>
    raise e
  File "/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/core.py", line 313, in <module>
    from . import core_noavx
ImportError: cannot import name 'core_noavx' from partially initialized module 'paddle.fluid' (most likely due to a circular import) (/deploy/venv3/lib/python3.9/site-packages/paddle/fluid/__init__.py)

**Comment by Gmgge** [comment]
1.paddlepaddle在2.0.0是同时支持avx和no_avx的，在此之后便不在支持，所以可以安装2.0.0版本。
2.你的机器不支持avx指令，如果需要安装新版本，需要在飞浆官方下载no_avx支持的whl包，或者自行编译。
