### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 325-326:

### ISSUE THREAD

**Issue by wuvalue** [PaddlePaddle/PaddleOCR#6364]
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\__init__.py", line 52, in <module>
    from . import io
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\io.py", line 31, in <module>
    from paddle.fluid import layers
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layers\__init__.py", line 17, in <module>
    from . import ops
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layers\ops.py", line 82, in <module>
    globals()['_scale'] = generate_layer_fn('scale')
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layers\layer_function_generator.py", line 149, in generate_layer_fn
    op_proto = OpProtoHolder.instance().get_op_proto(op_type)
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py", line 2487, in instance
    cls._instance = cls()
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py", line 2494, in __init__
    op_protos = get_all_op_protos()
  File "C:\Users\wu\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py", line 2474, in get_all_op_protos
    op_proto = framework_pb2.OpProto.FromString(six.binary_type(pbstr))
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 801, in FromString
    message.MergeFromString(s)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1128, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1195, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 705, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1195, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 591, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 553, in _ConvertToUnicode
    value = str(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 325-326: 'utf-8' codec can't decode bytes in position 325-326: invalid continuation byte in field: paddle.framework.proto.OpProto.Attr.comment

paddlepaddle-gpu==0.0.0.post115 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html

**Comment by littletomatodonkey** [comment]
你好，升级下protobuf看下呢？
