### ISSUE TITLE
cannot import name 'inference' from 'paddle'

### ISSUE THREAD

**Issue by Stephenzho** [PaddlePaddle/PaddleOCR#6371]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
paddleocr --image_dir C:/Users/admin/Pictures/微信图片_20220521091100.jpg 
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\Scripts\paddleocr.exe\__main__.py", line 4, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\paddleocr\paddleocr.py", line 29, in <module>
    from tools.infer import predict_system
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 30, in <module>
    import tools.infer.utility as utility
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\paddleocr\tools\infer\utility.py", line 23, in <module>
    from paddle import inference
ImportError: cannot import name 'inference' from 'paddle' (C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\__init__.py)

- 系统环境/System Environment： windows11
- 版本号/Version：Paddle：1.0.2  PaddleOCR：2.3.0.2 问题相关组件/Related components：
- 运行指令/Command Code：paddleocr --image_dir C:/Users/admin/Pictures/微信图片_20220521091100.jpg 
- 完整报错/Complete Error Message：

**Comment by MissPenguin** [comment]
安装paddle了吗

**Comment by finch-ift** [comment]
> paddleocr

安装了paddle-1.0.2
还是报错ImportError: cannot import name 'inference' from 'paddle'

**Comment by yxdwind** [comment]
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html
按照官网的步骤操作，也是报同样的错误

**Comment by yxdwind** [comment]
<img width="796" alt="1665722105662" src="https://user-images.githubusercontent.com/8383118/195763327-c84dc86f-1b32-468b-b420-7f04138007de.png">
