### ISSUE TITLE
cannot import name 'OCRSystem' from 'ppstructure.predict_system'

### ISSUE THREAD

**Issue by chldong** [PaddlePaddle/PaddleOCR#6378]
Run “python .\PPOCRLabel.py --lang=ch” Prompt as the title

**Comment by chldong** [comment]
Windows 10 Python 3.8.12

**Comment by chldong** [comment]
❯ python .\PPOCRLabel.py --lang=ch
Traceback (most recent call last):
  File ".\PPOCRLabel.py", line 40, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "C:\ProgramData\Miniconda3\envs\hub\lib\site-packages\paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "C:\ProgramData\Miniconda3\envs\hub\lib\site-packages\paddleocr\paddleocr.py", line 37, in <module>
    from ppstructure.predict_system import OCRSystem, save_structure_res
ImportError: cannot import name 'OCRSystem' from 'ppstructure.predict_system' (C:\Users\Administrator\Github\PaddleOCR\ppstructure\predict_system.py)

**Comment by sajidali22** [comment]
I had the same issue , just update paddleocr package, 'pip install -U paddleocr'
