### ISSUE TITLE
安装完成后运行测试代码提示SSLerror SSL module is not available

### ISSUE THREAD

**Issue by shixnjs** [PaddlePaddle/PaddleOCR#6417]
windows 10 python3.8 
运行如下代码时：
from paddleocr import PaddleOCR

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(lang="ch")  #
img_path = r'D:\PYcode\1.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
出现报错requests.exceptions.SSLError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

完整报错如下：
download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to C:\Users\86134/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer\ch_PP-OCRv3_det_infer.tar
Traceback (most recent call last):
  File "D:\anaconda\envs\paddle_env\lib\site-packages\urllib3\connectionpool.py", line 692, in urlopen   
    conn = self._get_conn(timeout=pool_timeout)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\urllib3\connectionpool.py", line 281, in _get_conn 
    return conn or self._new_conn()
  File "D:\anaconda\envs\paddle_env\lib\site-packages\urllib3\connectionpool.py", line 1009, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\paddle_env\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\anaconda\envs\paddle_env\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\anaconda\envs\paddle_env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/PaddleOCR-release-2.5/ocr.py", line 5, in <module>
    ocr = PaddleOCR(lang="ch")  #
  File "d:\PaddleOCR-release-2.5\paddleocr.py", line 420, in __init__
    maybe_download(params.det_model_dir, det_url)
  File "d:\PaddleOCR-release-2.5\ppocr\utils\network.py", line 55, in maybe_download
    download_with_progressbar(url, tmp_path)
  File "d:\PaddleOCR-release-2.5\ppocr\utils\network.py", line 26, in download_with_progressbar
    response = requests.get(url, stream=True)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by littletomatodonkey** [comment]
你好，这个应该是python的ssl库没有安装正确，或者机器无法联网导致的

**Comment by shixnjs** [comment]
我刚刚安装完成时不会出现这个问题但是会出现
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.      
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).        

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
PS D:\PaddleOCR-release-2.5>
提示我下调protobuf版本，我按照提示下调之后就会出现sslerror。

**Comment by nil-is-lin** [comment]
遇到同样问题，
from paddleocr import PaddleOCR, draw_ocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python38\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\Python\Python38\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "D:\Python\Python38\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "D:\Python\Python38\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\Python\Python38\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "D:\Python\Python38\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\Python\Python38\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "D:\Python\Python38\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "D:\Python\Python38\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
