### ISSUE TITLE
我在写一个flutter安卓版插件,但是启动报错

### ISSUE THREAD

**Issue by mdddj** [PaddlePaddle/PaddleOCR#646]
```java
Launching lib\main.dart on L2 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Debug service listening on ws://127.0.0.1:59667/m_SREwK7pbg=/ws
Syncing files to device L2...
E/Predictor(30600): model path/data/user/0/shop.itbug.flutter_plugin_textocr_example/cache/models/ocr_v1_for_cpu/ch_det_mv3_db_opt.nb ; /data/user/0/shop.itbug.flutter_plugin_textocr_example/cache/models/ocr_v1_for_cpu/ch_rec_mv3_crnn_opt.nb
E/MethodChannel#flutter_plugin_textocr(30600): Failed to handle method call
E/MethodChannel#flutter_plugin_textocr(30600): java.lang.RuntimeException: Load libNative.so failed, please check it exists in apk file.
E/MethodChannel#flutter_plugin_textocr(30600): 	at ocrs.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:18)
E/MethodChannel#flutter_plugin_textocr(30600): 	at ocrs.OCRPredictorNative.<init>(OCRPredictorNative.java:31)
E/MethodChannel#flutter_plugin_textocr(30600): 	at ocrs.Predictor.loadModel(Predictor.java:128)
E/MethodChannel#flutter_plugin_textocr(30600): 	at ocrs.Predictor.init(Predictor.java:52)
E/MethodChannel#flutter_plugin_textocr(30600): 	at shop.itbug.flutter_plugin_textocr.FlutterPluginTextocrPlugin.onLoadModel(FlutterPluginTextocrPlugin.java:99)
E/MethodChannel#flutter_plugin_textocr(30600): 	at shop.itbug.flutter_plugin_textocr.FlutterPluginTextocrPlugin.onMethodCall(FlutterPluginTextocrPlugin.java:78)
E/MethodChannel#flutter_plugin_textocr(30600): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_plugin_textocr(30600): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_plugin_textocr(30600): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_plugin_textocr(30600): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_plugin_textocr(30600): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter_plugin_textocr(30600): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter_plugin_textocr(30600): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E/MethodChannel#flutter_plugin_textocr(30600): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_plugin_textocr(30600): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/MethodChannel#flutter_plugin_textocr(30600): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/MethodChannel#flutter_plugin_textocr(30600): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/shop.itbug.flutter_plugin_textocr_example-2/base.apk"],nativeLibraryDirectories=[/data/app/shop.itbug.flutter_plugin_textocr_example-2/lib/arm, /data/app/shop.itbug.flutter_plugin_textocr_example-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libNative.so"
E/MethodChannel#flutter_plugin_textocr(30600): 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
E/MethodChannel#flutter_plugin_textocr(30600): 	at java.lang.System.loadLibrary(System.java:1562)
E/MethodChannel#flutter_plugin_textocr(30600): 	at ocrs.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:16)
E/MethodChannel#flutter_plugin_textocr(30600): 	... 15 more

```

**Comment by bsse9803** [comment]
@[WenmuZhou](https://github.com/WenmuZhou) How did you solve? It is same with my log.

**Comment by AlvinZheng** [comment]
关闭了，倒是给个原因啊！！
