### ISSUE TITLE
Load libNative.so failed

### ISSUE THREAD

**Issue by wangxinit** [PaddlePaddle/PaddleOCR#6472]
请问这个问题怎么解决 小米手机  Android 9   paddleocr 2.5 分支

 -06-02 00:30:31.864 22163-22193/com.baidu.paddle.lite.demo.ocr E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.ocr, PID: 22163
    java.lang.RuntimeException: Load libNative.so failed, please check it exists in apk file.
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:18)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31)
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:95)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:46)
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:57)
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242)
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:158)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.baidu.paddle.lite.demo.ocr-aFNg-54nbYigY4pMyG_eBQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.baidu.paddle.lite.demo.ocr-aFNg-54nbYigY4pMyG_eBQ==/lib/arm, /system/lib]]] couldn't find "libNative.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.loadLibrary(OCRPredictorNative.java:16)
        at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:31) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:95) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:46) 
        at com.baidu.paddle.lite.demo.ocr.Predictor.init(Predictor.java:57) 
        at com.baidu.paddle.lite.demo.ocr.MainActivity.onLoadModel(MainActivity.java:242) 
        at com.baidu.paddle.lite.demo.ocr.MainActivity$2.handleMessage(MainActivity.java:158) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2022-06-02 00:30:31.896 22163-22193/com.baidu.paddle.lite.demo.ocr I/Process: Sending signal. PID: 22163 SIG: 9

**Comment by littletomatodonkey** [comment]
你好，可以参考这个[链接](https://gitee.com/paddlepaddle/PaddleOCR/issues/I2BLD4)修改看下哈
