### ISSUE TITLE
nvidia agx xaiver关于paddleocr使用python接口use_tensorrt报错的问题

### ISSUE THREAD

**Issue by SparkleXFantasy** [PaddlePaddle/PaddleOCR#6479]
在nvidia agx xavier上运行官方文档的python程序进行推理，使用默认的接口use_tensorrt=False时代码已经成功运行。当保持其他配置不变，通过接口设置use_tensorrt=True后，模型报错如下：

InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /home/paddle/data/wangye19/tag_release/Paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:287)

运行的demo程序使用paddleocr中的PaddleOCR接口，并设置参数use_tensorrt=True，输入的图片维度为(320x320), (512x512), (768x768), (960x960)，程序具体如下：

from time import time
from paddleocr import PaddleOCR, draw_ocr

def main():
    img_root = '../data/'
    file_name_list = [***]    # the input file list

    resize_dim_list = [(320, 320), (512, 512), (768, 768), (960, 960)]

    loop_time = 20
    img_num = loop_time * len(file_name_list)

    ocr = PaddleOCR(use_angle_cls=True, lang="en", use_gpu=True, use_tensorrt=True)

    f = open('record.txt', 'w')
    for dim in resize_dim_list:
        inference_time = 0
        f.write('-----------------------------------------------------\n')
        f.write('Resize dim: {}x{}\n'.format(dim[0], dim[1]))
        for i in range(loop_time):
            for file in file_name_list:
                img_path = img_root + file + '({}x{})'.format(dim[0], dim[1]) + '.jpeg'
                tic = time()
                result = ocr.ocr(img_path, det=True, cls=True)
                toc = time()
                inference_time += toc - tic
        avg_time = inference_time / img_num
        f.write('Average time: {:.4f}s\n'.format(avg_time))
        f.write('-----------------------------------------------------\n')
    f.close()

if __name__ == '__main__':
    main()

系统环境：
NVIDIA Jetson AGX Xavier [16GB] - Jetpack 4.6 [L4T 32.6.1]
Board:
* Type: AGX Xaiver[16GB]
* SOC Family: tegra194    ID:25
* Module: P2888-0001    Board:P2822-0000
* Code Name: galen
* Cuda ARCH:7.2

Libraries:
* CUDA: 10.2.300
* OpenCV: 4.1.1    compiled CUDA:NO
* TensorRT: 8.0.1.6
* VPI: ii libnvvpil 1.1.12 arm64 NVIDIA Vision Programming Interface Library
* VisionWorks: 1.6.0.501
* Vulkan: 1.2.70
* cuDNN: 8.2.1.32

Paddle相关版本：
paddlepaddle-gpu    2.3.0    pypi_0    pypi
paddleocr    2.5.0.3    pypi_0    pypi

完整报错：
[2022/06/02 21:27:24] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/agxmaster/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/agxmaster/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir=None, ir_optim=True, label_list=['0', '180'], lang='en', layout=True, layout_label_map=None, layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', max_batch_size=10, max_text_length=25, min_subgraph_size=15, mode='structure', ocr=True, ocr_version='PP-OCRv3', output='./output', precision='fp32', process_id=0, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/home/agxmaster/miniforge3/envs/paddleocr/lib/python3.6/site-packages/paddleocr/ppocr/utils/en_dict.txt', rec_image_shape='3, 48, 320', rec_model_dir='/home/agxmaster/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer', save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], show_log=True, structure_version='PP-STRUCTURE', table=True, table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=True, use_mp=False, use_onnx=False, use_pdserving=False, use_space_char=True, use_tensorrt=True, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
Traceback (most recent call last):
  File "paddleocr_avp.py", line 66, in <module>
    main()
  File "paddleocr_avp.py", line 41, in main
    ocr = PaddleOCR(use_angle_cls=True, lang="en", use_gpu=True, use_tensorrt=True)
  File "/home/agxmaster/miniforge3/envs/paddleocr/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 437, in __init__
    super().__init__(params)
  File "/home/agxmaster/miniforge3/envs/paddleocr/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 47, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "/home/agxmaster/miniforge3/envs/paddleocr/lib/python3.6/site-packages/paddleocr/tools/infer/predict_rec.py", line 74, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "/home/agxmaster/miniforge3/envs/paddleocr/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 312, in create_predictor
    predictor = inference.create_predictor(config)
ValueError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)

3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
13  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /home/paddle/data/wangye19/tag_release/Paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:287)

**Comment by littletomatodonkey** [comment]
你好，可以试着加上这句话试下

https://github.com/PaddlePaddle/PaddleOCR/blob/36f9a0d253093e29c74181a4c38794fc43563608/tools/infer/utility.py#L280
