### ISSUE TITLE
Fine Tuning error: AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict

### ISSUE THREAD

**Issue by emigomez** [PaddlePaddle/PaddleOCR#6481]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows
- 版本号/Version：Last in master branch Paddle：  PaddleOCR： 问题相关组件/Related components：CUDA and Cudnn as indicated in the repo, python 3.8
- 运行指令/Command Code：python tools/train.py -c configs/rec/rec_icdar15_train.yml -o Global.checkpoints=./../models/best_accuracy
- 完整报错/Complete Error Message：
```
............................................._fw.bias_hh', 'neck.encoder.lstm.1.cell_bw.weight_ih', 'neck.encoder.lstm.1.cell_bw.weight_hh', 'neck.encoder.lstm.1.cell_bw.bias_ih', 'neck.encoder.lstm.1.cell_bw.bias_hh', 'head.fc.weight', 'head.fc.bias']) !
[2022/06/02 16:43:42] ppocr WARNING: backbone.blocks.14.linear_conv.bn._variance not in loaded params dict_keys(['backbone.conv1.conv.weight', 'backbone.conv1.bn.weight', 'backbone.conv1.bn.bias', 'backbone.conv1.bn._mean', 'backbone.conv1.bn._variance', 'backbone.blocks.0.expand_conv.conv.weight', 'backbone.blocks.0.expand_conv.bn.weight', 'backbone.blocks.0.expand_conv.bn.bias', 'backbone.blocks.0.expand_conv.bn._mean', 'backbone.blocks.0.expand_conv.bn._variance', 'backbone.blocks.0.bottleneck_conv.conv.weight', 'backbone.blocks.0.bottleneck_conv.bn.weight', 'backbone.blocks.0.bottleneck_conv.bn.bias', 'backbone.blocks.0.bottleneck_conv.bn._mean', 'backbone.blocks.0.bottleneck_conv.bn._variance', 'backbone.blocks.0.mid_se.conv1.weight', 'backbone.blocks.0.mid_se.conv1.bias', 'backbone.blocks.0.mid_se.conv2.weight', 'backbone.blocks.0.mid_se.conv2.bias', 'backbone.blocks.0.linear_conv.conv.weight', 'backbone.blocks.0.linear_conv.bn.weight', 'backbone.blocks.0.linear_conv.bn.bias', 'backbone.blocks.0.linear_conv.bn._mean', 'backbone.blocks.0.linear_conv.bn._variance', 'backbone.blocks.1.expand_conv.conv.weight', 'backbone.blocks.1.expand_conv.bn.weight', 'backbone.blocks.1.expand_conv.bn.bias', 'backbone.blocks.1.expand_conv.bn._mean', 'backbone.blocks.1.expand_conv.bn._variance', 'backbone.blocks.1.bottleneck_conv.conv.weight', 'backbone.blocks.1.bottleneck_conv.bn.weight', 'backbone.blocks.1.bottleneck_conv.bn.bias', 'backbone.blocks.1.bottleneck_conv.bn._mean', 'backbone.blocks.1.bottleneck_conv.bn._variance', 'backbone.blocks.1.linear_conv.conv.weight', 'backbone.blocks.1.linear_conv.bn.weight', 'backbone.blocks.1.linear_conv.bn.bias', 'backbone.blocks.1.linear_conv.bn._mean', 'backbone.blocks.1.linear_conv.bn._variance', 
'backbone.blocks.2.expand_conv.conv.weight', 'backbone.blocks.2.expand_conv.bn.weight', 'backbone.blocks.2.expand_conv.bn.bias', 'backbone.blocks.2.expand_conv.bn._mean', 'backbone.blocks.2.expand_conv.bn._variance', 'backbone.blocks.2.bottleneck_conv.conv.weight', 'backbone.blocks.2.bottleneck_conv.bn.weight', 'backbone.blocks.2.bottleneck_conv.bn.bias', 'backbone.blocks.2.bottleneck_conv.bn._mean', 'backbone.blocks.2.bottleneck_conv.bn._variance', 'backbone.blocks.2.linear_conv.conv.weight', 'backbone.blocks.2.linear_conv.bn.weight', 'backbone.blocks.2.linear_conv.bn.bias', 'backbone.blocks.2.linear_conv.bn._mean', 'backbone.blocks.2.linear_conv.bn._variance', 'backbone.blocks.3.expand_conv.conv.weight', 'backbone.blocks.3.expand_conv.bn.weight', 'backbone.blocks.3.expand_conv.bn.bias', 'backbone.blocks.3.expand_conv.bn._mean', 'backbone.blocks.3.expand_conv.bn._variance', 'backbone.blocks.3.bottleneck_conv.conv.weight', 'backbone.blocks.3.bottleneck_conv.bn.weight', 'backbone.blocks.3.bottleneck_conv.bn.bias', 'backbone.blocks.3.bottleneck_conv.bn._mean', 'backbone.blocks.3.bottleneck_conv.bn._variance', 'backbone.blocks.3.mid_se.conv1.weight', 'backbone.blocks.3.mid_se.conv1.bias', 'backbone.blocks.3.mid_se.conv2.weight', 'backbone.blocks.3.mid_se.conv2.bias', 'backbone.blocks.3.linear_conv.conv.weight', 'backbone.blocks.3.linear_conv.bn.weight', 'backbone.blocks.3.linear_conv.bn.bias', 'backbone.blocks.3.linear_conv.bn._mean', 'backbone.blocks.3.linear_conv.bn._variance', 'backbone.blocks.4.expand_conv.conv.weight', 'backbone.blocks.4.expand_conv.bn.weight', 'backbone.blocks.4.expand_conv.bn.bias', 'backbone.blocks.4.expand_conv.bn._mean', 'backbone.blocks.4.expand_conv.bn._variance', 'backbone.blocks.4.bottleneck_conv.conv.weight', 'backbone.blocks.4.bottleneck_conv.bn.weight', 'backbone.blocks.4.bottleneck_conv.bn.bias', 'backbone.blocks.4.bottleneck_conv.bn._mean', 'backbone.blocks.4.bottleneck_conv.bn._variance', 'backbone.blocks.4.mid_se.conv1.weight', 'backbone.blocks.4.mid_se.conv1.bias', 'backbone.blocks.4.mid_se.conv2.weight', 'backbone.blocks.4.mid_se.conv2.bias', 'backbone.blocks.4.linear_conv.conv.weight', 'backbone.blocks.4.linear_conv.bn.weight', 'backbone.blocks.4.linear_conv.bn.bias', 'backbone.blocks.4.linear_conv.bn._mean', 'backbone.blocks.4.linear_conv.bn._variance', 'backbone.blocks.5.expand_conv.conv.weight', 'backbone.blocks.5.expand_conv.bn.weight', 'backbone.blocks.5.expand_conv.bn.bias', 'backbone.blocks.5.expand_conv.bn._mean', 'backbone.blocks.5.expand_conv.bn._variance', 'backbone.blocks.5.bottleneck_conv.conv.weight', 'backbone.blocks.5.bottleneck_conv.bn.weight', 'backbone.blocks.5.bottleneck_conv.bn.bias', 'backbone.blocks.5.bottleneck_conv.bn._mean', 'backbone.blocks.5.bottleneck_conv.bn._variance', 'backbone.blocks.5.mid_se.conv1.weight', 'backbone.blocks.5.mid_se.conv1.bias', 'backbone.blocks.5.mid_se.conv2.weight', 'backbone.blocks.5.mid_se.conv2.bias', 'backbone.blocks.5.linear_conv.conv.weight', 'backbone.blocks.5.linear_conv.bn.weight', 'backbone.blocks.5.linear_conv.bn.bias', 'backbone.blocks.5.linear_conv.bn._mean', 'backbone.blocks.5.linear_conv.bn._variance', 'backbone.blocks.6.expand_conv.conv.weight', 'backbone.blocks.6.expand_conv.bn.weight', 'backbone.blocks.6.expand_conv.bn.bias', 'backbone.blocks.6.expand_conv.bn._mean', 'backbone.blocks.6.expand_conv.bn._variance', 'backbone.blocks.6.bottleneck_conv.conv.weight', 'backbone.blocks.6.bottleneck_conv.bn.weight', 'backbone.blocks.6.bottleneck_conv.bn.bias', 'backbone.blocks.6.bottleneck_conv.bn._mean', 'backbone.blocks.6.bottleneck_conv.bn._variance', 'backbone.blocks.6.mid_se.conv1.weight', 'backbone.blocks.6.mid_se.conv1.bias', 'backbone.blocks.6.mid_se.conv2.weight', 'backbone.blocks.6.mid_se.conv2.bias', 'backbone.blocks.6.linear_conv.conv.weight', 'backbone.blocks.6.linear_conv.bn.weight', 'backbone.blocks.6.linear_conv.bn.bias', 'backbone.blocks.6.linear_conv.bn._mean', 'backbone.blocks.6.linear_conv.bn._variance', 'backbone.blocks.7.expand_conv.conv.weight', 'backbone.blocks.7.expand_conv.bn.weight', 'backbone.blocks.7.expand_conv.bn.bias', 'backbone.blocks.7.expand_conv.bn._mean', 'backbone.blocks.7.expand_conv.bn._variance', 'backbone.blocks.7.bottleneck_conv.conv.weight', 'backbone.blocks.7.bottleneck_conv.bn.weight', 'backbone.blocks.7.bottleneck_conv.bn.bias', 'backbone.blocks.7.bottleneck_conv.bn._mean', 'backbone.blocks.7.bottleneck_conv.bn._variance', 'backbone.blocks.7.mid_se.conv1.weight', 'backbone.blocks.7.mid_se.conv1.bias', 'backbone.blocks.7.mid_se.conv2.weight', 'backbone.blocks.7.mid_se.conv2.bias', 'backbone.blocks.7.linear_conv.conv.weight', 'backbone.blocks.7.linear_conv.bn.weight', 'backbone.blocks.7.linear_conv.bn.bias', 'backbone.blocks.7.linear_conv.bn._mean', 'backbone.blocks.7.linear_conv.bn._variance', 'backbone.blocks.8.expand_conv.conv.weight', 'backbone.blocks.8.expand_conv.bn.weight', 'backbone.blocks.8.expand_conv.bn.bias', 'backbone.blocks.8.expand_conv.bn._mean', 'backbone.blocks.8.expand_conv.bn._variance', 'backbone.blocks.8.bottleneck_conv.conv.weight', 'backbone.blocks.8.bottleneck_conv.bn.weight', 'backbone.blocks.8.bottleneck_conv.bn.bias', 'backbone.blocks.8.bottleneck_conv.bn._mean', 'backbone.blocks.8.bottleneck_conv.bn._variance', 'backbone.blocks.8.mid_se.conv1.weight', 'backbone.blocks.8.mid_se.conv1.bias', 'backbone.blocks.8.mid_se.conv2.weight', 'backbone.blocks.8.mid_se.conv2.bias', 'backbone.blocks.8.linear_conv.conv.weight', 'backbone.blocks.8.linear_conv.bn.weight', 'backbone.blocks.8.linear_conv.bn.bias', 'backbone.blocks.8.linear_conv.bn._mean', 'backbone.blocks.8.linear_conv.bn._variance', 'backbone.blocks.9.expand_conv.conv.weight', 'backbone.blocks.9.expand_conv.bn.weight', 'backbone.blocks.9.expand_conv.bn.bias', 'backbone.blocks.9.expand_conv.bn._mean', 'backbone.blocks.9.expand_conv.bn._variance', 'backbone.blocks.9.bottleneck_conv.conv.weight', 'backbone.blocks.9.bottleneck_conv.bn.weight', 'backbone.blocks.9.bottleneck_conv.bn.bias', 'backbone.blocks.9.bottleneck_conv.bn._mean', 'backbone.blocks.9.bottleneck_conv.bn._variance', 'backbone.blocks.9.mid_se.conv1.weight', 'backbone.blocks.9.mid_se.conv1.bias', 'backbone.blocks.9.mid_se.conv2.weight', 'backbone.blocks.9.mid_se.conv2.bias', 'backbone.blocks.9.linear_conv.conv.weight', 'backbone.blocks.9.linear_conv.bn.weight', 'backbone.blocks.9.linear_conv.bn.bias', 'backbone.blocks.9.linear_conv.bn._mean', 'backbone.blocks.9.linear_conv.bn._variance', 'backbone.blocks.10.expand_conv.conv.weight', 'backbone.blocks.10.expand_conv.bn.weight', 'backbone.blocks.10.expand_conv.bn.bias', 'backbone.blocks.10.expand_conv.bn._mean', 'backbone.blocks.10.expand_conv.bn._variance', 'backbone.blocks.10.bottleneck_conv.conv.weight', 'backbone.blocks.10.bottleneck_conv.bn.weight', 'backbone.blocks.10.bottleneck_conv.bn.bias', 'backbone.blocks.10.bottleneck_conv.bn._mean', 'backbone.blocks.10.bottleneck_conv.bn._variance', 'backbone.blocks.10.mid_se.conv1.weight', 'backbone.blocks.10.mid_se.conv1.bias', 'backbone.blocks.10.mid_se.conv2.weight', 'backbone.blocks.10.mid_se.conv2.bias', 'backbone.blocks.10.linear_conv.conv.weight', 'backbone.blocks.10.linear_conv.bn.weight', 'backbone.blocks.10.linear_conv.bn.bias', 'backbone.blocks.10.linear_conv.bn._mean', 'backbone.blocks.10.linear_conv.bn._variance', 'backbone.conv2.conv.weight', 'backbone.conv2.bn.weight', 'backbone.conv2.bn.bias', 'backbone.conv2.bn._mean', 'backbone.conv2.bn._variance', 'neck.encoder.lstm.weight_ih_l0', 'neck.encoder.lstm.weight_hh_l0', 'neck.encoder.lstm.bias_ih_l0', 'neck.encoder.lstm.bias_hh_l0', 'neck.encoder.lstm.weight_ih_l0_reverse', 'neck.encoder.lstm.weight_hh_l0_reverse', 'neck.encoder.lstm.bias_ih_l0_reverse', 'neck.encoder.lstm.bias_hh_l0_reverse', 'neck.encoder.lstm.weight_ih_l1', 'neck.encoder.lstm.weight_hh_l1', 'neck.encoder.lstm.bias_ih_l1', 'neck.encoder.lstm.bias_hh_l1', 'neck.encoder.lstm.weight_ih_l1_reverse', 'neck.encoder.lstm.weight_hh_l1_reverse', 'neck.encoder.lstm.bias_ih_l1_reverse', 
'neck.encoder.lstm.bias_hh_l1_reverse', 'neck.encoder.lstm.0.cell_fw.weight_ih', 'neck.encoder.lstm.0.cell_fw.weight_hh', 'neck.encoder.lstm.0.cell_fw.bias_ih', 'neck.encoder.lstm.0.cell_fw.bias_hh', 'neck.encoder.lstm.0.cell_bw.weight_ih', 'neck.encoder.lstm.0.cell_bw.weight_hh', 'neck.encoder.lstm.0.cell_bw.bias_ih', 'neck.encoder.lstm.0.cell_bw.bias_hh', 'neck.encoder.lstm.1.cell_fw.weight_ih', 'neck.encoder.lstm.1.cell_fw.weight_hh', 'neck.encoder.lstm.1.cell_fw.bias_ih', 'neck.encoder.lstm.1.cell_fw.bias_hh', 'neck.encoder.lstm.1.cell_bw.weight_ih', 'neck.encoder.lstm.1.cell_bw.weight_hh', 'neck.encoder.lstm.1.cell_bw.bias_ih', 'neck.encoder.lstm.1.cell_bw.bias_hh', 'head.fc.weight', 'head.fc.bias']) !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params backbone.conv2.conv.weight [480, 80, 1, 1] not matched with loaded params shape [288, 48, 1, 1] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params backbone.conv2.bn.weight [480] not matched with loaded params shape [288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params backbone.conv2.bn.bias [480] not matched with loaded params shape [288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params backbone.conv2.bn._mean [480] not matched with loaded params shape [288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params backbone.conv2.bn._variance [480] not matched with loaded params shape [288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_ih_l0 [384, 480] not matched with loaded params shape [192, 288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_hh_l0 [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_ih_l0 [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_hh_l0 [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_ih_l0_reverse [384, 480] not matched with loaded params shape [192, 288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_hh_l0_reverse [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_ih_l0_reverse [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_hh_l0_reverse [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_ih_l1 [384, 192] not matched with loaded params shape [192, 96] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_hh_l1 [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_ih_l1 [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_hh_l1 [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_ih_l1_reverse [384, 192] not matched with loaded params shape [192, 96] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.weight_hh_l1_reverse [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_ih_l1_reverse [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.bias_hh_l1_reverse [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_fw.weight_ih [384, 480] not matched with loaded params shape [192, 288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_fw.weight_hh [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_fw.bias_ih [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_fw.bias_hh [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_bw.weight_ih [384, 480] not matched with loaded params shape [192, 288] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_bw.weight_hh [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_bw.bias_ih [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.0.cell_bw.bias_hh [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_fw.weight_ih [384, 192] not matched with loaded params shape [192, 96] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_fw.weight_hh [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_fw.bias_ih [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_fw.bias_hh [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_bw.weight_ih [384, 192] not matched with loaded params shape [192, 96] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_bw.weight_hh [384, 96] not matched with loaded params shape [192, 48] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_bw.bias_ih [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params neck.encoder.lstm.1.cell_bw.bias_hh [384] not matched with loaded params shape [192] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params head.fc.weight [192, 112] not matched with loaded params shape [96, 111] !
[2022/06/02 16:43:42] ppocr WARNING: The shape of model params head.fc.bias [112] not matched with loaded params shape [111] !
[2022/06/02 16:43:42] ppocr INFO: resume from ./../models/best_accuracy
[2022/06/02 16:43:42] ppocr INFO: train dataloader has 13 iters
[2022/06/02 16:43:42] ppocr INFO: valid dataloader has 4 iters
[2022/06/02 16:43:42] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\Users\MSI\Desktop\Projects\OCR\paddleocr\PaddleOCR\tools\program.py", line 278, in train
    optimizer.step()
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\optimizer\adam.py", line 450, in step
    optimize_ops = self._apply_optimize(
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\optimizer\optimizer.py", line 963, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\optimizer\optimizer.py", line 749, in _create_optimization_pass
    self._create_accumulators(target_block, [
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\optimizer\adam.py", line 317, in _create_accumulators
    self._add_moments_pows(p)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\optimizer\adam.py", line 282, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\optimizer\optimizer.py", line 620, in _add_accumulator
    assert var_name in self._accumulators_holder, \
AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict
```

I am trying to fine tune the spanish paddleocr model from (https://github.com/PaddlePaddle/PaddleOCR/issues/1048) with my own dataset. Im having the previous error while training and I dont know how to fixe it.

Do you know how to solve it?

I adapted my configuration file to my workspace as follows:

```
Global:
  use_gpu: True
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/finetuning_model/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints:
  save_inference_dir: ./output/finetuning_inference/
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ppocr/utils/dict/xi_dict.txt
  max_text_length: 50
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/finetuning_res/

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: E:\\xxxxxxxxxxxxxxxxxxx\\train\\images\\
    label_file_list: ["./../dataset/gt_dni_paddleocr_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8
    use_shared_memory: False
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: E:\\xxxxxxxxxxxxxxxxxxx\\test\\images\\
    label_file_list: ["./../dataset/gt_dni_paddleocr_test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 0
    use_shared_memory: False
```

**Comment by littletomatodonkey** [comment]
hi, you should assign `prerained_model` rather than `checkpoints` to finetune your model.

`checkpoints` is just used for resume-training

**Comment by emigomez** [comment]
Hi @littletomatodonkey !
Thanks for your reply, it was that
