### ISSUE TITLE
paddleocr运行报错

### ISSUE THREAD

**Issue by zhang291** [PaddlePaddle/PaddleOCR#6483]
conda环境安装可正常运行，系统环境安装运行报错

- 系统环境/System Environment：Win10
- Paddle：  2.3.0.post110
- PaddleOCR： 2.5.0.3
- python：3.7.6
- 完整报错/Complete Error Message：
- D:\Anaconda\lib\site-packages\scipy\fft\__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
D:\Anaconda\lib\site-packages\scipy\special\orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
D:\Anaconda\lib\site-packages\scipy\sparse\sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from UI import *
  File "F:\业务知识检索\UI.py", line 7, in <module>
    import save_text
  File "F:\业务知识检索\save_text.py", line 1, in <module>
    from get_text import getImgdata, getDocXdata, getExceldata, getPdfdata, getPPTXdata
  File "F:\业务知识检索\get_text.py", line 4, in <module>
    from paddleocr import PaddleOCR
  File "D:\Anaconda\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\Anaconda\lib\site-packages\paddleocr\paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "D:\Anaconda\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 32, in <module>
    import tools.infer.predict_rec as predict_rec
  File "D:\Anaconda\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 31, in <module>
    from ppocr.postprocess import build_post_process
  File "D:\Anaconda\lib\site-packages\paddleocr\ppocr\postprocess\__init__.py", line 32, in <module>
    from .pg_postprocess import PGPostProcess
  File "D:\Anaconda\lib\site-packages\paddleocr\ppocr\postprocess\pg_postprocess.py", line 25, in <module>
    from ppocr.utils.e2e_utils.pgnet_pp_utils import PGNet_PostProcess
  File "D:\Anaconda\lib\site-packages\paddleocr\ppocr\utils\e2e_utils\pgnet_pp_utils.py", line 25, in <module>
    from extract_textpoint_slow import *
  File "D:\Anaconda\lib\site-packages\paddleocr\ppocr\utils\e2e_utils\extract_textpoint_slow.py", line 24, in <module>
    from skimage.morphology._skeletonize import thin
  File "D:\Anaconda\lib\site-packages\skimage\morphology\__init__.py", line 7, in <module>
    from ..measure._label import label
  File "D:\Anaconda\lib\site-packages\skimage\measure\__init__.py", line 8, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "D:\Anaconda\lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "D:\Anaconda\lib\site-packages\scipy\signal\__init__.py", line 301, in <module>
    from .filter_design import *
  File "D:\Anaconda\lib\site-packages\scipy\signal\filter_design.py", line 18, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "D:\Anaconda\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from ._minimize import *
  File "D:\Anaconda\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "D:\Anaconda\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "D:\Anaconda\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "D:\Anaconda\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .eigen import *
  File "D:\Anaconda\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "D:\Anaconda\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "D:\Anaconda\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: 找不到指定的程序。

**Comment by littletomatodonkey** [comment]
你好，看着是上面提到的这些库的问题，可以依次排查下
