### ISSUE TITLE
Raising CUBLAS error when starting recognition

### ISSUE THREAD

**Issue by ShakhzodbekYuldoshov** [PaddlePaddle/PaddleOCR#6511]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle：  PaddleOCR：
-  问题相关组件/Related components：paddlepaddle-gpu==2.2.0.post112
   GPU: 3080 ti
   cuda: 10.1, 10.2, 11.3
   cudnn: 7.6.5
   python: 3.7, 3.8
   anaconda environment
- 运行指令/Command Code：
```python
from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang='korean', use_gpu=True)
img_path = 'path/img.jpg'
result = ocr.ocr(img_path, cls=True)
txts = [ ]
for line in result:
    txts.append(line)
print('TXTS:  ', txts)
```
- 完整报错/Complete Error Message：
```
video 1/1 (304/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 횡단보도, Done. (0.010s)
video 1/1 (305/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 횡단보도, Done. (0.010s)
video 1/1 (306/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 횡단보도, Done. (0.011s)
video 1/1 (307/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 횡단보도, Done. (0.010s)
video 1/1 (308/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.010s)
video 1/1 (309/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.010s)
video 1/1 (310/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007732391357421875
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (311/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007990837097167969
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 9.5367431640625e-07
TXTS:   []
video 1/1 (312/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007704257965087891
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 4.76837158203125e-07
TXTS:   []
video 1/1 (313/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.014s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007760763168334961
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (314/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
video 1/1 (315/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007666826248168945
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007294416427612305
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 4.76837158203125e-07
TXTS:   []
video 1/1 (316/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 2 최고속도제한s, Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007689237594604492
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (317/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007741451263427734
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (318/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007657766342163086
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 4.76837158203125e-07
TXTS:   []
video 1/1 (319/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:43] root DEBUG: dt_boxes num : 0, elapse : 0.007787466049194336
[2022/06/07 16:14:43] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:43] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (320/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007840633392333984
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (321/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007935047149658203
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (322/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.0077648162841796875
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (323/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007597923278808594
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (324/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007653951644897461
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 9.5367431640625e-07
TXTS:   []
video 1/1 (325/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007856130599975586
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 9.5367431640625e-07
TXTS:   []
video 1/1 (326/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007812738418579102
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (327/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007868766784667969
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 1.1920928955078125e-06
TXTS:   []
video 1/1 (328/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007767677307128906
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 9.5367431640625e-07
TXTS:   []
video 1/1 (329/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
video 1/1 (330/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007685422897338867
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (331/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007666826248168945
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (332/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.014s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007655620574951172
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (333/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007927894592285156
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 4.76837158203125e-07
TXTS:   []
video 1/1 (334/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:44] root DEBUG: dt_boxes num : 0, elapse : 0.007752418518066406
[2022/06/07 16:14:44] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:44] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (335/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
video 1/1 (336/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.014s)
video 1/1 (337/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 Done. (0.010s)
[2022/06/07 16:14:45] root DEBUG: dt_boxes num : 0, elapse : 0.00775599479675293
[2022/06/07 16:14:45] root DEBUG: cls num  : 0, elapse : 0
[2022/06/07 16:14:45] root DEBUG: rec_res num  : 0, elapse : 7.152557373046875e-07
TXTS:   []
video 1/1 (338/166929) /home/octobot/projects/traffic_sign/videos/2.mp4: 384x640 1 최고속도제한, Done. (0.010s)
[2022/06/07 16:14:45] root DEBUG: dt_boxes num : 1, elapse : 0.008326530456542969
[2022/06/07 16:14:45] root DEBUG: cls num  : 1, elapse : 0.009241342544555664
Traceback (most recent call last):
  File "detect.py", line 242, in <module>
    main(opt)
  File "detect.py", line 237, in main
    run(**vars(opt))
  File "/home/octobot/anaconda3/envs/paddleocr/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 154, in run
    sign_text = ocr.ocr(crop_img, cls=True)
  File "/home/octobot/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 379, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/home/octobot/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 88, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/octobot/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py", line 360, in __call__
    self.predictor.run()
OSError: (External) CUBLAS error(13). 
  [Hint: 'CUBLAS_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  To correct: check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed. ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:35)
  [operator < fc > error]
```

**Comment by WenmuZhou** [comment]
方便提供能稳定复现的图像吗

**Comment by ShakhzodbekYuldoshov** [comment]
This youtube video is being used for inference: https://www.youtube.com/watch?v=4ZdWeTFZRks
Task: Detection and recognition of traffic signs
We are using yolov5 for detection and PaddleOCR for reading speed, height, and width limits written inside of the sign.

中国人:
此 youtube 视频用于推理：https://www.youtube.com/watch?v=4ZdWeTFZRks
任务：交通标志的检测与识别
我们使用 yolov5 进行检测，使用 PaddleOCR 读取标志内的速度、高度和宽度限制。

**Comment by WenmuZhou** [comment]
运行过程中看一下有没有显存OOM的问题
