### ISSUE TITLE
🔥🔥🔥中文繁体识别训练报错

### ISSUE THREAD

**Issue by yfq512** [PaddlePaddle/PaddleOCR#6530]
参照教程 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/recognition.md 去训练模型，报错：
```
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 166, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/cmdata/docker/yfq/PaddleOCR/tools/program.py", line 243, in train
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/py37/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 632, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 4 workers exit unexpectedly, pids: 27425, 27426, 27427, 27428
    for idx, batch in enumerate(train_dataloader):

  File "/opt/conda/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 742, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

```
我的gpu显存24G，他只用1G就不够了么？这个环境我训练其他的项目（如openai 的 mmdectection）是没问题的，这种怎么解决呢？

**Comment by yfq512** [comment]
解决了，数据集结构严格要求按照教程的来，需要改对应的 configs/rec/PP-OCRv3/***.yml 文件，label_file_list 改为 ./train_data/rec/rec_gt_train.txt， data_dir: 修改为 ./
