### ISSUE TITLE
弯曲文本识别SAST和rec放一起用会出现问题

### ISSUE THREAD

**Issue by PHI6kai** [PaddlePaddle/PaddleOCR#6606]
(pd) F:\WorkProjects\testTrain\PaddleOCR-release-2.5>python tools/infer/predict_system.py --det_algorithm="SAST" --image_dir="./train_data/Itron_RU/" --det_model_dir="./inference/det_sast_tt" --det_sast_polygon=True --rec_model_dir="./inference/rec_rare/" --rec_image_shape="3, 48, 100" --rec_char_dict_path="./ppocr/utils/en_dict.txt"
[2022/06/16 11:25:25] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2022/06/16 11:25:32] ppocr DEBUG: dt_boxes num : 24, elapse : 7.580059051513672
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 220, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 158, in main
    dt_boxes, rec_res = text_sys(img)
  File "tools/infer/predict_system.py", line 81, in __call__
    img_crop = get_rotate_crop_image(ori_im, tmp_box)
  File "F:\WorkProjects\testTrain\PaddleOCR-release-2.5\tools\infer\utility.py", line 617, in get_rotate_crop_image
    assert len(points) == 4, "shape of points must be 4*2"
AssertionError: shape of points must be 4*2

**Comment by PHI6kai** [comment]
想问一下这个咋解决

**Comment by LDOUBLEV** [comment]
目前识别不支持弯曲文本

**Comment by ZimaBlue307** [comment]
> python tools/infer/predict_system.py --det_algorithm="SAST" --image_dir="./train_data/Itron_RU/" --det_model_dir="./inference/det_sast_tt" --det_sast_polygon=True --rec_model_dir="./inference/rec_rare/" --rec_image_shape="3, 48, 100" --rec_char_dict_path="./ppocr/utils/en_dict.txt"

也就是说，目前的paddleocr，使用了SAST对一张图片做了detection之后，没有任何办法可以进一步进行recognition么？求教

**Comment by ZimaBlue307** [comment]
也就是说，目前的paddleocr，如果使用SAST进行了detection之后，没有任何办法进行进一步recognition是么？

**Comment by LDOUBLEV** [comment]
是的

**Comment by chujian521** [comment]
> 也就是说，目前的paddleocr，如果使用SAST进行了detection之后，没有任何办法进行进一步recognition是么？

TPS展开detection结果然后再rec

**Comment by chujian521** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/4608这个issue里面说的仿射变换或许也可以吧
