### ISSUE TITLE
使用PPOCRLabel标注的kie数据集无法直接用来训练

### ISSUE THREAD

**Issue by wangpf09** [PaddlePaddle/PaddleOCR#6627]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

使用PPOCRLabel标注的kie数据集无法直接用来训练，请问数据格式是需要手动转以下吗？

- 完整报错/Complete Error Message：

[2022/06/17 17:27:43] ppocr ERROR: When parsing line *****.jpg	[{"transcription": "***", "points": [[168, 675], [210, 679], [203, 1234], [159, 1233]], "difficult": false, "key_cls": "number"}, {"transcription": "***", "points": [[375, 529], [413, 532], [406, 946], [362, 945]], "difficult": false, "key_cls": "address"}, {"transcription": "**年*月*日", "points": [[454, 542], [488, 545], [485, 863], [442, 862]], "difficult": false, "key_cls": "birthday"}, {"transcription": "***", "points": [[594, 548], [632, 548], [632, 691], [594, 691]], "difficult": false, "key_cls": "name"}, {"transcription": "***", "points": [[323, 527], [363, 528], [355, 792], [316, 791]], "difficult": false, "key_cls": "address"}, {"transcription": "*", "points": [[514, 737], [554, 737], [554, 776], [514, 776]], "difficult": false, "key_cls": "nation"}, {"transcription": "*", "points": [[518, 543], [560, 543], [560, 588], [518, 588]], "difficult": false, "key_cls": "sex"}]
, error happened with msg: Traceback (most recent call last):
  File "E:\project-space\ocr-tools\PaddleOCR\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "E:\project-space\ocr-tools\PaddleOCR\ppocr\data\imaug\__init__.py", line 50, in transform
    data = op(data)
  File "E:\project-space\ocr-tools\PaddleOCR\ppocr\data\imaug\label_ops.py", line 456, in __call__
    return self.list_to_numpy(ann_infos)
  File "E:\project-space\ocr-tools\PaddleOCR\ppocr\data\imaug\label_ops.py", line 335, in list_to_numpy
    labels = np.array(labels, np.int32)
ValueError: invalid literal for int() with base 10: 'number'

**Comment by LDOUBLEV** [comment]
你的key_cls 需要生成一个映射列表："key_cls": "sex"}

比如：
![image](https://user-images.githubusercontent.com/26592129/175467194-1d5b6ee5-06b3-405a-b663-4345cb4921a6.png)

前面的数字和后面的类别是对应关系

**Comment by py703703** [comment]
我也遇到同样的问题，生成的标记连id都没有，不知道如何解决
