### ISSUE TITLE
PPOCR 服务化部署更换识别模型报错

### ISSUE THREAD

**Issue by yfq512** [PaddlePaddle/PaddleOCR#6642]
- 系统环境/System Environment：ubuntu
- 版本号/Version：Paddle：paddlepaddle-gpu==2.3.0, PaddleOCR：paddleocr==2.3.0.2, 问题相关组件/Related components：PPOCR 服务化部署(https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/pdserving/README_CN.md)
- 运行指令/Command Code：python web_service.py(不报错) 和 python pipeline_http_client.py(会打印报错信息，但服务程序不退出)
- 完整报错/Complete Error Message：
#### 客户端返回：
```
**********06203.jpg**********
erro_no:10000, err_msg:Log_id: 0  Raise_msg: list index out of range  ClassName: Op._run_postprocess.<locals>.postprocess_help  FunctionName: postprocess_help
For details about error message, see PipelineServingLogs/pipeline.log
**********06201.png**********
erro_no:10000, err_msg:Log_id: 0  Raise_msg: list index out of range  ClassName: Op._run_postprocess.<locals>.postprocess_help  FunctionName: postprocess_help
For details about error message, see PipelineServingLogs/pipeline.log
```
#### 服务端
```
python web_service.py 
[DAG] Succ init
[PipelineServicer] succ init
2022/06/20 08:44:08 start proxy service
W0620 08:44:12.699844 53348 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_build_pass]
W0620 08:44:12.738945 53325 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_graph_build_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_bn_fuse_pass]
W0620 08:44:12.804028 53361 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
W0620 08:44:12.804087 53335 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
W0620 08:44:12.804427 53373 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
I0620 08:44:12.818477 53348 fuse_pass_base.cc:57] ---  detected 33 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_bn_fuse_pass]
W0620 08:44:12.829947 53317 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_build_pass]--- Running analysis [ir_graph_build_pass]

--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running analysis [ir_graph_build_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I0620 08:44:12.855777 53325 fuse_pass_base.cc:57] ---  detected 33 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0620 08:44:12.889423 53348 fuse_pass_base.cc:57] ---  detected 34 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
I0620 08:44:12.896971 53361 fuse_pass_base.cc:57] ---  detected 19 subgraphs
I0620 08:44:12.897512 53373 fuse_pass_base.cc:57] ---  detected 19 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0620 08:44:12.898355 53348 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
I0620 08:44:12.907676 53361 fuse_pass_base.cc:57] ---  detected 9 subgraphs
--- Running analysis [ir_graph_clean_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
I0620 08:44:12.908190 53373 fuse_pass_base.cc:57] ---  detected 9 subgraphs
--- Running analysis [ir_analysis_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
I0620 08:44:12.908708 53361 fuse_pass_base.cc:57] ---  detected 4 subgraphs
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
I0620 08:44:12.909276 53373 fuse_pass_base.cc:57] ---  detected 4 subgraphs
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running analysis [inference_op_replace_pass]
I0620 08:44:12.912616 53361 fuse_pass_base.cc:57] ---  detected 9 subgraphs
--- Running analysis [memory_optimize_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
I0620 08:44:12.913236 53373 fuse_pass_base.cc:57] ---  detected 9 subgraphs
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
I0620 08:44:12.914342 53361 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I0620 08:44:12.914986 53373 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
I0620 08:44:12.918624 53348 memory_optimize_pass.cc:216] Cluster name : x  size: 12
I0620 08:44:12.918639 53348 memory_optimize_pass.cc:216] Cluster name : elementwise_add_1  size: 64
I0620 08:44:12.918644 53348 memory_optimize_pass.cc:216] Cluster name : tmp_7  size: 384
I0620 08:44:12.918650 53348 memory_optimize_pass.cc:216] Cluster name : tmp_1  size: 384
I0620 08:44:12.918655 53348 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 96
I0620 08:44:12.918658 53348 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_3  size: 1920
I0620 08:44:12.918663 53348 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_1  size: 1920
I0620 08:44:12.918666 53348 memory_optimize_pass.cc:216] Cluster name : elementwise_add_7  size: 224
I0620 08:44:12.918671 53348 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_0  size: 1920
I0620 08:44:12.918677 53348 memory_optimize_pass.cc:216] Cluster name : batch_norm_46.tmp_3  size: 1920
I0620 08:44:12.918942 53335 fuse_pass_base.cc:57] ---  detected 33 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running analysis [ir_graph_to_program_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0620 08:44:12.926528 53361 fuse_pass_base.cc:57] ---  detected 21 subgraphs
I0620 08:44:12.926563 53325 fuse_pass_base.cc:57] ---  detected 34 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
I0620 08:44:12.927245 53373 fuse_pass_base.cc:57] ---  detected 21 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0620 08:44:12.933977 53361 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running analysis [ir_params_sync_among_devices_pass]
I0620 08:44:12.934747 53373 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0620 08:44:12.935338 53325 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I0620 08:44:12.958242 53317 fuse_pass_base.cc:57] ---  detected 33 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running analysis [inference_op_replace_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running analysis [memory_optimize_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0620 08:44:12.983819 53361 memory_optimize_pass.cc:216] Cluster name : transpose_1.tmp_0_slice_2  size: 480
I0620 08:44:12.983834 53361 memory_optimize_pass.cc:216] Cluster name : tmp_0  size: 480
I0620 08:44:12.983839 53361 memory_optimize_pass.cc:216] Cluster name : batch_norm_25.tmp_0  size: 2048
I0620 08:44:12.983845 53361 memory_optimize_pass.cc:216] Cluster name : x  size: 576
I0620 08:44:12.983850 53361 memory_optimize_pass.cc:216] Cluster name : batch_norm_4.tmp_4  size: 6144
I0620 08:44:12.983857 53361 memory_optimize_pass.cc:216] Cluster name : depthwise_conv2d_2.tmp_0  size: 6144
I0620 08:44:12.983862 53361 memory_optimize_pass.cc:216] Cluster name : transpose_1.tmp_0_slice_1  size: 480
I0620 08:44:12.983867 53361 memory_optimize_pass.cc:216] Cluster name : linear_21.tmp_1  size: 50980
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running analysis [ir_graph_to_program_pass]
I0620 08:44:12.986368 53373 memory_optimize_pass.cc:216] Cluster name : transpose_1.tmp_0_slice_2  size: 480
I0620 08:44:12.986383 53373 memory_optimize_pass.cc:216] Cluster name : tmp_0  size: 480
I0620 08:44:12.986388 53373 memory_optimize_pass.cc:216] Cluster name : batch_norm_25.tmp_0  size: 2048
I0620 08:44:12.986395 53373 memory_optimize_pass.cc:216] Cluster name : x  size: 576
I0620 08:44:12.986400 53373 memory_optimize_pass.cc:216] Cluster name : batch_norm_4.tmp_4  size: 6144
I0620 08:44:12.986403 53373 memory_optimize_pass.cc:216] Cluster name : depthwise_conv2d_2.tmp_0  size: 6144
I0620 08:44:12.986408 53373 memory_optimize_pass.cc:216] Cluster name : transpose_1.tmp_0_slice_1  size: 480
I0620 08:44:12.986413 53373 memory_optimize_pass.cc:216] Cluster name : linear_21.tmp_1  size: 50980
I0620 08:44:12.987550 53325 memory_optimize_pass.cc:216] Cluster name : x  size: 12
I0620 08:44:12.987565 53325 memory_optimize_pass.cc:216] Cluster name : elementwise_add_1  size: 64
I0620 08:44:12.987571 53325 memory_optimize_pass.cc:216] Cluster name : tmp_7  size: 384
I0620 08:44:12.987576 53325 memory_optimize_pass.cc:216] Cluster name : tmp_1  size: 384
I0620 08:44:12.987581 53325 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 96
I0620 08:44:12.987586 53325 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_3  size: 1920
I0620 08:44:12.987591 53325 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_1  size: 1920
I0620 08:44:12.987596 53325 memory_optimize_pass.cc:216] Cluster name : elementwise_add_7  size: 224
I0620 08:44:12.987601 53325 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_0  size: 1920
I0620 08:44:12.987607 53325 memory_optimize_pass.cc:216] Cluster name : batch_norm_46.tmp_3  size: 1920
--- Running analysis [ir_graph_to_program_pass]
--- Running analysis [ir_graph_to_program_pass]
I0620 08:44:12.990826 53335 fuse_pass_base.cc:57] ---  detected 34 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0620 08:44:13.000020 53335 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
I0620 08:44:13.009590 53348 analysis_predictor.cc:1007] ======= optimize end =======
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0620 08:44:13.015779 53348 naive_executor.cc:102] ---  skip [feed], feed -> x
I0620 08:44:13.019474 53348 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
I0620 08:44:13.021596 53335 memory_optimize_pass.cc:216] Cluster name : x  size: 12
I0620 08:44:13.021615 53335 memory_optimize_pass.cc:216] Cluster name : elementwise_add_1  size: 64
I0620 08:44:13.021621 53335 memory_optimize_pass.cc:216] Cluster name : tmp_7  size: 384
I0620 08:44:13.021627 53335 memory_optimize_pass.cc:216] Cluster name : tmp_1  size: 384
I0620 08:44:13.021638 53335 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 96
I0620 08:44:13.021643 53335 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_3  size: 1920
I0620 08:44:13.021647 53335 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_1  size: 1920
I0620 08:44:13.021654 53335 memory_optimize_pass.cc:216] Cluster name : elementwise_add_7  size: 224
I0620 08:44:13.021661 53335 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_0  size: 1920
I0620 08:44:13.021667 53335 memory_optimize_pass.cc:216] Cluster name : batch_norm_46.tmp_3  size: 1920
[OP Object] init success
--- Running analysis [ir_graph_to_program_pass]
I0620 08:44:13.029614 53317 fuse_pass_base.cc:57] ---  detected 34 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0620 08:44:13.039022 53317 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0620 08:44:13.059217 53361 analysis_predictor.cc:1007] ======= optimize end =======
I0620 08:44:13.061542 53317 memory_optimize_pass.cc:216] Cluster name : x  size: 12
I0620 08:44:13.061563 53317 memory_optimize_pass.cc:216] Cluster name : elementwise_add_1  size: 64
I0620 08:44:13.061568 53317 memory_optimize_pass.cc:216] Cluster name : tmp_7  size: 384
I0620 08:44:13.061574 53317 memory_optimize_pass.cc:216] Cluster name : tmp_1  size: 384
I0620 08:44:13.061579 53317 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 96
I0620 08:44:13.061585 53317 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_3  size: 1920
I0620 08:44:13.061590 53317 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_1  size: 1920
I0620 08:44:13.061594 53317 memory_optimize_pass.cc:216] Cluster name : elementwise_add_7  size: 224
I0620 08:44:13.061599 53317 memory_optimize_pass.cc:216] Cluster name : batch_norm_41.tmp_0  size: 1920
I0620 08:44:13.061602 53317 memory_optimize_pass.cc:216] Cluster name : batch_norm_46.tmp_3  size: 1920
I0620 08:44:13.063879 53373 analysis_predictor.cc:1007] ======= optimize end =======
I0620 08:44:13.064393 53361 naive_executor.cc:102] ---  skip [feed], feed -> x
--- Running analysis [ir_graph_to_program_pass]
I0620 08:44:13.067242 53361 naive_executor.cc:102] ---  skip [softmax_2.tmp_0], fetch -> fetch
I0620 08:44:13.069537 53373 naive_executor.cc:102] ---  skip [feed], feed -> x
I0620 08:44:13.072443 53373 naive_executor.cc:102] ---  skip [softmax_2.tmp_0], fetch -> fetch
[OP Object] init success
I0620 08:44:13.086016 53325 analysis_predictor.cc:1007] ======= optimize end =======
[OP Object] init success
I0620 08:44:13.092128 53325 naive_executor.cc:102] ---  skip [feed], feed -> x
I0620 08:44:13.095834 53325 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
[OP Object] init success
I0620 08:44:13.118063 53335 analysis_predictor.cc:1007] ======= optimize end =======
I0620 08:44:13.123272 53335 naive_executor.cc:102] ---  skip [feed], feed -> x
I0620 08:44:13.126937 53335 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
[OP Object] init success
I0620 08:44:13.155829 53317 analysis_predictor.cc:1007] ======= optimize end =======
I0620 08:44:13.161463 53317 naive_executor.cc:102] ---  skip [feed], feed -> x
I0620 08:44:13.164954 53317 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
[OP Object] init success
web_service.py:50: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0620 08:46:12.014737 53325 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0620 08:46:12.018563 53325 gpu_context.cc:306] device: 0, cuDNN Version: 7.5.
W0620 08:46:12.275887 53325 gpu_context.cc:506] WARNING: device: . The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
PROFILE pid:53325       prep#[det|1]_0:1655714771919464 prep#[det|1]_1:1655714772010776 midp#[det|1]_0:1655714772010824 midp#[det|1]_1:1655714773871439 postp#[det|1]_0:1655714773871951 postp#[det|1]_1:1655714773913767 
W0620 08:46:13.953223 53361 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0620 08:46:13.956557 53361 gpu_context.cc:306] device: 0, cuDNN Version: 7.5.
W0620 08:46:14.201880 53361 gpu_context.cc:506] WARNING: device: . The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

PROFILE pid:53145       prepack_0#@DAGExecutor_0:1655714771912404 prepack_0#@DAGExecutor_1:1655714771913098 postpack_0#@DAGExecutor_0:1655714775858816 postpack_0#@DAGExecutor_1:1655714775858940 call_0#DAG-0_0:1655714771912302 call_0#DAG-0_1:1655714775858964 
web_service.py:50: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)

PROFILE pid:53145       prepack_1#@DAGExecutor_0:1655714775875545 prepack_1#@DAGExecutor_1:1655714775875855 postpack_1#@DAGExecutor_0:1655714775888524 postpack_1#@DAGExecutor_1:1655714775888594 call_1#DAG-1_0:1655714775875511 call_1#DAG-1_1:1655714775888614 
web_service.py:50: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0620 08:46:16.037941 53335 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0620 08:46:16.041527 53335 gpu_context.cc:306] device: 0, cuDNN Version: 7.5.
W0620 08:46:16.286514 53335 gpu_context.cc:506] WARNING: device: . The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
PROFILE pid:53335       prep#[det|2]_0:1655714775916946 prep#[det|2]_1:1655714776034514 midp#[det|2]_0:1655714776034551 midp#[det|2]_1:1655714777848544 postp#[det|2]_0:1655714777849000 postp#[det|2]_1:1655714777865813 
W0620 08:46:17.899431 53373 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0620 08:46:17.902961 53373 gpu_context.cc:306] device: 0, cuDNN Version: 7.5.
W0620 08:46:18.151192 53373 gpu_context.cc:506] WARNING: device: . The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

PROFILE pid:53145       prepack_2#@DAGExecutor_0:1655714775911969 prepack_2#@DAGExecutor_1:1655714775912331 postpack_2#@DAGExecutor_0:1655714779735766 postpack_2#@DAGExecutor_1:1655714779735862 call_2#DAG-2_0:1655714775911929 call_2#DAG-2_1:1655714779735884
```
#### PipelineServingLogs/pipeline.log 报错信息：
```
Classname: Op._run_postprocess.<locals>.postprocess_help
FunctionName: postprocess_help
ERROR 2022-06-20 08:07:14,987 [dag.py:420] (data_id=7 log_id=0) Failed to predict: Log_id: 0  Raise_msg: list index out of range  ClassName: Op._run_postprocess.<locals>.postprocess_help  FunctionName: postprocess_help
INFO 2022-06-20 08:07:15,021 [pipeline_server.py:64] (log_id=0) inference request name:ocr self.name:ocr time:1655712435.0217533
INFO 2022-06-20 08:07:15,022 [operator.py:1791] RequestOp unpack one request. log_id:0, clientip:             name:ocr, method:prediction, time:1655712435.0221748
INFO 2022-06-20 08:07:15,022 [dag.py:379] (data_id=8 log_id=0) Succ Generate ID
INFO 2022-06-20 08:07:15,134 [operator.py:1454] prometheus inf count +1
INFO 2022-06-20 08:07:15,228 [operator.py:1454] prometheus inf count +1
ERROR 2022-06-20 08:07:15,236 [error_catch.py:125]
Log_id: 0
Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 1156, in postprocess_help
    midped_data, data_id, logid_dict.get(data_id))
  File "web_service.py", line 145, in postprocess
    one_batch, with_score=True)
  File "/cmdata/docker/yfq/PaddleOCR/deploy/pdserving/ocr_reader.py", line 405, in postprocess
    preds_idx, preds_prob, is_remove_duplicate=True)
  File "/cmdata/docker/yfq/PaddleOCR/deploy/pdserving/ocr_reader.py", line 204, in decode
    idx])])
IndexError: list index out of range

```

**Comment by littletomatodonkey** [comment]
你好，看着是更换后的模型的字符数据与默认中文不一致导致的，可以再检查下字典

**Comment by littletomatodonkey** [comment]
tools/infer/utilility.py ，参数里有个char_dict_path，可以看下，需要修改下

**Comment by yfq512** [comment]
> tools/infer/utilility.py ，参数里有个char_dict_path，可以看下，需要修改下

解决了，修改 deploy/pdserving/web_service.py 中的char_dict_path就可以了，感谢！

**Comment by yfq512** [comment]
解决了

**Comment by 784117672** [comment]
> > tools/infer/utilility.py ，参数里有个char_dict_path，可以看下，需要修改下
> 
> 解决了，修改 deploy/pdserving/web_service.py 中的char_dict_path就可以了，感谢！

请问你是怎么修改的。我遇到了同样的错误，我使用java调用python的restful接口，返回错误信息：{err_no=10000, err_msg=Log_id: 0  Raise_msg: image  ClassName: Op._run_preprocess.<locals>.preprocess_help  FunctionName: preprocess_help, key=[], value=[], tensors=[]}

**Comment by 784117672** [comment]
> 
已解决，java调用时的请求参数要按照python中pipeline_http_client.py中的boty体格式请求
