### ISSUE TITLE
识别模型训练报错RuntimeError: (PreconditionNotMet) warp-ctc [version 2] Error in get_workspace_size: execution failed

### ISSUE THREAD

**Issue by angel-yi** [PaddlePaddle/PaddleOCR#6687]
[2022/06/23 23:11:24] ppocr INFO: load pretrain successful from D:\python_project\ocr_project\bxy_ocr_v2\pretrain_models\ch_PP-OCRv3_rec_train\best_accuracy
[2022/06/23 23:11:24] ppocr INFO: train dataloader has 43263 iters
[2022/06/23 23:11:24] ppocr INFO: valid dataloader has 2278 iters
[2022/06/23 23:11:24] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 10000 iterations
Traceback (most recent call last):
  File "tools/train.py", line 193, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 168, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "D:\python_project\ocr_project\train_ocr\tools\program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python_project\ocr_project\train_ocr\ppocr\losses\combined_loss.py", line 55, in forward
    loss = loss_func(input, batch, **kargs)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python_project\ocr_project\train_ocr\ppocr\losses\distillation_loss.py", line 154, in forward
    loss = super().forward(out['ctc'], batch[:2] + batch[3:])
  File "D:\python_project\ocr_project\train_ocr\ppocr\losses\rec_ctc_loss.py", line 38, in forward
    loss = self.loss_func(predicts, labels, preds_lengths, label_lengths)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\nn\layer\loss.py", line 1130, in forward
    norm_by_times=norm_by_times)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\nn\functional\loss.py", line 1126, in ctc_loss
    input_lengths, label_lengths)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\loss.py", line 613, in warpctc
    norm_by_times, )
RuntimeError: (PreconditionNotMet) warp-ctc [version 2] Error in get_workspace_size: execution failed
  [Hint: Expected CTC_STATUS_SUCCESS == status, but received CTC_STATUS_SUCCESS:0 != status:3.] (at ../paddle/phi/kernels/impl/warpctc_kernel_impl.h:199)
  [operator < warpctc > error]

**Comment by angel-yi** [comment]
paddlepaddle-gpu2.3降级为2.2.2解决了
