### ISSUE TITLE
Not able to train PGNet with new characters

### ISSUE THREAD

**Issue by SaiKrishnaBala** [PaddlePaddle/PaddleOCR#6739]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
My objective it is train an end2end model(PGNet) with character set(numbers, alphabets(small/large) and some special character like (/, \, ', (, ), etc)). Accordingly i've added new characters in my dictionary file and updated the Loss.pad_num 
 in the configuration file. But I get the following error:

- 系统环境/System Environment：Linux/18.04.1-Ubuntu/
- 版本号/Version：Paddle：v2.3  PaddleOCR：v2.5 问题相关组件/Related components：
- 运行指令/Command Code：!python3 -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/e2e/e2e_r50_vd_pg_app1.yml -o Global.pretrained_model=./pretrain_models/train_step1/best_accuracy Global.load_static_weights=False
- 完整报错/Complete Error Message：0623 15:33:17.894275 5988 gpu_context.cc:306] device: 0, cuDNN Version: 8.2.
[2022/06/23 15:33:20] ppocr INFO: Initialize indexs of datasets:['./../data/input/labelled_data/train/train.txt']
[2022/06/23 15:33:20] ppocr INFO: Initialize indexs of datasets:['./../data/input/labelled_data/val/val.txt']
[2022/06/23 15:33:34] ppocr INFO: load pretrain successful from ./pretrain_models/train_step1/best_accuracy
[2022/06/23 15:33:34] ppocr INFO: train dataloader has 3 iters
[2022/06/23 15:33:34] ppocr INFO: valid dataloader has 20 iters
[2022/06/23 15:33:34] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 10 iterations
Traceback (most recent call last):
File "tools/train.py", line 191, in
main(config, device, logger, vdl_writer)
File "tools/train.py", line 164, in main
program.train(config, train_dataloader, valid_dataloader, device, model,
File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lr-compute-instance-gpu/code/Users/sai.krishna.bala/PaddleOCR/tools/program.py", line 268, in train
loss = loss_class(preds, batch)
File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in call
return self._dygraph_call_func(*inputs, *kwargs)
File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
outputs = self.forward(inputs,  kwargs)
File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lr-compute-instance-gpu/code/Users/sai.krishna.bala/PaddleOCR/ppocr/losses/e2e_pg_loss.py", line 130, in forward
ctc_loss = self.ctcloss(f_char, pos_list, pos_mask, label_list, label_t)
File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lr-compute-instance-gpu/code/Users/sai.krishna.bala/PaddleOCR/ppocr/losses/e2e_pg_loss.py", line 105, in ctcloss
cost = paddle.nn.functional.ctc_loss(
File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1125, in ctc_loss
loss_out = fluid.layers.warpctc(log_probs, labels, blank, norm_by_times,
File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 605, in warpctc
grad, loss_out = _C_ops.warpctc(
ValueError: (InvalidArgument) The value of Attr(blank) should be in interval [0, 39), but received
[Hint: Expected blank < sequence_width, but received blank:39 >= sequence_width:37.] (at /paddle/paddle/phi/infermeta/multiary.cc:1868)
[operator < warpctc > error]
INFO 2022-06-23 15:33:44,161 launch_utils.py:343] terminate all the procs
INFO 2022-06-23 15:33:44,161 launch_utils.py:343] terminate all the procs
ERROR 2022-06-23 15:33:44,161 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
ERROR 2022-06-23 15:33:44,161 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-06-23 15:33:48,165 launch_utils.py:343] terminate all the procs
INFO 2022-06-23 15:33:48,165 launch_utils.py:343] terminate all the procs
INFO 2022-06-23 15:33:48,166 launch.py:402] Local processes completed.
INFO 2022-06-23 15:33:48,166 launch.py:402] Local processes completed.

**Comment by SaiKrishnaBala** [comment]
@LDOUBLEV Can you please look into this and throw some light?
