### ISSUE TITLE
OCR自定义数据集训练报错

### ISSUE THREAD

**Issue by hcwwch2021** [PaddlePaddle/PaddleOCR#6783]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10-cpu
- 版本号/Version：Paddle：2.3.0  PaddleOCR：PaddleOCR-release-2.5 问题相关组件/Related components：
- 运行指令/Command Code： python tools/train.py -c configs/rec/PP-OCRv3/en_num_cht_PP-OCRv3_rec.yml -o Global.pretrained_model=./pretrain_models/ch_PP-OCRv3_rec_train/best_accuracy
[test.zip](https://github.com/PaddlePaddle/PaddleOCR/files/9036681/test.zip)

- 完整报错/Complete Error Message：
[2022/07/04 12:01:28] ppocr ERROR: When parsing line 11_crop_0.jpg      E20220620 09:57:57C
, error happened with msg: Traceback (most recent call last):
  File "E:\Anaconda3\envs\OCR\PaddleOCR-release-2.5\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "E:\Anaconda3\envs\OCR\PaddleOCR-release-2.5\ppocr\data\imaug\__init__.py", line 50, in transform
    data = op(data)
  File "E:\Anaconda3\envs\OCR\PaddleOCR-release-2.5\ppocr\data\imaug\operators.py", line 165, in __call__
    data_list.append(data[key])
KeyError: 'label_ctc'

**Comment by hcwwch2021** [comment]
如果在配置文件中把- KeepKeys:参数删掉，训练程序不报错，但无论迭代多少次，acc始终为0。训练集有70张图片
