### ISSUE TITLE
在直接运行表单demo时to excel出错

### ISSUE THREAD

**Issue by onenerve** [PaddlePaddle/PaddleOCR#6790]
Traceback (most recent call last):
  File "D:/CVcode/Table/PaddleOCR-release-2.5/table_infer.py", line 33, in <module>
    to_excel(pred_html, os.path.join(args.output, '1.xlsx'))
  File "D:\CVcode\Table\PaddleOCR-release-2.5\ppstructure\table\predict_table.py", line 188, in to_excel
    tablepyxl.document_to_xl(html_table, excel_path)
  File "D:\CVcode\Table\PaddleOCR-release-2.5\ppstructure\table\tablepyxl\tablepyxl.py", line 101, in document_to_xl
    wb = document_to_workbook(doc, base_url=base_url)
  File "D:\CVcode\Table\PaddleOCR-release-2.5\ppstructure\table\tablepyxl\tablepyxl.py", line 87, in document_to_workbook
    inline_styles_doc = Premailer(doc, base_url=base_url, remove_classes=False).transform()
  File "D:\Anaconda\working\envs\paddle_env\lib\site-packages\premailer\premailer.py", line 319, in transform
    stripped = html.strip()
AttributeError: 'dict' object has no attribute 'strip'

**Comment by andyjpaddle** [comment]
提供一下运行命令哈~
