### ISSUE TITLE
program.py

### ISSUE THREAD

**Issue by 15926273249** [PaddlePaddle/PaddleOCR#68]
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    FLAGS = parser.parse_args()
  File "/paddle/paddle/program.py", line 49, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/paddle/paddle/program.py", line 58, in _parse_opt
    k, v = s.split('=')
ValueError: need more than 1 value to unpack

**Comment by LDOUBLEV** [comment]
可否提供下报这个错的命令

**Comment by 15926273249** [comment]
python train.py -c configs/det/det_mv3_db.yml -o Global.use_gpu = True
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    FLAGS = parser.parse_args()
  File "/paddle/paddle/program.py", line 49, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/paddle/paddle/program.py", line 58, in _parse_opt
    k, v = s.split('=')
ValueError: need more than 1 value to unpack

**Comment by 15926273249** [comment]
请问您遇到过同样的问题吗

**Comment by tink2123** [comment]
尝试去掉“=”两端空格的空格？

`python train.py -c configs/det/det_mv3_db.yml -o Global.use_gpu=True`

**Comment by 15926273249** [comment]
去掉之后报这个错：
2020-05-19 07:13:02,494-INFO: {'Loss': {'function': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'ohem_ratio': 3, 'beta': 10, 'main_loss_type': 'DiceLoss', 'alpha': 5, 'balance_loss': True}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'inner_channels': 256, 'k': 50, 'model_name': 'large', 'out_channels': 2}, 'Global': {'train_batch_size_per_card': 8, 'reader_yml': './configs/det/det_db_icdar15_reader.yml', 'save_inference_dir': None, 'eval_batch_step': 5000, 'checkpoints': None, 'save_model_dir': './output/det_db/', 'test_batch_size_per_card': 16, 'pretrain_weights': './pretrain_models/ResNet50_vd_pretrained/', 'algorithm': 'DB', 'log_smooth_window': 20, 'use_gpu': True, 'image_shape': [3, 640, 640], 'print_batch_step': 2, 'save_res_path': './output/det_db/predicts_db.txt', 'save_epoch_step': 200, 'epoch_num': 1200}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta2': 0.999, 'beta1': 0.9}, 'EvalReader': {'label_file_path': './train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'test_image_shape': [736, 1280], 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': './train_data/icdar2015/text_localization/'}, 'Backbone': {'function': 'ppocr.modeling.backbones.det_resnet_vd,ResNet', 'layers': 50}, 'TestReader': {'label_file_path': './train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'do_eval': True, 'single_img_path': None, 'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestReader', 'test_image_shape': [736, 1280], 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_dir': './train_data/icdar2015/text_localization/'}, 'Architecture': {'function': 'ppocr.modeling.architectures.det_model,DetModel'}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProcess', 'max_candidates': 1000, 'box_thresh': 0.7, 'unclip_ratio': 1.5, 'thresh': 0.3}, 'TrainReader': {'label_file_path': './train_data/icdar2015/text_localization/train_icdar2015_label.txt', 'num_workers': 8, 'reader_function': 'ppocr.data.det.dataset_traversal,TrainReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'img_set_dir': './train_data/icdar2015/text_localization/'}}
E0519 07:13:02.495303     1 pybind.cc:1261] Cannot use GPU because there is no GPU detected on your machine.

**Comment by tink2123** [comment]
请确认您的机器是否支持GPU，如果支持的话请提供一下机器的环境，包括：GPU型号，cudnn和cuda版本

**Comment by 15926273249** [comment]
有gpu  cuda10.2d

**Comment by 15926273249** [comment]
TITAN Xp

**Comment by tink2123** [comment]
参考[安装说明](https://www.paddlepaddle.org.cn/install/quick):
请查看paddlepaddle-gpu 是否安装正确
```
使用 python3 进入python解释器，输入import paddle.fluid ，再输入 paddle.fluid.install_check.run_check()

如果出现 Your Paddle Fluid is installed successfully!，说明您已成功安装。
```

**Comment by 15926273249** [comment]
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
2020-05-19 08:29:04,353-WARNING: Your Paddle Fluid has some problem with multiple GPU. This may be caused by:
 1. There is only 1 or 0 GPU visible on your Device;
 2. No.1 or No.2 GPU or both of them are occupied now
 3. Wrong installation of NVIDIA-NCCL2, please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html

 Original Error is: No places for execution.
Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CPU! 
 Let's start deep Learning with Paddle Fluid now

**Comment by LDOUBLEV** [comment]
如果确保了你的cuda没问题，卸载paddle重新装一下吧，安装命令使用
```
pip install paddlepaddle-gpu==1.7.2.post107 -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by 15926273249** [comment]
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.7.2.post107 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==1.7.2.post107

**Comment by 15926273249** [comment]
装的是这个：python -m pip install paddlepaddle-gpu==1.8.0.post107 -i https://mirror.baidu.com/pypi/simple
但是还是不行

**Comment by tink2123** [comment]
请问你是在docker里装的吗？

**Comment by 15926273249** [comment]
是的

**Comment by tink2123** [comment]
可能是nccl没有正确安装和安装的版本不对，请参考Paddle安装文档 https://www.paddlepaddle.org.cn/install/quick 和NCCL安装文档 https://developer.nvidia.com/nccl 正确安装NCCL。
另外，建议安装paddle 1.7.x 版本，PaddleOCR暂时不支持paddle1.8版本

**Comment by LDOUBLEV** [comment]
> 装的是这个：python -m pip install paddlepaddle-gpu==1.8.0.post107 -i https://mirror.baidu.com/pypi/simple
> 但是还是不行

建议用paddle1.7 ，目前PaddleOCR还不支持Paddle1.8 ，

顺便问下，你用的是我们的提供的docker吗

**Comment by 15926273249** [comment]
https://hub.docker.com/r/paddlepaddle/paddle/tags/ 是访问这个 然后docker pull paddlepaddle/paddle:latest

**Comment by LDOUBLEV** [comment]
换install.md里提到的docker试一下：
```

如果您的机器安装的是CUDA9，请运行以下命令创建容器
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev /bin/bash

如果您的机器安装的是CUDA10，请运行以下命令创建容器
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev /bin/bash

```
这个docker比latest好用

**Comment by 15926273249** [comment]
可是不是root用户，不能使用sudo命令

**Comment by LDOUBLEV** [comment]
非root用户需要sudo吧，root用户不需要加sudo了

**Comment by 15926273249** [comment]
用不了这条命令，只能是写dockerfile

**Comment by LDOUBLEV** [comment]
那你直接 docker pull hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7-dev 可以拉下来吗

**Comment by 15926273249** [comment]
这个可以，这个拉下来可以直接用吗

**Comment by LDOUBLEV** [comment]
当然可以啊，这个也是在https://hub.docker.com/r/paddlepaddle/paddle/tags/  里的

**Comment by 15926273249** [comment]
是不用再写dockerfile,加requirments.txt了吧

**Comment by LDOUBLEV** [comment]
不用了

**Comment by 15926273249** [comment]
安装了上述镜像之后还是，
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:1078: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
2020-05-20 06:17:26,132-WARNING: Your Paddle Fluid has some problem with multiple GPU. This may be caused by:
 1. There is only 1 or 0 GPU visible on your Device;
 2. No.1 or No.2 GPU or both of them are occupied now
 3. Wrong installation of NVIDIA-NCCL2, please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html

 Original Error is: No places for execution.
Your Paddle Fluid is installed successfully ONLY for SINGLE GPU or CPU! 
 Let's start deep Learning with Paddle Fluid now
