### ISSUE TITLE
The setting of Parameter-Server must has server_num or servers

### ISSUE THREAD

**Issue by Alice-Thirty** [PaddlePaddle/PaddleOCR#6843]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：https://hub.docker.com/r/paddlepaddle/paddle
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components： 2.5
- 运行指令/Command Code：python3 -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/rec/PP-OCRv3/123.yml
- 完整报错/Complete Error Message：
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-----------  Configuration Arguments -----------
gpus: 0,1,2,3
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/rec/PP-OCRv3/123.yml']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-07-10 06:47:23,502 launch.py:311] Not found distinct arguments and not compiled with cuda. Default use ps mode
Traceback (most recent call last):
  File "/usr/local/python3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/distributed/fleet/launch.py", line 330, in launch
    launch_ps(args, distribute_mode)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/distributed/fleet/launch.py", line 263, in launch_ps
    ps_launcher = ParameterServerLauncher(args, distribute_mode)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/distributed/fleet/launch_utils.py", line 716, in __init__
    self.get_role_endpoints(args)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/distributed/fleet/launch_utils.py", line 733, in get_role_endpoints
    assert args.servers != "", "The setting of Parameter-Server must has server_num or servers."
AssertionError: The setting of Parameter-Server must has server_num or servers.

```  

123.yml  
```
Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/bigo
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ./train_data/en_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: false
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3_en.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list:
    - ./train_data/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 2
    num_workers: 4
```

**Comment by Alice-Thirty** [comment]
pip3 install -r requirements.txt  
The error:  
```
  Could not find a version that satisfies the requirement opencv-contrib-python==4.4.0.46 (from -r requirements.txt (line 10)) (from versions: 3.2.0.7, 3.3.0.10, 3.4.1.15, 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.0.0.21, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32, 4.2.0.34)
No matching distribution found for opencv-contrib-python==4.4.0.46 (from -r requirements.txt (line 10))

```

**Comment by LDOUBLEV** [comment]
Please install paddlepaddle-gpu instead of paddlepaddle  if using distributed function.

pip install paddlepaddle-gpu 


opencv-contrib-python==4.2.* is ok too

**Comment by Alice-Thirty** [comment]
Thanks.
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

```
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.3.1-gpu-cuda11.2-cudnn8
```
