### ISSUE TITLE
ImportError: cannot import name 'logger' from 'utils' 

### ISSUE THREAD

**Issue by Crown-Messi** [PaddlePaddle/PaddleOCR#6872]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos 7
- 版本号/Version：Paddle：2.3.0  PaddleOCR：2.5 Paddleclas:  2.2.1 问题相关组件/Related components：在paddleclas 与 paddleocr冲突
- 运行指令/Command Code：
     在 终端环境下进入python，执行import paddleocr 与 import paddleclas 时报错
- 完整报错/Complete Error Message：
- `>>> import paddleclas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wushuaihong/opt/miniconda3/envs/PaddleOCR_env/lib/python3.8/site-packages/paddleclas/__init__.py", line 16, in <module>
    from .paddleclas import PaddleClas
  File "/Users/wushuaihong/opt/miniconda3/envs/PaddleOCR_env/lib/python3.8/site-packages/paddleclas/paddleclas.py", line 36, in <module>
    from deploy.python.predict_cls import ClsPredictor
  File "/Users/wushuaihong/opt/miniconda3/envs/PaddleOCR_env/lib/python3.8/site-packages/paddleclas/deploy/python/predict_cls.py", line 23, in <module>
    from utils import logger
ImportError: cannot import name 'logger' from 'utils' (/Users/wushuaihong/opt/miniconda3/envs/PaddleOCR_env/lib/python3.8/site-packages/paddleocr/ppocr/postprocess/../utils/__init__.py)`

**Comment by WenmuZhou** [comment]
先import paddleclas 再import paddleocr

**Comment by Crown-Messi** [comment]
为什么会出现这种问题呢

**Comment by WenmuZhou** [comment]
这个问题主要是由于很两个包里都有logger 但是paddleclas里没有进行相对导入，所以会报错

**Comment by WenmuZhou** [comment]
最新的paddleclas包已经修复了这个问题
