### ISSUE TITLE
win10 已经成功配置paddle环境，运行快速体验时报错AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'get_input_names'

### ISSUE THREAD

**Issue by Yanchao-L** [PaddlePaddle/PaddleOCR#6911]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10  显卡是4x NVIDIA GeForce RTX 3090 
- Paddlepaddle-gpu:2.3.0
- 运行指令/Command Code：cd applications.FootballAction.predict&&python predict
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "D:/PaddleVideo-develop/applications/FootballAction/predict/predict.py", line 18, in <module>
    model_predict.load_model()
  File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\action.py", line 45, in timer
    retval = func(*args)
  File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\action.py", line 81, in load_model
    self.image_model = image_model.InferModel(self.configs)
  File "D:\PaddleVideo-develop\applications\FootballAction\predict\action_detect\models\pptsm_infer.py", line 36, in __init__
    input_names = self.predictor.get_input_names()
AttributeError: 'paddle.fluid.core_avx.AnalysisConfig' object has no attribute 'get_input_names'
![image](https://user-images.githubusercontent.com/109326094/179235183-c4a65269-f8fc-4ed2-99ed-ad54f40f4b54.png)

**Comment by MissPenguin** [comment]
看着是使用PaddleVideo的报错，可以去PaddleVideo官网提个issue哈：https://github.com/PaddlePaddle/PaddleVideo/issues
