### ISSUE TITLE
pip直装PaddlePaddle存在问题：Can not import avx core while this file exists

### ISSUE THREAD

**Issue by haaddii** [PaddlePaddle/PaddleOCR#6925]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：**System:** Ubuntu 5.15.0-40-generic Python3.8  **CPU:** AMD R9 4900HS  **GPU:** 2060  CUDA: 11.6
- 版本号/Version：Paddle：Develop 0.0.0.post116  PaddleOCR：ch_pp-ocrv3==1.0.0 问题相关组件/Related components：ch_pp-ocrv3==1.0.0
- 运行指令/Command Code 
```bash
python -m pip install paddlepaddle-gpu==0.0.0.post116 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html && pip install paddlehub -i https://mirror.baidu.com/pypi/simple && hub install ch_pp-ocrv3==1.0.0
```
- 完整报错/Complete Error Message：
```bash
Error: Can not import avx core while this file exists: /home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/home/users/miniforge3/envs/paddle/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 299, in <module>
    raise e
  File "/home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 257, in <module>
    from . import core_avx
ImportError: /home/users/miniforge3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

> 目前自己找到的解决方法都是Windows环境的，Linux下依葫芦画瓢转移libs里的so.x文件并没有用。不知道是不是和AMD CPU有关
> Update, 更换为11.2的CUDA和使用conda安装稳定版（gpu2.3.1），会出现相同情况，GCC是自带的版本gcc-9.4

**Comment by WenmuZhou** [comment]
可能是gcc版本太高了，试一下gcc-8.2看看

**Comment by angel-yi** [comment]
请问解决了吗？

**Comment by nissansz** [comment]
解决了吗？
