### ISSUE TITLE
docker环境，报错ImportError: cannot import name 'blake2s'

### ISSUE THREAD

**Issue by RONG-SONG** [PaddlePaddle/PaddleOCR#693]
详细：
1、按照docker安装教程（https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/installation.md）CPU环境安装完毕
2、下载通用中文inference模型
3、在/home/projects/PaddleOCR目录下，执行：
`python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_r50_vd_db/"  --rec_model_dir="./inference/ch_rec_r34_vd_crnn/"`
4、报错：
```
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 20, in <module>
    import tools.infer.utility as utility
  File "/home/projects/PaddleOCR/tools/infer/utility.py", line 17, in <module>
    from ppocr.utils.utility import initial_logger
  File "/home/projects/PaddleOCR/ppocr/utils/utility.py", line 19, in <module>
    from paddle import fluid
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/__init__.py", line 30, in <module>
    import paddle.dataset
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import paddle.dataset.mq2007
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
    import rarfile
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/rarfile.py", line 64, in <module>
    from hashlib import blake2s, sha1, sha256
ImportError: cannot import name 'blake2s'
```
请问有没有遇到类似的错误？

**Comment by MissPenguin** [comment]
试试这个，应该能解决：
pip3 uninstall rarfile
pip3 install rarfile==3.0

**Comment by RONG-SONG** [comment]
可以了，谢谢
