### ISSUE TITLE
KeyError: 'image'

### ISSUE THREAD

**Issue by caojunyongnb** [PaddlePaddle/PaddleOCR#6931]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
您好
训练的时候使用python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml 可以正常运行，但是如果加上--eval会出现KeyError: 'image'报错，请问这个会是什么造成的。
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 506, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 529, in _eval_with_loader
    outs = self.model(data)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 128, in get_pred
    return self._forward()
  File "/home/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 79, in _forward
    body_feats = self.backbone(self.inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 577, in forward
    x = inputs['image']
KeyError: 'image'

**Comment by WenmuZhou** [comment]
这个辛苦再PaddleDetection那边提问看看
