### ISSUE TITLE
Do the centers in center loss need to update while training the model

### ISSUE THREAD

**Issue by TLedTS** [PaddlePaddle/PaddleOCR#6947]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Hi, when I checked the code of center loss, didn't see any obviously update about centers inside. So is it fixed? Or it will update while training by itself? 
Thanks a bunch in advance.

**Comment by littletomatodonkey** [comment]
no, you just need to save the center once and use it.

**Comment by TLedTS** [comment]
@littletomatodonkey Thanks !

**Comment by nissansz** [comment]
v3模型能用center loss吗？
我用上面的设置，放到resnet34中的loss部分，没有训练进度，读完数据半天后报以下错误？

Traceback (most recent call last):
File "./tools/train.py", line 191, in
main(config, device, logger, vdl_writer)
File "./tools/train.py", line 164, in main
program.train(config, train_dataloader, valid_dataloader, device, model,
File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train
loss = loss_class(preds, batch)
File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in call
return self._dygraph_call_func(*inputs, **kwargs)
File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward
loss = loss_func(input, batch, **kargs)
File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in call
assert isinstance(predicts, (list, tuple))
AssertionError
