### ISSUE TITLE
使用python脚本运行报错，直接使用PaddleOCR指令就没问题

### ISSUE THREAD

**Issue by RollingWang** [PaddlePaddle/PaddleOCR#6952]
Traceback (most recent call last):
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/subprocess.py", line 64, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/paddle/fluid/framework.py", line 29, in <module>
    import numpy as np
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/numpy/core/__init__.py", line 100, in <module>
    from . import _add_newdocs_scalars
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/numpy/core/_add_newdocs_scalars.py", line 87, in <module>
    add_newdoc_for_scalar_type('byte', [],
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/numpy/core/_add_newdocs_scalars.py", line 62, in add_newdoc_for_scalar_type
    alias_doc += ''.join(":Alias on this platform ({} {}): `numpy.{}`: {}.\n    ".format(platform.system(), platform.machine(), alias, doc)
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/site-packages/numpy/core/_add_newdocs_scalars.py", line 62, in <genexpr>
    alias_doc += ''.join(":Alias on this platform ({} {}): `numpy.{}`: {}.\n    ".format(platform.system(), platform.machine(), alias, doc)
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/platform.py", line 897, in system
    return uname().system
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/platform.py", line 863, in uname
    processor = _syscmd_uname('-p', '')
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/platform.py", line 617, in _syscmd_uname
    import subprocess
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/subprocess.py", line 71, in <module>
    import selectors
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/selectors.py", line 290, in <module>
    class SelectSelector(_BaseSelectorImpl):
  File "/workdir/wangzhiling02/anaconda3/envs/yolo/lib/python3.8/selectors.py", line 317, in SelectSelector
    _select = select.select
AttributeError: module 'select' has no attribute 'select'

**Comment by LDOUBLEV** [comment]
看报错信息-> ModuleNotFoundError: No module named 'msvcrt'
