### ISSUE TITLE
 all input arrays must have the same shape 

### ISSUE THREAD

**Issue by xiaobai-python** [PaddlePaddle/PaddleOCR#6985]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 20.04
- 版本号/Version：Paddle： 2.3 PaddleOCR：2.5 问题相关组件/Related components：
- 运行指令/Command Code：python tools/eval.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_student.yml -o Global.checkpoints=/workspace/PaddleOCR/output/ch_PP-OCR_V3_det/latest.pdparams Eval.dataset.data_dir=/workspace/PaddleOCR/ccpd_data Eval.dataset.label_file_list=[/workspace/PaddleOCR/PPOCR_data/test/det.txt] Eval.loader.num_workers=0

- 完整报错/Complete Error Message：
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by WenmuZhou** [comment]
batch改为1看看
