### ISSUE TITLE
使用tools/infer_vqa_token_ser_re.py做表单识别时报算子错误

### ISSUE THREAD

**Issue by wangxin0718** [PaddlePaddle/PaddleOCR#7045]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： ubuntu
- 版本号/Version：Paddle： 2.3.0   PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- python3 tools/infer_vqa_token_ser_re.py \
    -c configs/vqa/re/layoutxlm.yml \
    -o Architecture.Backbone.checkpoints=pretrain/re_LayoutXLM_xfun_zh/ \
    Global.infer_img=test_imgs/ \
    -c_ser configs/vqa/ser/layoutxlm.yml \
    -o_ser Architecture.Backbone.checkpoints=pretrain/ser_LayoutXLM_xfun_zh/
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "tools/infer_vqa_token_ser_re.py", line 192, in <module>
    result = ser_re_engine(img_path)
  File "tools/infer_vqa_token_ser_re.py", line 138, in __call__
    preds = self.model(re_input)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 79, in forward
    x = self.backbone(x)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 129, in forward
    labels=None)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 994, in forward
    head_mask=head_mask,
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 853, in forward
    ) // self.config["image_feature_pool_shape"][1])
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (NotFound) There are no kernels which are registered in the elementwise_floordiv operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:327)
  [operator < elementwise_floordiv > error]

**Comment by WenmuZhou** [comment]
升级paddlenlp看看
