### ISSUE TITLE
docker版重启容器后，启动失败，并且运行几天后容器也会自动停止运行

### ISSUE THREAD

**Issue by yuqiangabab** [PaddlePaddle/PaddleOCR#712]
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 199, in install_module
    self.all_modules(update=False)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 84, in check_module_valid
    return True, {'version': version, 'name': _item._name}
UnboundLocalError: local variable 'version' referenced before assignment

**Comment by heyuncoder** [comment]
```sh
~cpu git:(develop) docker logs paddle_ocr_cpu
Successfully installed ocr_system
ocr_system == 1.0.0
 * Serving Flask app "paddlehub.serving.app_single" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-10-09 16:35:30,064-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
/bin/bash: line 1:    33 Killed                  hub serving start -m ocr_system
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 199, in install_module
    self.all_modules(update=False)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/manager.py", line 84, in check_module_valid
    return True, {'version': version, 'name': _item._name}
UnboundLocalError: local variable 'version' referenced before assignment
```
遇到了同样的问题

**Comment by libsgh** [comment]
我也遇到了...

**Comment by w-Bro** [comment]
同遇到此问题，只要重启就会失败

**Comment by littletomatodonkey** [comment]
可以试着重新安装下paddlehub以及hub服务

**Comment by libsgh** [comment]
> 可以试着重新安装下paddlehub以及hub服务

每次都重装是不是太麻烦了，这也不是解决问题的办法吧
