### ISSUE TITLE
请问执行训练时出现一次样是什么意思呢?

### ISSUE THREAD

**Issue by miwang881210** [PaddlePaddle/PaddleOCR#7122]
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.rnn_decoder.0.cell.bias_ih not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.rnn_decoder.0.cell.bias_hh not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.rnn_decoder.1.cell.weight_ih not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.rnn_decoder.1.cell.weight_hh not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.rnn_decoder.1.cell.bias_ih not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.rnn_decoder.1.cell.bias_hh not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.embedding.weight not in model
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.prediction.weight not in model       
[2022/08/06 01:18:05] ppocr WARNING: The pretrained params Student.head.sar_head.decoder.prediction.bias not in model
[2022/08/06 01:18:05] ppocr INFO: load pretrain successful from ./pretrain_models\ch_PP-OCRv3_rec_train\best_accuracy
[2022/08/06 01:18:05] ppocr INFO: train dataloader has 2 iters
[2022/08/06 01:18:05] ppocr INFO: valid dataloader has 2 iters
[2022/08/06 01:18:05] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 50 iterations
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 163, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "D:\Documents\Uibot\PaddleOCR-release-2.5\tools\program.py", line 285, in train
    post_result = post_process_class(preds, batch[1])
  File "D:\Documents\Uibot\PaddleOCR-release-2.5\ppocr\postprocess\db_postprocess.py", line 219, in __call__
    results[k] = self.post_process(predicts[k], shape_list=shape_list)
  File "D:\Documents\Uibot\PaddleOCR-release-2.5\ppocr\postprocess\db_postprocess.py", line 181, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
ValueError: too many values to unpack (expected 4)

**Comment by LDOUBLEV** [comment]
更新代码重新试下
