### ISSUE TITLE
CUBLAS_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by 980202006** [PaddlePaddle/PaddleOCR#7138]
The problem doesn't exist when I run paddleocr alone, but if I load the torch model, the problem occurs.
```
Traceback (most recent call last):
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/xingyum/models/videos/ky_watermark_removal/serve0/inference.py", line 106, in <module>
    inf_api.inference('/home/xingyum/models/content_detection/watermark_2/tiktok/tiktok/5b6cae0a659038dbbf0603c94add4896.mp4')
  File "/home/xingyum/models/videos/ky_watermark_removal/serve0/inference.py", line 48, in inference
    mask_path = get_mask_frome_video(local_path,out_path)
  File "/home/xingyum/models/videos/ky_watermark_removal/serve0/make_masks.py", line 205, in get_mask_frome_video
    masks = assert_label(image_dir, vide_shape, labels)
  File "/home/xingyum/models/videos/ky_watermark_removal/serve0/make_masks.py", line 99, in assert_label
    result = ocr.ocr(img_path_)  # 存在一定情况：没有检测出id
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/site-packages/paddleocr-2.5.0.3-py3.10.egg/paddleocr/paddleocr.py", line 480, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/site-packages/paddleocr-2.5.0.3-py3.10.egg/paddleocr/tools/infer/predict_system.py", line 84, in __call__
    img_crop_list, angle_list, elapse = self.text_classifier(
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/site-packages/paddleocr-2.5.0.3-py3.10.egg/paddleocr/tools/infer/predict_cls.py", line 111, in __call__
    self.predictor.run()
OSError: (External) CUBLAS error(15). 
  [Hint: 'CUBLAS_STATUS_NOT_SUPPORTED'.  The functionality requested is not supported ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < fc > error]
```

**Comment by loveflywing** [comment]
me too;
Did you solve this problem?

**Comment by Qiang-HU** [comment]
me too;
This error is reported when I import torch in the code of Paddle
Did you solve this problem?

**Comment by 980202006** [comment]
It's been too long. I have the impression that it is solved with an independent environment, and then use os.system to call the independent environment.
