### ISSUE TITLE
KIE model training not working

### ISSUE THREAD

**Issue by adesgautam** [PaddlePaddle/PaddleOCR#7164]
Hi,
I have prepared my custom dataset just like `wildreceipt`. I have 33 classes added.
When I start the training it throws error as below:
```Traceback (most recent call last):
  File "PaddleOCR/tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "PaddleOCR/tools/train.py", line 166, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/content/PaddleOCR/tools/program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/content/PaddleOCR/ppocr/losses/kie_sdmgr_loss.py", line 103, in forward
    loss_node = self.loss_node(node_preds, node_gts)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/loss.py", line 406, in forward
    name=self.name)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/loss.py", line 1723, in cross_entropy
    label_max.item()))
ValueError: Target 32 is out of upper bound.
```

When I checked the line `268` in `tools/program.py`, the shape of pred is coming as `26` which is the num of classes present in `wildreceipt` dataset. 
Is there something wrong with my dataset or is there a bug ?

Eagerly waiting for your response

**Comment by andyjpaddle** [comment]
Maybe you should change this param https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/ppocr/modeling/heads/kie_sdmgr_head.py#L38

**Comment by adesgautam** [comment]
Thank you it worked !
