### ISSUE TITLE
 部署异常：hub install deploy/hubserving/structure_system/ 

### ISSUE THREAD

**Issue by neozhu** [PaddlePaddle/PaddleOCR#7224]
[root@jieyida PaddleOCR]hub install deploy/hubserving/structure_table/
/usr/local/python3/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/local/python3/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 177, in install
    with lock:
  File "/usr/local/python3/lib/python3.7/site-packages/filelock/_api.py", line 199, in __enter__
    self.acquire()
  File "/usr/local/python3/lib/python3.7/site-packages/filelock/_api.py", line 155, in acquire
    self._acquire()
  File "/usr/local/python3/lib/python3.7/site-packages/filelock/_unix.py", line 29, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.paddlehub/tmp/deploy/hubserving/structure_table/'
[root@jieyida PaddleOCR]# hub install deploy/hubserving/structure_system/
/usr/local/python3/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/local/python3/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 177, in install
    with lock:
  File "/usr/local/python3/lib/python3.7/site-packages/filelock/_api.py", line 199, in __enter__
    self.acquire()
  File "/usr/local/python3/lib/python3.7/site-packages/filelock/_api.py", line 155, in acquire
    self._acquire()
  File "/usr/local/python3/lib/python3.7/site-packages/filelock/_unix.py", line 29, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.paddlehub/tmp/deploy/hubserving/structure_system/'

**Comment by neozhu** [comment]
其它几个服务都可以，就这两个服务structure_system,structure_table失败了

**Comment by WenmuZhou** [comment]
试一下2.6看看

**Comment by tingxiao88** [comment]
> > 试一下2.6看看
> 
> 2.6可以

2.6 是paddleocr么
