### ISSUE TITLE
M1芯片docker环境使用，提示机器不支持AVX

### ISSUE THREAD

**Issue by yoeaki** [PaddlePaddle/PaddleOCR#7225]
- 系统环境/System Environment：macOS M1Pro.   docker环境
- 版本号/Version：Paddle：2.3.1  PaddleOCR： 2.5.3
- 环境构建和和演示步骤描述
   1. 安装mac版本的docker环境：`docker pull registry.baidubce.com/paddlepaddle/paddle:2.3.1` 
   2. 启动后，把paddleOCR项目复制到docker容器中。
   3. 进入tools/infer，执行： `python predict_system.py  --image_dir="/paddle/PaddleOCR-release-2.5.3/source/static/picture/test/0006.jpg" --det_model_dir="/paddle/PaddleOCR-release-2.5.3/inference/ch_PP-OCRv3_det_infer/" --rec_model_dir="/paddle/PaddleOCR-release-2.5.3/inference/ch_PP-OCRv3_rec_infer/" --cls_model_dir="/paddle/PaddleOCR-release-2.5.3inference/ch_ppocr_mobile_v2.0_cls_infer/" --use_angle_cls=False --use_gpu=False --use_space_char=True`
   4. 报错！！！如下！！！
- 完整报错/Complete Error Message：
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/39695971/185051988-c2f52863-0f22-4621-899a-4fd7a5b3c0ef.png">
`grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "predict_system.py", line 31, in <module>
    import tools.infer.utility as utility
  File "/paddle/PaddleOCR-release-2.5.3/tools/infer/utility.py", line 21, in <module>
    import paddle
  File "/usr/local/lib/python3.7/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 365, in <module>
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 313, in <module>
    from . import core_noavx
ImportError: cannot import name 'core_noavx' from 'paddle.fluid' (/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py)`

**Comment by tink2123** [comment]
建议安装不带avx的paddle， 可以参考这篇文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/macos-docker.html
