### ISSUE TITLE
TensorRT execution is not working

### ISSUE THREAD

**Issue by Auth0rM0rgan** [PaddlePaddle/PaddleOCR#7230]
Hello, Im applying paddleocr on a video to detect and reconize the texts in the video. Everything is working fine if I dont turn on the TensorRT execution. However Im getting following error when I use tensorRT and have no idea how to solve it :|

```
E0817 10:47:06.451982  8461 helper.h:111] 3: [executionContext.cpp::setBindingDimensions::940] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::940, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0817 10:47:06.459640  8461 helper.h:111] 3: [executionContext.cpp::getBindingDimensions::997] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::997, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
E0817 10:47:06.469121  8461 helper.h:111] 3: [executionContext.cpp::enqueueInternal::328] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::328, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
In user code:

    File "tools/export_model.py", line 172, in <module>
      main()
    File "tools/export_model.py", line 165, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 99, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 623, in wrapper
      func(layer, path, input_spec, **configs)
    File "<decorator-gen-106>", line 2, in save
      
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 845, in save
      inner_input_spec)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 519, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 429, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 729, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 719, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-104>", line 2, in from_func_spec
      
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 664, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/temp/tmpl_91or8v.py", line 40, in forward
      false_fn_2, (data, x), (x,), (x,))
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/architectures/base_model.py", line 85, in forward
      x = self.head(x, targets=data)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/heads/rec_multi_head.py", line 60, in forward
      ctc_encoder = self.ctc_encoder(x)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/temp/tmpa7rjmzk8.py", line 37, in forward
      self, x), (__return_value_2, self, x), (__return_value_2, x))
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 189, in forward
      x = self.encoder(x)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 140, in forward
      z = self.conv1(z)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/backbones/rec_svtrnet.py", line 69, in forward
      out = self.conv(inputs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 678, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 165, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3582, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2596, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input's dimension of Operator(Conv2DFusion) is expected to be 4. But received: input's dimension = 0, shape = [].
      [Hint: Expected in_dims.size() == 4U, but received in_dims.size():0 != 4U:4.] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cc:75)
      [operator < conv2d_fusion > error]

``` 

I have already tested my tensorRT installation and it works fine for other algorithms and also with the same setting without tensorRT paddleocr is working perfectly. I also executed `paddle.utils.run_check()` and no error

```
Running verify PaddlePaddle program ... 
W0817 11:02:37.627573  9824 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0817 11:02:37.630101  9824 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
W0817 11:02:38.567567  9824 parallel_executor.cc:642] Cannot enable P2P access from 0 to 1
W0817 11:02:38.567577  9824 parallel_executor.cc:642] Cannot enable P2P access from 1 to 0
W0817 11:02:39.156227  9824 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

```
* before I had the version of paddlepaddle-gpu for cuda 11.2 and my code was working without any issue with TensorRT!

Also this is an error im getting when I run paddleocr with CL and tensorrt flag true. No problem when tensorrt is false.

`
paddleocr --image_dir /home/test_ocr/inputs/010_.jpg --use_angle_cls false --lang en --use_gpu true --use_tensorrt true --rec true
`

```
E0817 11:05:43.434645 10250 helper.h:111] 2: [convolutionBuilder.cpp::createConvolution::239] Error Code 2: Internal Error (Assertion isOpConsistent(convolution.get()) failed. Cask convolution isconsitent check failed.)
E0817 11:05:43.441792 10250 helper.h:111] 2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

```

Here is my env setting:
OS: Ubuntu 20.04
GPU: 3090 RTX
python: 3.8.13
paddle-bfloat: 0.1.7                    
paddleocr: 2.5.0.3                 
paddlepaddle-gpu: 2.3.1.post116  
nvidia-tensorrt: 8.4.1.5
cuda: 11.6
cudnn: 8.4

Thanks!

**Comment by Rm1n90** [comment]
@Auth0rM0rgan Did you find any solution for your problem with tensorRT? Im facing the same issue with tensorRT after upgrading paddlepaddle-gpu for cuda11.6 from cuda11.2, which before I didnt have any problem with TensorRT

My Env:
Os: Ubuntu 20.04
Paddleocr: 2.5.0.3
Paddlepaddle-gpu: 2.3.1.post116
Nvidia-tensorrt: 8.4.1.5
Cuda and Cudnn: 11.6 -- 8.4

**Comment by Rm1n90** [comment]
@Auth0rM0rgan, I think the issue is paddlepaddle-gpu with cuda11.6. I was able to solve the first problem by downgrade the paddlepaddle-gpu for cuda11.2 insted of the one for cuda 11.6 and it doesnt matter you have cuda11.6 on your system. Just compile the file paddlepaddle-gpu with cuda11.2 However the second issue is still exists
