### ISSUE TITLE
TypeError: setValue(self, int): argument 1 has unexpected type 'float' 目测是个新bug

### ISSUE THREAD

**Issue by Daniel-ccx** [PaddlePaddle/PaddleOCR#7236]
- 系统环境/System Environment：mac m1 conda python3.10
- 版本号/Version： PaddleOCR：2.50 /Related components：PPOCRLabel
- 运行指令/Command Code：python PPOCRLabel.py --lang ch
- 完整报错/Complete Error Message：
[2022/08/18 03:43:18] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "/projects/python/PaddleOCR-2.5.0/PPOCRLabel/PPOCRLabel.py", line 1292, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[1]    62489 abort      python PPOCRLabel.py --lang ch
/mambaforge/envs/imageProcess/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5927124/185230087-88ba58eb-e260-46bb-b9a5-17049d16e01f.png">

**Comment by Daniel-ccx** [comment]
另外一个，
/projects/python/PaddleOCR-2.5.0/PPOCRLabel/libs/canvas.py", line 609, in paintEvent
    p.drawLine(self.prevPoint.x(), 0, self.prevPoint.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'
[1]    63065 abort      python PPOCRLabel.py --lang ch

**Comment by whyazalea** [comment]
System Environment：mac m1 conda python3.10.4
Version： paddlepaddle 2.4.2   ;PaddleOCR：2.7.3 ;  PPOCRLabel 1.0.1 ;
Command Code：python PPOCRLabel.py --lang ch
**1. when  labeling，it crash：**
Complete Error Message：
(pytorch) C:\Users\why>PPOCRLabel --lang ch
D:\anaconda3\envs\pytorch\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
[2024/04/26 14:55:13] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  D:\py\labelimg\sealocr\111111.png
DirPath in importDirImages is D:/py/labelimg/sealocr
Traceback (most recent call last):
  File "D:\anaconda3\envs\pytorch\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**2.after  labeling，when  confirm ，it crash：**
[2024/04/26 15:37:21] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  D:\py\labelimg\sealocr\111111.png
DirPath in importDirImages is D:/py/labelimg/sealocr
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
file name in openNext is  D:\py\labelimg\sealocr\22222222.png
unicodeFilePath is D:\py\labelimg\sealocr\22222222.png

**Comment by whyazalea** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.

System Environment：mac m1 conda python3.10.4
Version： paddlepaddle 2.4.2 ;PaddleOCR：2.7.3 ; PPOCRLabel 1.0.1 ;
Command Code：python PPOCRLabel.py --lang ch
1. when labeling，it crash：
Complete Error Message：
(pytorch) C:\Users\why>PPOCRLabel --lang ch
D:\anaconda3\envs\pytorch\lib\site-packages\skimage\util\dtype.py:27: DeprecationWarning: np.bool8 is a deprecated alias for np.bool_. (Deprecated NumPy 1.24)
np.bool8: (False, True),
[2024/04/26 14:55:13] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is D:\py\labelimg\sealocr\111111.png
DirPath in importDirImages is D:/py/labelimg/sealocr
Traceback (most recent call last):
File "D:\anaconda3\envs\pytorch\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

2.after labeling，when confirm ，it crash：
[2024/04/26 15:37:21] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is D:\py\labelimg\sealocr\111111.png
DirPath in importDirImages is D:/py/labelimg/sealocr
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
file name in openNext is D:\py\labelimg\sealocr\22222222.png
unicodeFilePath is D:\py\labelimg\sealocr\22222222.png
