### ISSUE TITLE
how to Offline Use PPOCRLabel tool

### ISSUE THREAD

**Issue by anidiatm41** [PaddlePaddle/PaddleOCR#7241]
I am not able to invoke PPOCRLabel tool , looks some network restriction as shown below:

How can I set the entire PPOCRLabel in my system locally(offline) ?

###################ERROR ########################################
(test1) C:\Users\1619872\OneDrive - Standard Chartered Bank\Desktop\PaddleOCR-release-2.5\PPOCRLabel>python PPOCRLabel.py
download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to C:\Users\1619872/.paddleocr/whl\det\en\en_PP-OCRv3_det_infer\en_PP-OCRv3_det_infer.tar
Traceback (most recent call last):
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\1619872\AppData\Local\conda\conda\envs\test1\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020C50F376A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/english/en_PP-OCRv3_det_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020C50F376A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PPOCRLabel.py", line 2704, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2692, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2682, in get_main_app
    win = MainWindow(lang=args.lang,
  File "PPOCRLabel.py", line 97, in __init__
    self.ocr = PaddleOCR(use_pdserving=False,
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\paddleocr\paddleocr.py", line 420, in __init__
    maybe_download(params.det_model_dir, det_url)
  File "..\ppocr\utils\network.py", line 55, in maybe_download
    download_with_progressbar(url, tmp_path)
  File "..\ppocr\utils\network.py", line 26, in download_with_progressbar
    response = requests.get(url, stream=True)
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\1619872\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/english/en_PP-OCRv3_det_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020C50F376A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by Evezerest** [comment]
Hi, our model had uploaded on '[https://paddleocr.bj.bcebos.com](https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar)', if you fail to download or access the model in the [README](https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-series-model-listupdate-on-september-8th), we'll try to upload to another place.

Could you please tell me your location?  I wonder how many others face the same issue
