### ISSUE TITLE
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by si-fahad-nadeem** [PaddlePaddle/PaddleOCR#7281]
- 系统环境/System Environment：Linux
- 版本号/Version：20.02 paddlepaddle-gpu:2.0.0  PaddleOCR： 2.5.0.3 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_mv3_db.yml
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/home/imsdev3/Documents/PaddleOCR/tools/program.py", line 574, in preprocess
    device = 'gpu:{}'.format(dist.ParallelEnv()
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 200, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

**Comment by andyjpaddle** [comment]
更新一下paddle版本，推荐使用2.3.1版本

**Comment by si-fahad-nadeem** [comment]
it works but the new error is below:
(error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 121, in main
    model = build_model(config['Architecture'])
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 30, in build_model
    arch = BaseModel(config)
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 50, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 63, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 97, in __init__
    self.conv = ConvBNLayer(
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 167, in __init__
    self.conv = nn.Conv2D(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 644, in __init__
    super(Conv2D, self).__init__(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 133, in __init__
    self.weight = self.create_parameter(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 365, in __call__
    out_var = _C_ops.gaussian_random(
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:59)
  [operator < gaussian_random > error]

**Comment by andyjpaddle** [comment]
It seems like that your CUDNN or CUDA lib is not installed correctly, I suggest you use the docker to prepare you environment. https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/docker/linux-docker_en.html

**Comment by ShafieCoder** [comment]
How did you solve this error: 
File "tools/train.py", line 188, in
config, device, logger, vdl_writer = program.preprocess(is_train=True)
File "/home/imsdev3/Documents/PaddleOCR/tools/program.py", line 574, in preprocess
device = 'gpu:{}'.format(dist.ParallelEnv()
File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 200, in device_id
return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id' 
 I tried [andyjiang1116] suggestion and prepared my environment through steps that provided in https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/docker/linux-docker_en.html
but the issue persists.

**Comment by LouisVA** [comment]
@ShafieCoder 
You just need to make sure your paddlepaddle-gpu version is the right one.
In my case I was using CUDA 11.8 so https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/windows-pip_en.html#gpu got me the right command.
