### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.

### ISSUE THREAD

**Issue by si-fahad-nadeem** [PaddlePaddle/PaddleOCR#7300]
python3 tools/train.py -c configs/det/det_mv3_db.yml
[2022/08/22 13:13:45] ppocr INFO: Architecture : 
[2022/08/22 13:13:45] ppocr INFO:     Backbone : 
[2022/08/22 13:13:45] ppocr INFO:         model_name : large
[2022/08/22 13:13:45] ppocr INFO:         name : MobileNetV3
[2022/08/22 13:13:45] ppocr INFO:         scale : 0.5
[2022/08/22 13:13:45] ppocr INFO:     Head : 
[2022/08/22 13:13:45] ppocr INFO:         k : 50
[2022/08/22 13:13:45] ppocr INFO:         name : DBHead
[2022/08/22 13:13:45] ppocr INFO:     Neck : 
[2022/08/22 13:13:45] ppocr INFO:         name : DBFPN
[2022/08/22 13:13:45] ppocr INFO:         out_channels : 256
[2022/08/22 13:13:45] ppocr INFO:     Transform : None
[2022/08/22 13:13:45] ppocr INFO:     algorithm : DB
[2022/08/22 13:13:45] ppocr INFO:     model_type : det
[2022/08/22 13:13:45] ppocr INFO: Eval : 
[2022/08/22 13:13:45] ppocr INFO:     dataset : 
[2022/08/22 13:13:45] ppocr INFO:         data_dir : ./train_data/icdar2015/text_localization/
[2022/08/22 13:13:45] ppocr INFO:         label_file_list : ['./train_data/icdar2015/text_localization/test_label.txt']
[2022/08/22 13:13:45] ppocr INFO:         name : SimpleDataSet
[2022/08/22 13:13:45] ppocr INFO:         transforms : 
[2022/08/22 13:13:45] ppocr INFO:             DecodeImage : 
[2022/08/22 13:13:45] ppocr INFO:                 channel_first : False
[2022/08/22 13:13:45] ppocr INFO:                 img_mode : BGR
[2022/08/22 13:13:45] ppocr INFO:             DetLabelEncode : None
[2022/08/22 13:13:45] ppocr INFO:             DetResizeForTest : 
[2022/08/22 13:13:45] ppocr INFO:                 image_shape : [736, 1280]
[2022/08/22 13:13:45] ppocr INFO:             NormalizeImage : 
[2022/08/22 13:13:45] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2022/08/22 13:13:45] ppocr INFO:                 order : hwc
[2022/08/22 13:13:45] ppocr INFO:                 scale : 1./255.
[2022/08/22 13:13:45] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2022/08/22 13:13:45] ppocr INFO:             ToCHWImage : None
[2022/08/22 13:13:45] ppocr INFO:             KeepKeys : 
[2022/08/22 13:13:45] ppocr INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2022/08/22 13:13:45] ppocr INFO:     loader : 
[2022/08/22 13:13:45] ppocr INFO:         batch_size_per_card : 4
[2022/08/22 13:13:45] ppocr INFO:         drop_last : False
[2022/08/22 13:13:45] ppocr INFO:         num_workers : 8
[2022/08/22 13:13:45] ppocr INFO:         shuffle : False
[2022/08/22 13:13:45] ppocr INFO:         use_shared_memory : True
[2022/08/22 13:13:45] ppocr INFO: Global : 
[2022/08/22 13:13:45] ppocr INFO:     cal_metric_during_train : False
[2022/08/22 13:13:45] ppocr INFO:     checkpoints : None
[2022/08/22 13:13:45] ppocr INFO:     distributed : False
[2022/08/22 13:13:45] ppocr INFO:     epoch_num : 1200
[2022/08/22 13:13:45] ppocr INFO:     eval_batch_step : [0, 2000]
[2022/08/22 13:13:45] ppocr INFO:     infer_img : doc/imgs_en/img_10.jpg
[2022/08/22 13:13:45] ppocr INFO:     log_smooth_window : 20
[2022/08/22 13:13:45] ppocr INFO:     pretrained_model : ./pretrain_models/MobileNetV3_large_x0_5_pretrained
[2022/08/22 13:13:45] ppocr INFO:     print_batch_step : 10
[2022/08/22 13:13:45] ppocr INFO:     save_epoch_step : 1200
[2022/08/22 13:13:45] ppocr INFO:     save_inference_dir : None
[2022/08/22 13:13:45] ppocr INFO:     save_model_dir : ./output/db_mv3/
[2022/08/22 13:13:45] ppocr INFO:     save_res_path : ./output/det_db/predicts_db.txt
[2022/08/22 13:13:45] ppocr INFO:     use_gpu : True
[2022/08/22 13:13:45] ppocr INFO:     use_visualdl : False
[2022/08/22 13:13:45] ppocr INFO:     use_xpu : False
[2022/08/22 13:13:45] ppocr INFO: Loss : 
[2022/08/22 13:13:45] ppocr INFO:     alpha : 5
[2022/08/22 13:13:45] ppocr INFO:     balance_loss : True
[2022/08/22 13:13:45] ppocr INFO:     beta : 10
[2022/08/22 13:13:45] ppocr INFO:     main_loss_type : DiceLoss
[2022/08/22 13:13:45] ppocr INFO:     name : DBLoss
[2022/08/22 13:13:45] ppocr INFO:     ohem_ratio : 3
[2022/08/22 13:13:45] ppocr INFO: Metric : 
[2022/08/22 13:13:45] ppocr INFO:     main_indicator : hmean
[2022/08/22 13:13:45] ppocr INFO:     name : DetMetric
[2022/08/22 13:13:45] ppocr INFO: Optimizer : 
[2022/08/22 13:13:45] ppocr INFO:     beta1 : 0.9
[2022/08/22 13:13:45] ppocr INFO:     beta2 : 0.999
[2022/08/22 13:13:45] ppocr INFO:     lr : 
[2022/08/22 13:13:45] ppocr INFO:         learning_rate : 0.001
[2022/08/22 13:13:45] ppocr INFO:     name : Adam
[2022/08/22 13:13:45] ppocr INFO:     regularizer : 
[2022/08/22 13:13:45] ppocr INFO:         factor : 0
[2022/08/22 13:13:45] ppocr INFO:         name : L2
[2022/08/22 13:13:45] ppocr INFO: PostProcess : 
[2022/08/22 13:13:45] ppocr INFO:     box_thresh : 0.6
[2022/08/22 13:13:45] ppocr INFO:     max_candidates : 1000
[2022/08/22 13:13:45] ppocr INFO:     name : DBPostProcess
[2022/08/22 13:13:45] ppocr INFO:     thresh : 0.3
[2022/08/22 13:13:45] ppocr INFO:     unclip_ratio : 1.5
[2022/08/22 13:13:45] ppocr INFO: Train : 
[2022/08/22 13:13:45] ppocr INFO:     dataset : 
[2022/08/22 13:13:45] ppocr INFO:         data_dir : ./train_data/icdar2015/text_localization/
[2022/08/22 13:13:45] ppocr INFO:         label_file_list : ['./train_data/icdar2015/text_localization/train_label.txt']
[2022/08/22 13:13:45] ppocr INFO:         name : SimpleDataSet
[2022/08/22 13:13:45] ppocr INFO:         ratio_list : [1.0]
[2022/08/22 13:13:45] ppocr INFO:         transforms : 
[2022/08/22 13:13:45] ppocr INFO:             DecodeImage : 
[2022/08/22 13:13:45] ppocr INFO:                 channel_first : False
[2022/08/22 13:13:45] ppocr INFO:                 img_mode : BGR
[2022/08/22 13:13:45] ppocr INFO:             DetLabelEncode : None
[2022/08/22 13:13:45] ppocr INFO:             IaaAugment : 
[2022/08/22 13:13:45] ppocr INFO:                 augmenter_args : 
[2022/08/22 13:13:45] ppocr INFO:                     args : 
[2022/08/22 13:13:45] ppocr INFO:                         p : 0.5
[2022/08/22 13:13:45] ppocr INFO:                     type : Fliplr
[2022/08/22 13:13:45] ppocr INFO:                     args : 
[2022/08/22 13:13:45] ppocr INFO:                         rotate : [-10, 10]
[2022/08/22 13:13:45] ppocr INFO:                     type : Affine
[2022/08/22 13:13:45] ppocr INFO:                     args : 
[2022/08/22 13:13:45] ppocr INFO:                         size : [0.5, 3]
[2022/08/22 13:13:45] ppocr INFO:                     type : Resize
[2022/08/22 13:13:45] ppocr INFO:             EastRandomCropData : 
[2022/08/22 13:13:45] ppocr INFO:                 keep_ratio : True
[2022/08/22 13:13:45] ppocr INFO:                 max_tries : 50
[2022/08/22 13:13:45] ppocr INFO:                 size : [640, 640]
[2022/08/22 13:13:45] ppocr INFO:             MakeBorderMap : 
[2022/08/22 13:13:45] ppocr INFO:                 shrink_ratio : 0.4
[2022/08/22 13:13:45] ppocr INFO:                 thresh_max : 0.7
[2022/08/22 13:13:45] ppocr INFO:                 thresh_min : 0.3
[2022/08/22 13:13:45] ppocr INFO:             MakeShrinkMap : 
[2022/08/22 13:13:45] ppocr INFO:                 min_text_size : 8
[2022/08/22 13:13:45] ppocr INFO:                 shrink_ratio : 0.4
[2022/08/22 13:13:45] ppocr INFO:             NormalizeImage : 
[2022/08/22 13:13:45] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2022/08/22 13:13:45] ppocr INFO:                 order : hwc
[2022/08/22 13:13:45] ppocr INFO:                 scale : 1./255.
[2022/08/22 13:13:45] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2022/08/22 13:13:45] ppocr INFO:             ToCHWImage : None
[2022/08/22 13:13:45] ppocr INFO:             KeepKeys : 
[2022/08/22 13:13:45] ppocr INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2022/08/22 13:13:45] ppocr INFO:     loader : 
[2022/08/22 13:13:45] ppocr INFO:         batch_size_per_card : 16
[2022/08/22 13:13:45] ppocr INFO:         drop_last : False
[2022/08/22 13:13:45] ppocr INFO:         num_workers : 8
[2022/08/22 13:13:45] ppocr INFO:         shuffle : True
[2022/08/22 13:13:45] ppocr INFO:         use_shared_memory : True
[2022/08/22 13:13:45] ppocr INFO: profiler_options : None
[2022/08/22 13:13:45] ppocr INFO: train with paddle 2.3.1 and device Place(gpu:0)
[2022/08/22 13:13:45] ppocr INFO: Initialize indexs of datasets:['./train_data/icdar2015/text_localization/train_label.txt']
[2022/08/22 13:13:45] ppocr INFO: Initialize indexs of datasets:['./train_data/icdar2015/text_localization/test_label.txt']
W0822 13:13:45.430591  2522 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 10.2
W0822 13:13:45.432212  2522 dynamic_loader.cc:305] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 121, in main
    model = build_model(config['Architecture'])
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 30, in build_model
    arch = BaseModel(config)
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 50, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 63, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 97, in __init__
    self.conv = ConvBNLayer(
  File "/home/imsdev3/Documents/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 167, in __init__
    self.conv = nn.Conv2D(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 644, in __init__
    super(Conv2D, self).__init__(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 133, in __init__
    self.weight = self.create_parameter(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/imsdev3/.local/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 365, in __call__
    out_var = _C_ops.gaussian_random(
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:59)
  [operator < gaussian_random > error]

**Comment by tink2123** [comment]
It may be that the version installed by paddlepaddle does not match the version of cudnn in your environment. 
Please refer to the [installation documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/install/index_en.html) to select the correct paddle version.
