### ISSUE TITLE
RuntimeError: cudnnGetConvolutionForwardAlgorithm not found.

### ISSUE THREAD

**Issue by xunlongjun** [PaddlePaddle/PaddleOCR#7339]
Does anyone know how to fix this error?

- System Environment：Windows 11
- Version：paddlepaddle-gpu：2.3.2  PaddleOCR：2.6
- Command Code：paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true --use_gpu true
- Complete Error Message：
[2022/08/24 22:14:48] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, shape_info_filename=None, precision='fp32', gpu_mem=500, image_dir='./imgs/11.jpg', det_algorithm='DB', det_model_dir='C:\\Users\\billo/.paddleocr/whl\\det\\ch\\ch_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_box_type='quad', det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, det_fce_box_type='poly', rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\billo/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv3_rec_infer', rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='C:\\Program Files\\Python310\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='C:\\Users\\billo/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, save_pdf=False, lang='ch', det=True, rec=True, type='ocr', ocr_version='PP-OCRv3', structure_version='PP-Structurev2')
[2022/08/24 22:14:49] ppocr INFO: **********./imgs/11.jpg**********
E0824 22:14:50.281687 19672 port.h:53] Load symbol cudnnGetConvolutionForwardAlgorithm failed.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\paddleocr\paddleocr.py", line 633, in main
    result = engine.ocr(img_path,
  File "C:\Program Files\Python310\lib\site-packages\paddleocr\paddleocr.py", line 511, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Program Files\Python310\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Program Files\Python310\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 234, in __call__
    self.predictor.run()
RuntimeError: cudnnGetConvolutionForwardAlgorithm not found.

**Comment by WenmuZhou** [comment]
Did paddle.utils.run_check() pass?

**Comment by xunlongjun** [comment]
I have reinstalled CUDA 11.7 and paddle for 11.6. Everything goes fine now.

**Comment by dlliu0422** [comment]
I also meet the same issue.
python=3.9
paddleocr=2.6.0.1
paddlepaddle-gpu=2.3.2
CUDA=11.7

**Comment by ForBagels** [comment]
Using: paddleOCR = 2.6.1.3 /paddlepaddle-gpu = 2.4.2/ CUDA = 11.7,
meet this problem when trying to use end2end model PgNet.
Found the solution on the[ installation guide of PaddlePaddle ](https://www.paddlepaddle.org.cn/documentation/docs/en/install/index_en.html)

> Please attention that PaddlePaddle installed through command below only supports CUDA10.2 under Windows、Ubuntu、CentOS: python -m pip install paddlepaddle-gpu==2.4.2 -i https://mirror.baidu.com/pypi/simple

Solved the problem by installing CUDA version 10.2
