### ISSUE TITLE
SER training raise an exception

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#7348]
按照这个指导 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md
用XFUND数据训练SER模型，报错

:/data/SourceCodes/PaddleOCR# python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/scipy/fft/__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/scipy/sparse/sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
[2022/08/25 06:41:05] ppocr INFO: Architecture : 
[2022/08/25 06:41:05] ppocr INFO:     Backbone : 
[2022/08/25 06:41:05] ppocr INFO:         checkpoints : None
[2022/08/25 06:41:05] ppocr INFO:         mode : vi
[2022/08/25 06:41:05] ppocr INFO:         name : LayoutXLMForSer
[2022/08/25 06:41:05] ppocr INFO:         num_classes : 7
[2022/08/25 06:41:05] ppocr INFO:         pretrained : True
[2022/08/25 06:41:05] ppocr INFO:     Transform : None
[2022/08/25 06:41:05] ppocr INFO:     algorithm : LayoutXLM
[2022/08/25 06:41:05] ppocr INFO:     model_type : kie
[2022/08/25 06:41:05] ppocr INFO: Eval : 
[2022/08/25 06:41:05] ppocr INFO:     dataset : 
[2022/08/25 06:41:05] ppocr INFO:         data_dir : train_data/XFUND/zh_val/image
[2022/08/25 06:41:05] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_val/val.json']
[2022/08/25 06:41:05] ppocr INFO:         name : SimpleDataSet
[2022/08/25 06:41:05] ppocr INFO:         transforms : 
[2022/08/25 06:41:05] ppocr INFO:             DecodeImage : 
[2022/08/25 06:41:05] ppocr INFO:                 channel_first : False
[2022/08/25 06:41:05] ppocr INFO:                 img_mode : RGB
[2022/08/25 06:41:05] ppocr INFO:             VQATokenLabelEncode : 
[2022/08/25 06:41:05] ppocr INFO:                 algorithm : LayoutXLM
[2022/08/25 06:41:05] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2022/08/25 06:41:05] ppocr INFO:                 contains_re : False
[2022/08/25 06:41:05] ppocr INFO:                 order_method : tb-yx
[2022/08/25 06:41:05] ppocr INFO:                 use_textline_bbox_info : True
[2022/08/25 06:41:05] ppocr INFO:             VQATokenPad : 
[2022/08/25 06:41:05] ppocr INFO:                 max_seq_len : 512
[2022/08/25 06:41:05] ppocr INFO:                 return_attention_mask : True
[2022/08/25 06:41:05] ppocr INFO:             VQASerTokenChunk : 
[2022/08/25 06:41:05] ppocr INFO:                 max_seq_len : 512
[2022/08/25 06:41:05] ppocr INFO:             Resize : 
[2022/08/25 06:41:05] ppocr INFO:                 size : [224, 224]
[2022/08/25 06:41:05] ppocr INFO:             NormalizeImage : 
[2022/08/25 06:41:05] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2022/08/25 06:41:05] ppocr INFO:                 order : hwc
[2022/08/25 06:41:05] ppocr INFO:                 scale : 1
[2022/08/25 06:41:05] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2022/08/25 06:41:05] ppocr INFO:             ToCHWImage : None
[2022/08/25 06:41:05] ppocr INFO:             KeepKeys : 
[2022/08/25 06:41:05] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2022/08/25 06:41:05] ppocr INFO:     loader : 
[2022/08/25 06:41:05] ppocr INFO:         batch_size_per_card : 8
[2022/08/25 06:41:05] ppocr INFO:         drop_last : False
[2022/08/25 06:41:05] ppocr INFO:         num_workers : 4
[2022/08/25 06:41:05] ppocr INFO:         shuffle : False
[2022/08/25 06:41:05] ppocr INFO: Global : 
[2022/08/25 06:41:05] ppocr INFO:     cal_metric_during_train : False
[2022/08/25 06:41:05] ppocr INFO:     distributed : False
[2022/08/25 06:41:05] ppocr INFO:     epoch_num : 200
[2022/08/25 06:41:05] ppocr INFO:     eval_batch_step : [0, 19]
[2022/08/25 06:41:05] ppocr INFO:     infer_img : ppstructure/docs/kie/input/zh_val_42.jpg
[2022/08/25 06:41:05] ppocr INFO:     kie_det_model_dir : None
[2022/08/25 06:41:05] ppocr INFO:     kie_rec_model_dir : None
[2022/08/25 06:41:05] ppocr INFO:     log_smooth_window : 10
[2022/08/25 06:41:05] ppocr INFO:     print_batch_step : 10
[2022/08/25 06:41:05] ppocr INFO:     save_epoch_step : 2000
[2022/08/25 06:41:05] ppocr INFO:     save_inference_dir : None
[2022/08/25 06:41:05] ppocr INFO:     save_model_dir : ./output/ser_vi_layoutxlm_xfund_zh
[2022/08/25 06:41:05] ppocr INFO:     save_res_path : ./output/ser/xfund_zh/res
[2022/08/25 06:41:05] ppocr INFO:     seed : 2022
[2022/08/25 06:41:05] ppocr INFO:     use_gpu : True
[2022/08/25 06:41:05] ppocr INFO:     use_visualdl : False
[2022/08/25 06:41:05] ppocr INFO: Loss : 
[2022/08/25 06:41:05] ppocr INFO:     key : backbone_out
[2022/08/25 06:41:05] ppocr INFO:     name : VQASerTokenLayoutLMLoss
[2022/08/25 06:41:05] ppocr INFO:     num_classes : 7
[2022/08/25 06:41:05] ppocr INFO: Metric : 
[2022/08/25 06:41:05] ppocr INFO:     main_indicator : hmean
[2022/08/25 06:41:05] ppocr INFO:     name : VQASerTokenMetric
[2022/08/25 06:41:05] ppocr INFO: Optimizer : 
[2022/08/25 06:41:05] ppocr INFO:     beta1 : 0.9
[2022/08/25 06:41:05] ppocr INFO:     beta2 : 0.999
[2022/08/25 06:41:05] ppocr INFO:     lr : 
[2022/08/25 06:41:05] ppocr INFO:         epochs : 200
[2022/08/25 06:41:05] ppocr INFO:         learning_rate : 5e-05
[2022/08/25 06:41:05] ppocr INFO:         name : Linear
[2022/08/25 06:41:05] ppocr INFO:         warmup_epoch : 2
[2022/08/25 06:41:05] ppocr INFO:     name : AdamW
[2022/08/25 06:41:05] ppocr INFO:     regularizer : 
[2022/08/25 06:41:05] ppocr INFO:         factor : 0.0
[2022/08/25 06:41:05] ppocr INFO:         name : L2
[2022/08/25 06:41:05] ppocr INFO: PostProcess : 
[2022/08/25 06:41:05] ppocr INFO:     class_path : train_data/XFUND/class_list_xfun.txt
[2022/08/25 06:41:05] ppocr INFO:     name : VQASerTokenLayoutLMPostProcess
[2022/08/25 06:41:05] ppocr INFO: Train : 
[2022/08/25 06:41:05] ppocr INFO:     dataset : 
[2022/08/25 06:41:05] ppocr INFO:         data_dir : train_data/XFUND/zh_train/image
[2022/08/25 06:41:05] ppocr INFO:         label_file_list : ['train_data/XFUND/zh_train/train.json']
[2022/08/25 06:41:05] ppocr INFO:         name : SimpleDataSet
[2022/08/25 06:41:05] ppocr INFO:         ratio_list : [1.0]
[2022/08/25 06:41:05] ppocr INFO:         transforms : 
[2022/08/25 06:41:05] ppocr INFO:             DecodeImage : 
[2022/08/25 06:41:05] ppocr INFO:                 channel_first : False
[2022/08/25 06:41:05] ppocr INFO:                 img_mode : RGB
[2022/08/25 06:41:05] ppocr INFO:             VQATokenLabelEncode : 
[2022/08/25 06:41:05] ppocr INFO:                 algorithm : LayoutXLM
[2022/08/25 06:41:05] ppocr INFO:                 class_path : train_data/XFUND/class_list_xfun.txt
[2022/08/25 06:41:05] ppocr INFO:                 contains_re : False
[2022/08/25 06:41:05] ppocr INFO:                 order_method : tb-yx
[2022/08/25 06:41:05] ppocr INFO:                 use_textline_bbox_info : True
[2022/08/25 06:41:05] ppocr INFO:             VQATokenPad : 
[2022/08/25 06:41:05] ppocr INFO:                 max_seq_len : 512
[2022/08/25 06:41:05] ppocr INFO:                 return_attention_mask : True
[2022/08/25 06:41:05] ppocr INFO:             VQASerTokenChunk : 
[2022/08/25 06:41:05] ppocr INFO:                 max_seq_len : 512
[2022/08/25 06:41:05] ppocr INFO:             Resize : 
[2022/08/25 06:41:05] ppocr INFO:                 size : [224, 224]
[2022/08/25 06:41:05] ppocr INFO:             NormalizeImage : 
[2022/08/25 06:41:05] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2022/08/25 06:41:05] ppocr INFO:                 order : hwc
[2022/08/25 06:41:05] ppocr INFO:                 scale : 1
[2022/08/25 06:41:05] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2022/08/25 06:41:05] ppocr INFO:             ToCHWImage : None
[2022/08/25 06:41:05] ppocr INFO:             KeepKeys : 
[2022/08/25 06:41:05] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2022/08/25 06:41:05] ppocr INFO:     loader : 
[2022/08/25 06:41:05] ppocr INFO:         batch_size_per_card : 8
[2022/08/25 06:41:05] ppocr INFO:         drop_last : False
[2022/08/25 06:41:05] ppocr INFO:         num_workers : 4
[2022/08/25 06:41:05] ppocr INFO:         shuffle : True
[2022/08/25 06:41:05] ppocr INFO: profiler_options : None
[2022/08/25 06:41:05] ppocr INFO: train with paddle 2.2.1 and device CUDAPlace(0)
[2022/08/25 06:41:05] ppocr INFO: Initialize indexs of datasets:['train_data/XFUND/zh_train/train.json']
[2022-08-25 06:41:08,798] [    INFO] - Already cached /root/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2022-08-25 06:41:09,855] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2022-08-25 06:41:09,856] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2022/08/25 06:41:09] ppocr INFO: Initialize indexs of datasets:['train_data/XFUND/zh_val/val.json']
[2022-08-25 06:41:09,859] [    INFO] - Already cached /root/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2022-08-25 06:41:11,077] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2022-08-25 06:41:11,077] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2022-08-25 06:41:11,080] [    INFO] - Already cached /root/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2022-08-25 06:41:11,080] [    INFO] - Already cached /root/.paddlenlp/models/vi-layoutxlm-base-uncased/model_config.json
W0825 06:41:11.082350 21676 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.1
W0825 06:41:11.087002 21676 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[2022-08-25 06:41:21,270] [    INFO] - Weights from pretrained model not used in LayoutXLMModel: ['classifier.weight', 'classifier.bias']
[2022/08/25 06:41:24] ppocr INFO: train dataloader has 19 iters
[2022/08/25 06:41:24] ppocr INFO: valid dataloader has 7 iters
[2022/08/25 06:41:24] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
Corrupt JPEG data: 18 extraneous bytes before marker 0xc4
Traceback (most recent call last):
  **_File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/data/SourceCodes/PaddleOCR/tools/program.py", line 299, in train
    preds = model(batch)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/SourceCodes/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/SourceCodes/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 177, in forward
    res.update(x[1])
IndexError: tuple index out of range_**

**Comment by littletomatodonkey** [comment]
你好，需要安装最新版本的paddlenlp哈，或者使用这个whl包：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl
