### ISSUE TITLE
尝试将SEED训练模型转换为inference模型时报错IndexError: Valid index accept int or slice or ellipsis, but received [].

### ISSUE THREAD

**Issue by labmanno004** [PaddlePaddle/PaddleOCR#7375]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：registry.baidubce.com/paddlepaddle/paddle   2.1.3-gpu-cuda11.2-cudnn8 
- 运行指令/Command Code：python3 tools/export_model.py -c configs/rec/rec_resnet_stn_bilstm_att.yml -o Global.pretrained_model=./rec_resnet_stn_bilstm_att/best_accuracy Global.save_inference_dir=./inference/SEED/
- 完整报错/Complete Error Message：
[2022/08/26 07:35:33] ppocr INFO: load pretrain successful from ./rec_resnet_stn_bilstm_att/best_accuracy
Traceback (most recent call last):
  File "tools/export_model.py", line 255, in <module>
    main()
  File "tools/export_model.py", line 251, in main
    model, arch_config, save_path, logger, input_shape=input_shape)
  File "tools/export_model.py", line 171, in export_single_model
    paddle.jit.save(model, save_path)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 726, in save
    inner_input_spec)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
IndexError: In transformed code:

    File "/tmp/tmpyezlupqm.py", line 92, in forward
        final_name, x))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward (* user code *)
        x = self.head(x, targets=data)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpqgv3my0n.py", line 29, in forward
        x), (embedding_vectors, return_dict, self, x), (rec_pred,))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/PaddleOCR/ppocr/modeling/heads/rec_aster_head.py", line 64, in forward (* user code *)
        x, self.beam_width, self.eos, embedding_vectors)
    File "/home/PaddleOCR/ppocr/modeling/heads/rec_aster_head.py", line 174, in beam_search (* user code *)
        sequence_scores[index] = 0.0
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1686, in __setitem__
        return _setitem_impl_(self, item, value)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 317, in _setitem_impl_
        format(slice_item))
    IndexError: Valid index accept int or slice or ellipsis, but received [].

**Comment by tink2123** [comment]
问题排查中，感谢反馈～

**Comment by labmanno004** [comment]
拉取最新的代码后，发生了新的问题
Traceback (most recent call last):
  File "tools/export_model.py", line 256, in <module>
    main()
  File "tools/export_model.py", line 252, in main
    model, arch_config, save_path, logger, input_shape=input_shape)
  File "tools/export_model.py", line 172, in export_single_model
    paddle.jit.save(model, save_path)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 726, in save
    inner_input_spec)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/tmp/tmp312yizyn.py", line 92, in forward
        final_name, x))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward (* user code *)
        x = self.head(x, targets=data)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp7aslpa23.py", line 31, in forward
        x), (embedding_vectors, return_dict, self, x), (rec_pred,))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/PaddleOCR/ppocr/modeling/heads/rec_aster_head.py", line 64, in forward (* user code *)
        x, self.beam_width, self.eos, embedding_vectors)
    File "/home/PaddleOCR/ppocr/modeling/heads/rec_aster_head.py", line 133, in beam_search (* user code *)
        batch_size, l, d = paddle.shape(x)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1683, in __getitem__
        return _getitem_impl_(self, item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 225, in _getitem_impl_
        attrs=attrs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2967, in append_op
        attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2154, in __init__
        self.desc.infer_shape(self.block.desc)
    ValueError: (InvalidArgument) end should greater than start, but received end = 4, start = 3.
  [Hint: Expected end > start, but received end:3 <= start:3.] (at /paddle/paddle/fluid/operators/slice_op.cc:135)
  [operator < slice > error]

**Comment by labmanno004** [comment]
> 拉取最新的代码后，发生了新的问题 Traceback (most recent call last): File "tools/export_model.py", line 256, in main() File "tools/export_model.py", line 252, in main model, arch_config, save_path, logger, input_shape=input_shape) File "tools/export_model.py", line 172, in export_single_model paddle.jit.save(model, save_path) File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in **impl** return func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 726, in save inner_input_spec) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec *desired_input_spec) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program concrete_program, partial_program_layer = self._program_cache[cache_key] File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in **getitem** self._caches[item] = self._build_once(item) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once class_instance=cache_key.class_instance) File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in **impl** return func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec error_data.raise_new_exception() File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception six.exec_("raise new_exception from None") File "", line 1, in ValueError: In transformed code:
> 
> ```
> File "/tmp/tmp312yizyn.py", line 92, in forward
>     final_name, x))
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
>     return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
>     return true_fn(*true_args) if pred else false_fn(*false_args)
> File "/home/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward (* user code *)
>     x = self.head(x, targets=data)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
>     outputs = self.forward(*inputs, **kwargs)
> File "/tmp/tmp7aslpa23.py", line 31, in forward
>     x), (embedding_vectors, return_dict, self, x), (rec_pred,))
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
>     return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
>     return true_fn(*true_args) if pred else false_fn(*false_args)
> File "/home/PaddleOCR/ppocr/modeling/heads/rec_aster_head.py", line 64, in forward (* user code *)
>     x, self.beam_width, self.eos, embedding_vectors)
> File "/home/PaddleOCR/ppocr/modeling/heads/rec_aster_head.py", line 133, in beam_search (* user code *)
>     batch_size, l, d = paddle.shape(x)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1683, in __getitem__
>     return _getitem_impl_(self, item)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 225, in _getitem_impl_
>     attrs=attrs)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2967, in append_op
>     attrs=kwargs.get("attrs", None))
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2154, in __init__
>     self.desc.infer_shape(self.block.desc)
> ValueError: (InvalidArgument) end should greater than start, but received end = 4, start = 3.
> ```
> 
> [Hint: Expected end > start, but received end:3 <= start:3.] (at /paddle/paddle/fluid/operators/slice_op.cc:135) [operator < slice > error]

已提交新issue#7512
