### ISSUE TITLE
转成inference模型报错

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#7412]
训练好的模型转换成inference模型时报错：

Traceback (most recent call last):
  File "tools/export_model.py", line 258, in <module>
    main()
  File "tools/export_model.py", line 254, in main
    model, arch_config, save_path, logger, input_shape=input_shape)
  File "tools/export_model.py", line 174, in export_single_model
    paddle.jit.save(model, save_path)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
    inner_input_spec)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 744, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 735, in _build_once
    **cache_key.kwargs)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 689, in from_func_spec
    error_data.raise_new_exception()
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/data/SourceCodes/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
	x = self.backbone(x)
    File "/data/SourceCodes/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 174, in forward
	labels=None)
    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1047, in forward
	head_mask=head_mask,
    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 919, in forward
            ],
            axis=-1,
        ).reshape([expand_shape[0] * expand_shape[1],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                   paddle.shape(bbox)[-1]])

    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 798, in stack
	return layers.stack(x, axis, name)
    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 10203, in stack
	attrs={'axis': axis})
    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
	attrs=kwargs.get("attrs", None))
    File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2344, in __init__
	self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) Dims of all Inputs(X) must be the same, but received input 1 dim is:7, -1 not equal to input 0 dim:-1, 7.
  [Hint: Expected input_dims[i] == input_dims[0], but received input_dims[i]:7, -1 != input_dims[0]:-1, 7.] (at /paddle/paddle/fluid/operators/stack_op.cc:46)
  [operator < stack > error]

**Comment by littletomatodonkey** [comment]
你好，paddle版本请使用2.3.1+，paddlenlp可以使用：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

**Comment by jack-gits** [comment]
报了另外错误

/PaddleOCR$ python3 tools/export_model.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_cro_vl_fr_category.yml -o Architecture.Backbone.checkpoints=./output/cro_vl_fr_category_models/best_accuracy Global.save_inference_dir=./inference/cro_vl_fr_category_models
[2022/09/01 14:37:45] ppocr INFO: resume from ./output/cro_vl_fr_category_models/best_accuracy
[2022/09/01 14:37:45] ppocr INFO: arch_config={'model_type': 'kie', 'algorithm': 'LayoutXLM', 'Transform': None, 'Backbone': {'name': 'LayoutXLMForSer', 'pretrained': True, 'checkpoints': './output/cro_vl_fr_category_models/best_accuracy', 'mode': 'vi', 'num_classes': 147}}
Traceback (most recent call last):
  File "tools/export_model.py", line 258, in <module>
    main()
  File "tools/export_model.py", line 253, in main
    export_single_model(
  File "tools/export_model.py", line 174, in export_single_model
    paddle.jit.save(model, save_path)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "/home/venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/home/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/home/model-server/neuron/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
	x = self.backbone(x)
    File "/home/model-server/neuron/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 166, in forward
	x = self.model(
    File "/home/venv/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 873, in forward
	outputs = self.layoutxlm(
    File "/home/venv/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 781, in forward
            attention_mask = paddle.ones(input_shape)

        visual_attention_mask = paddle.ones(visual_shape)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        attention_mask = attention_mask.astype(visual_attention_mask.dtype)

    File "/home/venv/lib/python3.8/site-packages/paddle/tensor/creation.py", line 291, in ones
	return fill_constant(value=1.0, shape=shape, dtype=dtype, name=name)
    File "/home/venv/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 797, in fill_constant
	check_shape(shape)
    File "/home/venv/lib/python3.8/site-packages/paddle/fluid/layers/utils.py", line 386, in check_shape
	raise ValueError(

    ValueError: All elements in ``shape`` must be positive when it's a list or tuple

**Comment by gjj123** [comment]
有没有人遇到模型转成推理模型 成功了，但是推理结果不对？

**Comment by gjj123** [comment]
> paddlenlp 2.3.0 paddlepaddle 2.3.2

paddlenlp develop 用
paddlepaddle 2.3.2
