### ISSUE TITLE
tensor变list的神奇转化

### ISSUE THREAD

**Issue by Morickie** [PaddlePaddle/PaddleOCR#7414]
aistudio环境, 服了, 各种问题层出不穷....
之前还能正常训练, 不知为何就报如下问题, 实在头大.....

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 297, in train
    preds = model(images, data=batch[1:])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward
    x = self.head(x, targets=data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/heads/rec_multi_head.py", line 69, in forward
    sar_out = self.sar_head(x, targets[1:])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 400, in forward
    feat, holistic_feat, label, img_metas=targets)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 133, in forward
    return self.forward_train(feat, out_enc, label, img_metas)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 293, in forward_train
    assert paddle.shape(img_metas[0])[0] == paddle.shape(feat)[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 11702, in shape
    out = _C_ops.shape(input)
ValueError: (InvalidArgument) shape(): argument 'Input' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)

**Comment by tink2123** [comment]
麻烦提供下启动命令，代码分支和修改
