### ISSUE TITLE
用SLANet 算法训练中文表格识别模型出错，训练的数据是自己标注的。

### ISSUE THREAD

**Issue by asinwon** [PaddlePaddle/PaddleOCR#7424]
- 系统环境/System Environment：ubuntu20.04 + docker镜像： nvcr.io/nvidia/paddlepaddle:22.07-py3
- 版本号/Version：Paddle：paddlepaddle-gpu  2.3.0  PaddleOCR：2.6 问题相关组件/Related components：ppstructure
- 运行指令/Command Code：python3 tools/train.py -c configs/table/SLANet_ch.yml
- 完整报错/Complete Error Message：
[2022/08/30 11:12:56] ppocr INFO: Architecture : 
[2022/08/30 11:12:56] ppocr INFO:     Backbone : 
[2022/08/30 11:12:56] ppocr INFO:         name : PPLCNet
[2022/08/30 11:12:56] ppocr INFO:         pretrained : True
[2022/08/30 11:12:56] ppocr INFO:         scale : 1.0
[2022/08/30 11:12:56] ppocr INFO:         use_ssld : True
[2022/08/30 11:12:56] ppocr INFO:     Head : 
[2022/08/30 11:12:56] ppocr INFO:         hidden_size : 256
[2022/08/30 11:12:56] ppocr INFO:         loc_reg_num : 8
[2022/08/30 11:12:56] ppocr INFO:         max_text_length : 500
[2022/08/30 11:12:56] ppocr INFO:         name : SLAHead
[2022/08/30 11:12:56] ppocr INFO:     Neck : 
[2022/08/30 11:12:56] ppocr INFO:         name : CSPPAN
[2022/08/30 11:12:56] ppocr INFO:         out_channels : 96
[2022/08/30 11:12:56] ppocr INFO:     algorithm : SLANet
[2022/08/30 11:12:56] ppocr INFO:     model_type : table
[2022/08/30 11:12:56] ppocr INFO: Eval : 
[2022/08/30 11:12:56] ppocr INFO:     dataset : 
[2022/08/30 11:12:56] ppocr INFO:         data_dir : /paddle/label/images/data/Eval
[2022/08/30 11:12:56] ppocr INFO:         label_file_list : ['/paddle/label/images/annotation.jsonl']
[2022/08/30 11:12:56] ppocr INFO:         name : PubTabDataSet
[2022/08/30 11:12:56] ppocr INFO:         transforms : 
[2022/08/30 11:12:56] ppocr INFO:             DecodeImage : 
[2022/08/30 11:12:56] ppocr INFO:                 channel_first : False
[2022/08/30 11:12:56] ppocr INFO:                 img_mode : BGR
[2022/08/30 11:12:56] ppocr INFO:             TableLabelEncode : 
[2022/08/30 11:12:56] ppocr INFO:                 learn_empty_box : False
[2022/08/30 11:12:56] ppocr INFO:                 loc_reg_num : 8
[2022/08/30 11:12:56] ppocr INFO:                 max_text_length : 500
[2022/08/30 11:12:56] ppocr INFO:                 merge_no_span_structure : True
[2022/08/30 11:12:56] ppocr INFO:                 replace_empty_cell_token : False
[2022/08/30 11:12:56] ppocr INFO:             TableBoxEncode : 
[2022/08/30 11:12:56] ppocr INFO:                 in_box_format : xyxyxyxy
[2022/08/30 11:12:56] ppocr INFO:                 out_box_format : xyxyxyxy
[2022/08/30 11:12:56] ppocr INFO:             ResizeTableImage : 
[2022/08/30 11:12:56] ppocr INFO:                 max_len : 488
[2022/08/30 11:12:56] ppocr INFO:             NormalizeImage : 
[2022/08/30 11:12:56] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2022/08/30 11:12:56] ppocr INFO:                 order : hwc
[2022/08/30 11:12:56] ppocr INFO:                 scale : 1./255.
[2022/08/30 11:12:56] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2022/08/30 11:12:56] ppocr INFO:             PaddingTableImage : 
[2022/08/30 11:12:56] ppocr INFO:                 size : [488, 488]
[2022/08/30 11:12:56] ppocr INFO:             ToCHWImage : None
[2022/08/30 11:12:56] ppocr INFO:             KeepKeys : 
[2022/08/30 11:12:56] ppocr INFO:                 keep_keys : ['image', 'structure', 'bboxes', 'bbox_masks', 'shape']
[2022/08/30 11:12:56] ppocr INFO:     loader : 
[2022/08/30 11:12:56] ppocr INFO:         batch_size_per_card : 18
[2022/08/30 11:12:56] ppocr INFO:         drop_last : False
[2022/08/30 11:12:56] ppocr INFO:         num_workers : 1
[2022/08/30 11:12:56] ppocr INFO:         shuffle : False
[2022/08/30 11:12:56] ppocr INFO: Global : 
[2022/08/30 11:12:56] ppocr INFO:     box_format : xyxyxyxy
[2022/08/30 11:12:56] ppocr INFO:     cal_metric_during_train : True
[2022/08/30 11:12:56] ppocr INFO:     character_dict_path : /paddle/PaddleOCR/ppocr/utils/dict/table_structure_dict_ch.txt
[2022/08/30 11:12:56] ppocr INFO:     character_type : en
[2022/08/30 11:12:56] ppocr INFO:     checkpoints : None
[2022/08/30 11:12:56] ppocr INFO:     distributed : False
[2022/08/30 11:12:56] ppocr INFO:     epoch_num : 400
[2022/08/30 11:12:56] ppocr INFO:     eval_batch_step : [0, 331]
[2022/08/30 11:12:56] ppocr INFO:     infer_img : /paddle/PaddleOCR/doc/table/table.jpg
[2022/08/30 11:12:56] ppocr INFO:     infer_mode : False
[2022/08/30 11:12:56] ppocr INFO:     log_smooth_window : 20
[2022/08/30 11:12:56] ppocr INFO:     max_text_length : 500
[2022/08/30 11:12:56] ppocr INFO:     pretrained_model : /paddle/model/pretrained/SLANet/best_accuracy.pdparams
[2022/08/30 11:12:56] ppocr INFO:     print_batch_step : 20
[2022/08/30 11:12:56] ppocr INFO:     save_epoch_step : 400
[2022/08/30 11:12:56] ppocr INFO:     save_inference_dir : /paddle/model/inference/Custom
[2022/08/30 11:12:56] ppocr INFO:     save_model_dir : /paddle/model/trained/output
[2022/08/30 11:12:56] ppocr INFO:     save_res_path : /paddle/output
[2022/08/30 11:12:56] ppocr INFO:     use_gpu : True
[2022/08/30 11:12:56] ppocr INFO:     use_sync_bn : True
[2022/08/30 11:12:56] ppocr INFO:     use_visualdl : False
[2022/08/30 11:12:56] ppocr INFO: Loss : 
[2022/08/30 11:12:56] ppocr INFO:     loc_loss : smooth_l1
[2022/08/30 11:12:56] ppocr INFO:     loc_weight : 2.0
[2022/08/30 11:12:56] ppocr INFO:     name : SLALoss
[2022/08/30 11:12:56] ppocr INFO:     structure_weight : 1.0
[2022/08/30 11:12:56] ppocr INFO: Metric : 
[2022/08/30 11:12:56] ppocr INFO:     box_format : xyxyxyxy
[2022/08/30 11:12:56] ppocr INFO:     compute_bbox_metric : False
[2022/08/30 11:12:56] ppocr INFO:     del_thead_tbody : True
[2022/08/30 11:12:56] ppocr INFO:     loc_reg_num : 8
[2022/08/30 11:12:56] ppocr INFO:     main_indicator : acc
[2022/08/30 11:12:56] ppocr INFO:     name : TableMetric
[2022/08/30 11:12:56] ppocr INFO: Optimizer : 
[2022/08/30 11:12:56] ppocr INFO:     beta1 : 0.9
[2022/08/30 11:12:56] ppocr INFO:     beta2 : 0.999
[2022/08/30 11:12:56] ppocr INFO:     clip_norm : 5.0
[2022/08/30 11:12:56] ppocr INFO:     lr : 
[2022/08/30 11:12:56] ppocr INFO:         learning_rate : 0.001
[2022/08/30 11:12:56] ppocr INFO:     name : Adam
[2022/08/30 11:12:56] ppocr INFO:     regularizer : 
[2022/08/30 11:12:56] ppocr INFO:         factor : 0.0
[2022/08/30 11:12:56] ppocr INFO:         name : L2
[2022/08/30 11:12:56] ppocr INFO: PostProcess : 
[2022/08/30 11:12:56] ppocr INFO:     merge_no_span_structure : True
[2022/08/30 11:12:56] ppocr INFO:     name : TableLabelDecode
[2022/08/30 11:12:56] ppocr INFO: Train : 
[2022/08/30 11:12:56] ppocr INFO:     dataset : 
[2022/08/30 11:12:56] ppocr INFO:         data_dir : /paddle/label/images/data/Train
[2022/08/30 11:12:56] ppocr INFO:         label_file_list : ['/paddle/label/images/annotation.jsonl']
[2022/08/30 11:12:56] ppocr INFO:         name : PubTabDataSet
[2022/08/30 11:12:56] ppocr INFO:         transforms : 
[2022/08/30 11:12:56] ppocr INFO:             DecodeImage : 
[2022/08/30 11:12:56] ppocr INFO:                 channel_first : False
[2022/08/30 11:12:56] ppocr INFO:                 img_mode : BGR
[2022/08/30 11:12:56] ppocr INFO:             TableLabelEncode : 
[2022/08/30 11:12:56] ppocr INFO:                 learn_empty_box : False
[2022/08/30 11:12:56] ppocr INFO:                 loc_reg_num : 8
[2022/08/30 11:12:56] ppocr INFO:                 max_text_length : 500
[2022/08/30 11:12:56] ppocr INFO:                 merge_no_span_structure : True
[2022/08/30 11:12:56] ppocr INFO:                 replace_empty_cell_token : False
[2022/08/30 11:12:56] ppocr INFO:             TableBoxEncode : 
[2022/08/30 11:12:56] ppocr INFO:                 in_box_format : xyxyxyxy
[2022/08/30 11:12:56] ppocr INFO:                 out_box_format : xyxyxyxy
[2022/08/30 11:12:56] ppocr INFO:             ResizeTableImage : 
[2022/08/30 11:12:56] ppocr INFO:                 max_len : 488
[2022/08/30 11:12:56] ppocr INFO:             NormalizeImage : 
[2022/08/30 11:12:56] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2022/08/30 11:12:56] ppocr INFO:                 order : hwc
[2022/08/30 11:12:56] ppocr INFO:                 scale : 1./255.
[2022/08/30 11:12:56] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2022/08/30 11:12:56] ppocr INFO:             PaddingTableImage : 
[2022/08/30 11:12:56] ppocr INFO:                 size : [488, 488]
[2022/08/30 11:12:56] ppocr INFO:             ToCHWImage : None
[2022/08/30 11:12:56] ppocr INFO:             KeepKeys : 
[2022/08/30 11:12:56] ppocr INFO:                 keep_keys : ['image', 'structure', 'bboxes', 'bbox_masks', 'shape']
[2022/08/30 11:12:56] ppocr INFO:     loader : 
[2022/08/30 11:12:56] ppocr INFO:         batch_size_per_card : 18
[2022/08/30 11:12:56] ppocr INFO:         drop_last : True
[2022/08/30 11:12:56] ppocr INFO:         num_workers : 1
[2022/08/30 11:12:56] ppocr INFO:         shuffle : True
[2022/08/30 11:12:56] ppocr INFO: profiler_options : None
[2022/08/30 11:12:56] ppocr INFO: train with paddle 2.3.0 and device Place(gpu:0)
[2022/08/30 11:12:56] ppocr INFO: Initialize indexs of datasets:['/paddle/label/images/annotation.jsonl']
[2022/08/30 11:12:56] ppocr INFO: Initialize indexs of datasets:['/paddle/label/images/annotation.jsonl']
[2022/08/30 11:13:18] ppocr INFO: convert_sync_batchnorm
[2022/08/30 11:13:18] ppocr INFO: train dataloader has 1 iters
[2022/08/30 11:13:18] ppocr INFO: valid dataloader has 1 iters
[2022/08/30 11:13:18] ppocr INFO: load pretrain successful from /paddle/model/pretrained/SLANet/best_accuracy
[2022/08/30 11:13:18] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 331 iterations
[2022/08/30 11:13:18] ppocr ERROR: When parsing line {"filename":"029-ZY·HYDJ2015-Y-2301.jpg","split":"train","imgid":15,"html":{"structure":{"tokens":["<tbody>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","<tr>","<td>","</td>","<td>","</td>","<td>","</td>","</tr>","</tbody>"]},"cells":[{"tokens":["页","数"],"bbox":[2050,347,2173,418]}, ...................error happened with msg: Traceback (most recent call last):
  File "/paddle/PaddleOCR/ppocr/data/pubtab_dataset.py", line 118, in __getitem__
    outs = transform(data, self.ops)
  File "/paddle/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform
    data = op(data)
  File "/paddle/PaddleOCR/ppocr/data/imaug/label_ops.py", line 673, in __call__
    bboxes[i] = bbox
ValueError: could not broadcast input array from shape (4,) into shape (8,)�

**Comment by WenmuZhou** [comment]
你的标注点是四个，使用slanet.yml

**Comment by asinwon** [comment]
> 你的标注点是四个，使用slanet.yml

谢谢，已经解决了

**Comment by lltzahdz** [comment]
请问如何解决的
