### ISSUE TITLE
SystemError: (Fatal) DataLoader process (pid 10222) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

### ISSUE THREAD

**Issue by lingyiliu016** [PaddlePaddle/PaddleOCR#7433]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：**ubuntu18.04**
- 版本号/Version：Paddle：**2.3.0**  PaddleOCR：**release2.6** 问题相关组件/Related components：**tools/train.py**
- 运行指令/Command Code：`python3 tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.use_gpu=false Global.epoch_num=50 Global.pretrained_model=/home/cly/Downloads/ch_PP-OCRv3_rec_train/best_accuracy Optimizer.lr.learning_rate=0.0001 Train.dataset.data_dir=./train_data/rec/train/ Train.dataset.label_file_list=./train_data/rec/process_train.txt  Eval.dataset.data_dir=./train_data/rec/val/ Eval.dataset.label_file_list=./train_data/rec/process_val.txt`
- 完整报错/Complete Error Message：
[2022/08/31 10:44:23] ppocr INFO: Architecture : 
[2022/08/31 10:44:23] ppocr INFO:     Models : 
[2022/08/31 10:44:23] ppocr INFO:         Student : 
[2022/08/31 10:44:23] ppocr INFO:             Backbone : 
[2022/08/31 10:44:23] ppocr INFO:                 last_conv_stride : [1, 2]
[2022/08/31 10:44:23] ppocr INFO:                 last_pool_type : avg
[2022/08/31 10:44:23] ppocr INFO:                 name : MobileNetV1Enhance
[2022/08/31 10:44:23] ppocr INFO:                 scale : 0.5
[2022/08/31 10:44:23] ppocr INFO:             Head : 
[2022/08/31 10:44:23] ppocr INFO:                 head_list : 
[2022/08/31 10:44:23] ppocr INFO:                     CTCHead : 
[2022/08/31 10:44:23] ppocr INFO:                         Head : 
[2022/08/31 10:44:23] ppocr INFO:                             fc_decay : 1e-05
[2022/08/31 10:44:23] ppocr INFO:                         Neck : 
[2022/08/31 10:44:23] ppocr INFO:                             depth : 2
[2022/08/31 10:44:23] ppocr INFO:                             dims : 64
[2022/08/31 10:44:23] ppocr INFO:                             hidden_dims : 120
[2022/08/31 10:44:23] ppocr INFO:                             name : svtr
[2022/08/31 10:44:23] ppocr INFO:                             use_guide : True
[2022/08/31 10:44:23] ppocr INFO:                     SARHead : 
[2022/08/31 10:44:23] ppocr INFO:                         enc_dim : 512
[2022/08/31 10:44:23] ppocr INFO:                         max_text_length : 25
[2022/08/31 10:44:23] ppocr INFO:                 name : MultiHead
[2022/08/31 10:44:23] ppocr INFO:             Transform : None
[2022/08/31 10:44:23] ppocr INFO:             algorithm : SVTR
[2022/08/31 10:44:23] ppocr INFO:             freeze_params : False
[2022/08/31 10:44:23] ppocr INFO:             model_type : rec
[2022/08/31 10:44:23] ppocr INFO:             pretrained : None
[2022/08/31 10:44:23] ppocr INFO:             return_all_feats : True
[2022/08/31 10:44:23] ppocr INFO:         Teacher : 
[2022/08/31 10:44:23] ppocr INFO:             Backbone : 
[2022/08/31 10:44:23] ppocr INFO:                 last_conv_stride : [1, 2]
[2022/08/31 10:44:23] ppocr INFO:                 last_pool_type : avg
[2022/08/31 10:44:23] ppocr INFO:                 name : MobileNetV1Enhance
[2022/08/31 10:44:23] ppocr INFO:                 scale : 0.5
[2022/08/31 10:44:23] ppocr INFO:             Head : 
[2022/08/31 10:44:23] ppocr INFO:                 head_list : 
[2022/08/31 10:44:23] ppocr INFO:                     CTCHead : 
[2022/08/31 10:44:23] ppocr INFO:                         Head : 
[2022/08/31 10:44:23] ppocr INFO:                             fc_decay : 1e-05
[2022/08/31 10:44:23] ppocr INFO:                         Neck : 
[2022/08/31 10:44:23] ppocr INFO:                             depth : 2
[2022/08/31 10:44:23] ppocr INFO:                             dims : 64
[2022/08/31 10:44:23] ppocr INFO:                             hidden_dims : 120
[2022/08/31 10:44:23] ppocr INFO:                             name : svtr
[2022/08/31 10:44:23] ppocr INFO:                             use_guide : True
[2022/08/31 10:44:23] ppocr INFO:                     SARHead : 
[2022/08/31 10:44:23] ppocr INFO:                         enc_dim : 512
[2022/08/31 10:44:23] ppocr INFO:                         max_text_length : 25
[2022/08/31 10:44:23] ppocr INFO:                 name : MultiHead
[2022/08/31 10:44:23] ppocr INFO:             Transform : None
[2022/08/31 10:44:23] ppocr INFO:             algorithm : SVTR
[2022/08/31 10:44:23] ppocr INFO:             freeze_params : False
[2022/08/31 10:44:23] ppocr INFO:             model_type : rec
[2022/08/31 10:44:23] ppocr INFO:             pretrained : None
[2022/08/31 10:44:23] ppocr INFO:             return_all_feats : True
[2022/08/31 10:44:23] ppocr INFO:     algorithm : Distillation
[2022/08/31 10:44:23] ppocr INFO:     model_type : rec
[2022/08/31 10:44:23] ppocr INFO:     name : DistillationModel
[2022/08/31 10:44:23] ppocr INFO: Eval : 
[2022/08/31 10:44:23] ppocr INFO:     dataset : 
[2022/08/31 10:44:23] ppocr INFO:         data_dir : **./train_data/rec/val/**
[2022/08/31 10:44:23] ppocr INFO:         label_file_list : **./train_data/rec/process_val.txt**
[2022/08/31 10:44:23] ppocr INFO:         name : SimpleDataSet
[2022/08/31 10:44:23] ppocr INFO:         transforms : 
[2022/08/31 10:44:23] ppocr INFO:             DecodeImage : 
[2022/08/31 10:44:23] ppocr INFO:                 channel_first : False
[2022/08/31 10:44:23] ppocr INFO:                 img_mode : BGR
[2022/08/31 10:44:23] ppocr INFO:             MultiLabelEncode : None
[2022/08/31 10:44:23] ppocr INFO:             RecResizeImg : 
[2022/08/31 10:44:23] ppocr INFO:                 image_shape : **[3, 48, 640]**
[2022/08/31 10:44:23] ppocr INFO:             KeepKeys : 
[2022/08/31 10:44:23] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2022/08/31 10:44:23] ppocr INFO:     loader : 
[2022/08/31 10:44:23] ppocr INFO:         batch_size_per_card : 128
[2022/08/31 10:44:23] ppocr INFO:         drop_last : False
[2022/08/31 10:44:23] ppocr INFO:         num_workers : 4
[2022/08/31 10:44:23] ppocr INFO:         shuffle : False
[2022/08/31 10:44:23] ppocr INFO: Global : 
[2022/08/31 10:44:23] ppocr INFO:     cal_metric_during_train : True
[2022/08/31 10:44:23] ppocr INFO:     character_dict_path : **ppocr/utils/ppocr_keys_v1.txt**
[2022/08/31 10:44:23] ppocr INFO:     checkpoints : None
[2022/08/31 10:44:23] ppocr INFO:     debug : False
[2022/08/31 10:44:23] ppocr INFO:     distributed : False
[2022/08/31 10:44:23] ppocr INFO:     epoch_num : **50**
[2022/08/31 10:44:23] ppocr INFO:     eval_batch_step : [0, 2000]
[2022/08/31 10:44:23] ppocr INFO:     infer_img : doc/imgs_words/ch/word_1.jpg
[2022/08/31 10:44:23] ppocr INFO:     infer_mode : False
[2022/08/31 10:44:23] ppocr INFO:     log_smooth_window : 20
[2022/08/31 10:44:23] ppocr INFO:     max_text_length : 25
[2022/08/31 10:44:23] ppocr INFO:     pretrained_model : **/home/cly/Downloads/ch_PP-OCRv3_rec_train/best_accuracy**
[2022/08/31 10:44:23] ppocr INFO:     print_batch_step : 10
[2022/08/31 10:44:23] ppocr INFO:     save_epoch_step : 3
[2022/08/31 10:44:23] ppocr INFO:     save_inference_dir : None
[2022/08/31 10:44:23] ppocr INFO:     save_model_dir : ./output/rec_ppocr_v3_distillation
[2022/08/31 10:44:23] ppocr INFO:     save_res_path : ./output/rec/predicts_ppocrv3_distillation.txt
[2022/08/31 10:44:23] ppocr INFO:     use_gpu : **False**
[2022/08/31 10:44:23] ppocr INFO:     use_space_char : True
[2022/08/31 10:44:23] ppocr INFO:     use_visualdl : False
[2022/08/31 10:44:23] ppocr INFO: Loss : 
[2022/08/31 10:44:23] ppocr INFO:     loss_config_list : 
[2022/08/31 10:44:23] ppocr INFO:         DistillationDMLLoss : 
[2022/08/31 10:44:23] ppocr INFO:             act : softmax
[2022/08/31 10:44:23] ppocr INFO:             dis_head : ctc
[2022/08/31 10:44:23] ppocr INFO:             key : head_out
[2022/08/31 10:44:23] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2022/08/31 10:44:23] ppocr INFO:             multi_head : True
[2022/08/31 10:44:23] ppocr INFO:             name : dml_ctc
[2022/08/31 10:44:23] ppocr INFO:             use_log : True
[2022/08/31 10:44:23] ppocr INFO:             weight : 1.0
[2022/08/31 10:44:23] ppocr INFO:         DistillationDMLLoss : 
[2022/08/31 10:44:23] ppocr INFO:             act : softmax
[2022/08/31 10:44:23] ppocr INFO:             dis_head : sar
[2022/08/31 10:44:23] ppocr INFO:             key : head_out
[2022/08/31 10:44:23] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2022/08/31 10:44:23] ppocr INFO:             multi_head : True
[2022/08/31 10:44:23] ppocr INFO:             name : dml_sar
[2022/08/31 10:44:23] ppocr INFO:             use_log : True
[2022/08/31 10:44:23] ppocr INFO:             weight : 0.5
[2022/08/31 10:44:23] ppocr INFO:         DistillationDistanceLoss : 
[2022/08/31 10:44:23] ppocr INFO:             key : backbone_out
[2022/08/31 10:44:23] ppocr INFO:             mode : l2
[2022/08/31 10:44:23] ppocr INFO:             model_name_pairs : [['Student', 'Teacher']]
[2022/08/31 10:44:23] ppocr INFO:             weight : 1.0
[2022/08/31 10:44:23] ppocr INFO:         DistillationCTCLoss : 
[2022/08/31 10:44:23] ppocr INFO:             key : head_out
[2022/08/31 10:44:23] ppocr INFO:             model_name_list : ['Student', 'Teacher']
[2022/08/31 10:44:23] ppocr INFO:             multi_head : True
[2022/08/31 10:44:23] ppocr INFO:             weight : 1.0
[2022/08/31 10:44:23] ppocr INFO:         DistillationSARLoss : 
[2022/08/31 10:44:23] ppocr INFO:             key : head_out
[2022/08/31 10:44:23] ppocr INFO:             model_name_list : ['Student', 'Teacher']
[2022/08/31 10:44:23] ppocr INFO:             multi_head : True
[2022/08/31 10:44:23] ppocr INFO:             weight : 1.0
[2022/08/31 10:44:23] ppocr INFO:     name : CombinedLoss
[2022/08/31 10:44:23] ppocr INFO: Metric : 
[2022/08/31 10:44:23] ppocr INFO:     base_metric_name : RecMetric
[2022/08/31 10:44:23] ppocr INFO:     ignore_space : False
[2022/08/31 10:44:23] ppocr INFO:     key : Student
[2022/08/31 10:44:23] ppocr INFO:     main_indicator : acc
[2022/08/31 10:44:23] ppocr INFO:     name : DistillationMetric
[2022/08/31 10:44:23] ppocr INFO: Optimizer : 
[2022/08/31 10:44:23] ppocr INFO:     beta1 : 0.9
[2022/08/31 10:44:23] ppocr INFO:     beta2 : 0.999
[2022/08/31 10:44:23] ppocr INFO:     lr : 
[2022/08/31 10:44:23] ppocr INFO:         decay_epochs : [700, 800]
[2022/08/31 10:44:23] ppocr INFO:         learning_rate : **0.0001**
[2022/08/31 10:44:23] ppocr INFO:         name : Piecewise
[2022/08/31 10:44:23] ppocr INFO:         values : [0.0005, 5e-05]
[2022/08/31 10:44:23] ppocr INFO:         warmup_epoch : 5
[2022/08/31 10:44:23] ppocr INFO:     name : Adam
[2022/08/31 10:44:23] ppocr INFO:     regularizer : 
[2022/08/31 10:44:23] ppocr INFO:         factor : 3e-05
[2022/08/31 10:44:23] ppocr INFO:         name : L2
[2022/08/31 10:44:23] ppocr INFO: PostProcess : 
[2022/08/31 10:44:23] ppocr INFO:     key : head_out
[2022/08/31 10:44:23] ppocr INFO:     model_name : ['Student', 'Teacher']
[2022/08/31 10:44:23] ppocr INFO:     multi_head : True
[2022/08/31 10:44:23] ppocr INFO:     name : DistillationCTCLabelDecode
[2022/08/31 10:44:23] ppocr INFO: Train : 
[2022/08/31 10:44:23] ppocr INFO:     dataset : 
[2022/08/31 10:44:23] ppocr INFO:         data_dir : **./train_data/rec/train/**
[2022/08/31 10:44:23] ppocr INFO:         ext_op_transform_idx : 1
[2022/08/31 10:44:23] ppocr INFO:         label_file_list : **./train_data/rec/process_train.txt**
[2022/08/31 10:44:23] ppocr INFO:         name : SimpleDataSet
[2022/08/31 10:44:23] ppocr INFO:         transforms : 
[2022/08/31 10:44:23] ppocr INFO:             DecodeImage : 
[2022/08/31 10:44:23] ppocr INFO:                 channel_first : False
[2022/08/31 10:44:23] ppocr INFO:                 img_mode : BGR
[2022/08/31 10:44:23] ppocr INFO:             RecConAug : 
[2022/08/31 10:44:23] ppocr INFO:                 ext_data_num : 2
[2022/08/31 10:44:23] ppocr INFO:                 image_shape : [48, 640, 3]
[2022/08/31 10:44:23] ppocr INFO:                 prob : 0.5
[2022/08/31 10:44:23] ppocr INFO:             RecAug : None
[2022/08/31 10:44:23] ppocr INFO:             MultiLabelEncode : None
[2022/08/31 10:44:23] ppocr INFO:             RecResizeImg : 
[2022/08/31 10:44:23] ppocr INFO:                 image_shape : **[3, 48, 640]**
[2022/08/31 10:44:23] ppocr INFO:             KeepKeys : 
[2022/08/31 10:44:23] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2022/08/31 10:44:23] ppocr INFO:     loader : 
[2022/08/31 10:44:23] ppocr INFO:         batch_size_per_card : 128
[2022/08/31 10:44:23] ppocr INFO:         drop_last : True
[2022/08/31 10:44:23] ppocr INFO:         num_workers : 4
[2022/08/31 10:44:23] ppocr INFO:         shuffle : True
[2022/08/31 10:44:23] ppocr INFO: profiler_options : None
[2022/08/31 10:44:23] ppocr INFO: train with paddle 2.3.0 and device Place(cpu)
[2022/08/31 10:44:23] ppocr INFO: Initialize indexs of datasets:./train_data/rec/process_train.txt
[2022/08/31 10:44:23] ppocr INFO: Initialize indexs of datasets:./train_data/rec/process_val.txt
[2022/08/31 10:44:23] ppocr INFO: train dataloader has 46 iters
[2022/08/31 10:44:23] ppocr INFO: valid dataloader has 16 iters
[2022/08/31 10:44:24] ppocr INFO: load pretrain successful from /home/cly/Downloads/ch_PP-OCRv3_rec_train/best_accuracy
[2022/08/31 10:44:24] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
[2022/08/31 11:07:35] ppocr INFO: epoch: [1/50], global_step: 10, lr: 0.000010, acc: 0.527344, norm_edit_dis: 0.866522, Teacher_acc: 0.535156, Teacher_norm_edit_dis: 0.878785, dml_ctc_0: 3.117863, loss: 24.215019, dml_sar_0: 4.324786, loss_distance_l2_Student_Teacher_0: 0.019566, loss_ctc_Student_0: 5.932144, loss_ctc_Teacher_1: 5.397104, loss_sar_Student_0: 2.872767, loss_sar_Teacher_1: 2.837010, avg_reader_cost: 0.24627 s, avg_batch_cost: 139.07039 s, avg_samples: 128.0, ips: 0.92040 samples/s, eta: 3 days, 16:27:51
[2022/08/31 11:28:58] ppocr INFO: epoch: [1/50], global_step: 20, lr: 0.000021, acc: 0.546875, norm_edit_dis: 0.875692, Teacher_acc: 0.546875, Teacher_norm_edit_dis: 0.881271, dml_ctc_0: 2.715768, loss: 23.720713, dml_sar_0: 3.955844, loss_distance_l2_Student_Teacher_0: 0.018937, loss_ctc_Student_0: 5.806084, loss_ctc_Teacher_1: 5.212008, loss_sar_Student_0: 2.727805, loss_sar_Teacher_1: 2.663478, avg_reader_cost: 0.00034 s, avg_batch_cost: 128.36385 s, avg_samples: 128.0, ips: 0.99717 samples/s, eta: 3 days, 12:41:15
[2022/08/31 11:50:21] ppocr INFO: epoch: [1/50], global_step: 30, lr: 0.000042, acc: 0.554687, norm_edit_dis: 0.882203, Teacher_acc: 0.562500, Teacher_norm_edit_dis: 0.885838, dml_ctc_0: 2.141121, loss: 20.600224, dml_sar_0: 3.616118, loss_distance_l2_Student_Teacher_0: 0.018202, loss_ctc_Student_0: 4.697291, loss_ctc_Teacher_1: 4.848706, loss_sar_Student_0: 2.458442, loss_sar_Teacher_1: 2.493194, avg_reader_cost: 0.00034 s, avg_batch_cost: 128.30656 s, avg_samples: 128.0, ips: 0.99761 samples/s, eta: 3 days, 11:10:43
[2022/08/31 12:11:43] ppocr INFO: epoch: [1/50], global_step: 40, lr: 0.000064, acc: 0.582031, norm_edit_dis: 0.897155, Teacher_acc: 0.578125, Teacher_norm_edit_dis: 0.897683, dml_ctc_0: 1.666832, loss: 18.027260, dml_sar_0: 3.205089, loss_distance_l2_Student_Teacher_0: 0.017313, loss_ctc_Student_0: 4.069637, loss_ctc_Teacher_1: 4.095708, loss_sar_Student_0: 2.296335, loss_sar_Teacher_1: 2.344547, avg_reader_cost: 0.00033 s, avg_batch_cost: 128.19107 s, avg_samples: 128.0, ips: 0.99851 samples/s, eta: 3 days, 10:13:41
[2022/08/31 12:24:33] ppocr INFO: epoch: [1/50], global_step: 46, lr: 0.000077, acc: 0.605469, norm_edit_dis: 0.917260, Teacher_acc: 0.601562, Teacher_norm_edit_dis: 0.910741, dml_ctc_0: 1.387131, loss: 15.688611, dml_sar_0: 3.041705, loss_distance_l2_Student_Teacher_0: 0.016794, loss_ctc_Student_0: 3.403398, loss_ctc_Teacher_1: 3.465828, loss_sar_Student_0: 2.175888, loss_sar_Teacher_1: 2.241463, avg_reader_cost: 0.00014 s, avg_batch_cost: 76.99808 s, avg_samples: 76.8, ips: 0.99743 samples/s, eta: 3 days, 9:47:35
[2022/08/31 12:24:35] ppocr INFO: save model in ./output/rec_ppocr_v3_distillation/latest
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 632, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 10221

Exception ignored in: <bound method _DataLoaderIterMultiProcess.__del__ of <paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess object at 0x7fa2da2fcfd0>>
Traceback (most recent call last):
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 708, in __del__
    self._try_shutdown_all()
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 513, in _try_shutdown_all
    w.join(timeout)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 10222) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/home/cly/temp/PaddleOCR/tools/program.py", line 297, in train
    preds = model(images, data=batch[1:])
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/temp/PaddleOCR/ppocr/modeling/architectures/distillation_model.py", line 59, in forward
    result_dict[model_name] = self.model_list[idx](x, data)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/temp/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/temp/PaddleOCR/ppocr/modeling/backbones/rec_mv1_enhance.py", line 224, in forward
    y = self.block_list(y)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/temp/PaddleOCR/ppocr/modeling/backbones/rec_mv1_enhance.py", line 98, in forward
    y = self._depthwise_conv(inputs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/temp/PaddleOCR/ppocr/modeling/backbones/rec_mv1_enhance.py", line 64, in forward
    y = self._batch_norm(y)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 1375, in forward
    batch_norm_out, act=self._act, use_mkldnn=self._use_mkldnn)
  File "<decorator-gen-29>", line 2, in _append_activation_in_dygraph
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/dygraph_utils.py", line 45, in _append_activation_in_dygraph
    return act_op(input, *attrs)
  File "/home/cly/.local/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 10222) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

**Comment by littletomatodonkey** [comment]
1. 先把batch_size改小些，num worker修改为0，看下是否能够跑通
2. 如果上面还有问题的话，需要检查下数据标注文件格式是否正确

**Comment by lingyiliu016** [comment]
这里的训练集./train_data/rec/process_val.txt、 ./train_data/rec/process_train.txt是按照如下过程生成的。
1、在windows上运行PPOCRLabel半自动标注工具生成，生成的文件train.txt如下


![微信图片_20220831132640](https://user-images.githubusercontent.com/27277897/187599337-b47e0a23-299e-45fe-a3ef-398be57604cb.jpg)
2、用程序
替换成ubuntu路径
替换程序：
![微信图片_20220831132920](https://user-images.githubusercontent.com/27277897/187599406-ee34ac15-299b-4bc5-b854-9b9e832bdff4.jpg)
3、替换结果为：
![微信图片_20220831133158](https://user-images.githubusercontent.com/27277897/187599625-18c60585-5d6b-4cd6-bf9d-00691534b3f9.jpg)

**Comment by lingyiliu016** [comment]
> 1. 先把batch_size改小些，num worker修改为0，看下是否能够跑通
> 2. 如果上面还有问题的话，需要检查下数据标注文件格式是否正确

我之前运行`python3 tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.use_gpu=false Global.epoch_num=50 Global.pretrained_model=/home/cly/Downloads/ch_PP-OCRv3_rec_train/best_accuracy Optimizer.lr.learning_rate=0.0001 Train.dataset.data_dir=./train_data/rec/train/ Train.dataset.label_file_list=./train_data/rec/process_train.txt Eval.dataset.data_dir=./train_data/rec/val/ Eval.dataset.label_file_list=./train_data/rec/process_val.txt`，但是没有改动ch_PP-OCRv3_rec_distillation.yml文件中的Train.dataset.transforms.RecResizeImg.image_shape、Eval.dataset.transforms.RecResizeImg.image_shape的时候（原始是[3, 48, 320]）是不报错的。
但是因为我这个场景需要[3, 48, 640],所以我分别修改了文件ch_PP-OCRv3_rec_distillation.yml中的Train.dataset.transforms.RecResizeImg.image_shape、Eval.dataset.transforms.RecResizeImg.image_shape为[3, 48, 640]，具体如下：
![微信图片_20220831134032](https://user-images.githubusercontent.com/27277897/187600937-e5c7d8f8-3e76-455a-b9b7-860b5a1830d8.jpg)

然后运行一段时间，就出现了上述的错误。
想问一下，这是否就可以断定需要将batch_size、num_worker改小一些？

**Comment by lingyiliu016** [comment]
> > 1. 先把batch_size改小些，num worker修改为0，看下是否能够跑通
> > 2. 如果上面还有问题的话，需要检查下数据标注文件格式是否正确
> 
> 我之前运行`python3 tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.use_gpu=false Global.epoch_num=50 Global.pretrained_model=/home/cly/Downloads/ch_PP-OCRv3_rec_train/best_accuracy Optimizer.lr.learning_rate=0.0001 Train.dataset.data_dir=./train_data/rec/train/ Train.dataset.label_file_list=./train_data/rec/process_train.txt Eval.dataset.data_dir=./train_data/rec/val/ Eval.dataset.label_file_list=./train_data/rec/process_val.txt`，但是没有改动ch_PP-OCRv3_rec_distillation.yml文件中的Train.dataset.transforms.RecResizeImg.image_shape、Eval.dataset.transforms.RecResizeImg.image_shape的时候（原始是[3, 48, 320]）是不报错的。 但是因为我这个场景需要[3, 48, 640],所以我分别修改了文件ch_PP-OCRv3_rec_distillation.yml中的Train.dataset.transforms.RecResizeImg.image_shape、Eval.dataset.transforms.RecResizeImg.image_shape为[3, 48, 640]，具体如下： ![微信图片_20220831134032](https://user-images.githubusercontent.com/27277897/187600937-e5c7d8f8-3e76-455a-b9b7-860b5a1830d8.jpg)
> 
> 然后运行一段时间，就出现了上述的错误。 想问一下，这是否就可以断定需要将batch_size、num_worker改小一些？

这应该可以说明，训练集./train_data/rec/process_val.txt、 ./train_data/rec/process_train.txt格式、内容都符合，抛出错误是因为自己的ubuntu主机内存小导致的？
