### ISSUE TITLE
RuntimeError: Can't load weights for 'vi-layoutxlm-base-uncased'.

### ISSUE THREAD

**Issue by geekplusaa** [PaddlePaddle/PaddleOCR#7434]
python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
···
[2022/08/31 13:57:33] ppocr INFO: Architecture : 
[2022/08/31 13:57:33] ppocr INFO:     Backbone : 
[2022/08/31 13:57:33] ppocr INFO:         checkpoints : None
[2022/08/31 13:57:33] ppocr INFO:         mode : vi
[2022/08/31 13:57:33] ppocr INFO:         name : LayoutXLMForSer
[2022/08/31 13:57:33] ppocr INFO:         num_classes : 2
[2022/08/31 13:57:33] ppocr INFO:         pretrained : True
[2022/08/31 13:57:33] ppocr INFO:     Transform : None
[2022/08/31 13:57:33] ppocr INFO:     algorithm : LayoutXLM
[2022/08/31 13:57:33] ppocr INFO:     model_type : kie
[2022/08/31 13:57:33] ppocr INFO: Eval : 
[2022/08/31 13:57:33] ppocr INFO:     dataset : 
[2022/08/31 13:57:33] ppocr INFO:         data_dir : data/idcard/kie
[2022/08/31 13:57:33] ppocr INFO:         label_file_list : ['data/idcard/kie/val.json']
[2022/08/31 13:57:33] ppocr INFO:         name : SimpleDataSet
[2022/08/31 13:57:33] ppocr INFO:         transforms : 
[2022/08/31 13:57:33] ppocr INFO:             DecodeImage : 
[2022/08/31 13:57:33] ppocr INFO:                 channel_first : False
[2022/08/31 13:57:33] ppocr INFO:                 img_mode : RGB
[2022/08/31 13:57:33] ppocr INFO:             VQATokenLabelEncode : 
[2022/08/31 13:57:33] ppocr INFO:                 algorithm : LayoutXLM
[2022/08/31 13:57:33] ppocr INFO:                 class_path : data/idcard/kie/class_list.txt
[2022/08/31 13:57:33] ppocr INFO:                 contains_re : False
[2022/08/31 13:57:33] ppocr INFO:                 order_method : tb-yx
[2022/08/31 13:57:33] ppocr INFO:                 use_textline_bbox_info : True
[2022/08/31 13:57:33] ppocr INFO:             VQATokenPad : 
[2022/08/31 13:57:33] ppocr INFO:                 max_seq_len : 512
[2022/08/31 13:57:33] ppocr INFO:                 return_attention_mask : True
[2022/08/31 13:57:33] ppocr INFO:             VQASerTokenChunk : 
[2022/08/31 13:57:33] ppocr INFO:                 max_seq_len : 512
[2022/08/31 13:57:33] ppocr INFO:             Resize : 
[2022/08/31 13:57:33] ppocr INFO:                 size : [224, 224]
[2022/08/31 13:57:33] ppocr INFO:             NormalizeImage : 
[2022/08/31 13:57:33] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2022/08/31 13:57:33] ppocr INFO:                 order : hwc
[2022/08/31 13:57:33] ppocr INFO:                 scale : 1
[2022/08/31 13:57:33] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2022/08/31 13:57:33] ppocr INFO:             ToCHWImage : None
[2022/08/31 13:57:33] ppocr INFO:             KeepKeys : 
[2022/08/31 13:57:33] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2022/08/31 13:57:33] ppocr INFO:     loader : 
[2022/08/31 13:57:33] ppocr INFO:         batch_size_per_card : 1
[2022/08/31 13:57:33] ppocr INFO:         drop_last : False
[2022/08/31 13:57:33] ppocr INFO:         num_workers : 4
[2022/08/31 13:57:33] ppocr INFO:         shuffle : False
[2022/08/31 13:57:33] ppocr INFO: Global : 
[2022/08/31 13:57:33] ppocr INFO:     cal_metric_during_train : False
[2022/08/31 13:57:33] ppocr INFO:     distributed : False
[2022/08/31 13:57:33] ppocr INFO:     epoch_num : 200
[2022/08/31 13:57:33] ppocr INFO:     eval_batch_step : [0, 19]
[2022/08/31 13:57:33] ppocr INFO:     infer_img : ppstructure/docs/kie/input/zh_val_42.jpg
[2022/08/31 13:57:33] ppocr INFO:     kie_det_model_dir : None
[2022/08/31 13:57:33] ppocr INFO:     kie_rec_model_dir : None
[2022/08/31 13:57:33] ppocr INFO:     log_smooth_window : 10
[2022/08/31 13:57:33] ppocr INFO:     print_batch_step : 10
[2022/08/31 13:57:33] ppocr INFO:     save_epoch_step : 2000
[2022/08/31 13:57:33] ppocr INFO:     save_inference_dir : None
[2022/08/31 13:57:33] ppocr INFO:     save_model_dir : ./output/ser_vi_layoutxlm_xfund_zh
[2022/08/31 13:57:33] ppocr INFO:     save_res_path : ./output/ser/xfund_zh/res
[2022/08/31 13:57:33] ppocr INFO:     seed : 2022
[2022/08/31 13:57:33] ppocr INFO:     use_gpu : False
[2022/08/31 13:57:33] ppocr INFO:     use_visualdl : True
[2022/08/31 13:57:33] ppocr INFO: Loss : 
[2022/08/31 13:57:33] ppocr INFO:     key : backbone_out
[2022/08/31 13:57:33] ppocr INFO:     name : VQASerTokenLayoutLMLoss
[2022/08/31 13:57:33] ppocr INFO:     num_classes : 2
[2022/08/31 13:57:33] ppocr INFO: Metric : 
[2022/08/31 13:57:33] ppocr INFO:     main_indicator : hmean
[2022/08/31 13:57:33] ppocr INFO:     name : VQASerTokenMetric
[2022/08/31 13:57:33] ppocr INFO: Optimizer : 
[2022/08/31 13:57:33] ppocr INFO:     beta1 : 0.9
[2022/08/31 13:57:33] ppocr INFO:     beta2 : 0.999
[2022/08/31 13:57:33] ppocr INFO:     lr : 
[2022/08/31 13:57:33] ppocr INFO:         epochs : 200
[2022/08/31 13:57:33] ppocr INFO:         learning_rate : 5e-05
[2022/08/31 13:57:33] ppocr INFO:         name : Linear
[2022/08/31 13:57:33] ppocr INFO:         warmup_epoch : 2
[2022/08/31 13:57:33] ppocr INFO:     name : AdamW
[2022/08/31 13:57:33] ppocr INFO:     regularizer : 
[2022/08/31 13:57:33] ppocr INFO:         factor : 0.0
[2022/08/31 13:57:33] ppocr INFO:         name : L2
[2022/08/31 13:57:33] ppocr INFO: PostProcess : 
[2022/08/31 13:57:33] ppocr INFO:     class_path : data/idcard/kie/class_list.txt
[2022/08/31 13:57:33] ppocr INFO:     name : VQASerTokenLayoutLMPostProcess
[2022/08/31 13:57:33] ppocr INFO: Train : 
[2022/08/31 13:57:33] ppocr INFO:     dataset : 
[2022/08/31 13:57:33] ppocr INFO:         data_dir : data/idcard/kie
[2022/08/31 13:57:33] ppocr INFO:         label_file_list : ['data/idcard/kie/train.json']
[2022/08/31 13:57:33] ppocr INFO:         name : SimpleDataSet
[2022/08/31 13:57:33] ppocr INFO:         ratio_list : [1.0]
[2022/08/31 13:57:33] ppocr INFO:         transforms : 
[2022/08/31 13:57:33] ppocr INFO:             DecodeImage : 
[2022/08/31 13:57:33] ppocr INFO:                 channel_first : False
[2022/08/31 13:57:33] ppocr INFO:                 img_mode : RGB
[2022/08/31 13:57:33] ppocr INFO:             VQATokenLabelEncode : 
[2022/08/31 13:57:33] ppocr INFO:                 algorithm : LayoutXLM
[2022/08/31 13:57:33] ppocr INFO:                 class_path : data/idcard/kie/class_list.txt
[2022/08/31 13:57:33] ppocr INFO:                 contains_re : False
[2022/08/31 13:57:33] ppocr INFO:                 order_method : tb-yx
[2022/08/31 13:57:33] ppocr INFO:                 use_textline_bbox_info : True
[2022/08/31 13:57:33] ppocr INFO:             VQATokenPad : 
[2022/08/31 13:57:33] ppocr INFO:                 max_seq_len : 512
[2022/08/31 13:57:33] ppocr INFO:                 return_attention_mask : True
[2022/08/31 13:57:33] ppocr INFO:             VQASerTokenChunk : 
[2022/08/31 13:57:33] ppocr INFO:                 max_seq_len : 512
[2022/08/31 13:57:33] ppocr INFO:             Resize : 
[2022/08/31 13:57:33] ppocr INFO:                 size : [224, 224]
[2022/08/31 13:57:33] ppocr INFO:             NormalizeImage : 
[2022/08/31 13:57:33] ppocr INFO:                 mean : [123.675, 116.28, 103.53]
[2022/08/31 13:57:33] ppocr INFO:                 order : hwc
[2022/08/31 13:57:33] ppocr INFO:                 scale : 1
[2022/08/31 13:57:33] ppocr INFO:                 std : [58.395, 57.12, 57.375]
[2022/08/31 13:57:33] ppocr INFO:             ToCHWImage : None
[2022/08/31 13:57:33] ppocr INFO:             KeepKeys : 
[2022/08/31 13:57:33] ppocr INFO:                 keep_keys : ['input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels']
[2022/08/31 13:57:33] ppocr INFO:     loader : 
[2022/08/31 13:57:33] ppocr INFO:         batch_size_per_card : 4
[2022/08/31 13:57:33] ppocr INFO:         drop_last : False
[2022/08/31 13:57:33] ppocr INFO:         num_workers : 4
[2022/08/31 13:57:33] ppocr INFO:         shuffle : True
[2022/08/31 13:57:33] ppocr INFO: profiler_options : None
[2022/08/31 13:57:33] ppocr INFO: train with paddle 2.3.2 and device Place(cpu)
[2022/08/31 13:57:33] ppocr INFO: Initialize indexs of datasets:['data/idcard/kie/train.json']
[2022-08-31 13:57:34,220] [    INFO] - Already cached /home/geekplusa/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2022-08-31 13:57:34,625] [    INFO] - tokenizer config file saved in /home/geekplusa/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2022-08-31 13:57:34,625] [    INFO] - Special tokens file saved in /home/geekplusa/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2022/08/31 13:57:34] ppocr INFO: Initialize indexs of datasets:['data/idcard/kie/val.json']
[2022-08-31 13:57:34,669] [    INFO] - Already cached /home/geekplusa/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2022-08-31 13:57:35,062] [    INFO] - tokenizer config file saved in /home/geekplusa/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2022-08-31 13:57:35,063] [    INFO] - Special tokens file saved in /home/geekplusa/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2022-08-31 13:57:35,064] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased/model_state.pdparams and saved to /home/geekplusa/.paddlenlp/models/vi-layoutxlm-base-uncased
[2022-08-31 13:57:35,064] [    INFO] - Downloading model_state.pdparams from https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased/model_state.pdparams
[2022-08-31 13:57:35,131] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased/model_state.pdparams failed with code 404!
Traceback (most recent call last):
  File "/home/geekplusa/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 260, in from_pretrained
    file_path, default_root)
  File "/home/geekplusa/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/home/geekplusa/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 201, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased/model_state.pdparams failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 121, in main
    model = build_model(config['Architecture'])
  File "/home/geekplusa/ai/projects/github/paddle/paddleocr/PaddleOCR/ppocr/modeling/architectures/__init__.py", line 30, in build_model
    arch = BaseModel(config)
  File "/home/geekplusa/ai/projects/github/paddle/paddleocr/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 55, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/geekplusa/ai/projects/github/paddle/paddleocr/PaddleOCR/ppocr/modeling/backbones/__init__.py", line 71, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/geekplusa/ai/projects/github/paddle/paddleocr/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 156, in __init__
    num_classes=num_classes)
  File "/home/geekplusa/ai/projects/github/paddle/paddleocr/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 61, in __init__
    pretrained_model_name)
  File "/home/geekplusa/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 264, in from_pretrained
    f"Can't load weights for '{pretrained_model_name_or_path}'.\n"
RuntimeError: Can't load weights for 'vi-layoutxlm-base-uncased'.
Please make sure that 'vi-layoutxlm-base-uncased' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).

···

**Comment by littletomatodonkey** [comment]
你好，可以安装这个nlp的whl包哈：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

**Comment by py703703** [comment]
我试了这个方法，在ai studio 中，如何卸载原来的paddlenlp包呢，因为需要权限。

**Comment by py703703** [comment]
兄弟，试过了，还是不行，需要权限
 pip install -U https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting paddlenlp==2.3.0.dev0
  Downloading https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 9.9 MB/s eta 0:00:00
Requirement already satisfied: jieba in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (0.42.1)
Requirement already satisfied: paddle2onnx in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (1.0.0)
Requirement already satisfied: protobuf<=3.20.0,>=3.1.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (3.20.0)
Requirement already satisfied: dill<0.3.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (0.3.3)
Requirement already satisfied: sentencepiece in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (0.1.96)
Requirement already satisfied: multiprocess<=0.70.12.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (0.70.11.1)
Requirement already satisfied: colorama in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (0.4.4)
Requirement already satisfied: datasets>=2.0.0 in ./.data/webide/pip/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (2.4.0)
Requirement already satisfied: tqdm in ./.data/webide/pip/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (4.64.1)
Requirement already satisfied: paddlefsl in ./.data/webide/pip/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (1.1.0)
Requirement already satisfied: seqeval in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (1.2.2)
Requirement already satisfied: colorlog in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp==2.3.0.dev0) (4.1.0)
Requirement already satisfied: fsspec[http]>=2021.11.1 in ./.data/webide/pip/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2022.8.2)
Requirement already satisfied: responses<0.19 in ./.data/webide/pip/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (0.18.0)
Requirement already satisfied: packaging in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (21.3)
Requirement already satisfied: pyarrow>=6.0.0 in ./.data/webide/pip/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (9.0.0)
Collecting xxhash
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ef/ac/0eb796cf052c392f1ae586452c89ca66164f7d4f655b039ca3d06e2291af/xxhash-3.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 714.9 kB/s eta 0:00:00
Requirement already satisfied: requests>=2.19.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2.24.0)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.1.0 in ./.data/webide/pip/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (0.9.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.19.5)
Requirement already satisfied: importlib-metadata in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (4.2.0)
Requirement already satisfied: aiohttp in ./.data/webide/pip/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (3.8.1)
Requirement already satisfied: pandas in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.1.5)
Requirement already satisfied: scikit-learn>=0.21.3 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from seqeval->paddlenlp==2.3.0.dev0) (0.24.2)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (22.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.8.1)
Requirement already satisfied: typing-extensions>=3.7.4 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (4.3.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2.1.1)
Requirement already satisfied: asynctest==0.13.0 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (0.13.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (6.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in ./.data/webide/pip/lib/python3.7/site-packages (from aiohttp->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.2.0)
Requirement already satisfied: filelock in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (3.0.12)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (5.1.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from packaging->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.19.0->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2019.9.11)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.19.0->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.19.0->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.25.6)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from requests>=2.19.0->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (3.0.4)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.0/128.0 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: joblib>=0.11 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp==2.3.0.dev0) (0.14.1)
Requirement already satisfied: scipy>=0.19.1 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp==2.3.0.dev0) (1.6.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from scikit-learn>=0.21.3->seqeval->paddlenlp==2.3.0.dev0) (2.1.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from importlib-metadata->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (3.8.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from pandas->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from pandas->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (2019.3)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->datasets>=2.0.0->paddlenlp==2.3.0.dev0) (1.16.0)
Installing collected packages: xxhash, urllib3, paddlenlp
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.6
    Uninstalling urllib3-1.25.6:
      Successfully uninstalled urllib3-1.25.6
  Attempting uninstall: paddlenlp
    Found existing installation: paddlenlp 2.1.1
    Uninstalling paddlenlp-2.1.1:
ERROR: Could not install packages due to an OSError: [Errno 13] 权限不够: 'METADATA'
Consider using the `--user` option or check the permissions.

**Comment by py703703** [comment]
感谢，问题已解决了，在命令后面加了一个 --user就行了！
