### ISSUE TITLE
SER模型训练总是报相同的错误 OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleOCR#7458]
每次训练到30次左右的时候都会报错误：OSError: [Errno 12] Cannot allocate memory

[2022/09/01 14:33:33] ppocr INFO: best metric, hmean: 0.9957094244710756, precision: 0.9951940850277264, recall: 0.9962252979054104, fps: 22.35040101606416, best_epoch: 27
[2022/09/01 14:33:42] ppocr INFO: epoch: [27/200], global_step: 16210, lr: 0.000044, loss: 0.004817, avg_reader_cost: 0.00039 s, avg_batch_cost: 0.63360 s, avg_samples: 8.0, ips: 12.62630 samples/s, eta: 19:14:39
[2022/09/01 14:33:51] ppocr INFO: epoch: [27/200], global_step: 16220, lr: 0.000044, loss: 0.000738, avg_reader_cost: 0.00033 s, avg_batch_cost: 0.62623 s, avg_samples: 8.0, ips: 12.77483 samples/s, eta: 19:14:31
[2022/09/01 14:34:01] ppocr INFO: epoch: [27/200], global_step: 16230, lr: 0.000044, loss: 0.003507, avg_reader_cost: 0.00029 s, avg_batch_cost: 0.64096 s, avg_samples: 8.0, ips: 12.48124 samples/s, eta: 19:14:23
[2022/09/01 14:34:11] ppocr INFO: epoch: [27/200], global_step: 16240, lr: 0.000044, loss: 0.006015, avg_reader_cost: 0.00038 s, avg_batch_cost: 0.63097 s, avg_samples: 8.0, ips: 12.67884 samples/s, eta: 19:14:15
[2022/09/01 14:34:20] ppocr INFO: epoch: [27/200], global_step: 16250, lr: 0.000044, loss: 0.005352, avg_reader_cost: 0.00028 s, avg_batch_cost: 0.62918 s, avg_samples: 8.0, ips: 12.71499 samples/s, eta: 19:14:07
[2022/09/01 14:34:29] ppocr INFO: epoch: [27/200], global_step: 16260, lr: 0.000044, loss: 0.003126, avg_reader_cost: 0.00030 s, avg_batch_cost: 0.62761 s, avg_samples: 8.0, ips: 12.74684 samples/s, eta: 19:13:59
[2022/09/01 14:34:39] ppocr INFO: epoch: [27/200], global_step: 16270, lr: 0.000044, loss: 0.007211, avg_reader_cost: 0.00028 s, avg_batch_cost: 0.62816 s, avg_samples: 8.0, ips: 12.73552 samples/s, eta: 19:13:50
[2022/09/01 14:34:48] ppocr INFO: epoch: [27/200], global_step: 16280, lr: 0.000044, loss: 0.003284, avg_reader_cost: 0.00027 s, avg_batch_cost: 0.62766 s, avg_samples: 8.0, ips: 12.74570 samples/s, eta: 19:13:42
[2022/09/01 14:34:58] ppocr INFO: epoch: [27/200], global_step: 16290, lr: 0.000044, loss: 0.007100, avg_reader_cost: 0.00026 s, avg_batch_cost: 0.62912 s, avg_samples: 8.0, ips: 12.71610 samples/s, eta: 19:13:34
[2022/09/01 14:35:07] ppocr INFO: epoch: [27/200], global_step: 16300, lr: 0.000044, loss: 0.004817, avg_reader_cost: 0.00027 s, avg_batch_cost: 0.62784 s, avg_samples: 8.0, ips: 12.74204 samples/s, eta: 19:13:25

eval model::   0%|          | 0/290 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/data/SourceCodes/PaddleOCR/tools/program.py", line 390, in train
    amp_custom_black_list=amp_custom_black_list)
  File "/data/SourceCodes/PaddleOCR/tools/program.py", line 497, in eval
    for idx, batch in enumerate(valid_dataloader):
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/reader.py", line 434, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 355, in __init__
    self._init_workers()
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 388, in _init_workers
    worker.start()
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f3cdaa5a320>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 675, in __del__
    self._try_shutdown_all()
  File "/home/ubuntu/anaconda3/envs/py_3.7_ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 474, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
eval model::   0%|          | 0/290 [00:00<?, ?it/s]

**Comment by littletomatodonkey** [comment]
num worker修改为0看下呢？同时把batch size调小点

**Comment by sattychen** [comment]
内存是有可能慢慢增加的，代码有时候内存释放不及时或者有内存泄漏
