### ISSUE TITLE
大佬们,有知道这个报错怎么处理吗,我训练识别模型的时候报错的, AssertionError: neck only support ['FPN', 'FCEFPN', 'LKPAN', 'DBFPN', 'RSEFPN', 'EASTFPN', 'SASTFPN', 'SequenceEncoder', 'PGFPN', 'TableFPN', 'PRENFPN', 'CSPPAN']

### ISSUE THREAD

**Issue by HutaoAI** [PaddlePaddle/PaddleOCR#7471]
A:\anaconda\envs\paddle\python.exe B:/PaddleOCR-release-2.6/tools/train.py
[2022/09/03 11:17:51] ppocr INFO: Architecture : 
[2022/09/03 11:17:51] ppocr INFO:     Backbone : 
[2022/09/03 11:17:51] ppocr INFO:         layers : 34
[2022/09/03 11:17:51] ppocr INFO:         name : ResNet
[2022/09/03 11:17:51] ppocr INFO:     Head : 
[2022/09/03 11:17:51] ppocr INFO:         fc_decay : 0
[2022/09/03 11:17:51] ppocr INFO:         name : CTCHead
[2022/09/03 11:17:51] ppocr INFO:     Neck : 
[2022/09/03 11:17:51] ppocr INFO:         encoder_type : rnn
[2022/09/03 11:17:51] ppocr INFO:         hidden_size : 256
[2022/09/03 11:17:51] ppocr INFO:         name : LMDBDataSet
[2022/09/03 11:17:51] ppocr INFO:     Transform : None
[2022/09/03 11:17:51] ppocr INFO:     algorithm : CRNN
[2022/09/03 11:17:51] ppocr INFO:     model_type : rec
[2022/09/03 11:17:51] ppocr INFO: Eval : 
[2022/09/03 11:17:51] ppocr INFO:     dataset : 
[2022/09/03 11:17:51] ppocr INFO:         data_dir : B:/PaddleOCR-release-2.6/train_data/
[2022/09/03 11:17:51] ppocr INFO:         label_file_list : ['B:/PaddleOCR-release-2.6/train_data/Label.txt']
[2022/09/03 11:17:51] ppocr INFO:         name : SimpleDataSet
[2022/09/03 11:17:51] ppocr INFO:         transforms : 
[2022/09/03 11:17:51] ppocr INFO:             DecodeImage : 
[2022/09/03 11:17:51] ppocr INFO:                 channel_first : False
[2022/09/03 11:17:51] ppocr INFO:                 img_mode : BGR
[2022/09/03 11:17:51] ppocr INFO:             CTCLabelEncode : None
[2022/09/03 11:17:51] ppocr INFO:             RecResizeImg : 
[2022/09/03 11:17:51] ppocr INFO:                 image_shape : [3, 32, 100]
[2022/09/03 11:17:51] ppocr INFO:             KeepKeys : 
[2022/09/03 11:17:51] ppocr INFO:                 keep_keys : ['image', 'label', 'length']
[2022/09/03 11:17:51] ppocr INFO:     loader : 
[2022/09/03 11:17:51] ppocr INFO:         batch_size_per_card : 68
[2022/09/03 11:17:51] ppocr INFO:         drop_last : False
[2022/09/03 11:17:51] ppocr INFO:         num_workers : 6
[2022/09/03 11:17:51] ppocr INFO:         shuffle : False
[2022/09/03 11:17:51] ppocr INFO: Global : 
[2022/09/03 11:17:51] ppocr INFO:     cal_metric_during_train : True
[2022/09/03 11:17:51] ppocr INFO:     character_dict_path : ../ppocr/utils/dict90.txt
[2022/09/03 11:17:51] ppocr INFO:     checkpoints : None
[2022/09/03 11:17:51] ppocr INFO:     distributed : False
[2022/09/03 11:17:51] ppocr INFO:     epoch_num : 200
[2022/09/03 11:17:51] ppocr INFO:     eval_batch_step : [0, 2000]
[2022/09/03 11:17:51] ppocr INFO:     infer_img : doc/imgs_words_en/word_10.png
[2022/09/03 11:17:51] ppocr INFO:     infer_mode : False
[2022/09/03 11:17:51] ppocr INFO:     log_smooth_window : 20
[2022/09/03 11:17:51] ppocr INFO:     max_text_length : 25
[2022/09/03 11:17:51] ppocr INFO:     pretrained_model : ../pretrain_models/rec/ResNet34_vd_pretrained
[2022/09/03 11:17:51] ppocr INFO:     print_batch_step : 10
[2022/09/03 11:17:51] ppocr INFO:     save_epoch_step : 3
[2022/09/03 11:17:51] ppocr INFO:     save_inference_dir : None
[2022/09/03 11:17:51] ppocr INFO:     save_model_dir : ./output/rec/r34_vd_none_bilstm_ctc/
[2022/09/03 11:17:51] ppocr INFO:     save_res_path : ./output/rec/predicts_r34_vd_none_bilstm_ctc.txt
[2022/09/03 11:17:51] ppocr INFO:     use_gpu : True
[2022/09/03 11:17:51] ppocr INFO:     use_space_char : True
[2022/09/03 11:17:51] ppocr INFO:     use_visualdl : False
[2022/09/03 11:17:51] ppocr INFO: Loss : 
[2022/09/03 11:17:51] ppocr INFO:     name : CTCLoss
[2022/09/03 11:17:51] ppocr INFO: Metric : 
[2022/09/03 11:17:51] ppocr INFO:     main_indicator : acc
[2022/09/03 11:17:51] ppocr INFO:     name : RecMetric
[2022/09/03 11:17:51] ppocr INFO: Optimizer : 
[2022/09/03 11:17:51] ppocr INFO:     beta1 : 0.9
[2022/09/03 11:17:51] ppocr INFO:     beta2 : 0.999
[2022/09/03 11:17:51] ppocr INFO:     lr : 
[2022/09/03 11:17:51] ppocr INFO:         learning_rate : 0.0005
[2022/09/03 11:17:51] ppocr INFO:     name : Adam
[2022/09/03 11:17:51] ppocr INFO:     regularizer : 
[2022/09/03 11:17:51] ppocr INFO:         factor : 0
[2022/09/03 11:17:51] ppocr INFO:         name : L2
[2022/09/03 11:17:51] ppocr INFO: PostProcess : 
[2022/09/03 11:17:51] ppocr INFO:     name : CTCLabelDecode
[2022/09/03 11:17:51] ppocr INFO: Train : 
[2022/09/03 11:17:51] ppocr INFO:     dataset : 
[2022/09/03 11:17:51] ppocr INFO:         data_dir : B:/PaddleOCR-release-2.6/train_data/
[2022/09/03 11:17:51] ppocr INFO:         label_file_list : ['B:/PaddleOCR-release-2.6/train_data/Label.txt']
[2022/09/03 11:17:51] ppocr INFO:         name : SimpleDataSet
[2022/09/03 11:17:51] ppocr INFO:         transforms : 
[2022/09/03 11:17:51] ppocr INFO:             DecodeImage : 
[2022/09/03 11:17:51] ppocr INFO:                 channel_first : False
[2022/09/03 11:17:51] ppocr INFO:                 img_mode : BGR
[2022/09/03 11:17:51] ppocr INFO:             CTCLabelEncode : None
[2022/09/03 11:17:51] ppocr INFO:             RecResizeImg : 
[2022/09/03 11:17:51] ppocr INFO:                 image_shape : [3, 32, 100]
[2022/09/03 11:17:51] ppocr INFO:             KeepKeys : 
[2022/09/03 11:17:51] ppocr INFO:                 keep_keys : ['image', 'label', 'length']
[2022/09/03 11:17:51] ppocr INFO:     loader : 
[2022/09/03 11:17:51] ppocr INFO:         batch_size_per_card : 68
[2022/09/03 11:17:51] ppocr INFO:         drop_last : True
[2022/09/03 11:17:51] ppocr INFO:         num_workers : 6
[2022/09/03 11:17:51] ppocr INFO:         shuffle : True
[2022/09/03 11:17:51] ppocr INFO: profiler_options : None
[2022/09/03 11:17:51] ppocr INFO: train with paddle 2.3.2 and device Place(gpu:0)
[2022/09/03 11:17:51] ppocr INFO: Initialize indexs of datasets:['B:/PaddleOCR-release-2.6/train_data/Label.txt']
[2022/09/03 11:17:51] ppocr INFO: Initialize indexs of datasets:['B:/PaddleOCR-release-2.6/train_data/Label.txt']
W0903 11:17:51.965698  9872 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0903 11:17:51.972682  9872 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "B:\PaddleOCR-release-2.6\tools\train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "B:\PaddleOCR-release-2.6\tools\train.py", line 121, in main
    model = build_model(config['Architecture'])
  File "B:\PaddleOCR-release-2.6\ppocr\modeling\architectures\__init__.py", line 30, in build_model
    arch = BaseModel(config)
  File "B:\PaddleOCR-release-2.6\ppocr\modeling\architectures\base_model.py", line 67, in __init__
    self.neck = build_neck(config['Neck'])
  File "B:\PaddleOCR-release-2.6\ppocr\modeling\necks\__init__.py", line 35, in build_neck
    assert module_name in support_dict, Exception('neck only support {}'.format(
AssertionError: neck only support ['FPN', 'FCEFPN', 'LKPAN', 'DBFPN', 'RSEFPN', 'EASTFPN', 'SASTFPN', 'SequenceEncoder', 'PGFPN', 'TableFPN', 'PRENFPN', 'CSPPAN']

Process finished with exit code 1

**Comment by andyjpaddle** [comment]
配置里面neck部分关键字错误，看你写的是`LMDBDataSet `，这个是数据集的格式
