### ISSUE TITLE
PPOCRLabelv2 表格识别报错闪退

### ISSUE THREAD

**Issue by chx-xuan** [PaddlePaddle/PaddleOCR#7488]
您好，PPOCRLabelv2 表格识别报错闪退，自从更新完paddle，一点击表格识别，就出现 please change manually，闪退，找不到原因。

unicodeFilePath is C:\Users\Administrator\Desktop\tableimg\ppstrcture_tests\emobile_2022-08-25_11-56-13.png
unicodeFilePath is C:\Users\Administrator\Desktop\tableimg\ppstrcture_tests\emobile_2022-08-25_15-32-24.png
Traceback (most recent call last):
  File "D:\Anaconda3\envs\paddle\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2371, in TableRecognition
    to_excel('', excel_path) # create an empty excel
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddleocr\ppstructure\table\predict_table.py", line 170, in to_excel
    tablepyxl.document_to_xl(html_table, excel_path)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\PaddleOCR\ppstructure\table\tablepyxl\tablepyxl.py", line 101, in document_to_xl
    wb = document_to_workbook(doc, base_url=base_url)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\PaddleOCR\ppstructure\table\tablepyxl\tablepyxl.py", line 87, in document_to_workbook
    inline_styles_doc = Premailer(doc, base_url=base_url, remove_classes=False).transform()
  File "D:\Anaconda3\envs\paddle\lib\site-packages\premailer\premailer.py", line 353, in transform
    tree = etree.fromstring(stripped, parser).getroottree()
AttributeError: 'NoneType' object has no attribute 'getroottree'

**Comment by WenmuZhou** [comment]
我们正在修复中

**Comment by chx-xuan** [comment]
> 建议用python PPOCRLabel.py --lang ch，脚本运行的方式启动，若出现import to_excel调取错误，可将错误位置处2288行from paddleocr import to_excel，修改为from paddleocr.ppstructure.table.predict_table import to_excel，即可解决

您好，感谢您的答复，试过了，还是不行，不是import to_excel调取错误，我用ppocr2.5版本的已解决上述问题。

**Comment by WenmuZhou** [comment]
今天刚刚发布修复版，已经解决了，需要更新paddleocr和ppocrlabel都到最新版

**Comment by TasneemVKhan** [comment]
I have the same error. How was this issue solved?

**Comment by rexzhengzhihong** [comment]
没修复吧。我还是报这个错
