### ISSUE TITLE
表格识别模型在xpu跑报错

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/PaddleOCR#7491]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS
- 版本号/Version：Paddle：0.0.0   PaddleOCR：2.6  问题相关组件/Related components：
- 运行指令/Command Code： 
```bash
cd ppstructure
python table/predict_table.py --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer --image_dir=./docs/table/table.jpg --det_model_dir=inference/ch_PP-OCRv3_det_infer --rec_model_dir=inference/ch_PP-OCRv3_rec_infer --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt --output=./table_output --use_xpu=True
```
- 完整报错/Complete Error Message：
```bash
     File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpoao4pdr5.py", line 93, in forward
      final_name, x))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/ssd1/zhoujun20/table/ch/pr/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward
      x = self.head(x, targets=data)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpkf42zlih.py", line 96, in forward
      structure_preds, structure_step)))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpkf42zlih.py", line 87, in false_fn_17
      structure_step, loc_step, fea, structure_preds, hidden])
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
      output_vars = body(*loop_vars)
    File "/ssd1/zhoujun20/table/ch/pr/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 232, in forward
      hidden)
    File "/ssd1/zhoujun20/table/ch/pr/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 250, in _decode
      emb_feature = self.emb(pre_chars)
    File "/ssd1/zhoujun20/table/ch/pr/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 262, in _char_to_onehot
      input_ont_hot = F.one_hot(input_char, self.num_embeddings)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/input.py", line 115, in one_hot
      stop_gradient=True)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::operators::WhileOp::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
5   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
8   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
9   int const* phi::DenseTensor::data<int>() const
10  phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
11  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():9 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at /workspace/repos/PaddleWhlGen/Paddle/paddle/phi/core/dense_tensor.cc:143)
  [operator < one_hot_v2 > error]
```

**Comment by WenmuZhou** [comment]
看起来是one_hot 不支持
