### ISSUE TITLE
PaddleOCR(use_onnx=True) will try to download wrong model file

### ISSUE THREAD

**Issue by safecat** [PaddlePaddle/PaddleOCR#7534]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：MacOS 12.4
- 版本号/Version：Paddle：2.3.1  PaddleOCR：2.6 问题相关组件/Related components：PaddleOCR python class
- 运行指令/Command Code：
```python
PaddleOCR(use_onnx=True, det_model_dir=os.path.expanduser("~/.paddleocr/onnx/ch_PP-OCRv3_det_infer.onnx"),
          rec_model_dir=os.path.expanduser("~/.paddleocr/onnx/ch_PP-OCRv3_rec_infer.onnx"),
          cls_model_dir=os.path.expanduser("~/.paddleocr/onnx/ch_ppocr_mobile_v2.0_cls_infer.onnx"))
```
- 完整报错/Complete Error Message：
```
download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to ~/.paddleocr/onnx/ch_PP-OCRv3_det_infer.onnx/ch_PP-OCRv3_det_infer.tar
Process SpawnProcess-5:
Traceback (most recent call last):
  ...
  (some framework file)
  ...
  File "..././main.py", line 32, in <module>
    PaddleOCR(use_onnx=True, det_model_dir=os.path.expanduser("~/.paddleocr/onnx/ch_PP-OCRv3_det_infer.onnx"),
  File "[VENV PATH]/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 457, in __init__
    maybe_download(params.det_model_dir, det_url)
  File "[VENV PATH]/lib/python3.9/site-packages/paddleocr/ppocr/utils/network.py", line 52, in maybe_download
    os.makedirs(model_storage_directory, exist_ok=True)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '~/.paddleocr/onnx/ch_PP-OCRv3_det_infer.onnx'
```

I've already convert paddleocr model into onnx format, but when I tried to use them in PaddleOCR python class, the maybe_download function still try to download paddle model file. I've created a PR and will submit it soon.

**Comment by safecat** [comment]
issue fixed by #7535
