### ISSUE TITLE
Export quant rec model error

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleOCR#7554]
Hello dear paddleocr team 
I get this error when I try to export inference from quant aware trained model (REC SVTR BASE MODEL) 
paddleslim == 2.3.4
paddleocr == 2.6
paddlepaddle-gpu == 2.3.2.post111
Traceback (most recent call last):
  File "deploy/slim/quantization/export_model.py", line 169, in <module>
    main()
  File "deploy/slim/quantization/export_model.py", line 164, in main
    export_single_model(model, arch_config, save_path, logger, quanter)
  File "E:\new\PaddleOCR-release-2.6\tools\export_model.py", line 74, in export_single_model
    shape=[None] + input_shape, dtype="float32"),
TypeError: can only concatenate list (not "QAT") to list

**Comment by littletomatodonkey** [comment]
你好，感觉反馈，可以参考这个pr进行修复：https://github.com/PaddlePaddle/PaddleOCR/pull/7586/files
