### ISSUE TITLE
ValueError: could not broadcast input array from shape如何解决？

### ISSUE THREAD

**Issue by lishijia2740** [PaddlePaddle/PaddleOCR#7567]
Traceback (most recent call last):
  File "tools/infer_kie.py", line 178, in <module>
    main()
  File "tools/infer_kie.py", line 156, in main
    batch = transform(data, ops)
  File "/workspace/HOSTDIR/project/PaddleOCR-release-2.5/ppocr/data/imaug/__init__.py", line 51, in transform
    data = op(data)
  File "/workspace/HOSTDIR/project/PaddleOCR-release-2.5/ppocr/data/imaug/label_ops.py", line 459, in __call__
    return self.list_to_numpy(ann_infos)
  File "/workspace/HOSTDIR/project/PaddleOCR-release-2.5/ppocr/data/imaug/label_ops.py", line 350, in list_to_numpy
    temp_bboxes[:h, :] = bboxes
ValueError: could not broadcast input array from shape (495,4) into shape (300,4)

**Comment by lishijia2740** [comment]
使用kie，train和infer时出现的问题！

**Comment by cookiesyip** [comment]
我也有相同問題
