### ISSUE TITLE
KeyError: 'LinearWarmup_LR' error while custom training with transfer learning from default best_accuracy models

### ISSUE THREAD

**Issue by anidiatm41** [PaddlePaddle/PaddleOCR#7580]
[2022/09/13 15:24:00] ppocr INFO: valid dataloader has 31 iters
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 169, in main
    pre_best_model_dict = load_model(config, model, optimizer,
  File "C:\Users\1619872\Desktop\paddleocr_2\ppocr\utils\save_load.py", line 124, in load_model
    optimizer.set_state_dict(optim_dict)
  File "C:\Users\1619872\AppData\Local\conda\conda\envs\torch\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\1619872\AppData\Local\conda\conda\envs\torch\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\1619872\AppData\Local\conda\conda\envs\torch\lib\site-packages\paddle\fluid\framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\1619872\AppData\Local\conda\conda\envs\torch\lib\site-packages\paddle\optimizer\optimizer.py", line 305, in set_state_dict
    self._learning_rate.set_state_dict(state_dict["LR_Scheduler"])
  File "C:\Users\1619872\AppData\Local\conda\conda\envs\torch\lib\site-packages\paddle\optimizer\lr.py", line 799, in set_state_dict
    self.learning_rate.set_state_dict(state_dict["LinearWarmup_LR"])
**KeyError: 'LinearWarmup_LR'**

**Comment by anidiatm41** [comment]
any idea how to fix the issue?

**Comment by anidiatm41** [comment]
I am using below parameters in yml file:

 **pretrained_model: ./pretrain_models/MobileNetV3_large_x0_5_pretrained
  checkpoints: C:/Users/1619872/Desktop/ch_en2/ch_ppocr_mobile_v2.0_det_train/best_accuracy**

**Comment by anidiatm41** [comment]
@Evezerest
