### ISSUE TITLE
表格模型训练，CPU版本报错

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleOCR#7589]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：mac m1 cpu
- 版本号/Version：Paddle：  PaddleOCR： paddlepaddle==2.2.2   PaddleOCR==2.6
- 运行指令/Command Code：/PaddleOCR/tools/train.py  -c configs/table/SLANet.yml
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/tools/program.py", line 303, in train
    preds = model(images, data=batch[1:])
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 93, in forward
    x = self.neck(x)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/ppocr/modeling/necks/csp_pan.py", line 300, in forward
    inputs = self.conv_t(inputs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/ppocr/modeling/necks/csp_pan.py", line 228, in forward
    outs = [self.convs[i](x[i]) for i in range(len(x))]
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/ppocr/modeling/necks/csp_pan.py", line 228, in <listcomp>
    outs = [self.convs[i](x[i]) for i in range(len(x))]
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tmp/Desktop/git_project/paddleocr2.6/PaddleOCR/ppocr/modeling/necks/csp_pan.py", line 50, in forward
    x = self.bn(self.conv(x))
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tmp/miniforge3/envs/ppocr_rosetta/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 1095, in forward
    sync_batch_norm_out, _, _, _, _, _ = _C_ops.sync_batch_norm(
AttributeError: module 'paddle.fluid.core_noavx.ops' has no attribute 'sync_batch_norm'

**Comment by liuzhipengchd** [comment]
配置文件 use_sync_bn: True，修改为False，sync_batch_norm 不支持cpu

**Comment by WenmuZhou** [comment]
是的

**Comment by wang-love-yu** [comment]
配置文件 use_sync_bn: True，修改为False，sync_batch_norm 不支持cpu
