### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 6: illegal multibyte sequence

### ISSUE THREAD

**Issue by HayCarota** [PaddlePaddle/PaddleOCR#7601]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：anaconda python3.7
- 版本号/Version：Paddle：  PaddleOCR：**2.6** 问题相关组件/Related components：
- 运行指令/Command Code：`python web_service.py --config=./config.yml >log.txt`
- 完整报错/Complete Error Message：
- `Traceback (most recent call last):
  File "E:\Job\ocr\PaddleOCR\deploy\pdserving\web_service.py", line 166, in <module>
    FLAGS = ArgsParser().parse_args()
  File "E:\Job\ocr\PaddleOCR\deploy\pdserving\ocr_reader.py", line 424, in parse_args
    args.conf_dict = self._parse_opt(args.opt, args.config)
  File "E:\Job\ocr\PaddleOCR\deploy\pdserving\ocr_reader.py", line 440, in _parse_opt
    config = yaml.load(f, Loader=yaml.Loader)
  File "D:\Anaconda3\envs\paddleOcr\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\Anaconda3\envs\paddleOcr\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "D:\Anaconda3\envs\paddleOcr\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Anaconda3\envs\paddleOcr\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\Anaconda3\envs\paddleOcr\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 6: illegal multibyte sequence`

**Comment by HayCarota** [comment]
### 解决方案：ocr_reader.py
_--行440_
代码更改：
`def _parse_opt(self, opts, conf_path):`
      `  f = open(conf_path)        `

`def _parse_opt(self, opts, conf_path):`
      `  f = open(conf_path, encoding='utf-8' )     `
