### ISSUE TITLE
使用ppstructurev2转型成功的model.onnx进行模型预测出现错误

### ISSUE THREAD

**Issue by NBd-hub** [PaddlePaddle/PaddleOCR#7605]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：aistudio
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle2.3.2
- 运行指令/Command Code：!python3.7 /home/aistudio/work/PaddleOCR/ppstructure/predict_system.py --use_gpu=False --use_onnx=True  --det_model_dir=/home/aistudio/work/PaddleOCR/inference/det_onnx/model.onnx --image_dir=/home/aistudio/work/PaddleOCR/ppstructure/docs/table/1.png
- 完整报错/Complete Error Message：layout
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleOCR/ppstructure/predict_system.py", line 285, in <module>
    main(args)
  File "/home/aistudio/work/PaddleOCR/ppstructure/predict_system.py", line 216, in main
    structure_sys = StructureSystem(args)
  File "/home/aistudio/work/PaddleOCR/ppstructure/predict_system.py", line 66, in __init__
    self.layout_predictor = LayoutPredictor(args)
  File "/home/aistudio/work/PaddleOCR/ppstructure/layout/predict_layout.py", line 68, in __init__
    utility.create_predictor(args, 'layout', logger)
  File "/home/aistudio/work/PaddleOCR/tools/infer/utility.py", line 181, in create_predictor
    sess = ort.InferenceSession(model_file_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/aistudio/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer failed:Protobuf parsing failed.

**Comment by BenjiaminLiu** [comment]
@NBd-hub 你好，我也遇到了这个问题，请问你后面知道啥原因吗？多谢

**Comment by Iteachyou233** [comment]
参数不对导致加载模型失败
