### ISSUE TITLE
Error loading data PPOCR-v3

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#7613]
when I traing ocr with ppocr-v3, I get error:
```
line 121, in fetch\n    data.append(self.dataset[idx])\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/lmdb_dataset.py", line 115, in __getitem__\n    outs = transform(data, self.ops)\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform\n    data = op(data)\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/imaug/rec_img_aug.py", line 159, in __call__\n    for idx, ext_data in enumerate(data["ext_data"]):\nKeyError: \'ext_data\'\n'
```
It comes from rec_img_aug.py
```
def __call__(self, data):
        rnd_num = random.random()
        if rnd_num > self.prob:
            return data
        for idx, ext_data in enumerate(data["ext_data"]):
            if len(data["label"]) + len(ext_data[
                    "label"]) > self.max_text_length:
                break
            concat_ratio = data['image'].shape[1] / data['image'].shape[
                0] + ext_data['image'].shape[1] / ext_data['image'].shape[0]
            if concat_ratio > self.max_wh_ratio:
                break
            data = self.merge_ext_data(data, ext_data)
        data.pop("ext_data")
        return data
```
Thank for your comment!

**Comment by andyjpaddle** [comment]
please provide the config you used for training

**Comment by phamkhactu** [comment]
@andyjpaddle  a change backbone model to resnet 34, and I change size image
Here my configs:

```
Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/v3_en_resnet34
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/dict/en_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3_en.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    # name: MobileNetV1Enhance
    # scale: 0.5
    # last_conv_stride: [1, 2]
    # last_pool_type: avg
    name: ResNet
    layer: 34
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/en/train_hw
    ext_op_transform_idx: 1
    # label_file_list:
    # - ./train_data/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [32,150,3] #[48, 320, 3]
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3,32,150] #[3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/en/valid_hw
    # label_file_list:
    # - ./train_data/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 150] #[3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4

```

**Comment by andyjpaddle** [comment]
please provide you error info in one page, one line is not easy to understand

**Comment by phamkhactu** [comment]
```
[2022/09/16 09:25:55] ppocr INFO: train dataloader has 4205 iters
[2022/09/16 09:25:55] ppocr INFO: valid dataloader has 1407 iters
[2022/09/16 09:25:55] ppocr INFO: train from scratch
[2022/09/16 09:25:55] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/home/tupk/tupk/ocr-digits/PaddleOCR/tools/program.py", line 271, in train
    for idx, batch in enumerate(train_dataloader):
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 671, in _get_data
    batch.reraise()
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
KeyError: 'DataLoader worker(3) caught KeyError with message:\nTraceback (most recent call last):\n  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop\n    batch = fetcher.fetch(indices)\n  File "/home/tupk/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch\n    data.append(self.dataset[idx])\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/lmdb_dataset.py", line 115, in __getitem__\n    outs = transform(data, self.ops)\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/imaug/__init__.py", line 53, in transform\n    data = op(data)\n  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/data/imaug/rec_img_aug.py", line 159, in __call__\n    for idx, ext_data in enumerate(data["ext_data"]):\nKeyError: \'ext_data\'\n'
    
data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

INFO 2022-09-16 09:26:01,023 launch_utils.py:343] terminate all the procs
INFO 2022-09-16 09:26:01,023 launch_utils.py:343] terminate all the procs
ERROR 2022-09-16 09:26:01,024 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-09-16 09:26:01,024 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-09-16 09:26:05,028 launch_utils.py:343] terminate all the procs
INFO 2022-09-16 09:26:05,028 launch_utils.py:343] terminate all the procs
INFO 2022-09-16 09:26:05,029 launch.py:402] Local processes completed.
INFO 2022-09-16 09:26:05,029 launch.py:402] Local processes completed.
```

**Comment by andyjpaddle** [comment]
currently, `RecConAug` is not supported for `LMDBDataSet` format, it's only supported for `SimpleDataSet`, you can convert you dataset to SimpleDataSet or you can rewrite the code of LMDBDataSet follow SimpleDataSet

**Comment by phamkhactu** [comment]
@andyjpaddle thank you, If I dont use ```RecConAug``` maybe error not occur?

**Comment by andyjpaddle** [comment]
yes, you are right, the error happens only in LMDBDataSet

**Comment by phamkhactu** [comment]
@andyjpaddle thank you
