### ISSUE TITLE
使用pyinstaller打包成可执行文件报错

### ISSUE THREAD

**Issue by lqllife** [PaddlePaddle/PaddleOCR#7635]
- 系统环境/System Environment：win 11
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6.0.1

项目已经写好，使用 `python main.py`可以运行项目，但是使用`pyinstaller -F -w main.py`编译成可执行的二进制文件时，报错：
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "libs\ocr.py", line 2, in <module>
ModuleNotFoundError: No module named 'paddleocr'
```

是我打包的方式不对吗？

**Comment by WenmuZhou** [comment]
这个我们不清楚，我们也没有试过打包exe
