### ISSUE TITLE
enhanced_ctc_loss

### ISSUE THREAD

**Issue by Delay0123456789** [PaddlePaddle/PaddleOCR#7656]
你好，在我想用enhanced_ctc_loss时，怎样在ch_PP-OCRv2_rec_enhanced_ctc_loss.yml中设置，其中 Focal-CTC Loss，A-CTC Loss， 怎么设置用哪一个，非常感谢
Loss:
  name: CombinedLoss
  loss_config_list:
  - CTCLoss:
      use_focal_loss: false
      weight: 1.0
  - CenterLoss:
      weight: 0.05
      num_classes: 6625
      feat_dim: 96
      center_file_path:
  # you can also try to add ace loss on your own dataset
  # - ACELoss:
  #     weight: 0.1

**Comment by Delay0123456789** [comment]
非常感谢

**Comment by nissansz** [comment]
设置成功了吗？
我用上面的设置，放到resnet34中的loss部分，没有训练进度，读完数据半天后报以下错误？

Traceback (most recent call last):
  File "./tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "./tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward
    loss = loss_func(input, batch, **kargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in __call__
    assert isinstance(predicts, (list, tuple))
AssertionError
