### ISSUE TITLE
PPOCRv3_det训练报错

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleOCR#7721]
有人知道这是什么问题吗？
[2022/09/25 01:31:33] ppocr INFO: epoch: [123/292], global_step: 3900, lr: 0.000355, dila_dbloss_Student_Teacher: 1.147592, dila_dbloss_Student2_Teacher: 1.116941, loss: 5.599220, dml_thrink_maps_0: 0.004171, db_Student_loss_shrink_maps: 0.845251, db_Student_loss_threshold_maps: 0.532987, db_Student_loss_binary_maps: 0.169158, db_Student2_loss_shrink_maps: 0.852246, db_Student2_loss_threshold_maps: 0.523404, db_Student2_loss_binary_maps: 0.170709, avg_reader_cost: 0.27565 s, avg_batch_cost: 0.90337 s, avg_samples: 8.0, ips: 8.85577 samples/s, eta: 6:00:30
[2022/09/25 01:31:52] ppocr INFO: epoch: [123/292], global_step: 3920, lr: 0.000354, dila_dbloss_Student_Teacher: 1.051392, dila_dbloss_Student2_Teacher: 1.033185, loss: 5.377273, dml_thrink_maps_0: 0.003931, db_Student_loss_shrink_maps: 0.979663, db_Student_loss_threshold_maps: 0.526779, db_Student_loss_binary_maps: 0.195901, db_Student2_loss_shrink_maps: 0.992239, db_Student2_loss_threshold_maps: 0.534106, db_Student2_loss_binary_maps: 0.198338, avg_reader_cost: 0.26140 s, avg_batch_cost: 0.94430 s, avg_samples: 8.0, ips: 8.47188 samples/s, eta: 6:00:01
[2022/09/25 01:32:12] ppocr INFO: epoch: [123/292], global_step: 3940, lr: 0.000353, dila_dbloss_Student_Teacher: 0.930293, dila_dbloss_Student2_Teacher: 0.890593, loss: 5.369464, dml_thrink_maps_0: 0.005529, db_Student_loss_shrink_maps: 1.016422, db_Student_loss_threshold_maps: 0.542861, db_Student_loss_binary_maps: 0.203539, db_Student2_loss_shrink_maps: 0.934451, db_Student2_loss_threshold_maps: 0.529297, db_Student2_loss_binary_maps: 0.186863, avg_reader_cost: 0.30269 s, avg_batch_cost: 0.98709 s, avg_samples: 8.0, ips: 8.10465 samples/s, eta: 5:59:37
[2022/09/25 01:32:32] ppocr INFO: epoch: [123/292], global_step: 3960, lr: 0.000352, dila_dbloss_Student_Teacher: 1.169991, dila_dbloss_Student2_Teacher: 1.192590, loss: 5.808578, dml_thrink_maps_0: 0.003896, db_Student_loss_shrink_maps: 0.918923, db_Student_loss_threshold_maps: 0.532042, db_Student_loss_binary_maps: 0.183799, db_Student2_loss_shrink_maps: 0.958903, db_Student2_loss_threshold_maps: 0.536719, db_Student2_loss_binary_maps: 0.191571, avg_reader_cost: 0.27315 s, avg_batch_cost: 0.95936 s, avg_samples: 8.0, ips: 8.33893 samples/s, eta: 5:59:10
[2022/09/25 01:32:40] ppocr INFO: save model in F:\ocr_dataset\project_path\latest
[2022/09/25 01:33:01] ppocr INFO: epoch: [124/292], global_step: 3980, lr: 0.000350, dila_dbloss_Student_Teacher: 1.155356, dila_dbloss_Student2_Teacher: 1.136014, loss: 5.787402, dml_thrink_maps_0: 0.005272, db_Student_loss_shrink_maps: 0.950435, db_Student_loss_threshold_maps: 0.542937, db_Student_loss_binary_maps: 0.189759, db_Student2_loss_shrink_maps: 0.923214, db_Student2_loss_threshold_maps: 0.534945, db_Student2_loss_binary_maps: 0.184802, avg_reader_cost: 0.75305 s, avg_batch_cost: 1.44805 s, avg_samples: 8.0, ips: 5.52467 samples/s, eta: 5:59:34
[2022/09/25 01:33:21] ppocr INFO: epoch: [124/292], global_step: 4000, lr: 0.000349, dila_dbloss_Student_Teacher: 0.989578, dila_dbloss_Student2_Teacher: 1.104956, loss: 5.511506, dml_thrink_maps_0: 0.003489, db_Student_loss_shrink_maps: 0.917086, db_Student_loss_threshold_maps: 0.528550, db_Student_loss_binary_maps: 0.183331, db_Student2_loss_shrink_maps: 0.912267, db_Student2_loss_threshold_maps: 0.538557, db_Student2_loss_binary_maps: 0.182220, avg_reader_cost: 0.29575 s, avg_batch_cost: 0.97608 s, avg_samples: 8.0, ips: 8.19603 samples/s, eta: 5:59:09
eval model:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 499/500 [01:12<00:00,  6.93it/s]
[2022/09/25 01:34:33] ppocr INFO: cur metric, precision: 0.4901712111604312, recall: 0.37270973963355836, hmean: 0.42344563133388113, fps: 7.845428397087431
[2022/09/25 01:34:33] ppocr INFO: save best model is to F:\ocr_dataset\project_path\best_accuracy
[2022/09/25 01:34:44] ppocr INFO: best metric, hmean: 0.42344563133388113, is_float16: False, precision: 0.4901712111604312, recall: 0.37270973963355836, fps: 7.845428397087431, best_epoch: 124, start_epoch: 92
Traceback (most recent call last):
  File "PaddleOCR\train.py", line 198, in <module>
  File "PaddleOCR\train.py", line 171, in main
  File "D:\PaddleOCR\tools\program.py", line 483, in train
    loss = loss_class(preds, batch)
  File "paddle\fluid\dygraph\layers.py", line 930, in __call__
  File "paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
  File "D:\PaddleOCR\ppocr\losses\combined_loss.py", line 58, in forward
    loss = loss_func(input, batch, **kargs)
  File "paddle\fluid\dygraph\layers.py", line 930, in __call__
  File "paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
  File "D:\PaddleOCR\ppocr\losses\distillation_loss.py", line 265, in forward
    stu_binary_maps = stu_preds[:, 2, :, :]
  File "paddle\fluid\dygraph\varbase_patch_methods.py", line 740, in __getitem__
IndexError: (OutOfRange) The starting index 2 of slice is out of bounds in tensor 1-th axis, it shound be in the range of [-1, 1). (at ..\paddle/fluid/pybind/slice_utils.h:197)

训练config文件如下：
Global:
  debug: false
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: F:\ocr_dataset\project_path
  save_epoch_step: 200
  eval_batch_step:
  - 0
  - 400
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true

Architecture:
  name: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      pretrained:
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: True
      Head:
        name: DBHead
        k: 50
    Student2:
      pretrained: 
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        name: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        name: RSEFPN
        out_channels: 96
        shortcut: True
      Head:
        name: DBHead
        k: 50
    Teacher:
      pretrained: 
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        name: ResNet_vd
        in_channels: 3
        layers: 50
      Neck:
        name: LKPAN
        out_channels: 256
      Head:
        name: DBHead
        kernel_list: [7,2,2]
        k: 50

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDilaDBLoss:
      weight: 1.0
      model_name_pairs:
      - ["Student", "Teacher"]
      - ["Student2", "Teacher"]
      key: maps
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
  - DistillationDMLLoss:
      model_name_pairs:
      - ["Student", "Student2"]
      maps_name: "thrink_maps"
      weight: 1.0
      model_name_pairs: ["Student", "Student2"]
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list: ["Student", "Student2"]
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05

PostProcess:
  name: DistillationDBPostProcess
  model_name: ["Student"]
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: 1.0 #[1.0]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - CopyPaste:
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 960
        - 960
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.5 #0.485
        - 0.5 #0.456
        - 0.5 #0.406
        std:
        - 0.5 #0.229
        - 0.5 #0.224
        - 0.5 #0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 8
    num_workers: 2
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          image_shape: [960, 960]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.5, 0.5, 0.5] #[0.485, 0.456, 0.406]
          std: [0.5, 0.5, 0.5] #[0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2

**Comment by LDOUBLEV** [comment]
训练中报错？有没有对代码做了调整
