### ISSUE TITLE
KIE训练时报错 (External) CUDA error(719), unspecified launch failure

### ISSUE THREAD

**Issue by husiluanxiang** [PaddlePaddle/PaddleOCR#7739]
基本配置 系统windows10 显卡2060 12G
![image](https://user-images.githubusercontent.com/38007233/192415995-8d876756-eb60-421b-958a-b8b8a8eec253.png)
配置文件 ：
![image](https://user-images.githubusercontent.com/38007233/192416113-fad57a46-021e-42db-89c9-e8fa9086385d.png)
![image](https://user-images.githubusercontent.com/38007233/192416152-57b36374-fb87-4518-a4c8-e21f0cc16948.png)
![image](https://user-images.githubusercontent.com/38007233/192416210-ad32aab5-e91a-43f0-8524-9673b60d3523.png)
![image](https://user-images.githubusercontent.com/38007233/192416262-6fd2356f-a9f8-4337-bb8a-539fbe359e61.png)
![image](https://user-images.githubusercontent.com/38007233/192416303-3ba30420-8afe-441f-9997-318ef5960e11.png)
![image](https://user-images.githubusercontent.com/38007233/192416344-3faf0283-563d-4b13-bab0-952e4a14a9c0.png)
![image](https://user-images.githubusercontent.com/38007233/192416398-36a67b7b-ba1f-49c3-a233-b5d1e0f1d2ad.png)
![image](https://user-images.githubusercontent.com/38007233/192416436-4c073deb-159c-46e0-bb19-5eceacaa30cb.png)
![image](https://user-images.githubusercontent.com/38007233/192416481-45b5ad7c-f092-4766-b6f9-eeb6fcdb310e.png)

报错信息：
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Traceback (most recent call last):
  File "D:\QB\pypro\PaddleOCR\tools\train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "D:\QB\pypro\PaddleOCR\tools\train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\QB\pypro\PaddleOCR\tools\program.py", line 317, in train
    preds = model(batch)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\QB\pypro\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\QB\pypro\PaddleOCR\ppocr\modeling\backbones\vqa_layoutlm.py", line 166, in forward
    x = self.model(
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1040, in forward
    outputs = self.layoutxlm(
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 925, in forward
    final_bbox = paddle.concat([bbox, visual_bbox], axis=1)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\tensor\manipulation.py", line 331, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\layers\tensor.py", line 343, in concat
    _C_ops.concat(input, out, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)
  [operator < concat > error]
这个错误应该如何解决

**Comment by littletomatodonkey** [comment]
你好，把bs改小点看下呢？先改为1，看下能否跑起来，这个模型对显存要求比较高

**Comment by husiluanxiang** [comment]
> 你好，把bs改小点看下呢？先改为1，看下能否跑起来，这个模型对显存要求比较高

你好我的bs已经是1了 我感觉不像显存不够啊 不够报错应该是显存耗尽吧

**Comment by littletomatodonkey** [comment]
显存不够的时候，他计算的时候没办法申请新的显存，所以就报在了申请现存的这个op上，这块报错信息我们看下怎么优化下

**Comment by husiluanxiang** [comment]
> 显存不够的时候，他计算的时候没办法申请新的显存，所以就报在了申请现存的这个op上，这块报错信息我们看下怎么优化下

那这个训练显存一般需要多少 我按照基本配置24个G的显存是否够用。如果可以我先尝试下3090单卡的 现在这个显存是12G的

**Comment by husiluanxiang** [comment]
> 


> 

我调成1都不够。 我不知道换3090是否能满足训练的要求
