### ISSUE TITLE
ser GPU训练报错

### ISSUE THREAD

**Issue by guishilike** [PaddlePaddle/PaddleOCR#7740]
ser训练报错，数据集采用的示例的发票数据集

- 系统环境/System Environment：ubuntu20.04 RTX3070
- 版本号：PadldleOCR
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "/home/luyu/git/PaddleOCR/tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/luyu/git/PaddleOCR/tools/train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/luyu/git/PaddleOCR/tools/program.py", line 302, in train
    loss = loss_class(preds, batch)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/luyu/git/PaddleOCR/ppocr/losses/combined_loss.py", line 58, in forward
    loss = loss_func(input, batch, **kargs)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/luyu/git/PaddleOCR/ppocr/losses/distillation_loss.py", line 346, in forward
    loss = super().forward(out, batch)
  File "/home/luyu/git/PaddleOCR/ppocr/losses/vqa_token_layoutlm_loss.py", line 38, in forward
    active_output = predicts.reshape(
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 736, in __getitem__
    return _getitem_impl_(self, item)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/variable_index.py", line 431, in _getitem_impl_
    return get_value_for_bool_tensor(var, slice_item)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/variable_index.py", line 309, in get_value_for_bool_tensor
    return cond(
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/layers/control_flow.py", line 2466, in cond
    return false_fn()
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/variable_index.py", line 311, in <lambda>
    lambda: idx_not_empty(var, item))
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/variable_index.py", line 300, in idx_not_empty
    bool_2_idx = where(item == True)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/layers/nn.py", line 14566, in where
    return _C_ops.where_index(condition)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1130389438, 1] now
  [Hint: Expected numel() >= 0, but received numel():-1130389438 < 0:0.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:108)
  [operator < where_index > error]
```

**Comment by littletomatodonkey** [comment]
你好，paddleocr的版本请使用2.6分支，paddlenlp请安装这里的版本：[链接](https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/ppstructure/kie/requirements.txt)，paddle请使用2.3.1

如果还是有问题，麻烦提供下复现的命令或者方法
