### ISSUE TITLE
关于快速构建卡证类OCR的一些问题

### ISSUE THREAD

**Issue by engrwuang** [PaddlePaddle/PaddleOCR#7759]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu

- 版本号/Version：PaddleOCR 2.6.0

- 运行指令/Command Code： python tools/train.py  -c  configs/det/det_mv3_db.yml

- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "/home/luyu/git/CardOCR/PaddleOCR/tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/luyu/git/CardOCR/PaddleOCR/tools/train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/luyu/git/CardOCR/PaddleOCR/tools/program.py", line 302, in train
    loss = loss_class(preds, batch)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/luyu/.conda/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/luyu/git/CardOCR/PaddleOCR/ppocr/losses/det_db_loss.py", line 60, in forward
    label_threshold_map, label_threshold_mask, label_shrink_map, label_shrink_mask = labels[1:]
ValueError: too many values to unpack (expected 4)

另：对于[快速构建卡证类OCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%E5%8D%A1%E8%AF%81%E7%B1%BBOCR.md#%E5%BF%AB%E9%80%9F%E6%9E%84%E5%BB%BA%E5%8D%A1%E8%AF%81%E7%B1%BBocr)中，给到的项目实践指南在loss修改、后处理等方面均有遗漏，希望得到更新。

**Comment by an1018** [comment]
请问这个错误是按【快速构建卡证类OCR】教程运行报的错吗

**Comment by 450616391** [comment]
> 请问这个错误是按【快速构建卡证类OCR】教程运行报的错吗

是的

**Comment by an1018** [comment]
好的，我反馈一下

**Comment by BeyondYourself** [comment]
1）对于Loss在文档中已经说明了，采用的是交叉熵损失函数
2）后处理部分中，根据mask中，找到对应的索引即可获得所属的分类

**Comment by 450616391** [comment]
> 1）对于Loss在文档中已经说明了，采用的是交叉熵损失函数 2）后处理部分中，根据mask中，找到对应的索引即可获得所属的分类

请问在loss部分，调用的交叉熵损失函数是如下吗？
from paddle.nn.layer.loss import CrossEntropyLoss

**Comment by BeyondYourself** [comment]
这个你可以验证一下，对于多分类的交叉熵损失问题不大

**Comment by izhaolinger** [comment]
> 

您好，请问您这个报错是怎么解决的呢

**Comment by xtl1889** [comment]
请问解决这个问题怎么解决的
我也是根据【快速构建卡证类OCR】步骤,提示同样的错误
