### ISSUE TITLE
ImportError: /usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core_avx.so: cannot read file data

### ISSUE THREAD

**Issue by xul168** [PaddlePaddle/PaddleOCR#7789]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：centos7
- 版本号/Version：Paddle：2.3.2  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：import paddle
- 完整报错/Complete Error Message：
Error: Can not import avx core while this file exists: /usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /usr/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core_avx.so: cannot read file data

**Comment by xul168** [comment]
编译安装的，最后 make -j$(nproc) 的时候有中断，不知道是不是这个原因，现在重新执行 make -j$(nproc) 重新编译，然后重新pip安装就正常了

>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
W0929 23:03:55.380520 15760 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
