### ISSUE TITLE
使用GPU能够正常推理，use_tensorrt运行失败

### ISSUE THREAD

**Issue by zpy78987** [PaddlePaddle/PaddleOCR#7795]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： arm64
- 版本号/Version：Paddle2.3.2：  PaddleOCR-dygraph： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

root@d0e7840681f9:/data/PaddleOCR-dygraph# python tools/infer/predict_system.py --image_dir=/data/datasets/icdar2019_3k/images/ --det_model_dir="../paddleOCR/ch_ppocr_server_v2.0_det_infer" --cls_model_dir="./cls/" --rec_model_dir="../paddleOCR/ch_ppocr_server_v2.0_rec_infer" --use_angle_cls=false --use_mp=True --total_process_num=8 --draw_img_save_dir=res_icdar2019_trt_t8 --use_gpu=true --use_tensorrt=true
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 259, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 137, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/data/PaddleOCR-dygraph/tools/infer/predict_det.py", line 139, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/data/PaddleOCR-dygraph/tools/infer/utility.py", line 277, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string > > const&)
9   paddle::framework::ir::PassRegistry::Get(std::string const&) const
10  phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
11  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /data/TOOLS/Paddle/paddle/fluid/framework/ir/pass.h:242)

**Comment by zpy78987** [comment]
问题已解决，是由于arm上编译时没有增加TENSORRT编译选项导致的，建议在ARM安装指导界面增加提示。
