### ISSUE TITLE
ABINet 转推理模型出现错误

### ISSUE THREAD

**Issue by LoveSimons** [PaddlePaddle/PaddleOCR#7797]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10+Anaconda
- 版本号/Version：Paddle：Paddle-2.6  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
- 主要问题：采用训练模型进行预测，可以识别出结果：
命令：python tools/infer_rec.py -c configs/rec/rec_r45_abinet_icdar.yml -o Global.infer_img="./rec_test_icdar/" Global.checkpoints="./output/rec_abinet_icdar/best_accuracy"
[2022/09/30 16:09:36] ppocr INFO: resume from ./output/rec_abinet_icdar/best_accuracy
[2022/09/30 16:09:36] ppocr INFO: infer_img: ./rec_test_icdar/word_10.png
[2022/09/30 16:09:36] ppocr INFO:        result: cautin 0.7027849555015564
[2022/09/30 16:09:36] ppocr INFO: infer_img: ./rec_test_icdar/word_11.png
[2022/09/30 16:09:36] ppocr INFO:        result: citi   0.9997815489768982
[2022/09/30 16:09:36] ppocr INFO: infer_img: ./rec_test_icdar/word_12.png
[2022/09/30 16:09:37] ppocr INFO:        result: smrt   0.9997391700744629
[2022/09/30 16:09:37] ppocr INFO: infer_img: ./rec_test_icdar/word_13.png
[2022/09/30 16:09:37] ppocr INFO:        result: why    0.7770702242851257
[2022/09/30 16:09:37] ppocr INFO: infer_img: ./rec_test_icdar/word_14.png
[2022/09/30 16:09:37] ppocr INFO:        result: ay     0.971611738204956
[2022/09/30 16:09:37] ppocr INFO: infer_img: ./rec_test_icdar/word_15.png
......
训练模型转推理模型：python tools/export_model.py -c configs/rec/rec_r45_abinet_icdar.yml -o Global.checkpoints="./output/rec_abinet_icdar/best_accuracy" Global.save_inference_dir="./inference/rec_r45_abinet_icdar/"
使用推理模型进行预测：python tools/infer/predict_rec.py --image_dir="./rec_test_icdar/" --rec_model_dir="./inference/rec_r45_abinet_icdar/" --rec_char_dict_path="./train_data/rec_dataset/ICDAR_2015/ic15_dict.txt" --use_space_char=False --rec_algorithm="ABINet" --rec_image_shape="3,32,128"
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_10.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_11.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_12.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_13.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_14.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_15.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_16.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_17.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_18.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_19.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_2.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_20.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_21.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_3.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_4.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_5.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_6.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_7.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_8.png:('', nan)
[2022/09/30 16:16:27] ppocr INFO: Predicts of ./rec_test_icdar/word_9.png:('', nan)
请问什么问题？

**Comment by Topdu** [comment]
请尝试[ABINet doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_abinet.md)中的python推理部署是否可以跑通

**Comment by LoveSimons** [comment]
> 请尝试[ABINet doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_abinet.md)中的python推理部署是否可以跑通

尝试过，一样的问题；训练模型直接预测没有问题，转推理模型进行预测，预测结果是空的。

**Comment by Topdu** [comment]
我根据[ABINet doc](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/algorithm_rec_abinet.md)中的python推理部署流程跑了一遍，可以正常输出结果，命令和输出如下：

```shell
# 下载模型
wget https://paddleocr.bj.bcebos.com/rec_r45_abinet_train.tar && tar xf rec_r45_abinet_train.tar

# 导出推理模型命令
python3 tools/export_model.py -c configs/rec/rec_r45_abinet.yml -o Global.pretrained_model=./rec_r45_abinet_train/best_accuracy Global.save_inference_dir=./inference/rec_r45_abinet/

# 推理命令
python3 tools/infer/predict_rec.py --image_dir='./doc/imgs_words_en/word_10.png' --rec_model_dir='./inference/rec_r45_abinet/' --rec_algorithm='ABINet' --rec_image_shape='3,32,128' --rec_char_dict_path='./ppocr/utils/ic15_dict.txt'
```

输出预测结果为：
```shell
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2022/10/08 07:02:31] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2022/10/08 07:02:34] ppocr INFO: Predicts of ./doc/imgs_words_en/word_10.png:('pain', 0.9999995231628418)
```
请您根据以上的命令尝试运行，如果与以上结果不符，请反馈所有命令的输出结果。注意：保证代码与release/2.6分支一致，如果您改动了某些代码或者参数，请一并反馈。

**Comment by Topdu** [comment]
以上运行结果在linux系统下运行，注意到你运行的环境为win10，可能是因为你环境不同导致输出不正常，建议先尝试不使用ABINet的lang模块，检查能否正常输出结果。

**Comment by LoveSimons** [comment]
> 以上运行结果在linux系统下运行，注意到你的运行环境为win10，可能是因为环境不同导致输出不正常，建议先尝试不使用ABINet的lang模块，检查能否正常输出结果。
在linux下训练出现如下错误：
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/home/work_pp/PaddleOCR-2.6/tools/program.py", line 301, in train
    preds = model(images)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 578, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work_pp/PaddleOCR-2.6/ppocr/modeling/architectures/base_model.py", line 100, in forward
    x = self.head(x, targets=data)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work_pp/PaddleOCR-2.6/ppocr/modeling/heads/rec_abinet_head.py", line 231, in forward
    vis_lengths = _get_length(vis_logits)
  File "/home/work_pp/PaddleOCR-2.6/ppocr/modeling/heads/rec_abinet_head.py", line 274, in _get_length
    out = (out_int.cumsum(-1) == 1) & out
TypeError: unsupported operand type(s) for &: 'Tensor' and 'Tensor'
定位到错误是 ：out = (out_int.cumsum(-1) == 1) & out，此时的paddle版本为2.1.0，这个错误是否因为版本低的问题？

**Comment by MissPenguin** [comment]
paddle已经release到2.3了，先更新一下试试吧，2.1有点老了
