### ISSUE TITLE
ValueError: (InvalidArgument) shape(): argument 'Input' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)

### ISSUE THREAD

**Issue by ziyuwzf** [PaddlePaddle/PaddleOCR#7864]
按照[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)/[ppstructure](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure)/[kie](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/ppstructure/kie)/README_ch.md
要求准备好环境，数据，模型后，运行SER + RE模型串联命令代码时报错：
- 系统环境/System Environment：CUDA 10.2  linux
- 版本号/Version：Paddle： 2.3.2 PaddleOCR：2.6 问题相关组件/Related components：kie  re
- 运行指令/Command Code：
CUDA_VISIBLE_DEVICES=1 python3 ./tools/infer_kie_token_ser_re.py   -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml   -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy   Global.infer_img=./train_data/XFUND/zh_val/image/zh_val_42.jpg   -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml   -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy

- 完整报错/Complete Error Message：
[2022-10-10 08:28:58,214] [    INFO] - Already cached /root/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2022-10-10 08:28:59,013] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2022-10-10 08:28:59,013] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2022/10/10 08:29:01] ppocr INFO: resume from ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy
Corrupt JPEG data: premature end of data segment
Traceback (most recent call last):
  File "./tools/infer_kie_token_ser_re.py", line 205, in <module>
    result = ser_re_engine(data)
  File "./tools/infer_kie_token_ser_re.py", line 139, in __call__
    preds = self.model(re_input)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/AI/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/AI/ppocr/modeling/backbones/vqa_layoutlm.py", line 233, in forward
    relations=x[6])
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1542, in forward
    relations)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1407, in forward
    batch_size, max_length, _ = paddle.shape(entities)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 11702, in shape
    out = _C_ops.shape(input)
ValueError: (InvalidArgument) shape(): argument 'Input' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)

**Comment by littletomatodonkey** [comment]
你好，用这个包试下：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

**Comment by ziyuwzf** [comment]
> https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl
pip list显示已安装
paddlenlp                         2.3.0.dev0
重新运行后，依然报相同的错误

**Comment by ziyuwzf** [comment]
> 你好，用这个包试下：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

pip list显示已安装
paddlenlp 2.3.0.dev0
重新运行后，依然报相同的错误

**Comment by ziyuwzf** [comment]
> 你好，用这个包试下：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl
尝试更新paddlenlp之后，如下：
paddlenlp                         2.4.0
问题解决

**Comment by ziyuwzf** [comment]
> 尝试更新paddlenlp之后，如下：
> paddlenlp 2.4.0
> 问题解决

**Comment by ziyuwzf** [comment]
> 你好，用这个包试下：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

尝试更新paddlenlp之后，如下：
paddlenlp 2.4.0
问题解决
