### ISSUE TITLE
Error when prune rec model: __init__() missing 1 required positional argument: 'out_channels_list'

### ISSUE THREAD

**Issue by yearzhengcheng** [PaddlePaddle/PaddleOCR#7869]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- win11 22000.978
- 版本号/Version：Paddle：2.3.1  PaddleOCR：2.5.0.3 问题相关组件/Related components：
- 运行指令/Command Code：python deploy/slim/prune/sensitivity_anal.py -c project/rec_model/config.yml
- 完整报错/Complete Error Message：
[2022/10/11 11:14:09] ppocr INFO: Architecture : 
[2022/10/11 11:14:09] ppocr INFO:     Backbone : 
[2022/10/11 11:14:09] ppocr INFO:         last_conv_stride : [1, 2]
[2022/10/11 11:14:09] ppocr INFO:         last_pool_type : avg
[2022/10/11 11:14:09] ppocr INFO:         name : MobileNetV1Enhance
[2022/10/11 11:14:09] ppocr INFO:         scale : 0.5
[2022/10/11 11:14:09] ppocr INFO:     Head :
[2022/10/11 11:14:09] ppocr INFO:         head_list :
[2022/10/11 11:14:09] ppocr INFO:             CTCHead :
[2022/10/11 11:14:09] ppocr INFO:                 Head :
[2022/10/11 11:14:09] ppocr INFO:                     fc_decay : 1e-05
[2022/10/11 11:14:09] ppocr INFO:                 Neck :
[2022/10/11 11:14:09] ppocr INFO:                     depth : 2
[2022/10/11 11:14:09] ppocr INFO:                     dims : 64
[2022/10/11 11:14:09] ppocr INFO:                     hidden_dims : 120
[2022/10/11 11:14:09] ppocr INFO:                     name : svtr
[2022/10/11 11:14:09] ppocr INFO:                     use_guide : True
[2022/10/11 11:14:09] ppocr INFO:             SARHead :
[2022/10/11 11:14:09] ppocr INFO:                 enc_dim : 512
[2022/10/11 11:14:09] ppocr INFO:                 max_text_length : 25
[2022/10/11 11:14:09] ppocr INFO:         name : MultiHead
[2022/10/11 11:14:09] ppocr INFO:     Transform : None
[2022/10/11 11:14:09] ppocr INFO:     algorithm : SVTR
[2022/10/11 11:14:09] ppocr INFO:     model_type : rec
[2022/10/11 11:14:09] ppocr INFO: Eval :
[2022/10/11 11:14:09] ppocr INFO:     dataset :
[2022/10/11 11:14:09] ppocr INFO:         data_dir : ./project
[2022/10/11 11:14:09] ppocr INFO:         label_file_list : ['./project/train_data/rec/val.txt']
[2022/10/11 11:14:09] ppocr INFO:         name : SimpleDataSet
[2022/10/11 11:14:09] ppocr INFO:         transforms :
[2022/10/11 11:14:09] ppocr INFO:             DecodeImage :
[2022/10/11 11:14:09] ppocr INFO:                 channel_first : False
[2022/10/11 11:14:09] ppocr INFO:                 img_mode : BGR
[2022/10/11 11:14:09] ppocr INFO:             MultiLabelEncode : None
[2022/10/11 11:14:09] ppocr INFO:             RecResizeImg :
[2022/10/11 11:14:09] ppocr INFO:                 image_shape : [3, 48, 160]
[2022/10/11 11:14:09] ppocr INFO:             KeepKeys :
[2022/10/11 11:14:09] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2022/10/11 11:14:09] ppocr INFO:     loader :
[2022/10/11 11:14:09] ppocr INFO:         batch_size_per_card : 32
[2022/10/11 11:14:09] ppocr INFO:         drop_last : False
[2022/10/11 11:14:09] ppocr INFO:         num_workers : 4
[2022/10/11 11:14:09] ppocr INFO:         shuffle : False
[2022/10/11 11:14:09] ppocr INFO: Global :
[2022/10/11 11:14:09] ppocr INFO:     cal_metric_during_train : True
[2022/10/11 11:14:09] ppocr INFO:     character_dict_path : project/dict.txt
[2022/10/11 11:14:09] ppocr INFO:     checkpoints : project/rec_model/best_accuracy
[2022/10/11 11:14:09] ppocr INFO:     debug : True
[2022/10/11 11:14:09] ppocr INFO:     distributed : False
[2022/10/11 11:14:09] ppocr INFO:     epoch_num : 500
[2022/10/11 11:14:09] ppocr INFO:     eval_batch_step : [0, 2000]
[2022/10/11 11:14:09] ppocr INFO:     infer_img : project/train_data/rec/train/12626277.bmp
[2022/10/11 11:14:09] ppocr INFO:     infer_mode : False
[2022/10/11 11:14:09] ppocr INFO:     log_smooth_window : 20
[2022/10/11 11:14:09] ppocr INFO:     max_text_length : 25
[2022/10/11 11:14:09] ppocr INFO:     pretrained_model : project/rec_model/best_accuracy
[2022/10/11 11:14:09] ppocr INFO:     print_batch_step : 10
[2022/10/11 11:14:09] ppocr INFO:     save_epoch_step : 100
[2022/10/11 11:14:09] ppocr INFO:     save_inference_dir : project/rec_model/inference
[2022/10/11 11:14:09] ppocr INFO:     save_model_dir : ./project/rec_model/prune_model/
[2022/10/11 11:14:09] ppocr INFO:     save_res_path : ./project/output/rec1/predicts_ppocrv3_en.txt
[2022/10/11 11:14:09] ppocr INFO:     use_gpu : False
[2022/10/11 11:14:09] ppocr INFO:     use_space_char : True
[2022/10/11 11:14:09] ppocr INFO:     use_visualdl : False
[2022/10/11 11:14:09] ppocr INFO: Loss :
[2022/10/11 11:14:09] ppocr INFO:     loss_config_list :
[2022/10/11 11:14:09] ppocr INFO:         CTCLoss : None
[2022/10/11 11:14:09] ppocr INFO:         SARLoss : None
[2022/10/11 11:14:09] ppocr INFO:     name : MultiLoss
[2022/10/11 11:14:09] ppocr INFO: Metric :
[2022/10/11 11:14:09] ppocr INFO:     ignore_space : False
[2022/10/11 11:14:09] ppocr INFO:     main_indicator : acc
[2022/10/11 11:14:09] ppocr INFO:     name : RecMetric
[2022/10/11 11:14:09] ppocr INFO: Optimizer :
[2022/10/11 11:14:09] ppocr INFO:     beta1 : 0.9
[2022/10/11 11:14:09] ppocr INFO:     beta2 : 0.999
[2022/10/11 11:14:09] ppocr INFO:     lr :
[2022/10/11 11:14:09] ppocr INFO:         learning_rate : 0.001
[2022/10/11 11:14:09] ppocr INFO:         name : Cosine
[2022/10/11 11:14:09] ppocr INFO:         warmup_epoch : 5
[2022/10/11 11:14:09] ppocr INFO:     name : Adam
[2022/10/11 11:14:09] ppocr INFO:     regularizer :
[2022/10/11 11:14:09] ppocr INFO:         factor : 3e-05
[2022/10/11 11:14:09] ppocr INFO:         name : L2
[2022/10/11 11:14:09] ppocr INFO: PostProcess :
[2022/10/11 11:14:09] ppocr INFO:     name : CTCLabelDecode
[2022/10/11 11:14:09] ppocr INFO: Train :
[2022/10/11 11:14:09] ppocr INFO:     dataset :
[2022/10/11 11:14:09] ppocr INFO:         data_dir : ./project
[2022/10/11 11:14:09] ppocr INFO:         ext_op_transform_idx : 1
[2022/10/11 11:14:09] ppocr INFO:         label_file_list : ['./project/train_data/rec/train.txt']
[2022/10/11 11:14:09] ppocr INFO:         name : SimpleDataSet
[2022/10/11 11:14:09] ppocr INFO:         transforms :
[2022/10/11 11:14:09] ppocr INFO:             DecodeImage :
[2022/10/11 11:14:09] ppocr INFO:                 channel_first : False
[2022/10/11 11:14:09] ppocr INFO:                 img_mode : BGR
[2022/10/11 11:14:09] ppocr INFO:             RecConAug :
[2022/10/11 11:14:09] ppocr INFO:                 ext_data_num : 2
[2022/10/11 11:14:09] ppocr INFO:                 image_shape : [48, 160, 3]
[2022/10/11 11:14:09] ppocr INFO:                 prob : 0.5
[2022/10/11 11:14:09] ppocr INFO:             RecAug : None
[2022/10/11 11:14:09] ppocr INFO:             MultiLabelEncode : None
[2022/10/11 11:14:09] ppocr INFO:             RecResizeImg :
[2022/10/11 11:14:09] ppocr INFO:                 image_shape : [3, 48, 160]
[2022/10/11 11:14:09] ppocr INFO:             KeepKeys :
[2022/10/11 11:14:09] ppocr INFO:                 keep_keys : ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']
[2022/10/11 11:14:09] ppocr INFO:     loader :
[2022/10/11 11:14:09] ppocr INFO:         batch_size_per_card : 24
[2022/10/11 11:14:09] ppocr INFO:         drop_last : True
[2022/10/11 11:14:09] ppocr INFO:         num_workers : 4
[2022/10/11 11:14:09] ppocr INFO:         shuffle : True
[2022/10/11 11:14:09] ppocr INFO: profiler_options : None
[2022/10/11 11:14:09] ppocr INFO: train with paddle 2.3.1 and device Place(cpu)
[2022/10/11 11:14:09] ppocr INFO: Initialize indexs of datasets:['./project/train_data/rec/train.txt']
[2022/10/11 11:14:09] ppocr INFO: Initialize indexs of datasets:['./project/train_data/rec/val.txt']
Traceback (most recent call last):
  File "deploy/slim/prune/sensitivity_anal.py", line 175, in <module>
    main(config, device, logger, vdl_writer)
  File "deploy/slim/prune/sensitivity_anal.py", line 75, in main
    model = build_model(config['Architecture'])
  File "E:\WorkPower\Project\px\PaddleOCR\deploy/slim/prune\..\..\..\ppocr\modeling\architectures\__init__.py", line 27, in build_model
    arch = BaseModel(config)
  File "E:\WorkPower\Project\px\PaddleOCR\deploy/slim/prune\..\..\..\ppocr\modeling\architectures\base_model.py", line 71, in __init__
    self.head = build_head(config["Head"])
  File "E:\WorkPower\Project\px\PaddleOCR\deploy/slim/prune\..\..\..\ppocr\modeling\heads\__init__.py", line 57, in build_head
    module_class = eval(module_name)(**config)
TypeError: __init__() missing 1 required positional argument: 'out_channels_list'

**Comment by Suannz** [comment]
do U have answer?
