### ISSUE TITLE
访问hubsvring中的kie_ser报错

### ISSUE THREAD

**Issue by bank010** [PaddlePaddle/PaddleOCR#7892]
H:\ocr\PaddleOCR>python tools/test_hubserving.py --server_url=http://127.0.0.1:8871/predict/kie_ser --image_dir=./train_data/XFUND/zh_train/image/ --visualize=false
{'msg': 'not enough values to unpack (expected 3, got 2)', 'results': '', 'status': '101'}
[2022/10/12 12:06:33] ppocr INFO: Predict time of ./train_data/XFUND/zh_train/image/0.png: 6.928s
Traceback (most recent call last):
  File "H:\ocr\PaddleOCR\tools\test_hubserving.py", line 158, in <module>
    main(args)
  File "H:\ocr\PaddleOCR\tools\test_hubserving.py", line 120, in main
    res = r.json()["results"][0]
IndexError: string index out of range

**Comment by littletomatodonkey** [comment]
你好，安装下最新的paddleocr和dygraph分支代码试下

**Comment by LangJiHuangSha** [comment]
+1 服务启动成功，但是访问服务返回报错信息：
{
    "msg": "not enough values to unpack (expected 3, got 2)",
    "results": "",
    "status": "101"
}
