### ISSUE TITLE
ImportError: cannot import name '_switch_declarative_mode_guard_' from 'paddle.fluid.dygraph.base' (/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py)

### ISSUE THREAD

**Issue by wangyang581** [PaddlePaddle/PaddleOCR#7898]
环境为ppocr docker 镜像2.1.3-gpu-cuda11.2-cudnn8容器环境，正常训练没有问题，但是根据官方文档进行量化就报错了，量化命令为python deploy/slim/quantization/quant.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.save_model_dir=./output/quant_model_distill/

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR：2.6 
- 问题相关组件/Related components： paddleslim   2.3.2
- 运行指令/Command Code：python deploy/slim/quantization/quant.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.save_model_dir=./output/quant_model_distill/
- 完整报错/Complete Error Message：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "deploy/slim/quantization/quant.py", line 42, in <module>
    from paddleslim.dygraph.quant import QAT
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/__init__.py", line 17, in <module>
    from paddleslim import prune
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/prune/__init__.py", line 16, in <module>
    from .pruner import *
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/prune/pruner.py", line 20, in <module>
    from ..core import VarWrapper, OpWrapper, GraphWrapper
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/core/__init__.py", line 19, in <module>
    from ..core import dygraph
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/core/dygraph.py", line 7, in <module>
    from paddle.fluid.dygraph.base import program_desc_tracing_guard, _switch_declarative_mode_guard_
ImportError: cannot import name '_switch_declarative_mode_guard_' from 'paddle.fluid.dygraph.base' (/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py)

**Comment by WenmuZhou** [comment]
你的paddle也需要用2.3.2的
