### ISSUE TITLE
将det_r50_vd_dcn_fce_ctw.yml中的backbone改为mobilev3后训练报错

### ISSUE THREAD

**Issue by LiLiLiam** [PaddlePaddle/PaddleOCR#8026]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：2.6  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_r50_vd_dcn_fce_ctw.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "d:/yuling/PaddleOCR-release-2.6/tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "d:/yuling/PaddleOCR-release-2.6/tools/train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "d:\yuling\PaddleOCR-release-2.6\tools\program.py", line 302, in train
    loss = loss_class(preds, batch)
  File "D:\ProgramData\Anaconda3\envs\paddle-env-cuda11.1\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\paddle-env-cuda11.1\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "d:\yuling\PaddleOCR-release-2.6\ppocr\losses\det_fce_loss.py", line 65, in forward
    losses = multi_apply(self.forward_single, preds, gts)
  File "d:\yuling\PaddleOCR-release-2.6\ppocr\losses\det_fce_loss.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "d:\yuling\PaddleOCR-release-2.6\ppocr\losses\det_fce_loss.py", line 113, in forward_single
    loss_tr = self.ohem(tr_pred, tr_mask, train_mask)
  File "d:\yuling\PaddleOCR-release-2.6\ppocr\losses\det_fce_loss.py", line 168, in ohem
    predict.masked_select(pos2).reshape([-1, 2]),
  File "D:\ProgramData\Anaconda3\envs\paddle-env-cuda11.1\lib\site-packages\paddle\tensor\search.py", line 798, in masked_select
    return _C_ops.masked_select(x, mask)
ValueError: (InvalidArgument) The dim size of input and mask in OP(masked_selected) must be equal, but got input dim:(40000, 2), mask dim: (10000, 2). Please check input value.
  [Hint: Expected input_dim == mask_dim, but received input_dim:40000, 2 != mask_dim:10000, 2.] (at ../paddle/phi/kernels/gpu/masked_select_kernel.cu:64)
  [operator < masked_select > error]

**Comment by LiLiLiam** [comment]
应该是因为mobile的输出的是4个feature map，resnet_vd输出的是3个，导致后续处理完到计算loss的时候报错了，但是具体的还不明确

**Comment by littletomatodonkey** [comment]
你只输出3个feature map试下呢？

**Comment by LiLiLiam** [comment]
只输出三个feature map是可以的，加断点看了下是因为数据都进来的时候是生成了三个尺度的ground truth，所以backbone只能输出三个feature map不然算loss的时候会报错。但是找不到地方可以修改数据读取的时候生成几个尺度的ground truth，如果那天我想用两个、四个或者其他数量的feature map的时候这代码就不能用了。
