### ISSUE TITLE
kie训练下载模型404

### ISSUE THREAD

**Issue by YmanChris** [PaddlePaddle/PaddleOCR#8034]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu
- 版本号/Version：Paddle：  PaddleOCR：2.6.0 问题相关组件/Related components：
- 运行指令/Command Code：python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- 完整报错/Complete Error Message：
[2022-10-21 09:05:35,953] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased/model_state.pdparams failed with code 404!
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/paddlenlp/transformers/model_utils.py", line 276, in from_pretrained
    file_path, default_root)
  File "/root/.local/lib/python3.6/site-packages/paddlenlp/utils/downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/root/.local/lib/python3.6/site-packages/paddlenlp/utils/downloader.py", line 201, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/vi-layoutxlm-base-uncased/model_state.pdparams failed with code 404!

PS:paddleocr版本已经切换其他相似问题提出的develop2.3.0版本

**Comment by littletomatodonkey** [comment]
你好，pip install https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

重装下paddlenlp试下

**Comment by YmanChris** [comment]
重装十几次，各种方式都试了。。




发自我的手机


-------- 原始邮件 --------
发件人： littletomatodonkey ***@***.***>
日期： 2022年10月21日周五 晚上8:15
收件人： PaddlePaddle/PaddleOCR ***@***.***>
抄送： Yman ***@***.***>, Author ***@***.***>
主 题： Re: [PaddlePaddle/PaddleOCR] kie训练下载模型404 (Issue #8034)

你好，pip install https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl

重装下paddlenlp试下

**Comment by tangjielong928** [comment]
同样的问题
