### ISSUE TITLE
PPOCRLabel auto recognition Error

### ISSUE THREAD

**Issue by haiderasad** [PaddlePaddle/PaddleOCR#8041]
Is your PPOCRLabel depreciated? After running auto recognition on a batch of images , after clicking OK program ends with the following error 

`(paddle_env) haider@haider-pc:~/Documents/PaddleOCR/PPOCRLabel$ PPOCRLabel
[2022/10/21 19:18:39] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  /home/haider/Documents/paddle_docker/frames/temp/X_filename00001.png
DirPath in importDirImages is /home/haider/Documents/paddle_docker/frames/temp
Using model from  paddle
unicodeFilePath is /home/haider/Documents/paddle_docker/frames/temp/X_filename00007.png
[[[1649.0, 251.0], [1757.0, 257.0], [1755.0, 291.0], [1647.0, 286.0]], ('Darmz', 0.7529038786888123)]
Traceback (most recent call last):
  File "/home/haider/anaconda3/envs/paddle_env/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 2178, in autoRecognition
    self.loadFile(self.filePath)  # ADD
  File "/home/haider/anaconda3/envs/paddle_env/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 1579, in loadFile
    self.showBoundingBoxFromPPlabel(filePath)
  File "/home/haider/anaconda3/envs/paddle_env/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 1621, in showBoundingBoxFromPPlabel
    self.loadLabels(shapes)
  File "/home/haider/anaconda3/envs/paddle_env/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 1171, in loadLabels
    self.addLabel(shape)
  File "/home/haider/anaconda3/envs/paddle_env/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 1101, in addLabel
    item = HashableQListWidgetItem(shape.label)
  File "/home/haider/anaconda3/envs/paddle_env/lib/python3.8/site-packages/PPOCRLabel/libs/hashableQListWidgetItem.py", line 37, in __init__
    super(HashableQListWidgetItem, self).__init__(*args)
TypeError: arguments did not match any overloaded call:
  QListWidgetItem(parent: QListWidget = None, type: int = QListWidgetItem.Type): argument 1 has unexpected type 'list'
  QListWidgetItem(str, parent: QListWidget = None, type: int = QListWidgetItem.Type): argument 1 has unexpected type 'list'
  QListWidgetItem(QIcon, str, parent: QListWidget = None, type: int = QListWidgetItem.Type): argument 1 has unexpected type 'list'
  QListWidgetItem(QListWidgetItem): argument 1 has unexpected type 'list'

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666361939 (unix time) try "date -d @1666361939" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800009243) received by PID 37443 (TID 0x7fc04df20180) from PID 37443 ***]

Aborted (core dumped)
`
There were a lot of bugs initially also which i somehow manged to pass

![image](https://user-images.githubusercontent.com/55244143/197219498-974a6b02-c207-4387-867c-63e055bb5645.png)

![image](https://user-images.githubusercontent.com/55244143/197219523-41707d5a-29ff-4f9c-8384-7bf5e9ad093f.png)

**Comment by Evezerest** [comment]
please install ppocrlabel==2.1.3
