### ISSUE TITLE
Cant install paddleclas

### ISSUE THREAD

**Issue by JonhSilver** [PaddlePaddle/PaddleOCR#8059]
193 main -> Error on line 179 ModuleNotFoundError No module named 'paddleclas'
Traceback (most recent call last):
  File "C:\Users\1\OneDrive\Desktop\PDF\1.py", line 199, in <module>
    main()
  File "C:\Users\1\OneDrive\Desktop\PDF\1.py", line 179, in main
    table_engine = PPStructure(recovery=False, layout=False, table=False, ocr=True, show_log=True, image_orientation=True)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py", line 620, in __init__
    super().__init__(params)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 49, in __init__
    import paddleclas
ModuleNotFoundError: No module named 'paddleclas'

paddleclas is not possible to install
https://github.com/PaddlePaddle/PaddleClas/issues/2404

**Comment by JonhSilver** [comment]
table_engine = PPStructure(recovery=False, layout=False, table=**True**, ocr=False, show_log=False, image_orientation=False)




193 main -> Error on line 179 ModuleNotFoundError No module named 'auto_log'
Traceback (most recent call last):
  File "C:\Users\1\OneDrive\Desktop\PDF\1.py", line 199, in <module>
    main()
  File "C:\Users\1\OneDrive\Desktop\PDF\1.py", line 179, in main
    table_engine = PPStructure(recovery=False, layout=False, table=True, ocr=False, show_log=False, image_orientation=False)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py", line 620, in __init__
    super().__init__(params)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 76, in __init__
    self.table_system = TableSystem(args)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\ppstructure\table\predict_table.py", line 69, in __init__
    self.table_structurer = predict_strture.TableStructurer(args)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\ppstructure\table\predict_structure.py", line 94, in __init__
    import auto_log
ModuleNotFoundError: No module named 'auto_log'

**Comment by huangjun12** [comment]
`python3.7 -m pip install git+https://github.com/LDOUBLEV/AutoLog`
安装一下AutoLog
