### ISSUE TITLE
OCR2.6版本，排序算法问题

### ISSUE THREAD

**Issue by yoeaki** [PaddlePaddle/PaddleOCR#8081]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS、linux都存在此问题，麻烦官方人员排查。
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleOCR2.6最新版本
- 运行指令/Command Code：
识别图片如下：
![single](https://user-images.githubusercontent.com/39695971/197494193-97214dc9-f129-4002-ab1b-fa62d0f3eddc.jpg)

描述：
1. 裁剪上方图片《案由》单独识别。
2. 实例化TextSystem对象，调用call方法。
3. 在`predict_system`的79行 `dt_boxes = sorted_boxes(dt_boxes)`的`sorted_boxes`方法`sorted_boxes = sorted(dt_boxes, key=lambda x: (x[1], x[0]))`异常。我看到dt_boxes是个二位数组，但是调用`sorted`排序，只访问第一位数组提示错误 `The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
4. `debug`截图：<img width="1439" alt="image" src="https://user-images.githubusercontent.com/39695971/197655944-e7f42538-5365-49a5-b20a-8604e2ebb505.png">
5. 错误描述：
<img width="856" alt="image" src="https://user-images.githubusercontent.com/39695971/197656139-bab3d489-659e-4f9f-abc2-47c8b1bdf1a1.png">
6. 完整堆栈信息： `Traceback (most recent call last):
  File "/Users/xilongyuan/opt/anaconda3/envs/jykj-orc-2.6/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xilongyuan/opt/anaconda3/envs/jykj-orc-2.6/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/xilongyuan/project/jykj/project/AI/project-code/PaddleOCR-release-2.6-latest/jykjocr/modules/ocr/controller/general_controller.py", line 26, in general_rec
    result = single_img_predict(img, PaddleConfig())
  File "/Users/xilongyuan/project/jykj/project/AI/project-code/PaddleOCR-release-2.6-latest/jykjocr/modules/ocr/service/general_predict_system.py", line 87, in single_img_predict
    dt_boxes, rec_res, rec_time = text_sys(img)
  File "/Users/xilongyuan/project/jykj/project/AI/project-code/PaddleOCR-release-2.6-latest/tools/infer/predict_system.py", line 79, in __call__
    dt_boxes = sorted_boxes(dt_boxes)
  File "/Users/xilongyuan/project/jykj/project/AI/project-code/PaddleOCR-release-2.6-latest/tools/infer/predict_system.py", line 120, in sorted_boxes
    sorted_boxes = sorted(dt_boxes, key=lambda x: (x[1], x[0]))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/39695971/197664008-0af07e06-1b08-4e2c-979b-c8f74707c282.png">

**Comment by TranPhu1999** [comment]
Hi @yoeaki, it's seem that they have some mistake when coding this part, you can just switch line 120 and 122 like this and everthing will work fine.
![image](https://user-images.githubusercontent.com/43123257/198185573-a4d8d17f-e984-4425-ba8d-8139bb2cb6ca.png)

**Comment by yoeaki** [comment]
Hi @TranPhu1999 ,Thank you! 你是否知道`abs(num_boxes - 2) < 1e-4` 这个条件的作用？如果知道希望告诉我，谢谢！

**Comment by TranPhu1999** [comment]
You can try to pull the repo down, they have fixed this problem by totally remove the if else clause. 
Check this out: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/predict_system.py
![image](https://user-images.githubusercontent.com/43123257/198217983-3e35a684-703a-4fe5-b56b-565088daa7d1.png)

The `abs(num_boxes - 2) < 1e-4` they just want to check if the number of detected boxes is equal to 2. `1e-4` = 0.0001. I still don't understand why they did but at least the problem have solve now. 

Have a good day ;)))
