### ISSUE TITLE
训练KIE-RE模型，报错AttributeError: 'list' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by sybest1259** [PaddlePaddle/PaddleOCR#8106]
场景：
增值税发票关键信息抽取KIE任务，SER训练任务可以正常执行，RE训练任务报错

1、使用ppocrLabel工具进行标注，部分标注数据示例：
b0.jpg	[{"transcription": "广东增值税专用发票", "label": "question", "points": [[1648, 479], [2747, 469], [2749, 638], [1649, 648]], "id": 0, "linking": [[0, 24]]}, {"transcription": "2016年06月12日", "label": "answer", "points": [[3485, 789], [3954, 789], [3954, 851], [3485, 851]], "id": 1, "linking": [[1, 35]]}, {"transcription": "深圳市购机汇网络有限公司", "label": "answer", "points": [[1026, 962], [1766, 962], [1766, 1024], [1026, 1024]], "id": 2, "linking": [[2, 25]]}, {"transcription": "纳税人识别号：", "label": "question", "points": [[526, 1037], [947, 1037], [947, 1112], [526, 1112]], "id": 3, "linking": [[3, 4]]},......

2、执行RE训练任务
- 系统环境/System Environment：
   ubuntu18.4，python3.7

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
   Paddle：2.2.0-gpu

- 运行指令/Command Code：
   python3 -m paddle.distributed.launch --gpus '0,1,2,3'  tools/train.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml

- 完整报错/Complete Error Message：
[2022/10/26 02:39:26] ppocr INFO: train dataloader has 4 iters
[2022/10/26 02:39:26] ppocr INFO: valid dataloader has 2 iters
[2022/10/26 02:39:26] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 20 iterations
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/home/sxct-ocr/api/PaddleOCR-release-2.6/tools/program.py", line 299, in train
    preds = model(batch)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 701, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/sxct-ocr/api/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/sxct-ocr/api/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 233, in forward
    relations=x[6])
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1542, in forward
    relations)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1407, in forward
    batch_size, max_length, _ = paddle.shape(entities)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 11402, in shape
    ], 'shape')
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 82, in check_variable_and_dtype
    check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
AttributeError: 'list' object has no attribute 'dtype'
INFO 2022-10-26 02:39:34,715 launch_utils.py:340] terminate all the procs
ERROR 2022-10-26 02:39:34,715 launch_utils.py:603] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-10-26 02:39:38,720 launch_utils.py:340] terminate all the procs
INFO 2022-10-26 02:39:38,720 launch.py:304] Local processes completed.

**Comment by sybest1259** [comment]
配置文件re_vi_layoutxlm_xfund_zh.yml如下：

Global:
  use_gpu: True
  epoch_num: &epoch_num 500
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: /home/models/train_models/re_models/
  save_epoch_step: 100
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [ 0, 20 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: /home/sxct-ocr/static/pic/b201.jpg
  save_res_path: /home/models/train_models/re_models/output
  kie_rec_model_dir: 
  kie_det_model_dir: /home/models/export_models/det/db_plus/inference

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutXLM"
  Transform:
  Backbone:
    name: LayoutXLMForRe
    pretrained: True
    mode: vi
    checkpoints:

Loss:
  name: LossFromOutput
  key: loss
  reduction: mean

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr:
    learning_rate: 0.00005
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: VQAReTokenLayoutLMPostProcess

Metric:
  name: VQAReTokenMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/sxct-ocr/static/invoice/kie
    label_file_list: 
      - /home/sxct-ocr/static/invoice/kie/train.json
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: &class_path /home/sxct-ocr/static/invoice/kie/class_list.txt
          use_textline_bbox_info: &use_textline_bbox_info True
          order_method: &order_method "tb-yx"
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox','attention_mask', 'token_type_ids', 'image', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 2
    num_workers: 4
    collate_fn: ListCollator

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/sxct-ocr/static/invoice/kie
    label_file_list:
      - /home/sxct-ocr/static/invoice/kie/val.json
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: *use_textline_bbox_info
          order_method: *order_method
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 4
    collate_fn: ListCollator

**Comment by sybest1259** [comment]
升级paddlepaddle-gpu到2.3.2

报这个错：
[2022/10/26 08:30:26] ppocr INFO: train dataloader has 4 iters
[2022/10/26 08:30:26] ppocr INFO: valid dataloader has 2 iters
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 173, in main
    model = paddle.DataParallel(model)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 620, in __init__
    sync_params_buffers(self._layers)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 401, in sync_params_buffers
    coalesced_var, src=src_rank, group=comm_group, use_calc_stream=True)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/distributed/collective.py", line 571, in broadcast
    return _C_ops.c_broadcast(tensor, tensor, 'root', gsrc,
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'c_broadcast'

**Comment by andyjpaddle** [comment]
更新一下paddlenlp版本

**Comment by sybest1259** [comment]
paddlenlp=2.3.0.dev0，这是现在的版本，升级到哪个版本呢？

**Comment by andyjpaddle** [comment]
现在应该到2.4了吧

**Comment by sybest1259** [comment]
好的，我试试，非常感谢

**Comment by sybest1259** [comment]
升级了paddlenlp 2.4.1
还是报这个错：AttributeError: 'list' object has no attribute 'dtype'

是不是paddlepaddle-gpu的版本不对？

**Comment by sybest1259** [comment]
把paddlepaddle-gpu升级到2.4.0rc0，报错如下：

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 177, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list)
  File "/home/sxct-ocr/api/PaddleOCR-release-2.6/tools/program.py", line 299, in train
    preds = model(batch)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/sxct-ocr/api/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/sxct-ocr/api/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 233, in forward
    relations=x[6])
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1559, in forward
    relations)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1424, in forward
    batch_size, max_length, _ = paddle.shape(entities)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/tensor/attribute.py", line 118, in shape
    out = _C_ops.shape(input)
ValueError: (InvalidArgument) shape(): argument 'input' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/eager_utils.cc:894)

**Comment by bank010** [comment]
> 把paddlepaddle-gpu升级到2.4.0rc0，报错如下：
> 
> Traceback (most recent call last): File "tools/train.py", line 202, in main(config, device, logger, vdl_writer) File "tools/train.py", line 177, in main eval_class, pre_best_model_dict, logger, vdl_writer, scaler,amp_level, amp_custom_black_list) File "/home/sxct-ocr/api/PaddleOCR-release-2.6/tools/program.py", line 299, in train preds = model(batch) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward outputs = self._layers(*inputs, **kwargs) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/home/sxct-ocr/api/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 86, in forward x = self.backbone(x) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/home/sxct-ocr/api/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 233, in forward relations=x[6]) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1559, in forward relations) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1424, in forward batch_size, max_length, _ = paddle.shape(entities) File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/tensor/attribute.py", line 118, in shape out = _C_ops.shape(input) ValueError: (InvalidArgument) shape(): argument 'input' (position 0) must be Tensor, but got list (at /paddle/paddle/fluid/pybind/eager_utils.cc:894)

楼主，解决这个问题了吗？

**Comment by sybest1259** [comment]
paddlenlp升级到2.4.2试试

**Comment by bank010** [comment]
已经解决发自我的手机-------- 原始邮件 --------发件人： Yu-Song ***@***.***>日期： 2022年12月5日周一 11:21收件人： PaddlePaddle/PaddleOCR ***@***.***>抄送： back ***@***.***>, Comment ***@***.***>主    题： Re: [PaddlePaddle/PaddleOCR] 训练KIE-RE模型，报错AttributeError: 'list' object has no attribute 'dtype' (Issue #8106)

paddlenlp升级到2.4.2试试

**Comment by 1061302569** [comment]
> paddlenlp升级到2.4.2试试

没用的，楼主如何解决的，现在是2.4.2，我所有版本都试过也没用
argument 'input' (position 0) must be Tensor, but got list 
这个错误是什么情况

**Comment by MIKL2077** [comment]
> > paddlenlp升级到2.4.2试试
> 
> 没用的，楼主如何解决的，现在是2.4.7，我所有版本都试过也没用 argument 'input' (position 0) must be Tensor, but got list 这个错误是什么情况
+1
