### ISSUE TITLE
RuntimeError: (NotFound) There are no kernels which are registered in the ceil operator.

### ISSUE THREAD

**Issue by minusplusminus** [PaddlePaddle/PaddleOCR#8118]
Hi everyone, 

I have an issue regarding training based on new set or existing. 

` python3 -m paddle.distributed.launch --gpus '0'  tools/train.py -c en_PP-OCRv3_rec.yml`
and 
`python3 tools/train.py  -c en_PP-OCRv3_rec.yml -o Global.checkpoints=./trained/en_PP-OCRv3_rec_train/best_accuracy`

result in the following error:
```
[2022/10/26 17:25:35] ppocr INFO: Architecture : 
[2022/10/26 17:25:35] ppocr INFO:     Backbone : 
[2022/10/26 17:25:35] ppocr INFO:         last_conv_stride : [1, 2]
[2022/10/26 17:25:35] ppocr INFO:         last_pool_type : avg
[2022/10/26 17:25:35] ppocr INFO:         name : MobileNetV1Enhance
[2022/10/26 17:25:35] ppocr INFO:         scale : 0.5
[2022/10/26 17:25:35] ppocr INFO:     Head : 
[2022/10/26 17:25:35] ppocr INFO:         head_list : 
[2022/10/26 17:25:35] ppocr INFO:             CTCHead : 
[2022/10/26 17:25:35] ppocr INFO:                 Head : 
[2022/10/26 17:25:35] ppocr INFO:                     fc_decay : 1e-05
[2022/10/26 17:25:35] ppocr INFO:                 Neck : 
[2022/10/26 17:25:35] ppocr INFO:                     depth : 2
[2022/10/26 17:25:35] ppocr INFO:                     dims : 64
[2022/10/26 17:25:35] ppocr INFO:                     hidden_dims : 120
[2022/10/26 17:25:35] ppocr INFO:                     name : svtr
[2022/10/26 17:25:35] ppocr INFO:                     use_guide : True
[2022/10/26 17:25:35] ppocr INFO:             SARHead : 
[2022/10/26 17:25:35] ppocr INFO:                 enc_dim : 512
[2022/10/26 17:25:35] ppocr INFO:                 max_text_length : 25
[2022/10/26 17:25:35] ppocr INFO:         name : MultiHead
[2022/10/26 17:25:35] ppocr INFO:     Transform : None
[2022/10/26 17:25:35] ppocr INFO:     algorithm : SVTR
[2022/10/26 17:25:35] ppocr INFO:     model_type : rec
[2022/10/26 17:25:35] ppocr INFO: Eval : 
[2022/10/26 17:25:35] ppocr INFO:     dataset : 
[2022/10/26 17:25:35] ppocr INFO:         data_dir : ./train_data/ic15_data/
[2022/10/26 17:25:35] ppocr INFO:         label_file_list : ['./train_data/ic15_data/rec_gt_test.txt']
[2022/10/26 17:25:35] ppocr INFO:         name : SimpleDataSet
[2022/10/26 17:25:35] ppocr INFO:         transforms : 
[2022/10/26 17:25:35] ppocr INFO:             DecodeImage : 
[2022/10/26 17:25:35] ppocr INFO:                 channel_first : False
[2022/10/26 17:25:35] ppocr INFO:                 img_mode : BGR
[2022/10/26 17:25:35] ppocr INFO:             MultiLabelEncode : None
[2022/10/26 17:25:35] ppocr INFO:             RecResizeImg : 
[2022/10/26 17:25:35] ppocr INFO:                 image_shape : [3, 48, 320]
[2022/10/26 17:25:35] ppocr INFO:             KeepKeys : 
[2022/10/26 17:25:35] ppocr INFO:                 keep_keys : ['image', 'label', 'length']
[2022/10/26 17:25:35] ppocr INFO:     loader : 
[2022/10/26 17:25:35] ppocr INFO:         batch_size_per_card : 128
[2022/10/26 17:25:35] ppocr INFO:         drop_last : False
[2022/10/26 17:25:35] ppocr INFO:         num_workers : 4
[2022/10/26 17:25:35] ppocr INFO:         shuffle : False
[2022/10/26 17:25:35] ppocr INFO: Global : 
[2022/10/26 17:25:35] ppocr INFO:     cal_metric_during_train : True
[2022/10/26 17:25:35] ppocr INFO:     character_dict_path : ppocr/utils/en_dict.txt
[2022/10/26 17:25:35] ppocr INFO:     checkpoints : ./trained/en_PP-OCRv3_rec_train/best_accuracy
[2022/10/26 17:25:35] ppocr INFO:     debug : False
[2022/10/26 17:25:35] ppocr INFO:     distributed : False
[2022/10/26 17:25:35] ppocr INFO:     epoch_num : 500
[2022/10/26 17:25:35] ppocr INFO:     eval_batch_step : [0, 2000]
[2022/10/26 17:25:35] ppocr INFO:     infer_img : doc/imgs_words/en/word_1.jpg
[2022/10/26 17:25:35] ppocr INFO:     infer_mode : False
[2022/10/26 17:25:35] ppocr INFO:     log_smooth_window : 20
[2022/10/26 17:25:35] ppocr INFO:     max_text_length : 25
[2022/10/26 17:25:35] ppocr INFO:     pretrained_model : None
[2022/10/26 17:25:35] ppocr INFO:     print_batch_step : 10
[2022/10/26 17:25:35] ppocr INFO:     save_epoch_step : 3
[2022/10/26 17:25:35] ppocr INFO:     save_inference_dir : None
[2022/10/26 17:25:35] ppocr INFO:     save_model_dir : ./output/v3_en_mobile
[2022/10/26 17:25:35] ppocr INFO:     save_res_path : ./output/rec/predicts_ppocrv3_en.txt
[2022/10/26 17:25:35] ppocr INFO:     use_gpu : True
[2022/10/26 17:25:35] ppocr INFO:     use_space_char : True
[2022/10/26 17:25:35] ppocr INFO:     use_visualdl : False
[2022/10/26 17:25:35] ppocr INFO: Loss : 
[2022/10/26 17:25:35] ppocr INFO:     loss_config_list : 
[2022/10/26 17:25:35] ppocr INFO:         CTCLoss : None
[2022/10/26 17:25:35] ppocr INFO:         SARLoss : None
[2022/10/26 17:25:35] ppocr INFO:     name : MultiLoss
[2022/10/26 17:25:35] ppocr INFO: Metric : 
[2022/10/26 17:25:35] ppocr INFO:     ignore_space : False
[2022/10/26 17:25:35] ppocr INFO:     main_indicator : acc
[2022/10/26 17:25:35] ppocr INFO:     name : RecMetric
[2022/10/26 17:25:35] ppocr INFO: Optimizer : 
[2022/10/26 17:25:35] ppocr INFO:     beta1 : 0.9
[2022/10/26 17:25:35] ppocr INFO:     beta2 : 0.999
[2022/10/26 17:25:35] ppocr INFO:     lr : 
[2022/10/26 17:25:35] ppocr INFO:         learning_rate : 0.001
[2022/10/26 17:25:35] ppocr INFO:         name : Cosine
[2022/10/26 17:25:35] ppocr INFO:         warmup_epoch : 5
[2022/10/26 17:25:35] ppocr INFO:     name : Adam
[2022/10/26 17:25:35] ppocr INFO:     regularizer : 
[2022/10/26 17:25:35] ppocr INFO:         factor : 3e-05
[2022/10/26 17:25:35] ppocr INFO:         name : L2
[2022/10/26 17:25:35] ppocr INFO: PostProcess : 
[2022/10/26 17:25:35] ppocr INFO:     name : CTCLabelDecode
[2022/10/26 17:25:35] ppocr INFO: Train : 
[2022/10/26 17:25:35] ppocr INFO:     dataset : 
[2022/10/26 17:25:35] ppocr INFO:         data_dir : ./train_data/ic15_data/
[2022/10/26 17:25:35] ppocr INFO:         label_file_list : ['./train_data/ic15_data/rec_gt_train.txt']
[2022/10/26 17:25:35] ppocr INFO:         name : SimpleDataSet
[2022/10/26 17:25:35] ppocr INFO:         transforms : 
[2022/10/26 17:25:35] ppocr INFO:             DecodeImage : 
[2022/10/26 17:25:35] ppocr INFO:                 channel_first : False
[2022/10/26 17:25:35] ppocr INFO:                 img_mode : BGR
[2022/10/26 17:25:35] ppocr INFO:             CTCLabelEncode : None
[2022/10/26 17:25:35] ppocr INFO:             RecResizeImg : 
[2022/10/26 17:25:35] ppocr INFO:                 image_shape : [3, 48, 320]
[2022/10/26 17:25:35] ppocr INFO:             KeepKeys : 
[2022/10/26 17:25:35] ppocr INFO:                 keep_keys : ['image', 'label', 'length']
[2022/10/26 17:25:35] ppocr INFO:     loader : 
[2022/10/26 17:25:35] ppocr INFO:         batch_size_per_card : 64
[2022/10/26 17:25:35] ppocr INFO:         drop_last : True
[2022/10/26 17:25:35] ppocr INFO:         num_workers : 8
[2022/10/26 17:25:35] ppocr INFO:         shuffle : True
[2022/10/26 17:25:35] ppocr INFO:         use_shared_memory : False
[2022/10/26 17:25:35] ppocr INFO: profiler_options : None
[2022/10/26 17:25:35] ppocr INFO: train with paddle 2.3.2 and device Place(gpu:0)
[2022/10/26 17:25:35] ppocr INFO: Initialize indexs of datasets:['./train_data/ic15_data/rec_gt_train.txt']
[2022/10/26 17:25:35] ppocr INFO: Initialize indexs of datasets:['./train_data/ic15_data/rec_gt_test.txt']
W1026 17:25:35.755965  8599 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W1026 17:25:35.756711  8599 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
[2022/10/26 17:25:36] ppocr INFO: resume from ./trained/en_PP-OCRv3_rec_train/best_accuracy
[2022/10/26 17:25:36] ppocr INFO: train dataloader has 76 iters
[2022/10/26 17:25:36] ppocr INFO: valid dataloader has 17 iters
[2022/10/26 17:25:36] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Tensor(shape=[1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [280])
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 166, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/martijn/development/PaddleOCR/tools/program.py", line 262, in train
    preds = model(images, data=batch[1:])
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 85, in forward
    x = self.head(x, targets=data)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/heads/rec_multi_head.py", line 69, in forward
    sar_out = self.sar_head(x, targets[1:])
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 400, in forward
    holistic_feat = self.encoder(feat, targets)  # bsz c
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 106, in forward
    c =  paddle.ceil(valid_ratios[i] * T).astype('int32')
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 269, in func
    return op(x)
RuntimeError: (NotFound) There are no kernels which are registered in the ceil operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < ceil > error]
```

When I execute 
```
import paddle

x = paddle.to_tensor([[-1.5,6], [1,15.6]])
res = paddle.ceil(x).astype('int32')
print(res)
```
returns
```
Tensor(shape=[2, 2], dtype=int32, place=Place(gpu:0), stop_gradient=True,
       [[-1,  6],
        [ 1, 16]])
```
so that works correct. 

and when i execute
`python3 -m paddle.distributed.launch --gpus '0'  tools/train.py -c configs/rec/rec_icdar15_train.yml` 
 works correct too. 

Could this possibly be related to GPU limitations? 

- 系统环境/System Environment：
- Ubuntu 18.04
- RTX 2060 with 5gb mem

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- paddle: paddlepaddle-gpu 2.3.2
- paddleOCR: 2.6

**Comment by andyjpaddle** [comment]
try run `python3 tools/train.py -c en_PP-OCRv3_rec.yml`

**Comment by minusplusminus** [comment]
hi, I just changed to ubuntu 20.04 and 11.2 to validate if the issue still exists
installed with: 
```
python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
tested:
```
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1103 16:18:30.558614 929558 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.8, Runtime API Version: 11.2
W1103 16:18:31.094717 929558 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

```
and executed above command I get this
```
python3 tools/train.py -c en_PP-OCRv3_rec.yml

[2022/11/03 16:24:48] ppocr INFO: Architecture : 
[2022/11/03 16:24:48] ppocr INFO:     Backbone : 
[2022/11/03 16:24:48] ppocr INFO:         last_conv_stride : [1, 2]
[2022/11/03 16:24:48] ppocr INFO:         last_pool_type : avg
[2022/11/03 16:24:48] ppocr INFO:         name : MobileNetV1Enhance
[2022/11/03 16:24:48] ppocr INFO:         scale : 0.5
[2022/11/03 16:24:48] ppocr INFO:     Head : 
[2022/11/03 16:24:48] ppocr INFO:         head_list : 
[2022/11/03 16:24:48] ppocr INFO:             CTCHead : 
[2022/11/03 16:24:48] ppocr INFO:                 Head : 
[2022/11/03 16:24:48] ppocr INFO:                     fc_decay : 1e-05
[2022/11/03 16:24:48] ppocr INFO:                 Neck : 
[2022/11/03 16:24:48] ppocr INFO:                     depth : 2
[2022/11/03 16:24:48] ppocr INFO:                     dims : 64
[2022/11/03 16:24:48] ppocr INFO:                     hidden_dims : 120
[2022/11/03 16:24:48] ppocr INFO:                     name : svtr
[2022/11/03 16:24:48] ppocr INFO:                     use_guide : True
[2022/11/03 16:24:48] ppocr INFO:             SARHead : 
[2022/11/03 16:24:48] ppocr INFO:                 enc_dim : 512
[2022/11/03 16:24:48] ppocr INFO:                 max_text_length : 25
[2022/11/03 16:24:48] ppocr INFO:         name : MultiHead
[2022/11/03 16:24:48] ppocr INFO:     Transform : None
[2022/11/03 16:24:48] ppocr INFO:     algorithm : SVTR
[2022/11/03 16:24:48] ppocr INFO:     model_type : rec
[2022/11/03 16:24:48] ppocr INFO: Eval : 
[2022/11/03 16:24:48] ppocr INFO:     dataset : 
[2022/11/03 16:24:48] ppocr INFO:         data_dir : ./train_data/ic15_data/
[2022/11/03 16:24:48] ppocr INFO:         label_file_list : ['./train_data/ic15_data/rec_gt_test.txt']
[2022/11/03 16:24:48] ppocr INFO:         name : SimpleDataSet
[2022/11/03 16:24:48] ppocr INFO:         transforms : 
[2022/11/03 16:24:48] ppocr INFO:             DecodeImage : 
[2022/11/03 16:24:48] ppocr INFO:                 channel_first : False
[2022/11/03 16:24:48] ppocr INFO:                 img_mode : BGR
[2022/11/03 16:24:48] ppocr INFO:             MultiLabelEncode : None
[2022/11/03 16:24:48] ppocr INFO:             RecResizeImg : 
[2022/11/03 16:24:48] ppocr INFO:                 image_shape : [3, 48, 320]
[2022/11/03 16:24:48] ppocr INFO:             KeepKeys : 
[2022/11/03 16:24:48] ppocr INFO:                 keep_keys : ['image', 'label', 'length']
[2022/11/03 16:24:48] ppocr INFO:     loader : 
[2022/11/03 16:24:48] ppocr INFO:         batch_size_per_card : 128
[2022/11/03 16:24:48] ppocr INFO:         drop_last : False
[2022/11/03 16:24:48] ppocr INFO:         num_workers : 4
[2022/11/03 16:24:48] ppocr INFO:         shuffle : False
[2022/11/03 16:24:48] ppocr INFO: Global : 
[2022/11/03 16:24:48] ppocr INFO:     cal_metric_during_train : True
[2022/11/03 16:24:48] ppocr INFO:     character_dict_path : ppocr/utils/en_dict.txt
[2022/11/03 16:24:48] ppocr INFO:     checkpoints : None
[2022/11/03 16:24:48] ppocr INFO:     debug : False
[2022/11/03 16:24:48] ppocr INFO:     distributed : False
[2022/11/03 16:24:48] ppocr INFO:     epoch_num : 500
[2022/11/03 16:24:48] ppocr INFO:     eval_batch_step : [0, 2000]
[2022/11/03 16:24:48] ppocr INFO:     infer_img : doc/imgs_words/en/word_1.jpg
[2022/11/03 16:24:48] ppocr INFO:     infer_mode : False
[2022/11/03 16:24:48] ppocr INFO:     log_smooth_window : 20
[2022/11/03 16:24:48] ppocr INFO:     max_text_length : 25
[2022/11/03 16:24:48] ppocr INFO:     pretrained_model : None
[2022/11/03 16:24:48] ppocr INFO:     print_batch_step : 10
[2022/11/03 16:24:48] ppocr INFO:     save_epoch_step : 3
[2022/11/03 16:24:48] ppocr INFO:     save_inference_dir : None
[2022/11/03 16:24:48] ppocr INFO:     save_model_dir : ./output/v3_en_mobile
[2022/11/03 16:24:48] ppocr INFO:     save_res_path : ./output/rec/predicts_ppocrv3_en.txt
[2022/11/03 16:24:48] ppocr INFO:     use_gpu : True
[2022/11/03 16:24:48] ppocr INFO:     use_space_char : True
[2022/11/03 16:24:48] ppocr INFO:     use_visualdl : False
[2022/11/03 16:24:48] ppocr INFO: Loss : 
[2022/11/03 16:24:48] ppocr INFO:     loss_config_list : 
[2022/11/03 16:24:48] ppocr INFO:         CTCLoss : None
[2022/11/03 16:24:48] ppocr INFO:         SARLoss : None
[2022/11/03 16:24:48] ppocr INFO:     name : MultiLoss
[2022/11/03 16:24:48] ppocr INFO: Metric : 
[2022/11/03 16:24:48] ppocr INFO:     ignore_space : False
[2022/11/03 16:24:48] ppocr INFO:     main_indicator : acc
[2022/11/03 16:24:48] ppocr INFO:     name : RecMetric
[2022/11/03 16:24:48] ppocr INFO: Optimizer : 
[2022/11/03 16:24:48] ppocr INFO:     beta1 : 0.9
[2022/11/03 16:24:48] ppocr INFO:     beta2 : 0.999
[2022/11/03 16:24:48] ppocr INFO:     lr : 
[2022/11/03 16:24:48] ppocr INFO:         learning_rate : 0.001
[2022/11/03 16:24:48] ppocr INFO:         name : Cosine
[2022/11/03 16:24:48] ppocr INFO:         warmup_epoch : 5
[2022/11/03 16:24:48] ppocr INFO:     name : Adam
[2022/11/03 16:24:48] ppocr INFO:     regularizer : 
[2022/11/03 16:24:48] ppocr INFO:         factor : 3e-05
[2022/11/03 16:24:48] ppocr INFO:         name : L2
[2022/11/03 16:24:48] ppocr INFO: PostProcess : 
[2022/11/03 16:24:48] ppocr INFO:     name : CTCLabelDecode
[2022/11/03 16:24:48] ppocr INFO: Train : 
[2022/11/03 16:24:48] ppocr INFO:     dataset : 
[2022/11/03 16:24:48] ppocr INFO:         data_dir : ./train_data/ic15_data/
[2022/11/03 16:24:48] ppocr INFO:         label_file_list : ['./train_data/ic15_data/rec_gt_train.txt']
[2022/11/03 16:24:48] ppocr INFO:         name : SimpleDataSet
[2022/11/03 16:24:48] ppocr INFO:         transforms : 
[2022/11/03 16:24:48] ppocr INFO:             DecodeImage : 
[2022/11/03 16:24:48] ppocr INFO:                 channel_first : False
[2022/11/03 16:24:48] ppocr INFO:                 img_mode : BGR
[2022/11/03 16:24:48] ppocr INFO:             CTCLabelEncode : None
[2022/11/03 16:24:48] ppocr INFO:             RecResizeImg : 
[2022/11/03 16:24:48] ppocr INFO:                 image_shape : [3, 48, 320]
[2022/11/03 16:24:48] ppocr INFO:             KeepKeys : 
[2022/11/03 16:24:48] ppocr INFO:                 keep_keys : ['image', 'label', 'length']
[2022/11/03 16:24:48] ppocr INFO:     loader : 
[2022/11/03 16:24:48] ppocr INFO:         batch_size_per_card : 64
[2022/11/03 16:24:48] ppocr INFO:         drop_last : True
[2022/11/03 16:24:48] ppocr INFO:         num_workers : 8
[2022/11/03 16:24:48] ppocr INFO:         shuffle : True
[2022/11/03 16:24:48] ppocr INFO:         use_shared_memory : False
[2022/11/03 16:24:48] ppocr INFO: profiler_options : None
[2022/11/03 16:24:48] ppocr INFO: train with paddle 2.3.1 and device Place(gpu:0)
[2022/11/03 16:24:48] ppocr INFO: Initialize indexs of datasets:['./train_data/ic15_data/rec_gt_train.txt']
[2022/11/03 16:24:48] ppocr INFO: Initialize indexs of datasets:['./train_data/ic15_data/rec_gt_test.txt']
W1103 16:24:48.973866 931158 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.8, Runtime API Version: 11.2
W1103 16:24:48.976385 931158 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[2022/11/03 16:24:49] ppocr INFO: train from scratch
[2022/11/03 16:24:49] ppocr INFO: train dataloader has 76 iters
[2022/11/03 16:24:49] ppocr INFO: valid dataloader has 17 iters
[2022/11/03 16:24:49] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Tensor(shape=[1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [280])
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 166, in main
    eval_class, pre_best_model_dict, logger, vdl_writer, scaler)
  File "/home/martijn/development/PaddleOCR/tools/program.py", line 262, in train
    preds = model(images, data=batch[1:])
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 85, in forward
    x = self.head(x, targets=data)
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/heads/rec_multi_head.py", line 69, in forward
    sar_out = self.sar_head(x, targets[1:])
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 400, in forward
    holistic_feat = self.encoder(feat, targets)  # bsz c
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/martijn/development/PaddleOCR/ppocr/modeling/heads/rec_sar_head.py", line 106, in forward
    c =  paddle.ceil(valid_ratios[i] * T).astype('int32')
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 269, in func
    return op(x)
RuntimeError: (NotFound) There are no kernels which are registered in the ceil operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:327)
  [operator < ceil > error]

```

**Comment by andyjpaddle** [comment]
make sure only one version paddlepaddle is installed
try to decrease `num_workers`
