### ISSUE TITLE
安装hub install stylepro_artistic报错：ModuleNotFoundError: No module named 'paddle'

### ISSUE THREAD

**Issue by sshappys** [PaddlePaddle/PaddleOCR#8161]
安装hub install stylepro_artistic时报错：ModuleNotFoundError: No module named 'paddle'
详情：
Traceback (most recent call last):
  File "D:\myAi\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\myAi\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\myAi\anaconda3\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "D:\myAi\anaconda3\lib\site-packages\paddlehub\__init__.py", line 18, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

**Comment by sshappys** [comment]
已解决，也是安装问题，重新安装paddlepaddle
