### ISSUE TITLE
libgeos_c.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/PaddleOCR#8200]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：jetson arrch 64
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：import paddleocr
- 完整报错/Complete Error Message：
`
```
Python 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddleocr

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/project/PaddleOCR/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "/home/nvidia/project/PaddleOCR/tools/infer/predict_system.py", line 32, in <module>
    import tools.infer.predict_rec as predict_rec
  File "/home/nvidia/project/PaddleOCR/tools/infer/predict_rec.py", line 31, in <module>
    from ppocr.postprocess import build_post_process
  File "/home/nvidia/project/PaddleOCR/ppocr/postprocess/__init__.py", line 24, in <module>
    from .db_postprocess import DBPostProcess, DistillationDBPostProcess
  File "/home/nvidia/project/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 25, in <module>
    from shapely.geometry import Polygon
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/site-packages/shapely/geos.py", line 94, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/nvidia/archiconda3/envs/python36/lib/libgeos_c.so: cannot open shared object file: No such file or directory
>>>
`
机器为jetson arrch 64系统，jetpack 4.4.
根据官方编译好的whl文件（[Jetpack4.5(4.4): [nv_jetson-cuda10.2-trt7-xavier](https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python)）,安装好PaddlePaddle, 调用没问题，
然后使用pip install paddleocr（不知道其他安装方式）,最终import 出错

**Comment by Biaocsu** [comment]
如果不安装paddleocr, 通过git clone https://github.com/PaddlePaddle/PaddleOCR
然后pip install -r requirements.txt
运行tools/infer项目下predict_system.py文件，仍然出现相同问题。

请问我应该怎样才能调用该项目呢？例如怎样才能正常调用predict_system.py

**Comment by andyjpaddle** [comment]
推荐python3.7，3.6后续不再维护，另外要先安装paddle再安装paddleocr

**Comment by tikboaHIT** [comment]
> 如果不安装paddleocr, 通过git clone https://github.com/PaddlePaddle/PaddleOCR 然后pip install -r requirements.txt 运行tools/infer项目下predict_system.py文件，仍然出现相同问题。
> 
> 请问我应该怎样才能调用该项目呢？例如怎样才能正常调用predict_system.py

Hi 这个问题你解决了吗？

**Comment by BenjiaminLiu** [comment]
解决了，先自己安装paddlepaddle， 不用安装paddleocr，自己根据代码调用可以跑通

**Comment by 1556900941lizerui** [comment]
我遇到了同样的问题，但是没有解决：
Traceback (most recent call last):
  File "ppocrv4_server.py", line 4, in <module>
    from paddleocr import PaddleOCR
  File "/home/dzint/ocr_test/PaddleOCR-main/paddleocr.py", line 64, in <module>
    from tools.infer import predict_system
  File "/home/dzint/ocr_test/PaddleOCR-main/tools/infer/predict_system.py", line 32, in <module>
    import tools.infer.predict_rec as predict_rec
  File "/home/dzint/ocr_test/PaddleOCR-main/tools/infer/predict_rec.py", line 32, in <module>
    from ppocr.postprocess import build_post_process
  File "/home/dzint/ocr_test/PaddleOCR-main/ppocr/postprocess/__init__.py", line 25, in <module>
    from .db_postprocess import DBPostProcess, DistillationDBPostProcess
  File "/home/dzint/ocr_test/PaddleOCR-main/ppocr/postprocess/db_postprocess.py", line 25, in <module>
    from shapely.geometry import Polygon
  File "/home/dzint/archiconda3/envs/ocr/lib/python3.6/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/dzint/archiconda3/envs/ocr/lib/python3.6/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/dzint/archiconda3/envs/ocr/lib/python3.6/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/home/dzint/archiconda3/envs/ocr/lib/python3.6/site-packages/shapely/geos.py", line 94, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/home/dzint/archiconda3/envs/ocr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dzint/archiconda3/envs/ocr/lib/libgeos_c.so: cannot open shared object file: No such file or directory

机器为jetson arrch 64系统，jetpack 4.6.6
根据官方编译好的whl文件(https://paddle-inference-lib.bj.bcebos.com/2.3.2/python/Jetson/jetpack4.6_gcc7.5/tx2/paddlepaddle_gpu-2.3.2-cp36-cp36m-linux_aarch64.whl#python)）,安装好PaddlePaddle, 调用没问题，
然后使用git clone paddleocr项目,最终import 出错
