### ISSUE TITLE
ppstructure识别表格出错，IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by Priest2wyw** [PaddlePaddle/PaddleOCR#8205]
我尝试了很多次，都是这个错误，搜索也没有找到解决办法，可以帮我看一下吗。非常感谢。

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：`Linux version 5.4.0-122-generic (buildd@lcy02-amd64-095) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1))`
- 版本号/Version：Paddle：`paddlepaddle-gpu 2.3.2.post101`  PaddleOCR：`2.6.1.0` 问题相关组件/Related components：
- 运行指令/Command Code：
```python
import os
import cv2
from paddleocr import PPStructure,save_structure_res

table_engine = PPStructure(layout=False, show_log=True)

save_folder = './output'
img_path = 'ppstructure/docs/table/table.jpg'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)
```
- 完整报错/Complete Error Message：
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [2], line 10
      8 img_path = '/storage/home/someone/PaddleOCR/ppstructure/docs/table/table.jpg'
      9 img = cv2.imread(img_path)
---> 10 result = table_engine(img)
     11 save_structure_res(result, save_folder, os.path.basename(img_path).split('.')[0])
     13 for line in result:

File ~/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/paddleocr.py:624, in PPStructure.__call__(self, img, return_ocr_result_in_table, img_idx)
    [622](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/paddleocr.py?line=621) def __call__(self, img, return_ocr_result_in_table=False, img_idx=0):
    [623](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/paddleocr.py?line=622)     img = check_img(img)
--> [624](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/paddleocr.py?line=623)     res, _ = super().__call__(
    [625](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/paddleocr.py?line=624)         img, return_ocr_result_in_table, img_idx=img_idx)
    [626](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/paddleocr.py?line=625)     return res

File ~/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py:129, in StructureSystem.__call__(self, img, return_ocr_result_in_table, img_idx)
    [127](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py?line=126) if region['label'] == 'table':
    [128](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py?line=127)     if self.table_system is not None:
--> [129](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py?line=128)         res, table_time_dict = self.table_system(
    [130](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py?line=129)             roi_img, return_ocr_result_in_table)
    [131](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py?line=130)         time_dict['table'] += table_time_dict['table']
    [132](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/predict_system.py?line=131)         time_dict['table_match'] += table_time_dict['match']

File ~/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/predict_table.py:100, in TableSystem.__call__(self, img, return_ocr_result_in_table)
     [97](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/predict_table.py?line=96)     result['rec_res'] = rec_res
     [99](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/predict_table.py?line=98) tic = time.time()
--> [100](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/predict_table.py?line=99) pred_html = self.match(structure_res, dt_boxes, rec_res)
    [101](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/predict_table.py?line=100) toc = time.time()
    [102](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/predict_table.py?line=101) time_dict['match'] = toc - tic

File ~/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py:65, in TableMatch.__call__(self, structure_res, dt_boxes, rec_res)
     [63](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=62) pred_structures, pred_bboxes = structure_res
     [64](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=63) if self.filter_ocr_result:
---> [65](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=64)     dt_boxes, rec_res = self._filter_ocr_result(pred_bboxes, dt_boxes,
     [66](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=65)                                                 rec_res)
     [67](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=66) matched_index = self.match_result(dt_boxes, pred_bboxes)
     [68](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=67) if self.use_master:

File ~/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py:183, in TableMatch._filter_ocr_result(self, pred_bboxes, dt_boxes, rec_res)
    [182](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=181) def _filter_ocr_result(self, pred_bboxes, dt_boxes, rec_res):
--> [183](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=182)     y1 = pred_bboxes[:, 1::2].min()
    [184](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=183)     new_dt_boxes = []
    [185](file:///storage/home/someone/anaconda/envs/ppocr/lib/python3.9/site-packages/paddleocr/ppstructure/table/matcher.py?line=184)     new_rec_res = []

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by WenmuZhou** [comment]
你好，我这边同样的版本，未能复现问题

**Comment by Priest2wyw** [comment]
邮件已收到

**Comment by Priest2wyw** [comment]
邮件已收到

**Comment by zyzz1974** [comment]
请问是怎么解决的，我也出现这样的问题

**Comment by Priest2wyw** [comment]
邮件已收到

**Comment by Priest2wyw** [comment]
> 

我更新过cuda版本之后，就好了

**Comment by Priest2wyw** [comment]
我在更新过 cuda 版本之后，就没这方面问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] ppstructure识别表格出错，IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed (Issue #8205)





 
请问是怎么解决的，我也出现这样的问题

**Comment by s957995299** [comment]
> 我在更新过 cuda 版本之后，就没这方面问题了。
请问您是更新到什么版本

**Comment by Priest2wyw** [comment]
邮件已收到

**Comment by Priest2wyw** [comment]
> > 我在更新过 cuda 版本之后，就没这方面问题了。
> > 请问您是更新到什么版本

CUDA Version: 11.7， nvcc 10.1

**Comment by Katherinaxxx** [comment]
cuda 12.3 nvcc11.3同样报错

**Comment by rudra0713** [comment]
Hi, has this issue been resolved? 
I am trying the following command:
`
python3 table/predict_table.py  --image_dir=/scratch/rrs99/PaddleOCR/ppstructure/page_4.jpg \
                                --det_limit_side_len=736 \
                                --rec_model_dir=/scratch/rrs99/PaddleOCR/ppstructure/inference/en_ppocr_mobile_v2.0_table_rec_infer \
                                --table_model_dir=/scratch/rrs99/PaddleOCR/ppstructure/inference/en_ppocr_mobile_v2.0_table_structure_infer \
                                --det_model_dir=/scratch/rrs99/PaddleOCR/ppstructure/inference/en_ppocr_mobile_v2.0_table_det_infer \
                                --rec_char_dict_path=/scratch/rrs99/PaddleOCR/ppocr/utils/dict/table_dict.txt \
                                --table_char_dict_path=/scratch/rrs99/PaddleOCR/ppocr/utils/dict/table_structure_dict.txt \
                                --det_limit_type=min \
                                --output=/scratch/rrs99/PaddleOCR/ppstructure/output/table
`
The error I am getting:
`
Traceback (most recent call last):
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/predict_table.py", line 241, in <module>
    main(args)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/predict_table.py", line 189, in main
    pred_res, _ = table_sys(img)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/predict_table.py", line 109, in __call__
    pred_html = self.match(structure_res, dt_boxes, rec_res)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/matcher.py", line 65, in __call__
    dt_boxes, rec_res = self._filter_ocr_result(pred_bboxes, dt_boxes, rec_res)
  File "/scratch/rrs99/PaddleOCR/ppstructure/table/matcher.py", line 194, in _filter_ocr_result
    y1 = pred_bboxes[:, 1::2].min()
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
`

**Comment by jacarrichan** [comment]
如果报错，先用paddle自带的图片试试。我今天碰到了，是自己的图片格式有问题。
