### ISSUE TITLE
can not install PPOCRLabel on mac m1

### ISSUE THREAD

**Issue by Yosiiiiiiiiiiiiiiii** [PaddlePaddle/PaddleOCR#8213]
System Environment：python 3.7
Complete Error Message：
when i run `python3 PPOCRLabel.py ` in terminal and i got this error :
`/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Loading setting failed
Traceback (most recent call last):
  File "PPOCRLabel.py", line 2849, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 2837, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 2830, in get_main_app
    default_predefined_class_file=args.predefined_classes_file)
  File "PPOCRLabel.py", line 103, in __init__
    show_log=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 503, in __init__
    self.page_num = params.page_num
AttributeError: 'Namespace' object has no attribute 'page_num'`

**Comment by Evezerest** [comment]
try: pip install paddleocr==2.6.0.0
