### ISSUE TITLE
layoutlmv2进行ser+re联合推理出错（单独ser推理正常），权重均来自于官方。layoutxlm和vi_layoutxlm均能正常推理。

### ISSUE THREAD

**Issue by Qiang-HU** [PaddlePaddle/PaddleOCR#8226]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：2.0 Paddle：2.3  PaddleOCR：2.6 问题相关组件/Related components：
- 运行指令/Command Code：
- python tools/infer_kie_token_ser_re.py -c configs/kie/layoutlm_series/re_layoutlmv2_xfund_zh.yml -o Architecture.Backbone.checkpoints=./per_weights/re_LayoutLMv2_xfun_zh/ Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg Global_mode=False -c_ser configs/kie/layoutlm_series/ser_layoutlmv2_xfund_zh.yml -o_ser Architecture.Backbone.checkpoints=./per_weights/ser_LayoutLMv2_xfun_zh/
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/infer_kie_token_ser_re.py", line 220, in <module>
    result = ser_re_engine(data)
  File "tools/infer_kie_token_ser_re.py", line 154, in __call__
    preds = self.model(re_input)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/Paddle_Model/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/Paddle_Model/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 194, in forward
    x = self.model(
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddlenlp/transformers/layoutlmv2/modeling.py", line 1419, in forward
    loss, pred_relations = self.extractor(sequence_output, entities,
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddlenlp/transformers/layoutlmv2/modeling.py", line 1295, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddlenlp/transformers/layoutlmv2/modeling.py", line 1245, in build_relation
    if len(entities[b]["start"]) <= 2:
  File "/home/.pyenv/versions/KIE/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 740, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received str in 1th slice item (at /paddle/paddle/fluid/pybind/slice_utils.h:279)

**Comment by an1018** [comment]
把Global_mode=False去掉试试呢

**Comment by Qiang-HU** [comment]
没有效果，还是同样报错。

**Comment by an1018** [comment]
@littletomatodonkey 看一下呢

**Comment by DYF-AI** [comment]
同样的报错

**Comment by rexzhengzhihong** [comment]
同样的报错

**Comment by harshsummit** [comment]
Same error
