### ISSUE TITLE
测试关键信息抽取

### ISSUE THREAD

**Issue by forword-1234** [PaddlePaddle/PaddleOCR#8306]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20
- 版本号/Version：Paddle：2.3  PaddleOCR：2.6 问题相关组件/Related components：python ./tools/infer_kie_token_ser_re.py
- 运行指令/Command Code：python ./tools/infer_kie_token_ser_re.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "./tools/infer_kie_token_ser_re.py", line 220, in <module>
    result = ser_re_engine(data)
  File "./tools/infer_kie_token_ser_re.py", line 154, in __call__
    preds = self.model(re_input)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\code\PaddlePaddle\PaddleOCR-release-2.6\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\code\PaddlePaddle\PaddleOCR-release-2.6\ppocr\modeling\backbones\vqa_layoutlm.py", line 227, in forward
    x = self.model(
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1427, in forward
    loss, pred_relations = self.extractor(sequence_output, entities,
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1305, in forward
    relations, entities = self.build_relation(relations, entities)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1258, in build_relation
    if len(entities[b]["start"]) <= 2:
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 598, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received str in 1th slice item (at ..\paddle\fluid\pybind\imperative.cc:644)

**Comment by DYF-AI** [comment]
你好，我的也是同样报错，请问你解决了吗
