### ISSUE TITLE
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.

### ISSUE THREAD

**Issue by sunwei317** [PaddlePaddle/PaddleOCR#8307]
In MacOs, docker compose two containers, one contains paddleocr (**Container1**), and the other is for other application  (**Container2**). 

**Container1**: 
paddle-bfloat            0.1.7
paddleclas               2.5.0
paddleocr                2.6.1.0
paddlepaddle             2.3.2

**Problem:** 
From Container2, run paddleorc in Container1,  the error is as follows:

/venv/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module\'s documentation for alternative uses
  
import imp
Traceback (most recent call last):
  File "/venv/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 644, in main
    engine = PPStructure(**(args.__dict__))
  File "/venv/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 620, in __init__
    super().__init__(params)
  File "/venv/lib/python3.6/site-packages/paddleocr/ppstructure/predict_system.py", line 67, in __init__
    self.layout_predictor = LayoutPredictor(args)
  File "/venv/lib/python3.6/site-packages/paddleocr/ppstructure/layout/predict_layout.py", line 68, in __init__
    utility.create_predictor(args, \'layout\', logger)
  File "/venv/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 277, in create_predictor
    **predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.**
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

****However, after running 'docker exec -it Container1 bash', running paddleocr has no problem.****

**Comment by sunwei317** [comment]
For case, I found out paddleorc cannot find the model paths for some reason. So, after setting model paths in the command, everything runs as expected.
