### ISSUE TITLE
部署异常：hub install deploy/hubserving/ocr_system

### ISSUE THREAD

**Issue by tingxiao88** [PaddlePaddle/PaddleOCR#8327]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6  问题相关组件/Related components：paddlehub 2.1.0
- 运行指令/Command Code：hub install deploy/hubserving/ocr_system/
- 完整报错/Complete Error Message：

hub install deploy/hubserving/ocr_system/
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/usr/lib/python3/dist-packages/requests/__init__.py:95: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib import pyopenssl
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/commands/install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/module/manager.py", line 177, in install
    with lock:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/filelock/_api.py", line 220, in __enter__
    self.acquire()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/filelock/_api.py", line 173, in acquire
    self._acquire()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.paddlehub/tmp/deploy/hubserving/ocr_system/'

**Comment by jingsongliujing** [comment]
hub install 后面直接跟模型就好了，详情看这个：https://www.paddlepaddle.org.cn/hubdetail?name=chinese_ocr_db_crnn_server&en_category=TextRecognition
