### ISSUE TITLE
安装完paddleocr后运行报错

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleOCR#833]
当我使用pip install paddleocr后，运行报错，报错如下：
```
Traceback (most recent call last):
  File ".\Main.py", line 11, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\paddleocr\__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\paddleocr\paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 26, in <module>
    import tools.infer.predict_det as predict_det
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 35, in <module>
    from ppocr.data.det.db_process import DBProcessTest
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\paddleocr\ppocr\data\det\db_process.py", line 25, in <module>
    from .make_shrink_map import MakeShrinkMap
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\paddleocr\ppocr\data\det\make_shrink_map.py", line 10, in <module>
    from shapely.geometry import Polygon
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\thugbobby\anaconda3\envs\ocr\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
```
已经安装paddlepaddle可以正常运行的
![image](https://user-images.githubusercontent.com/68416779/94111902-3dd2a600-fe77-11ea-8c26-c2a8a239d34f.png)
请问如何解决？

**Comment by WenmuZhou** [comment]
你这好像是shapely没装好

**Comment by zhaobingkun** [comment]
是shapely没装好，https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely 手动下载安装可以解决这个问题。
