### ISSUE TITLE
训练时报错，python版本不匹配

### ISSUE THREAD

**Issue by namemzy** [PaddlePaddle/PaddleOCR#8333]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu 20.04  
official docker：paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8.2-gcc82
4x3090 GPU
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
appdirs               1.4.4
asn1crypto            0.24.0
aspy.yaml             1.3.0
astor                 0.8.1
astroid               2.5.1
attrdict              2.0.1
attrs                 20.3.0
Babel                 2.10.3
bce-python-sdk        0.8.73
cached-property       1.5.2
cachetools            5.2.0
certifi               2020.12.5
cfgv                  3.2.0
chardet               4.0.0
click                 8.1.3
contourpy             1.0.6
cryptography          2.1.4
cssselect             1.1.0
cssutils              2.6.0
cycler                0.11.0
Cython                0.29.30
decorator             4.4.2
dill                  0.3.5.1
distlib               0.3.1
et-xmlfile            1.1.0
filelock              3.0.12
Flask                 2.1.3
Flask-Babel           2.0.0
fonttools             4.38.0
future                0.18.2
gast                  0.4.0
identify              2.2.0
idna                  2.10
imageio               2.22.4
imgaug                0.4.0
importlib-metadata    5.0.0
iniconfig             1.1.1
ipykernel             4.6.0
ipython               5.3.0
ipython-genutils      0.2.0
isort                 5.8.0
itsdangerous          2.1.2
Jinja2                3.1.2
jupyter-client        6.1.12
jupyter-core          4.7.1
keyring               10.6.0
keyrings.alt          3.0
kiwisolver            1.4.4
lanms                 1.0.2
lazy-object-proxy     1.5.2
lmdb                  1.3.0
lxml                  4.9.1
MarkupSafe            2.1.1
matplotlib            3.6.2
mccabe                0.6.1
multiprocess          0.70.13
networkx              2.8.8
nodeenv               1.5.0
numpy                 1.23.3
opencv-contrib-python 4.6.0.66
opencv-python         4.6.0.66
openpyxl              3.0.10
opt-einsum            3.3.0
packaging             20.9
paddle-bfloat         0.1.7
paddleocr             2.6.0.1
paddlepaddle-gpu      2.3.2
pandas                1.5.0
pexpect               4.8.0
pickleshare           0.7.5
Pillow                9.3.0
pip                   22.3.1
pluggy                0.13.1
Polygon3              3.0.9.1
pre-commit            1.10.4
premailer             3.10.0
prompt-toolkit        1.0.18
protobuf              3.15.6
ptyprocess            0.7.0
py                    1.10.0
pyclipper             1.3.0.post3
pycrypto              2.6.1
pycryptodome          3.15.0
Pygments              2.8.1
PyGObject             3.26.1
pylint                2.7.2
PyMuPDF               1.18.7
pyparsing             2.4.7
pytest                6.2.2
python-apt            1.6.5+ubuntu0.5
python-dateutil       2.8.1
pytz                  2022.6
PyWavelets            1.4.1
pyxdg                 0.25
PyYAML                5.4.1
pyzmq                 22.0.3
rapidfuzz             2.11.1
requests              2.25.1
scikit-image          0.19.3
scipy                 1.9.3
SecretStorage         2.3.1
setuptools            65.5.1
Shapely               1.8.5.post1
simplegeneric         0.8.1
six                   1.15.0
tifffile              2022.10.10
toml                  0.10.2
tornado               6.1
tqdm                  4.64.1
traitlets             5.0.5
unattended-upgrades   0.1
urllib3               1.26.4
virtualenv            20.4.3
visualdl              2.4.1
wcwidth               0.2.5
Werkzeug              2.1.2
wheel                 0.36.2
wrapt                 1.12.1
zipp                  3.10.0
- 运行指令/Command Code：
python3 -m paddle.distributed.launch --gpus '0,1,2,3' tools/train.py -c configs/det/det_r50_db++_icdar15.yml 
- 完整报错/Complete Error Message：
INFO 2022-11-16 02:35:49,946 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-11-16 02:35:49,946 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:7395 idx:0
launch proc_id:7400 idx:1
launch proc_id:7405 idx:2
launch proc_id:7411 idx:3
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    from ppocr.data import build_dataloader
  File "/workspace/code/OCR/PaddleOCR/ppocr/data/__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/workspace/code/OCR/PaddleOCR/ppocr/data/imaug/__init__.py", line 48, in <module>
    from .drrg_targets import DRRGTargets
  File "/workspace/code/OCR/PaddleOCR/ppocr/data/imaug/drrg_targets.py", line 21, in <module>
    from lanms import merge_quadrangle_n9 as la_nms
  File "/usr/local/lib/python3.8/dist-packages/lanms/__init__.py", line 2, in <module>
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: Python version mismatch: module was compiled for version 3.6, while the interpreter is running version 3.8.
INFO 2022-11-16 02:36:00,163 launch_utils.py:343] terminate all the procs
INFO 2022-11-16 02:36:00,163 launch_utils.py:343] terminate all the procs
ERROR 2022-11-16 02:36:00,163 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
ERROR 2022-11-16 02:36:00,163 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-11-16 02:36:04,168 launch_utils.py:343] terminate all the procs
INFO 2022-11-16 02:36:04,168 launch_utils.py:343] terminate all the procs
INFO 2022-11-16 02:36:04,168 launch.py:402] Local processes completed.
INFO 2022-11-16 02:36:04,168 launch.py:402] Local processes completed.

**Comment by namemzy** [comment]
用百度的源安装PaddleOCR
```
pip3 install "paddleocr>=2.6" -i https://mirror.baidu.com/pypi/simple
pip3 install lanms
pip3 install lanms-neo
```
