### ISSUE TITLE
windows转pdf报错

### ISSUE THREAD

**Issue by lun9090** [PaddlePaddle/PaddleOCR#8351]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows11
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.6.0
- 运行指令/Command Code：paddleocr  --image_dir="D:\python-code\pythonProject\1.pdf" --type=structure --recovery=true --use_pdf2docx_api=true  
- 完整报错/Complete Error Message：
paddleocr  --image_dir="D:\python-code\pythonProject\1.pdf" --type=structure --recovery=true --use_pdf2docx_api=true                                                                                                                                                          
[2022/11/17 11:00:32] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir=None, cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:
\\Users\\liting/.paddleocr/whl\\det\\ch\\ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=
0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_
limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False,
 fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir='D:\\python-code\\pythonProject\\1.pdf', image_orientation=False, ir_optim=True, kie_algorithm='LayoutX
LM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path='D:\\python-code\\pythonProject\\venv\\lib\\site-packages\\paddleocr\\ppocr\\utils\\dict\\layou
t_dict\\layout_cdla_dict.txt', layout_model_dir='C:\\Users\\liting/.paddleocr/whl\\layout\\picodet_lcnet_x1_0_fgd_layout_cdla_infer', layout_nms_threshold=0.5, layout
_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, oc
r_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_cha
r_dict_path='D:\\python-code\\pythonProject\\venv\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 32
0', rec_model_dir='C:\\Users\\liting/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv3_rec_infer', recovery=True, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16
, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, str
ucture_version='PP-Structurev2', table=True, table_algorithm='TableAttn', table_char_dict_path='D:\\python-code\\pythonProject\\venv\\lib\\site-packages\\paddleocr\\p
pocr\\utils\\dict\\table_structure_dict_ch.txt', table_max_len=488, table_model_dir='C:\\Users\\liting/.paddleocr/whl\\table\\ch_ppstructure_mobile_v2.0_SLANet_infer'
, total_process_num=1, type='structure', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2022/11/17 11:00:35] ppocr INFO: **********D:\python-code\pythonProject\1.pdf**********
Deprecation: 'getPixmap' removed from class 'Page' after v1.19.0 - use 'get_pixmap'.
[INFO] Start to convert D:\python-code\pythonProject\1.pdf
[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
[WARNING] Words count: 0. It might be a scanned pdf, which is not supported yet.
[INFO] [3/4] Parsing pages...
[INFO] (1/23) Page 1
[INFO] (2/23) Page 2
[INFO] (3/23) Page 3
[INFO] (4/23) Page 4
[INFO] (5/23) Page 5
[INFO] (6/23) Page 6
[INFO] (7/23) Page 7
[INFO] (8/23) Page 8
[INFO] (9/23) Page 9
[INFO] (10/23) Page 10
[INFO] (11/23) Page 11
[INFO] (12/23) Page 12
[INFO] (13/23) Page 13
[INFO] (14/23) Page 14
[INFO] (15/23) Page 15
[INFO] (16/23) Page 16
[INFO] (17/23) Page 17
[INFO] (18/23) Page 18
[INFO] (19/23) Page 19
[INFO] (20/23) Page 20
[INFO] (21/23) Page 21
[INFO] (22/23) Page 22
[INFO] (23/23) Page 23
[INFO] [4/4] Creating pages...
[INFO] (1/23) Page 1
[INFO] (2/23) Page 2
[INFO] (3/23) Page 3
[INFO] (4/23) Page 4
[INFO] (5/23) Page 5
[INFO] (6/23) Page 6
[INFO] (7/23) Page 7
[INFO] (8/23) Page 8
[INFO] (9/23) Page 9
[INFO] (10/23) Page 10
[INFO] (11/23) Page 11
[INFO] (12/23) Page 12
[INFO] (13/23) Page 13
[INFO] (14/23) Page 14
[INFO] (15/23) Page 15
[INFO] (16/23) Page 16
[INFO] (17/23) Page 17
[INFO] (18/23) Page 18
[INFO] (19/23) Page 19
[INFO] (20/23) Page 20
[INFO] (21/23) Page 21
[INFO] (22/23) Page 22
[INFO] (23/23) Page 23
Traceback (most recent call last):
  File "D:\python-code\WPy64-38100\python-3.8.10.amd64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python-code\WPy64-38100\python-3.8.10.amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python-code\pythonProject\venv\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "D:\python-code\pythonProject\venv\lib\site-packages\paddleocr\paddleocr.py", line 671, in main
    cv.convert(docx_file)
  File "D:\python-code\pythonProject\venv\lib\site-packages\pdf2docx\converter.py", line 329, in convert
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "D:\python-code\pythonProject\venv\lib\site-packages\pdf2docx\converter.py", line 213, in make_docx
    docx_file.save(filename)
  File "D:\python-code\pythonProject\venv\lib\site-packages\docx\document.py", line 135, in save
    self._part.save(path_or_stream)
  File "D:\python-code\pythonProject\venv\lib\site-packages\docx\parts\document.py", line 111, in save
    self.package.save(path_or_stream)
  File "D:\python-code\pythonProject\venv\lib\site-packages\docx\opc\package.py", line 172, in save
    PackageWriter.write(pkg_file, self.rels, self.parts)
  File "D:\python-code\pythonProject\venv\lib\site-packages\docx\opc\pkgwriter.py", line 32, in write
    phys_writer = PhysPkgWriter(pkg_file)
  File "D:\python-code\pythonProject\venv\lib\site-packages\docx\opc\phys_pkg.py", line 141, in __init__
    self._zipf = ZipFile(pkg_file, 'w', compression=ZIP_DEFLATED)
  File "D:\python-code\WPy64-38100\python-3.8.10.amd64\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: './output\\1.docx'

**Comment by an1018** [comment]
可以先创建一个output目录，我们修复下代码~

**Comment by lun9090** [comment]
嗯，我觉得是应该修增加一个参数，能够指定路径，这样windows和linux就通用了

**Comment by an1018** [comment]
可以下载最新的代码，通过--output='output_path/'来指定输出路径
