### ISSUE TITLE
PPOCRLable自动标注报错

### ISSUE THREAD

**Issue by lixian-wtu** [PaddlePaddle/PaddleOCR#8393]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
[2022/11/21 14:43:35] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is D:\table-datasets\tttt.png
DirPath in importDirImages is D:/table-datasets
Using model from paddle
can only concatenate str (not "list") to str
Traceback (most recent call last):
File "D:\Anaconda3\envs\py38\lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 62, in run
strs += "Transcription: " + chars + " Probability: " + str(cond) + \
TypeError: can only concatenate str (not "list") to str

**Comment by lixian-wtu** [comment]
系统环境/System Environment：windows
版本号/Version：Paddle： PaddleOCR： 问题相关组件/Related components：
运行指令/Command Code：PPOCRLabel --lang ch
完整报错/Complete Error Message：
[2022/11/21 14:43:35] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is D:\table-datasets\tttt.png
DirPath in importDirImages is D:/table-datasets
Using model from paddle
can only concatenate str (not "list") to str
Traceback (most recent call last):
File "D:\Anaconda3\envs\py38\lib\site-packages\PPOCRLabel\libs\autoDialog.py", line 62, in run
strs += "Transcription: " + chars + " Probability: " + str(cond) +
TypeError: can only concatenate str (not "list") to str

**Comment by wujia3308** [comment]
解决了吗，我也一直报这个错，不知道为啥

**Comment by jingruijie** [comment]
chars不是一个字符串，debug看一下  那个地方的for循环好像是有问题的，for res in self.result_dic[0]: 要改成这样

**Comment by Evezerest** [comment]
升级2.1.3版本的PPOCRLabel
