### ISSUE TITLE
PPOCRLabel 批量标注报错

### ISSUE THREAD

**Issue by jingruijie** [PaddlePaddle/PaddleOCR#8395]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Centos
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：PPOCRLabel --lang ch
- 完整报错/Complete Error Message：unicodeFilePath is /home/yy/main/0Data/imgs/3.jpg
Traceback (most recent call last):
  File "/home/yy/2Support/Anaconda3/envs/ppocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 2177, in autoRecognition
    self.loadFile(self.filePath)  # ADD
  File "/home/yy/2Support/Anaconda3/envs/ppocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 1578, in loadFile
    self.showBoundingBoxFromPPlabel(filePath)
  File "/home/yy/2Support/Anaconda3/envs/ppocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 1620, in showBoundingBoxFromPPlabel
    self.loadLabels(shapes)
  File "/home/yy/2Support/Anaconda3/envs/ppocr/lib/python3.7/site-packages/PPOCRLabel/PPOCRLabel.py", line 1154, in loadLabels
    for x, y in points:
ValueError: too many values to unpack (expected 2)

**Comment by taojing7** [comment]
请问您解决了吗，我也遇到了同样的问题

**Comment by jingruijie** [comment]
没有解决，问题很多

> 



> 请问您解决了吗，我也遇到了同样的问题

没有解决，问题好多

**Comment by jingruijie** [comment]
> 请问您解决了吗，我也遇到了同样的问题

解決了

**Comment by taojing7** [comment]
> > 请问您解决了吗，我也遇到了同样的问题
> 
> 解決了

方便指教一下吗862978601@qq.com

**Comment by Evezerest** [comment]
升级2.1.3版本的PPOCRLabel

**Comment by PxCPeter** [comment]
@jingruijie Hello, How did you solve it ? Actually the current version of paddleocr  is 2.7.0.3. 
Please give me advices.
Thank you in advance .
