### ISSUE TITLE
PPOCRLabel启动时报错, No module named 'auto_log'

### ISSUE THREAD

**Issue by Cong-Wan** [PaddlePaddle/PaddleOCR#8411]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu20.04LTS
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.6  问题相关组件/Related components：
- 运行指令/Command Code：PPOCRLabel --lang ch
- 完整报错/Complete Error Message：
- 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[2022/11/22 16:49:39] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
Traceback (most recent call last):
  File "/root/anaconda3/envs/pp/bin/PPOCRLabel", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/PPOCRLabel/PPOCRLabel.py", line 104, in __init__
    self.table_ocr = PPStructure(use_pdserving=False,
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 620, in __init__
    super().__init__(params)
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 76, in __init__
    self.table_system = TableSystem(args)
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/paddleocr/ppstructure/table/predict_table.py", line 69, in __init__
    self.table_structurer = predict_strture.TableStructurer(args)
  File "/root/anaconda3/envs/pp/lib/python3.8/site-packages/paddleocr/ppstructure/table/predict_structure.py", line 94, in __init__
    import auto_log
ModuleNotFoundError: No module named 'auto_log'

**Comment by Evezerest** [comment]
paddleocr whl包缺少auto_log依赖

**Comment by littletomatodonkey** [comment]
可以参考这个repo安装一下

https://github.com/LDOUBLEV/AutoLog

**Comment by Cong-Wan** [comment]
> 可以参考这个repo安装一下
> 
> [LDOUBLEV/AutoLog](https://github.com/LDOUBLEV/AutoLog)

感谢！已解决
