### ISSUE TITLE
PPOCRLabel 无法操作，点击和框选报错！！

### ISSUE THREAD

**Issue by wubostc** [PaddlePaddle/PaddleOCR#8420]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 64
- 版本号/Version：Paddle：2.3.2.post116   PaddleOCR：2.6.1.0 问题相关组件/Related components：PPOCRLabel 2.1.3
- 运行指令/Command Code：PPOCRLabel --lang ch
- 完整报错/Complete Error Message：
DirPath in importDirImages is D:/PROJ/datasets/mhxy/wenzi
Traceback (most recent call last):
  File "C:\Users\GameBoy\AppData\Local\Programs\Python\Python310\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

Traceback (most recent call last):
  File "C:\Users\GameBoy\AppData\Local\Programs\Python\Python310\lib\site-packages\PPOCRLabel\libs\canvas.py", line 596, in paintEvent
    p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'float'
  drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'float'

一点击或者一框选文字就崩溃，没法用，希望能尽快修复

还有就是这个和labelimg有冲突，我把labelimg卸载之后就能打开了

**Comment by wubostc** [comment]
> 收到

退回python3.9好了，感觉是版本兼容问题
