### ISSUE TITLE
paddleocr 包报错  缺少模块

### ISSUE THREAD

**Issue by justliveisperfect** [PaddlePaddle/PaddleOCR#8421]
运行一下代码
from paddleocr import PaddleOCR, draw_ocr
报错：
Traceback (most recent call last):
  File "C:/Users/xinxi015/PaddleOCR/temp_r.py", line 1, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\xinxi015\PaddleOCR\paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "C:\Users\xinxi015\PaddleOCR\tools\infer\predict_system.py", line 32, in <module>
    import tools.infer.predict_rec as predict_rec
  File "C:\Users\xinxi015\PaddleOCR\tools\infer\predict_rec.py", line 31, in <module>
    from ppocr.postprocess import build_post_process
  File "C:\Users\xinxi015\PaddleOCR\ppocr\postprocess\__init__.py", line 33, in <module>
    from .pg_postprocess import PGPostProcess
  File "C:\Users\xinxi015\PaddleOCR\ppocr\postprocess\pg_postprocess.py", line 25, in <module>
    from ppocr.utils.e2e_utils.pgnet_pp_utils import PGNet_PostProcess
  File "C:\Users\xinxi015\PaddleOCR\ppocr\utils\e2e_utils\pgnet_pp_utils.py", line 25, in <module>
    from extract_textpoint_slow import *
  File "C:\Users\xinxi015\PaddleOCR\ppocr\utils\e2e_utils\extract_textpoint_slow.py", line 24, in <module>
    from skimage.morphology._skeletonize import thin
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\skimage\morphology\__init__.py", line 8, in <module>
    from ..measure._label import label
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\skimage\measure\__init__.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\__init__.py", line 233, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "D:\Anaconda3\envs\paddle_env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\signal\__init__.py", line 331, in <module>
    from ._peak_finding import *
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\signal\_peak_finding.py", line 8, in <module>
    from scipy.stats import scoreatpercentile
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\stats\__init__.py", line 467, in <module>
    from ._stats_py import *
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\stats\_stats_py.py", line 46, in <module>
    from . import distributions
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\stats\_continuous_distns.py", line 31, in <module>
    import scipy.stats._boost as _boost
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\scipy\stats\_boost\__init__.py", line 25, in <module>
    from scipy.stats._boost.ncf_ufunc import (
ModuleNotFoundError: No module named 'scipy.stats._boost.ncf_ufunc'

**Comment by an1018** [comment]
可以重新安装scipy，这个错误看着是scipy问题
![image](https://user-images.githubusercontent.com/19808900/203576949-49feabf9-e9f1-46dc-8f92-1edfc31ccde2.png)

**Comment by justliveisperfect** [comment]
是的  换了个scipy版本运行正常了  感谢
