### ISSUE TITLE
paddle 在window 2019 无法运行 

### ISSUE THREAD

**Issue by songsh** [PaddlePaddle/PaddleOCR#8523]
- 系统环境/System Environment： window 2019
- 版本号/Version：Paddle： 2.4.0  PaddleOCR：2.6.1.1  问题相关组件/Related components：
- 运行指令/Command Code： paddleocr
- 完整报错/Complete Error Message：
- Error: Can not import paddle core while this file exists: c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\paddleocr.exe\__main__.py", line 4, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\core.py", line 304, in <module>
    raise e
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\core.py", line 249, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: 找不到指定的模块。

**Comment by helloblackmarch** [comment]
I am also facing the same issue. It is not working in window Datacenter 2019. It was working in my local machine which has Windows 10

**Comment by helloblackmarch** [comment]
@songsh : I tried installing Anaconda and installed the complete thing from the Anaconda prompt. It worked for me after the same. Below is the step I followed : 

1. Install Anaconda/Miniconda (https://docs.conda.io/en/latest/miniconda.html)
NOTE : Python 3.9.12 comes with the Miniconda 
2. Open Anaconda Command Prompt and run the below commands (For CPU)
python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install paddleocr
3. import paddleocr (Import paddle ocr is working after this)

**Comment by songsh** [comment]
i use conda, the bug is   
File "C:\ProgramData\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\paddleocr.py", line 718, in main
    result = engine(new_img_path, img_idx=index)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\paddleocr.py", line 645, in __call__
    res, _ = super().__call__(
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 143, in __call__
    filter_boxes, filter_rec_res, ocr_time_dict = self.text_system(
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 271, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 240, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 131, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "C:\ProgramData\miniconda3\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

**Comment by songsh** [comment]
i use conda, the bug is   
File "C:\ProgramData\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\paddleocr.py", line 718, in main
    result = engine(new_img_path, img_idx=index)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\paddleocr.py", line 645, in __call__
    res, _ = super().__call__(
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 143, in __call__
    filter_boxes, filter_rec_res, ocr_time_dict = self.text_system(
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 271, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 240, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 131, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "C:\ProgramData\miniconda3\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

> @songsh : I tried installing Anaconda and installed the complete thing from the Anaconda prompt. It worked for me after the same. Below are the steps I followed :
> 
> 1. Install Anaconda/Miniconda (https://docs.conda.io/en/latest/miniconda.html)
>    NOTE : Python 3.9.12 comes with the Miniconda
> 2. Open Anaconda Command Prompt and run the below commands (For CPU)
>    python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
>    pip install paddleocr
>    python
>    > > import paddleocr (Import paddle ocr is working after this)
> 
> NOTE : I tried installing python 3.9.12 (same version) separately but that one resulted in the above error. For some reason when I used the python from conda, it worked for me

i use conda, the bug is   
File "C:\ProgramData\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\paddleocr.py", line 718, in main
    result = engine(new_img_path, img_idx=index)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\paddleocr.py", line 645, in __call__
    res, _ = super().__call__(
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 143, in __call__
    filter_boxes, filter_rec_res, ocr_time_dict = self.text_system(
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 271, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 240, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 131, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "C:\ProgramData\miniconda3\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "C:\ProgramData\miniconda3\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
