### ISSUE TITLE
paddle-serving 部署后 自动重载问题

### ISSUE THREAD

**Issue by fanruifeng** [PaddlePaddle/PaddleOCR#8565]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： ubuntu18.04以上  cuda 11.6 python 3.8 
我在paddleserver外面包了一层sanic服务，来支持自动重载, 遇到的问题: 
- 运行指令/Command Code：python web_service.py --config=config.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "handle_request", line 96, in handle_request
    if TYPE_CHECKING:
  File "/home/frf/word_space/PaddleOCR/deploy/pdserving/web_service.py", line 176, in main
    uci_service.run_service()
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_server/web_service.py", line 69, in run_service
    self._server.run_server()
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_server/pipeline/pipeline_server.py", line 314, in run_server
    PipelineServicer(self._name, self._response_op, self._conf),
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_server/pipeline/pipeline_server.py", line 57, in __init__
    raise CustomException(CustomExceptionCode.INIT_ERROR, "pipeline server init error")
paddle_serving_server.pipeline.error_catch.CustomException:
        exception_code: 3003
        exception_type: INIT_ERROR
        error_msg: pipeline server init error
        is_send_to_user: False

**Comment by ZhuXiang-tuxing** [comment]
你好，我也遇到这个问题了，请问你解决了吗

**Comment by aiyoagan** [comment]
怎么解决，我也遇到这个问题，Mac下
