### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS报错怎么解决

### ISSUE THREAD

**Issue by eagleLiu82** [PaddlePaddle/PaddleOCR#8597]
CentOS7.6运行程序时报这个错。
代码如下：`from paddleocr import PaddleOCR, draw_ocr

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)`
报错信息：
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/skimage/__init__.py", line 151, in <module>
    from ._shared import geometry
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ocrtest.py", line 1, in <module>
    from paddleocr import PaddleOCR, draw_ocr
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 32, in <module>
    import tools.infer.predict_rec as predict_rec
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py", line 31, in <module>
    from ppocr.postprocess import build_post_process
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/__init__.py", line 33, in <module>
    from .pg_postprocess import PGPostProcess
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/pg_postprocess.py", line 25, in <module>
    from ppocr.utils.e2e_utils.pgnet_pp_utils import PGNet_PostProcess
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/ppocr/utils/e2e_utils/pgnet_pp_utils.py", line 25, in <module>
    from extract_textpoint_slow import *
  File "/usr/local/python3/lib/python3.7/site-packages/paddleocr/ppocr/utils/e2e_utils/extract_textpoint_slow.py", line 24, in <module>
    from skimage.morphology._skeletonize import thin
  File "/usr/local/python3/lib/python3.7/site-packages/skimage/__init__.py", line 154, in <module>
    _raise_build_error(e)
  File "/usr/local/python3/lib/python3.7/site-packages/skimage/__init__.py", line 133, in _raise_build_error
    %s""" % (e, msg))
ImportError: dlopen: cannot load any more object with static TLS
It seems that scikit-image has not been built correctly.

**Comment by MissPenguin** [comment]
“It seems that scikit-image has not been built correctly.” 试试重装一下 scikit-image  呢？

**Comment by zyzz1974** [comment]
重装也不行，怎么办呢？

**Comment by zyzz1974** [comment]
重装也不行，怎么办呢？
