### ISSUE TITLE
训练SER报错numpy.core._exceptions.MemoryError: Unable to allocate 9.00 MiB for an array with shape (3072, 768) and data type float32

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleOCR#8598]
之前的问题解决后又出新问题，这是之前的：https://github.com/PaddlePaddle/PaddleOCR/issues/8456

现在报下面的问题：
[2022/12/10 20:57:27] ppocr INFO: cur metric, precision: 1.0, recall: 1.0, hmean: 1.0, fps: 8.010037602815723
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 183, in main
    amp_level, amp_custom_black_list)
  File "D:\dzkj\PaddleOCR26\tools\program.py", line 409, in train
    global_step=global_step)
  File "D:\dzkj\PaddleOCR26\ppocr\utils\save_load.py", line 198, in save_model
    paddle.save(optimizer.state_dict(), model_prefix + '.pdopt')
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\paddle\framework\io.py", line 732, in save
    _legacy_save(obj, path, protocol)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\paddle\framework\io.py", line 771, in _legacy_save
    saved_obj = _build_saved_state_dict(obj)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\paddle\framework\io.py", line 57, in _build_saved_state_dict
    save_dict[key] = value.numpy()
numpy.core._exceptions.MemoryError: Unable to allocate 9.00 MiB for an array with shape (3072, 768) and data type float32

![图片](https://user-images.githubusercontent.com/6648329/206880404-e50ae740-5754-4d8a-a1eb-a3728293eb5a.png)
![图片](https://user-images.githubusercontent.com/6648329/206880511-c9a4e132-9c3b-4ea5-a7a6-94e879eb2610.png)

**Comment by MissPenguin** [comment]
应该是环境问题，看您上一个issue说aistudio上跑没问题，要不直接在aistudio上跑呢，linux环境问题少一点

**Comment by gg22mm** [comment]
> aistudio

是的，用aistudio上没有这个问是，但是跑出来的效果有点尴尬: https://github.com/PaddlePaddle/PaddleOCR/issues/8627
