### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by chenyangMl** [PaddlePaddle/PaddleOCR#86]
运行　python3 tools/eval.py 出现如下错误
2020-05-21 09:38:02,350-INFO: Finish initing model from ./output/det_db/iter_epoch_1600
2020-05-21 09:38:04,318-INFO: test tackling num:8
Traceback (most recent call last):
  File "tools/eval.py", line 101, in <module>
    main()
  File "tools/eval.py", line 80, in main
    metrics = eval_det_run(exe, config, eval_info_dict, "eval")
  File "/paddle/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 126, in eval_det_run
    cal_det_res(exe, config, eval_info_dict)
  File "/paddle/PaddleOCR/tools/eval_utils/eval_det_utils.py", line 59, in cal_det_res
    img_list = np.concatenate(img_list, axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by LDOUBLEV** [comment]
看报错是imglist中的图像数据维度不一致，能否将imglist中img的维度打印出来看下。

**Comment by MissPenguin** [comment]
是用的自己的数据把，看着像图像尺度不一致，因此不能concatenate，icdar2015的图像尺寸一样，所以不会有这个问题，可以把config中的 test_batch_size_per_card 改成1试试
