### ISSUE TITLE
执行kie/predict_kie_token_ser_re.py报错

### ISSUE THREAD

**Issue by DYF-AI** [PaddlePaddle/PaddleOCR#8610]
补充下报错信息：

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：win11
版本号/Version：paddlepaddle-gpu | 2.3.0    paddleocr  |  2.6.1.1

运行指令/Command Code：
cd ppstructure
python kie/predict_kie_token_ser_re.py ^
--kie_algorithm=LayoutXLM ^
--re_model_dir=../inference/re_vi_layoutxlm_xfund_infer ^
--ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer ^
--use_visual_backbone=False ^
--image_dir=./docs/kie/input/zh_val_42.jpg ^
--ser_dict_path=../train_data/XFUND/class_list_xfun.txt ^
--vis_font_path=../doc/fonts/simfang.ttf ^
--ocr_order_method="tb-yx"
cd ..

完整报错/Complete Error Message：
(paddle) G:\com\dongyongfei786\paddle\PaddleOCR\ppstructure>python kie/predict_kie_token_ser_re.py --kie_algorithm=LayoutXLM --re_model_dir=../inference/re_vi_layoutxlm_xfund_infer --ser_model_dir=..
/inference/ser_vi_layoutxlm_xfund_infer --use_visual_backbone=False --image_dir=./docs/kie/input/zh_val_42.jpg --ser_dict_path=../train_data/XFUND/class_list_xfun.txt --vis_font_path=../doc/fonts/simfang.ttf --ocr_order_method="tb-yx"
[2022-12-13 23:01:54,628] [ INFO] - Already cached C:\Users\21702.paddlenlp\models\layoutxlm-base-uncased\sentencepiece.bpe.model
[2022-12-13 23:01:55,091] [ INFO] - tokenizer config file saved in C:\Users\21702.paddlenlp\models\layoutxlm-base-uncased\tokenizer_config.json
[2022-12-13 23:01:55,093] [ INFO] - Special tokens file saved in C:\Users\21702.paddlenlp\models\layoutxlm-base-uncased\special_tokens_map.json
Corrupt JPEG data: premature end of data segment
Traceback (most recent call last):
File "kie/predict_kie_token_ser_re.py", line 127, in
main(parse_args())
File "kie/predict_kie_token_ser_re.py", line 99, in main
re_res, elapse = ser_predictor(img)
File "kie/predict_kie_token_ser_re.py", line 62, in call
self.predictor.run()
ValueError: In user code:

File "tools/export_model.py", line 258, in <module>
  main()
File "tools/export_model.py", line 254, in main
  model, arch_config, save_path, logger, input_shape=input_shape)
File "tools/export_model.py", line 174, in export_single_model
  paddle.jit.save(model, save_path)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
  func(layer, path, input_spec, **configs)
File "<decorator-gen-106>", line 2, in save

File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
  return wrapped_func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
  return func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 861, in save
  inner_input_spec, with_hook=with_hook)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
  *desired_input_spec, with_hook=with_hook)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
  concrete_program, partial_program_layer = self._program_cache[cache_key]
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
  self._caches[item_id] = self._build_once(item)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
  **cache_key.kwargs)
File "<decorator-gen-104>", line 2, in from_func_spec

File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
  return wrapped_func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
  return func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
  outputs = static_func(*inputs)
File "/tmp/tmp1jzgs091.py", line 28, in forward
  false_fn_1, (x,), (x,), (x,))
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
  out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
  return true_fn(*true_args) if pred else false_fn(*false_args)
File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
  x = self.backbone(x)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
  return self._dygraph_call_func(*inputs, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
  outputs = self.forward(*inputs, **kwargs)
File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 237, in forward
  relations=relations)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
  return self._dygraph_call_func(*inputs, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
  outputs = self.forward(*inputs, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1542, in forward
  relations)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
  return self._dygraph_call_func(*inputs, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
  outputs = self.forward(*inputs, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1408, in forward
  relations, entities = self.build_relation(relations, entities)
File "/tmp/tmpt8u0m8_d.py", line 106, in build_relation
  for_loop_body_2, [entities, new_relations, relations, b, batch_size])
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
  loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
  loop_vars = control_flow.while_loop(cond, body, loop_vars)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
  output_vars = body(*loop_vars)
File "/tmp/tmpt8u0m8_d.py", line 30, in for_loop_body_2
  paddle.jit.dy2static.convert_ifelse(entities[b, 0, 0] <= 2,
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
  attrs={'axis': axis})
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
  attrs=kwargs.get("attrs", None))
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
  for frame in traceback.extract_stack():

InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at ..\paddle\phi\core\dense_tensor.cc:137)  
  [operator < less_equal > error]

**Comment by DYF-AI** [comment]
补充下报错信息：

请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

系统环境/System Environment：win11
版本号/Version：paddlepaddle-gpu | 2.3.0  paddleOCR v2.6.0

运行指令/Command Code：
cd ppstructure
python kie/predict_kie_token_ser_re.py ^
    --kie_algorithm=LayoutXLM ^
    --re_model_dir=../inference/re_vi_layoutxlm_xfund_infer ^
    --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer ^
    --use_visual_backbone=False ^
    --image_dir=./docs/kie/input/zh_val_42.jpg ^
    --ser_dict_path=../train_data/XFUND/class_list_xfun.txt ^
    --vis_font_path=../doc/fonts/simfang.ttf ^
    --ocr_order_method="tb-yx"
cd ..


完整报错/Complete Error Message：
(paddle) G:\com\dongyongfei786\paddle\PaddleOCR\ppstructure>python kie/predict_kie_token_ser_re.py     --kie_algorithm=LayoutXLM     --re_model_dir=../inference/re_vi_layoutxlm_xfund_infer     --ser_model_dir=..
/inference/ser_vi_layoutxlm_xfund_infer     --use_visual_backbone=False     --image_dir=./docs/kie/input/zh_val_42.jpg     --ser_dict_path=../train_data/XFUND/class_list_xfun.txt     --vis_font_path=../doc/fonts/simfang.ttf     --ocr_order_method="tb-yx"
[2022-12-13 23:01:54,628] [    INFO] - Already cached C:\Users\21702\.paddlenlp\models\layoutxlm-base-uncased\sentencepiece.bpe.model
[2022-12-13 23:01:55,091] [    INFO] - tokenizer config file saved in C:\Users\21702\.paddlenlp\models\layoutxlm-base-uncased\tokenizer_config.json
[2022-12-13 23:01:55,093] [    INFO] - Special tokens file saved in C:\Users\21702\.paddlenlp\models\layoutxlm-base-uncased\special_tokens_map.json
Corrupt JPEG data: premature end of data segment
Traceback (most recent call last):
  File "kie/predict_kie_token_ser_re.py", line 127, in <module>
    main(parse_args())
  File "kie/predict_kie_token_ser_re.py", line 99, in main
    re_res, elapse = ser_predictor(img)
  File "kie/predict_kie_token_ser_re.py", line 62, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 258, in <module>
      main()
    File "tools/export_model.py", line 254, in main
      model, arch_config, save_path, logger, input_shape=input_shape)
    File "tools/export_model.py", line 174, in export_single_model
      paddle.jit.save(model, save_path)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "<decorator-gen-106>", line 2, in save

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 861, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-104>", line 2, in from_func_spec

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmp1jzgs091.py", line 28, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/ssd1/zhoujun20/tipc/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 237, in forward
      relations=relations)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1542, in forward
      relations)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1408, in forward
      relations, entities = self.build_relation(relations, entities)
    File "/tmp/tmpt8u0m8_d.py", line 106, in build_relation
      for_loop_body_2, [entities, new_relations, relations, b, batch_size])
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
      output_vars = body(*loop_vars)
    File "/tmp/tmpt8u0m8_d.py", line 30, in for_loop_body_2
      paddle.jit.dy2static.convert_ifelse(entities[b, 0, 0] <= 2,
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at ..\paddle\phi\core\dense_tensor.cc:137)  
      [operator < less_equal > error]

**Comment by DYF-AI** [comment]
问题解决了，找到提交代码的大佬的request：
https://github.com/PaddlePaddle/PaddleOCR/pull/8475/commits/e7543cffa24ab85f2b7c0c65092355290a5bca54

**Comment by Lebron-Harden** [comment]
> 问题解决了，找到提交代码的大佬的request： [e7543cf](https://github.com/PaddlePaddle/PaddleOCR/commit/e7543cffa24ab85f2b7c0c65092355290a5bca54)

感谢！这个错误我debug了半天也没有弄出来，原来是数据类型有问题

**Comment by LeoRainly** [comment]
按照这个改了dtype=np.int64，然而并没有什么用
