### ISSUE TITLE
Windows下无法启动paddle serving,运行python web_service.py报错

### ISSUE THREAD

**Issue by ZhuXiang-tuxing** [PaddlePaddle/PaddleOCR#8620]
1.环境：window10，paddlepaddle_cpu:2.20, 
paddle_serving_server-0.8.3
paddle_serving_client-0.8.3
paddle_serving_app-0.8.3
2. 报错：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\admin\.conda\envs\paddle\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\admin\.conda\envs\paddle\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\admin\.conda\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PycharmProjectsWork\paddleocr-id_card_db\deploy\pdserving\web_service.py", line 45, in <module>
    uci_service.run_service()
  File "C:\Users\admin\.conda\envs\paddle\lib\site-packages\paddle_serving_server\web_service.py", line 69, in run_service
    self._server.run_server()
  File "C:\Users\admin\.conda\envs\paddle\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 314, in run_server
    PipelineServicer(self._name, self._response_op, self._conf),
  File "C:\Users\admin\.conda\envs\paddle\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 57, in __init__
    raise CustomException(CustomExceptionCode.INIT_ERROR, "pipeline server init error")
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 3003
	exception_type: INIT_ERROR
	error_msg: pipeline server init error
	is_send_to_user: False

**Comment by ZhuXiang-tuxing** [comment]
你解决了吗？这个我不知道问题是出在哪里

**Comment by rbsrcy** [comment]
没有，毫无头绪

**Comment by jingsongliujing** [comment]
试试命令：python3 ocr_web_server.py gpu(使用gpu方式)
或者
python3 ocr_web_server.py cpu(使用cpu方式)
按照官方的说法：链接参照：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/README_CN.md#%E9%83%A8%E7%BD%B2
![image](https://user-images.githubusercontent.com/45508593/207761857-ba94f416-2cbc-48ae-86c8-d5f4daaf33be.png)
