### ISSUE TITLE
关键信息提取(KIE)的时候提示keyError

### ISSUE THREAD

**Issue by eerenyuan** [PaddlePaddle/PaddleOCR#8623]
下载wildreceipt
运行python tools/train.py -c .\configs\kie\sdmgr\kie_unet_sdmgr3.yml （修改为非GPU运行）

在load数据时提示错误:KeyError。似乎脚本不认识用id编号的label

[2022/12/14 16:15:00] ppocr ERROR: When parsing line image_files/Image_86/8/b3110275501898d430ce6aa433d441759a31f9c4.jpeg       [{"label": 1, "transcription": "WoodRanch", "points": [[147.0, 96.0], [198.0, 96.0], [198.0, 84.0], [147.0, 84.0]]}, {"label": 3, "transcription": "MissionValley", "points": [[138.0, 107.0], [208.0, 107.0], [208.0, 96.0], [138.0, 96.0]]}, {"label": 5, "transcription": "(619)764-4411", "points": [[138.0, 119.0], [207.0, 119.0], [207.0, 106.0], [138.0, 106.0]]}, {"label": 25, "transcription": "Server:Michael", "points": [[65.0, 140.0], [142.0, 140.0], [142.0, 128.0], [65.0, 128.0]]}, {"label": 25, "transcription": "Table201/1", "points": [[65.0, 152.0], [122.0, 152.0], [122.0, 139.0], [65.0, 139.0]]}, {"label": 25, "transcription": "Guests:2", "points": [[64.0, 162.0], [112.0, 162.0], [112.0, 152.0], [64.0, 152.0]]}, {"label": 7, "transcription": "07/26/2016", "points": [[227.0, 142.0], [278.0, 142.0], [278.0, 131.0], [227.0, 131.0]]}, {"label": 9, "transcription": "7:28PM", "points": [[242.0, 153.0], [280.0, 153.0], [280.0, 144.0], [242.0, 144.0]]}, {"label": 25, "transcription": "80034", "points": [[253.0, 165.0], [280.0, 165.0], [280.0, 155.0], [253.0, 155.0]]}, {"label": 11, "transcription": "25ozMooseDrool", "points": [[62.0, 188.0], [151.0, 188.0], [151.0, 175.0], [62.0, 175.0]]}, {"label": 11, "transcription": "SantaFeBBQCknSandwich", "points": [[61.0, 202.0], [193.0, 202.0], [193.0, 189.0], [61.0, 189.0]]}, {"label": 11, "transcription": "TrefethenEst.Merlot", "points": [[61.0, 213.0], [172.0, 213.0], [172.0, 202.0], [61.0, 202.0]]}, {"label": 11, "transcription": "VeggieBurger", "points": [[59.0, 227.0], [129.0, 227.0], [129.0, 214.0], [59.0, 214.0]]}, {"label": 11, "transcription": "SubSaladfor1Side", "points": [[69.0, 239.0], [176.0, 239.0], [176.0, 227.0], [69.0, 227.0]]}, {"label": 11, "transcription": "1/2HouseSalad(Add/Ext)", "points": [[79.0, 254.0], [213.0, 254.0], [213.0, 240.0], [79.0, 240.0]]}, {"label": 11, "transcription": "FreshFruitSmoothies", "points": [[57.0, 266.0], [170.0, 266.0], [170.0, 253.0], [57.0, 253.0]]}, {"label": 25, "transcription": "5Items", "points": [[59.0, 292.0], [98.0, 292.0], [98.0, 279.0], [59.0, 279.0]]}, {"label": 18, "transcription": "Subtotal", "points": [[51.0, 320.0], [97.0, 320.0], [97.0, 308.0], [51.0, 308.0]]}, {"label": 20, "transcription": "Tax", "points": [[51.0, 337.0], [68.0, 337.0], [68.0, 323.0], [51.0, 323.0]]}, {"label": 24, "transcription": "Total", "points": [[48.0, 365.0], [76.0, 365.0], [76.0, 353.0], [48.0, 353.0]]}, {"label": 25, "transcription": "BalanceDue", "points": [[45.0, 398.0], [174.0, 398.0], [174.0, 383.0], [45.0, 383.0]]}, {"label": 15, "transcription": "9.75", "points": [[259.0, 189.0], [280.0, 189.0], [280.0, 179.0], [259.0, 179.0]]}, {"label": 15, "transcription": "12.95", "points": [[255.0, 202.0], [281.0, 202.0], [281.0, 192.0], [255.0, 192.0]]}, {"label": 15, "transcription": "6.00", "points": [[260.0, 214.0], [283.0, 214.0], [283.0, 205.0], [260.0, 205.0]]}, {"label": 15, "transcription": "12.95", "points": [[257.0, 228.0], [283.0, 228.0], [283.0, 217.0], [257.0, 217.0]]}, {"label": 15, "transcription": "1.95", "points": [[262.0, 254.0], [283.0, 254.0], [283.0, 244.0], [262.0, 244.0]]}, {"label": 15, "transcription": "4.95", "points": [[262.0, 267.0], [284.0, 267.0], [284.0, 256.0], [262.0, 256.0]]}, {"label": 17, "transcription": "48.55", "points": [[258.0, 323.0], [287.0, 323.0], [287.0, 311.0], [258.0, 311.0]]}, {"label": 19, "transcription": "3.89", "points": [[264.0, 338.0], [288.0, 338.0], [288.0, 326.0], [264.0, 326.0]]}, {"label": 23, "transcription": "52.44", "points": [[260.0, 367.0], [290.0, 367.0], [290.0, 355.0], [260.0, 355.0]]}, {"label": 25, "transcription": "52.44", "points": [[232.0, 398.0], [291.0, 398.0], [291.0, 385.0], [232.0, 385.0]]}, {"label": 22, "transcription": "TipCalculator", "points": [[127.0, 429.0], [211.0, 429.0], [211.0, 415.0], [127.0, 415.0]]}, {"label": 21, "transcription": "20%=9.71", "points": [[137.0, 444.0], [198.0, 444.0], [198.0, 431.0], [137.0, 431.0]]}]
, error happened with msg: Traceback (most recent call last):
  File "C:\Users\Administrator\PaddleOCR\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "C:\Users\Administrator\PaddleOCR\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "C:\Users\Administrator\PaddleOCR\ppocr\data\imaug\label_ops.py", line 426, in __call__
    labels.append(self.label2classid_map[ann['label']])
KeyError: 1

在class_list.txt文件中是可以查到这些id的 (这个文件用windows默认编辑器打开没有换行，用notepad++打开显示正常）
0 Ignore
1 Store_name_value
2 Store_name_key
3 Store_addr_value
4 Store_addr_key
5 Tel_value
6 Tel_key
7 Date_value
8 Date_key
9 Time_value
10 Time_key
11 Prod_item_value
12 Prod_item_key
13 Prod_quantity_value
14 Prod_quantity_key
15 Prod_price_value
16 Prod_price_key
17 Subtotal_value
18 Subtotal_key
19 Tax_value
20 Tax_key
21 Tips_value
22 Tips_key
23 Total_value
24 Total_key
25 Others

**Comment by eerenyuan** [comment]
查了一下源代码，似乎label如果用id，应该用“key_cls”关键字；如果用字符串，才用“label”关键字？ 但是官方的配置文件中又是用的"label":1,2,3这样的组合。有什么文档可以参考吗

**Comment by gjj123** [comment]
> 
读取label的时候改下代码应该可以了
# labels.append(self.label2classid_map[ann['label']])
labels.append(ann['label'])
