### ISSUE TITLE
paddle 训练报错了，不知道是不是visualdl之后造成的？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/PaddleOCR#8639]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

[2022/12/15 17:38:19] ppocr INFO: epoch: [1/5], global_step: 16300, lr: 0.000008, acc: 0.100000, norm_edit_dis: 0.732207, CTCLoss: 15.893930, SARLoss: 1.189057, loss: 16.934299, avg_reader_cost: 0.36790 s, avg_batch_cost: 0.86541 s, avg_samples: 20.0, ips: 23.11031 samples/s, eta: 19 days, 1:13:50
Traceback (most recent call last):
  File "./tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "./tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 262, in train
    preds = model(images, data=batch[1:])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\modeling\architectures\base_model.py", line 79, in forward
    x = self.backbone(x)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\modeling\backbones\rec_mv1_enhance.py", line 223, in forward
    y = self.conv1(inputs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\modeling\backbones\rec_mv1_enhance.py", line 63, in forward
    y = self._conv(inputs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\nn\layer\conv.py", line 666, in forward
    out = F.conv._conv_nd(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\nn\functional\conv.py", line 144, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
OSError: (External) CUDA error(999), unknown error.
  [Hint: 'cudaErrorUnknown'. This indicates that an unknown internal error has occurred. ] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)
  [operator < conv2d > error]

**Comment by WenmuZhou** [comment]
关闭vdl后正常吗，这个看起来是cuda方面的原因
