### ISSUE TITLE
Training kie/ser error

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleOCR#8643]
Thanks for your great repo.
When I follow the [tutorial kie](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/kie_en.md). I get error:
```
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tupk/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/tupk/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/tupk/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/tupk/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/tupk/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/tupk/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/tupk/tupk/ocr-digits/PaddleOCR/tools/train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/tupk/tupk/ocr-digits/PaddleOCR/tools/train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/tupk/tupk/ocr-digits/PaddleOCR/tools/program.py", line 302, in train
    loss = loss_class(preds, batch)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tupk/tupk/ocr-digits/PaddleOCR/ppocr/losses/vqa_token_layoutlm_loss.py", line 41, in forward
    loss = self.loss_class(active_output, active_label)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/nn/layer/loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1715, in cross_entropy
    label != ignore_index, dtype=label.dtype) * label
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:105)
  [operator < not_equal > error]
```
I see that the error from:
```
tools/program.py at line: 302
loss = loss_class(preds, batch)
```
I had debug it. Every working well: Dataloader, predict,... except backpropagation loss
Now I am in branch 2.6. Here is my env:
```
paddle-bfloat             0.1.7                  
paddle2onnx               1.0.5                   
paddlefsl                 1.1.0                  
paddlenlp                 2.3.0.dev0            
paddleocr                 2.5.0.3               
paddlepaddle-gpu          2.3.2                  
```
Many thanks!!

**Comment by an1018** [comment]
You can check/print the preds and batch

**Comment by an1018** [comment]
you also need to change the path of dataset，please refer to (Key Information Extraction document)[https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/kie_en.md]

**Comment by phamkhactu** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.6/doc/doc_en/kie_en.md

@an1018 yes, I have followed the tutorial, I have trained successfully, but I have  another [issue](https://github.com/PaddlePaddle/PaddleOCR/issues/8660). The OCR model is only for Chinese
Thanks for your help.

**Comment by wangweiweinimeng** [comment]
> > You can check/print the preds and batch
> 
> Yes, after I try, I know that it comes from version not compatible with GPU. I have an other question that: "how to training kie with portugal". I think that I can use this text detection from DB and use other OCR is portugal OCR. I will config kie_rec_model_dir and kie_det_model_dir:
> 
> ```
> Global:
>   use_gpu: True
>   epoch_num: &epoch_num 200
>   log_smooth_window: 10
>   print_batch_step: 10
>   save_model_dir: ./output/ser_vi_layoutxlm_xfund_zh
>   save_epoch_step: 2000
>   # evaluation is run every 10 iterations after the 0th iteration
>   eval_batch_step: [ 0, 19 ]
>   cal_metric_during_train: False
>   save_inference_dir:
>   use_visualdl: False
>   seed: 2022
>   infer_img: train_data/mc_ocr/train_images/train_images/mcocr_public_145013aqeha.jpg
>   # if you want to predict using the groundtruth ocr info,
>   # you can use the following config
>   # infer_img: train_data/XFUND/zh_val/val.json
>   # infer_mode: False
> 
>   save_res_path: ./output/ser/xfund_zh/res
>   kie_rec_model_dir: inference/rec_svtr
>   kie_det_model_dir: inference/ch_PP-OCRv3_det_infer
> ```
> 
> Is it right??

Hi,
May I ask what version is not compatible with your GPU? I met the same error as yours.
Thanks ahead,
Vivian

**Comment by phamkhactu** [comment]
> > > You can check/print the preds and batch
> > 
> > 
> > Yes, after I try, I know that it comes from version not compatible with GPU. I have an other question that: "how to training kie with portugal". I think that I can use this text detection from DB and use other OCR is portugal OCR. I will config kie_rec_model_dir and kie_det_model_dir:
> > ```
> > Global:
> >   use_gpu: True
> >   epoch_num: &epoch_num 200
> >   log_smooth_window: 10
> >   print_batch_step: 10
> >   save_model_dir: ./output/ser_vi_layoutxlm_xfund_zh
> >   save_epoch_step: 2000
> >   # evaluation is run every 10 iterations after the 0th iteration
> >   eval_batch_step: [ 0, 19 ]
> >   cal_metric_during_train: False
> >   save_inference_dir:
> >   use_visualdl: False
> >   seed: 2022
> >   infer_img: train_data/mc_ocr/train_images/train_images/mcocr_public_145013aqeha.jpg
> >   # if you want to predict using the groundtruth ocr info,
> >   # you can use the following config
> >   # infer_img: train_data/XFUND/zh_val/val.json
> >   # infer_mode: False
> > 
> >   save_res_path: ./output/ser/xfund_zh/res
> >   kie_rec_model_dir: inference/rec_svtr
> >   kie_det_model_dir: inference/ch_PP-OCRv3_det_infer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it right??
> 
> Hi, May I ask what version is not compatible with your GPU? I met the same error as yours. Thanks ahead, Vivian

@wangweiweinimeng 
My version is  2.3.2 paddle-gpu
