### ISSUE TITLE
cpu版本下运行会出现AttributeError: 'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by bthuntergg** [PaddlePaddle/PaddleOCR#8666]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 版本号/Version：Paddle：2.4.1  PaddleOCR： /Related components：site-packages\paddle\fluid\dygraph\parallel.py:208
- 运行指令/Command Code：python3 tools/train.py -c configs/table/SLANet.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "D:\pythonProject\PaddleOCR-release-2.6\tools\program.py", line 656, in preprocess
    device = 'gpu:{}'.format(dist.ParallelEnv()
  File "D:\ProgramData\anconda\envs\py38\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 208, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

cpu版本下没有修改配置文件的 use_gpu: False 时会产生

**Comment by andyjpaddle** [comment]
> cpu版本下没有修改配置文件的 use_gpu: False 时会产生

cpu版本要修改配置文件的 use_gpu: False ，另外不建议使用cpu版本进行训练

**Comment by Freedom-bjt** [comment]
> > cpu版本下没有修改配置文件的 use_gpu: False 时会产生
> 
> cpu版本要修改配置文件的 use_gpu: False ，另外不建议使用cpu版本进行训练

是这样的，我回去试了下，用cpu跑没问题，一旦用gpu就会有以下的报错内容
2023-10-31 19:08:14,330-WARNING: post-quant-hpo is not support in system other than linux
Traceback (most recent call last):
  File "deploy/slim/quantization/quant.py", line 201, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "D:\Program_computersoftware\Anaconda\envs\ppocr\practice-12.27\PaddleOCR-release-2.6\PaddleOCR\tools\program.py", line 657, in preprocess
    .dev_id) if use_gpu else 'cpu'
  File "D:\Program_computersoftware\Anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 200, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'
我怀疑是paddlepaddle-gpu出问题了，打算重装一遍。
