### ISSUE TITLE
windows PPOCRLabel --lang ch 启动失败

### ISSUE THREAD

**Issue by iknow34languages** [PaddlePaddle/PaddleOCR#8682]
PPOCRLabel --lang ch
会从download https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar
下载推理模型，
网络无法连接   https://paddleocr.bj.bcebos.com  然后提示错误  ConnectionResetError: [WinError 10054]
通过手动的方法，下载了det / cls/rec/ppstructure 解压至目标文件夹后，错误不提示
最后一个手动下载的  picodet_lcnet_x1_0_fgd_layout_cdla_infer 
放到正确的位置解压  但是仍然报无法下载异常

请问需要怎么处理？

**Comment by iknow34languages** [comment]
download https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar to D:\Users\10934326/.paddleocr/whl\layout\picodet_lcnet_x1_0_fgd_layout_cdla_infer\picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar
Traceback (most recent call last):
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "F:\python\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "F:\python\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "F:\python\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "F:\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "F:\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "F:\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "F:\python\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "F:\python\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "F:\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "F:\python\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "F:\python\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "F:\python\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "F:\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "F:\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "F:\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\python\Scripts\PPOCRLabel.exe\__main__.py", line 7, in <module>
  File "F:\python\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2828, in main
    app, _win = get_main_app(sys.argv)
  File "F:\python\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 2818, in get_main_app
    win = MainWindow(lang=args.lang,
  File "F:\python\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 104, in __init__
    self.table_ocr = PPStructure(use_pdserving=False,
  File "F:\python\lib\site-packages\paddleocr\paddleocr.py", line 629, in __init__
    maybe_download(params.layout_model_dir, layout_url)
  File "F:\python\lib\site-packages\PaddleOCR\ppocr\utils\network.py", line 53, in maybe_download
    download_with_progressbar(url, tmp_path)
  File "F:\python\lib\site-packages\PaddleOCR\ppocr\utils\network.py", line 26, in download_with_progressbar
    response = requests.get(url, stream=True)
  File "F:\python\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "F:\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\python\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by iknow34languages** [comment]
下载的文件名称对不上
文件夹里面的文件名
model.pdmodel -> inference.pdmodel
