### ISSUE TITLE
KIE: PPOCR : Relation extraction training crash: ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by chowkamlee81** [PaddlePaddle/PaddleOCR#8709]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu20.0.4
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle-gpu+ 2.3.2, paddlenlp: 2.4.1, paddleocr:2.6, 
- 运行指令/Command Code：python tools/train.py -c  configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh_xfund_funsd.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 671, in _get_data
    batch.reraise()
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 79, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 79, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 60, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

Traceback (most recent call last):
  File "tools/train.py", line 213, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 188, in main
    amp_level, amp_custom_black_list)
  File "/home/computer/Wkspc/PaddleOCR-custom_exp/tools/program.py", line 258, in train
    for idx, batch in enumerate(train_dataloader):
  File "/home/computer/anaconda3/envs/spaceX/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Kindly suggest

**Comment by chowkamlee81** [comment]
@MissPenguin 
Above error occurs when i mix all the languages in XFUND dataset and train it for Relation extraction module. Kindly help

**Comment by ChidanandKumarVimaan** [comment]
@MissPenguin , iam training with multi-tasking with multi-lingual data as entire training and validation data. It seems Relation extraction module training is crashing a lot. Kindly suggest

**Comment by hritikiiti** [comment]
infer_mode : false
