### ISSUE TITLE
KIE: PPOCR : Relation extraction training crash: ValueError: The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]

### ISSUE THREAD

**Issue by chowkamlee81** [PaddlePaddle/PaddleOCR#8710]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Ubuntu20.0.4
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddlepaddle-gpu+ 2.3.2, paddlenlp: 2.4.1, paddleocr:2.6,
- 运行指令/Command Code：python tools/train.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh_xfund_funsd.yml
- 完整报错/Complete Error Message：Error occurs when i train with all the language gets mixed and training Relation extraction module

2022/12/19 20:40:48] ppocr INFO: train dataloader has 40 iters
[2022/12/19 20:40:48] ppocr INFO: valid dataloader has 20 iters
[2022/12/19 20:40:48] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
[2022/12/19 20:40:54] ppocr INFO: epoch: [1/130], global_step: 10, lr: 0.000001, loss: 0.836779, avg_reader_cost: 0.01602 s, avg_batch_cost: 0.61701 s, avg_samples: 1.0, ips: 1.62071 samples/s, eta: 0:53:22
eval model::  20%|███████████████████▊                                                                               | 4/20 
Traceback (most recent call last):
  File "/data/hsy/PPOCREXP/PaddleOCR/tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "/data/hsy/PPOCREXP/PaddleOCR/tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/data/hsy/PPOCREXP/PaddleOCR/tools/program.py", line 376, in train
    cur_metric = eval(
  File "/data/hsy/PPOCREXP/PaddleOCR/tools/program.py", line 519, in eval
    preds = model(batch)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/hsy/PPOCREXP/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/hsy/PPOCREXP/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 228, in forward
    x = self.model(
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1412, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1304, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1241, in build_relation
    entities[b] = entitie_new
  File "/data/xyd/miniconda3/envs/paddle23/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 786, in __setitem__
    return self.__setitem_varbase__(item, value)
ValueError: (InvalidArgument) The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]. (at /paddle/paddle/phi/kernels/impl/set_value_kernel_impl.h:69) 
  [operator < set_value > error]
eval model::  25%|████████████████████████▊

**Comment by chowkamlee81** [comment]
@MissPenguin
Above error occurs when i mix all the languages in XFUND dataset and train it for Relation extraction module. Kindly help

**Comment by an1018** [comment]
Hi，you can use processed [XFUND_zh dataset](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/kie_en.md#21-start-training) for training, and  if it's ok, you can use [this script](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/kie_en.md#13-download-data) to process other languages.

**Comment by ChidanandKumarVimaan** [comment]
@an1018 
I used the script and made the same convention formatting similar to [XFUND_zh dataset. SER training works but criticality lies in RElation Extraction module training, which doesn't train at all. AS per the paper mentioned in XFUND dataset, by training with multi-lingual languages there is more than 10% improvemnt in Multitask fine-tuning accuracy (F1).
It is on the paper page no:8 https://arxiv.org/pdf/2104.08836.pdf.

Kindly help on this to resolve

**Comment by ChidanandKumarVimaan** [comment]
@MissPenguin do you have any update on Multi-lingual training or Mult-task fine-tiuning on Relation extraction module in KIE?

**Comment by beez2022** [comment]
I can't train with funsd dataset. it stops after 1 epoch with no error message

**Comment by skupr** [comment]
Recently stepped onto the same problem, RE training failed with the error
> ValueError: (InvalidArgument) The shape of tensor assigned value must match the shape of target shape: [512, 3], but now shape is [513, 3]. (at /paddle/paddle/phi/kernels/impl/set_value_kernel_impl.h:69)

After investigations, I've found out that this error is triggered when training dataset sample has less than 3 labels. So just providing more reach datasets will workaround this problem.

Hopefully, that will help somebody.

If somebody is interested, I can even point on some code places which cause this, though I don't yet fully understand how it should work and how to fix this.

**Comment by munish0838** [comment]
> I can't train with funsd dataset. it stops after 1 epoch with no error message

Hi @beez2022, were you able to train the model on FUNSD for RE task.. were you able to resole the issue?
