### ISSUE TITLE
Numpy error: AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by hchen98** [PaddlePaddle/PaddleOCR#8718]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Ubuntu 22.04, CUDA 11.7, cuDNN 8.7, Python 3.9
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components： PaddleOCR OCR feature
- 运行指令/Command Code：`paddleocr --image_dir ./img_12.jpg --use_angle_cls true --lang en --use_gpu false`
- 完整报错/Complete Error Message：

`
[2022/12/26 23:53:24] ppocr INFO: **********./img_12.jpg**********
Traceback (most recent call last):
  File "/home/hui/paddle/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 673, in main
    result = engine.ocr(img_path,
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 555, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/tools/infer/predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/tools/infer/predict_det.py", line 271, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/ppocr/postprocess/db_postprocess.py", line 240, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/ppocr/postprocess/db_postprocess.py", line 131, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "/home/hui/paddle/lib/python3.9/site-packages/paddleocr/ppocr/postprocess/db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "/home/hui/paddle/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
`

![image](https://user-images.githubusercontent.com/12217705/209613504-823bcccc-1b2b-4064-9823-a103d0167aa2.png)

**Comment by andyjpaddle** [comment]
降低一下numpy的版本试试

**Comment by hchen98** [comment]
Resolve the issue through the following steps:

1. Uninstall the local and environment numpy installation
2. Install the numpy 1.23 via: `pip install numpy==1.23`
