### ISSUE TITLE
在使用PPOCRLabel创建矩形框时程序崩了，看起来像是需要int的地方传了float

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleOCR#8723]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：arch linux, linux 6.1.1-zen1-1-zen
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddleocr             2.6.1.2
paddlepaddle-gpu      2.4.1.post116
PyQt5                 5.15.7
PyQt5-Qt5             5.15.2
PyQt5-sip             12.11.0
PPOCRLabel            2.1.3

- 运行指令/Command Code：启动ppocrlabel, 之后拉一个矩形框，在点第一个点的时候立即报错，程序卡死
- 完整报错/Complete Error Message：

```shell
(ocr) ➜  ~ PPOCRLabel               
[2022/12/27 05:23:31] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  /home/lin/Desktop/data/ocr/ppocr_img/ch/ch.jpg
DirPath in importDirImages is /home/lin/Desktop/data/ocr/ppocr_img/ch
Using model from  paddle
unicodeFilePath is /home/lin/Desktop/data/ocr/ppocr_img/ch/word_1.jpg
unicodeFilePath is /home/lin/Desktop/data/ocr/ppocr_img/ch/ch.jpg
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3169, resource id: 13645149, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/home/lin/micromamba/envs/ocr/lib/python3.10/site-packages/PPOCRLabel/libs/canvas.py", line 596, in paintEvent
    p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'float'
  drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'float'


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1672136653 (unix time) try "date -d @1672136653" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800007ff3) received by PID 32755 (TID 0x7f6f5b7f7740) from PID 32755 ***]

[1]    32755 IOT instruction (core dumped)  PPOCRLabel

```

**Comment by andyjpaddle** [comment]
PPOCRLabel是多少，由于兼容问题，使用PPOCRLabel建议安装paddleocr2.6.0系列版本

**Comment by linhandev** [comment]
> PPOCRLabel是多少，由于兼容问题，使用PPOCRLabel建议安装paddleocr2.6.0系列版本

ocrlabel版本在上面添加了

**Comment by icaicai** [comment]
编辑 python安装目录下的site-packages/PPOCRLabel/libs/canvas.py
第16行末尾加 `, QRectF` 改成
`from PyQt5.QtCore import Qt, pyqtSignal, QPointF, QPoint, QRectF`
再报错的596行改成
`p.drawRect(QRectF(leftTop.x(), leftTop.y(), rectWidth, rectHeight))`

**Comment by linhandev** [comment]
收到，尝试了，拉框好用了，之后mouseUp之后报了另一个问题

```shell
PPOCRLabel
[2022/12/31 02:05:51] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  /home/lin/Desktop/data/ocr/ppocr_img/ch/ch.jpg
DirPath in importDirImages is /home/lin/Desktop/data/ocr/ppocr_img/ch
initPos PyQt5.QtCore.QPointF(344.1111111111111, 52.333333333333336)
Traceback (most recent call last):
  File "/home/lin/micromamba/envs/PaddleLabel-ML/lib/python3.10/site-packages/PPOCRLabel/PPOCRLabel.py", line 1425, in scrollRequest
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1672470367 (unix time) try "date -d @1672470367" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800017b1b) received by PID 97051 (TID 0x7f2cc5c14740) from PID 97051 ***]

[1]    97051 IOT instruction (core dumped)  PPOCRLabel
```

我主要就是尝试下ocrlabel，感觉遇到好几次int/float这种问题，猜测是经历了pyqt版本升级之类的一些api变了。感觉有空的话你们可以踩一踩主要功能修一修类似的bug

**Comment by Evezerest** [comment]
你好，可以尝试：
PyQt5                              5.15.6
PyQt5-Qt5                          5.15.2
PyQt5-sip                          12.9.0
Python 3.10并未进行验证，可以尝试3.8版本
