### ISSUE TITLE
按照教程下载了PPOCRLabel想对自己的数据进行四点标注，但是在输入PPOCRLabel --lang ch --kie True后出现报错

### ISSUE THREAD

**Issue by hjh55** [PaddlePaddle/PaddleOCR#8749]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：No LSB modules are available.
                                                       Distributor ID: Ubuntu
                                                       Description:    Ubuntu 18.04.5 LTS
                                                       Release:        18.04
                                                       Codename:       bionic

- 版本号/Version：Paddle：2.3.2  PaddleOCR： 问题相关组件/Related components：PPOCRLabel
- 运行指令/Command Code：PPOCRLabel --lang ch --kie True
- 完整报错/Complete Error Message：
- grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Error: Can not import avx core while this file exists: /usr/local/lib/python3.7/dist-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/usr/local/bin/PPOCRLabel", line 5, in <module>
    from PPOCRLabel.PPOCRLabel import main
  File "/usr/local/lib/python3.7/dist-packages/PPOCRLabel/PPOCRLabel.py", line 40, in <module>
    from paddleocr import PaddleOCR, PPStructure
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/usr/local/lib/python3.7/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /usr/lib/x86_64-linux-gnu/libGLX.so.0: undefined symbol: pthread_mutex_lock

**Comment by moyueheng** [comment]
没有人回答吗，遇到相同的问题了

**Comment by huangjun12** [comment]
可能是paddle版本有问题，升级一下paddle版本试试
