### ISSUE TITLE
windows下中文用户名识别报错找不到model文件，实际文件存在，英文用户名则正常

### ISSUE THREAD

**Issue by AIPythoner** [PaddlePaddle/PaddleOCR#8757]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows 11
- 版本号/Version：Paddle：2.3.2  PaddleOCR：2.5.0.3 问题相关组件/Related components：tools/infer/utility.py   predictor = inference.create_predictor(config)
- 运行指令/Command Code： from paddleocr import PaddleOCR

    ocr = PaddleOCR(use_angle_cls=True, lang="ch")
    msg_text_list = ocr.ocr(r'to_reply_form.png', cls=True)
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "D:/Code/mobduos/tigerkin-rpa-executor/flow/flows/pdd_workbench_reply/login.py", line 18, in <module>
    ocr = PaddleOCR(use_angle_cls=True, lang="ch")
  File "D:\Code\mobduos\pyenv\rpa\lib\site-packages\paddleocr\paddleocr.py", line 437, in __init__
    super().__init__(params)
  File "D:\Code\mobduos\pyenv\rpa\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "D:\Code\mobduos\pyenv\rpa\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 120, in __init__
    args, 'det', logger)
  File "D:\Code\mobduos\pyenv\rpa\lib\site-packages\paddleocr\tools\infer\utility.py", line 313, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file C:\Users\Administrator\Desktop\中文\ch_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1500)

**Comment by jingsongliujing** [comment]
PaddleOCR安装2.6

**Comment by andyjpaddle** [comment]
这应该是Windows兼容性问题，推荐使用全英文路径

**Comment by AIPythoner** [comment]
> PaddleOCR安装2.6
非优雅解决方案，我修改了paddleocr模块的model保存路径相关的代码，放入其他目录了

**Comment by jafer11** [comment]
具体修改哪里的代码呢？怎么解决啊？

**Comment by AIPythoner** [comment]
> 这应该是Windows兼容性问题，推荐使用全英文路径

不太可能是windows的问题，应该是c++模块 读取模型的时候没有考虑到中文路径
