### ISSUE TITLE
关于PaddleHub Serving的服务部署后开启并发就出现requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))的问题

### ISSUE THREAD

**Issue by Absurd2** [PaddlePaddle/PaddleOCR#8758]
机器：4个单核CPU
部署环境没有任何问题
使用并发的方式启动服务器
`hub serving start --modules ocr_system==1.0.0 --port 8866 --workers 4 --use_multiprocess`
如图片较大就会出现：
```
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\anaconda\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\anaconda\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\anaconda\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_hubserving.py", line 158, in <module>
    main(args)
  File "tools/test_hubserving.py", line 115, in main
    r = requests.post(
  File "D:\anaconda\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
PS E:\PaddleOCR-release-2.6> python tools/test_hubserving.py --server_url=http://192.168.10.6:8866/predict/ocr_system --image_dir=./doc/imgs/tests/test1.png
D:\anaconda\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
D:\anaconda\lib\site-packages\paddle\fluid\framework.py:634: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\anaconda\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\anaconda\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\anaconda\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_hubserving.py", line 158, in <module>
    main(args)
  File "tools/test_hubserving.py", line 115, in main
    r = requests.post(
  File "D:\anaconda\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

如果使用：
`hub serving start --modules ocr_system==1.0.0 --port 8866`
进行启动服务就无法并发，但是对于出现以上情况的图片有响应结果

**Comment by andyjpaddle** [comment]
可以试试调整下works的数量，另外看是否是RAM不足引起多线程报错

**Comment by Absurd2** [comment]
> 可以试试调整下works的数量，另外看是否是RAM不足引起多线程报错

你好，把workers改成1也会存在这个问题

**Comment by Absurd2** [comment]
> 可以试试调整下works的数量，另外看是否是RAM不足引起多线程报错

看了实时内存，也不会不够

**Comment by Absurd2** [comment]
> 可以试试调整下works的数量，另外看是否是RAM不足引起多线程报错

你好，请问有解决的方案吗

**Comment by Absurd2** [comment]
> 可以试试调整下works的数量，另外看是否是RAM不足引起多线程报错

你好请问是否还有其它的解决方法呢

**Comment by andyjpaddle** [comment]
目前没有了，可能是PaddleHub的并发机制问题

**Comment by Absurd2** [comment]
> 目前没有了，可能是PaddleHub的并发机制问题

paddleHub是不是也无法开启多线程？

**Comment by andyjpaddle** [comment]
我看了下PaddleHub的repo，也有部分人提了这个问题，好像官方还没有完全支持多线程，可以再问下PaddleHub那边

**Comment by Absurd2** [comment]
> 我看了下PaddleHub的repo，也有部分人提了这个问题，好像官方还没有完全支持多线程，可以再问下PaddleHub那边

好的，谢谢

**Comment by rexzhengzhihong** [comment]
我的改  "use_gpu": true就行
