### ISSUE TITLE
ocr关键信息抽取在预测的时候仅预测SER模型没问题。SER + RE模型串联预测的时候就一直报错

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#8833]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
 paddle                         1.0.2
paddle-bfloat                  0.1.2
paddle2onnx                    0.9.7
paddlefsl                      1.1.0
paddlenlp                      2.4.0
paddleocr                      2.6.1.2
paddlepaddle-gpu               2.4.1.post116
pandas                         1.1.5
pandocfilters                  1.5.0

- 运行指令/Command Code：
 SER + RE模型串联
```
python3 ./tools/infer_kie_token_ser_re.py \
  -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./train_data/XFUND/zh_val/image/zh_val_42.jpg \
  -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy 
```
- 完整报错/Complete Error Message：
```
[2023/01/12 15:07:35] ppocr INFO: resume from ./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
[2023-01-12 15:07:35,944] [    INFO] - Already cached /home/onez/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
[2023-01-12 15:07:36,231] [    INFO] - tokenizer config file saved in /home/onez/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2023-01-12 15:07:36,232] [    INFO] - Special tokens file saved in /home/onez/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2023/01/12 15:07:37] ppocr INFO: resume from ./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy
Traceback (most recent call last):
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/tools/infer_kie_token_ser_re.py", line 229, in <module>
    result = ser_re_engine(data)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/tools/infer_kie_token_ser_re.py", line 162, in __call__
    preds = self.model(re_input)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
    x = self.model(
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/onez/.local/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1492, in forward
    loss, pred_relations = self.extractor(sequence_output, entities,
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/onez/.local/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1368, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/home/onez/.local/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1318, in build_relation
    if len(entities[b]["start"]) <= 2:
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 753, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received str in 1th slice item (at /paddle/paddle/fluid/pybind/slice_utils.h:295)

```

**Comment by WenmuZhou** [comment]
paddlenlp要求2.4.1+

**Comment by rexzhengzhihong** [comment]
> paddlenlp要求2.4.1+

可以了
