### ISSUE TITLE
 no module named 'framework_pb2' 

### ISSUE THREAD

**Issue by vb6iscool** [PaddlePaddle/PaddleOCR#8895]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10
- 版本号/Version：Paddle：  PaddleOCR：2.4.1  问题相关组件/Related components：python 3.8.10
- 运行指令/Command Code：python -m pip install paddlepaddle==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
                                                python -m pip install paddleocr==2.4 -i https://pypi.tuna.tsinghua.edu.cn/simple 
                                                Pyinstaller -F py_ocr.py
- 完整报错/Complete Error Message：
![2023 1 24](https://user-images.githubusercontent.com/95078692/214243884-e9e97da6-bc6e-4b52-bbb8-3cfc2e138bcc.png)

我尝试了三天时间, 尝试安装其他版本的paddleOcr, 但是都失败了~! 不知道是什么原因, pyinstaller编译后的exe出现报错, 如上图;
有大侠说将: import framework_pb2 as framework__pb2
修改为:
import paddle.fluid.proto.framework_pb2 as framework__pb2
可以解决问题, 但是还是出现如下的报错:
![486448](https://user-images.githubusercontent.com/95078692/214244332-6cad2fcb-b1f5-4f4a-b8c9-c604be425305.png)

因为别人的电脑不一定有python, 所以需要打包exe, 但是总是打包失败, 希望有大神可以解救了, 非常感谢!!

-----------------------

![2023 1 24](https://user-images.githubusercontent.com/95078692/214245189-e618d1f6-16a8-4bee-86fc-ef2ff90e86ab.png)
I tried for three days, trying to install other versions of paddleOcr, but all failed~! I don't know why, the pyinstaller compiles the exe with an error, as shown in the picture above;
someone said that the:
import framework_pb2 as framework__pb2
modified to :
import paddle.fluid.proto.framework_pb2 as framework__pb2
could solves the problem, but it is not working for me, it still gives the following error:
![486448](https://user-images.githubusercontent.com/95078692/214245142-9dfa5257-cea6-49db-b49c-037f144870c1.png)

Because other people's computers do not necessarily have python, so need to package exe, but always package failure, plz help me, , thank you very much!

Translated with www.DeepL.com/Translator (free version)

**Comment by vb6iscool** [comment]
plz help~thx!!

**Comment by andyjpaddle** [comment]
you can try this method https://github.com/PaddlePaddle/PaddleOCR/issues/5326  
change the code of import cv2 in 'paddle\dataset\image.py'

**Comment by vb6iscool** [comment]
> 

thank you so much for help!!
but i still got the following error:


Microsoft Windows [版本 10.0.18363.418]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\py_codes\paddle_ocr_20230125\dist\py_ocr>py_ocr.exe
Traceback (most recent call last):
  File "py_ocr.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
    exec(bytecode, module.__dict__)
  File "paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
    exec(bytecode, module.__dict__)
  File "paddleocr\paddleocr.py", line 20, in <module>
    import paddle
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\__init__.py", line 76, in <module>
    import paddle.dataset  # noqa: F401
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\dataset\__init__.py", line 27, in <module>
    import paddle.dataset.flowers  # noqa: F401
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\dataset\flowers.py", line 39, in <module>
    from paddle.dataset.image import load_image_bytes
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\dataset\image.py", line 48, in <module>
    import_cv2_proc = subprocess.Popen([interpreter, "-c", "import cv2"],
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[6356] Failed to execute script 'py_ocr' due to unhandled exception!

C:\py_codes\paddle_ocr_20230125\dist\py_ocr>

**Comment by andyjpaddle** [comment]
it seems lack imghdr package, you can install it manually and then try again

**Comment by ArsalanAli915** [comment]
I am getting this error while using ppocr for recognition on my dataset. please help. I have tried to use pip install polygon but yet this problem occured.
LAUNCH INFO 2023-01-30 17:27:42,776 -----------  Configuration  ----------------------
LAUNCH INFO 2023-01-30 17:27:42,776 devices: None
LAUNCH INFO 2023-01-30 17:27:42,776 elastic_level: -1
LAUNCH INFO 2023-01-30 17:27:42,776 elastic_timeout: 30
LAUNCH INFO 2023-01-30 17:27:42,776 gloo_port: 6767
LAUNCH INFO 2023-01-30 17:27:42,776 host: None
LAUNCH INFO 2023-01-30 17:27:42,776 ips: None
LAUNCH INFO 2023-01-30 17:27:42,776 job_id: default
LAUNCH INFO 2023-01-30 17:27:42,776 legacy: False
LAUNCH INFO 2023-01-30 17:27:42,776 log_dir: log
LAUNCH INFO 2023-01-30 17:27:42,776 log_level: INFO
LAUNCH INFO 2023-01-30 17:27:42,776 master: None
LAUNCH INFO 2023-01-30 17:27:42,777 max_restart: 3
LAUNCH INFO 2023-01-30 17:27:42,777 nnodes: 1
LAUNCH INFO 2023-01-30 17:27:42,777 nproc_per_node: None
LAUNCH INFO 2023-01-30 17:27:42,777 rank: -1
LAUNCH INFO 2023-01-30 17:27:42,777 run_mode: collective
LAUNCH INFO 2023-01-30 17:27:42,777 server_num: None
LAUNCH INFO 2023-01-30 17:27:42,777 servers: 
LAUNCH INFO 2023-01-30 17:27:42,777 start_port: 6070
LAUNCH INFO 2023-01-30 17:27:42,777 trainer_num: None
LAUNCH INFO 2023-01-30 17:27:42,777 trainers: 
LAUNCH INFO 2023-01-30 17:27:42,777 training_script: tools/train.py
LAUNCH INFO 2023-01-30 17:27:42,777 training_script_args: ['-c', 'configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml', '-o', 'Global.pretrained_model=/content/PaddleOCR/pretrain_models/en_PP-OCRv3_rec_train/best_accuracy.pdparams']
LAUNCH INFO 2023-01-30 17:27:42,777 with_gloo: 1
LAUNCH INFO 2023-01-30 17:27:42,777 --------------------------------------------------
LAUNCH INFO 2023-01-30 17:27:42,777 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-01-30 17:27:42,778 Run Pod: tzkihv, replicas 1, status ready
LAUNCH INFO 2023-01-30 17:27:42,785 Watching Pod: tzkihv, replicas 1, status running
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    from ppocr.data import build_dataloader
  File "/content/PaddleOCR/ppocr/data/__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/content/PaddleOCR/ppocr/data/imaug/__init__.py", line 47, in <module>
    from .ct_process import *
  File "/content/PaddleOCR/ppocr/data/imaug/ct_process.py", line 22, in <module>
    import Polygon as plg
ModuleNotFoundError: No module named 'Polygon'
LAUNCH INFO 2023-01-30 17:27:47,793 Pod failed
LAUNCH ERROR 2023-01-30 17:27:47,793 Container failed !!!
Container rank 0 status failed cmd ['/usr/bin/python3', '-u', 'tools/train.py', '-c', 'configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml', '-o', 'Global.pretrained_model=/content/PaddleOCR/pretrain_models/en_PP-OCRv3_rec_train/best_accuracy.pdparams'] code 1 log log/workerlog.0 
env {'SHELL': '/bin/bash', 'NV_LIBCUBLAS_VERSION': '11.4.1.1043-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'NV_NVML_DEV_VERSION': '11.2.152-1', 'NV_CUDNN_PACKAGE_NAME': 'libcudnn8', 'GLIBCXX_FORCE_NEW': '1', 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events', 'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.2', 'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.8.4-1', 'VM_GCE_METADATA_HOST': '169.254.169.253', 'HOSTNAME': 'bd8f0f4288c2', 'TBE_RUNTIME_ADDR': '172.28.0.1:8011', 'GCE_METADATA_TIMEOUT': '3', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=450,driver<451', 'NV_LIBCUBLAS_DEV_PACKAGE': 'libcublas-dev-11-2=11.4.1.1043-1', 'NV_NVTX_VERSION': '11.2.152-1', 'NV_CUDA_CUDART_DEV_VERSION': '11.2.152-1', 'NV_LIBCUSPARSE_VERSION': '11.4.1.1152-1', 'NV_LIBNPP_VERSION': '11.3.2.152-1', 'NCCL_VERSION': '2.8.4-1', 'KMP_LISTEN_PORT': '6000', 'TF_FORCE_GPU_ALLOW_GROWTH': 'true', 'ENV': '/root/.bashrc', 'PWD': '/content/PaddleOCR', 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009', 'TBE_CREDS_ADDR': '172.28.0.1:8008', 'NV_CUDNN_PACKAGE': 'libcudnn8=8.1.1.33-1+cuda11.2', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'LAST_FORCED_REBUILD': '20221207', 'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-2=11.2.152-1', 'NV_LIBNPP_PACKAGE': 'libnpp-11-2=11.3.2.152-1', 'NV_LIBNCCL_DEV_PACKAGE_NAME': 'libnccl-dev', 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.19', 'GLIBCPP_FORCE_NEW': '1', 'NV_LIBCUBLAS_DEV_VERSION': '11.4.1.1043-1', 'NV_LIBCUBLAS_DEV_PACKAGE_NAME': 'libcublas-dev-11-2', 'LD_PRELOAD': '/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4', 'USE_AUTH_EPHEM': '1', 'NV_CUDA_CUDART_VERSION': '11.2.152-1', 'HOME': '/root', 'LANG': 'en_US.UTF-8', 'CUDA_VERSION': '11.2.2', 'CLOUDSDK_CONFIG': '/content/.config', 'NV_LIBCUBLAS_PACKAGE': 'libcublas-11-2=11.4.1.1043-1', 'COLAB_RELEASE_TAG': 'release-colab-20230126-060047-RC00', 'PYDEVD_USE_FRAME_EVAL': 'NO', 'KMP_TARGET_PORT': '9000', 'CLICOLOR': '1', 'KMP_EXTRA_ARGS': '--listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/m-s-2i58y3ypkfkvb --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true', 'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-2=11.3.2.152-1', 'NV_LIBCUBLAS_PACKAGE_NAME': 'libcublas-11-2', 'CLOUDSDK_PYTHON': 'python3', 'NV_LIBNPP_DEV_VERSION': '11.3.2.152-1', 'ENABLE_DIRECTORYPREFETCHER': '1', 'NO_GCE_CHECK': 'False', 'JPY_PARENT_PID': '87', 'PYTHONPATH': '/env/python', 'TERM': 'xterm-color', 'NV_LIBCUSPARSE_DEV_VERSION': '11.4.1.1152-1', 'GIT_PAGER': 'cat', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'NV_CUDNN_VERSION': '8.1.1.33', 'SHLVL': '0', 'PAGER': 'cat', 'NV_CUDA_LIB_VERSION': '11.2.2-1', 'NVARCH': 'x86_64', 'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.12","jupyterArgs":["--ip=172.28.0.12","--transport=ipc"],"debugAdapterMultiplexerPath":"/usr/local/bin/dap_multiplexer","enableLsp":true}', 'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.1.1.33-1+cuda11.2', 'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-2', 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline', 'NV_LIBNCCL_PACKAGE': 'libnccl2=2.8.4-1+cuda11.2', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'GCS_READ_CACHE_BLOCK_SIZE_MB': '16', 'NV_NVPROF_VERSION': '11.2.152-1', 'PATH': '/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin', 'NV_LIBNCCL_PACKAGE_NAME': 'libnccl2', 'NV_LIBNCCL_PACKAGE_VERSION': '2.8.4-1', 'PYTHONWARNINGS': 'ignore:::pip._internal.cli.base_command', 'DEBIAN_FRONTEND': 'noninteractive', 'COLAB_BACKEND_VERSION': 'next', 'OLDPWD': '/', '_': '/usr/bin/python3', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/usr/local/lib/python3.8/dist-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/usr/local/lib/python3.8/dist-packages/cv2/qt/fonts', 'POD_NAME': 'tzkihv', 'PADDLE_MASTER': '172.28.0.12:38176', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '172.28.0.12:38177', 'PADDLE_CURRENT_ENDPOINT': '172.28.0.12:38177', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'PADDLE_DISTRI_BACKEND': 'gloo'}
LAUNCH INFO 2023-01-30 17:27:47,793 ------------------------- ERROR LOG DETAIL -------------------------
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    from ppocr.data import build_dataloader
  File "/content/PaddleOCR/ppocr/data/__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "/content/PaddleOCR/ppocr/data/imaug/__init__.py", line 47, in <module>
    from .ct_process import *
  File "/content/PaddleOCR/ppocr/data/imaug/ct_process.py", line 22, in <module>
    import Polygon as plg
ModuleNotFoundError: No module named 'Polygon'
LAUNCH INFO 2023-01-30 17:27:47,794 Exit code 1

**Comment by andyjpaddle** [comment]
try `pip install Polygon3`

**Comment by ashlod** [comment]
> it seems lack imghdr package, you can install it manually and then try again

Did it work?

**Comment by ArsalanAli915** [comment]
Yes, it is working.

**Comment by ashlod** [comment]
> you can try this method #5326 change the code of import cv2 in 'paddle\dataset\image.py'

I tried to change the code of image.py, but I still got  the following error:
Hope somebody could help, plz!
Traceback (most recent call last):
  File "GUI_Re_Test.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\paddleocr.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\__init__.py", line 76, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\dataset\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\dataset\flowers.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\dataset\image.py", line 48, in <module>
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by ashlod** [comment]
I am getting this error, and tried pip install tools in my envs, but it didn't work.
Hopefully somebody could help!

Traceback (most recent call last):
  File "GUI_Re_Test.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\paddleocr.py", line 33, in <module>
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'tools'
