### ISSUE TITLE
paddle nlp error while inferencing ser model

### ISSUE THREAD

**Issue by Tanmay98** [PaddlePaddle/PaddleOCR#8897]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu 20.04
- 版本号/Version：Paddle：2.3.1  PaddleOCR：2.6.1.2 问题相关组件/Related components：paddlenlp 2.3.1
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
/usr/local/lib/python3.8/dist-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
[2023-01-24 16:17:47,695] [    INFO] - Already cached /root/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
Traceback (most recent call last):
  File "PaddleOCR/ppstructure/kie/predict_kie_token_ser.py", line 177, in <module>
    main(parse_args())
  File "PaddleOCR/ppstructure/kie/predict_kie_token_ser.py", line 134, in main
    ser_predictor = SerPredictor(args)
  File "PaddleOCR/ppstructure/kie/predict_kie_token_ser.py", line 95, in __init__
    self.preprocess_op = create_operators(pre_process_list,
  File "/root/tma/PaddleOCR/ppocr/data/imaug/__init__.py", line 78, in create_operators
    op = eval(op_name)(**param)
  File "/root/tma/PaddleOCR/ppocr/data/imaug/label_ops.py", line 970, in __init__
    self.tokenizer = tokenizer_config['class'].from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1626, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlenlp/transformers/utils.py", line 86, in __impl__
    init_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlenlp/transformers/layoutxlm/tokenizer.py", line 95, in __init__
    self.sp_model.Load(vocab_file)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
Traceback (most recent call last):

**Comment by andyjpaddle** [comment]
try to update the paddlenlp package
