### ISSUE TITLE
window10 使用命令行paddleocr 命令识别pdf，提示没有pageCount属性是啥意思？ 

### ISSUE THREAD

**Issue by HysUnknown** [PaddlePaddle/PaddleOCR#8914]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：2.6.1.2
- 运行指令/Command Code：paddleocr --image_dir ./test.pdf --use_angle_cls true --use_gpu
 false --page_num 7
- 完整报错/Complete Error Message：
`
Traceback (most recent call last):
  File "D:\software\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\Anaconda3\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "D:\software\Anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 673, in main
    result = engine.ocr(img_path,
  File "D:\software\Anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 544, in ocr
    img = check_img(img)
  File "D:\software\Anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 434, in check_img
    img, flag_gif, flag_pdf = check_and_read(image_file)
  File "D:\software\Anaconda3\lib\site-packages\paddleocr\ppocr\utils\utility.py", line 96, in check_and_read
    for pg in range(0, pdf.pageCount):
AttributeError: 'Document' object has no attribute 'pageCount'
`

**Comment by HysUnknown** [comment]
已解决，paddleocr关联下载的 PyMuPDF过高，降低 PyMuPDF版本就可以了

**Comment by zgpnuaa** [comment]
> 已解决，paddleocr关联下载的 PyMuPDF过高，降低 PyMuPDF版本就可以了

你好，降低到哪个版本可以解决问题啊 @HysUnknown

**Comment by zgpnuaa** [comment]
找到了 that property  has been deprecated since June 2021 (v1.18.14) and was removed in June 2022 (v1.20.0).
Use Document.page_count instead. @HysUnknown @MissPenguin
