### ISSUE TITLE
PPOCRLabel无法启动

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/PaddleOCR#8941]
paddlepaddle：2.3.2
paddleocr：2.6.1.2
ppocrlabel：2.1.3

启动命令：
`PPOCRLabel --lang ch --kie True`
提示错误：
`Traceback (most recent call last):
  File "...\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\Python\Python37\Scripts\PPOCRLabel.exe\__main__.py", line 4, in <module>
  File "...\python\python37\lib\site-packages\PPOCRLabel\PPOCRLabel.py", line 56, in <module>
    from libs.keyDialog import KeyDialog
  File "...\python\python37\lib\site-packages\PPOCRLabel\libs\keyDialog.py", line 6, in <module>
    from PyQt5.Qt import QT_VERSION_STR
ImportError: cannot import name 'QT_VERSION_STR' from 'PyQt5.Qt' (...\python\python37\lib\site-packages\PyQt5\Qt.pyd)`

**Comment by leoterry-ulrica** [comment]
问题已解决
需要把PyQT5的版本降低为5.12.1，高版本存在兼容性问题。

**Comment by jingsongliujing** [comment]
建议直接clone源码下来：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel，在这个目录下运行：python PPOCRLabel.py

**Comment by leoterry-ulrica** [comment]
> 建议直接clone源码下来：[https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel，在这个目录下运行：python](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel%EF%BC%8C%E5%9C%A8%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%E4%B8%8B%E8%BF%90%E8%A1%8C%EF%BC%9Apython) PPOCRLabel.py

如果不降低PyQT5的版本，在源码中启动也同样报错的。

**Comment by ArsalanAli915** [comment]
I am getting this error when traing the ppocr.
Exception: /content/drive/MyDrive/dataset/train_data/rec/train/49.png, does not exist!

[2023/02/02 19:09:42] ppocr ERROR: When parsing line 12.png,	"Safa"
, error happened with msg: Traceback (most recent call last):
  File "/content/PaddleOCR/ppocr/data/simple_dataset.py", line 132, in __getitem__
    raise Exception("{} does not exist!".format(img_path))
Exception: /content/drive/MyDrive/dataset/train_data/rec/train/12.png, does not exist!

[2023/02/02 19:09:42] ppocr ERROR: When parsing line 37.png,	"###"
, error happened with msg: Traceback (most recent call last):
  File "/content/PaddleOCR/ppocr/data/simple_dataset.py", line 132, in __getitem__
    raise Exception("{} does not exist!".format(img_path))
Exception: /content/drive/MyDrive/dataset/train_data/rec/train/37.png, does not exist!

[2023/02/02 19:09:42] ppocr ERROR: When parsing line 41.png,	"###"
, error happened with msg: Traceback (most recent call last):
  File "/content/PaddleOCR/ppocr/data/simple_dataset.py", line 132, in __getitem__
    raise Exception("{} does not exist!".format(img_path))
Exception: /content/drive/MyDrive/dataset/train_data/rec/train/41.png, does not exist!


please help.
