### ISSUE TITLE
pyinstaller 打包 PPOCRLabel报错AssertionError: Missing string id : tempLabel

### ISSUE THREAD

**Issue by LeoRainly** [PaddlePaddle/PaddleOCR#8980]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows
- 版本号/Version：Paddle：2.0.0  PaddleOCR：2.0 问题相关组件/Related components：

  (PaddleOCR2.6可直接使用命令PPOCRLabel正常运行，而python PPOCRLabel.py运行打开后使用自动标注会报错
list index out of range
Traceback (most recent call last):
  File "G:\projects2\PaddleOCR-release-2.6\PPOCRLabel\libs\autoDialog.py", line 56, in run
    chars = res[1][0]
IndexError: list index out of range 
因此使用PaddleOCR2.0打包)

- 运行指令/Command Code：pyinstaller -D -c PPOCRLabel.py后 运行PPOCRLabel.exe
- 完整报错/Complete Error Message：
(work) F:\projects\PaddleOCR-release-2.0\PPOCRLabel\dist\PPOCRLabel>PPOCRLabel.exe
Loading setting failed
Namespace(cls=True, cls_batch_num=30, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\leora/.paddleocr/2.0/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:\\Users\\leora/.paddleocr/2.0/det', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=30, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:\\Users\\leora/.paddleocr/2.0/rec/ch', use_angle_cls=True, use_dilation=False, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)
Traceback (most recent call last):
  File "PaddleOCR-release-2.0\PPOCRLabel\PPOCRLabel.py", line 2005, in <module>
    output = os.system('pyrcc5 -o libs/resources.py resources.qrc')
  File "PaddleOCR-release-2.0\PPOCRLabel\PPOCRLabel.py", line 1993, in main

  File "PaddleOCR-release-2.0\PPOCRLabel\PPOCRLabel.py", line 1986, in get_main_app
    args = argparser.parse_args(argv[1:])
  File "PaddleOCR-release-2.0\PPOCRLabel\PPOCRLabel.py", line 149, in __init__
    self.shapesToItems = {}
  File "PaddleOCR-release-2.0\PPOCRLabel\PPOCRLabel.py", line 108, in <lambda>
    print('**lang:', lang)
  File "libs\stringBundle.py", line 42, in getString
    @classmethod
AssertionError: Missing string id : tempLabel
[25116] Failed to execute script 'PPOCRLabel' due to unhandled exception!

求解决

**Comment by LXX230** [comment]
您好，我也出现了类似问题，请问您解决了没有？
Traceback (most recent call last):
  File "PPOCRLabel\PPOCRLabel.py", line 2840, in <module>
  File "PPOCRLabel\PPOCRLabel.py", line 2828, in main
  File "PPOCRLabel\PPOCRLabel.py", line 2818, in get_main_app
  File "PPOCRLabel\PPOCRLabel.py", line 94, in __init__
  File "PPOCRLabel\PPOCRLabel.py", line 88, in <lambda>
  File "C:\PPOCRLabel\dist\PPOCRLabel\_internal\libs\stringBundle.py", line 58, in getString
    assert(stringId in self.idToMessage), "Missing string id : " + stringId
AssertionError: Missing string id : keyDialogTip
