### ISSUE TITLE
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

### ISSUE THREAD

**Issue by hemantsummit** [PaddlePaddle/PaddleOCR#8986]
I have been doing the training for the FUNSD dataset with the given config file and getting the below error, can someone help me?
`
Traceback (most recent call last):
  File "/home/ubuntu/compile/paddleOcr/tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/ubuntu/compile/paddleOcr/tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/ubuntu/compile/paddleOcr/tools/program.py", line 258, in train
    for idx, batch in enumerate(train_dataloader):
  File "/home/ubuntu/miniconda3/envs/pad_env/lib/python3.9/site-packages/paddle/fluid/reader.py", line 567, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/ubuntu/miniconda3/envs/pad_env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 345, in __init__
    super(_DataLoaderIterMultiProcess, self).__init__(loader)
  File "/home/ubuntu/miniconda3/envs/pad_env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 99, in __init__
    self._prefetch_factor = loader.prefetch_factor
AttributeError: 'DataLoader' object has no attribute 'prefetch_factor'
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7fbd69ca28b0>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pad_env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 715, in __del__
    self._try_shutdown_all()
  File "/home/ubuntu/miniconda3/envs/pad_env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
`

yml config file 
[https://github.com/harshsummit/paddleOcr/blob/release/2.6/configs/kie/vi_layoutxlm/re_layoutxlm_funsd.yml](https://github.com/harshsummit/paddleOcr/blob/release/2.6/configs/kie/vi_layoutxlm/re_layoutxlm_funsd.yml)

**Comment by andyjpaddle** [comment]
please provide more info about your environment, eg, platform, paddle version, CUDA version, code version. 
before training, you should check paddlepaddle is installed successfully

**Comment by hemantsummit** [comment]
I am running it on aws ec2 instance p3.2xlarge. I have checked the paddlepaddle is installed perfectly and util checks are running. 
CUDA version - 11.2
paddle version - 2.4.1
environment - Ubuntu 20.4
I trained ser model for FUNSD. It worked perfectly but for re it is giving above error.

**Comment by andyjpaddle** [comment]
please try to update paddlenlp package

**Comment by harshsummit** [comment]
@andyjpaddle on updating paddlenlp, it gives an error for tensor input
which is resolved at version 2.3.1
