### ISSUE TITLE
SVTR模型转为inference失败

### ISSUE THREAD

**Issue by LUXUS1** [PaddlePaddle/PaddleOCR#9006]
使用网盘中提供的config.yml转换SVTR模型报如下错误：
`[2023/02/08 11:29:38] ppocr INFO: load pretrain successful from ./seal_models/SVTR/best_accuracy
Traceback (most recent call last):
  File "tools/export_model.py", line 269, in <module>
    main()
  File "tools/export_model.py", line 251, in main
    input_shape = config["Eval"]["dataset"]["transforms"][-2][
KeyError: 'SVTRRecResizeImg'`
使用configs/rec/rec_svtrnet_ch.yml的模型可以转换成功，但识别文字出现乱码
`[2023/02/08 11:06:20] ppocr INFO: In PP-OCRv3, rec_image_shape parameter defaults to '3, 48, 320', if you are using recognition model with PP-OCRv2 or an older version, please set --rec_image_shape='3,32,320
[2023/02/08 11:06:20] ppocr INFO: Predicts of ./images/5.jpg:('鏖轿高ˋ傍打默痒棍炊ˋ积ˋ鏖慷鏖ˋ痒鏖戎积ˋ倭慷鏖戎蝾戎淇', 0.010082118213176727)`
**将config.yml中的image_shape与configs/rec/rec_svtrnet_ch.yml中修改一致，仍然转换错误**

**Comment by LUXUS1** [comment]
已解决，需要将configyml文件中的‘- RecResizeImg:'修改为' - SVTRRecResizeImg:'
![image](https://user-images.githubusercontent.com/57226206/217445283-96c493a0-d997-4ee0-9568-3da513b3f61b.png)

**Comment by LUXUS1** [comment]
已解决，需要将configyml文件中的‘- RecResizeImg:'修改为' - SVTRRecResizeImg:'
![image](https://user-images.githubusercontent.com/57226206/217445283-96c493a0-d997-4ee0-9568-3da513b3f61b.png)
