### ISSUE TITLE
Training SVTR in grayscale mode

### ISSUE THREAD

**Issue by susanin1970** [PaddlePaddle/PaddleOCR#9062]
Hello, thanks for great repo :)
I have a question about possibility of training SVTR model in grayscale mode  

I tried to change number of input channel in parameter `image_shape` of SVTR configAlso I :  
```yaml
transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          character_dict_path: D:\Repositories\PaddleOCR\ppocr\utils\wagons_numbers_dict.txt
          image_shape: [1, 64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order

```  

but I got followed error:  
```
[2022/12/13 13:40:57] ppocr ERROR: When parsing line D:\Datasets\ArcisNumbers\DATA4\58410986_#1_040781.bmp      58410986
, error happened with msg: Traceback (most recent call last):
  File "D:\Repositories\PaddleOCR\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\rec_img_aug.py", line 462, in __call__
    norm_img, valid_ratio = resize_norm_img(img, self.image_shape, self.padding)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\rec_img_aug.py", line 548, in resize_norm_img
    padding_im[:, :, 0:resized_w] = resized_image
ValueError: could not broadcast input array from shape (64,256,3) into shape (1,64,256)
```  

Also I tried to add `GrayImageChannelFormat` parameter in `transforms` section of format, because I found implementation of this class in `operators.py`:  

```yaml
transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - GrayImageChannelFormat:
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          character_dict_path: D:\Repositories\PaddleOCR\ppocr\utils\wagons_numbers_dict.txt
          image_shape: [3, 64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
```  

but I got error again:
```
```
[2022/12/13 15:21:37] ppocr ERROR: When parsing line D:\Datasets\ArcisNumbers\DATA4\56796279_#4_005214.bmp      56796279
, error happened with msg: Traceback (most recent call last):
  File "D:\Repositories\PaddleOCR\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\rec_img_aug.py", line 462, in __call__
    norm_img, valid_ratio = resize_norm_img(img, self.image_shape, self.padding)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\rec_img_aug.py", line 548, in resize_norm_img
    padding_im[:, :, 0:resized_w] = resized_image
ValueError: could not broadcast input array from shape (290,64,256) into shape (3,64,256)
```

Is it currently possible to train the SVTR model in grayscale mode
Thanks in advance :)

**Comment by susanin1970** [comment]
Also I tried to change image mode from BGR to GRAY:
```yaml
transforms:
      - DecodeImage: # load image
          img_mode: GRAY
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          character_dict_path: D:\Repositories\PaddleOCR\ppocr\utils\wagons_numbers_dict.txt
          image_shape: [1, 64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
```
but I got another error:  
```
[2022/12/13 14:39:59] ppocr ERROR: When parsing line D:\Datasets\ArcisNumbers\DATA4\94023298_#3_003131.bmp      94023298
, error happened with msg: Traceback (most recent call last):
  File "D:\Repositories\PaddleOCR\ppocr\data\simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\__init__.py", line 56, in transform
    data = op(data)
  File "D:\Repositories\PaddleOCR\ppocr\data\imaug\operators.py", line 59, in __call__
    img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
cv2.error: OpenCV(4.6.0) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<1,-1,-1>,struct cv::impl::A0xf2302844::Set<3,4,-1>,struct cv::impl::A0xf2302844::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 3
```

**Comment by LDOUBLEV** [comment]
> img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
cv2.error: OpenCV(4.6.0) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<1,-1,-1>,struct cv::impl::A0xf2302844::Set<3,4,-1>,struct cv::impl::A0xf2302844::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 3


Please check whether the input image is Gray Image or not. 

https://github.com/PaddlePaddle/PaddleOCR/blob/d78b945608a6599e0b97101ce9f31e2d5ca89469/ppocr/data/imaug/operators.py#L58-L63

When setting the img_mode is 'GRAY', the input will be converted to BGR mode.
