### ISSUE TITLE
RuntimeError: (NotFound) The kernel with key (CPU, NCHW, float16) of kernel `conv2d` is not registered.

### ISSUE THREAD

**Issue by Mrfuhang** [PaddlePaddle/PaddleOCR#9079]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：window10
- 版本号/Version：Paddle：2.4.1  PaddleOCR：2.6.1.3  问题相关组件/Related components：执行混合精度命令报错
- 运行指令/Command Code：
python C:\Users\fuhang\Project\OcrProject\PaddleOCR\tools\train.py -c configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml -o Global.pretrained_model=./pretrain_models/en_PP-OCRv3_rec_train/best_accuracy Global.use_amp=True Global.scale_loss=1024.0 Global.use_dynamic_loss_scaling=True
- 完整报错/Complete Error Message：

[2023/02/15 10:35:19] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations
Traceback (most recent call last):
  File "C:\Users\fuhang\Project\OcrProject\PaddleOCR\tools\train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "C:\Users\fuhang\Project\OcrProject\PaddleOCR\tools\train.py", line 183, in main
    amp_level, amp_custom_black_list)
  File "C:\Users\fuhang\Project\OcrProject\PaddleOCR\tools\program.py", line 273, in train
    preds = model(images, data=batch[1:])
  File "C:\Users\fuhang\tools\Envs\paddleOCR_py37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\fuhang\Project\OcrProject\PaddleOCR\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "C:\Users\fuhang\tools\Envs\paddleOCR_py37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\fuhang\Project\OcrProject\PaddleOCR\ppocr\modeling\backbones\rec_mv1_enhance.py", line 223, in forward
    y = self.conv1(inputs)
  File "C:\Users\fuhang\tools\Envs\paddleOCR_py37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\fuhang\Project\OcrProject\PaddleOCR\ppocr\modeling\backbones\rec_mv1_enhance.py", line 63, in forward
    y = self._conv(inputs)
  File "C:\Users\fuhang\tools\Envs\paddleOCR_py37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\fuhang\tools\Envs\paddleOCR_py37\lib\site-packages\paddle\nn\layer\conv.py", line 724, in forward
    use_cudnn=self._use_cudnn,
  File "C:\Users\fuhang\tools\Envs\paddleOCR_py37\lib\site-packages\paddle\nn\functional\conv.py", line 151, in _conv_nd    False,
RuntimeError: (NotFound) The kernel with key (CPU, NCHW, float16) of kernel `conv2d` is not registered.
  [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at ..\paddle\phi\core\kernel_factory.cc:147)

**Comment by tink2123** [comment]
CPU 不支持混合精度训练，请使用GPU 或关闭混合精度， --use_gpu=True or use_amp=False

**Comment by Mrfuhang** [comment]
> 在win10 系统   改成  use_amp=False  之后   ，内存消耗了  9 G  ， 这个正常不？
