### ISSUE TITLE
How to train FUNSD KIE RE model

### ISSUE THREAD

**Issue by harshsummit** [PaddlePaddle/PaddleOCR#9121]
I have tried each and every solution to train KIE RE model for FUNSD dataset, but have got no lead, everytime have recieved one or another error.

If someone has successfully trained model on custom dataset please tell me your dataset strcuture,
PaddlePaddle version, PaddleOCR version, PaddleNLP version CUDA and CUDNN version, and the environment used.

I have been trying over two weeks but not able to train RE model on any custom dataset.

**Comment by TasneemVKhan** [comment]
What is your error?

**Comment by an1018** [comment]
@harshsummit we provide the scipts of FUNSD，you can refer to :https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/kie_en.md#13-download-data
![image](https://user-images.githubusercontent.com/19808900/219657384-23bf874d-79b7-445f-be42-3e7fbe17a22a.png)

And  the format of train datasets is also provided:https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/kie_en.md#12-custom-dataset

**Comment by harshsummit** [comment]
@TasneemVKhan I get Floating Point Exception (Core Dumped) Error when training on GPU, and 
"Indices can be only integer, float, tuple, but given string in a Tensor error"

**Comment by harshsummit** [comment]
@an1018 I have formatted the data as per requirement and structure as well, I have literally replaced just the images and content of train.json, val.json of XFUND dataset with FUNSD dataset content, so as to maintain the structure and remove any ambiguity

**Comment by TasneemVKhan** [comment]
Did you the convert the dataset to PPOCRLabel format ?

**Comment by harshsummit** [comment]
Yes I did

**Comment by TasneemVKhan** [comment]
Can you share your dataset ?

**Comment by harshsummit** [comment]
@TasneemVKhan I tried doing it manually and also tried the script to convert

**Comment by TasneemVKhan** [comment]
How did you label your DataSet ?

**Comment by harshsummit** [comment]
@TasneemVKhan dataset https://file.io/8P2J5emm1JCQ

**Comment by harshsummit** [comment]
Its pre labeled dataset as given in the links in paddle KIE dataset documentation
https://paddleocr.bj.bcebos.com/ppstructure/dataset/FUNSD.tar
Here is the official link

**Comment by harshsummit** [comment]
I am able to train the model for SER, on this dataset, but as soon as I try for RE training it pops up a floating point exception error

**Comment by TasneemVKhan** [comment]
I'll look into it and let you know the results

**Comment by harshsummit** [comment]
Yeah please @TasneemVKhan

**Comment by hemantsummit** [comment]
@TasneemVKhan  any updat?

**Comment by munish0838** [comment]
@harshsummit @TasneemVKhan Any updates?

**Comment by NaumanHSA** [comment]
@harshsummit @TasneemVKhan 
Things got working for me with GTX 3080 ti desktop, CUDA 11.7, CuDNN 8.4.1 and Ubuntu 20.04. I tried first on windows and was running on Floating Point issue. I also tried using RTX4070 using Ubuntu 18, then I got Core Dump Error which is ofcourse because of less GPU memory.

With my current system, with batch_size 8 I got Core Dump error. Then I reduced the batch_size to 2, it's not working. On first 10 epochs on FUNSD dataset, I got recall of 0.84 and precision 0.82.

**Comment by harshsummit** [comment]
@NaumanHSA if you were sucessfully able to train the model, can you please share it?

**Comment by NaumanHSA** [comment]
@harshsummit I just started the training process but I didn't continue it. I trained it on my custom dataset. 

Which GPU you have? If you have setup like mine, you can try training using Ubuntu. If you face core dump error, remember it will be because of not enough GPU memory. I hope things will work for you.

**Comment by hemantsummit** [comment]
@NaumanHSA did you trained ser or re because ser worked we are facing problem in re also we get floating point exception

**Comment by NaumanHSA** [comment]
I have tried SER only for the FUNSD. However, on my custom dataset, I'm able to do the SER and RE both. Sorry, I didn't read the title properly. I'll try RE also on the FUNSD dataset, will update you if it worked.

**Comment by harshsummit** [comment]
@NaumanHSA if you have a working re model, please do share if its on english documents

**Comment by NaumanHSA** [comment]
@harshsummit my current models is only for ID cards with very little images. I don't know if it will work for you? I'll soon train another model on different types of document, it will be generic. I'll then share with you.

**Comment by harshsummit** [comment]
Okay sure @NaumanHSA

**Comment by munish0838** [comment]
Were you able to train the model on FUNSD? Any updates guys? @harshsummit @hemantsummit @NaumanHSA

**Comment by feixian15** [comment]
have you solved the problem？ i also meet the issue when i train re model on my custom dataset   @harshsummit @hemantsummit @NaumanHSA

**Comment by minhduc01168** [comment]
@NaumanHSA  I trained the RE task on my custom dataset and got this error with paddlenlp version. Can you help me?
Version：paddlepaddle-gpu==2.6.0,  paddlenlp==2.6.0
list index out of range
(…)s/layoutxlm_base/sentencepiece.bpe.model: 100%|█| 5.07M/5.07M [00:16<00:00, 3
[2024-05-31 16:44:44,142] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2024-05-31 16:44:44,142] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2024/05/31 16:44:44] ppocr INFO: Initialize indexs of datasets:['train_data/GiayKhaiSinh/val/val.json']
[2024-05-31 16:44:44,687] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2024-05-31 16:44:44,687] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2024-05-31 16:44:44,693] [ WARNING] - You are using a model of type layoutlmv2 to instantiate a model of type layoutxlm. This is not supported for all configurations of models and can yield errors.
(…)outxlm-base-uncased/model_state.pdparams: 100%|█| 1.12G/1.12G [01:05<00:00, 1
[2024-05-31 16:45:50,438] [    INFO] - Loading weights file from cache at /root/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2024-05-31 16:45:51,777] [    INFO] - Loaded weights file from disk, setting weights to model.
W0531 16:45:51.780944   169 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.2, Runtime API Version: 11.8
W0531 16:45:51.782017   169 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
[2024-05-31 16:45:53,983] [ WARNING] - Some weights of the model checkpoint at vi-layoutxlm-base-uncased were not used when initializing LayoutXLMForRelationExtraction: ['visual.pixel_mean', 'visual.pixel_std', 'visual_proj.bias', 'visual_proj.weight']
- This IS expected if you are initializing LayoutXLMForRelationExtraction from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LayoutXLMForRelationExtraction from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2024-05-31 16:45:53,984] [ WARNING] - Some weights of LayoutXLMForRelationExtraction were not initialized from the model checkpoint at vi-layoutxlm-base-uncased and are newly initialized: ['extractor.ffnn_tail.0.weight', 'extractor.ffnn_head.0.bias', 'extractor.ffnn_tail.3.bias', 'extractor.ffnn_tail.3.weight', 'extractor.rel_classifier.bilinear.weight', 'extractor.ffnn_head.3.weight', 'extractor.entity_emb.weight', 'extractor.ffnn_tail.0.bias', 'extractor.ffnn_head.0.weight', 'extractor.ffnn_head.3.bias', 'extractor.rel_classifier.linear.bias', 'extractor.rel_classifier.linear.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[2024/05/31 16:45:54] ppocr INFO: train dataloader has 40 iters
[2024/05/31 16:45:54] ppocr INFO: valid dataloader has 3 iters
[2024/05/31 16:45:54] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 40 iterations
Traceback (most recent call last):
  File "/kaggle/working/PaddleOCR_GKS_v2_re/tools/train.py", line 255, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "/kaggle/working/PaddleOCR_GKS_v2_re/tools/train.py", line 208, in main
    program.train(
  File "/kaggle/working/PaddleOCR_GKS_v2_re/tools/program.py", line 339, in train
    preds = model(batch)
  File "/opt/conda/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/kaggle/working/PaddleOCR_GKS_v2_re/ppocr/modeling/architectures/base_model.py", line 85, in forward
    x = self.backbone(x)
  File "/opt/conda/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/kaggle/working/PaddleOCR_GKS_v2_re/ppocr/modeling/backbones/vqa_layoutlm.py", line 248, in forward
    x = self.model(
  File "/opt/conda/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/opt/conda/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/opt/conda/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1189, in build_relation
    if negative_mask.sum() > 0:
AttributeError: 'bool' object has no attribute 'sum'

**Comment by NaumanHSA** [comment]
@minhduc01168 This is probably the issue with the versions. Are you trying with PPOCRv4 or PPOCRv3? Can you try paddlepaddle-gpu version 2.4.2? Also, try downgrading paddlenlp version if you have installed the latest one.

**Comment by minhduc01168** [comment]
@NaumanHSA I have a new mission. I have trained the SER and RE models on my custom data set. Now I need to replace the ocr paddle module with my ocr module but I haven't found specific instructions for this task. Can you help me or is there any resource you know? Sorry for my bad English

**Comment by minhduc01168** [comment]
@NaumanHSA Do you know what format the input of the SER model is?

**Comment by NaumanHSA** [comment]
@minhduc01168 It has been some time I haven't worked with their SER and RE algos. As I remember the workflow, it first do text detection and recognition to get the bboxes and the text. Combined information of bboxes and text are then passed to the SER to classify them as a question, answer, header or other. Finally, all these information are used by RE to make the key, value pairs. 

As in your case, it's pretty easy to replace PaddleOCR with your own OCR. You just need to find the code where outputs from the PPOCR are being passed in the SER pipeline. Remember, you may need bbox coordinates and the text inside for SER to work. Also, it is worth noticing that the SER is greatly dependent on the recognition, and so the RE is dependent on the SER. There can be some bottlenecks to take care of. Hope that helps you.
