### ISSUE TITLE
当时尝试用CPU训练的时候报错了

### ISSUE THREAD

**Issue by QianquanChina** [PaddlePaddle/PaddleOCR#9123]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：**OS：Arch Linux x86_64,  Kernel: Linux 6.1.11-arch1-1**
- 版本号/Version： **paddlepaddle 的版本是 2.4.1，PaddleOCR的版本是 2.6**
- 运行指令/Command Code：**python tools/train.py -c configs/table/SLANet_ch.yml**
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/jc/Study/DeepLearn/Pytorch/Ocr/PaddleOCR-release-2.6/tools/program.py", line 288, in train
    preds = model(images, data=batch[1:])
  File "/home/jc/.local/share/anaconda3/envs/Test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/jc/Study/DeepLearn/Pytorch/Ocr/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 93, in forward
    x = self.neck(x)
  File "/home/jc/.local/share/anaconda3/envs/Test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/jc/Study/DeepLearn/Pytorch/Ocr/PaddleOCR-release-2.6/ppocr/modeling/necks/csp_pan.py", line 300, in forward
    inputs = self.conv_t(inputs)
  File "/home/jc/.local/share/anaconda3/envs/Test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/jc/Study/DeepLearn/Pytorch/Ocr/PaddleOCR-release-2.6/ppocr/modeling/necks/csp_pan.py", line 228, in forward
    outs = [self.convs[i](x[i]) for i in range(len(x))]
  File "/home/jc/Study/DeepLearn/Pytorch/Ocr/PaddleOCR-release-2.6/ppocr/modeling/necks/csp_pan.py", line 228, in <listcomp>
    outs = [self.convs[i](x[i]) for i in range(len(x))]
  File "/home/jc/.local/share/anaconda3/envs/Test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/jc/Study/DeepLearn/Pytorch/Ocr/PaddleOCR-release-2.6/ppocr/modeling/necks/csp_pan.py", line 50, in forward
    x = self.bn(self.conv(x))
  File "/home/jc/.local/share/anaconda3/envs/Test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/jc/.local/share/anaconda3/envs/Test/lib/python3.8/site-packages/paddle/nn/layer/norm.py", line 1182, in forward
    sync_batch_norm_out, _, _, _, _, _ = _C_ops.sync_batch_norm_(
RuntimeError: (NotFound) The kernel `sync_batch_norm` is not registered.
  [Hint: Expected iter != kernels_.end(), but received iter == kernels_.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:113)

**Comment by an1018** [comment]
配置文件中的use_gpu改为False再试试

**Comment by QianquanChina** [comment]
@an1018  您好，我尝试训练的时候就已经设置成False，能告知一下这个错误是怎么引起的吗？我没办法google到类似的问题。谢谢

**Comment by Mrfuhang** [comment]
> 配置文件中的use_gpu改为False再试试

不行

**Comment by archeradvanture** [comment]
一年了都没人来解答一下
