### ISSUE TITLE
关于训练检测模型的配置文件中训练集路径的问题

### ISSUE THREAD

**Issue by GrooveWJH** [PaddlePaddle/PaddleOCR#9217]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：MacOS 13.0 Ventura
- 版本号/Version：Paddle：  PaddleOCR：V3  
- 问题相关组件/Related components：det_res18_db_v2.0.yml
- 运行指令/Command Code：`python tools/train.py -c configs/det/det_res18_db_v2.0.yml`
- 完整报错/Complete Error Message：
```
[2023/02/24 21:16:06] ppocr INFO: Architecture : 
[2023/02/24 21:16:06] ppocr INFO:     Backbone : 
[2023/02/24 21:16:06] ppocr INFO:         layers : 18
[2023/02/24 21:16:06] ppocr INFO:         name : ResNet_vd
···[省略]
[2023/02/24 21:16:06] ppocr INFO:         shuffle : True
[2023/02/24 21:16:06] ppocr INFO: profiler_options : None
[2023/02/24 21:16:06] ppocr INFO: train with paddle 2.4.2 and device Place(cpu)
[2023/02/24 21:16:06] ppocr INFO: Initialize indexs of datasets:['./train_data/train/Label.txt']
[2023/02/24 21:16:06] ppocr INFO: Initialize indexs of datasets:['./train_data/train/Label.txt', {'DecodeImage': {'img_mode': 'BGR', 'channel_first': False}}, {'DetLabelEncode': None}, {'DetResizeForTest': None}, {'NormalizeImage': {'scale': '1./255.', 'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225], 'order': 'hwc'}}, {'ToCHWImage': None}, {'KeepKeys': {'keep_keys': ['image', 'shape', 'polys', 'ignore_tags']}}]
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 63, in main
    valid_dataloader = build_dataloader(config, 'Eval', device, logger)
  File "/Users/groovewjh/[隐私]/PaddleOCR/ppocr/data/__init__.py", line 66, in build_dataloader
    dataset = eval(module_name)(config, mode, logger, seed)
  File "/Users/groovewjh/[隐私]/PaddleOCR/ppocr/data/simple_dataset.py", line 47, in __init__
    self.data_lines = self.get_image_info_list(label_file_list, ratio_list)
  File "/Users/groovewjh/[隐私]/PaddleOCR/ppocr/data/simple_dataset.py", line 61, in get_image_info_list
    with open(file, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not dict
```

以下为PaddleOCR/train_data的主要文件路径树

└── train_data
    ├── test
    │   ├── Label.txt
    │   ├── d7_1.png
    │   └── d7_2.png
    └── train
        ├── Label.txt
        ├── d1_1.png
        ├── d1_2.png
        ├──...
        └── d6_2.png

以下为det_res18_db_v2.0.yml中的核心信息
```
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/train/Label.txt
```

```
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/train/Label.txt

```

**Comment by an1018** [comment]
根据这个文档，查看一下自己的Label.txt：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/dataset/ocr_datasets.md#11-paddleocr-%E6%96%87%E5%AD%97%E6%A3%80%E6%B5%8B%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F

**Comment by taojing7** [comment]
大佬解决了吗，我也是这个问题

**Comment by GrooveWJH** [comment]
并未解决，我使用paddleocr的label工具进行标注的，生成的label文本严格遵循文档要求的规则。
按照报错信息，应该是文件读写权限之类的问题。但我无法进一步定位。

**Comment by taojing7** [comment]
> 并未解决，我使用paddleocr的label工具进行标注的，生成的label文本严格遵循文档要求的规则。 按照报错信息，应该是文件读写权限之类的问题。但我无法进一步定位。

我的已解决，拉取了dygraph里最新的训练脚本并重新修改配置文件即可

**Comment by GrooveWJH** [comment]
> > 并未解决，我使用paddleocr的label工具进行标注的，生成的label文本严格遵循文档要求的规则。 按照报错信息，应该是文件读写权限之类的问题。但我无法进一步定位。
> 
> 我的已解决，拉取了dygraph里最新的训练脚本并重新修改配置文件即可

好的谢谢，我将会参考你的做法。
