### ISSUE TITLE
npu训练使用amp， 报错：Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end()

### ISSUE THREAD

**Issue by old-steel** [PaddlePaddle/PaddleOCR#9252]
- 系统环境/System Environment：npu_x86 
- 版本号/Version：Paddle：  PaddleOCR  amp
- 运行指令/Command Code：python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained \
     Global.use_amp=True Global.scale_loss=1024.0 Global.use_dynamic_loss_scaling=True
- 完整报错/Complete Error Message：
- Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 183, in main
    amp_level, amp_custom_black_list)
  File "/myfile/zbl/new_ocr/paddleocr_nzd/tools/program.py", line 285, in train
    scaler.minimize(optimizer, scaled_avg_loss)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/amp/grad_scaler.py", line 736, in minimize
    return super().minimize(optimizer, *args, **kwargs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/amp/grad_scaler.py", line 227, in minimize
    self._unscale(optimizer)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/amp/grad_scaler.py", line 369, in _unscale
    self._temp_found_inf_fp16,
RuntimeError: (NotFound) There are no kernels which are registered in the check_finite_and_unscale operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:421)
  [operator < check_finite_and_unscale > error]

**Comment by ronny1996** [comment]
请问下使用的PaddleCustomDevice commit是多少？最新的应该解决这个问题了
