### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'pageCount'. Did you mean: 'page_count'?

### ISSUE THREAD

**Issue by zgpnuaa** [PaddlePaddle/PaddleOCR#9261]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment： Windows11
- 版本号/Version：Paddle：  2.4.2  PaddleOCR： 2.6.1.3  问题相关组件/Related components： utility.py
- 运行指令/Command Code：   `paddleocr --image_dir=走向繁荣的战略选择.pdf --type=structure --recovery=true`
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\VScodeProjects\paddlePDF\PaddleOCR\venv\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "D:\VScodeProjects\paddlePDF\PaddleOCR\venv\lib\site-packages\paddleocr\paddleocr.py", line 683, in main
    img, flag_gif, flag_pdf = check_and_read(img_path)
  File "D:\VScodeProjects\paddlePDF\PaddleOCR\venv\lib\site-packages\paddleocr\ppocr\utils\utility.py", line 96, in check_and_read
    for pg in range(0, pdf.pageCount):
AttributeError: 'Document' object has no attribute 'pageCount'. Did you mean: 'page_count'?
```

**Comment by an1018** [comment]
python版本太高了，可以换个python版本试试

**Comment by zgpnuaa** [comment]
> python版本太高了，可以换个python版本试试

不是python版本高，是PyMuPDF版本高了，1.20版本后这个特性换掉了。PyMuPDF<=1.19就解决了。@an1018

**Comment by zgpnuaa** [comment]
> > python版本太高了，可以换个python版本试试
> 
> 不是python版本高，是PyMuPDF版本高了，1.20版本后这个特性换掉了。PyMuPDF<=1.19就解决了。@an1018 

大于1.20版本的PyMuPDF中pageCount换成了page_count。

**Comment by creo13** [comment]
Have this same error as well, running Python 3.10.6

**Comment by zgpnuaa** [comment]
> Have this same error as well, running Python 3.10.6

pip install PyMuPDF<=1.19
@creo13

**Comment by creo13** [comment]
Works, thanks
