### ISSUE TITLE
KIE training after update of PaddleNLP

### ISSUE THREAD

**Issue by botastark** [PaddlePaddle/PaddleOCR#9263]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：AWS sagemaker
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：KIE (SER) training 
- 
paddlepaddle-gpu==2.3.2
paddleocr==2.6.0.1
opencv-python==4.5.5.64
paddlenlp==2.5.0

- 运行指令/Command Code：!python tools/train.py -c ser_vi_layoutxlm_xfund_zh-play.yml
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/root/botshelf-paddleocr-experimentations/PaddleOCR/tools/program.py", line 310, in train
    eval_class(preds, batch)
  File "/root/botshelf-paddleocr-experimentations/PaddleOCR/ppocr/metrics/vqa_token_ser_metric.py", line 31, in __call__
    preds, labels = preds
ValueError: too many values to unpack (expected 2)

The same settings used to work a month ago. I suspect that it is caused by new version of PaddleNLP 2.5.1 (used to work fine with PaddleNLP=2.5.0). Installing PaddleNLP 2.5.0 back and deleting .paddlenlp  not helping now. Any suggestion?

**Comment by botastark** [comment]
checked preds:
it returns a list with 13 dict: backbone_out and hidden_states_0-11 with tensors shape=[2, 561, 768]

but expected a tuple of preds, labels

**Comment by botastark** [comment]
I am not sure if it is a proper solution, leaving in case if anyone else encounters the same.
uninstall paddlenlp version and installed needed version
restarted kernel 
The trick was: in configuration file I run with  "pretrained: False" and then "True" again.
(Idk why the last step solved the issue)

**Comment by whisky-12** [comment]
Global:
  use_gpu: True
  epoch_num: &epoch_num 50
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: ./output/re_vi_layoutxlm_fapiao_udml
  save_epoch_step: 2000
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [ 0, 19 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: ppstructure/docs/vqa/input/zh_val_21.jpg
  save_res_path: ./output/re/re_vi_layoutxlm_xfund_zh_udml/res

Architecture:
  model_type: &model_type "kie"
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: &algorithm "LayoutXLM"
      Transform:
      Backbone:
        name: LayoutXLMForRe
        pretrained: True
        mode: vi
        checkpoints:
    Student:
      pretrained:
      freeze_params: false
      return_all_feats: true
      model_type: *model_type
      algorithm: *algorithm
      Transform:
      Backbone:
        name: LayoutXLMForRe
        pretrained: True
        mode: vi
        checkpoints:

Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationLossFromOutput:
      weight: 1.0
      model_name_list: ["Student", "Teacher"]
      key: loss
      reduction: mean
  - DistillationVQADistanceLoss:
      weight: 0.5
      mode: "l2"
      model_name_pairs:
        - ["Student", "Teacher"]
      key: hidden_states_5
      name: "loss_5"
  - DistillationVQADistanceLoss:
      weight: 0.5
      mode: "l2"
      model_name_pairs:
        - ["Student", "Teacher"]
      key: hidden_states_8
      name: "loss_8"


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr:
    learning_rate: 0.00005
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: DistillationRePostProcess
  model_name: ["Student", "Teacher"]
  key: null


Metric:
  name: DistillationMetric
  base_metric_name: VQAReTokenMetric
  main_indicator: hmean
  key: "Student"

Train:
  dataset:
    name: SimpleDataSet
    data_dir: train_data/zzsfp/imgs
    label_file_list: 
      - train_data/zzsfp/train.json
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: &class_path train_data/zzsfp/class_list.txt
          use_textline_bbox_info: &use_textline_bbox_info True
          # [None, "tb-yx"]
          order_method: &order_method "tb-yx"
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox','attention_mask', 'token_type_ids', 'image', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 4
    num_workers: 4
    collate_fn: ListCollator

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: train_data/zzsfp/imgs
    label_file_list: 
      - train_data/zzsfp/val.json
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: *use_textline_bbox_info
          order_method: *order_method
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8
    num_workers: 8
    collate_fn: ListCollator




2023/09/21 17:14:49] ppocr INFO: train dataloader has 8 iters
[2023/09/21 17:14:49] ppocr INFO: valid dataloader has 1 iters
[2023/09/21 17:14:49] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 202, in main
    amp_dtype)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 303, in train
    preds = model(batch)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/architectures/distillation_model.py", line 59, in forward
    result_dict[model_name] = self.model_list[idx](x, data)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 237, in forward
    relations=relations)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1412, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1303, in forward
    batch_size, max_length, _ = paddle.shape(entities)
ValueError: too many values to unpack (expected 3)
