### ISSUE TITLE
关于min_subgraph_size的设置问题。

### ISSUE THREAD

**Issue by smallsmallwood** [PaddlePaddle/PaddleOCR#9267]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux20.04
- 版本号/Version：Paddle： 2.4.1.post112,  tensorrt:8.5.1.7, cuda:11.8
- 运行指令/Command Code：如果min_subgraph_size 由4改为3就会报如下错误
```
class RankCrossEncoderPredict:
    def __init__(self):
        self.shape_file = "shape_range_info.pbtxt"
        self.config = paddle_infer.Config(kc.static_model_structure, kc.static_model_params)
        self.precision_map = {
                "fp16": paddle_infer.PrecisionType.Half,
                "fp32": paddle_infer.PrecisionType.Float32,
                "int8": paddle_infer.PrecisionType.Int8,
            }
        self.config_set()
        self.predictor = paddle_infer.create_predictor(self.config)
        self.input_handles = [self.predictor.get_input_handle(name) for name in self.predictor.get_input_names()]
        self.output_handle = self.predictor.get_output_handle(self.predictor.get_output_names()[0])
        print(f"input_handles: {self.input_handles}")
        print(f"output_handle: {self.output_handle}")

    def config_set(self):
        # self.config.disable_glog_info()

        self.config.enable_memory_optim()
        self.config.enable_use_gpu(1000, 0)
        # self.config.collect_shape_range_info(self.shape_file)
        print("Use GPU is: {}".format(self.config.use_gpu()))  # True
        print("Init mem size is: {}".format(self.config.memory_pool_init_size_mb()))  # 100
        print("Init mem frac is: {}".format(self.config.fraction_of_gpu_memory_for_pool()))  # 0.003
        print("GPU device id is: {}".format(self.config.gpu_device_id()))  # 0
        self.config.enable_tensorrt_engine(max_batch_size=30, min_subgraph_size=3, precision_mode=self.precision_map[kc.precision_config])
        # self.config.enable_tuned_tensorrt_dynamic_shape(self.shape_file, True)
        # min_input_shape = {"input_ids": [1, 1], "segment_ids": [1, 256]}
        # max_input_shape = {"input_ids": [30, 256], "segment_ids": [30, 256]}
        # opt_input_shape = {"input_ids": [30, 256], "segment_ids": [30, 256]}
        #
        # self.config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape, opt_input_shape)
        self.config.switch_use_feed_fetch_ops(False)

    def infer(self, data_loader):
        result = []
        for batch in data_loader:
            input_ids, token_type_ids = batch
            input_ids, token_type_ids = input_ids.numpy(), token_type_ids.numpy()
            # 设置输入，此处以随机输入为例，用户可自行输入真实数据
            self.input_handles[0].copy_from_cpu(input_ids)
            self.input_handles[1].copy_from_cpu(token_type_ids)
            # 运行预测引擎
            self.predictor.run()
            # 获得输出handle
            sim_score = self.output_handle.copy_to_cpu()
            result.append(sim_score)
        return result
```
- 完整报错/Complete Error Message：
```
/usr/local/lib/python3.8/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-03-02 11:40:19,802] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.modeling.ErnieModel'> to load 'rocketqa-zh-base-query-encoder'.
[2023-03-02 11:40:19,803] [    INFO] - Model config ErnieConfig {
  "attention_probs_dropout_prob": 0.1,
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 2048,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 4,
  "use_task_id": true,
  "vocab_size": 40000
}

W0302 11:40:29.094058 4082974 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.8
W0302 11:40:29.107303 4082974 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
[2023-03-02 11:40:30,160] [ WARNING] - Some weights of the model checkpoint at rocketqa-zh-base-query-encoder were not used when initializing ErnieModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing ErnieModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ErnieModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2023-03-02 11:40:30,161] [    INFO] - All the weights of ErnieModel were initialized from the model checkpoint at rocketqa-zh-base-query-encoder.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ErnieModel for predictions without further training.
Loaded parameters from ../models/in_batch_checkpoint/model_191000/model_state.pdparams
[2023-03-02 11:40:30,548] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'rocketqa-zh-base-query-encoder'.
[2023-03-02 11:40:30,548] [    INFO] - Already cached /root/.paddlenlp/models/rocketqa-zh-base-query-encoder/ernie_3.0_base_zh_vocab.txt
[2023-03-02 11:40:30,563] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/rocketqa-zh-base-query-encoder/tokenizer_config.json
[2023-03-02 11:40:30,563] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/rocketqa-zh-base-query-encoder/special_tokens_map.json
Use GPU is: True
Init mem size is: 1000
Init mem frac is: 0.10753844678401947
GPU device id is: 0
W0302 11:40:30.698228 4082974 analysis_predictor.cc:1391] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0302 11:40:30.714800 4082974 analysis_predictor.cc:1099] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_fill_constant_op_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [delete_weight_dequant_linear_op_pass]
--- Running IR pass [delete_quant_dequant_linear_op_pass]
--- Running IR pass [identity_scale_op_clean_pass]
--- Running IR pass [add_support_int8_pass]
I0302 11:40:31.123723 4082974 fuse_pass_base.cc:59] ---  detected 425 subgraphs
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [trt_embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [delete_c_identity_op_pass]
--- Running IR pass [trt_multihead_matmul_fuse_pass_v2]
I0302 11:40:31.357304 4082974 fuse_pass_base.cc:59] ---  detected 12 subgraphs
--- Running IR pass [trt_multihead_matmul_fuse_pass_v3]
--- Running IR pass [vit_attention_fuse_pass]
--- Running IR pass [trt_skip_layernorm_fuse_pass]
I0302 11:40:31.400095 4082974 fuse_pass_base.cc:59] ---  detected 25 subgraphs
--- Running IR pass [preln_skip_layernorm_fuse_pass]
--- Running IR pass [preln_residual_bias_fuse_pass]
--- Running IR pass [layernorm_shift_partition_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [trt_squeeze2_matmul_fuse_pass]
--- Running IR pass [trt_flatten2_matmul_fuse_pass]
--- Running IR pass [trt_map_matmul_v2_to_mul_pass]
I0302 11:40:31.408931 4082974 fuse_pass_base.cc:59] ---  detected 38 subgraphs
--- Running IR pass [trt_map_matmul_v2_to_matmul_pass]
--- Running IR pass [trt_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0302 11:40:31.420440 4082974 fuse_pass_base.cc:59] ---  detected 38 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [remove_padding_recover_padding_pass]
--- Running IR pass [delete_remove_padding_recover_padding_pass]
--- Running IR pass [dense_fc_to_sparse_pass]
--- Running IR pass [dense_multihead_matmul_to_sparse_pass]
--- Running IR pass [constant_folding_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0302 11:40:31.445873 4082974 tensorrt_subgraph_pass.cc:244] ---  detect a sub-graph with 4 nodes
W0302 11:40:31.446130 4082974 tensorrt_subgraph_pass.cc:501] The Paddle Inference library is compiled with 8 version TensorRT, but the runtime TensorRT you are using is 8.5 version. This might cause serious compatibility issues. We strongly recommend using the same TRT version at runtime.
I0302 11:40:31.447271 4082974 tensorrt_subgraph_pass.cc:560] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
W0302 11:40:40.680794 4082974 helper.h:110] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
W0302 11:40:40.680825 4082974 helper.h:110] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
I0302 11:41:26.408326 4082974 engine.cc:684] Inspector needs TensorRT version 8.2 and after.
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0302 11:41:26.414340 4082974 ir_params_sync_among_devices_pass.cc:89] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0302 11:41:26.672955 4082974 memory_optimize_pass.cc:219] Cluster name : token_type_ids  size: 30720
I0302 11:41:26.672973 4082974 memory_optimize_pass.cc:219] Cluster name : cumsum_0.tmp_0  size: 8
I0302 11:41:26.672977 4082974 memory_optimize_pass.cc:219] Cluster name : unsqueeze2_0.tmp_0  size: 30720
I0302 11:41:26.672981 4082974 memory_optimize_pass.cc:219] Cluster name : layer_norm_33.tmp_2  size: 23592960
I0302 11:41:26.672982 4082974 memory_optimize_pass.cc:219] Cluster name : linear_120.tmp_1  size: 94371840
I0302 11:41:26.672986 4082974 memory_optimize_pass.cc:219] Cluster name : layer_norm_30.tmp_2  size: 23592960
I0302 11:41:26.672992 4082974 memory_optimize_pass.cc:219] Cluster name : gelu_8.tmp_0  size: 94371840
--- Running analysis [ir_graph_to_program_pass]
I0302 11:41:26.687917 4082974 analysis_predictor.cc:1314] ======= optimize end =======
I0302 11:41:26.689465 4082974 naive_executor.cc:110] ---  skip [feed], feed -> token_type_ids
I0302 11:41:26.689476 4082974 naive_executor.cc:110] ---  skip [feed], feed -> input_ids
I0302 11:41:26.689888 4082974 naive_executor.cc:110] ---  skip [linear_147.tmp_1], fetch -> fetch
input_handles: [<paddle.fluid.libpaddle.PaddleInferTensor object at 0x7faf1e6f4570>, <paddle.fluid.libpaddle.PaddleInferTensor object at 0x7faf1e6f44b0>]
output_handle: <paddle.fluid.libpaddle.PaddleInferTensor object at 0x7faf237d8ab0>
[2023-03-02 11:41:26,690] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'rocketqa-base-cross-encoder'.
[2023-03-02 11:41:26,690] [    INFO] - Already cached /root/.paddlenlp/models/rocketqa-base-cross-encoder/ernie_3.0_base_zh_vocab.txt
[2023-03-02 11:41:26,704] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/rocketqa-base-cross-encoder/tokenizer_config.json
[2023-03-02 11:41:26,704] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/rocketqa-base-cross-encoder/special_tokens_map.json
[2023-03-02 11:41:26,735] [    INFO] - start build index..........
[2023-03-02 11:41:50,216] [    INFO] - Total index number:27863
recall_data_process_cost_time：9.131431579589844e-05
recall_infer_cost_time：0.047154903411865234
rank_data_process_cost_time：0.0001239776611328125
Traceback (most recent call last):
  File "/root/workspace/algo-topic-rcmd/inference/recall_rank_inference_opt_infer.py", line 190, in <module>
    pipline()
  File "/root/workspace/algo-topic-rcmd/inference/recall_rank_inference_opt_infer.py", line 176, in pipline
    rank_result = km.infer(rank_data_loader)
  File "/root/workspace/algo-topic-rcmd/inference/recall_rank_inference_opt_infer.py", line 101, in infer
    self.predictor.run()
ValueError: (InvalidArgument) Input shapes are inconsistent with the model. Expect [256, 768] in model description, but got [58, 768] in runtime. TRT 5 or lower version does not support dynamic input shapes. Please check and modify your input shapes.
  [Hint: Expected model_input_shape == runtime_input_shape == true, but received model_input_shape == runtime_input_shape:0 != true:1.] (at /paddle/paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:90)


Process finished with exit code 1


```

**Comment by WenmuZhou** [comment]
这个辛苦在paddle下提问看看
