### ISSUE TITLE
Docker化部署服务出错

### ISSUE THREAD

**Issue by nckf** [PaddlePaddle/PaddleOCR#929]
[原文](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/deploy/docker/hubserving/README_cn.md#3%E5%90%AF%E5%8A%A8docker%E5%AE%B9%E5%99%A8)
在阿里云新主机 Ubuntu 16.04 上
进行到 3.a 步骤时候抛出了异常

```
2020-10-14 02:42:25,218-INFO: not find model file path ./inference/ch_ppocr_mobile_v1.1_det_infer//model
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 413, in execute
    self.start_serving()
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 360, in start_serving
    self.start_single_app_with_args()
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 275, in start_single_app_with_args
    self.preinstall_modules()
  File "/usr/local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 205, in preinstall_modules
    m = hub.Module(**init_args)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddlehub/module/module.py", line 174, in init_with_name
    raise RuntimeError(tips)
RuntimeError: Can't find module ocr_system, please check your spelling.
```

**Comment by LDOUBLEV** [comment]
模型路径不对吧，not find model file path ./inference/ch_ppocr_mobile_v1.1_det_infer//model

**Comment by nckf** [comment]
> 模型路径不对吧，not find model file path ./inference/ch_ppocr_mobile_v1.1_det_infer//model
确认了是 Dockerfile 下载的模型与仓库 params.py 中的路径不一致导致的
