### ISSUE TITLE
评估时发生import问题

### ISSUE THREAD

**Issue by PajamASO** [PaddlePaddle/PaddleOCR#9292]
- 系统环境/System Environment：BML codelab
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：python tools/eval.py     -c configs/det/ch_PP-OCRv2/ch_PP-OCRv2_det_cml.yml
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "tools/eval.py", line 26, in <module>
    from ppocr.data import build_dataloader
  File "/home/work/mnt/project/qD1uLHQm/test/PaddleOCR/ppocr/data/__init__.py", line 24, in <module>
    import paddle
  File "/home/work/mnt/project/qD1uLHQm/.env/lib/python3.7/site-packages/paddle/__init__.py", line 36, in <module>
    import paddle.distributed
  File "/home/work/mnt/project/qD1uLHQm/.env/lib/python3.7/site-packages/paddle/distributed/__init__.py", line 15, in <module>
    from . import spawn
  File "/home/work/mnt/project/qD1uLHQm/.env/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 24, in <module>
    from paddle.distributed.utils import _print_arguments, _prepare_trainer_env, get_host_name_ip
ImportError: cannot import name '_print_arguments' from 'paddle.distributed.utils' (/home/work/mnt/project/qD1uLHQm/.env/lib/python3.7/site-packages/paddle/distributed/utils/__init__.py)

尝试更新下paddlepaddle和paddleocr的包，发现paddlepaddle2.4.2和onnx1.13.1间存在冲突：
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
paddlepaddle 2.4.2 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.3 which is incompatible.
请问是这方面的原因吗？初次接触ppocr很多方面都不懂，还请指教

**Comment by an1018** [comment]
卸载了，重新安装环境吧，如果是gpu，需要安装paddlepaddle-gpu

**Comment by DazzlingGalaxy** [comment]
@an1018 ，我也遇到了这个问题，详细的描述在https://github.com/PaddlePaddle/PaddleOCR/issues/8940#issuecomment-1454449494，请问怎么解决？
另外这个问题是不是能和 #8940 关联起来？

**Comment by PajamASO** [comment]
后来重装一遍，这个问题过了

**Comment by DazzlingGalaxy** [comment]
> 

我用的python 3.8，conda remove -n 环境名 --all，删掉虚拟环境后再安装，还是不行，我的pip源是阿里源，我装的GPU版paddlepaddle。
是我python版本或者pip源的问题吗？你装的CPU还是GPU版的paddlepaddle？

**Comment by DazzlingGalaxy** [comment]
补充，解决方法在 #9426
