### ISSUE TITLE
PaddleOCR下cpp_infer文本识别SRN模型失败，en_PP-OCRv3_rec_infer识别正常。

### ISSUE THREAD

**Issue by Cyuliang** [PaddlePaddle/PaddleOCR#9307]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：./PadConOcr --det_model_dir=/home/det/inference/ --rec_model_dir=/home/rec/inference/ --cls_model_dir=/home/cls/inference/  --image_dir=/home/img/0.jpg --det=false --rec=true --cls=false --enable_mkldnn=true  --rec_char_dict_path=/home/rec_keys_v1.txt
- 完整报错/Complete Error Message：I0305 23:01:57.274271 25309 analysis_predictor.cc:1187] MKLDNN is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [mkldnn_placement_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
I0305 23:01:57.475667 25309 fuse_pass_base.cc:59] ---  detected 10 subgraphs
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
I0305 23:01:57.492375 25309 fuse_pass_base.cc:59] ---  detected 55 subgraphs
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
W0305 23:01:57.496428 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.496711 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.497099 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.497375 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.497649 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.497920 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.498209 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.498484 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.498754 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.499022 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
W0305 23:01:57.499053 25309 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape. 
I0305 23:01:57.499060 25309 fuse_pass_base.cc:59] ---  detected 21 subgraphs
--- Running IR pass [matmul_scale_fuse_pass]
I0305 23:01:57.504303 25309 fuse_pass_base.cc:59] ---  detected 10 subgraphs
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0305 23:01:57.537892 25309 fuse_pass_base.cc:59] ---  detected 24 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0305 23:01:57.629053 25309 fuse_pass_base.cc:59] ---  detected 53 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
I0305 23:01:57.659332 25309 fuse_pass_base.cc:59] ---  detected 2 subgraphs
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [constant_folding_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running IR pass [squeeze2_transpose2_onednn_fuse_pass]
--- fused 0 squeeze2 with transpose2
--- Running IR pass [depthwise_conv_mkldnn_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_affine_channel_mkldnn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_bias_mkldnn_fuse_pass]
I0305 23:01:57.815107 25309 fuse_pass_base.cc:59] ---  detected 5 subgraphs
--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]
--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]
---    Fused 4 projection conv (as y) + elementwise_add patterns
---    Fused 12 conv (as x) + elementwise_add patterns
---    Fused 0 conv (as y) + elementwise_add patterns
I0305 23:01:57.898775 25309 fuse_pass_base.cc:59] ---  detected 16 subgraphs
--- Running IR pass [conv_activation_mkldnn_fuse_pass]
I0305 23:01:57.918200 25309 fuse_pass_base.cc:59] ---  detected 51 subgraphs
---    fused 51 conv with relu activation
--- Running IR pass [scale_matmul_fuse_pass]
I0305 23:01:57.927659 25309 fuse_pass_base.cc:59] ---  detected 10 subgraphs
---    fused 10 scale with matmul
--- Running IR pass [reshape_transpose_matmul_mkldnn_fuse_pass]
I0305 23:01:57.953786 25309 fuse_pass_base.cc:59] ---  detected 30 subgraphs
---    fused 30 reshape + transpose + matmul with reshape's xshape with transpose's xshape
--- Running IR pass [matmul_transpose_reshape_mkldnn_fuse_pass]
--- Running IR pass [matmul_elementwise_add_mkldnn_fuse_pass]
I0305 23:01:57.977439 25309 fuse_pass_base.cc:59] ---  detected 8 subgraphs
---    fused 8 matmul (as x) with elementwise_add
---    fused 0 matmul (as y) with elementwise_add
I0305 23:01:57.980648 25309 fuse_pass_base.cc:59] ---  detected 10 subgraphs
---    fused 10 matmul_v2 (as x) with elementwise_add
---    fused 0 matmul_v2 (as y) with elementwise_add
--- Running IR pass [matmul_activation_mkldnn_fuse_pass]
---    fused 0 matmul with abs activation
---    fused 0 matmul with clip activation
---    fused 0 matmul with gelu activation
---    fused 0 matmul with hard_sigmoid activation
---    fused 0 matmul with hard_swish activation
---    fused 0 matmul with leaky_relu activation
---    fused 0 matmul with mish activation
---    fused 0 matmul with relu activation
---    fused 0 matmul with relu6 activation
---    fused 0 matmul with sigmoid activation
---    fused 0 matmul with sqrt activation
---    fused 0 matmul with swish activation
---    fused 0 matmul with tanh activation
---    fused 0 matmul_v2 with abs activation
---    fused 0 matmul_v2 with clip activation
---    fused 0 matmul_v2 with gelu activation
---    fused 0 matmul_v2 with hard_sigmoid activation
---    fused 0 matmul_v2 with hard_swish activation
---    fused 0 matmul_v2 with leaky_relu activation
---    fused 0 matmul_v2 with mish activation
---    fused 0 matmul_v2 with relu activation
---    fused 0 matmul_v2 with relu6 activation
---    fused 0 matmul_v2 with sigmoid activation
---    fused 0 matmul_v2 with sqrt activation
---    fused 0 matmul_v2 with swish activation
---    fused 0 matmul_v2 with tanh activation
--- Running IR pass [fc_elementwise_add_mkldnn_fuse_pass]
---    Fused 0 fc (as x) + elementwise_add patterns
---    Fused 0 fc (as y) + elementwise_add patterns
--- Running IR pass [batch_norm_act_fuse_pass]
---    fused 0 batch norm with relu activation
--- Running IR pass [softplus_activation_mkldnn_fuse_pass]
---    fused 0 softplus with abs activation
---    fused 0 softplus with clip activation
---    fused 0 softplus with gelu activation
---    fused 0 softplus with hard_sigmoid activation
---    fused 0 softplus with hard_swish activation
---    fused 0 softplus with leaky_relu activation
---    fused 0 softplus with mish activation
---    fused 0 softplus with relu activation
---    fused 0 softplus with relu6 activation
---    fused 0 softplus with sigmoid activation
---    fused 0 softplus with sqrt activation
---    fused 0 softplus with swish activation
---    fused 0 softplus with tanh activation
--- Running IR pass [shuffle_channel_mkldnn_detect_pass]
--- Running IR pass [elt_act_mkldnn_fuse_pass]
---    fused 0 elementwise_add with abs activation
---    fused 0 elementwise_add with clip activation
---    fused 0 elementwise_add with gelu activation
---    fused 0 elementwise_add with hard_sigmoid activation
---    fused 0 elementwise_add with hard_swish activation
---    fused 0 elementwise_add with leaky_relu activation
---    fused 0 elementwise_add with mish activation
---    fused 0 elementwise_add with relu activation
---    fused 0 elementwise_add with relu6 activation
---    fused 0 elementwise_add with sigmoid activation
---    fused 0 elementwise_add with sqrt activation
---    fused 0 elementwise_add with swish activation
I0305 23:01:58.012250 25309 fuse_pass_base.cc:59] ---  detected 1 subgraphs
---    fused 1 elementwise_add with tanh activation
---    fused 0 elementwise_sub with abs activation
---    fused 0 elementwise_sub with clip activation
---    fused 0 elementwise_sub with gelu activation
---    fused 0 elementwise_sub with hard_sigmoid activation
---    fused 0 elementwise_sub with hard_swish activation
---    fused 0 elementwise_sub with leaky_relu activation
---    fused 0 elementwise_sub with mish activation
---    fused 0 elementwise_sub with relu activation
---    fused 0 elementwise_sub with relu6 activation
---    fused 0 elementwise_sub with sigmoid activation
---    fused 0 elementwise_sub with sqrt activation
---    fused 0 elementwise_sub with swish activation
---    fused 0 elementwise_sub with tanh activation
---    fused 0 elementwise_mul with abs activation
---    fused 0 elementwise_mul with clip activation
---    fused 0 elementwise_mul with gelu activation
---    fused 0 elementwise_mul with hard_sigmoid activation
---    fused 0 elementwise_mul with hard_swish activation
---    fused 0 elementwise_mul with leaky_relu activation
---    fused 0 elementwise_mul with mish activation
---    fused 0 elementwise_mul with relu activation
---    fused 0 elementwise_mul with relu6 activation
---    fused 0 elementwise_mul with sigmoid activation
---    fused 0 elementwise_mul with sqrt activation
---    fused 0 elementwise_mul with swish activation
---    fused 0 elementwise_mul with tanh activation
--- Running IR pass [operator_scale_onednn_fuse_pass]
I0305 23:01:58.025215 25309 fuse_pass_base.cc:59] ---  detected 20 subgraphs
---    fused 20 fc with scale
--- Running IR pass [operator_unsqueeze2_onednn_fuse_pass]
--- Running IR pass [operator_reshape2_onednn_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0305 23:01:58.178503 25309 analysis_predictor.cc:1318] ======= optimize end =======
I0305 23:01:58.192869 25309 naive_executor.cc:110] ---  skip [feed], feed -> data_3
I0305 23:01:58.192884 25309 naive_executor.cc:110] ---  skip [feed], feed -> data_2
I0305 23:01:58.192888 25309 naive_executor.cc:110] ---  skip [feed], feed -> data_1
I0305 23:01:58.192890 25309 naive_executor.cc:110] ---  skip [feed], feed -> data_0
I0305 23:01:58.192893 25309 naive_executor.cc:110] ---  skip [feed], feed -> x
I0305 23:01:58.196471 25309 naive_executor.cc:110] ---  skip [top_k_v2_0.tmp_1], fetch -> fetch
I0305 23:01:58.196480 25309 naive_executor.cc:110] ---  skip [reshape2_46.tmp_0], fetch -> fetch
I0305 23:01:58.196482 25309 naive_executor.cc:110] ---  skip [softmax_12.tmp_0], fetch -> fetch
I0305 23:01:58.196485 25309 naive_executor.cc:110] ---  skip [matmul_v2_4.tmp_0], fetch -> fetch
I0305 23:01:58.196488 25309 naive_executor.cc:110] ---  skip [linear_79.tmp_1], fetch -> fetch
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "/home/cc/Documents/PaddleOCR-release-2.6/tools/export_model.py", line 255, in <module>
      main()
    File "/home/cc/Documents/PaddleOCR-release-2.6/tools/export_model.py", line 250, in main
      export_single_model(
    File "/home/cc/Documents/PaddleOCR-release-2.6/tools/export_model.py", line 171, in export_single_model
      paddle.jit.save(model, save_path)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpbfnacgzp.py", line 27, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.use_backbone, true_fn_1,
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/cc/Documents/PaddleOCR-release-2.6/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/home/cc/Documents/PaddleOCR-release-2.6/ppocr/modeling/backbones/rec_resnet_fpn.py", line 149, in __call__
      x = self.conv(x)
    File "/home/cc/Documents/PaddleOCR-release-2.6/ppocr/modeling/backbones/rec_resnet_fpn.py", line 211, in __call__
      x = self.conv(x)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 666, in forward
      out = F.conv._conv_nd(
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/nn/functional/conv.py", line 168, in _conv_nd
      helper.append_op(
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/home/cc/Public/anaconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const
6   paddle::operators::ConvOp::ComputeOutputShape(paddle::framework::InferShapeContext*) const
7   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
8   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [1, 3, 48, 410]; the filter's channels is 1, the filter's shape is [64, 1, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:131)
  [operator < conv2d > error]
已放弃 (核心已转储)

**Comment by Cyuliang** [comment]
SRN模型在python下正常。
