### ISSUE TITLE
dbnet using Paddle2onnx  convert to onnx, but  output results of dbnet.onnx using onnxruntime are all zeros and  onnx.load report error.

### ISSUE THREAD

**Issue by seriphdog** [PaddlePaddle/PaddleOCR#9314]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubuntu 18.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
PaddlePaddle 2.4.1, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
PaddleOCR
git clone https://github.com/PaddlePaddle/PaddleOCR 
version on 2023/3/6

- 运行指令/Command Code：
- wget  https://paddleocr.bj.bcebos.com/dygraph_v2.0/en/det_mv3_db_v2.0_train.tar
tar xvf det_mv3_db_v2.0_train.tar

python3 tools/export_model.py \
-c configs/det/det_mv3_db.yml \
-o Global.pretrained_model=../dbnet_external/det_mv3_db_v2.0_train/best_accuracy  \
Global.save_inference_dir=../dbnet_external/inference/det_db

paddle2onnx --model_dir ../dbnet_external/inference/det_db \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ../dbnet_external/inference/model_dbnet_try.onnx \
--opset_version 13 \
--input_shape_dict="{'x':[2,3,736,1280]}" \
--enable_onnx_checker True

- 完整报错/Complete Error Message：
1)import onnxruntime
import numpy as np
indata1 = np.load("./input_dbnet.npz")['x']
assert indata1.shape==(2,3,736,1280),indata1.shape
session = onnxruntime.InferenceSession('./inference/model_dbnet_try.onnx')
results = session.run(["sigmoid_0.tmp_0"], {"x": indata1})
assert results[0].shape==(2,1,736,1280)
output_data = results[0]
outputs_dbnet = dict()
outputs_dbnet['sigmoid_0.tmp_0'] = output_data
assert 0,results

Then, all results are zero, here input_dbnet.npz is of rand_float32 dtype in range [0,1].
The results should be some small floating numbers,as I believe.

2)import onnx
import paddle
program = paddle.load("./inference/det_db/inference.pdmodel")
load_layer_state_dict = paddle.load("./inference/det_db/inference.pdiparams")
program.set_state_dict(load_layer_state_dict)

model = onnx.load('model_dbnet_v11.onnx')
output =[node.name for node in model.graph.output]

input_all = [node.name for node in model.graph.input]
input_initializer =  [node.name for node in model.graph.initializer]
net_feed_input = list(set(input_all)  - set(input_initializer))

print('Inputs: ', net_feed_input)
print('Outputs: ', output)

Then error:

ceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 1044, in load
    load_result = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '\x0a'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 1076, in load
    tensor, _ = _load_selected_rows(path)
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 610, in _load_selected_rows
    _seek = core.load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:167104522 != 0U:0.] (at /paddle/paddle/phi/core/serialization.cc:163)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 1080, in load
    tensor, _ = _load_lod_tensor(path)
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 567, in _load_lod_tensor
    _seek = paddle.fluid.core.load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 167104522 found).
  [Hint: Expected version == 0U, but received version:167104522 != 0U:0.] (at /paddle/paddle/phi/core/serialization.cc:106)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 1092, in load
    program_desc_str
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 6280, in parse_from_string
    p._sync_with_cpp()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 6503, in _sync_with_cpp
    block._sync_with_cpp()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 4180, in _sync_with_cpp
    op = Operator(self, op_desc)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2810, in __init__
    "`type` to initialized an Operator can not be None."
ValueError: `type` to initialized an Operator can not be None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onnx_process.py", line 3, in <module>
    program = paddle.load("./inference/det_db/inference.pdmodel")
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 1098, in load
    path
ValueError: `paddle.load` can not parse the file:./inference/det_db/inference.pdmodel.

**Comment by seriphdog** [comment]
Quite Strange, 
for question 1)
I ran another docker and reinstall my numpy, then  assert 0,np.sum(np.abs(results)) is not 0 and became expected distribution.
so only question 2) need to be solved, thank you anyway
