### ISSUE TITLE
ser训练。 epoch: [2/5]的时候会报错

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9345]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
 ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
python3 tools/train.py -c configs/onezbill/yhzyhd_v1/ser_vi_layoutxlm.yml
```
- 完整报错/Complete Error Message：
```
W0308 14:25:33.177753 91690 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0308 14:25:33.179906 91690 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[2023/03/08 14:25:34] ppocr INFO: train dataloader has 11 iters
[2023/03/08 14:25:34] ppocr INFO: valid dataloader has 2 iters
[2023/03/08 14:25:34] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
[2023/03/08 14:25:36] ppocr INFO: epoch: [1/5], global_step: 10, lr: 0.000010, loss: 3.582051, avg_reader_cost: 0.01632 s, avg_batch_cost: 0.14326 s, avg_samples: 1.0, ips: 6.98053 samples/s, eta: 0:00:06
[2023/03/08 14:25:36] ppocr INFO: epoch: [1/5], global_step: 11, lr: 0.000013, loss: 3.508493, avg_reader_cost: 0.00002 s, avg_batch_cost: 0.00576 s, avg_samples: 0.1, ips: 17.34610 samples/s, eta: 0:00:05
[2023/03/08 14:25:49] ppocr INFO: save model in /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/model/ser/output/ser_vi_layoutxlm/latest
[2023/03/08 14:25:51] ppocr INFO: cur metric, precision: 0.14181818181818182, recall: 0.20855614973262032, hmean: 0.16883116883116883, fps: 44.60313013282134
[2023/03/08 14:26:17] ppocr INFO: save best model is to /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/model/ser/output/ser_vi_layoutxlm/best_accuracy
[2023/03/08 14:26:17] ppocr INFO: best metric, hmean: 0.16883116883116883, precision: 0.14181818181818182, recall: 0.20855614973262032, fps: 44.60313013282134, best_epoch: 2
[2023/03/08 14:26:17] ppocr INFO: epoch: [2/5], global_step: 20, lr: 0.000033, loss: 2.584854, avg_reader_cost: 1.26041 s, avg_batch_cost: 1.31442 s, avg_samples: 0.9, ips: 0.68471 samples/s, eta: 0:00:25
[2023/03/08 14:26:17] ppocr INFO: epoch: [2/5], global_step: 22, lr: 0.000038, loss: 2.350556, avg_reader_cost: 0.00002 s, avg_batch_cost: 0.01183 s, avg_samples: 0.2, ips: 16.91115 samples/s, eta: 0:00:22
[2023/03/08 14:26:58] ppocr INFO: save model in /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/model/ser/output/ser_vi_layoutxlm/latest
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 623, in _get_data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
        data = self._data_queue.get(timeout=self._timeout)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 108, in get
self._reader.read_next_list()[0])
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:175)

    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop

```

- 配置文件
```
Global:
  use_gpu: true
  epoch_num: 5
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/model/ser/output/ser_vi_layoutxlm/
  save_epoch_step: 2000
  eval_batch_step:
  - 0
  - 19
  cal_metric_during_train: false
  save_inference_dir: null
  use_visualdl: false
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_42.jpg
  save_res_path: null
  kie_rec_model_dir: null
  kie_det_model_dir: null
Architecture:
  model_type: kie
  algorithm: LayoutXLM
  Transform: null
  Backbone:
    name: LayoutXLMForSer
    pretrained: true
    checkpoints: null
    mode: vi
    num_classes: 39
Loss:
  name: VQASerTokenLayoutLMLoss
  num_classes: 39
  key: backbone_out
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Linear
    learning_rate: 5.0e-05
    epochs: 5
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.0
PostProcess:
  name: VQASerTokenLayoutLMPostProcess
  class_path: /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/class_list.txt
Metric:
  name: VQASerTokenMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/zh_train/image
    label_file_list:
    - /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/zh_train/train.json
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: false
        algorithm: LayoutXLM
        class_path: /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/class_list.txt
        use_textline_bbox_info: true
        order_method: tb-yx
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQASerTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - labels
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/zh_val/image
    label_file_list:
    - /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/zh_val/val.json
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: false
        algorithm: LayoutXLM
        class_path: /home/DiskA/zncsPython/picture_ocr/yhzyhd_v1/train_data/class_list.txt
        use_textline_bbox_info: true
        order_method: tb-yx
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQASerTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - labels
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 4

```

**Comment by rexzhengzhihong** [comment]
参考了https://github.com/PaddlePaddle/PaddleOCR/issues/9177  这个。说是train.json文件中是：img_path + \t + gt
但我好像就是

**Comment by rexzhengzhihong** [comment]
@tink2123 麻烦帮忙看看

**Comment by rexzhengzhihong** [comment]
奇怪，啥也没改。在pycharm中debugger就会有问题。在shell中就不会？？？？

**Comment by tink2123** [comment]
不要使用debug模式，直接在shell里执行吧

**Comment by rexzhengzhihong** [comment]
可以。就是不知道为啥
