### ISSUE TITLE
使用Pyinstaller将PPOCRLabel.py打包成exe文件时遇到No module named 'framework_pb2'的报错。官方是不是有一个打包工具的，这个工具文档在哪里？

### ISSUE THREAD

**Issue by Mr-Diaolvyu** [PaddlePaddle/PaddleOCR#9355]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10
- 运行指令/Command Code：
`Pyinstaller -F -w -i=D:\MyWorkSpace\PythonProject\PaddleOCR-Label\PPOCRLabel\images\icons\app.png D:\MyWorkSpace\PythonProject\PaddleOCR-Label\PPOCRLabel\PPOCRLabel.py --distpath=C:\Users\HUAWEI\Desktop\out`
- 完整报错/Complete Error Message：
```During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PaddleOCR-Label\PPOCRLabel\PPOCRLabel.py", line 43, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\paddleocr.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\__init__.py", line 62, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\spawn.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\utils\launch_utils.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\fleet\__init__.py", line 31, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\fleet\fleet.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\fluid\ir.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

**Comment by Mr-Diaolvyu** [comment]
> 使用文档在：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel
> 
> 升级一下paddle版本试试

谢谢大佬，有打包工具的文档吗？这个标签工具做了一些二开，升级会有些麻烦。

**Comment by Mr-Diaolvyu** [comment]
> 使用文档在：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/PPOCRLabel
> 
> 升级一下paddle版本试试

您好，我已经升级为paddlepaddle-2.4.1的版本了，还是有如上问题

**Comment by Camphora7** [comment]
打包命令写-D，缺什么包就直接从conda环境文件夹下site-package复制到生成的文件夹

**Comment by kerneltravel** [comment]
> 打包命令写-D，缺什么包就直接从conda环境文件夹下site-package复制到生成的文件夹

pyinstaller 打包时要加参数：
```
--collect-all  paddleocr
```

**Comment by qq819931129** [comment]
--collect-all  paddleocr
