### ISSUE TITLE
使用PPOCRLabel表格识别报错，PPOCRLabel==2.1.3、paddlepaddle==2.4.2、paddleocr==2.6.1.3

### ISSUE THREAD

**Issue by xurning** [PaddlePaddle/PaddleOCR#9360]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：windows10
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "C:\out\Release\resources\PPOCRLabel.py", line 2210, in TableRecognition
    to_excel('', excel_path) # create an empty excel
  File "C:\out\Release\Python\Lib\site-packages\paddleocr\ppstructure\table\predict_table.py", line 145, in to_excel
    tablepyxl.document_to_xl(html_table, excel_path)
  File "C:\out\Release\Python\Lib\site-packages\paddleocr\ppstructure\table\tablepyxl\tablepyxl.py", line 101, in document_to_xl
    wb = document_to_workbook(doc, base_url=base_url)
  File "C:\out\Release\Python\Lib\site-packages\paddleocr\ppstructure\table\tablepyxl\tablepyxl.py", line 87, in document_to_workbook
    inline_styles_doc = Premailer(doc, base_url=base_url, remove_classes=False).transform()
  File "C:\out\Release\Python\Lib\site-packages\premailer\premailer.py", line 353, in transform
    tree = etree.fromstring(stripped, parser).getroottree()
AttributeError: 'NoneType' object has no attribute 'getroottree'

**Comment by WenmuZhou** [comment]
方便提供你的图片吗

**Comment by xurning** [comment]
可以邮箱发送吗？

**Comment by rexzhengzhihong** [comment]
![chpypkhxbgb_v2_01](https://github.com/PaddlePaddle/PaddleOCR/assets/32863094/b3442f1e-46e7-4586-8231-913a133bb73e)
我也是同样的报错
