### ISSUE TITLE
用静态shape（input_shape_dict="{'x':[1,3,640,640]}" ）输入方式paddle2onnx模型后，进行det_mv3_db的det_model_1_3_640_640.onnx模型推理出现问题，求解答

### ISSUE THREAD

**Issue by likecv** [PaddlePaddle/PaddleOCR#9361]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
padddle-cpu_py37

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
git clone  -b release/2.4 https://github.com/PaddlePaddle/PaddleOCR.git

- 运行指令/Command Code：
python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=./inference/det_onnx/det_model_1_3_640_640.onnx  --rec_model_dir=./inference/rec_onnx/det_model_1_3_640_640.onnx  --cls_model_dir=./inference/cls_onnx/det_model_1_3_640_640.onnx  --image_dir=./deploy/lite/imgs/lite_demo.png

- 完整报错/Complete Error Message：
 (paddle) root@74a1c807b06a:/home/lk/paddle_code/PaddleOCR# python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --det_model_dir=./inference/det_onnx/det_model_1_3_640_640.onnx  --rec_model_dir=./inference/rec_onnx/det_model_1_3_640_640.onnx  --cls_model_dir=./inference/cls_onnx/det_model_1_3_640_640.onnx  --image_dir=./deploy/lite/imgs/lite_demo.png
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 244, in <module>
    main(args)
  File "tools/infer/predict_system.py", line 148, in main
    text_sys = TextSystem(args)
  File "tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/lk/paddle_code/PaddleOCR/tools/infer/predict_det.py", line 113, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by likecv** [comment]
麻烦看看这个问题，谢谢

**Comment by Arnoldnuo** [comment]
> 试一下2.6分支呢

试了2.6分支，报一样的错

**Comment by wanggoudanscd** [comment]
请问解决了吗？我也遇到了这个问题

**Comment by younger-diao** [comment]
安装paddle2onnx = 0.9.0即可

**Comment by zhangzhaoyin** [comment]
paddle2onnx = 0.9.0 , opset_version 10 才能用
