### ISSUE TITLE
训练DRRG模型时数据解析出现问题

### ISSUE THREAD

**Issue by xiehuanyi** [PaddlePaddle/PaddleOCR#9392]
```
[2023/03/10 20:41:42] ppocr ERROR: When parsing line /home/aistudio/data/ocr_dataset/6371842732512259/699.jpg   [{"points": [[120, 603], [422, 574], [419, 621], [118, 650]], "transcription": "HEAD"}, {"points": [[1045, 396], [1046, 397], [682, 456], [682, 460]], "transcription": "#####"}]
, error happened with msg: Traceback (most recent call last):
  File "/home/aistudio/PaddleOCR/ppocr/data/simple_dataset.py", line 137, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/fce_aug.py", line 86, in __call__
    results = self.random_crop_flip(results)
  File "/home/aistudio/PaddleOCR/ppocr/data/imaug/fce_aug.py", line 136, in random_crop_flip
    ppiou, _ = poly_intersection(ppi, pp, buffer=0)
  File "/home/aistudio/PaddleOCR/ppocr/utils/poly_nms.py", line 53, in poly_intersection
    poly_inter = poly_det & poly_gt
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/shapely/geometry/base.py", line 189, in __and__
    return self.intersection(other)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/shapely/geometry/base.py", line 582, in intersection
    return shapely.intersection(self, other, grid_size=grid_size)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/shapely/set_operations.py", line 133, in intersection
    return lib.intersection(a, b, **kwargs)
shapely.errors.GEOSException: TopologyException: Input geom 0 is invalid: Self-intersection at 1107.6523099442734 471.91723796592032

[2023/03/10 20:44:43] ppocr INFO: epoch: [1/120], global_step: 500, lr: 0.002800, loss: 0.689215, loss_text: 0.172800, loss_center: 0.258875, loss_height: 0.207202, loss_sin: 0.001279, loss_cos: 0.010549, loss_gcn: 0.026229, avg_reader_cost: 0.05851 s, avg_batch_cost: 0.64687 s, avg_samples: 4.0, ips: 6.18362 samples/s, eta: 76 days, 22:48:42
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 183, in main
    amp_level, amp_custom_black_list)
  File "/home/aistudio/PaddleOCR/tools/program.py", line 295, in train
    loss = loss_class(preds, batch)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleOCR/ppocr/losses/det_drrg_loss.py", line 163, in forward
    gt['gt_mask'][0])
  File "/home/aistudio/PaddleOCR/ppocr/losses/det_drrg_loss.py", line 42, in balance_bce_loss
    assert paddle.all(pred >= 0) and paddle.all(pred <= 1)
AssertionError
```

**Comment by StuPidMRE** [comment]
@an1018 老师， 请问为什么会出现这个问题？我刚接触ocr，对这块不是很了解
