### ISSUE TITLE
版面复原报：'Document' object has no attribute 'pageCount'

### ISSUE THREAD

**Issue by bigdataer01** [PaddlePaddle/PaddleOCR#9401]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：mac os 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
paddleocr --image_dir=./test.pdf --type=structure --recovery=true --use_pdf2docx_api=true
- 完整报错/Complete Error Message：
paddleocr --image_dir=./test.pdf --type=structure --recovery=true --use_pdf2docx_api=true
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2023/03/12 14:21:08] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir=None, cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir='./test.pdf', image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path='/usr/local/lib/python3.7/dist-packages/paddleocr/ppocr/utils/dict/layout_dict/layout_cdla_dict.txt', layout_model_dir='/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer', layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/usr/local/lib/python3.7/dist-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=True, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path='/usr/local/lib/python3.7/dist-packages/paddleocr/ppocr/utils/dict/table_structure_dict_ch.txt', table_max_len=488, table_model_dir='/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer', total_process_num=1, type='structure', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=True, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2023/03/12 14:21:10] ppocr INFO: **********./test.pdf**********
Traceback (most recent call last):
  File "/usr/local/bin/paddleocr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/paddleocr.py", line 683, in main
    img, flag_gif, flag_pdf = check_and_read(img_path)
  File "/usr/local/lib/python3.7/dist-packages/paddleocr/ppocr/utils/utility.py", line 96, in check_and_read
    for pg in range(0, pdf.pageCount):
AttributeError: 'Document' object has no attribute 'pageCount'

**Comment by chchan585** [comment]
Someone also report that in gitee: https://gitee.com/paddlepaddle/PaddleOCR/issues/I63WKH
Seems it is a package versioning issue, maybe can try to rollback pymupdf to 1.18.14 and see if it presists?

**Comment by chchan585** [comment]
Not sure about the guide haha I am not the official
I also failed to rolllback pymupdf, I thought it was my environment's issue but then it seems not the case

BTW I saw a guy postes a workaround here: https://github.com/PaddlePaddle/PaddleOCR/pull/9340
> 找到一个可以不修改paddleocr源码的方式：
> `import fitz 并在ocr之前调用 fitz.restore_aliases()`
> 好让fitz恢复旧的别名映射

It works in my case, you may want to take a try

**Comment by azfarbkhr** [comment]
In my case, I had to make 2 changes in the "\Lib\site-packages\paddleocr\ppocr\utils\utility.py" file of the library to make it work. 
I think it is not correct a practice but it worked for me. 

The changes were to replace the pdf.pageCount by pdf.page_count 
and replacing pdf.getPixmap by pdf.get_pixmap
