### ISSUE TITLE
PP-OCR模型量化导出模型时报错

### ISSUE THREAD

**Issue by ChihoJack** [PaddlePaddle/PaddleOCR#9437]
- 系统环境/System Environment：Windows 10 家庭版 64位
- 版本号/Version：Paddle：paddlepaddle-gpu 2.4.2.post112  PaddleOCR：2.6.1.3 问题相关组件/Related components：模型量化
- 运行指令/Command Code：
python deploy/slim/quantization/export_model.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.checkpoints=output/quant_model_distill/best_accuracy Global.save_inferenc
e_dir=./output/quant_inference_model
- 完整报错/Complete Error Message：
- [03-15 09:09:52 MainThread @logger.py:242] Argv: deploy/slim/quantization/export_model.py -c configs/det/ch_PP-OCRv3/ch_PP-OCRv3_det_cml.yml -o Global.checkpoints=output/quant_model_distill/best_accuracy Global.save_inference_dir=./out
put/quant_inference_model
[03-15 09:09:52 MainThread @utils.py:73] paddlepaddle version: 2.4.2.
2023-03-15 09:09:53,041-WARNING: post-quant-hpo is not support in system other than linux
[2023/03/15 09:09:53] ppocr INFO: Architecture :
[2023/03/15 09:09:53] ppocr INFO:     Models :
[2023/03/15 09:09:53] ppocr INFO:         Student :
[2023/03/15 09:09:53] ppocr INFO:             Backbone :
[2023/03/15 09:09:53] ppocr INFO:                 disable_se : True
[2023/03/15 09:09:53] ppocr INFO:                 model_name : small
[2023/03/15 09:09:53] ppocr INFO:                 name : MobileNetV3
[2023/03/15 09:09:53] ppocr INFO:                 scale : 0.5
[2023/03/15 09:09:53] ppocr INFO:             Head :
[2023/03/15 09:09:53] ppocr INFO:                 k : 50
[2023/03/15 09:09:53] ppocr INFO:                 name : DBHead
[2023/03/15 09:09:53] ppocr INFO:             Neck :
[2023/03/15 09:09:53] ppocr INFO:                 name : RSEFPN
[2023/03/15 09:09:53] ppocr INFO:                 out_channels : 96
[2023/03/15 09:09:53] ppocr INFO:                 shortcut : True
[2023/03/15 09:09:53] ppocr INFO:             Transform : None
[2023/03/15 09:09:53] ppocr INFO:             algorithm : DB
[2023/03/15 09:09:53] ppocr INFO:             model_type : det
[2023/03/15 09:09:53] ppocr INFO:             pretrained : None
[2023/03/15 09:09:53] ppocr INFO:         Student2 :
[2023/03/15 09:09:53] ppocr INFO:             Backbone :
[2023/03/15 09:09:53] ppocr INFO:                 disable_se : True
[2023/03/15 09:09:53] ppocr INFO:                 model_name : small
[2023/03/15 09:09:53] ppocr INFO:                 name : MobileNetV3
[2023/03/15 09:09:53] ppocr INFO:                 scale : 0.5
[2023/03/15 09:09:53] ppocr INFO:             Head :
[2023/03/15 09:09:53] ppocr INFO:                 k : 50
[2023/03/15 09:09:53] ppocr INFO:                 name : DBHead
[2023/03/15 09:09:53] ppocr INFO:             Neck :
[2023/03/15 09:09:53] ppocr INFO:                 name : RSEFPN
[2023/03/15 09:09:53] ppocr INFO:                 out_channels : 96
[2023/03/15 09:09:53] ppocr INFO:                 shortcut : True
[2023/03/15 09:09:53] ppocr INFO:             Transform : None
[2023/03/15 09:09:53] ppocr INFO:             algorithm : DB
[2023/03/15 09:09:53] ppocr INFO:             model_type : det
[2023/03/15 09:09:53] ppocr INFO:             pretrained : None
[2023/03/15 09:09:53] ppocr INFO:         Teacher :
[2023/03/15 09:09:53] ppocr INFO:             Backbone :
[2023/03/15 09:09:53] ppocr INFO:                 in_channels : 3
[2023/03/15 09:09:53] ppocr INFO:                 layers : 50
[2023/03/15 09:09:53] ppocr INFO:                 name : ResNet_vd
[2023/03/15 09:09:53] ppocr INFO:             Head :
[2023/03/15 09:09:53] ppocr INFO:                 k : 50
[2023/03/15 09:09:53] ppocr INFO:                 kernel_list : [7, 2, 2]
[2023/03/15 09:09:53] ppocr INFO:                 name : DBHead
[2023/03/15 09:09:53] ppocr INFO:             Neck :
[2023/03/15 09:09:53] ppocr INFO:                 name : LKPAN
[2023/03/15 09:09:53] ppocr INFO:                 out_channels : 256
[2023/03/15 09:09:53] ppocr INFO:             algorithm : DB
[2023/03/15 09:09:53] ppocr INFO:             freeze_params : True
[2023/03/15 09:09:53] ppocr INFO:             model_type : det
[2023/03/15 09:09:53] ppocr INFO:             return_all_feats : False
[2023/03/15 09:09:53] ppocr INFO:     algorithm : Distillation
[2023/03/15 09:09:53] ppocr INFO:     model_type : det
[2023/03/15 09:09:53] ppocr INFO:     name : DistillationModel
[2023/03/15 09:09:53] ppocr INFO: Eval :
[2023/03/15 09:09:53] ppocr INFO:     dataset :
[2023/03/15 09:09:53] ppocr INFO:         data_dir : ./train_data/icdar2015/text_localization/
[2023/03/15 09:09:53] ppocr INFO:         label_file_list : ['./train_data/icdar2015/text_localization/test_icdar2015_label.txt']
[2023/03/15 09:09:53] ppocr INFO:         name : SimpleDataSet
[2023/03/15 09:09:53] ppocr INFO:         transforms :
[2023/03/15 09:09:53] ppocr INFO:             DecodeImage :
[2023/03/15 09:09:53] ppocr INFO:                 channel_first : False
[2023/03/15 09:09:53] ppocr INFO:                 img_mode : BGR
[2023/03/15 09:09:53] ppocr INFO:             DetLabelEncode : None
[2023/03/15 09:09:53] ppocr INFO:             DetResizeForTest : None
[2023/03/15 09:09:53] ppocr INFO:             NormalizeImage :
[2023/03/15 09:09:53] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2023/03/15 09:09:53] ppocr INFO:                 order : hwc
[2023/03/15 09:09:53] ppocr INFO:                 scale : 1./255.
[2023/03/15 09:09:53] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2023/03/15 09:09:53] ppocr INFO:             ToCHWImage : None
[2023/03/15 09:09:53] ppocr INFO:             KeepKeys :
[2023/03/15 09:09:53] ppocr INFO:                 keep_keys : ['image', 'shape', 'polys', 'ignore_tags']
[2023/03/15 09:09:53] ppocr INFO:     loader :
[2023/03/15 09:09:53] ppocr INFO:         batch_size_per_card : 1
[2023/03/15 09:09:53] ppocr INFO:         drop_last : False
[2023/03/15 09:09:53] ppocr INFO:         num_workers : 1
[2023/03/15 09:09:53] ppocr INFO:         shuffle : False
[2023/03/15 09:09:53] ppocr INFO: Global :
[2023/03/15 09:09:53] ppocr INFO:     cal_metric_during_train : False
[2023/03/15 09:09:53] ppocr INFO:     checkpoints : output/quant_model_distill/best_accuracy
[2023/03/15 09:09:53] ppocr INFO:     debug : False
[2023/03/15 09:09:53] ppocr INFO:     distributed : False
[2023/03/15 09:09:53] ppocr INFO:     epoch_num : 100
[2023/03/15 09:09:53] ppocr INFO:     eval_batch_step : [0, 400]
[2023/03/15 09:09:53] ppocr INFO:     infer_img : doc/imgs_en/img_10.jpg
[2023/03/15 09:09:53] ppocr INFO:     log_smooth_window : 20
[2023/03/15 09:09:53] ppocr INFO:     pretrained_model : None
[2023/03/15 09:09:53] ppocr INFO:     print_batch_step : 10
[2023/03/15 09:09:53] ppocr INFO:     save_epoch_step : 100
[2023/03/15 09:09:53] ppocr INFO:     save_inference_dir : ./output/quant_inference_model
[2023/03/15 09:09:53] ppocr INFO:     save_model_dir : ./output/ch_PP-OCR_v3_det/
[2023/03/15 09:09:53] ppocr INFO:     save_res_path : ./checkpoints/det_db/predicts_db.txt
[2023/03/15 09:09:53] ppocr INFO:     use_gpu : True
[2023/03/15 09:09:53] ppocr INFO:     use_visualdl : False
[2023/03/15 09:09:53] ppocr INFO: Loss :
[2023/03/15 09:09:53] ppocr INFO:     loss_config_list :
[2023/03/15 09:09:53] ppocr INFO:         DistillationDilaDBLoss :
[2023/03/15 09:09:53] ppocr INFO:             alpha : 5
[2023/03/15 09:09:53] ppocr INFO:             balance_loss : True
[2023/03/15 09:09:53] ppocr INFO:             beta : 10
[2023/03/15 09:09:53] ppocr INFO:             key : maps
[2023/03/15 09:09:53] ppocr INFO:             main_loss_type : DiceLoss
[2023/03/15 09:09:53] ppocr INFO:             model_name_pairs : [['Student', 'Teacher'], ['Student2', 'Teacher']]
[2023/03/15 09:09:53] ppocr INFO:             ohem_ratio : 3
[2023/03/15 09:09:53] ppocr INFO:             weight : 1.0
[2023/03/15 09:09:53] ppocr INFO:         DistillationDMLLoss :
[2023/03/15 09:09:53] ppocr INFO:             key : maps
[2023/03/15 09:09:53] ppocr INFO:             maps_name : thrink_maps
[2023/03/15 09:09:53] ppocr INFO:             model_name_pairs : ['Student', 'Student2']
[2023/03/15 09:09:53] ppocr INFO:             weight : 1.0
[2023/03/15 09:09:53] ppocr INFO:         DistillationDBLoss :
[2023/03/15 09:09:53] ppocr INFO:             alpha : 5
[2023/03/15 09:09:53] ppocr INFO:             balance_loss : True
[2023/03/15 09:09:53] ppocr INFO:             beta : 10
[2023/03/15 09:09:53] ppocr INFO:             main_loss_type : DiceLoss
[2023/03/15 09:09:53] ppocr INFO:             model_name_list : ['Student', 'Student2']
[2023/03/15 09:09:53] ppocr INFO:             ohem_ratio : 3
[2023/03/15 09:09:53] ppocr INFO:             weight : 1.0
[2023/03/15 09:09:53] ppocr INFO:     name : CombinedLoss
[2023/03/15 09:09:53] ppocr INFO: Metric :
[2023/03/15 09:09:53] ppocr INFO:     base_metric_name : DetMetric
[2023/03/15 09:09:53] ppocr INFO:     key : Student
[2023/03/15 09:09:53] ppocr INFO:     main_indicator : hmean
[2023/03/15 09:09:53] ppocr INFO:     name : DistillationMetric
[2023/03/15 09:09:53] ppocr INFO: Optimizer :
[2023/03/15 09:09:53] ppocr INFO:     beta1 : 0.9
[2023/03/15 09:09:53] ppocr INFO:     beta2 : 0.999
[2023/03/15 09:09:53] ppocr INFO:     lr :
[2023/03/15 09:09:53] ppocr INFO:         learning_rate : 0.001
[2023/03/15 09:09:53] ppocr INFO:         name : Cosine
[2023/03/15 09:09:53] ppocr INFO:         warmup_epoch : 2
[2023/03/15 09:09:53] ppocr INFO:     name : Adam
[2023/03/15 09:09:53] ppocr INFO:     regularizer :
[2023/03/15 09:09:53] ppocr INFO:         factor : 5e-05
[2023/03/15 09:09:53] ppocr INFO:         name : L2
[2023/03/15 09:09:53] ppocr INFO: PostProcess :
[2023/03/15 09:09:53] ppocr INFO:     box_thresh : 0.6
[2023/03/15 09:09:53] ppocr INFO:     key : head_out
[2023/03/15 09:09:53] ppocr INFO:     max_candidates : 1000
[2023/03/15 09:09:53] ppocr INFO:     model_name : ['Student']
[2023/03/15 09:09:53] ppocr INFO:     name : DistillationDBPostProcess
[2023/03/15 09:09:53] ppocr INFO:     thresh : 0.3
[2023/03/15 09:09:53] ppocr INFO:     unclip_ratio : 1.5
[2023/03/15 09:09:53] ppocr INFO: Train :
[2023/03/15 09:09:53] ppocr INFO:     dataset :
[2023/03/15 09:09:53] ppocr INFO:         data_dir : ./train_data/icdar2015/text_localization/
[2023/03/15 09:09:53] ppocr INFO:         label_file_list : ['./train_data/icdar2015/text_localization/train_icdar2015_label.txt']
[2023/03/15 09:09:53] ppocr INFO:         name : SimpleDataSet
[2023/03/15 09:09:53] ppocr INFO:         ratio_list : [1.0]
[2023/03/15 09:09:53] ppocr INFO:         transforms :
[2023/03/15 09:09:53] ppocr INFO:             DecodeImage :
[2023/03/15 09:09:53] ppocr INFO:                 channel_first : False
[2023/03/15 09:09:53] ppocr INFO:                 img_mode : BGR
[2023/03/15 09:09:53] ppocr INFO:             DetLabelEncode : None
[2023/03/15 09:09:53] ppocr INFO:             CopyPaste : None
[2023/03/15 09:09:53] ppocr INFO:             IaaAugment :
[2023/03/15 09:09:53] ppocr INFO:                 augmenter_args :
[2023/03/15 09:09:53] ppocr INFO:                     args :
[2023/03/15 09:09:53] ppocr INFO:                         p : 0.5
[2023/03/15 09:09:53] ppocr INFO:                     type : Fliplr
[2023/03/15 09:09:53] ppocr INFO:                     args :
[2023/03/15 09:09:53] ppocr INFO:                         rotate : [-10, 10]
[2023/03/15 09:09:53] ppocr INFO:                     type : Affine
[2023/03/15 09:09:53] ppocr INFO:                     args :
[2023/03/15 09:09:53] ppocr INFO:                         size : [0.5, 3]
[2023/03/15 09:09:53] ppocr INFO:                     type : Resize
[2023/03/15 09:09:53] ppocr INFO:             EastRandomCropData :
[2023/03/15 09:09:53] ppocr INFO:                 keep_ratio : True
[2023/03/15 09:09:53] ppocr INFO:                 max_tries : 50
[2023/03/15 09:09:53] ppocr INFO:                 size : [960, 960]
[2023/03/15 09:09:53] ppocr INFO:             MakeBorderMap :
[2023/03/15 09:09:53] ppocr INFO:                 shrink_ratio : 0.4
[2023/03/15 09:09:53] ppocr INFO:                 thresh_max : 0.7
[2023/03/15 09:09:53] ppocr INFO:                 thresh_min : 0.3
[2023/03/15 09:09:53] ppocr INFO:             MakeShrinkMap :
[2023/03/15 09:09:53] ppocr INFO:                 min_text_size : 8
[2023/03/15 09:09:53] ppocr INFO:                 shrink_ratio : 0.4
[2023/03/15 09:09:53] ppocr INFO:             NormalizeImage :
[2023/03/15 09:09:53] ppocr INFO:                 mean : [0.485, 0.456, 0.406]
[2023/03/15 09:09:53] ppocr INFO:                 order : hwc
[2023/03/15 09:09:53] ppocr INFO:                 scale : 1./255.
[2023/03/15 09:09:53] ppocr INFO:                 std : [0.229, 0.224, 0.225]
[2023/03/15 09:09:53] ppocr INFO:             ToCHWImage : None
[2023/03/15 09:09:53] ppocr INFO:             KeepKeys :
[2023/03/15 09:09:53] ppocr INFO:                 keep_keys : ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask']
[2023/03/15 09:09:53] ppocr INFO:     loader :
[2023/03/15 09:09:53] ppocr INFO:         batch_size_per_card : 2
[2023/03/15 09:09:53] ppocr INFO:         drop_last : False
[2023/03/15 09:09:53] ppocr INFO:         num_workers : 8
[2023/03/15 09:09:53] ppocr INFO:         shuffle : True
[2023/03/15 09:09:53] ppocr INFO: profiler_options : None
[2023/03/15 09:09:53] ppocr INFO: train with paddle 2.4.2 and device Place(gpu:0)
W0315 09:09:53.222466 14088 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0315 09:09:53.228482 14088 gpu_resources.cc:91] device: 0, cuDNN Version: 8.8.
[2023/03/15 09:09:57] ppocr INFO: resume from output/quant_model_distill/best_accuracy
[2023/03/15 09:09:57] ppocr INFO: Initialize indexs of datasets:['./train_data/icdar2015/text_localization/test_icdar2015_label.txt']
eval model::  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 20/21 [00:05<00:00,  3.76it/s]
[2023/03/15 09:10:02] ppocr INFO: metric eval ***************
[2023/03/15 09:10:02] ppocr INFO: precision:0.0
[2023/03/15 09:10:02] ppocr INFO: recall:0.0
[2023/03/15 09:10:02] ppocr INFO: hmean:0
[2023/03/15 09:10:02] ppocr INFO: fps:3.8443568125790994
Traceback (most recent call last):
  File "deploy/slim/quantization/export_model.py", line 176, in <module>
    main()
  File "deploy/slim/quantization/export_model.py", line 165, in main
    export_single_model(model.model_list[idx], archs[idx],
  File "E:\Yix\PaddleOCR-release-2.6\tools\export_model.py", line 187, in export_single_model
    quanter.save_quantized_model(model, save_path)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddleslim\dygraph\quant\qat.py", line 289, in save_quantized_model
    self.imperative_qat.save_quantized_model(
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\contrib\slim\quantization\imperative\qat.py", line 292, in save_quantized_model
    self._quantize_outputs.save_quantized_model(layer, path, input_spec,
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\contrib\slim\quantization\imperative\qat.py", line 500, in save_quantized_model
    paddle.jit.save(layer=model, path=path, input_spec=input_spec, **config)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\dygraph\jit.py", line 649, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\dygraph\base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\dygraph\jit.py", line 892, in save
    configs = _parse_save_configs(configs)
  File "D:\Program Files\anaconda3\envs\PaddleOCR-release-2.6\lib\site-packages\paddle\fluid\dygraph\jit.py", line 391, in _parse_save_configs
    raise ValueError(
ValueError: The additional config (onnx_format) of `paddle.jit.save` is not supported.

**Comment by LDOUBLEV** [comment]
你的paddleslim版本是多少
