### ISSUE TITLE
训练时报错：ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by star-rain-out** [PaddlePaddle/PaddleOCR#9471]
只有当我将batch_size_per_card设置为1的时候才能正常训练，设置成其他数值都会报ValueError: all input arrays must have the same shape这个错

Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddle38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\anaconda3\envs\paddle38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda3\envs\paddle38\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "D:\anaconda3\envs\paddle38\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 138, in fetch
    data = self.collate_fn(data)
  File "D:\anaconda3\envs\paddle38\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "D:\anaconda3\envs\paddle38\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "D:\anaconda3\envs\paddle38\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 180, in stack
  File "D:\anaconda3\envs\paddle38\lib\site-packages\numpy\core\shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

搜过类似的问题，始终找不到方法，求指教

**Comment by LDOUBLEV** [comment]
报错提示batch size>1的时候，维度不一致，
batch = np.stack(batch, axis=0)
检查下stack前，batch的维度为什么不一样

**Comment by wangmengmeng99** [comment]
don't worry, you just set batch_size_per_card is 1 in the yaml

**Comment by lipeng1109** [comment]
> don't worry, you just set batch_size_per_card is 1 in the yaml

您好，请问你是指将eval阶段的batch_size_per_card设置为1吗？这种设置验证过程会不会很慢？对模型性能有什么影响吗
