### ISSUE TITLE
It that possible to add ace loss and focal loss while training a distillation recognition model?

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleOCR#9476]
I wanna add ace/focal/center loss while training a distillation recognition model, but I found https://github.com/PaddlePaddle/PaddleOCR/blob/2be9fe763e4ebb55d59cc192eee437b0e09207ce/ppocr/losses/rec_multi_loss.py#L41-L58

the code excludes them.

**Comment by LDOUBLEV** [comment]
Yes. It can do that.

According to our previous experimental conclusions in our training dataset, the acc of adding focal loss during distillation is slightly lower than that without adding focal loss.

**Comment by nissansz** [comment]
导出的center loss文件train_center.pkl怎么使用？加入yml文件报错了。

#Loss:
#  name: CTCLoss
Loss:
  name: CombinedLoss
  loss_config_list:
  - CTCLoss:
      use_focal_loss: false
      weight: 1.0
  - CenterLoss:
      weight: 0.05
      num_classes: 63466
      feat_dim: 512
      center_file_path: C:/F/pycharm2020.2/PaddleOCR-release-2.5/train_center.pkl
  # you can also try to add ace loss on your own dataset
  - ACELoss:
      weight: 0.1

 报错如下

 Traceback (most recent call last):
  File "./tools/train.py", line 191, in <module>
    main(config, device, logger, vdl_writer)
  File "./tools/train.py", line 164, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\tools\program.py", line 268, in train
    loss = loss_class(preds, batch)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\combined_loss.py", line 55, in forward
    loss = loss_func(input, batch, **kargs)
  File "C:\F\pycharm2020.2\PaddleOCR-release-2.5\ppocr\losses\center_loss.py", line 50, in __call__
    assert isinstance(predicts, (list, tuple))
AssertionError


![image](https://github.com/PaddlePaddle/PaddleOCR/assets/41010669/3907dc9b-dced-4c3e-822f-db19722f6c46)
