### ISSUE TITLE
paddle_inference.dll: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by yangwenliang123** [PaddlePaddle/PaddleOCR#9528]
我尝试使用Java加载paddle_inference.dll文件，出现了%1 不是有效的 Win32 应用程序Erroe。我的Oracle JDK和Windows都是64位以下是代码和错误信息:
public static void main(String[] args) throws IOException {
    System.load("C:\\Users\\admin\\Desktop\\demo-win\\demo-win\\src\\main\\resources\\paddle_inference.dll");
}

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\admin\Desktop\demo-win\demo-win\src\main\resources\paddle_inference.dll: %1 不是有效的 Win32 应用程序。
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at io.github.greycode.DemoApp.main(DemoApp.java:24)

**Comment by liveever** [comment]
我这边也遇到类似的问题 。
这个可能是2.3.2 版本paddle_inference编译的问题， cpu_avx_mkl 2.2.2 没有这个问题， cpu_avx_mkl 2.3.2 有这个问题.

**Comment by xuxh6** [comment]
> 



> 我这边也遇到类似的问题 。 这个可能是2.3.2 版本paddle_inference编译的问题， cpu_avx_mkl 2.2.2 没有这个问题， cpu_avx_mkl 2.3.2 有这个问题.

有编译好的paddle_inference.dll文件分享一下吗？

**Comment by xuxh6** [comment]
> 我这边也遇到类似的问题 。 这个可能是2.3.2 版本paddle_inference编译的问题， cpu_avx_mkl 2.2.2 没有这个问题， cpu_avx_mkl 2.3.2 有这个问题.

有编译好的paddle_inference.dll文件分享一下吗？
