### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by hktalent** [PaddlePaddle/PaddleOCR#9540]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
conda create --name paddle_env -y python=3.8 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
```
$ pip list
Package               Version
--------------------- -----------
aiofiles              23.1.0
aiohttp               3.8.4
aiosignal             1.3.1
altair                4.2.2
anyio                 3.6.2
appnope               0.1.3
astor                 0.8.1
asttokens             2.2.1
async-timeout         4.0.2
attrdict              2.0.1
attrs                 22.2.0
Babel                 2.12.1
backcall              0.2.0
bce-python-sdk        0.8.79
beautifulsoup4        4.12.0
cachetools            5.3.0
certifi               2022.12.7
charset-normalizer    3.1.0
click                 8.1.3
colorama              0.4.6
colorlog              6.7.0
comm                  0.1.3
contourpy             1.0.7
cssselect             1.2.0
cssutils              2.6.0
cycler                0.11.0
Cython                0.29.33
datasets              2.10.1
debugpy               1.6.6
decorator             5.1.1
dill                  0.3.4
docarray              0.21.0
docker                6.0.1
easydict              1.10
ecdsa                 0.18.0
entrypoints           0.4
et-xmlfile            1.1.0
executing             1.2.0
fastapi               0.95.0
ffmpy                 0.3.0
filelock              3.10.0
fire                  0.5.0
Flask                 2.2.3
Flask-Babel           2.0.0
fonttools             4.39.2
frozenlist            1.3.3
fsspec                2023.3.0
future                0.18.3
gradio                3.22.1
gunicorn              20.1.0
h11                   0.14.0
httpcore              0.16.3
httpx                 0.23.3
huggingface-hub       0.13.2
idna                  3.4
imageio               2.26.1
imgaug                0.4.0
importlib-metadata    6.1.0
importlib-resources   5.12.0
ipykernel             6.22.0
ipython               8.11.0
ipywidgets            8.0.5
itsdangerous          2.1.2
jedi                  0.18.2
jieba                 0.42.1
jina-hubble-sdk       0.34.1
Jinja2                3.1.2
joblib                1.2.0
jsonschema            4.17.3
jupyter_client        8.1.0
jupyter_core          5.3.0
jupyterlab-widgets    3.0.6
kiwisolver            1.4.4
lazy_loader           0.2
linkify-it-py         2.0.0
lmdb                  1.4.0
lxml                  4.9.2
markdown-it-py        2.2.0
MarkupSafe            2.1.2
matplotlib            3.7.1
matplotlib-inline     0.1.6
mdit-py-plugins       0.3.3
mdurl                 0.1.1
multidict             6.0.4
multiprocess          0.70.12.2
nest-asyncio          1.5.6
networkx              3.0
numpy                 1.24.2
opencv-contrib-python 4.6.0.66
opencv-python         4.6.0.66
openpyxl              3.1.2
opt-einsum            3.3.0
orjson                3.8.7
packaging             23.0
paddle-bfloat         0.1.7
paddle-lpips          0.1.2.0
paddle2onnx           1.0.5
paddlefsl             1.1.0
paddlehub             2.3.1
paddlenlp             2.5.2
paddleocr             2.6.1.3
paddlepaddle          2.4.2
pandas                1.5.3
parso                 0.8.3
pathspec              0.11.1
pdf2docx              0.5.6
pexpect               4.8.0
pickleshare           0.7.5
Pillow                9.4.0
pip                   23.0.1
pkgutil_resolve_name  1.3.10
platformdirs          3.1.1
premailer             3.10.0
prompt-toolkit        3.0.38
protobuf              3.20.0
psutil                5.9.4
ptyprocess            0.7.0
pure-eval             0.2.2
pyarrow               11.0.0
pyasn1                0.4.8
pyclipper             1.3.0.post4
pycryptodome          3.17
pydantic              1.10.6
pydub                 0.25.1
Pygments              2.14.0
PyMuPDF               1.20.2
pyparsing             3.0.9
pyrsistent            0.19.3
python-dateutil       2.8.2
python-docx           0.8.11
python-jose           3.3.0
python-multipart      0.0.6
pytz                  2022.7.1
PyWavelets            1.4.1
PyYAML                6.0
pyzmq                 25.0.1
rapidfuzz             2.13.7
rarfile               4.0
requests              2.28.2
responses             0.18.0
rfc3986               1.5.0
rich                  13.3.2
rsa                   4.9
scikit-image          0.20.0
scikit-learn          1.2.2
scipy                 1.9.1
sentencepiece         0.1.96
seqeval               1.2.2
setuptools            65.6.3
shapely               2.0.1
six                   1.16.0
sniffio               1.3.0
soupsieve             2.4
stack-data            0.6.2
starlette             0.26.1
termcolor             2.2.0
threadpoolctl         3.1.0
tifffile              2023.3.21
toolz                 0.12.0
tornado               6.2
tqdm                  4.65.0
traitlets             5.9.0
typer                 0.7.0
typing_extensions     4.5.0
uc-micro-py           1.0.1
urllib3               1.26.15
uvicorn               0.21.1
visualdl              2.4.2
wcwidth               0.2.6
websocket-client      1.5.1
websockets            10.4
Werkzeug              2.2.3
wheel                 0.38.4
widgetsnbextension    4.0.6
xxhash                3.2.0
yarl                  1.8.2
zipp                  3.15.0
```
- 运行指令/Command Code：
```
import matplotlib.pyplot as plt 
import matplotlib.image as mpimg 
import paddlehub as hub
import cv2

# ocr = hub.Module(name="chinese_text_detection_db_mobile")
# 待预测图片
test_img_path = ["xxx.jpg"]

# 展示其中广告信息图片
ocr = hub.Module(name="chinese_ocr_db_crnn_mobile", enable_mkldnn=False)       # mkldnn加速仅在CPU下有效
for x in test_img_path:
    result = ocr.recognize_text(images=[cv2.imread(x)])
    print(result)
```
- 完整报错/Complete Error Message：
```
$ python testId.py 
/Users/51pwn/anaconda3/envs/paddle_env/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "testId.py", line 27, in <module>
    result = ocr.recognize_text(images=[cv2.imread(x)])
  File "/Users/51pwn/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "/Users/51pwn/.paddlehub/modules/chinese_ocr_db_crnn_mobile/module.py", line 265, in recognize_text
    'text_box_position': boxes[index].astype(np.int).tolist()
  File "/Users/51pwn/anaconda3/envs/paddle_env/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by hktalent** [comment]
```
pip uninstall -y numpy
pip install "Numpy==1.23.5"
```

**Comment by sparshgarg23** [comment]
2026 and this error still persists what is the point of opensourcing when the person who is maintaining this repository cant be bothered with updating it.
you also have langchain.docstore no module error.
