### ISSUE TITLE
Table Recognition in English

### ISSUE THREAD

**Issue by AyushiNM** [PaddlePaddle/PaddleOCR#9551]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows 11
- 版本号/Version： Paddle：2.4.2  PaddleOCR：2.6.1.3 问题相关组件/Related components： I'm working on Anaconda Powershell. Models used by me - ![PaddleOCR](https://user-images.githubusercontent.com/54371479/227854210-b5fb2018-c564-4e28-9cd4-b74d56d86fb7.png)
- 运行指令/Command Code： python table/predict_table.py --det_model_dir=inference/en_ppocr_mobile_v2.0_table_det_infer --rec_model_dir=inference/en_ppocr_mobile_v2.0_table_rec_infer  --table_model_dir=inference/en_ppstructure_mobile_v2.0_SLANet_infer --rec_char_dict_path=../ppocr/utils/en_dict.txt --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt --image_dir=docs/table/table.jpg --output=../output/table
- 完整报错/Complete Error Message：Traceback (most recent call last):
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppstructure\table\predict_table.py", line 230, in <module>
    main(args)
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppstructure\table\predict_table.py", line 181, in main
    pred_res, _ = table_sys(img)
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppstructure\table\predict_table.py", line 90, in __call__
    dt_boxes, rec_res, det_elapse, rec_elapse = self._ocr(
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppstructure\table\predict_table.py", line 137, in _ocr
    rec_res, rec_elapse = self.text_recognizer(img_crop_list)
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\tools\infer\predict_rec.py", line 619, in __call__
    rec_result = self.postprocess_op(preds)
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 121, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 83, in decode
    char_list = [
  File "C:\Users\MY PC\Documents\Raptor Supplies Capstone Project\PaddleOCR\ppocr\postprocess\rec_postprocess.py", line 84, in <listcomp>
    self.character[text_id]
IndexError: list index out of range

I'm trying to use table recognition models to make inferences on an existing dataset. Still, I keep getting this "list index out of range error", meaning there are not enough characters in the dictionary. The model is making some predictions even greater than 200, which doesn't make sense since english doesn't have that many characters.

Any help is appreciated. Thanks a lot!

**Comment by UserWangZz** [comment]
This issue has not been updated for a long time. This issue is temporarily closed and can be reopened if necessary.
