### ISSUE TITLE
利用predict_system.py預測英文錯誤

### ISSUE THREAD

**Issue by 38weiying** [PaddlePaddle/PaddleOCR#9555]
環境:Ubuntu 22.04，但在conda虛擬環境之下

指令
python ./tools/infer/predict_system2.py --image_dir="../upload/1.jpg" \
--det_model_dir="./inference/det/en/en_PP-OCRv3_det_infer" \
--rec_model_dir="./inference/rec/en/en_PP-OCRv3_rec_infer" \
--cls_model_dir="./inference/cls/ch_ppocr_mobile_v2.0_cls_infer" \
--rec_char_dict_path="./ppocr/utils/dict/en_dict.txt" \
--drop_score=0.0 --det_db_box_thresh=0.6 --det_db_unclip_ratio=1.5 \
--show_log=false --draw_img_save_dir="../static/output/predict_system"

抱錯
Traceback (most recent call last):
  File "./tools/infer/predict_system2.py", line 264, in <module>
    main(args)
  File "./tools/infer/predict_system2.py", line 181, in main
    dt_boxes, rec_res, time_dict = text_sys(img)
  File "./tools/infer/predict_system2.py", line 95, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/user/ocr/paddleocr_api/PaddleOCR/tools/infer/predict_rec.py", line 619, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/user/ocr/paddleocr_api/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 121, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/user/ocr/paddleocr_api/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 83, in decode
    char_list = [
  File "/home/user/ocr/paddleocr_api/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 84, in <listcomp>
    self.character[text_id]
IndexError: list index out of range

**Comment by 38weiying** [comment]
已解決!!
--rec_char_dict_path="./ppocr/utils/dict/en_dict.txt"
改成
--rec_char_dict_path="./ppocr/utils/en_dict.txt"

**Comment by jiangbossB** [comment]
> 已解決!! --rec_char_dict_path="./ppocr/utils/dict/en_dict.txt" 改成 --rec_char_dict_path="./ppocr/utils/en_dict.txt"

这个文件是要和训练时的保持一致吗 我改了还是报错

**Comment by 38weiying** [comment]
> > 已解決!! --rec_char_dict_path="./ppocr/utils/dict/en_dict.txt" 改成 --rec_char_dict_path="./ppocr/utils/en_dict.txt"
> 
> 这个文件是要和训练时的保持一致吗 我改了还是报错

訓練的時候應該也要用同一個字典檔的
