### ISSUE TITLE
在进行RE关系抽取训练时，标注文件中把question和answer换成其它自定义标签时会报错，请问在RE训练时只能用question和answer作为有关系的文本行的label吗

### ISSUE THREAD

**Issue by happybuby** [PaddlePaddle/PaddleOCR#9613]
在进行RE关系抽取训练时，标注文件中把question和answer换成其它自定义标签时会报错，请问在RE训练时只能用question和answer作为有关系的文本行的label吗？

**Comment by an1018** [comment]
配置文件中的类别list也需要改变

**Comment by happybuby** [comment]
class_list也相应的改过了，但还是报Floating point exception

**Comment by happybuby** [comment]
代码里已写死成answer和question，通过修改源码，目前已支持自定义标签的训练

**Comment by c-avan** [comment]
@happybuby  _你好，请问是怎末解决的，我自定义标签，形如【answer_1,question_1,answer_2,question_2】多对，每次训练，迭代几十步就出现内存爆掉的问题，或者是一开始就爆掉，batch_size已改为1，是有哪块没有修改吗？使用官方数据可以正常训练。_

**Comment by BB86818BB** [comment]
你好，我训练完之后进行预测的时候报错，请问你遇到过么？报错的信息如下：

**Comment by BB86818BB** [comment]
你好，我训练完之后进行预测的时候报错，请问你遇到过么？报错的信息如下：Traceback (most recent call last):
File "/home/ocr/PaddleOCR-release-2.7.1/./tools/infer_kie_token_ser_re.py", line 218, in
result = ser_re_engine(data)
File "/home/ocr/PaddleOCR-release-2.7.1/./tools/infer_kie_token_ser_re.py", line 152, in call
preds = self.model(re_input)
File "/usr/local/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in call
return self.forward(*inputs, **kwargs)
File "/home/ocr/PaddleOCR-release-2.7.1/ppocr/modeling/architectures/base_model.py", line 86, in forward
x = self.backbone(x)
File "/usr/local/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in call
return self.forward(*inputs, **kwargs)
File "/home/ocr/PaddleOCR-release-2.7.1/ppocr/modeling/backbones/vqa_layoutlm.py", line 220, in forward
x = self.model(
File "/usr/local/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in call
return self.forward(*inputs, **kwargs)
File "/usr/local/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1329, in forward
loss, pred_relations = self.extractor(sequence_output, entities, relations)
File "/usr/local/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in call
return self.forward(*inputs, **kwargs)
File "/usr/local/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1223, in forward
relations, entities = self.build_relation(relations, entities)
File "/usr/local/lib/python3.10/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1167, in build_relation
all_possible_relations = paddle.stack(
File "/usr/local/lib/python3.10/site-packages/paddle/tensor/manipulation.py", line 2001, in stack
return _C_ops.stack(x, axis)
ValueError: (InvalidArgument) x dim number should greater than 0, but received value is: 0
[Hint: Expected x_dim > 0, but received x_dim:0 <= 0:0.] (at ../paddle/phi/backends/gpu/gpu_launch_config.h:166)
