### ISSUE TITLE
数据生成器异常退出，141错误，

### ISSUE THREAD

**Issue by lx-rookie** [PaddlePaddle/PaddleOCR#962]
下面这个错误信息：
[linyicheng@A5-401-NF5288M5-2018-012 PaddleOCR-develop]$ python tools/train.py -c configs/rec/ch_ppocr_v1.1/rec_chinese_common_train_v1.1.yml
2020-10-19 20:52:00,810-INFO: {'Global': {'debug': False, 'algorithm': 'CRNN', 'use_gpu': True, 'epoch_num': 500, 'log_smooth_window': 20, 'print_batch_step': 10, 'save_model_dir': './output/rec_crnn/201019', 'save_epoch_step': 1, 'eval_batch_step': 10000, 'train_batch_size_per_card': 128, 'test_batch_size_per_card': 128, 'image_shape': [3, 32, 320], 'max_text_length': 25, 'character_type': 'ch', 'character_dict_path': './ppocr/utils/train_keys.txt', 'loss_type': 'ctc', 'distort': False, 'use_space_char': False, 'reader_yml': './configs/rec/rec_chinese_reader.yml', 'pretrain_weights': './checkpoint/ch_ppocr_server_v1.1_rec_pre/best_accuracy', 'checkpoints': None, 'save_inference_dir': './output/rec_crnn/201019/models/', 'infer_img': '/data2/crnn_image/'}, 'Architecture': {'function': 'ppocr.modeling.architectures.rec_model,RecModel'}, 'Backbone': {'function': 'ppocr.modeling.backbones.rec_resnet_vd,ResNet', 'layers': 34}, 'Head': {'function': 'ppocr.modeling.heads.rec_ctc_head,CTCPredict', 'encoder_type': 'rnn', 'fc_decay': 4e-05, 'SeqRNN': {'hidden_size': 256}}, 'Loss': {'function': 'ppocr.modeling.losses.rec_ctc_loss,CTCLoss'}, 'Optimizer': {'function': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.0005, 'l2_decay': 4e-05, 'beta1': 0.9, 'beta2': 0.999, 'decay': {'function': 'cosine_decay_warmup', 'step_each_epoch': 254, 'total_epoch': 500, 'warmup_minibatch': 1000}}, 'TrainReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'num_workers': 8, 'img_set_dir': '/data2/', 'label_file_path': './train_data/train_3.txt'}, 'EvalReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'img_set_dir': '/data2/', 'label_file_path': './train_data/test_3.txt'}, 'TestReader': {'reader_function': 'ppocr.data.rec.dataset_traversal,SimpleReader', 'img_set_dir': '/data2/', 'label_file_path': './train_data/test_3.txt'}}
import ujson error: No module named 'ujson' use json
2020-10-19 20:52:02,019-INFO: places would be ommited when DataLoader is not iterable
W1019 20:52:02.913641 34353 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 9.0
W1019 20:52:02.919180 34353 device_context.cc:245] device: 0, cuDNN Version: 7.4.
2020-10-19 20:52:04,129-INFO: Loading parameters from ./checkpoint/ch_ppocr_server_v1.1_rec_pre/best_accuracy...
2020-10-19 20:52:05,546-WARNING: variable ctc_fc_w_attr not used
2020-10-19 20:52:05,546-WARNING: variable ctc_fc_b_attr not used
2020-10-19 20:52:05,648-INFO: Finish initing model from ./checkpoint/ch_ppocr_server_v1.1_rec_pre/best_accuracy
I1019 20:52:05.674093 34353 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I1019 20:52:05.705708 34353 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I1019 20:52:05.750758 34353 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1019 20:52:05.770315 34353 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-10-19 20:52:11,862-WARNING: Your reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/linyicheng/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/linyicheng/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 853, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 489, in __reader_creator__
    yield self.feed(item)
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 323, in feed
    "len(feed_list) (%d)") % (len(each_sample), len(converter))
AssertionError: The number of fields in data (1) does not match len(feed_list) (2)

/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main()
  File "tools/train.py", line 105, in main
    program.train_eval_rec_run(config, exe, train_info_dict, eval_info_dict)
  File "/home/linyicheng/wanghb/PaddleOCR-develop/tools/program.py", line 422, in train_eval_rec_run
    return_numpy=False)
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 850, in _run_impl
    return_numpy=return_numpy)
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 684, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 733, in _init_non_iterable
    outputs={'Out': self._feed_list})
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 646, in __init__
    self._init_non_iterable()
  File "/home/linyicheng/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 280, in from_generator
    iterable, return_list)
  File "/home/linyicheng/wanghb/PaddleOCR-develop/ppocr/modeling/architectures/rec_model.py", line 148, in create_feed
    iterable=False)
  File "/home/linyicheng/wanghb/PaddleOCR-develop/ppocr/modeling/architectures/rec_model.py", line 199, in __call__
    image, labels, loader = self.create_feed(mode)
  File "/home/linyicheng/wanghb/PaddleOCR-develop/tools/program.py", line 172, in build
    dataloader, outputs = model(mode=mode)
  File "tools/train.py", line 51, in main
    config, train_program, startup_program, mode='train')
  File "tools/train.py", line 131, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

下面是配置文件：
![image](https://user-images.githubusercontent.com/54061448/96453925-bb5abd80-124d-11eb-9911-aed29d22bb9a.png)
txt里的图片路径是相对于/data2/的路径，最主要是我之前跑通过了一次这个，后面相同的数据又不行了。。。。。。。。

**Comment by littletomatodonkey** [comment]
重新获取下最新代码吧，确保代码部分没有什么改动，同时再检查一下数据路径和标注格式吧，感觉是reader这块有问题

**Comment by lx-rookie** [comment]
数据路径是对的，别的crnn都能训练起来，间隔是空格也是对的。代码都没动过。
这个reader的错误提示都很难看懂。

**Comment by lx-rookie** [comment]
已解决，生成的数据label有\t,分隔符有连续两个\t，导致切割之后出现label空字符，导致reader报错。
