### ISSUE TITLE
c++ 调用python PaddleOCR报错

### ISSUE THREAD

**Issue by lxinghai007** [PaddlePaddle/PaddleOCR#963]
单独执行python 调用没有问题
使用c++调用python 就报如下错误，不知道咋回事

2020-10-19 21:58:50,218-ERROR: basic_ios::clear: iostream error
Traceback (most recent call last):
  File "/home/lxh/workspace/hs/project/zheNeng/code/grab_image_ros/build/ocrDetector.py", line 12, in <module>
    from paddleocr import PaddleOCR
  File "/home/lxh/.local/lib/python3.6/site-packages/paddleocr/__init__.py", line 16, in <module>
    from .paddleocr import PaddleOCR
  File "/home/lxh/.local/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 28, in <module>
    from tools.infer import predict_system
  File "/home/lxh/.local/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 26, in <module>
    import tools.infer.predict_det as predict_det
  File "/home/lxh/.local/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 35, in <module>
    from ppocr.data.det.db_process import DBProcessTest
  File "/home/lxh/.local/lib/python3.6/site-packages/paddleocr/ppocr/data/det/db_process.py", line 25, in <module>
    from .make_shrink_map import MakeShrinkMap
  File "/home/lxh/.local/lib/python3.6/site-packages/paddleocr/ppocr/data/det/make_shrink_map.py", line 10, in <module>
    from shapely.geometry import Polygon
  File "/home/lxh/.local/lib/python3.6/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/lxh/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 183, in <module>
    EMPTY = deserialize_wkb(a2b_hex(b'010700000000000000'))
  File "/home/lxh/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 123, in deserialize_wkb
    "Could not create geometry because of errors while reading input.")
shapely.errors.WKBReadingError: Could not create geometry because of errors while reading input.
Can not open python file! 
W1019 21:58:50.247069 25286 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1019 21:58:50.247089 25286 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1019 21:58:50.247095 25286 init.cc:231] The detail failure signal is:

W1019 21:58:50.247102 25286 init.cc:234] *** Aborted at 1603115930 (unix time) try "date -d @1603115930" if you are using GNU date ***
W1019 21:58:50.248844 25286 init.cc:234] PC: @                0x0 (unknown)
W1019 21:58:50.248980 25286 init.cc:234] *** SIGSEGV (@0x8) received by PID 25272 (TID 0x7f94e8b7f700) from PID 8; stack trace: ***
W1019 21:58:50.251214 25286 init.cc:234]     @     0x7f95105898a0 (unknown)
W1019 21:58:50.253892 25286 init.cc:234]     @     0x7f950fe8825b PyModule_GetDict
W1019 21:58:50.253979 25286 init.cc:234]     @     0x55ce14b45395 (unknown)
W1019 21:58:50.256624 25286 init.cc:234]     @     0x7f951057e6db start_thread
W1019 21:58:50.259112 25286 init.cc:234]     @     0x7f950e86fa3f clone
W1019 21:58:50.260648 25286 init.cc:234]     @                0x0 (unknown)

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/96532449-863a8380-12be-11eb-8cdf-386f17780953.png)
