### ISSUE TITLE
Error [operator < conv2d_fusion > error] while use ppyolov2_r50vd_dcn_365e_publaynet model

### ISSUE THREAD

**Issue by ghazalli** [PaddlePaddle/PaddleOCR#9654]
Hi, i want to ask when using this model ppyolov2_r50vd_dcn_365e_publaynet i got this error 

```
    InvalidArgumentError: The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2411)
      [operator < conv2d_fusion > error]
```

here is the code that i use. I'm using paddlepaddle-gpu 2.4.0.post117

```python
import os
import cv2
from paddleocr import PPStructure, save_structure_res

table_engine = PPStructure(
    table=False,
    ocr=False,
    show_log=True,
    lang="en",
    layout_model_dir="model_zoo/ppyolov2_r50vd_dcn_365e_publaynet/",)
```

pls help, it's works normal when i'm use picodet_lcnet_x1_0_fgd_layout model, it use the same dict path.

**Comment by WenjinW** [comment]
I got the same error too. It works well with the picodet_lcnet_x1_0_fgd_layout model.

**Comment by rexzhengzhihong** [comment]
我也是。使用picodet_lcnet_x1_0_fgd_layout_table_infer模型没问题。但使用ppyolov2_r50vd_dcn_365e_tableBank_word和自己在paddleDetection训练的模型就报这个错
```
Traceback (most recent call last):
  File "/snap/pycharm-community/329/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/329/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppstructure/predict_system_test.py", line 454, in <module>
    main(args)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppstructure/predict_system_test.py", line 388, in main
    res, time_dict = structure_sys(img, img_idx=index)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppstructure/predict_system_test.py", line 170, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppstructure/layout/predict_layout.py", line 86, in __call__
    self.predictor.run()
ValueError: (InvalidArgument) The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2411)
  [operator < conv2d_fusion > error]
python-BaseException

```

**Comment by duyquang392** [comment]
The cause of the error is because you use model pyolov2 and config file of picodet model, arch of pyolov2 model is YOLO while arch of Picodet model is PicoDet, 2 different arch will initialize different layer. 
To fix the error just replace the config file of pyolov2. It has the form:

`mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 640
  - 640
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
label_list:
- text
- title
- list
- table
- figure`

**Comment by TrentonBush** [comment]
@duyquang392 thanks for your help. Where do you put that config file? I don't see any any layout models in the PaddleOCR/configs directory.

**Comment by kenho211** [comment]
Confirms that the config from the above works. It is on the resize height and width. PPYolov2 requires (640 x 640) while PICODet requires (800 x 640). The following code works for both PPYolov2 and PICODet given the right resized height and width.

`import paddleocr
import cv2
from paddleocr.ppstructure.layout.predict_layout import LayoutPredictor
from paddleocr.tools.infer import utility
from ppocr.data import create_operators, transform
from ppocr.postprocess import build_post_process
from ppocr.utils.logging import get_logger
logger = get_logger()

class LayoutPredictor_custom_resize(LayoutPredictor):
    def __init__(self, args):
        super().__init__(args)
        
        pre_process_list = [{
            'Resize': {
                'size': [args.resized_height, args.resized_width]
            }
        }, {
            'NormalizeImage': {
                'std': [0.229, 0.224, 0.225],
                'mean': [0.485, 0.456, 0.406],
                'scale': '1./255.',
                'order': 'hwc'
            }
        }, {
            'ToCHWImage': None
        }, {
            'KeepKeys': {
                'keep_keys': ['image']
            }
        }]
        self.preprocess_op = create_operators(pre_process_list)
        self.predictor, self.input_tensor, self.output_tensors, self.config = \
            utility.create_predictor(args, 'layout', logger)
        

        
class Config(object):
    pass

cfg = Config()
# cfg.layout_model_dir = './layout/ppyolov2_r50vd_dcn_365e_publaynet'
cfg.layout_model_dir = './layout/picodet_lcnet_x1_0_fgd_layout_infer'
cfg.layout_dict_path = './layout/layout_publaynet_dict.txt"
cfg.layout_score_threshold = 0.5
cfg.layout_nms_threshold = 0.5
cfg.use_xpu = False
cfg.use_gpu = False
cfg.ir_optim = True
cfg.enable_mkldnn = False
# cfg.cpu_threads = 4
cfg.use_onnx = False
cfg.use_tensorrt = False
cfg.min_subgraph_size = 15
cfg.precision = 'fp32'
cfg.resized_height = 640
cfg.resized_width = 640
layout_predictor = LayoutPredictor_custom_resize(cfg)


# Example 
img_path = "./img/img.jpeg"
img = cv2.imread(img_path)
pred = layout_predictor(img)[0]
print(pred)`

**Comment by tuongtranngoc** [comment]
@kenho211 it does not work for the isssue

**Comment by kenho211** [comment]
> @kenho211 it does not work for the issue

That is not a fix to the issue. PPstructure is using LayoutPredictor under the hood. 
I just want to show that LayoutPredictor is hardcoded for the resized size in preprocess. And if you need to make it work or someone to fix it, input shape will be the issue to look at.

**Comment by chmjelek** [comment]
> Confirms that the config from the above works. It is on the resize height and width. PPYolov2 requires (640 x 640) while PICODet requires (800 x 640). The following code works for both PPYolov2 and PICODet given the right resized height and width.
> 
> ```
> import paddleocr
> import cv2
> from paddleocr.ppstructure.layout.predict_layout import LayoutPredictor
> from paddleocr.tools.infer import utility
> from ppocr.data import create_operators, transform
> from ppocr.postprocess import build_post_process
> from ppocr.utils.logging import get_logger
> logger = get_logger()
> 
> class LayoutPredictor_custom_resize(LayoutPredictor):
>     def __init__(self, args):
>         super().__init__(args)
>         
>         pre_process_list = [{
>             'Resize': {
>                 'size': [args.resized_height, args.resized_width]
>             }
>         }, {
>             'NormalizeImage': {
>                 'std': [0.229, 0.224, 0.225],
>                 'mean': [0.485, 0.456, 0.406],
>                 'scale': '1./255.',
>                 'order': 'hwc'
>             }
>         }, {
>             'ToCHWImage': None
>         }, {
>             'KeepKeys': {
>                 'keep_keys': ['image']
>             }
>         }]
>         self.preprocess_op = create_operators(pre_process_list)
>         self.predictor, self.input_tensor, self.output_tensors, self.config = \
>             utility.create_predictor(args, 'layout', logger)
>         
> class Config(object):
>     pass
> 
> cfg = Config()
> cfg.layout_model_dir = './layout/ppyolov2_r50vd_dcn_365e_publaynet'
> cfg.resized_height = 640   ### For PPYolov2
> cfg.resized_width = 640    ### For PPYolov2
> # cfg.layout_model_dir = './layout/picodet_lcnet_x1_0_fgd_layout_infer'
> # cfg.resized_height = 800   ### For PICODet
> # cfg.resized_width = 608    ### For PICODet
> cfg.layout_dict_path = './layout/layout_publaynet_dict.txt"
> cfg.layout_score_threshold = 0.5
> cfg.layout_nms_threshold = 0.5
> cfg.use_xpu = False
> cfg.use_gpu = False
> cfg.ir_optim = True
> cfg.enable_mkldnn = False
> cfg.use_onnx = False
> cfg.use_tensorrt = False
> cfg.min_subgraph_size = 15
> cfg.precision = 'fp32'
> 
> layout_predictor = LayoutPredictor_custom_resize(cfg)
> 
> 
> # Example
> img_path = "./img/img.jpeg"
> img = cv2.imread(img_path)
> pred = layout_predictor(img)[0]
> print(pred)
> ```

This code snippet does not work for `PPYolov2`, still getting error: `InvalidArgumentError: The size of Op(Conv) inputs should not be 0.`

**Comment by luan78zaoha** [comment]
遇到同样的问题，怎么解决

**Comment by duyquang392** [comment]
> @duyquang392 thanks for your help. Where do you put that config file? I don't see any any layout models in the PaddleOCR/configs directory.

This config file is generated when exporting from train model to inference model. It's in the same folder as the predicted model

**Comment by chmjelek** [comment]
What would be the fix then

**Comment by kenho211** [comment]
```import paddleocr
import numpy as np
import cv2
import os
import time
from paddleocr.ppstructure.layout.predict_layout import LayoutPredictor
from paddle import inference
from paddleocr.tools.infer.utility import get_output_tensors
from ppocr.data import create_operators, transform
from ppocr.postprocess import build_post_process
from ppocr.utils.logging import get_logger
logger = get_logger()

# from paddleocr.tools.infer import utility
# replace with the following

def create_predictor(args, mode, logger):
    if mode == "det":
        model_dir = args.det_model_dir
    elif mode == 'cls':
        model_dir = args.cls_model_dir
    elif mode == 'rec':
        model_dir = args.rec_model_dir
    elif mode == 'table':
        model_dir = args.table_model_dir
    elif mode == 'ser':
        model_dir = args.ser_model_dir
    elif mode == 're':
        model_dir = args.re_model_dir
    elif mode == "sr":
        model_dir = args.sr_model_dir
    elif mode == 'layout':
        model_dir = args.layout_model_dir
    else:
        model_dir = args.e2e_model_dir

    if model_dir is None:
        logger.info("not find {} model file path {}".format(mode, model_dir))
        sys.exit(0)
    if args.use_onnx:
        import onnxruntime as ort
        model_file_path = model_dir
        if not os.path.exists(model_file_path):
            raise ValueError("not find model file path {}".format(
                model_file_path))
        sess = ort.InferenceSession(model_file_path)
        return sess, sess.get_inputs()[0], None, None

    else:
        file_names = ['model', 'inference']
        for file_name in file_names:
            model_file_path = '{}/{}.pdmodel'.format(model_dir, file_name)
            params_file_path = '{}/{}.pdiparams'.format(model_dir, file_name)
            if os.path.exists(model_file_path) and os.path.exists(
                    params_file_path):
                break
        if not os.path.exists(model_file_path):
            raise ValueError(
                "not find model.pdmodel or inference.pdmodel in {}".format(
                    model_dir))
        if not os.path.exists(params_file_path):
            raise ValueError(
                "not find model.pdiparams or inference.pdiparams in {}".format(
                    model_dir))

        config = inference.Config(model_file_path, params_file_path)

        if hasattr(args, 'precision'):
            if args.precision == "fp16" and args.use_tensorrt:
                precision = inference.PrecisionType.Half
            elif args.precision == "int8":
                precision = inference.PrecisionType.Int8
            else:
                precision = inference.PrecisionType.Float32
        else:
            precision = inference.PrecisionType.Float32

        if args.use_gpu:
            gpu_id = get_infer_gpuid()
            if gpu_id is None:
                logger.warning(
                    "GPU is not found in current device by nvidia-smi. Please check your device or ignore it if run on jetson."
                )
            config.enable_use_gpu(args.gpu_mem, args.gpu_id)
            if args.use_tensorrt:
                config.enable_tensorrt_engine(
                    workspace_size=1 << 30,
                    precision_mode=precision,
                    max_batch_size=args.max_batch_size,
                    min_subgraph_size=args.
                    min_subgraph_size,  # skip the minmum trt subgraph
                    use_calib_mode=False)

                # collect shape
                trt_shape_f = os.path.join(model_dir,
                                           f"{mode}_trt_dynamic_shape.txt")

                if not os.path.exists(trt_shape_f):
                    config.collect_shape_range_info(trt_shape_f)
                    logger.info(
                        f"collect dynamic shape info into : {trt_shape_f}")
                try:
                    config.enable_tuned_tensorrt_dynamic_shape(trt_shape_f,
                                                               True)
                except Exception as E:
                    logger.info(E)
                    logger.info("Please keep your paddlepaddle-gpu >= 2.3.0!")

        elif args.use_npu:
            config.enable_custom_device("npu")
        elif args.use_xpu:
            config.enable_xpu(10 * 1024 * 1024)
        else:
            config.disable_gpu()
            if args.enable_mkldnn:
                # cache 10 different shapes for mkldnn to avoid memory leak
                config.set_mkldnn_cache_capacity(10)
                config.enable_mkldnn()
                if args.precision == "fp16":
                    config.enable_mkldnn_bfloat16()
                if hasattr(args, "cpu_threads"):
                    config.set_cpu_math_library_num_threads(args.cpu_threads)
                else:
                    # default cpu threads as 10
                    config.set_cpu_math_library_num_threads(10)
        # enable memory optim
        config.enable_memory_optim()
        config.disable_glog_info()
        config.delete_pass("conv_transpose_eltwiseadd_bn_fuse_pass")
        config.delete_pass("matmul_transpose_reshape_fuse_pass")
        if mode == 're':
            config.delete_pass("simplify_with_basic_ops_pass")
        if mode == 'table':
            config.delete_pass("fc_fuse_pass")  # not supported for table
        config.switch_use_feed_fetch_ops(False)
        config.switch_ir_optim(True)

        # create predictor
        predictor = inference.create_predictor(config)
        input_names = predictor.get_input_names()
        if mode in ['ser', 're', 'layout']:
            input_tensor = []
            for name in input_names:
                input_tensor.append(predictor.get_input_handle(name))
        else:
            for name in input_names:
                input_tensor = predictor.get_input_handle(name)
        output_tensors = get_output_tensors(args, mode, predictor)
        return predictor, input_tensor, output_tensors, config
    

class LayoutPredictor_custom(LayoutPredictor):
    def __init__(self, args):
        super().__init__(args)
        pre_process_list = [{
            'Resize': {
                'size': [args.resized_height, args.resized_width]
            }
        }, {
            'NormalizeImage': {
                'std': [0.229, 0.224, 0.225],
                'mean': [0.485, 0.456, 0.406],
                'scale': '1./255.',
                'order': 'hwc'
            }
        }, {
            'ToCHWImage': None
        }, {
            'KeepKeys': {
                'keep_keys': ['im_shape', 'image', 'scale_factor']
            }
        }]
        self.resized_height = args.resized_height
        self.resized_width = args.resized_width
        self.preprocess_op = create_operators(pre_process_list)
        self.predictor, self.input_tensor, self.output_tensors, self.config = \
            create_predictor(args, 'layout', logger)
        
    def __call__(self, img):
        ori_im = img.copy()
        data = {
            'im_shape': np.array([img.shape[:2]]),
            'image': img,
            'scale_factor': np.array([[1,1]])
        }
        data = transform(data, self.preprocess_op)
        im_shape = data[0]
        img = data[1]
        scale_factor = data[2]

        if img is None:
            return None, 0

        img = np.expand_dims(img, axis=0)
        img = img.copy()

        preds, elapse = 0, 1
        starttime = time.time()

        self.input_tensor[0].copy_from_cpu(im_shape)
        self.input_tensor[1].copy_from_cpu(img)
        self.input_tensor[2].copy_from_cpu(scale_factor)
        self.predictor.run()

        np_score_list, np_boxes_list = [], []
        output_names = self.predictor.get_output_names()
        num_outs = int(len(output_names) / 2)
        for out_idx in range(num_outs):
            np_score_list.append(
                self.predictor.get_output_handle(output_names[out_idx])
                .copy_to_cpu())
            np_boxes_list.append(
                self.predictor.get_output_handle(output_names[
                    out_idx + num_outs]).copy_to_cpu())

        preds = dict(boxes=np_score_list, boxes_num=np_boxes_list)
        return preds
        # post_preds = self.postprocess_op(ori_im, img, preds)
        # elapse = time.time() - starttime
        # return post_preds, elapse
        
        
class Config(object):
    pass

cfg = Config()
cfg.layout_model_dir = 'C:\\Users\\kenho\\Desktop\\ppocr_model\\layout\\ppyolov2_r50vd_dcn_365e_publaynet'
cfg.layout_dict_path = "C:\\Users\\kenho\\Desktop\\ppocr_model\\layout\\layout_publaynet_dict.txt"
cfg.layout_score_threshold = 0.5
cfg.layout_nms_threshold = 0.5
cfg.use_xpu = False
cfg.use_gpu = False
cfg.use_npu = False
cfg.ir_optim = True
cfg.enable_mkldnn = False
cfg.use_onnx = False
cfg.use_tensorrt = False
cfg.min_subgraph_size = 15
cfg.precision = 'fp32'
cfg.resized_height = 640
cfg.resized_width = 640
layout_predictor = LayoutPredictor_custom(cfg)

# Example 
img_path = "./img/71531_p1.jpeg"
img = cv2.imread(img_path)
pred = layout_predictor(img)
print(pred)```

Further changing the code snippet on calling LayoutDetector and create_predictor will make it "run" without error
But the output is clearly not correct. 
Also it is quite obvious that LayoutDetector class does not support PPYOLOv2 format yet.
- line 285-286 of `create_predictor` does not support multiple `input_names`
- Currently LayoutDetector's postprocess is hardcoded to use PicoDetPostprocess. But Yolo's postprocess cannot be found in the list of supported postprocesses.

**Comment by duyquang392** [comment]
> The cause of the error is because you use model pyolov2 and config file of picodet model, arch of pyolov2 model is YOLO while arch of Picodet model is PicoDet, 2 different arch will initialize different layer. To resolve i replaced the config file of ppyolov2 : _**infer_cfg.yml.**_ It has the form:
> 
> ```
> mode: paddle
> draw_threshold: 0.5
> metric: COCO
> use_dynamic_shape: false
> arch: YOLO
> min_subgraph_size: 3
> Preprocess:
> - interp: 2
>   keep_ratio: false
>   target_size:
>   - 640
>   - 640
>   type: Resize
> - is_scale: true
>   mean:
>   - 0.485
>   - 0.456
>   - 0.406
>   std:
>   - 0.229
>   - 0.224
>   - 0.225
>   type: NormalizeImage
> - type: Permute
> label_list:
> - text
> - title
> - list
> - table
> - figure
> ```


Further changing the code snippet on calling PPYoloDetector and create_predictor make it "run" without error. (The **_infer_cfg.yml_** as mentioned above)
```
import os
import yaml
import numpy as np
import paddle
import time
import cv2
import sys
__dir__ = os.path.dirname(os.path.abspath(__file__))
sys.path.append(__dir__)
sys.path.insert(0, os.path.abspath(os.path.join(__dir__, '../../')))

os.environ["FLAGS_allocator_strategy"] = 'auto_growth'
import utility as utility
from utility import Timer
from logging import get_logger
from utility import get_image_file_list, check_and_read
from utility import parse_args

logger = get_logger()

def decode_image(im_file, im_info):
    """read rgb image
    Args:
        im_file (str|np.ndarray): input can be image path or np.ndarray
        im_info (dict): info of image
    Returns:
        im (np.ndarray):  processed image (np.ndarray)
        im_info (dict): info of processed image
    """
    if isinstance(im_file, str):
        with open(im_file, 'rb') as f:
            im_read = f.read()
        data = np.frombuffer(im_read, dtype='uint8')
        im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
        im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    else:
        im = im_file
    im_info['im_shape'] = np.array(im.shape[:2], dtype=np.float32)
    im_info['scale_factor'] = np.array([1., 1.], dtype=np.float32)
    return im, im_info


def preprocess(im, preprocess_ops):
    # process image by preprocess_ops
    im_info = {
        'scale_factor': np.array(
            [1., 1.], dtype=np.float32),
        'im_shape': None,
    }
    im, im_info = decode_image(im, im_info)
    for operator in preprocess_ops:
        im, im_info = operator(im, im_info)
    return im, im_info


class PPYoloDetector(object):

    def __init__(self, args):
        model_dir = args.layout_ppyolo_model_dir
        self.labels = self.load_layout_dict(args.layout_dict_path)
        self.pred_config = self.set_config(model_dir)
        self.predictor, self.input_tensor, self.output_tensors, self.config = \
            utility.create_predictor(args, 'layout_ppyolo', logger)
        
        self.det_times = Timer()
        self.cpu_mem, self.gpu_mem, self.gpu_util = 0, 0, 0
        self.threshold = args.layout_score_threshold

    def load_layout_dict(self, layout_dict_path):
        with open(layout_dict_path, 'r', encoding='utf-8') as fp:
            labels = fp.readlines()
        return [label.strip('\n') for label in labels]
    
    def set_config(self, model_dir):
        return PredictConfig(model_dir)

    def preprocess(self, image_list):
        preprocess_ops = []
        for op_info in self.pred_config.preprocess_infos:
            new_op_info = op_info.copy()
            op_type = new_op_info.pop('type')
            preprocess_ops.append(eval(op_type)(**new_op_info))

        im, im_info = preprocess(image_list, preprocess_ops)
        inputs = create_inputs(im, im_info)
        input_names = self.predictor.get_input_names()
        for i in range(len(input_names)):
            input_tensor = self.predictor.get_input_handle(input_names[i])
            if input_names[i] == 'x':
                input_tensor.copy_from_cpu(inputs['image'])
            else:
                input_tensor.copy_from_cpu(inputs[input_names[i]])

        return inputs

    def postprocess(self, inputs, result):
        # postprocess output of predictor
        np_boxes_num = result['boxes_num']
        assert isinstance(np_boxes_num, np.ndarray), \
            '`np_boxes_num` should be a `numpy.ndarray`'

        result = {k: v for k, v in result.items() if v is not None}
        return result

    def filter_box(self, result, threshold):
        np_boxes_num = result['boxes_num']
        boxes = result['boxes']
        start_idx = 0
        filter_boxes = []
        filter_num = []
        for i in range(len(np_boxes_num)):
            boxes_num = np_boxes_num[i]
            boxes_i = boxes[start_idx:start_idx + boxes_num, :]
            idx = boxes_i[:, 1] > threshold
            filter_boxes_i = boxes_i[idx, :]
            filter_boxes.append(filter_boxes_i)
            filter_num.append(filter_boxes_i.shape[0])
            start_idx += boxes_num
        boxes = np.concatenate(filter_boxes)
        filter_num = np.array(filter_num)
        filter_res = {'boxes': boxes, 'boxes_num': filter_num}
        return filter_res

    def predict(self, repeats=1, run_benchmark=False):
        # model prediction
        np_boxes_num, np_boxes, np_masks = np.array([0]), None, None

        if run_benchmark:
            for i in range(repeats):
                self.predictor.run()
                paddle.device.cuda.synchronize()
            result = dict(
                boxes=np_boxes, masks=np_masks, boxes_num=np_boxes_num)
            return result

        for i in range(repeats):
            self.predictor.run()
            output_names = self.predictor.get_output_names()
            boxes_tensor = self.predictor.get_output_handle(output_names[0])
            np_boxes = boxes_tensor.copy_to_cpu()
            if len(output_names) == 1:
                # some exported model can not get tensor 'bbox_num' 
                np_boxes_num = np.array([len(np_boxes)])
            else:
                boxes_num = self.predictor.get_output_handle(output_names[1])
                np_boxes_num = boxes_num.copy_to_cpu()
        result = dict(boxes=np_boxes, masks=np_masks, boxes_num=np_boxes_num)
        return result

    def __call__(self, image_list):
        resultouts = []
        starttime = time.time()
        # preprocess
        self.det_times.preprocess_time_s.start()
        inputs = self.preprocess(image_list)
        self.det_times.preprocess_time_s.end()

        # model prediction
        self.det_times.inference_time_s.start()
        result = self.predict()
        self.det_times.inference_time_s.end()

        # postprocess
        self.det_times.postprocess_time_s.start()
        result = self.postprocess(inputs, result)
        self.det_times.postprocess_time_s.end()
        self.det_times.img_num += len(image_list)

        elapse = time.time() - starttime
        np_boxes = result['boxes']
        
        expect_boxes = (np_boxes[:, 1] > self.threshold) & (np_boxes[:, 0] > -1)
        np_boxes = np_boxes[expect_boxes, :]
        for dt in np_boxes:
            clsid, bbox, score = int(dt[0]), dt[2:], dt[1]
            label = self.labels[clsid]
            resultout = {'bbox': bbox, 'label': label}
            resultouts.append(resultout)
        return resultouts, elapse

def create_inputs(imgs, im_info):
    """generate input for different model type
    Args:
        imgs (list(numpy)): list of images (np.ndarray)
        im_info (list(dict)): list of image info
    Returns:
        inputs (dict): input of model
    """
    inputs = {}

    im_shape = []
    scale_factor = []
    if len(imgs) == 1:
        inputs['image'] = np.array((imgs[0], )).astype('float32')
        inputs['im_shape'] = np.array(
            (im_info[0]['im_shape'], )).astype('float32')
        inputs['scale_factor'] = np.array(
            (im_info[0]['scale_factor'], )).astype('float32')
        return inputs

    for e in im_info:
        im_shape.append(np.array((e['im_shape'], )).astype('float32'))
        scale_factor.append(np.array((e['scale_factor'], )).astype('float32'))

    inputs['im_shape'] = np.concatenate(im_shape, axis=0)
    inputs['scale_factor'] = np.concatenate(scale_factor, axis=0)

    imgs_shape = [[e.shape[1], e.shape[2]] for e in imgs]
    max_shape_h = max([e[0] for e in imgs_shape])
    max_shape_w = max([e[1] for e in imgs_shape])
    padding_imgs = []
    for img in imgs:
        im_c, im_h, im_w = img.shape[:]
        padding_im = np.zeros(
            (im_c, max_shape_h, max_shape_w), dtype=np.float32)
        padding_im[:, :im_h, :im_w] = img
        padding_imgs.append(padding_im)
    inputs['image'] = np.stack(padding_imgs, axis=0)
    return inputs

class PredictConfig():
    def __init__(self, model_dir):
        # parsing Yaml config for Preprocess
        deploy_file = os.path.join(model_dir, 'infer_cfg.yml')
        with open(deploy_file) as f:
            yml_conf = yaml.safe_load(f)
        self.arch = yml_conf['arch']
        self.preprocess_infos = yml_conf['Preprocess']
        self.min_subgraph_size = yml_conf['min_subgraph_size']
        self.labels = yml_conf['label_list']
        self.mask = False
        self.use_dynamic_shape = yml_conf['use_dynamic_shape']
        if 'mask' in yml_conf:
            self.mask = yml_conf['mask']
        self.tracker = None
        if 'tracker' in yml_conf:
            self.tracker = yml_conf['tracker']
        if 'NMS' in yml_conf:
            self.nms = yml_conf['NMS']
        if 'fpn_stride' in yml_conf:
            self.fpn_stride = yml_conf['fpn_stride']
        if self.arch == 'RCNN' and yml_conf.get('export_onnx', False):
            print(
                'The RCNN export model is used for ONNX and it only supports batch_size = 1'
            )

def main(args):
    image_file_list = get_image_file_list(args.image_dir)
    layout_predictor = PPYoloDetector(args)
    count = 0
    total_time = 0

    repeats = 50
    for image_file in image_file_list:
        img, flag, _ = check_and_read(image_file)
        if not flag:
            img = cv2.imread(image_file)
        if img is None:
            logger.info("error in loading image:{}".format(image_file))
            continue

        layout_res, elapse = layout_predictor(img)

        logger.info("result: {}".format(layout_res))

        if count > 0:
            total_time += elapse
        count += 1
        logger.info("Predict time of {}: {}".format(image_file, elapse))


if __name__ == "__main__":
    main(parse_args())

```
