### ISSUE TITLE
分别训练多个网络检测模型时出现报错

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#9663]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Win10
- 版本号/Version：Paddle：  PaddleOCR：2.6 问题相关组件/Related components：det_r50_vd_east.yml
- 运行指令/Command Code：python tools/train.py -c configs/det/det_r50_vd_east.yml
- 完整报错/Complete Error Message：

Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\PaddleOCR-release-2.6\tools\program.py", line 321, in train
    post_result = post_process_class(preds, batch[1])
  File "D:\PaddleOCR-release-2.6\ppocr\postprocess\east_postprocess.py", line 132, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[ino]
ValueError: not enough values to unpack (expected 4, got 1)
PS D:\PaddleOCR-release-2.6> python tools/train.py -c configs/det/det_r50_vd_east.yml

训练检测模型的时候会出现上述错误，det_r50_vd_east.yml，det_mv3_db.yml等都会报错，请问是什么原因，如何解决？

**Comment by phb-shiyige-fw** [comment]
@WenmuZhou 希望您能给我回复，谢谢！

**Comment by phb-shiyige-fw** [comment]
@an1018 @andyjpaddle 各位大佬可以解决一下吗？
