### ISSUE TITLE
 err msg: list index out of range

### ISSUE THREAD

**Issue by litongjava** [PaddlePaddle/PaddleOCR#9700]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
Ubuntu 20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddleocr  2.6.1.3
是使用的 pdf转docx功能
- 运行指令/Command Code：
```
paddleocr --image_dir=人教版高中数学A版必修3.pdf --type=structure --recovery=true
```
- 完整报错/Complete Error Message：
``
[2023/04/11 19:07:22] ppocr INFO: processing 154/154 page:
[2023/04/11 19:07:23] ppocr DEBUG: dt_boxes num : 20, elapse : 0.5084586143493652
[2023/04/11 19:07:33] ppocr DEBUG: rec_res num  : 20, elapse : 9.703635215759277
[2023/04/11 19:07:33] ppocr DEBUG: dt_boxes num : 2, elapse : 0.4979572296142578
[2023/04/11 19:07:33] ppocr DEBUG: rec_res num  : 2, elapse : 0.35898280143737793
[2023/04/11 19:07:34] ppocr DEBUG: dt_boxes num : 1, elapse : 0.4979114532470703
[2023/04/11 19:07:34] ppocr DEBUG: rec_res num  : 1, elapse : 0.08002519607543945
[2023/04/11 19:07:37] ppocr ERROR: error in layout recovery image:人教版高中数学A版必修3, err msg: list index out of range

``
文件一共154页,已经转换完成了,在最后一页出现了这个错误,pdf文件下载地址
https://github.com/litongjava/china_high_school_math_people_teach_a_version_book/blob/main/book/%E4%BA%BA%E6%95%99A%E7%89%88%E6%95%99%E6%9D%90/%E4%BA%BA%E6%95%99%E7%89%88%E9%AB%98%E4%B8%AD%E6%95%B0%E5%AD%A6A%E7%89%88%E5%BF%85%E4%BF%AE3.pdf

**Comment by litongjava** [comment]
经过一番调试最终解决了问题,最终的命令
```
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt \
    --vis_font_path=../doc/fonts/simfang.ttf \
    --recovery=True \
    --output=../output/ \
    --image_dir=/data/code/math/人教A版教材/人教版高中数学A版必修3.pdf
```

**Comment by litongjava** [comment]
调试过程
```
python3 /data/code/python/PaddleOCR/ppstructure/predict_system.py \
    --image_dir=人教版高中数学A版必修3.pdf \
    --recovery=True \
--output=../output/
```
出现错误
```
FileNotFoundError: [Errno 2] No such file or directory: '../ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt'
``
切换指定目录
```
cd /data/code/python/PaddleOCR/ppstructure
python3 predict_system.py \
    --image_dir=/data/code/math/人教A版教材/人教版高中数学A版必修3.pdf \
    --recovery=True \
--output=../output/
```
出错错误
```
[2023/04/12 18:42:53] ppocr INFO: not find layout model file path None
```
增加指定参数
```
cd /data/code/python/PaddleOCR/ppstructure
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --image_dir=/data/code/math/人教A版教材/人教版高中数学A版必修3.pdf \
    --recovery=True \
--output=../output/
```
错误错误
```
FileNotFoundError: [Errno 2] No such file or directory: './ppocr/utils/ppocr_keys_v1.txt'
```
猜测是PyMuPDF的问题,将PyMuPDF从1.19.0升级到1.20.2 出现下面的错误
``
Traceback (most recent call last):
  File "predict_system.py", line 315, in <module>
    main(args)
  File "predict_system.py", line 227, in main
    img, flag_gif, flag_pdf = check_and_read(image_file)
  File "/data/code/python/PaddleOCR/ppocr/utils/utility.py", line 93, in check_and_read
    for pg in range(0, pdf.pageCount):
AttributeError: 'Document' object has no attribute 'pageCount'
```
还原PyMuPDF为1.19.0

执行命令再次增加指定参数
``
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_publaynet_dict.txt \
    --vis_font_path=../doc/fonts/simfang.ttf \
    --recovery=True \
    --output=../output/ \
    --image_dir=/data/code/math/人教A版教材/人教版高中数学A版必修3.pdf
``
出现下面的错误
```
  File "/data/code/python/PaddleOCR/ppocr/postprocess/picodet_postprocess.py", line 247, in __call__
    label = self.labels[clsid]
IndexError: list index out of range
```
打印输出self.labels和clsid
```
['text', 'title', 'list', 'table', 'figure'] 0
['text', 'title', 'list', 'table', 'figure'] 8
```
传入的参数layout_dict_path指定的layout_publaynet_dict.txt只有5行,从layout_publaynet_dict.txt修改为layout_cdla_dict.txt
```
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt \
    --vis_font_path=../doc/fonts/simfang.ttf \
    --recovery=True \
    --output=../output/ \
    --image_dir=/data/code/math/人教A版教材/人教版高中数学A版必修3.pdf
```
错误错误
```
../output/structure/人教版高中数学A版必修3/show_16.jpg

File "/data/code/python/PaddleOCR/ppocr/postprocess/table_postprocess.py", line 85, in decode
    text = self.character[char_idx]
IndexError: list index out of range
```
比对发现是第17页,输出 self.character[char_idx],但是识别第17页
```
cd /data/code/python/PaddleOCR/ppstructure
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt \
    --vis_font_path=../doc/fonts/simfang.ttf \
    --recovery=True \
    --output=../output/ \
--image_dir=/data/code/math/人教版高中数学A版必修3/人教版高中数学A版必修3_17.png
```
单独识别成功

再次执行输出的错误信息如下
```
[2023/04/12 19:42:25] ppocr DEBUG: rec_res num  : 2, elapse : 0.5202276706695557
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 5
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 7
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 11
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 8
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 9
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 6
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 5
['sos', '<thead>', '<tr>', '</td>', '</tr>', '</thead>', '<tbody>', '</tbody>', '<td', ' colspan="5"', '>', ' colspan="2"', ' colspan="3"', ' rowspan="2"', ' colspan="4"', ' colspan="6"', ' rowspan="3"', ' colspan="9"', ' colspan="10"', ' colspan="7"', ' rowspan="4"', ' rowspan="5"', ' rowspan="9"', ' colspan="8"', ' rowspan="8"', ' rowspan="6"', ' rowspan="7"', ' rowspan="10"', '<td></td>', 'eos'] 48
```
table_structure_dict.txt改为table_structure_dict_ch.txt
```
python3 predict_system.py \
    --det_model_dir=/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer \
    --rec_model_dir=/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer \
    --table_model_dir=/root/.paddleocr/whl/table/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --layout_model_dir=/root/.paddleocr/whl/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
    --layout_dict_path=../ppocr/utils/dict/layout_dict/layout_cdla_dict.txt \
    --vis_font_path=../doc/fonts/simfang.ttf \
    --recovery=True \
    --output=../output/ \
    --image_dir=/data/code/math/人教A版教材/人教版高中数学A版必修3.pdf
```
成功
