### ISSUE TITLE
paddle label矩形标注闪退，

### ISSUE THREAD

**Issue by cuyoo** [PaddlePaddle/PaddleOCR#9703]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
2.1.3版本，
点击矩形标注，在图片中只能点一下，然后就卡死，出这个错。多点标注正常。

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
C:\Users\jacky>PPOCRLabel --lang ch
[2023/04/12 12:46:35] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  D:\Users\user\Desktop\AI Studio\vehicle_invoice\vehicle_invoice\train\0.jpg
DirPath in importDirImages is D:/Users/user/Desktop/AI Studio/vehicle_invoice/vehicle_invoice/train
Traceback (most recent call last):
  File "D:\python\Python310\lib\site-packages\PPOCRLabel\libs\canvas.py", line 596, in paintEvent
    p.drawRect(leftTop.x(), leftTop.y(), rectWidth, rectHeight)
TypeError: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'float'
  drawRect(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'float'

**Comment by 107295472** [comment]
我的也是PPOCRLabelv2，不能标注，只能改以有的标注

**Comment by 107295472** [comment]
没懂，用的python3.10.xx

**Comment by cuyoo** [comment]
这个标注工具不太好用，要是能在easedata上标注完了导入一样的格式就好了。

**Comment by 107295472** [comment]
> 这个标注工具不太好用，要是能在easedata上标注完了导入一样的格式就好了。

其他工具标不起，这个他可以识别一些，不对的要标一下

**Comment by louxingrui** [comment]
我也出现矩形标注闪退，不过我的报错是

> Traceback (most recent call last):
  File "C:\Users\90760\anaconda3\envs\paddle\lib\site-packages\PPOCRLabel\libs\canvas.py", line 164, in mouseMoveEvent
    self.line.close()
  File "C:\Users\90760\anaconda3\envs\paddle\lib\site-packages\PPOCRLabel\libs\shape.py", line 95, in close
    self.center = QPointF((self.points[0].x() + self.points[2].x()) / 2,
IndexError: list index out of range
然后我下调了文件夹中图片的个数，就不闪退了。

**Comment by huangye123** [comment]
使用Python3.8 可以解决，Python3.10会有这个问题，希望官方可以改善一下Python版本兼容性

**Comment by cuyoo** [comment]
感觉有点校验不严格。drawRect(self, x: int, y: int, w: int, h: int)要求是Int，而调用的leftTop.x()不一定是整数，这里应该int(leftTop.x())一下，保险。
我改完了，不出错用起来还挺顺畅。
&nbsp;


Jacky：
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月8日(星期四) 晚上11:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] paddle label矩形标注闪退， (Issue #9703)





 
使用Python3.8 可以解决，Python3.10会有这个问题，希望官方可以改善一下Python版本兼容性
