### ISSUE TITLE
找不到错误来源，名称似乎不是本人

### ISSUE THREAD

**Issue by xunfeng2zkj** [PaddlePaddle/PaddleOCR#9810]
python3 table/predict_table.py \                                                                     
    --det_model_dir=inference/ch_PP-OCRv3_det_infer \
    --rec_model_dir=inference/ch_PP-OCRv3_rec_infer  \
    --table_model_dir=inference/ch_ppstructure_mobile_v2.0_SLANet_infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
    --image_dir=/home/ly/Pictures/11111.jpg \
    --output=../output/table
[2023/04/24 15:11:32] ppocr INFO: [0/1] /home/ly/Pictures/11111.jpg
Traceback (most recent call last):
  File "table/predict_table.py", line 230, in <module>
    main(args)
  File "table/predict_table.py", line 181, in main
    pred_res, _ = table_sys(img)
  File "table/predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "table/predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "/home/ly/data2/zkj/PaddleOCR/ppstructure/table/predict_structure.py", line 134, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 255, in <module>
      main()
    File "tools/export_model.py", line 250, in main
      export_single_model(
    File "tools/export_model.py", line 171, in export_single_model
      paddle.jit.save(model, save_path)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "**/Users/zhoujun20/**opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmpyqukhdph.py", line 91, in forward
      final_name, x = paddle.jit.dy2static.convert_ifelse(self.use_head,
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 100, in forward
      x = self.head(x, targets=data)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmpco4rpr5e.py", line 97, in forward
      paddle.jit.dy2static.convert_ifelse(paddle.jit.dy2static.
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmpco4rpr5e.py", line 91, in false_fn_17
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_3,
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/layers/control_flow.py", line 1257, in while_loop
      output_vars = body(*loop_vars)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/heads/table_att_head.py", line 237, in forward
      structure_preds[:, i, :] = structure_step
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2189, in __setitem__
      return _setitem_impl_(self, item, value)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/variable_index.py", line 699, in _setitem_impl_
      cur_block.append_op(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: When step > 0, end should be greater than start, but received end = 0, start = 501.
      [Hint: Expected end >= start, but received end:0 < start:501.] (at /paddle/paddle/phi/kernels/funcs/slice_utils.h:75)
      [operator < set_value > error]

**Comment by xunfeng2zkj** [comment]
为什么会出现“/Users/zhoujun20/opt/anaconda3/envs/py38”，我自己电脑没有装anaconda，zhoujun20又是谁

**Comment by Cute-Yang** [comment]
> 为什么会出现“/Users/zhoujun20/opt/anaconda3/envs/py38”，我自己电脑没有装anaconda，zhoujun20又是谁

你用which python看一下不就知道啦。。。

**Comment by xunfeng2zkj** [comment]
> 

这个是我自己本机，我都没装anaconda，需要which吗

**Comment by Cute-Yang** [comment]
这个应该是把paddle的编译的debug info带了过来，跟你没关系，你可以问以下baidu有没有一个叫zhoujun的人，哈哈哈

**Comment by liuyifan6613** [comment]
我也遇到了这个错误，请问最后怎么解决的呀？

**Comment by xunfeng2zkj** [comment]
> 

我是直接先pip装，然后用工程命令行打开

**Comment by royrx93** [comment]
这个问题是怎么解决的啊，我也遇到了

**Comment by wytyl13** [comment]
同样的问题，请问如何解决
