### ISSUE TITLE
Does Model Pruning has support for VisionLAN text recognition model?

### ISSUE THREAD

**Issue by vexagal** [PaddlePaddle/PaddleOCR#9861]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem:

Trained a VisionLAN recognition model on my custom recognition dataset as it's instructed in this repo. Training results are great, model can recognize language specific letters. Trained model can be converted to inference engine with .pdiparams extension. Also I re-trained with quantization instructions however output model size is not low as desired. Then I tried **model pruning** but it thrown below error. Do you still support model pruning? Does model pruning feature cover VisionLAN model?

 
- 系统环境/System Environment：
- 版本号/Version：Paddle：Installed via develop branch  PaddleOCR：paddleocr-2.6.1.3 问题相关组件/Related components：PaddleSlim: Installed via develop branch
- 运行指令/Command Code:
```
python3 deploy/slim/prune/sensitivity_anal.py -c output/rec/r45_visionlan/config.yml -o Global.pretrained_model=output/rec/r45_visionlan/best_accuracy  Global.save_model_dir=./output/prune_model/
```
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "deploy/slim/prune/sensitivity_anal.py", line 176, in <module>
    main(config, device, logger, vdl_writer)
  File "deploy/slim/prune/sensitivity_anal.py", line 81, in main
    flops = paddle.flops(model, input_shape)
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/hapi/dynamic_flops.py", line 112, in flops
    return dynamic_flops(
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/hapi/dynamic_flops.py", line 260, in dynamic_flops
    model(inputs)
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/nn/layer/layers.py", line 1255, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/models/paddlep/PaddleOCR/deploy/slim/prune/../../../ppocr/modeling/architectures/base_model.py", line 100, in forward
    x = self.head(x, targets=data)
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/nn/layer/layers.py", line 1255, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/models/paddlep/PaddleOCR/deploy/slim/prune/../../../ppocr/modeling/heads/rec_visionlan_head.py", line 470, in forward
    text_pre, x = self.MLM_VRM(
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/nn/layer/layers.py", line 1255, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/models/paddlep/PaddleOCR/deploy/slim/prune/../../../ppocr/modeling/heads/rec_visionlan_head.py", line 428, in forward
    text_pre = self.Prediction(
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/nn/layer/layers.py", line 1255, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/models/paddlep/PaddleOCR/deploy/slim/prune/../../../ppocr/modeling/heads/rec_visionlan_head.py", line 289, in forward
    g_output = self.pp(cnn_feature)  # b,25,512
  File "/usr/local/lib/python3.8/dist-packages/paddlepaddle-0.0.0-py3.8-linux-x86_64.egg/paddle/nn/layer/layers.py", line 1255, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/models/paddlep/PaddleOCR/deploy/slim/prune/../../../ppocr/modeling/heads/rec_visionlan_head.py", line 248, in forward
    paddle.transpose(
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 512] and the shape of Y = [1, 160, 512]. Received [256] in X is not equal to [160] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /home/core-group-onur/models/paddle-to-onnx/Paddle/paddle/phi/kernels/funcs/common_shape.h:73)
```

**Comment by WenmuZhou** [comment]
currently not supported
