### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.infer'

### ISSUE THREAD

**Issue by NaeemKhanNiazi** [PaddlePaddle/PaddleOCR#9882]
Traceback (most recent call last):
  File "/home/pc/Music/PD_OCR/demo.py", line 1, in <module>
    from paddleocr import PaddleOCR,tools
  File "/home/pc/.local/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/home/pc/.local/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 37, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'

Ubuntu :22:04
paddleocr : 2.6.1.3
paddlepaddle : 2.4.2

**Comment by ucas010** [comment]
have the same bug
how to deal with it ?

**Comment by yuanjie-ai** [comment]
what?????还有人维护吗
