### ISSUE TITLE
ValueError: not find model.pdmodel or inference.pdmodel in /Users/zjh/.paddleocr/whl/det/ch/ch_ppocr_server_v2.0_det_train

### ISSUE THREAD

**Issue by king-bcolor** [PaddlePaddle/PaddleOCR#9902]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：macOS Ventura
- 版本号/Version：Paddle：2.0  PaddleOCR：2.6.1.3  问题相关组件/Related components：'PP-OCRv3'
- 运行指令/Command Code：`python lib/ocr.py`
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "lib/ocr.py", line 56, in <module>
    ocr_png(img_path,'./text/list')
  File "lib/ocr.py", line 10, in ocr_png
    ocr = PaddleOCR(use_angle_cls=True, lang="ch",show_log = False)  # need to run only once to download and load model into memory
  File "/Users/zjh/.pyenv/versions/3.7.9/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 523, in __init__
    super().__init__(params)
  File "/Users/zjh/.pyenv/versions/3.7.9/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/Users/zjh/.pyenv/versions/3.7.9/lib/python3.7/site-packages/paddleocr/tools/infer/predict_det.py", line 142, in __init__
    args, 'det', logger)
  File "/Users/zjh/.pyenv/versions/3.7.9/lib/python3.7/site-packages/paddleocr/tools/infer/utility.py", line 198, in create_predictor
    model_dir))
ValueError: not find model.pdmodel or inference.pdmodel in /Users/zjh/.paddleocr/whl/det/ch/ch_ppocr_server_v2.0_det_train
```

**Comment by king-bcolor** [comment]
## 我正在尝试使用最重的中文的训练模型
1. 先是修改了 paddleocr.py 里的模型 url
2. 然后尝试运行脚本调api ` ocr = PaddleOCR(use_angle_cls=True, lang="ch",show_log = False)`
3. 自动下载训练模型,且进度条完成
4. 报错`ValueError: not find model.pdmodel or inference.pdmodel in /Users/zjh/.paddleocr/whl/det/ch/ch_ppocr_server_v2.0_det_train`

**Comment by king-bcolor** [comment]
奇怪的是在下载过程中，相关目录下是有压缩包的。完成下载之后压缩包又立马消失了

**Comment by andyjpaddle** [comment]
安装的是哪个版本的paddleocr呢，看报错不应该下载train model,最新版默认是v3的模型，会自动下载对应的inference model，可以更新下最新的paddleocr
