### ISSUE TITLE
RuntimeError: could not execute a primitive

### ISSUE THREAD

**Issue by ByLiangCheng** [PaddlePaddle/PaddleOCR#9934]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：CentOS Linux release 7.6.1810 (Core)
- 版本号/Version：Paddle：paddlepaddle Version 2.4.2
  PaddleOCR： 2.6.1.3
问题相关组件/Related components：ocr
- 运行指令/Command Code：

```
@app.route("/ocr", methods=["POST"])
def PaddleOCR():
    data = json.loads(request.data)
    print(DateTime.DateTime())
    imgBase64 = data["image"]
    imgByte = base64.b64decode(imgBase64)
    image = io.BytesIO(imgByte)
    temp = Image.open(image)
    img = np.array(temp)[:, :, :3]
    print(DateTime.DateTime())
    info = ocrService.ocr(img)
    print(DateTime.DateTime())
    print(info)
    return APIResult.ok(info)


def main():
    global ocrService
    ocrService = paddleocr.PaddleOCR(enable_mkldnn=True, use_gpu=False)
    app.run(debug=False, host="0.0.0.0", port=8080)


if __name__ == "__main__":
    main()
```

- 完整报错/Complete Error Message：
```

2023/05/12 19:44:11.255783 US/Central
2023/05/12 19:44:11.258415 US/Central
[2023-05-12 19:44:11,265] [   ERROR] app.py:1414 - Exception on /ocr [POST]
Traceback (most recent call last):
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/src/python/code/ocr/index.py", line 41, in PaddleOCR
    info = ocrService.ocr(img)
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 555, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/paddleocr/tools/infer/predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/usr/local/src/python/3.9.16/lib/python3.9/site-packages/paddleocr/tools/infer/predict_det.py", line 245, in __call__
    self.predictor.run()
RuntimeError: could not execute a primitive
[2023-05-12 19:44:11,266] [    INFO] _internal.py:186 - 103.36.24.17 - - [12/May/2023 19:44:11] "POST /ocr HTTP/1.1" 500 -

```

就是一段很简单的调用，然后在window可以一直调用成功，在linux上启动调用后一次成功一次失败，失败就是提示的上面错误

如果去掉 enable_mkldnn=True 配置，可以一直调用成功，但是识别速度很慢

识别的图片就是官网提供的

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/45414993/9f6e2fb1-7eba-47e0-98b8-1a55e0a7a455)

**Comment by ByLiangCheng** [comment]
@an1018 你好，能看看这个问题吗

**Comment by devwasabi2** [comment]
Were you able to solve this issue @ByLiangCheng
