### ISSUE TITLE
Pyinstall related problem

### ISSUE THREAD

**Issue by hsk20011** [PaddlePaddle/PaddleOCR#9944]
Traceback (most recent call last):
  File "paddle\fluid\ir.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 34, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "wkr\AllWorker.py", line 31, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "wkr\ItrWorker.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddleocr\paddleocr.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\__init__.py", line 62, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\spawn.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\utils\launch_utils.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\fleet\__init__.py", line 31, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\distributed\fleet\fleet.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\fluid\ir.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "paddle\fluid\proto\pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

**Comment by LDOUBLEV** [comment]
试试
import framework_pb2 as framework__pb2改成import paddle.fluid.proto.framework_pb2 as framework__pb2
